### ISSUE TITLE
Can't update on EAP.

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#1000]
Windows 10E
Current Version:  2.0.1234 [EAP]

I switched from MASTER to EAP. Ran git checkout EAP, and changed the brand on the web-UI, however, I 'm getting an update notification, despite me running Git Pull from a CLI and it's saying I'm on the latest version.

Which branch includes the update support for Radarr?

THANKS,

**Comment by tidusjar** [comment]
Take a look at the releases section on github :)

Also this is the 1000th issue!

**Comment by seanvree** [comment]
yaay. do I get a prize?
