### ISSUE TITLE
{REQUEST} Other Movie Search Options

### ISSUE THREAD

**Issue by Foebik** [tidusjar/Ombi#1002]
Hey I think it is great that we are looking at other apps for searching for movies, such as 'Watcher'.

> Integrate Watcher (CouchPotato Replacement) #844 

There is also another new kid on the block I would like to put up for consideration.

Radarr
https://radarr.video/

This is a fork off Sonarr and starting to look pretty good. The Meteor version of PlexRequest app has already started integrated it within it's app.

Please consider adding this as well. -Thanks!

**Comment by tidusjar** [comment]
It's already in the early access preview branch!
