### ISSUE TITLE
Provider Id is null

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#1004]
#### Ombi Version:

V 2.0.1234

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.2.3.4

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Message	Area	Log Level	Date
Provider Id on movie Closet Monster is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie A Clockwork Orange is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie Clash of the Titans is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie Cinderella is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie A Christmas Story is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie Chicken Little is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie Chernobyl Diaries is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
Provider Id on movie Chappie is null	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 8:38:03 PM
```

#### Problem Description:

Ombi crashes when (I'm assuming it is due to the PlexContentCacher timing out) run some task.

#### Reproduction Steps:

None

**Comment by tidusjar** [comment]
It seems that this happens sometimes when Plex is refreshing it's library
metadata and we are trying to also get the metadata at the same time. It
will fix itself on the next run.

**Comment by causefx** [comment]
That's what i thought too but this is the third time in 5 days.  I wonder if I should just do a fresh install...  I migrated from the previous version.
