### ISSUE TITLE
EAP not recognizing radarr is configured

### ISSUE THREAD

**Issue by c4ddy** [tidusjar/Ombi#1005]
#### Ombi Version:

V 2.0.1293

#### Update Branch:

Early Access Preview

#### Operating System:

Ubuntu 14.04

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/01/26 11:03:17.213 Ombi.Core.MovieSender Error: Invalid Path

```

#### Problem Description:

on request approval, Ombi says it is approved but that it was not passed to Couchpotato/watcher as they are not configured, seems to be completely ignoring that Radarr is configured and working.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Hi,

Can you post a printscreen of your settings  for Couchpotato or watcher page?

**Comment by c4ddy** [comment]
that is part of the problem, I am not using Couchpotato or watcher they are both default and selected as disabled(or the enable check box is unchecked.) these are my radarr settings.
http://imgur.com/a/ulhUH

**Comment by tidusjar** [comment]
The error log you posted does state that your Path is incorrect. This is the Path that Radarr will see, similar to what Sonarr has.

**Comment by SuperPotatoMen** [comment]
Your path M:/ does not exists, can you try M:\.
Other way, the erorr was sending back from Radarr. The only thing Ombi does is log the error ;)

**Comment by c4ddy** [comment]
ok , so does that path have to be relative to the Radarr server? as it is installed on a different server than ombi.

**Comment by SuperPotatoMen** [comment]
The path is the path that radarr use to store the media. So it need to exists on the server where you run the radarr server

**Comment by c4ddy** [comment]
ok so after some testing.
Radarr is on a windows server and the movies are on the M: drive and works fine.
Ombi is on a linux server and I had to mount the movies folder to the linux server. pointing ombi to the movies share /share/Movies

once I did that everything worked correctly so the directory setting needs to be relative to Ombi but the same directory as Radarr.

**Comment by SuperPotatoMen** [comment]
Good the hear! Can we close this issue for you?

**Comment by c4ddy** [comment]
yah for sure I will close it!

**Comment by SuperPotatoMen** [comment]
(y)
