### ISSUE TITLE
pushover not sending once requests have been made

### ISSUE THREAD

**Issue by phairplay** [tidusjar/Ombi#1007]
Ombi Version:
V 2.0.1
Update Branch:
Stable
Operating System:
windows 10
Applicable Logs (from /logs/ directory or the Admin page):
Message
Area
Log Level
Date
Ombi Version:
V 1.10.1
Update Branch:
Stable
Operating System:
windows 10
Applicable Logs (from /logs/ directory or the Admin page):
Message
Area
Log Level
Date
nothing in the log
Problem Description:
i dont recieve a pushover notification when new movies are added. ive checked the settings and the test works. noticed in version 1.10.1 just upgraded and still facing the same problem
Reproduction Steps:
in the main plex request options "do not send notifications for requests that don't require approval"
is unticked.Problem Description:
i dont recieve a pushover notification when new movies are added. ive checked the settings and the test works.

**Comment by SuperPotatoMen** [comment]
Pleas use our bug format, i can't read this :(
