### ISSUE TITLE
Donate button 

### ISSUE THREAD

**Issue by FVGAZI** [tidusjar/Ombi#1013]
#### Ombi Version:

2.0.1293

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 10 64bit
#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

No current logs

```

#### Problem Description:

Button functions, but adds the paypal.me url to the current url.
Resulting in a 404
![image](https://cloud.githubusercontent.com/assets/19436076/22393910/e679c778-e4ce-11e6-9d70-e61d897504d0.png)

#### Reproduction Steps:

This happens on any account and on any device/browser.

**Comment by tidusjar** [comment]
Add Http:// or Https:// infront so it doesn't think it's a relative path
