### ISSUE TITLE
Authentication settings

### ISSUE THREAD

**Issue by naq90** [tidusjar/Ombi#1015]
Hi I am on the latest version running on Ubuntu. I have an issue with two settings that are not working.

1. In authentication, I have "enable user authentication checked", but I have "Require Users to login with their passwords" unchecked. Despite this and after restarting the program, Ombi still is making users type in the passwords.

2. For individual user management, the settings do not reflect what I have as default permissions in User Management Settings.

**Comment by tidusjar** [comment]
In your case only users with the administrator permission need to log in.
