### ISSUE TITLE
Settings not applying

### ISSUE THREAD

**Issue by naq90** [tidusjar/Ombi#1016]
#### Ombi Version:

V 2.01

#### Update Branch: Stable

Stable/Early Access Preview/development

#### Operating System: Ubuntu

(Place text here)

#### Mono Version (only if your not on windows)

4.6.2 
#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Hi I am on the latest version running on Ubuntu. I have an issue with two settings that are not working.

In authentication, I have "enable user authentication checked", but I have "Require Users to login with their passwords" unchecked. Despite this and after restarting the program, Ombi still is making users type in the passwords.

For individual user management, the settings do not reflect what I have as default permissions in User Management Settings.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Users with the admin permission need to log in.

That settings page is for new users added outside of Ombi e.g. new friend
on Plex.
