### ISSUE TITLE
Sonarr Issues

### ISSUE THREAD

**Issue by HitsvilleUK** [tidusjar/Ombi#1018]
#### Ombi Version:

V 2.0.1293
#### Update Branch:

Stable
#### Operating System:

Windows 10
#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Invalid Path
Ombi.Api.SonarrApi
Error
1/28/2017 7:30:31 PM
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 120 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137
Ombi.Api.SonarrApi
Error
1/28/2017 7:30:31 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02
Ombi.Api.SonarrApi
Error
1/28/2017 7:30:29 PM


```
#### Problem Description:

Guys I know this was reported earlier and closed as being fixed here
#994 by updating to 2.0.1293
But I have still never been able to get Sonarr to work. Radarr works fine. (same as in the previous report of this issue.
I run Ombi locally and connect to Sonarr on my Seedbox exactly as I do with Radarr.

**Comment by SuperPotatoMen** [comment]
@HitsvilleUK, No problem, i can you help with this one.

Can you post a screenshot of your sonarr settings in Ombi? 
First we need to know is what path that you config on your ombi settings.
You need to use path that exist on your exernal seedbox. Is it doesn't exist, Sonarr will return a error.

**Comment by HitsvilleUK** [comment]
Oh sorry must have missed attaching it 
![capture ombi](https://cloud.githubusercontent.com/assets/9288228/22399607/22e37c08-e598-11e6-9e7d-2ca0bf29b823.PNG)

**Comment by SuperPotatoMen** [comment]
Okay i just deleted it beceause you can read the api key. Can you cover it a little bit beter? (just delete it with paint or something)

**Comment by HitsvilleUK** [comment]
![capture ombi](https://cloud.githubusercontent.com/assets/9288228/22399635/c1dedb04-e598-11e6-9e15-a2922aac43c4.PNG)

**Comment by SuperPotatoMen** [comment]
Can you post a printscreen from a random already show on your sonarr ?

**Comment by tidusjar** [comment]
I've fixed this. Press save in the sonarr settings and then it will work!

**Comment by HitsvilleUK** [comment]
Bu save you mean submit?

**Comment by tidusjar** [comment]
Just press save in the sonarr settings. It saves a hidden value behind the scenes which is new, that's why you need to press save again

**Comment by HitsvilleUK** [comment]
Ah so in Sonarr itself. With you now. 
Done that.. same error message. 
Restarted the remote Sonarr & local Ombi... same result.. 
From Sonarr logs also still says

NzbDroneErrorPipeline
Invalid request Validation failed: -- Invalid Path

**Comment by tidusjar** [comment]
Ah you might not be running the version with the fix. 

Version 2.0.1312 is the latest EAP build

**Comment by HitsvilleUK** [comment]
Ok thought it was fixed in 2.0.1293
Assuming auto update is still not working can you remind me where to find the zip for  2.0.1312

**Comment by tidusjar** [comment]
Auto update works for some people, but it's here:
https://ci.appveyor.com/project/tidusjar/requestplex/branch/eap/artifacts

**Comment by HitsvilleUK** [comment]
Ok will report back. Thanks for all the help to both yourself and @SuperPotatoMen

**Comment by HitsvilleUK** [comment]
Ok error has gone when adding a show. The show doesn't appear in Sonarr but I think I saw that discussed as another issue. Will read up. Thanks again @tidusjar @SuperPotatoMen

**Comment by HitsvilleUK** [comment]
Made same error as the last person who reported it. All is good. Awesome stuff
