### ISSUE TITLE
Plex users are not allowed to place requests

### ISSUE THREAD

**Issue by Vidis79** [tidusjar/Ombi#1024]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Could not find anything in the logs.

```

#### Problem Description:

The Plex users are not able to request movies nor series.
With my local admin account everything is working and I request both movies and series and both Sonarr and CouchPoato starts to download.
But when I do the same for the Plex users it simply says "Sorry, you do not have the correct permissions to request a movie!".
I have even tried to make the Plex user an admin and that does not help neither.
I can't see anything about this in the logs.
I have just upgraded from version 1.1 to 2.0.1 and I copied the PlexRequests.sqlite DB from the old location to the new.

#### Reproduction Steps:

All the movies that I try and request with a Plex Users are not working.

**Comment by SuperPotatoMen** [comment]
@Vidis79 
Can you post a printscreen of one of the users that can't request something? We need to see the permissions :)

**Comment by SuperPotatoMen** [comment]
Also, did you delete every plexrequest file and place the database back to by the ombi files?

**Comment by Vidis79** [comment]
Hi SuperPotatoMen! Love the name BTW :)

I have attached two screen dumps from the user that isn't working.

> Also, did you delete every plexrequest file and place the database back to by the ombi files?

This is what I have done so far.
1. I downloaded the latest release of OMBI.
2. Right clicked the zip file and selected unblock and then extract them to a new location (C:\OMBI).
3. Then I copied the "PlexRequests.sqlite" DB from the old location (C:\PlexRequest.net).
4. Created the services so that it OMBI autostarts with Windows.

I have **NOT** deleted any plexrequest files.

![ombi user access-1](https://cloud.githubusercontent.com/assets/18517394/22425292/abd18cb8-e6fa-11e6-82cd-235d3e4ecab1.JPG)
![ombi deny-1](https://cloud.githubusercontent.com/assets/18517394/22425293/abd194ce-e6fa-11e6-9993-069caf73a252.jpg)

**Comment by SuperPotatoMen** [comment]
Everthing looks okay. Maybe a bug.  @tidusjar  Can you look at this one?

**Comment by tidusjar** [comment]
They have the permission "Read Only User" That means they can only view
things!

**Comment by Vidis79** [comment]
Well that was silly of me.
You are absolutely correct. This was the issue and as soon as I unchecked it, it started working.
Thanks for the help and sorry for the trouble.

**Comment by tidusjar** [comment]
It's no trouble! 😄
