### ISSUE TITLE
Machine ID missing in "View in Plex" URLs

### ISSUE THREAD

**Issue by wptex** [tidusjar/Ombi#1026]
#### Ombi Version:

V 2.1.1331

#### Update Branch:

Early Access Preview

#### Operating System:

Ubuntu 16.04.1 LTS

#### Mono Version (only if you're not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Machine ID is missing from "View in Plex" URLs. Example URL:
https://app.plex.tv/web/app#!/server//details/%2Flibrary%2Fmetadata%2F25927

I have the correct Machine Identifier filled in admin/plex settings.

This had been an issue for me in 2.0.1234 Stable, and 2.0.1312 - 1331 EAP. I have modified search.js to correct the URLs for Movies, TV Shows and Music after the results are successfully returned but that is not ideal.

Possible duplicate of #1006

#### Reproduction Steps:

Default behavior, with or without Machine Identifier filled.

**Comment by tidusjar** [comment]
So even know you have the machine identifier in your settings, it's still not being applied?

Even after a restart of Ombi?

**Comment by wptex** [comment]
Yes, to both. I have restarted to test. Running via Mono, there are relatively frequent crashes, resulting in 502 Bad Gateway from Nginx, so it gets restarted one way or another. I have it being immediately restarted via Supervisor, so it's not that big of an issue.

I will try the latest EAP build to see if the Machine ID is being inserted.

**Comment by wptex** [comment]
Tested V 2.1.1339 EAP. With newly approved (marked available) requests, Machine ID _is inserted_ into the URL. With older requests, Machine ID is still empty.

Also, when I set the Machine ID to blank in admin/plex and save, it gets reset to the correct Machine ID. I set it to '0' to test, which saves properly, but that didn't have immediate effect on the "View in Plex" URLs.

**Comment by SuperPotatoMen** [comment]
@tidusjar jamie do you have time to look at this one?
