### ISSUE TITLE
TV Show Request doesn't do anything

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#1030]
#### Ombi Version:

Application Version:	2.0.1223
OS:	Mono
System Version:	4.2.2 (Stable 4.2.2.30/996df3c Fri Jan 29 21:11:18 CET 2016)
Branch:	Stable
Log Level:	Error
Database Location:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release/Ombi.sqlite
Running Directory:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release

#### Operating System:

QNAP

#### Problem Description:

After finding a TV-Show and select "All Seasons" or "First Season" or any other option nothings happens. In the logs I see the search messages but not errors. I don't rememember if this was working initially as I've been using the Movie section more. Requests movies are working normally.

#### Reproduction Steps:

Search and request a season(s) of a TV-Show.

**Comment by SuperPotatoMen** [comment]
Which backend system you are using? Sonarr, SickRage ?

**Comment by cesalo** [comment]
I don't have that configured. For movies I use couchpotato. Is it mandatory?

**Comment by SuperPotatoMen** [comment]
Well, Sonarr and Sickrage handle tv-show requested. If you don't configured it, nothing will happens because Ombi can't send you request to a backend system ;-)

**Comment by tidusjar** [comment]
When you say "nothing happens" what's nothing? Is there no request on the request page?

**Comment by cesalo** [comment]
mmm .. maybe I'm missing something but shouldn't register the request in Ombi's queue?

**Comment by cesalo** [comment]
Hi @tidusjar .. Yes, I don't get any confirmation at all .. is like nothing was pressed.

**Comment by cesalo** [comment]
I know is not related but just in case I configured SickRage, same result. Didn't get any confirmation and no request was created

**Comment by cesalo** [comment]
It seems reporting issues of available TV-Shows works fine. The issue I'm experiencing is when I try to ask for a new TV-Show.

**Comment by cesalo** [comment]
I just installed the last version available for QNAP and the issues are solved:

https://forum.qnap.com/viewtopic.php?f=320&t=121568

Application Version:	2.1.1336

So far the new version looks great. I loved that it says if is available in Netflix and how many years ago was released.

Thanks.
