### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#1034]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable

#### Operating System:

win server 2012 r2
#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
Auto update has never worked for me. Trying to auto upgrade to 2.1.0 but doesn't work.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Thanks for reporting. We know its still a issue :(
Main case: https://github.com/tidusjar/Ombi/issues/236
