### ISSUE TITLE
Error when approving Movie requests when using Radarr

### ISSUE THREAD

**Issue by AD1995** [tidusjar/Ombi#1037]
#### Ombi Version:

V 2.1.1339

#### Update Branch:

Early Access Preview

#### Operating System:

WIndows Server 2012 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/01/31 23:45:42.773 Ombi.Core.MovieSender Error: Invalid Path 
2017/01/31 23:51:58.054 Ombi.Core.MovieSender Error: Invalid Path 
2017/01/31 23:53:38.784 Ombi.Core.MovieSender Error: Invalid Path 
2017/01/31 23:59:17.833 Ombi.Core.MovieSender Error: Invalid Path 

```

#### Problem Description:

When approving a request, a message appears saying "This has been approved, but It has not been sent to CouchPotato/Watcher because it has not been configured." 
This is while Radarr is enabled
I have disabled Radarr and enabled Couchpotato and that works as it previously did
I was on version 2.1.1336 stable and upgraded to 2.1.1339 EAP to see if the issue was down to the version but the problem followed to the newer version

#### Reproduction Steps:

Enable Radarr and try approving a request

**Comment by tidusjar** [comment]
This is because the path in the settings is incorrect. 
That path needs to be the path that is in Radarr
