### ISSUE TITLE
Verbiage bug on Latest EAP

### ISSUE THREAD

**Issue by astlaurent** [tidusjar/Ombi#1042]
#### Ombi Version:

V 2.1.1346

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Verbiage issue when enabling Radarr

#### Reproduction Steps:

Enable couch potato and then attempt to enable Radarr. Ombi replies back that Couch Potato and Watcher cannot be enabled at the same time.

**Comment by SuperPotatoMen** [comment]
Well, it is excly a correct error.  However.  I think @tidusjar forgot to add Radarr in that error.
