### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by FVGAZI** [tidusjar/Ombi#1043]
#### Ombi Version:

V 2.0.1293

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 10 64bit

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```N\A

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The automatic update button doesn't work.
I've tried to manually update several times and it has no effect.
I've unblocked the zip also.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Hi,

Did you delete your files and manually unzip the EAP files? (you need to user a other download link)

**Comment by FVGAZI** [comment]
First I stopped Ombi. Then I manually unzipped the EAP and copied over the original.
What other download link?

**Comment by SuperPotatoMen** [comment]
You can found the EAP version over here:

https://ci.appveyor.com/project/tidusjar/requestplex/branch/eap/artifacts

Can you try this one?

**Comment by FVGAZI** [comment]
That worked. Thank you very much.
Is that where I should go for any future updates?

**Comment by tidusjar** [comment]
In the screen where it states there is a new update, there is a little "Tick" symbol, if you click that it will take you to the page with the update ;)
