### ISSUE TITLE
Issues with Emby

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1048]
Emby: Stable Version 3.1.5.0
Ombi: Early Access 2.1.1358
CouchPotato: Version 3.01
Sonarr: 2.0.0.4472 (1/1/2017)
Windows 8 x64 (latest updates)
Early Access Preview

#### Problem Description:

Issues after install:
1. After a restart, Plex will re-enable itself under settings.  Note - You must fill out IP (0.0.0.0), Machine Identifier (random name), and Plex Authorization Token (random #) to be able to save the Plex config un-enabled/unchecked.
2. TV Shows already present show up as "pending approval" rather than "available" on Ombi search
3. Movies already requested (and approved) by another user show up as "Not Requested" in Ombi search
​4. Scheduled jobs for Emby Availability Checker, Emby Content Cacher, Emby User Cacher, and Emby Episode Cacher all set to 0.   Restarting Ombi will reset them to 0 even if you change the settings.

**Comment by tidusjar** [comment]
Regarding no.3:
There is a permission called `Users can only view their own requests` This means that they will not see other requests from users. They will only see Available requests.

**Comment by AgileHumor** [comment]
re #3, I think this is a personal "not requested" rather than global...which is just what I was expecting.  I do see the admin sees that requests from more than one user when it happens

#2 fixed :)

#1 still issue, plex re-enables after ombi.exe restarted (or PC reboots).  It will keep setting until process exits though :)   Also, should not need to put in fake info to save Plex as not checked.  Fresh install without some  IP, Machine Identifier, and Plex Authorization Token won't be able to save unchecked.

**Comment by AgileHumor** [comment]
#1 I tested this and it's now working as expected.  Thanks so much!

**Comment by SuperPotatoMen** [comment]
Roepend because problem 2 is still there.

**Comment by delphiactual** [comment]
What needs set in emby to fix this error?
`Provider Id on tv Undateable is null	Ombi.Services.Jobs.EmbyContentCacher	Error	2/6/2017 12:58:24 PM`

I have 5 shows that get this error over and over. I have checked them in Emby and the info looks complete.

**Comment by tidusjar** [comment]
So that error @delphiactual is when Emby doesn't contain a primary Id (IMDBId for movies and TheTVDb Id for Tv Shows). If the media doesn't have this primary Id then Ombi doesn't know what show/movie it is. 

It's not a fatal error, but it means that Ombi will not be able to detect if this show has already been requested.

**Comment by delphiactual** [comment]
@tidusjar maybe you can send a refresh request when that error is received.

**Comment by SuperPotatoMen** [comment]
That is a nice idea

**Comment by tidusjar** [comment]
Hmmm. Not too sure about that, since if I encountered that error it could take 5-10mins to refresh depending on your lib size, also if it's incorrectly matched and will never have an ID then I'll always be refreshing the library
