### ISSUE TITLE
TV request list not showing

### ISSUE THREAD

**Issue by chris10136** [tidusjar/Ombi#1051]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

Windows Server 2012

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

No logs have been created since updating.

```

#### Problem Description:

Since we updated to this release a few days ago, we're not able to see any TV requests on the requests page in admin. On the user end, they're able to view their own requests fine. It's just the admin view that's not showing any TV show requests. We have hundreds of TV requests. Maybe too many to load?

#### Reproduction Steps:

Login, click Requests and then TV shows.

**Comment by tidusjar** [comment]
Can you go into your Sonarr settings and just press Save. That should fix
it.

**Comment by chris10136** [comment]
We're using SickRage and not Sonar.

**Comment by tidusjar** [comment]
Can you please switch to the EAP branch to see if that makes a difference? As I did fix an issue around that.

**Comment by chris10136** [comment]
Fixed. Thank you :)

**Comment by SuperPotatoMen** [comment]
Nice! Cool
