### ISSUE TITLE
Still requesting CP even though not in use

### ISSUE THREAD

**Issue by shadowswan** [tidusjar/Ombi#1052]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

unRaid

#### Mono Version (only if your not on windows)

Application Version:	2.1.1336
OS:	Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
Branch:	Stable
Log Level:	Debug
Database Location:	/app/Ombi/Ombi.sqlite
Running Directory:	/app/Ombi

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in :0	Ombi.Api.ApiRequest	Error	2/2/2017 4:31:25 PM

Exception when calling GetProfiles for CP, Retrying 00:00:05	Ombi.Api.CouchPotatoApi	Error	2/2/2017 4:31:19 PM

```

#### Problem Description:

Even though CP is disabled and i an using radarr now OMBI is still calling to CP and erroring when it can't get to it

#### Reproduction Steps:

Use system

**Comment by SuperPotatoMen** [comment]
We still hit the Pi of cp even its not enabled.  I know that @tidusjar was busy fixing it.  I can't found any changes in the code.  Can you confirm you already busy with fixing it @tidusjar?

**Comment by tidusjar** [comment]
That's strange. Ill take a look.

**Comment by tidusjar** [comment]
Are you sure that CouchPotato is actually disabled? The enable checkbox is unchecked in the settings?

**Comment by shadowswan** [comment]
<img width="857" alt="screen shot 2017-02-03 at 16 54 46" src="https://cloud.githubusercontent.com/assets/1742260/22600220/82f56618-ea31-11e6-8892-23b64d66155b.png">

I am also getting these errors regularly, I don't know if they are connected?

`Mono.Data.Sqlite.SqliteException (0x80004005): Abort due to constraint violation PlexEpisodes.ProviderId may not be NULL at Mono.Data.Sqlite.SQLite3.Reset (Mono.Data.Sqlite.SqliteStatement stmt) [0x00096] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SQLite3.Step (Mono.Data.Sqlite.SqliteStatement stmt) [0x00046] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteDataReader.NextResult () [0x00129] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, System.Data.CommandBehavior behave) [0x00051] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader:.ctor (Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior) at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00006] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00000] in :0 at Dapper.SqlMapper.QueryMultipleImpl (System.Data.IDbConnection cnn, Dapper.CommandDefinition& command) [0x00071] in <66e14dd398ba43d6a00d12629a33213a>:0`

`Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0 --- End of inner exception stack trace --- at Ombi.Api.ApiRequest.Execute[T] (RestSharp.IRestRequest request, System.Uri baseUri) [0x0005a] in <4291b6fb13504ddfb4bd3ad49e0f16a9>:0 at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId (System.Int32 theTvDbId) [0x0004e] in <4291b6fb13504ddfb4bd3ad49e0f16a9>:0 at Ombi.Services.Jobs.RecentlyAdded.GenerateTvHtml (System.Collections.Generic.List`1[T] tv, Ombi.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x00099] in <7d30b485e04b4d81ad44f0b2cb2d3afb>:0`

`System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0`

**Comment by tidusjar** [comment]
Can you please update to EAP, I have resolved these issues. When you enterd the CP settings we try and load the qualities even know it wasn't enabled.

**Comment by shadowswan** [comment]
I'm running on the unraid docker and when I try to update using the auto update the system just crashes... is there another way to try this?

**Comment by jodfie** [comment]
i have Radarr set up and have verified the connection is solid several times. If i try and approve a movie it says that it can't download anything because i dont have couch potato or watcher set up

**Comment by tidusjar** [comment]
@jodfie You enabled it right? there is an "Enable" checkbox.

**Comment by jodfie** [comment]
just verified @tidusjar and it is enabled and ive tested its connectivity several times.

**Comment by SuperPotatoMen** [comment]
@shadowswan do you have already more information for us?
