### ISSUE TITLE
Episodes repeat

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1064]
#### Ombi Version:

V 2.1.1384

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When browsing for individual episodes during a search I see the episodes being repeated. I see the formatted Season # with its episodes beneath it and then immediately after the last episode in the last season I see the episodes repeated but with no season formatting, the episodes are just being listed one after the other. 

#### Reproduction Steps:

Go to Search. TV Series. Search for Gotham. (2014). Click Available. Click Select Episodes. You will then see Seasons 1, 2, 3 with their episodes but then after the s03e22 it immediately shows s01e01 followed by all the other episodes.

**Comment by diedrichg** [comment]
You can try Supergirl too and get the same result.

**Comment by diedrichg** [comment]
Update:

Admin>Settings>Emby>Enable Episode Searching was not enabled. Add soon as I enabled this, the duplicate issue went away. 

Is this a bug? Should this be fixed? What IS Episode Searching? Shouldn't that be an automatic function? Maybe a ? hint button with floating text describing what Episode Searching does would be prudent.

**Comment by SuperPotatoMen** [comment]
Yes, you need to enable Episode searching when you enable the option that you can search for it. 
Ombi check you embi or plex server If it is available.
