### ISSUE TITLE
Radarr settings not pulling multiple root folders

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1065]
#### Ombi Version:

V2.1.1384

#### Update Branch:

development

#### Operating System:

W7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I have multiple root folders for movies in Radarr, but Ombi is not pulling these in, so all movies are added to the same folder in Radarr when approved, instead of the folder I want it to be added to.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
This is not a issue beceause its not in the code ;) Can you raise a feathub request for that?

**Comment by SuperPotatoMen** [comment]
on the todo list for 2.2.0 after talking with jamie :)

**Comment by CBers** [comment]
Thanks :smile:

**Comment by SuperPotatoMen** [comment]
No problem, sorry for closing it!
