### ISSUE TITLE
No episodes checked during search and a request was made gives a error

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1070]
#### Ombi Version:

V 2.1.1384

#### Update Branch:

development

#### Operating System:

Win 8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Core.TvSenderOld.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Core.TvSenderOld.d__11.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 57 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__135.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 1754 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__119.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 1254

```

#### Problem Description:

I (purposefully) tried to submit a request where no individual episodes were checked. I then got a error notification that said "Something went wrong" followed by an error email that said:
----------------
Ombi: A request could not be added.

Hello! The user 'admin123' has requested Vikings but it could not be added. This has been added into the requests queue and will keep retrying
----------------

*If a user does not check any episodes when searching for individual episodes and then clicks "Request" there should be a error notification saying that they must either click "Close" or click a checkbox next to an episode.

#### Reproduction Steps:

1. Search>TV Shows>Vikings>Search Episodes
2. Don't click any boxes and then click Request

**Comment by diedrichg** [comment]
This was in the Request Fault Queue:
 Object reference not set to an instance of an object. 

We need a delete option next to each fault, please.

**Comment by SuperPotatoMen** [comment]
See Also https://github.com/tidusjar/Ombi/issues/1012
