### ISSUE TITLE
Newsletter subject says Plex when using Emby only

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1071]
#### Ombi Version:

V 2.1.1384
#### Update Branch:

Emby development

#### Operating System:

Win 8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The Newsletter says in the subject line "New Content on Plex!" even though Plex is not enabled and Emby is enabled.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
This is a left over when we change our name to Ombi.
