### ISSUE TITLE
Unable to connect to Plex Media Server

### ISSUE THREAD

**Issue by Thurman86** [tidusjar/Ombi#1072]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

Windows 10 Pro

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:11496 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)
```

#### Problem Description:

When I go under Settings>Plex and test the connectivity I get an error that it is unable to connect to the remote server. The Plex server and Ombi are running on the same machine. I have verified I have the correct token from my plex.

#### Reproduction Steps:

Go to Settings>Plex and click Test Connectivity

**Comment by SuperPotatoMen** [comment]
Can you revoke your api key and restart your Plex and Ombi server? 
When you get a error like No connection could be made because the target machine actively refused it.   That is almost not a issue on the Ombi site because plex blocked a api hit. Do you use ssl only connection? You can try to config to use a secure connection.  Enable the ssl setting

**Comment by tidusjar** [comment]
Yes, it means that Ombi cannot connect to Plex, this is usually down to settings, are you 100% sure that your Plex settings are correct? Please triple check them.

**Comment by Thurman86** [comment]
Sorry after checking plex again I noticed I had ombi set to connect on the external port and not the internal port. After updating the port setting it now works. Thanks for all the help!

**Comment by SuperPotatoMen** [comment]
Cool!
