### ISSUE TITLE
Problem selecting English as language

### ISSUE THREAD

**Issue by permanentmarker** [tidusjar/Ombi#1073]
#### Ombi Version:

V 2.1.1336 

#### Update Branch:

Stable

#### Operating System:

Mono 4.6.2 / MacOSX

#### Mono Version (only if your not on windows)

Mono 4.6.2 / MacOSX

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I cannot choose english as default language. Not in configuration and not logged in as a user. I can provide screenshots if needed.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What language are you currently "stuck on".

Have you tried changing language on different pages or you cannot change it at all?

**Comment by permanentmarker** [comment]
I'm stuck in Danish.
The funny thing is that there is two selectable languages "Danish" from the drop down menu. If I choose the first one in the drop down it goes to English.

**Comment by SuperPotatoMen** [comment]
@tidusjar i see something the same. I can set the default language to a other language but nothing happend after that.
