### ISSUE TITLE
Request Added Notification not sending email to requester when content marked as available

### ISSUE THREAD

**Issue by bobpullen** [tidusjar/Ombi#1075]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

Windows 10 Pro x64

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

Here are the log entries after I marked the content as available:

```

2017/02/05 22:26:30.663 Ombi.Services.Notification.NotificationEngine Debug: Notifying Users Count 2 
2017/02/05 22:26:30.686 Ombi.Services.Notification.NotificationEngine Debug: Users with the feature count 2 
2017/02/05 22:26:30.712 Ombi.Services.Notification.NotificationEngine Debug: Usernames:  
2017/02/05 22:26:30.743 Ombi.Services.Notification.NotificationEngine Debug: [Redacted username]
2017/02/05 22:26:30.762 Ombi.Services.Notification.NotificationEngine Debug:  [Redacted username]
2017/02/05 22:26:30.787 Ombi.Services.Notification.NotificationEngine Debug: Users in the requested model count: 1 
2017/02/05 22:26:30.811 Ombi.Services.Notification.NotificationEngine Debug: usernames from model:  
2017/02/05 22:26:30.833 Ombi.Services.Notification.NotificationEngine Debug:  [Redacted username]
2017/02/05 22:26:30.855 Ombi.Services.Notification.NotificationEngine Debug: Users being notified for this request count 2 
2017/02/05 22:28:18.964 Ombi.Services.Notification.NotificationEngine Debug: Notifying Users Count 2 
2017/02/05 22:28:18.983 Ombi.Services.Notification.NotificationEngine Debug: Users with the feature count 2 
2017/02/05 22:28:19.007 Ombi.Services.Notification.NotificationEngine Debug: Usernames:  
2017/02/05 22:28:19.030 Ombi.Services.Notification.NotificationEngine Debug:  [Redacted username]
2017/02/05 22:28:19.054 Ombi.Services.Notification.NotificationEngine Debug: [Redacted username]
2017/02/05 22:28:19.078 Ombi.Services.Notification.NotificationEngine Debug: Users in the requested model count: 1 
2017/02/05 22:28:19.104 Ombi.Services.Notification.NotificationEngine Debug: usernames from model:  
2017/02/05 22:28:19.127 Ombi.Services.Notification.NotificationEngine Debug:  [Redacted username]
2017/02/05 22:28:19.154 Ombi.Services.Notification.NotificationEngine Debug: Users being notified for this request count 2 

```

#### Problem Description:

Users with 'Request Added Notification' enabled are not receiving emails when admin marks requested content as available. SMTP settings are correct and test emails/newsletters are sent to admin email address successfully. When users request content, notification emails are bwing sent to admin address without issue.

Email notification settings as follows (I don't seem to have an 'Enable user notifications' check box which I've seen others post screenshots of?) - http://imgur.com/a/S8Tss

I have access to my SMTP submission logs so know for definite that an email was not sent to the relay server.

#### Reproduction Steps:

- User has 'Request Added Notification' enabled in user profile
- User requests Movie/TV show
- Admin logs in, approves
- Content downloads via CouchPotato and is moved to Plex Media library
- Admin logs in and marks request as available
- User does not receive notification email

**Comment by tidusjar** [comment]
The users are present in the log right? So the log is stating we are sending the email?

**Comment by bobpullen** [comment]
It does seem that way if I'm reading the logs correctly. The two usernames I redacted in the logs belong to the requester and the account owner (me). Although come to think of it the full username of the requester is <first name><space><second name>, whereas in the logs it just shows <first name>. Could that be something to do with it?

**Comment by bobpullen** [comment]
Sorry, chevrons hid part of my reply:

* ...the full username of the requester is 'Forename Surname', whereas in the logs it just shows 'Forename'. Perhaps the space isn't being handled correctly?
