### ISSUE TITLE
alias not being used....

### ISSUE THREAD

**Issue by Spydie88** [tidusjar/Ombi#1076]
#### Ombi Version:

V 	2.1.1382

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 8/Windows Server 2012

#### Mono Version (only if your not on windows)

n/a

#### Applicable Logs (from `/logs/` directory or the Admin page):

n/a

#### Problem Description:

alias is not used in notifications or on the request page, as seen below.

![image](https://cloud.githubusercontent.com/assets/8152913/22664653/3b405790-ec77-11e6-9e5c-5526cae6a8bd.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
And the request was made while the user had an alias?

**Comment by Spydie88** [comment]
yes

**Comment by tidusjar** [comment]
This should be fixed in the latest EAP version.
