### ISSUE TITLE
Ombi freezes, schedule doesn't send emails.

### ISSUE THREAD

**Issue by elit3ge** [tidusjar/Ombi#1077]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

Docker/Mono

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
https://gist.github.com/elit3ge/fee6c792d84eb3eaa5960695d1df5272
https://gist.github.com/elit3ge/f0f8dcbecf68d1e0017fceca95518a64

The issue about getting the latest log is that the container has frozen so I can't extract it. When I restart the container it deletes the logs. Is there a way to specify another location for the logs?
```

#### Problem Description:

Ombi displays errors. Email notification doens't send on set time. Ombi freezes after a couple days, have to restart the docker container.

#### Reproduction Steps:

It does it normally.

**Comment by tidusjar** [comment]
Log level?

**Comment by elit3ge** [comment]
Log level is set to Error

**Comment by elit3ge** [comment]
Another few logs. https://gist.github.com/elit3ge/176af2a4e2b8bb52c0b43dee45f8143a
I remove episode searching from the 9th.
Newsletter was meant to send at 9am on the 11th. Nothing.

**Comment by SuperPotatoMen** [comment]
@elit3ge can you upgrade to the last eap versiokn? we did some changes around the newssletter

**Comment by elit3ge** [comment]
I have upgraded. The schedule is set to run tomorrow, hopefully it goes off.

**Comment by elit3ge** [comment]
It works! Right on schedule!
