### ISSUE TITLE
Problem with autoupdate (See picture)

### ISSUE THREAD

**Issue by permanentmarker** [tidusjar/Ombi#1079]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

MacOSX

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Problem with the auto updater.
![mono autoupdate](https://cloud.githubusercontent.com/assets/25579594/22683339/c7b81e06-ed17-11e6-953b-4a8edbb00932.PNG)
 see picture

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by permanentmarker** [comment]
Mono is a global command, and isn't located in the /Applications/Ombi folder.
There is a space between the file path and the exe for ombi.Updater.exe

**Comment by SuperPotatoMen** [comment]
See the known issue list
