### ISSUE TITLE
Localized titles no recognized

### ISSUE THREAD

**Issue by Fuechslein** [tidusjar/Ombi#1080]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

Mono

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

-

```

#### Problem Description:

My Plex Library uses localized titles in my language. Those with a title different than the English title are not recognized and shown as not requested. I can find those movies in ombi with the localized title, but the result is the correct movie but with the title in English. The following image should make my problem clear.

![ombi](https://cloud.githubusercontent.com/assets/15112818/22698427/cf95caf0-ed54-11e6-9d4b-275382b1ef1e.png)

Is there any way I can change the language of the metadata which ombi uses or is it possible to implement a feature which checks localized titles aswell?

**Comment by SuperPotatoMen** [comment]
Nope, the api doesn't support it.

**Comment by Fuechslein** [comment]
Too bad. But would it be possible to implement advanced functionality to the cacher tasks? I dont know how it matches the Plex Library with the provider from ombi, but if I can get the right movie with the localized title with the search function, why shouldnt the cacher-task be able to do so too?

**Comment by SuperPotatoMen** [comment]
@Fuechslein can you raise a feature request for that on feathub :)
