### ISSUE TITLE
Import only selected users

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1082]
#### Ombi Version:

V2.1.1387

#### Update Branch:

development

#### Operating System:

windows 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Ombi automatically imports all (Emby) users, but this is not always required.

So, would prefer a list of users to be able to select to import.

Would also like a DELETE user function as well, just from Ombi, not the underlying system (Emby).

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Can you open a feathub item for this one?

**Comment by SuperPotatoMen** [comment]
Re-opened. I saw the Requests from Jamie on gitter

**Comment by CBers** [comment]
Yes, I should have put in the description that Jamie requested an ISSUE :)

**Comment by SuperPotatoMen** [comment]
@CBers yeah, i'm sorry!
