### ISSUE TITLE
TV Shows requests page not opening

### ISSUE THREAD

**Issue by tijmenvn** [tidusjar/Ombi#1083]
[logs_Ombi_1083.zip](https://github.com/tidusjar/Ombi/files/760422/logs_Ombi_1083.zip)

#### Ombi Version:

V 2.1.1336

#### Update Branch:

**Stable**/Early Access Preview/development

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

Stable 4.6.2.16/ac9e222

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

see attached file

```

#### Problem Description:

While the Movies requests page loads just fine, when clicking on my TV Shows requests, Ombi hangs, it does not show the regular "no TV Shows" in grey. 

Problem seems to only produces with the admin account, user who requested the TV Show is still able to see the request

#### Reproduction Steps:

Noting yet that I know what is causing it. I do use the installation way of HTPCguides for installing ombi, that is if it makes a difference. I will try to find something in the logs.

**Comment by tidusjar** [comment]
Can you go into your sonarr settings and re-press save?

**Comment by tijmenvn** [comment]
Just did that, made sure I got notification that settings in sonarr were saved. restarted Ombi. No difference. It does tell me now it's indexing files.

**Comment by tidusjar** [comment]
Can you open up the developer tools (F12), click the network tab and then refresh the page, there should be something in red.

Can you click the red item and then press preview and post the result here?

**Comment by ubun2Junky** [comment]
I'm getting the same issues, here are my results.

{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.FormatException: Input string was not in a correct format.↵  at System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) [0x0005e] in <8f2c484307284b51944a1a13a14c0266>:0 ↵  at System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 ↵  at System.Int32.Parse (System.String s) [0x00007] in <8f2c484307284b51944a1a13a14c0266>:0 ↵  at Ombi.UI.Modules.RequestsModule+<>c__DisplayClass47_0.<GetRootPath>b__3 (Ombi.Api.Models.Sonarr.SonarrRootFolder x) [0x00014] in <367d18f7a34843c8a4234d9d0db03142>:0 ↵  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00035] in <63992662b765477a898ef49cdcc99ee2>:0 ↵  at Ombi.UI.Modules.RequestsModule+<GetRootPath>d__47.MoveNext () [0x0013a] in <367d18f7a34843c8a4234d9d0db03142>:0 ↵   --- End of inner exception stack trace ---↵  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) [0x000bd] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500

**Comment by tidusjar** [comment]
Can you go into your Sonarr settings and re-press Save? If that doesn't work there is an update in the EAP branch.
