### ISSUE TITLE
Ubuntu 16.10 - Ombi crashes. 

### ISSUE THREAD

**Issue by yeyeoke** [tidusjar/Ombi#1084]
I know you guys are already aware of the problems with ubuntu and ombi, but I thought I'd help out by submitting my logs at least. 

#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

Ubuntu server 16.10

#### Mono version:

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
[2017-02-07.txt](https://github.com/tidusjar/Ombi/files/761154/2017-02-07.txt)



#### Problem Description:

Ombi becomes unresponsive, I can still see the process so I dont believe its an actual crash. 

#### Reproduction Steps:

Start Ombi, wait. Voila.

**Comment by tidusjar** [comment]
Turn off Trace logging and put it to error.

**Comment by yeyeoke** [comment]
Damn, sorry, I'll upload new log when it becomes unresponsive again.

**Comment by tidusjar** [comment]
That is what was causing the crash! Trace logging enabled causes a LOAD of
logs to be generated and can cause issues when used in a production
scenario.

**Comment by yeyeoke** [comment]
Yeah, that explains why it's been more frequent for the last couple of days (since I turned it on) but probably doesn't explain why it crashed before that.

**Comment by tidusjar** [comment]
Episode searching enabled?

**Comment by yeyeoke** [comment]
Yeah that was on but that doesn't seem to have been my problem as much as my own idiocy was. I believe trace was actually enabled the whole time since now that I've turned it off its been stable for 17 hours which is a new record for me. I'm sorry, I'm retarded..

**Comment by SuperPotatoMen** [comment]
cool :) If you have any problems in the future just open a issue report :)
