### ISSUE TITLE
Emby Login does not work correctly

### ISSUE THREAD

**Issue by PhyberApex** [tidusjar/Ombi#1090]
#### Ombi Version:

V 2.1.1401

#### Update Branch:

Early Access Preview

#### Operating System:

Debian

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/02/09 16:04:17.127 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/02/09 16:04:17.160 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/02/09 16:04:17.171 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True 
2017/02/09 16:04:22.529 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass 
2017/02/09 16:04:22.565 Ombi.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list 
2017/02/09 16:04:22.578 Ombi.UI.Modules.UserLoginModule Debug: User is the account owner 
2017/02/09 16:04:22.612 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
```

#### Problem Description:

Login with users from emby does not work. I only get the login page repeatedly. If I click search I get the search page after a login attempt. I seem to be somewhat logged in but the session is not created correctly. I do not get a settings dropdown on the top of the page and can't create requests. If I report an issue the name in the email is set to ''.

#### Reproduction Steps:

Try to log in as emby user.

**Comment by tidusjar** [comment]
I think you are correct, the session probably isn't getting created correctly.

Thanks, i'll take a look

**Comment by tidusjar** [comment]
Have you tried this with different browsers?

**Comment by PhyberApex** [comment]
Yes I tried chrome and Firefox. Also tried to empty my cache and deleted the Omni.sqlite and set it up again. Also tried running as root to exclude privilege errors.

~Cheers

**Comment by tidusjar** [comment]
Found it!

Was deep in the authentication layer, must of missed that part for emby

**Comment by tidusjar** [comment]
This was also stopping the emby users from using the permissions too!
