### ISSUE TITLE
Delete button deletes all requests when filter is applied.

### ISSUE THREAD

**Issue by dunecokc** [tidusjar/Ombi#1092]
#### Ombi Version:

V 	2.1.1401

#### Update Branch:

Early Access Preview

#### Operating System:

Windows Server 2012

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

I was wanting to clear out all completed requests in one step.  When I applied the Completed filter and clicked Delete Movies, all movie requests deleted.

#### Reproduction Steps:

Go to Requests page, Set a filter, Press Delete Movies. Expected behavior was only the movies displayed would be purged.

**Comment by tidusjar** [comment]
This is not really a bug as it's expected behavior. Pressing Delete Movies will always delete them all.

I'm not going to do anything with this as I still plan to rewrite that page.
