### ISSUE TITLE
Approving a TV Season - Series not in library - yeilded no search

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1095]
#### Ombi Version:

V 2.1.1404

#### Update Branch:

development

#### Operating System:

Win8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

See here [https://emby.media/community/index.php?/topic/44267-ombi-for-emby/page-13#entry419168](url)

#### Reproduction Steps:

Request a season from a TV series that does not exist on the server.
Approve the request for the season.
--request gets sent to Sonarr
--Sonarr grabs the series
--latest season does not get tagged for download

**Comment by SuperPotatoMen** [comment]
Can you update to te last EAP version and check if its okay now?

**Comment by diedrichg** [comment]
Tested under  	2.2.1608, worked great! The specific season was tagged as "monitored" and then each episode was searched to be downloaded.
![2017-04-05 11_02_42-the king of queens - sonarr](https://cloud.githubusercontent.com/assets/9559987/24712096/e1eccb1e-19ef-11e7-91a0-f375022b5bf4.png)
