### ISSUE TITLE
Silence update notification

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1096]
#### Ombi Version:

V 2.1.1406

#### Update Branch:

development

#### Operating System:

Win 8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

There is no way to silence the update notification. 

#### Reproduction Steps:

Suggestion: after clicking the update notification, the notification will no longer be displayed - even if the user does not update.

Suggestion: Provide the user a way to turn off notifications. (I don't even see a scheduled update job)

**Comment by SuperPotatoMen** [comment]
This is a feature request not a issue or bug ;) pleas open a topic on feathub.
