### ISSUE TITLE
Auto Update Button Missing?

### ISSUE THREAD

**Issue by VanCityGuy** [tidusjar/Ombi#1097]
#### Ombi Version
V 2.1.1401
#### Update Branch:
Early Access Preview
#### Operating System:
Mono
#### Log Level:
Debug
For the last few commits, the Auto Update button in the Status section of settings is gone. I have been having to download the .zip, replace my ombi.qlite file in the new version and move it manually to my Applications. I loved having that button that would do it all automatically.

I am on EAP branch, latest commit on Mac OSX, with the latest version of Mono.

There are no relevant logs.

Thanks!

**Comment by SuperPotatoMen** [comment]
We removed the option beceause it doesn't work.

**Comment by escservices** [comment]
@PotatoQuality Do you ever plan on re adding it, without it there's no way for people to update certain dockers.

**Comment by tidusjar** [comment]
Yes i do. It was enabled while in eap since i did rework parts of it but it's still not ready.

**Comment by escservices** [comment]
OK cool, it also looks like LinuxServer.io will manually update their docker tomorrow, once that update button is in though it will make things much easier.  Good luck!
