### ISSUE TITLE
Auto Update Button Missing?

### ISSUE THREAD

**Issue by VanCityGuy** [tidusjar/Ombi#1098]
#### Ombi Version

V 2.1.1401

#### Update Branch:

Early Access Preview

#### Operating System:

Mac OSX

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
There are no relevant logs.
```

#### Problem Description:

For the last few commits, the Auto Update button in the Status section of settings is gone. I have been having to download the .zip, replace my ombi.qlite file in the new version and move it manually to my Applications. I loved having that button that would do it all automatically.

I am on EAP branch, latest commit on Mac OSX, with the latest version of Mono.

#### Reproduction Steps:

Go to update page, don't see button anymore.

**Comment by VanCityGuy** [comment]
After digging around the known issues, I see it was removed eight days ago, but why? It had been working fine for me.

**Comment by SuperPotatoMen** [comment]
It is removed beceause the auto updater doesn't work. Jamie is working on it to fix it.
