### ISSUE TITLE
Users not listed on requests

### ISSUE THREAD

**Issue by mmozeiko** [tidusjar/Ombi#1099]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

ArchLinux, https://aur.archlinux.org/packages/ombi

#### Mono Version (only if your not on windows)

4.6.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

It doesn't seem to have anything reasonable is in logs, but I can post them if you need it. Most of the contents is `System.Net.WebException: Error: NameResolutionFailure`.

#### Problem Description:

I often get no user on movie requests. Not sure if same thing happens on TV, my users mostly request TV shows. It seems this is same issue as #967.

Users don't have alias set in User Management. This happens for both Plex Home users and just Friends. Today one non-Home user requested bunch of movies, and only first 2 has their user assigned, but next 5 don't have any user assigned!

This also happens with admin user (with which I am usually staying logged in).

If I remember correctly, then this seems to start with v2.0. With v1.1 it was not happening.

#### Reproduction Steps:

This is very random. Most of the time its not reproducible.

**Comment by mmozeiko** [comment]
When I look into database in RequestBlobs table I can see that some of latest requests correctly has user:

    ...,"RequestedUsers":["user"],...

But others have just an empty string:

    ...,"RequestedUsers":[""],...

**Comment by JimboMonkey1234** [comment]
From my limited testing, I'm getting repros from Safari in iOS, but not Firefox on Windows. Two users, both with aliases.

**Comment by SuperPotatoMen** [comment]
What is your ombi version? V 2.1.0 isn't a build

**Comment by mmozeiko** [comment]
What do you mean its not a build? What is this https://github.com/tidusjar/Ombi/releases/tag/v2.1.0 ?

For me it definetely happens with Chrome on Windows.

**Comment by JimboMonkey1234** [comment]
Here's my application version: 2.1.1336
Same branch/mono version as mmozeiko.

**Comment by ersan** [comment]
Happening to me also on the nightly build, not sure how to reproduce

**Comment by ersan** [comment]
I'm worried this is allowing users to bypass the weekly request limits as well, though I can't be sure because I don't know who is actually submitting the requests.

**Comment by SuperPotatoMen** [comment]
Guys do you have still this problem with the last EAP version?

**Comment by PiZZ4** [comment]
@SuperPotatoMen I had this same problem & solved it. It happened when users upgrade from plexrequests.net to ombi. I had to do a clean install (using NSSM). 

Additionally, i copied the old sqlite file, in order to preserve the old settings. I hope this can shed a little light for you.

**Comment by mmozeiko** [comment]
Yes, I still have this problem. It happens even if one user is adding many movies. For some of them it records his username, for other movies "RequestedUsers" has list with empty string.

In my case I have PlexRequests.sqlite from time when it was called PlexRequests. When I upgraded I removed all other files, only file I kept is this sqlite database.

**Comment by PiZZ4** [comment]
@mmozeiko what solved it for me was the clean install (removing services), then reinstalling, then adding back the SQLite after the fact. Try that

**Comment by mmozeiko** [comment]
That's exactly what I have done when I upgraded to ombi. Before it was in /opt/PlexRequests, now it is in /plex/ombi. When I upgraded it did install ombi files in clean space (/opt/ombi folder didn't exist before), and then I copied only PlexRequests.sqlite file from /opt/PlexRquests.

**Comment by ersan** [comment]
As a data point I have never used plexrequests.net (and thus did not upgrade to Ombi) and still get this problem fairly often - 5 out of the last 40 requested movies and 1 out of the last 10 TV shows do not have a username associated with them.

**Comment by tidusjar** [comment]
What type of user is this? Plex/Emby/Local user?

What are your authentication settings set to?
