### ISSUE TITLE
Ombi Stuck using Safari after entering password

### ISSUE THREAD

**Issue by gforce75** [tidusjar/Ombi#1100]
#### Ombi Version:

V  	2.1.1336 

#### Update Branch:

Stablet

#### Operating System:

Windows and IOS

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

No logs, just gets stuck and doesn't log

```

#### Problem Description:

Using Safari on IOS and/or MAC, Ombi refuses to do anything after the password is entered.

#### Reproduction Steps:

Use Safari on iphone or mac with password authentication enabled.

**Comment by SuperPotatoMen** [comment]
If you hit a hard refresh ctrl-f5. does it still there? Maybe a cache issue.

**Comment by gforce75** [comment]
Yes, still an issue.  Does it on iphone also with safari

**Comment by badincite** [comment]
Yeah I had user inform me of this last night so I tired it on another iphone and it did the same thing. Once I enter a username it just redirects me back to the landing page.

**Comment by gforce75** [comment]
Good to know.  I warn users not use Safari. Works on chrome fine even with
an iPhone.

**Comment by escservices** [comment]
Yeah my users have the same issue they enter their username and it defaults back to the login page.  The problem I believe is an issue with the cookies not being allowed.  I was able to replicate this issue on chrome by disabling cookies on all sites and clearing my cache, if I turned back on cookies for all sites it works fine.  I use android so I can't test it on an iPhone but my friend said it solved it on his iPhone.  I have a feeling it's a IOS update that caused it.

**Comment by tidusjar** [comment]
If cookies are not allowed then that issue is out of my control. If that was the case they would have issues on a lot of website in regards to logging in.

**Comment by escservices** [comment]
@tidusjar  Yeah you're right there's nothing you can do if it's a cookie issue.  Safari by itself has always had a terrible cookie system. if you google it you'll see tons of login and posting issues.  But after reading up on first vs third party cookies I think what's happening is people are using managers like Organizr that creates a first party cookie by itself then ombi is considered a third party cookie which apparently apple blocks by default.  Below I posted Apple's cookie settings and you'll see that pretty much all of them block third party plugins.  If I'm right there's nothing you can do and that everyone here must be using something like Organizr, if not then it's just another failed hypothesis. 

> Always Block - Block all first-party cookies and block all third-party cookies.
Allow from Current Website Only - Allow all first-party cookies and block all third-party cookies.
Allow from Websites I Visit - Allow all first-party cookies and block all third-party cookies unless that third party was a first party at one time (based on current cookies and browsing history).
Always Allow - Allow all first-party cookies and allow all third-party cookies.

**Comment by temper1** [comment]
An easy workaround is going into safari settings and allowing all cookies from all sites. After that login to ombi, which should work fine, then put the setting back to its original value and it should still work. (Can't remeber the exact names of the settings I changed as it was around a month ago.)
