### ISSUE TITLE
Newsletter test not working, email notification and mass email is 

### ISSUE THREAD

**Issue by the1legend1** [tidusjar/Ombi#1103]
#### Ombi Version:

2.1.1401

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 10 64bit

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I can fire off email notifications from Ombi and I receive the email within a minute. I can shoot out a mass email as well, but the "Send test email to admin" button below the enable newsletter checkbox just spins until I refresh the page and no newsletter is received.
The logs shows this many times:

System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source) at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 movies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 215

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Hi can you put your logs in the place " (Logs go here."  the text is there for a reason ;)

**Comment by the1legend1** [comment]
Sorry, here you go.
[logs.zip](https://github.com/tidusjar/Ombi/files/769631/logs.zip)

**Comment by SuperPotatoMen** [comment]
@the1legend1  thanks, this will help jamie with fixing 👍
