### ISSUE TITLE
Refactor landing page after login

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1106]
My idea is simple, instead of have a landing page or a request page we have full covert landing page what you can customize.

After a user login, it shows you a sort kind of home screen and ask the enduser what he likes to do. 
You can customize the buttons or just use the default buttons with images.
Also its possible to add buttons with text, images and put a external url on it.
Admin can show a text or warning message if a service is down.

![image](https://cloud.githubusercontent.com/assets/2944704/22866909/cba0d3b8-f17d-11e6-8257-d3d49a40b0bf.png)

**Comment by LindsayCole** [comment]
I love the idea. The only thing I would like to make sure is possible, is that we integrate the Plex Server status there, and allow multiple Plex Servers ;)

**Comment by simonk83** [comment]
Why not add newsletter type information to the landing screen?   "These are the series that were added since you last logged in".  "These are the movies that have been released since you last logged in".  "These are the requests from everyone else since you last logged in" etc etc.
