### ISSUE TITLE
Enhancement: Additional filter needed for hiding approved requests

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1108]
#### Ombi Version:

V 2.1.1407

#### Update Branch:

development

#### Operating System:

Win8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

There is not a way to filter out Approved requests. "Not Approved" ≠ 'not yet approved'. "Not Approved" = 'rejected'.

*Suggestion: Once a request is approved, it should do some cool fade away shrink thing to the background and be "Archived" - or something like that. The user could then enable a filter called "Archived" - or whatever, and see their approved AND rejected requests. Something like that. I'm sure you have a more elegant way of hiding approved requests. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Pleas open a feathub for this :)

**Comment by SuperPotatoMen** [comment]
You can filter out what you don't need over here:

![image](https://cloud.githubusercontent.com/assets/2944704/22867137/58c2435e-f182-11e6-8b41-82e2f50223bc.png)
