### ISSUE TITLE
EmbyAddedNewsletter	Error

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1109]
#### Ombi Version:

V2.1.1407

#### Update Branch:

development

#### Operating System:

W7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 120 at Ombi.Api.EmbyApi.<>c__DisplayClass10_0.b__1() in C:\projects\requestplex\Ombi.Api\EmbyApi.cs:line 151 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.EmbyApi.GetInformation(String mediaId, EmbyMediaType type, String apiKey, String userId, Uri baseUri) in C:\projects\requestplex\Ombi.Api\EmbyApi.cs:line 149 at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GetHtml(Boolean test) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 118 at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GetNewsletterHtml(Boolean test) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 82

```

#### Problem Description:

Error found in Omni logs.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Hmmm. I can see there is an error but I am not going to be able to fix it without knowing the response from Emby, can I add some logging in and you run that and post the new logs?

**Comment by CBers** [comment]
Yes, no problem.

**Comment by SuperPotatoMen** [comment]
@CBers do you have some more logs for us already for debugging the problem?

**Comment by tidusjar** [comment]
In the EAP/Dev branch there is additional logging.

Can you please set your logging to DEBUG and then try and send a test and post the results back here?

**Comment by CBers** [comment]
No errors being generated when clicking on Send Email to Admin.

**Comment by tidusjar** [comment]
No logging at all? 😕

**Comment by CBers** [comment]
No, nothing. 

Only real problem now is the "This email is only available on devices that support HTML." issue mentioned elsewhere. 

Close this for now if you wish 😀

**Comment by CBers** [comment]
Actually, it took a while to show in the logs, perhaps I didn't leave the task long enough to complete. 

This is what is in the logs at TRACE level, after running the task manually. 

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: O. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.EmbyApi.GetInformation(String mediaId, EmbyMediaType type, String apiKey, String userId, Uri baseUri) in C:\projects\requestplex\Ombi.Api\EmbyApi.cs:line 230 at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GetHtml(Boolean test) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 143 at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GetNewsletterHtml(Boolean test) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 84

Area = Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter

Just before it (1s),there's this error:

System.Exception: Exception of type 'System.Exception' was thrown.

Area = Ombi.Api.EmbyApi

Sorry for the confusion.

**Comment by CBers** [comment]
This is from the Emby server log at the same time as the above errors:

2017-02-19 21:53:34.1813 Info HttpServer: HTTP GET http://192.168.1.140:8096/emby/users/f7fa0486ef474424b511875eb3326297/items/2849f6248d3d387a2bafca754857f010. UserAgent: RestSharp/105.2.3.0
2017-02-19 21:53:34.1893 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.2.1.110
	Command line: C:\Users\Media\AppData\Roaming\MediaBrowser-Server\System\MediaBrowser.ServerApplication.exe
	Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
	64-Bit OS: True
	64-Bit Process: True
	Processor count: 4
	Program data path: C:\Users\Media\AppData\Roaming\MediaBrowser-Server
	Application directory: C:\Users\Media\AppData\Roaming\MediaBrowser-Server\System
	System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
	   at MediaBrowser.Api.UserLibrary.UserLibraryService.<Get>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceController.<Execute>d__13.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.<ProcessRequestAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__74.MoveNext()
	---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()<---
	
	System.AggregateException
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
	   at MediaBrowser.Api.UserLibrary.UserLibraryService.<Get>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.<Execute>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceController.<Execute>d__13.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.<ProcessRequestAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.<RequestHandler>d__74.MoveNext()
	InnerException: System.ArgumentNullException
	System.ArgumentNullException: Value cannot be null.
	Parameter name: item
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	   at Emby.Server.Implementations.Dto.DtoService.<GetBaseItemDtoInternal>d__22.MoveNext()
	
2017-02-19 21:53:34.1893 Info HttpServer: HTTP Response 500 to 192.168.1.140. Time: 3ms. http://192.168.1.140:8096/emby/users/f7fa0486ef474424b511875eb3326297/items/2849f6248d3d387a2bafca754857f010
	
Not sure if this was a coincidence..

**Comment by CBers** [comment]
I run beta version of Emby server if that makes any difference. 

You might be running stable?

**Comment by tidusjar** [comment]
Same error as I was seeing.

Related issue: https://github.com/MediaBrowser/Emby/issues/2471

**Comment by CBers** [comment]
Jamie - might be worth posting on the Emby forums, if you don't get a response.

**Comment by tidusjar** [comment]
@CBers Can you try again but make sure the log level is debug?

You should find these sort of things together:

```
"Could not get the media item's information"
"ResponseContent"
"ResponseStatusCode"
```
etc

**Comment by CBers** [comment]
Updated to v2.2.1 44. 

Logs:

System.AggregateException: One or more errors occurred. ---> TMDbLib.Objects.Exceptions.RequestLimitExceededException: You have exceeded the maximum number of request allowed by TMDb please try again later at TMDbLib.Rest.RestRequest.d__21.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 231 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Rest.RestRequest.d__16`1.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 149 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__135.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 67 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__133.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 27 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Api.TheMovieDbApi.d__15.MoveNext() in C:\projects\requestplex\Ombi.Api\TheMovieDbApi.cs:line 100 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 199 ---> (Inner Exception #0) TMDbLib.Objects.Exceptions.RequestLimitExceededException: You have exceeded the maximum number of request allowed by TMDb please try again later at TMDbLib.Rest.RestRequest.d__21.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 231 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Rest.RestRequest.d__16`1.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 149 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__135.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 67 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__133.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 27 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Api.TheMovieDbApi.d__15.MoveNext() in C:\projects\requestplex\Ombi.Api\TheMovieDbApi.cs:line 100<---	Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter	Error	2/24/2017 2:57:40 PM



System.AggregateException: One or more errors occurred. ---> TMDbLib.Objects.Exceptions.RequestLimitExceededException: You have exceeded the maximum number of request allowed by TMDb please try again later at TMDbLib.Rest.RestRequest.d__21.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 231 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Rest.RestRequest.d__16`1.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 149 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__135.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 67 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__133.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 27 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Api.TheMovieDbApi.d__15.MoveNext() in C:\projects\requestplex\Ombi.Api\TheMovieDbApi.cs:line 100 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter.GenerateMovieHtml(IEnumerable`1 recentlyAddedMovies, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\EmbyRecentlyAddedNewsletter.cs:line 199 ---> (Inner Exception #0) TMDbLib.Objects.Exceptions.RequestLimitExceededException: You have exceeded the maximum number of request allowed by TMDb please try again later at TMDbLib.Rest.RestRequest.d__21.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 231 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Rest.RestRequest.d__16`1.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Rest\RestRequest.cs:line 149 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__135.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 67 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at TMDbLib.Client.TMDbClient.d__133.MoveNext() in T:\Mike\Projects\TMDbLib\TMDbLib\Client\TMDbClientMovies.cs:line 27 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Api.TheMovieDbApi.d__15.MoveNext() in C:\projects\requestplex\Ombi.Api\TheMovieDbApi.cs:line 100<---

**Comment by tidusjar** [comment]
Think I found the issue!

Looks like if you have episode searching on we could have been overloading the Emby API with all of the episode requests (to get the information about those episodes e.g. Episode number and season number).

**Comment by CBers** [comment]
Nice find.

**Comment by tidusjar** [comment]
Apologies it took so long, just testing and working out some kinks now

**Comment by tidusjar** [comment]
So it looks like when we have episode searching enabled with a lot of episodes, emby can't keep up with the API requests we are sending. I've added some handling around it so it wont crash out and it will just move on, but with episodes included in the newsletter is can take some time to generate, this is not much of an issue for when they send out on the schedule, but if you are waiting using the admin test button then go make a tea/coffee 😆

**Comment by CBers** [comment]
I have seen that before.

The task can take 5+ minutes to complete and there's shed loads in the Ombi
log.

I thought it was working when I saw that, but then I got the email with
nothing in it.

**Comment by CBers** [comment]
Updated to the latest version (2.1.1536) and seeing the following in the
Ombi logs during the NEWSLETTER process.

2017/03/16 23:07:19.073 Ombi.UI.Modules.Admin.AdminModule Debug: Clicked
Admin Newsletter Email Test
2017/03/16 23:07:19.073
Ombi.Services.Jobs.RecentlyAddedNewsletter.RecentlyAddedNewsletter Debug:
Starting Recently Added Newsletter Test
2017/03/16 23:08:20.721 Ombi.Services.Jobs.EmbyAvailabilityChecker Debug:
There are no requests to check.
2017/03/16 23:10:33.170 Ombi.Api.EmbyApi Error: Could not get the media
item's information
2017/03/16 23:10:33.185 Ombi.Api.EmbyApi Error:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while
parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader
reader, JsonContract contract, Boolean hasConverter)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,
Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type
type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,
JsonSerializerSettings settings)
   at Ombi.Api.EmbyApi.GetInformation(String mediaId, EmbyMediaType type,
String apiKey, String userId, Uri baseUri) in
C:\projects\requestplex\Ombi.Api\EmbyApi.cs:line 204
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while
parsing value: O. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader
reader, JsonContract contract, Boolean hasConverter)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,
Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type
type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,
JsonSerializerSettings settings)
   at Ombi.Api.EmbyApi.GetInformation(String mediaId, EmbyMediaType type,
String apiKey, String userId, Uri baseUri) in
C:\projects\requestplex\Ombi.Api\EmbyApi.cs:line 204
2017/03/16 23:10:33.198 Ombi.Api.EmbyApi Debug: ResponseContent
2017/03/16 23:10:33.198 Ombi.Api.EmbyApi Debug: One or more errors
occurred.
2017/03/16 23:10:33.221 Ombi.Api.EmbyApi Debug: ResponseStatusCode
2017/03/16 23:10:33.234 Ombi.Api.EmbyApi Debug: InternalServerError
2017/03/16 23:10:33.245 Ombi.Api.EmbyApi Debug: ResponseError
2017/03/16 23:10:33.245 Ombi.Api.EmbyApi Debug: No Error
2017/03/16 23:10:33.268 Ombi.Api.EmbyApi Debug: ResponseException
2017/03/16 23:10:33.283 Ombi.Api.EmbyApi Debug: System.Exception: Exception
of type 'System.Exception' was thrown. System.Exception: Exception of type
'System.Exception' was thrown.
2017/03/16 23:10:33.296
Ombi.Services.Jobs.RecentlyAddedNewsletter.EmbyAddedNewsletter Error:
Failed getting episode information, we may have overloaded Emby's api...
Waiting and we will skip this one and go to the next


On 16 Mar 2017 10:42 pm, "Keith" <cbers62@gmail.com> wrote:

I have seen that before.

The task can take 5+ minutes to complete and there's shed loads in the Ombi
log.

I thought it was working when I saw that, but then I got the email with
nothing in it.

**Comment by tidusjar** [comment]
Can you turn off your episode searching and try?

**Comment by CBers** [comment]
It is off.

I did receive an email in the end, full of movies and TV shows.

**Comment by tidusjar** [comment]
So it did work, but took a long time with lots of errors?

**Comment by CBers** [comment]
Yes 👍

I'll see what my DAILY newsletter includes later.

**Comment by tidusjar** [comment]
Any update @CBers ?

**Comment by CBers** [comment]
It's better, but still occasionally getting everything. Need to check
again.

**Comment by tidusjar** [comment]
Hmmmm... If you can confirm with the latest builds if you are getting everything that would be interesting.

**Comment by CBers** [comment]
OK, I'll update to the latest version (2.1.1565)  and report back.

On 29 Mar 2017 10:49 am, "Jamie" <notifications@github.com> wrote:

Hmmmm... If you can confirm with the latest builds if you are getting
everything that would be interesting.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/Ombi/issues/1109#issuecomment-290040443>, or mute
the thread

**Comment by CBers** [comment]
OK, just updated and manually run the task and the email arrives with new
content only, but not all new content.

I had several episodes added overnight, but none of those were in the
email.


On 29 Mar 2017 10:52 am, "Keith" <cbers62@gmail.com> wrote:

OK, I'll update to the latest version (2.1.1565)  and report back.

On 29 Mar 2017 10:49 am, "Jamie" <notifications@github.com> wrote:

Hmmmm... If you can confirm with the latest builds if you are getting
everything that would be interesting.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/Ombi/issues/1109#issuecomment-290040443>, or mute
the thread

**Comment by tidusjar** [comment]
Anything in the logs? You also have episode searching enabled?

**Comment by CBers** [comment]
No, nothing in the logs, other then the email being put together with new content, but not all new content. 

Should I run the Emby jibs again before running the email job? How often does the Emby cached run?

**Comment by SuperPotatoMen** [comment]
@CBers can you look in your Rootombi folder/logs/ folder if you found something?

**Comment by CBers** [comment]
Just said above, there's nothing in the logs.

**Comment by SuperPotatoMen** [comment]
@CBers i mean, did you manually open the log file? There is sometime more logging then we show in the admin interface.

**Comment by tidusjar** [comment]
The emby episode cacher should run on the schedule that has been set in the schedule settings page. The episode cacher and the emby cacher both should run.

**Comment by CBers** [comment]
@SuperPotatoMen Yes, I opened it manually as its quicker than in the UI.

@tidusjar Yes, it they run when you run the newsletter job.

**Comment by tidusjar** [comment]
So everything is ok then?

**Comment by CBers** [comment]
No, the email arrives with some new content, but not all new content.

I had several episodes added overnight, but none of those were in the email.

**Comment by tidusjar** [comment]
And the metadata for those episodes are all correct? 
If the metadata is incorrect we will not display it as we will do a lookup on the provider id e.g. Imdb/TheTVDbId

Also if Emby's api does not return a nice response we will skip it (but will log that to the error log)

**Comment by AciDCooL** [comment]
I know this is closed, but why log it to the error log if its just informational, this puts people (like me I guess) on the wrong path.

**Comment by PotatoQuality** [comment]
@AciDCooL thanks for you reporting. We working current on version 3 with better logs.
