### ISSUE TITLE
Undo button for Removes

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#111]
Very low priority enhancement, but I just found out that it would be nice to have an Undo button for when requests are Removed. If possible, it could go on the notification itself.

**Comment by tidusjar** [comment]
Go on the notifications?

**Comment by Auwen** [comment]
Maybe popup was a better work. Like this crude model.

![2016-03-28_10-29-53](https://cloud.githubusercontent.com/assets/12058855/14081473/761fe92e-f4d0-11e5-825a-3ba46027d616.png)

**Comment by tidusjar** [comment]
Ahh I see what you mean!
