### ISSUE TITLE
Search API For 3rd-Party Integration

### ISSUE THREAD

**Issue by d8ahazard** [tidusjar/Ombi#1110]
It would be most excellent if Ombi provided a RESTful-ish API for third-party services and apps to be able to submit requests directly to Ombi via a search title.

At least in my use-case, it is possible that the type of media being requested is unknown, in which case it would be useful to have a generic /search endpoint that aggregates results from any/all media sources...although it may also be necessary to provide video-only results as well. So possibly something like: /search /search/video /search/video/tv /search/video/movie /search/music

This way, a user could query a specific or general type of media as needed.

For authentication, I'd maybe recommend allowing either a persistent API token (a-la couchpotato), OR allowing direct use of Plex credentials. Not sure if an expiring token is necessary, unless required to stay current with Plex.

**Comment by d8ahazard** [comment]
Hello - why was this closed?  Has an API been implemented?  If there are no plans to create an api, please let me know so I can drop the placeholder I have for this in my app's UI.

**Comment by bulbajackel** [comment]
I suggest checking out #1455 its why the issue was closed.

**Comment by d8ahazard** [comment]
Okay, you're doing a cleanup to v3.  Should I re-submit this request?

**Comment by tidusjar** [comment]
This is already in v3 ;) the UI uses the API, so anything that can be done in the UI, you can do it via the API

**Comment by d8ahazard** [comment]
Sweet!

**Comment by d8ahazard** [comment]
Okay, so how do I use the apikey in a GET command to do a search, or for
any other command without authentication?
