### ISSUE TITLE
Need a Approve mail send even with enabled Auto Approve TV Show Requests

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#1114]
#### Ombi Version:

V 	2.1.1412

#### Update Branch:

Early Access Preview

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

End user has Auto Approve TV Show Requests but the admin still receive a email to approve the request

**Comment by tidusjar** [comment]
Really? When did this start happening?

**Comment by SuperPotatoMen** [comment]
Yesterday, after i update to  V2.1.1412

**Comment by tidusjar** [comment]
Do they have the administrator role? As if the user is an admin then no notification is sent

**Comment by SuperPotatoMen** [comment]
@tidusjar No, i have only to admin's, myself (plex acocount) and the local admin account.

**Comment by allanak** [comment]
I'm having this issue in 2.1.1336. Users who have their requests auto-approved still result in admin email requesting approval.

**Comment by tidusjar** [comment]
What do you have in the `Do not send notifications for requests that don't require approval` checkbox in the Ombi settings page?

**Comment by SuperPotatoMen** [comment]
@tidusjar i need to check that, my request server is now offline, can check this weekend for you

**Comment by allanak** [comment]
@tidusjar mine was not checked...just turned it on so assume this fixes the issue. Didn't even realize this was a setting! Thanks

**Comment by SuperPotatoMen** [comment]
@tidusjar maybe we delete that option beceause nobody using it?

**Comment by tidusjar** [comment]
Maybe...

**Comment by SuperPotatoMen** [comment]
me too. i will close this one.
