### ISSUE TITLE
Requested TV shows do not display for admin even if requested by admin. Movies work though.

### ISSUE THREAD

**Issue by SgtBatten** [tidusjar/Ombi#1115]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

Windows 10 however ombi reports as windows 8

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/14/2017 12:14:19 PM
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/14/2017 12:14:19 PM
Could not approve and send the TV Happy Endings to Sonarr!	Ombi.UI.Modules.ApprovalModule	Error	2/14/2017 12:14:19 PM
Invalid Path	Ombi.Api.SonarrApi	Error	2/14/2017 12:14:19 PM
Invalid Path	Ombi.Api.SonarrApi	Error	2/14/2017 12:14:19 PM
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 120 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137	Ombi.Api.SonarrApi	Error	2/14/2017 12:14:19 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	2/14/2017 12:14:17 PM
Error messages: Invalid Path	Ombi.UI.Modules.ApprovalModule	Error	2/14/2017 12:14:16 PM

```
#### Problem Description:

Tv shows not showing up once requested but admin or other user.
When logged in as admin and viewing the requests page movies behave as expected but tv shows are not displayed. It's just blank.

#### Reproduction Steps:

Any user requests a TV show. Admin recieves the appropriate Pushbullet notofication saying a show has been requested

Admin views tv shows requested and none are displayed.

Sometimes the approve all tv shows button displays but doesn't appear to work as per logs.

**Comment by SuperPotatoMen** [comment]
Your config a path that doesn't exists. 
Error messages: Invalid Path

**Comment by SgtBatten** [comment]
Would you be able to explain that a little better please. I don't really know which config you mean

**Comment by SuperPotatoMen** [comment]
In your setting page there is a setting called "Default Root Folders". You need to set a valid path where you like to store your tv shows. Otherway Sonarr doesn't know where to store it and gives a error back: Error messages: Invalid Path

**Comment by SgtBatten** [comment]
Thanks for clarifying. I believe the path is valid already though.

D:\Plex\TV\

All my content downloads to a different location but during post processing gets moved to the above location.

**Comment by SuperPotatoMen** [comment]
The reported error doesn't come from Ombi but from Sonarr.
i suggest to open a support topic on the sonarr forum.

**Comment by SgtBatten** [comment]
Okay I will do that thanks.

Can you confirm that the requested TVs shows not appearing as a requested item for the admin is caused by sonarr? 

I definitely had all this working a few months ago when I set it up and just have not used it until now.

**Comment by tidusjar** [comment]
@SgtBatten It's the path that is local to the Sonarr server for example:

![image](https://cloud.githubusercontent.com/assets/6642220/22920855/03ca1b70-f28f-11e6-9c58-2c3b27c80d14.png)

**Comment by SgtBatten** [comment]
Thank you both very much.

I went into sonarr and manually added a new series to see what the default root folder is.

It is the same as in ombi D:\Plex\TV\

I then went to series manager and selected all series and changed their root to the above. Even though they all were in that location already.

Now ombi is working as expected.

Strange but thankfully you guys had the answer. Cheers.

**Comment by SuperPotatoMen** [comment]
:)
