### ISSUE TITLE
Sonarr Path Invalid

### ISSUE THREAD

**Issue by kfulgham** [tidusjar/Ombi#1118]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Invalid Path	Ombi.Api.SonarrApi	Error	2/13/2017 9:50:37 PM
Invalid Path	Ombi.Api.SonarrApi	Error	2/13/2017 9:50:37 PM
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 120 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137	Ombi.Api.SonarrApi	Error	2/13/2017 9:50:37 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02

```

#### Problem Description:

Sonarr Path Invalid --> No new TV shows can be added

#### Reproduction Steps:

Suddenly, whenever anyone requests a new series they receive this error: "Errors from Sonarr: Invalid Path, Invalid Path". 

On the admin side under Sonarr settings I've noticed the following:

- Quality Profiles is blank
- Root Folders is blank
- If I click "Get Quality Profiles/Root Folders". I am sent to a plain text file that says "{"result":false,"message":"You must specify a Quality Profile."}"
- The same error occurs if I click "Test Connectivity".

**Comment by SuperPotatoMen** [comment]
Pleas save you settings again in the admin panel. press f5 and press get quality profile..
If that doesn't work. Herstart your ombi server and try it again.

**Comment by SuperPotatoMen** [comment]
Also on which version are you? V21.0 is not the whole version number ;)

**Comment by MarMed** [comment]
I had the same problem on 2.1.1336, these steps fixed the issue.

**Comment by kfulgham** [comment]
Pleas save you settings again in the admin panel. press f5 and press get quality profile..

This did nothing.

Restarting worked, and then 15 minutes later it is broken again.

**Comment by SuperPotatoMen** [comment]
Can you upgrade to the lasted eap branch?

**Comment by kfulgham** [comment]
Not via the beta Automatic Update feature. I'm away from home, so I'll try to update tonight.

Note the Automatic Update feature works for a bit, then brings me back to the login screen with the update alert still there.

**Comment by SuperPotatoMen** [comment]
The automatically updater is broken at the moment :( you need to do it manualy.  I hope it helps. Let me know!

**Comment by jaketame** [comment]
May be related but I can't add Sonarr into Ombi "Something went wrong" all details are correct

Exception when calling GetRootFolders for Sonarr, Retrying 

Running latest EAP

**Comment by mow4cash** [comment]
Ombi Version:

        v 2.1.1336
Update Branch:

	Stable

Operating System:

       FreeBsd

Mono Version (only if your not on windows)

       4.6.2 (Stable 4.6.2.7/08fd525 Tue Jan 17 01:47:51 UTC 2017)

Problem Description:

       Sonarr Path Invalid --> No new TV shows can be added

Applicable Logs (from /logs/ directory or the Admin page):


` System.Runtime.Serialization.SerializationException: Invalid JSON string at      RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0`

**Comment by maddestructor** [comment]
Hi everyone  (and @SuperPotatoMen)! I seem to be having the same problem (Invalid Path error + JSON return 
{"result":false,"message":"You must specify a Quality Profile."} on every button of the Sonarr configuration page). I was running Stable v2.1.0 and just switched to EAP v2.1.1430. I am still able to reproduce it in the latter version. I also did the steps mentionned by SuperPotatoMen without any luck.

I have attached some logs of the bug to this message.
[log.txt](https://github.com/tidusjar/Ombi/files/789281/log.txt)

I am a student in software engineering so if I can be of assistance, it would be my pleasure to help out here! ;)

**Comment by kfulgham** [comment]
Sorry, I just got time to do the EAP, and nothing has changed I still have the same issue.

**Comment by SuperPotatoMen** [comment]
@maddestructor If you can assist @tidusjar that will be great!

**Comment by kfulgham** [comment]
Anything else I can do to help?

**Comment by smcpeck** [comment]
@kfulgham @maddestructor 

If you resave your Sonarr setup on the latest EAP, does this issue go away?

**Comment by kfulgham** [comment]
No. I get the error on save.

**Comment by tidusjar** [comment]
Please post a screenshot of your Sonarr settings page (In Ombi)?

**Comment by andrewiankidd** [comment]
https://imgur.com/a/H5Nuj

Trying to do anything (adding quality profiles, disabling sonarr) gives the above error

Can't add anything to ombi as it throws sonarr related errors

**Comment by tidusjar** [comment]
Can you please open up the development tools (F12) and then refresh that settings page, is there anything in the console?

**Comment by andrewiankidd** [comment]
Don't worry too much about the API key, it's an old one

https://imgur.com/a/AYqf8

**Comment by tidusjar** [comment]
Can you click the following and post the result:
![image](https://cloud.githubusercontent.com/assets/6642220/23996657/1fdfbad0-0a46-11e7-9eb3-c452dd5d8073.png)

**Comment by andrewiankidd** [comment]
Ah sorry for that, should have been an obvious one to add

![](https://i.imgur.com/QkLz4Dk.png)

**Comment by tidusjar** [comment]
@andrewiankidd what branch are you running?

**Comment by andrewiankidd** [comment]
Initially stable but jumped to early access to check this before I found this open issue
![](https://i.imgur.com/wosCPsu.png)

**Comment by tidusjar** [comment]
Yeah when I seen the issue I thought I fixed it, I only fixed forward slashes escaping...

**Comment by SuperPotatoMen** [comment]
@tidusjar i got the same problem with radarr. Can you fix it also for Radarr?

**Comment by tidusjar** [comment]
Done it!
