### ISSUE TITLE
GUI typo's

### ISSUE THREAD

**Issue by MwC-Trexx** [tidusjar/Ombi#1119]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:
QNAP QTS 4.3.1

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.7/08fd525 mercredi 23 novembre 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
1) When presented with OMBI user login, text description references **Plex.tv** login (should be Ombi login)
2) Setting/Radarr/Root save directory for **TV shows** (Should be Movies)
3) Settings/Enable Newsletter/Enable newslette (missing **r**)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Thanks for reporting.

1. Hmm, the problem is its plex.tv or emby beceause it relay on it.

2. thanks i will fix that.

3 is already fixed, see: https://github.com/tidusjar/Ombi/commit/2cbba6d7543629fdc9e1d655d9193fea664bcc4e

**Comment by MwC-Trexx** [comment]
1) I don't think that is what is causing it.

When you run the initial setup "wizard" on 1st launch, you are asked for your Plex.TV login to get a Plex authorization token, and then later in the wizard you create your OMBI "admin" user account.

When you subsequently connect to OMBI through the web gui, you are prompted for your OMBI user login ("admin" account), but the description for the login prompt references your "Plex.TV" login/pw which just gives you invalid user id/password if you actually use your Plex.tv account information.

**Comment by tidusjar** [comment]
In the early access branch it just states Username
