### ISSUE TITLE
Request Fault Queue V2.0

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1120]
In my opinion a requests user doesn't see any kind of errors when he made a requests.
Let the server admin handle the errors in the backend :)

- [x] Give the option to the admin to edit, delete and force sending again a requests in the system.
- [ ] When a request failed we show a new message in a blue item to the enduser: We added your request, a server admin will process it manually
- [ ] New status tag and requests page status: _Manually processing by the server admin_
- [ ] if a request failed it doesn't care which exception we have. It should always add that request to the failed queue
- [ ] Support for all systems (Sonarr, SickRage, CouchPotato, Radarr and Watcher)
- [ ] When the TheTVDbId is Null, store the request to the failed queue system and try to catch every day the id from tvmaze. Also show every TV show on the search request page even when the tvdbid is null
- [ ] Friendly errors in the queue system (something like _Request can't send to Sonarr because there is no thetvd id yet value is: NULL_)
- [ ] handle the situation when themoviedb.org / tvmaze is down or not returning information back. (store requests and re-try catching information.)

**Comment by SuperPotatoMen** [comment]
linked feathub: http://feathub.com/tidusjar/Ombi/+77

**Comment by SuperPotatoMen** [comment]
Updated for @tidusjar to add some points from this list for the 2.2.1 release
