### ISSUE TITLE
Radarr does not auto-search/download

### ISSUE THREAD

**Issue by Kaallis** [tidusjar/Ombi#1123]
#### Ombi Version:

V 2.1.1412

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 8/Windows Server 2012

#### Applicable Logs (from `/logs/` directory or the Admin page):

Pushbullet api returned a null value, the notification did not get pushed	Ombi.Services.Notification.PushbulletNotification	Error	2/15/2017 1:47:38 PM
Pushbullet api returned a null value, the notification did not get pushed	Ombi.Services.Notification.PushbulletNotification	Error	2/15/2017 1:40:29 PM
Pushbullet api returned a null value, the notification did not get pushed	Ombi.Services.Notification.PushbulletNotification	Error	2/15/2017 1:37:37 PM

#### Problem Description:

Movie requests are sent to Radarr but the search/download does not start automatically.

#### Reproduction Steps:

Configure Radarr (beta) with the IP, port, API, quality profiles and root directory.
Enable Radarr
Do a movie request
the movie is added to radarr but it does not search automatically

**Comment by SuperPotatoMen** [comment]
@tidusjar can you look at this one?

**Comment by tidusjar** [comment]
I don't see how this is not working.

Can you please upgrade your EAP branch?

**Comment by Kaallis** [comment]
Updated the EAP, not i'm testing connectivity for Radarr and it says 'Root Path' should not be empty.
I have tried to click on Get Root Folders and try again but it gives me the same error.
Root Path is: \\kaallis-pc\X\Videos\Movies

**Comment by tidusjar** [comment]
Can you go into the Radarr settings and reconfigure it please.

**Comment by halali** [comment]
I have probably same issue

it start last update EAP

when i want request movie it write me 'Could not add movie, please contract your administrator'

and in admin settings raddar is everything set up correctly and test button write error "'Root Path' should not be empty"

**Comment by tidusjar** [comment]
Press the get root paths button?

**Comment by halali** [comment]
root patch button works

i have setted it up correctly

**Comment by jodfie** [comment]
i have the same problem on OSX..only after i just now updated to newest EAP
http://prntscr.com/eafdgp

**Comment by tidusjar** [comment]
Update EAP, fixed that. Apologies.
