### ISSUE TITLE
Series Requestable Even When in Library and Episode Searching Off

### ISSUE THREAD

**Issue by spaceboy76** [tidusjar/Ombi#1124]
#### Ombi Version:

V 2.1.1412

#### Update Branch:

Early Access Preview

#### Operating System:

WIn 10

#### Problem Description:

If a series is in the emby library and episode level searching is off the series should show as available and the request button should say Available in red. Instead it shows as Request in green

#### Reproduction Steps:

disable episode level searching and search for a series already in the library

**Comment by tidusjar** [comment]
But the user can request other seasons...

**Comment by SuperPotatoMen** [comment]
THis is excly not a but by design. If you don't disable request episode searching it will be possible to request other seasons or episodes.

You can disable that option under the Ombi Configuration page in your admin panel.
![image](https://cloud.githubusercontent.com/assets/2944704/23015102/e7b5d4ac-f431-11e6-8e46-3a3ba41b37db.png)

**Comment by spaceboy76** [comment]
well all of that was disabled from the start and users were still able to request the whole series, even if it were in the library or outstanding in sonarr

but i see that over the last couple of days this has changed slightly, if i now request these series i get an error message telling me its already in emby. the only slight "bug" i see now is the the user can still click the request button even though the series is available and season and episode level request are disabled. yes they do just get a warning message on doing this but ombi knows the series is available so i would expect it to mirror the available button for a movie already in the library

**Comment by SuperPotatoMen** [comment]
There was a bug! Can you upgrade to the last eap release? Jamie Fixed the bug
