### ISSUE TITLE
The "Open in Plex" button link omits the Machine Identifier

### ISSUE THREAD

**Issue by Runaway254** [tidusjar/Ombi#1128]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable 

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

The "View in Plex" button on apps omits the machine identifier. It currently links to https://app.plex.tv/web/app#!/server//details/%2Flibrary%2Fmetadata%[...] omitting the machine identifier that should appear between /server/ and /details/

#### Reproduction Steps:

Add series to Ombi. Have series download. Search for series in the search bar then click the orange "View in Plex" button.

**Comment by Mark7even** [comment]
Have the same issue.

**Comment by SuperPotatoMen** [comment]
Still the same issue guys?

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/1026

**Comment by Mark7even** [comment]
Yes, "View in Plex" brings to Plex with a "You must be lost" prompt.

**Comment by SuperPotatoMen** [comment]
Pleas update to the last EAP version

**Comment by Mark7even** [comment]
Do we just have to reinstall? Or is there a simpler way to update on windows?

**Comment by Mark7even** [comment]
I overwrote the C:/Ombi director with the newest stable release, same issue.
