### ISSUE TITLE
SMTP configuration doesn't stick

### ISSUE THREAD

**Issue by barbidule** [tidusjar/Ombi#1132]
#### Ombi Version:

2.1.1336

#### Update Branch:

Stable

#### Operating System:

Windows server 2016

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Error: authentication failed: authentication failure à MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) à MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) à Ombi.Services.Notification.EmailMessageNotification.d__17.MoveNext() dans C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:ligne 264
```

#### Problem Description:

I successfully configure SMTP with authentication, and receive the test message. If I leave the page and come back, the test no longer works. If I reenter the password, it works again.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Did you use the save button insteady only use the test admin button?
Beceause otherways we won't save your settings.

**Comment by barbidule** [comment]
I used the submit button.

Le 17 févr. 2017 09:25, "SuperPotatoMen" <notifications@github.com> a
écrit :

**Comment by SuperPotatoMen** [comment]
Can you do a re-installation? 
You are the first one that report this issue, i fhink it is a local issue.

**Comment by barbidule** [comment]
Just did a reinstall : same thing.
I can set up the SMTP successfully and receive the test message :
[image: Inline images 1]


But the normal notifications fail :
[image: Inline images 3]


Same thing happens with Pushbullet.

NB : testing SMTP always return a success, even when the configuration is
incorrect and the test is a failure.

**Comment by SuperPotatoMen** [comment]
Can you provide the admin login of your Ombi on github?

**Comment by barbidule** [comment]
I can PM it to you

**Comment by SuperPotatoMen** [comment]
Thanks, can you use gitter for it? :)

**Comment by barbidule** [comment]
On it right now

**Comment by tidusjar** [comment]
The authentication failed:
Error: authentication failed:

If you are using GMail you need to enable unsecure apps.
If you are using 2 factor auth then the password is the auth key that you need to generate

**Comment by barbidule** [comment]
No, I'm using a single factor authentication SMTP server, and I receive
successfully the test emails. I just don't receive the actual notifications.

**Comment by barbidule** [comment]
I tried to delete ombi.sqlite, I did the whole configuration again, same result :
the smtp test works fine
but I don't receive the actual notifications

**Comment by barbidule** [comment]
Update : the notifications actually work for all accounts excepts mine. Not sure if it's the intended behaviour, but it's OK for me.

**Comment by SuperPotatoMen** [comment]
check! cool
