### ISSUE TITLE
Typo in notification, and suggestion for updated notification

### ISSUE THREAD

**Issue by simonk83** [tidusjar/Ombi#1134]
#### Ombi Version:

V 2.1.1412

#### Update Branch:

Early Access Preview

#### Operating System:

Mono (via Docker on a Synology)

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

This series has already been added	Ombi.Core.MovieSender	Error
```

#### Reproduction Steps:

I just tried to request a movie that I already have in my Radarr wanted list.  The notification that popped up was "Could not add movie, please contract your administrator".  There's a minor typo in there (contract instead of contact), however when I checked the log, the error in there shows as "This series has already been added".    Aside from it saying series instead of movie, this seems like a much more useful message to show the user instead.  "This movie is already added and pending a release" or something along those lines.

**Comment by SuperPotatoMen** [comment]
This excly a bug beceause Ombi need to show a error that it already requested. i taget this one for bug

**Comment by SuperPotatoMen** [comment]
@tidusjar you make a new typo xD

**Comment by tidusjar** [comment]
HAHAHAHA
