### ISSUE TITLE
Logout button doesn't work for users other than Admin

### ISSUE THREAD

**Issue by simonk83** [tidusjar/Ombi#1135]
#### Ombi Version:

V 2.1.1412

#### Update Branch:

Early Access Preview

#### Operating System:

Mono (via Docker on a Synology)

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Problem Description:

Logout button doesn't work for users other than Admin

#### Reproduction Steps:

Login as admin, click logout, takes you back to the login page.  Login as another user (Emby user), clicking logout just refreshes the page but the user stays logged in.

**Comment by tidusjar** [comment]
I cannot reproduce this issue.

Are you using a base url for ombi (reverse proxy)?

**Comment by simonk83** [comment]
I do use a reverse proxy yep

**Comment by SuperPotatoMen** [comment]
Does the reverse proxy cache the page or just passing it to ombi?

**Comment by simonk83** [comment]
Sorry, you can close this one.  It was because I hadn't enabled user auth.  If you enter a username that isn't auth'd it let's you login but you can't log out.

So I guess that is a bug after all, just a different one ;)
