### ISSUE TITLE
Ombi keep crashing almost every 5 minutes

### ISSUE THREAD

**Issue by giacomofabbri** [tidusjar/Ombi#1136]
Hi guys! I'm not sure what to say, but anyway I have installed the latest version of Mono and also Ombi and it keeps crashing every 5 minutes or so! There is also another problem, I'd like for my user to just put their username and even if I choose to not ask for password obviously it keep asking!!
There is also another little problem, I setup my plex to be accessible using plex.mydomain.com but omni doesn't know my personalization so it redirect to plex.tv!!
Let me know what do you need to understand whats the problem!!
Sorry for my English

**Comment by SuperPotatoMen** [comment]
Pleas don't delete the issue format we can't help you without it ;).


your second question isn't supported by emby. we don't support custom urls yet. there is a topic on feathub that support it. you can vote it up if you like.
