### ISSUE TITLE
ombi crashing regularly

### ISSUE THREAD

**Issue by c4ddy** [tidusjar/Ombi#1137]
#### Ombi Version:

V 	2.1.1336

#### Update Branch:

Stable

#### Operating System:

Ubuntu 14.04

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer () [0x00064] in <4a1d0aec9205467fa6f454b3ef89045f>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <4291b6fb13504ddfb4bd3ad49e0f16a9>:0

```

#### Problem Description:

Ombi crashing/shutting down every seems like hour or so

#### Reproduction Steps:

I dont do anything I restart the service and just let it sit within a hour or so it shuts down

**Comment by tidusjar** [comment]
Logging level?

**Comment by c4ddy** [comment]
I just increased it to debug cause i wasnt getting anything else.

**Comment by tidusjar** [comment]
Episode searching for Plex enabled?

**Comment by c4ddy** [comment]
no i do not have it enabled.

**Comment by c4ddy** [comment]
i have advanced search on but episode searching off

**Comment by c4ddy** [comment]
I am still having this issue even with updating, is there more logs I can get for you to troubleshoot this?

**Comment by SuperPotatoMen** [comment]
Do you have a error log from mono?

**Comment by skinnyzaz** [comment]
I am having the same issue crashes for me daily at least once sometimes more.
Ubuntu 14.04
Mono JIT compiler version 4.8.0

**Comment by RyanAStrouse** [comment]
I have a similar issue, Ubuntu 16.04 running on Docker. It is crashing just about anytime I try to access the page.

**Comment by GeezusTx** [comment]
I had the same problem on CentOS 7.3 whenever I tried to navigate to pages within Ombi it would randomly crash.

**Comment by RyanAStrouse** [comment]
Ever get it fixed?

**Comment by SuperPotatoMen** [comment]
Jamie is going to do a rewrite to .net to support linux better.
Untill then, we can't fix it. see https://github.com/tidusjar/Ombi/issues/865

**Comment by keithwoelke** [comment]
I wrote a script to query ombi every 5 minutes and restart it if it is down. Here are my results over the night:

Sun Feb  4 02:05:03 PST 2018 - Ombi is down.
Sun Feb  4 03:45:05 PST 2018 - Ombi is down.
Sun Feb  4 05:05:07 PST 2018 - Ombi is down.
Sun Feb  4 08:55:05 PST 2018 - Ombi is down.
Sun Feb  4 10:00:04 PST 2018 - Ombi is down.

On the plus side, my script seems to be keeping it running fairly well. :-)

**Comment by tidusjar** [comment]
@keithwoelke use v3
