### ISSUE TITLE
Ombi Crashing Regularly

### ISSUE THREAD

**Issue by kingwoftam** [tidusjar/Ombi#1139]
#### Ombi Version: 
V2.1.1336

#### Update Branch: 
Stable

#### Operating System:
QNAP 4.2.3

#### Mono Version (only if your not on windows)
Mono 4.4.2.11

#### Applicable Logs (from `/logs/` directory or the Admin page):
Log level set to Error. Lots of errors like the two below

```
System.FormatException: Input string was not in a correct format. at System.Number.StringToNumber (System.String str, NumberStyles options, System.NumberBuffer& number, System.Globalization.NumberFormatInfo info, Boolean parseDecimal) <0x7f6852bb5ed0 + 0x000e1> in :0 at System.Number.ParseInt32 (System.String s, NumberStyles style, System.Globalization.NumberFormatInfo info) <0x7f6852bb4cb0 + 0x00094> in :0 at System.Int32.Parse (System.String s) <0x7f6852b91790 + 0x0001d> in :0 at Ombi.Helpers.PlexHelper.GetSeasonsAndEpisodesFromPlexGuid (System.String guid) <0x41047f00 + 0x00191> in :0	Ombi.Helpers.PlexHelper	Error	2/18/2017 12:52:13 PM

com.plexapp.agents.none://24596/2015/2015-07-08?lang=xn	Ombi.Helpers.PlexHelper	Error	2/18/2017 12:52:13 PM
```

#### Problem Description:

Ombi crashing/shutting down every seems like hour or so

#### Reproduction Steps:

I don't do anything in particular. I realise it's down,  restart the app via QNAP AppCentre and just let it sit. Within a hour or less it shuts down again

**Comment by tidusjar** [comment]
Log level and is Episode Searching in Plex enabled?

**Comment by kingwoftam** [comment]
Log Level is Error. Episode Searching is enabled currently along with Advanced Search.

**Comment by tidusjar** [comment]
Disable episode searching. It causes issues with large libraries.

**Comment by kingwoftam** [comment]
Ok, will do that and monitor for the next wee while

**Comment by kingwoftam** [comment]
No crashes since disabling episode searching. Do you have an open issue for the fact that frequent crashes occur with Episode Searching on with large libraries?

**Comment by tidusjar** [comment]
No not really, it's something I am aware of, not sure how to fix it as it's due to x requests to the Plex API hogging all of the available threads.
