### ISSUE TITLE
Requests are not viewable

### ISSUE THREAD

**Issue by kingwoftam** [tidusjar/Ombi#1142]
#### Ombi Version: 
V2.1.1336

#### Update Branch: 
Stable

#### Operating System:
QNAP 4.2.3

#### Mono Version (only if your not on windows)
Mono 4.4.2.11

#### Applicable Logs (from `/logs/` directory or the Admin page):
Log level set to Error. Cleared logs and reproduced issue but no logs present for this activity.

```

```

#### Problem Description:
On the Requests page, under both Movies and TV Shows tabs, there is nothing displayed. Not even the 'Sorry, we didn't find any results'

#### Reproduction Steps:
Click on Requests from top ribbon, then click on Movies or TV Shows tabs. Both show the filters and approval buttons but no actual requests are shown. Screen is left for at least 5 minutes to see if they will appear eventually but to no avail.

**Comment by tidusjar** [comment]
Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by kingwoftam** [comment]
{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object↵  at Ombi.Helpers.DateTimeHelper.OffsetUTCDateTime (DateTime utcDateTime, Int32 minuteOffset) <0x408015d0 + 0x00030> in <filename unknown>:0 ↵  at Ombi.UI.Modules.RequestsModule+<>c__DisplayClass46_0.<GetTvShows>b__9 (Ombi.Store.RequestedModel tv) <0x40800c00 + 0x00297> in <filename unknown>:0 ↵  at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () <0x40a3bce0 + 0x001a5> in <filename unknown>:0 ↵  at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x7f6852b11c60 + 0x001fb> in <filename unknown>:0 ↵  at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x408ae540 + 0x00070> in <filename unknown>:0 ↵  at Ombi.UI.Modules.RequestsModule+<GetTvShows>d__46.MoveNext () <0x407fcb50 + 0x0174b> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f6852bdab40 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f6852bd9c20 + 0x000b3> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f6852bd9b80 + 0x00093> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f6852bd9b30 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f6852bd9f60 + 0x00017> in <filename unknown>:0 ↵  at Ombi.UI.Modules.RequestsModule+<<-ctor>b__0_2>d.MoveNext () <0x407fc550 + 0x00152> in <filename unknown>:0 ↵  --- End of inner exception stack trace ---↵  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x41977510 + 0x002d7> in <filename unknown>:0 "
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500

**Comment by tidusjar** [comment]
Can you please upgrade mono

**Comment by kingwoftam** [comment]
Upgrade of Mono to 4.6.2 did the trick - thanks
