### ISSUE TITLE
How to provide access outside local network?

### ISSUE THREAD

**Issue by bartolomesoriano** [tidusjar/Ombi#1146]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I am totally new to this and want to use under Windows for my 50+ Plex users, outside of my local network.  How do I enable access to Ombi from outside my local network? I could not find a FAQ or guide about this.  I think it would be a good idea to include as part of the installation steps, at least for Windows users.  Thank you for your help.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
I can help you. I will give you instructions tomorrow okay?

**Comment by bartolomesoriano** [comment]
That would be great, thank you @SuperPotatoMen !

**Comment by squirrellydw** [comment]
I would like to know this also

**Comment by gilbN** [comment]
The ombi port was blocked by my windows firewall, so I had to make an exception for it. After that you will have to open the port in your router. Now you should be able to access ombi when you enter your IP:port 

You can also buy a domain. I got mine on www.get.tech using a coupon code from https://level1techs.com/support

**Comment by Aireezz** [comment]
@squirrellydw Reverse proxies are better and safer IMO than just port forwarding.

**Comment by bartolomesoriano** [comment]
I don't know enough about those either.  Is there any guide anywhere for Windows? Does it make sense to go for one of those Dynamic DNS services? How can those be secured? Any help would be greatly appreciated.

**Comment by usafle** [comment]
I'm still struggling with this myself.  I've got it set up because I can access it from the computer I installed it on.  However, I can't access it from any other computer on my network nor can I access it from outside my network.

I've got my LAN IP address manually assigned to the PC running Plex + this software.  I've tried to access it from another machine on the same LAN but I get no response.

I thought my problems were solved when I saw this thread but there isn't any real information in here on what to do or how to do it....

**Comment by gilbN** [comment]
@usafle Are you on Windows? If so the port ombi is using is most likely blocked by the windows firewall. You need to make a new inbound rule in the windows firewall.

**Comment by bartolomesoriano** [comment]
@usafle , I did just what @gilbN suggested.  In my case, I created a rule in the Avast firewall that I am using.  However, you should be able to launch from another device in your same LAN by using <ip address>:<port> in any browser.  If that isn't working, then perhaps you have another network issue that you need to tackle first.  Do you have different subnets within your LAN or just one? Are the other devices where you want to access from connected wired or wireless?

I was finally able to access from outside my home network.  I used a free dynamic DNS service and tested that I could access from my mobile not on WiFi.  Now I have provided the URL to some test users and will see how it goes.

From my perspective, this issue can be closed, but I leave that decision to the moderators of this repo.

**Comment by usafle** [comment]
@gilbN and @bartolomesoriano:
I've created a rule in Win10 Firewall. I'm only able to enter the service on my LAN now. Using my external IP doesn't work. 
At least I got this far, so far

**Comment by bartolomesoriano** [comment]
Do you have more than one router in your network? Did you, if it is needed, create a forwarding rule in your router so that any request for the port you chose for Ombi is routed internally to the machine running Ombi? This is a required step for your external IP address to work.

**Comment by usafle** [comment]
Nope. Just one single Google Wifi Router.  Already created a port forward rule in it.

**Comment by bartolomesoriano** [comment]
Great! One thing to remember for setting up Gmail for the notification is that if you are using two-factor authentication to sign in to your Google account, the sending of notifications will not work.  I had to turn that off in order to be able to send test messages and newsletters.  Also, you have to enable the setting in your Google account to allow access to older apps with weaker security (I think that is what the setting is called).

**Comment by usafle** [comment]
@bartolomesoriano Damn. 13 minutes too late.  I just opened a support issue on here.  Since Google is telling me this is a "less secure app" and blocked it.
I only have two choices, "allow access to all less secure apps" or find some other email service apparently?  It's not cool that I have to allow access to ALL less secure apps.  There should be a "rule" you can set up in Gmail to allow specific ones...

**Comment by bartolomesoriano** [comment]
I think Google will notify you anytime a new app is requesting access, so you decide which ones get access or not.

**Comment by usafle** [comment]
Unfortunately, it doesn't appear that way.  This is the page I'm greeted with when I click on the link.  It's either <i>all or none</i>

![less_secure_apps_account_settings](https://cloud.githubusercontent.com/assets/18576664/23235875/188e64c0-f925-11e6-98c9-249bf92acce2.png)

**Comment by bartolomesoriano** [comment]
True, but when a new app actually requests access, at that time, Google notifies you and you can deny or approve the access.

**Comment by usafle** [comment]
You've actually seen that happen before or are you hoping that is what the case is? LoL  
It's making me nervous now to do that.  Damn.  So close.

**Comment by bartolomesoriano** [comment]
I have seen that happen.

**Comment by usafle** [comment]
@bartolomesoriano Ok, I'm going to trust you on this one then.

**Comment by gilbN** [comment]
You can make a app password for google, no need to turn of two factor.You can make one in sign in & security under my account

**Comment by gilbN** [comment]
https://myaccount.google.com/apppasswords

**Comment by usafle** [comment]
@gilbN I got the following when I went to your link:
`The setting you are looking for is not available for your account.`

**Comment by bobbintb** [comment]
It can be pretty technical if you want to make it secure. I set up letsencrypt with a reverse proxy and default to SSL.

**Comment by smcpeck** [comment]
@SuperPotatoMen I would vote that this be closed.  This is more of a networking question than an Ombi question.
