### ISSUE TITLE
Request status stuck on "Processing Request" after successful download and addition of specific episodes

### ISSUE THREAD

**Issue by okiwoki** [tidusjar/Ombi#1148]
#### Ombi Version:

V 2.1.1428

#### Update Branch:

Development

#### Operating System:

unRAID 6.3.2, using Docker container

#### Problem Description:

Selecting a specific episode to download will successfully download and add the episode to Plex, however, the status of the request never changes and is stuck on "Processing Request", even when the episode is clearly available.

This was tried on two separate TV Shows; both yielding the same results.

#### Reproduction Steps:

1.) Search and select a TV Show
2.) Select a specific episode to download
3.) Verify download and addition to Plex
4.) Refresh "Requests" page, status is stuck at "Processing Request" and doesn't change even when episode is available.

**Comment by tidusjar** [comment]
Is episode searching in Plex/Emby enabled?

**Comment by okiwoki** [comment]
I just turned it on, but doesn't that run every 12 hours (11 hours is the lowest possible setting)? So a user who requests an episode, won't be able to see an episode is available until 11+ hours later?

**Comment by okiwoki** [comment]
Also, just manually invoked the availability checker as well as the episode cacher and the problem still remains. Available still shows an "X" even though the episode is available on Plex.

**Comment by Enf0** [comment]
Hi, I'd like to chime in and say that I also have an issue with requests stuck on "Processing request".

I'm using Sonarr for shows and Radarr for movies, and the issue occurs with both.

Only movies/shows that are not on Plex (aka should be marked as "unavailable") show as "Processing request", other requests that are available on Plex are correctly marked as "available".

Ombi 2.1.1492
Plex Media Server 1.3.4.3285
Radarr 0.2.0.453
Sonarr 2.0.0.4613

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/817
