### ISSUE TITLE
Cant request movie from Radarr and request from sonarr using Raddar patch

### ISSUE THREAD

**Issue by halali** [tidusjar/Ombi#1149]
#### Ombi Version:

V 2.1.1430

#### Update Branch:

Early Access Preview

#### Operating System:

Windows Server 2012 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

Ombi.Core.MovieSender Error: Invalid Path 

#### Problem Description:

When i try to request any Movie it say me "Could not add movie, please contract your administrator"
and when i request TV Show in Sonarr it add but patch is taken from Radarr settings.

I made new database and reconfigure settings to be sure, but doesnt help.

**Comment by tidusjar** [comment]
go into your radarr settings and reapply.

**Comment by halali** [comment]
Don't help.

**Comment by tidusjar** [comment]
Well Radarr is telling me that your root path is not set up correctly.
Please post a screenshot of your settings

**Comment by halali** [comment]
![ombi](https://cloud.githubusercontent.com/assets/17801420/23119674/7397c1ae-f759-11e6-9a47-549177971a89.png)

**Comment by SuperPotatoMen** [comment]
We broke something, Main issue is now: https://github.com/tidusjar/Ombi/issues/1152
