### ISSUE TITLE
Cast/Crew/Genre Information

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/Ombi#115]
Would be nice to see some basic cast/crew information in the results. Maybe something like the following:

Cast -- top 3-4 actors/actresses
Director(s)
Writer(s)
Genre
Rating (5 star scale?)

I know you can get to this by clicking the link, but it's nice to see at a glance if you've got the right show or movie.

**Comment by tidusjar** [comment]
My only concern is that there will be too much information displayed. But we can look into it.

**Comment by Drewster727** [comment]
I agree, too much info would hurt, maybe something to think about.

**Comment by Auwen** [comment]
Instead of showing that information by default, you could have an "More Info" button for each result, requiring the user to click to see but not leave the page.

**Comment by Drewster727** [comment]
Great idea. That would keep the initial tmdb api request fast and responsive, then query the api for cast info when clicking show info.

**Comment by tidusjar** [comment]
I agree.

**Comment by Drewster727** [comment]
additionally, let's indicate, for tv shows, whether the show has "ended" or is "continuing"

**Comment by tidusjar** [comment]
Let's add some of the suggestions from #373
