### ISSUE TITLE
Movies on Plex not showing up on Ombi - Foreign titles/mismatch year

### ISSUE THREAD

**Issue by henrikrox** [tidusjar/Ombi#1150]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Problem Description:

Okay so i have to examples to reproduce these steps.

The movie headhunters also called hodejegerne (localized title). Doesnt snow in library on ombi. I changed the movie title in Plex to headhunters so that it matches Ombi, but how do i force and update of the plex database in ombi?

Also the movie A Monster Calls is being scraped as year 2017 in Plex, in Ombi its year 2016. So it doesnt show up as in library. And i can request it, even though i have it. I have tried changing the year to 2016 in Plex but it still doesnt pick up in Ombi. 

Is there here also a way to force and update? I like to 100% match plex library to Ombi

#### Reproduction Steps:

See above

**Comment by tidusjar** [comment]
We match on the IMDBId. there is some old code there to fall back on matching titles, but that path never gets executed anymore.

**Comment by henrikrox** [comment]
Thanks for answering, im just manually adding the movies that has a mismatch so its a workaround :)
