### ISSUE TITLE
Trying to request movie via Radarr -- Could not add movie, please contract your administrator

### ISSUE THREAD

**Issue by VanCityGuy** [tidusjar/Ombi#1152]
#### Ombi Version:

V 2.1.1430

#### Update Branch:

Early Access Preview

#### Operating System:

Mac OSX

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/02/19 20:43:58.595 Ombi.Core.MovieSender Error: Invalid Path 

```

Similar logs in Radarr:

```
Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path
```

#### Problem Description:

When trying to add a movie via Radarr in Ombi I get the error: Could not add movie, please contract your administrator.  I am still able to add TV shows via Sonarr. I am on the latest EAP release, and have re-configured, and disabled, and re-enabled Radarr in the settings.

I saw a similar issue that was recently closed, but updating and turning Radarr on and off in the settings didn't work for me.

#### Reproduction Steps:

Search for movie.
Hit request button.
Get Error.

**Comment by tidusjar** [comment]
Go into Radarr and re configure your settings, this is because of the new Root path functionality I added.

**Comment by VanCityGuy** [comment]
What settings in Radarr do I need to re-configure? Do I have to wipe my config and redo it all? Do I just need to regenerate the API key? 

I've tried just changing the host, saving, and changing it back, with Ombi disabled, but that didn't work.

**Comment by SuperPotatoMen** [comment]
No you need to wipe your settings in ombi for Radarr. Save it and reconfig it again.

**Comment by VanCityGuy** [comment]
Tried this a few times earlier today. I even went as far as completely uninstalling and reinstalling Omni and going though the setup wizard again, but it didn't fix it.

Should I try shutting down ombi, deleting my ombi.sqlite file, and firing it back up and starting again?

**Comment by SuperPotatoMen** [comment]
Yes, can you delete your ombi.sqlie file and start over again?

Groet,
Pieter-bas Ronner




2017-02-20 11:12 GMT+01:00 VanCityGuy <notifications@github.com>:

**Comment by VanCityGuy** [comment]
Thanks didn't work. Still getting the same error. I do have a base URL set /movies in Radarr and and the Omni radarr settings, and it is also going through nginx, but I tried bypassing all of that earlier while troubleshooting and it didn't fix it.

**Comment by VanCityGuy** [comment]
Could we re-open this please?

**Comment by henrikrox** [comment]
I met this bug updating from stable to dev, and i have tried removing omni and installing a differnet version, but i keep getting this bug, and i dont know how to to fix it.

**Comment by SuperPotatoMen** [comment]
@VanCityGuy yeah i reopend it., i will ask Jamie to look at this, your not the first that did the reporting this in.

**Comment by VanCityGuy** [comment]
Awesome, thanks! Just did a fully fresh install, and still getting the same error. Thanks for all the support you guys provide, I love Ombi!

**Comment by tidusjar** [comment]
Hey guys. 

Can someone send me their database ? Tidusjar@gmail.com

Can you change your admin password and then send me the username and password. If I can reproduce this issue it will be a lot quicker to fix. 

Thanks.

**Comment by VanCityGuy** [comment]
@tidusjar Sent my database to your email. The user name and password are included.

Thanks!

**Comment by smcpeck** [comment]
To potentially add some color here, I was seeing the same issue with logs showing `Invalid Path` on the Radarr side.  Using cURL, I was able to add the movie after a couple tries.

```user@plex:/$ curl -X POST -H "X-Api-Key: xxxxxxx" -H "Content-Type: application/json" -d '{"title": "Stranger Than Fiction", "tmdbId": 1262, "qualityProfileId": 1, "rootFolderPath": "/mnt/Movies/", "titleSlug": "stranger-than-fiction-1262", "monitored": true, "year": 2006, "addOptions": { "searchForMovie": true } }' http://192.168.0.5:7878/api/movie/
{
  "message": "constraint failed\nNOT NULL constraint failed: Movies.Images"
}

user@plex:/$ curl -X POST -H "X-Api-Key: xxxxxxx" -H "Content-Typ: application/json" -d '{"title": "Stranger Than Fiction", "tmdbId": 1262, "qualityProfileId": 1, "rootFolderPath": "/mnt/Movies/", "titleSlug": "stranger-than-fiction-1262", "monitored": true, "year": 2006, "images": [], "addOptions": { "searchForMovie": true } }' http://192.168.0.5:7878/api/movie/```

I attempted to fashion the first request after what the Ombi code **looks like** it is doing.  After adding the `"images": []` item to my request payload, things succeeded using cURL.

Let me know if you don't think this is pertinent and I can open a new issue to track what I'm seeing.  The behavior definitely seems to be the same.

**Comment by tidusjar** [comment]
It's in the latest EAP build.

Please go into the Radarr setting and clear your browser cache and then re-save.

**Comment by VanCityGuy** [comment]
Updated to latest EAP, and re-saved my settings. Can now send movies to Radarr, and it is downloading as expected.

Thanks!

**Comment by ajkis** [comment]
I updated to latest EAP but root folder is still not being saved.

**Comment by vertigo235** [comment]
I'm having this same issue had to disable Radarr to get requests to save. 

Resaving radarr settings did not help, I even tried a different browser.

**Comment by kewlrobd** [comment]
I am having this exact same issue.  I have done everything in this thread including a complete fresh install of both Radarr and Ombi.  I am still getting the error.

**Comment by PotatoQuality** [comment]
Pleas open your own issue ticket pleas.

**Comment by xrishox** [comment]
enabling the radarr plugin seems to make ombi unusable for me. on top of that the radarr plugin used to succeed on connect, but no longer does. dunno if it corrupted something or what.

**Comment by PotatoQuality** [comment]
See my text above... 
Stop reporting issues over here and open a new issue
