### ISSUE TITLE
Requested TV show does not show on requests page.

### ISSUE THREAD

**Issue by gilbN** [tidusjar/Ombi#1154]
#### Ombi Version 2.1.1336

OS: Windows 10

Branch:	Stable

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The requested TV show does not appear in the requested tab. I get the email. And when I try to request the show again it says "pending approval"

#### Reproduction Steps:

Request a TV show.

**Comment by gilbN** [comment]
Here is a photo of what it looks like if I try to request it again. [http://imgur.com/a/ApoDZ](url)

**Comment by SuperPotatoMen** [comment]
On you requests page you need to use the filter function to see the pending approvals.

**Comment by gilbN** [comment]
Filter option is set to All

**Comment by gilbN** [comment]
And I have tried Not approved, but nothing shows up

**Comment by SuperPotatoMen** [comment]
Pleas follow the instructions over here from Jamie:

https://github.com/tidusjar/Ombi/issues/1142

**Comment by gilbN** [comment]
So this was the error:

{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.FormatException: Input string was not in a correct format.
↵   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
↵   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
↵   at Ombi.UI.Modules.RequestsModule.<>c__DisplayClass47_0.<GetRootPath>b__3(SonarrRootFolder x) in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 297
↵   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
↵   at Ombi.UI.Modules.RequestsModule.<GetRootPath>d__47.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 297
↵   --- End of inner exception stack trace ---
↵   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)"
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500

**Comment by SuperPotatoMen** [comment]
You are now on the stable branch.
Can you upgrade to the Lasted AEP version? Jamie fixed some problems with the requested page?

**Comment by gilbN** [comment]
Thanks, will try when I get home from work.

**Comment by SuperPotatoMen** [comment]
No problem! Let me know.

**Comment by tidusjar** [comment]
It's a mono issue. Please can you upgrade mono?

**Comment by gilbN** [comment]
I don't use mono. I'm on Windows :)

**Comment by gilbN** [comment]
Upgrading to EAP fixed my issues. Requests are now appearing as normal. Thanks for the fast replies and help!

**Comment by SuperPotatoMen** [comment]
Cool
