### ISSUE TITLE
Newsletter not send

### ISSUE THREAD

**Issue by thesatman** [tidusjar/Ombi#1155]
#### Ombi Version
V 2.1.1336
#### Update Branch:
Stable
#### Operating System:
Windows 7/Windows Server 2008 R2
#### Log Level:
Error
Application Version:	2.1.1336
OS:	Windows 7/Windows Server 2008 R2
System Version:	4.0.30319.42000
Branch:	Stable
Log Level:	Error
Database Location:	C:\PlexOmbi\Ombi.sqlite
Running Directory:	C:\PlexOmbi

This is my very first post. Succesfully installed Ombi.I have not yet entered any parameters to automate passing on requests o SR or CP. To start with I will do this manually.

Parameters for Plex have been entered, and I have contact with the server.

Email notification: Entered SMTP info and test email is successful.

Newsletter settings: Enabled. When sending a test email to the admin, Ombi presents a spinning "O" for about 1,5 minute before confirming success. When checking my email account I find the email but a few things are off....

The new content summary starts with over 100 horizontal lines (dividers?, missing content?), then followed by a list of ALL movies. I also find movies listed that I do NOT have in my Plex movie collection ??

Then I get the NEW EPISODES. Same issue here, lots of horizontal lines, then the episodes.

Conclusion for the test email: 

1- It looks like the 1,5 minute is due to the fact that it is going thouh the entire database. Maybe a hint? Make a pop up notification that the test email can take some time. I unintentionally aborted the process many times by entering one of the side menus just to check if all settings were correct. 

2- There is something wrong with the composistion. I could forward you copy of the email. Where can i send i to? A-The "dividers", B-the movies on my liting that are not in Plex. And something I just found out:C- no music listed.

Now, after going through this process, I was curious on how Ombi would notify me after I added some new TV-show episodes. No email has been delivered to my inbox, nothing in my SPAM box. When is the cron job for sending newsletters? I tested the test email to admin, and they do work.

LOG: Not sure if this is related,but it may be a start:

Exception when trying to process a TV Show, either in getting the metadata from Plex OR getting the information from TVMaze, Plex GUID = com.plexapp.agents.none://17637/3?lang=xn	Ombi.Services.Jobs.RecentlyAdded	Error	2/20/2017 12:11:01 PM

Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) --- End of inner exception stack trace --- at Ombi.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 68 at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 86 at Ombi.Services.Jobs.RecentlyAdded.GenerateTvHtml(List`1 tv, PlexSettings plexSettings, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 399	Ombi.Services.Jobs.RecentlyAdded	Error	2/20/2017 12:11:01 PM

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)	Ombi.Api.ApiRequest	Error	2/20/2017 12:11:01 PM

Notice the line  "C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 399". I have no C:\projects folder ...

If you need more info, please let me know.

**Comment by SuperPotatoMen** [comment]
Don't worry about the: Notice the line "C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 399". I have no C:\projects folder ...

That path is a internal one

**Comment by SuperPotatoMen** [comment]
Can you upgrade to the lasted version of thhe eap branch? Jamie did a lot of fixes for the newsletter.

**Comment by thesatman** [comment]
Thx for the swift respons. The newsletter is better now in the header
(for what is concerned for the movies section). There are still
dividers/horizontal lines above the TV Episodes.

There are still movies in the list that I do not have in my library. So
I'm curious where Ombi gets the data to build the list?

A suggestion: I have some double postings in the list. This is because I
use multiple libraries where a movie can be found. I use f.ex. this setup:

Folder structure:

movies
movies family
movies kids

Plex libraries:

Movies (movies found in folder Movies + Movies Family)
Movies Kids (movies found in folder Movies kids + movies family)

So if possible your listing should give the reader the info about in
whatr Library the movie is found.

**Comment by tidusjar** [comment]
Can you please try again, I have reworked completely how we get the information from Plex.

**Comment by SuperPotatoMen** [comment]
No answer, closing this one.

**Comment by thesatman** [comment]
Sorry for not getting back to you. In the middle of moving to a new
address. So much to do, so little time. I installed the latest EAP. Just
waiting for the cron to do it's job. Not sure how often it runs for the
email newsletter.

**Comment by thesatman** [comment]
Thanks for the update. I have send the test email to the admin account. There are still movies in the list that I do not have in my library. So I'm curious where Ombi gets the data to build the list?

Please also note that in the log file the copy of the email (debug) is showing the movie title in white font, thus not showing on white background.

**Comment by SuperPotatoMen** [comment]
The data is directly from your plex database.

**Comment by thesatman** [comment]
I did a search in my Plex web app. one of the movies that are in the newsletter, but unknown to me is "Love Potion No. 9". Searching for "Love Potion" returns zero hits. I have emptied my Plex cache. And there are more examples. Is there a way to do a CLI query to see the results?

**Comment by tidusjar** [comment]
So once we have the content from plex we will use the IMDB id provided in the Plex Metadata for that media item. We use that IMDB Id and lookup some extra information on TheMovieDB. So it could be that the IMDB Id in Plex is incorrect or the mapping on TheMovieDb is incorrect.

**Comment by thesatman** [comment]
I'll be doing some more testing next week with the ExportTools Plex plugin to export the movie library. From here I can check all IMDB IDs, if present. Some movies don't have a IMDb ID, but an ID of TheMovieDB instead. Some don't have even that (usually when they're 'unmatched' or when they're matched with a 3rd party agent like the .nfo importer agents for instance).

The first movie I have found out. It was not matched in Plex. It is an online documentary. No match, no ID. Does Ombi in case of missing ID still do something? Maybe a good solution would be to use a placeholder picture (Sorry No Info), and use the actual name of the video (as used in Plex). In this case Ombi did a lookup based on something weird, then fetched the name that IMDB or TMDB suggested. And in some cases it uses a picture from IMDB/TMDB, or it puts a blank / missing picture. Just a suggestion ;). I'll get back to you with the results of my tests.
