### ISSUE TITLE
Newsletter not send

### ISSUE THREAD

**Issue by thesatman** [tidusjar/Ombi#1156]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Version 1.3.4.3285

#### Operating System:

Windows 7/Windows Server 2008 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Exception when trying to process a TV Show, either in getting the metadata from Plex OR getting the information from TVMaze, Plex GUID = com.plexapp.agents.none://17637/3?lang=xn Ombi.Services.Jobs.RecentlyAdded	Error	2/20/2017 12:11:01 PM

Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) --- End of inner exception stack trace --- at Ombi.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 68 at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 86 at Ombi.Services.Jobs.RecentlyAdded.GenerateTvHtml(List`1 tv, PlexSettings plexSettings, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 399	Ombi.Services.Jobs.RecentlyAdded Error	2/20/2017 12:11:01 PM

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)	Ombi.Api.ApiRequest	Error 2/20/2017 12:11:01 PM

```

#### Problem Description:

Newsletter not send

#### Reproduction Steps:

Application Version:	2.1.1336
OS:	Windows 7/Windows Server 2008 R2
System Version:	4.0.30319.42000
Branch:	Stable
Log Level:	Error
Database Location:	C:\PlexOmbi\Ombi.sqlite
Running Directory:	C:\PlexOmbi

This is my very first post. Succesfully installed Ombi.I have not yet entered any parameters to automate passing on requests o SR or CP. To start with I will do this manually.

Parameters for Plex have been entered, and I have contact with the server.

Email notification: Entered SMTP info and test email is successful.

Newsletter settings: Enabled. When sending a test email to the admin, Ombi presents a spinning "O" for about 1,5 minute before confirming success. When checking my email account I find the email but a few things are off....

The new content summary starts with over 100 horizontal lines (dividers?, missing content?), then followed by a list of ALL movies. I also find movies listed that I do NOT have in my Plex movie collection ??

Then I get the NEW EPISODES. Same issue here, lots of horizontal lines, then the episodes.

Conclusion for the test email:

1- It looks like the 1,5 minute is due to the fact that it is going thouh the entire database. Maybe a hint? Make a pop up notification that the test email can take some time. I unintentionally aborted the process many times by entering one of the side menus just to check if all settings were correct.

2- There is something wrong with the composistion. I could forward you copy of the email. Where can i send i to? A-The "dividers", B-the movies on my liting that are not in Plex. And something I just found out:C- no music listed.

Now, after going through this process, I was curious on how Ombi would notify me after I added some new TV-show episodes. No email has been delivered to my inbox, nothing in my SPAM box. When is the cron job for sending newsletters? I tested the test email to admin, and they do work.

LOG: Not sure if this is related,but it may be a start:

Notice the line "C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 399". I have no C:\projects folder ...

If you need more info, please let me know.

PS: I posted this first from within the Ombi interface, but I see this post #1155 was closed immediatly b your robot. So I needed to post this twice, now manually.

**Comment by SuperPotatoMen** [comment]
We will help you in the other one :)
