### ISSUE TITLE
HTTPS/SLL Support 

### ISSUE THREAD

**Issue by sam4ks** [tidusjar/Ombi#1158]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever: 

Plex

#### Operating System: 

Windows 10

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
How would I put SSL certificate on my domain that I am using for Ombi?
I rent my domain from 1&1.
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
We don't support SSL connection yet.
