### ISSUE TITLE
User notification emails not an option? How to enable

### ISSUE THREAD

**Issue by henrikrox** [tidusjar/Ombi#1160]
#### Ombi Version:

	2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 8/Windows Server 2012

#### Problem Description:

Hi

I have 3 users, myself (admin), my gf, local user with email setup, and a plex friend also with email.

Both accounts have 

Newsletter
Request Added Notification

setup, but when i go to notification and set up email, the option of user notification email doesnt show, i have seen this option on my screenshots, but its gone for me. I only have Enable, and Enable smtp.

Dunno what im doing wrong, feel like i have set it up how it supposed to be

#### Reproduction Steps:

See above

**Comment by henrikrox** [comment]
![capture](https://cloud.githubusercontent.com/assets/6884716/23140457/088c81d4-f7b2-11e6-83e5-9ed0f3220041.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6884716/23140459/0b8274c0-f7b2-11e6-91be-7f654c6cdc32.PNG)

See pictures

**Comment by SuperPotatoMen** [comment]
I'm not following your question here. There is no other check mark in the admin panel to enable to send notification over email. If you enable "Request added notification" and you config your smtp settings in the admin you are ready to go!

**Comment by henrikrox** [comment]
Hm okay i must have seen a earlier build then, because then you had an option on email settings.

I started working with Ombi yesterday but its working 100%. But i think email is setup wrong.

I have used the same info in email sender and username and password, on email reciepent, i have used my main perssonal email email. I used the test feature, and the email listed in reciepent got the mail.

So like this

Email sender:
plex.myname@gmail.com (with disabled 2 step verification and unsafe apps)
Email recipent:
personalmail@gmail.com
Username:
plex.myname@gmail.com
Passowrd:
plex.myname password

I have tested it and it sending a test email to my personal email. So it seems to be working.

However how can i know for sure the emails in my user list is getting email?

I cant find when the emails are sent? is it after each new request? request completed? So test is working fine, but i havnt gotten any after adding and requesting new movies, but then again, i dont know how often they are sent out.

Any help is greatly appreciated

**Comment by SuperPotatoMen** [comment]
Yeah you are right. We delete the option early in a build. You can set up a local account and give it your email adress. Request something with that account. Go back to your admin account and go to requests page. Then hit the button: mark ad available. You will recieve a email for that.

**Comment by henrikrox** [comment]
Im not following, so is there not a way to send automaticly emails to all the people in the user lists. local users and other plex users?
 
I have manged to send myself emails, but not the above.

**Comment by henrikrox** [comment]
Nvm i understand now SuperPotatoMen, and it worked.

Ty! :)

**Comment by SuperPotatoMen** [comment]
cool! Happy to help @henrikrox  👍

**Comment by henrikrox** [comment]
hi again @SuperPotatoMen 

hope its okay i still ask here, i thought it worked, but i didnt, running into this error now.

i have disabled 2 stpe verificiation and enabled less secure apps, getting error message though

MailKit.Security.AuthenticationException: Authentication failed. at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) at Ombi.Services.Notification.EmailMessageNotification.d__17.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 264

**Comment by henrikrox** [comment]
I got it working with hotmail :)
