### ISSUE TITLE
Package contents no longer has Ombi.exe file?

### ISSUE THREAD

**Issue by VanCityGuy** [tidusjar/Ombi#1161]
#### Ombi Version:

Trying to install latest

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

OSX

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

No Logs

```

#### Problem Description:

While troubleshooting the other issue I had I decided to completely wipe Ombi and download the latest EAP release from github. I notice the file structure has completely changed, and I don't know how to run it anymore. I used to run from the terminal:

```
mono /Applications/Ombi/Release/Ombi.exe
```

However, has mentioned there is no longer an  executable file that I could find in the new releases.

How do we run the latest version on OSX?

Thanks!

#### Reproduction Steps:

Download latest release from github
Unzip, look in folder
No executable file to be found to run via mono in OSX.

**Comment by SuperPotatoMen** [comment]
Hi there,

If you don't have the ombi.exe file you didn't download the correct files. Don't clone or download the github. You need to use the download buttons on the main page:

![image](https://cloud.githubusercontent.com/assets/2944704/23141618/f0bdb68a-f7b7-11e6-9995-99e92e9a5999.png)

**Comment by VanCityGuy** [comment]
Yup, I'm dumb, used that big blue button and got it re-installed.

Thanks! :)

**Comment by SuperPotatoMen** [comment]
yeey ;)
