### ISSUE TITLE
Plex Availability Cacher wont run

### ISSUE THREAD

**Issue by danilitland** [tidusjar/Ombi#1162]
#### Ombi Version:

V 2.1.1430

#### Update Branch:

Tried Stable and Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

Version 1.4.1.3362

#### Operating System:

Unraid 6.3.1 Using Docker Container

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.NullReferenceException: Object reference not set to an instance of an object at Ombi.Services.Jobs.PlexAvailabilityChecker+<>c__DisplayClass44_0.b__0 (Ombi.Store.Models.Plex.PlexContent x) <0x405bef40 + 0x00044> in :0 at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x41e9ebc0 + 0x00090> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.IsAlbumAvailable (Ombi.Store.Models.Plex.PlexContent[] plexAlbums, System.String title, System.String year, System.String artist) <0x405beb10 + 0x0015b> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.CheckAndUpdateAll () <0x405ba730 + 0x007cf> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.Start () <0x405ba590 + 0x00043> in :0

```

#### Problem Description:

Hi
Seems that Plex Availability Cacher doesnt quite work. Tried looking on the other post on githuh to see if someone has similar issue, and cant seems to find anything that can fix the issue.
Have tried on all log levels and still doesnt run properly.
And it wont update Movie requested that has been downloaded and appeared in the Plex library.

#### Reproduction Steps:

1. Happens every time the Job Plex Availability Cacher is running.

**Comment by SuperPotatoMen** [comment]
Hi, can you put the trace log on and run the cacher manualy and post the error over here?

**Comment by danilitland** [comment]
This is what I get:

System.NullReferenceException: Object reference not set to an instance of an object at Ombi.Services.Jobs.PlexAvailabilityChecker+<>c__DisplayClass44_0.b__0 (Ombi.Store.Models.Plex.PlexContent x) <0x405bef40 + 0x00044> in :0 at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x41e9ebc0 + 0x00090> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.IsAlbumAvailable (Ombi.Store.Models.Plex.PlexContent[] plexAlbums, System.String title, System.String year, System.String artist) <0x405beb10 + 0x0015b> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.CheckAndUpdateAll () <0x405ba730 + 0x007cf> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.Execute (IJobExecutionContext context) <0x403cad60 + 0x00043> in :0

**Comment by SuperPotatoMen** [comment]
To be sure, can you force to get a new api key from your plex server?
Something re-authenticate will solve the problem.

**Comment by danilitland** [comment]
Done and got this error from the log:

System.NullReferenceException: Object reference not set to an instance of an object at Ombi.Services.Jobs.PlexAvailabilityChecker+<>c__DisplayClass44_0.b__0 (Ombi.Store.Models.Plex.PlexContent x) <0x405bef40 + 0x00044> in :0 at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x41e9ebc0 + 0x00090> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.IsAlbumAvailable (Ombi.Store.Models.Plex.PlexContent[] plexAlbums, System.String title, System.String year, System.String artist) <0x405beb10 + 0x0015b> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.CheckAndUpdateAll () <0x405ba730 + 0x007cf> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.Start () <0x405ba590 + 0x00043> in :0

**Comment by SuperPotatoMen** [comment]
I think the api is changed by plex. Jamie need to look at this one.

**Comment by danilitland** [comment]
Sweet, Ill keep you updated if anything happens.

**Comment by SuperPotatoMen** [comment]
Workaround is to downgrade you plex server back to 1.3.3 but i don't you like that do that :P

**Comment by danilitland** [comment]
Would be impractical, I dont mind waiting for a update to fix this. I can still do it manually till its fixes. Love this project. Does everything I need and want. Keep up the good work folks.

**Comment by SuperPotatoMen** [comment]
We will give you a update if there is a progress for a fix :) Thanks for you report anyway.

**Comment by tidusjar** [comment]
It's crashing when looking for an album... I'm thinking about removing headphones support.

**Comment by smcpeck** [comment]
@tidusjar I can maybe look at Headphones stuff at some point.  I've been meaning to add it to my setup, so I have an interest. 😃

**Comment by smcpeck** [comment]
@danilitland Can you verify that this is still an issue for you in EAP?  There have been a good handful of changes around the HP integration that should make things much better.  Thanks!

**Comment by danilitland** [comment]
I'll give it a try after work.

**Comment by danilitland** [comment]
Still getting issues. Been trying with HP on and off

System.NullReferenceException: Object reference not set to an instance of an object at Ombi.Services.Jobs.PlexAvailabilityChecker+<>c__DisplayClass44_0.b__0 (Ombi.Store.Models.Plex.PlexContent x) <0x40bebd00 + 0x00044> in :0 at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x42061bc0 + 0x00090> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.IsAlbumAvailable (IEnumerable`1 plexAlbums, System.String title, System.String year, System.String artist) <0x40bebb50 + 0x0015b> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.CheckAndUpdateAll () <0x40be7520 + 0x007cf> in :0 at Ombi.Services.Jobs.PlexAvailabilityChecker.Start () <0x40be6760 + 0x00043> in :0

This is the error message that is showing.

**Comment by danilitland** [comment]
This is interesting, might wanna read this, Ive removed all the request I had on the Album Section. Its runs fine now. Ill keep testing around in coming days to see where the breaking point is.

**Comment by tidusjar** [comment]
Any luck?

**Comment by danilitland** [comment]
Yes and no, seems to partially work from time to time, havent had much time lately do deal with cause of work.

**Comment by tidusjar** [comment]
Ok no problem. Would be interesting to find out why it's not working sometimes with some logs when you get the chance.

**Comment by danilitland** [comment]
Seems the problem has disappeard, I completely removed it and reinstalled it. But got new issues that is already on the forum.

**Comment by SuperPotatoMen** [comment]
cool 👍  i will close this one
