### ISSUE TITLE
Updated to dev branch - Cant download movies with Radarr - Invalid Path	Ombi.Core.MovieSender

### ISSUE THREAD

**Issue by henrikrox** [tidusjar/Ombi#1164]
#### Ombi Version:

	2.1.1430

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

Invalid Path	Ombi.Core.MovieSender	Error

#### Problem Description:

Ridded with bugs today :( 

I updated from stable to dev, i havnt changed anything, Ombi says Radarr is connecting fine, then i try to add movie, and i get "cant add movie, contact administrator".

I havnt changed anything, path, and profile is exactly like before and its the same as in Radarr.

**Comment by henrikrox** [comment]
![1](https://cloud.githubusercontent.com/assets/6884716/23142798/0dc723b4-f7be-11e6-8fa5-12f894cb7b84.PNG)

**Comment by SuperPotatoMen** [comment]
See the knowing bug list for the solution ;)

**Comment by henrikrox** [comment]
that solution didnt not work, still wont add movies/requests

**Comment by SuperPotatoMen** [comment]
Did you push the button get root folders and choose something? After that, you need to save your settings again and that will fix the issue. Can you do that for me and restart ombi server after that?

**Comment by henrikrox** [comment]
Thats what i have done, i even deleted all my settings and did a fresh install. Same thing.

I remove all traces of Radarr, restart Ombi, press get quality profiles and get root folders, choose the root folder thats the same in radarr. restart service, same issue.

I have many movie folders in radarr though, but im current downloading movies to H:\Movies\

settings havnt changed from stable, so something is iffy

**Comment by SuperPotatoMen** [comment]
Yeah, i think we broke something. Main issue ticket is now: https://github.com/tidusjar/Ombi/issues/1152
