### ISSUE TITLE
Requested Tvshows not showing

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/Ombi#1166]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.2.3400

#### Operating System:

Docker

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

No logs

#### Problem Description:

I am using Ombi behind a reverse proxy, but I does not look like that has anything to say (base url: request).
When I try to view my requested tvshows, I don't se anything there, just blank like nothing has ever been requested. 
If I right click and press "inspect element" in chrome, I get a red X in the lower right corner, that says "Failed to load resource: xxxx.net/request/requests/tvshows the server responded with a status of 500 (Internal Server Error)"

If I go to the adress, I get this message. If I try to to to xxxx.net/request/requests/movies, it works just fine (I get alot of text information about the movies in raw format).
![tvshows](https://cloud.githubusercontent.com/assets/4106070/23177891/cb232c6e-f868-11e6-9a02-c2c582b1c686.png)

#### Reproduction Steps:
Not sure... Happens all the time for me.

**Comment by bjonness406** [comment]
Looks like something with my database is corrupt, any way to fix it?
I deleted the sqlite file, and created a new one. Then it worked fine

**Comment by tidusjar** [comment]
Not sure what happened here. Can you send me the corrupt db file?

**Comment by ruricu** [comment]
@tidusjar I'm experiencing the same issue and have just sent my .sqlite file to you; let me know if you need anything else.

**Comment by torem** [comment]
I have the exact same issue. Two days ago I had no tv requests and the page showed the expected "Sorry, we didn't find any results!". Then yesterday I got a tv request and the list went blank with the same 500 error from .../requests/tvshows as described above.

**Comment by bjonness406** [comment]
Sendt you the corrupted db file on your email. 
If it becomes a lot of work for you to fix it, then I can create a new file myself and add the requests again :)
But it looks like more people are having this problem, so maybe a good idea to find out why this is happening?

**Comment by tidusjar** [comment]
Yeah I'll figure it out and fix it when I get a chance tonight!

**Comment by tidusjar** [comment]
I'm not seeing this issue with your databases... Can you guys go into Sonarr and resave the settings (Make sure everything is filled out)

**Comment by ruricu** [comment]
@tidusjar That cleared it up; Cheers!

**Comment by tidusjar** [comment]
I think it might be caused from when I added the new root path selection... I thought I coded around that so you wouldn't run into issues but maybe there is a bug somewhere in that 'migration process'...

If you guys just resave it should be all cool.

**Comment by torem** [comment]
This worked for me as well. Thank you!
