### ISSUE TITLE
Radarr - Missing default root folders option (similar to Sonarr)

### ISSUE THREAD

**Issue by PhAzE-Variance** [tidusjar/Ombi#1168]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.1.3362

#### Operating System:

Unraid Docker

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Radarr - Needs to have scan for default root folders, similar to how it's done in Sonarr.  People who have movies and kids movies separated may want to choose where to download the movie when request is approved.

#### Reproduction Steps:

Go into Radarr settings, there is only the option for a single static default root folder.

**Comment by tidusjar** [comment]
It's already in the eap branch. It will be in the next release.

**Comment by PhAzE-Variance** [comment]
Awesome, closing issue.
