### ISSUE TITLE
EAP zip for Windows?

### ISSUE THREAD

**Issue by bartolomesoriano** [tidusjar/Ombi#1175]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I have not been able to find a zip file for Windows for the Early Access Preview branch, and if I switch branches from the GUI, nothing happens when I try to update from within the GUI.

**Comment by SuperPotatoMen** [comment]
look at the github page. there are 3 big download buttons ;)

**Comment by SuperPotatoMen** [comment]
![image](https://cloud.githubusercontent.com/assets/2944704/23141618/f0bdb68a-f7b7-11e6-9995-99e92e9a5999.png)

**Comment by bartolomesoriano** [comment]
My bad, I am sorry for opening a ticket for this.  I don't know how I missed that! Thank you.

**Comment by SuperPotatoMen** [comment]
No problem, you're welcome. feel free to open a ticket :)
