### ISSUE TITLE
Blocked Sign in Attempt Gmail

### ISSUE THREAD

**Issue by usafle** [tidusjar/Ombi#1176]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10x64

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```


```

#### Problem Description:

Google blocks email sign in attempt due to Ombi being a "less secure app"

#### Reproduction Steps:

I've just received a notice from Google after submitting my user/pass to send myself a "test email" from Ombi.  My only options are to allow <b>all</b> less secure apps or none.

Apparently this is a "less secure app"?
![2017_02_22](https://cloud.githubusercontent.com/assets/18576664/23235373/43cb0500-f923-11e6-9029-4d0ffffafc6d.png)

**Comment by Auwen** [comment]
I created an App Password for Ombi: https://support.google.com/accounts/answer/185833?hl=en

**Comment by SuperPotatoMen** [comment]
@Auwen

**Comment by SuperPotatoMen** [comment]
@Auwen you need to allow less secure apps on gmail for that.
