### ISSUE TITLE
Tv show can still be requested even if its available.

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#1177]
#### Ombi Version:

V 2.1.1412

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

1.4.2

#### Operating System:
Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
When a show is available and the Disable TV requests by episode and Disable TV requests by season are checked it is still possible to request the tv show.
The request button is green instead that the button is showing the text: Available.

![image](https://cloud.githubusercontent.com/assets/2944704/23271382/913b8a24-f9f7-11e6-8a7a-5d0e00f87301.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by ersan** [comment]
Can confirm, just switched from the meteor version to Omni and noticed this, is this only specific to Early Access?  I can roll back if needed.

**Comment by tidusjar** [comment]
Can you guys update and confirm it is now working as expected?

**Comment by ersan** [comment]
Looks fixed now, thanks
