### ISSUE TITLE
Headphone API Key

### ISSUE THREAD

**Issue by almontef** [tidusjar/Ombi#1180]
#### Ombi Version:

2.1.1336 

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:
1.4.0.3224

#### Operating System:
Windows 7 x64
(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I am trying to setup Headphones within the admin settings page. It is asking for a Headphones API Key. Where exactly is that located? I can't seem to find the Headphone API key anywhere within settings. Also, do I need to use the base url or is that optional? Thanks in advance. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by Auwen** [comment]
On the Config page of Headphones, Web Interface tab, right column is the Enable API option. Check that, click Generate. Copy the resulting key into Ombi.

You do not need base url, it's used if you wanna do something like http://yourIP/ombi instead of http://yourIP:3579

**Comment by almontef** [comment]
That did it. Thanks for the pointer in the right direction!
