### ISSUE TITLE
EAP Shows New Update

### ISSUE THREAD

**Issue by elit3ge** [tidusjar/Ombi#1187]
#### Ombi Version:

V 2.1.1463

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

1.3.4

#### Operating System:

Docker/Mono

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Problem Description:

Ombi displays update available, however versions show. 

Current Version:  2.1.1463
New Version:  2.1.1462

**Comment by tidusjar** [comment]
Make sure you change the branch to EAP in the settings?

**Comment by elit3ge** [comment]
It was, another update available now which resolved it.
