### ISSUE TITLE
Ombi picks up trailers in Emby Trailers plugin as available movie

### ISSUE THREAD

**Issue by OverseerMB** [tidusjar/Ombi#1188]
#### Ombi Version:

V 2.1.1462

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Media Server Version:

Emby 3.2.3.0

#### Operating System:

Windows Server 2012R2

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

 I have the Trailers plug-in installed so that we can watch upcoming Trailers and it appears that Ombi picks up those Trailers as AVAILABLE for movie watching in Emby.  For example, Nocturnal Animals is a trailer available to view in via the Trailers plugin.  Ombi shows it as AVAILABLE as a movie.  I actually don't have that movie nor does that Trailers plugin download the trailer as a local file.  This prevents a user from actually requesting the actual movie.

#### Reproduction Steps:

1) Install Trailers plug-in via Emby catalog for server
2) Trailers plug-in does a scan
3) Search for a movie in Ombi
4) Trailer reflects as available in Ombi
5) User cannot Request movie

**Comment by BAS-MB** [comment]
@Cbers do you have this plugin installed?

**Comment by CBers** [comment]
No I don't, but I can install and test if you want?

**Comment by CBers** [comment]
OK, I installed the Emby Trailers plugin and ran the Refresh Channels task. 

I also ran all of the Emby scheduled jobs on Ombi. 

Then I found a movie trailer (Dunkirk) and requested it in Ombi and it requested OK. 

I then logged in as an admin and approved the request, which then added it to Radarr. 

I'm running the following versions of the apps:

Ombi - development 
Radarr - nightly 
Emby - beta
