### ISSUE TITLE
Radarr - Change root folder for requests 

### ISSUE THREAD

**Issue by NightShaman** [tidusjar/Ombi#1189]
#### Ombi Version:

V 2.1.1462 

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
No error log entry created
```

#### Problem Description:

Radarr change root folder not working. 
It pulls the list of root folders from Radarr fine, when going to change one it says successful, but does not change the root folder. in either Ombi nor Radarr

**Comment by smoofus** [comment]
I can't get the even get the root folders to populate.  The button sits and spins. This started with the update that introduced the "-- Invalid Path" issue when requesting movies... I have been unable to solve either of these issue and I've started from scratch.  Radarr is pretty much a no-go for me at the moment.

**Comment by tidusjar** [comment]
@smoofus please raise a new issue

**Comment by tidusjar** [comment]
@NightShaman Just tested this in the latest EAP and it is working correctly for me.

Changed the root folder, (I needed to refresh Ombi to see the changes in the UI which I can change). Approved the movie and it used the root folder I selected.

**Comment by smoofus** [comment]
I may have finally worked through this and I think it was an issue with Radarr rather than Ombi.  I've been troubleshooting the Ombi side of things exclusively but just after I posted this I tried to add a movie in Radarr proper and the "Path" was not populated.  I dorked around with that and set the "Path" in Radarr and then restarted.  Tried to add a movie again, in Radarr, and noticed that the "Profile" was no longer set.  I had to go into Radarr settings to save all the configured profiles. I was then able to add a movie in Radarr and tested successfully with Ombi as well.  The Root folder populated and all is well with me.   That being said, I have not tried to switch root folders so that may still be an issue.

**Comment by tidusjar** [comment]
@NightShaman I see what you may have done, it was possible to click the change root folder button rather than the dropdown arrow.

**Comment by NightShaman** [comment]
Sorry Just got back to checking. 

So I noticed there was a new version for EAP. So upgraded to that version. 
Went in to the Radarr settings verified I can pull both Quality Profiles, and Root folders. and everything looks good there. 
Go to a request, and try to change the root folder from the arrow (I have always used the arrow) and it says root folder changed, Refresh the page, and it still wasn't changed. So then I approved the request choosing the Quality, and tried to change the root folder again Says root folder was changed Successfully yet still the same. 
Went in to Radarr and was still the main root folder. not the one I chose. 

I will go in tonight and remove all the setting for Radarr in Ombi, and then remove my root folders from Radarr and recreate them all to see if I still have issues.

**Comment by NightShaman** [comment]
Still the same. Recreated everything and everything populated with no issues. 
Changing the root folder does nothing. If I have some time this weekend I will see if I can create another instance in my home lab and see if it still happens there. I had recently redid my automation setup and copied Databases instead of going from scratch. I don't think it would cause an issue, but maybe I have a DB borking things.

**Comment by NightShaman** [comment]
Setup in my lab, I get a different issue, The roots show up fine, but when I try and select a root, it says something went wrong. But there is nothing in the logs.

**Comment by tidusjar** [comment]
Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by NightShaman** [comment]
Looks like a 500 Error from Json, 

But I have decided to simplify my environment for testing, As it was a bit complex. 
Originally I have Sonarr, and Radarr running on a linux box, attached to a windows share and Ombi on a windows box, I wanted to take the complexity out of the equation. 

So Setup a new Server 2016 box, Installed Ombi, Sonarr, and Radarr on the same box. My movies, and shows are on another server but there is less issues with windows handling that. 

So in the new setup I have the same Original issue. When I change a root folder it says it was successful but does not actually change the root folder, in either Ombi or Radarr. 
I am not getting any errors in the logs for either. I have both logs set to debug. 
Sonarr works fine with changing the root directory. 

Looking at the browser console everything looks fine.

**Comment by tidusjar** [comment]
I cannot reproduce this. When it says successful, if you refresh the page, you should see it state the root folder it's going to

For example:
![image](https://cloud.githubusercontent.com/assets/6642220/23480949/a8b9b850-fec1-11e6-9551-db7cbf0053d9.png)

**Comment by NightShaman** [comment]
Well the other test turned out different results. With Ombi, and Radarr on the the same server with Radarrs root folders on a local drive. In the config in ombi I can pull the root folders no issue. When I try and change the root folder I get "Something went wrong" 

I get a JSON error 500, 

```
details:"Nancy.RequestExecutionException: Oh noes! ---> Ombi.Helpers.Exceptions.ApplicationSettingsException: The URI is null, please check your settings to make sure you have configured the applications correctly.
   at Ombi.Helpers.UriHelper.ReturnUri(String val, Int32 port, Boolean ssl) in C:\projects\requestplex\Ombi.Helpers\UriHelper.cs:line 64
   at Ombi.Core.SettingModels.ExternalSettings.get_FullUri() in C:\projects\requestplex\Ombi.Core\SettingModels\ExternalSettings.cs:line 46
   at Ombi.UI.Modules.RequestsModule.<ChangeRootFolder>d__67.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 562
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.UI.Modules.RequestsModule.<<-ctor>b__0_9>d.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 107
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)"

```

I have even tried giving 'Everyone' Full Access and the same thing. 

I can give you access to that as well if you wanted.

**Comment by tidusjar** [comment]
Yeah been on this morning and had a look. It is very strange. I was able to switch between Action and Adventure fine... No errors or anything, but I'll see if I can reproduce this

**Comment by NightShaman** [comment]
Thanks, I can leave this up however long. If you need me to grab anything for you, or install a nightly or anything let me know.

**Comment by tidusjar** [comment]
It's in the latest EAP

**Comment by NightShaman** [comment]
Yes! Works great thank you!
