### ISSUE TITLE
Could not load file or assembly 'file:///C:\Ombi\Ninject.Extensions.ChildKernel.dll - Exception from HRESULT: 0x80131515

### ISSUE THREAD

**Issue by rtoolz** [tidusjar/Ombi#1194]
#### Ombi Version:

v2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

127.0.0.1 refused to connect.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Unblock the .zip file before extracting.
