### ISSUE TITLE
Send email out to all users

### ISSUE THREAD

**Issue by squirrellydw** [tidusjar/Ombi#1201]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Can I send an email out to all my users and explaining to them how to use Ombi?  If so how, I don't see any place to write an email and send it?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
This is a feature that Isn't in the stable branch yet. You can upgrade to the lasted Eap version. There is a option in the admin panel called "mass mail".
