### ISSUE TITLE
Radarr Root Save Directory text

### ISSUE THREAD

**Issue by jarkle** [tidusjar/Ombi#1202]
#### Ombi Version:

2.1.1336
#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The Root save directory text says:
'Root save directory for TV shows'

Radarr is for movies, not TV shows..

**Comment by tidusjar** [comment]
This has been resolved in the EAP branch
