### ISSUE TITLE
Not able to re-add request after deletion

### ISSUE THREAD

**Issue by bazhip** [tidusjar/Ombi#1205]
#### Ombi Version
V 2.1.1480
#### Update Branch:
Development
#### Operating System:
Mono
#### Log Level:
Debug
So, I'm new to using this (although plenty familiar with the software it integrates with) and I was having an issue with a couple of my requests going nowhere and not getting added to sickrage or couchpotato. I figured I'd quick delete the requests and then add/approve them again. Unfortunately it seems it didn't kill the database entry and it is not letting me add the shows again, saying an entry already exists. Going under requests, there are zero entries. 

I know I could edit the SQLite db, but I really don't wanna do that. 

This is running on the latest dev version on the docker image.

**Comment by SuperPotatoMen** [comment]
Hi,
Thanks for reporting.
We aware of this.
See: https://github.com/tidusjar/Ombi/issues/1102
