### ISSUE TITLE
Cannot give permissions to plex user

### ISSUE THREAD

**Issue by xhaloz** [tidusjar/Ombi#1208]
#### Ombi Version: 

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

N/A

#### Media Server Version:

N/A

#### Operating System:

Mono

#### Mono Version (only if your not on windows)

4.2.1 

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
System.Net.WebException: Error: ConnectFailure (The requested address is not valid in this context) ---> System.Net.Sockets.SocketException: The requested address is not valid in this context at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40b8b090 + 0x00293> in :0 at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x40b8a260 + 0x0058b> in :0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) <0x42001510 + 0x0013f> in :0 at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (IAsyncResult iar, System.Func`2 endFunction, System.Action`1 endAction, System.Threading.Tasks.Task`1 promise, Boolean requiresSynchronization) <0x40c06b70 + 0x00093> in :0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x42002620 + 0x0002b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x420022b0 + 0x000d3> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x42002200 + 0x00097> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c07ac0 + 0x0003b> in :0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c07a40 + 0x00017> in :0 at Ombi.Helpers.Analytics.Analytics+d__15.MoveNext () <0x41ffc3c0 + 0x00397> in :0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x42002620 + 0x0002b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x420022b0 + 0x000d3> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x42002200 + 0x00097> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c07ac0 + 0x0003b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x4103d570 + 0x00013> in :0 at Ombi.Helpers.Analytics.Analytics+d__11.MoveNext () <0x41ffb510 + 0x0045f> in :0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x42002620 + 0x0002b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x420022b0 + 0x000d3> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x42002200 + 0x00097> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c07ac0 + 0x0003b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x4103d570 + 0x00013> in :0 at Ombi.Helpers.Analytics.Analytics+d__5.MoveNext () <0x41ffab90 + 0x00277> in :0

```

#### Problem Description:

I cannot allow plex users to request content. They can login just fine but get the error "Sorry, you do not have the correct permissions to request music"

I have "Request music" box checked for the user and the user is NOT a "Read only user".  Any local users I have made can request content fine.  Just not a plex user.

#### Reproduction Steps:

Deleted user/restarted server all resulted in the same error.

**Comment by smcpeck** [comment]
If you go to "User Management," does each user actually have the permission to request music?

**Comment by xhaloz** [comment]
Yes sir, the plex user has permission to request music.

**Comment by smcpeck** [comment]
No idea here.  Will have to wait for @tidusjar to offer some thoughts.

**Comment by tidusjar** [comment]
Cannot seem to reproduce this.

Can you send me a image of the permissions of that user?

**Comment by tidusjar** [comment]
No response.

**Comment by ziggie216** [comment]
@tidusjar I'm having the same issue

![screen shot 2017-03-16 at 8 26 03 pm](https://cloud.githubusercontent.com/assets/25150500/24027787/531907b2-0a87-11e7-9b91-2b6698b6e181.png)
![screen shot 2017-03-16 at 8 26 27 pm](https://cloud.githubusercontent.com/assets/25150500/24027788/53191d24-0a87-11e7-9ceb-b848e7352744.png)

**Comment by EnemyWithin** [comment]
Same problem when I login as a Plex user using the email address.  If I login using the Plex name, then it works.

**Comment by tidusjar** [comment]
Do you have another user with the same name?

**Comment by EnemyWithin** [comment]
No, usernames are unique.  I have one local administrator account and the rest are Plex users imported from my friend's list during the install.

**Comment by EnemyWithin** [comment]
Also, User Type in blank and Last Logged In is "Jan 1, 0001 12:00 AM" for all imported Plex users.

**Comment by ziggie216** [comment]
@EnemyWithin do you have "REQUIRE EMAIL ADDRESS WHEN SIGNING IN" enabled in https://plex.tv/users/edit ? Mine was checked so I disabled it, wiped Ombi configuration (I tried without and didn't fix anything), reconfigure Ombi using Plex username (not email address), gave the plex user request permission, and now it's working. 

@tidusjar Issue with using email address as the username?

**Comment by EnemyWithin** [comment]
@ziggie216 No, that wasn't enabled on my Plex account

**Comment by leveraged7** [comment]
#1252

**Comment by tidusjar** [comment]
Is this still an issue?

**Comment by EnemyWithin** [comment]
Unfortunately, yes.  Tested on 2.1.1564

**Comment by tidusjar** [comment]
That icon is just a gravatar image http://en.gravatar.com/. If your email is associated with Gravatar we will show it. Your image must be blue :)

**Comment by EnemyWithin** [comment]
I'm not familiar with Gravatar.  I tried resetting the password (in case I had signed up and forgot), but it didn't recognize my email address.  Another bug?

**Comment by tidusjar** [comment]
I don't think so, i just send the email, and I get an image back if there is an image associated with the email,  and then I display it. Otherwise I don't get an image.
