### ISSUE TITLE
Minor typo in Scheduled Jobs area

### ISSUE THREAD

**Issue by BAS-MB** [tidusjar/Ombi#1210]
#### Ombi Version:

V 2.1.1482

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Problem Description:

Scheduled Jobs page there is a typo on the Watcher Cacher (min) as it reads Wactcher instead.

**Comment by CBers** [comment]
I'll add to this issue, as I noticed that if Ombi can't add a mix, it say "Contract your administrator" instead of "Contact".
