### ISSUE TITLE
Newsletter empty

### ISSUE THREAD

**Issue by bobbintb** [tidusjar/Ombi#1216]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) (Docker)

#### Mono Version (only if your not on windows)

Don't know

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A

```

#### Problem Description:

Newsletter sends but is blank.

#### Reproduction Steps:

When the newsletter sends, either as a scheduled job or test, I get the newsletter but it is blank, meaning there are no newly added shows or movies. There are no errors in the logs. When I turn the logs up to trace, I see a whole bunch of metadata between the "Api Content Response:" and "Deserialzing Object" for both movies and TV. This metdata pertains to the recently added shows and movies, names of the shows, episodes, descriptions, etc. It is obviously getting the information from Plex but it is not in the email. I tested the connection to Plex in the Ombi settings and it works. I can provide the trace logs if requested but it just contains the show descriptions and other metadata, no errors. It doesn't look useful.

**Comment by diedrichg** [comment]
It's an open issue that is actively being worked on.

**Comment by bobbintb** [comment]
Do you have a link? I looked before I started a new one but didn't see anything.

**Comment by bobbintb** [comment]
Why was this closed? I looked through every open issue with the word "newsletter" in it and this is not a duplicate. If so, please link me to it so I can follow progress.

**Comment by tidusjar** [comment]
I think you can follow this: #1163

**Comment by bobbintb** [comment]
That's not the same issue as far as I can tell. I don't have an issue sending emails, the emails are blank. Yes, there are other issues with newsletters being blank but mine issue seems to have a different cause. I get absolutely no errors in my case. When I turn on trace login I can see the request in the logs contains all the correct information that should be in the newsletter. The log shows all the new shows and movies but for some reason, they aren't displayed in the email.

**Comment by SuperPotatoMen** [comment]
:)

**Comment by bobbintb** [comment]
Ok, I did see that issue and I commented on it before I started this as well. It did not look like the same issue but I think that's because there seems to be a lot of others chiming in that aren't experiencing the same problem the OP is. I'll just keep following that issues then. Thanks.

**Comment by magefesa** [comment]
Same problem here.. Newsletter sent but not multimedia added... Thanks to all contributors, great piece of software
