### ISSUE TITLE
Incorrect password disables user

### ISSUE THREAD

**Issue by uberswimmer** [tidusjar/Ombi#1217]
#### Ombi Version:

V 2.1.1496

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

QNAP  OS 4.2.3

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Exception when calling SignIn for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	3/6/2017 7:01:20 PM
Exception when calling SignIn for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	3/6/2017 7:01:14 PM
Exception when calling SignIn for Plex, Retrying 00:00:02	Ombi.Api.PlexApi	Error	3/6/2017 7:01:12 PM
```

#### Problem Description:

When a wrong password is entered in the login screen no user-facing error message is displayed. Ombi hangs at the password screen and that user becomes permanently locked out until Ombi is restarted. 

#### Reproduction Steps:

Ombi hangs at the password screen after a single incorrect password attempt. Attempting to log in using the same username on another browser or device does not solve the issue. Other users are still able to log in.

**Comment by Garderoben** [comment]
Just want to point out in my case the user can login again without restart.
