### ISSUE TITLE
Error when requesting movie already on queue in Radarr

### ISSUE THREAD

**Issue by ladude626** [tidusjar/Ombi#1221]
#### Ombi Version:

V 2.1.1496 (inside rogueosb/ombi docker)

#### Update Branch:

EAP

#### Media Sever:

Plex

#### Media Server Version:

1.3.4.3285

#### Operating System:

Ubuntu 16.04 LTS

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

This movie has already been added	Ombi.Core.MovieSender	Error	3/7/2017 4:54:04 PM

```

#### Problem Description:

When a user tries to request a movie that's already on the Radarr queue for download, it gives a generic error "Could not add movie, please contract your administrator". Would be better to state that movie has already in queue.

#### Reproduction Steps:

Request a movie that's already on Radarr's queue but was not originally requested through Ombi.

**Comment by SuperPotatoMen** [comment]
Yeah we are aware for this issue. I agree on that we don't show a "Could not add movie, please contract your administrator" but a error that it is already requested

**Comment by scoopydude2002** [comment]
Was this fixed with the new update? Seems similar to #1152

**Comment by seanvree** [comment]
I"m seeing this issue as well on Widnows / EAP , 

Application Version:	2.1.1577
OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview


however, It's not just requesting movies that are already in the queue, for me its establishing connection:


"Could not connect to Radarr, please check your settings. Exception Message: Got StatusCode=Unauthorized for http://192.168.1.20:7878/radarr/api/system/status."

**Comment by SuperPotatoMen** [comment]
@seanvree pleas open a new issue for that.

**Comment by tidusjar** [comment]
that means that your API key is incorrect

**Comment by seanvree** [comment]
@SuperPotatoMen @tidusjar - But it's the correct API Key tho.  

I'll open a new issue...thought it was related.

**Comment by ladude626** [comment]
Was this issue fix?

**Comment by PotatoQuality** [comment]
See issue tracker

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455
