### ISSUE TITLE
TV Series could not be found

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1222]
#### Ombi Version:

V 2.1.1496

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Operating System:

Win 8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Core.TvSenderOld.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 173 ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Core.TvSenderOld.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 116<--- 

```

#### Problem Description:

Making History (2017)
www.imdb.com/title/tt5515410/

Making History could not be found during a TV Series search. I couldn't determine what service you're using for the lookup so I could not do a manual search outside of Ombi to let you know if it's a bug or not.

I don't know if the log has anything to do with this issue but I posted it anyways.

**Comment by SuperPotatoMen** [comment]
Hi,

Currently we use TVmaze.com for a TheTVDbId that we need to send you're request to Sonarr.
When the TheTVDbId is NULL on TVmaze we don't show the tv show on the request page beceause Sonarr doesn't allow a Thetvdid is null.
We have a running issue for this to improve our failed queue to handle this situation: https://github.com/tidusjar/Ombi/issues/1120
