### ISSUE TITLE
Can not set up "Notices" if only have Emby Server

### ISSUE THREAD

**Issue by tymanthius** [tidusjar/Ombi#1223]
#### Ombi Version:

V 2.1.1496

#### Update Branch:
Early Access Preview

#### Media Sever:

Emby

#### Media Server Version:

3.2.6.1~beta-79.1

#### Operating System:

Debian Jessie

#### Mono Version (only if your not on windows)

Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

#### Applicable Logs (from `/logs/` directory or the Admin page):

Nothing shows in the logs that I can see, this is just a pop-up msg.

#### Problem Description:

On Landing Page set up screen, if I try to enable notices I get a pop-up that states: We cannot enable the landing page if Plex is not setup!

Can this be changed to work with Emby?

#### Reproduction Steps:

Have Emby only, try to set up notice.  Might work if you had Plex set up before, I don't know.

**Comment by SuperPotatoMen** [comment]
Landing page doesn's support Emby yet ;)

**Comment by SuperPotatoMen** [comment]
It is support excly. @tidusjar can you look in to this one?

**Comment by tidusjar** [comment]
Ah... My bad! I'll fix it, thought i did it 😄

**Comment by tymanthius** [comment]
Thanks guys.  The exchange is amusing, btw.  :)

I'm LOVING that this now supports Emby.  :)

**Comment by SuperPotatoMen** [comment]
Fixed in the EAP branch :)
