### ISSUE TITLE
Log Screen Does Not Match Log (RadarrCacher)

### ISSUE THREAD

**Issue by OverseerMB** [tidusjar/Ombi#1226]
#### Ombi Version:

V 2.1.1499

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Operating System:

3.2.5.0

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

17-3-8 17:47:51.9|Debug|Api|[GET] /api/movie: 200.OK (11630 ms)

```

#### Problem Description:

When running RadarrCacher Ombi Log screen shows

`Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/8/2017 5:47:52 PM`

but log file shows

`17-3-8 17:47:51.9|Debug|Api|[GET] /api/movie: 200.OK (11630 ms)`

Running Radarr nightly 0.2.0.505

#### Reproduction Steps:

Run RadarrCacher Job
Go to log screen
Match against log in logs folder

**Comment by tidusjar** [comment]
What log file are you looking at?
I'm a bit lost, if you are comparing my logs to Radarr's logs that's a silly thing to do.

Just because Ombi reported it failed to cache the items doesn't mean that the api call failed... If you have an issue with the cacher failing please raise a bug for it.
