### ISSUE TITLE
Discord Notifications do not appear when requested through an admin account

### ISSUE THREAD

**Issue by ultimate255** [tidusjar/Ombi#1227]
#### Ombi Version:

V 2.1.1336
#### Update Branch:
Stable
#### Media Sever:
1.4.3.343
Plex
#### Operating System:
Linux Mint 18

#### Mono Version (only if your not on windows)

Stable 4.8.0.495

#### Applicable Logs (from `/logs/` directory or the Admin page):

n/a

#### Problem Description:

When admin users add a movie, a discord notification does not appear. Only when requesting movies on non-admin user account allows Discord notifications to go through.

#### Reproduction Steps:
Use discord notification, request a movie through an admin account.

**Comment by tidusjar** [comment]
This is expected. 

If an administrator requests, we don't bother sending out any notifications.

**Comment by ultimate255** [comment]
Any way to change this? I want notifications for all users including Admins.

**Comment by tidusjar** [comment]
Not currently sorry! Please feel free to raise a feature request on feathub
