### ISSUE TITLE
Ombi is crashing unexpectedly

### ISSUE THREAD

**Issue by lastb0isct** [tidusjar/Ombi#1229]
#### Ombi Version:

2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
* ombi.service - Systemd script to run Ombi as a service
   Loaded: loaded (/lib/systemd/system/ombi.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-03-05 00:06:04 UTC; 16h ago
  Process: 225 ExecStart=/usr/bin/mono ${statedir}/Ombi.exe -p 8083 (code=exited, status=1/FAILURE)
 Main PID: 225 (code=exited, status=1/FAILURE)

Mar 05 00:06:04 PlexRequestsCT mono[225]:    --- End of inner exception stack trace ---
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.Timer+Scheduler.SchedulerThread () [0x0000f] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT mono[225]:   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Mar 05 00:06:04 PlexRequestsCT systemd[1]: ombi.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 00:06:04 PlexRequestsCT systemd[1]: ombi.service: Unit entered failed state.
Mar 05 00:06:04 PlexRequestsCT systemd[1]: ombi.service: Failed with result 'exit-code'.

```

#### Problem Description:

Ombi randomly shuts down

#### Reproduction Steps:

N/A - Happens randomly

**Comment by lastb0isct** [comment]
Also getting these errors within Ombi...not sure if they're related.

`Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 4:07:25 PM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 3:07:16 PM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 2:07:18 PM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 1:07:17 PM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 12:07:17 PM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 11:07:19 AM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 10:07:18 AM
Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/11/2017 9:07:18 AM`

**Comment by tidusjar** [comment]
Can you please upgrade to the EAP version?

**Comment by lastb0isct** [comment]
Upgrading right now.  What was changed in the EAP that you think might fix this?

**Comment by lastb0isct** [comment]
When attempting the update via the auto update tool this is what happens.  Then it never restarts.  I can start the service back up again and it works though...

`service ombi status
* ombi.service - Systemd script to run Ombi as a service
   Loaded: loaded (/lib/systemd/system/ombi.service; enabled; vendor preset: ena
   Active: inactive (dead) since Sat 2017-03-11 22:57:33 UTC; 15s ago
  Process: 32078 ExecStart=/usr/bin/mono ${statedir}/Ombi.exe -p 8083 (code=exit
 Main PID: 32078 (code=exited, status=0/SUCCESS)

Mar 11 22:56:24 PlexRequestsCT systemd[1]: Started Systemd script to run Ombi as
Mar 11 22:56:26 PlexRequestsCT mono[32078]: Starting Up! Please wait, this can u
Mar 11 22:56:26 PlexRequestsCT mono[32078]: Version: 2.1.1336
Mar 11 22:56:26 PlexRequestsCT mono[32078]: Location of the database: /opt/ombi/
Mar 11 22:56:33 PlexRequestsCT mono[32078]: no configuration section <common/log
Mar 11 22:56:34 PlexRequestsCT mono[32078]: Ombi is running on the following: ht
Mar 11 22:56:34 PlexRequestsCT mono[32078]: All setup, Ombi is now ready!
Mar 11 22:57:32 PlexRequestsCT mono[32078]: Starting PlexRequests .Net updater
Mar 11 22:57:32 PlexRequestsCT mono[32078]: Backing up the current version
lines 1-15/15 (END)`

**Comment by lastb0isct** [comment]
Any suggestions on how to upgrade?  Should I manually upgrade to the EAP branch?  Not sure how to do that...

**Comment by SuperPotatoMen** [comment]
@lastb0isct download the EAP files on the main github page and overwrite your files :)

**Comment by lastb0isct** [comment]
@SuperPotatoMen I replaced all of the files that were within the EAP zip and it keeps saying that i'm still behind a version.

I then went a step further and removed the entire directory, while backing up my .sql file.  I re-downloaded the most current release via the main github page, extracted it and then copied over those files again with the EAP files.  Put my DB back in and tried to start the service.  All worked, but it still said I am behind a version, so I attempted the auto-upgrade again and I got the same behavior I reported above.

This is what it is saying on my upgrade page:

Status
Current Version:  2.1.1336
New Version:  2.1.1530

Not sure what else I can do here, since I completely blew out the entire folder already.

**Comment by tidusjar** [comment]
Make sure your Branch on the Update page is correct

**Comment by lastb0isct** [comment]
The branch on the page is EAP.
![eap](https://cloud.githubusercontent.com/assets/19312164/23951663/0dfbd772-094c-11e7-857e-6e7a9e3b3f29.PNG)

**Comment by SuperPotatoMen** [comment]
You didn't download the correct version.

Pleas make sure you download the EAP zip file over here:

![image](https://cloud.githubusercontent.com/assets/2944704/23951908/fba654b4-098f-11e7-98f7-eaa1f1134602.png)

**Comment by lastb0isct** [comment]
That did it! Thanks for all the help.  I am still getting this error, not sure if you're aware of it. I know Radarr is still in beta.

Failed caching queued items from Radarr	Ombi.Services.Jobs.RadarrCacher	Error	3/15/2017 2:04:12 PM

**Comment by tidusjar** [comment]
Make sure Radarr is up to date
