### ISSUE TITLE
How do I set for all users?

### ISSUE THREAD

**Issue by CyberMew** [tidusjar/Ombi#1230]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Always the latest

#### Operating System:

4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

#### Mono Version (only if your not on windows)

not sure

#### Applicable Logs (from `/logs/` directory or the Admin page):

No need

#### Problem Description:

When I setup, all my user are already set to default settings, but I want them to only have auto approve only for movies and not tv series/albums. Also, I want them all to receive newsletter (?) by default. But I don't know how to mass edit the accounts or if it is possible to.

**Comment by SuperPotatoMen** [comment]
Not possible at the moment. we are busy with a bulk option. For now you need to do it manually :(

**Comment by SuperPotatoMen** [comment]
In the admin panel, you can set the default settings under the option "User Management Settings"  for new plex/emby users:

**Comment by SuperPotatoMen** [comment]
See also: https://github.com/tidusjar/Ombi/issues/957

**Comment by CyberMew** [comment]
Cool awesome. I didn't like how the current users list keeps getting resized after closing the user view (messes up the scroll bar, bad for 20+ users editing), looking forward to the new interface. I'm also slightly confused on what some of the user management options do, will explain more in detail but is there a list of explanations currently?

Also, I like the landing page with the notice, but can we have a text field dedicated to a welcome message? 

Finally, your wiki states that gmail uses 465 but actually we can use 587 as well. Better yet if it has the direct link to the gmail help page on SMTP settings though. 

All in all thank you for your help. It's a great project 👍
