### ISSUE TITLE
Plex API error.

### ISSUE THREAD

**Issue by elit3ge** [tidusjar/Ombi#1234]
#### Ombi Version:

V 2.1.1512

#### Update Branch:

development

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

Mono/Docker

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Exception when calling GetMetadata for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	3/11/2017 11:55:44 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	3/11/2017 11:55:44 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	3/11/2017 11:55:44 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	3/11/2017 11:55:34 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	3/11/2017 11:55:34 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	3/11/2017 11:55:34 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	3/11/2017 11:55:29 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	3/11/2017 11:55:29 AM
Exception when calling GetMetadata for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	3/11/2017 11:55:28 AM
There has been a API Exception when attempting to get the Plex GetMetadata	Ombi.Api.PlexApi	Error	3/11/2017 11:55:28 AM

```

#### Problem Description:

Constant errors in the log, Ombi will crash after a couple of hours after this.

#### Reproduction Steps:

Plex setup, episode searching turned off.

I am unable to turn off Use Advanced Search. 

This issue has only been since I have upgraded Plex to the latest version. I have seen in PlexPy updates that they had to change the API due to the new Web version, not sure if it has anything to do with it,

https://github.com/JonnyWong16/plexpy/commit/5997aa5cd9a07096895f918e76cdd1aa041dc5b1

**Comment by tidusjar** [comment]
Hmmm... I cannot see an issue and I am running the same Plex version.

Make sure your API key is correct in Ombi for Plex.

**Comment by elit3ge** [comment]
I have reset all my values and now I have another issue.

'''Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 11:26:10 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 10:53:02 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 10:26:09 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 9:26:11 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 9:21:18 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 9:01:14 AM
'''

**Comment by jaycedk** [comment]
I'm seeing the same error, over and over again.
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 4:52:30 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 3:52:31 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 2:52:30 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 1:52:30 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 12:52:30 AM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/13/2017 11:52:29 PM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/13/2017 10:52:30 PM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/13/2017 9:52:30 PM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/13/2017 8:52:29 PM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/13/2017 7:52:33 PM

**Comment by tidusjar** [comment]
I've added some more logging to see what is going down to see If i can narrow down the issue.

Can someone try the latest EAP build and set your log level to **Debug** please?

**Comment by elit3ge** [comment]
```
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 8:19:14 PM
Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error table PlexContent has no column named ItemId at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x00236] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00059] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 8:19:14 PM
Exception:	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 8:19:14 PM
done all that, moving onto the DB now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 8:19:14 PM
```

**Comment by SuperPotatoMen** [comment]
I think you have the same problem like me:

https://github.com/tidusjar/Ombi/issues/1237

**Comment by tidusjar** [comment]
correct, can you please follow the instructions in the above issue please

**Comment by elit3ge** [comment]
Completed that and this is what I get.

```
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	3/14/2017 9:07:27 PM
Mono.Data.Sqlite.SqliteException (0x80004005): Abort due to constraint violation PlexContent.ItemID may not be NULL at Mono.Data.Sqlite.SQLite3.Reset (Mono.Data.Sqlite.SqliteStatement stmt) [0x00096] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SQLite3.Step (Mono.Data.Sqlite.SqliteStatement stmt) [0x00046] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteDataReader.NextResult () [0x00129] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, System.Data.CommandBehavior behave) [0x00051] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader:.ctor (Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior) at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00006] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <9ff639bdf6294ddea5cf93a0f499a1d4>:0 at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00000] in :0 at Dapper.SqlMapper.QueryMultipleImpl (System.Data.IDbConnection cnn, Dapper.CommandDefinition& command) [0x00071] in <66e14dd398ba43d6a00d12629a33213a>:0	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:07:27 PM
Exception:	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:07:26 PM
Done TV	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:07:26 PM
Done movies	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:06:54 PM
done all that, moving onto the DB now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:06:12 PM
Item count 3	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:07 PM
Going through all the items now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:07 PM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:07 PM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:07 PM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:06 PM
Going through sections now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:04 PM
Getting Lib sections	Ombi.Services.Jobs.PlexContentCacher	Debug	3/14/2017 9:05:03 PM
```

**Comment by SuperPotatoMen** [comment]
Okay, you need to delete the whole table and after that give ombi a restart.

**Comment by elit3ge** [comment]
That is exactly what I did.

**Comment by tidusjar** [comment]
I can see the error with the additional logging. All fixed in latest EAP

**Comment by elit3ge** [comment]
Looks like it's fixed! :D

```
Requests that will be updated count 0	Ombi.Services.Jobs.PlexAvailabilityChecker	Debug	3/15/2017 6:57:59 AM
Done albums	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:55:10 AM
Done TV	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:55:08 AM
Done movies	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:54:43 AM
done all that, moving onto the DB now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:54:13 AM
Item count 3	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:53:04 AM
Going through all the items now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:53:04 AM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:53:03 AM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:53:03 AM
adding lib	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:53:02 AM
Going through sections now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:52:59 AM
Getting Lib sections	Ombi.Services.Jobs.PlexContentCacher	Debug	3/15/2017 6:52:59 AM
```

**Comment by tidusjar** [comment]
Excellent!

**Comment by Morphy2515** [comment]
I also get There has been a API Exception when attempting to get the Plex Libraries	, but I dont know how to solve it :(
The error came after i installed the latest version

**Ombi Version**:

2.2.1591

**Update Branch**:

Stable

**Media Server**:

Plex

**Media Server Version**:

Version 1.5.3.3580

**Operating System**:

Ubuntu 16.04 64bit

**Mono Version (only if your not on windows)**

System Version:	4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

There has been a API Exception when attempting to get the Plex Libraries	Ombi.Api.PlexApi	Error	4/4/2017 7:29:55 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	4/4/2017 7:29:24 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	4/4/2017 7:29:14 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	4/4/2017 7:29:09 PM
There has been a API Exception when attempting to get the Plex Libraries	Ombi.Api.PlexApi	Error	4/4/2017 6:29:55 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	4/4/2017 6:29:24 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	4/4/2017 6:29:14 PM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	4/4/2017 6:29:09 PM
