### ISSUE TITLE
Link to plex functionality

### ISSUE THREAD

**Issue by cardinalfan1** [tidusjar/Ombi#1236]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.3.3433

#### Operating System:

Ubuntu

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

"View in Plex" functionality is not working due to an incorrect URL being passed.

#### Reproduction Steps:

Hi, I'm just crossposting this from something I wrote in #544 , but since the issue was closed, wasn't sure if anyone would see it. I think I've identified the problem and the solution, but I don't have enough knowledge of github to actually try and fix it. 

> Thanks for implementing this feature. I have not been able to get it to work unfortunately. I tried getting my machine identifier from this site: https://plex.tv/pms/servers.xml. When I click on the "View in Plex" button, it takes me to a "You must be lost / This page doesn't exist".
> 
> For reference, the URL it is trying to take me to is: https://app.plex.tv/web/app#!/server/c5e18006a738bcc48bfef87e78f2c2d629851904/details/%2Flibrary%2Fmetadata%2F663
> 
> I tried changing the %2F to https://app.plex.tv/web/app#!/server/c5e18006a738bcc48bfef87e78f2c2d629851904/details//library/metadata/663
> but this did not help either.
> 
> Any suggestions?
> 
> EDIT: Actually I just tried looking for what the correct URL should be, which is:
> https://app.plex.tv/web/app#!/server/c5e18006a738bcc48bfef87e78f2c2d629851904/details?key=%2Flibrary%2Fmetadata%2F663
> 
> Is there any way to get the '?key=' part added on?
> Thanks
> 
> EDIT 2: I think its Ombi/Ombi.Helpers/PlexHelper.cs, line 102 GetPlexMediaUrl...
> If only I could figure out how to edit that file on my copy lol

`public static string GetPlexMediaUrl(string machineId, string mediaId)
 {
 var url= $"https://app.plex.tv/web/app#!/server/{machineId}/details?key=library%2Fmetadata%2F{mediaId}";
            return url;
}`

**Comment by SuperPotatoMen** [comment]
@cardinalfan1 i pushed your report to the dev branch for a fix :)
