### ISSUE TITLE
How do you install? error Ombi: Unexpected status SERVICE_STOPPED in response to START control.

### ISSUE THREAD

**Issue by gbdavidx** [tidusjar/Ombi#1239]
Trying to install Ombi for use with Plex - however when i try to start the service i get: Ombi: Unexpected status SERVICE_STOPPED in response to START control.

I am on windows 10 - installed nssm - i was able to get to everything except the last step

I made sure to unblock the .rar.  I did the download of the master.zip file extracted,  however i noticed there's no C:\Ombi\ombi.exe file, shouldn't this exist? https://github.com/tidusjar/Ombi

Would be nice to be able to use this software

**Comment by SuperPotatoMen** [comment]
You didn't use the download buttons...

![image](https://cloud.githubusercontent.com/assets/2944704/23845527/f5225c1e-07c8-11e7-849d-d25bdcb81af1.png)
