### ISSUE TITLE
Ombi: Unexpected status SERVICE_STOPPED in response to START control.

### ISSUE THREAD

**Issue by gbdavidx** [tidusjar/Ombi#1240]
#### Ombi Version:

V 2.1

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex

#### Operating System:

Windows 8.1

#### Mono Version (only if your not on windows)
n/a

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
not applicable
Not sure where the logs are...

```

#### Problem Description:
Ombi: Unexpected status SERVICE_STOPPED in response to START control.
#### Reproduction Steps:

Starting Service: nssm start Ombi fails everytime
Not able to start the service
Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Deleted folder from C:\Ombi and made sure to follow all steps as described in the windows installation site

**Comment by SuperPotatoMen** [comment]
Pleas start the file Ombi.exe manualy in administrator rights and post the error over here

**Comment by SuperPotatoMen** [comment]
If you don't have ombi.exe file. Then you didn't used the download button on the github page ;)

![image](https://cloud.githubusercontent.com/assets/2944704/23845508/d7307fe2-07c8-11e7-8eb7-088acecbf58e.png)
