### ISSUE TITLE
Request Added Notification

### ISSUE THREAD

**Issue by MrDragonsEye** [tidusjar/Ombi#1241]
#### Ombi Version:

Application Version: 2.1.1336
OS: Windows 8/Windows Server 2012
System Version: 4.0.30319.42000
Branch: Stable
Log Level: Debug
Database Location: E:\ServerFolders\Ombi\Ombi.sqlite
Running Directory: E:\ServerFolders\Ombi

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Version 1.4.3.3433

#### Operating System:

Windows Server 2012 R2 Datacenter V6.3 (Build 9600)

#### Problem Description:

Hi, Please can you confirm what the "Request Added Notification" feature in User Management means?
Should it notify the admin or the user or both when the requested media is added to Plex?
And if so, do you know why this isn't working for me?

I've tested by logging on as an unprivileged user and requesting some media.
I then approved the request as the admin.
I then went and found the film and added it to plex.
Ombi then detected this and automatically set it as "available" but no email notification was sent to anyone.

I've setup SMTP in the Email Notifications section and tested successfully.

I'm missing the "Enable user email notifications" in Email notifications settings:
Was this option removed?
![](http://i.imgur.com/w27vJjH.png)

I've managed to setup the Newsletter feature and have set the CRON scheduler as `0 0 18 ? * FRI *` so will wait and see what happens this Friday evening.

**Comment by tidusjar** [comment]
Hi yes, that option was removed.

So the "Request Added Notification" feature will notify the user (via email if they have one) when Ombi detects the request is now available.

**Comment by MrDragonsEye** [comment]
Okay, thanks for the confirmation.

And would the admin marking the request as available trigger the same notification?

**Comment by MrDragonsEye** [comment]
I've also just changed my SMTP settings to use smtp.gmail.com than smtp-mail.outlook.com and saw no difference.
Test emails send fine, Newsletters send fine, but no Request Added Notification's are being sent.

I've also done that test I just mentioned and requested a film as a user then manually set it as "available" by the admin and nothing was sent. Do I need to approve the request before I set it as available?

What should I be looking for in the logs and at what level will they appear?

Thanks,

**Comment by tidusjar** [comment]
Hi,

So yes marking it as available should send out an email. Are you sure the user has a valid email address. Also check your sent folder on the account you are sending from

**Comment by MrDragonsEye** [comment]
Okay.
Yes, the email address is valid. I've tried changing it to another like Gmail, Outlook and a business Exchange.
The user I'm testing with is an Ombi user, not a Plex server account but I have also tested with one of my PMS users and they are also not receiving anything other than the test emails sent from the Email Notifications settings page and the Newsletters.
The Gmail account I'm now sending from only has the test messages and Movie Request emails in the sent folder.

**Comment by MrDragonsEye** [comment]
So I've just temporarily set the Logging level to Trace and found the following in the logs when simulating it again:

2017/03/13 21:14:09.382 Ombi.Services.Notification.NotificationEngine Debug: Users in the requested model count: 1 
2017/03/13 21:14:09.382 Ombi.Services.Notification.NotificationEngine Debug: usernames from model:  
2017/03/13 21:14:09.396 Ombi.Services.Notification.NotificationEngine Debug: test 
2017/03/13 21:14:09.396 Ombi.Services.Notification.NotificationEngine Debug: Users being notified for this request count 4 
2017/03/13 21:14:09.396 Ombi.Services.Notification.NotificationEngine Info: Notifying user test 
2017/03/13 21:14:09.396 Ombi.Services.Notification.NotificationEngine Info: There is no email address for this Plex user, cannot send notification 

Apparently;
## There is no email address for this Plex user, cannot send notification
However from what I can see, this "test" user has an email address. See below.
![temp](https://cloud.githubusercontent.com/assets/26221415/23875947/28bc27b6-0833-11e7-915a-3074bc9afdfa.png)
![temp](https://cloud.githubusercontent.com/assets/26221415/23875878/ec25802c-0832-11e7-9606-604f1793ead5.png)

**Comment by MrDragonsEye** [comment]
I've also just done the same test with an actual Plex User and not a Local user and get the same error in the logs:

## 2017/03/13 21:25:25.319 Ombi.Services.Notification.NotificationEngine Info: There is no email address for this Plex user, cannot send notification

**Comment by tidusjar** [comment]
Interesting.

I know I have changed this alot in the upcoming version, can you please try the Early Access branch?


My result for a local user:
![image](https://cloud.githubusercontent.com/assets/6642220/23892899/65239f52-0894-11e7-8a07-1071ae28cf0f.png)

**Comment by MrDragonsEye** [comment]
After updating to the EAP, the emails are now coming through for both local and Plex Users, Thanks!

![image](https://cloud.githubusercontent.com/assets/26221415/23894670/eccd1842-089a-11e7-8b37-8bcd4f8e01e0.png)


I also like the slightly new look as well as the Mass Email feature.
However this Mass Email feature doesn't appear to be taking the Email Sender name specified in the settings as is just sending as the gmail account and not adding the "From:" name to the emails.

**Comment by SuperPotatoMen** [comment]
@MrDragonsEye can you open a new issue for that?
