### ISSUE TITLE
Deleted requests shown as requested

### ISSUE THREAD

**Issue by warburp** [tidusjar/Ombi#1242]
#### Ombi Version:

2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Win server 2012 R2

#### Problem Description:

I deleted a few requests that were sent through while CP was down and didn't go through after I relaunched it.  They are no longer shown in the requests tab but if I attempt to request the Movie again it lists it as already requested.

**Comment by warburp** [comment]
They are in neither

**Comment by tidusjar** [comment]
This still happening? I can see a scenario where it's still in the cache, but that would expire after an hour or so
