### ISSUE TITLE
New added TV series not added to Sonarr

### ISSUE THREAD

**Issue by ghallford** [tidusjar/Ombi#1244]
All connectivity tests succeed. Worked adding a series 2 days ago. Nothing in Sonarr logs.

#### Ombi Version: 

2.1.0

#### Update Branch: 

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 7 x86

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Error every 24 mins in the logs:

Ombi.Services.Jobs.PlexUserChecker

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.PlexUserChecker.Start() in C:\projects\requestplex\Ombi.Services\Jobs\PlexUserChecker.cs:line 91

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
That log you are posting has nothing to do with us sending anything to Sonarr.

Can you please fill out the issue template as much as you can otherwise I have no hope of understanding what has gone on to fix this.
