### ISSUE TITLE
Plex primary user not added correctly (can't update permissions)

### ISSUE THREAD

**Issue by ghallford** [tidusjar/Ombi#1249]
#### Ombi Version:

V 2.1.1528

#### Update Branch:

Development

#### Media Sever:

Plex

#### Media Server Version:

Version 2.13.0

#### Operating System:

Windows 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Debug
System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.PlexUserChecker.Start() in C:\projects\requestplex\Ombi.Services\Jobs\PlexUserChecker.cs:line 92

```

#### Problem Description:

Ombi.Services.Jobs.PlexUserChecker Error. Plex primary user not added correctly (can't update permissions)

#### Reproduction Steps:

Scheduled job for user checker puts in this debug error. Also, when I got into authentication > user management and click to edit the plex user, change a permission and click update, the web UI gives the error [object Object] and doesn't udpate.

**Comment by tidusjar** [comment]
Do you have duplicate users with the same name?

**Comment by ghallford** [comment]
No I do not, just the admin user and the primary user. Thanks.

**Comment by tidusjar** [comment]
Are your plex settings correct and upto date?

**Comment by ghallford** [comment]
Yes they are correct and Plex is up to date. It is correctly pulling the
Plex inventory and connection succeeds. Thanks.

**Comment by Kinematic9** [comment]
I am curious if I am having the same issue. I just have Plex connected and it brings everyone in with proper settings. My main username (the one I have Plex registered under) is showing 'processing' for 2 days now. If I try and updated the user settings, nothing happens at all.
![untitled](https://cloud.githubusercontent.com/assets/26988920/24824580/ed0aa2bc-1bdb-11e7-849a-7b6ea9a6f0a7.png)

**Comment by jshapiro26** [comment]
@Kinematic9 i've run into the same issue as you except that I have several other plex users than the admin/owner. All of them have been able default permissions set as expected and updated afterwards. Only the admin/owner of the plex server has been unable to have its permissions set/add. I get the same "Processing..." under permissions for this user.

I am running the latest stable version in a docker container from the image made by @rogueosb at https://github.com/rogueosb/docker-ombi

```
Application Version:	2.2.1678
OS:	Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
Branch:	Stable
```

**Comment by Kinematic9** [comment]
I have that SAME exact issue. All other users have updated with the proper
permissions but my Plex Admin account will not update, just stuck under
Processing. I am now on newest version of Ombi and was hoping that was
fixed.

**Comment by tidusjar** [comment]
Hey guys, 

I've not got around to fixing this yet.

I am currently working on it now and can't seem to be able to reproduce the issue.

Can someone send me their Ombi database so I can investigate to see why this is happening?

tidusjar@ombi.io

Thanks

**Comment by Kinematic9** [comment]
I can get that sent over to you in a bit, once I return. You just need the
ombi.*** file?

**Comment by tidusjar** [comment]
Yeah that's correct. `Ombi.Sqlite`

Thanks

**Comment by Kinematic9** [comment]
@tidusjar Sent over - let me know if I can provide anything else. Thank you!

**Comment by jshapiro26** [comment]
@tidusjar LMK if you need my DB as well. If so can you let me know which data in which tables has personal information that I can obfuscate before sending?

**Comment by tidusjar** [comment]
Please update to EAP

**Comment by jshapiro26** [comment]
i've updated to EAP and it works! thanks so much for working on this issue.

I find that I also don't get any "Last Logged in" dates. Looking at the plexusers table in the DB i see that a new user entry is created upon login with a differing ID, possibly related. But that sounds like another issue for another time.

**Comment by Kinematic9** [comment]
Thank you as well - Processing has been removed now but I also notice the
Last Logged In date is still Jan 0001, but not a big deal.

**Comment by leifi76** [comment]
Sorry to post on a closed issue, but I seem to be in the same scenario as described in this thread. I'm running the latest version (only setup today) on Linux. Any chance this could be looked into - if you need the Ombi.sqlite file (or anything else) please let me know. 

Many thanks.

**Comment by jshapiro26** [comment]
@leifi76 moving to the EAP release solved this issue for me. Additionally, I just moved over to the v3 release which seems to run very well on linux. After looking around for a Dockerfile I decided to slap one together which you can find here if you'd like to test out to see if it resolves your issues: https://github.com/jshapiro26/ombi 
Just run `docker run -p 5000:5000 -v /some/local/dir:/config -d jshapiro26/ombi` and navigate to `http://localhost:5000`.

**Comment by tidusjar** [comment]
Thanks but most people are using the lsio image
