### ISSUE TITLE
Unable to send emails via Gmail

### ISSUE THREAD

**Issue by TheEvilMonkey** [tidusjar/Ombi#1250]
#### Ombi Version:

2.1.1530

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 10 Pro (although Ombi reports as Win 8/Server 2012)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

MailKit.Security.AuthenticationException: Authentication failed. at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) at Ombi.Services.Notification.EmailMessageNotification.d__11.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 205

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Can't get any email notifications to go through.  Using Gmail and I've tried multiple different ports, options, etc.  I don't have 2-step authentication enabled.  I also have enabled "less secure" apps.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by TheEvilMonkey** [comment]
Actually I was able to send emails with another of my Gmail accounts so closing this at this time.

**Comment by tidusjar** [comment]
Did you have 2 factor auth?

**Comment by TheEvilMonkey** [comment]
No, didn't have 2 factory auth on either account, so not sure why one works and the other doesn't.

**Comment by tidusjar** [comment]
Enabled less secure apps? Looks like it's not a code problem :smile

**Comment by joelang1699** [comment]
I have the same issue with multiple gmail accounts.

**Comment by tidusjar** [comment]
Done the above?

**Comment by joelang1699** [comment]
I have indeed. Less secure enabled and one one stage verification. Always ends with Failed: Authentication failed.

**Comment by tidusjar** [comment]
That means that we cannot authenticate. Make sure your credentials are
correct. Not much I can help with here.

**Comment by joelang1699** [comment]
It seems it took the gmail server a while to change the less secure method. Now working!

**Comment by RyanEwen** [comment]
I have the same issue but looking at the instructions for using gmail SMTP it seems you'll may get a CAPTCHA word verification on first login. 

https://support.google.com/a/answer/176600?hl=en

**Comment by ltjdym** [comment]
I figured it out. I had Less secure enabled a long time ago. Just double checked and google said someone suspicious tried to login. I clicked it was me. Now working.
