### ISSUE TITLE
Trying to login with wrong username or password gives no error

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#1253]
#### Ombi Version:

2.1.1496

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Problem Description:

When loggin in with wrong username or password there is no error or message given, just nothing happens.

#### Reproduction Steps:

Login with wrong username and password.

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/1217

**Comment by Dyan654** [comment]
I had this exact same issue after changing my plex password and revoking access to all currently signed in applications. You can fix this by going to http://ip:port/login, logging into your local ombi admin account, and re-authenticating with Plex by generating a new access token.
