### ISSUE TITLE
Ombi/Plexrequest Registration?

### ISSUE THREAD

**Issue by Tatt2edone** [tidusjar/Ombi#1255]
#### Ombi Version:

2.1.1336
#### Update Branch:
Stable

#### Media Sever:

Plex

#### Operating System:

Win 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

System.Net.WebException: The remote name could not be resolved: 'local' at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	3/15/2017 10:05:17 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:10	Ombi.Api.RadarrApi	Error	3/15/2017 10:05:04 AM
System.Net.WebException: The remote name could not be resolved: 'local' at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	3/15/2017 10:05:04 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:05	Ombi.Api.RadarrApi	Error	3/15/2017 10:04:56 AM
System.Net.WebException: The remote name could not be resolved: 'local' at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	3/15/2017 10:04:56 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:02	Ombi.Api.RadarrApi	Error	3/15/2017 10:04:52 AM
System.Net.WebException: The remote name could not be resolved: 'local' at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	3/15/2017 10:04:52 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:10	Ombi.Api.RadarrApi	Error	3/15/2017 10:03:07 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:05	Ombi.Api.RadarrApi	Error	3/15/2017 10:03:02 AM
Exception when calling SystemStatus for Sonarr, Retrying 00:00:02	Ombi.Api.RadarrApi	Error	3/15/2017 10:03:00 AM
```
#### Problem Description:

This may not be a bug,,,or an issue, I have been searching for a couple hours now. I can't login into plexrequests.net or register as it asks for a registration code, if I go to Ombi.io there is no area to register. Without a web link how can users request things?

I have not found anything on the net to resolve this, the program seems to be set up and no errors except that it hasn't scanned my Plex and denied a request to the movie being on the system already.

I am sorry of this is not the correct place for this, just trying to get things set up

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
I

**Comment by SuperPotatoMen** [comment]
I'm not following your question.
Register on ombi.io or on plexrequest.net?!?
You need to host it local and setup a domain name if you like that.

**Comment by Tatt2edone** [comment]
I am sorry, I thought that users would go to plexrequest.net and then they'd make a request. On the Ombi.io site there is very little information aside from features and a download option.

Thank you for your answer, I did not realize when starting into this that I would need a domain. I am assuming the base url is the domain i set up?

**Comment by SuperPotatoMen** [comment]
No,  plexrequest.net is our old name.  .net is a scripting language.  the base url is for proxy servers.
If you like to have a domain, you can buy something from a domain seller.

**Comment by Tatt2edone** [comment]
thank you for your time, I'll do some more research and go from there. All I am trying to do is make it easier to search for things and automate things on my end a little further. I am obviously not either understanding the setup/install, or asking the right questions.

Feel free to close this

**Comment by SuperPotatoMen** [comment]
Best way you get started is following the installation instruction: https://github.com/tidusjar/Ombi/wiki
Helping with setting up a domain name or something is not in our scope to support ;)

**Comment by Tatt2edone** [comment]
No worries, I followed the install guide, its getting outside traffic to access it that I am new to and not sure how to proceed. I trust all the people who have access to my Plex, Ombi just seemed easier than them texting or emailing me for content request
