### ISSUE TITLE
Radarr still doesn't work

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#1258]
#### Ombi Version:

V 	2.1.1538

#### Update Branch:

Early Access Preview
#### Media Sever:

Plex
#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/03/16 23:50:31.190 Ombi.Api.SonarrApi Error: Exception when calling GetRootFolders for Sonarr, Retrying 00:00:01 Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=Unauthorized for http://localhost:7878/api/rootfolder.
   at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 98
   at Ombi.Api.SonarrApi.<>c__DisplayClass7_0.<GetRootFolders>b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 76
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.RetrySyntax.<>c__DisplayClass14_0.<WaitAndRetry>b__1()
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)

```

#### Problem Description:

Test option and get root folders button doesn't work

#### Reproduction Steps:

Copy past your api key to ombi, save it and i stil lget a unauthorized error back.
Are we sure we send the api key?

**Comment by diedrichg** [comment]
I'm not getting confirmation during a search that a movie is already in the Radarr queue. I have multiple errors for `Failed caching queued items from Radarr` and then there was this after a test search for a movie that was already in the queue.
`System.NullReferenceException: Object reference not set to an instance of an object. at MimeKit.MailboxAddress.Encode(FormatOptions options, StringBuilder builder, Int32& lineLength) at MimeKit.InternetAddressList.Encode(FormatOptions options, StringBuilder builder, Int32& lineLength) at MimeKit.MimeMessage.SerializeAddressList(String field, InternetAddressList list) at MimeKit.MimeMessage.InternetAddressListChanged(Object addrlist, EventArgs e) at MimeKit.InternetAddressList.OnChanged() at MimeKit.InternetAddressList.Add(InternetAddress address) at Ombi.Services.Notification.EmailMessageNotification.d__11.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 208`

**Comment by SuperPotatoMen** [comment]
@diedrichg that error is fixed on the Dev branch last commits. You can upgrade to the dev branch for that.
