### ISSUE TITLE
TV Series was never requested but is pending approval despite pre-existing in the Sonarr database

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#1259]
#### Ombi Version:

2.1.1538

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Media Server Version:

Sonarr 2.0.0.4645

#### Operating System:

Win8.1

#### Problem Description:

Searching for a TV series that exists in Sonarr yields a "Pending Approval" **despite the request was never even made** **AND** the series already exists in Sonarr and is Available. Here's the kicker: It appears completely random which series is labeled Pending, Processing or Available. I can not find any commonality be it - monitored in Sonarr, a shared library in Emby, Ended series, Running series.... anything.

![2017-03-16 20_34_48-ombi](https://cloud.githubusercontent.com/assets/9559987/24024439/d2276998-0a89-11e7-9f5a-42816f4f2a41.png)
![2017-03-16 20_35_31-ncis - sonarr](https://cloud.githubusercontent.com/assets/9559987/24024441/d450564e-0a89-11e7-9991-323b2c86efd0.png)

#### Reproduction Steps:

Search for all TV series that exist in Sonarr. The series does not need to be monitored, does not need unwatched media, or anything of that nature. The existing series will display as either Pending, Processing or Available even though the series was never requested through Ombi and already exists (with media) in Sonarr.

**Comment by SuperPotatoMen** [comment]
We going to refactor the Sonarr integration. that will fix this issue.
