### ISSUE TITLE
Last Logged In = Never

### ISSUE THREAD

**Issue by gangoes** [tidusjar/Ombi#1261]
#### Ombi Version:

2.1.1538

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 7

#### Problem Description:

Despite Ombi being used very regularly by around 10 users (Plex Firends) the 'User Management' section shows 'Last Logged In' = 'Never' for all users (except admin). (Also, maybe unrelated, 'User Type' is blank as in #1252.)

This has been the case since before upgrading to Ombi, as well as in stable branch. I have also made a separate fresh installation and this also has the same problem.

Many thanks,

#### Reproduction Steps:

Have a user (Plex Friend in my case) log in to Ombi.
Notice that the User Management page still says they have never logged in.

**Comment by SuperPotatoMen** [comment]
I see this problem too , by me its stuck on: jan 1, 0001 12:00 AM

**Comment by SuperPotatoMen** [comment]
Marked for Issue,
