### ISSUE TITLE
Sonarr searches for individual episodes when season is requested

### ISSUE THREAD

**Issue by transiti0nary** [tidusjar/Ombi#1262]
#### Problem Description:

When I approve a requested TV show in Ombi, Sonarr then searches for each individual episode. As my torrent tracker only keeps pilots and full season packs, this results in just the pilot being downloaded. 

#### Reproduction Steps:

Add and approve a TV show request in Ombi that is configured to be fulfilled by Sonarr.

**Comment by SuperPotatoMen** [comment]
Knowing issue :(
