### ISSUE TITLE
E-Mail Notifications Are Not Being Sent

### ISSUE THREAD

**Issue by bartolomesoriano** [tidusjar/Ombi#1263]
#### Ombi Version:

2.1.1538

#### Update Branch:

EAP

#### Operating System:

Windows 10  

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.NullReferenceException: Object reference not set to an instance of an object. at MimeKit.MailboxAddress.Encode(FormatOptions options, StringBuilder builder, Int32& lineLength) at MimeKit.InternetAddressList.Encode(FormatOptions options, StringBuilder builder, Int32& lineLength) at MimeKit.MimeMessage.SerializeAddressList(String field, InternetAddressList list) at MimeKit.MimeMessage.InternetAddressListChanged(Object addrlist, EventArgs e) at MimeKit.InternetAddressList.OnChanged() at MimeKit.InternetAddressList.Add(InternetAddress address) at Ombi.Services.Notification.EmailMessageNotification.d__11.MoveNext() in C:\projects\requestplex\Ombi.Services\Notification\EmailMessageNotification.cs:line 208

```

#### Problem Description:

With latest EAP, e-mail notification stopped working.  When trying to send a test e-mail notification, nothing gets sent, even though the program says that the e-mail was sent successfully.  Using a G-mail account.  The info above appears in the log.

**Comment by tidusjar** [comment]
Everything filled in, in your settings?

**Comment by bartolomesoriano** [comment]
Yes, everything filled in:

![2017-03-17](https://cloud.githubusercontent.com/assets/7786357/24052307/6b31e68c-0b0b-11e7-9db1-7fc60b42207e.png)

**Comment by SuperPotatoMen** [comment]
Can you upgrade to the last EAP branch, it that fixing your issue?

**Comment by bartolomesoriano** [comment]
Just upgraded to the latest EAP.  The issue is fixed.  Thank you!

**Comment by dhruvb14** [comment]
In latest dev branch i just added another fix that tells you why test email fails if you have config issues as there was a missing exception not being thrown if there was auth or server response issue. No longer will throw success message if it fails. PR is pending.
