### ISSUE TITLE
Ombi wont load after changing port to port 80

### ISSUE THREAD

**Issue by gbdavidx** [tidusjar/Ombi#1269]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

windows 8

#### Mono Version (only if your not on windows)

(Place text here)

2017/03/19 10:00:12 [warn] 4824#4972: conflicting server name "example.com" on [::]:80, ignored
2017/03/19 10:00:12 [warn] 4824#4972: conflicting server name "www.example.com" on [::]:80, ignored
2017/03/19 10:00:12 [warn] 6464#4816: conflicting server name "example.com" on [::]:80, ignored
2017/03/19 10:00:12 [warn] 6464#4816: conflicting server name "www.example.com" on [::]:80, ignored

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Changed port to 80, now ombi wont load, how can i change the port to something else?

**Comment by tidusjar** [comment]
Looks like something else is using that port. You can change it on startup
by doing the following:

Ombi.exe -p 8080

**Comment by gbdavidx** [comment]
i do that in command prompt? i tried and it didn't work...

**Comment by gbdavidx** [comment]
'Ombi.exe' is not recognized as an internal or external command,

**Comment by SuperPotatoMen** [comment]
You need to go to the path first.
