### ISSUE TITLE
View in Plex Issue

### ISSUE THREAD

**Issue by Larcen22** [tidusjar/Ombi#1272]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

#### Mono Version (only if your not on windows)
NA
#### Applicable Logs (from `/logs/` directory or the Admin page):

```

NA

```

#### Problem Description:

When I search a movie that already exists in my Plex, I get the "View in Plex" button. I click it but its not redirecting properly. 

URL Given = https://app.plex.tv/web/app#!/server//details/%2Flibrary%2Fmetadata%2F13009
URL Needed = https://app.plex.tv/web/app#!/server/MACHINEID/details?key=%2Flibrary%2Fmetadata%2F13009

Notice that machineid is not populating and after details should be ? and not /

#### Reproduction Steps:

Search for a movie that already exists on target plex server. Click View in Plex Button, notice it doesn't use the correct URL.

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/commit/53cfb29130814b4d31611d4a7d842c6940b6b4a5 ;)

**Comment by Larcen22** [comment]
I looked around and didn't see that, sorry.
