### ISSUE TITLE
Is there a way to force debug logging during initial startup?

### ISSUE THREAD

**Issue by RXWatcher1** [tidusjar/Ombi#1276]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Docker

#### Mono Version (only if your not on windows)

4.2, 4.6, 4.8

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Starting Up! Please wait, this can usually take a few seconds.
Version: 2.1.1336
Location of the database: /opt/ombi/Ombi.sqlite
Ombi is running on the following: http://+:3579/ombi
All setup, Ombi is now ready!

```

#### Problem Description:

I'm having issues getting the base set properly via docker. It looks like its set however I can't go to http://host/ombi and have it work

#### Reproduction Steps:

This is a fork of the docker you link to on your website but with the -b /ombi set

docker pull rxwatcher/docker-ombi

or

This is a different fork of a linuxserver.io ombi docker with the -b /ombi set.

docker pull rxwatcher/docker-ombi-1

The base isnt being set upon initial pull.

I dont think the issue is a specific version of Ombi. It's probably something docker related but I have a hard time figuring out what that is without some type of logging in ombi as to why its not taking the base when it looks like it is per the startup messages.

**Comment by tidusjar** [comment]
No there is no way to change the logging via startup sorry.
