### ISSUE TITLE
Changed Plex Password, Can't Sign In

### ISSUE THREAD

**Issue by xnaas** [tidusjar/Ombi#1277]
Apologies for skipping the usual information, but I can't sign into Ombi, so I can't really get you any useful info (the database even has several version listed...). Sorry!

Pretty sure I simply need to clear out a token or cached login info or something, somewhere.

I was skimming through the `Ombi.sqlite` database, but couldn't figure out which exact thing is the problem.

**Comment by xnaas** [comment]
Sorry @Ombi-robot. Today, you have failed at your job!

**Comment by tidusjar** [comment]
Everything should work if you are trying to log in with your Plex account. The way we sign in is by calling the Plex API. If the call fails then you didn't authenticate with Plex correctly.

**Comment by xnaas** [comment]
I don't know what else to say. If I try to sign in with my new or old password, it just tells me bad username/password. This worked all just fine before changing my password.

PlexPy had a similar issue, but all I had to do was generate a new token and all was well. I presume this is a similar situation?

**Comment by SuperPotatoMen** [comment]
You need to login with our local ombi account and change the api key in your settings. Ombi can't talk to the api of plex beceause its revoke

**Comment by xnaas** [comment]
Ahh, fuck. Alright. I'll keep guessing my local password then.

Is there any way I can reset that password in the Ombi database, or no? If not, it's fine, I'll get it eventually.

**Comment by xnaas** [comment]
I don't know what on Earth it set my local password to, but it's definitely not what I set it to originally...I've tried every possible password it could be and *nothing* works to sign into /admin. ¯\\\_(ツ)_/¯

**Comment by xnaas** [comment]
I'll just do a fresh install, fuck it. 😛 Thanks anyway. 👍

**Comment by Dyan654** [comment]
I had this exact same issue after changing my plex password and revoking access to all currently signed in applications. You can fix this by going to http://ip:port/login, logging into your local ombi admin account, and re-authenticating with Plex by generating a new access token.

**Comment by pressRtowin** [comment]
happening to me now after the plex data breach. Every attempt to log in with a local account has failed.
