### ISSUE TITLE
TV Shows requested not showing to approve

### ISSUE THREAD

**Issue by TheEvilMonkey** [tidusjar/Ombi#1278]
#### Ombi Version:

2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10 Professional

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I've had users request new TV Shows and I get email notification but when I go to approve them nothing is showing up.  Movies are fine however.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Check your filters on the requests page

**Comment by TheEvilMonkey** [comment]
Thanks, already checked that...just tried adding another show myself and it just lists an empty screen.

**Comment by TheEvilMonkey** [comment]
If I search for the show (after requesting it), it does show as "Pending approval", just won't show on the Requests page so I can approve it.

**Comment by SuperPotatoMen** [comment]
@TheEvilMonkey is it mandatory that there is a need for a approval?

Otherway you need to check the option "Do not send notifications for requests that don't require approval"  in your admin panel under "Ombi Configuration"

**Comment by TheEvilMonkey** [comment]
Currently yes, I do require approval.  I don't believe this is a notification issue.  The problem is that I'm not seeing TV show requests that are pending approval when I'm logged in as Admin.

**Comment by SuperPotatoMen** [comment]
What do you see If you loggen in?

**Comment by SuperPotatoMen** [comment]
Pleas post a printscreen van the permissions from the user and from the requests page

**Comment by TheEvilMonkey** [comment]
Here is the Request User permissions
![requestuser](https://cloud.githubusercontent.com/assets/2296106/24214403/5fc4f978-0f03-11e7-8e02-524204f093f6.JPG)

**Comment by TheEvilMonkey** [comment]
And here is the Admin user
![adminuser](https://cloud.githubusercontent.com/assets/2296106/24214418/6f7c2f94-0f03-11e7-8a07-5c4f7168e2a6.JPG)

**Comment by TheEvilMonkey** [comment]
This is what I see when logged in as Admin under TV Shows...
![tv show requests](https://cloud.githubusercontent.com/assets/2296106/24214493/ad9db536-0f03-11e7-93df-4fad2f0e60d6.JPG)

**Comment by SuperPotatoMen** [comment]
Can you press f12 in chromecast on that requests page and choose for console. I'm intrested if there is any kind of error.

**Comment by TheEvilMonkey** [comment]
Good catch...

http://localhost:3579/requests/tvshows Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by TheEvilMonkey** [comment]
I read through some of the other issues related to a 500 status...went into Sonarr settings, clicked Test, then Submit and now it's working correctly.  Closing this issue, thanks!
