### ISSUE TITLE
couple of questions

### ISSUE THREAD

**Issue by sydeburnz** [tidusjar/Ombi#1279]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Sever:

Plex

#### Operating System:  Windows Server 2008 r2

on the ombi configuration page, what is the api field for?  if this generates an api key, where does this key go?

also, when i try sending the newsletter to admin i get this error:  Object reference not set to an instance of an object.

Is there any documentation for configuration?  After the install is done?

Glad you have been making updates, the old version kept crashing on my windows server, this seems to be running great.

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```


System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.RecentlyAdded.Start(NewletterSettings newletterSettings, Boolean testEmail) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 119 at Ombi.Services.Jobs.RecentlyAdded.Test() in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 112 at Ombi.UI.Modules.Admin.AdminModule.RecentlyAddedTest() in C:\projects\requestplex\Ombi.UI\Modules\Admin\AdminModule.cs:line 1166

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Hi!

> on the ombi configuration page, what is the api field for? if this generates an api key, where does this key go?

Its for people that want to use the Ombi API, I will be reworking it as it's not really that friendly

> also, when i try sending the newsletter to admin i get this error: Object reference not set to an instance of an object.  

Please raise a new issue for this with all the log details

> Is there any documentation for configuration? After the install is done?

No there is none sorry, there is some handy tooltips to start explaining things in the EAP branch. It's an area i'd like to improve

> Glad you have been making updates, the old version kept crashing on my windows server, this seems to be running great.

Excellent!

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/1280
