### ISSUE TITLE
documentation for configuration in wiki

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1280]
I'm going to work on a wikipedia page to make some documentation for configuration. 
My english is not very good on this point so maybe someone can help me to improve the text when i'm finished :)

**Comment by sydeburnz** [comment]
i would be happy to help.  i could even do my own documentation and send it to you.  i just dont want to duplicate efforts.

**Comment by SuperPotatoMen** [comment]
@sydeburnz  Cool, maybe we can splitt out the work so we are faster?

**Comment by sydeburnz** [comment]
how about i just knock it out and send it to you for revview, additions and adding to the wiki?

**Comment by sydeburnz** [comment]
i also think the windows install should be brought in house to the wiki instead of pointing to an external source that still says plexrequest.net becaues it is confusing to a n00b.

**Comment by SuperPotatoMen** [comment]
@sydeburnz yeah good idea, lets do it :)

**Comment by SuperPotatoMen** [comment]
@sydeburnz maybe we can work with printscreens and explain what the functions are doing.

**Comment by sydeburnz** [comment]
what timezone are you in?  if you give me a few hours, i can probably have a rough doc for configuration.  with step by step and screenshots.

**Comment by sydeburnz** [comment]
@SuperPotatoMen and you can work on the windows install documentation?

**Comment by SuperPotatoMen** [comment]
@sydeburnz Timezone is +1 :) \You can start already, i will check later on

**Comment by sydeburnz** [comment]
here is my first draft of the config guide
[Configuration Guide for Ombi.pdf](https://github.com/tidusjar/Ombi/files/866261/Configuration.Guide.for.Ombi.pdf)

**Comment by tidusjar** [comment]
Wow guys, thanks a lot!

Sydeburnz here is some information about the yellow parts

> Ombi Configuration:
Base Url:

This is for when the user want's to use some sort of reverse proxy. Once the base url is enetered e.g. `base` everything on the website will be the following: http://localhost/base/ including all scripts and assets.

API Key 
this if the Ombi API key, Ombi has it's own API (Not great at the moment and I will be reworking sometime soon)


> Ombi: Customization Settings
Enable Issues

This is to enable the users to report issues for media available on the server either from the search page or requests page

I'll update this post when I have a bit more time

**Comment by SuperPotatoMen** [comment]
@sydeburnz i will look at this today. It looks great!

**Comment by sydeburnz** [comment]
can you tell i do documentation and cookbooks for our dev team and infrastructure for my day job?

haha

**Comment by sydeburnz** [comment]
updated
[Configuration Guide for Ombi.pdf](https://github.com/tidusjar/Ombi/files/873138/Configuration.Guide.for.Ombi.pdf)

**Comment by tidusjar** [comment]
> Enable Netflix results to be shown in the search

When searching for movies / tv shows if this is enabled we will also call the Netflix Roulette API to check if this is available on Netflix. If so it will show a "Available on Netflix" icon


>Recently Added Email (CRON)
I think this is for the newsletter? Why does the cron have a ? in the settings
Is there any more explanation on this page?

This is a [CRON Expression](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm) that will determine when the newsletter is sent.

> Ombi: Request Fault Queue

When there is an error either adding a request OR sending a request to a third party client e.g. Sonarr/Radarr/CP then we will put it into this queue and keep trying. So if the error is that Sonarr is down when we try and send that media to it, it will add it to the queue and keep retrying until Sonarr is back up and we get a successful result.


It's looking really good!

I think it worth putting these into the wiki!

**Comment by sydeburnz** [comment]
3rd time is a charm
[Configuration Guide for Ombi.pdf](https://github.com/tidusjar/Ombi/files/876644/Configuration.Guide.for.Ombi.pdf)

**Comment by leveraged7** [comment]
I use Pushbullet and I have it setup/configured and working. Would you like me to type up some info and send it?

**Comment by sydeburnz** [comment]
that would be great.  grab a before and after screenshot if you can

**Comment by leveraged7** [comment]
@sydeburnz - So do I send this to you directly, or just drop the pictures and the text into "this box" LOL, and you can cut and paste from there?

**Comment by sydeburnz** [comment]
@leveraged7 - you can add a text file and images here as an attachment

**Comment by leveraged7** [comment]
[1_before-pushbullet.pdf](https://github.com/tidusjar/Ombi/files/880025/1_before-pushbullet.pdf)
[2_before access token-pushbullet.pdf](https://github.com/tidusjar/Ombi/files/880027/2_before.access.token-pushbullet.pdf)
[3_after access token-pushbullet.pdf](https://github.com/tidusjar/Ombi/files/880029/3_after.access.token-pushbullet.pdf)
[4_api-token as password.pdf](https://github.com/tidusjar/Ombi/files/880031/4_api-token.as.password.pdf)
[5_api-device list-pushbullet.pdf](https://github.com/tidusjar/Ombi/files/880032/5_api-device.list-pushbullet.pdf)
[6_success.pdf](https://github.com/tidusjar/Ombi/files/880036/6_success.pdf)

**Please note. Before setting up Pushbullet Notifications, must have a valid Pushbullet account. (It's Free)
(Photo 1) Step 1. From the Admin Settings -> Notifications -> Pushbullet Notifications Menu. Click on enable Pushbullet and then Right click on the "Pushbullet", open in a new tab and login into your Pushbullet Account. 
(Photo 2) Step 2. Click on settings, click on account and scroll down to **Access Tokens.** Click on create **Access Token.** WARNING: This is a full access API so do not go around posting your API on the interwebz.  
(Photo 3) Step 3.) Copy the Access Token and paste it into an open notepad file for easy access. 
If you only have one device registered with Pushbullet or if you want to send push notifications to ALL registered devices, then copy and paste this access token to the access token box in Ombi. **Proceed to Step 6**
(Photo 4) Step 4.)  If you want to send to specific devices only, in our example an iPhone, we need the Pushbullet Identification for that device. (You can go to https://docs.pushbullet.com/  to educate yourself on the Pushbullet API.) Open up a new browser tab and proceed to https://api.pushbullet.com/v2/devices. You will be prompted for a user name and password, enter your Access Token as both the User Name and Password. This is the API function to call for the list of all devices associated with your Pushbullet Account.
(Photo 5) Step 5.) After you enter in your access token as both the username and the password, it will return a list of devices both active and inactive associated with your account. Look for the device that you want to send the Pushbullet Notifications to and grab the string of characters and numbers to the right of the "iden:" tag. (In Photo 6, it is highlighted blue and underlined) You do not need the quotations "" just everything in between. Copy and paste this into an empty notepad and proceed to Step 6.
(Photo 6) Step 6.) If you are pushing to all devices or only have one device registered, leave the device Identification blank and only enter in your Access Token. If you are wanting to only push to certain devices, enter the Device Identification under "Device Identifier".  
Click on Test and then click on submit and enjoy your Pushbullet Notifications. They are near instantaneous.
(Photo 7) iOS Sample Screenshot.
[7_iPhone Pushbullet.pdf](https://github.com/tidusjar/Ombi/files/880114/7_iPhone.Pushbullet.pdf)

**Comment by leveraged7** [comment]
Feel free to change the wording around it so sounds better and matches with the rest of the document. I hope this is helpful. Enjoy

**Comment by sydeburnz** [comment]
with pushbullet added
[Configuration Guide for Ombi.pdf](https://github.com/tidusjar/Ombi/files/880301/Configuration.Guide.for.Ombi.pdf)

**Comment by MadsKejser** [comment]
Really nice work sydeburnz.

I just noticed that in the index you have multiple instances where some text goes as a heading.

Page 2 in the middle
Page 3 top and buttom
Page 4 middle and buttom
Page 5 top, middle and buttom
Page 6 top and middle

Each is with this wording:
"This is for when the user wants to use some sort of reverse proxy. Once the base URL is entered (ex.
base) everything on the website will be the following: http://localhost/base/ including all scripts and
assets."

But again - you did a really nice job!. :) 👍

**Comment by sydeburnz** [comment]
thanks.  has now been converted over to the wiki (without images for now)

will look at the notes you left.

**Comment by sydeburnz** [comment]
fixed table of contents formatting.
[Configuration Guide for Ombi.pdf](https://github.com/tidusjar/Ombi/files/880510/Configuration.Guide.for.Ombi.pdf)
