### ISSUE TITLE
Newsletter not sending to admin

### ISSUE THREAD

**Issue by sydeburnz** [tidusjar/Ombi#1281]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows Server 2008 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.RecentlyAdded.Start(NewletterSettings newletterSettings, Boolean testEmail) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 119 at Ombi.Services.Jobs.RecentlyAdded.Test() in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAdded.cs:line 112 at Ombi.UI.Modules.Admin.AdminModule.RecentlyAddedTest() in C:\projects\requestplex\Ombi.UI\Modules\Admin\AdminModule.cs:line 1166	Ombi.UI.Modules.Admin.AdminModule	Error	3/23/2017 7:29:47 AM
System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 134

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Sending email to admin not working.  Also, I have a a test user that I checked the newsletter box in the settings and they did not get a newsletter overnight, or notification of the movie i added via that user which was downloaded (and not shown as available in the view requests area).  

To post logs for this post, i emptied the logs, and then tried to send to admin again so the logs were just focused on that error.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
This is already fixed in the EAP branch. You can test it out in the EAP branch :)

**Comment by sydeburnz** [comment]
ok, it doesnt give an error, but i have not got the test newsletter either.  checked logs and nothing in there.

**Comment by SuperPotatoMen** [comment]
Can you upgrade to the eap branch first?

**Comment by sydeburnz** [comment]
im on 2.1.1548 now

**Comment by sydeburnz** [comment]
have to drive to work, so i will be off for about an hour

**Comment by sydeburnz** [comment]
ok, im near a computer again.  let me know if you need something from me.  still have not received the test newsletter.

**Comment by sydeburnz** [comment]
ok, so while writing the config guide i came across the status page which i found out you can change to EAP there.  I did that and eventually I got a newsletter.  Probably was delayed since my library is a bit big and it was creating a large newsletter.  Maybe upon first setup you can have a setting that allows how many days to go back for the first newsletter?

Just a thought.  

Since I created a config guide, I guess you can say im all in now.  :)
