### ISSUE TITLE
TV shows not loading "requests"

### ISSUE THREAD

**Issue by heartisall** [tidusjar/Ombi#1282]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System
Server 2012R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
When I login as an administrator and go to "requests" so I can review people's submissions the TV tab doesn't populate. The Movie's tab works fine.

![image](https://cloud.githubusercontent.com/assets/17910286/24264361/8b2cebec-0fd6-11e7-8281-68ac38177bbd.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Make sure your sonarr/sick rage settings are all up to date

**Comment by heartisall** [comment]
Whenever I attempt to change any settings within the Sonarr tab I get "{"result":false,"message":"You must specify a Quality Profile."}" message. I don't use sick rage.

**Comment by SuperPotatoMen** [comment]
Pleas update to the eap branch and re save your sonarr settings. (There is a fix for this one :))

**Comment by GregoryGHarding** [comment]
same issue here verified sonarr and radarr settings. requests still do not laod

**Comment by SuperPotatoMen** [comment]
@GregoryGHarding  "Pleas update to the eap branch and re save your sonarr settings. (There is a fix for this one :))"

**Comment by heartisall** [comment]
I updated to version 2.1.1564 which I think is the EAP? (it was the early Access build) but I'm still having the exact same issue. Am I doing something wrong?
