### ISSUE TITLE
Long login times with Plex credentials

### ISSUE THREAD

**Issue by gerby123** [tidusjar/Ombi#1288]
#### Ombi Version: 
2.1.1336
#### Update Branch: 
Stable
#### Media Sever: 
Plex
#### Media Server Version:
1.5.1.3520 
#### Operating System:
Debian (Docker)
#### Mono Version:
4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Login times exceed 20s for users with Plex authentication.

#### Reproduction Steps:

Login with Plex credentials.

Other notes:
Ombi response times in general are very slow; other services on the same hardware typically respond in < 5ms while even health checks against Ombi typically take 200ms.

**Comment by gerby123** [comment]
Captured a sample login session; this one ran 8 seconds; actually the fastest I've seen.

We are authenticated! Setting session.	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:21 PM
Friends list result = True	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:21 PM
Correct credentials, checking if the user is account owner or in the friends list	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:20 PM
Need to auth and also provide pass	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:20 PM
Friends list result = True	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:13 PM
Need to auth	Ombi.UI.Modules.UserLoginModule	Debug	3/27/2017 8:38:12 PM

**Comment by SuperPotatoMen** [comment]
This sound more than a docker settup issue than a ombi problem

**Comment by SuperPotatoMen** [comment]
Login and response times from ombi are very fast.

**Comment by gerby123** [comment]
I can respin the deployment without docker but I moved to docker because performance was so poor.  I'm running HAProxy in front of Ombi when I present it to the rest of the world to add TLS; I'm attaching a screenshot of three different services health checks.  The top is a Java application and the bottom is PlexPy, the middle is Ombi.  Any pointers as to where to start looking for trouble or resource contention would be most appreciated.  I have had to set my timeouts on HA Proxy for this backend to 30 seconds for it to operate properly.
![image](https://cloud.githubusercontent.com/assets/24830453/24383766/0af0ece4-132d-11e7-968a-fd269fe8be72.png)

**Comment by tidusjar** [comment]
Yeah this is unusual behavior.

I am not sure I can help with this as my docker knowledge is pretty poor, but I can help with information on how we are logging in with Plex accounts.

We will call the Plex API to sign in the users passing the users entered credentials:
https://plex.tv/users/sign_in.json

Once we get a response back depending on the response, we either log the user in OR tell them their credentials are invalid.

Other than that I do not know how to help you. There are a lot of users running Ombi in a docker instance with no issues.

**Comment by gerby123** [comment]
I've respun my deployment out of docker to bare Debain; I am still experiencing inconsistent login times.  Could the delays be caused by the Plex auth API?  is there an easy way to determine that? Performance has improved since moving out of Docker.  As an attempt to further improve performance I'm now running Ombi with mono-sgen --llvm -O=all,-gshared ./Ombi.exe

**Comment by akizzle** [comment]
Just want to report that I as well am reporting the same issues as gerby123.

**Comment by CyberMew** [comment]
I'm also experiencing slow logins. It's also happening with the local(?) admin account. Separating the username and login on different screens doesn't make it any easier/faster.

**Comment by gerby123** [comment]
So I've done further testing; there appears to be a memory leak when running Ombi with Mono.  I've tried both mono and mono-sg (different garbage collectors).  Is there any way to log or better profile Ombi to try and determine what isn't being freed?  At the moment I have a crontab set to reboot the guest every 2 hours to keep things usable.  @tidusjar I'd love to be able to help track this down as you've got a great product but the performance on *nix is quite troubling.

**Comment by tidusjar** [comment]
@gerby123 This is the difficulty I struggle with quite a lot, the beast that is mono.
Don't get me wrong, mono is a great product but there are a lot of limitations and things like this are very hard to track down. 

I regularly try and profile Ombi to make sure everything is being freed and cleared up without mono. Trying to do this with mono is a whole different ball games as I do not know the internal workings of mono (They have different implementations to core libs e.g. `System.IO`). I could find this out but it would take quite a long time that I just do not have.

I am planning to move over to .Net Core at one point. But that's almost also a complete rewrite of Ombi... But it will then be platform agnostic without the monolith of mono.
