### ISSUE TITLE
Typo website ombi.io

### ISSUE THREAD

**Issue by wessel01** [tidusjar/Ombi#1291]
#### Ombi Version:

V 2.10.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Linux

#### Mono Version (only if your not on windows)

N.A.

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
The website has a typo:

Ulitmate Plex Companion

shouldn't that be:

Ultimate Plex Companion

:-D

Kind Regards,

Wessel
#### Reproduction Steps:

N.A.

**Comment by tidusjar** [comment]
Fixed! Thanks!
