### ISSUE TITLE
Exception when calling AddSeries for Sonarr, Retrying 00:00:02

### ISSUE THREAD

**Issue by CyberMew** [tidusjar/Ombi#1294]
#### Ombi Version:

V 2.1.1554

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

1.5.1

#### Operating System:

Unraid 6.2.4

#### Mono Version (only if your not on windows)

Not sure how to find out:
Application Version:	2.1.1554
OS:	Mono
System Version:	4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Branch:	Early Access Preview
Log Level:	Info
Database Location:	/opt/ombi/Ombi.sqlite
Running Directory:	/run/s6/services/ombi

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	3/29/2017 1:59:01 PM
approving request 25	Ombi.UI.Modules.ApprovalModule	Info	3/29/2017 1:59:01 PM

```

#### Problem Description:

Unable to accept TV show request. Connection tests to Sonarr in the config setup works ok.

#### Reproduction Steps:

Someone requested a TV series, and I attempted to approve and add them according to my profile.

**Comment by tidusjar** [comment]
Run in the terminal `mono --version`

**Comment by CyberMew** [comment]
The Sonarr version is 2.0.0.4645 - 08 Mar 2017. I can't check mono version for now but I will get back to you on that. Is it possible to add that in the configuration screen too? I have no issues for couch potato and it's running fine.

**Comment by CyberMew** [comment]
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by CyberMew** [comment]
Still happening on the latest stable version 2.2 unfortunately. 

2.2.1591
OS:	Mono
System Version:	4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by camwise** [comment]
I'm also having this same issue.

Sonarr: Version 2.0.0.4645
Ombi: 
Application Version:	2.1.1577
OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview

Error log in cojunction with the one pasted above:

> System.AggregateException: One or more errors occurred. ---> Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=BadRequest for http://127.0.0.1:8989/api/Series?. at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 96 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Ombi.Core.TvSenderOld.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 159 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Ombi.Services.Jobs.FaultQueueHandler.ProcessTvShow(RequestedModel tvModel, SonarrSettings sonarr, SickRageSettings sickrage) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 182 ---> (Inner Exception #0) Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=BadRequest for http://127.0.0.1:8989/api/Series?. at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 96 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Ombi.Core.TvSenderOld.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\TvSenderOld.cs:line 159<---	Ombi.Services.Jobs.FaultQueueHandler	Error	4/3/2017 9:19:45 AM

**Comment by tidusjar** [comment]
Can you guys try the latest EAP?

**Comment by camwise** [comment]
Just updated to EAP 2.2.1607

Looks like I'm getting the same error:

> Ombi.Helpers.Exceptions.ApiRequestException: Got StatusCode=BadRequest for http://127.0.0.1:8989/api/Series?. at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 96 at Ombi.Api.SonarrApi.<>c__DisplayClass9_0.b__1() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 173 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(SonarrAddSeries series, String apiKey, Uri baseUrl) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 173 at Ombi.Core.Tv.TvSenderV2.AddSeries(SonarrSettings sonarrSettings, RequestedModel model, String rootFolderPath, Int32 qualityId) in C:\projects\requestplex\Ombi.Core\Tv\TvSenderV2.cs:line 212 at Ombi.Core.Tv.TvSenderV2.d__13.MoveNext() in C:\projects\requestplex\Ombi.Core\Tv\TvSenderV2.cs:line 121 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.Core.Tv.TvSenderV2.d__12.MoveNext() in C:\projects\requestplex\Ombi.Core\Tv\TvSenderV2.cs:line 90 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Ombi.Core.Tv.TvSenderV2.d__11.MoveNext() in C:\projects\requestplex\Ombi.Core\Tv\TvSenderV2.cs:line 58 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__152.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 1894 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__136.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 1394

**Comment by camwise** [comment]
Also looks like I can't delete anything out of the request fault queue.  "x" delete button isn't working for me.

**Comment by SuperPotatoMen** [comment]
Its look like a local problem. Can you restart sonarr and make a new api key?

**Comment by camwise** [comment]
Found out the problem.  Had to review the logs on Sonarr and it looks like that during the course of some update of Ombi it lost the Quality Profile I had set up under the Sonarr settings.  As soon as I told it to detect Quality profiles and chose my default Sonarr profile everything is working again.
![qualityprofile](https://cloud.githubusercontent.com/assets/7816266/24680334/c412bc36-194d-11e7-833b-170eab10d18d.png)

**Comment by SuperPotatoMen** [comment]
cool!

**Comment by CyberMew** [comment]
I'm still having this problem. Quality profiles are updated. Please add in more debugging log in the next release so I can paste more info. Currently other than the exception error there aren't any other errors.

**Comment by CyberMew** [comment]
Guess I have to start a new issue for this? Please do advise.

**Comment by tidusjar** [comment]
Sorry. I didn't see your previous message. 

Just to recover things, all your settings are up-to-date date and you can pull back all the quality profiles and root rathers back correctly? 

Can you post an image of your settings and blank out the API key?

**Comment by eivl** [comment]
Had the same issue, for me everything worked when i fixed my Quality Profile.

**Comment by CyberMew** [comment]
@tidusjar Sorry for the late response, been very busy. Yes, settings are up-to-date date and I can pull them without issues.

Not sure what is there to show for the settings but here it is: http://imgur.com/AIxY73T

The only related logs are:
Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	6/19/2017 12:40:03 PM
approving request 51	Ombi.UI.Modules.ApprovalModule	Info	6/19/2017 12:40:03 PM

Edit: I enabled trace mode and accepted the tv request. Here are the logs:
Request made to http://192.168.x.x:8989/api/Series? with status code BadRequest. The response was [ { "propertyName": "Path", "errorMessage": "Invalid Path", "formattedMessageArguments": [], "formattedMessagePlaceholderValues": { "propertyName": "Path", "propertyValue": null } }, { "propertyName": "RootFolderPath", "errorMessage": "Invalid Path", "formattedMessageArguments": [], "formattedMessagePlaceholderValues": { "propertyName": "Root Folder Path", "propertyValue": null } } ]	Ombi.Api.ApiRequest	Trace	6/19/2017 12:48:23 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	6/19/2017 12:48:21 PM
Request made to http://192.168.x.x:8989/api/Series? with status code BadRequest. The response was [ { "propertyName": "Path", "errorMessage": "Invalid Path", "formattedMessageArguments": [], "formattedMessagePlaceholderValues": { "propertyName": "Path", "propertyValue": null } }, { "propertyName": "RootFolderPath", "errorMessage": "Invalid Path", "formattedMessageArguments": [], "formattedMessagePlaceholderValues": { "propertyName": "Root Folder Path", "propertyValue": null } } ]	Ombi.Api.ApiRequest	Trace	6/19/2017 12:48:21 PM
{ "addOptions": null, "title": "The Get Down", "seasons": [ { "seasonNumber": 1, "monitored": true, "statistics": null }, { "seasonNumber": 2, "monitored": true, "statistics": null } ], "rootFolderPath": null, "qualityProfileId": 6, "seasonFolder": false, "monitored": true, "tvdbId": 300886, "tvRageId": 0, "cleanTitle": null, "imdbId": null, "titleSlug": "The Get Down", "id": 0, "images": [] }	Ombi.Api.SonarrApi	Debug	6/19/2017 12:48:21 PM
Sonarr API Options:	Ombi.Api.SonarrApi	Debug	6/19/2017 12:48:21 PM
Seasons = [], out of 2 seasons	Ombi.Api.SonarrApi	Debug	6/19/2017 12:48:20 PM
Adding series The Get Down	Ombi.Api.SonarrApi	Debug	6/19/2017 12:48:20 PM
Request
**(there is another trace log here which is apparently showing Ombi pulling ALL my TV shows records?)**
Sending to Sonarr	Ombi.UI.Modules.ApprovalModule	Trace	6/19/2017 12:48:20 PM
approving request 51	Ombi.UI.Modules.ApprovalModule	Info	6/19/2017 12:48:20 PM

**Comment by tidusjar** [comment]
It seems that your default root folder is incorrect. That's the error
coming back from sonarr. That path is what sonarr will use so sonarr needs
to be able to see it correctly
