### ISSUE TITLE
No ombi file

### ISSUE THREAD

**Issue by chrisvdgeld** [tidusjar/Ombi#1304]
#### Ombi Version:

/shrug

#### Update Branch:

??

#### Media Sever:

no

#### Media Server Version:

no

#### Operating System:

ubuntu 16/04

#### Mono Version (only if your not on windows)

4.8.0

```

no logs
```

#### Problem Description:

I've just cloned the latest commit, however I can find no Release folder and/or Ombi.exe?

#### Reproduction Steps:

clone github

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/releases/tag/v2.2.0

**Comment by SuperPotatoMen** [comment]
There are no instructions to close the git. You need to download the zip file
