### ISSUE TITLE
Newsletter does not send when scheduled

### ISSUE THREAD

**Issue by brooklyn11218** [tidusjar/Ombi#1307]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.4.4.3495

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Newsletter does not send. Email notifications and test newsletter go through no problem and the test email reflects the new content added but it doesn't send when scheduled. 

#### Reproduction Steps:

Set cron to send at a scheduled time, wait for said time.

**Comment by SuperPotatoMen** [comment]
logs?

**Comment by brooklyn11218** [comment]
Sorry. The logs didn't show anything so I didn't add them. Here they are.


[logs.zip](https://github.com/tidusjar/Ombi/files/883388/logs.zip)

**Comment by SuperPotatoMen** [comment]
Thanks, what is the setting in our configuration?

**Comment by brooklyn11218** [comment]
which settings do you want? The cron is: 0 0 12 1/1 * ? *

**Comment by brooklyn11218** [comment]
So the newsletter started sending randomly. I don't know what was stopping it but it seems to be working now, so you can mark this closed. If it acts up again I'll be sure to post.
