### ISSUE TITLE
Automatic updates from GUI on Windows 

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#1309]
#### Ombi Version:

V 2.1.1528

#### Update Branch: 
Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Noticed the automatic updates button when I was prompted that there was an update. However, when I click on the button it appears like it is loading but after about 1 minute presents the same page again. No errors in the log. Does this work on Windows?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
See the knowing issue list
