### ISSUE TITLE
Landing page notice before log in danish chars problem

### ISSUE THREAD

**Issue by Microbone** [tidusjar/Ombi#1313]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Debian

#### Mono Version (only if your not on windows)

4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 16:18:35 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Landingpage notice shown before login char set recognition?

I can select Danish under the default language but if I write danish in the notice characters are displayed wrongfully - see screenshot!

http://i.imgur.com/2IqFoKb.png

We use special letters like Æ Ø Å!

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tanjer45** [comment]
Hi buddy! Use this site: http://www.starr.net/is/type/htmlcodes.html

for Æ you should write &Aelig; and for Ø you will write &Oslash;  

If i would write a swedish sentence like "I Love Ombi" i would write, Jag &auml;lskar Ombi"  and it will translate to "Jag älskar Ombi"

**Comment by tidusjar** [comment]
Yeah, use HTML encoding.
