### ISSUE TITLE
Sickrage flat folders

### ISSUE THREAD

**Issue by hjone72** [tidusjar/Ombi#1315]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Plex Server 1.5.1

#### Operating System:

Mono

#### Mono Version (only if your not on windows)

4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

nothing actually appears in the log because the request works and is successful.

```

#### Problem Description:

Recently I've noticed that new shows added to sickrage from Ombi are being added with 'group episodes by season folder' unchecked.
My default settings in SR are set specifying that season folder should be used but all new Ombi shows have the option unticked.

#### Reproduction Steps:

Approve a show that has been requested through Ombi with a SickRage backend.

Happy to help where I can, I turned on the trace logs and could only see some requests for list seasons. I don't have the log anymore and don't have any shows to be added currently.

**Comment by HarryShowerdrain** [comment]
I am having the same problem, it looks like it happened in 2.2.0 as well.

**Comment by DirtyCajunRice** [comment]
Current release v2.2.1 happening on ubuntu 16.04

**Comment by masterxdk** [comment]
Why was this closed? I still got the issue

**Comment by PotatoQuality** [comment]
ehhhh

**Comment by PotatoQuality** [comment]
did take time to see the whole open issue list.

maybe you notice something instead of asking in a very old issue report.

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455

**Comment by hjone72** [comment]
Sorry I didn't come back and update this issue. It isn't anything to do with Ombi.

There was an issue with SickRage that is fixed here: https://github.com/SickRage/SickRage/commit/789d9f2613cf8bea74a302f33b74f745ba57b880

The commit isn't in the main branch yet but should be easy enough to implement in your own setup. :)
