### ISSUE TITLE
[BUG] Failed to obtain Plex libraries  SQLite error

### ISSUE THREAD

**Issue by ajkis** [tidusjar/Ombi#1316]
Latest 2.2 version 

> 2017/03/31 14:18:39.161 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException: SQLite error
> table PlexContent has no column named ItemId

**Comment by SuperPotatoMen** [comment]
Not a bug, pleas delete the plexcontent table and restart  you're ombi settup ;)
