### ISSUE TITLE
cannot auto update to new 2.2

### ISSUE THREAD

**Issue by GitHub010931** [tidusjar/Ombi#1318]
#### Operating System:

Windows 10 x64

#### Problem Description:

I'm trying to upgrade plex requests (ombi) to the newest stable release 2.2, and it doesn't seem to be working. Is there any advice on how to upgrade it? the automatic button doesn't do anything and I don't know how to install it a new version. i used t he NSSM method to have it auto run at startup.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Pleas read the known issue list. You need to download the Zip file, un-zip it and overwrite te files. After that, re-start ombi.

**Comment by GitHub010931** [comment]
How do I restart ombi? And will these overwrite my config file of all my setting if I replace all the files?

Sent from my iPhone

On Mar 31, 2017, at 10:36 AM, SuperPotatoMen <notifications@github.com<mailto:notifications@github.com>> wrote:


Pleas read the known issue list. You need to download the Zip file, un-zip it and overwrite te files. After that, re-start ombi.

**Comment by SuperPotatoMen** [comment]
No when you  overwrite it you don't overwrite your config file. just replace it.

**Comment by tidusjar** [comment]
If you are using the NSSM method, it will be in your Windows Services as Ombi.

You can also do it via the command line
```
net stop Ombi
```

**Comment by GitHub010931** [comment]
amazing, thank you very much!

**Comment by GeezusTx** [comment]
How about Linux? I'v been trying to update for the last two days and nothing works. I tried using the bash script from the wiki and downloading the .zip and extracting it to the ombi directory while ombi was shut down.

**Comment by SuperPotatoMen** [comment]
Best way you can download the zip file manualy and overwrite the files.
