### ISSUE TITLE
cannot disable "advanced search"

### ISSUE THREAD

**Issue by noahruss** [tidusjar/Ombi#1319]
#### Ombi Version:
V 2.2.1591
#### Update Branch:
Stable
#### Media Sever:
Plex 
#### Media Server Version:
1.5.2.3557 
#### Operating System:
Linux Mint 18.1 Serena (cinnamon)
#### Mono Version (only if your not on windows)
4.8.0
#### Problem Description:
cannot disable "advanced search"
#### Reproduction Steps:
I setup a fresh VM to see if it was something with my OS config, but I still can't disable advanced search. It'll let me uncheck it and hit submit but when I come back to that settings page its checked again. Makes searching for TV shows take 30 seconds+. this has been happening for at least 6 weeks (I auto update with cron and the script)

**Comment by SuperPotatoMen** [comment]
Did you search for it first? ;)

https://github.com/tidusjar/Ombi/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20advanced%20search

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/904#issuecomment-271308055
