### ISSUE TITLE
Another custom notifications/newsletter request.

### ISSUE THREAD

**Issue by bobbintb** [tidusjar/Ombi#1320]
I know there are already a few requests for notification customization but I have something different in mind. Or at least I didn't see something similar. This might be better left to Plex or the other programs but I would like more user control over the content in notifications, meaning a user should be able to see a list of all TVs shows in Plex and requests and movie requests and select which ones they want notifications for. The approach would be different between movies and TV because of the 1 and done vs episodic differences. For instance, I know there are a lot of TV shows that only some users care about but I can currently. It would be nice to get an instant SMS or pushbullet notification when when a new episode of only their personally selected shows or movies becomes available.

**Comment by SuperPotatoMen** [comment]
Pleas open a feathub requests
