### ISSUE TITLE
SSO SAML SAML2

### ISSUE THREAD

**Issue by untotren** [tidusjar/Ombi#1321]
Please develop a SAML2 connector.  Emby will hopefully soon have HTTPS so I will be using SSO once they do, I would highly enjoy using SSO for this product as well without creating a hacky jscript solution.
http://saml.xml.org/saml-specifications

**Comment by SuperPotatoMen** [comment]
Since when is this a hacky jscript solution?

**Comment by SuperPotatoMen** [comment]
:/

**Comment by untotren** [comment]
I am not saying anything you made is.  I am saying I would have to make one to get SSO behavior.  I am asking you to implement SSO so I can avoid having to make my hacky solution.  Sorry, maybe I spoke ina  confusing manner.
