### ISSUE TITLE
Unable to start as service with latest Windows 10 Creators Update

### ISSUE THREAD

**Issue by arm3n** [tidusjar/Ombi#1323]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.2.3557

#### Operating System:

Windows 10 1703

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/04/01 11:49:58.349 Ombi.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)```
```
#### Problem Description:

I have been running fine with v2.1.0 and its nssm-created service, but every since I upgraded to Windows 10 Creators Update, the service is now getting paused and won't resume. I have tried re-installing with the latest 2.2 version to no avail.

#### Reproduction Steps:

**Comment by tidusjar** [comment]
Run as admin. Check the FAQ

**Comment by arm3n** [comment]
It's been running as admin since day 1, and I checked it again after upgrading.

**Comment by tidusjar** [comment]
The error is that we cannot reserve the port 3579 because it doesn't have access. It's a permission issue.

**Comment by arm3n** [comment]
Thanks Jamie - I have also posted this on the [Windows 10 forums](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-10-creators-update-startup-and-services/75fe15e1-2015-45ec-a96d-5a0b6598db9a).

**Comment by tidusjar** [comment]
It you take a look at the FAQ there is a section on how you can manually reserve the URL with a console command. It wouldn't need admin permissions then.

**Comment by arm3n** [comment]
Jamie - I tried that as well:

![image](https://cloud.githubusercontent.com/assets/1934272/24581722/e1451a94-16ee-11e7-86f5-2ece8d26e99d.png)

Truly believe something is up with the new Win10 build - no worries though, I have been using this method with success this morning: https://superuser.com/a/198530

**Comment by tidusjar** [comment]
Strange!

**Comment by mrwebsmith** [comment]
arm3n - can you please detail how that link has you running again.. my service is also doing this "paused" only thing.. and i dont quite get the connection to the running the vbs/batch method you linked to...  can you reply here with more detail for others that are also on updated win10s

**Comment by arm3n** [comment]
mrwebsmith - just create ombi.vbs, put it into C:\Users\YOURUSERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
with the following content:
```
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Ombi\Ombi.exe" & Chr(34), 0
Set WinScriptHost = Nothing
```

**Comment by mrwebsmith** [comment]
thanks... managed to figure that out last night but i appreciate the confirmation ;)

**Comment by sekrause** [comment]
Some info for everyone who (like me) arrives at this issue through Google because their service won't start with nssm anymore after upgrading to the Windows 10 Creators Update: It seems that all nssm services won't start in the final version of the Windows 10 Creators Update if they were created with the "Console window" option which is enabled by default:

![nssm](https://cloud.githubusercontent.com/assets/595780/24798099/957a2f3c-1b94-11e7-97fb-ddf34fe546a9.png)

In my case it was a custom service and happened with multiple different services.

There is no need to reinstall the service, you can fix most services by creating the DWORD value AppNoConsole=1 in the registry key `[HKLM\SYSTEM\CurrentControlSet\Services\MyService\Parameters]`.

However, if your service requires a console window I don't know any fix and I also don't know if it's a Windows 10 bug or an intentional change.

**Comment by arm3n** [comment]
Thanks Sebastian, that's something I might try.  However, this does not exclude the existence of a regression in how Windows 10 handles ability to grab ports at startup (as you can see in this [thread ](https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_security/windows-10-creators-update-startup-and-services/75fe15e1-2015-45ec-a96d-5a0b6598db9a)I started).

**Comment by CBers** [comment]
https://forums.ombi.io/viewtopic.php?f=9&t=25
