### ISSUE TITLE
Incorrect API error when connecting to Radarr

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#1325]
#### Ombi Version:

I"m seeing this issue as well on Widnows / EAP ,

Application Version:	2.1.1577

#### Update Branch:

Branch:	Early Access Preview

#### Media Sever:

PLEX PMS

#### Media Server Version:

Version 1.5.2.3557 

#### Operating System:

Windows 10E X64
System Version:	4.0.30319.42000

#### Mono Version (only if your not on windows)

Mono version 4.8.0

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

"Could not connect to Radarr, please check your settings. Exception Message: Got StatusCode=Unauthorized for http://192.168.1.20:7878/radarr/api/system/status."

```

#### Problem Description:

Connection to Radarr (worked in the past - not sure when it stopped working

#### Reproduction Steps:

Settings / Radarr / Test connection

Sonarr works fine.

**Comment by tidusjar** [comment]
Check your API key. It looks like it may have changed.

**Comment by seanvree** [comment]
@tidusjar  ---- AANNND ROGER.  My bad.
