### ISSUE TITLE
Managed plex Users cannot login without password

### ISSUE THREAD

**Issue by kmickeletto** [tidusjar/Ombi#1328]
#### Ombi Version:

V 2.2.1596

#### Update Branch:

development

#### Media Sever:

Plex

#### Media Server Version:

Version 1.5.2.3557
#### Operating System:

Ubuntu 14.04

#### Mono Version

Stable 4.8.0.520

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

When the option 'Require users to login with their passwords' is enabled, local Plex users are not able to login.  There doesn't seem to be an option to set a password for the local users through the Admin page.  I have also tried allowing the user to login with require passwords disabled, but there is no option to set a password there either.

#### Reproduction Steps:

See above.

**Comment by tidusjar** [comment]
Are they administrators?

**Comment by kmickeletto** [comment]
No, these are just standard users in ombi.

I have my kids setup but I don't want them to be administrators.  I do want
them to be able to make requests though.

**Comment by tidusjar** [comment]
You set the local users password when creating them...So of you don't know
the password anymore then i suggest you delete them and recreate

**Comment by kmickeletto** [comment]
Forgive me if I am missing something here.  When I create a local Plex
user, it automatically lists the account in Ombi.  Plex only allows me to
set a pin for the user, no password.

**Comment by SuperPotatoMen** [comment]
What do you mean with a local plex user?  Local plex user doesn't exists.
Only Managed Users and plex user exists.

**Comment by tidusjar** [comment]
Sorry I misunderstood!

So a managed user in Plex cannot log in when you have the require password... Yeah... Good point.

**Comment by kmickeletto** [comment]
Sorry for not being a bit clearer to start with.  Please let me know if you
need anything further.  I'll keep an eye on the dev branch in hopes that
this garners enough demand. :-)

Thanks for your help!

**Comment by mattgphoto** [comment]
Seconding this request/bug... just had a few 'friends' that can access my plex server get imported into Ombi automatically, but there is no way for them to login, or me (as admin) to change their password, even with a valid Plex Auth Token. 

A bit of feedback as well: The new user flow is a bit odd right now, since there IS options for email notifications, but upon creating a new user (NOT imported from plex itself), I'd be forced to send passwords via some other method, instead of them just trying to login, as well as no 'forgot password' link on page so users can't just create their passwords securely.

**Comment by SuperPotatoMen** [comment]
@mattgphoto thats correct. We can't change the password because you need to change it on the site of plex.tv

**Comment by SuperPotatoMen** [comment]
@mattgphoto you can open a feathub request for your feedback. Github is only for bug reports.

**Comment by mattgphoto** [comment]
I understand that @SuperPotatoMen, but that would imply the plex user
authentication is working to begin with. ;-)

Due to the bug listed, this is the flow currently for my auto-imported
users from my plex install into ombi:
None. The user cannot login with their plex.tv password. No option to
change password from admin, nothing. I have a valid plex auth token for
ombi. Let me know if i need to provide more info.

**Comment by tidusjar** [comment]
So regarding this issue,

There is no way for me to send an authentication request to Plex.tv to verify if this user is actually a managed user with the correct PIN. This is currently not possible unless Plex opens up that functionality,

**Comment by kmickeletto** [comment]
Would it be possible to just add a field in Ombi to set an Ombi password?  Ombi detects the user, and then an administrator can provision the user, enter the email address and set the password.

**Comment by mattgphoto** [comment]
So I have to ask then, what is the point of Ombi auto-importing users if those users can't login at all? Not sure if this should be a new ticket or not.

**Comment by Qwatuz** [comment]
If I make a login and password for a user in Ombi before adding the user to my Plex friends list that works. So they will be added two times eventually - once manually and the other automatically with email attached by Ombi once i've added them as friends on Plex.

The only problem is I cannot add them manually after Ombi has automatically added them, thus unable to give or reassign a password.

**Comment by tidusjar** [comment]
@mattgphoto because your **dont** need to enable authentication for Ombi. Users can log in without a password.

@Qwatuz Not sure what you mean

**Comment by Qwatuz** [comment]
@tidusjar I'll give an example:

Username1
Username2

Before adding any friends on Plex, I went into Ombi and added Userername1 in the Account Management and gave them the password "Potato".

Now on Plex I will friend Username1 and Username2.

Username1 can log into Ombi using the password "Potato"  as I made the password before they were Plex friends. Note they are a User and not Admin.

Username2 asks for a password to login with. I try to make one: I cannot, as the user already exists (automatically imported by Ombi). I cannot change or view the current password for Username2.

**Comment by mattgphoto** [comment]
@tidusjar I understand that, unfortunately in my testing, there's no way to login without a password, and additionally, I wouldn't want a public facing website (where my users can make requests) that is open for attack.

**Comment by tidusjar** [comment]
@qwatuz if you are adding Plex friends then they need to log in with their Plex friends accounts.

**Comment by tidusjar** [comment]
@qwatuz if you are adding Plex friends then they need to log in with their Plex friends accounts.

**Comment by Qwatuz** [comment]
@tidusjar is there no way of giving them a custom password for Ombi access, after adding them as a Plex friend? It works before adding them but not after. I'd like to give all users the same easy to remember password.

**Comment by tidusjar** [comment]
I think you might be getting confused with the terms. Plex Friend = Plex User that has their own Plex account that you share your lib with. 

Managed user = Plex Pass feature that allows you to create local users.

**Comment by StevenChorkley** [comment]
+1, local users can't connect.

**Comment by tidusjar** [comment]
@StevenChorkley This issue is closed.

**Comment by StevenChorkley** [comment]
So... you're not going to fix it?

**Comment by tidusjar** [comment]
Please read the whole issue.

**Comment by StevenChorkley** [comment]
I have. 

My managed users can't log in because they haven't got a plex.tv account. That's a huge bug... not a fucking feature request.

**Comment by tidusjar** [comment]
@StevenChorkley If you think this is a bug then please feel free to fix it. This is open source code.

If you are not going to fix it then I suggest you look at the recent issues list and you may see why I am not going to fix this.

You clearly have an problem with my response, so for you I am going to offer you my consultancy rate to help you out with this if you are willing to pay, since this project is maintained and developed in my free time.

**Comment by StevenChorkley** [comment]
I have a problem with your attitude and tone of your response. 

Your answer could've simply been a simple 'yes' or 'no', but your righteous self couldn't handle that.

**Comment by MattJeanes** [comment]
He said this cannot be fixed yet because of Plex api limitations, if you had read the issue you would know that

**Comment by PotatoQuality** [comment]
@StevenChorkley start reading the whole issue before you using that tone.

**Comment by StevenChorkley** [comment]
Pillarks.

**Comment by PotatoQuality** [comment]
@StevenChorkley pleas learn to read....

![image](https://user-images.githubusercontent.com/2944704/28460256-8a5016ce-6e11-11e7-82ce-17af35aa99d1.png)

**Comment by StevenChorkley** [comment]
https://www.urbandictionary.com/define.php?term=manners

**Comment by schmittyd** [comment]
This issue is closed! Move on!
