### ISSUE TITLE
Error Trying to Add Movie to Radarr

### ISSUE THREAD

**Issue by hematic** [tidusjar/Ombi#1329]
Application Version:	2.2.1591
OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Stable
Plex

When trying to add a movie i get a message saying to contact the administrator.

When checking the logs i see the following 

nvalid Path	Ombi.Core.MovieSender	Error	4/2/2017 4:34:52 PM
Invalid Path	Ombi.Core.MovieSender	Error	4/2/2017 4:34:29 PM
System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.PlexUserChecker.Start() in C:\projects\requestplex\Ombi.Services\Jobs\PlexUserChecker.cs:line 73	Ombi.Services.Jobs.PlexUserChecker	Error	3/30/2017 1:42:31 PM
System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 134	Ombi.Api.ApiRequest	Error	3/30/2017 1:42:20 PM

**Comment by SuperPotatoMen** [comment]
Pleas use our issue template. i'm not following the problem over here
