### ISSUE TITLE
IIS Reverse Proxy shows a page without formatting

### ISSUE THREAD

**Issue by xdflames** [tidusjar/Ombi#1330]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

_Windows 8/Windows Server 2012_
I'm actually using Windows Server 2016. Ombi reports this, though.

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

I'll add if required, but nothing in the logs reflects issues I'm having.

```

#### Problem Description:

Using IIS to reverse proxy Ombi so I can use 127.0.0.1/ombi (or similar) to access the page. 
I've tried using the rewrite URL as the following:
http://127.0.0.1:3579/request/{R:1} - This throws a 404 error
http://127.0.0.1:3579/requests/{R:1} - This displays a page that looks like the style sheet didn't load

My web.config

```

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions>
                      <add input="{CACHE_URL}" pattern="^(https?)://" />
                    </conditions>
                    <action type="Rewrite" url="http://127.0.0.1:3579/requests/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_ACCEPT_ENCODING" value="" />
                    </serverVariables>
                </rule>
            </rules>
            <outboundRules>
              <rule name="ReverseProxyOutboundRule1" preCondition="ResponselsHtml1">
                <match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="^http(s)?://127.0.0.1:3579/requests/(.*)" />
                <action type="Rewrite" value="/127.0.0.1:3579/{R:2}" />
              </rule>
              <rule name="RewriteRelativePaths" preCondition="ResponselsHtml1">
                <match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="^/(.*)" negate="false" />
                <action type="Rewrite" value="/127.0.0.1:3579/{R:1}" />
              </rule>
              <preConditions>
                <preCondition name="ResponselsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                </preCondition>
              </preConditions>
            </outboundRules>
        </rewrite>
    </system.webServer>
</configuration>

```

Is it something obvious or am I doing this incorrectly?
#### Reproduction Steps:

N/A

**Comment by SuperPotatoMen** [comment]
We are not supporting reverse proxy on this platform beceause its out of the scope of ombi.

**Comment by tidusjar** [comment]
Actually all I think you need to do is go into the Ombi settings and set the Base Url as `request` and then restart Ombi.

**Comment by xdflames** [comment]
I understood it wasn't an Ombi issue specifically, but was hoping someone had a workaround here, as I'm sure someone has a reverse proxy setup so their friends don't have to remember port numbers. Unfortunately, seems like no one is using IIS. I may give up and switch to Caddy if I don't resolve this tonight.

Changing the Base Url to `request` just brings me to a 404 page whenever I try to access it via 127.0.0.1:3579.

Is it possible to edit this value in a config somewhere or will I need to uninstall and reinstall Ombi to get back to the page?

**Comment by tidusjar** [comment]
Go to: 127.0.0.1:3579/request

**Comment by xdflames** [comment]
Ah. That should've been intuitive. Thanks for your help. If I can get the content to load properly with the Base Url edit tonight I'll leave an edit if anyone else comes across the same problem.

**Comment by tidusjar** [comment]
@xdflames Yeah it should work with the Base URL. I do know some people are running it through IIS, but the majority is either Apache or NGINX

**Comment by xdflames** [comment]
Figured it out. My previous code needed to be edited so Ombi could find the location of the graphics. For example: `href="/ombi/Content/favicon/favicon.ico"` points to an actual location, where as in my code this was pointing to `href="/127.0.0.1:3579/ombi/Content/favicon/favicon.ico"` which didn't load anything.
 In my research I thought that 

```
            <outboundRules>
              <rule name="ReverseProxyOutboundRule1" preCondition="ResponselsHtml1">
                <match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="^http(s)?://127.0.0.1:3579/requests/(.*)" />
                <action type="Rewrite" value="/127.0.0.1:3579/{R:2}" />
              </rule>
              <rule name="RewriteRelativePaths" preCondition="ResponselsHtml1">
                <match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="^/(.*)" negate="false" />
                <action type="Rewrite" value="/127.0.0.1:3579/{R:1}" />
              </rule>
              <preConditions>
                <preCondition name="ResponselsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                </preCondition>
              </preConditions>
            </outboundRules>
```
Was required but it isn't, simply removing this fixed my problem.

So, in short:
web.config
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions>
                      <add input="{CACHE_URL}" pattern="^(https?)://" />
                    </conditions>
                    <action type="Rewrite" url="http://127.0.0.1:3579/ombi/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_ACCEPT_ENCODING" value="" />
                    </serverVariables>
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```
Where `<action type="Rewrite" url="http://127.0.0.1:3579/BASE_URL/{R:1}" />` BASE_URL reflects whatever you made it in Ombi settings, in my case I want it to go to Ombi instead of requests.
@tidusjar Thanks for pointing me in the right direction. I feel dumb not having realized this sooner, since all I had to do was inspect the page in Chrome..

I'll definitely support Ombi in the future!
