### ISSUE TITLE
Emby Connect Users not logging on

### ISSUE THREAD

**Issue by animosity22** [tidusjar/Ombi#1331]
#### Ombi Version:

2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Emby

#### Media Server Version:
```

Application Version:	2.2.1591
OS:	Mono
System Version:	4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 16:18:35 UTC 2017)
Branch:	Stable
Log Level:	Error
Database Location:	/data/Ombi/Ombi.sqlite
Running Directory:	/
```

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/04/02 21:18:46.565 Ombi.UI.Modules.UserLoginModule Debug: Need to auth
2017/04/02 21:18:46.613 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True
2017/04/02 21:18:54.286 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2017/04/02 21:19:07.874 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2017/04/02 21:21:10.253 Ombi.UI.Modules.UserLoginModule Debug: Need to auth
2017/04/02 21:21:10.278 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = True
2017/04/02 21:21:17.333 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2017/04/02 21:22:25.586 Ombi.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass

```

#### Problem Description:
I have a few users that are setup as guests to my Emby server. If I try to have them login (one is my wife so we're sure the password is right), it never lets them on. I have a "user" on the Emby server that works fine.
#### Reproduction Steps:

I've tried wiping out the sqlite and starting from scratch. I have a reverse proxy (apache) and I've tried directly to the Ombi server without the proxy as well.

**Comment by animosity22** [comment]
To add some more detail, it seems to be the difference between "User" and "Guest".

I have only 1 user on the system and that account can login in fine. If I try to use a guest that authenticates via Emby Connect, that fails.

**Comment by animosity22** [comment]
Looks to fixed via a server side patch coming up:

https://emby.media/community/index.php?/topic/46504-local-vs-connect-login/

**Comment by tidusjar** [comment]
OK thanks for the investigation into this! I'll close this since it's not a direct ombi issue (it's still searchable)
