### ISSUE TITLE
Plex Cloud not syncing with Ombi

### ISSUE THREAD

**Issue by Na3blis** [tidusjar/Ombi#1338]
#### Ombi Version:

V 2.2.1591 (LinuxServer Docker Container)

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Plex Cloud

#### Operating System:

Docker Container for Ombi

#### Mono Version (only if your not on windows)

Docker Container

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher
	
Error	4/4/2017 1:31:58 AM

System.InvalidOperationException: There is an error in XML document (0, 0). ---> 
System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw 
(System.Exception e) <0x401abbc0 + 0x000a3> in :0 at 
System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) <0x401ab730 + 
0x0006f> in :0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () <0x4048a3d0 + 
0x0062b> in :0 at System.Xml.XmlTextReaderImpl.Read () <0x404837e0 + 0x00067> in :0 at 
System.Xml.XmlTextReader.Read () <0x404837c0 + 0x0001a> in :0 at 
System.Xml.XmlReader.MoveToContent () <0x40483670 + 0x00084> in :0 at 
Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexMetadata.Read12_Med
iaContainer () <0x401a2840 + 0x00027> in :0 at (wrapper managed-to-native) 
System.Reflection.MonoMethod:InternalInvoke 
(System.Reflection.MonoMethod,object,object[],System.Exception&) at 
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, 
System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo 
culture) <0x4047c940 + 0x000a3> in :0 --- End of inner exception stack trace --- at 
System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, 
System.String encodingStyle, XmlDeserializationEvents events) <0x401865d0 + 0x007f3> in :0 at 
System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, 
System.String encodingStyle) <0x40186530 + 0x0007f> in :0 at 
System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) 
<0x40186120 + 0x0008f> in :0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) 
<0x40137750 + 0x000b3> in :0	Ombi.Api.ApiRequest


```

#### Problem Description:

Ombi not showing content as available that is already in Plex

#### Reproduction Steps:

Grabbed plex cloud url from CPMS. When I test connectivity it says it connected.

**Comment by romancin** [comment]
Same error here with docker vontainer installed yesterday:

Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	14/04/2017 3:33:56
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexMetadata.Read12_MediaContainer () [0x00008] in <8d9bc77d24624affb06d8a0922d2a04f>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <2a63c45e97a245c1bf3c2df5f23972c5>:0

This container is linked to a Plex Cloud Instance. Users are working correctly from plex, but not libraries.

Another container is working perfectly linked to a local instance of plex.

**Comment by PotatoQuality** [comment]
Pleas revoke the authorization from ombi in plex.  and re-add it in ombi.

After that, can you run a test connection with the plex server?

**Comment by romancin** [comment]
Done, plex connection stablished successfully again. I will update this when checker passes again. Thank you!

**Comment by romancin** [comment]
Still failing :(

Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	14/04/2017 8:39:18
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexMetadata.Read12_MediaContainer () [0x00008] in <8d9bc77d24624affb06d8a0922d2a04f>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <2a63c45e97a245c1bf3c2df5f23972c5>:0

**Comment by Na3blis** [comment]
Was this actually fixed?

**Comment by romancin** [comment]
Not for me...

**Comment by bulbajackel** [comment]
Looks like it was closed in preparation for ombi v3. Check out #1455

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
