### ISSUE TITLE
Radarr Minimum Availibility option missing causing radarr to not fetch release on approval when negative delay is set in Availibilty Delay

### ISSUE THREAD

**Issue by nilleiz** [tidusjar/Ombi#1341]
#### Ombi Version:

V.2.2.1607

#### Update Branch:

Early Access Preview/

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Ombi has no option for minimum Availabilty in Radarr settings. That is no problem until you set a negative amount of days for delay unter Settings > Indexers > Availibilty Options > Availibility Delay
If set to default (0) releases are fetched on approval as expected.

#### Reproduction Steps:

- Set "Settings > Indexers > Availibilty Options > Availibility Delay" to a negative value (eg. -14)
- Configure Radarr in Ombi
- Request and approve a movie (movie is added with blank "Min Availibilty" value)
- see Radarr log for error: 
"DownloadDecisionMaker"
Couldn't evaluate decision on "<Release>" , with spec: AvailabilitySpecification: Der addierte oder subtrahierte Wert ergibt eine nicht darstellbare DateTime.
Parametername: value

**Comment by SuperPotatoMen** [comment]
This is a feature request. Its correct that ombi has no option for minimum Availibility.
In Radarr setting  Default settings in radarr is web when we don't send a minimum Availibility.

**Comment by SuperPotatoMen** [comment]
See also: https://github.com/Radarr/Radarr/issues/740
