### ISSUE TITLE
Couchpotato and Radarr both stuck on enabled.

### ISSUE THREAD

**Issue by michaeljbiro** [tidusjar/Ombi#1342]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

FreeNAS jail

#### Mono Version (only if your not on windows)

4.6.2.7

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm trying to replace Couchpotato with Radarr. Both are showing up as enabled, but requests aren't getting through to Radarr. Whenever I try to disable CP, I get the error "Cannot have Radarr and CouchPotato both enabled." and if I try to disable Radarr I get the error "CouchPotato is enabled, we cannot enable Radarr and CouchPotato". Possibly related to #970?

#### Reproduction Steps:

Enable CP then radarr?

**Comment by SuperPotatoMen** [comment]
If you disable cp first. Is that possible?

**Comment by michaeljbiro** [comment]
Nope. Right now they are both enabled and I get an error no matter which I try to disable.

**Comment by michaeljbiro** [comment]
Just an update, I ended up reverting to a backup. After making sure CP was disabled, I re-added the radarr config and now it works.

**Comment by SuperPotatoMen** [comment]
cool :+1:

**Comment by matty87a** [comment]
im seeing the same thing and unfortunately have no backup if theres any other ideas

**Comment by tidusjar** [comment]
That's strange. 

I'll add some code in to allow you to disable them. 

But for now what you can do is open the Ombi. sqlite file in SQLite Browser and open the global settings table and delete the Couch Potato setting there. Then restart Ombi

**Comment by xyber411** [comment]
> But for now what you can do is open the Ombi. sqlite file in SQLite Browser and open the global settings table and delete the Couch Potato setting there. Then restart Ombi

I did this, but now I have an error.  Could someone without CP filled out, please post the original empty contents of the field?
