### ISSUE TITLE
Omby (Docker Image) cannot connect to Plex (Synology package)

### ISSUE THREAD

**Issue by mattgphoto** [tidusjar/Ombi#1344]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.3.3580 

#### Operating System:

Docker/Synology DSM

#### Mono Version (only if your not on windows)

Not sure?

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.UriFormatException: Invalid URI: The hostname could not be parsed. at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x00090] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at System.Uri..ctor (System.String uriString) [0x00017] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at System.UriBuilder..ctor (System.String uri) [0x0009d] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 at Ombi.Helpers.UriHelper.ReturnUriWithSubDir (System.String val, System.Int32 port, System.Boolean ssl, System.String subDir) [0x00000] in :0 at Ombi.Core.SettingModels.ExternalSettings.get_FullUri () [0x00025] in <0188546a066c4e9a950cdc0c8b71cba2>:0 at Ombi.UI.Modules.ApplicationTesterModule.PlexTest () [0x0006e] in <53d13059badb4287a75f78f06561872e>:0	Ombi.UI.Modules.ApplicationTesterModule	Warn	4/5/2017 10:35:28 PM
Exception thrown when attempting to get Plex's status:	Ombi.UI.Modules.ApplicationTesterModule	Warn	4/5/2017 10:35:28 PM

```

#### Problem Description:

When trying to connect to my Plex installation (The plex package is installed directly on the Synology), Ombi (installed in a Docker image) does not want to connect to the internal hostname or the internal IP of the Plex installation, which IS reachable via browser at the Synology's internal IP:
http://192.168.10.15:32400/web/

Not sure what other URL I could put here?

#### Reproduction Steps:

1. In Synology DSM Package Manager, install Plex (Go through Plex set up, etc)
2. In DSM, install Docker
3. Download Ombi image in Docker, deploy
4. Access Ombi via default port on internal IP of synology
5. Go through set up
6. Once set up, login as Admin, go to Settings, Plex
7. Try to set the base URL as what you know it is reachable as via browser.

**Comment by SuperPotatoMen** [comment]
the error says it already: System.UriFormatException: Invalid URI: **_The hostname could not be parsed._**

Pleas post a printscreen of your Plex Settings in the admin panel

**Comment by mattgphoto** [comment]
![vivaldi_2017-04-05_15-47-09](https://cloud.githubusercontent.com/assets/26942853/24730243/580421f4-1a17-11e7-934a-c25f809c3b58.png)

My apologies! Here you go. It is reachable (I just had a friend test from outside world) via
http://sfo.netstacked.com:32505/web 

(The hostname above resolves to the 67... ip)

**Comment by mattgphoto** [comment]
Unless you were referring to this:
![vivaldi_2017-04-05_16-41-00](https://cloud.githubusercontent.com/assets/26942853/24731432/d05fab62-1a1e-11e7-8fe9-919eb67ce7df.png)

(plex.netstacked.com also resolves to the same public IP)

**Comment by SuperPotatoMen** [comment]
Well that is your problem. You have two config errors over there. 

First of all, why are there two IP adress on the "plex hostname or IP"?  The files is only for 1 IP not for 2 or 3. 

Second: that is not a base URL. Pleas make that field empty.

**Comment by SuperPotatoMen** [comment]
You need only a base URL if plex is behind a proxy server. 
(see the wiki for more information)

**Comment by mattgphoto** [comment]
@SuperPotatoMen Sorry about the multiple IP's, it filled it in by default, wasn't sure if I needed to change that or not. Here's what I get now if I follow the instructions you mentioned:
![vivaldi_2017-04-05_17-21-35](https://cloud.githubusercontent.com/assets/26942853/24732237/81d9cd82-1a24-11e7-9556-9490fa195d19.png)

And this is the info from logs:
`System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexStatus.Read4_MediaContainer () [0x00008] in <166182bc8af54a1ab4a5298c28da039d>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/6/2017 12:23:14 AM`

**Comment by mattgphoto** [comment]
My apologies, looks like all is good now, followed the tip by @thurman86 in this thread:
https://github.com/tidusjar/Ombi/issues/1072

And was connecting to external port, not internal. Thank you guys!
