### ISSUE TITLE
No longer loading as a service / service after Win10 Creators Update

### ISSUE THREAD

**Issue by Kinematic9** [tidusjar/Ombi#1353]
#### Ombi Version:

V 2.20

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10 Creator update (final)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I had ombi configured and working perfectly, ran the creators update and now receive an error/crashing when loading Ombi.
Ombi: Unexpected status SERVICE_PAUSED in response to START control.

#### Reproduction Steps:

I have tried reinstalling, removing the service, redownloading and unlocking the zip, fresh installing service and everything again, but the service will no longer start. I run the exe and get a UAC notice, hit yes and it says:

Starting Up! Please wait, this can usually take a few seconds.
Version: 2.2.1591
Location of the database: C:\Ombi\Ombi.sqlite
no configuration section <common/logging> found - suppressing logging output
Ombi is running on the following: http://+:3579/
All setup, Ombi is now ready!
Press any key to exit

Hitting keys does not exit it. This only happened after I loaded up after the Creators update.

**Comment by Kinematic9** [comment]
As an update, if I run Ombi.exe normally, hit YES for the UAC and leave the CMD prompt running, it will load. If I close CMD, it will not work. It does not load at all on start either anymore in the background.

**Comment by delphiactual** [comment]
You need to remove the old service and readd it again.

https://www.htpcguides.com/install-plex-requests-net-windows-system-service/

**Comment by Kinematic9** [comment]
Hi Delphiactual, I've removed the service totally from my system using CMD (sc delete Ombi..). It was removed and no longer showing in services.msc. Restarted, did a full FRESH Ombi install. I have it running now but only if I keep the CMD window open. It shows status "Paused" in the Services section, startup type is Automatic.

If I totally stop it and restart it, I get the following:

Windows could not start the Ombi service on Local Computer.
Ther service did not return an error. This could be an internal Windows
error or an internal service error.
If the problem persists, contact your system administrator.

**Comment by delphiactual** [comment]
How did you create the service?

**Comment by Kinematic9** [comment]
I used the previous linked instructions..nssm. Let me run it through again from scratch after removing from command line again and will report back

**Comment by Kinematic9** [comment]
So I went into an admin CMD, used the 'sc delete Ombi' and had it removed. Restarted and it was gone from services.
Everything is fine until I nssm start Ombi, see attached:
![untitled](https://cloud.githubusercontent.com/assets/26988920/24782590/2bea2560-1b15-11e7-92cc-4095a69f22d2.png)

**Comment by delphiactual** [comment]
dir c:\ombi

**Comment by Kinematic9** [comment]
Okay - I received the list on the cmd

**Comment by delphiactual** [comment]
I want to see it

**Comment by Kinematic9** [comment]
Sorry, pasted it above

**Comment by delphiactual** [comment]
Only thing I see is that during your nssm executions you did not close the quotes, for
nssm install Ombi "C:\Ombi\Ombi.exe"
nssm set Ombi AppDirectory "C:\Ombi"

**Comment by Kinematic9** [comment]
Deleted service, restarted, added it all again through the walkthrough with closing all the quotes and I still receive the SERVICE_PAUSED issue.

Double clicked the Ombi.exe and it loads up fine, but still have to keep that cmd window open and it doesn't auto start.

Right clicked Ombi.exe and checked off run as admin.

Ombi in the Services.msc is still showing 'Paused' and automatic startup, even though it's running in the CMD window / accessible through my browser now only when it is open.

**Comment by delphiactual** [comment]
You'll have to wait for @tidusjar or @SuperPotatoMen. That's all my knowledge on the service...

**Comment by Kinematic9** [comment]
Thank you for helping though Delphiactual, I appreciate it

**Comment by toconquer** [comment]
Having this same issue with Ombi, PlexPy, and nginx, all created with NSSM.

**Comment by Kinematic9** [comment]
My PlexPy was not affected at all with the Windows 10 update I ran (literally the only thing that changed). That still runs and starts, everything is fine with that. Ombi is the only thing I now have to manually run and open, it will not set as a service / run properly.

**Comment by toconquer** [comment]
@Kinematic9 , did you create a service for PlexPy using NSSM?

**Comment by Kinematic9** [comment]
@toconquer I used the 2nd method using Git Gui on the installation page:
https://github.com/JonnyWong16/plexpy/wiki/Installation

I did not use NSSM for anything other than Ombi

**Comment by toconquer** [comment]
@Kinematic9 
On further investigation, this appears to be related to the app and NOT NSSM.
SABnzbd which uses NSSM also is loading properly via service.
PlexPy, Ombi, and nginx are not.

**Comment by Kinematic9** [comment]
@toconquer I am not too too technical, so I appreciate looking into it. Does this mean that something changed when we upgraded windows and now Ombi is no longer working properly/wait for an update?

**Comment by Kinematic9** [comment]
I noticed that there is an issue starting services that try and connect to ports.. see article here down a bit
http://windowsreport.com/windows-10-creators-update-bugs/

**Comment by SuperPotatoMen** [comment]
Guys, can you start Ombi without using nssm? We need to know If its a naam issue or Ombi issue. 

Pleas en ombi.exe with admin rights

**Comment by tidusjar** [comment]
It's a windows 10 issue
