### ISSUE TITLE
Plex Availability Cacher not finding requests that need to be updated

### ISSUE THREAD

**Issue by burkasaurusrex** [tidusjar/Ombi#1355]
#### Ombi Version:

V 2.2.1591

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

V 1.5.3.3580

#### Operating System:

Windows 8

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Requests that will be updated count 0	Ombi.Services.Jobs.PlexAvailabilityChecker	Debug	4/7/2017 2:03:08 AM

```

#### Problem Description:

I have several series that I have added to Sonarr using Ombi, and after they have finished downloading, they are never marked as available. Every time I force run Plex Availability Cacher, I get the same response (even with trace logs enabled): Requests that will be updated count 0. I have deleted the Plex Content table from the sqlite database and restarted twice. I haven't received any other errors.

#### Reproduction Steps:

Add new series, force run Plex Availability Cacher

**Comment by SuperPotatoMen** [comment]
I see the same problem, after the cacher is running and the checks run the tv show doesn't marked for availabled.

I see this problem with when i request a All tv show. 
What kind of requests did you make? Season, last season, all?

**Comment by burkasaurusrex** [comment]
I've only tested it in request all seasons for TV show

**Comment by SuperPotatoMen** [comment]
Okay, looks like a bug. Tagged for bug

**Comment by qazero** [comment]
I'm having the same issue but it's also effecting grabs of selected episodes and season as well. Any update?

**Comment by tidusjar** [comment]
@qazero There is no update. This will be resolved in the new version Ombi v3
