### ISSUE TITLE
Allow suppress of searching a plex instance

### ISSUE THREAD

**Issue by the4ndy** [tidusjar/Ombi#136]
I would like to use Plex Requests but I do not want the requirement of having to tie it to my Plex server. As of current the users get an error that it cannot properly search the plex server. Is there a way to suppress this error and allow the requests to be submitted anyway? Is this something that I perhaps could implement myself (albeit I am not a very experienced programmer)? Let me know if its something i can be pointed in the direction of or if it is something you guys / gals can help with. Thanks.

**Comment by tidusjar** [comment]
Why wouldn't you want it to check your Plex server? 
Yeah it's something we can configure.

**Comment by the4ndy** [comment]
I dont want to add undo work for you, I would perhaps be willing to take a crack at doing it myself if you could point me in the right direction (though I have no .NET programming experience sadly). Its not that I do not want it to check my plex server, its more that I do not want it to HAVE to check the plex server (for example if it were offline / down, not responding, not on the same network perhaps, etc). Also, I do not have a "good" working version of plex running yet, but I would like to start fielding requests from family members as i build out my home network. Again, no extra work meant for you, i do understand that I may be somewhat alone in this request

**Comment by the4ndy** [comment]
UPDATE: The meteor version of plex requests does not seem to have the "search through plex" feature at all...which is cool for you guys being ahead of the curve i guess. It also seems like the .NET version is a bit smoother, but i think i need to just adjust some VM settings. Either way, for now, my particular issue is resolved, still think it would be a cool on/off toggle for the search through plex feature, but its entirely up to you guys, obviously. Thanks again!

**Comment by tidusjar** [comment]
I agree. It would be a good idea.

**Comment by curlz620** [comment]
Basically this would allow people to use Plex Requests even if they were not running plex. believe it or not some people use other programs like Media Server? I think thats what its called. idk.

**Comment by tidusjar** [comment]
I agree.

**Comment by Drewster727** [comment]
Another popular one is kodi - we could potentially add support for that. This would take some re-working, not to mention the potential name change?

**Comment by PotatoQuality** [comment]
i have talked to Jamie. for now we don't make this. But in the feature it will be possible to make a local users only settup.
