### ISSUE TITLE
Ombi API key usage

### ISSUE THREAD

**Issue by Cerothen** [tidusjar/Ombi#1360]
Good Day,

I was hoping for a quick guide on how I would use the API to authenticate a user with a username and password. Also if doing this would trickle through to emby/plex

Thanks,

**Comment by tidusjar** [comment]
Hello the API doesn't support that functionality. But i am rewriting it all

**Comment by shadowswan** [comment]
Will this work in v3?

**Comment by PotatoQuality** [comment]
See wiki. Its there

**Comment by PotatoQuality** [comment]
:)

**Comment by shadowswan** [comment]
Doh!

So I should be able to pass through a logon from something else like organizr and save the user logging on again?
