### ISSUE TITLE
Staggered Login is slow and annoying

### ISSUE THREAD

**Issue by kamikasky** [tidusjar/Ombi#1367]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu Linux

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I've been using Ombi for a quite a while (since it was called PlexRequests!) and I find it an essential part of my server setup. However, ever since the login style changed I've found it very annoying and cumbersome to use. I understand it is in place for login without a password or for manual users, but please give us an option. Not only does the staggered login take additional time—if works horrible on mobile devices and breaks autofill/login functionality. Please consider changing it back or giving options for types of login prompts.

#### Reproduction Steps:

Login

**Comment by PotatoQuality** [comment]
Pleas open a feature requests because now its by design ;)
