### ISSUE TITLE
Requests not showing as fulfilled and no emails sent to requestor when file added

### ISSUE THREAD

**Issue by antigravity83** [tidusjar/Ombi#1369]
#### Ombi Version:

V 2.2.1

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.3.3580

#### Operating System:

Windows 10

#### Applicable Logs (from /logs/ directory or the Admin page):
2017/04/11 00:14:40.567 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/04/11 00:14:41.497 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = False 
2017/04/11 00:15:07.504 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/04/11 00:21:23.232 Ombi.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles 
2017/04/11 00:21:23.232 Ombi.Core.Setup Info: Begin executing GetProfiles call to CouchPotato for quality profiles 
2017/04/11 00:21:24.899 Ombi.Core.Setup Error: Failed to cache CouchPotato quality profiles! System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal(String key, Object value, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.AddOrGetExisting(CacheItem item, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.Add(CacheItem item, CacheItemPolicy policy)
   at Ombi.Helpers.MemoryCacheProvider.Set(String key, Object data, Int32 cacheTime) in C:\projects\requestplex\Ombi.Helpers\MemoryCacheProvider.cs:line 114
   at Ombi.Core.Setup.CacheCouchPotatoQualityProfiles(ICacheProvider cacheProvider) in C:\projects\requestplex\Ombi.Core\Setup.cs:line 180
2017/04/11 00:21:24.915 Ombi.Core.Setup Error: Failed to cache Sonarr quality profiles! System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal(String key, Object value, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.AddOrGetExisting(CacheItem item, CacheItemPolicy policy)
   at System.Runtime.Caching.MemoryCache.Add(CacheItem item, CacheItemPolicy policy)
   at Ombi.Helpers.MemoryCacheProvider.Set(String key, Object data, Int32 cacheTime) in C:\projects\requestplex\Ombi.Helpers\MemoryCacheProvider.cs:line 114
   at Ombi.Core.Setup.CacheSonarrQualityProfiles(ICacheProvider cacheProvider) in C:\projects\requestplex\Ombi.Core\Setup.cs:line 138
2017/04/11 00:21:27.916 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/04/11 00:21:29.275 Ombi.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107 System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107
2017/04/11 00:21:29.400 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/04/11 00:21:29.435 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/04/11 00:21:29.463 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 0 
2017/04/11 00:21:29.510 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/04/11 00:21:29.603 Ombi.Services.Jobs.PlexContentCacher Debug: Done movies 
2017/04/11 00:21:29.697 Ombi.Services.Jobs.PlexContentCacher Debug: Done TV 
2017/04/11 00:21:29.791 Ombi.Services.Jobs.PlexContentCacher Debug: Done albums 
2017/04/11 00:21:29.869 Ombi.Services.Jobs.PlexContentCacher Debug: Did not find any libraries in Plex. 
2017/04/11 00:23:19.234 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/04/11 00:23:19.664 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = False 
2017/04/11 00:23:49.493 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/04/11 00:26:27.614 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 

#### Problem Description:

When a file is requested and subsequently added- Ombi 

1. Doesn't detect that the file has been added to the library when request fulfilled
2. Even when manually selecting "Mark Available" no email is sent to the user advising that their request has been completed

#### Reproduction Steps:

Here are some examples of what I have done. I've created a test account and requested some content. As an admin, I've then gone in and added the content. 

- Request Added Notification turned on for test user http://imgur.com/a/Tr9ZK
- Email notifications turned on and email settings added correctly. http://imgur.com/ufOTx5a
- When added, Ombi doesn't detect the show as "Available". Here is an example of a show that is fully downloaded and has been for over 8 hours http://imgur.com/veBGArZ
- Even when manually selecting "Mark Available", nothing is sent to the user. I did it with the following show with a test account. No emails received by it http://imgur.com/VGUdkSY
- Confirming that Sonarr is connected correctly http://imgur.com/VGUdkSY
- Show completely added in Sonarr https://imgur.com/a/ZGc2R

**Comment by PotatoQuality** [comment]
Thanks for you reporting in your issue.


1. Ombi doesn't scan files. We just caching the libary of your plex server.
Pleas make sure Ombi Plex Cacher and after that the Plex Availability Cacher.


2. Hi, can you printscreen your configuration of your email settings and place it here?

You deleted the most important question from our help format: **"Applicable Logs (from /logs/ directory or the Admin page):"**.
Can you pleas edit your issue report above and update it with logs?
(in the feature, pleas don't delete our help format).

Before you getting you logs best way to generate it is to set your log level temporary on Debug.
Save the setting and go back to your email settings, run the email test button and copy past your logs in your mean issue.

**Comment by antigravity83** [comment]
Hi thanks for the response- thank you for the software btw, it's excellent :)

Apologies for not including logs, I hadn't set them up when I did my post.

1. I've left the default settings for Ombi Plex Cacher and Plex Availability Cacher
http://imgur.com/a/CylGl

Although I don't have Episode Searching in Plex enabled do I need to do this?

2. Here are my Gmail settings- test email and newsletter test works OK
http://imgur.com/a/f5oYB. 

3. I changed logs to Debug, went to email settings, ran the test email, got success. But the log file doesn't show any of this action (have pasted in the original post)

My main issue though seems to be the fact that Ombi isn't picking up any additions of content in Plex. Do I need to have Episode Searching enabled for this to occur?

Thanks again

**Comment by antigravity83** [comment]
Logs added. Thanks

**Comment by antigravity83** [comment]
Update- email seems to work now. It could have been related to Chrome auto saving the login password, and trying to use it in the Email Settings Password field - seems to override it even though I saved the email password and tested ok.

Main issue now is Ombi not auto detecting added content. Any help with that would be great.

Otherwise, it's a perfect piece of kit- thank you very much :)

**Comment by PotatoQuality** [comment]
@antigravity83 nice,

Can you change your caching settings to the following thing:

Ombi Plex Cacher 60 minuts
Plex Availability Cacher 62 minuts.


Can you config plex in your admin panel?

Something is wrong with the returning data from plex:

**2017/04/11 00:21:29.869 Ombi.Services.Jobs.PlexContentCacher Debug: Did not find any libraries in Plex.**

**Comment by antigravity83** [comment]
@PotatoQuality 

Thanks. By re-config I'm guessing you mean re type username and password and request new Plex Token and Machine ID? 

I changed the Plex Cache settings to this- is that what you mean?

![capture](https://cloud.githubusercontent.com/assets/27241813/24903031/7a2765c0-1eef-11e7-8e9c-bed6969119e6.PNG)

**Comment by antigravity83** [comment]
I've made those changes, and restarted the service. Here are the new logs:

New Request emails are working now- just not seeing any "Request Added to Library" emails.

2017/04/11 09:50:29.033 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/04/11 09:50:29.110 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/04/11 09:50:29.232 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/04/11 09:50:29.289 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/04/11 09:50:29.314 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/04/11 09:50:29.342 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 2 
2017/04/11 09:50:30.684 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/04/11 09:50:30.747 Ombi.Services.Jobs.PlexContentCacher Debug: Done movies 
2017/04/11 09:50:32.195 Ombi.Services.Jobs.PlexContentCacher Debug: Done TV 
2017/04/11 09:50:32.239 Ombi.Services.Jobs.PlexContentCacher Debug: Done albums 
2017/04/11 09:51:07.994 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/04/11 09:51:08.949 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = False 
2017/04/11 09:51:11.090 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session.

**Comment by PotatoQuality** [comment]
That is looking good. Can you restart Ombi and delete the Requests on Requests page? Pleas request something to check of its fix. (mail will be send after a houd because the system checks every hou If its completed)

**Comment by antigravity83** [comment]
Ok great thanks will check it and report back.

**Comment by antigravity83** [comment]
Hi there,

Made those changes- gave it 12 hours or so, and unfortunately no email notifications for completed requests.

For example, I added Bosch with a test user after making the previous changes. 12 hours later, Bosch is listed as complete in Plex and Sonarr, but still shows as "Processing Request" in the Requests section.

Here are the updated logs

**Comment by antigravity83** [comment]
Hi @PotatoQuality - any updates on this one?

Thanks

**Comment by PotatoQuality** [comment]
There is just one day past? I didn't know Ombi is a payed service

**Comment by antigravity83** [comment]
Sorry- I wasn't sure what your normal turnaround is for issues.

No intention to offend. Ombi is great!

**Comment by tidusjar** [comment]
Looks like there could possibly be a bug when trying to find TV Shows. It's unusual though that it didn't find it at all.

The request is also ALL seasons, do in Sonarr do you have ALL seasons?

But when marking as available manually we do send a notification.

**Comment by antigravity83** [comment]
Hi thanks,

Yeah all seasons are complete in both Sonarr and Plex. 

When marking manually an email does get sent yes, it's just not auto detecting when a show is complete.

**Comment by antigravity83** [comment]
Just wondering whether I should change to the early access version? Will that help this issue?

**Comment by tidusjar** [comment]
@antigravity83 Not currently, i've made no changes around this area yet.

**Comment by enz1ey** [comment]
Is there a reason this was closed? I have the same issue, requests are added to Ombi and sent to Sonarr successfully, however even days after they've been downloaded and added to Plex, they're still marked as "processing" in Ombi.

**Comment by bulbajackel** [comment]
The issue was closed in prep for V3. Check out issue #1455

**Comment by enz1ey** [comment]
Roger that! Thanks
