### ISSUE TITLE
Unable to log into OMBI with a HOME user

### ISSUE THREAD

**Issue by rjsears** [tidusjar/Ombi#1370]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

#### Media Sever:

Plex

#### Media Server Version:

1.5.4.3596

#### Operating System:

Ubuntu 16.04.2 LTS

#### Mono Version (only if your not on windows)

Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):

https://pastebin.com/T8xUswfz

#### Problem Description:

Unable to log in with any of my HOME users. These are users that DO NOT have plex.tv accounts (such as my kids, family, wife) that log into plex by clicking on their name and entering a 4-digit pin. 

These users do show up in the Ombi user management screen.

Dev console in Chrome is getting this error:

https://pastebin.com/GE6Apm2B

#### Reproduction Steps:

Create a HOME user in Plex, attempt to log into OBMI using that user. 

PLEX = > Settings => Users => => My Home => Add User

**Comment by PotatoQuality** [comment]
I guess you mean management users? 

See https://github.com/tidusjar/Ombi/issues/1328

**Comment by rjsears** [comment]
Don't know - Jamie asked me to open a bug on this so I did :-)
