### ISSUE TITLE
When marking movie as Unavailable, a "Denied" email is sent to requestor

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#1371]
#### Ombi Version:

V 2.2.1676

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

A "Denied" email is sent to user after marking a request as Unavailable. Instead, no email should be sent.

#### Reproduction Steps:

Have a request that is marked as Available. Click the Mark Unavailable button, an email stating that the request was denied is sent to the requesting user.

**Comment by tidusjar** [comment]
Fixed in EAP.
