### ISSUE TITLE
Managed Plex Users with PIN can't login.

### ISSUE THREAD

**Issue by vingesus** [tidusjar/Ombi#1373]
**Ombi Version:**

V 2.2.1

**Update Branch:**

Stable

**Media Sever:**

Plex

**Media Server Version:**

1.5.4.3596

**Operating System:**

Windows 10

**Applicable Logs (from `/logs/` directory or the Admin page):**

N/A

**Problem Description:**

My managed users on Plex with PIN gets imported to Ombi. However, they are not able to login since they need a password. The PIN as password doesn't work, and I'm not able to assign a password to them manually, since they are imported from Plex.

**Reproduction Steps:**

1. Make some Managed Users on Plex with PIN as login.
2. Get them imported to Ombi.
3. Now they have no password, and aren't able to login on Ombi.

**Comment by PotatoQuality** [comment]
Ombi doesn't support Managed users. The api of plex doesn't support it to login a user.
