### ISSUE TITLE
Sonarr not connecting

### ISSUE THREAD

**Issue by mattya802** [tidusjar/Ombi#1375]
#### Ombi Version: 

2.2.1694

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

There has been an API exception when getting the Sonarr Series	Ombi.Api.SonarrApi	Error	4/12/2017 10:01:31 PM
Failed to cache Sonarr quality profiles!	Ombi.Core.Setup	Error	4/12/2017 9:58:29 PM
Request made to with status code 0. The response was	Ombi.Api.ApiRequest	Trace	4/12/2017 9:31:42 PM

```

#### Problem Description:

I can not get "Test connectivity" or requests to Sonarr to work. I was previously on 2.1 and upgraded to 2.2 EAP and still no luck. API key is correct and I've done a fresh install of Sonarr. 

![ombi](https://cloud.githubusercontent.com/assets/27392465/24987227/c53d2c06-1fcc-11e7-92cc-fbda45363608.PNG)

**Comment by tidusjar** [comment]
What happens when your press the Get Quality?

Are you running Sonarr inside a reverse proxy?

**Comment by mattya802** [comment]
When pressing Get Quality Profiles it says "Something went wrong" and leaves nothing in the log.

Sonarr is running on my main PC, Ombi is running on my web server with nginx installed. I have the root / domain pointed to Ombi which is running directly on my web server.

To note, CouchPotato is setup the same way and is working fine. Thanks.

**Comment by mattya802** [comment]
When pressing Get Quality Profiles it says "Something went wrong". 
Sonarr is running on my main PC, Ombi is running on my web server with nginx installed. I have the root / domain pointed to Ombi which is running directly on my web server.

**Comment by tidusjar** [comment]
Is Sonarr behind a proxy?

If so you need to fill in the base url.

**Comment by mattya802** [comment]
To note, CouchPotato is setup the exact same way and working fine.

**Comment by mattya802** [comment]
No. Here is my Sonarr setup:
![ombi](https://cloud.githubusercontent.com/assets/27392465/25011844/b77cac66-203c-11e7-8f98-545d4959e38b.PNG)

**Comment by tidusjar** [comment]
There is something different about your setup as it works fine for me and everyone else.

Any idea?

**Comment by mattya802** [comment]
I'm brand new to Web servers/nginx/Ombi, so it's possible, but unlikely as the setup is very basic. It seems pretty straightforward. Ombi on Server A is pointing to Sonarr on Server B. 

I'll double check to make sure I can even ping the Sonarr port on server B from server A. It appears Ombi isnt even trying, as the log says "Request made to ______ (blank)."

**Comment by mattya802** [comment]
I'll try a fresh Ombi install too when I get home.

**Comment by mattya802** [comment]
I apologize for wasting your time - Port 8989 was being blocked by Windows Firewall.

**Comment by tidusjar** [comment]
Glad you sorted it!
