### ISSUE TITLE
Newsletter not complete 

### ISSUE THREAD

**Issue by CBers** [tidusjar/Ombi#1376]
#### Ombi Version:

V 2.2.1962

#### Update Branch:

development

#### Media Sever:

Emby

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm still not getting all content added to Emby listed in the email. As mentioned before, I also have the nuVue app (http://nuvueapp.com/) installed on my phone and that also sends an email listed new content on Emby and its always correct.

I know you said previously about items having the correct IDs etc, but if nuVue can do it without them, why can't Ombi?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What type of content is now showing?

**Comment by CBers** [comment]
I would say mainly TV shows/episodes, but sometimes movies.

**Comment by Shiroihige** [comment]
I am also having an issue with the newsletter being incomplete.  However mine only displays movies and not episodes.  

In my logs I have about a million of this error
`System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) <0x41e13430 + 0x000a3> in :0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) <0x41591f60 + 0x0006f> in :0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () <0x416473d0 + 0x0062b> in :0 at System.Xml.XmlTextReaderImpl.Read () <0x416407e0 + 0x00067> in :0 at System.Xml.XmlTextReader.Read () <0x416407c0 + 0x0001a> in :0 at System.Xml.XmlReader.MoveToContent () <0x41640670 + 0x00084> in :0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () <0x41586200 + 0x00027> in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41639940 + 0x000a3> in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, XmlDeserializationEvents events) <0x408aef80 + 0x007f3> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) <0x408aeee0 + 0x0007f> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) <0x408aead0 + 0x0008f> in :0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) <0x40862270 + 0x000b3> in :0`

**Comment by CBers** [comment]
Just received an email saying that a TV show was now available, but it said on PLEX, not in EMBY

Hi there!
Ombi: Prison Break is now available!
Hello! You requested Prison Break on Ombi! This is now available on **Plex**! :)

**Comment by dejected1** [comment]
i'm having the same problem. when i was on the stable branch the newsletter would only send out new movies and brand new tv shows that weren't already in plex. New tv episodes of existing tv shows already in plex never showed up. I then moved to EAP. Now it sends new tvs episodes for existing shows only if i manually run the plex scheduled jobs then manually force the email to be generated from scheduled jobs immediately afterwards. It doesn't detect any new tv show episodes on its own.  The log does shows the newsletter being generated each time it's supposed to but it never finds any content. Movies do get added to the newsletter still correctly.
