### ISSUE TITLE
Windows 10 Creator Update Issues

### ISSUE THREAD

**Issue by DereckR** [tidusjar/Ombi#1377]
#### Ombi Version:

Ombi v2.2.1

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows 10 x64 Creators Update

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
No Logs to provide

```

#### Problem Description:

NSSM.exe for running the services have seemed to stop compatibility. Service sits as paused can't start it. Tried fresh install of Ombi same result. I can run Ombi from the command prompt fine.

#### Reproduction Steps:
None

**Comment by PotatoQuality** [comment]
Ombi works fine. 
Nssm.exe is not a Ombi program so we can't support it ;-)

**Comment by PotatoQuality** [comment]
But there is a fix for nssm: https://github.com/tidusjar/Ombi/issues/1323
