### ISSUE TITLE
Requested episodes are added to Sonarr as unmonitored

### ISSUE THREAD

**Issue by FluffMe** [tidusjar/Ombi#1378]
#### Ombi Version:

V 	2.2.1694

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby

#### Media Server Version:

3.2.12.0

#### Operating System:

Ubuntu 16.04.2 LTS

#### Mono Version (only if your not on windows)

4.6.2

#### Sonarr Version

2.0.0.4689

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

{ "addOptions": { "ignoreEpisodesWithFiles": true, "ignoreEpisodesWithoutFiles": true, "searchForMissingEpisodes": false }, "title": "Oz", "seasons": [ { "seasonNumber": 1, "monitored": false, "statistics": null }, { "seasonNumber": 2, "monitored": false, "statistics": null }, { "seasonNumber": 3, "monitored": false, "statistics": null }, { "seasonNumber": 4, "monitored": false, "statistics": null }, { "seasonNumber": 5, "monitored": false, "statistics": null }, { "seasonNumber": 6, "monitored": false, "statistics": null } ], "rootFolderPath": "/home/dex/Videos/Requested/Series/", "qualityProfileId": 2, "seasonFolder": false, "monitored": true, "tvdbId": 70682, "tvRageId": 0, "cleanTitle": null, "imdbId": null, "titleSlug": "Oz", "id": 0, "images": [] }

```

#### Problem Description:

If request contains only couple of episodes (episodes 1, 2 from the season 1 in this example) the show is added to Sonarr, but all the episodes and seasons are unmonitored. Tried this on several shows, happens with all of them.

#### Reproduction Steps:

1) Search > TV Shows > Find a new TV show (not included in Sonarr or Emby libraries)
2) Request > Select episode... > check episodes 1, 2 > Request
3) Success message, but episodes in Sonarr are unmonitored

**Comment by PotatoQuality** [comment]
Hi, i'm not following your question. Only the requested episodes will be monitored. Other request wil lbe unmonitored beceause you didn't request it ;-)

**Comment by FluffMe** [comment]
Hi! 

The problem is that even the requested episodes are not marked as monitored. Nothing is :(

**Comment by PotatoQuality** [comment]
That sounds like a bug.

Thanks for reporting in.

@tidusjar  can you look at this one? I don't see in the json a requests to download a episode

**Comment by NielsjeNL** [comment]
+1. Just had the same thing happen. Requested a few episodes from a TV show, checked Sonarr, and the episodes weren't being monitored.

**Ombi version:** 2.2.1
**Log:**
>{ "addOptions": { "ignoreEpisodesWithFiles": true, "ignoreEpisodesWithoutFiles": true, "searchForMissingEpisodes": false }, "title": "And Then There Were None", "seasons": [ { "seasonNumber": 1, "monitored": false, "statistics": null } ], "rootFolderPath": "/media/shows/", "qualityProfileId": 7, "seasonFolder": true, "monitored": true, "tvdbId": 299855, "tvRageId": 0, "cleanTitle": null, "imdbId": null, "titleSlug": "And Then There Were None", "id": 0, "images": []

**Comment by tidusjar** [comment]
Strange, seems to be working as expected on my end. Requested Episodes 1 & 2

![image](https://cloud.githubusercontent.com/assets/6642220/25074022/c64b7082-22ea-11e7-908e-2862cf761099.png)

**Comment by FluffMe** [comment]
Still the same behaviour for me. 
http://fluffme.ru/cap/0416amoqg.png
Could it be connected to different quality profiles? I might experiment on those.

**Comment by tidusjar** [comment]
If someone could mess around and see if they can get any further information that would be excellent,

**Comment by FluffMe** [comment]
Tried to mess up with different Sonarr settings in Ombi, including base URL, quality rofiles and paths - nothing helps.

Switched to trace log and tried to add a show again. After a bunch of tvmaze requests and before giant sonarr requests there is a line

`Episode db info is not available.`
by Ombi.Services.Jobs.EmbyAvailabilityChecker

Nothing else out of the ordinary.

**Comment by qazero** [comment]
Any update regarding this? I'm experiencing the same issue...

**Comment by tidusjar** [comment]
@qazero There is no update. This will be resolved in the new version Ombi v3

**Comment by rv10guy** [comment]
For me this seems to happen when the Series is not in Sonarr to begin with. If the series is in Sonarr then it marks it fine. If the series is not, it adds the series but does not set the specified episodes as monitored. At least this is how it seems to be for me.

**Comment by williamwoelke** [comment]
I see the same issue. For example, I don't have Game of Thrones. I add an episode, and the show is added to Sonarr, but no episodes are monitored. I delete the request in Ombi and re-request the episode, then it is marked as monitored.

**Comment by PotatoQuality** [comment]
Guys, This will be resolved in the new version Ombi v3.

**Comment by PlexPower** [comment]
Hi all. I still have this problem the V3.0.4256. How can i fix that. 

Thx all.

**Comment by unfeomateo** [comment]
I have always had this problem. 

3.0.4256
