### ISSUE TITLE
Ombi incorrectly runs search when requesting specific season

### ISSUE THREAD

**Issue by Shiroihige** [tidusjar/Ombi#1382]
#### Ombi Version:

V 2.2.1694

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

1.5.5.3634

#### Operating System:

Docker container

#### Mono Version (only if your not on windows)

Docker container

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
No log entries

```

#### Problem Description:

When adding a tv show by specific season, Ombi will not follow this guideline when adding it to sonarr.

I requested season 3 of a show, and while it only set season 3 in sonarr to be monitored, it ran a search for season 2, season 3 and the first episode of season 1.

#### Reproduction Steps:

Request a specific season for a show, ombi sets monitored status correctly in sonarr, but still runs sonarr's season search for some seasons, and ran a search for the pilot

**Comment by Shiroihige** [comment]
Just checked sonarr again, and it looks like it set the monitored status of the seasons correctly, but all the episodes in each season that it set to unmonitored are still monitored.

**Comment by PotatoQuality** [comment]
But maybe its a sonarr bug and not a Ombi bug ;-)

**Comment by Shiroihige** [comment]
I dunno.  If I manually change a season's monitored status in sonarr it will change all episodes in the that season as well.

**Comment by tidusjar** [comment]
Is this an existing series or did Ombi add it?

**Comment by Shiroihige** [comment]
I just tested it again with another series and the results were the same.  Both times it was a new series being added by Ombi.  

The requested series was added to sonarr by ombi, and the season requested was set to monitored, and all other season set to unmonitored.  However every episode in the none requested season were still set to monitored.

**Comment by tidusjar** [comment]
But the episodes being monitored doesn't matter, there is a sort of monitored hierarchy from lowest to highest:

Episode > Season > Series.

If the Episodes are monitored but the season is not, it does not matter. 

So what's the issue here?

**Comment by Shiroihige** [comment]
Sonarr runs search and downloads seasons for ones that are requested.  If say I request season 9 of a show in Ombi, sonarr then turns around and does a search for every season in the show instead of just one.  I was pointing out the monitored episodes because the failure to set episodes in the non-requested season to unmonitored seems to be the reason for why sonarr will run a search for those seasons.

**Comment by tidusjar** [comment]
Just did some investigation into this and not sure if it's a problem with how I am using the API or at Sonarr's end.

Just logged an issue on the Sonarr github. https://github.com/Sonarr/Sonarr/issues/1852

**Comment by ajp69** [comment]
I am getting the exact same issue running in mono on stable branch.  If Omni adds a series it will add to sonarr and mark what I want as monitored correctly but it downloads every episode no matter.

I added into the bad lands and selected only season 2 it did that and season 1 was unmonitored but still downloaded all of season 1.

**Comment by ajp69** [comment]
I added seinfeld and it selected season 1, it added and downloaded all 9 seasons.

**Comment by weirdcrap** [comment]
Just experienced this as well. On the latest stable branch (2.2.1678). 

One of my users requested the latest season of My Little Pony: Friendship is magic which airs tonight. Ombi added the series to sonarr, only season 7 is set to monitored but all the individual episodes under all of the other unmonitored seasons got marked as monitored and have started downloading.

Here is excerpt from sonarr log
'
17-4-22 17:04:18.2|Info|AddSeriesService|Adding Series [212171][My Little Pony: Friendship is Magic] Path: [/tv/My Little Pony- Friendship is Magic]
17-4-22 17:04:18.2|Info|RefreshSeriesService|Updating Info for My Little Pony: Friendship is Magic
17-4-22 17:04:19.0|Info|RefreshEpisodeService|Starting episode info refresh for: [212171][My Little Pony: Friendship is Magic]
17-4-22 17:04:19.0|Info|RefreshEpisodeService|Finished episode refresh for series: [212171][My Little Pony: Friendship is Magic].
17-4-22 17:04:19.1|Info|DiskScanService|Scanning disk for My Little Pony: Friendship is Magic
17-4-22 17:04:19.1|Info|DiskScanService|Completed scanning disk for My Little Pony: Friendship is Magic
17-4-22 17:04:19.1|Info|SeriesScannedHandler|[My Little Pony: Friendship is Magic] was recently added, performing post-add actions
17-4-22 17:04:19.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
17-4-22 17:04:19.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
17-4-22 17:04:19.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
17-4-22 17:04:19.2|Info|ExistingExtraFileService|Found 0 extra files
17-4-22 17:04:19.3|Info|EpisodeSearchService|Performing missing search for 146 episodes
17-4-22 17:04:19.4|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S01]
17-4-22 17:04:19.4|Info|MediaCoverService|Downloading Fanart for [212171][My Little Pony: Friendship is Magic] http://thetvdb.com/banners/fanart/original/212171-15.jpg
17-4-22 17:04:19.6|Info|MediaCoverService|Downloading Banner for [212171][My Little Pony: Friendship is Magic] http://thetvdb.com/banners/graphical/212171-g.jpg
17-4-22 17:04:19.6|Info|MediaCoverService|Downloading Poster for [212171][My Little Pony: Friendship is Magic] http://thetvdb.com/banners/posters/212171-5.jpg
17-4-22 17:04:43.1|Info|DownloadDecisionMaker|Processing 318 releases
17-4-22 17:04:47.7|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E19.A.Dog.and.Pony.Show.PROPER.720p.WEB-DL.DD5.1.h.264-ETP ] to the queue.
17-4-22 17:04:47.8|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E19.A.Dog.and.Pony.Show.PROPER.720p.WEB-DL.DD5.1.h.264-ETP 
17-4-22 17:04:48.6|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.Is.Magic.S01E01.Friendship.Is.Magic.Part.1.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:04:50.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E02.Friendship.Is.Magic.Part.2.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:04:50.2|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E02.Friendship.Is.Magic.Part.2.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:04:51.7|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E03.The.Ticket.Master.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:04:52.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E03.The.Ticket.Master.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:04:54.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E04.Applebuck.Season.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:04:54.2|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E04.Applebuck.Season.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:11.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E05.Griffon.the.Brush-off.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:11.3|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E05.Griffon.the.Brush-off.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:16.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E06.Boast.Busters.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:16.8|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E06.Boast.Busters.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:18.8|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E07.Dragonshy.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:18.9|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E07.Dragonshy.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:26.9|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E11.Winter.Wrap.Up.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:27.9|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E11.Winter.Wrap.Up.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:31.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E12.Call.of.the.Cutie.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:31.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E12.Call.of.the.Cutie.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:33.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E14.Suited.for.Success.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:33.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E14.Suited.for.Success.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:35.5|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E15.Feeling.Pinkie.Keen.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:35.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E15.Feeling.Pinkie.Keen.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:40.0|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E16.Sonic.Rainboom.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:40.1|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E16.Sonic.Rainboom.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:43.4|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E17.Stare.Master.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:43.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E17.Stare.Master.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:48.8|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E18.The.Show.Stoppers.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:49.1|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E18.The.Show.Stoppers.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:05:57.4|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E24.Owls.Well.That.Ends.Well.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:05:57.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E24.Owls.Well.That.Ends.Well.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:06:00.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E25.Party.of.One.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:06:00.8|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E25.Party.of.One.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:06:05.5|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S01E26.The.Best.Night.Ever.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:06:05.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S01E26.The.Best.Night.Ever.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:06:06.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E08.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:06.3|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E08.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:08.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E09.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:13.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E09.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:14.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E10.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:14.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E10.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:16.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E13.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:16.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E13.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:18.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E20.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:18.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E20.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:20.9|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E21.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:21.0|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E21.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:22.7|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E22.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:23.0|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E22.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:24.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S01E23.WEB-RIP.720p.NL.AAC.2.0-mHD] to the queue.
17-4-22 17:06:24.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S01E23.WEB-RIP.720p.NL.AAC.2.0-mHD
17-4-22 17:06:24.6|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S02]
17-4-22 17:06:50.3|Info|DownloadDecisionMaker|Processing 286 releases
17-4-22 17:08:37.2|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. My.Little.Pony.Friendship.is.Magic.S02.720p.WEB-DL.DD5.1.H.264-YayPonies

[v2.0.0.4689] System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse (System.Net.WebRequest request) [0x00002] in <9d687fb9c46d481292a78781773c6116>:0 

17-4-22 17:08:40.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E01.The.Return.of.Harmony.Part.1.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:40.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E01.The.Return.of.Harmony.Part.1.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:08:41.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E02.The.Return.of.Harmony.Part.2.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:41.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E02.The.Return.of.Harmony.Part.2.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:08:46.9|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E03.Lesson.Zero.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:49.2|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E03.Lesson.Zero.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:08:51.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E04.Luna.Eclipsed.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:51.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E04.Luna.Eclipsed.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:08:53.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E05.Sisterhooves.Social.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:53.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E05.Sisterhooves.Social.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:08:56.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E06.The.Cutie.Pox.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:08:58.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E06.The.Cutie.Pox.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:00.8|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E07.May.the.Best.Pet.Win.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:09:01.1|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E07.May.the.Best.Pet.Win.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:02.1|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E08.The.Mysterious.Mare.Do.Well.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:09:02.2|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E08.The.Mysterious.Mare.Do.Well.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:04.0|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E09.Sweet.and.Elite.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:09:04.3|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E09.Sweet.and.Elite.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:07.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E10.Secret.of.My.Excess.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:09:07.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E10.Secret.of.My.Excess.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:08.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.Is.Magic.S02E11.Hearths.Warming.Eve.720p.WEB-DL.DD5.1.h.264-ETP] to the queue.
17-4-22 17:09:08.8|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.Is.Magic.S02E11.Hearths.Warming.Eve.720p.WEB-DL.DD5.1.h.264-ETP
17-4-22 17:09:10.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E12.1080p-DarkMorford] to the queue.
17-4-22 17:09:10.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E12.1080p-DarkMorford
17-4-22 17:09:12.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E13.1080p-DarkMorford] to the queue.
17-4-22 17:09:16.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E13.1080p-DarkMorford
17-4-22 17:09:17.5|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E14.1080p-DarkMorford] to the queue.
17-4-22 17:09:17.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E14.1080p-DarkMorford
17-4-22 17:09:19.4|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E15.1080p-DarkMorford] to the queue.
17-4-22 17:09:19.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E15.1080p-DarkMorford
17-4-22 17:09:21.4|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E16.1080p-DarkMorford] to the queue.
17-4-22 17:09:21.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E16.1080p-DarkMorford
17-4-22 17:09:24.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E17.1080p-DarkMorford] to the queue.
17-4-22 17:09:24.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E17.1080p-DarkMorford
17-4-22 17:09:26.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E18.1080p-DarkMorford] to the queue.
17-4-22 17:09:26.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E18.1080p-DarkMorford
17-4-22 17:09:28.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E19.1080p-DarkMorford] to the queue.
17-4-22 17:09:28.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E19.1080p-DarkMorford
17-4-22 17:09:30.4|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E20.1080p-DarkMorford] to the queue.
17-4-22 17:09:30.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E20.1080p-DarkMorford
17-4-22 17:09:32.2|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E21.1080p-DarkMorford] to the queue.
17-4-22 17:09:32.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E21.1080p-DarkMorford
17-4-22 17:09:34.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E22.1080p-DarkMorford] to the queue.
17-4-22 17:09:34.6|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E22.1080p-DarkMorford
17-4-22 17:09:36.6|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E23.1080p-DarkMorford] to the queue.
17-4-22 17:09:36.8|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E23.1080p-DarkMorford
17-4-22 17:09:38.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E24.1080p-DarkMorford] to the queue.
17-4-22 17:09:38.5|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E24.1080p-DarkMorford
17-4-22 17:09:40.5|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E25.1080p-Obfuscated] to the queue.
17-4-22 17:09:40.7|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E25.1080p-Obfuscated
17-4-22 17:09:42.3|Info|Nzbget|Adding report [My.Little.Pony.Friendship.is.Magic.S02E26.1080p-DarkMorford] to the queue.
17-4-22 17:09:42.4|Info|DownloadService|Report sent to NZBGet. My.Little.Pony.Friendship.is.Magic.S02E26.1080p-DarkMorford
17-4-22 17:09:42.4|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S03]
17-4-22 17:10:10.3|Info|DownloadDecisionMaker|Processing 76 releases
17-4-22 17:10:11.7|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.Is.Magic.S03.720p.WEB-DL.DD5.1.AAC2.0.H.264-BTN
17-4-22 17:10:11.9|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S04]
17-4-22 17:10:56.4|Info|DownloadDecisionMaker|Processing 212 releases
17-4-22 17:10:56.6|Info|RssSyncService|Starting RSS Sync
17-4-22 17:11:00.3|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.is.Magic.S04.720p.WEB-DL.DD5.1.H.264-BS
17-4-22 17:11:00.5|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S05]
17-4-22 17:11:08.6|Info|DownloadDecisionMaker|Processing 200 releases
17-4-22 17:11:10.0|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
17-4-22 17:11:42.7|Info|DownloadDecisionMaker|Processing 378 releases
17-4-22 17:11:49.8|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.is.Magic.S05.720p.WEB-DL.DD5.1.H.264-iT00NZ
17-4-22 17:11:50.1|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S06]
17-4-22 17:12:25.6|Info|DownloadDecisionMaker|Processing 921 releases
17-4-22 17:12:41.0|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.is.Magic.S06.720p.WEB-DL.DD5.1.H.264-iT00NZ
17-4-22 17:12:41.3|Info|NzbSearchService|Searching 8 indexers for [My Little Pony: Friendship is Magic : S07]
17-4-22 17:12:53.1|Info|DownloadDecisionMaker|Processing 53 releases
17-4-22 17:12:54.5|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.is.Magic.S07E01.Celestial.Advice.720p.WEB-DL.DD5.1.H.264-iT00NZ
17-4-22 17:12:56.6|Info|DownloadService|Report sent to rTorrent. My.Little.Pony.Friendship.is.Magic.S07E02.All.Bottled.Up.720p.WEB-DL.DD5.1.H.264-iT00NZ
17-4-22 17:12:56.6|Info|EpisodeSearchService|Completed missing search for 146 episodes. 58 reports downloaded.
'

**Comment by PotatoQuality** [comment]
Sonarr team is looking into it how we can fix this problem

**Comment by ltjdym** [comment]
same problem here

**Comment by ethanopp** [comment]
+1

**Comment by lattedesu** [comment]
Having same issue as well.

A friend of mine requested a specific season of a TV show, but instead of that specific season, all seasons and episodes are started to being downloaded. Using latest versions as of today along with mono on Debian Jessie.

**Comment by PotatoQuality** [comment]
Its a sonarr bug. Reporting that you have the same problem is logic :P

**Comment by lattedesu** [comment]
I'm not using a docker container, so I posted since my build is a little bit different. Also, the issue wasn't closed back when it was realized it was a sonarr bug, so :P

**Comment by smakdafrog** [comment]
@PotatoQuality 

> PotatoQuality commented on May 16
Its a sonarr bug. Reporting that you have the same problem is logic :P

I'm experiencing this issue currently, do you have a thread referencing that its a sonarr bug?  Any news on when it will be patched/fixed/acknowledged?

**Comment by weirdcrap** [comment]
Read the thread: https://github.com/Sonarr/Sonarr/issues/1852

**Comment by smakdafrog** [comment]
> The sonarr bug was posted up above: Sonarr/Sonarr#1852

I see that it was acknowledged, and a fix was implemented here:
http://github.com/Sonarr/Sonarr/commit/5aa02eb15c9c57953b5f8c68b59cc7058c2ff3cc

I'm using a Docker with Unraid, how do I implement this change?  Or am I waiting for an updated docker version to get released with the included changes?  Newbie at this :/

Thanks for your help!

**Comment by weirdcrap** [comment]
I also use UnRAID. If you are using the LSIO docker for Sonarr they rebuild the dockers weekly. Sonarr's latest release was back in may so if you have been keeping your containers up to date then you should have had the fix for a while now.

In Sonarr under System > Updates does it say  "2.0.0.4753 - May 12 2017  Installed"?

**Comment by smakdafrog** [comment]
Version
2.0.0.4753
Mono Version
5.0.1.1
It is the LSIO docker.
LIke you said, the update should be there, but I'm still experiencing the issue described in the bug above.  I can try out the developer branch I guess.

**Comment by weirdcrap** [comment]
According to the [commit log](https://github.com/Sonarr/Sonarr/commits?author=markus101) the fix wasn't even committed until May 24th, after 2.0.0.4753 was already released. If you need the fix now you will most likely need to hop on the development branch.

Do some reading on the Lime-Technology forums, I believe LSIO recommends against enabling the built-in mechanism for updates. IIRC it can cause issues if they rebase the image and your docker container has had updates applied through the built-in updater that haven't yet made it into the base image for the docker.

**Comment by smakdafrog** [comment]
I'll toggle on that Develop branch in Sonarr, see how that works and change it back to Master after another release hits.  I'll continue to look around the forums, even though each time I do its going down a different rabbit hole :P

Still fairly new to Dockers and GitHub, pretty overwhelming at first when you don't know what to look for, so thank you for all your help and advise!
