### ISSUE TITLE
Suddenly can not log in

### ISSUE THREAD

**Issue by tymanthius** [tidusjar/Ombi#1385]
#### Ombi Version:

V 3.0.1701 (Downloaded update 4/15/2017)

#### Update Branch:

Early Access Preview

#### Media Sever:

Emby Version 3.2.12.5 beta

#### Operating System:

Debian 8 in a container on proxmox

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)

#### Reproduction Steps:

I couldn't log in with any users this morning, and there had been an update out for a few days, so I updated. Still can't log in.

This is running on the same container as Sonarr & Radarr, and both of those are working fine.

The only changes I recall off hand are there was a mono update recently, and I switched from PFSense to Sophos for my router software.

**Comment by PotatoQuality** [comment]
Version V 3.0.1701 doesn't exists

**Comment by PotatoQuality** [comment]
Try to login with your local Ombi account

**Comment by tymanthius** [comment]
I did - same issue.  Basically, I type in a username, and click login, or hit enter, and nothing happens.

As to version #, I don't know how to get it if I can't log in. that was the number off the latest update. That's why I was so specific as to when I downloaded.

If there's a file I can look at in my /opt/Ombi folder I'll check it.  I have both the old version and the current in seperate folders.

**Comment by tidusjar** [comment]
Any logs
?

**Comment by tymanthius** [comment]
Total log from the 'new' install:

2017/04/15 15:03:02.097 Ombi.Services.Jobs.EmbyContentCacher Error: Failed to obtain Emby libraries System.NullReferenceException: Object reference not set to an instance of an
 object                                                                                                                                                                         
  at Ombi.Services.Jobs.EmbyContentCacher.GetMovies () [0x00029] in <c7c05fd7a9f9459abda6adc32680a541>:0                                                                        
  at Ombi.Services.Jobs.EmbyContentCacher.CachedLibraries (Ombi.Core.SettingModels.EmbySettings embySettings) [0x00019] in <c7c05fd7a9f9459abda6adc32680a541>:0                 
2017/04/15 15:04:02.036 Ombi.Services.Jobs.EmbyUserChecker Error: System.NullReferenceException: Object reference not set to an instance of an object                           
  at Ombi.Services.Jobs.EmbyUserChecker.Start () [0x0006a] in <c7c05fd7a9f9459abda6adc32680a541>:0  System.NullReferenceException: Object reference not set to an instance of an
 object                                                                                                                                                                         
  at Ombi.Services.Jobs.EmbyUserChecker.Start () [0x0006a] in <c7c05fd7a9f9459abda6adc32680a541>:0                                                                              
2017/04/15 15:13:02.220 Ombi.Services.Jobs.EmbyEpisodeCacher Error: System.NullReferenceException: Object reference not set to an instance of an object                         
  at Ombi.Services.Jobs.EmbyEpisodeCacher.CacheEpisodes (Ombi.Core.SettingModels.EmbySettings settings) [0x00022] in <c7c05fd7a9f9459abda6adc32680a541>:0                       
  at Ombi.Services.Jobs.EmbyEpisodeCacher.Execute (Quartz.IJobExecutionContext context) [0x00027] in <c7c05fd7a9f9459abda6adc32680a541>:0  System.NullReferenceException: Object
 reference not set to an instance of an object                                                                                                                                  
  at Ombi.Services.Jobs.EmbyEpisodeCacher.CacheEpisodes (Ombi.Core.SettingModels.EmbySettings settings) [0x00022] in <c7c05fd7a9f9459abda6adc32680a541>:0                       
  at Ombi.Services.Jobs.EmbyEpisodeCacher.Execute (Quartz.IJobExecutionContext context) [0x00027] in <c7c05fd7a9f9459abda6adc32680a541>:0

**Comment by tidusjar** [comment]
I'm lost, so you cannot log in right?

Who are you logging in as? Local account or Emby account?

Is there any error in the browser console? (F12)

**Comment by tymanthius** [comment]
Can not log in with Emby admin account, Emby regular user account or local admin account.

Here's what the console shows:

www.google-analytics.com/r/collect?v=1&_v=j50&a=43234817&t=pageview&_s=1&dl…id=1695348705&cid=185963988.1491705848&tid=UA-77083919-2&_r=1&z=1157732895 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
userlogin:1 Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined
    at chrome-extension://gabdloknkpdefdpkkibplcfnkngbidim/content.min.js:9:4405
    at chrome-extension://gabdloknkpdefdpkkibplcfnkngbidim/content.min.js:8:1741
userlogin/login Failed to load resource: net::ERR_NAME_NOT_RESOLVED
userlogin:179 Objectabort: function (a)always: function ()complete: function ()done: function ()error: function ()fail: function ()getAllResponseHeaders: function ()getResponseHeader: function (a)overrideMimeType: function (a)pipe: function ()progress: function ()promise: function (a)readyState: 0responseJSON: undefinedsetRequestHeader: function (a,b)state: function ()status: 0statusCode: function (a)statusText: "error"success: function ()then: function ()__proto__: Object
userlogin/login Failed to load resource: net::ERR_INTERNET_DISCONNECTED
userlogin:179 Object

**Comment by tidusjar** [comment]
regarding this: `userlogin:1 Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined`

can you click on that and then press the "Preview" tab?

**Comment by tymanthius** [comment]
I don't see a preview tab.  I'm in chrome.

**Comment by tidusjar** [comment]
Sorry. if you click the right hand side of the error e.g. where it states `1385:1`

![image](https://cloud.githubusercontent.com/assets/6642220/25067381/c19b7dfe-2239-11e7-96d1-a1cf28417cef.png)

**Comment by tymanthius** [comment]
Ok, I clicked and then widened that section of screen to show as much as possible.  Not sure this is what you want:

![ombi](https://cloud.githubusercontent.com/assets/3689380/25132801/53b43686-2410-11e7-8975-930953ada6cf.PNG)


Sorry I took so long, was out of town the last cpl days.

**Comment by tidusjar** [comment]
So you can press the little red X in the top right in your screenshot?

**Comment by tymanthius** [comment]
Updated after pressing the X I highlighted & circled in red.
![capture](https://cloud.githubusercontent.com/assets/3689380/25140483/211be384-2426-11e7-8f58-627b9c460573.PNG)

**Comment by tymanthius** [comment]
And what did I press that closed this?  That was a mistake!

**Comment by tidusjar** [comment]
One last thing, in the bottom where the error.message is. 

Can you click on user login:1 ?

**Comment by tymanthius** [comment]
I did that, but nothing seemed to change. Which seems odd to me.

**Comment by tymanthius** [comment]
FYI:  I did a test.  I renamed the Ombi.sqlite to .old, and restarted the service. So far, it's letting me set everything back up.

One thing that came to mind - I recently added a user to Emby, and so in Ombi that user has no email address defined. But my base template for user permissions has both Newsletter & Notifications checked.

I don't think that is the issue, but you never know.

I'm thinking it was just a corrupt db.  :/

**Comment by tidusjar** [comment]
There is definitely a bug there somewhere. The error in the screenshot confirms it, just needed you to press the userlogin:1 text on the bottom right :)

**Comment by pendo** [comment]
One thing that I have found recently that has caught one of my users is that whitespace end characters are not ignored. Make sure that you don't have a space after the last character of the username.

**Comment by tymanthius** [comment]
Deleteing the DB fixed it. but I could go in and test w/ the old version if you want. But I don't think that it would be a whitespace issue as i don't copy paste, and it happened consistently.

**Comment by tymanthius** [comment]
Did you want to do more testing here, or should we close this as a corrupted DB?

**Comment by tidusjar** [comment]
We can close this. I doubt I am going to look into it as I am concentrating on the rewrite currently.

**Comment by Dyan654** [comment]
I had this exact same issue after changing my plex password and revoking access to all currently signed in applications. You can fix this by going to http://ip:port/login, logging into your local ombi admin account, and re-authenticating with Plex by generating a new access token.
