### ISSUE TITLE
I can't view the requested movies/shows

### ISSUE THREAD

**Issue by bartdelange** [tidusjar/Ombi#1390]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

3.2.1

#### Operating System:

unRaid

#### Mono Version (only if your not on windows)

4.8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Cleared logs and nothing shows up when the issue occurs

```

#### Problem Description:

I can't see any movie or show that has been requested. I have tried reinstalling ombi and re requested all shows and movies without any luck. 
I can however mass approve and delete all movies/shows, but then they still don't show (even after requesting a new one when I mass deleted them)
This is the error I get in my console: http://imgur.com/a/xwrno
Hope you can help.

#### Reproduction Steps:

- Request a movie/show
- Go to requests

**Comment by harihoudini** [comment]
I have exactly the same problem. I have tried enabling "user can view other requests" etc and restarted several times experimenting with settings but without luck. I do not get any error message. When i navigate to requests page as admin - i see two tabs for Movies/Tv Shows and the page below is blank.

**Comment by tidusjar** [comment]
This is a mono issue with how it handles TimeZones.

Looks like this is a bug introduced in the latest version of mono...

https://github.com/tidusjar/Ombi/issues/1142
https://github.com/tidusjar/Ombi/issues/849
https://github.com/tidusjar/Ombi/issues/661

**Comment by mdefran65** [comment]
newbie question how do I access the user interface
