### ISSUE TITLE
CouchPotato/SickRage SSL Bug

### ISSUE THREAD

**Issue by entropydo** [tidusjar/Ombi#1392]
#### Ombi Version:

V 2.2.1694

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

FreeNAS-9.10.2-U2 [running inside FreeBSD Jail]

#### Mono Version (only if you're not on windows)

4.6.2 (Stable 4.6.2.7/08fd525 Sat Feb 25 02:31:03 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Request made to https://domainname/sickrage/api/APIKEY/?cmd=sb.ping with status code OK. The response was {"data": {"pid": 23276}, "message": "Pong", "result": "success"}	Ombi.Api.ApiRequest	Trace	4/17/2017 8:14:56 PM
Request made to with status code 0. The response was	Ombi.Api.ApiRequest	Trace	4/17/2017 8:14:34 PM
Request made to https://domainname/couchpotato/api/APIKEY/app.available/ with status code OK. The response was {"success": true}	Ombi.Api.ApiRequest	Trace	4/17/2017 8:14:26 PM
System.NullReferenceException: Object reference not set to an instance of an object at Ombi.UI.Modules.ApplicationTesterModule.CouchPotatoTest () [0x00046] in <61b7963a5c4a4fc2bfce6c8c993d2152>:0	Ombi.UI.Modules.ApplicationTesterModule	Warn	4/17/2017 8:13:52 PM
Exception thrown when attempting to get CP's status:	Ombi.UI.Modules.ApplicationTesterModule	Warn	4/17/2017 8:13:52 PM
Request made to with status code 0. The response was	Ombi.Api.ApiRequest	Trace	4/17/2017 8:13:52 PM

```

#### Problem Description:

Inconsistent connection with SSL checked to both CouchPotato and SickRage.
Problems with approving movies/TV shows. Need to click approve a couple times before it goes through. Mimics the same process as the "Test Connectivity" button if pressed twice, the second time it will succeed with connection.

CouchPotato Settings:
Hostname = domain.name.tld
Port = 443
API key = correct
Username/password = empty
SSL = checked
CouchPotato Base URL = couchpotato (using reverse proxy for https)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I can consistently reproduce the problem by:
1. Click on Admin --> Settings in the upper right corner
2. Click on CouchPotato
3. Click Test Connectivity
4. Error pops up (Could not connect to CouchPotato, please check your settings. Exception Message: Object reference not set to an instance of an object)
5. Click Test Connectivity again = Success
6. Click on SickRage
7. Click Test Connectivity
8. Error pops up (Could not connect to SickRage, please check your settings.)
9. Click Test Connectivity again = Success (Connected to SickRage successfully!)

The error messages can be consistently brought up, but sometimes it connects without any error when clicking Test Connectivity.
This translates to issues when approving Movie/TV Show requests. It will pop up with an error of not working when approving. And if I click approve a couple times it will send it through with a success message.

**Comment by entropydo** [comment]
Sorry, PotatoQuality - wasn't sure if the title was descriptive enough. Please let me know if there is anything I can do to help the team.

**Comment by entropydo** [comment]
Is there anything I can do to help with this issue...or is this getting addressed in V3? Thanks!

**Comment by tidusjar** [comment]
It will be addressed in V3 ;)
