### ISSUE TITLE
Ombi Newsletter: From Name is set to the SMTP Auth Username

### ISSUE THREAD

**Issue by jshapiro26** [tidusjar/Ombi#1393]
#### Ombi Version:

V 2.2.1694

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

Not Necessary 

#### Operating System:

using the following docker image: https://github.com/rogueosb/docker-ombi

#### Mono Version (only if your not on windows)

4.6.2

#### Problem Description:

When my newsletter is sent out, it is setting the From name as the username in my SMTP auth settings. However, when I receive email notifications about requests or send test emails it doesn't set a name (which is preferred!!) and just sets the from address. 

This is an issue in my case because I am using sendgrid as my SMTP server. The way they do authentication is to set username as `apikey` and password is the actual key. 

When my users receive their weekly newsletter it shows that it is from `apikey` which could be pretty confusing. Instead, simply not setting the from name from the SMTP auth username field, like is done for other email notifications would be preferable.

**Comment by jshapiro26** [comment]
was this resolved @PotatoQuality?

**Comment by bulbajackel** [comment]
I suggest checking out #1455 its why the issue was closed.

**Comment by jshapiro26** [comment]
got it. thanks @bulbajackel
