### ISSUE TITLE
Skip Plex section(s) during scan

### ISSUE THREAD

**Issue by Djelibeybi** [tidusjar/Ombi#1394]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.5.3634

#### Operating System:

linuxserver.io/ombi Docker image

#### Mono Version (only if your not on windows)

4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Is it possible to configure Ombi to skip/ignore one or more Plex sections when scanning? I have a few libraries that are personal but I can't get Ombi to avoid them. 

#### Reproduction Steps:

Configure Ombi to integrate with Plex and enable Advanced Search and Episode Scanning. There is no option to pick specific libraries/sections to search.

**Comment by PotatoQuality** [comment]
No that is not possible.

**Comment by PotatoQuality** [comment]
You can open a feature request on our forum If you like/need it
