### ISSUE TITLE
ombi crashing if i close the CMD window and ombi not starting on startup

### ISSUE THREAD

**Issue by lukas15110168** [tidusjar/Ombi#1395]
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/04/20 09:47:49.814 Ombi.Core.Setup Info: Begin executing GetProfiles call to Radarr for quality profiles 
2017/04/20 09:47:49.814 Ombi.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles
```

#### Problem Description:

For some reason, after installing the Win10 creator's update, I noticed I couldn't remote access into Ombi anymore. I tried reinstalling the new update and overwriting the install folder, while maintaining ONLY the sqlite file (I deleted all files except sqlite then unblocked zip file and pasted in all the files from the newest 2.2.1694 early access preview zip file).

Anytime I run as admin ombi.exe, it opens the CMD showing it successfully started, and I can remote access and access on localhost:3579. If I close the CMD window, then Ombi completely stops working and I need to close the process in task manager and re-run ombi.exe (again with the CMD window left open for it to work).

Any idea what could be happening? I also noticed my new NSSM startup of Ombi in the services is not working. If I try hit start, it says "Windows could not start Ombi on the local computer. The service did not return an error. This could be an internal windows error or an internal service error. If the problem persists, contact your system administrator". I have ombi.exe set to run as admin in the properties, and I am admin logged in on windows.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by lukas15110168** [comment]
This is what I found on the NSSM page, it looks like this may be an issue with NSSM?

> NSSM - the Non-Sucking Service Manager
> 
> Windows 10 Creators Update Redstone 2
> 
> 2017-04-07: Sebasian Krause reports that services which try to create a console window will fail on Windows 10. The workaround is to configure the service not to open a console window:
> 
> nssm set <service> AppNoConsole 1
> Note that that you will need a pre-release build to to use the set command. Version 2.24 can be configured using the registry or the GUI.
> 
> **There is currently no workaround for services which actually require a console window.**

**Comment by PotatoQuality** [comment]
"Before posting make sure you also read our FAQ and **known issues**."

You didn't read our known issues...

**Comment by lukas15110168** [comment]
okay, now i see it in the known issues. I ran stopped the service, ran "nssm set Ombi AppNoConsole 1" and it seemed to have fixed it. Thank you very much!
