### ISSUE TITLE
There is no way to request a movie that exists in Radarr but is not present in Plex Media Server(PMS)

### ISSUE THREAD

**Issue by letchu22** [tidusjar/Ombi#1396]
Ombi Version:
2.2.1678

Update Branch:
Stable

Media Sever:
Plex

Media Server Version:
Version 1.5.5.3634 

Radarr Version:
0.2.0.654

Operating System:
Windows 10

Problem Description:

There is no way to request a movie that exists in Radarr but is not available in Plex Media Server(PMS).

I hope I am raising the problem at the appropriate place. I'm not too sure if I should raise this here or in the Radarr forum. I'm highlighting/bolding why I'm bringing up the request here. In any case, this might not be a problem and solution might lie in using the software better. Please advice.

1. When a user searches for a movie, that is currently unavailable on PMS but exists in Radarr, it shows the tag 'Requested'. **At this point the requester can do nothing**. Radarr is often set to 'Not Monitor' a file after the file is deleted. A user should be able to request such a file, one that has been deleted and is currently set to 'Not Monitored', and have it download itself again. 

2. This behavior works correctly for Sonarr. When a user searches for a show that is 'Not Monitored,' or not available in PMS as well as 'Monitored' but incomplete, **they have the option to request what they want.** Sonarr marks the file as Monitored if "Not Monitored" and proceeds with the workflow.  

Reproduction Steps:

1. Search for any movie which is in Radarr - doesn't matter if its 'Not Monitored' or not - but unavailable on PMS. 
2. You will be unable to request it to watch. 

Thank you for your time.

**Comment by tidusjar** [comment]
Looks like that is a bug in Ombi. We should only look for monitored movies
