### ISSUE TITLE
Ombi opening too many files

### ISSUE THREAD

**Issue by sdalberg** [tidusjar/Ombi#1398]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable (I tihnk

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.5.5.3634

#### Operating System:

docker

#### Mono Version (only if your not on windows)

docker, no idea

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:
Leaving application running.  

lsof | awk '{ print $2; }' | uniq -c | sort -rn | head
this command shows massive amounts of files being held open by ombi, causing numerous system problems.  I currently have over 100000 files open.

**Comment by sdalberg** [comment]
looks like the open files are different file descriptor of Ombi.sqlite...  100k openings...

**Comment by PotatoQuality** [comment]
We are working on a new version with better linux support. pleas wait for the ombi 3.0 version

**Comment by sdalberg** [comment]
For future reference is was when the plex connector was enabled.

**Comment by CyberMew** [comment]
@sdalberg sorry for digging this up but what do you mean by plex connector?

I'm also getting too many opened files errors. shfs/user: err: shfs_flush: close: (9) Bad file descriptor

This makes ombi unusable and I'm not sure why it's opening so many files.

**Comment by sdalberg** [comment]
In Ombi (in a linux/docker env), when you enable the connection to plex, the ombi sqlite database gets opened (and left open) at a rate that rapidly increases.  disabling the connector to plex keeps this from happening, so something in the plex code is opening the sqlite database to write to it, and then opening another copy without closing it from a linux filesystem perspective.

**Comment by CyberMew** [comment]
If we remove the connection the plex then the newsletter and status check will no longer work, right? Would accounts work too? At the very least I want my users to be able to request for stuff. They really need to rework this whole project or fix this bug. Close resource after use. Free memory after new.

**Comment by tidusjar** [comment]
@CyberMew please take a look at issue #865
