### ISSUE TITLE
Feature - Adding TAGS to REQUESTS which are sent to Sonarr #1443

### ISSUE THREAD

**Issue by letchu22** [tidusjar/Ombi#1402]
Greetings,

If Sonarr allows adding TAGS in its API, is it possible to have an option in which when a USER requests an item, their USERNAME or ALIAS (an ability to choose between both) is parsed as a TAG of the show's in Sonarr? Said option might be available in the ADMIN's settings.

Additionally, if possible, this option can be set, on a per user basis.
Additionally, if possible, this option can be set, on a per category basis( Just TV Shows or Movies or both.)

Flow:
USER requests TV SHOW
TV SHOW is added to Sonarr with the TAG - USERNAME/ALIAS

USE CASE:
Sonarr's connections like Pushbullet only notifies the USER only about relevant shows being available.
Sonarr's Delay Profiles set differently for various users.
Sonarr's Restriction for various users.

Thank you for your time.

**Comment by tidusjar** [comment]
Can you please raise this on the forums
