### ISSUE TITLE
Show requests other than 'all seasons' not working: Sonarr monitors everything

### ISSUE THREAD

**Issue by bartdelange** [tidusjar/Ombi#1404]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

3.2.1

#### Operating System:

unRaid

#### Mono Version (only if your not on windows)

4.8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

Logs are cleared and are staying empty when requesting a show.

#### Problem Description:

When I request a show and select anything other than All seasons Sonarr still monitors all seasons/episodes. For example if I request only the latest season of Sherlock, Sonarr monitors all episodes of the previous seasons. (however it does not monitor the season itself just the episodes)

screenshot: http://imgur.com/a/5IUDJ
Note how the monitor icon for the episodes are black and for the season it's not (except for the latest season, which is expected since I requested that season)

#### Reproduction Steps:

- Request a show selecting any option other than 'All Seasons'
- Go to Sonarr
- Problem is visible

**Comment by tidusjar** [comment]
https://github.com/Sonarr/Sonarr/issues/1852
