### ISSUE TITLE
Development Delayed, I would appreciate everyones help if it's possible

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1405]
Hi everyone,

Some people may know that recently my server died, I thought the PSU went so I plugged my main PC's PSU and it seemed to fry that (https://forums.ombi.io/viewtopic.php?f=4&t=53).

Ombi is maintained and developed completely by me in my free time. I'm not big on asking for donations, but any amount will help support the Ombi development road map and allow me to support the community better. Development is currently delayed until I get a new server. My upcoming nuptials are putting a dent on my ability to spend money to upgrade. Your generous donation is appreciated and will help with: 

- New Dev Machine/Server
- V2 Development/Support
- V3 Rewrite 

Thank you.
Jamie

**Comment by baerface** [comment]
Let's get him a new server! I'm in for some $$, thanks for all you do on this, it makes things so much easier. 

https://www.paypal.me/PlexRequestsNet

**Comment by nagetech** [comment]
Hey there! I may be able to help you out directly. I sent you an email amigo! Hoping to hear from you

**Comment by jstevenson72** [comment]
Will donate right away, love your work.  I'd also be willing to setup a VM in Azure for you, if that would help you out.  Let me know.

**Comment by untotren** [comment]
I can give you a VPS.

**Comment by tidusjar** [comment]
Hey guys thanks for the support and help. I'll be building the new server this weekend!

**Comment by untotren** [comment]
Let me know if you need any servers to bounce off.  I have a few hyperv beds with 64gb+ of ram + i7 black.
