### ISSUE TITLE
Headphones not showing up for search

### ISSUE THREAD

**Issue by untotren** [tidusjar/Ombi#1406]
I have enabled headphones and tested the connectivity.  I see no way to search for music.

**Comment by Glynnryan** [comment]
@untotren open Ombi and with your admin account and go to Settings > Ombi Configuration and make sure "Search for Music" is ticked. 

I just setup Headphones and had the same problem, but after enabling the "Search for Music" setting, I now have an "Albums" option in the search screen.

**Comment by tidusjar** [comment]
Please follow the Issue template
