### ISSUE TITLE
Attempted the Beta Upgrade of Ombi to newest version, now Ombi.exe is an unkillable process even after restart

### ISSUE THREAD

**Issue by rausch101** [tidusjar/Ombi#1408]
#### Ombi Version:

Not sure how the upgrade went, but either Ombi v2.2.1 or Ombi v2.2.0

#### Operating System:

Windows 10 Pro

#### Problem Description:

Attempted the Beta upgrade and now Ombi.exe is permanently an unkillable process in Windows, even after restart

After issuing a "taskkill /pid #### /f", Ombi.exe just spawns another with a new PID. 

UPDATE: Also, now apparently PlexPy is no longer working. Pretty frustrating. What are the chances I'm going to have to wipe my harddrive and reinstall everything?

#### Reproduction Steps:

Attempt to use the built-in beta upgrader for Ombi

**Comment by tidusjar** [comment]
Are you running it via a service or something? There is **no** code that will spawn a new process if it's shut down. This looks like you have sets omething up. Also we have 0 integration with PlexPy.

**Comment by PotatoQuality** [comment]
Do you use nssm to start Ombi? You need to run the stop command of nssm.

**Comment by untotren** [comment]
Yeah this is a local system problem, not a problem with Ombi.
