### ISSUE TITLE
OMBI to resubmit request to Sonarr/Radarr

### ISSUE THREAD

**Issue by Phelms215** [tidusjar/Ombi#1414]
**OMBI Information:**
Docker - linuxserver/docker-ombi
Version: 2.2.1678
Stable Branch

**Media Server:** Plex 

**Problem/Question** 
Is it possible, without deleting and readding the request, to have OMBI resubmit request to Sonarr/Radarr?

I had an issue when setting up docker with OMBI & Sonarr/Radarr. As a solution I ended up recreating from scratch the Sonarr and Radarr installations. The problem is the shows within OMBI list as 'Processing Request' and are not present in Sonarr/Radarr.

If I delete the request from OMBI and resubmit it works as expected

Thanks for any help!

**Comment by tidusjar** [comment]
Hello. This is currently not possible. It might be worth adding though!

**Comment by nixtv** [comment]
Do you think this will ever be done? I'd love to resubmit requests. It'd also be nice to have to option to have Ombi delete the movie from Radarr and then re-add it. Recently I had a bunch of requests and it seemed to mess up in Radarr so nothing actually went thru and it's like the movie are somewhat broken in Radarr.

**Comment by tidusjar** [comment]
Yes. This is planned for v4. Check the projects tab

**Comment by guillaumedsde** [comment]
Hello, it seems like the projects tab (I assume github projects?) is not used anymore?

I am currently running version 4.43.5 and was wondering whether this feature ended up being implemented in v4?
