### ISSUE TITLE
Requested Movie List not returned

### ISSUE THREAD

**Issue by jw6jw6jw6** [tidusjar/Ombi#1415]
#### Ombi Version:

2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:
Ubuntu 16.04 LTS Server x64

#### Mono Version (only if your not on windows)

4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 16:18:35 UTC 2017)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Select[TSource,TResult] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector) [0x00010] in <2392cff65f724abaaed9de072f62bc4a>:0 at Ombi.UI.Modules.RequestsModule+d__57.MoveNext () [0x0047e] in :0

When attempting to manually make the REST call I recieve the following error from the server:
Nancy.ErrorHandling.DefaultStatusCodeHandler.DefaultStatusCodeHandlerResult cannot be serialized because it does not have a parameterless constructor.

```

#### Problem Description:

Requested movies no longer render.

#### Reproduction Steps:

I do not know what I did to cause the issue, if needed I can send you the sqlite db file for inspection.

**Comment by tidusjar** [comment]
Yeah think i'm going to need you to reset the admin password or create a admin account so I can log in with the sqlite db.

So just going to the Requests page generates this error?

**Comment by jw6jw6jw6** [comment]
I was able to fix this by deleting all the requested movies. I am guessing there was a corrupted entry in the movies table that stopped the iterator.
