### ISSUE TITLE
Deleted Users Still Get the Daily Newsletter. FYI

### ISSUE THREAD

**Issue by TATUMTOT** [tidusjar/Ombi#1416]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Server 2012

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Users that are no longer shared with in plex still get the daily email newsletter.

#### Reproduction Steps:

Add Users to plex and Then Remove them if they show up in OMBI then they will still get the daily notification emails.

**Comment by tidusjar** [comment]
Are they still in the user management section?

**Comment by TATUMTOT** [comment]
No they are not showing up in the user management section.

Also thought of another little issue with the email portion is when you send a Mass email. and when you view it on your phone. Your phone will start to give you a summery of what is in the email before you open it and it says."Ombi Recently Added." then you message. another FYI

**Comment by TATUMTOT** [comment]
ok i have looked into this a little more. the users are not showing up in the front-end users management but they are still in  the DB

**Comment by PotatoQuality** [comment]
@TATUMTOT hmm that sounds like a bug.
