### ISSUE TITLE
Deleted Requests Continue to Show as Requested, unable to re-request.

### ISSUE THREAD

**Issue by CriticalMachTV** [tidusjar/Ombi#1417]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.6.3790-4613ce077

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

None

#### Problem Description:

I requested a movie and then deleted the request, however the movie is still listed as requested when searching for it to re-request.

#### Reproduction Steps:

Request a movie
Delete the request
Search for movie to see that it is still listed as requested.

**Comment by tidusjar** [comment]
Is it in Radarr/CP?

**Comment by CriticalMachTV** [comment]
I'll check tomorrow when I get home and let you know then.

**Comment by CriticalMachTV** [comment]
Yes, the requests are still in Radarr.

**Comment by CriticalMachTV** [comment]
Even if I delete the item from Radarr, update the library, then restart Ombi the item still shows as requested.
