### ISSUE TITLE
Cookie Conflict with Sonarr

### ISSUE THREAD

**Issue by kmlucy** [tidusjar/Ombi#1424]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Docker on Debian Jessie

#### Mono Version (only if your not on windows)

5.0.1.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

None

```

#### Problem Description:

Ombi is creating a cookie conflict with Sonarr.

#### Reproduction Steps:

When logging into Ombi, it sets a cookie titled ``_ncfa`` at ``/``. I have my base url set to ``/ombi``, but the cookie is still set at the root. Sonarr uses the same name for the cookie to authenticate the user, so when the cookie from Ombi is set, I am unable to login to Sonarr. Sonarr has changed to writing the cookie to the base URL path, but seems to still break when a cookie is set at ``/``. 

Relevant issue: Sonarr/Sonarr/issues/1962

**Comment by tidusjar** [comment]
This will be resolved with V3 as we are using JWT tokens for authentication.

**Comment by navickas12** [comment]
Still having this issue

**Comment by kmlucy** [comment]
Try updating Sonarr. They fixed it on their end.
