### ISSUE TITLE
Newsletter not sending at all

### ISSUE THREAD

**Issue by ckersey2** [tidusjar/Ombi#1426]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.7.2.3878 on QNAP NAS

#### Operating System:

QNAP Firmware version: 4.3.3

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```





```

<img width="752" alt="screen shot 1" src="https://user-images.githubusercontent.com/13756203/27097166-5e6805aa-5041-11e7-9591-2923da8e570b.png">

#### Problem Description:

I am not able to get the newsletter to send at all. The other email functions for mass email as well as sending test emails through notifications work fine.

#### Reproduction Steps:

- Go to Newsletter Settings
- Ensure Enable Newlsetter is checked.
- Click Send Test Email to Admin
- No email is sent at all.
<img width="913" alt="screen shot 2017-06-13 at 2 02 27 pm" src="https://user-images.githubusercontent.com/13756203/27097061-106b9434-5041-11e7-810a-56c6a50aa0ea.png">

**Comment by tidusjar** [comment]
Is your email notifications setup?

**Comment by ckersey2** [comment]
Yes, they are. I have tested the other email features and they all work fine. All accounts are set to receive notifications.

**Comment by tidusjar** [comment]
Has any content been added? Because the newsletter will not send if Ombi has not picked up any new content.

Are the Plex Content cacher and availability checker jobs running ok?

**Comment by ckersey2** [comment]
I have not added new content since I installed it today. I will add some content to plex tonight and give it another go.

**Comment by ckersey2** [comment]
Where do I check to see if the Plex Content cacher and availability checker jobs are running? I don't see them listed in the scheduled jobs.

**Comment by CrazyDave9** [comment]
Hi. Should be located under Scheduled Jobs and i belive its called "Plex Cacher" should be running every 60 min as default, you can also run it manualy by clicking the circling arrows to the right of plex chacher
<img width="427" alt="ombi" src="https://user-images.githubusercontent.com/29477260/27217090-b6f744b8-5278-11e7-9951-536a73a20a1f.PNG">

**Comment by ckersey2** [comment]
Those jobs are not even listed in my scheduled tasks.
<img width="702" alt="screen shot 2017-06-16 at 7 53 01 am" src="https://user-images.githubusercontent.com/13756203/27225576-f72b5070-5268-11e7-9400-b279fde3649e.png">

**Comment by tidusjar** [comment]
Is Plex Enabled?

**Comment by ckersey2** [comment]
Nice catch. It wasn't enabled. I'm not sure why it didn't enable it during setup when I provided my plex.tv credentials. I manually enabled it and tested it and it works now. Thanks!!
