### ISSUE TITLE
Systemd doesn't restart Ombi when it crashes silently

### ISSUE THREAD

**Issue by sfunk1x** [tidusjar/Ombi#1427]
#### Ombi Version:

2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04.2 LTS

#### Mono Version (only if your not on windows)

4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2017/06/11 12:00:42.149 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/06/11 12:00:42.292 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/06/11 12:00:42.340 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:42.987 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.094 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.144 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.193 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.730 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.766 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.906 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/11 12:00:43.911 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/06/11 12:00:43.915 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 8 
2017/06/11 12:03:20.325 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/06/11 12:03:33.823 Ombi.Services.Jobs.PlexContentCacher Debug: Done movies 
2017/06/11 12:03:34.322 Ombi.Services.Jobs.PlexContentCacher Debug: Done TV 
2017/06/11 12:03:35.292 Ombi.Services.Jobs.PlexContentCacher Debug: Done albums 
2017/06/11 12:05:42.171 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0
```

```

2017/06/14 07:47:31.363 Ombi.Core.Setup Error: Failed to cache CouchPotato quality profiles! System.ArgumentNullException: Value cannot be null.
Parameter name: value
  at System.Runtime.Caching.MemoryCacheEntry..ctor (System.String key, System.Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, System.Collections.ObjectModel.Collection`1 dependencies, System.Runtime.Caching.CacheEntryRemovedCallback removedCallback, System.Runtime.Caching.MemoryCache cache) <0x409aebe0 + 0x00347> in <filename unknown>:0 
  at System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal (System.String key, System.Object value, System.Runtime.Caching.CacheItemPolicy policy) <0x409ad5a0 + 0x0026f> in <filename unknown>:0 
  at System.Runtime.Caching.MemoryCache.AddOrGetExisting (System.Runtime.Caching.CacheItem item, System.Runtime.Caching.CacheItemPolicy policy) <0x409ad310 + 0x0004b> in <filename unknown>:0 
  at System.Runtime.Caching.MemoryCache.Add (System.Runtime.Caching.CacheItem item, System.Runtime.Caching.CacheItemPolicy policy) <0x409ad250 + 0x00021> in <filename unknown>:0 
  at Ombi.Helpers.MemoryCacheProvider.Set (System.String key, System.Object data, Int32 cacheTime) <0x409ac230 + 0x001cc> in <filename unknown>:0 
  at Ombi.Core.Setup.CacheCouchPotatoQualityProfiles (ICacheProvider cacheProvider) <0x408aef10 + 0x001a1> in <filename unknown>:0 
2017/06/14 07:47:32.201 Ombi.Services.Jobs.PlexContentCacher Debug: Getting Lib sections 
2017/06/14 07:47:32.492 Ombi.Services.Jobs.PlexContentCacher Debug: Going through sections now 
2017/06/14 07:47:32.529 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.140 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.234 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.284 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.337 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.806 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:33.886 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:34.026 Ombi.Services.Jobs.PlexContentCacher Debug: adding lib 
2017/06/14 07:47:34.034 Ombi.Services.Jobs.PlexContentCacher Debug: Going through all the items now 
2017/06/14 07:47:34.041 Ombi.Services.Jobs.PlexContentCacher Debug: Item count 8 
2017/06/14 07:49:15.472 Ombi.UI.Modules.UserLoginModule Debug: Need to auth 
2017/06/14 07:49:15.958 Ombi.UI.Modules.UserLoginModule Debug: Friends list result = False 
2017/06/14 07:49:21.706 Ombi.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2017/06/14 07:51:04.042 Ombi.Services.Jobs.PlexContentCacher Debug: done all that, moving onto the DB now 
2017/06/14 07:51:18.195 Ombi.Services.Jobs.PlexContentCacher Debug: Done movies 
2017/06/14 07:51:18.996 Ombi.Services.Jobs.PlexContentCacher Debug: Done TV 
2017/06/14 07:51:20.281 Ombi.Services.Jobs.PlexContentCacher Debug: Done albums 
2017/06/14 07:52:32.210 Ombi.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0
```

#### Problem Description:

Ombi process dies and doesn't notify systemd that the process has died, so it is not restarted. Restart directive is set in the service file, as seen here:

[Unit]
Description=PlexRequest
After=network.target

[Service]
User=arbeiter
Type=simple
WorkingDirectory=/home/user/Ombi
ExecStart=/usr/bin/mono /home/user/Ombi/Ombi.exe
Restart=always
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target

This happens extremely frequently (daily), and it occurred with PlexRequests as well - which is what spurred me to switch to Ombi.

#### Reproduction Steps:

1. Install Ombi.
2. Add systemd service file.
3. Start service.
4. Come back the next day and notice that Ombi is no longer accessible, the service has died but systemd thinks it is still active so it doesn't restart it.
5. Note that there is nothing indicative in the logfile as to why Ombi crashed.

**Comment by camwise** [comment]
I am also having this same issue.

**Comment by silvether** [comment]
I can also replicate this behaviour.

**Comment by PotatoQuality** [comment]
We working on a new version to support Linux systems a lot better. Pleas wait for Ombi v3

**Comment by camwise** [comment]
I changed my ombi.service script a little bit and haven't had issues since then.  Close to the same script as the OP

[Unit]
Description=Systemd script to run Ombi as a service
After=network-online.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/bin/mono /opt/Ombi/Release/Ombi.exe
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target


Only change I made from original install wiki was adding:

Restart=always
RestartSec=3

Since i've added that i haven't had it crash without restarting itself.

**Comment by sfunk1x** [comment]
Caught this in the log:

`Jun 21 15:21:00 media systemd[1]: plexrequests.service: Service hold-off time over, scheduling restart.
Jun 21 15:21:00 media systemd[1]: Stopped PlexRequest.
Jun 21 15:21:00 media systemd[1]: Started PlexRequest.
Jun 21 15:21:00 media mono[3790]: Starting Up! Please wait, this can usually take a few seconds.
Jun 21 15:21:00 media mono[3790]: Version: 2.2.1678
Jun 21 15:21:00 media mono[3790]: Location of the database: /home/user/Ombi/Ombi.sqlite
Jun 21 15:21:00 media mono[1118]: [Debug] Api: [GET] /api/profile: 200.OK (2 ms)
Jun 21 15:21:01 media mono[3790]: no configuration section <common/logging> found - suppressing logging output
Jun 21 15:21:01 media mono[3790]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: Address already in use
Jun 21 15:21:01 media mono[3790]:   at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) <0x41d759d0 + 0x000ef> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointListener..ctor (System.Net.IPAddress addr, Int32 port, Boolean secure) <0x41d75650 + 0x00143> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.GetEPListener (System.String host, Int32 port, System.Net.HttpListener listener, Boolean secure) <0x41d74f80 + 0x002eb> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.AddPrefixInternal (System.String p, System.Net.HttpListener listener) <0x41d749b0 + 0x000c3> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.AddListener (System.Net.HttpListener listener) <0x41d744c0 + 0x00147> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   --- End of inner exception stack trace ---
Jun 21 15:21:01 media mono[3790]:   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f5ed69ab960 + 0x000ef> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x7f5ed67e3ec0 + 0x0002a> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create (IAppBuilder builder) <0x41d715d0 + 0x001f2> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer (Microsoft.Owin.Hosting.Engine.StartContext context) <0x41d71550 + 0x00029> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start (Microsoft.Owin.Hosting.Engine.StartContext context) <0x4107c7b0 + 0x0015b> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x4107b9e0 + 0x0005c> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x41078ca0 + 0x0007b> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.StartImplementation (IServiceProvider services, Microsoft.Owin.Hosting.StartOptions options) <0x410779e0 + 0x00062> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.Start (Microsoft.Owin.Hosting.StartOptions options) <0x41073710 + 0x00027> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.Start[TStartup] (Microsoft.Owin.Hosting.StartOptions options) <0x41073600 + 0x00047> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Ombi.UI.Program.Main (System.String[] args) <0x40e7fea0 + 0x0091b> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]: [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: Address already in use
Jun 21 15:21:01 media mono[3790]:   at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) <0x41d759d0 + 0x000ef> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointListener..ctor (System.Net.IPAddress addr, Int32 port, Boolean secure) <0x41d75650 + 0x00143> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.GetEPListener (System.String host, Int32 port, System.Net.HttpListener listener, Boolean secure) <0x41d74f80 + 0x002eb> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.AddPrefixInternal (System.String p, System.Net.HttpListener listener) <0x41d749b0 + 0x000c3> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Net.EndPointManager.AddListener (System.Net.HttpListener listener) <0x41d744c0 + 0x00147> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   --- End of inner exception stack trace ---
Jun 21 15:21:01 media mono[3790]:   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f5ed69ab960 + 0x000ef> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x7f5ed67e3ec0 + 0x0002a> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create (IAppBuilder builder) <0x41d715d0 + 0x001f2> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer (Microsoft.Owin.Hosting.Engine.StartContext context) <0x41d71550 + 0x00029> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start (Microsoft.Owin.Hosting.Engine.StartContext context) <0x4107c7b0 + 0x0015b> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x4107b9e0 + 0x0005c> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x41078ca0 + 0x0007b> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.StartImplementation (IServiceProvider services, Microsoft.Owin.Hosting.StartOptions options) <0x410779e0 + 0x00062> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.Start (Microsoft.Owin.Hosting.StartOptions options) <0x41073710 + 0x00027> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Microsoft.Owin.Hosting.WebApp.Start[TStartup] (Microsoft.Owin.Hosting.StartOptions options) <0x41073600 + 0x00047> in <filename unknown>:0
Jun 21 15:21:01 media mono[3790]:   at Ombi.UI.Program.Main (System.String[] args) <0x40e7fea0 + 0x0091b> in <filename unknown>:0
`
