### ISSUE TITLE
When adding sonarr, ombi hangs when clicking "Get root folders"

### ISSUE THREAD

**Issue by therza** [tidusjar/Ombi#1429]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04
#### Mono Version (only if your not on windows)

5.0.1.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```


```

#### Problem Description:

When clicking "get root folders" while adding Sonarr config, button hangs and never completes job. Radarr adds just fine.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Anything in the browsers console? Press F12 and then console

**Comment by therza** [comment]
Hmm, this is weird:

Hit root folders . .
error Not found

**Comment by tidusjar** [comment]
Can you follow this and post the result please: https://forums.ombi.io/viewtopic.php?f=11&t=58

**Comment by therza** [comment]
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088790
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088791
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088792
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088793
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088794
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088795
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088796
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088797
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088798
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088799
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088800
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088801
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088802
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088803
tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088804
tapi?mode=history&search=&failed_only=0&start=0&limit=10&last_history_update=1497533171&output=json&apikey=cbbe0e7055724b5368442d7be405929d&_=1497545088805


It just keeps doing this on repeat until I X out the tab

**Comment by tidusjar** [comment]
Can I get a screenshot like the guide please?

Open up the development tools, then refresh the page and it should show something.

**Comment by rossviljoen** [comment]
Same issue here,

Nothing at all in the console.

**Comment by ydkmlt84** [comment]
After talking with him (therza) in Organizr chat, it looks like the problem was that he didn't have any "root" folders. His Sonarr library was empty. So he hadn't set a root folder yet. 
Not sure about rossviljoen and his problem.

**Comment by therza** [comment]
Yes, it was my fault! Sorry :(

**Comment by rossviljoen** [comment]
Yeah, same thing, sorry :/
