### ISSUE TITLE
Plex Connection Failed: There is an error in XML document

### ISSUE THREAD

**Issue by AlanMcCormick** [tidusjar/Ombi#1432]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Hmm not sure it's the one from: https://hub.docker.com/r/linuxserver/ombi/

#### Media Sever:

Plex

#### Media Server Version:

Version 3.2.1

#### Operating System:

Linux/Docker on unRAID

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.InvalidOperationException: There is an error in XML document (14, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexStatus.Read4_MediaContainer () [0x00064] in <8018ceebbaf743e8af9d8c35f444f8a6>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x0011b] in <087c2b5f99634a258bd5e3d9ce5629db>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <087c2b5f99634a258bd5e3d9ce5629db>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <087c2b5f99634a258bd5e3d9ce5629db>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <2a63c45e97a245c1bf3c2df5f23972c5>:0

```

#### Problem Description:

I cannot connect to the Plex server. I went into my Plex account and deleted the Ombi device client, then went to Ombi and re-requested a new token, which worked, but that did not help. 

I tried disabling/enabling "Enable episode searching" and also "Use advanced search", and had no better results.

#### Reproduction Steps:

Hostname: 192.168.1.100
Port: 32400
SSL: No
Plex Base URL: /web

Test Connectivity: Could not connect to Plex, please check your settings

Note: browsing my setting on plex gives me, for example, http://192.168.1.100:32400/web/index.html#!/settings/devices

Below is the document I receive when I go to:
http://192.168.1.100:32400/library/sections?X-Plex-Token=5hr51zpfhnQSmLKvc8Ls&X-Plex-Client-Identifier=test&X-Plex-Product=PlexRequest&X-Plex-Version=1
```

<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="2" allowSync="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1492033170" title1="Plex Library">
<Directory allowSync="1" art="/:/resources/movie-fanart.jpg" composite="/library/sections/1/composite/1492890856" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="1" type="movie" title="Movies" agent="com.plexapp.agents.imdb" scanner="Plex Movie Scanner" language="en" uuid="e8b2e902-8815-4bcb-951d-48668b808831" updatedAt="1492890856" createdAt="1492890856">
<Location id="1" path="/movies" />
</Directory>
<Directory allowSync="1" art="/:/resources/show-fanart.jpg" composite="/library/sections/2/composite/1493267767" filters="1" refreshing="0" thumb="/:/resources/show.png" key="2" type="show" title="TV Shows" agent="com.plexapp.agents.thetvdb" scanner="Plex Series Scanner" language="en" uuid="bc94ab24-1d9f-49bd-8f0b-1eeb29d0ccfc" updatedAt="1493267767" createdAt="1493267767">
<Location id="2" path="/tv" />
</Directory>
</MediaContainer>


```

Note: There is no line 14 in my XML file, so I'm not sure I understand the error from the stack trace. I'm a software engineer, let me know if you need any other logs/debugging.

**Comment by PotatoQuality** [comment]
Don't set the base URL. Can you try that?

**Comment by AlanMcCormick** [comment]
Looks like that worked. Test connection worked successfully. Is that a known bug?

**Comment by PotatoQuality** [comment]
It isn't a bug because you don't have a base url ;). /web is a default url. Only if you have something before the /web you need to use the base url setting
