### ISSUE TITLE
Ombi crashes and db file getting bigger and bigger

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#1433]
Application Version:	2.2.1
OS:	(QNAP) Mono
System Version:	4.2.2 (Stable 4.2.2.30/996df3c Fri Jan 29 21:11:18 CET 2016)
Branch:	Stable
Log Level:	Error
Database Location:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release/Ombi.sqlite
Running Directory:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release

#### Media Sever:

Plex

#### Media Server Version:

1.7.3.3937

#### Problem Description:

Yesterday I applied the last patch (2.2.1) before this it was working fine. After I applied the patch I noticed that the db file (Ombi.sqlite) has started to grow quite a lot. After a while Ombi was down and the error was the following:

Mono.Data.Sqlite.SqliteException: Insertion failed because the database is full

After a little bit of troubleshooting the issue was related to the fs /tmp that was around 50MB it was getting short for what Ombi was trying to do. I assume it uses it as a temporary location.

I gave it 500MB more thinking that was going to enough for the operations (rebuild or reindexin) Ombi was doing product of the upgrade but it wasn't. Today I checked and Ombi is down and the db file is around 510MB.

Something seems to be wrong. My media library is pretty much the same and before the database was less than 50MB not is getting close to 512MB.

Some assistance will be appreciated. Thanks a lot.

**Comment by tidusjar** [comment]
That's very strange. There is a scheduled job that purges the database and
we try and compress it too.

What are some of the errors?

**Comment by cesalo** [comment]
There are no errors it just crashing because there is no more space in /tmp. The file is huge in comparison with the old logs. It seems is processing a lot of video files, I've uploaded the last 10000 files of the last log.

Thanks for your help.
[ombi_log.zip](https://github.com/tidusjar/Ombi/files/1083295/ombi_log.zip)

**Comment by cesalo** [comment]
Any ideas? .. The issue persists and the db keeps growing.

**Comment by tidusjar** [comment]
Turn off the Trace level. Change it to Warn in the log settings.
