### ISSUE TITLE
Cannot connect to Plex

### ISSUE THREAD

**Issue by TheBigC53** [tidusjar/Ombi#1435]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable
#### Media Sever:

Plex

#### Operating System: Win10 x86

Using the Wizard, Ombi found the correct ip address, and I changed the port from 17090 to 32400. I was able to retrieve the token. Trying to connect to Plex returned an error.

```

System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlTextReader.Read() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexStatus.Read4_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by TheBigC53** [comment]
Last bit from log should be Line 107

**Comment by PotatoQuality** [comment]
Pleas downgrade your plex version to the stable version and re-setup ombi.

**Comment by Terebi42** [comment]
I am having this issue too, but AFAIK I am on the current stable version of plex. FWIW I can authenticate and grab the tokens correctly, but this error goes into the log when I try to test the connection.

Plex version : Version 3.27.1

System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlTextReader.Read() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexStatus.Read4_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107
