### ISSUE TITLE
"You cannot use 'requests' as this is reserved by the application."

### ISSUE THREAD

**Issue by topper59** [tidusjar/Ombi#1437]
#### Ombi Version:

V 2.2.1694

#### Update Branch:

Early Access Preview
#### Media Sever:

Plex

#### Operating System:

FreeNAS 9.10

#### Problem Description:

My base URL is configured as "requests", because I have nginx with a reverse proxy so people can go to mydomain.com/requests to get to Ombi. It looks like "requests" isn't allowed as a base URL anymore because when I tried to change the weekly movie limit I get "You cannot use 'requests' as this is reserved by the application.". It still works fine because the setting is still saved as "requests" but I just can't update anything on the Ombi config page unless I change my base URL. I'd rather not have to change the URL because that's what everyone else is used to using. Any quick solution to keeping the base URL while changing other settings? I tried editing the sqlite database file but the content for settings looks encrypted.

**Comment by tidusjar** [comment]
The reason why I don't allow requests as we have a requests page and it can
conflict with it.
