### ISSUE TITLE
API URLs return 404

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#1438]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 14.04

#### Mono Version (only if your not on windows)

5.0.1.1

#### Problem Description:

Whenever I attempt to access the API URL's, I simply get a 404 error returned. Do i need to set something up to enable API access?

The wiki entry isn't very helpful: https://github.com/tidusjar/Ombi/wiki/API---Ombi-V3

Does that wiki page mean that the API isn't available until Ombi version 3? If it is not available until version 3 (which is not available), then why is the page available?

Or does that wiki page mean that the API on version 3? in that case, should the documentation of the url reference `/api/v3` instead of `/api/v1`?

Thanks for any clarification on the matter.

**Comment by tidusjar** [comment]
I started writing the documentation when I started the Ombi rewrite (v3). Thanks for pointing this out as it's also not upto date. 

Once v3 is available the API will be documented and accessible via a Swagger link.
