### ISSUE TITLE
API Exception when attempting to get the Plex Libraries

### ISSUE THREAD

**Issue by dinner95** [tidusjar/Ombi#1441]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.7.3.3933 (Web: 3.7.0)

#### Operating System:

Windows 10 Pro Version 1703 Build 15063.413

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

There has been a API Exception when attempting to get the Plex Libraries	Ombi.Api.PlexApi	Error	23.06.2017 14:58:25
Exception when calling GetLibrarySections for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	23.06.2017 14:57:55
Exception when calling GetLibrarySections for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	23.06.2017 14:57:45
Exception when calling GetLibrarySections for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	23.06.2017 14:57:40
Exception when calling GetLibrarySections for Plex, Retrying 00:00:30	Ombi.Api.PlexApi	Error	23.06.2017 14:55:22
Exception when calling GetLibrarySections for Plex, Retrying 00:00:10	Ombi.Api.PlexApi	Error	23.06.2017 14:55:12
Exception when calling GetLibrarySections for Plex, Retrying 00:00:05	Ombi.Api.PlexApi	Error	23.06.2017 14:55:07
There has been a API Exception when attempting to get the Plex Libraries	Ombi.Api.PlexApi

```

#### Problem Description:

Ombi is not getting movies from plex. Database table plex cacher is empty. Before the last plex update there were all movies listet

#### Reproduction Steps:

Just start ombi after the plex update useing the plex pass update channel.
Then you'll see that no movie is "available" on the Websurface.
I also tried it with a new key from the plex server. It was not working too.

**Comment by dinner95** [comment]
I also tried it with a new key from the plex server. It was not working too.

**Comment by PotatoQuality** [comment]
Pleas downgrade your plex server version to the stable version.

**Comment by dinner95** [comment]
I set it to the public channel. Im waiting for the next update because the servers re running 24/7.
Thanks for your help!

**Comment by dinner95** [comment]
i downgraded plex to the last stable version. The error is still there

**Comment by PotatoQuality** [comment]
Can you restart Ombi? 
If the problem are still there. Pleas open root ombi/ logs/ and post more logs around the failedGetLibrarySections

**Comment by dinner95** [comment]
I found the mistake. It was because i set a base url in the plex settings
