### ISSUE TITLE
Email notification setup failure (Gmail)

### ISSUE THREAD

**Issue by stretch886** [tidusjar/Ombi#1442]
SMTP authentication enabled
Host name: smtp-relay.gmail.com
Port: tried 25 and 465
Sender/recipient/username all listed as my email
Password is Gmail password

I get this error:
Failed: 5.7.0 Mail relay denied [98.144.108.17]. Invalid credentials for relay for 5.7.0 one of the domains in: 168.1.176], 1.176], [192.168.1.176] (as 5.7.0 obtained from HELO and MAIL FROM). 5.7.0 Email is being sent from a domain or IP address which isn't registered 5.7.0 in your G Suite account. Please login to your G Suite account and 5.7.0 verify that your sending device IP address has been registered within 5.7.0 the G Suite SMTP Relay Settings. For more information, please visit 5.7.0 https://support.google.com/a/answer/6140680#maildenied c31sm1401185itd.5 - gsmtp 

Any ideas?

**Comment by tidusjar** [comment]
Take a look at this: https://support.google.com/a/answer/176600?hl=en

**Comment by stretch886** [comment]
Do I even have G-suite?  I'm just a regular Gmail user.  Seems like some admin function.

**Comment by tidusjar** [comment]
You are using the G-Suite relay, use this as the host: smtp.gmail.com

**Comment by stretch886** [comment]
I updated to this and the port to 587.  Working great now.

Thanks.
