### ISSUE TITLE
Minimum Availability Default in Radarr

### ISSUE THREAD

**Issue by davemanster** [tidusjar/Ombi#1445]
#### Ombi Version:

V 2.2.1678
System: 4.0.30319.36392

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Radarr 0.2.0.779

#### Operating System:

Windows

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When placing a request from OMBI to Radarr minimum availability is always left blank. This is causing a bunch of fakes to be downloaded.

#### Reproduction Steps:

Request movie from OMBI
Check availability in Radarr
No availability set

**Comment by JoeStratton** [comment]
Can confirm this appears to be an issue.

**Comment by tidusjar** [comment]
This has been fixed in the EAP branch
