### ISSUE TITLE
Ombi Periodically not able to connect

### ISSUE THREAD

**Issue by MorkaiTheWolf** [tidusjar/Ombi#1446]
Ombi Version: V 2.2.1

Update Branch: Stable

Media Sever: Plex 1.5.3.3580

Operating System: QNAP  (I believe these run a flavor of Debian?)
Firmware version	4.3.3.0210 Build 20170606

Mono Version: 4.6.2.7

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <2a63c45e97a245c1bf3c2df5f23972c5>:0

```

#### Problem Description:

Periodically it appears that Ombi's page will not load and the page will come back stating that is unavailable or it refuses to connect. For good measure I checked my port forwarding which all looks good.  It only seems to happen when a user requests some media and it's in the process of saving.  In order to resolve I have to restart Ombi and Qmono before the page becomes available again.  I'm thinking it may be a permissions issues with writing out to QMono though I can't be entirely sure.  The log snippet above is the latest one I could find as I'm actively trying to force the issue again and will provide more logs as I come across them.

Reproduction Steps:
User logs into ombi page, requests any TV show or movie and page loads successfully.  Then, after 1-3 requests the page no longer responds.
Only concrete steps I've found is that after shutting down QMono and Ombi then restarting QMon and Ombi that the page becomes available.

Are there any other logs that would be helpful for investigation? Mind you, I'm fairly new to the QNAP system so I'm still learning the ropes but will provide anything I can to assist,

**Comment by tidusjar** [comment]
This will. So resolved with the V3 of Ombi.

**Comment by MorkaiTheWolf** [comment]
Ohhh, is this a known issue or anything? If so, mind pointing me to any documentation?

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/865
