### ISSUE TITLE
Unable to see movie requests

### ISSUE THREAD

**Issue by andrewiankidd** [tidusjar/Ombi#1448]
#### Ombi Version:

V 2.2.1810

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

Version 1.7.1.3856 

#### Operating System:

Windows Server 2012 R2

#### Mono Version:
N/A

#### Applicable Logs:

Ombi Logs:
```
System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector) at Ombi.UI.Modules.RequestsModule.d__57.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 191
```
Chrome Console:
```
GET http://xxx/requests/movies 500 (Internal Server Error)
send @ jquery-2.2.1.min.js:4
ajax @ jquery-2.2.1.min.js:4
movieLoad @ requests.js?v=2.2.1:784
initLoad @ requests.js?v=2.2.1:740
(anonymous) @ requests.js?v=2.2.1:68
```
/requests/movies output:

```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.UI.Modules.RequestsModule.d__60.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\RequestsModule.cs:line 0
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

#### Problem Description:

Attempting to view movie requests comes up blank, similar issue described here: [issues/1023](https://github.com/tidusjar/Ombi/issues/1023)

#### Reproduction Steps:

- Log in as admin
- Navigate to /requests
- Open TV Shows tab (works as expected)
- Open Movies tab (empty)

**Comment by CallMeRev** [comment]
i get the same but with tv shows , i can see all movie requests and nothing on tv shows , + as expected they dont download in sonarr
