### ISSUE TITLE
unable to login with any account, including admin

### ISSUE THREAD

**Issue by dejected1** [tidusjar/Ombi#1451]
#### Ombi Version:

V v2.2.0

#### Media Sever:

Plex

#### Operating System:
windows 10 x64

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

unable to log into long standing installation of ombi with any account. 

#### Reproduction Steps:

the admin accounts or any other account. the login page pops up and it takes my user id but when i type in the password on the next page it just sits there. Tried with 3 different accounts.

**Comment by Jose-Linares** [comment]
Same thing happening to me. I updated Plex and then I couldn't access to Obmi using any user.

**Comment by snickbit** [comment]
I'm experiencing the same issue. You can login by going to /login instead of /userlogin. I put a link in my landing page to make it easier.

**Comment by tidusjar** [comment]
What are in the logs?

**Comment by tidusjar** [comment]
Plex is down for maintenance
