### ISSUE TITLE
No visual error message displayed in browser when Auth is invalid

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#1452]
#### Ombi Version:

Application Version:	2.2.1678
Branch:	Stable
Log Level:	Info
Database Location:	C:\Ombi\PlexRequests.sqlite
Running Directory:	C:\Ombi

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

PLEX PMS Version 1.7.5.4035 

#### Operating System:

OS:	Windows 8/Windows Server 2012 X64

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
No errors relating to this issue are present in the LOGS.
```

#### Problem Description:

No visual error is desplayed in the browser if auth creds are wrong.  You can put in ANY user, then put in ANY password, as soon as you click LOG IN, the button will turn green, but no visual error is displayed. 

#### Reproduction Steps:

Go to OMBI log in page, input bad auth creds. click LOG IN

**Comment by PotatoQuality** [comment]
Knowing bug, will not be fixed. We focussing now on V3
