### ISSUE TITLE
TV Series : season/episode request usless due to sonarr monitor 

### ISSUE THREAD

**Issue by CallMeRev** [tidusjar/Ombi#1453]
#### Ombi Version:

V 12.2.1810 

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Operating System:

Windows Server 2012

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Hello, on the sonarr settings i see you get the default set root directory for series, shouldnt there be a filed that ges the default monitor option ? Because else the episode request is usless since its beeing added with monitor on on sonarr so it downloads the hole thing , Im i missing something ?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by ZBrisson** [comment]
Just thought I would mention I am having I believe the same thing. If I request the latest season for a show or pick a specific season ombi add's it, but Sonarr takes that request and searches for every single episode in the show.  

Sonarr Version
    2.0.0.4753
Mono Version
    5.0.1.1
Ombi Version
Application Version: 	2.2.1678

I have switched my Ombi log file to info to see if Ombi is sending the right request. CallMeRev mentions sonarr monitored status and each tv show is set to monitored with the seasons that I picked as monitored, but sonarr then searchs for all seasons. 

Sonarr log. 

`17-7-4 11:06:40.9|Info|AddSeriesService|Adding Series [78901][Supernatural] Path: [/home/plex/local_storage/series/Supernatural]
17-7-4 11:06:40.9|Info|RefreshSeriesService|Updating Info for Supernatural
17-7-4 11:06:41.4|Info|RefreshEpisodeService|Starting episode info refresh for: [78901][Supernatural]
17-7-4 11:06:41.5|Info|RefreshEpisodeService|Finished episode refresh for series: [78901][Supernatural].
17-7-4 11:06:41.5|Info|DiskScanService|Scanning disk for Supernatural
17-7-4 11:06:41.6|Info|DiskScanService|Completed scanning disk for Supernatural
17-7-4 11:06:41.6|Info|SeriesScannedHandler|[Supernatural] was recently added, performing post-add actions
17-7-4 11:06:42.0|Info|MediaCoverService|Downloading Fanart for [78901][Supernatural] http://thetvdb.com/banners/fanart/original/78901-104.jpg
17-7-4 11:06:42.2|Info|EpisodeSearchService|Performing missing search for 264 episodes
17-7-4 11:06:42.2|Info|NzbSearchService|Searching 2 indexers for [Supernatural : S01]
17-7-4 11:06:42.5|Info|MediaCoverService|Downloading Banner for [78901][Supernatural] http://thetvdb.com/banners/graphical/78901-g47.jpg
17-7-4 11:06:42.6|Info|MediaCoverService|Downloading Poster for [78901][Supernatural] http://thetvdb.com/banners/posters/78901-35.jpg
17-7-4 11:06:42.8|Info|MetadataService|Series folder does not exist, skipping metadata creation
17-7-4 11:06:51.9|Info|DownloadDecisionMaker|Processing 319 releases
17-7-4 11:07:07.3|Info|Nzbget|Adding report [Supernatural.S01.PROPER.1080p.BluRay.X264-FLHD] to the queue.
17-7-4 11:07:09.4|Info|DownloadService|Report sent to NZBGet. Supernatural.S01.PROPER.1080p.BluRay.X264-FLHD
17-7-4 11:07:09.8|Info|NzbSearchService|Searching 2 indexers for [Supernatural : S02]`

**Comment by PotatoQuality** [comment]
No we don't need a default monitor option in the settings page.
When a user request a single episode the system ask sonarr to monitor that only ep not the whole episode.

@ZBrisson that is a sonarr bug. they fixed it already but is not pushed yet to the stable branch.
