### ISSUE TITLE
Issue list is cleaned

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1455]
I just cleaning up the issue list beceause we focussing now on the V3 release.
The V3 is a complete re-write of the ombi code.
It will be a fresh start with better linux support and it will be more stable.

V2 will not be supported anymore, pleas wait for the big V3 release.

**Comment by DirtyCajunRice** [comment]
V2 is not supported and V3 is not out? So every single person is in limbo?

**Comment by PotatoQuality** [comment]
@dirtyCajunRice we need our time to make a mutch better version than v2. Because our free time is limited we decided to use the free to focussing on v3. Jamie told already that there will be not a update anymore for v2. So its a little bit useless to keep bug report open for that version because we make a complete rewrite. Feel free to help us out with the new version.

**Comment by tidusjar** [comment]
@DirtyCajunRice Please keep in mind that all support is done in mine and @PotatoQuality 's free time.
If you are willing to pay for support then I will be happy to help. But to be fair, all bugs raised in the last month or two I've not done anything about unless they are stopping everyone from using the application.

This is a open source project and not a full time job, we do not get paid for this.

**Comment by DunnCloud** [comment]
keeping doing great things team. i noticed the instability of running on linux and using windows to reach out and perform ombi operations. hope all is well, it's eric by the way. using linux more and more,  but thought ombi was better the other way around. when v3 is out, i'll drop a big donation.

**Comment by francesco2013** [comment]
Let's wait for this V3. The V2 keeps on crashing randomly and it is rather unstable I would say. Thank you guys for your great work I wait the V3 :)

**Comment by francesco2013** [comment]
Any ETA guys ?

**Comment by PotatoQuality** [comment]
Its done when its done. No eta yet

**Comment by francesco2013** [comment]
thanks man 👍

**Comment by tidusjar** [comment]
@francesco2013 As I've mentioned to other people,
I cannot give a ETA as people will treat it like a deadline, since this is not my job I cannot commit to such a thing. Other things in life has a higher priority.

But what I can assure you that I am spending almost all of my spare/free time on the rewrite and it is progressing.

**Comment by francesco2013** [comment]
Thank you very much Jamie much appreciated guys :)

**Comment by jfairham1** [comment]
Can't wait for V3, keep up the good work. V2 is stable for me but uses 12G of RAM -.-
