### ISSUE TITLE
User Management Tasks

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1456]
- [x] Add forgotten password functionality
    - [x] Need to make sure email settings are setup, then create a token with an expiry of 7 days
    - [x] When clicked the link in the email they will get redirected to a reset password page.
    - [x] This requires us to have an email address for the user

- [x] Add the ability for the logged in user to change their password
- [x] Add the "Remember Me" functionality

- [x] Rework the user management page
    - [x] It's not really useable, maybe when we click edit it navigates to a new page where we can customize the user rather than a modal popup
- [x] Add the ability to make "bulk" changes against the users
- [x] Create a settings page for the user management
    - We should add the option (boolean) to import users from Plex/Emby depending what ones are enabled
- [x] Create the Plex user importer scheduled tasks (for the above to actually import the users)
- [x] Create the Emby user importer scheduled tasks (for the above to actually import the users)

**Comment by roly445** [comment]
Are you considering IdentityServer?

**Comment by tidusjar** [comment]
I have considered switching. I did attempt switching but ran into a few issues (due to use using SQLite).

But you are welcome to implement Identity. It's something that will benefit us.

**Comment by roly445** [comment]
So just a simple Identity server, then at a later stage allow users to map a Plex user to that account?  That might be a way around the Plex Pass user account issue.
I don't know enough about Emby so I don't know about user mapping with that system.

**Comment by tidusjar** [comment]
Yeah there would have to be a reference to the Plex user id on the users table. I like it!

**Comment by tidusjar** [comment]
@roly445 We are using Identity Server 4.

**Comment by PotatoQuality** [comment]
@tidusjar will there a cronjob running to update the reference in identity server 4 when a user changes his username? (for example)

**Comment by tidusjar** [comment]
Yeah I'll be adding something like that

**Comment by PotatoQuality** [comment]
Nice!

one more thing:

The bigest problem in the V2 version is that you can't config the permission **before** ombi imports the user accounts. Is it possible that you can config the permissions for the normal users **before** ombi imports and set the permissions? Maybe in the quick install page?

**Comment by tidusjar** [comment]
There will be a setting that you need to enable for the users to be imported. It's disabled by default, if the admin enables it then we will import the users.

This allows the admin to setup any defaults before they get imported.

**Comment by ScousePete** [comment]
Remember me, please!

**Comment by gold007eye** [comment]
@tidusjar Let me know if you need help with any testing of V3 for bugs thoughts ideas, etc. :)
