### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1458]
- Finish the landing page

The landing page is kinda half done, it needs proper styling (Im useless at it) or maybe an overhaul

**Comment by Burry** [comment]
Borrowing from the Plex look a little, here's an idea for the landing page. Would be great if admins could customize the logo and/or page markup + CSS

![ombi landing](https://user-images.githubusercontent.com/1909420/28553352-598ad528-70b0-11e7-9bfc-2dc2e646704f.png)

**Comment by Burry** [comment]
Maybe unrelated, but here's a look for a new log in page that could use js to appear when the "Open Ombi" button is selected.

![ombi login](https://user-images.githubusercontent.com/1909420/28553438-dd150148-70b0-11e7-9e02-4778fb8bb4b0.png)

**Comment by tidusjar** [comment]
That's a good idea. 

I don't have any plans for allowing customizing the CSS, but the logo and application name is already customizable.

**Comment by tidusjar** [comment]
The Landing page and login page have been reworked!
The background will be random movie and tv backgrounds that are customizable

Login:
![](https://files.gitter.im/tidusjar/Ombi/fW3E/image.png)


Landing Page:
![](https://files.gitter.im/tidusjar/Ombi/9RAX/image.png)

**Comment by tidusjar** [comment]
Finished!

**Comment by leveraged7** [comment]
FUCKING SEXY!

**Comment by tidusjar** [comment]
Glad you like it @leveraged7 !! :)
