### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1459]
We need to add more notifications:

 - [x] Slack
 - [x] Mattermost
 - [x] Pushbullet
 - [x] Pushover
 - [ ] Telegram

**Comment by noahruss** [comment]
growl notifications would be nice!

**Comment by tidusjar** [comment]
Pushbullet done @jamjop Growl as in the macOS application?

**Comment by tidusjar** [comment]
Going to close this, Telegram can come with a new update.

**Comment by aaomidi** [comment]
Is the telegram feature implemented or do you still need help with that?

**Comment by tidusjar** [comment]
@aaomidi I have not yet added telegram notifications, please feel free to implement it if you wish!
