### ISSUE TITLE
Condition not met

### ISSUE THREAD

**Issue by pmow** [tidusjar/Ombi#1466]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.5.7.4016

#### Operating System:

Linux (Ubuntu)
#### Mono Version (only if your not on windows)

4.8.0

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Invalid Path	Ombi.Core.MovieSender	Error	7/3/2017 7:31:52 PM
[lots of these]
```

#### Problem Description:

App is closing.  The log indicates an invalid path, but it's valid and accessible from the user running Ombi (my user, folder is within home).

#### Reproduction Steps:

I'm not really sure, as it crashed when I wasn't using it.

**Comment by tidusjar** [comment]
It's an invalid path setup on Radarr. Make sure your Radarr settings are correct.
