### ISSUE TITLE
Request: Login Page

### ISSUE THREAD

**Issue by Fiala06** [tidusjar/Ombi#1468]
I know your suppose to use the feathub link but it hasn't work for the last 3 days I've checked  (via home wifi or cell data) so figured I would just post here. 

Anyways my only issue with ombi is the login page which hopefully will be changed down the road. (of if you could tell me how) The username and password fields should be on the same page and the delay between them is annoying to me. Due to being on separate pages, you can't use auto logins etc. There are also no "incorrect password" warnings so you can never tell if its working. For the technology challenged folks I allow access to, this has been an issue. 

Anyways thanks and keep up the good work!

**Comment by PotatoQuality** [comment]
Hi, 

We dropped the support of v2. We working hard on v3. Pleas wait for the v3  release
