### ISSUE TITLE
Broken indexing?

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/Ombi#1470]
#### Ombi Version:

V 2.2.1

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

W10

#### Problem Description:

After updating to 2.0+ Ombi no longer detects/indexes media. No media is listed as available resulting in a flood of requests for media that already exists.

#### Reproduction Steps:

Updated to 2.2.1, waited for indexing banner to go away, searched for existing media.

**Comment by tidusjar** [comment]
Need some logs...

**Comment by Grimshad** [comment]
>
> Requests that will be updated count 0 | Ombi.Services.Jobs.PlexAvailabilityChecker | Debug | 7/13/2017 9:09:46 PM
> -- | -- | -- | --
> Did not find any libraries in Plex. | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:33 PM
> Done albums | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:33 PM
> Done TV | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> Done movies | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> done all that, moving onto the DB now | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> Item count 0 | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> Going through all the items now | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> Going through sections now | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:05:32 PM
> There has been a API Exception when attempting to get the Plex Libraries | Ombi.Api.PlexApi | Error | 7/13/2017 9:05:32 PM
> Exception when calling GetLibrarySections for Plex, Retrying 00:00:30 | Ombi.Api.PlexApi | Error | 7/13/2017 9:05:02 PM
> Exception when calling GetLibrarySections for Plex, Retrying 00:00:10 | Ombi.Api.PlexApi | Error | 7/13/2017 9:04:52 PM
> Exception when calling GetLibrarySections for Plex, Retrying 00:00:05 | Ombi.Api.PlexApi | Error | 7/13/2017 9:04:47 PM
> Getting Lib sections | Ombi.Services.Jobs.PlexContentCacher | Debug | 7/13/2017 9:04:46 PM
> 
>

**Comment by tidusjar** [comment]
Ombi cannot talk to Plex. Check your settings

**Comment by Grimshad** [comment]
I checked my plex settings, it's all correct. Just in case, I removed all my plex settings and re-added them. Used the test button and the connection is successful. Same result.

**Comment by Grimshad** [comment]
I just realized what changed. I recently added a home user to PMS and now when I login to plex it also requires a pin. I don't think ombi has a check for this or the ability to handle this yet. This has turned into a whole other ticket. Ombi signs in successfully but can't get past the pin page.

**Comment by Grimshad** [comment]
I just realized what changed. I recently added a home user to PMS and now when I login to plex it also requires a pin. I don't think ombi has a check for this or the ability to handle this yet. This has turned into a whole other ticket. Ombi signs in successfully but can't get past the pin page.
