### ISSUE TITLE
why was issue closed?

### ISSUE THREAD

**Issue by DaveG9856** [tidusjar/Ombi#1472]
Ombi Version:

V 2.2.1678

Update Branch:

Stable

Media Sever:

Plex

Media Server Version:

1.7.6.4058

Operating System:

Ubuntu 16.0.4

Mono Version (only if your not on windows)

5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)

Applicable Logs (from /logs/ directory or the Admin page):

TV:
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) [0x00058] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x00012] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0007f] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 at Ombi.Api.ApiRequest.ExecuteJson[T] (RestSharp.IRestRequest request, System.Uri baseUri) [0x00051] in <Removed>:0 at Ombi.Api.SonarrApi+<>c__DisplayClass9_0.b__1 () [0x0000b] in <2a63c45e97a245c1bf3c2df5f23972c5>:0 at Polly.Policy+<>c__DisplayClass8_0`1[TResult].b__0 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.RetrySyntax+<>c__DisplayClass14_0.b__1 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at (wrapper delegate-invoke) System.Func`1[Polly.Utilities.EmptyStruct]:invoke_TResult () at Polly.Retry.RetryEngine.Implementation[TResult] (System.Func`1[TResult] action, System.Collections.Generic.IEnumerable`1[T] shouldRetryExceptionPredicates, System.Collections.Generic.IEnumerable`1[T] shouldRetryResultPredicates, System.Func`1[TResult] policyStateFactory) [0x00098] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.RetrySyntax+<>c__DisplayClass14_1.b__0 (System.Action action, Polly.Context context) [0x00027] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.Policy.Execute[TResult] (System.Func`1[TResult] action, Polly.Context context) [0x0002c] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.Policy.Execute[TResult] (System.Func`1[TResult] action) [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Ombi.Api.SonarrApi.AddSeries (Ombi.Api.Models.Sonarr.SonarrAddSeries series, System.String apiKey, System.Uri baseUrl) [0x000ae] in <removed>:0

Movies:

Newtonsoft.Json.JsonReaderException: JSON integer 2781505847 is too large or small for an Int32. Path 'revenue', line 1, position 1147. at Newtonsoft.Json.JsonTextReader.ParseNumber (Newtonsoft.Json.ReadType readType) [0x00254] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonTextReader.ReadNumberValue (Newtonsoft.Json.ReadType readType) [0x00203] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonTextReader.ReadAsInt32 () [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00267] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 at Ombi.Api.ApiRequest.ExecuteJson[T] (RestSharp.IRestRequest request, System.Uri baseUri) [0x00051] in <>:0 at Ombi.Api.TheMovieDbApi.GetMovieInformationWithVideos (System.Int32 tmdbId) [0x0005f] in <2a63c45e97a245c1bf3c2df5f23972c5>:0

Problem Description:
radar : 0.2.0.778
sonarr :2.0.0.4855

fresh install ( right down to os ) ombi connects to sonarr/radarr fine grabs profiles etc.when I go to add a request I get a red box "error from sonarr"
I've currently had to disable radarr and sonarr so requests can still be made.

Reproduction Steps:

make a request on my emby install?
issue not solved

**Comment by PotatoQuality** [comment]
![image](https://user-images.githubusercontent.com/2944704/28223817-1fb782e6-68cd-11e7-93f4-eca02e969aba.png)

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455
