### ISSUE TITLE
adding old movies with Radarr

### ISSUE THREAD

**Issue by crazyman143** [tidusjar/Ombi#1475]
Not sure if this has come up already (probably) but since radarr and sonarr only search rss feeds on a schedule, they don't find old releases automatically. Not really an issue with Sonarr, but when folks use ombi to request older movies, I want to ensure Radarr grabs them. 

When adding via Radarr interface, there's a button to "add and scan." When movies are added to ombi will it utilize this function? Or will it just add the movie using the regular button that doesn't search? In this case older movies will never be found.

!! Version 2.X is not supported anymore. Pleas don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
Ombi fires a add and search to radarr.

**Comment by crazyman143** [comment]
thanks
