### ISSUE TITLE
Ombi cannot use plex API if local users exist

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/Ombi#1476]
Ombi Version:

V 2.2.1

Update Branch:

Stable

Media Sever:

Plex

Operating System:

W10

Problem Description:

Ombi cannot index the plex library if there is a local user other than the account owner. Ombi cannot detect when a pin is required or enter the pin so it is denied access.

Reproduction Steps:

Link ombi to a plex server, then on the plex server create a local user or guest. After this whenever you login to the plex server you are required to enter a pin for the owner account.

**Comment by tidusjar** [comment]
I don't plan to change this in V2. This is not a supported scenario
