### ISSUE TITLE
Nancy.ViewEngines.AmbiguousViewsException

### ISSUE THREAD

**Issue by Logvin** [tidusjar/Ombi#1477]
#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Operating System:

Ubuntu 17.04

#### Mono Version (only if your not on windows)

4.6.2

#### Problem Description:

Ubuntu Linux 17.04, clean install. Mono is able to start Ombi, but always returns a server 500 error. This occurs when I go to http://ipaddress:3579
I have the port opened in the firewall. I did not set up as a service yet. To start the app, I used the following line:

> /usr/bin/mono /path/to/ombi/Ombi.exe

```
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.AmbiguousViewsException: This exception was thrown because multiple views were found. 2 view(s):
	/index.html
	/Index.cshtml
```

**Comment by PotatoQuality** [comment]
See the text that you delete in the issue format. 

Version 2 is not suported anymore. Pleas dont open a issue for it.

**Comment by Logvin** [comment]
I apologize, but I don't understand what that means. I downloaded the newest version available, how is it not supported?

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455

**Comment by tidusjar** [comment]
Are you sure that you extracted it to a new clean location? You also
unblocked the zip file?

**Comment by Logvin** [comment]
Do I need to unblock in Ubuntu?

**Comment by tidusjar** [comment]
Oh no. You 100% sure it was a clean dir,?

**Comment by Logvin** [comment]
Yes.i created a user specifically for it and installed to its home
directory.
