### ISSUE TITLE
Newsletter only sending Movies

### ISSUE THREAD

**Issue by jbalki** [tidusjar/Ombi#1481]
#### Ombi Version
V 2.2.1851
#### Update Branch:
Early Access Preview
#### Operating System:
Mono
#### Log Level:
Error

Newsletter process runs, but only sends the latest movies and not TV shows. I have advanced searching enabled and also Enable Episode Searching enabled but still just sends movies only.

I have checked every option but cannot see what the issue is. I have tried both stable branch and EAP on both Windows and Linux. Also running Plex.

Here is the the error log:
System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source) <0x4090c5c0 + 0x000ea> in :0 at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml (IEnumerable`1 recentlyAddedMovies, System.Text.StringBuilder sb) <0x4111c250 + 0x0092c> in :0

**Comment by jbalki** [comment]
This is the message from the error log:

System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source) <0x4090c5c0 + 0x000ea> in :0 at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateMovieHtml (IEnumerable`1 recentlyAddedMovies, System.Text.StringBuilder sb) <0x4111c250 + 0x0092c> in :0	Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter	Error	8/4/2017 12:01:48 PM

**Comment by tidusjar** [comment]
I don't plan to fix this. Please see #1455
