### ISSUE TITLE
Display Name Missing From Sent Email

### ISSUE THREAD

**Issue by DivinityCycle** [tidusjar/Ombi#1482]
Currently, all email generated by Ombi is getting sent with no display-name set in the header. This is the "Friendly Name" which clients like Gmail use to match against the user's contacts list. Without this being set, all email sent by Ombi shows up with the full email address displayed in the "From" field and it's not possible to nicely integrate it on the client end.

I'm more of a Python guy so my reading of how this works could be very incorrect, but it looks like EmailNotificationSettings contains a string named "Sender" which is used to fill in the relevant details when building the email.
Because the settings as they are stored in the SQLite database are encrypted, it's not easy for me to test this out, but it looks like the current header is getting built with the sender info set to:
whatever@somedomain.com

To make the email appear normally to the client, it should be more like this:

From: Some Name <whatever@somedomain.com>

Where "Some Name" is the display name desired by the user, and whatever@somedomain.com is the "from" address. It looks like simply filling the Sender setting with a string in the above format would probably be all that's needed, but I can't easily test this. Ombi's configuration page will not let the user set the string as such because it's doing input validation for "just an email address".

**Comment by tidusjar** [comment]
Hello! I am aware of this and it will be fixed in V3 :)

**Comment by DivinityCycle** [comment]
Glad to know it'll be changed in an upcoming version! Ombi is awesome!
