### ISSUE TITLE
Upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1486]
https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/

**Comment by FlynnLives** [comment]
does the dnc 1.x branch work on 2.0 at all?

**Comment by tidusjar** [comment]
I'm not 100% following you...

**Comment by FlynnLives** [comment]
Theres a DotNetCore release on the main project page, does this work under DotNetCore v2 or does it only work on v1? 

I ask as Microsoft only has v2 available for Debian 9. I wouldn't mind testing it out

**Comment by tidusjar** [comment]
I'm pretty sure .net core and standard 2 is backwards compatible. But you
do not need the .net core framework installed for Ombi to run. All the
dependencies are within the zip

**Comment by FlynnLives** [comment]
Ah ok. I can’t get it to run on Debian 9, even with v2.0 installed 

./Ombi
Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.debian.8-x64.microsoft.netcore.runtime.coreclr', version: '1.1.2', path: 'runtimes/debian.8-x64/native/sosdocsunix.txt'

**Comment by tidusjar** [comment]
Please remember this is still in development. Currently it requires Debian 8

**Comment by tidusjar** [comment]
DONE!
