### ISSUE TITLE
V3 Systemd

### ISSUE THREAD

**Issue by jscottdouglas** [tidusjar/Ombi#1487]
Can't seem to get this to start in systemd, works fine running from console but i get errors that args are missing when trying to run as a service on debian. 

Version 3.X is not supported anymore. Please don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by jscottdouglas** [comment]
Sorry you make no sense are you saying v3 and v2 are no longer supported? My issue is with 3.x

**Comment by tidusjar** [comment]
V3 is still in development.
