### ISSUE TITLE
ssl reverse proxy help

### ISSUE THREAD

**Issue by stevens-r** [tidusjar/Ombi#1489]
trying to make ombi accessible at www.domain.ca/ombi it kind of works it redirects to www.domain.ca/userlogin but its just says not found id like www.domain.ca to go to muximux and www.domain.ca/ombi to go to ombi with https

if i try to make it work through www.domain.ca   ombi works fine its the /ombi after proxypass and proxypassreverse thats screwing it up leaving it at just a / it works fine ive spent hours searching and come up with nothing

/etc/apache2/sites-available/default-ssl.conf
```
`<IfModule` mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin ****
                ServerName domain.ca
                ServerAlias www.domain.ca

                DocumentRoot /var/www/Muximux


                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass /ombi http://www.domain.ca:3579/
                ProxyPassReverse /ombi `http://www.domain.ca:3579/

```

#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex
#### Operating System:

ubuntu 16.04

**Comment by tidusjar** [comment]
Did you put the base URL to Ombi in the settings?

**Comment by stevens-r** [comment]
i put www.domain.ca/ombi as the base url just now i cant access ombi at all now

**Comment by tidusjar** [comment]
The base URL should have just been ombi...

**Comment by stevens-r** [comment]
is there a config file i can change it in

**Comment by stevens-r** [comment]
just found this https://github.com/tidusjar/Ombi/issues/825 thanks for the help @tidusjar
