### ISSUE TITLE
gui not loading with reverse proxy base url

### ISSUE THREAD

**Issue by stevens-r** [tidusjar/Ombi#1490]
when i set the base url to request       www.domain.ca/request it loads this
[Ombi.pdf](https://github.com/tidusjar/Ombi/files/1236828/Ombi.pdf)

then if i log in i get this 
[500.pdf](https://github.com/tidusjar/Ombi/files/1236830/500.pdf)
 
apache2 reverse proxy
        
```
                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass /request http://www.domain.ca:3579/
                ProxyPassReverse /request http://www.domain.ca:3579/

```

#### Ombi Version:

V 2.2.1678

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

**Comment by tidusjar** [comment]
Restart Ombi. It states in the settings to restart it after changing the base URL.

**Comment by stevens-r** [comment]
@tidusjar restsrting ombi does nothing to solve this issue after a reboot it just goes to 404 not found and i have to reinstall ombi
