### ISSUE TITLE
Gui not loading with reverse proxy base url

### ISSUE THREAD

**Issue by stevens-r** [tidusjar/Ombi#1491]
when i set the base url to request www.domain.ca/request it loads this
[Ombi.pdf](https://github.com/tidusjar/Ombi/files/1237103/Ombi.pdf)

then if i log in i get this
[500.pdf](https://github.com/tidusjar/Ombi/files/1237104/500.pdf)

Restarting ombi and the computer doesnt solve the issue 
after the restart of ombi to only shows this 
[404.pdf](https://github.com/tidusjar/Ombi/files/1237106/404.pdf)

apache2 reverse proxy

                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass /request http://www.domain.ca:3579/
                ProxyPassReverse /request http://www.domain.ca:3579/

Ombi Version:

V 2.2.1678

Update Branch:

Stable

Media Sever:

Plex

Operating System

Ubuntu 16.04

**Comment by tidusjar** [comment]
Please stop opening new issues. 

You need the base URL in Ombi set to "request". 

Restart. 

Then access Ombi via http://localhost:3579/request

**Comment by stevens-r** [comment]
@tidusjar ok so i installed ombi fresh changed base url to request [Ombi base url.pdf](https://github.com/tidusjar/Ombi/files/1237121/Ombi.base.url.pdf) and restarted ombi with `sudo systemctl restart ombi` and i still get 404
[404.pdf](https://github.com/tidusjar/Ombi/files/1237122/404.pdf)

**Comment by stevens-r** [comment]
managed to find a answer elsewhere had to  add request at the end of the proxypass and reverse
`           ProxyRequests Off
            ProxyPreserveHost On
            ProxyPass /request http://www.domain.ca:3579/request
            ProxyPassReverse /request http://www.domain.ca:3579/request`

**Comment by PotatoQuality** [comment]
version 2.2 id not supported anymore.
stop spamming
