### ISSUE TITLE
Ombi UI and Services Errors

### ISSUE THREAD

**Issue by Comfubar** [tidusjar/Ombi#1494]
#### Ombi Version
V 2.2.1851
#### Update Branch:
Stable
#### Operating System:
Windows 10
#### Log Level:
Error
Upon adding Shows and Movies Ombi tells me it succeeds but notification emails tell me it fails and never adds any requests or adds to a queue

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Api.CouchPotatoApi.AddMovie(String imdbid, String apiKey, String title, Uri baseUrl, String profileId) in C:\projects\requestplex\Ombi.Api\CouchPotatoApi.cs:line 63 at Ombi.Core.MovieSender.SendToCp(RequestedModel model, CouchPotatoSettings settings, String qualityId) in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 106 at Ombi.Core.MovieSender.d__23.MoveNext() in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 0 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Ombi.Services.Jobs.FaultQueueHandler.ProcessMovies(RequestedModel model) in C:\projects\requestplex\Ombi.Services\Jobs\FaultQueueHandler.cs:line 222 ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Api.CouchPotatoApi.AddMovie(String imdbid, String apiKey, String title, Uri baseUrl, String profileId) in C:\projects\requestplex\Ombi.Api\CouchPotatoApi.cs:line 63 at Ombi.Core.MovieSender.SendToCp(RequestedModel model, CouchPotatoSettings settings, String qualityId) in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 106 at Ombi.Core.MovieSender.d__23.MoveNext() in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 0<--- 	Ombi.Services.Jobs.FaultQueueHandler	Error	8/25/2017 9:15:50 PM

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Api.CouchPotatoApi.AddMovie(String imdbid, String apiKey, String title, Uri baseUrl, String profileId) in C:\projects\requestplex\Ombi.Api\CouchPotatoApi.cs:line 63 at Ombi.Core.MovieSender.SendToCp(RequestedModel model, CouchPotatoSettings settings, String qualityId) in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 106 at Ombi.Core.MovieSender.d__23.MoveNext() in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__135.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 981	Ombi.UI.Modules.SearchModule	Fatal	8/25/2017 9:27:00 PM

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Api.CouchPotatoApi.AddMovie(String imdbid, String apiKey, String title, Uri baseUrl, String profileId) in C:\projects\requestplex\Ombi.Api\CouchPotatoApi.cs:line 63 at Ombi.Core.MovieSender.SendToCp(RequestedModel model, CouchPotatoSettings settings, String qualityId) in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 106 at Ombi.Core.MovieSender.d__23.MoveNext() in C:\projects\requestplex\Ombi.Core\MovieSender.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Ombi.UI.Modules.SearchModule.d__135.MoveNext() in C:\projects\requestplex\Ombi.UI\Modules\SearchModule.cs:line 981	Ombi.UI.Modules.SearchModule	Fatal	8/25/2017 10:10:45 PM

**Comment by Comfubar** [comment]
Not entirely sure what is causing this would just like to fix it OMBI searches perfectly fine and finds everything just requesting is fine then they all send errors to my phone notifications and then add them to the Request Fault Queue

**Comment by tidusjar** [comment]
I'm not going to fix this as consentrating on v3
