### ISSUE TITLE
Ombi not recognizing Radarr

### ISSUE THREAD

**Issue by aaronth07** [tidusjar/Ombi#1495]
Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 2.2.1 (It said that you don't support 2.x versions anymore, but I couldn't find a download link to a 3.x version)

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Exception when calling SystemStatus for Sonarr, Retrying 00:00:10

```

#### Problem Description:

Whenever I approve a request, it says it is approved but that it was not passed to Couchpotato/watcher as they are not configured. I don't have Couchpotato/watcher configured as I use Radarr (and have it set up correctly).

#### Reproduction Steps:

Approve any request.

**Comment by dhruvb14** [comment]
This happens sometimes to me also. Go into Radarr settings, change one of the settings and hit save, then change it back and hit save again. you should be all fixed...
