### ISSUE TITLE
Request Token always says Incorrect username or password

### ISSUE THREAD

**Issue by hocplyr98** [tidusjar/Ombi#1498]
Whenever I put in my Plex info in the wizard and hit Request Token, it takes forever for anything to happen, then tells me my username or password is invalid, even though it's not. 

Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by hocplyr98** [comment]
Apparently had DNS issues which caused Ombi and a slew of other websites to fail to load. Closing.

**Comment by PotatoQuality** [comment]
pleas dont ignore the text:Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See #1455 for more information


its there die a reason....
