### ISSUE TITLE
Cannot change port

### ISSUE THREAD

**Issue by ersan** [tidusjar/Ombi#1501]
#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Media Server Version:

N/A

#### Operating System:

Debian

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm not sure if this is supposed to work yet or not but changing the port in Ombi configuration doesn't seem to do anything.  I Ctrl+C ombi and then start it again and it is still running on port 5000

#### Reproduction Steps:

Change port in Ombi settings, Ctrl+C, start Ombi again.

**Comment by tidusjar** [comment]
This is still in development. I am aware of this. 

Please do not raise bugs for V3 yet.
