### ISSUE TITLE
Unable to connect to EMBY server.net core

### ISSUE THREAD

**Issue by alz41** [tidusjar/Ombi#1503]
Using OMBI .net core builds im unable to get it to connect to EMBY server.net core

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

development

#### Media Sever:

Emby

#### Media Server Version:

.net core

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
Hey,

pleas use Version 2.

Version 3 is not ready for using it.
