### ISSUE TITLE
Suggestion: Checkbox to disable search suggsetions

### ISSUE THREAD

**Issue by scottocs11** [tidusjar/Ombi#1504]
Could a setting/checkbox be added to enable or disable search suggestions?

Thanks!

**Comment by tidusjar** [comment]
Why wouldn't you want it?

**Comment by scottocs11** [comment]
So that people have to know what they want to suggest. Keeps the amount of requests lower.

**Comment by qazero** [comment]
+1 for this! Can you please implement this?

**Comment by Lownin** [comment]
I would also like this.  People go on a request spree and I'd rather people only request things that they had thought to request explicitly.

**Comment by godofjesters** [comment]
i'm also looking for this as an idea. suggestion overload for those requesting is request overload for us. not only that but its a little too much right out of the gate for when first logging into ombi
