### ISSUE TITLE
Issues for items that already exist in library

### ISSUE THREAD

**Issue by sheldontking** [tidusjar/Ombi#1505]
Application Version: | 2.2.1678
OS: | Windows 7/Windows Server 2008 R2
System Version: | 4.0.30319.42000
Branch: | Stable
Log Level: | Error
Database Location: | C:\Ombi\Ombi.sqlite
Running Directory: | C:\Ombi
Plex 3.14.1

#### Problem Description:

Hello, I am having an issue submitting "issues" with items that already exist in the library that someone has not requested. Basically, you search for the movie and it says it is already requested. However, you can not click the link/button drop down to report an issue with the said already downloaded item. Hovering over the requested block changes your cursor to a red circle-slash sign.

![requested](https://user-images.githubusercontent.com/17148408/30250940-dde69822-9624-11e7-9c6e-7d4698a10faa.png)

#### Reproduction Steps:

See above

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455
