### ISSUE TITLE
Styles different in the CI Build

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1507]
No Idea why, cannot produce locally...

Some reason there are missing styles when building via AppVeyor... Using the same commands and Cake script locally the styles are fine...

Might need the master that is @MattJeanes assistance on this one.

**Comment by MattJeanes** [comment]
I'll take a quick look tomorrow if I can

**Comment by tidusjar** [comment]
@MattJeanes no problem, don't worry if you can't!

**Comment by MattJeanes** [comment]
What styles are different? Hard to see what's up if I don't know what's wrong lol

**Comment by PotatoQuality** [comment]
xD

**Comment by tidusjar** [comment]
Sorry Matt, should have explained.

If you search for a TV show e.g. Game Of Thrones while debugging for example it all looks good.

If you download the windows.zip file from here: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts and do the same, the styling is completely different.

Now I am using Cake for the build system, all the CI does is run the `build.ps1` file and it will publish all of the .zips.

**Comment by tidusjar** [comment]
Example or running locally
![waterfox_2017-09-16_22-03-11](https://user-images.githubusercontent.com/6642220/30516004-efcffbae-9b2a-11e7-8a91-905375b24473.png)


Example of the CI build output:
![waterfox_2017-09-16_22-01-40](https://user-images.githubusercontent.com/6642220/30516008-f81abb64-9b2a-11e7-9308-c8da5a27c949.png)
