### ISSUE TITLE
Nginx Auth_Request

### ISSUE THREAD

**Issue by solaris765** [tidusjar/Ombi#1509]
I've noticed that the Auth_request module from nginx, when used with ombi as a reverse proxy breaks the login page. When I try to login to ombi I can't get past the username page. I can just go back and forth with the username and banner page

Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
>Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.

**Comment by PotatoQuality** [comment]
why are they still users ignoring that text :/
