### ISSUE TITLE
NetflixCheck not working on newer shows

### ISSUE THREAD

**Issue by teekayzee** [tidusjar/Ombi#1511]
Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Search for The Defenders or even The Flash - none are showing the Netflix brand as available. I assume the API that OMBI is using is outdated :/

For reference - searching for Arrow works.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
why are you opening a issue and kust ignoring the text that is above you?

**Comment by PotatoQuality** [comment]
pleas explain what is dificult to understand the following text what jou are seeing when you open a issue.

> Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.
See #1455 for more information
