### ISSUE TITLE
Rewrite the Readme

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1512]
It's no longer relevant after v3 is released. We should rewrite this to reflect v3

**Comment by PotatoQuality** [comment]
I will going to re-write it

**Comment by tidusjar** [comment]
@PotatoQuality OK cool, let me know when you are doing it and I can review :)

**Comment by PotatoQuality** [comment]
@tidusjar done. I just make a few more things to support the open beta
