### ISSUE TITLE
V3 Beta Issues

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1513]
- [x] Allow user to pass in a directory where we store the database and logs 
- [x] reverse proxies do not work. Think it's to do with Angulars Base element. #[df1ab01 ](https://github.com/tidusjar/Ombi/commit/dd8f8493e115f00607d0a90a1fbaa4f18ec62190)(NEEDS TESTING)
- [x] Something is null 
-here:https://github.com/tidusjar/Ombi/blob/DotNetCore/src/Ombi/Controllers/External/PlexController.cs#L55

- [x] at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 81
2017-10-01 07:01:22.062 +00:00 [Error] Connection id ""0HL88J5VQTL4M"", Request id ""0HL88J5VQTL4M:0000000A"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by ydkmlt84** [comment]
I am on Ubuntu 16.04 and these are the issues that I have noticed:
- Login page doesn't show the custom logo very well.
- My servers are online but Landing Page shows 1 of 4 offline. I only have one Emby server.
- Settings-> User Management page is blank.
- Pushover test notification pop up doesn't show the correct verbage.
- Possible issue with auto updater not working when Ombi ran as a service.
- Did not receive a notification when an episode is requested...even as a non ADMIN user. it shows 
  pending approval after hitting the request button.

**Comment by tidusjar** [comment]
Allow user to pass in a directory where we store the database and logs

**Comment by AmansRevenger** [comment]
- [ ] (Test) user approved requests dont seem to get forwarded to Sonarr/Radarr

- [ ] On the Requests page , clicking one of the headers Movies/TV Shows switches the page content, but not the header 

will add as I see more, okay?

**Comment by Auwen** [comment]
On Windows 10, some issues and thoughts I've noticed:

**Issues** - Something broken
- [ ] The Send Reset Password Link uses "http://localhost" as the url domain. Haven't seen a way to customize that, making the link unusable for any other user but admin.
- [ ] Admin email notification is setup and working, but clicking on Send Welcome Email on a user, no email is sent, no notification is displayed. I assume this is a coming feature.
- [ ] Gmail SMTP requires an "insecure app password" (https://support.google.com/accounts/answer/185833?hl=en) when using Google two-factor authentication. However, when inputting the account password and not the "app password", Ombi says that the password is correct (it's not). Not sure how this could be handled in Ombi, or just a wiki page with a pointer to Google's documentation.
- [ ] Deny with a Reason button doesn't work, Deny does though.

**UI Tweaks** - Typos, small visual changes
- [ ] When testing Pushbullet during setup, the notification popup says "check the discord channel" instead of "pushbullet". I don't have the other systems to check theirs.
- [ ] Deny drop down on Requests page is extra large. See https://i.imgur.com/x7bawvv.png
- [ ] Report Issue drop down on Requests page shows incorrect text. See https://i.imgur.com/x7bawvv.png

**Suggestions** - Ways to improve user experience
- [ ] Application Name field in Customization should have a tooltip that states "Requires application restart", as should anything else that should.
- [ ] Favicon should be on transparent background
- [ ] User roles are not defined. Most are self explanatory, but what does Power User give?
- [ ] Just verifying, users will have their own Ombi passwords and not authenticate through Plex? If that's the case, it should be noted somewhere within Ombi at least for the Admin to let users know, but best if for users at logon. I could assume this will be noted in the Welcome email.

**Missing Feature** - Features present in V2 but not in V3. I assume these will be added later
- [ ] Users can see all other requests.
- [ ] Users cannot request a movie after someone else has. In theory this would mean that the second, third, etc. users would not get notified once the movie is available. 
- [ ] No rate limiting on requests. Please make the time variable: for example, I would like to limit to 7 Movie requests per week, and 1 TV Show per 2 weeks.
- [ ] No ability to filter views on Requests.

**Feature Request** - Features I've always wanted
- [ ] Unable to edit Issue reasons. (the default ones have never met my needs so I instruct all my users to choose Other)
- [ ] Ability to archive completed requests instead of remove. Keeps the Requests page clean, but keeps the history for users
- [ ] Import currently active requests from V2 so that those users get notified and don't have to 

I'll add more as I come across them.

**Comment by Jose-Linares** [comment]
- [ ] Allow imported users to login.

- [ ] Remove the option "Allow media server users to authenticate"

**Comment by jonfinley** [comment]
- [ ] notification that your not on the latest version

**Comment by PotatoQuality** [comment]
Beaware, the reported function is not finished yet.

**Comment by tidusjar** [comment]
@Auwen 

> Application Name field in Customization should have a tooltip that states "Requires application restart", as should anything else that should.

It doesn't need a restart, just need to refresh the page

>  User roles are not defined. Most are self explanatory, but what does Power User give?

There will be a button on all the settings pages to take you to a wiki entry on Github that will explain all of this.

> Just verifying, users will have their own Ombi passwords and not authenticate through Plex? If that's the case, it should be noted somewhere within Ombi at least for the Admin to let users know, but best if for users at logon. I could assume this will be noted in the Welcome email.

If they have been imported into Ombi from Plex/Emby then they will authenticate through Plex/Emby and they do not have a password on Ombi. (The authentication through 3rd party is not done yet)

**Comment by Auwen** [comment]
> It doesn't need a restart, just need to refresh the page

Hmm, could have sworn I did that. Maybe my browser was caching, or probably just crazy. I'll believe you and close.

> button on all settings pages to take to a wiki entry

Perfect!

> The authentication through 3rd party is not done yet

Ah! That makes sense on why my test user was having issues.

**Comment by PotatoQuality** [comment]
- [ ] Delete button in User Management isn't working (when you try to delete a user)

**Comment by PotatoQuality** [comment]
Found a critical bug in the user import job for plex, we need to support also special characters and spaces in usernames

warn: Microsoft.AspNetCore.Identity.UserManager[13]
      User 9b3c7ac7-5912-4551-b8fc-c54ae7433d35 validation failed: InvalidUserName.
fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2003]
      User name 'XX XX XX' is invalid, can only contain letters or digits.

**Comment by jonfinley** [comment]
Unable to trigger the update nor does the auto update seem to want to run.
```
Failed
An exception occurred during performance of the job.
System.IO.InvalidDataException

End of Central Directory record could not be found.

System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 194
```

**Comment by PotatoQuality** [comment]
Got some errors in the console log 

We are running on
D:\OmbiV3
Hosting environment: Production
Content root path: D:\OmbiV3
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Api.Api[1000]
      StatusCode: 429, Reason:
fail: Ombi.Schedule.Jobs.Radarr.RadarrCacher[2000]
      Failed caching queued items from Radarr
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.<EnterCriticalSectionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.<ExecuteSqlCommandAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Schedule.Jobs.Radarr.RadarrCacher.<CacheContent>d__11.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Radarr\RadarrCacher.cs:line 44

**Comment by jonfinley** [comment]
<img width="1504" alt="screen shot 2017-09-30 at 11 53 27 am" src="https://user-images.githubusercontent.com/23283167/31047337-9032fa64-a5d6-11e7-89f0-4b7e97b335e2.png">

Reverse Proxied, default image still go to domain.com/images versus domain.com/ombi/images

**Comment by Brentnall27** [comment]
Can confirm the reverse proxied image issue jonfinley posted above, seeing the same behaviour.

Also: Background image on home screen should stretch-to-fit instead of tile on large monitors.

![image](https://user-images.githubusercontent.com/3908975/31047378-662d9c3a-a601-11e7-9779-77de787a378c.png)

**Comment by PotatoQuality** [comment]
@Brentnall27 can you please use the issue format?
````- [ ] Short issue description  ````

**Comment by PotatoQuality** [comment]
- [ ] plexusers can't login with there e-mail adres instead of the username. (i was trying to make a workaround to at the e-mail adres like a Alias, also that didn't work :( )

**Comment by FalafelMuncher69** [comment]
- [ ] Discord notifications produce error:  
```
Failed to send Discord Notification
System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
```

**Comment by tidusjar** [comment]
@jonfinley Looks like the .gz file was malformed, does this keep happening for you?

**Comment by LettuceSnob** [comment]
- [ ] Using "run importer" under User Management Settings with "Import Plex Users" selected does not work. No errors in Ombi log, but browser console points to a query of `localhost:5000/request/api/v1/Emby/users` despite not having an Emby server added to Ombi
- [ ] The "run importer" feature should probably also be available by clicking the User Management header. It's currently only accessible via Settings --> Configuration --> User Management

**Comment by PotatoQuality** [comment]
@LettuceSnob did you check after hitting run importer button the tab usermanagement ?

**Comment by LettuceSnob** [comment]
@PotatoQuality Yes, I checked. No plex users were there.

**Comment by jscottdouglas** [comment]
Anyone get this to work as a service systemd?

**Comment by LettuceSnob** [comment]
@jscottdouglas yea

```
[Unit]
Description=Ombi
After=syslog.target network.target

[Service]
User=name
Group=name
Type=simple
WorkingDirectory=/opt/Ombi/
ExecStart=/opt/Ombi/Ombi
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by AcidRain999** [comment]
segmentation fault comes up whenever i run the program and browse to it from chrome on windows

"Segmentation fault" is all i get back from the program. it is running on debian.

**Comment by PotatoQuality** [comment]
@AcidRain999 can you provide use the whole error  in the error log?

its in ./logs

**Comment by AcidRain999** [comment]
i looked all over the Ombi directory and there is no logs folder or file called logs

**Comment by LettuceSnob** [comment]
@AcidRain999 I had the same problem earlier, but then it randomly appeared the next day. I suspect that the directory only creates itself the first time a log worthy event occurs, and then when it needs to write to a file, a path is created.

**Comment by tidusjar** [comment]
@AcidRain999 Please post a screenshot of the full error

**Comment by shawpe** [comment]
V3 email notifications (not tested others). shows as changing format of notification, but doesn't actually send email with those changes.

![untitled](https://user-images.githubusercontent.com/28063585/31076618-ffb13480-a772-11e7-81c7-f02f9f985a30.png)

![img_5237](https://user-images.githubusercontent.com/28063585/31077419-548e368a-a776-11e7-99af-87766447e41e.PNG)

**Comment by jonfinley** [comment]
`Looks like the .gz file was malformed, does this keep happening for you?` @tidusjar 

So I just tried running the auto update. The only output I see in hangfire `+2ms .   Starting the updater` nothing else. this was a manually triggered update via the webui.

**Comment by AcidRain999** [comment]
@tidusjar tidusjar

![untitled](https://user-images.githubusercontent.com/13775717/31085387-f6ed620a-a764-11e7-8fe8-e2eb136fcfbb.png)

that is all i get, and that is just from going to the website and waiting for it to load, the page will load but the program crashes after that

**Comment by tidusjar** [comment]
@AcidRain999 take a look at this: https://github.com/dotnet/core/issues/649

**Comment by verttex** [comment]
@jonfinley @tidusjar Getting the same error for the updater. 

`warn: Hangfire.AutomaticRetryAttribute[0]
      Failed to process the job '1e766c7c-8b57-4f3b-9633-b2c71256dd1a': an exception occurred. Retry                                                                                  attempt 1 of 10 will be performed in 00:00:29.
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, E                                                                                 ncoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryN                                                                                 ameEncoding)
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__16.MoveNext() in C:\projects\requestple                                                                                 x\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 194
`

**Comment by scottocs11** [comment]
I just tried out Ombi 3 on Windows, and I can get it to connect to Sonarr and Radarr, but I can't manage to get it to actually add movies. [This](https://pastebin.com/raw/nk2wuSWu) is what I get when I try to add a movie.

**Comment by goldenpipes** [comment]
Hello! I tried setting up Discord notifications. I added the {PosterImage} tag to get pictures showing up but it seems there is an error in the markup.  The URL i got has an extra "/" in it.  Im not sure if its pulling it from https://image.tmdb.org that way or if its being generated oddly. here is the URL i got `https://image.tmdb.org/t/p/w300//l2LObt7s0hakFi9ga6tOKMqKkuo.jpg`

here is the url I expected (which loads in discord.)
`https://image.tmdb.org/t/p/w300/l2LObt7s0hakFi9ga6tOKMqKkuo.jpg`

![image](https://user-images.githubusercontent.com/6140137/31104219-5a0e2932-a7a1-11e7-9d98-50dd9384ff47.png)

sorry if i am doing this wrong i am new to github!

**Comment by AcidRain999** [comment]
well if anyone else has the issue with segmentation fault on debian i was able to get it to work so far by using this command.

apt-get install libcurl3=7.38.0-4+deb8u5 libcurl4-openssl-dev=7.38.0-4+deb8u5

**Comment by Nashable** [comment]
Another report on a fresh windows install with the Radarr issue Scott reported. https://github.com/tidusjar/Ombi/issues/1513#issuecomment-333695703

`2017-10-02 19:38:56.622 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request`
`2017-10-02 19:38:56.639 -04:00 [Error] 'Profile Id' must be greater than '0'.`
`2017-10-02 19:38:56.642 -04:00 [Warning] Tried auto sending movie but failed. Message: "'Profile Id' must be greater than '0'."`

I have profiles selected and API key has been verified. Sonarr seems to be working fine importing requests.

Key | Value
-- | --
Version | 3.0.2073
Branch | DotNetCore
OS Architecture | X64
OS Description | Microsoft Windows 10.0.15063
Process Architecture | X64

**Comment by tidusjar** [comment]
The Radarr issue must be from my latest changes... I'll get it fixed

**Comment by DirtyCajunRice** [comment]
- [ ] As of the latest release No one can request a show. not even the original admin. Popup reply is: show added: 'Profile Id' must be greater than '0'.
![image](https://user-images.githubusercontent.com/15788890/31114506-06fd3920-a7e4-11e7-8658-b99179f7dd35.png)

**Comment by tidusjar** [comment]
Upgrade to 3.0.2075  and this has been fixed @DirtyCajunRice

**Comment by PotatoQuality** [comment]
@DirtyCajunRice that is already fixed https://github.com/tidusjar/Ombi/commit/43a78f0e3cbb02559e63902530e54c0b3690da05

**Comment by DirtyCajunRice** [comment]
Yep. Tested. Must have downloaded 5 minutes before the fix. Yall are fast!

**Comment by tidusjar** [comment]
@shawpe So I had a look if I could convert the newlines into `<br />`'s and that would work fine, but the issue would be that it would also apply to other notifications that may not support HTML.

So i'm not going to fix this, What I suggest you do is input HTML into that field to format HTML notifications.

**Comment by Codehhh** [comment]
- [ ]  Requesting TV sets each episode to wanted, but not the season
![image](https://user-images.githubusercontent.com/12055335/31126488-ebc25718-a819-11e7-92ae-c83da5065e38.png)

- [ ]  View Request doesn't default season number for selection
![image](https://user-images.githubusercontent.com/12055335/31126571-2f0e5314-a81a-11e7-9586-a1176efae5d1.png)

- [ ] Test Connectivity for Plex gives an error growl - "We could not connect to the Plex server {my server name here}!", but I can Load Libraries and import users

- [ ] (i) in Email Notifications is not user friendly, it goes off the screen and loads a scrollbar that I can't use.

- [ ] No "send test email"?


Sorry if these have been fixed already, I'm using the docker from LSIO and am still on v3.0.2073

**Comment by PotatoQuality** [comment]
@Codehhh, you are running on a old code. Can you pleas upgrade to the last version?

**Comment by PotatoQuality** [comment]
@Codehhh  edit: My mistake, you are up to date!

**Comment by Codehhh** [comment]
@PotatoQuality I believe the auto-updater just updated me while I was typing the report but all of my configuration besides the admin account is gone.

**Comment by Codehhh** [comment]
@PotatoQuality I think I updated during the post. 

I'm now getting a massive stack trace in my log file.
[log-20171003.txt](https://github.com/tidusjar/Ombi/files/1352454/log-20171003.txt)

If you need access to check my configuration I can make an account for you.

**Comment by tidusjar** [comment]
@Codehhh your radarr configuration is incorrect according to the log

**Comment by Codehhh** [comment]
@tidusjar Currently all I'm trying to do is import users from Plex. The job in Hangfire has been processing for 6 minutes with no users imported. I'm still getting the Radarr exception even with Radarr disabled and no settings filled in

**Comment by PotatoQuality** [comment]
- [ ] don't show deny button when a request is auto approved

**Comment by goldenpipes** [comment]
- [ ] clicking "approve request" on an item requested by Plex user with only `RequestTv` and `RequestMovie` permissions; as admin seems to do nothing.  Green growl pops up and changes to approved, but on page refresh it's reverted back to "Request status: Pending Approval."

**Comment by daymanbpi** [comment]
- [ ] New Request Notification does not display Subject Line. Slack message only displays generic message.
https://imgur.com/a/VvySH
Generic
https://imgur.com/a/bYVaQ

**Comment by Codehhh** [comment]
- [ ] Updater fails -- Docker running on UnRaid
![image](https://user-images.githubusercontent.com/12055335/31157437-f1187de0-a888-11e7-85c7-0146525127bf.png)

**Comment by Unimatrix0** [comment]
Hangs at loading screen on mobile browsers.

Tested on:
- iOS 9.3.3
  - Safari
  - Chrome 61.0.3163.73
  - Firefox 8.3 (5826)
- iOS 10.3.3
  - Safari
  - Chrome 61.0.3163.73
  - Opera 16.0.3

**Comment by filoor** [comment]
Hi,

When i try to run in on a win7 32bit version i get 

C:\ombi>ombi.exe
This version of C:\ombi\Ombi.exe is not compatible with the version of Windows y
ou're running. Check your computer's system information to see whether you need
a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the soft
ware publisher.


it runs normal on win10

**Comment by tidusjar** [comment]
@filoor This is a 64bit application only. If there are more requiring 32bit then I can look into this.

**Comment by tidusjar** [comment]
@daymanbpi Slack does not support the concept of a subject. The editor that you are looking at is generic for all notifications.

@Unimatrix0 I cannot reproduce this

**Comment by daymanbpi** [comment]
@unimatrix0
Same issue on IOS. Issue resolved by updating to IOS 11.0.3

**Comment by Adouken** [comment]
Running the docker container on Unraid and having issues with approving TV requests. When a user has requested a TV episode and I go to approve it nothing happens. No toast or anything, I can deny though. I have attached the log.
[ombilog.txt](https://github.com/tidusjar/Ombi/files/1355960/ombilog.txt)

**Comment by RyanAStrouse** [comment]
@LettuceSnob I can't seem to get it to work with this.

It starts, then I get this
● ombi.service - Systemd script to run Ombi as service
   Loaded: loaded (/etc/systemd/system/ombi.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: core-dump) since Wed 2017-10-04 11:13:27 EDT; 1s ago
  Process: 23812 ExecStart=/opt/ombi/Ombi (code=dumped, signal=ABRT)
 Main PID: 23812 (code=dumped, signal=ABRT)

Oct 04 11:13:27 TandarLinux systemd[1]: ombi.service: Unit entered failed state.
Oct 04 11:13:27 TandarLinux systemd[1]: ombi.service: Failed with result 'core-dump'.

**Comment by Unimatrix0** [comment]
@RyanAStrouse Make sure the user it's running as (in the [service] section) has appropriate permissions to the files and directories.

**Comment by Unimatrix0** [comment]
@tidusjar What version of iOS did you test on?

**Comment by RyanAStrouse** [comment]
@Unimatrix0 Everything has the same permissions as before. The only adjustment I've made is removed the Mono dependency from my script. It basically matches @LettuceSnob example

**Comment by Unimatrix0** [comment]
@RyanAStrouse Am I correct in assuming you're able to launch it successfully from the command line, and only when running as a service do you have the core dump?

**Comment by RyanAStrouse** [comment]
@Unimatrix0 Yes, I can run it successfully as command, although it is very slow when I do.

**Comment by Unimatrix0** [comment]
@RyanAStrouse Can you share both your systemd script and the full CLI command you're using to launch manually?

**Comment by Unimatrix0** [comment]
@RyanAStrouse Hop on the gitter if you can. https://gitter.im/tidusjar/Ombi

**Comment by Anijake** [comment]
Just updated to 3.0.2086, still can not add root folder for Sonarr. I have only one item on the dropdown list and since it is pre-selected there is nothing I can change to select. 

![screen shot 2017-10-05 at 1 37 06 am](https://user-images.githubusercontent.com/25043155/31212300-bad46c04-a96d-11e7-8835-72abfa51c9b8.png)

**Comment by filoor** [comment]
After deleting a  tv show on Sonarr
I see the  button request and the drop down menu on Ombi 
But cant select any thing on it

**Comment by PotatoQuality** [comment]
@filoor how do you know you can't do something with it?

**Comment by filoor** [comment]
@PotatoQuality Because when i click all season it does not change to requested and 
also don't show up in Sonarr

**Comment by tidusjar** [comment]
@filoor Please open a new issue please with more information.

**Comment by tidusjar** [comment]
I am locking this thread.

I originally thought it would be a good idea to keep all the issues in one place but it's becoming unmanageable now...

Please open a new issue with as much information as you can when raising a bug.

This will be managed via the projects: https://github.com/tidusjar/Ombi/projects/3
