### ISSUE TITLE
A Default Root Path is required

### ISSUE THREAD

**Issue by Anijake** [tidusjar/Ombi#1522]
V3.x on Mac. when setting up Sonarr when setting up root folders, I only have one, it comes up on the dropdown but because its the only directory it does not register and can not be selected so I keep getting "A Default Root Path is required" and can not complete setup.

**Comment by PotatoQuality** [comment]
Pleas don't ignore the text when you open a issue 

Please report V3 beta issues here: https://github.com/tidusjar/Ombi/issues/1513
