### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#1524]
https://github.com/tidusjar/Ombi/blob/9ae5ad0ecd9d1b151acf6a12608fafbf51321e2c/Old/Ombi.Services/Notification/DiscordNotification.cs#L62

should it be `WebHookId;` ?

**Comment by tidusjar** [comment]
Yes it should! :D

**Comment by goldenpipes** [comment]
Line 126 as well!

Cheers!
