### ISSUE TITLE
Backup restore 

### ISSUE THREAD

**Issue by filoor** [tidusjar/Ombi#1527]
How can I restore a backup is lost all my wanted movies

**Comment by PotatoQuality** [comment]
V2 or V3?

**Comment by PotatoQuality** [comment]
Go to .\Backup you can find there a backup of you database :)

**Comment by filoor** [comment]
Hi @PotatoQuality 

I did that i renamed the backup to "Ombi.sqlite"
and moved it to the ombi folder but my requested movies are stil not there.
I checked the file with sqllite and i see the movies on table "RequestBlobs"
but they don't show op on the ombi page
