### ISSUE TITLE
Re-adding Tv-Show after deleted from Sonarr 

### ISSUE THREAD

**Issue by filoor** [tidusjar/Ombi#1531]
Ombi Version:

V 3.0.2086

Os: 
Windows

Problem:
After deleting a tv show on Sonarr
Ombi wil show the Request button insted of requested
bet when you click request it wil show the drop down menu
But if i click any thing like "All Seasons" nothings happen
and it will also not add it on Sonarr

**Comment by tidusjar** [comment]
Please attach any relevant log files.

You can find this in your installation folder in the folder `/logs/`

**Comment by filoor** [comment]
@tidusjar I have it on my c:\ombi\
But i don't see any logs folder there

**Comment by filoor** [comment]
Sorry You mean the sonarr logs

If i select on episodes that works

**Comment by filoor** [comment]
This is what i get if select one episode 
But if i select all season  nothing happens 

17-10-5 09:47:20.0|Info|MediaCoverService|Downloading Banner for [328724][Young Sheldon] http://thetvdb.com/banners/graphical/328724-g2.jpg
17-10-5 09:47:20.3|Info|MediaCoverService|Downloading Poster for [328724][Young Sheldon] http://thetvdb.com/banners/posters/328724-2.jpg
17-10-5 09:47:20.6|Info|MetadataService|Series folder does not exist, skipping metadata creation
17-10-5 09:47:27.2|Info|DownloadDecisionMaker|Processing 78 releases
17-10-5 09:47:29.0|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.
17-10-5 09:49:36.5|Info|RssSyncService|Starting RSS Sync

**Comment by halali** [comment]
I have problem with cacher i have only few series tagged as available on plex and not tagget as requested, and when i request them it change in sonarr from unmonitored to monitored...

Movies works good

**Comment by tidusjar** [comment]
Guys, Can you please be a bit more descriptive, it's hard to understand what is going on with no sonarr logs.

Please provide some reproduction steps.

e.g.

1. The Tv Show Sheldon is not in Sonarr
1. Search For Tv Show Sheldon
1. Request First Season as Admin
1. Series is not added to Sonarr

Expected result:

First Season is added to Sonarr

Logs from `C:\Ombi\Logs` = LINK

**Comment by filoor** [comment]
I will try

1. I dont have any logs of ombi V3 there is no logs folder in C:\Ombi\
2. I had the show "Young Sheldon " on Sonarr but not yet on Ombi.
3. i I searched for "Young Sheldon " on Ombi it showed "Requested" 
4. I wanted to show up under the tab "requests" on Ombi.
5. I deleted "Young Sheldon" from Sonarr 
3. I went back to Ombi and searched for "Young Sheldon " and it showd now "Request"
7. clicked "Request" and then all Seasons but nothing happens it stays on "Request" and its also not adding it to Sonarr.



i hope you understand now what i mean

**Comment by PotatoQuality** [comment]
@filoor where did you install ombi v3?

**Comment by filoor** [comment]
on c:\Ombi

**Comment by filoor** [comment]
Application Base PathC:\ombi

**Comment by Codehhh** [comment]
@tidusjar

I believe when the config path code was created the committer disabled rolling files, putting everything into the db

**Comment by filoor** [comment]
I triad also to 
 start with C:\ombi>ombi.exe -s C:\ombi\Logs
Ombi.exe will Crash

**Comment by tidusjar** [comment]
@Codehhh Your right, there is a new build that will write out the logs again.

**Comment by filoor** [comment]
The logs are showing up nog
thanks

[log-20171005.txt](https://github.com/tidusjar/Ombi/files/1359281/log-20171005.txt)

**Comment by filoor** [comment]
thanks
