### ISSUE TITLE
mouse cursor in dropdown menu

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1532]
Can we have the old mouse cursor?

In the new one it change to a different one that you also get when you click somewhere you like to write.

Old one:
![image](https://user-images.githubusercontent.com/2944704/31228406-b21e323c-a9dd-11e7-8ec9-a5fdfe1d27cf.png)

**Comment by tidusjar** [comment]
Already done it! Check the latest version
