### ISSUE TITLE
All seasons request is not monitoring the latest season

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#1534]
When i do a all season request the latest season isn't requested:

![image](https://user-images.githubusercontent.com/2944704/31253511-89774e98-aa25-11e7-9771-8cbedc318d18.png)

**Comment by tidusjar** [comment]
https://github.com/Sonarr/Sonarr/issues/2217

**Comment by PotatoQuality** [comment]
@tidusjar did you saw the reply of markus101 ?

**Comment by tidusjar** [comment]
Yes I need time to look into it
