### ISSUE TITLE
TV Shows already requested aren't listed as requested in search results

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#1536]
- [ ] TV Shows already requested aren't listed as requested in search results
- [x] Buttons don't update while API call is processing so user doesn't know when things are actually happening vs broken

![image](https://user-images.githubusercontent.com/12055335/31258292-3157b108-aa0c-11e7-9245-2ba0c022f02d.png)

**Comment by tidusjar** [comment]
Regarding TV shows, if you Press "Select..." do the episodes appear as requested?

**Comment by Codehhh** [comment]
![image](https://user-images.githubusercontent.com/12055335/31273385-639215b4-aa5c-11e7-9273-908d99b78b76.png)

@tidusjar Yes, all episodes are either available or processing request

**Comment by tidusjar** [comment]
So what should show as requested?

**Comment by Codehhh** [comment]
I would think that the entire show would show as requested since every episode became monitored in Sonarr when I hit request All Seasons

**Comment by tidusjar** [comment]
Think i'm going to close this for now, I don't think we should add too many labels since it may get confusing, Ombi has already added the available label to the series.
