### ISSUE TITLE
FR: give users different credentials

### ISSUE THREAD

**Issue by horstepipe** [tidusjar/Ombi#1537]
hey
I'd like to be able to give my users different passwords in Ombi than they have in Emby.
Yeah, that's it :-)

Best regards

**Comment by tidusjar** [comment]
If they are imported via Emby then we authenticate through emby for those users. If you want them to have their own Ombi accounts with their own passwords then you just need to create them as local accounts in Ombi.

**Comment by horstepipe** [comment]
Thanks
but how can I connect to Emby database without importing the users?

**Comment by tidusjar** [comment]
Importing users is disabled by default, you need to enable it in the User Management Settings

**Comment by horstepipe** [comment]
okay then I messed something up last time I tried it. Thank you :-)
