### ISSUE TITLE
Unable to change quality/destination folder for user requests. 

### ISSUE THREAD

**Issue by BHGaming** [tidusjar/Ombi#1539]
First some details:
OS: Ubuntu 16.04 Server (fresh install, fully patched, VMWare tools installed)
Hypervisor: ESXi 6.5 (fully patched)
VM Specs: 2 Cores, 2GB ram, 20gb Storage
Sister Software: Plex, Sonarr, Radarr (All up to date, Plex using Plexpass build)
I tried v3 for the first time today. Got it setup and running, and added 1 non-admin account for testing. I ran into the following issues:

Unable to change quality/destination folder for user requests. Ombi can pull my Quality/Destination folders in configuration. When I try to change it, it puts me back on the main screen.

**Comment by Enf0** [comment]
Just wanted to chime in and let you know opening a bunch of issues that just say "issue with v3" is not very helpful, try to make more descriptive titles.
