### ISSUE TITLE
Minor problem with v3

### ISSUE THREAD

**Issue by BHGaming** [tidusjar/Ombi#1540]
First some details:
OS: Ubuntu 16.04 Server (fresh install, fully patched, VMWare tools installed)
Hypervisor: ESXi 6.5 (fully patched)
VM Specs: 2 Cores, 2GB ram, 20gb Storage
Sister Software: Plex, Sonarr, Radarr (All up to date, Plex using Plexpass build)

Ombi is pulling my wanted lists from Sonarr. The problem I found was if I have a show added to Sonarr, but it has not started yet (0 episodes in Sonarr/Plex), Ombi will allow a user to request that show again.

**Comment by tidusjar** [comment]
Can you please expand on this issue? I am unsure what you mean

**Comment by DirtyCajunRice** [comment]
He is saying that because there are no episodes to flag the show as downloaded, that ombi will continually allow someone to request, even tho the show hasnt officially started yet

**Comment by tidusjar** [comment]
Example of a show like this?

**Comment by jpeters** [comment]
Mindhunter (2017)

**Comment by PotatoQuality** [comment]
double https://github.com/tidusjar/Ombi/issues/1536

**Comment by tidusjar** [comment]
I think it's a separate issue

**Comment by tidusjar** [comment]
I'm still not following,

I requested all seasons of Mindhunter, Then I try and request all seasons and Ombi wont let me because it's already added.

**Comment by mdhwoods** [comment]
It sounds like the show is already in sonarr but was not requested though Ombi and has not started.  Ombi isn't detecting this as already being there and allowing users to request again.
