### ISSUE TITLE
Medium Problem with v3

### ISSUE THREAD

**Issue by BHGaming** [tidusjar/Ombi#1541]
The problem I have found is.. Latest Ombi will not load in Organizr on mobile.  It will load on Muximux.  I get a blank screen on normal view and desktop view in Organizr.

Device:  Nexus 5X
OS:  PureNexus [latest]
Android :  7.1.1
Browser:  Chrome

**Comment by tidusjar** [comment]
Doesn't sound like a direct Ombi issue
