### ISSUE TITLE
Approve status not persisting

### ISSUE THREAD

**Issue by BHGaming** [tidusjar/Ombi#1543]
I hope this has been posted before, but i did not see it.

[Link 1](https://www.reddit.com/r/Ombi/comments/73nxt6/approved_request/?st=j8gxxogk&sh=b44ba522)

[Link 2](https://www.reddit.com/r/Ombi/comments/74hqr2/a_few_issues_with_v3/?st=j8gxzexr&sh=c1fdebf4)

The Problem:  

Request approval is strange. I can approve a users request, and the download will start/complete/import, but they would not see it as approved on their account. I would also have the approve button come back on the admin account, with the error "Movie already approved" when I try to approve it again.

**Comment by Scorcher7986** [comment]
Getting the same issue. The only error that's thrown is when you try approving it a second time after it's already been added:
```
 fail: Ombi.Api.Api[1000]
       StatusCode: BadRequest, Reason: Bad Request
 fail: Ombi.Core.MovieSender[2001]
       This movie has already been added
 warn: Ombi.Core.Engine.MovieRequestEngine[0]
       Tried auto sending movie but failed. Message: This movie has already been added
```

Once the download finishes and gets added by radarr/sonarr, Ombi marks it as 'Available', but also keeps the 'Pending Approval' tag for Request status:

![image](https://user-images.githubusercontent.com/17667531/31308630-c2c86212-abc5-11e7-87f5-f15b3dcb0fa6.png)

Currently on latest version 3.0.2093

**Comment by Sm0k3d0uT** [comment]
I have been having the same problem too
