### ISSUE TITLE
mail notificaiton does not work with localhost server

### ISSUE THREAD

**Issue by xp-1000** [tidusjar/Ombi#1545]
Hi, I test v3 (3.0.2094) version from one day it is cool to remove mono dependencie from my server, thanks!

I cannot configure my mail server for mail notification. May be I did mistake but I use a very trivial config (localhost:25 without authentification) which works with some other services.

Here is my configuration : 

![ombi-mail-issue](https://user-images.githubusercontent.com/2693213/31312887-2e92770c-abd1-11e7-9511-e2f1ece36127.PNG)

xp-1000@domain.com (which is not my real domain) exists and is assigned as email address to my local admin user of ombi.

When I click on "test", a first green message appears to inform of an error and disappears very quicky to let place to another which inform that configuration is saved.

Here is the log error : 

`
    oct. 08 02:16:46 manfroi.fr Ombi[25502]: warn: Ombi.Controllers.External.TesterController[0]
    oct. 08 02:16:46 manfroi.fr Ombi[25502]:       Exception when testing Email Notifications
    oct. 08 02:16:46 manfroi.fr Ombi[25502]: System.InvalidOperationException: A call to SSPI failed, see inner exception.
    oct. 08 02:16:46 manfroi.fr Ombi[25502]:    at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 70
    oct. 08 02:16:46 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:16:46 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:16:46 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:16:46 manfroi.fr Ombi[25502]:    at Ombi.Controllers.External.TesterController.<Email>d__45.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 175
`

Thanks in advance for your help, I could help for the debug and test.

**Comment by jpeters** [comment]
This appears to be similar to an SMTP problem that I noticed in #1549. It appears to center around the way that MailKit is handling TLS/SSL.

**Comment by xp-1000** [comment]
Thanks @jpeters it works fine
