### ISSUE TITLE
Approve action cannot update in database

### ISSUE THREAD

**Issue by xp-1000** [tidusjar/Ombi#1546]
Hi, I am on 3.0.2094  version of omby and have a problem with approve action.

I click on "approve" button, all seems work fine, the request status change but I don't recieve any notification (from discord which works fine) and when I refresh the page (F5), the status comes back in "to approve".

Here is the error log : 

`    oct. 08 02:07:42 manfroi.fr Ombi[25502]: warn: Hangfire.AutomaticRetryAttribute[0]
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:       Failed to process the job '017944b8-aa02-4777-9e0e-db0d7a9c1438': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:38.
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    --- End of inner exception stack trace ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Ombi.Store.Repository.EmbyContentRepository.<AddRange>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\EmbyContentRepository.cs:line 110
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Ombi.Schedule.Jobs.Emby.EmbyEpisodeCacher.<CacheEpisodes>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyEpisodeCacher.cs:line 111
    oct. 08 02:07:42 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:07:42 manfroi.fr Ombi[25502]:    at Ombi.Schedule.Jobs.Emby.EmbyEpisodeCacher.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyEpisodeCacher.cs:line 65
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: warn: Hangfire.AutomaticRetryAttribute[0]
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:       Failed to process the job '017944b8-aa02-4777-9e0e-db0d7a9c1438': an exception occurred. Retry attempt 3 of 10 will be performed in 00:01:25.
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    --- End of inner exception stack trace ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Ombi.Store.Repository.EmbyContentRepository.<AddRange>d__15.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\EmbyContentRepository.cs:line 110
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Ombi.Schedule.Jobs.Emby.EmbyEpisodeCacher.<CacheEpisodes>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyEpisodeCacher.cs:line 111
    oct. 08 02:09:12 manfroi.fr Ombi[25502]: --- End of stack trace from previous location where exception was thrown ---
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    oct. 08 02:09:12 manfroi.fr Ombi[25502]:    at Ombi.Schedule.Jobs.Emby.EmbyEpisodeCacher.<Start>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyEpisodeCacher.cs:line 65`

Thanks in advance for your help, I am available for test, debug or if you need more information.

**Comment by xp-1000** [comment]
Workaround : click on approve, don't reload the page, click on "mark available" and now the request is correctly updated in database and keep its new status even after page reload. Just have to "mark unaivailable" to get the status it should have just after approve.

**Comment by xp-1000** [comment]
Hi,
Seems the log error posted before is not related to this issue.
I tested with a new fresh install with last version 3.0.2098 and I observe the same behavior but the error from server side is not raised when we click on approve button.
In fact the true error is the request is never sent to backend, I see nothing in network tab of web browser debugging tool and I got this error in console : 
`
Form submission canceled because the form is not connected
`
It explains the workaround : I click on approve, form sent no update in database then I click on mark available, form sent (with the approve update in addition of the available status) object updated in database.

I hope it could help you.

**Comment by Scorcher7986** [comment]
> form is never sent to backend
Are you sure that's the case? I only ask because when 'approving', ombi does send a request to sonarr/radarr and the movie/show starts downloading - so it is receiving something.

**Comment by xp-1000** [comment]
Hi @Scorcher7986,

No I am not sure that is the case I only refer to the console message : 

>  Form submission canceled because the form is not connected

from the network point of view the form should be sent because I see a HTTP POST request (with 200 response) sent exactly as for "Mark available" action which works fine. The only difference between approve and mark available is the path of the request, respectively `/Request/Movie/Approve` and `/Request/movie/`.

If you want, may be I could tcpdump confirm the request is sent ?
