### ISSUE TITLE
Plex users with accents not being imported 

### ISSUE THREAD

**Issue by joelteixeira** [tidusjar/Ombi#1547]
Hello there,

When users names (not the email) has any accent it fails to import the user with the following log message:

![accent](https://user-images.githubusercontent.com/12114795/31316532-b50d2c12-ac05-11e7-9c48-89ab66407056.png)

After renaming the user it imported successfully. Please note that this is not the username the user uses to login (even being possible on plex) the user uses the email when logging in.

**Comment by PotatoQuality** [comment]
You note is not correct :-) 

Plex have two usernames. One for login in with email and a username like this. 
Users can Also login with that username you seeing right now

**Comment by joelteixeira** [comment]
@PotatoQuality, 

Sorry if it wasn't clear enough. But it doesn't seem incorrect since I already said that both can be used.  

> "Please note that this is not the username the user uses to login (**even being possible on plex**) the user uses the email when logging in."

I meant that, yes, both of them can be used to log in. But this user uses his email and not the username on logons.
