### ISSUE TITLE
SMTP Notification certificate validation

### ISSUE THREAD

**Issue by jpeters** [tidusjar/Ombi#1549]
Ombi 3.0.2094 on Windows Server 2016.
IIS SMTP server on same host

Email Notifications page is set to

SMTP Host: 127.0.0.1
SMTP Port: 25

When attempting to test send I get the following error.

`2017-10-08 12:33:11.500 -04:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The remote certificate is invalid according to the validation procedure.
   at Ombi.Notifications.GenericEmailProvider.<SendAdHoc>d__4.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Email>d__45.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 175`

I would prefer to send over clear-text locally and not use TLS. It does appear that the line throws the exception in the GenericEmailProvider.cs:

`client.Connect(settings.Host, settings.Port); // Let MailKit figure out the correct SecureSocketOptions.`

I think the preferred way to handle this would be to include options in the Email Notifications settings page to enable/disable TLS/SSL as opposed to calling a custom client.ServerCertificateValidationCallback.

May even want to give the option of disabling certificate checking.

I am happy to take a shot at a pull request, just give me a little direction on what behavior you would like to see happen.

**Comment by tidusjar** [comment]
I agree,

It might be good to let the user specify.

Yeah a pull request would be awesome!

What needs to be done is to add a new property onto the `EmailNotificationSettings.cs` maybe an enum of the [SecureSocketOptions](http://www.mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm)? Makes sense really.

Also add a dropdown option onto the `emailnotification.component.ts` (frontend is in Angular) with the enum values.

**Comment by jpeters** [comment]
@tidusjar I am having an issue with the build.ps1. This is relating to Cake.Incubator not being updated to cake.core 0.22. How are you currently getting around this? The build.cake does not seem to be able to handle this.

**Comment by jpeters** [comment]
Just performed pull request #1552.

**Comment by tidusjar** [comment]
Nice work :)
