### ISSUE TITLE
Impossible to view a requested tv show 

### ISSUE THREAD

**Issue by xp-1000** [tidusjar/Ombi#1550]
Hi, 

I am on 3.0.2094 version.

When I try to click on "view" button from a tv show request admin view, nothing happens.
There is no log on server side but I have an error on my browser console : 

> ERROR 
TypeError
columnNumber: 149370
fileName: "https://requests.domain.tld/dist/main.js?v=stiUq6czeyN6qBdciw7W1jjGlLUxqhtzxla4eOU3WGs"
lineNumber: 48
message: "e is undefined"
stack: "l</e.prototype.openClosestTab@https://requests.domain.tld/dist/main.js?v=stiUq6czeyN6qBdciw7W1jjGlLUxqhtzxla4eOU3WGs:48:149370\nView_e_3/<@ng:///e/e.ngfactory.js:46:23\nQn/<.handleEvent@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:113:1580\nhandleEvent@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:113:8808\nie@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:64:1741\nMe/<@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:71:2363\ng/<@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:620:545\nvendor_ca6a7d745ecdb0207d63</</</</u</t.prototype.invokeTask@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:8040\nonInvokeTask@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:36:815\nvendor_ca6a7d745ecdb0207d63</</</</u</t.prototype.invokeTask@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:7953\nvendor_ca6a7d745ecdb0207d63</</</</l</r.prototype.runTask@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:3208\nvendor_ca6a7d745ecdb0207d63</</</</p</e.invokeTask@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:9178\nh@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:951:3306\nf@https://requests.domain.tld/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:951:3526\n"
__proto__: {…}
constructor: function TypeError()
message: ""
name: "TypeError"
stack: ""
__proto__: {…}
constructor: function Error()
message: ""
name: "Error"
stack: Getter & Setter
toSource: function toSource()
toString: function toString()
__proto__: {…}
__defineGetter__: function __defineGetter__()
__defineSetter__: function __defineSetter__()
__lookupGetter__: function __lookupGetter__()
__lookupSetter__: function __lookupSetter__()
constructor: function Object()
hasOwnProperty: function hasOwnProperty()
isPrototypeOf: function isPrototypeOf()
propertyIsEnumerable: function propertyIsEnumerable()
toLocaleString: function toLocaleString()
toSource: function toSource()
toString: function vendor_ca6a7d745ecdb0207d63</</</</Object.prototype.toString()
unwatch: function unwatch()
valueOf: function valueOf()
watch: function watch()

Any body have the same error ?
Thanks for your help.

**Comment by tidusjar** [comment]
Browser?

**Comment by xp-1000** [comment]
Firefox 57.0b6 (64 bits)
As you asked me, I tested and it works on chromium Version 60.0.3106.0

**Comment by Scorcher7986** [comment]
#1544

**Comment by PotatoQuality** [comment]
Double
