### ISSUE TITLE
Discord notifications aren't being sent

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#1554]
v 3.0.2094

Issue:
- [ ] Discord notifications not sent on request. Test message is sent successfully but not upon request. Tested as Admin, Power User, and Regular User, all with AutoApprove enabled.

**Comment by Scorcher7986** [comment]
Sorry if this is a misconception, but isn't this intended?

I thought that the 'new request' notification is only sent when users don't have AutoApprove enabled, where an admin or power user would have to manually approve the request. The default template of the message suggests this is the intended case too:
```
Hello! The user '{RequestedUser}' has requested the {Type} '{Title}'!
Please log in to approve this request.
Request Date: {RequestedDate}
```

What it sounds like is that you want a discord notification to be sent regardless of whether AutoApprove is enabled or not, which would be a feature request.

I do think the name 'New Request' for notifications might suggest that it should include both cases, and should probably be changed to be more clear.

Discord notifications work fine for me when AutoApprove is disabled.

**Comment by Codehhh** [comment]
Ah, that makes sense! Maybe there should be an option to send notification upon request, even if it is auto-approved? I like to know when things are requested 😄

**Comment by tidusjar** [comment]
Ah yes @Scorcher7986 is correct, I'm not going to change this for now.
