### ISSUE TITLE
Unable to find shows Sonarr finds

### ISSUE THREAD

**Issue by carnivorouz** [tidusjar/Ombi#1556]
Ombi ver: | 2.2.1678 
Application Version: | 2.2.1678
OS: | Mono
System Version: | 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 11:42:39 UTC 2017)
Branch: | Stable

===========================
I did some searching and the issue looks to be a result of using TVMaze versus TVDb based on what Jamie has said back in 2016.  Recently a user said they were unable to find two shows "Ride with Norman Reedus" and "Mike Judge Presents: Tales From the Tour Bus".  I confirmed this was the case in Ombi and then searched and added without issue from within Sonarr.  
It's not a huge issue as can deal with these one-offs, however I want to bring it up as an issue if users are unable to find shows due to TVMaze search method.
Thanks!

**Comment by PotatoQuality** [comment]
Problem on this is that TVmaze don't have all of the information yet for ombi to phase the request to Sonarr.
You see this problem a lot of times with tv shows that didn't is on tv yet.

I guess the only thing we can do rightnow is bring the queue system back to life.

If we can't send it yet to sonarr beceause we are missing information store it in the queue and try to get the information and send it again to sonarr.

**Comment by tidusjar** [comment]
No plans until we are at a stable release.
