### ISSUE TITLE
Request Status/Options Missing

### ISSUE THREAD

**Issue by Sm0k3d0uT** [tidusjar/Ombi#1557]
Ombi:  3.0.2098
OS: Ubuntu 16.04

I created  user to test requests requested a TV show and most of the status is missing.
I also logged in as admin to try and approve request, most of the request status missing there too and missing all buttons to approve, deny, etc... 

Can't delete requests

![request_error](https://user-images.githubusercontent.com/595687/31352777-09543a74-acfe-11e7-8b88-a4a068b091e1.png)

**Comment by PotatoQuality** [comment]
Click on view. There you have al of The buttons

**Comment by Sm0k3d0uT** [comment]
Clicking on view does nothing.

**Comment by PotatoQuality** [comment]
Mobile support is not finished yet. Pleas test on a desktop

**Comment by Sm0k3d0uT** [comment]
I tested from my desktop and server Ombi is installed on.

**Comment by tidusjar** [comment]
browser?

**Comment by Sm0k3d0uT** [comment]
Doesn't work with:
Cyberfox 52.3.0
Firefox Nightly 58.0a1
Waterfox 55.2.0

Does work with:
Vivaldi 1.12 
Chrome 61.0.3163.100

**Comment by Scorcher7986** [comment]
Same as issue #1544 I think
Seems like it's a bug on all firefox based web browsers, chromium based web browsers work fine
Version 56.0 of Firefox is when it stopped working for me - it would be interesting to see what changed

**Comment by tidusjar** [comment]
Duplicate
