### ISSUE TITLE
"Please select the server" list not loading

### ISSUE THREAD

**Issue by LindsayCole** [tidusjar/Ombi#1563]
Sorry if this isn't the right place, I followed your link, which then took me to projects, and it won't let me create a card.

When I add Plex during initial setup, everything seems to work fine.

However, when I go to Media Server, to add details, under Please select the server, it doesn't populate a list.

I've redownloaded the files, and tried multiple browsers.
![ombiv3](https://user-images.githubusercontent.com/15201976/31475440-3dc272be-aed7-11e7-906f-033abe07ac94.PNG)

Any ideas?

**Comment by LindsayCole** [comment]
Something I forgot to add. When I tell it to load servers, it does say Found the servers.

**Comment by PotatoQuality** [comment]
Can you upload your log file here?

You can find it in the Ombi folder. Logs

**Comment by LindsayCole** [comment]
[log-20171011.txt](https://github.com/tidusjar/Ombi/files/1380183/log-20171011.txt)

Log is attached. Please let me know if there is anything else I can do to help.

**Comment by PotatoQuality** [comment]
Is your Plex server behind a proxy server?

**Comment by LindsayCole** [comment]
Wow, I'm so sorry I forgot to mention that. Yes. It is behind a nginx proxy. All on the same network and subnet.

It turns out you are correct. The proxy is causing the issue. I have three servers, two are behind it. The third one can be seen no issue.

Any idea of a workaround for this?

**Comment by PotatoQuality** [comment]
Somehow the settup is triggering a Internal Server error on the proxy site.

> 
> 
> 2017-10-11 22:37:49.549 -03:00 [Warning] Looks like we can't find any Plex Servers
> 2017-10-11 22:38:04.735 -03:00 [Error] StatusCode: InternalServerError, Reason: Internal Server Error

Can you post your  error logs from nginx proxy? Maybe we can figure out what the problem is.


What you can do with the workaround:
Connect directly on the port of the plex server instead of using the proxy server.
Is Ombi in the same network or external?

**Comment by LindsayCole** [comment]
Same network. I have tried both using the internal (non proxy side) and proxy side. Both return the same results. I'll have info from nginx shortly.

**Comment by sgu222e** [comment]
Today's error.log, was going to post the access.log, but it's 34mb
Tailed the logs and didn't see any local traffic going though the proxy
[error.log](https://github.com/tidusjar/Ombi/files/1380425/error.log)

**Comment by sgu222e** [comment]
I think I understand the problem more, I have a similar setup. The Load Servers checks in with Plex.tv online to see which servers you have access to, that populates the Drop down list, where if you select a server, the fields on the left get populated. This will fail if Remote Server Access is disabled.
In the OP's case, he would like to add the servers that are behind the proxy and have Remote Access disabled. Manually filling in the fields should allow the connection to work, but how would he get the Plex Auth Token and Machine ID?

**Comment by LindsayCole** [comment]
Plex Auth Token, I can get: https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

Machine ID, I have no idea.

**Comment by mattohm** [comment]
Machine ID can be found here:
Windows - Open regedit and navigate to Computer\HKEY_CURRENT_USER\Software\Plex, Inc.\Plex Media Server
Ubuntu/Fedora - /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml
Synology - /volume1/Plex/Library/Application Support/Plex Media Server/Preferences.xml
QNAP - /share/MD0_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Preferences.xml
unRAID -
ReadyNAS - /c/.plex/Library/Application Support/Plex Media Server/Preferences.xml

**Comment by tidusjar** [comment]
Is there any update on this?

Is this still an issue?

**Comment by sgu222e** [comment]
I believe the issue has been worked around by enabling remote access on the Plex servers temporary. There should probably be an enhancement request to allow local server addition if remote access is disabled.
