### ISSUE TITLE
Support for FreeBSD Jail:

### ISSUE THREAD

**Issue by bassrock** [tidusjar/Ombi#1564]
The current 2.0 is supported on FreeBSD through mono. I get the following error when I run the linux version on a FreeBSD Jail:

```
ELF binary type "0" not known.
./Ombi: Exec format error. Binary file not executable.
```

Is FreeBSD support planned?

**Comment by PotatoQuality** [comment]
This is an knowing ssue. Not sure if Jamie going to fix this

**Comment by tidusjar** [comment]
Looks like FreeBSD is currently not supported on .Net Core currently. There is not much I can do on this at the moment.

Closing for now, i'll reopen once .Net Core add's support for FreeBSD

**Comment by psychoflame** [comment]
Look's like there's work on it right now. Might be coming soon

https://github.com/dotnet/corefx/issues/1626

**Comment by wfurt** [comment]
It is tedious and incomplete:
https://github.com/dotnet/corefx/wiki/Building-.NET-Core--2.x-on-FreeBSD

You can probably git bit further @bassrock  by 'kldload linux64' but the linux emulation path did not lead to success for me.

**Comment by rubenverhoef** [comment]
Is there a way to run version 3 on FreeBSD? I tried using mono and windows zip file but i get: 
`Cannot open assembly 'Ombi.exe': File does not contain a valid CIL image.`

**Comment by PotatoQuality** [comment]
@rubenverhoef  beceause  you  dont need mono to run this application.

Of you read this github issue, tidusjar said it already:

Looks like FreeBSD is currently not supported on .Net Core currently. There is not much I can do on this at the moment.

**Comment by rubenverhoef** [comment]
@PotatoQuality Yeah alright, so no FreeBSD support for Ombi V3. I thought maybe mono can do the job on the windows version. like i did with V2.

**Comment by srscott** [comment]
Any update on running v3 in an iocage jail? Would love to have the config for ombi save away from a van that can be blown away at anytime.

**Comment by tidusjar** [comment]
If you have got it working in a jail, you can change where the config is by passing the --storage parameter. See the wiki for more information

**Comment by srscott** [comment]
Nah it’s not in a jail, it’s in a Ubuntu vm on my FreeNAS machine. Just noticed my typo above sorry.
If there is a way to map storage from my FreeNAS datasets to the vm then that would help (I’m not sure how) but I’d much rather ombi in a jail but that can’t happen because of .net?
My other option is docker but it seems like I can only “mount” one nfs share path and I need multiple to switch to Docker. Although I couldn’t find a Docker image for ombi.

**Comment by tidusjar** [comment]
https://hub.docker.com/r/lsiodev/ombi
