### ISSUE TITLE
V3 - Unable to login to admin account (same as plex.tv account)

### ISSUE THREAD

**Issue by akhan23wgu** [tidusjar/Ombi#1568]
(I know, I know, I shouldn't have used the same username/password as my plex account, found that out after the fact.)

Is there any workaround or do I have to perform a reinstall? A "forgot your password" did not work.

No other user has power user access or admin access.

**Comment by halali** [comment]
Your admin acc must be different from your plex account.

**Comment by akhan23wgu** [comment]
I know - that's why I'm in this dilemma :)

I modified the database file to make another use an admin in the meantime.
Hopefully he can login and create/modify the account.

On Oct 13, 2017 3:21 AM, "halali" <notifications@github.com> wrote:

Your admin acc must be different from your plex account.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/Ombi/issues/1568#issuecomment-336399034>, or mute
the thread

**Comment by PotatoQuality** [comment]
We need to make a check that the importer will check if the username as a local account already exist.

**Comment by akhan23wgu** [comment]
I was successfully able to have the other user create a new local admin account.

**Comment by PotatoQuality** [comment]
We need still a fix in the code for this.  Can we keep this open?

**Comment by snakefeet** [comment]
I have same username/password as Plex account and I am able to login as admin.
Why can't you have the same details?

**Comment by akhan23wgu** [comment]
> I have same username/password as Plex account and I am able to login as admin.
Why can't you have the same details?

On V3?

**Comment by tidusjar** [comment]
I'm slightly confused. What is the issue here?

**Comment by snakefeet** [comment]
Yeah I'm on V3 latest update. 
I have been able to login fine every time. Mac OSX High Sierra.

Only issue I have now is I can't import and users, gives no warnings or error it's Asif the import button is dead. 
The previous update was ok.

**Comment by tidusjar** [comment]
What's in the logs? Please raise a new issue for that.
