### ISSUE TITLE
V3 - Import Plex Users Fail with Special Character Usernames

### ISSUE THREAD

**Issue by jessiebryan** [tidusjar/Ombi#1569]
Hello,

I am unable to import Plex Users that contain special characters - Below is a log with a pseudo-username that fails to import.

`Oct 13 15:07:24 Ombi3 Ombi[6080]: warn: Microsoft.AspNetCore.Identity.UserManager[13]
Oct 13 15:07:24 Ombi3 Ombi[6080]:       User daa876z8-a7b8-45b9-a9ba-783ba09490ee validation failed: InvalidUserName.
Oct 13 15:07:24 Ombi3 Ombi[6080]: fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
Oct 13 15:07:24 Ombi3 Ombi[6080]:       User name 'bart!2017' is invalid, can only contain letters or digits.`

Ver: 3.0.2099

**Comment by tidusjar** [comment]
Please try latest version. this has been fixed.
