### ISSUE TITLE
V3 - On Qnap corerun remain error coreclr_initialize failed - status: 0x80070057

### ISSUE THREAD

**Issue by nephaste** [tidusjar/Ombi#1575]
Hi tidusjar

got request to make the V3 on Qnap

i have a working corerun... but when i launch

[/share/CACHEDEV1_DATA/.qpkg/Ombi3/OmbiV3] # /opt/DotNET/Release/corerun -c /opt/DotNET/Release Ombi
coreclr_initialize failed - status: 0x80070057

I really have no idea how to fix this...

thanks for any help

**Comment by tidusjar** [comment]
Hey!

i'm not familiar with how corerun works since i've never needed to use it. But couldn't you just run the `Ombi` file? Make it an executable e.g. `chmod +x Ombi` ? The working directory also needs to be where the Ombi files are

**Comment by nephaste** [comment]
wow.. i am so stupid... thanks
just got the libunwind.so.8 issue just an export LD_LIBRARY_PATH and it launch..

I was sure corerun command was necessary to launch it... thanks again

can i put libunwind.so.8 in Ombi files are and it will be auto detected ? or i need to export my LD_LIBRARY_PATH ? and is there a way to run as Daemon ?

[/share/CACHEDEV1_DATA/.qpkg/Ombi3/OmbiV3] # ./Ombi --host http://*:8986
Hello, and welcome to the  console application.
This application takes in a data file and attempts to import that data into our systems.
Valid options are:
Ombi 3.0.2113-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.


Press any key to exit

We are running on
/share/CACHEDEV1_DATA/.qpkg/Ombi3/OmbiV3
Hosting environment: Production
Content root path: /share/CACHEDEV1_DATA/.qpkg/Ombi3/OmbiV3
Now listening on: http://0.0.0.0:8986

**Comment by tidusjar** [comment]
Ok excellent. 

For all of your questions, I do not know the answer! Give it a go? Sorry
