### ISSUE TITLE
Welcome E-Mail not sending

### ISSUE THREAD

**Issue by Sm0k3d0uT** [tidusjar/Ombi#1578]
#### Ombi build Version:

V 3.0.2124

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.9.3.4290 

#### Operating System:

Ubuntu 16.04.02 64bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Welcome e-mail in user management doesn't send.

#### Reproduction Steps:

Create new user 
Setup with valid e-mail address 
Press Send Welcome E-Mail Button

**Comment by tidusjar** [comment]
Checked junk?
Please also include some log files

**Comment by Sm0k3d0uT** [comment]
Checked junk/spam folder no e-mails in there from ombi.

Attached is my log file but it doesn't look like anything happened when the button was pressed.
[log-20171016.txt](https://github.com/tidusjar/Ombi/files/1388823/log-20171016.txt)

**Comment by tidusjar** [comment]
Does the user have an email address? And your SMTP settings are correct and the test button works right?

**Comment by Sm0k3d0uT** [comment]
Yes the user has an e-mail address. Test, request and approval e-mails work.

**Comment by tidusjar** [comment]
Is the email valid?

I think you are going to need to do a bit of investigation on your SMTP side of things, can you check what was sent? Sent Folder? 

I am unable to reproduce this.

**Comment by Sm0k3d0uT** [comment]
Here is a screenshot of my sent mail. It can't be an smtp setup issue because all other e-mails are sent. It's like pushing the button does nothing, I don't even see an attempt in my logs.

![sentbox](https://user-images.githubusercontent.com/595687/31670536-d46c1312-b325-11e7-8d01-d50e56e8f9b7.png)
