### ISSUE TITLE
No admin option when logged in as admin

### ISSUE THREAD

**Issue by mdhwoods** [tidusjar/Ombi#1579]
#### Ombi build Version:

V 3.0.2122

#### Update Branch:

Open Beta

#### Media Sever:

Plex
#### Operating System:

qnap nas 64bit running 4.3.3.0299

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

No admin option when logged in as admin, no way to approve requests etc.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Please provide some more information. e.g. browser,
do you have admin permissions, screenshots?

**Comment by mdhwoods** [comment]
This is on Mobil safari. Same issue on chrome. My server and this user has admin rights.

**Comment by mdhwoods** [comment]
not sure why pics didn't show from phone.  This is from chrome.  This is my Server as well as the admin account i set up.

![screen2](https://user-images.githubusercontent.com/27958996/31637532-27b66e98-b29d-11e7-9c07-d62191b55c28.PNG)
![screen](https://user-images.githubusercontent.com/27958996/31637533-27cba47a-b29d-11e7-8df5-14775556b639.PNG)
![screen3](https://user-images.githubusercontent.com/27958996/31637534-27d902b4-b29d-11e7-8607-8eddef364cb3.PNG)

**Comment by tidusjar** [comment]
It's already been approved. Admin requests are auto approved.

**Comment by mdhwoods** [comment]
thanks, i watched the video and didn't catch that admin was auto approved.  Is the build i'm on the latest? its reporting a new release but it seems to be the one im on.  Bug in the updater?

**Comment by tidusjar** [comment]
Latest build is 3.0.2124.
