### ISSUE TITLE
User Management Not Sorting Users

### ISSUE THREAD

**Issue by christronyxyocum** [tidusjar/Ombi#1581]
#### Ombi build Version:

V 3.0.2124

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 4.10.0-19-generic #21-Ubuntu 17.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Logs from the most recent user addition have been rotated out so I don't have any applicable logs.

```

#### Problem Description:

After the initial import of Plex users, any new users that get imported are placed at the bottom of the User Management page and are not sorted alphabetically with no way to sort by column, etc.

IE:

```
Adam
Brian
Chris
Danielle
Eddie
Fran
Gary
Hannah
Ian
Jerssica
Kevin
Calvin
Kristen
Bob
```

#### Reproduction Steps:

Setup Ombi, import users from Plex, view User Management page, add new user to Plex, import users into Ombi again, view user at the bottom of the User Management page.

**Comment by Night1** [comment]
I no longer see this issue in current build 3.0.2131
