### ISSUE TITLE
Re-send requests button

### ISSUE THREAD

**Issue by seffyroff** [tidusjar/Ombi#1584]
#### Ombi build Version:

lsiodev/ombi-preview

#### Update Branch:

lsiodev/ombi-preview

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Docker on Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Problem Description:

As requested in Gitter:

As a user, If an issue prevents requests being sent to the target provider (e.g. Sonarr) I would like a button to resend requests to the provider.  Currently I have to remove the requests and re-add them.

**Comment by PotatoQuality** [comment]
Pleas provide the correct Ombi build. You can find it in the config screen.

**Comment by tidusjar** [comment]
This is more of a feature request I asked him to post :)

**Comment by tidusjar** [comment]
Going to close this for now, this will not be added for the v3 release.
