### ISSUE TITLE
Movies not being added to Radarr

### ISSUE THREAD

**Issue by tomdaniels** [tidusjar/Ombi#1585]
#### Ombi Version
V 2.2.1678
#### Update Branch:
Stable
#### Operating System:
Windows 7/Windows Server 2008 R2
#### Log Level:
Trace
Search Movie "Shallow Grave" hit request > Pop up appears "Successfully added to Radarr"
tracelog:
https://api.themoviedb.org/3/movie/412435?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos

On Radarr side no movie has been added and download not started. 

API Key, Hostname(IP) and Port are correct. 

Not sure how else to trouble shoot this.

**Comment by tomdaniels** [comment]
[ombiTrace.txt](https://github.com/tidusjar/Ombi/files/1394001/ombiTrace.txt)
Full trace log above.

**Comment by tidusjar** [comment]
Please use v3. I have dropped v2 as I'm working on v3.
