### ISSUE TITLE
Issue with Slack notifications

### ISSUE THREAD

**Issue by rixton** [tidusjar/Ombi#1588]
#### Ombi build Version:
V 3.0.2141
#### Update Branch:

Open Beta

#### Me/Embydia Sever:

Plex

#### Media Server Version:

Plex Media Server 3.20.8
#### Operating System:

Debian 9.2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin 

Nothing about Slack in the logs from /opt/Ombi/Logs

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

#### Problem Description:
I cannot get Slack notifications for anything other than the test-notifications as well as new requests, but the ones for Request Approved, Request Available and Request Declined does not post to the Slack-channel

#### Reproduction Steps:
Create a new request, wait for the notification in Slack, sign in to an admin-account, approve / deny the request, nothing happens

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Because admin's do not trigger notifications. These types that you are expecting go out to the user that requested the content. In Slack's case, we do not know who it was to send to.

But I see your point. Would you want this posted to Slack?

**Comment by rixton** [comment]
If admins don´t trigger notifications, then whats the point of having slack-notifications for approvals as it´s only admins that can approve the requests?

Yeah, if it is possible
My idea was to set this up as an request-channel in Slack that notifices the users when anything new has been approved

**Comment by tidusjar** [comment]
This should be fixed in the latest build. Please let me know how it goes, I've triggered notifications on Approve, Decline and Mark Available.
