### ISSUE TITLE
Migrate database from v2 to v3

### ISSUE THREAD

**Issue by tscibilia** [tidusjar/Ombi#1589]
#### Ombi build Version:

V 3.0.2123

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Plex Server v.1.9.5.

#### Operating System:

uname -a.
Linux ombi 4.4.79-1-pve '#'1 SMP PVE 4.4.79-95 (Thu, 31 Aug 2017 13:23:58 +0200) x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
Distributor ID: Ubuntu
Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

I installed v3 into a directory separate from the v2 I had previously running for testing. Is there a way to migrate the user requests to the new version? What is the recommended way to persist the existing data in the new update? 

Also is there a way to have the user login with just the username (similar to v2 no password) or is that feature removed for security?

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
No, the reason it's call V3 is because it's a Major version bump and is not compatible with V2.

You have to start from scratch.

Currently all logins require a password. I will be adding the option to bypass the password in the future.

**Comment by tscibilia** [comment]
Thanks, I wasn't assuming compatibility. I was hoping there would be a way to migrate the request data. Is there potentially a way to edit the Ombi v3 sqlite file? I'm assuming that's not recommended, just thought it should be asked.

**Comment by tidusjar** [comment]
It's possible, but it wouldn't be easy, the data structures are completely different.

**Comment by Sitruk** [comment]
I foolishly assumed it would function like a normal update and was disappointed when it didn't. It's a bummer we can't import our settings from version 2.
