### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by flawlessdeadpixel** [tidusjar/Ombi#1592]
#### Ombi build Version:

V 3.0.2144

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.9.4.4325

#### Operating System:

Mac OS X 10.11 El Capitan

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

NA

#### Problem Description:

Ombi will not launch. Changed working directory in terminal to the correct path. When the command for Ombi is ran, I get an "Illegal instruction: 4" and nothing happens. This is using the osx download zip from the provided link.

**Comment by tidusjar** [comment]
Can you post the full error please?

**Comment by flawlessdeadpixel** [comment]
That is the entire error. I'll attach a screenshot of the terminal window.
![ombierror](https://user-images.githubusercontent.com/25791527/31746086-83c22fc8-b41a-11e7-8f43-8c4d57f2563e.jpg)

**Comment by tidusjar** [comment]
https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x

Looks like .net core 2.0 is only supported on macOS 10.12 "Sierra" and later versions
