### ISSUE TITLE
Add More Unit Tests

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1596]
We need better unit test coverage.

**Comment by AnnahGerletti** [comment]
Looking into your current unit tests.

**Comment by tidusjar** [comment]
Hi @AnnahGerletti !

So you need to fork the repository and then clone it. It's all written in C# using the .Net Core 2.0 framework https://www.microsoft.com/net/core#windowscmd

So yes it would work on macOS!
