### ISSUE TITLE
Landing Page with Text Not Accessible from Mobile Device

### ISSUE THREAD

**Issue by Jakesparrow** [tidusjar/Ombi#1599]
#### Ombi build Version:

V 3.0.2147

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

iOS 11

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```



```

#### Problem Description:

When putting landing page text up, it pushes the "continue" button and all other text off-screen and you can't scroll down to get to it

#### Reproduction Steps:

Add text to landing page, and attempt to access with iOS (possible android as well?)
https://i.imgur.com/nqvSI44.jpg

**Comment by tidusjar** [comment]
Ok i'll fix that, regarding your message, Issues are not part of v3 yet.

**Comment by bromanguydude** [comment]
Having an issue with iOS and also IE which will just stay on Loading... screen forever. FYI. Thanks.

**Comment by tidusjar** [comment]
@bromanguydude please open a different issue.

**Comment by Jakesparrow** [comment]
I got'cha, I'll remove that. Thanks for the heads up!  You rock!

**Comment by weirdcrap** [comment]
Just to update I do not experience this on Android 8.1 w/ Chrome and Ombi v3.0.2234

![screenshot_20171027-143123](https://user-images.githubusercontent.com/22824785/32121950-54d1ee90-bb24-11e7-9553-a9c07ac73ade.png)

**Comment by tidusjar** [comment]
It's probably an iOS issue. Not had time to investigate yet

**Comment by weirdcrap** [comment]
no pressure, just letting you know it appears to indeed by iOS specific.

**Comment by Jakesparrow** [comment]
@weirdcrap  Have  you tried adding more text than that? I had a good bit of text entered and one of my android users reported the same thing to me after some testing, so I took it back off again. I had a couple paragraphs in there lol

**Comment by weirdcrap** [comment]
@Jakesparrow ok you are correct, I just didn't have a big enough wall of text. I don't ever have that much to say to my users lol.

After about 1,100 characters the same thing happened to me.

I suppose the simplest solution (to my plebian brain) is to make the text area overflow and add a scrollbar rather than let it push everything off to the bottom (or possibly the side).

**Comment by Jakesparrow** [comment]
Just checking if someone had a chance to look at this yet?

**Comment by tidusjar** [comment]
@Jakesparrow Nope, this is pretty low on my list of priorities at the moment.

**Comment by louis-lau** [comment]
@Jakesparrow fixed it :)

**Comment by Jakesparrow** [comment]
Huzzah! Thanks a lot!
