### ISSUE TITLE
version 3.0.2147 - not able to select any roles

### ISSUE THREAD

**Issue by sliddjur** [tidusjar/Ombi#1600]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex
#### Operating System:

ubuntu 16.10
httpd reverse proxy

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I cannot select any roles for any user. The roles header is there, but there are no checkboxes to select the actual roles. Not on imported users. Neither can I create a new local user, since I must assign atleast one role.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Can you show a screenshot?

**Comment by sliddjur** [comment]
Actually I got it working now. I reinstalled from latest source, but I used my reverse proxy to access it first time. I realized I never got a setup wizard. So I reinstalled again and deleted the sqlite file, and went to the non-reverse proxy web page and it gave me the setup wizard. Now I get the groups again.
