### ISSUE TITLE
[Request] API Change

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#1601]
Hi,

I want to formally make a request to edit/change the API.  

I want to be able to POST or GET to the API, and set the approval flag to true.  Ombi would have to then process the request as usual after this flag change.

I would also like to do the same to the denied flag.

**Comment by tidusjar** [comment]
Updated the following endpoints:

```
POST /api/v1/request/tv/approve (NOTE This was previously `/api/v1/request/tv/child/approve`)
PUT /api/v1/request/tv/deny

POST /api/v1/request/movie/approve
PUT /api/v1/request/movie/deny
```
They now accept the following body:

    {
        "id": 123
    }

Where "id" is the internal Ombi request id

**Comment by causefx** [comment]
@tidusjar  Hey man, sorry to add on, but is it possible at all to add an option to mark as available? 

P.S. 

I got the code working for everything else.

**Comment by tidusjar** [comment]
There we go,

So we now also have 
```
POST /api/v1/request/tv/available
POST /api/v1/request/tv/unavailable
POST /api/v1/request/movie/available
POST /api/v1/request/movie/unavailable
```

These accept the same body as `POST /api/v1/request/movie/approve`

**Comment by causefx** [comment]
You my friend, Are the best!
