### ISSUE TITLE
TV Show availability button

### ISSUE THREAD

**Issue by goofballtech** [tidusjar/Ombi#1602]
#### Ombi build Version:

V 3.0.2147

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows server

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
none
```

#### Problem Description:

When searching for tv shows that already exist on plex the green "available" shows inline with continuing/ended and release date info and the view on plex button is available but there is still a request button. Even for shows that are already 100% available so there isn't even any "fill in" requests possible. Is this intentional for some reason? if so would it be possible to put something a bit more visible that says in plain text "already exists" because i have gotten a couple repeat requests from users that are less savvy. 

Thanks as always. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
If the shows are 100% available it should not allow you to request. I must have missed this out, thanks!

**Comment by goofballtech** [comment]
100% minus specials, which you don't show as options so i am assuming they don't count. 
For whatever that's worth.

**Comment by tidusjar** [comment]
Yeah we ignore specials

**Comment by jpeters** [comment]
I have found only one challenge with the fix for this. If a show has been requested, but no episodes are available yet, it shows as available in search. This could be a little misleading. An example show would be Marvel's Runaways (2017). I think the desired behavior would be to display something like processing or requested.
