### ISSUE TITLE
remove tv show requests image stays

### ISSUE THREAD

**Issue by goofballtech** [tidusjar/Ombi#1603]
#### Ombi build Version:

V 3.0.2149

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When removing a requested tv show the image and view button stay visible on the page until a refresh or move to another page and return. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Yeah I'm aware of this, but thanks for raising it! 
I won't forget about it now!

**Comment by goofballtech** [comment]
just trying to bring up thing i know was on v2 that might have been overlooked as i see them. 

Thanks for the great product.

**Comment by tidusjar** [comment]
That's great @goofballtech ! Thanks for the time you are spending raising these, they are very helpful.
