### ISSUE TITLE
Lates Build wont start

### ISSUE THREAD

**Issue by Sm0k3d0uT** [tidusjar/Ombi#1608]
#### Ombi build Version:

V 3.0.2160

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 64Bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Here is what is shown in the console:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Ombi.Store.Context.OmbiContext..ctor() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 17
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 40
Aborted (core dumped)

```

#### Problem Description:

Latest Build won't start.



#### Reproduction Steps:

Downloaded latest build
Extracted files
Copied to Ombi directory overwriting existing files
made Ombi executable  (chmod +x Ombi)
ran Ombi (./Ombi)

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1607
