### ISSUE TITLE
Startup Script not working

### ISSUE THREAD

**Issue by rrbailey89** [tidusjar/Ombi#1609]
#### Ombi build Version:

V 3.0.2162

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 LTS

#### Problem Description:

Been trying to get a startup script working properly, I can start Ombi just fine manually but it wont autostart using this script. 

```
[Unit]
Description=OmbiV3 Test Server
After=network-online.target

[Service]
User=user
Group=user
Type=simple
WorkingDirectory=/opt/Ombi/
ExecStart=/opt/Ombi/Ombi --host http://*:5050
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by mattohm** [comment]
run 'journalctl --follow' in another terminal while you start it to get the error.

**Comment by causefx** [comment]
Here is mine:
```
[Unit]
Description=Systemd script to run Ombi as a service
After=network-online.target

[Service]
User=causefx
Group=causefx
WorkingDirectory=/opt/OmbiV3/
ExecStart=/opt/OmbiV3/Ombi
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by tidusjar** [comment]
Not directly related to this repository so going to close, CauseFX has provided you with a working example :)
