### ISSUE TITLE
Users with the Power User role cannot approve TV Shows

### ISSUE THREAD

**Issue by iVirus** [tidusjar/Ombi#1610]
#### Ombi build Version:

V 3.0.2162

#### Update Branch:

Open Beta/DotNetCore

#### Media Sever:

Plex

#### Operating System:

Docker/Ubuntu

#### Problem Description:

A user with the Power User, Request TV, and Request Movie roles can _request_ Movies and TV Shows. The user can _approve_ Movies but _not_ TV Shows.

#### Reproduction Steps:

- Add a user with the Power User, Request TV, and Request Movie roles
- Login as new user
- Request a TV Show
- Go to Requests and find no option to approve newly requested TV Show

**Comment by mdthejericho** [comment]
This is observed in 3.0.3383 and 3.0.3164

Kinda defeats the purpose of power user.
