### ISSUE TITLE
breaks with mono 5.4.x

### ISSUE THREAD

**Issue by evanrich** [tidusjar/Ombi#1611]
ombi version: 2.2.1678
mono version: 5.4.x (sorry didn't write it down)

I did the latest pull from linuxserver/ombi:latest, started up ombi, and while everything looked ok, suddenly requests stopped working.  Users would receive a "something went wrong" message.  Looking at trace logs, everything looked ok, but the request would never process.  I turned on tracing, tried it myself, no joy.   I rolled back to linuxserver/ombi:52 ( the previous version using mono 5.2.0.215) and everything works again.

One thing I noticed after rolling back, was that with tracing enabled, the JSON output in logs was properly formatted, whereas, with 5.4.x, it was one long run-on line. 

I would not upgrade to mono 5.4 for now.

**Comment by PotatoQuality** [comment]
Version 2.X is not supported anymore. Please don't open a issue for the 2.x version.

**Comment by evanrich** [comment]
@PotatoQuality  the latest release is 2.2.1?

**Comment by PotatoQuality** [comment]
@evanrich no that is V3. 
And you still ignore the text when you open a issue:

![image](https://user-images.githubusercontent.com/2944704/31867294-3202652e-b78d-11e7-8ced-5e7b5d6af390.png)

**Comment by evanrich** [comment]
![screen](https://user-images.githubusercontent.com/518320/31867478-5db0a9d0-b745-11e7-866e-768c255141ed.JPG)

no need to be negative man... had the "LATEST RELEASE" said 3.x, i would've upgraded first.  Maybe post in your release area. geez

**Comment by PotatoQuality** [comment]
![image](https://user-images.githubusercontent.com/2944704/31867600-0027258e-b793-11e7-8e28-3de990e3add7.png)
