### ISSUE TITLE
Error Loading on Landing Page

### ISSUE THREAD

**Issue by bromanguydude** [tidusjar/Ombi#1612]
--->

#### Ombi build Version:

V 3.0.2165

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

On iOS and IE I have found that the landing page will never load, it will just sit there with "Loading..."

#### Reproduction Steps:

Have tested this with multiple PCs with IE on different IPs and with different iOS devices.

**Comment by tidusjar** [comment]
Is there an error in the browser on IE? You can open the development tools and check the console. 

Also what version of ie?

**Comment by bromanguydude** [comment]
IE 11.1715.14393

Console shows only: 

Current window: mydomain.com
Current window: mydomainredirect.com

Nothing else ever loads. Similar behavior with iOS browser.

**Comment by bromanguydude** [comment]
Seems that new build has resolved this issue for iOS. IE still having some issues loading.

**Comment by tidusjar** [comment]
So there are some fixes for iOS (We cannot support iOS 9) but everything should work in 10.3.

Regarding IE, that's difficult, We have pollyfills to downgrade any ES6 code, but with the tech stack I am using and how bad IE is i'm going to have to say I cannot support IE.
