### ISSUE TITLE
Ombi on mobile - issues

### ISSUE THREAD

**Issue by gilbN** [tidusjar/Ombi#1615]
#### Ombi build Version:

3.0.2165
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 4.9.30-unRAID #1 SMP PREEMP (Docker)
iOS 11 - iPhone 8+

#### Problem Description:

I'm having issues using the UI on mobile.  Requesting works, but navigating the settings doesn't work. The only setting I can access is "Ombi"
And removing the green "Request Added" popup doesn't work. Hitting X does nothing. 

#### Reproduction Steps:
Navigate the settings meny

**Comment by tidusjar** [comment]
This should be fixed with the latest build
