### ISSUE TITLE
Error with Medusa

### ISSUE THREAD

**Issue by lilp69** [tidusjar/Ombi#1616]
Hi,
I've this error when trying to adding TVshows from Medusa.
#### Ombi build Version:

Application Version: | 2.2.1678
OS: | Mono
System Version: | 5.4.0.201 (tarball Fri Oct 13 22:01:59 UTC 2017)
Branch: | Stable
Log Level: | Info
Database Location: | /opt/Ombi/Release/Ombi.sqlite
Running Directory: | /opt/Ombi/Release

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 at Ombi.Api.ApiRequest.ExecuteJson[T] (RestSharp.IRestRequest request, System.Uri baseUri) [0x00051] in <2a63c45e97a245c1bf3c2df5f23972c5>:0 at Ombi.Api.SickrageApi+<>c__DisplayClass7_0.b__1 () [0x0000b] in <2a63c45e97a245c1bf3c2df5f23972c5>:0 at Polly.Policy+<>c__DisplayClass8_0`1[TResult].b__0 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.RetrySyntax+<>c__DisplayClass14_0.b__1 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at (wrapper delegate-invoke) System.Func`1[Polly.Utilities.EmptyStruct]:invoke_TResult () at Polly.Retry.RetryEngine.Implementation[TResult] (System.Func`1[TResult] action, System.Collections.Generic.IEnumerable`1[T] shouldRetryExceptionPredicates, System.Collections.Generic.IEnumerable`1[T] shouldRetryResultPredicates, System.Func`1[TResult] policyStateFactory) [0x00098] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.RetrySyntax+<>c__DisplayClass14_1.b__0 (System.Action action, Polly.Context context) [0x00027] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.Policy.Execute[TResult] (System.Func`1[TResult] action, Polly.Context context) [0x0002c] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Polly.Policy.Execute[TResult] (System.Func`1[TResult] action) [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0 at Ombi.Api.SickrageApi.Ping (System.String apiKey, System.Uri baseUrl) [0x00067] in <2a63c45e97a245c1bf3c2df5f23972c5>:0 at Ombi.UI.Modules.ApplicationTesterModule.SickRageTest () [0x00041] in :0 	Ombi.UI.Modules.ApplicationTesterModule	Warn	24/10/2017 11:17:15

**Comment by Codehhh** [comment]
Ombi v2 isn't supported anymore, try v3!

**Comment by lilp69** [comment]
I don't see download link for v3.

**Comment by tidusjar** [comment]
It's on the readme.

**Comment by lilp69** [comment]
Sorry but I don't find the linux.zip file for V3...

**Comment by mattohm** [comment]
Click the download link and it'll come up with a list.  The most recent is:
https://ci.appveyor.com/api/buildjobs/w8rhikq01d1eavt9/artifacts/linux.tar.gz

**Comment by lilp69** [comment]
I follow this tuto for install on Ubuntu, but doesn't work : https://github.com/tidusjar/Ombi/wiki/Installation

**Comment by mattohm** [comment]
What doesn't work?

**Comment by lilp69** [comment]
I download the tar.gaz, I Untar it on /Ombi, make chmod +X, but ./Ombi don't run anything.

**Comment by mattohm** [comment]
Does it give you any output?

**Comment by lilp69** [comment]
Yes, ./Ombi give me this output : ./Ombi: 1: ./Ombi: Syntax error: ")" unexpected

**Comment by Codehhh** [comment]
tar.gz is a compressed file so you need to decompress it before you can run it.

**Comment by lilp69** [comment]
I've untar -xzvvf before.
