### ISSUE TITLE
Can not expand setting options on mobile browser

### ISSUE THREAD

**Issue by thetvguru** [tidusjar/Ombi#1619]
#### Ombi build Version:

V 3.0.2172

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

iOS11

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

After entering settings I am unable to expand Cinfiguration, Media Server, TV, Movies, Notifications or System. 
When clicked on they only highlight. I am able to select ‘Ombi’ since it is not a drop down.

#### Reproduction Steps:

This issue has persisted since the initial public beta and occurs in Safari, Chrome and Firefox on my iPad and iPhone running iOS11.

**Comment by tidusjar** [comment]
Duplicate #1615
