### ISSUE TITLE
html page title of the application is set to Ombi

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#1622]
#### Ombi build Version:

V 3.0.2172

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.0-693.2.2.el7.x86_64

#### Problem Description:

 html page title of the application is hardcoded to Ombi instead of the ApplicationName set in settings

#### Reproduction Steps:

Set the application name in settings. Page title does not change.

**Comment by overdox** [comment]
Same issue on the same build
Ombi: V 3.0.2172
OS: Linux 3.16.0-4-amd64
