### ISSUE TITLE
Report Issue Button

### ISSUE THREAD

**Issue by bromanguydude** [tidusjar/Ombi#1624]
--->

#### Ombi build Version:

V 3.0.2172
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Win 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Was the report problem feature removed from V3?

#### Reproduction Steps:

Really liked that feature for users, cut down on direct contact from users on issues. Thanks.

**Comment by tidusjar** [comment]
It wasn't removed. I've just not added it yet.
