### ISSUE TITLE
Plex 'My Home' users are not importing (Including self)

### ISSUE THREAD

**Issue by Nomelas** [tidusjar/Ombi#1625]
#### Ombi build Version:

V 3.0.2174

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 1.9.6.4385

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Nothing Applicable

```

#### Problem Description:

As the title says. I've connected plex to ombi, and when go to 'User Management Settings' and select 'Run Importer' it only adds friends I shared my plex with, and neither my own plex account nor any 'Managed User' I created within Plex are imported.

#### Reproduction Steps:

'Run importer' for Plex

**Comment by Nomelas** [comment]
also, it would be nice if the 'admin' role didn't automatically inherit the auto approve roles - I'd like to be able to make myself an admin, but have to still approve my own stuff (so I can set the base directory before approving)

**Comment by PotatoQuality** [comment]
home users are not supported.

Server owners are not imported beceause hou make on the begin of the install an Admin account  doe ombi.

**Comment by parkerreno** [comment]
@PotatoQuality 
> home users are not supported.

Do you mean home users that are 'local' accounts or all home users?  Because Ombi v2 imports my home users that are also friends (have their own plex accounts) but Ombi v3 does not.  This is pretty important functionality to me.

**Comment by tidusjar** [comment]
@parkerreno Correct, v2 did import them, but they had no password so you could never login as them
