### ISSUE TITLE
All Users are able to see who requested everything

### ISSUE THREAD

**Issue by MrDragonsEye** [tidusjar/Ombi#1629]
#### Ombi build Version:
V 3.0.2184
#### Update Branch:
Open Beta
#### Media Sever:
Plex
#### Media Server Version:
Plex Version 1.9.6.4385
#### Operating System:
Server 2012 R2 - Microsoft Windows 6.3.9600
#### Problem Description:
All users are able to see the user who requested any media requests.
The option to hide this was available in V2, just wondering if this was coming back?
#### Reproduction Steps:
Logged in as non-admin test user and can see any admin's or other users name in the "Requested By:" field.

**Comment by tidusjar** [comment]
This has not been developed yet, I will be adding it back in at some point.

**Comment by MrDragonsEye** [comment]
Awesome, thanks! (:
