### ISSUE TITLE
"Forgot your password?" dispay/render issue

### ISSUE THREAD

**Issue by MrDragonsEye** [tidusjar/Ombi#1630]
#### Ombi build Version:
V 3.0.2184
#### Update Branch:
Open Beta
#### Media Sever:
Plex
#### Media Server Version:
Plex Version 1.9.6.4385
#### Operating System:
Server 2012 R2 - Microsoft Windows 6.3.9600
#### Problem Description:
From the login page, when requesting a forgotten password email, the page dosen't remove the old screen layout and renders the box behind the login.
This is resovled by refreshing the page.
#### Reproduction Steps:
Normal Login screen (https://plex.theraistricks.uk/home/login)
https://i.imgur.com/m67jt6m.jpg
After pressing "Forgot your password?" (https://plex.theraistricks.uk/home/reset)
https://i.imgur.com/MpjBIDG.jpg
After pressing either F5 or Ctrl + F5 on https://plex.theraistricks.uk/home/reset
https://i.imgur.com/bSbCkEA.png

**Comment by tidusjar** [comment]
It's because of #1631 there is an error on the page. If I fix #1631 then this will also be resolved.
