### ISSUE TITLE
Unable to sort requests or hide available

### ISSUE THREAD

**Issue by MrDragonsEye** [tidusjar/Ombi#1633]
#### Ombi build Version:
3.0.2188
#### Update Branch:
Open Beta
#### Media Sever:
Plex
#### Media Server Version:
Plex Version 1.9.6.4385
#### Operating System:
Server 2012 R2 - Microsoft Windows 6.3.9600
#### Problem Description:
Feel free to close this if the reason if the same  #1629.

Unable to sort the TV or Movie requests by variables such as release date or date requested etc just like in V2.
Also, the ability to hide available requests would be amazing as this was also in V2 and meant that you only saw the requests that were not available yet.  It kept the list small and quick to read through, knowing that if it's in the list, it's being requested but just not available yet 
#### Reproduction Steps:
NA

**Comment by tidusjar** [comment]
Sorting and filtering is not there yet. i'll be adding this. But there is a searchbar that you can use for now
