### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by i2fat2kidnap** [tidusjar/Ombi#1636]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10 - 32 bit

#### Problem Description:

Ombi v3 does not currently support 32-bit operating systems

**Comment by PotatoQuality** [comment]
its a work in progess thing but not a very high priority at the moment

**Comment by i2fat2kidnap** [comment]
Jamie asked me to put it as an issue, but appreciate the follow up.

**Comment by PotatoQuality** [comment]
im sorry about that

**Comment by kushfest** [comment]
I'm another one of those unfortunate souls stuck on 32-bit. At the direction of TidusJar, I'm posting on here to ask about a 32-bit version. Thanks in advance!

**Comment by i2fat2kidnap** [comment]
Thanks for all the hardwork! Any update on this issue?

**Comment by tidusjar** [comment]
Nope not yet! Soon

**Comment by tidusjar** [comment]
It has now been added

**Comment by i2fat2kidnap** [comment]
Awesome, thanks tidusjar!

**Comment by DSchau** [comment]
@tidusjar where exactly can I get the 32-bit version for Linux? I see Windows, but not Linux!

Great work on this BTW, really looking forward to trying it out!

**Comment by tidusjar** [comment]
Linux coming soon.

**Comment by tidusjar** [comment]
No immediate plans. People stopped asking for this.

**Comment by jeffersonmouze** [comment]
linux x86 version +1!!!
