### ISSUE TITLE
Reverse proxy issue v3

### ISSUE THREAD

**Issue by Fma965** [tidusjar/Ombi#1641]
#### Ombi build Version:

V 3.0.2239

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Reverse proxy not working, tries to read the language translation file from root not my base directory, also when trying to login via the reverse proxied url it shows
VM768:1 POST https://URL/requestv3/api/v1/token/ 400 (Bad Request)

both of the below don't work

	# Ombi v3
	location /requestv3 {
		include /config/nginx/proxy.conf;
		proxy_pass http://192.168.1.2:5001;
	}

	# Ombi v3
	location /requestv3 {
		include /config/nginx/proxy.conf;
		proxy_pass http://192.168.1.2:5001/requestv3;
	}

#### Reproduction Steps:

try to do a reverse proxy.

**Comment by Fma965** [comment]
![image](https://user-images.githubusercontent.com/1707290/32136637-157ea70c-bc09-11e7-8f93-7e07b6bccb18.png)

**Comment by PotatoQuality** [comment]
@Fma965 what is your config in ombi on the baseurl?

**Comment by Fma965** [comment]
/requestv3

ombi v2 works fine with this setup as /request instead of /requestv3

**Comment by tidusjar** [comment]
Make sure the base URL is set in the ombi settings.

**Comment by tidusjar** [comment]
I actually broke it even more...

**Comment by Fma965** [comment]
Still not working, no longer has 404's but won't log me in and says password is incorrect, if i got to the internal ip it's fine.

**Comment by tidusjar** [comment]
@Fma965 The original issue is fixed. The text is now showing correctly. Regarding your user/pass issue, make sure you are using the correct credentials. If you think there is something wrong then please raise a separate issue.

**Comment by Fma965** [comment]
in all fairness that was never my issue, if you read the first message you will see it clearly says "also when trying to login via the reverse proxied url it shows
VM768:1 POST https://URL/requestv3/api/v1/token/ 400 (Bad Request)"

which it still does.

I am using the correct credentials i can log in perfectly fine from a windows 10 VM on the same server via 192.168.1.2:5001/requestsv3 the issue is with the reverse proxy.

**Comment by tidusjar** [comment]
If you have having a issue logging in with your reverse proxy setup jump on Gitter and ask some of the guys. I don't know much about nginx so it's difficult for me to assist you.

**Comment by Fma965** [comment]
i appreciate the advice but i have it set up identically to the live version of v2 i'm running. the issue is with v3 not my reverse proxy. I have also wrote a complete guide on unraid and reverse proxying so know what i am doing in that regard.

Regardless you clearly just want to mark this issue as solve so go ahead.

**Comment by tidusjar** [comment]
What is the exact text you have in the base URL field in the ombi settings?

**Comment by Fma965** [comment]
exactly what i said in the second post of this issue

/requestv3

and this

# Ombi v3
location /requestv3 {
	include /config/nginx/proxy.conf;
	proxy_pass http://192.168.1.2:5001/requestv3;
}

which is indentical to my ombi v2 setup with a different root

# Ombi v2
location /request {
	include /config/nginx/proxy.conf;
	proxy_pass http://192.168.1.2:5001/request;
}

**Comment by Fma965** [comment]
do you want me to try a fresh config incase your old version broke something and it needs to be re-set up?

**Comment by PotatoQuality** [comment]
@Fma965 can you give it a shot?

**Comment by Fma965** [comment]
Yeah i can do but not for a bit, i'll get back to you ASAP :)

**Comment by Fma965** [comment]
nope hasn't made any difference what so ever. 

still complains about 

VM768:1 POST https://URL/requestv3/api/v1/token/ 400 (Bad Request)"

**Comment by Fma965** [comment]
however i have figured the issue out but it doesn't explaiin why it works on v2 and not v3.

something in this included config file breaks it.

`proxy_connect_timeout   59s;
proxy_send_timeout      600;
proxy_read_timeout      36000s;  ## Timeout after 10 hours
proxy_buffer_size       64k;
proxy_buffers           16 32k;
proxy_pass_header       Set-Cookie;
proxy_hide_header       Vary;

proxy_busy_buffers_size         64k;
proxy_temp_file_write_size      64k;

proxy_set_header        Accept-Encoding         '';
proxy_ignore_headers    Cache-Control           Expires;
proxy_set_header        Referer                 $http_referer;
proxy_set_header        Host                    $host;
proxy_set_header        Cookie                  $http_cookie;
proxy_set_header        X-Real-IP               $remote_addr;
proxy_set_header        X-Forwarded-Host        $host;
proxy_set_header        X-Forwarded-Server      $host;
proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Ssl         on;
proxy_set_header        X-Forwarded-Proto $scheme;

proxy_buffering         off;
proxy_redirect          off;

## Required for Plex WebSockets
proxy_http_version      1.1;
proxy_set_header        Upgrade         $http_upgrade;
proxy_set_header        Connection      "upgrade";`

I can't however confirm what and i can confirm that this same config works in ombi v2

**Comment by overdox** [comment]
Can confirm that Apache reverse proxy works fine with v3 atleast. Have you tried starting with a basic nginx config and see if that works?

**Comment by Niksal12** [comment]
I am using nginx with the below config and it works fine for me. Although I am using a sub domain and not a sub directory

`server {
# The IP that you forwarded in your router (nginx proxy)
  listen xx.xx.xx.xx:80 default_server;
# Make site accessible from http://localhost/
 server_name sub.domain.com;

# The internal IP of the VM that hosts your Apache config
 set $upstream xx.xx.xx.xx;

location / {
 proxy_pass_header Authorization;
 proxy_pass http://xx.xx.xx.xx:5000; 
 proxy_set_header Host $host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_http_version 1.1;
 proxy_set_header Connection "";
 proxy_buffering off;
 client_max_body_size 0;
 proxy_read_timeout 36000s;
 proxy_redirect off;

 }
}`

**Comment by christronyxyocum** [comment]
Not sure why, but it's this line that's breaking it:

`proxy_set_header Host $host;`

Removing that from my block for Ombi v3 allows the Reverse Proxy to work:

`        location /ombi/ {
                auth_request /auth-user;
                include /config/nginx/proxy.conf;
                proxy_pass http://docker.yocum.local:3579;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }`

**Comment by Fma965** [comment]
I still don't understand why this is "closed" i mean thats a bug with your new v3 just "fobbing" the issue off as closed because we found the reason doesn't make the issue closed.

**Comment by tidusjar** [comment]
What do you expect me to do? There is a solution above. 

Please remember that this project is maintained and developed in my free time, for absolutely free. Outside of my free time, I have a full time job, a baby and a wife.

**Comment by Fma965** [comment]
"There is a solution above"
I'm not sure a developer should say that is a solution, removing a line of code that works for v2 and all my other services, sonarr,radarr,organizr,plexpy etc just so it can work with v3 doens't seem much like a solution to me.

I have created various applications over the years for free and without pay so completely understand that but i would also not just close a issue once the reason is found without actually figuring out why, no rush but closing a ticket without investigation is just bad development.

**Comment by Niksal12** [comment]
Have you tested every other part of your setup? Like I said, I am using that config with v3 with no issues.

**Comment by Fma965** [comment]
@Niksal12 how can i test every other part of my setup? what exactly needs to be tested? this isn't an issue with my nginx config as it works perfectly fine with ombi v2 , sonarr, plex, plexpy, radarr, headphones, nzbget, nzbhydra, nextcloud, netdata and more. 

I'm done discussing this issue so just close it but i bet i won't be the last to report this "bug"

**Comment by PotatoQuality** [comment]
@fma965 im  following your point. but im wondering what the trouble is to delete that line out of your proxy config.
will it give you a problem on your site?

we happy that you are reporting bugs. we try to fix or find a solution. we are not always find a wat that we can fix on uur site. of we can find a solution that will be great.

**Comment by Fma965** [comment]
@PotatoQuality no there is no problem but i guess being a small dev my self telling the end user to do something to fix your problem isn't a solution. maybe thats just me?

either way it's all good without those lines.

**Comment by PotatoQuality** [comment]
why is changing your config not a solution?

**Comment by PotatoQuality** [comment]
we dont say in out github page that we support proxy reserve at all

**Comment by PotatoQuality** [comment]
@Fma965 where did you read that we do a official support doe that feature in v3?

**Comment by PotatoQuality** [comment]
feel free to do a pr doe fizing the code of you still thing there is a problem in our code

**Comment by Fma965** [comment]
where was it ever a feature in v2. now you are just being a ass so i'm done.

**Comment by Fma965** [comment]
do you want to maybe check what your write before "keyboard warrioring" away. like i said im done. goodbye.

**Comment by PotatoQuality** [comment]
@Fma965 pleas show me more respect and act normal.
its  not nice how you are acting right now.

**Comment by Fma965** [comment]
you are the one who is blurting things out before even looking at what your wrote and then expecting me to understand what ever bs it is you just wrote. also from what i can see you have done 32 commits, tidusjar has done 600 so i wouldn't really call it "our code"

**Comment by PotatoQuality** [comment]
our code = a general term.

**Comment by PotatoQuality** [comment]
@Fma965 pleas show me more respect and act normal.
its not nice how you are acting right now

**Comment by Fma965** [comment]
please stop filling my email up with your repeated responses.
