### ISSUE TITLE
Login Place Holder Bug

### ISSUE THREAD

**Issue by jrdnlc** [tidusjar/Ombi#1642]
See below photo of login page. Running Obi v3.0.2239 @tidusjar 

![screen-shot-2017-10-27-at-7 36 06-pm](https://user-images.githubusercontent.com/15741144/32136899-86085e48-bbcb-11e7-9a78-fdb3013ac7bc.png)

**Comment by PotatoQuality** [comment]
nice logo xD

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1641
