### ISSUE TITLE
Docker Development Environment Instructions

### ISSUE THREAD

**Issue by gugahoi** [tidusjar/Ombi#1647]
I am trying to get the application running from source in Docker so that I can contribute back however I have little experience in `.Net`. I presume I can run this off of [Microsoft's `dotnet`](https://hub.docker.com/r/microsoft/dotnet/) container, if so what other requirements other than dotnet? NPM, Nuget? 

Furthermore what are the commands to compile the application or to just run from source? If I place the `src` folder in `/app` in my container and try to run it I run into the following error:

```bash
root@7696d0447744:/app/Ombi# dotnet run -p Ombi.csproj
/app/Ombi/Ombi.csproj(26,5): error MSB3073: The command "npm run-script vendor" exited with code 1.

The build failed. Please fix the build errors and run again.
```

So I installed npm@5.4.2 and ran `npm install` and tried again with a little more success:

```bash
root@7696d0447744:/app/Ombi# dotnet run -p Ombi.csproj
Using launch settings from Properties/launchSettings.json...
Hello, welcome to Ombi
Valid options are:
Ombi 1.0.0
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on http://*:5000
/app/Ombi
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Ombi.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: /app/Ombi
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
```

However visiting `http://localhost:5000/` leads me to a page with `Loading...` forever. Developer console tells me  `GET http://localhost:5000/dist/main.js 404 (Not Found)`. How do I compile this `js` file? Is there a `dotnet blah` command I can run? Or is the gulp task missing? Would love some assistance...

**Comment by gugahoi** [comment]
Ok so it seems `Styles.scss` starts with a capital letter but imports use `styles.scss`, got a little further. How is this building successfully in CI with the imports being wrong?

**Comment by tidusjar** [comment]
You need to run some gulp taks. Everyone.g. gulp publish. 

There already is a docker container available for V3 by the Linux server.io team.

**Comment by gugahoi** [comment]
Sorry if I wasn't clear, I understand you already have pipelines that produce runnable artefacts in AppVeyor. 

What I want is to be able to contribute to the project (pull requests) however I can't install the dependencies on my computer so I am trying to create a development environment inside a container - this will also allow for anyone to be able to get up and running quickly without needing to install anything (_except for docker_). 

I have so far identified that `dotnet` and `npm` are the requirements to get this project compiling however I am still running into problems like the one I posted above about [`styless.scss`](https://github.com/tidusjar/Ombi/blob/DotNetCore/src/Ombi/ClientApp/styles/Styles.scss) being capitalised in the file name but [being imported lower case](https://github.com/tidusjar/Ombi/blob/DotNetCore/src/Ombi/ClientApp/styles/_imports.scss) which obviously makes webpack imports break. 

Unless I am missing something obvious?

**Comment by tidusjar** [comment]
Ah ok.

so the process would be:

1. dotnet restore (Restores nuget packages)
1. dotnet build
1. npm install
1. gulp publish

Interesting about the styles breaking for you, i'm not sure why but it works fine on mine and other developers setups and also the build server 😖

**Comment by gugahoi** [comment]
Perfect, I'll give it another go next time I'm in front of the computer.

**Comment by tidusjar** [comment]
Going to close this for now, any issues let me know.
