### ISSUE TITLE
New Preview GIF for V3

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1649]
We need a new "preview GIF" for V3 to put in the readme!

**Comment by jrdnlc** [comment]
I'll take care of that

**Comment by jj-owens** [comment]
Pull request created

**Comment by jrdnlc** [comment]
damn you beat me to it! @jj-owens

**Comment by jj-owens** [comment]
@jrdnlc Sorry! I had been working on it for a while, just forgot to comment earlier. I'm new to contributing to open source. My bad.

**Comment by jrdnlc** [comment]
Don't be sorry. It's all good no worries @jj-owens
