### ISSUE TITLE
Issue adding request when request already exists in Sonarr

### ISSUE THREAD

**Issue by mdhwoods** [tidusjar/Ombi#1655]
#### Ombi build Version:

V 3.0.2239

#### Update Branch:

Open Beta

#### Media Sever:plex

Plex

#### Operating System:

qnap nas, runs linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When adding a request for something that exists in sonarr but is not in plexrequests the request does not properly get added.

#### Reproduction Steps:

have request already in sonarr and then add it to plexrequest.

![image](https://user-images.githubusercontent.com/27958996/32241268-15dc24e2-be46-11e7-94e2-e17795fc495a.png)

**Comment by mdhwoods** [comment]
only season 1 is currently on the server. he wants more seasons downloaded so he added to plex request and the screen shot above is the result.  All season are in sonarr, but only season 1 is currently monitored.

**Comment by tidusjar** [comment]
Do you know what he actually requested so I can recreate the issue?

**Comment by mdhwoods** [comment]
he requested season 3, but said he cant request it entirely. all season are in sonar, just only season 1& 2 are currently monitored as i didn't want to get them all at once.

**Comment by tidusjar** [comment]
Ok,

So what are the exact steps? What option are you pressing in the drop-down?

**Comment by mdhwoods** [comment]
i click request, then i click select. once the seasons populated i clicked season 3 then the green submit request button.  Remember this is already in sonarr so i am guessing its not sure how to handle a request that already exists in sonarr but isnt in plex requests. seems it needs a check and if it sees it in sonarr already add the request to requests but not submit it to sonarr.  or pull from sonar whats in there and show that in the requests screen. thinking out loud here as i dont know whats feasible.

**Comment by mdhwoods** [comment]
deleted it from sonarr as well as from ombi, still bugs out. thinks the request exists and shows as processing even with it deleted from sonarr and ombi.

**Comment by tidusjar** [comment]
So you are not selecting any episodes? You just press submit?

**Comment by mdhwoods** [comment]
ya, cant select any individual ep's directly as they all show processing and have the no symbol over them. even with it removed from sonarr as well as plexrequests.

**Comment by tidusjar** [comment]
That's the issue, you shouldn't be able to press that button without selecting episodes!

They are processing because they are already in sonarr

**Comment by mdhwoods** [comment]
even removed from sonarr, still shows processing. i did a test. even with it in sonarr, should be a way to show in ombi no? maybe just season 1 is in sonarr, and they want to request other seasons but its not in ombi yet.

how does someone request a new season when ombi shows them all as processing even when not in sonarr.

ie. season 3 is not in sonarr, but season 1 and 2 are.

**Comment by tidusjar** [comment]
Is season 3 monitored?

**Comment by mdhwoods** [comment]
ok, so now its showing properly. season 3 is allowing me to request. as its not monitored. maybe a delay in when it was deleted from sonarr and when ombi realized?  So only bug i see now is being able to hit send request when nothing was actually selected in the selection method.

**Comment by tidusjar** [comment]
There would be a delay, Ombi runs a job every hour to look at Sonarr and take a local copy of what is monitored and what is not, that way we can speed up stuff.

I shall fix that bug!

**Comment by mdhwoods** [comment]
also, some means to get the request added to ombi even if its already in sonarr and monitored, or is there no way to do that?

**Comment by tidusjar** [comment]
Why would you want to do that? It's monitored so Sonarr will search and pick it up... So it's "Processing" in Ombi

**Comment by mdhwoods** [comment]
but only processing in search, not in requests cause it was never added to request since it was already in sonarr.
