### ISSUE TITLE
Option to remove forgot password on the login page

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#1656]
#### Ombi build Version:

V 3.0.2247

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.0-693.2.2.el7.x86_64 

#### Problem Description:

Option to remove forgotten password on the login page. Unless I am missing something... forgot password does not really work for plex users as their account is really managed by plex.tv.

**Comment by PotatoQuality** [comment]
please use the feature request button on the github page for feature request :)
