### ISSUE TITLE
No email/pushover notifcations are sent on requests or availability

### ISSUE THREAD

**Issue by mmozeiko** [tidusjar/Ombi#1660]
#### Ombi build Version:

3.0.2268

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

not relevant

#### Operating System:

ArchLinux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

There is absolutely nothing in log files
```
$ cat /opt/ombi/Logs/*.txt
2017-11-01 08:41:41.757 +02:00 [Information] Start installing Hangfire SQL objects...
2017-11-01 08:41:41.798 +02:00 [Information] Hangfire SQL objects installed.
2017-11-01 08:41:41.817 +02:00 [Information] Starting Hangfire Server
2017-11-01 08:41:41.819 +02:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-01 08:41:41.819 +02:00 [Information] Using the following options for Hangfire Server:
2017-11-01 08:41:41.819 +02:00 [Information]     Worker count: 1
2017-11-01 08:41:41.819 +02:00 [Information]     Listening queues: 'default'
2017-11-01 08:41:41.819 +02:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-01 08:41:41.819 +02:00 [Information]     Schedule polling interval: 00:00:15
```

#### Problem Description:

No notifications are sent via email or Pushover. Test button for email or Pushover successfully sends me notification. But when user requests movie - no notification is sent to me. Or when Ombi finds that movie has been added (or I manually press Mark Available button) - no email is sent to user who requested this movie. "User" in this case is non-admin user. "I" = admin user.

#### Reproduction Steps:

1) configure e-mail / pushover
2) request movie as non-admin user
3) no email to admin or pushover notification is sent

**Comment by tidusjar** [comment]
Cannot reproduce this, I am getting both email and pushbullet notifications:

![image](https://user-images.githubusercontent.com/6642220/32265826-a8f033e0-bedc-11e7-8bcc-9d82bbedaf38.png)


![image](https://user-images.githubusercontent.com/6642220/32265836-b3fa0c98-bedc-11e7-9fdf-b84d34f008f9.png)

**Comment by mmozeiko** [comment]
I use Pushover, not Pushbullet.

What can I do to diagnose issue in my setup?

Can I build special build with extra logging? Can I insert somewhere extra logging statements to see how it executes email/pushover? I'm ok to edit code and run custom build to figure out what is wrong in my setup. Just point me to relevant place in source code.

**Comment by tidusjar** [comment]
My bad lol! let me check pushover

**Comment by tidusjar** [comment]
![image](https://user-images.githubusercontent.com/6642220/32266654-122ae816-bee0-11e7-9760-e375b21f64ab.png)


Still cannot reproduce

Make sure you have the application and user keys in the settings

**Comment by mmozeiko** [comment]
Yes, I have correct settings for both - email and pushover. Pressing Test button in both cases successfully delivers message - email or pushover notification.

**Comment by tidusjar** [comment]
This may sound like a stupid question, but are they actually enabled? There is an enabled checkbox

**Comment by mmozeiko** [comment]
Yes, they are: https://imgur.com/a/D9VWX

**Comment by mmozeiko** [comment]
I tried to run latest version (3.0.2290) on Windows - notifications are sent to PushOver correctly. But when running same version under ArchLinux in clean space (new DB, no Plex connection, just two users - admin & non-admin) then no notifications are sent to PushOver.

**Comment by tidusjar** [comment]
Ok, going to close for now, if you encounter anything please re comment.

**Comment by mmozeiko** [comment]
No idea what was not working, but I did following:

1) copied Ombi.db file
2) removed ombi folder
3) removed ombi package
4) reinstalled latest version (3.0.2293)
5) moved back Ombi.db file
6) did not change any setting for email/pushover

And now notifications work fine - on request, on availability.

**Comment by mmozeiko** [comment]
Something is still wrong... I had received a few notifications (both e-mail and pushover) since my last comment, but after a while they stopped - no more notifications are going out. And I haven't changed any Ombi configuration, and have not restarted Ombi instance.

**Comment by mmozeiko** [comment]
And today I received all the notifications for new requests. Without any changes to ombi config...

**Comment by mmozeiko** [comment]
And few days after I wrote my previous comment, the notifications are not going through again.

One thing I noticed is that if I press "Mark Available" button on requests page manually then notification is sent to the user. But when Ombi finds itself that movie is available on Plex then most of the time notification doesn't go through.
