### ISSUE TITLE
Duplicate items for all requests

### ISSUE THREAD

**Issue by mmozeiko** [tidusjar/Ombi#1661]
#### Ombi build Version:

3.0.2268

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

not relevant

#### Operating System:

ArchLinux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

There is absolutely nothing in log files

```
$ cat /opt/ombi/Logs/*.txt
2017-11-01 08:41:41.757 +02:00 [Information] Start installing Hangfire SQL objects...
2017-11-01 08:41:41.798 +02:00 [Information] Hangfire SQL objects installed.
2017-11-01 08:41:41.817 +02:00 [Information] Starting Hangfire Server
2017-11-01 08:41:41.819 +02:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-01 08:41:41.819 +02:00 [Information] Using the following options for Hangfire Server:
2017-11-01 08:41:41.819 +02:00 [Information]     Worker count: 1
2017-11-01 08:41:41.819 +02:00 [Information]     Listening queues: 'default'
2017-11-01 08:41:41.819 +02:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-01 08:41:41.819 +02:00 [Information]     Schedule polling interval: 00:00:15
```

#### Problem Description:

All requests are rendered twice. See following screenshot:

https://i.imgur.com/xozWGOz.png

Removing any of two items removes both of them (after page is refreshed).

Sqlite database seems to contain only one copy of request, so this seems to be UI rendering issue?

```
$ sudo sqlite3 -line /opt/ombi/Ombi.db "SELECT * FROM MovieRequests WHERE Title = 'Hello'"
              Id = 18
        Approved = 1
       Available = 0
          Denied = 0
    DeniedReason =
          ImdbId = tt1087856
         IssueId =
        Overview = Hello... is a tale about the events that happen one night at a call center. Told through the views of the protagonist, Shyam, it is a story of almost lost love, thwarted ambitions, absence of family affection, pressures of a patriarchal set up, and the work environment of a globalized office. Shyam is losing his girl friend because his career is going nowhere as he trudges his way around in a call center. His girl friend, Priyanka, is also an agent like him at the call center who is about to be snatched by an NRI technogeek. There is also the aspiring model, Esha, who is hoping for the break that seems to be always already eluding her and the man about town, Vroom, who is into well, things. The housewife, Radhika, who is constantly at the receiving end of her mother-in-law and a beleaguered grandfather, Military Uncle, who has been barred from interacting with his grandchild make up the...
      PosterPath = /lzldL8ZBARt0vt6FdY4ahmIyXRD.jpg
     ReleaseDate = 2008-10-10 00:00:00
     RequestType = 1
   RequestedDate = 2017-11-01 07:08:02.7587144
 RequestedUserId = d9944074-a641-479e-903e-99cc2693be23
          Status = Released
    TheMovieDbId = 20365
           Title = Hello
 QualityOverride = 0
RootPathOverride = 0
```

#### Reproduction Steps:

1) request movie, as user or admin - doesn't matter.
2) check the request page - everything is duplicate.

**Comment by tidusjar** [comment]
I think it's to do with this: https://github.com/tidusjar/Ombi/issues/1497

**Comment by mmozeiko** [comment]
Yes, you are right. Its the same issue as 1497.

Only items after first 5 are duplicated. When I do search, then the first few items are never duplicated.

I thought some upgrade messed up newer requests when I did ombi upgrade after these first 5.

**Comment by mmozeiko** [comment]
No idea what was not working, but I did following:

1) copied Ombi.db file
2) removed ombi folder
3) removed ombi package
4) reinstalled latest version (3.0.2293)
5) moved back Ombi.db file
6) did not change any setting for email/pushover

And now notifications work fine - on request, on availability.
