### ISSUE TITLE
Moving From Plex to emby

### ISSUE THREAD

**Issue by filoor** [tidusjar/Ombi#1662]
Hi,

I want o move from plex to emby.
I have removed plex server from emby but when i search for a exisiting movie it still shows 
watch on plex 
See screenshot

i am on windows with ombi v3.0.2255

![image](https://user-images.githubusercontent.com/3647638/32270492-6c6e2cfa-bef6-11e7-9fa4-59e79cd6e8ab.png)

**Comment by tidusjar** [comment]
Yes, we do not go back into Plex to remove the data. You would have to manually purge the data, either by deleting everything from the PlexContent table inside the `Ombi.db` file or just start again.

**Comment by filoor** [comment]
Hi @tidusjar, 

Thank you, deleting from plexcontent did the trick only if i search for a movie thats on emby 
it will show common requested instead of available see screenshot.
Ar you also gone add watch on Emby if its available on Emby?

![image](https://user-images.githubusercontent.com/3647638/32274517-7dd9112e-bf07-11e7-99fa-929dceac8df1.png)

**Comment by tidusjar** [comment]
Hey!

So you are using an older version where the translations are missing. If you update it will show the correct text. 

No plans to add watch on emby. But it should be doable, just need to work out how to create the link for emby to directly link the media. 

I'll mark this as closed now.

**Comment by filoor** [comment]
Hi @tidusjar 

Thank you hope you find a way to do that
