### ISSUE TITLE
Movies Not Showing as Avaliable

### ISSUE THREAD

**Issue by ExeCuteUK** [tidusjar/Ombi#1663]
**#### Ombi build Version:**

> V 3.0.2291
> Plex 1.96
> Ubuntu 16.04

**#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):**

> 2017-11-01 23:17:57.074 +00:00 [Information] Start installing Hangfire SQL objects...
> 2017-11-01 23:17:57.118 +00:00 [Information] Hangfire SQL objects installed.
> 2017-11-01 23:17:57.141 +00:00 [Information] Starting Hangfire Server
> 2017-11-01 23:17:57.143 +00:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
> 2017-11-01 23:17:57.143 +00:00 [Information] Using the following options for Hangfire Server:
> 2017-11-01 23:17:57.143 +00:00 [Information]     Worker count: 1
> 2017-11-01 23:17:57.143 +00:00 [Information]     Listening queues: 'default'
> 2017-11-01 23:17:57.143 +00:00 [Information]     Shutdown timeout: 1.00:00:00
> 2017-11-01 23:17:57.143 +00:00 [Information]     Schedule polling interval: 00:00:15
> 2017-11-01 23:26:37.944 +00:00 [Error] StatusCode: 429, Reason: 
> 2017-11-01 23:26:37.983 +00:00 [Error] StatusCode: 429, Reason: 

```
> ● ombi.service - Ombi
   Loaded: loaded (/etc/systemd/system/ombi.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-11-01 23:17:52 GMT; 32min ago
 Main PID: 1868 (Ombi)
    Tasks: 50
   Memory: 395.8M
      CPU: 2min 44.754s
   CGroup: /system.slice/ombi.service
           └─1868 /opt/ombi/Ombi --host http://*:1234

Nov 01 23:22:20 pavs Ombi[1868]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeCacher[2002]
Nov 01 23:22:20 pavs Ombi[1868]:       Processed 500 more episodes. Total Remaining 830
Nov 01 23:22:20 pavs Ombi[1868]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeCacher[2002]
Nov 01 23:22:20 pavs Ombi[1868]:       Processed 500 more episodes. Total Remaining 330
Nov 01 23:26:37 pavs Ombi[1868]: fail: Ombi.Api.Api[1000]
Nov 01 23:26:37 pavs Ombi[1868]:       StatusCode: 429, Reason:
Nov 01 23:26:37 pavs Ombi[1868]: fail: Ombi.Api.Api[1000]
Nov 01 23:26:37 pavs Ombi[1868]:       StatusCode: 429, Reason:
Nov 01 23:30:06 pavs Ombi[1868]: info: Ombi.Schedule.Jobs.Couchpotato.CouchPotatoCacher[2007]
Nov 01 23:30:06 pavs Ombi[1868]:       Getting all active movies from CP
```

```
	**Succeeded Jobss**
	#24	CouchPotatoCacher.Start	6.574s	22 minutes ago
	#23	PlexAvailabilityChecker.Start	326ms	30 minutes ago
	#22	PlexEpisodeCacher.Start	1m 14.750s	30 minutes ago
	#21	PlexAvailabilityChecker.Start	14.149s	31 minutes ago
	#20	PlexContentCacher.CacheContent	1m 5.645s	31 minutes ago
	#19	PlexEpisodeCacher.Start	1m 21.694s	31 minutes ago
	#18	PlexContentCacher.CacheContent	58.161s	33 minutes ago
	#17	RadarrCacher.CacheContent	14.168s	37 minutes ago
	#16	SonarrCacher.Start	2m 29.326s	40 minutes ago
	#15	EmbyContentCacher.Start	20.053s	an hour ago
	#14	NotificationService.Publish	13.508s	an hour ago
	#13	NotificationService.Publish	1.017s	an hour ago
	#12	NotificationService.Publish	3.425s	an hour ago
	#11	NotificationService.Publish	4.358s	an hour ago
	#10	PlexAvailabilityChecker.Start	567ms	an hour ago
	#9	PlexEpisodeCacher.Start	2m 13.786s	an hour ago
	#8	PlexContentCacher.CacheContent	38.844s	an hour ago
	#7	PlexAvailabilityChecker.Start	71ms	an hour ago
	#6	PlexEpisodeCacher.Start	3.761s	an hour ago
	#5	PlexContentCacher.CacheContent	9.474s	an hour ago
	#4	PlexAvailabilityChecker.Start	208ms	an hour ago
	#3	PlexEpisodeCacher.Start	75ms	an hour ago
	#2	PlexContentCacher.CacheContent	27.529s	an hour ago
	#1	PlexContentCacher.CacheContent	10.034s	an hour ago
```

**#### Problem Description:**

Movies & TV Shows scan in after a fresh install. But when I search for a Movie I already have, it does not mark it as avaliable.

I have tried 3 fresh installs. Plex details are entered and categories are selected.

TV Shows work fine. Movies above do not.

> http://xxxx::32400/library/sections/2/all?X-Plex-Token=xxxx
> This returns all XML data for my Movie library correctly

It seems to pick up requested movies OK (I assume from CP?).

#### Reproduction Steps:

Fresh install. Enter Plex details, tokens appear.

Select Movies & TV Show Libraries.

Add Sonarr / Couch Potato settings.

Manual Cache of shows/movies button selected.

Search for movie.

**Comment by tidusjar** [comment]
In the logs it shouldn't we something like starting to cache movies. Can you post more of the log please

**Comment by PotatoQuality** [comment]
pleas dont modify the issue format:(

**Comment by ExeCuteUK** [comment]
Ive added a new movie library into Plex and selected that box only to see if it adds anything into the log file. The log file in /ombi/logs contains pretty much the same information as in the original post.

If i look on the main SSH terminal I can see its updating.

Nov 02 08:03:15 pavs Ombi[27945]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Nov 02 08:03:15 pavs Ombi[27945]:       Adding movie The Human Centipede (First Sequence)
Nov 02 08:03:15 pavs Ombi[27945]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Nov 02 08:03:15 pavs Ombi[27945]:       Adding movie Human Traffic
Nov 02 08:03:15 pavs Ombi[27945]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Nov 02 08:03:15 pavs Ombi[27945]:       Adding movie The Hunchback of Notre Dame
Nov 02 08:03:16 pavs Ombi[27945]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Nov 02 08:03:16 pavs Ombi[27945]:       Adding movie The Hunger Games
Nov 02 08:03:16 pavs Ombi[27945]: info: Ombi.Schedule.Jobs.Plex.PlexContentCacher[0]
Nov 02 08:03:16 pavs Ombi[27945]:       Adding movie The Hunger Games: Catching Fire

**Entire log contents of /opt/ombi/Logs/log-20171102.txt**

2017-11-02 07:36:36.032 +00:00 [Information] Start installing Hangfire SQL objects...
2017-11-02 07:36:36.301 +00:00 [Information] Hangfire SQL objects installed.
2017-11-02 07:36:36.326 +00:00 [Information] Starting Hangfire Server
2017-11-02 07:36:36.329 +00:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-02 07:36:36.329 +00:00 [Information] Using the following options for Hangfire Server:
2017-11-02 07:36:36.329 +00:00 [Information]     Worker count: 1
2017-11-02 07:36:36.330 +00:00 [Information]     Listening queues: 'default'
2017-11-02 07:36:36.330 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-02 07:36:36.330 +00:00 [Information]     Schedule polling interval: 00:00:15
2017-11-02 07:42:05.661 +00:00 [Information] Hangfire Server stopped.
2017-11-02 07:44:04.216 +00:00 [Information] Start installing Hangfire SQL objects...
2017-11-02 07:44:04.306 +00:00 [Information] Hangfire SQL objects installed.
2017-11-02 07:44:04.337 +00:00 [Information] Starting Hangfire Server
2017-11-02 07:44:04.340 +00:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-02 07:44:04.340 +00:00 [Information] Using the following options for Hangfire Server:
2017-11-02 07:44:04.340 +00:00 [Information]     Worker count: 1
2017-11-02 07:44:04.340 +00:00 [Information]     Listening queues: 'default'
2017-11-02 07:44:04.340 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-02 07:44:04.340 +00:00 [Information]     Schedule polling interval: 00:00:15
2017-11-02 07:48:34.019 +00:00 [Information] Hangfire Server stopped.
2017-11-02 07:57:24.763 +00:00 [Information] Start installing Hangfire SQL objects...
2017-11-02 07:57:24.858 +00:00 [Information] Hangfire SQL objects installed.
2017-11-02 07:57:24.887 +00:00 [Information] Starting Hangfire Server
2017-11-02 07:57:24.890 +00:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-02 07:57:24.890 +00:00 [Information] Using the following options for Hangfire Server:
2017-11-02 07:57:24.890 +00:00 [Information]     Worker count: 1
2017-11-02 07:57:24.890 +00:00 [Information]     Listening queues: 'default'
2017-11-02 07:57:24.890 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-02 07:57:24.890 +00:00 [Information]     Schedule polling interval: 00:00:15

**Comment by tidusjar** [comment]
If you search for `The Human Centipede (First Sequence)` what appears in the UI?

**Comment by ExeCuteUK** [comment]
The Human Centipede (First Sequence) (2009)

Release Date 26/04/2009 Not Requested

**Comment by ExeCuteUK** [comment]
![screen](https://user-images.githubusercontent.com/28557360/32315839-c1ca38d8-bfa5-11e7-8326-3963a75df71f.png)

**Comment by tidusjar** [comment]
Can you create a local admin for me and send me your `Ombi.db` file? also include the username and password you created tidusjar@gmail.com

**Comment by ExeCuteUK** [comment]
2x email sent

**Comment by ExeCuteUK** [comment]
Just as a note, I added my 4K Movie section which only has 35 movies, and they display as available in Ombi fine.

Could the problem be size related ? (1500+ entries in the main Movie library).

**Comment by tidusjar** [comment]
Please upgrade, you need to delete the ombi.db file though

**Comment by realswamo** [comment]
I appreciate your hard work in trying to resolve this problem. Unfortunately for me this problem still remains and I did a fresh install of Ombi.

![example](https://user-images.githubusercontent.com/33209961/32358213-7dae176c-c01a-11e7-89b5-e13c5d1cafe3.PNG)

**Comment by tidusjar** [comment]
Can you also create me a user and send me your dB?

**Comment by ExeCuteUK** [comment]
Removed old install and reinstalled with latest build. Scanned TV Show Library & Movie Library.

Movie library still fails, TV shows are fine.

![screen1](https://user-images.githubusercontent.com/28557360/32367504-36c7a9fc-c07a-11e7-8f97-8e58177e8642.png)

![screen2](https://user-images.githubusercontent.com/28557360/32367506-38459abe-c07a-11e7-9fe6-14df7bae3810.png)

![screen3](https://user-images.githubusercontent.com/28557360/32367508-39b9958a-c07a-11e7-9287-4c510bc7b9aa.png)

**Comment by realswamo** [comment]
E-mail sent.

**Comment by tidusjar** [comment]
Please let me know how you guys get on with the new build!

**Comment by realswamo** [comment]
Yup, issue is resolved. Thanks again!

**Comment by ExeCuteUK** [comment]
Issue resolved. Thanks for you efforts!

**Comment by MrTwIXx** [comment]
@tidusjar Hey , I have installed Ombi today and it always fails, when I want to cach my movies.
Can you help me please?

**Comment by Ing-Med** [comment]
Hi all,

i have the same problem. 
Logfile only says that it searches for episodes, but not movies. Plex settings are correct, folders are checked.

`info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server xxxxxxxxx
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV-gdrive = 2287
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2137
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1987
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1837
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1687
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1537
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1387
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1237
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1087
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 937
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 787
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 637
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 487
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 337
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 187
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 37
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      We have finished caching the episodes.
`
