### ISSUE TITLE
Placeholder title in popup, and clear already requested movie from deleted user?

### ISSUE THREAD

**Issue by joq3** [tidusjar/Ombi#1664]
#### Ombi build Version:

V 3.0.2268

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Two problems:
1. When adding a movie request, a yellow popup appears in the upper right corner, which says somethign like, Added {{movie title}}... problem is that it doesn't display the movies title, it displays the placeholder like this {{movie title}}.

2. I requested a movie on an account, then I deleted that account, and now the movie is not shown under request, but if I search for the movie, I cannot request it again, as the button is greyed out and it looks like it is already requested.
How do I clear this out, so that I can request it once again?

Thank you!

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
To fix 1. update.

I'll look into the 2nd.

**Comment by joq3** [comment]
@tidusjar Update? It says I am on the latest version when checking for update?

Yes please!

**Comment by tidusjar** [comment]
Really? That's strange since the latest version is 3.0.2293

**Comment by joq3** [comment]
Pressing Chek for update:
You are on the latest version!

I use Ombi in Docker if that matters!

**Comment by tidusjar** [comment]
Restart the docker container, that should update it

**Comment by joq3** [comment]
After activating automatic updates in Ombi?
Is it okey to always update via Ombi, or do I sometimes need to update the docker container itself?

Thank you!

**Comment by tidusjar** [comment]
Regarding docker, i'd disable the automatic updates and let the container handle it.

**Comment by joq3** [comment]
I tried updating it via Docker, and now I get 502 Bad gateway when I visit http://192.168.1.2:3579
This is how the Docker is configured:
https://imgur.com/a/qsL39

Why did this happen? It did work great before...

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/issues/1669
