### ISSUE TITLE
Movies dont show up as available 

### ISSUE THREAD

**Issue by filoor** [tidusjar/Ombi#1665]
#### Ombi build Version:

V 3.0.2297

#### Media Sever:

Emby

#### Media Server Version:

3.2.35.0

#### Operating System:

Win 10

A lot of movies that are on emby are snowing as requested and others are showing up as availabe 
see screenshot

it looks like only the last added movies are showing up as availabe

![image](https://user-images.githubusercontent.com/3647638/32339576-846c6ac6-bff8-11e7-96bd-e56869e4d06a.png)

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1663
