### ISSUE TITLE
Telegram notification "Not Found" and "Internal Server Error"

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1667]
#### Ombi build Version:

V 3.0.2297

#### Update Branch:

DotNetCore

#### Media Server:

Plex

#### Media Server Version:

Unnecessary.

#### Operating System:

Debian 8.9 with 4.9.0-0 kernel

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
From /logs/
2017-11-02 14:06:39.893 -07:00 [Error] StatusCode: InternalServerError, Reason: Internal Server Error
2017-11-02 14:16:12.865 -07:00 [Error] StatusCode: NotFound, Reason: Not Found

From systemd-journal
Nov 02 14:06:39 plexrequests Ombi[5912]: fail: Ombi.Api.Api[1000]
Nov 02 14:06:39 plexrequests Ombi[5912]: StatusCode: InternalServerError, Reason: Internal Server Error
Nov 02 14:22:34 plexrequests Ombi[9276]: fail: Ombi.Api.Api[1000]
Nov 02 14:22:34 plexrequests Ombi[9276]: StatusCode: NotFound, Reason: Not Found

```

#### Problem Description:

Telegram produces two different errors depending on the recipient (user or group)

#### Reproduction Steps:

upgraded today to 2297. Found telegram (yessss!)
Created a new bot and got the key. Put the key in.
First, tried to send notifications only to myself. Got the Internal Server Error.
Second, tried to send to a group. Got the "not found" message. 
These were all test attempts.  It never successfully sent a test message.

![image](https://user-images.githubusercontent.com/1329077/32351019-53c294aa-bfd9-11e7-9951-7dd5a7970c39.png)

**Comment by tidusjar** [comment]
Ah ok! I did state I didn't test it lol.

I'll get this fixed.

**Comment by didyouexpectthat** [comment]
No worries. I have been highly anticipating this feature for a long time. Glad to provide the testing :)

**Comment by tidusjar** [comment]
can you give it a go now?

**Comment by didyouexpectthat** [comment]
Upgraded to 2310.
![image](https://user-images.githubusercontent.com/1329077/32409212-cd3f3d88-c164-11e7-843d-cd00d5a4e4c9.png)
Looks like it is working now. I might file some enhancements requests later, like Telegram doesn't really use Subject. 
![image](https://user-images.githubusercontent.com/1329077/32409225-0395e2a6-c165-11e7-807b-24ad6f14e16e.png)
![image](https://user-images.githubusercontent.com/1329077/32409228-09f12822-c165-11e7-9c35-c1db8f255676.png)

**Comment by tidusjar** [comment]
Yeah it doesn't. I need to work on that slightly. But excellent!
