### ISSUE TITLE
Notification Settings - Expand Link Doesn't Close

### ISSUE THREAD

**Issue by kyse** [tidusjar/Ombi#1668]
#### Ombi build Version:

V 3.0.2297

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 17.10

#### Problem Description:

When clicking one of the links on the right side of one of the notification pages to expend a notification type to enable/disable, there is no collapse feature.  One can click on the link to expand again and another instance of the expanded settings for that notification type will expand.

#### Reproduction Steps:

Goto Settings -> Notifications -> Email -> Click on Issue link on the right twice.

**Comment by tidusjar** [comment]
I'm not seeing this behaviour. It's working as expected for me.

What browser?

**Comment by kyse** [comment]
Odd, I just did a refresh and the link is collapsing it now.  I should have checked console to see if angular crashed somewhere else.  I noticed notification popups when you click submit in other settings weren't disappearing either, so perhaps angular was broken at the time I was experiencing this issue when updating other settings.

Closing issue, apologies.
