### ISSUE TITLE
OMBI V3 API Addition

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#1672]
As discussed in Discord:

I would like to request an addition to the Ombi V3 API to include a new POST function for Requests  that will include the body of either tmdb id or tvbd id.  I would also include the username in body as well.

**Comment by tidusjar** [comment]
This is available for Movies, still need to work on TV, that's not going to be as simple

**Comment by tidusjar** [comment]
Tv shows are now done in latest release. Sorry it took so long
