### ISSUE TITLE
TV Show requests doubled

### ISSUE THREAD

**Issue by goofballtech** [tidusjar/Ombi#1678]
#### Ombi build Version:

3.0.2310

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

TV shows that have dates set for unaired episodes show a request button even if those episodes are set as monitored already in sonarr, pressing this button causes the show to attempt to redownload even episodes that are already available. 

Shows that have ended and are 100% or that are continuing but do not have dates set for the next season show an available icon as expected.

#### Reproduction Steps:

 I pressed this requests button on a show with 7 seasons and that is currently running weekly and Sonarr attempted to download all 7 seasons again.

**Comment by tidusjar** [comment]
Cannot reproduce this.

Can you provide more  detailed reproduction steps?

**Comment by goofballtech** [comment]
You have changed something since i posted this. Now when i press the request button on a show that is still airing weekly i get a popup that says "we already have this request" and it doesn't try to redownload it all. When i posted this there was no message and it would queue up the whole thing again.

Must have been something you fixed when working on other things. In any case it seems to be good to go now.
