### ISSUE TITLE
Where is the osx.zip file for mac?

### ISSUE THREAD

**Issue by orangemooncreative** [tidusjar/Ombi#1679]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

OSX Sierra

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Where is the osx.zip file described in the mac installation steps here: https://github.com/tidusjar/Ombi/wiki/Installation

I have looked in releases and do not see it there. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
pleas use the big blue download button on the frontpage..

**Comment by orangemooncreative** [comment]
I've done that and there is no OSX.zip file only OMBI.zip which does not contain an OSX.zip file.

**Comment by PotatoQuality** [comment]
version 2 is not supported anymore. pleas download the v3 version.

**Comment by PotatoQuality** [comment]
( you are following the v3 installation instructions and trying to download the version 2 )

**Comment by orangemooncreative** [comment]
Where is the version 3 releases? This is all I see https://github.com/tidusjar/Ombi/releases. Am I missing something?

**Comment by PotatoQuality** [comment]
so you didnt use the big blue download button. 

like i sad before :

pleas use the big blue download button on the frontpage..

**Comment by PotatoQuality** [comment]
dont say that you did does that instead of not using it.

**Comment by PotatoQuality** [comment]
![screenshot_20171104-155456](https://user-images.githubusercontent.com/2944704/32406571-45524ed0-c17b-11e7-9d5d-0973fa203add.png)

**Comment by orangemooncreative** [comment]
why are you being purposefully obtuse...you could have easily just been helpful and posted the link...i figured it out....no one is perfect. i did use the BIG BLUE BUTTON the first time but did not see there were two different version numbers. All this you are doing is uncalled for.

**Comment by PotatoQuality** [comment]
one is called  version 2 and one called version 3. not sure how we can it make more obvious for the end user.

**Comment by PotatoQuality** [comment]
not sure why it is a topic hoe of you are perfect or not. i didnt talk about that lol

**Comment by orangemooncreative** [comment]
literally what i am saying is when said i did click the button....all you had to say there are two buttons and you must of clicked v2. rather than saying....

so you didnt use the big blue download button.
like i sad before
pleas use the big blue download button on the frontpage..

but it's whatever now.

**Comment by PotatoQuality** [comment]
i did say that...

you are following the v3 installation instructions and trying to download the version 2
