### ISSUE TITLE
Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by stonehenge1861** [tidusjar/Ombi#1680]
#### Ombi build Version:

V 3.0.2310

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 14.04.5

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

I have no logs, cant get ombi to start.

```

#### Problem Description:

Trying to install Ombi following the instructions here, https://github.com/tidusjar/Ombi/wiki/Installation
when running ./Ombi i recieve the following error " ./Ombi: 1: ./Ombi: Syntax error: ")" unexpected"
not sure how to fix.

**Comment by Indebt1** [comment]
someone did poor programming and did't check their code before uploading.  Needs to be fixed and reuploaded.

**Comment by Indebt1** [comment]
There is a programming error in the update.  Will need to be fixed and re-uploaded.

**Comment by tidusjar** [comment]
You followed it exactly? What's in the /opt/Ombi folder?

**Comment by stonehenge1861** [comment]
There is quite a few thing so i will just paste the output.
``
appsettings.Development.json
appsettings.json
AutoMapper.Collection.dll
AutoMapper.dll
AutoMapper.Extensions.Microsoft.DependencyInjection.dll
BouncyCastle.Crypto.dll
CommandLine.dll
createdump
Dapper.dll
de
EasyCrypto.dll
Ensure.That.dll
es
fr
Hangfire.AspNetCore.dll
Hangfire.Console.dll
Hangfire.Core.dll
Hangfire.MemoryStorage.Core.dll
Hangfire.RecurringJobExtensions.dll
Hangfire.SQLite.dll
Hangfire.SqlServer.dll
hosting.json
it
ja
ko
libclrjit.so
libcoreclr.so
libcoreclrtraceptprovider.so
libdbgshim.so
libe_sqlite3.so
libhostfxr.so
libhostpolicy.so
libmscordaccore.so
libmscordbi.so
libsosplugin.so
libsos.so
libsqlite3.so
libuv.so
linux.tar.gz
MailKit.dll
Microsoft.AI.DependencyCollector.dll
Microsoft.ApplicationInsights.AspNetCore.dll
Microsoft.ApplicationInsights.dll
Microsoft.AspNetCore.Antiforgery.dll
Microsoft.AspNetCore.ApplicationInsights.HostingStartup.dll
Microsoft.AspNetCore.Authentication.Abstractions.dll
Microsoft.AspNetCore.Authentication.Cookies.dll
Microsoft.AspNetCore.Authentication.Core.dll
Microsoft.AspNetCore.Authentication.dll
Microsoft.AspNetCore.Authentication.Facebook.dll
Microsoft.AspNetCore.Authentication.Google.dll
Microsoft.AspNetCore.Authentication.JwtBearer.dll
Microsoft.AspNetCore.Authentication.MicrosoftAccount.dll
Microsoft.AspNetCore.Authentication.OAuth.dll
Microsoft.AspNetCore.Authentication.OpenIdConnect.dll
Microsoft.AspNetCore.Authentication.Twitter.dll
Microsoft.AspNetCore.Authorization.dll
Microsoft.AspNetCore.Authorization.Policy.dll
Microsoft.AspNetCore.AzureAppServices.HostingStartup.dll
Microsoft.AspNetCore.AzureAppServicesIntegration.dll
Microsoft.AspNetCore.CookiePolicy.dll
Microsoft.AspNetCore.Cors.dll
Microsoft.AspNetCore.Cryptography.Internal.dll
Microsoft.AspNetCore.Cryptography.KeyDerivation.dll
Microsoft.AspNetCore.DataProtection.Abstractions.dll
Microsoft.AspNetCore.DataProtection.AzureStorage.dll
Microsoft.AspNetCore.DataProtection.dll
Microsoft.AspNetCore.DataProtection.Extensions.dll
Microsoft.AspNetCore.Diagnostics.Abstractions.dll
Microsoft.AspNetCore.Diagnostics.dll
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.dll
Microsoft.AspNetCore.dll
Microsoft.AspNetCore.Hosting.Abstractions.dll
Microsoft.AspNetCore.Hosting.dll
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
Microsoft.AspNetCore.Html.Abstractions.dll
Microsoft.AspNetCore.Http.Abstractions.dll
Microsoft.AspNetCore.Http.dll
Microsoft.AspNetCore.Http.Extensions.dll
Microsoft.AspNetCore.Http.Features.dll
Microsoft.AspNetCore.HttpOverrides.dll
Microsoft.AspNetCore.Identity.dll
Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll
Microsoft.AspNetCore.JsonPatch.dll
Microsoft.AspNetCore.Localization.dll
Microsoft.AspNetCore.Localization.Routing.dll
Microsoft.AspNetCore.MiddlewareAnalysis.dll
Microsoft.AspNetCore.Mvc.Abstractions.dll
Microsoft.AspNetCore.Mvc.ApiExplorer.dll
Microsoft.AspNetCore.Mvc.Core.dll
Microsoft.AspNetCore.Mvc.Cors.dll
Microsoft.AspNetCore.Mvc.DataAnnotations.dll
Microsoft.AspNetCore.Mvc.dll
Microsoft.AspNetCore.Mvc.Formatters.Json.dll
Microsoft.AspNetCore.Mvc.Formatters.Xml.dll
Microsoft.AspNetCore.Mvc.Localization.dll
Microsoft.AspNetCore.Mvc.Razor.dll
Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
Microsoft.AspNetCore.Mvc.RazorPages.dll
Microsoft.AspNetCore.Mvc.TagHelpers.dll
Microsoft.AspNetCore.Mvc.ViewFeatures.dll
Microsoft.AspNetCore.NodeServices.dll
Microsoft.AspNetCore.Owin.dll
Microsoft.AspNetCore.Razor.dll
Microsoft.AspNetCore.Razor.Language.dll
Microsoft.AspNetCore.Razor.Runtime.dll
Microsoft.AspNetCore.ResponseCaching.Abstractions.dll
Microsoft.AspNetCore.ResponseCaching.dll
Microsoft.AspNetCore.ResponseCompression.dll
Microsoft.AspNetCore.Rewrite.dll
Microsoft.AspNetCore.Routing.Abstractions.dll
Microsoft.AspNetCore.Routing.dll
Microsoft.AspNetCore.Server.HttpSys.dll
Microsoft.AspNetCore.Server.IISIntegration.dll
Microsoft.AspNetCore.Server.Kestrel.Core.dll
Microsoft.AspNetCore.Server.Kestrel.dll
Microsoft.AspNetCore.Server.Kestrel.Https.dll
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
Microsoft.AspNetCore.Session.dll
Microsoft.AspNetCore.SpaServices.dll
Microsoft.AspNetCore.StaticFiles.dll
Microsoft.AspNetCore.WebSockets.dll
Microsoft.AspNetCore.WebUtilities.dll
Microsoft.Azure.KeyVault.dll
Microsoft.Azure.KeyVault.WebKey.dll
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.Razor.dll
Microsoft.CSharp.dll
Microsoft.Data.Edm.dll
Microsoft.Data.OData.dll
Microsoft.Data.Sqlite.dll
Microsoft.DotNet.PlatformAbstractions.dll
Microsoft.EntityFrameworkCore.Design.dll
Microsoft.EntityFrameworkCore.dll
Microsoft.EntityFrameworkCore.InMemory.dll
Microsoft.EntityFrameworkCore.Relational.Design.dll
Microsoft.EntityFrameworkCore.Relational.dll
Microsoft.EntityFrameworkCore.Sqlite.Design.dll
Microsoft.EntityFrameworkCore.Sqlite.dll
Microsoft.EntityFrameworkCore.SqlServer.dll
Microsoft.Extensions.Caching.Abstractions.dll
Microsoft.Extensions.Caching.Memory.dll
Microsoft.Extensions.Caching.Redis.dll
Microsoft.Extensions.Caching.SqlServer.dll
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.AzureKeyVault.dll
Microsoft.Extensions.Configuration.Binder.dll
Microsoft.Extensions.Configuration.CommandLine.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.dll
Microsoft.Extensions.Configuration.FileExtensions.dll
Microsoft.Extensions.Configuration.Ini.dll
Microsoft.Extensions.Configuration.Json.dll
Microsoft.Extensions.Configuration.UserSecrets.dll
Microsoft.Extensions.Configuration.Xml.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.DependencyInjection.dll
Microsoft.Extensions.DependencyModel.dll
Microsoft.Extensions.DiagnosticAdapter.dll
Microsoft.Extensions.FileProviders.Abstractions.dll
Microsoft.Extensions.FileProviders.Composite.dll
Microsoft.Extensions.FileProviders.Embedded.dll
Microsoft.Extensions.FileProviders.Physical.dll
Microsoft.Extensions.FileSystemGlobbing.dll
Microsoft.Extensions.Hosting.Abstractions.dll
Microsoft.Extensions.Identity.Core.dll
Microsoft.Extensions.Identity.Stores.dll
Microsoft.Extensions.Localization.Abstractions.dll
Microsoft.Extensions.Localization.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.AzureAppServices.dll
Microsoft.Extensions.Logging.Configuration.dll
Microsoft.Extensions.Logging.Console.dll
Microsoft.Extensions.Logging.Debug.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Logging.EventSource.dll
Microsoft.Extensions.Logging.TraceSource.dll
Microsoft.Extensions.ObjectPool.dll
Microsoft.Extensions.Options.ConfigurationExtensions.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.PlatformAbstractions.dll
Microsoft.Extensions.Primitives.dll
Microsoft.Extensions.WebEncoders.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll
Microsoft.IdentityModel.Logging.dll
Microsoft.IdentityModel.Protocols.dll
Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
Microsoft.IdentityModel.Tokens.dll
Microsoft.Net.Http.Headers.dll
Microsoft.Rest.ClientRuntime.Azure.dll
Microsoft.Rest.ClientRuntime.dll
Microsoft.VisualBasic.dll
Microsoft.VisualStudio.Web.BrowserLink.dll
Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry.dll
Microsoft.WindowsAzure.Storage.dll
MimeKit.dll
MiniProfiler.AspNetCore.dll
MiniProfiler.AspNetCore.Mvc.dll
MiniProfiler.Shared.dll
mscorlib.dll
netstandard.dll
Newtonsoft.Json.Bson.dll
Newtonsoft.Json.dll
nuget.config
Ombi
Ombi.Api.CouchPotato.dll
Ombi.Api.CouchPotato.pdb
Ombi.Api.Discord.dll
Ombi.Api.Discord.pdb
Ombi.Api.dll
Ombi.Api.DogNzb.dll
Ombi.Api.DogNzb.pdb
Ombi.Api.Emby.dll
Ombi.Api.Emby.pdb
Ombi.Api.FanartTv.dll
Ombi.Api.FanartTv.pdb
Ombi.Api.Mattermost.dll
Ombi.Api.Mattermost.pdb
Ombi.Api.pdb
Ombi.Api.Plex.dll
Ombi.Api.Plex.pdb
Ombi.Api.Pushbullet.dll
Ombi.Api.Pushbullet.pdb
Ombi.Api.Pushover.dll
Ombi.Api.Pushover.pdb
Ombi.Api.Radarr.dll
Ombi.Api.Radarr.pdb
Ombi.Api.Service.dll
Ombi.Api.Service.pdb
Ombi.Api.Slack.dll
Ombi.Api.Slack.pdb
Ombi.Api.Sonarr.dll
Ombi.Api.Sonarr.pdb
Ombi.Api.Telegram.dll
Ombi.Api.Telegram.pdb
Ombi.Api.TheMovieDb.dll
Ombi.Api.TheMovieDb.pdb
Ombi.Api.Trakt.dll
Ombi.Api.Trakt.pdb
Ombi.Api.TvMaze.dll
Ombi.Api.TvMaze.pdb
Ombi.Core.dll
Ombi.Core.pdb
Ombi.DependencyInjection.dll
Ombi.DependencyInjection.pdb
Ombi.deps.json
Ombi.dll
Ombi.Helpers.dll
Ombi.Helpers.pdb
Ombi.Mapping.dll
Ombi.Mapping.pdb
Ombi.Notifications.dll
Ombi.Notifications.pdb
Ombi.Notifications.Templates.dll
Ombi.Notifications.Templates.pdb
Ombi.pdb
Ombi.runtimeconfig.json
Ombi.Schedule.dll
Ombi.Schedule.pdb
Ombi.Settings.dll
Ombi.Settings.pdb
Ombi.Store.dll
Ombi.Store.pdb
Ombi.Updater
Ombi.Updater.deps.json
Ombi.Updater.dll
Ombi.Updater.pdb
Ombi.Updater.runtimeconfig.json
package.json
package-lock.json
refs
Remotion.Linq.dll
ru
Serilog.dll
Serilog.Extensions.Logging.dll
Serilog.Sinks.File.dll
Serilog.Sinks.RollingFile.dll
Serilog.Sinks.SQLite.dll
SharpCompress.dll
sosdocsunix.txt
SOS.NETCore.dll
SQLitePCLRaw.batteries_green.dll
SQLitePCLRaw.batteries_v2.dll
SQLitePCLRaw.core.dll
SQLitePCLRaw.provider.e_sqlite3.dll
StackExchange.Redis.StrongName.dll
Swagger.xml
Swashbuckle.AspNetCore.dll
Swashbuckle.AspNetCore.Swagger.dll
Swashbuckle.AspNetCore.SwaggerGen.dll
Swashbuckle.AspNetCore.SwaggerUI.dll
System.AppContext.dll
System.Buffers.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.Composition.dll
System.ComponentModel.DataAnnotations.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Configuration.ConfigurationManager.dll
System.Configuration.dll
System.Console.dll
System.Core.dll
System.Data.Common.dll
System.Data.dll
System.Data.SqlClient.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.dll
System.Drawing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.Globalization.Native.so
System.IdentityModel.Tokens.Jwt.dll
System.Interactive.Async.dll
System.IO.Compression.dll
System.IO.Compression.FileSystem.dll
System.IO.Compression.Native.so
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.AccessControl.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Native.a
System.Native.so
System.Net.dll
System.Net.Http.dll
System.Net.HttpListener.dll
System.Net.Http.Native.so
System.Net.Mail.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Security.Native.so
System.Net.ServicePoint.dll
System.Net.Sockets.dll
System.Net.WebClient.dll
System.Net.WebHeaderCollection.dll
System.Net.WebProxy.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.Numerics.dll
System.Numerics.Vectors.dll
System.ObjectModel.dll
System.Private.CoreLib.dll
System.Private.DataContractSerialization.dll
System.Private.Uri.dll
System.Private.Xml.dll
System.Private.Xml.Linq.dll
System.Reflection.DispatchProxy.dll
System.Reflection.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Reflection.TypeExtensions.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.WindowsRuntime.dll
System.Runtime.Loader.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Security.AccessControl.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Cng.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Native.OpenSsl.so
System.Security.Cryptography.OpenSsl.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.ProtectedData.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Cryptography.Xml.dll
System.Security.dll
System.Security.Principal.dll
System.Security.Principal.Windows.dll
System.Security.SecureString.dll
System.ServiceModel.dll
System.ServiceModel.Web.dll
System.ServiceProcess.dll
System.Spatial.dll
System.Text.Encoding.CodePages.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.Encodings.Web.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Transactions.dll
System.Transactions.Local.dll
System.ValueTuple.dll
System.Web.dll
System.Web.HttpUtility.dll
System.Windows.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.ReaderWriter.dll
System.Xml.Serialization.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
Templates
TraktApiSharp.dll
tsconfig.json
tslint.json
Views
web.config
WindowsBase.dll
wwwroot
zh
zh-Hans
zh-Hant
``

**Comment by tidusjar** [comment]
You made the ombi file an executable right?

**Comment by stonehenge1861** [comment]
Yes I did, I just made sure I did, the file and not the folder, I did do that once .

**Comment by TheRealDirtyMike** [comment]
I am having the same issue with my installation. Previously moved from an Ubuntu build to a Raspbian Jessie build on a pi. Moved to Ombi V3 as well. Followed the instructions to a tee. Tar file extracted with EVERYTHING set as executable already... ?? not sure why.... Seemed odd to me. But other than that I am seeing the same syntax error previously stated. 

Ombi build Version:

V 3.0.2381

**Update Branch:**

Open Beta

**Media Sever:**

Plex

**Operating System:**

Raspbian 9


ERROR: 
dirtymike@raspberrypi:/opt/Ombi $ ls -la | grep Ombi
-rwx------  1 root root    97408 Nov 23  2017 Ombi

dirtymike@raspberrypi:/opt/Ombi $ sudo ./Ombi
./Ombi: 1: ./Ombi: Syntax error: ")" unexpected

**Comment by tidusjar** [comment]
It is not supported on the raspberry pi yet.

**Comment by landopando** [comment]
I have the same issue on Ubuntu 16.04.3.

Following instructions, check permissions. All looks good to execute. Get error.

./Ombi
./Ombi: 1: ./Ombi: Syntax error: ")" unexpected

**Comment by tidusjar** [comment]
This is now supported for armv7 devices.

32bit is not supported YET. It will be coming.
