### ISSUE TITLE
issue launching Ombi V3 in linux/error: libunwind.so.8

### ISSUE THREAD

**Issue by xceed** [tidusjar/Ombi#1682]
#### Ombi build Version:
V3
latest version from https://ci.appveyor.com/api/buildjobs/bvelxt62id3u208i/artifacts/linux.tar.gz

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

when launching ombi from fresh debain install getting error: 
Failed to load ▒2▒, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/opt/Ombi/libcoreclr.so'

#### Reproduction Steps:

i also tried using fresh install of ubuntu 16.0.4 same error

**Comment by Codehhh** [comment]
```
libunwind8 error

libunwind.so.8: cannot open shared object file You may need to install libwind8.
Run apt install libunwind8
```

Taken from [here.](https://github.com/tidusjar/Ombi/wiki/Common-Errors#libunwind8-error)

**Comment by PotatoQuality** [comment]
see wiki....
