### ISSUE TITLE
css ID's for layer#Cake

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1687]
As per our conversation, i need a few id's, but i think i can do everything i need with just user-role ID's. So as long as i can drop #user #power-user or #admin (thats all of them right?) at the beginning of any selector, i should be able to drill down to everything i need.

**Comment by tidusjar** [comment]
Where are the specific areas that you need the ids?

**Comment by leram84** [comment]
hmmm... im really not sure. I was hoping you would know lol. I obviously don't have any experience w angular. I'm not even sure how to pull up the html in dev tools. Viewing page source doesn't show anything useful so i dont even really know how the page resolves per user type. In org, cause was able to add a class to the body depending on what user level was logged in. If admin is logged in, `.user-admin` class would be in the body, so if i put that class at the beginning of any selector, the css would only apply to admin, and so on.

It wasn't so much of a big deal in org though, because almost every element had unique classes. Ombi, however, mostly uses the same class for every 1st child of a div, so i have to use nth-child a lot. when u switch from admin to user, for example, this breaks everything since all those nth-child values change. If there is a way to get an id/class on the user level, it will save me from needing a bunch of unique classes
