### ISSUE TITLE
user cannot login

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#1688]
#### Ombi build Version:

V 3.0.2326

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.0-693.2.2.el7.x86_64 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized

```

#### Problem Description:

I have one user who cannot log in. I know the above error is not much to go on... is there any other way to debug this issue? Should there be logs on the plex side during login?

User was imported from plex.

The user has a "!" in their password. I used the same charter with a test account and it worked just fine. 

They are sure they are typing the correct password and the user has the same roles as other users that can successfully log in.

#### Reproduction Steps:
Unknown since I am unable to reproduce.

**Comment by samwiseg00** [comment]
One thing that is different with this user is that they have a camelcase username 

ie. "Jbob"

**Comment by tidusjar** [comment]
All I can say is that their username or password is wrong!

Not sure how much more I can help.

We do have an Audit table that does audit some things but not all. You could take a look at that table? It's in the `Ombi.db` you can view it using something like SQLiteBrowser for example.

**Comment by samwiseg00** [comment]
I have not had time to debug... I will comment back when i have something more concrete.. Thanks!
