### ISSUE TITLE
Request: Enable other Swagger API key methods for v3

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#1689]
https://swagger.io/docs/specification/authentication/api-keys/

It appears that it would be fairly trivial to enable various api key methods in Swagger. As far as I can tell only the header method is currently available.

Would it be possible to enable the query string  and or cookie methods as well? In some cases it might make integration with existing tools easier.

**Comment by tidusjar** [comment]
Swagger is just the documentation tool, I implementation the way the API key is parsed

**Comment by bagobones** [comment]
Ok I thought it was a complete framework not just for documenting APIs.

Regardless query string is important if you wanted to try to integrate something with the IFTTT Maker Channel since as fars as I know you can't use headers (maybe add movies with specific review scores). Among some other tools out like Tasker (get notified when someone requests something etc) on Android that can retrieve and parse but may not offer other authentication options.

http://www.makeuseof.com/tag/ifttt-connect-anything-maker-channel/

**Comment by tidusjar** [comment]
It's just for documenting! We use the WebApi framework for APIs. But yes I'll add the ability to read the API key from the query string.
