### ISSUE TITLE
Add the ability to request an artist. (Headphones)

### ISSUE THREAD

**Issue by HamilcarH** [tidusjar/Ombi#169]
Instead of just an album.

Thanks !

**Comment by DreamStatic** [comment]
Additionally, add the ability to request even if not found. As a lot of times it is for a brand new artist.

**Comment by smcpeck** [comment]
Similar to my recent "Search Movies by Actor" functionality in the `dev` branch, I will tackle this soon for "Search Albums by Artist."
🍻

**Comment by HamilcarH** [comment]
great :)

**Comment by bfir3** [comment]
Awesome to hear!

**Comment by HamilcarH** [comment]
Is this still happening ? I must be the only one that still wants to download his music :)
