### ISSUE TITLE
Email templates set in settings should be applied immediately

### ISSUE THREAD

**Issue by pironic** [tidusjar/Ombi#1690]
#### Ombi build Version:

V 3.0.2328

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

plex-pass

#### Operating System:

docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

irrelevant.

```

#### Problem Description:

When changing the smtp email templates and clicking save, the code will continue to use a cached version until restarted or an indeterminate amount of time passes. Ideally there should be a loadFromSettings function called when saving the email templates. As it stands, an admin must restart the app in order to apply the email template changes.

#### Reproduction Steps:

Change the welcome email template in /Settings/Email and click Submit. Then go to /usermanagement and click Send Welcome Email. The email received is not aligned with the recently edited template.

**Comment by SoulInfernoDE** [comment]
I can confirm this. Came here to search if this was opened already. In older version i think it checked 'saved successfully' on the top right. Doesn't now.

**Comment by tidusjar** [comment]
This should be resolved now.
