### ISSUE TITLE
Emby Movies and TV show as processing when should be available

### ISSUE THREAD

**Issue by alz41** [tidusjar/Ombi#1692]
#### Ombi build Version:

V 3.0.2330

#### Update Branch:

Open Beta

#### Media Sever:

Emby
V3.2.36.4

#### Operating System:

Windows10 64bit

#### Problem Description:

Emby Movies and TV show as Processing

#### Reproduction Steps:

Search for movie IT in Ombi and it shows as processing even though its in Emby DB

**Comment by PotatoQuality** [comment]
logs?

**Comment by alz41** [comment]
Console Window -

Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2331-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on
C:\Users\allen\Desktop\ombi-v3
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Ombi.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: C:\Users\allen\Desktop\ombi-v3
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.


*.log file -
2017-11-07 23:09:25.875 +00:00 [Information] Start installing Hangfire SQL objects...
2017-11-07 23:09:25.909 +00:00 [Information] Hangfire SQL objects installed.
2017-11-07 23:09:25.926 +00:00 [Information] Starting Hangfire Server
2017-11-07 23:09:25.929 +00:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-11-07 23:09:25.929 +00:00 [Information] Using the following options for Hangfire Server:
2017-11-07 23:09:25.929 +00:00 [Information]     Worker count: 1
2017-11-07 23:09:25.929 +00:00 [Information]     Listening queues: 'default'
2017-11-07 23:09:25.929 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2017-11-07 23:09:25.929 +00:00 [Information]     Schedule polling interval: 00:00:15
2017-11-08 22:22:36.195 +00:00 [Information] Hangfire Server stopped.

**Comment by alz41** [comment]
Ombi Version 3.0.2331 looks to of solved the issue, at least partially as some files showing as available

**Comment by alz41** [comment]
After digging into my situation, for some reason Emby has TMDB ID in the IMDB location for some of my files.

**Comment by tidusjar** [comment]
Oh god. How did that happen.

**Comment by alz41** [comment]
No idea tidusjar, but sorted after a metadata refresh ;)
