### ISSUE TITLE
Allow import of Plex primary user at admin discretion

### ISSUE THREAD

**Issue by Unimatrix0** [tidusjar/Ombi#1695]
#### Ombi build Version:

V 3.0.2330

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

N/A

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Ombi does not import primary Plex user account.

#### Feature Request:

Ombi should give the option to import the primary Plex user account. If the Plex primary user account has the same name as the Ombi admin account created during setup, the admin should have the option to overwrite the Ombi account, rename the Ombi account, or cancel the import.

**Comment by PotatoQuality** [comment]
Its by design that we don't do that in V3. Not sure if Jamie is going to make that.

**Comment by tidusjar** [comment]
Yes it on the project tab. It's to help with Org sso.

**Comment by goldenpipes** [comment]
Nice
