### ISSUE TITLE
layer#Cake

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1698]
This is gonna be an on going wish list. Feel free to add or ignore anything i write here :)

1)  Inside `<div _ngcontent-c0="" class="container top-spacing">` you have  the wrapper `<ng-component>` and the contents of that change depending on what tab you are in (search, requests, etc). is it possible to add a class or id to `<ng-component>` depending on which tab ur in? This would give me a lot more control of the different pages, but for right now, it would also be the easiest way to separate the css for the settings page from everything else, and i want to do some major rearranging of the settings layout

**Comment by tidusjar** [comment]
I have added it as an Id to `<div _ngcontent-c0="" class="container top-spacing">` div, since everything inside there is dynamic

**Comment by leram84** [comment]
ill check that out as soon as i figure out how to update lol... but in the meantime, i got another issue. This ones important. Can you set the custom css as the top of the cascade? I need my stuff to override the base without using `!important` since i will need to reserve that for addons.

**Comment by leram84** [comment]
![screenshot 2017-11-10 at 11 40 23 pm](https://user-images.githubusercontent.com/21117493/32694020-d6937954-c703-11e7-97cb-5ae73a0ab857.png)

so i can't really do any more until these issues are resolved, but i was looking through the new build and i saw you added the user role classes (thanks!) but there is a problem... it won't actually do anything for me when its buried in a div like that. The class needs to be attached to the parent of whatever im going to be changing, so i really need it attached to the body, or i might be able to make due w adding it to `<ombi _nghost-c0 ng-version="5.0.1">`, but anywhere else and i can't use it.

**Comment by tidusjar** [comment]
What about if there was a div that contained it inside the `<ombi>` tag?

e.g.

```
<ombi>
<div class="adminUser">
 Everything else
</div>
</ombi>

```

**Comment by tidusjar** [comment]
Also regarding your issue about 'the CSS being at the top of the cascade', it does not really work like that as the browser never sees CSS in terms of individual style sheets. When there are multiple style sheets, they are all treated as if they were one style sheet, and  cascading rules are evaluated accordingly.

**Comment by leram84** [comment]
> What about if there was a div that contained it inside the <ombi> tag?

Thats should work! It looks like the only thing outside that would be the loading images (right?) which i dont need to differentiate by user.

> When there are multiple style sheets, they are all treated as if they were one style sheet

... i thought each style sheet overrides the previous, so positioning MY css after the others would give it priority. Thats how it works in org.... cause just placed the custom css after his own, and it gets priority... could you maybe just try changing the order and see if it works? I've been going through it all weekend, and im pretty certain at this point that this wont work at all without that priority... too many changes

**Comment by tidusjar** [comment]
Your stylesheet if enabled are first in the list, you can see this by viewing the source when the website loads...

The thing that makes it take priority is the actual selector that you use e.g. the id selector will take priority over an xpath selector.

**Comment by tidusjar** [comment]
Doing some research it looks like I'm wrong! Ok i need to load it last and not first!
