### ISSUE TITLE
Specify a Sonarr file path on approval

### ISSUE THREAD

**Issue by R-Jimenez** [tidusjar/Ombi#170]
Obligatory 'Holy crap this makes everything much easier thanks a ton for working on this project xoxoxo'

Ehem. Anyways, as the title might suggest, I would love it if the Sonarr integration would allow me to specify the file path on a per-series basis. So that when I click approve on the requests panel, instead of using the default path found in the settings, I could instead use a certain path for certain shows, as needed.

**Comment by tidusjar** [comment]
Just trying to think how this would fit into the UI and flow, so maybe another dropdown option on the Approval button? What do you think?

**Comment by evilspectre** [comment]
Not OP, but was coming here to request same thing, another drop down would work, you could also put that info into approved/available/requested by list like https://i.imgur.com/81MQkWq.png

Also, I was going to make a similar request for Movies/CouchPotato and adding another drop down for Categories, do you want that a separate issue?

**Comment by tidusjar** [comment]
@evilspectre Yeah if we added another dropdown we would make sure we display it on the requests page.

Regarding the categories yes can you please raise that separately  :)

**Comment by R-Jimenez** [comment]
Either solution would be great! Having it tied to the request like @evilspectre suggested may be my preferred method (similar to Sonarr's object design), but something like Approve ([category name]) would work just fine, and users can just set up file categories in their config like everything else.

**Comment by tidusjar** [comment]
Well I was thinking, for TV under the approve dropdown there would be a new option `Approve with path` or something like that. That will then give you some sort of text box to specify a file path for that single approval ? Opinions?

**Comment by R-Jimenez** [comment]
Fine by me. Simply having the capability is more than enough for my needs.

**Comment by tidusjar** [comment]
I'm just wondering on the most user friendly way to do things (I don't have a need for this functionality).

What's the usual usecase? You would have series 1 = C:\Series\Series 1 and series 2 = D:\Series\Series 2?

**Comment by R-Jimenez** [comment]
I have three distributed media folders across three drives, but yeah, you've got the gist of the usecase. Live-action dramas go on one drive, anime on another, etc.

**Comment by evilspectre** [comment]
Same, have a /Media/TV /Media/Cartoons and a /Media/Anime folders

**Comment by onedr0p** [comment]
The best way to implement this IMO would be to expand on the dropdown under the approve button.

First separate the out the headers (Quality Profile, Path & others if we can add later) and then add a botton 'Done' to the dropdown that will submit those settings to the Sonarr API

```
Button: [+ Approve]
  Label: Quality Profile
    Radio button: [ ✓ ] Any
    Radio button: [     ] SD
    Radio button: [     ] HD
  Label: Path
    Radio button: [ ✓ ] /path/to/Airing TV Shows
    Radio button: [     ] /path/to/Archived TV Shows
  Button: [Done]
```

For the Path, we would need to send a request to Sonarrs API to gather all existing paths which shouldn't be hard.

If that all makes sense we could use the framework for the UI to implement specifing the Categories in CP too. Overall this shouldn't take much time to implement, if there is a frontend plugin for jQuery that would help. I would take a stab at this if I had more time.

Let me know your thoughts.

**Comment by tidusjar** [comment]
@onedr0p I like it!

But I think we should keep the default in the settings, saves having to select the same options every time.

**Comment by onedr0p** [comment]
@tidusjar I took sometime over the weekend and started implementing this. But, my lack of knowledge in c# is proving it to be harder than I thought. I come from a python/php background. Could I push a new branch and see if you can help out with it?

What is implemented:
* Grabbing the root folders via sonarr api
* In sonarr admin settings a button to refresh root folders and they show in the dropdown (like quality profiles)
* The selectbox gets populated with the root folders, but doesn't save in cache when you click save for some reason?? (it's not populated on page refesh)

**Comment by tidusjar** [comment]
Sure, just link me and i'll assist!

**Comment by onedr0p** [comment]
Awesome! I am at work now, but when I'm out ~8 hours I'll push over a new branch so you can take a look.

**Comment by tidusjar** [comment]
You could just fork the code and just commit it to the dev branch, easier to merge then.

**Comment by onedr0p** [comment]
Ok, I'll do that. I just didn't know if you wanted it on the Dev branch because it is incomplete.

**Comment by whitecollar17** [comment]
Case in progress in a pull request https://github.com/tidusjar/PlexRequests.Net/pull/535

**Comment by onedr0p** [comment]
Fuck yes, thanks dude!
