### ISSUE TITLE
Ombi adds new TV Shows to wrong root folder in Sonaar

### ISSUE THREAD

**Issue by pocketgeek** [tidusjar/Ombi#1701]
#### Ombi build Version:

V 3.0.2336

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.9.6.4401

Sonaar 2.0.0.5054
Mono Version 5.4.0.201

#### Operating System:

Centos 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Ombi doesn't log any errors

Sonaar logs the following:
17-11-9 22:30:10.4|Info|AddSeriesService|Adding Series [78949][Thomas The Tank Engine & Friends] Path: [/goodies/complete/Thomas The Tank Engine & Friends]
17-11-9 22:30:10.4|Info|RefreshSeriesService|Updating Info for Thomas The Tank Engine & Friends
17-11-9 22:30:11.9|Info|RefreshEpisodeService|Starting episode info refresh for: [78949][Thomas The Tank Engine & Friends]
17-11-9 22:30:12.1|Info|RefreshEpisodeService|Finished episode refresh for series: [78949][Thomas The Tank Engine & Friends].
17-11-9 22:30:12.1|Info|DiskScanService|Scanning disk for Thomas The Tank Engine & Friends
17-11-9 22:30:12.1|Info|DiskScanService|Completed scanning disk for Thomas The Tank Engine & Friends

Sonaar Debug:
17-11-9 22:30:10.4|Info|AddSeriesService|Adding Series [78949][Thomas The Tank Engine & Friends] Path: [/goodies/complete/Thomas The Tank Engine & Friends]
17-11-9 22:30:10.4|Info|RefreshSeriesService|Updating Info for Thomas The Tank Engine & Friends
17-11-9 22:30:10.5|Debug|Api|[POST] /api/series/: 201.Created (1607 ms)
17-11-9 22:30:10.8|Debug|Api|[GET] /api/series/433: 200.OK (235 ms)
17-11-9 22:30:10.8|Debug|Api|[GET] /api/Episode?seriesId=433: 200.OK (2 ms)
17-11-9 22:30:10.8|Debug|Api|[GET] /api/Episode?seriesId=433: 200.OK (1 ms)
17-11-9 22:30:11.3|Debug|Api|[GET] /api/Episode?seriesId=433: 200.OK (2 ms)
17-11-9 22:30:11.8|Debug|Api|[GET] /api/Episode?seriesId=433: 200.OK (2 ms)

This implies the destination folder "/goodies/complete/Thomas The Tank Engine & Friends" was sent to it by Ombi.  

#### Problem Description:

When queried by Ombi, Sonaar sends a list of 5 possible default folders.  Regardless of the folder I have selected and saved (by clicking the submit button) it always adds new TV Shows to the first folder in this list.  In my case "/goodies/complete"

#### Reproduction Steps:

This can be reproduced by adding any TV Show.

I've added some screenshots to help illustrate this bug:
![ombi bug 2](https://user-images.githubusercontent.com/10180058/32644728-b6006a62-c5a0-11e7-977e-06c727852d69.png)
![ombi bug 3](https://user-images.githubusercontent.com/10180058/32644729-b6152128-c5a0-11e7-8cce-776e5454ca55.png)
![ombi bug 1](https://user-images.githubusercontent.com/10180058/32644730-b6296cfa-c5a0-11e7-93c6-474a9f529d9d.png)

**Comment by PotatoQuality** [comment]
see last version
