### ISSUE TITLE
Changing base path with reverse proxy fails with token error

### ISSUE THREAD

**Issue by riemers** [tidusjar/Ombi#1706]
#### Ombi build Version:

3.0.2349-PR

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Latest

#### Operating System:

Ubuntu (using a docker container, but that shouldn't pose an issue)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Could not see any errors in logs.

#### Problem Description:

I am using a a custom base path, if you change it when you login you will get 500 errors, but that can be fixed by restarting ombi again. Once you restart it after you changed base path and try to login i get a token error. I am using a reverse proxy to make fancydomain.com/request/

POST https://fancydomain.com/request/api/v1/token/ 400 ()
![image](https://user-images.githubusercontent.com/682041/32693350-dcafc024-c729-11e7-9f6f-83f13e94e5b7.png)

#### Reproduction Steps:

Install a fresh one, then change base path to say /request , restart ombi and then try to login with a virtual host that has /request to it. I also changed the custom url but that didn't help either. My setup i am using did work with the old 2.x version without a hickup so i don't think it would be a problem there.

p.s. if you login to ombi as admin, nuke the .db and restart ombi and go back to it, you are still logged in? Seems like a strange situation ;) pressing logout brings you to the wizard then.

**Comment by jaycedk** [comment]
After reinstalling / deleting things server side, you should always hard refresh you browser.
things gets cached in you browser :D

**Comment by tidusjar** [comment]
This sounds like an issue either in your RP block or your browser.

The reason you are still logged in after deleting the db is because your JWT authentication token is still in your browser, but you cannot do anything since we still check server side.

**Comment by riemers** [comment]
I do know things get cached , but just mentioning it as feedback.

Regarding the reverse proxy setup, like i said, it did work with the old version. I also checked if it works directly on ip level with port, and then the /request does work. Perhaps it doesn't understand since its coming from another virtualhost/location whatever. Don't know if other people have tried a RP and have it working?

**Comment by tidusjar** [comment]
Yes there are many users running it via RP and working correctly. Can I suggest you jump onto the discord channel and ask on there? Since they will be able to help you more with your RP config.

**Comment by riemers** [comment]
On discord, asking now.. :)

**Comment by riemers** [comment]
```
        location /request {
            auth_request /auth/;
            proxy_pass http://ombi_backend/request;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            client_max_body_size 0;
            proxy_read_timeout 36000s;
            proxy_redirect off;
        }
```
Sample config, that does work. In case anybody bumps into this one.
