### ISSUE TITLE
Automatic Update In Windows 7 Causes Crash Upon Restart, Need to Start Manually

### ISSUE THREAD

**Issue by dshokouhi** [tidusjar/Ombi#1708]
#### Ombi build Version:

V 3.0.2351

#### Update Branch:

DotNetCOre

#### Media Sever:

Plex

#### Media Server Version:

 1.9.7.4441

#### Operating System:

Windows 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
The logs do not reflect the error in the below screenshot, if needed I can supply the install logs but they do not capture this particular error
```
![ombi](https://user-images.githubusercontent.com/1634145/32740675-7b91f64c-c858-11e7-8495-8d441fdde9a3.PNG)

#### Problem Description:

After running the automatic updater Ombi does not start on its own and requires a manual restart

#### Reproduction Steps:

1. Install Ombi V3
2. Setup automatic updater
3. Supply process name and account login information
4. Check for updates
5. Updates
6. Check the machine as the update runs
7. As soon as the program downloads, extracts and replaces necessary files the command window is closed and a new one is opened.  The new window crashes after the error in the screenshot

**Comment by PotatoQuality** [comment]
I have the same problem. But i was unable to get a error on my screen

**Comment by justinglock40** [comment]
Is there a way to provide more details for Auto update on Windows. I don't quite understand what to do ?
