### ISSUE TITLE
Admin/AutoApprovers does not need Approved! Pushbullet notification

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#1712]
#### Ombi build Version:

V 3.0.2354

#### Update Branch:

v3Issues

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Windows 10 64bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

After approving a user's request, a Pushbullet notification is sent. I would think no admins should get any Approved! notifications, and maybe not Auto Approve roles either as both groups would know the request is approved.

#### Reproduction Steps:

Admin approves a request, check Pushbullet.

**Comment by Unimatrix0** [comment]
Autoapproved requests should generate a single notification to admins (Request autoapproved: blah blah) as opposed to 2 notifications (Request: blah blah, Request approved: blah blah).

Requestors shouldn't get any notifications upon request or autoapproval.

**Comment by Auwen** [comment]
It also appears that the Admin is getting the "This is now available!" notifications through Pushbullet on items that the Admin didn't request. Admin doesn't need this notification.

Looks like all notifications are sent to the Admin's Pushbullet.
