### ISSUE TITLE
Couchpotato connection issue after reinstalling couch

### ISSUE THREAD

**Issue by trippinshrumes** [tidusjar/Ombi#1713]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

ubuntu 16.10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I had the request channel fully working, I ended up having a glitch with couchpotato not downloading properly and reinstalled to resolve the issue. Afterwards I have been unable to connect plex request channel to Couchpotato, although it works with everything else. I've reinstalled couchpotato as well as request channel. I'm not sure what my next steps for troubleshooting this would be.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
This is not the Plex request channel.
