### ISSUE TITLE
Raspbian Support?

### ISSUE THREAD

**Issue by weirdcrap** [tidusjar/Ombi#1716]
Not a bug, more of a check to see if this is going to be supported. 

I tried to research the state of .Net Core 2.0 on Raspbian and it sounds like it is mostly just for development?

Will it be possible to run Ombi v3 natively on the Raspberry Pi without a ton of extra work from the development team?

Without the need for Mono I imagine performance on the Pi will be much better if it is indeed supported.

**Comment by tidusjar** [comment]
Its something I would like to add going forward, but it does require some changes from my end. I'll keep this open, but it's not going to get done in the next few days.

**Comment by weirdcrap** [comment]
No rush at all, just glad to hear it is planned! You are doing great work and we all appreciate it.

**Comment by dayyan** [comment]
Try https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/

**Comment by FeatherKing** [comment]
FYI, .net core 2.0 requires armv7, so that will rule out the original raspberry pi

**Comment by weirdcrap** [comment]
Yeah When I said Raspberry Pi I was using it as a generic term for the Pi in general. I have Pi2s and Pi3s so doesn't matter to me as long as it is supported (which looks like we are very close to having).

**Comment by tidusjar** [comment]
This is now supported for armv7 devices
