### ISSUE TITLE
Upstart Script for Ombi V3 for Ubuntu before 15.04

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#1717]
I have been looking around but have only been able to find a systemd service file for starting Ombi on system startup. Has anyone created a startup script for Ombi V3 for versions of ubuntu that do not support systemd init? Or have I just missed it and it is specified somewhere here on github?

**Comment by tidusjar** [comment]
Not as far as I am aware. Ask on discord. That would be your best bet

**Comment by jasonlyle88** [comment]
@tidusjar I've never used discord before. Is there an Ombi discord server there? If so, what is the invite link? If not... where were you suggesting I ask this?

**Comment by Unimatrix0** [comment]
On the front page of this repo…

**Comment by jasonlyle88** [comment]
@Unimatrix0 Maybe I'm blind... but when I do a search for "discord" on the [front page of this repo](https://github.com/tidusjar/Ombi/), the only instance of the word "discord" that comes up is the bullet point of supported notifications. Can you please just tell me what it is?

**Comment by Unimatrix0** [comment]
Click the button that says “chat”

**Comment by jasonlyle88** [comment]
@Unimatrix0 Thanks, didn't realize that was a button as it looks like it is a badge.
