### ISSUE TITLE
Emby Connect user credentials not importing into Ombi

### ISSUE THREAD

**Issue by Magic815** [tidusjar/Ombi#1721]
#### Ombi build Version:

V 3.0.2363

#### Update Branch:

Open Beta

#### Media Sever:

Emby v3.2.36

#### Operating System:

Windows 8.1

#### Some Background Info:

So I have Emby set up where I create User accounts for my users, but then link in the Emby Connect account that they created on their own. For example, I might have a user who created an Emby Connect account with the following credentials:

> JonSmith1
> ECpassword

So I would then create a new user in my Emby server settings with the following credentials:

> Jon
> temppassword

And then I would link JonSmith1 to the user 'Jon' in my Emby settings. (In the user settings, 'Jon' is next to the 'Name' field. And 'JonSmith1' is next to the 'Emby Username' field.)

What this allows to happen is Jon can now go to my Emby login page, and see a profile picture with the name 'Jon' under it (instead of his JonSmith1 username). But then he uses JonSmith1 and ECpassword as his login credentials. (He could also use temppassword to login in too, but I never give him that password, so he doesn't know about it. And it gives me a backdoor way to get into his Emby account if any issues arise).

While I realize this is an odd way to do it, it's my way of dealing with Emby to get the login page how I wanted it to look (not displaying the full Emby Connect user names).

#### Problem Description:

Upon installing Ombi, I ran the 'Import Emby Users' function. It created user accounts off of all my Emby users, however, it looks like it pulled in the user account details:

> Jon, temppassword

And not the Emby Connect account details:

> JonSmith1, ECpassword

Would there be any way to get the Emby Connect credentials pulled instead? Or in addition?

Organizr has found a way to handle this by providing database and backend choices. In my case, I have these set in Organizr: https://i.imgur.com/SkvEiRt.png

'Emby_All' means it can pull in both Local Emby Users and Emby Connect users.

By having my Org settings like in that screenshot, my user Jon is able to sign into Organizr with the following:

> JonSmith1
> ECpassword

Any chance Ombi could be modified to allow the same? Right now, Jon would need to sign in with:

> Jon
> temppassword

But I'm trying to get it so users use their Emby Connect login info for everything. Org, Emby, and Ombi.

Thanks!

**Comment by causefx** [comment]
For local we use: `/Users/AuthenticateByName`

For Emby Connect we use: `/Users?api_key=`

**Comment by Magic815** [comment]
Continuing the discussion as it looks like I'm still having Emby Connect login issues with the most recent commits. It looks like Ombi properly pulls in the Emby Connect username info if it's available. However, the Emby Connect password does not seem to work in getting the user logged into Ombi.
