### ISSUE TITLE
[Feature Request] Requesting previous seasons

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#1723]
Would be nice to not have to select each episode from a previous season in order to tell Sonarr that a season is requested.

**Comment by tidusjar** [comment]
What do you suggest?

You can select all the episodes from season 1 and then 2 in the same request?

**Comment by Codehhh** [comment]
Easiest way might be to just add a "Select All" within the season which would just request the entire season rather then individual episodes.

iirc.monitoring an entire season in Sonarr is a little different then monitoring each episode

**Comment by tidusjar** [comment]
Yeah I can add that. But regarding the sonarr integration. Currently if you select all episodes in a season ombi will recognise that and perform a season search on sonarr.

**Comment by tidusjar** [comment]
This has been added
