### ISSUE TITLE
Cannot open assembly './Ombi': File does not contain a valid CIL image.

### ISSUE THREAD

**Issue by BrandonEckert** [tidusjar/Ombi#1730]
#### Ombi build Version:

V 3.0.2379

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Debian 9 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
Good afternoon, I followed the steps in the installation for Linux, and upon running Ombi.exe via Mono (Version 4.6.2), I receive the following error:

Cannot open assembly './Ombi': File does not contain a valid CIL image.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.
Followed installation
mono --debug ./Ombi
Receive error: Cannot open assembly './Ombi': File does not contain a valid CIL image.

**Comment by PotatoQuality** [comment]
Ombi v 3 doesnt use mono. Pleas follow the installation structions for version 3 instead of version 2
