### ISSUE TITLE
Autostart on OSX for v3 Open Beta

### ISSUE THREAD

**Issue by YodaSpow** [tidusjar/Ombi#1734]
#### Ombi build Version:

V 3.0.2379

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Darwin 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct 4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64

#### Problem Description:

Similar to the v2 mono setup, how can I Autostart v3 for mac OS X 
Previous v2 post explained it, not sure what to enter to get the v3 to Auto start?
https://github.com/tidusjar/Ombi/issues/501#issuecomment-242417016

Application Base Path: /Users/spowart/Movies/Ombi/

Thanks!

**Comment by tidusjar** [comment]
No idea. I hope someone else can answer this

**Comment by YodaSpow** [comment]
Here is what I have so far for it:

1. Create a file called net.tidusjar.ombi.plist in your `~/Library/LaunchAgents` directory with the following content:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<dict>
		<key>SuccessfulExit</key>
		<false/>
	</dict>
	<key>Label</key>
	<string>Ombi</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/spowart/Movies/Ombi</string>
		<string>Ombi</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/Users/spowart/Movies/Ombi</string>
</dict>
</plist>```

Bit I am not sure about is how to target the `Ombi` _Unix executable_ 
Also how do you make the launch file do this command:
`./Ombi` https://github.com/tidusjar/Ombi/wiki/Installation#macos
```	<array>
		<string>/Users/spowart/Movies/Ombi</string>
		<string>Ombi</string>
	</array>```

2. In Terminal:
To enable the daemon: launchctl load ~/Library/LaunchAgents/net.tidusjar.ombi.plist
To disable the daemon: launchctl unload ~/Library/LaunchAgents/net.tidusjar.ombi.plist

Credit to @kamikasky for mono v2 setup i'm biassing this on that.

**Comment by YodaSpow** [comment]
**Made a Apple Script Automation App as a work-around:**
Going to use this till I can get the Daemon working.

```
on run {input, parameters}
	tell application "Terminal"
		set terminal to window 1
		activate
		do script with command "cd /Users/spowart/Movies/Ombi" in terminal 
		do script with command "./Ombi" in terminal
	end tell
end run
```
![ombi-app](https://user-images.githubusercontent.com/26332959/33193298-85a906f6-d0bf-11e7-9b3a-28124b63cf76.gif)

Have it setup as a login App. "Login Items"
[https://support.apple.com/en-gb/HT204005](https://support.apple.com/en-gb/HT204005)

Have attached the `ombi.app` in a zip, if anyone wants to use or improve it..
You can edit the path by `ombi.app` in `Automator.app`
Just need to to edit the `/Users/spowart/Movies/Ombi` to your install location of Ombi.

[ombi.app.zip](https://github.com/tidusjar/Ombi/files/1500501/ombi.app.zip)

**Comment by tylerforesthauser** [comment]
This is what I've got set up and it works like a charm...

Create a .plist file in your `~/Library/LaunchAgents` folder. 
I've name mine as: `com.PlaceTheServer.Ombi.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.PlaceTheServer.Ombi</string>
    <key>ProgramArguments</key>
    <array>
        <string>./Ombi</string>
    </array>
    <key>WorkingDirectory</key>
    <string>/Applications/Ombi</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

Notes: 

- This requires your Ombi directory be in your Applications folder. 
- _com.PlaceTheServer.Ombi_ can be named whatever you want.

Indeed it you can manually load and unload using `launchctl load ~/Library/LaunchAgents/com.PlaceTheServer.Ombi.plist` and `launchctl unload ~/Library/LaunchAgents/com.PlaceTheServer.Ombi.plist` in Terminal, respectively.
