### ISSUE TITLE
[Feature Request] Add additional variables for notifications

### ISSUE THREAD

**Issue by schmittyd** [tidusjar/Ombi#1736]
#### Ombi build Version:

V 3.0.2382

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Media Server Version:

3.2.40.0

#### Operating System:

Ubuntu 16.04 LTS x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Not applicable

```

#### Problem Description:

Please add {ApprovedDate}, {RejectedDate}, {IssueDate} and {AvailableDate) variables to notification settings.

#### Reproduction Steps:

Not applicable

**Comment by didyouexpectthat** [comment]
Feature requests are handled via the FeatHub.
https://feathub.com/tidusjar/Ombi

**Comment by tidusjar** [comment]
@didyouexpectthat I asked him to put the issue on here. Thanks though :)

**Comment by CoderKiwi** [comment]
Could you also please add a {ViewOnPlex} and/or {ViewOnEmby} variable so that in the email you can click the link and it'll go to the server to view?

**Comment by xunil75** [comment]
I have two Plex Servers on my network. I was able to add them to Ombi, all great! Now my question, once a movie has been added, a Telegram message is sent, however I would like to inform my users on which server the movie was added. Can you please implement a variable notification for this as well?

Example:

`Hello! "User" You requested The Shape of Water (2017) on Plex Requests! This is now available on Plex Server {PlexServer}! :)`

Thanks!

**Comment by hbooo** [comment]
Hi, It also could be interesting to have current week number
