### ISSUE TITLE
Error connection with reverse proxy

### ISSUE THREAD

**Issue by lilp69** [tidusjar/Ombi#1747]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Debian 9.0

I make a reverse proxy for Ombi with this conf : https://pastebin.com/8jQgzwiB
I can go on XxX.ddns.net. But I stuck with "loading" message.

**Comment by tidusjar** [comment]
Jump on discord and we should be able to help.

But looks like you have not set your base url in the config, make sure it's also set in the app.

**Comment by Flaxee** [comment]
Sorry for reopening this issue, but is it a must to set the Base URL in Ombi even if you use a subdomain and just **location /** in Nginx? I thought Base URL is only needed if you have **location /ombi** for example.

**Comment by tidusjar** [comment]
Then in don't think you need the base URL
