### ISSUE TITLE
Windows Automatic Update Failing

### ISSUE THREAD

**Issue by dshokouhi** [tidusjar/Ombi#1748]
#### Ombi build Version:

V 3.0.2363

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.97.4460

#### Operating System:

Windows 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Unable to retrieve logs so I have screenshots of the command prompt window

```

![ombi1](https://user-images.githubusercontent.com/1634145/33342235-45711536-d436-11e7-84ee-d948a4a7038c.PNG)
![ombi2](https://user-images.githubusercontent.com/1634145/33342239-4b3fa27a-d436-11e7-8bff-422daf0eedbf.PNG)

#### Problem Description:

Windows automatic update will not continue

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1. install ombi v3 in windows
2. attempt automatic update

**Comment by Fiala06** [comment]
I had same issue. Turns out Autoupdater isn't complete let. Here was my post: https://github.com/tidusjar/Ombi/issues/1739

**Comment by PotatoQuality** [comment]
@Fiala06  Correct. 

@dshokouhi i hope its not a big trouble for you to post this printscreen in https://github.com/tidusjar/Ombi/issues/1460 ?
