### ISSUE TITLE
Error handling middlewear

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1749]
#### Ombi build Version:

V 3.0.2407

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

N/a

#### Operating System:

Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-11-28 12:28:42.751 -08:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at 5.7.8  https://support.google.com/mail/?p=BadCredentials p19sm8726pfj.140 - gsmtp

```

#### Problem Description:

Ombi needs middleware handling of errors

#### Reproduction Steps:

There are times where Ombi just confirms that it successfully issued a command but it would be good if the feedback from the command that occurred was captured in the UI. My example of the logs above show that I had a wrong username/password for Gmail; but nothing told me that and I sat around waiting to discover what was wrong. I looked at the logs and found this, but middleware should have told me.

In Discord, someone said they tried to access a Plex server with SSL but the log says that there is a security issue with the cert; would have been nice to know but had to look in the logs to find out. All Testing does is confirm it issued the test command.

**Comment by tidusjar** [comment]
We now get better errors in the browser console
