### ISSUE TITLE
Suggestion - Notifications and Search

### ISSUE THREAD

**Issue by Fiala06** [tidusjar/Ombi#1750]
#### Ombi build Version:

V 3.0.2407

-- | --

#### Update Branch:

Open Beta

#### Media Sever:

Plex/

#### Operating System:

Win10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I have 2 suggestions. 

**Notifications** - Would it be possible to get notifications for new content that shows up on Plex/ronarr/radarr even through it wasn't requested through ombi? I would prefer to get notifications from one place rather then from plexpy, ombi, sonarr and radarr each time something is new. :)

**Search** - Suggestions/Popular/Upcoming,Top Rated, could this be expand to show more recommendations? Each category for me only shows less than 10. Most which were requested already. Maybe hide ones that were already requested also?

Thanks for all your time and effort! 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
Point 1: News letter feature will do that job.


Point 2: pleas open an feature request on the feature request page tot that :)

**Comment by Fiala06** [comment]
So am I just not seeing the newsletter option or it's already in the works?

**Comment by Trenchguns** [comment]
Newsletter will be implemented in the future
