### ISSUE TITLE
Tv Show requests don't show up (sometimes)

### ISSUE THREAD

**Issue by Trenchguns** [tidusjar/Ombi#1755]
#### Ombi build Version:

V 3.0.2410

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 4.9.30-unRAID

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Logs seem to currently only show plex episode caching recently.

```

#### Problem Description:

https://gyazo.com/a3526d4d85c39cdd8610e2d2c7839451?token=ee62bb4b2f79d2351ae72d39c4c040fa
The whole season seems to be missing.
For family guy it's the same issue but only the first couple episodes were ever requested.
But for the the show Orville it works perfectly fine.
https://gyazo.com/c1e1937709fadf814668efed11229d50

#### Reproduction Steps:

1. Request TV Episode (single one or whole season)
2. Approve Request
3. Sometimes it gets borked.

**Comment by tidusjar** [comment]
Looks like no request was actually added, is there anything in the logs?

Can you get a repro 100% of the time?

**Comment by Trenchguns** [comment]
https://gyazo.com/225bd3dec8a4a7aaabd2dd78f09d885c
I submitted a request for another episode, approved it, waited a day and it's still there working perfectly fine. But as you can see The Orville is all fine and dandy there, but American Dad is missing the entire season (of which all are grabbed) and Family guy only has that latest episode.

**Comment by Trenchguns** [comment]
https://gyazo.com/754b69d6c38029a3299728049b620fca
So it's pending, I'll keep an eye out to see if it disappears as well.
