### ISSUE TITLE
TV Shows Request not comparing granular enough when checking for duplicate requests

### ISSUE THREAD

**Issue by rudyolph** [tidusjar/Ombi#1756]
#### Ombi build Version:

V 3.0.2410

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Win 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When making a request for a single episode from a single season of a tv show...you can not longer make any more additional requests for other episodes from that tv show.  Ombi raises an error saying that request had already been added.

#### Reproduction Steps:

1.) Pick TV Show
2.) Request a single episode from a single season.
3.) Go back into the tv show...and pick another episode from the same or a different season and try to submit the request for it.

**Comment by tidusjar** [comment]
Not going to do this yet.
