### ISSUE TITLE
Notifications (Discord possibly others) PosterImages

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#1758]
#### Ombi build Version:

V 3.0.2410

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Discord Webhook notification always adds the poster even when it's not in the template.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

have a notification sent to discord even without having the {PosterImage} on the template it shows the image.

**Comment by goldenpipes** [comment]
```        protected override async Task Test(NotificationOptions model, DiscordNotificationSettings settings)
        {
            var message = $"This is a test from Ombi, if you can see this then we have successfully pushed a notification!";
            var notification = new NotificationMessage
            {
                Message = message,
            };
await Send(notification, settings);
```
this is the Test message and there is no mention of image

```
protected override async Task AvailableRequest(NotificationOptions model, DiscordNotificationSettings settings)
        {
            var parsed = await LoadTemplate(NotificationAgent.Discord, NotificationType.RequestAvailable, model);
            if (parsed.Disabled)
            {
                Logger.LogInformation($"Template {NotificationType.RequestAvailable} is disabled for {NotificationAgent.Discord}");
                return;
            }
            var notification = new NotificationMessage
            {
                Message = parsed.Message,
            };
            notification.Other.Add("image", parsed.Image);
            await Send(notification, settings);
}
```

image is there. but yeah where is the if added to the template setting. Curious
i wonder if you take out the  
```notification.Other.Add("image", parsed.Image);```
 will it still add the image if you add it to the template with {PosterImage}

**Comment by tidusjar** [comment]
So yeah the code you have highlighted adds the image.

Now if I was to put it in the template I don't think it would work well due to you have no control of the position of it (for other notification agents) but this is an embedded image in discord and it not really part of the message body so this cannot be done.

I could look into adding an option to enable/disable images, but that's low priority.

**Comment by crepehat** [comment]
For what it's worth I'd appreciate the option to disable pictures.

**Comment by 19wolf** [comment]
Why is this issue closed? Even if low priority, it's still an issue that could be solved

**Comment by ellidi** [comment]
> Why is this issue closed? Even if low priority, it's still an issue that could be solved

Agreed.
