### ISSUE TITLE
[L#C] Missing search ID on launch and on clicking logo (which i assume is just a page refresh)

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1762]
Search ID is not applied to the page when you first launch ombi or when you click the ombi logo at the top left as seen here: 

![omblur no id](https://user-images.githubusercontent.com/21117493/33445381-b47e7096-d5ca-11e7-8307-b69ee2623cc0.PNG)

but if you click the search button, the proper ID is attached as seen here: 

![omblur search id](https://user-images.githubusercontent.com/21117493/33445333-90bcb56e-d5ca-11e7-9b07-7783ca151487.PNG)

**Comment by tidusjar** [comment]
I think I fixed this, can you confirm @leram84 ?

**Comment by leram84** [comment]
kind of... im guessing by fixed u mean that you got it to load /search on startup? that does work, but the problem is you can still get to the "ID-less" search page by clicking the ombi logo in the top left (the part that says omBlur above). If you can make that route to /search as well, that will work too
