### ISSUE TITLE
Sign-in credentials revoked unless "remember me" box is ticked

### ISSUE THREAD

**Issue by copcopcopcop** [tidusjar/Ombi#1764]
#### Ombi build Version:

V 3.0.2418

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 - running in lsio docker container

#### Problem Description:

Admin accounts and user accounts are unable to sign-in unless "remember me" box is ticked. When box is left unticked, Ombi complains that username / password is incorrect. When "remember me" box is ticked, all accounts are able to login normally.

**Comment by tidusjar** [comment]
I cannot recreate this issue.

Please can you clear your browser cache (or try a different browser) and see if the same issue still persisits
