### ISSUE TITLE
Buttons missing in TV Shows requests

### ISSUE THREAD

**Issue by copcopcopcop** [tidusjar/Ombi#1766]
#### Ombi build Version:

V 3.0.2418

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 - running in lsio docker container

#### Problem Description:

Buttons missing when viewing requests in TV Shows column. Unable to approve/delete/make available etc...

Movies column is fine.

![screenshot 2017-12-01 13 36 17](https://user-images.githubusercontent.com/22751167/33497744-ea56cef2-d69c-11e7-9d50-f8f85355bb1b.jpg)

**Comment by tidusjar** [comment]
Press the view button. 

Under each show you will find a list of requests. You don't delete the show, you delete the requests
