### ISSUE TITLE
Linux versions for Ombi v3 after 3.0.2410 are broken

### ISSUE THREAD

**Issue by valantislevas** [tidusjar/Ombi#1769]
#### Ombi build Version:

V 3.0.2410

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Today i reinstalled the ombi to make some changes and i see the other versions of ombi v3 after 3.0.2410 is broken on Wizard for setup.

When i download and install 3.0.2410 is worked and also update to the latest.

Broken are: 
https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.2422/artifacts
https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.2423/artifacts

thanks

**Comment by valantislevas** [comment]
Also on version
```
3.0.2422
```

Add user and edit user details dont open to configure..

**Comment by straying1** [comment]
Ubuntu 17.04 here. Same issue. 
Just upgraded to 3.0.2423 (I think) and I cannot get past the Wizard. When I hit "Next" a progress bar displays, but does not actually trigger anything (like the next step).

**Comment by lambro690** [comment]
I am also having that issue @straying1. I was not able to get past the wizard on the latest version. I am also running Ubuntu 17.04. I was able to get an older version working though.

**Comment by smoofus** [comment]
+1 Unable to get past the splash screen/wizard on latest version.

**Comment by mattgphoto** [comment]
Also having an issue like @valantislevas ...
Cannot edit users at all in version 3.0.2422 on Ubuntu 16.04 in IE, Edge, Firefox, Chrome, or Vivaldi.

**Comment by stoogefr** [comment]
Same issue there. Unable to connect to Ombi cause of wizard : 
http://**********:5000/Wizard

**Comment by tidusjar** [comment]
Fixed in latest build
