### ISSUE TITLE
CouchPotato suddenly not working.

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#1772]
#### Ombi Version
V 2.2.1678
#### Update Branch:
Stable
#### Operating System:
Ubuntu Desktop 16.04
#### Log Level:
Debug

Nothing on my system has changed.  Suddenly when I try to request a movie I get the error, Something went wrong adding the movie to CouchPotato! Please check your settings.  

I have checked my settings and nothing has changed. When I go into the CouchPotato section of ombi settings and click "Test Connectivity" it is successful.  I have rebooted both the server running couchpotato and the server running ombi.  

I can add movies directly to CouchPotato without issue.  

I don't see anything in the logs that relate to the issue.

**Comment by tidusjar** [comment]
What was the issue?

**Comment by Jakesparrow** [comment]
Probably that he was using CP instead of Radarr amiright! :rofl:

**Comment by kewlrobd** [comment]
Actually your right.  The issue was with CP.  It suddenly is very inconsistent with finding titles.  When a title is not found it spits out that error.  I have tried Radarr but it wasn't to my liking.
