### ISSUE TITLE
[LC] Need classes for media tags

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1773]
I need classes for each of those tags  (release date, home page., processing request). I can't use nth child on all those cause the number of tags changes depending on if  a movie has a homepage, etc... so i need each child (either attribute or span... doesn't matter, just need the first one) of that highlighted div to have a unique class.

![ombi tags](https://user-images.githubusercontent.com/21117493/33573081-cae5a530-d902-11e7-9667-cb4ccba8f8c4.PNG)

**Comment by leram84** [comment]
OHHH and i also need those classes to be different when the text in the label changes... so one class for "processing request" and a different one for "not requested" etc

**Comment by tidusjar** [comment]
I gave them some id's e.g. `processingRequestLabel`

**Comment by leram84** [comment]
i dont think this is working.. i see the labels you're trying to add in that commit, but on my side they all turn into `ng-star-inserted` class... its everywhere. I need each tag to have a unique class, and the last one (the one that says Available/Not Requested/Processing Request/etc) I need a class for each possible state that tag can have... as a side note, i think the best way to do that one would be:

Not Requested
Pending Approval
Pending (for when its approved, but not added for whatever reason... including "it hasnt been released yet)
Rejected
Available

lmk if u want to see what im doing if u need convincing that this is a good idea... it makes more sense when u see the way im laying things out

**Comment by tidusjar** [comment]
I added Id's:
![image](https://user-images.githubusercontent.com/6642220/34061826-aeccb2fc-e1e1-11e7-81f9-660a5d1b5aa1.png)

**Comment by tidusjar** [comment]
Fixed in develop
