### ISSUE TITLE
Tabs and buttons show backend code

### ISSUE THREAD

**Issue by DirtyCajunRice** [tidusjar/Ombi#1776]
#### Ombi build Version:

V 3.0.2435
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04.3

#### Problem Description:

![image](https://user-images.githubusercontent.com/15788890/33591695-8ed705b2-d94c-11e7-8f70-883925f6f4ac.png)

**Comment by tidusjar** [comment]
Clear your cache. When I update the translations this sometimes happens, refresh your cache and it should be good.
