### ISSUE TITLE
START: The system cannot find the file specified.

### ISSUE THREAD

**Issue by SanctiMortem** [tidusjar/Ombi#1780]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Everything was installed successfully, but when I try to start Ombi, I get  
"Ombi: START: The system cannot find the file specified."

I restarted the machine to be sure, and tried again, but got the same result.

I don't know what else to do, how can I uninstall so I can try again? 

Please help
Thanks in advance!

#### Reproduction Steps:

"nssm start Ombi"

**Comment by tidusjar** [comment]
You couldn't have setup NSSM correctly

**Comment by SanctiMortem** [comment]
Not sure what you mean, it's the first time I use NSSM, but I followed the guide to the letter and got every "successful" code, up until the "start" command.
If NSSM didn't install correctly it wouldn't let me write any of the nssm commands would it? 

What do I need to do? should I reinstall everything?

thank you!

**Comment by PotatoQuality** [comment]
We dont have  guide  with instructions to install ombi v3 with nssm?

**Comment by SanctiMortem** [comment]
Hi @PotatoQuality well, I used this one https://github.com/tidusjar/Ombi/wiki/Installing-on-Windows, I wasn't sure if it was from you directly, but this is the link to the actual guide (https://www.htpcguides.com/install-plex-requests-net-windows-system-service/)

It was the first time I used NSSM, is there a different way of installing Ombi?

Thank you!

**Comment by SanctiMortem** [comment]
How can I uninstall everything? so I can start again from the begining. haha I feel like I already screw up big time :S

**Comment by PotatoQuality** [comment]
Hmm that for v2. Not sure why we have still the v2 instructions online xd
 Installation for  v3:

Windows

Download the latest windows.zip
Right click > Properties > Unblock
Extract the zip
Run Ombi.exe

**Comment by SanctiMortem** [comment]
Oh great, I'll try that one!

Thank you!

**Comment by goldenpipes** [comment]
u can still use nssm to run ombi as a service in windows. otherwise you will have a console (cmd) window open when ombi is running.

**Comment by PotatoQuality** [comment]
@goldenpipes  we cant  supporting nssm
