### ISSUE TITLE
Ombi does not pull the DOGnzb watchlist

### ISSUE THREAD

**Issue by mannibis** [tidusjar/Ombi#1782]
#### Ombi build Version:

V 3.0.2440
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

macOS High Sierra

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When adding a movie to the DOGnzb watchlist via the Ombi UI, it does not already look through the existing DOGnzb watchlist. It will still allow you to Request a movie even though it has already been Watchlisted on DOGnzb. Is this how it is supposed to work? Perhaps mark it as approved automatically, or indicate that it has already been requested (even though it wasn't requested via Ombi)?

What are your thoughts? I believe the DOGnzb API allows for listing the Watchlist in XML format.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by PotatoQuality** [comment]
Github? Please rename  the topic  name to something that makes  sense.

**Comment by mannibis** [comment]
Apologies about the title, I left it blank and the default is "Github" I assume.
