### ISSUE TITLE
[Feature Request] Re-add "Search by Actor" to Ombi 3.0

### ISSUE THREAD

**Issue by simhavaktra** [tidusjar/Ombi#1784]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Problem Description:
I have a web-facing Ombi setup used by about twenty folks and the most used search method is "By Actor". I've been keeping both a 2.x and a 3.x version but everyone stays with the 2.0 so they can do actor searches. Is this something planned to return in 3.0?

Thanks!

**Comment by PotatoQuality** [comment]
---> https://feathub.com/tidusjar/Ombi
