### ISSUE TITLE
Cant Change Port Number in new ombi 3.0

### ISSUE THREAD

**Issue by 1tsmejp** [tidusjar/Ombi#1787]
#### Ombi build Version:

V 3.0.2450
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I cant seem to find where to replace the port number OMBI runs on. Is there a simple way to change it or perhaps issue it via command prompt?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by didyouexpectthat** [comment]
You can change it in the run command. 
https://github.com/tidusjar/Ombi/wiki/Startup-Parameters

**Comment by keithwoelke** [comment]
This solution does not work well with systemd, short of using an intermediary script to run Ombi (which is what I've done).

**Comment by hagabla** [comment]
How is that done with systemd?

**Comment by keithwoelke** [comment]
$ cat /etc/systemd/system/ombi.service
[Unit]
Description=Ombi - PMS Requests System
After=network-online.target

[Service]
User=ombi
Group=ombi
WorkingDirectory=/opt/ombi/
ExecStart=/usr/local/bin/ombi
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

cat /usr/local/bin/ombi
#! /bin/bash

/opt/ombi/Ombi --host 'http://*:8084'

**Comment by hagabla** [comment]
Thanks btw

**Comment by keithwoelke** [comment]
Oh? I recall having issues with that approach. It's been a while so I no longer remember the details, but if it works for you, so much the better. :-)
