### ISSUE TITLE
Non monitored movies in radarr when requested should be set to monitored

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1789]
If we have a movie in radarr set as unmonitored, when requested in Ombi, it should be set as monitored and we should not try and re-add it.

**Comment by djsecrist** [comment]
I would love to see this implemented. The error message that is currently returned if something already exists on the Sonarr/Radarr list is not ideal.  If something is requested through Ombi that already exists in either Sonarr/Radarr, the title should be set to monitored and added to the Ombi request list as if it were a new request.

**Comment by tidusjar** [comment]
That's the plan...
