### ISSUE TITLE
Issues installing on Windows 7 32bit

### ISSUE THREAD

**Issue by bsollenb54** [tidusjar/Ombi#1790]
#### Ombi build Version:

V 3.0.XX (not sure - downloaded latest windows.zip from today)

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 7 32-bit

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Getting this error when I try to run ombi.exe as an administrator:
The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 or x64 version of the program, and then contact the software publisher

Getting this error when I try to run nssm start ombi.exe from CMD as administrator:
Ombi: Unexpected status SERVICE_STOPPED in response to START control

Do you have an x86 version of the windows.zip?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
There is no 32bit version yet.
