### ISSUE TITLE
Requested items do not show up on Requests page.

### ISSUE THREAD

**Issue by daymanbpi** [tidusjar/Ombi#1791]
#### Ombi build Version:

V 3.0.2456

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Running in Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Item shows as requested in search, but does not show up on requests page.

#### Reproduction Steps:

Restarted/Updated/Shut Down/Start
![1](https://user-images.githubusercontent.com/25697834/33807741-42706a18-dda9-11e7-9e8e-ee5384265134.PNG)

**Comment by PotatoQuality** [comment]
If  the show is already on radarr it will not show on the requests  overview  page.
