### ISSUE TITLE
Notification sent to the incorrect answer

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#1794]
#### Ombi build Version:
Version | 3.0.2459
Branch | DotNetCore
Github | https://github.com/tidusjar/Ombi
Discord | https://discord.gg/KxYZ64w
Forums | https://forums.ombi.io
OS Architecture | X64
OS Description | Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
Process Architecture | X64
Application Base Path | /app/ombi/
#### Media Sever:

Plex -  1.10.1.4561

#### Problem Description:

When any user make a new request and I approve I get a notification (pushbullet) saying the following:

"Hello your request for XXX has been approved"

I get the notification initially when the user makes the request which is fine.

#### Reproduction Steps:

User to request a new Movie, I approve and get the notification like I was the one requesting the movie.

**Comment by tidusjar** [comment]
ok? What's the issue here?

**Comment by cesalo** [comment]
OK .. maybe I wasn't clear enough or my understanding is incorrect. Let's say I'm user "admin" and "userA" request a movie. As "admin" i'd get a message saying "userA" requested movie X which is fine then I approve it after this I'm also getting a message saying "Hello you request for movie X has been approved", shouldn't this last message being sent to "userA" instead of "admin".

**Comment by tidusjar** [comment]
Ah ok now I understand. The current problem is that we do not know the users pushbullet address. In the future I'll be adding the option to add these to the user. But currently this is the way the system works.

**Comment by goldenpipes** [comment]
I assume the same goes for things like discord, where their USER ID will be a field that can be used?

**Comment by tidusjar** [comment]
Correct @goldenpipes

**Comment by goldenpipes** [comment]
sweeeeeet!
