### ISSUE TITLE
OmbiV3 + Theme + nginx = Themes break

### ISSUE THREAD

**Issue by 1activegeek** [tidusjar/Ombi#1795]
#### Ombi build Version:
V 3.0.2459

#### Update Branch:
DotNetCore

#### Media Sever:
Plex

#### Operating System:
LS.io Dev Container

#### Problem Description:
Using nginx to front end OmbiV3 with HTTPS, redirecting to HTTP, with use of root URL of /requests. I noticed that as soon as I enable the root, restart, and validate connectivity - it seems themes break. I'm not sure if it's because the theme was enabled first, or if it's something to do with the connection through the proxy that is causing this. Happy to try and help provide any other valuable logging info, but there was nothing I could see of value in the 1 lines of log entries that existed. 

#### Reproduction Steps:

Setup Ombi
Configure Base Path setting to something
Configure LayerCake theme
Use nginx to proxy this base path
Notice the lack of Theme skin

**Comment by 1activegeek** [comment]
Ok, so not necessarily a fix, but I have found a workaround for now. Though depending on how you plan to use it (assuming an nginx running front end, is expected to be used and only accessed through here). Not familiar with the LayerCake stuff yet, but I took a look and something caught my eye at the top of theme box:

```
<link rel="stylesheet" type="text/css" href="/api/v1/Settings/ThemeContent?url=https://raw.githubusercontent.com/leram84/layer.Cake/master/ombi/css/omBlur.css">
```

So I decided to alter this by inserting my `/requests` in front of the `/api/v1......`. Doing this and submitting, rectified the situation immediately upon a page refresh. Interestingly it looks like the original link directly to the server:port is still working, but I'd imagine there may be bugs in that interface now since the URL has been changed. 

If this is deemed as the solution, perhaps maybe a quick note in the documentation with information around the nginx configs.

**Comment by tidusjar** [comment]
Yeah you spotted and corrected the issue!

I need to add some code in the modify that when there is a base url

**Comment by CoderKiwi** [comment]
Has this been fixed?

**Comment by tidusjar** [comment]
It's not broke, you can manually modify it like above

**Comment by CoderKiwi** [comment]
I'm running a Docker image... don't think I have access to manually change the CSS. Besides, it makes sense to add the baseURL string to the front of that CSS href. Seems like a simple enough change?

**Comment by tidusjar** [comment]
Yes just change ` href="/api/v1/Settings/ThemeContent` to ` href="/BASEURL/api/v1/Settings/ThemeContent`

**Comment by 1activegeek** [comment]
@CoderKiwi - I'm running it as a docker as well. The change is not made in core files outside your container. It's made in the place where you setup the theme inside ombi. Go to the customization section where you selected the Blue theme, and in the box below it one of the first lines you'll see containers the line of code I posted above. Insert your modification, save (submit), profit.

**Comment by CoderKiwi** [comment]
@1activegeek Ah of course - thank you.

**Comment by anojht** [comment]
Hello everyone, a fix for this has been merged in the latest develop build, can anyone test and let us know if it has been resolved? Thank you!

**Comment by CoderKiwi** [comment]
Don't have nginx set up anymore so I can't test it right away, but I will say thank you for the fix! I'll let you know once I can test it.

**Comment by phairplay** [comment]
Hi I’ve made the change as above on the latest version and it still doesn’t load the pages correctly

**Comment by anojht** [comment]
You don't have to edit the url and insert your baseurl manually anymore, Ombi handles this automatically. Please revert you manual edits and use the latest version.

**Comment by Xodus-CO** [comment]
On v. 3.0.3368 and the theme was still broken when behind nginx.   Added the manual fix above and it resolved the issue.
