### ISSUE TITLE
Description link for non released TV shows is empty

### ISSUE THREAD

**Issue by a3rosol** [tidusjar/Ombi#1797]
#### Ombi build Version:

V 3.0.2456 

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

n/a

#### Operating System:

Ubuntu Zesty

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Description for future requested tv shows link to imdb and is empty. Link is: http://www.imdb.com/title//
Returns 404

### Expected Behaviour:

No link or indication, that descrition is not available yet

#### Reproduction Steps:

Add TV Shows reverie and altered carbon. Description link will be emty

**Comment by tidusjar** [comment]
Not really sure what I can do about this since our data provider does not
yet have the ImdbId for this show:

http://api.tvmaze.com/search/shows?q=altered%20carbon

Under Externals

**Comment by a3rosol** [comment]
Interesting... I'd say either check if a link is provided and only then show it. Or link to tv maze? Maybe that's better than nothing
