### ISSUE TITLE
Cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by JorricksTU** [tidusjar/Ombi#1798]
#### Ombi build Version:

V 3.0.2460

#### Update Branch:

Open Beta

#### Media Sever:

None

#### Operating System:

Ubuntu on Samsung Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa core CPUs chip.

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Not applicable 

#### Problem Description:

When I run Ombi I get the following:
henk@henk:/opt/Ombi$ ./Ombi
-bash: ./Ombi: cannot execute binary file: Exec format error
henk@henk:/opt/Ombi$ /opt/Ombi/Ombi
-bash: /opt/Ombi/Ombi: cannot execute binary file: Exec format error

#### Reproduction Steps:

Follow tutorial here: https://github.com/tidusjar/Ombi/wiki/Installation
and run ./Ombi

**Comment by didyouexpectthat** [comment]
are you running 32-bit? The Ombi package is 64-bit.
```
/opt/ombi/Ombi: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=b1e8f043daaa70349629d6129728a9891a19c89e, stripped
```

**Comment by JorricksTU** [comment]
So my platform is not supported and I can not get it working right?

**Comment by PotatoQuality** [comment]
Only  64 bit support at the moment :(
