### ISSUE TITLE
[Enhancement] Request filter in Omvi v3

### ISSUE THREAD

**Issue by rickatnight11** [tidusjar/Ombi#1801]
#### Ombi build Version:

3.0.2459

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Not Applicable

#### Operating System:

Linuxserver.io Docker container (https://github.com/linuxserver/docker-ombi/tree/preview) on CentOS 7.4 host.

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Not applicable

#### Problem Description:

Ombi v2 has the ability to filter requests by things like Approved, Not Approved, Available, etc:

![image](https://user-images.githubusercontent.com/76622/34136043-01414b40-e432-11e7-967c-bcb8567dd3b0.png)

This is a super useful feature, especially after building a long history of fulfilled requests.  This feature appears to be missing from Ombi v3:

![image](https://user-images.githubusercontent.com/76622/34136072-1bee1090-e432-11e7-82c0-c330e3eacff9.png)

#### Reproduction Steps:

Compare Requests page on Ombi v2 and v3.

**Comment by rickatnight11** [comment]
@tidusjar, did this issue not meet some requirement?

**Comment by tidusjar** [comment]
I'm already planning to add it but not taking feature requests at the moment.
