### ISSUE TITLE
Email Sender partiall obeyed for email notifications

### ISSUE THREAD

**Issue by phiyuku** [tidusjar/Ombi#1802]
#### Ombi build Version:

 2.2.1678 

#### Update Branch:

Stable

#### Media Sever:

Emby

#### Operating System:

Docker

#### Problem Description:

Seems like when an email goes out at least for New Movies the Email Sender is not entirely correct. For a test for instance if I have Email Sender set to ombi@example.com but the username is username@example.com it would send as username@example.com <ombi@example.com>. When you hit test though it works fine and sends as ombi@example.com

#### Reproduction Steps:

Set Email Sender to a different username than the one actually sending it. Hit Test and see that it works. When the New Movies email is triggered you will see it come in as username@example.com <ombi@example.com>

**Comment by tidusjar** [comment]
That makes sense since it uses a SenderName and a FROM header. I've adjusted the test button to also use this,
