### ISSUE TITLE
Can't get Web App open

### ISSUE THREAD

**Issue by mrumley02** [tidusjar/Ombi#1803]
#### Ombi build Version:

V 3.0.2468

#### Update Branch:

Open Beta

#### Operating System:

Windows 10

#### Problem Description:

![image](https://user-images.githubusercontent.com/34703319/34193751-479e81c4-e5a5-11e7-9377-6dd5a5e1cdb8.png)

No matter how many installs and different locations etc. this is all I get. Am I doing something wrong?
It worked once but I couldn't open the url.

EDIT:
It worked this time. However, I still can't open the web app
![image](https://user-images.githubusercontent.com/34703319/34193837-bab920b0-e5a5-11e7-853b-4a049d649be1.png)

**Comment by tidusjar** [comment]
There are a few issues.

1. You are running a feature branch and not the DotNetCore branch
2. Your working directory needs to be where ombi is installed.

**Comment by mrumley02** [comment]
It works correctly.
But I still can't open the WebApp

**Comment by tidusjar** [comment]
Please see my first comment.

**Comment by mrumley02** [comment]
I apologise, but I am new to how github etc. works. I've downloaded the DotNetCore branch and extracted it to C:\Ombi . I have also downloaded the V3 application from the GitHub Landing Page and extracted it to the same location. I've run Ombi.exe and it appears to be working. However when I enter "localhost:5000" into my web browser, nothing loads.
I think I've solved error 1, but am unable to troubleshoot on my own, mainly due to lack of experience.
If you could enlighten me that would be greatly appreciated.

**Comment by tidusjar** [comment]
Ok, you need to set your working directory.

Open up the `cmd` and type:

```
cd C:\Ombi
```
Then launch Ombi via the CMD
```
Ombi.exe
```

**Comment by mrumley02** [comment]
Ok. I've done that

**Comment by mrumley02** [comment]
I've got the same thing I usually get.
Application Started

**Comment by tidusjar** [comment]
Please post a screenshot of the console

**Comment by mrumley02** [comment]
![image](https://user-images.githubusercontent.com/34703319/34205903-2fec6b70-e5d4-11e7-9c69-2255e8bc0b8e.png)

**Comment by tidusjar** [comment]
There is nothing wrong, you just need to go to
`http://localhost:5000` on the machine you are running Ombi on and it will work.

**Comment by mrumley02** [comment]
I get nothing:
![image](https://user-images.githubusercontent.com/34703319/34206023-b0c94326-e5d4-11e7-941f-fd3f11c9d6b8.png)

Meanwhile, Plex works using localhost:
![image](https://user-images.githubusercontent.com/34703319/34206056-cf6790b2-e5d4-11e7-9154-2b168b339e45.png)

**Comment by mrumley02** [comment]
Even using the loopback IP (127.0.0.1) and my direct IP (192.168.X.XXX) won't work)

**Comment by tidusjar** [comment]
Are you trying to access it on the same machine?

**Comment by mrumley02** [comment]
Yes.

Matthew Rumley

On 20 Dec 2017, at 10:36 pm, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you trying to access it on the same machine?

**Comment by tidusjar** [comment]
Check your firewall? The application is working fine and this has never been an issue so it must be something on your end

**Comment by mrumley02** [comment]
I’ll get back to you once I have.

Matthew Rumley

On 20 Dec 2017, at 10:38 pm, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Check your firewall? The application is working fine and this has never been an issue so it must be something on your end

**Comment by mrumley02** [comment]
After allowing it through the firewall I still can't get it to open in multiple browsers.

**Comment by mrumley02** [comment]
Ombi 2.x works

**Comment by tidusjar** [comment]
try changing the port to 3579

`Ombi.exe --host http://*:3579`

**Comment by mrumley02** [comment]
That appeared to work.
Thanks!!
