### ISSUE TITLE
User Management column sorting

### ISSUE THREAD

**Issue by PearsonFlyer** [tidusjar/Ombi#1804]
#### Ombi build Version:

V 3.0.2410

#### Update Branch:

Open Beta

#### Media Sever:

Plex and Kodi

#### Operating System:

Windows 10

#### Problem Description:

There used to be sortable columns on the User Management tab. It was nice to see which of my users had logged in most recently. Those don't appear to be there any more.

**Comment by tidusjar** [comment]
This has been done
