### ISSUE TITLE
Imported Emby Users Password

### ISSUE THREAD

**Issue by joelang1699** [tidusjar/Ombi#1807]
#### Ombi build Version:

3.0.2475 (todays latest)

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Operating System:

Linux Qnap

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Imported emby users with uppercase characters in passwords upon logging in generates "Incorrect username or password error"

No issue with all lower case passwords.

#### Reproduction Steps:

Assign password with uppercase character to imported emby account.

**Comment by tidusjar** [comment]
It's this a local emby user or a connect user?

Did this work fine before?

**Comment by joelang1699** [comment]
All connect users. 

I'm not sure if it worked before as I used Ombi local accounts previously.

**Comment by joelang1699** [comment]
Just tried out a few combinations to help things

Local Ombi user: Uppercase working
Local Emby user: Uppercase working

It seems to be Emby connect users.

**Comment by tidusjar** [comment]
I'll take a look a bit later, but all we do with emby connect users is call the emby connect API and pass the information up there...

Anything in your log file?

**Comment by joelang1699** [comment]
The only entry in the log file when trying to login as Connect user with uppercase password is...

[Error] StatusCode: Unauthorized, Reason: Unauthorized

**Comment by tidusjar** [comment]
Is it possible that the password is actually incorrect?

**Comment by tidusjar** [comment]
Cannot reproduce this, my test emby connect user has uppercase in the password and I can log in fine. 

Please can you try the latest version since 3.0.2475 is relatively old
