### ISSUE TITLE
So.. How about that ARM Core Build?

### ISSUE THREAD

**Issue by GregoryHlavac** [tidusjar/Ombi#1813]
`rtorrent@prism:~/Ombi$ uname -a
Linux prism 4.9.44-56 #1 SMP PREEMPT Thu Aug 24 10:38:35 UTC 2017 armv7l armv7l armv7l GNU/Linux
rtorrent@prism:~/Ombi$ dotnet Ombi.dll --host http://*:5001
Hello, welcome to Ombi
Valid options are:
Ombi 1.0.0
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;) 
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the 
                   server should listen for requests on any IP address or 
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be 
                   included with each URL. Supported formats vary between 
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.

We are running on 
/home/rtorrent/Ombi
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Schedules.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15
Hosting environment: Production
Content root path: /home/rtorrent/Ombi
Now listening on: http://[::]:5001
Application started. Press Ctrl+C to shut down.`

Just saying, it seems pretty possible to put it out there officially.

Admittedly did require a slight amount of hackery.
- Something up with ombi updater and how it fits into build and it not working in ubuntu-16.04-arm build.
- Swagger.xml not present
- Sqlite native library not being copied from nuget package (even tried adding the right nuget package manually and still nothing)
- Wwwroot missing dist.

But other than that, just finished the 'setup' process and its running now.

**Comment by tidusjar** [comment]
So... It's the holiday period at the moment so most of my time is spent with family at the moment
