### ISSUE TITLE
Cannot Start on Mac OSX

### ISSUE THREAD

**Issue by Mark7even** [tidusjar/Ombi#1814]
#### Ombi build Version:

V 3.0.2509

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Mac OSX El Capitan)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/Jon/Documents/Scripts/osx  3.0/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/Jon/Documents/Scripts/osx  3.0/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5


```

#### Problem Description:

Ombi will not run on Mac OSX El Capitan

#### Reproduction Steps:

I just try to start Ombi after extracting. Does it need High Sierra to run?

**Comment by tidusjar** [comment]
https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#macos

Needs 10.12 minimum
