### ISSUE TITLE
Ombi v3 FreeBSD support

### ISSUE THREAD

**Issue by wijagels** [tidusjar/Ombi#1818]
Currently there is no supported way to install on FreeBSD besides going down to the 2.x branch.  FreeBSD might not sound very important to support, but it's the OS for FreeNAS which has a strong Plex [community](https://forums.plex.tv/categories/freebsd).

I'm going to see if I can hack together a way to get it working in a FreeNAS jail.

**Comment by tidusjar** [comment]
duplicate #1564
