### ISSUE TITLE
Allow custom notifications

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#182]
Allow the users to specify the notification text etc.

**Comment by gold007eye** [comment]
Hopefully this would also allow for the use of HTML tags in Notifications as well similar to PlexPy

**Comment by tidusjar** [comment]
HTML tags? Like <movie> ? If so, that is the plan.

**Comment by gold007eye** [comment]
Like this.  This is from PushOver API page: https://pushover.net/api#html

HTML tags currently supported:

    <b>word</b> - display word in bold
    <i>word</i> - display word in italics
    <u>word</u> - display word underlined
    <font color="blue">word</font> - display word in blue text (most colors and hex codes permitted)
    <a href="http://example.com/">word</a> - display word as a tappable link to http://example.com/

**Comment by tidusjar** [comment]
Ah so allow you to specify your own markup. Sure, I could do this.
