### ISSUE TITLE
Unable to remove issues category

### ISSUE THREAD

**Issue by Tamburra** [tidusjar/Ombi#1823]
#### Ombi build Version:

V 3.0.2534

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.0.4

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I click on the delete button to remove an issues category and nothing happens.  Category is still there.  
This seems to happen only if there are already issues created with this category.  If I create a category and have no issues assigned to it, i am then able to delete the category.

#### Reproduction Steps:

Create an issues category.
Assign an issue to that category.
Trying to delete that category does not work.

**Comment by tidusjar** [comment]
I'm not seeing this issue, can you provide some logs? from browsers console and also the logs folder
