### ISSUE TITLE
Auto Update on Windows

### ISSUE THREAD

**Issue by rudyolph** [tidusjar/Ombi#1825]
#### Ombi build Version:

V 3.0.2534

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10 Creators Fall

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Auto Update Feature with service name specified. When an update is triggered the service is successfully stopped and a directory called TempUpdate is create and the latest zip appears to be extracted into it but then nothing else happens.  The files remain in the temp folder and the service is never restarted.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
There is already a bug open for the auto update #236

**Comment by tidusjar** [comment]
Nope not that one #1460

**Comment by goldenpipes** [comment]
lol #236 

Yeah i had the same issue today with the last build.  No idea whats happening.  It seems to start extracting then just stops and never re-starts the service.  Running OmbiUpdater.exe manually throws errors as well.  Im sure thats due to missing arguments?
