### ISSUE TITLE
Unable to delete imported plex user

### ISSUE THREAD

**Issue by rudyolph** [tidusjar/Ombi#1826]
#### Ombi build Version:

V 3.0.2534

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10 Fall Creators

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Trying to delete my test user that was imported from plex and after clicking delete and accepting the notifications that if the user is delete so are its requests nothing seems to happen. The user remains and nothing is showing in the logs as an issue.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
cannot reproduce this issue, is there anything in the browsers console?

**Comment by rudyolph** [comment]
I see this error:

VM575:1 DELETE https://rudyolph.com/requests/api/v1/Identity/dacb798d-b1c8-498b-b0af-41ff0f1fc6c7 500 (Internal Server Error)
vendor.js?v=-WHealbl…7YaGAaTJTgVqHq0Q8:1 ERROR 
e {headers: t, status: 500, statusText: "Internal Server Error", url: "https://rudyolph.com/requests/api/v1/Identity/dacb798d-b1c8-498b-b0af-41ff0f1fc6c7", ok: false, …}
error
:
error
:
"SQLite Error 19: 'FOREIGN KEY constraint failed'."
__proto__
:
Object
headers
:
t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
:
"Http failure response for https://rudyolph.com/requests/api/v1/Identity/dacb798d-b1c8-498b-b0af-41ff0f1fc6c7: 500 Internal Server Error"
name
:
"HttpErrorResponse"
ok
:
false
status
:
500
statusText
:
"Internal Server Error"
url
:
"https://rudyolph.com/requests/api/v1/Identity/dacb798d-b1c8-498b-b0af-41ff0f1fc6c7"
__proto__
:
Object
