### ISSUE TITLE
After landing page, I am logged in but nothing works

### ISSUE THREAD

**Issue by infamouswb** [tidusjar/Ombi#1828]
--->

#### Ombi build Version:

V 3.0.2534

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Cant get to page!

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

After forcing the landing page localhost/ombi/landingpage, and logging in, the it loads the page with the top bar, but you cant click on anything, its like all the links are broken, or something is wrong with authentication. I thought it was cache or something, but clearing the entire browser didn't do anything. I tried Chrome/Mozilla/Edge.

I also tried reapplying the update.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Login after landing page

**Comment by tidusjar** [comment]
See #1822

**Comment by infamouswb** [comment]
@tidusjar This does not effect Apache users. Everything was working fine till the update pushed last night. It must be something else, unless there is something to add in Apache, but it is not given in #1822 , Thanks for all the help and great work! Happy New Years!

**Comment by tidusjar** [comment]
@infamouswb it's the same concept. You need to rewrite a URL, please see the wiki.
