### ISSUE TITLE
[Feature Request] Enable SSL 

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#1833]
#### Ombi build Version:

V 3.x

#### Update Branch:

Open Beta

#### Media Server:

Not applicable

#### Media Server Version:

Not applicable

#### Operating System:

Windows, FreeBSD (Mono), Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Not applicable

#### Problem Description:

Would be nice to be able to have HTTPS, especially for port-forwarding applications. Perhaps also allow for custom certificates?

#### Reproduction Steps:

Not applicable

**Comment by tidusjar** [comment]
This is currently not on the cards. 

I would always recommend using some sort of reverse proxy to allow access externally, you would be able to setup SSL via the reverse proxy.
