### ISSUE TITLE
HTTPS/SSL broken in the latest versions?

### ISSUE THREAD

**Issue by hattenbachd** [tidusjar/Ombi#1834]
**Ombi build Version:**
V 3.0.2540

**Update Branch:**
DotNetCore

**Media Sever:**
Plex

**Media Server Version:**
1.11.0.4666

**Operating System:**
Ubuntu Server 16.04.3 LTS

**Problem Description:**
Since around v3.0.2504+ there is something wrong with either my Ombi or my HTTPS/SSL setup. I used your guide to setup Apache reverse proxy with SSL using websockets a long time ago and it works great. If I install the latest version 3.0.2540, I cannot access Ombi from outside my network using HTTPS/SSL. The "Loading..."-screen doesn't appear sometimes and I have come so far that I can login but then nothing works or the search forms aren't visible/doesn't work. The version I currently use is 3.0.2503 and I have no issues logging in from the outside using HTTPS/SSL on that version. Might be a bug somewhere or its just me and I might have to install everything fresh again. Thanks for a great application, keep up the good work and happy new year! :)

**Comment by tidusjar** [comment]
This is because in a later version we need to rewrite a url. I have examples for nginx but not for Apache, it's a pretty simple rewrite. 

https://github.com/tidusjar/Ombi/wiki/Nginx-Reverse-Proxy-examples-(Linux)

If you get the rewrite working in Apache please can you add it to the wiki for others?

Thanks.

**Comment by G4Zz0L1** [comment]
Same problem here, I'm trying to configure https://myhost/ombi/ to proxy through localhost:5000 on apache, but it seems to 404 everything (css and js as far as I see), and every rewrite i can make it's not working.

**Comment by bb12489** [comment]
I have this same issue as well, but with Nginx reverse proxy. I've tried the rewrite in the wiki, but it makes no difference. Just a blank black page when trying to access it from outside my network.

**Comment by tidusjar** [comment]
Hey guys, this working for almost everyone, the rewrite is pretty simple and it's been proven it works. What's in the wiki is a single example how to do this, I don't know enough about nginx or Apache to give you an accurate fix for your scenario. But I am using nginx and the rewrite in the wiki works for me

**Comment by SCRPD** [comment]
If you're using nginx & it's not working you must do this with the rewrite.

Before:
```
if ($http_referer ~* /ombi/) {
        rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
}
```

After:
```
if ($http_referer ~* /YOURBASEURL/) {
        rewrite ^/dist/([0-9\d*]).js /YOURBASEURL/dist/$1.js last;
}
```
