### ISSUE TITLE
Non-admin users cannot report issues

### ISSUE THREAD

**Issue by Collisionc** [tidusjar/Ombi#1835]
#### Ombi build Version:

3.0.2540

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

OS Architecture | X64
-- | --
OS Description | Linux 4.14.1-041401-generic #201711210430 SMP Tue Nov 21 09:32:36 UTC 2017

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
No applicable logs.
```

#### Problem Description:

The drop-down menu only shows up for the administrator, not normal users. 

#### Reproduction Steps:

Login as a non-power/admin user with issues enabled on server, the "Issues" tab shows up at the top, but when searching for movies/tv shows, the issues drop-down does not show up.

**Comment by tidusjar** [comment]
When searching it's only available on content that is available on the
server.

**Comment by Collisionc** [comment]
Yeah, I'm aware. It's not showing up even on content that is already on the server.

**Comment by Collisionc** [comment]
![image](https://user-images.githubusercontent.com/7837280/34469836-b4caee6a-eef4-11e7-99e8-ad0f80adbe9f.png)

**Comment by Collisionc** [comment]
6:07 PM] rob1998: @TidusJar Let me explain a bit more: the feature is enabled, an admin sees the issues "tab" and when searching for a movie/show it can report an issue, a non-admin user sees the issues "tab", but when searching for a movie/show it can't report an issue, there is no button
[6:07 PM] TidusJar: oh... @rob1998 , let me look
[6:09 PM] TidusJar: I see the issue @rob1998 give me a few mins

Seems to be the same problem someone else reported on discord on 12/28/2017

**Comment by rob1998** [comment]
That's my message 😊
And I can confirm that the issue is still unresolved..

**Comment by tidusjar** [comment]
Oh really? I thought I resolved it. My bad.
