### ISSUE TITLE
[Feature Request] Customization Email Templates and Homepage (-Title)

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [tidusjar/Ombi#1836]
With the introduction of automatic updating on Ombi v3, it seems to have become more crucial to have Ombi not override the Homepage HTML and Email Templates.

Either that, or requiring to disable/break the automatic update code.

Is there any chance that in a future update we can have actual support for editing Email Templates and some parts of the Homepage, like the title.
And by support, I am simply implying file/theme extending/customization which isn't going to get replaced by Ombi updates.

Happy new year!

**Comment by tidusjar** [comment]
Not sure what you mean by homepage html, you can apply your own CSS, see the customization settings page. 

Regarding the email templates, this is not currently on the priority list but maybe sometime in the future. 

Going to close this as currently not going to work on this for quite some time.
