### ISSUE TITLE
Welcome email custom template not applying

### ISSUE THREAD

**Issue by ksix** [tidusjar/Ombi#1841]
#### Ombi build Version:

V 3.0.2541

#### Update Branch:

Open Beta

#### Operating System:

Windows 10

#### Ombi Applicable Logs:

```
No logs were output as part of either:
- updating the custom welcome email template
- sending a welcome email
```

#### Problem Description:

The welcome emails are sent with the original template and don't correctly apply the custom template.

#### Reproduction Steps:

1. Apply the customisation to the welcome email template on the email notifications page.
2. Send a welcome email from the user management page.
3. Check email received by user to see how the email message was rendered. Message was rendered with the original template, not the customised template.

**Comment by tidusjar** [comment]
What happens if you restart Ombi, does the template then update?

**Comment by ksix** [comment]
Thanks for that, yeah it works after a restart.

**Comment by ValentinPasse** [comment]
Another problem concerning the template of the welcome email, I can not display the variables {UserName} and {Alias} in the email.

**Comment by macstainless** [comment]
I can confirm that I, too, am unable to use {UserName} and {Alias} in the welcome email either.

**Comment by tidusjar** [comment]
I don't think this is an issue anymore. Please comment if it is.
