### ISSUE TITLE
Custom Donation Link

### ISSUE THREAD

**Issue by sbcrumb** [tidusjar/Ombi#1843]
#### Ombi build Version:

V 3.0.2549

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

No Custom Donation link any longer. Will this be returning or is it gone forever? Lost of users use that to donate to me.

**Comment by tidusjar** [comment]
It will be coming back, it's not high priority at the moment, if you really want it I could enable mine and they could donate to me! Haha.

**Comment by jacc1234** [comment]
If this comes back I would like the option to send a percent of the donations to the devs. This might be too complex but it would be neat!

**Comment by tidusjar** [comment]
@jacc1234 wouldn't be possible since the custom donation link is just any link that the user puts in

**Comment by tidusjar** [comment]
Done
