### ISSUE TITLE
Change of language in the search

### ISSUE THREAD

**Issue by markettepigeon** [tidusjar/Ombi#1844]
--->

#### Ombi build Version:

V 3.0.2549

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Microsoft Serveur 2016 x64

#### Problem Description:

Hello,

First and foremost, I thank all the team who are really working on this project.
I managed to put everything in place and I had to put the version V3 3.0.2549 because the system of notification by mail towards the applicant did not work on the stable version.
The problem being settled why V3 I have another problem.
I would like to know if it is possible to adapt the language of the bookstore in French.
Because the request is obliged to search the series and films with the English language (for the demande).
Yet all OMBI interface is in French.
For example if I want to search for "Les Agents du SHIELD" I have to write "Agent of SHIELD" to find this series.

Thanks in advance guys

Sorry, i use Google translate for this post

**Comment by markettepigeon** [comment]
![agent](https://user-images.githubusercontent.com/34884922/34503112-0d5a96c0-f017-11e7-97cc-4b959111ddf4.PNG)
Is it also possible to change the language of the description to put it in French?
Thanks

**Comment by tidusjar** [comment]
Hello, this has been requested multiple times and is something I will be looking at doing in the future. Currently I've got a lot of other things to do, but this will be done at some point. 

Thanks
