### ISSUE TITLE
Placeholder Text for Issue Reporting

### ISSUE THREAD

**Issue by kmlucy** [tidusjar/Ombi#1849]
#### Ombi build Version:

V 3.0.2553

#### Update Branch:

DotNetCore

#### Operating System:

lsiodev/ombi-preview Docker

#### Problem Description:

I am looking into how to go about adding placeholder text into the subject and description fields for issue reporting. My users will often just report a subtitle error with the description of 'no subtitles' for an entire show, which is less than helpful.

I don't know enough to be able to fully integrate this into Ombi, but I was able to modify the HTML to show what I mean:

![capture](https://user-images.githubusercontent.com/13952475/34570105-d339123c-f138-11e7-8b01-a08e63741ffc.JPG)

And the relevant HTML:
```
<div class="ng-star-inserted" style="">

        <h3>Reporting an Issue for "Isle of Dogs"</h3>

        <!----><h4 class="ng-star-inserted">Issue type: Subtitles</h4>

        <div class="form-group">
            <label class="control-label" for="subject">Subject</label>
            <div>
                <input class="form-control form-control-custom ng-pristine ng-valid ng-touched" id="subject" name="subject" placeholder="Missing, Out of Sync, Wrong Content, etc." type="text">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label" for="description">Description</label>
            <div>
                <textarea class="form-control-custom form-control ng-pristine ng-valid ng-touched" placeholder="Please inlude as much detail as possible. For TV shows, make sure to list affected episodes in S##E## format." rows="5" type="text"></textarea>
            </div>
        </div>


        <button class="btn btn-primary-outline" type="button">Submit</button>
     </div>
```

The best case scenario would be different text for each issue type, set in the settings where you create the issue types. 

Also, I wasn't sure if this would be a better fit on FeatHub, but as it doesn't support images or code blocks (to the best of my knowledge), I thought I would post it here. If you want me to close it and move it over there, just let me know.

**Comment by tidusjar** [comment]
You are welcome to submit a PR?

This is the file: https://github.com/tidusjar/Ombi/blob/DotNetCore/src/Ombi/ClientApp/app/shared/issues-report.component.html

:)

**Comment by kmlucy** [comment]
I only know enough to directly modify the HTML, not enough to integrate it into the settings, so the text would have to be pretty generic. Is that something you would be interested in?

**Comment by tidusjar** [comment]
Actually I have not yet translated it, i'll add a placeholder when I translate that

**Comment by tidusjar** [comment]
I am not going to fix this as it will be replaced with V4
