### ISSUE TITLE
Requests.RequestStatus & Requests.RequestedDate

### ISSUE THREAD

**Issue by SCRPD** [tidusjar/Ombi#1851]
The Status and Date is not formatting correctly on my Requests page.
Not sure how to fix this myself.

![capture](https://user-images.githubusercontent.com/20602276/34591108-117b3b1a-f189-11e7-9536-1ae765fd9fd8.PNG)

#### Ombi build Version:

V 3.0.2564

#### Update Branch:

Open Beta.

#### Media Sever:

Plex.

#### Operating System:

Win10.

#### Problem Description:

Request Status & Request Date are not formatting correctly.

#### Reproduction Steps:

Visit requests page.

**Comment by tidusjar** [comment]
Clear cache ?

**Comment by carnivorouz** [comment]
Cleared cache and can confirm same behavior.  
![](https://user-images.githubusercontent.com/12376016/34618691-73a83c1c-f237-11e7-8137-40050921864f.png)

**Comment by SCRPD** [comment]
I tried clearing cache too.
Nothing changed.

**Comment by cesalo** [comment]
Same issue .. running last version in docker:

![image](https://user-images.githubusercontent.com/16859916/34621306-a2f32d72-f216-11e7-850e-45f943abf2b5.png)
