### ISSUE TITLE
Plex account import issues

### ISSUE THREAD

**Issue by daveguerra** [tidusjar/Ombi#1853]
#### Ombi build Version:

V 3.0.2564

#### Update Branch:

Open Beta

#### Media Sever:

Plex 
#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

1)  If you don't import your plex account as the admin user during initial setup, it can't be imported as a regular user account

2) 'Home users' account throw an error 
`fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
      User name '' is invalid, can only contain letters or digits.`

#### Reproduction Steps:

1) Fresh install, connect to plex.tv choose not to import account as admin.  Attempt to run the 'Import Plex Users'  the plex.tv owner account will not be created.

**Comment by tidusjar** [comment]
For 1. There is a checkbox to import the Plex Admin in the User Importer settings:
![image](https://user-images.githubusercontent.com/6642220/34626164-8a221028-f253-11e7-96e6-f8bf757e836b.png)

**Comment by daveguerra** [comment]
When I try to running that I get this in the console output

```info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Creating Plex user 
fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
      User name '' is invalid, can only contain letters or digits.
info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Creating Plex user 
fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
      User name '' is invalid, can only contain letters or digits.```

and the user account isn't actually created

**Comment by justinglock40** [comment]
I'm having that issue as well. Even when that checkbox does work. It doesn't allow you to login with your admin information afterwards

**Comment by tidusjar** [comment]
You need to wait for the importer to run or manually run before the account is created to log in

**Comment by justinglock40** [comment]
How long does that take when running from the initial install wizard?

**Comment by justinglock40** [comment]
<img width="953" alt="screenshot at jan 13 15-04-42" src="https://user-images.githubusercontent.com/23133649/34910056-4b8e2092-f873-11e7-868d-9df7f144a1b1.png">

???

**Comment by justinglock40** [comment]
Nevermind. It wasn't working because I had Plex to only authenicate with full e-mail address

**Comment by tidusjar** [comment]
So is everything ok?

**Comment by justinglock40** [comment]
Yep

**Comment by daveguerra** [comment]
I still can't import my plex account @tidusjar.  I don't know if this due to 1) not importing upon initial setup or b) having `Managed User` attached to my account

**Comment by justinglock40** [comment]
Make sure in your Plex account settings that you don’t have it set to “login with full email address only”

Delete the Omni.db and redo your initial setup should be golden then

**Comment by daveguerra** [comment]
Even on a brand new install I always get this.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/24866112/35027449-cba26934-fb1e-11e7-98b1-48a4f97d3335.png">


```info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Creating Plex user 
fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
      User name '' is invalid, can only contain letters or digits.
info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Creating Plex user 
fail: Ombi.Schedule.Jobs.Plex.PlexUserImporter[2004]
      User name '' is invalid, can only contain letters or digits.```
