### ISSUE TITLE
Can't send welcome email

### ISSUE THREAD

**Issue by ochbob** [tidusjar/Ombi#1856]
#### Ombi build Version:

3.0.2566 dotnetcore

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Media Server Version:

Plex/Emby

#### Operating System:

Debian 9

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
No Log for this

```

#### Problem Description:

Can't send welcome message, the box are blocked ? (see screenshot)

https://img15.hostingpics.net/pics/305961Capture.jpg

Any idea ? My SMTP settings are OK and i can send the test email (restart server already tried)

#### Reproduction Steps:

Can't send welcome message, the box are blocked ? (see screenshot)

https://img15.hostingpics.net/pics/305961Capture.jpg

Any idea ? My SMTP settings are OK and i can send the test email (restart server already tried)

**Comment by tidusjar** [comment]
You need to fill in the external URL under customization settings.

**Comment by ochbob** [comment]
Thank you, that's the trick :)

**Comment by jfairham1** [comment]
I too have this issue, what external URL is required? If I go to configuration - customization, the only URLS here are for the donation link?
