### ISSUE TITLE
Incorrect URL linked to "Check For Update" button?

### ISSUE THREAD

**Issue by SCRPD** [tidusjar/Ombi#1859]
![capture](https://user-images.githubusercontent.com/20602276/34627017-eeebb364-f22c-11e7-8af8-ab4b866f2572.PNG)

#### Ombi build Version:

V 3.0.2572

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Win10

#### Problem Description:

URL leads to a 403.

#### Reproduction Steps:

Click "Check For Update" button and view the cmd prompt for output

**Comment by tidusjar** [comment]
I am aware of this issue, it's due to my service being down because it's reached its limit.
