### ISSUE TITLE
https://webservice.fanart.tv requires API key

### ISSUE THREAD

**Issue by daveguerra** [tidusjar/Ombi#1861]
#### Ombi build Version:

V  3.0.2572 

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Ombi Logs
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/272094
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/77954


```
webservice.fanart.tv output 
{
    "status": "error",
    "error message": "API key is required"
}

<img width="634" alt="screen shot 2018-01-06 at 02 41 13" src="https://user-images.githubusercontent.com/24866112/34637842-9f92a2c2-f28c-11e7-9bfd-52ce29b9277e.png">

#### Problem Description:

fanart.tv requires an API but I don't see anywhere to configure a key in the UI

#### Reproduction Steps:

Go to TV Shows -> Suggestions -> Most Popular after a reset to force a search from fanart.tv

**Comment by tidusjar** [comment]
This is not an issue. 

I am using an API key, the not found errors is that some media doesn't have anything on fanart.
