### ISSUE TITLE
Issues Tab

### ISSUE THREAD

**Issue by filoor** [tidusjar/Ombi#1864]
Hi ,

Any idea when you gonna add the issue tab  to v3 really missing it

**Comment by tidusjar** [comment]
It's there. Enable it in the settings.

**Comment by filoor** [comment]
Sorry can't find it under which tab?

**Comment by tidusjar** [comment]
Settings > Configuration > Issues

**Comment by filoor** [comment]
![](https://i.imgur.com/wl3PmvG.png) sorry but don't see it

**Comment by tidusjar** [comment]
You are very behind. Please update
