### ISSUE TITLE
TV Shows allowing to be requested even if all aired shows are available

### ISSUE THREAD

**Issue by NumberedThought** [tidusjar/Ombi#1867]
#### Ombi build Version:

V 3.0.2593

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 4.13.0-041300-generic #201709031731 SMP Sun Sep 3 21:33:09 UTC 2017

#### Problem Description:

TV shows are allowed to be requested, even if all aired shows are available.  It looks as though Ombi is reading unaired episodes as "missing" and allows requesting of them.  It's confusing some users.
![2018-01-07 08_45_16-ombi](https://user-images.githubusercontent.com/25142109/34651595-2297b6da-f387-11e7-98f1-10b2690e6ca7.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
This is intended behaviour, unaired episodes are not available so users can request them. They may not be fulfilled yet, but all requests might not be fulfilled straight away.

**Comment by azgul** [comment]
@tidusjar You can't request an episode with the status `Processing Request`. The 'select' button is disabled and both S11E13 and S11E14 are monitored in Sonarr.

**Comment by tidusjar** [comment]
But it's not available fully available?

**Comment by azgul** [comment]
But given that the missing eps are already monitored by sonarr, then there is not work to be done by Ombi

**Comment by azgul** [comment]
I'd expect available to be shown when all aired episodes are attained

**Comment by tidusjar** [comment]
But then the status of the series would be flipping between available and not available potentially every day (depending on when the next episode airs). 

I'm not seeing a good reason to make this change yet.
