### ISSUE TITLE
NGINX not working with Ombi

### ISSUE THREAD

**Issue by justlookingaround12** [tidusjar/Ombi#1868]
#### Ombi build Version:

latest

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

ubuntu server LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Alright so i managed to set up my nginx configs for sonarr, radarr and plex. However i can't get it to work with Ombi! i followed the steps from the wiki but it just shows "404 Not Found". I have set the base url to "/request" from the Ombi settings. attached below is the code related to Ombi for the nginx config

    location /request/ {
            proxy_pass http://127.0.0.1:38088;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout  90;
            proxy_redirect http://127.0.0.1:38088 https://$host;
    }
    if ($http_referer ~* /request/) {
        rewrite ^/dist/([0-9\d*]).js /request/dist/$1.js last;
    }

#### Reproduction Steps:

I can access Ombi just fine by going to mydomain.com:38088 but if i go to mydomain.com/request/ it just shows 404 not found.

**Comment by tidusjar** [comment]
Did you put a base URL in ombi settings and then restart?

**Comment by justlookingaround12** [comment]
Yup restarted Ombi, reset nginx and then restarted the entire server as well

**Comment by justlookingaround12** [comment]
Anything wrong with my nginx config? Or any ideas as to what i should try?

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Nginx-and-Apache-Reverse-Proxy-examples-(Linux)

**Comment by justlookingaround12** [comment]
That's exactly what i followed/have, so it's just not supported?

**Comment by tidusjar** [comment]
It is supported as it works for many many people so it must be something to do with your setup. I suggest you ask on discord.

**Comment by pecigonzalo** [comment]
I would suggest reopening this, the support for reverse proxy + basepath is clearly sub-optimal, there issues everywhere, icons not loading etc.
Maybe it can take some ideas from sonarr implementation/support for this.

**Comment by tidusjar** [comment]
what? Please read the wiki. This issue is pretty old and things have moved on.

**Comment by pecigonzalo** [comment]
I know the issue is old, but it persists, the Wiki suggested configuration work but has issues. For example we should not need to setup:
```
proxy_redirect http://127.0.0.1:5000 https://$host;
```
or
```
 location /ombi {		
     return 301 $scheme://$host/ombi/;		
}
```
Also, some Wizard icons do not work during initial setup as they still point to the URL root instead of `/path`.
