### ISSUE TITLE
Movies/series stay on Processing

### ISSUE THREAD

**Issue by LickABrick** [tidusjar/Ombi#1869]
#### Ombi build Version:

3.0.2469

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

3.23.1

#### Operating System:

Debian 9 LXC Container 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Link to logfile [here](https://pastebin.com/zaM7uqmA)

#### Problem Description:

Movies/series stay on "Processing" after adding them. Already available movies/series are on processing as well.

I use Ombi in combination with Sonarr/Radarr and on both the "Get root folders / quality profiles" work and all tests are successful.

Some errors I get when hitting F12 in Chrome are:

GET http://172.16.10.131:5000/ombi/api/v1/Job/updateCached/ 500 (Internal Server Error)
ERROR e {headers: t, status: 500, statusText: "Internal Server Error", url: "http://172.16.10.131:5000/ombi/api/v1/Job/updateCached/", ok: false, …}
GET http://172.16.10.131:5000/ombi/api/v1/Job/updateCached/ 500 (Internal Server Error)

Not sure if this has anything to do with it though.

#### Reproduction Steps:

Request movie/series from Ombi. Movie/series gets downloaded and is completed downloading, Ombi stays on "Processing Request".

**Comment by tidusjar** [comment]
Please update, you are using a older version.

**Comment by LickABrick** [comment]
Thanks for your response, Ombi said it was up to date so I thought I had latest version.
It is working now which is great. Thanks!

**Comment by LickABrick** [comment]
Celebrated to soon. I've now downloaded a Movie and did not get a notification which says it is available.
In the requests tab it says "Processing", and when I manually search the movie as if I wanted to request it again it says "Available".

Series are also staying on "Processing"

Some new errors in my log (don't think they have anything to do with it.)

```
2018-01-08 13:53:13.671 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-01-08 13:53:13.690 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/0
2018-01-08 13:53:13.694 +00:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
2018-01-08 13:53:13.710 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/shows/0/episodes
2018-01-08 13:53:13.733 +00:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
2018-01-08 13:53:13.750 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/shows/0/episodes
2018-01-08 13:57:39.850 +00:00 [Error] StatusCode: Forbidden, Reason: Site Disabled, RequestUri: https://ombiservice.azurewebsites.net/api/update/DotNetCore

```

**Comment by tidusjar** [comment]
You need to wait for the Plex job to run.

**Comment by LickABrick** [comment]
@tidusjar It has been about a day since I updated and downloaded the movie, it is still on "Processing Request".

Manually running the cacher also doesn't fix anything.

**Comment by tidusjar** [comment]
Ok. Looks like we are not picking it up. In your log should be entries
about what episodes and movies we found. Can you please double check your
log when the job runs. Also make sure your settings are correct for
Plex/Emby

**Comment by LickABrick** [comment]
@tidusjar [this ](https://pastebin.com/eRxMVhzU)is the full log of today. When pressing the "Manually Run Cacher" button nothing new pops up in the log. Connectivity test to Plex is successful.

**Comment by tidusjar** [comment]
Is Plex enabled? Just want to make sure, some people miss that checkbox

**Comment by LickABrick** [comment]
@tidusjar Yup.

**Comment by LickABrick** [comment]
Got something new. I started the Ombi service by running ./Ombi instead of via systemctl. It does now show more info on the console about adding new shows (and they are now available within Ombi). It still does not show adding these series within the log though.

**Comment by LickABrick** [comment]
@tidusjar Tried downloading a new movies, once it worked and send me an email once it was completed. It also showed completed on the "Requests" page.

The second movie does only say completed when searching for the movie again. In the "Requests" page it is still sitting on processing without an email being sent saying it is available.

**Comment by tidusjar** [comment]
Is this still an issue?

**Comment by LickABrick** [comment]
@tidusjar Yes, requested some more movies. Movies got downloaded but no message email was sent + in requests tab it stays on processing. Still nothing new in log files.

**Comment by tidusjar** [comment]
What appears when you search that movie?

**Comment by LickABrick** [comment]
When I search as if I wanted to request them again it appears as available.

**Comment by devros42** [comment]
Having the same issue. Ombi v 3.0.2772 running in docker on my Unraid server.  If someone requests a movie and I approve, it will send the request to radarr as expected, but once the movie has been added, when I look at requests, it still shows as processing, but if I search for the movie as if I was searching for a new movie to add, it shows up as available.  Happy to help troubleshoot.

**Comment by tidusjar** [comment]
Is this an issue with the latest build?

**Comment by LickABrick** [comment]
I tried downloading some movies and they both are showing as available now. Also got an email from both of them.

**Comment by tidusjar** [comment]
Excellent

**Comment by devros42** [comment]
I updated to 3.0.2784, requested a new movie and am seeing the same thing.  Movie shows available, but the request is still processing.

**Comment by cduckett85** [comment]
@devros42 are you still having this issue with requests showing "Processing Request" even when they show as available during a search to add?

**Comment by devros42** [comment]
Working fine for me now
