### ISSUE TITLE
Win10 AutoUpdater doesn't progress past downloading

### ISSUE THREAD

**Issue by soulvoid86** [tidusjar/Ombi#1870]
#### Ombi build Version:

V 3.0.2459

#### Update Branch:

Open Beta

#### Media Sever:

Plex (Remote machine)

#### Media Server Version:

1.11.0.4666 (Remote machine)

#### Operating System:

Windows 10 Pro x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Logs do not update when the update is triggered. Even closing and reopening, Ombi doesn't write to the file.

#### Problem Description:

As the title says, the auto updater isn't working. Tried running as a service and just running the exe. No permissions errors. Gets to downloading update, the zip shows in the folder and is completely downloaded (watched network activity and the zip opens fine). Ombi simply sits there on downloading and won't trigger any other tasks until I close and reopen it. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by soulvoid86** [comment]
I should note I've never gotten the auto updater to work. I just copy the new files over and start it.

**Comment by Fiala06** [comment]
I thought the same thing. Updater isn't actually functioning in V3. It's still in development. 

To update just download the new zip and overwrite everything.

Here is the Update thread: https://github.com/tidusjar/Ombi/issues/1460

**Comment by tidusjar** [comment]
Duplicate
