### ISSUE TITLE
Unable to add user roles when creating a new user

### ISSUE THREAD

**Issue by channel2** [tidusjar/Ombi#1873]
#### Ombi build Version:

V 3.0.2607

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 1.9.7.4460

#### Operating System:

Ubuntu 16.04 LTS

#### Problem Description:

Options to add roles when creating a new user are not available/visible

#### Reproduction Steps:

New install of latest release. Try to create new user.

**Comment by tidusjar** [comment]
Tried clearing the cache? Logging out then back in?

**Comment by channel2** [comment]
I did try that, unfortunately it didn't change anything.

Reinstalled Ombi and everything looks good now. Not sure what was going on?
