### ISSUE TITLE
Not receiving request notifications

### ISSUE THREAD

**Issue by antigravity83** [tidusjar/Ombi#1875]
#### Ombi build Version:

3.0.2268

#### Update Branch:

PR

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

Ubuntu

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

https://drive.google.com/open?id=14ecdFEdOALtm-VcnafgCe4wIuVhy7Elt

#### Problem Description:

Not received email or pushover notifications when content is requested. 

#### Reproduction Steps:

I've confirmed that Email and Pushover notifications are working (tests work fine), however nothing is triggered when a request is processed. 

Emails are being sent for other actions (ie. password resets)

Have removed and re-entered both pushover and email settings. All tested ok. 

I've checked admin email addresses are also correct. 

Tried Pushover as a secondary option after emails weren't working- don't get request notifications to Pushover either. 

Ombi up-to-date

**Comment by tidusjar** [comment]
What notification type are not working?

**Comment by antigravity83** [comment]
When someone requests content, the admin doesn't receive any notification.

**Comment by tidusjar** [comment]
Is that notification enabled on the left hand side in the settings?

Does the user have auto approve, power user or admin permissions?

**Comment by antigravity83** [comment]
@tidusjar 

Yes, Notification is enabled on the left
- https://imgur.com/5g5iP6G (Pushover)
- https://imgur.com/a/RIrNr (Email)

The users only have the option to request movies/tv. No auto approve/power user or admin permissions
- https://imgur.com/nF0YKC9 (Every user is set up like this)

This is how the admin is set up
https://imgur.com/hhRf0rA

When testing both Email and Pushover notifications- the tests are received and work ok. 

But nothing is received when content is requested by users.

**Comment by RevelRob** [comment]
I'm also having this issue but with Discord. Tests work fine but no notifications are sent for anything else.

**Comment by tidusjar** [comment]
If 3.0.2268 is your version you are 400 builds behind.

3.0.2612 is currently the latest version

**Comment by antigravity83** [comment]
Thanks- when select Update within Ombi it says I'm on the latest version?

**Comment by tidusjar** [comment]
The update service that the older version uses is no longer available, I had to remove it.

**Comment by antigravity83** [comment]
Ah ok thanks. So update via terminal?

**Comment by tidusjar** [comment]
Not sure how you would do it because I am not aware of your setup, but to manually update just download the new build zip and extract and overwrite what was currently there.

**Comment by RevelRob** [comment]
I'm on 3.0.2612 and it's still not working for me.

**Comment by tidusjar** [comment]
@RevelRob Can you also confirm the stuff I asked the OP? since all you have told me so far is that it's not working.

**Comment by RevelRob** [comment]
Hey @tidusjar 
So... It's working now. I don't know why. I did nothing to change anything.
Thanks for the help though!

**Comment by Puyodead1** [comment]
Same issue here, Discord Notifications are not send when a user requests something.
![image](https://user-images.githubusercontent.com/14828766/51808092-6e56dc80-225d-11e9-9963-63e7a7a489fe.png)

**Comment by SmallwoodDR82** [comment]
> When someone requests content, the admin doesn't receive any notification.

I know this issue is "closed" but I'm having to same issue right now.  The reply above confuses me.

I am the admin and have to approve requests.  If the admin doesn't receive a notification how is it designed to let me know to go in and approve something?

Am I missing another setting?  I'm on 3.0.4256

**Comment by matthewtroup1983** [comment]
This issue is still an issue (maybe?)... I am not getting notifications however my notification test to discord works fine but requests do nothing

**Comment by epheterson** [comment]
Wow, old issue but still happening. I get notifications when things are finally available, but never when new requests are made. I do have auto-approve set up, but still want requests to be sent to me so I know what's going on.

**Comment by tidusjar** [comment]
Admins or power users will not trigger a notification. That’s by design

**Comment by epheterson** [comment]
> Admins or power users will not trigger a notification. That’s by design

Thanks for this info, I figured that might have been happening. I haven't had another user request since changing that setting, and imagine that'll go well.
