### ISSUE TITLE
Unable to launch on startup for Mac OS

### ISSUE THREAD

**Issue by jhenninger88** [tidusjar/Ombi#1876]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Mac OS 10.13.2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

(Not applicable)

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Unable to run Ombi at startup 

#### Reproduction Steps:

Unable to run Ombi at startup when following this guide. 

https://github.com/tidusjar/Ombi/wiki/Installing-on-macOS

Only way I can get Ombi to run is by opening terminal then type: CD /Applications/Ombi

Then pull the file in terminal.

**Comment by tidusjar** [comment]
What's the actual issue here. You are going to need to give me a lot more information for me to help you.
