### ISSUE TITLE
Scaling issues on smaller resolution phones

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1877]
#### Ombi build Version:

V 3.0.2610

#### Update Branch:

DotNetCore

#### Operating System:

Debian 8

#### Problem Description:

Smaller resolution screens don't scale well.

#### Reproduction Steps:

My mobile resolution is quite large and I can see Ombi fine in browsers but my friends who have smaller resolution phones complain about not being able to use Ombi while using a mobile device. Is there any room chance to make it more smaller-screen mobile friendly? 

My phone:
![image](https://user-images.githubusercontent.com/1329077/34808290-ca139c0e-f642-11e7-9d40-4801b04737a2.png)

My friend's phone:
![image](https://user-images.githubusercontent.com/1329077/34808308-e44f991a-f642-11e7-93de-84957e36563f.png)

May be related to https://github.com/tidusjar/Ombi/issues/1599 but on Android.
Friend can use a computer for the meantime so no rush.

**Comment by tidusjar** [comment]
What is the resolution of the phone with the issue?

**Comment by didyouexpectthat** [comment]
The phone resolution that has the problem is 720p. Mine is 4k.

**Comment by tidusjar** [comment]
What phone is it?

**Comment by didyouexpectthat** [comment]
Galaxy S7 Edge. From what I'm reading, this phone supported a wide range of resolutions until Samsung decided to lower it in Android Nougat to max 1080p. I don't know why my friend would run it on such a low resolution, and I'll inquire.

**Comment by didyouexpectthat** [comment]
I worked with my friend to change some settings on his phone and now it works better. If you want to support 720p, then go ahead, but I think we worked around it by changing the display settings on the phone. I'll close. Thanks!
