### ISSUE TITLE
Request button switches to "available" on tv shows instead of "pending"

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1878]
I still say it would be better to get rid of "pending approval" as well. Make everything uniform across movies and tv to just have these states for the button:
Request
Available
Pending
Blacklisted

Much easier to understand that way.

**Comment by tidusjar** [comment]
Why get rid of pending approval? 

This is when it has been requested but not yet approved by admin

**Comment by leram84** [comment]
ahh, sorry, i dont even remember what i was trying to do at the time, but i'v since completely changed the layout to work with the method ur using now. So ignore that part... still need the actual "request" button on tv items to switch to either "Pending Approval" or "Processing Request" the way they do for movies though

**Comment by tidusjar** [comment]
That's a lot more complicated than you think, the reason that does not currently happen is because the button shouldn't change to Pending Approval since there could be more episodes to request

**Comment by leram84** [comment]
actually been meaning to bring this up... in the case u just outlined, then, it should just stay as a "request" button, since ppl can still request more... but iv also been meaning to ask if ur still planning on supporting treating the whole show as 1 request. I personally want the entire show to be exactly like a movie... 1 thing. Dont even want the user to see the dropdown.

**Comment by tidusjar** [comment]
No i'm not planning to do that. The way i've architectured it is that requests are based on episodes. I had so many issues in V2 because it was not like this.

**Comment by leram84** [comment]
hey, you closed this, but are you not going to fix the "available" part? That parts just a bug no? Not the tag, but the actual "request" button. If i request all eps, the button immediately changes to say "available" so as not to allow you to click the drop down any more. shouldn't that bit just say "requested"? Anyway this doesn't affect LC any more, just thought ud want to know

**Comment by tidusjar** [comment]
My bad!
