### ISSUE TITLE
TV-Show Issue Reporting request

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#1880]
#### Ombi build Version:

V 3.0.2610
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Docker

#### Problem Description:

couldn't find something similar so not sure if this was already requested but for reporting issues within Ombi for TV-Shows it would very helpful to have a drill down of the season / episode having the issue. For example to report issues with subtitles or other specific episodes issues.
Thanks.

**Comment by tidusjar** [comment]
This will be added further down the line
