### ISSUE TITLE
Ombi v3 Dockerized Image

### ISSUE THREAD

**Issue by CoderKiwi** [tidusjar/Ombi#1881]
Is there a docker image to use for the newest v3 version? I’d like to run it on a Synology NAS. The GitHub install page doesn’t discuss this.

I found this image but it says “don’t use” https://hub.docker.com/r/lsiodev/ombi-preview/. Is this v3 and is it stable enough to use now? Last push was 6 days ago.

Maybe I’m being dumb and there’s a setting in the regular docker image that I can’t see? (If so, might want to include in the Wiki).

**Comment by cesalo** [comment]
I'm using it .. all good so far.

**Comment by CoderKiwi** [comment]
Cool, thanks.

If it’s stable, then maybe changing the description “In house testing version. Do not use!!” to something else makes sense. Not sure who built this image so not sure who to ask to do so.

**Comment by tidusjar** [comment]
That is the official docker, the reason why it states do not use is because it's still in preview.

**Comment by sho-87** [comment]
will we lose any settings if we run the lsiodev/ombi-preview docker now and then switch back over to linuxserver/ombi once that gets updated to v3?

**Comment by CoderKiwi** [comment]
V3 isn't backwards compatible with V2 so you'd be running two apps at once: Ombi and OmbiV3 using separate config files.

**Comment by sho-87** [comment]
but isnt ombi-preview already on v3? I was planning on running ombi-preview as my only instance of ombi, then when final release comes out just upgrade to the regular v3 docker. so no v2 anywhere

**Comment by CoderKiwi** [comment]
Oh I see what you mean.

I assume once it comes out of beta the official/master/stable release would be able to read the beta version's data. Otherwise it'd be silly.

@tidusjar

**Comment by tidusjar** [comment]
Yes the beta database will be compatible with the released version.

**Comment by jalmansor** [comment]
Seems like the code has been merged into master, but no "stable" releases of v3 posted to the release section, which is why the linuxserver.io docker image is still built with v2.2.1.

Any chance we can get this resolved?

**Comment by tidusjar** [comment]
Hey. Not yet since there is a pre release. I merged to master to remove V2. 

You can use the ombi preview dicker image.

**Comment by cesalo** [comment]
@tidusjar I'm using the Ombi-preview docker image and is currently stuck on V.3.0.2960. In the past it was updating automatically when I restarted the image but now is not doing it anymore at least in the last 30 days or so.
Is there a way to update Ombi-preview to the last version?
