### ISSUE TITLE
Invalid 'Base URL' breaks startup with an Unhandled Exception

### ISSUE THREAD

**Issue by azerial** [tidusjar/Ombi#1883]
#### Ombi build Version:

V 3.0.2613-PR

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 LTS

#### Problem Description:

**Impact**: Ombi will not start due to invalid setting

**Experienced**: Using the application configuration interface, i set the base URL to my domain's url with the port. Since there is no input validation on the field, there was no indication this what not okay. When i went to start up the server, i got the error message: Unhandled Exception: System.ArgumentException: The path in 'value' must start with '/'. 

This was fixed by loading the Ombi.db file and removing the value for BaseURL from the json of OmbiSettings in the GlobalSettings table. 

**Expected**: The base URL field should validate the entry to ensure it is correct. 

#### Reproduction Steps:

1. Install Ombi  
2. Navigate to <URL>:5000/Settings/Ombi  
3. Enter a URL into the "Base URL" field.  
4. Submit  
5. Restart the server and observe the terminal output.

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Due to the nature of the bug, the Ombi application had not started yet. This is the terminal output:

    :/opt/Ombi# ./Ombi
    Hello, welcome to Ombi
    Valid options are:
    Ombi 3.0.2613-PR
    Copyright (C) 2018 Ombi
    
      -h, --host   (Default: http://*:5000) Set to a semicolon-separated (;)
       list of URL prefixes to which the server should respond. For
       example, http://localhost:123. Use "*" to indicate that the
       server should listen for requests on any IP address or
       hostname using the specified port and protocol (for example,
       http://*:5000). The protocol (http:// or https://) must be
       included with each URL. Supported formats vary between
       servers.
    
    
    We are running on
    /opt/Ombi
    
    Unhandled Exception: System.ArgumentException: The path in 'value' must start with '/'.
    Parameter name: value
       at Microsoft.AspNetCore.Http.PathString..ctor(String value)
       at Ombi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IMemoryCache cache, IServiceProvider serviceProvider) in C:\projects\requestplex\src\Ombi\Startup.
    cs:line 149
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64
    Aborted

**Comment by tidusjar** [comment]
You can  no longer do this.
