### ISSUE TITLE
Forgotten password on plex.tv accounts

### ISSUE THREAD

**Issue by ChiPaulMichaels** [tidusjar/Ombi#1886]
#### Ombi build Version:

v 3.0.2607

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 3.31.1

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

For plex.tv accounts, if someone tries resetting their password or using the forgot password link, it currently sends them an email, let's them reset it (supposedly) and it doesn't do anything because it's actually using their plex.tv credentials. 
For accounts pulled/linked to plex.tv, if the user tries to reset the password, if it could let them know their password is the same as their plex.tv credentials, and to reset it on plex.tv, that'd be great and much less confusing.

**Comment by tidusjar** [comment]
I don't think it's a good idea to let them know it's a Plex account. That would be a security enumeration risk. I just think maybe we should send an email to the address stating they need to use their plex.tv credentials

**Comment by ChiPaulMichaels** [comment]
True. Didn't even think about that. I think your suggestion would be great. Currently the user gets an email with a link (tokenized) to reset their password. It resets a local password (I'm assuming) but that doesn't help.
If the email said to go to plex.tv to reset their password, that'd be MUCH better.

**Comment by tidusjar** [comment]
No problem! Makes sense to have !
