### ISSUE TITLE
[LC] Requests Page

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1887]
Just to get us started cause i know ur gonna want an issue, but don't worry about this until after we finish the search page stuff.

But right off the bat im gonna need a few things:

1) Can we get a "View in Plex" button for these items? No reason that should only exist in search imo.

2) TV section seems incomplete? It's missing a bunch of fields that movies have. (Request Status, Request Date, Requested By) though i guess ur putting some of that in the "view" drill down area, but it doesn't make sense to do so imo. would be better for that to be uniform w movies if possible. Ideally, the only thing that "view" button should display is the Seasons spreadsheet... everything else should be on the banner to begin w (like movies)

3) That view button (on tv items) needs an active state. Currently the css changes its background when in focus, but thats not really the right way to do a toggle button... should have an on off state instead.

4) I need id's on each button in the far right of each media item as well as an id for the wrapper (the one around ALL the buttons on the right). And please make sure to add the individual button id's at the highest level for said button... so for something like:

```
<div class="btn-group btn-split ng-star-inserted">
                            <button class="btn btn-sm btn-warning-outline" type="button"><i class="fa fa-plus"></i> Change Root Folder</button>
                            <button aria-expanded="false" aria-haspopup="true" class="btn btn-warning-outline dropdown-toggle" data-toggle="dropdown" type="button">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <!----><li class="ng-star-inserted"><a href="#">D:\Media\Movies\</a></li><li class="ng-star-inserted"><a href="#">E:\Media\Movies\</a></li><li class="ng-star-inserted"><a href="#">F:\Media\Stand-Up Comedy</a></li>
                            </ul>
                        </div>
```
make sure to add the id to that first div, and not the individual buttons.

Ill probably need more when i really get into it, but that should let me get started on the requests page :)

**Comment by goldenpipes** [comment]
[ITS HAPPENING](http://www.reactiongifs.com/r/2013/05/Ron-Paul_Its-Happening1.gif)

**Comment by tidusjar** [comment]
Regarding no. 2, that is not possible. 

Since you could have multiple requests for the same series by two different people with different statues, it wouldn't work.

**Comment by tidusjar** [comment]
1. would also take a lot more work, since all we are doing is loading stuff from the database on the requests page, the search page is quite dynamic and is doing a heck of a lot of processing in the backend so it's easier to do on the search

**Comment by leram84** [comment]
ok, but can u still move the existing stuff to the top layer (before you click the view button)... so you can see "requested by/approve/mark available/remove/deny/report issue" on the tile without needing to click "view" first? From a design standpoint, it will look much better than having a bunch of giant tiles with nothing status/release date on them, and none of that info is episode specific anyway, so no reason to force a drill down for that stuff

**Comment by tidusjar** [comment]
I don't think you understand. If two different users request episodes for the same series, that means there are two people requesting that TV show. There will be multiple requests under 1 TV show. 

Just request episodes 1 of something. Then the same series request episode 2. You have 2 requests.

**Comment by leram84** [comment]
ahhhh shit... ok, i get it now. yeah, this won't really work with what i was doing. ok, ill work on a different layout for the tv section.

I still really need some kind of status tag at the show level though. You have "available", and I dont see a problem with a "not requested" tag if nothing is requested right? and then can we add either a Pending Approval, Requested (if all eps are requested), or even just Pending/processing request tag (or maybe "Partial") for the other possible states? I dont really care what it is, just as long as there is that same status tag that everything else has... That should be the same weather ur in search or requests, so if, for example, you have a show w some requests, sure, the tags will exist per episode as it does now, but the show as a whole would have a "Pending" tag as well (the importance of this will make more sense if you look at my wip).

**Comment by tidusjar** [comment]
This has been fixed in develop
