### ISSUE TITLE
Requests show up in time order starting with the oldest

### ISSUE THREAD

**Issue by escservices** [tidusjar/Ombi#1889]
#### Ombi build Version:

V 3.0.2672

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Operating System:

Microsoft Windows 10.0.16299 x64

#### Problem Description:

All the requests my users put in show up as the oldest being the first one so they have to scroll to the very bottom to see what they recently requested.  Is there a way to change that?

**Comment by louis-lau** [comment]
I don't think there's a way to change it at the moment. I also vote for new to old.

**Comment by tidusjar** [comment]
I'll be adding sorting soon
