### ISSUE TITLE
How to Update to Ombi V3 Open Beta from Ombi V2 while Retaining Settings?

### ISSUE THREAD

**Issue by jeff15110168** [tidusjar/Ombi#1894]
#### Problem Description:

Have Ombi setup as a System Service in Windows using the guide below. How can I update Ombi to newest v3 Open Beta from my current installation (2.1694)? I tried stopping the service and overwriting the files in the Ombi installation folder but it won't load up when i restart the windows service.

https://www.htpcguides.com/install-plex-requests-net-windows-system-service/

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10 x64

**Comment by tidusjar** [comment]
You can't!

v3 is a new major version and a major rewrite, the databases are completly different.

**Comment by jeff15110168** [comment]
@tidusjar understood, so there is no way to import all old settings, users / history etc.?

**Comment by tidusjar** [comment]
Not currently.
