### ISSUE TITLE
Can't prevent searching for TV

### ISSUE THREAD

**Issue by harrv** [tidusjar/Ombi#1898]
#### Ombi build Version:

V 3.0.2677

#### Update Branch:

DotNetCore

#### Media Sever:

Emby Server

#### Media Server Version:

3.2.60.0

#### Operating System:

Microsoft Windows 10 Enterprise Version 10.0.16299 Build 16299

#### Problem Description:

I don't want to accept requests for TV shows from any of my users. I believe this is properly blocked since they don't have the RequestTv role, however, they can still search for TV shows and can issue the request before it is blocked. I would rather they didn't even see the TV tab on the search page. It may be confusing to them that they can search for TV, but then see an error when they request a show.

Version 2 had the ability to hide TV from the search page, but I can't use version 2 because it has a bug with caching Radarr content.

I would have entered this as a feature request on feathub, but that site has been down for quite a while (at least a week, but I'm not sure how long exactly).

I have solved this temporarily by directly editing wwwroot/dist/1.js and wwwroot/dist/2.js and removing the `<li>` element containing that tab, but I think I'll lose that edit at the next update.

#### Reproduction Steps:

1. Login to Ombi as a user who does not have the RequestTv role.

2. Navigate to the search tab (which is the default after logging in).

3. Note that the TV tab is available for searching.

Thanks for your help with this!

**Comment by louis-lau** [comment]
This feature will probably be added eventually, but in the meantime you can add this to your custom CSS to hide the tab:
```
#tvTabButton {
    display: none;
}
```

**Comment by harrv** [comment]
Thank you, Louis. That's a good workaround--better than mine because it should persist when updating. Much appreciated!

Unless you want to track feature requests as issues (since feathub.com is down), you could close this.

**Comment by MorningSleeper** [comment]
Anyway to do this in V4?
