### ISSUE TITLE
Can't save server settings: Error 500

### ISSUE THREAD

**Issue by lukezona** [tidusjar/Ombi#1905]
#### Ombi build Version:

V 3.0.2689

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm using nginx as reverse proxy for a subdomain: req.mydomain.ext (real domain is obscured for privacy reasons).

I can import my users and make requests but they aren't synced with my library.

In the Server settings page I log in with my account and select my server, then when I click on any button (Submit, Test connectivity, Load libraries) and in the browser console I see a 500 Error like this:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> Invalid URI: The hostname could not be parsed.
> Http failure response for http://req.mydomain.ext/api/v1/tester/plex: 500 Internal Server Error
```

When I click on "Load libraries" I also see an [object Object] notification in the top right corner

What can I do?

**Comment by tidusjar** [comment]
What's in the logs directory?

Does it happen in localhost without the proxy?

**Comment by tidusjar** [comment]
Sorry I missed this section: ` Invalid URI: The hostname could not be parsed.`

What's your hostname? or an example of how your hostname is structured.

**Comment by lukezona** [comment]
This is how my nginx conf file is configured:

```
upstream ombi-backend {
    server 127.0.0.1:5001;
    keepalive 64;
}

server {
    listen MyIP:80;
    server_name req.MyDOMAIN.ml;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://ombi-backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}

```

Of course my Ombi service point it to port 5001

Is that what you need?

**Comment by lukezona** [comment]
Ok I understand what you mean.
It was blank but there was a placeholder with "localhost" so i was pretty sure that it was loaded automatically.
I manually wrote localhost and now it's working.

It can be considered a little UX issue ;)

**Comment by tidusjar** [comment]
Ah! ok the placeholder! Cool, glad it's all fixed.

**Comment by DoctorNoonianSoong** [comment]
I experienced this issue just now as well. I think it should be far more visually distinctive when it's a placeholder vs actually filled in.
