### ISSUE TITLE
Cannot load remotely (nginx reverse proxy) after update

### ISSUE THREAD

**Issue by chrisbonilla95** [tidusjar/Ombi#1908]
#### Ombi build Version:

V 3.0.2689

#### Update Branch:

Open Beta (DotNetCore)

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

unRAID 6.4

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Don't think logs are relevant, but if you need them, ask. For now just see attached photo of errors shown in the console.

```
![ombibetaerror](https://user-images.githubusercontent.com/9061723/35082823-d452e5a6-fbe9-11e7-83c2-4d463543b4b5.PNG)

#### Problem Description:

After update I cannot access remotely, only locally. It shows "Loading..." screen and then just shows black screen. I find that sometimes after an update, there's a conflict with the database, so I just delete the DB file and redo initial setup (a bit annoying but I figure it's a beta issue so whatever). Looking at the console it seems it's trying to load a file and isn't using proper url; it's ignoring the base url. As for the other error in red, I have no idea.

#### Reproduction Steps:

1. Update to latest version
2. Delete db file
3. Do initial setup
4. Works fine locally
5. Try to open remotely (nginx reverse proxy) and it shows loading screen and then just black, with errors shown in console.

**Comment by JimboMonkey1234** [comment]
See the wiki page on [Reverse Proxy Examples](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples), you need a rewrite rule now.

**Comment by chrisbonilla95** [comment]
That did the trick, thank you!
