### ISSUE TITLE
Ombi Not Loading

### ISSUE THREAD

**Issue by kmlucy** [tidusjar/Ombi#1910]
#### Ombi build Version:

V 3.0.2731

#### Update Branch:

Open Beta

#### Operating System:

LSIO Dev Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Note: these are Chrome Console Logs, not Ombi Logs.
```

vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1 ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for e: ([object Object], ?, [object Object], [object Object], ?).
Error: Can't resolve all parameters for e: ([object Object], ?, [object Object], [object Object], ?).
    at U (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getDependenciesMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getTypeMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.getNonNormalizedDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.loadDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at t._loadModules (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at U (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getDependenciesMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getTypeMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.getNonNormalizedDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.loadDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at t._loadModules (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at O (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at O (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at t.invokeTask (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at Object.onInvokeTask (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.invokeTask (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at e.runTask (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at m (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at <anonymous>
Ot @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.handleError @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
next @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.object.r @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.__tryOrUnsub @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.next @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e._next @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.next @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.next @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.emit @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
(anonymous) @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.invoke @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.run @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.runOutsideAngular @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
onHandleError @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.handleError @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.runGuarded @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
n.microtaskDrainDone @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
m @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
Promise resolved (async)
f @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.scheduleTask @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
onScheduleTask @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
t.scheduleTask @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.scheduleTask @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
e.scheduleMicroTask @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
k @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
O @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
(anonymous) @ vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
window.webpackJsonp @ bootstrap a036b7a207ece732b8ca:21
(anonymous) @ 1.js:sourcemap:1
vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1 Uncaught (in promise) Error: Can't resolve all parameters for e: ([object Object], ?, [object Object], [object Object], ?).
    at U (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getDependenciesMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t._getTypeMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.getNonNormalizedDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at t.loadDirectiveMetadata (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1
    at Array.forEach (<anonymous>)
    at t._loadModules (vendor.js?v=0Z2xhj5otNjnkIkjbQX2dHN_AqIEUTByIklTmJf2EEM:1)

```

#### Problem Description:

Ombi isn't loading correctly. Whenever I click one of the tab at the top, nothing below the top bar and sometimes the page heading load. I see the above errors, sometimes with a 404 error for service_worker.js thrown in. 

#### Reproduction Steps:

I started noticing after I updated to the latest version this morning. I am running behind an Nginx reverse proxy with the rewrite rule specificed in the wiki in place. For completeness, here is my location block:

```
# Ombi
location /ombi {
        proxy_pass http://ombi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout  90;
        proxy_redirect http://ombi https://$host;
        }
if ($http_referer ~* /ombi) {
        rewrite ^/dist/([0-9\d*]).js /ombi/dist/$1.js last;
}

**Comment by tidusjar** [comment]
does it work locally?

**Comment by Migz93** [comment]
Hi,

Having the same issue. Nothing belowt he top bar seems to load. Also running behind nginx proxy, can confirm accessing it locally works.
Please let me know if theres anything i can provide to help, not an expert in debugging/grabbing logs though so not too sure how much help i can be.

**Comment by kmlucy** [comment]
My configuration does not currenly allow local access. I can reconfigure it to check tonight, but I suspect it will be the same as @Migz93.

**Comment by tidusjar** [comment]
@Migz93 Since it's working fine locally then it's an issue with your nginx setup. Please check your config: https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by Migz93** [comment]
@tidusjar following the example on that page did the trick, thank you very much, you're a star! I naivly assumed that as the only thing that changed was updating ombi that it may have been an issue with ombi itself, not that it was an issue with my nginx set up.

**Comment by cabagekiller** [comment]
I am have the same issue. Mine is , however, both locally and through the internet. Tried to reload it but have not attempted a total reinstall.

**Comment by kmlucy** [comment]
Okay, mine is working locally, but not through nginx. I modified my nginx config to be an exact match to the current wiki (I didn't realize it changed), but still am experiencing the same issue.

```
location /ombi {
        return 301 $scheme://$host/ombi/;
}

location /ombi/ {
        proxy_pass http://ombi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout  90;
        proxy_redirect http://ombi https://$host;
        }
if ($http_referer ~* /ombi/) {
        rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
}
```

Looking at my nginx logs, these lines look relevant:
```
192.168.1.1 - - [18/Jan/2018:18:58:49 -0500] "GET /dist/3.js HTTP/1.1" 301 178 "https://REDACTED/ombi/issues" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
192.168.1.1 - - [18/Jan/2018:18:58:51 -0500] "GET /dist/1.js.map HTTP/1.1" 404 957 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
192.168.1.1 - - [18/Jan/2018:18:58:54 -0500] "GET /dist/2.js.map HTTP/1.1" 404 957 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
192.168.1.1 - - [18/Jan/2018:19:02:24 -0500] "GET /service_worker.js HTTP/1.1" 404 958 "https://REDACTED/service_worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
```

From what I am seeing, it looks like the referrer is not being set correctly, so the rewrite policy is not taking effect. That results in the 404 errors on `/dist/1.js.map`, `/dist/2.js.map`, and `/service_worker.js`.

**Comment by tidusjar** [comment]
Hmmm, You tried in Incognito mode to make sure the browser is not caching anything?

I also do not think `/service_worker.js` is my code, are you running ombi through something like Org? 

Also you `proxy_redirect` is slightly different to the config (My understanding of nginx is pretty basic, so apologies if your way should be fine), in the wiki has set the loopback and port of ombi `http://127.0.0.1:5000 https://$host;`

**Comment by kmlucy** [comment]
Yeah, the difference is just that I have the IP and port set in an upstream server. It's the same thing, just in a different location in my file. 

The service worker could be for something else. I had though I hadn't gone to any of my other services since restarting nginx, but upstream robot or somthing else could have polled somthing and caused that error. 

I had tried previously with no difference, but I tried again this morning and it was working, so maybe it was some combination of my nginx config and browser cache.

**Comment by kmlucy** [comment]
Yeah, it looks good. I wanted to wait until I got to work to check on a second computer before I closed the issue. Thanks for the help!

**Comment by mudsloth** [comment]
I know this issue was closed, but I'm having the same problem and wasn't sure whether it warranted creating a new issue. Also, it's very clearly an nginx issue in my case so I didn't want to confuse things.

I can access Ombi without issue using a local IP, but through my reverse proxy it behaves exactly the same as this issue's problem description. I've tried an incognito browser with no success and have copied the default conf info straight from the wiki page, as well as a few different variations with no changes. I'm at a loss.

`#OMBIV3 CONTAINER
location /ombi {
auth_request /auth-user;
return 301 $scheme://$host/ombi/;
}
location /ombi/ {
auth_request /auth-user;
proxy_pass http://192.168.1.50:8083;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout  90;
proxy_redirect http://192.168.1.50:8083 https://$host;
}
if ($http_referer ~* /ombi/) {
rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
}`

@kmlucy did you ever have any further insight into the cause?
