### ISSUE TITLE
First start Wizzard Plex Login "System.Net.Http.Native DLL not Found"

### ISSUE THREAD

**Issue by STX2k** [tidusjar/Ombi#1911]
#### Ombi build Version:

V 3.0.2731

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.0.4666

#### Operating System:

Ubuntu 16.04 LTS (Fresh minimal Install)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

`2018-01-19 01:17:38.704 +01:00 [Debug] OK, signing into Plex
2018-01-19 01:17:38.706 +01:00 [Debug] This is our first time, good to go!
2018-01-19 01:17:38.713 +01:00 [Fatal] Error when trying to sign into Plex.tv
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.`

#### Problem Description:

If i want to login with my Plex.tv Account Data, Ombi doesnt Login. I Check the logs and found this error.

#### I have a FIX :)

Install: apt-get install libcurl4-openssl-dev

**Comment by tidusjar** [comment]
That's under the common errors section on the wiki
