### ISSUE TITLE
ombi.io redirects to wrong installer

### ISSUE THREAD

**Issue by Terebi42** [tidusjar/Ombi#1918]
http://www.ombi.io/

links to https://github.com/tidusjar/Ombi/releases/latest

which redirects to

https://github.com/tidusjar/Ombi/releases/tag/v2.2.1

but v2 is no longer supported (and I think is incompatible with the current version of Plex)

**Comment by Terebi42** [comment]
Should probably link to https://github.com/tidusjar/Ombi  where you at least get to choose between 2 and 3

**Comment by tidusjar** [comment]
Good point!
