### ISSUE TITLE
proxy_set_header connection "Upgrade" api/v1/token 400 error

### ISSUE THREAD

**Issue by delphiactual** [tidusjar/Ombi#1921]
#### Ombi build Version:

V 3.0.2679

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Operating System:

Ubuntu 16.04.3 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No errors in logs...

```

#### Problem Description:

Cannot login to Ombi

#### Reproduction Steps:

setting `proxy_set_header connection "Upgrade"` in the nginx config causes api/v1/token to return a 400 error in the web console.

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by delphiactual** [comment]
@PotatoQuality this command is required for other services that use nginx to work (i.e Emby) so closing this and pointing me to a reverse proxy example that does not meet my needs is unhelpful
