### ISSUE TITLE
MIME type error with reverse proxy

### ISSUE THREAD

**Issue by sho-87** [tidusjar/Ombi#1929]
#### Ombi build Version:

V 3.0.2772

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Media Server Version:

3.2.70.0

#### Operating System:

Docker container (ombi-preview)

#### Problem Description:

I'm trying to set up nginx reverse proxy to work with ombi. I saw another issue about this (https://github.com/tidusjar/Ombi/issues/1751) and done everything in the final comment there but it doesnt work. When I go to website.com/ombi I see the "Loading" text, it fades, then the progress bar at the top reaches the end and Im left with a blank page

Chrome dev tools shows the following errors:

```
Refused to execute script from 'https://www.website.com/dist/2.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

ERROR Error: Uncaught (in promise): Object: {"loadChunkError":true}
    at O (vendor.js:1)
    at O (vendor.js:1)
    at vendor.js:1
    at t.invokeTask (vendor.js:1)
    at Object.onInvokeTask (vendor.js:1)
    at t.invokeTask (vendor.js:1)
    at e.runTask (vendor.js:1)
    at m (vendor.js:1)
    at <anonymous>

Uncaught (in promise) Error: Loading chunk 2 failed.
    at HTMLScriptElement.c (main.js:1)
    at t.invoke (vendor.js:1)
    at e.runGuarded (vendor.js:1)
    at HTMLScriptElement.<anonymous> (vendor.js:1)
```
I used the same setup (below) for ombi v2 and it was working fine, not sure why the mime type issue is coming up in v3

Also, everything works fine when accessed using local ip:port (http://192.168.187.10:3579/ombi)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1. Set application URL to www.website.com
2. Change base url to /ombi
3. Add the following to nginx:

```
location /ombi {
        proxy_pass http://192.168.187.10:3579/ombi;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    } 
```

**Comment by tidusjar** [comment]
Please look at the reverse proxy examples on the wiki
