### ISSUE TITLE
Availability not updating

### ISSUE THREAD

**Issue by sfranke89** [tidusjar/Ombi#1930]
#### Ombi build Version:

V 3.0.2772

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.11.1.4730

#### Operating System:

Windows 10 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I have deleted content from my plex library and have deleted the content from my nas, however when i go to make a request for that content it is still showing as available in plex. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Correct, I have not added the behaviour to scan plex to see if stuff has been removed yet.
