### ISSUE TITLE
[Feature Request] Add ratings to suggestions

### ISSUE THREAD

**Issue by sinewave** [tidusjar/Ombi#1938]
Find myself using the suggestions a lot and it would be really awesome to see a movie/tv shows rating on the suggestions screen. (i.e. IMDB, tmdb, Rotten Tomato, etc..)

Thx 

#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Thanks, i need to take a look if the apis support this, i've added a task onto the project for this.

**Comment by bendschs** [comment]
ratings on the discovery page would be a great addition!
