### ISSUE TITLE
Unhandled Exception: System.FormatException: Unrecognized argument format when updating

### ISSUE THREAD

**Issue by hbooo** [tidusjar/Ombi#1939]
#### Ombi build Version:

V 3.0.2780
--

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Operating System:
Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Ombi 3.0.2780-DotNetCore
Copyright (C) 2018 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.
When Ombi Updater run in cmd I got this error : 

> We are running on
> 
> Unhandled Exception: System.FormatException: Unrecognized argument format: 'http://*:5000'.
>    at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 64

#### Reproduction Steps:

Let Ombi updater run in cmd

**Comment by tidusjar** [comment]
Please include more information e.g. the command you are actually using in cmd.

**Comment by hbooo** [comment]
I do nothing. It's Ombi that automatically launch the update, this is all I have in the cmd

**Comment by tidusjar** [comment]
You need to make sure the working directory is where Ombi is

**Comment by hbooo** [comment]
I think it's ok.

I tried both method : 
- Create a service with nsssm, updater stop the service but doesn't start it (nothing in event viewer)
- Create a .bat in ombi folder that contains only 

> Ombi.exe

Create a shortcut of this bat and add it in C:\Users\MYUSER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

Program is launched but failed when trying to update automatically

**Comment by tidusjar** [comment]
That is a known issue

**Comment by hbooo** [comment]
Is there a way to not update automatically? Currenty I need to check regularly if Ombi is still up as it will force close when it tries to update

**Comment by tidusjar** [comment]
Turn off the auto update in the settings. There is but depends on your OS, check the wiki

**Comment by hbooo** [comment]
thanks
