### ISSUE TITLE
Ombi not recognising available movie from Plex

### ISSUE THREAD

**Issue by rulles** [tidusjar/Ombi#1942]
#### Ombi build Version:

V 3.0.2823

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 1.10.1.4602 

#### Operating System:

CentOS Linux release 7.4.1708 (Core)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

2018-02-02 14:27:33.848 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/332331
2018-02-02 14:27:33.853 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/328599
2018-02-02 14:27:52.894 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/328599
2018-02-02 14:27:52.899 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/332331
2018-02-02 14:31:43.109 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/328599
2018-02-02 14:31:43.117 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/332331
2018-02-02 14:35:20.508 +00:00 [Debug] Hangfire Server is stopping...
2018-02-02 14:35:20.508 +00:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' stopped.
2018-02-02 14:35:20.509 +00:00 [Debug] Background process 'DelayedJobScheduler' stopped.
2018-02-02 14:35:20.509 +00:00 [Debug] Background process 'ServerWatchdog' stopped.
2018-02-02 14:35:20.509 +00:00 [Debug] Background process 'ServerHeartbeat' stopped.
2018-02-02 14:35:20.511 +00:00 [Debug] Background process 'RecurringJobScheduler' stopped.
2018-02-02 14:35:20.511 +00:00 [Debug] Background process 'Worker #025c2114' stopped.
2018-02-02 14:35:20.606 +00:00 [Debug] Background process 'BackgroundProcessingServer' stopped.
2018-02-02 14:35:20.606 +00:00 [Information] Hangfire Server stopped.
2018-02-02 14:35:28.087 +00:00 [Information] Start installing Hangfire SQL objects...
2018-02-02 14:35:28.201 +00:00 [Information] Hangfire SQL objects installed.
2018-02-02 14:35:28.252 +00:00 [Information] Starting Hangfire Server
2018-02-02 14:35:28.258 +00:00 [Information] Using job storage: 'SQLite Server: Schedules.db'
2018-02-02 14:35:28.258 +00:00 [Information] Using the following options for Hangfire Server:
2018-02-02 14:35:28.258 +00:00 [Information]     Worker count: 1
2018-02-02 14:35:28.258 +00:00 [Information]     Listening queues: 'default'
2018-02-02 14:35:28.259 +00:00 [Information]     Shutdown timeout: 1.00:00:00
2018-02-02 14:35:28.259 +00:00 [Information]     Schedule polling interval: 00:00:15
2018-02-02 14:35:28.276 +00:00 [Debug] Background process 'BackgroundProcessingServer' started.
2018-02-02 14:35:28.675 +00:00 [Debug] Background process 'ServerHeartbeat' started.
2018-02-02 14:35:28.675 +00:00 [Debug] Background process 'ServerWatchdog' started.
2018-02-02 14:35:28.677 +00:00 [Debug] Background process 'Hangfire.SQLite.ExpirationManager' started.
2018-02-02 14:35:28.679 +00:00 [Debug] Background process 'Worker #d5a2d091' started.
2018-02-02 14:35:28.682 +00:00 [Debug] Background process 'DelayedJobScheduler' started.
2018-02-02 14:35:28.691 +00:00 [Debug] Background process 'RecurringJobScheduler' started.
2018-02-02 14:35:28.693 +00:00 [Debug] Removing outdated records from the 'AggregatedCounter' table...
2018-02-02 14:35:28.722 +00:00 [Debug] Removing outdated records from the 'Job' table...
2018-02-02 14:35:29.777 +00:00 [Debug] Removing outdated records from the 'List' table...
2018-02-02 14:35:29.780 +00:00 [Debug] Removing outdated records from the 'Set' table...
2018-02-02 14:35:29.810 +00:00 [Debug] Removing outdated records from the 'Hash' table...

#### Problem Description:

I realized the jobs are not working.

I made a request for a movie, and later add that movie in plex, and almost two days later, the request not showed available yet.

The setup of jobs are in print:

![image](https://user-images.githubusercontent.com/14089574/35738619-49442ea8-0827-11e8-8ab1-592b08f2f80e.png)

#### Reproduction Steps:

Make some request, add it to plex and ombi not change that request to available.

**Comment by tidusjar** [comment]
Does it appear available in the search?

**Comment by rulles** [comment]
No, if i search that movie not appear available too.

**Comment by rulles** [comment]
I found some more log's who can help this problem.
[log_ombi.txt](https://github.com/tidusjar/Ombi/files/1690160/log_ombi.txt)

**Comment by tidusjar** [comment]
Does the movie Suburbicon show as available?

That log does help!

**Comment by rulles** [comment]
No, that is one of the movies already in plex server and don't show as available in requests and in search. And not send none notification...

**Comment by rulles** [comment]
Hello. I updated to last release but not resolve my issue. The movie in requests and in search not aapear available yet.
I update ombi more or less 5 hours ago, the job should be detected yet...

**Comment by tidusjar** [comment]
Please provide new logs?

**Comment by rulles** [comment]
Next monday, i provide more logs...

**Comment by tidusjar** [comment]
New build should fix it!

**Comment by rulles** [comment]
Hello,

I update Ombi to version 3.0.2849 and the movies already appear available in both sides (search and requests).

But i realised another two problems, The email notifications from issues is not working and the requests appear in total disorder. It´s is possible add some option to order by request date?Like from more recent request to the most older? 

Or maybe it's better open a new issue here on github?

**Comment by tidusjar** [comment]
Regarding ordering, that's planned. I've added a filter to get some feedback and next I'll be adding sorting. 

Regarding issues, please check your settings, make sure the issue notification template is enabled and also check your sent box and junk

**Comment by rulles** [comment]
Ok, for the ordering, i will wait for new releases.

About email notifications from issues, i already check all my folder, inbox, spam, trash, etc, and not receive nothing. And all email notifications templates are enabled.

Here the log from my last issue test:

Feb  5 11:31:14 requests systemd-logind: New session 879436 of user root.
Feb  5 11:31:38 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.NotificationService[4000]
Feb  5 11:31:38 requests Ombi: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Feb  5 11:31:38 requests Ombi: System.NullReferenceException: Object reference not set to an instance of an object.
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 15
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 159
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__34.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 145
Feb  5 11:31:38 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  5 11:31:38 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  5 11:31:38 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
Feb  5 11:31:38 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  5 11:31:38 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  5 11:31:38 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
Feb  5 11:31:38 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  5 11:31:38 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  5 11:31:38 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
Feb  5 11:31:38 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  5 11:31:38 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  5 11:31:38 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 47
Feb  5 11:31:38 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  5 11:31:38 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  5 11:31:38 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  5 11:31:38 requests Ombi: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82
Feb  5 11:31:53 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Api.Api[1000]
Feb  5 11:31:53 requests Ombi: StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/332331
Feb  5 11:31:53 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Api.Api[1000]
Feb  5 11:31:53 requests Ombi: StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/328599

**Comment by rulles** [comment]
Hello,

You need i make some more test or something like to help debug the problem? Or my last log help you enough?

**Comment by tidusjar** [comment]
Your last log helped, i just need to find some spare time to fix it.

**Comment by tidusjar** [comment]
Do you have an application URL set in the customization settings?

**Comment by rulles** [comment]
Yes, i have. 

![image](https://user-images.githubusercontent.com/14089574/35854543-85896b54-0b28-11e8-9ac8-947d51c26949.png)

Here the print.

But in Ombi Configuration i don´t have nothing.

![image](https://user-images.githubusercontent.com/14089574/35854589-a7d47e4c-0b28-11e8-853b-895955a7e6a7.png)

**Comment by tidusjar** [comment]
Can you try the latest version?

**Comment by rulles** [comment]
Hello,

I try last version (3.0.2855) and not receive mails yet.

Here the logs:
Feb  6 12:14:25 requests Ombi: Hosting environment: Production
Feb  6 12:14:25 requests Ombi: Content root path: /opt/OMBI
Feb  6 12:14:25 requests Ombi: Now listening on: http://[::]:80
Feb  6 12:14:25 requests Ombi: Application started. Press Ctrl+C to shut down.
Feb  6 12:15:53 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Controllers.SearchController[0]
Feb  6 12:15:53 requests Ombi: Searching : subu
Feb  6 12:15:54 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Feb  6 12:15:54 requests Ombi: Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult
Feb  6 12:15:54 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Controllers.SearchController[0]
Feb  6 12:15:54 requests Ombi: Searching : subur
Feb  6 12:15:54 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Feb  6 12:15:54 requests Ombi: Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult
Feb  6 12:15:56 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Api.Api[1000]
Feb  6 12:15:56 requests Ombi: StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/115626?api_key=b8eabaf5608b88d0298aa189dd90bf00
Feb  6 12:15:56 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Api.Api[1000]
Feb  6 12:15:56 requests Ombi: StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/397266?api_key=b8eabaf5608b88d0298aa189dd90bf00
Feb  6 12:16:20 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.NotificationService[4000]
Feb  6 12:16:20 requests Ombi: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Feb  6 12:16:21 requests Ombi: System.NullReferenceException: Object reference not set to an instance of an object.
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 16
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 159
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__34.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 145
Feb  6 12:16:21 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  6 12:16:21 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  6 12:16:21 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
Feb  6 12:16:21 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  6 12:16:21 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  6 12:16:21 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
Feb  6 12:16:21 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  6 12:16:21 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  6 12:16:21 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
Feb  6 12:16:21 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  6 12:16:21 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  6 12:16:21 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 47
Feb  6 12:16:21 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  6 12:16:21 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  6 12:16:21 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  6 12:16:21 requests Ombi: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82

**Comment by tidusjar** [comment]
I can see that there is an issue but cannot work out where. Can you please create me a local admin user on your ombi and then email me the ombi.db at tidusjar@gmail.com with the username and password for the user you created me.

**Comment by rulles** [comment]
Sorry but you really need my database?

I have some delicate information like email from my users, login to my plex server and SMTP credentials.

**Comment by tidusjar** [comment]
It would have been the quickest way for me to diagnose the information, you can easily remove that information.

Just take a backup of your database (`ombi.db`) and then remove that information in the OMBI UI.

If you still do not want to do this i'll add some more debug information around this specific area, but cannot promise that will help me identity the issue

**Comment by rulles** [comment]
Hello,

I try delete all the information i told you and all the requests and issues disappear.

But if you want, i send a DB without data to you check.

**Comment by tidusjar** [comment]
Ok I'll just have to add more logging at some point

**Comment by rulles** [comment]
OK,
I will wait for the new releases.

**Comment by rulles** [comment]
Just a little curiosity, how can i make a break line in email notifications?

I have something like this:
![image](https://user-images.githubusercontent.com/14089574/35877540-7cb76aea-0b6d-11e8-8edd-42074192e31e.png)

But not work, i already try <br> but not work too. In email, message appear all in single line.

**Comment by tidusjar** [comment]
It's a HTML body so use <br />

**Comment by tidusjar** [comment]
Regarding the notification issue see here: #1914
