### ISSUE TITLE
Medusa/SickRage adding TV shows defaults to IGNORE status

### ISSUE THREAD

**Issue by thisaintgonnahappen** [tidusjar/Ombi#1945]
#### Ombi build Version:

V 3.0.2827

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:
OSX

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Not sure where logs are located for Ombi (OSX install)

Here is Error log from Medusa:
2018-02-02 16:58:38 ERROR    TORNADO :: [c807f43] API :: 'argument 2 to map() must support iteration'
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 848, in run
    ep_list = show_obj.get_all_episodes(season=self.s)
  File "/home/**********/Medusa/Medusa/medusa/tv/series.py", line 613, in get_all_episodes
    sql_args.append(','.join(map(text_type, season)))
TypeError: argument 2 to map() must support iteration
```

#### Problem Description:

Unable to add TV Show Episodes, Seasons, or All episodes where status is anything but IGNORE. The show will add, and the quality can even be set, but the episode status does not set properly.

My apologies if this is a Medusa issue. This is my first day using Ombi and had been using PlexRequests. I was able to get PlexRequests to add shows with a status of 'Wanted' for all episodes (as you know there is not finer granularity with PlexRequests). 

I did work with the Medusa devs in the past on getting this same function to work due to an error with the API call (much like this error), ended up being a quick fix on their end. I do not even mind opening another issue on their queue, I just didn't know what error to put in to open it up (as I don't know what the API call looks like on your end).

#### Reproduction Steps:

Request TV Show (auto-approval), with any episode selection.

**Comment by thisaintgonnahappen** [comment]
After some digging around, I saw that the Medusa folks have been working on this section of code in the dev branch (which I was on): https://github.com/pymedusa/Medusa/issues/3661   

Once I returned to the Master branch I no longer saw the Medusa error, but I also couldn't get the episode status to change.

I also found the log, and had been getting this error:
2018-02-03 14:19:48.884 -06:00 [Debug] Added the show (tvdbid) 79349. The result is '"success"' : '"Dexter has been queued to be added"'
2018-02-03 14:20:11.024 -06:00 [Debug] Set the status to Wanted for season 1. The result is '"fatal"' : '"Medusa encountered an internal error! Please report to the Devs"'

Now that I've switched to the master branch, I only get the first message 'Added the show' but nothing regarding episode status.

**Comment by OmgImAlexis** [comment]
PING @p0psicles

**Comment by p0psicles** [comment]
We had to make some changes to make Medusa fully multi indexer compliant. Making it support also tvmaze and tmdb.

But because our api v1 has been deprecated, we do not allow it to be used multi indexer. So we also needed to make changes to it.

It could be some bugs popped up because of this. To be clear, apiv1 can still be used. But only for tvdb shows.

Ill look into it.

**Comment by tidusjar** [comment]
So now medusa has made a fix can someone confirm this works?

@p0psicles I'll take a look at migrating to the v2 api

**Comment by tidusjar** [comment]
Any update anyone?

**Comment by OmgImAlexis** [comment]
@tidusjar can you please reopen this as this may be an issue still.



CC: @sharkykh @p0psicles

**Comment by tidusjar** [comment]
Fixed in develop
