### ISSUE TITLE
Please ensure your base url start with a '/'

### ISSUE THREAD

**Issue by Bowsa2511** [tidusjar/Ombi#1947]
#### Ombi build Version: V.3.latest

V 3.0.XX

#### Update Branch: Open Beta

Open Beta

#### Media Sever: Plex

Plex/Emby

#### Operating System:

Ubuntu 16

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Fresh install of Ombi on Ubuntu via EC2 AWS Instance doesn't let me set the base url as anything. 

I have a public IP and DNS I can both access like so: Domain.com:5000 and XX.XXX.XX.XX:5000 which allows Ombi access, but I can't set the baseurl to anything.

I try /ombi and it simply says "Please ensure your base url start with a '/'...but it is starting with that?

I've been trying to set-up NGINX to reverse proxy to my Google Domain that's using CloudFlare DNS Name Servers. Going to my domain shows my NGINX page, but mydomain.com:5000 doesn't do anything. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Latest build currently building fixes this.
