### ISSUE TITLE
Emby episodes are incrrectly being treated as "available"

### ISSUE THREAD

**Issue by softworkz** [tidusjar/Ombi#1950]
#### Ombi build Version:

6227e11543943fc23d7ecb31768fbbc213dfe585 (current as of writing)

#### Update Branch:

DotNetCore

#### Media Sever:

Emby

#### Media Server Version:

N/A

#### Operating System:

N/A

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

No logs required

#### Problem Description:

The problem has been described here: https://github.com/tidusjar/Ombi/issues/1652#issuecomment-363270479 by @wikkixwikki

> Server: Emby
> Clients: Sonarr
> Example - TV Show1 has 10 seasons. I have all of Seasons 9 and all of currently available 10 as it is actively running, but no other seasons. When searching for TV Show1, I'm able to use the drop down to request specific episodes, but at that point, every episode is marked available rendering the requests useless. Even future unaired episodes.
> 
> Example 2 - Same scenario, but slightly different results. TV Show2 has 3 seasons. I have only season 3 in its entirety. From the initial search results screen, it is marked as available and I cannot interact with the drop down menu to requests seasons or individual episodes. It's completely locked out telling me it's available when it isn't.

#### Reproduction Steps:

Easiest repro:
- Find new series 
- Select only first episode to download
- Wait until episode has been downloaded, recognized by Emby and Ombi's cacher for Emby has run (or run manually)
- In ombi, find the series again
- Now **either** the series is marked as "Available" and you can't select select episodes, **or** you can expand to select individual episodes, but you will notice that most episodes are marked as "Available" despite being unavailable actually.

**Comment by softworkz** [comment]
Since this is a serious showstopper for me, I hunted this down and I think I found the bug in the code:

https://github.com/tidusjar/Ombi/blob/6227e11543943fc23d7ecb31768fbbc213dfe585/src/Ombi.Core/Rule/Rules/Search/EmbyAvailabilityRule.cs#L51

Here, you are comparing

`item.ProviderId.ToString() == searchResult.Id.ToString()`

But instead you should compare with x.Series.ProviderId (or similar)

**Comment by softworkz** [comment]
Sorry that I don't have a pull request, I've just been looking at the code on github..

**Comment by softworkz** [comment]
BTW, the comparisons that are done in PlexAvailabilityRule.cs seem to me a lot better... ;-)

**Comment by tidusjar** [comment]
Just commited a change, but I am unable to test it as I just got into work.

Can you please let me know how the change worked?

**Comment by softworkz** [comment]
I can confirm that it is fixed by your commit

Thank you very much for the lightning-fast action :-)

**Comment by tidusjar** [comment]
Excellent!!!!
