### ISSUE TITLE
Requested TV never appears as available

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#1951]
#### Ombi build Version:

V 3.0.2849

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.11.1.4760

#### Operating System:

Linux 3.10.0-693.2.2.el7.x86_64 

#### Problem Description:

After a user requests any TV it is not appearing as Available. 
![image](https://user-images.githubusercontent.com/2241731/35842829-c1d2a0ea-0ad2-11e8-80dc-c0def6706b1f.png)

It sees the show... 
```
Feb 05 23:57:26 Ombi[4788]: We already have show The Curse of Oak Island checking for new seasons
Feb 05 23:57:26 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
```
The EP cacher completes successfully... But it still shows as pending. 
```
Feb 05 23:57:31 Ombi[4788]: Starting EP Cacher
Feb 05 23:57:32 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Feb 05 23:57:32 Ombi[4788]: Total Epsiodes found for TV Shows = 7986
Feb 05 23:57:32 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Feb 05 23:57:32 Ombi[4788]: Processed 150 more episodes. Total Remaining 7836
Feb 05 23:57:32 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Feb 05 23:57:32 Ombi[4788]: Processed 150 more episodes. Total Remaining 7686
Feb 05 23:57:33 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Feb 05 23:57:33 Ombi[4788]: Processed 150 more episodes. Total Remaining 7536
Feb 05 23:57:33 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
Feb 05 23:57:33 Ombi[4788]: Processed 150 more episodes. Total Remaining 7386
Feb 05 23:57:33 Ombi[4788]: info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
```
I checked the DB and the episode is cached.
![image](https://user-images.githubusercontent.com/2241731/35842727-ecb9120e-0ad1-11e8-9bf1-fb68e7794cb6.png)

Edit: Same situation when requesting a tv show that is already available. It wont let you select it but it does not say available either. 
![image](https://user-images.githubusercontent.com/2241731/35845747-be1a1e60-0ae1-11e8-830b-974fa80439dd.png)

**Comment by tidusjar** [comment]
Please can you try the latest

**Comment by samwiseg00** [comment]
same problem... version 3.0.2855
![image](https://user-images.githubusercontent.com/2241731/35885953-87cda6f2-0b5d-11e8-9473-3669599dd0fa.png)

![image](https://user-images.githubusercontent.com/2241731/35886004-aa8d7cd0-0b5d-11e8-960e-3ffe987c2218.png)

**Comment by samwiseg00** [comment]
Sure
[ombi.log](https://github.com/tidusjar/Ombi/files/1700966/ombi.log)

**Comment by samwiseg00** [comment]
I ran the cacher manually a few more times and I did not see it try to recache the episodes... not sure if that is normal or not. 
[ombi2.log](https://github.com/tidusjar/Ombi/files/1701003/ombi2.log)

**Comment by tidusjar** [comment]
I notice you have ignored quite a few libraries, are you sure that you have all the correct libraries monitored in Ombi?

**Comment by samwiseg00** [comment]
Yep... I am sure... The other libraries are scripts or dupes of the content just in higher quality. The 2 that are selected contain all movies and TV shows
![image](https://user-images.githubusercontent.com/2241731/35950030-76633338-0c42-11e8-892a-7c08f8c9d4c2.png)

**Comment by samwiseg00** [comment]
Any updates on this one? Anything I can do to help debug?

**Comment by tidusjar** [comment]
I've looked into it but I cannot figure it out.

Are you able to create me a local user on your ombi and send me the database? (`ombi.db`) to me on Discord or at tidusjar@gmail.com

**Comment by samwiseg00** [comment]
> Are you able to create me a local user on your ombi and send me the database? (ombi.db) to me on Discord or at tidusjar@gmail.com
Yep... sent via email...

**Comment by suckerfish** [comment]
I have the same issue. 

I'm on 3.0.2903 
Docker + Unraid

TV and Movies both affected.

**Comment by bcpletcher** [comment]
This may be related to my issue as well, but only have tested with Movies since I dont add TV Shows as frequently [#1995](https://github.com/tidusjar/Ombi/issues/1995)

**Comment by tidusjar** [comment]
Can you guys try the latest version.

**Comment by samwiseg00** [comment]
Requested shows are now working... but when trying to request shows it still shows as pending... so one part is fixed but not the other.


![image](https://user-images.githubusercontent.com/2241731/36489448-e420ab38-16da-11e8-838f-6b1d4bd67ba6.png)

**Comment by tidusjar** [comment]
@samwiseg00 That's via searching right?

**Comment by tidusjar** [comment]
It looks like that Doctor Who in Plex has a MovieDbId but no TvDbId or ImdbId, So what are you Plex agents setup for, for TV Shows?

**Comment by samwiseg00** [comment]
yes it is via searching. I use the movie DB because if I use thetvdb the notifications from tautulli will not display the poster unless I use the movie db.
![image](https://user-images.githubusercontent.com/2241731/36490825-0ddce5d8-16de-11e8-9ca0-5fff112622d2.png)

**Comment by tidusjar** [comment]
Oh man this is awkward then.

TV Maze does not return TheMovieDb Id's for Tv Shows...So i'll never be able to match a TV Show if it's only got a MovieDBId.

**Comment by samwiseg00** [comment]
Hmm... that sucks...  is there a way that you could look it up and then store it?

**Comment by samwiseg00** [comment]
Looks like you can get the ID from the movieDB? https://developers.themoviedb.org/3/getting-started/external-ids

**Comment by tidusjar** [comment]
I do not use TheMovieDb to lookup TV Shows, I use TV Maze and it looks like they do not pass back TheMovieDbId.

I could look into adding more lookups but this would slow down the search.

I do not plan to switch from using TV Maze.

**Comment by samwiseg00** [comment]
I would be ok with a slower search... or if the lookup can be done when the cacher pulls the info from plex? that way the searcher can still be quick...

Another option would be to be able to chose which searcher to use?

**Comment by samwiseg00** [comment]
on a side note... digging through the logs on the latest version it looks like there was an issue with the cacher... 

```
Feb 21 10:39:11 server Ombi[7536]: Exception thrown when attempting to cache the Plex Content
Feb 21 10:39:11 server Ombi[7536]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite E
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of inner exception stack trace ---
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Ombi.Store.Repository.Repository`1.<AddRange>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Store\Repository\Repository.cs:line 41
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Ombi.Schedule.Jobs.Plex.PlexContentSync.<StartTheCache>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 298
Feb 21 10:39:11 server Ombi[7536]: --- End of stack trace from previous location where exception was thrown ---
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 21 10:39:11 server Ombi[7536]: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 21 10:39:11 server Ombi[7536]: at Ombi.Schedule.Jobs.Plex.PlexContentSync.<CacheContent>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 80
Feb 21 10:39:11 server Ombi[7536]: info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
```

**Comment by tidusjar** [comment]
I'll see what I can do. Regarding the above error I have a fix for it. I just need to test it tonight.

**Comment by samwiseg00** [comment]
> I'll see what I can do. Regarding the above error I have a fix for it. I just need to test it tonight.

Awesome!!! thanks again for all your hard work! All my users love this!

**Comment by bcsteeve** [comment]
I think this is still a problem.  

I've updated to 3.0.2907.

I've changed my jobs to run every 5 minutes

I added a request for TV and Sonarr handles it and SAB downloads it... but it just doesn't ever show up as available.  Furthermore... I got an email saying "user so-and-so made a request for" when I requested a MOVIE... but not for a TV show.  Similarly, I got a "such and such is available" for the MOVIE, but *not* for the TV show.

I'd love to show you logs... but I have been having trouble with log generation.  Once in awhile there will be a small, practically useless log file. But for the most part I can spent an hour in Ombi with not even a single log entry being generated.

**Comment by tidusjar** [comment]
What are your TV agents in Plex?

**Comment by bcsteeve** [comment]
I'm sure I left it on the default from years ago.  Admittedly, I've never understood the Agents or what difference they make.  Anyway, for TV I'm using  "TheTVDB"

**Comment by tidusjar** [comment]
Can you please provide some log files? I'd also suggest not running it every 5 minutes since depending on your lib size it could take longer.

**Comment by bcsteeve** [comment]
No, I can't provide log files.  They are rarely created.  Right now the folder is empty.

If five minutes isn't good... how about some guidance?  Every hour (default) is kind of horrible for testing.  Does five minutes or even less with with a very small test library?

**Comment by tidusjar** [comment]
What about the logs from stdout? You can manually run it from the Plex Settings page.

**Comment by bcsteeve** [comment]
Manually run "it"?

I have no idea about stdout logs.

**Comment by tidusjar** [comment]
Manually trigger the job that scans Plex, Check the console/terminal for errors

**Comment by daibakes** [comment]
Also experiencing this. Fresh install of Ombi, everything else is working as expected except requested TV show status remains at 'Processing Request'. Attempted to manually run cacher but had no effect.
