### ISSUE TITLE
Issues producing console errors and not submitting

### ISSUE THREAD

**Issue by didyouexpectthat** [tidusjar/Ombi#1957]
#### Ombi build Version:
3.0.2865
#### Update Branch:
DotNetCore
#### Media Sever:
Plex
#### Operating System:
Debian 8
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Nothing from /logs/ populates.
However, there are console messages in Chrome. I think this is the sufficient one...
```
18:40:40.351 vendor.js?v=Nsy5omll8U-FpuQHuhVg6TOQcLXmwG8RupcgcMzNR4k:1 ERROR e {headers: t, status: 500, statusText: "Internal Server Error", url: "https://plexrequests/api/v1/Issues/10/0/1", ok: false, …}error: error: "SQLite Error 1: 'no such column: x.UserReportedId'."__proto__: Objectheaders: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure response for https://plexrequests/api/v1/Issues/10/0/1: 500 Internal Server Error"name: "HttpErrorResponse"ok: falsestatus: 500statusText: "Internal Server Error"url: "https://plexrequests/api/v1/Issues/10/0/1"__proto__: Object
```
#### Problem Description:

SQLite Error 1: 'no such column: x.UserReportedId' when trying to go to the issues screen. Cannot submit issues, either.

#### Reproduction Steps:

Open /issues, see errors in console.
Go to episode, click report issue, click a category, type in subject and name, click submit, nothing.

**Comment by tidusjar** [comment]
It looks like you downloaded a non DotNetCore build at one stage and then when upgrading you would have had this issue due to the migrations already being run in. A few people have done something very similar. This sort of thing will be prevented when we finally push a stable release to github
