### ISSUE TITLE
Requests to some API endpoints throw 500 error

### ISSUE THREAD

**Issue by GLaDOSDan** [tidusjar/Ombi#1958]
#### Ombi build Version:

V 3.0.2671

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Debian 9.3

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2000]
      Exception thrown when attempting to cache the Plex Content
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an excnitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.


```

#### Problem Description:

Ombi starts up OK with no errors. When accessing Ombi I get the following error in my Chrome Developer tools:

```
GET http://plexrequests.int.dan-lab.net:5000/api/v1/Images/background/ 500 (Internal Server Error)
```

Attempting to log in always throws 'Invalid username / password' despite being correct. Requests to /api/v1/token also throw a 500 error upon attempting to log in.

After leaving Ombi to run for a while it attempts to fire up the Plex scheduled tasks and the above error output appears. No error output appears for the above 500 errors. 

#### Reproduction Steps:

Start Ombi, connect to Ombi in browser.

**Comment by GLaDOSDan** [comment]
Typically, as soon as I submitted this report I noticed that curl had uninstalled itself from my Ombi VM due to a change in my package handling process. 


Perhaps some debug output for these 500 errors would be useful - I only noticed the reference to curl in the error which appeared 15-20 minutes after starting Ombi when it tried to run the scheduled task. No error output appeared when the server was first started and was throwing 500s at me making this difficult to diagnose.

**Comment by tidusjar** [comment]
I understand that, but it's not really a good idea to test all these things at startup, since there are a few dependancies, basically on startup i'd need to issue a HTTP request and get the result, that could potentially slow down the startup process a lot.

I'm going to close this since I don't plan to make any changes like that.

**Comment by GLaDOSDan** [comment]
Hi @tidusjar  - thanks for your quick reply. My suggestion wasn't really towards testing at startup, but instead some form of output in the Ombi console when these server errors are thrown. Ombi was returning HTTP 500 errors but wasn't giving me any indication as to what was causing them. Is this something that could be looked at so that if a 500 is returned, some sort of output is provided to assist in debugging?

**Comment by tidusjar** [comment]
Maybe, but usually users would encounter this on the wizard and then look at the common errors section of the wiki. I think your scenario is a bit different.

I'll have a think so see how I can make this more apparent to the user.
