### ISSUE TITLE
Feature Requests: Support for multiple plex servers

### ISSUE THREAD

**Issue by stewie4684** [tidusjar/Ombi#196]
I know this is a probably a rare case but I run a separate plex server for my movies and tv shows. At the moment I have plex request set to check my tv shows server (well simply because tv shows are harder to mark off by hand). I was wondering if there are any plans to add support for multiple plex servers.
Thanks again for such a great program.

**Comment by tidusjar** [comment]
Someone else has also mentioned they use a separate plex server and split them up. It would be possible. We just need to plan it correctly really. Since this is the 2nd request we will implement this at some point.

**Comment by Codgedodger** [comment]
Pleaseeeee I need this! I run two different servers and really need this in plex request!

**Comment by CallMeRev** [comment]
has this been implemented yet ?

**Comment by tidusjar** [comment]
It's in v3
