### ISSUE TITLE
Email friendly name not used

### ISSUE THREAD

**Issue by CyberMew** [tidusjar/Ombi#1961]
#### Ombi build Version:

V 3.0.2878

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

latest plex pass

#### Operating System:

docker on unraid

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
i dont see the logs page in admin settings anymore, is this normal?
```
there's nothing to show
```

#### Problem Description:

I set email notification friendly name, but it doesn't appear and use my real name instead. I'm using a normal outlook account (smtp.office365.com)

#### Reproduction Steps:

getting issue status, issue comments tec.

**Comment by tidusjar** [comment]
Can you please explain?

**Comment by CyberMew** [comment]
I'm using my hotmail account to send emails. And my real name is being used instead of the sender name that we had configured in settings. Is this correct?

**Comment by tidusjar** [comment]
In the email I supply all the correct headers. Some email clients try and be a bit more clever by if they know the email then it does a lookup and will show the name, in your case your real name.
