### ISSUE TITLE
Released - actual DVD/BD dates, released/not released filter, "waiting for physical/digital release" label

### ISSUE THREAD

**Issue by enchained** [tidusjar/Ombi#1962]
I think that the filter was in v2, but is missing in v3. However, that's not the main issue. The main issue is that right now released status depends on the Theatrical date, which is totally irrelevant for the most of us. 

I saw the physical date request was marked as being "done" in v2, but couldn't find any corresponding commits, and don't see it working as I supposed it would in v2, and neither v3.

As far as I know, TMDB does provide Physical dates, and Radarr already uses that, so you could try that too.

For example, if I search for Thor: Ragnarok in v3, it says "Release Date 25/10/2017", which is a theatrical date. And Radarr shows "Available: 6. March 2018", which is the bluray date. Of course, in this case digital iTunes release came a month before that, and TMDB doesn't list that, but it doesn't really matter since there are granular setting in Radarr for when to start looking, and in Ombi I'm mostly worried that really released movies are totally mixing up with "says that released but actually will be released in 4 month" movies.

You could at least request additional release dates from TMDB, and take one with a physical/digital type, like it's done here: 
https://stackoverflow.com/questions/38162246/getting-release-dates-from-themoviedb-org-api-for-dvds
and then here:
https://github.com/Radarr/Radarr/blob/ca3d5c184e053aa6ef27fc7e516fe9d1f6969784/src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs#L178
And make an option of showing "No physical/digital release date available" or "Not released" if only the theatrical date is present.

Or you could even make some preference settings (just for the date and status shown on search and request lists):

* Type preference:
    * Prefer Physical
    * Prefer Digital
    * Prefer the earliest release

* Theatrical date display:
    * Show Theatrical if no Physical/Digital
    * Always show Theatrical
    * Always ignore Theatrical and show "Release date not available yet" if no Physical/Digital.

* Preferred region (region code, "US" by default):
    * Fallback to "US" if no entry on preferred version
    * Always ignore "US" and show "Release date not available yet" if nothing for the preferred region.

Then, based on the date, it could be shown to users either as (actually) "Released" on Date or "Waiting for physical/digital release" + on Date (if date is known).

**Comment by tidusjar** [comment]
Added the digital date, There doesn't seem to be many digital dates from TheMovieDb, mainly theatrical dates, but if we can find a digital we also show that.

I'm not going to do anything with the preferences as of yet since the user section needs some more work and a restructure.
