### ISSUE TITLE
Requests - Approval Library Selection

### ISSUE THREAD

**Issue by zeieri** [tidusjar/Ombi#1964]
#### Ombi build Version:

V 3.0.2878

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016 Standard

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When someone submits a request (TV or Movie), I cannot select which library to add it to upon approval:

![image](https://user-images.githubusercontent.com/36149372/36079137-fbe60b1e-0f3c-11e8-8e93-1598ae234eca.png)

As a non-administrative user, this is what is seen:

![image](https://user-images.githubusercontent.com/36149372/36079163-59b57e14-0f3d-11e8-9ee1-953f085d709d.png)

Is this functionality something to be enabled or is it non-existent?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1) Add TV Show or Movie using a non-administrative user account.
2) With an administrative account, go to approve the request. No selection for which library to add it to.

**Comment by zeieri** [comment]
Sorry, forgot a screenshot. This is what you see as an administrator when going to approve a user request:

![image](https://user-images.githubusercontent.com/36149372/36079229-480c9390-0f3e-11e8-847c-b8b99fefcd12.png)

**Comment by tidusjar** [comment]
There is a issue open for this to add this feature.
