### ISSUE TITLE
Cannot access Ombi via Nginx proxy.

### ISSUE THREAD

**Issue by Dhagon91** [tidusjar/Ombi#1965]
#### Ombi build Version:

V 3.0.2878

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Unraid 6.4.0

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

Hi.
First of all, sorry for creating yet another proxy-related issue, but I just don't feel like I can get any further on my own.

I've been trying to get Ombi v3 working on Nginx reverse proxy by mydomain.com/requests, but I never get further than loading a blank page.

I've done the rewrite from the wiki, and setup ombi base url (and made sure it matched nginx) like this:

![2018-02-13 14_12_47-requests](https://user-images.githubusercontent.com/36104729/36151597-1d177584-10c8-11e8-8fff-d9fa480b6144.png)
```
location /requests {		
     return 301 $scheme://$host/requests/;		
}
location /requests/ {
    proxy_pass http://192.168.0.40:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  90;
    proxy_redirect http://192.168.0.40:5000 https://$host;
}
if ($http_referer ~* /requests/) {
        rewrite ^/dist/(.*) $scheme://$host/requests/dist/$1 permanent;
}
```
Also tried clearing all cache, tried several browsers both with and without extensions/addons; Firefox, Chrome, Opera and Edge, and for some reason it loads properly only on Edge, which I don't really understand. Browser console in Chrome shows the following error messages:

![2018-02-13 14_44_00-requests](https://user-images.githubusercontent.com/36104729/36152825-9cc63b4a-10cc-11e8-9502-bb044ef4dff8.png)

Should also note that it does work locally using 192.168.0.40:5000. 

I've seen other similar issues in my search for a fix, but either their issue ended up being unrelated or fixed by doing the Nginx rewrite from the wiki. None of them have worked for me, so far, and now I'm stuck..

Let me know if you need more info

#### Reproduction Steps:

1. Access Ombi using mydomain.com/requests
2. Loads blank, dark ombi background. (IE Edge does load properly for some reason though)

**Comment by tidusjar** [comment]
Did you restart ombi? It also looks like your rewrite rule is not working since it's still trying to load /dist/1.js

**Comment by Dhagon91** [comment]
I had tried restarting several times, but it makes no difference. 
I've also been thinking it had something to do with the rewrite, but it must be working in some way, since I can access Ombi successfully on mydomain.com/requests using Microsoft Edge browser, right?

**Comment by tidusjar** [comment]
Can you jump onto discord and ask? Unfortunately my knowledge of reverse proxies is limited.
