### ISSUE TITLE
Ombi V3 Reverse proxy xampp issue

### ISSUE THREAD

**Issue by mochflix** [tidusjar/Ombi#1966]
#### Ombi build Version:

V 3.0.2878
--

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

doesn't matter... latest?

#### Operating System:

Server 2012R2

#### Problem Description:
Cannot acces Ombi behind reverse proxy.
I can access ombi just fine when going to my servers IP:5000 but when I try to connect using http://mydomain.nl/help it just shows a black screen..  ( I've set thebase url to "/help")

In my httpd-vhosts.conf ?I have the following line:

	<Location /help>
  
    ProxyPass http://10.1.130.3:5000/help
    ProxyPassReverse http://10.1.130.3:5000/help
    Require all granted
    </Location>

It worked fine untill this afternoon with Ombi V2.. The only thing I changed is the port.

I'm running Xampp on A server 2012R2 box if that's any help.

#### Reproduction Steps:

see above

**Comment by tidusjar** [comment]
Please read the wiki https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by mochflix** [comment]
I can read of course..

I tried the settings as suggested in the wiki, but sadly my apache won't even start when adding:
RewriteEngine on 
    RewriteRule ^/ombi$ https://mywebsite.com/ombi/ [R=301,L] 
    RewriteCond %{HTTP_REFERER} "https://mywebsite.com/ombi/" 
    RewriteCond %{REQUEST_URI} !^/ombi 
    RewriteRule ^(.*)$ /ombi$1 [R=301,L]

**Comment by mochflix** [comment]
I changed "ombi" to help of course and the domain name too

**Comment by mochflix** [comment]
@tidusjar 
![image](https://user-images.githubusercontent.com/17989026/36169319-3dd8ea3a-10fc-11e8-82a0-0207893d82a4.png)

**Comment by tidusjar** [comment]
Take a look at the Apache logs?

**Comment by mochflix** [comment]
sadly the logs won't give me a specific error. Probably due to the fact that apache can't start at all

**Comment by tidusjar** [comment]
There must be a reason why apache will not start, it must log it somewhere.

**Comment by mochflix** [comment]
I agree, but the error log shows nothing related to this..
It might be that I'm missing some prerequisite or something like that.

Or perhaps xampp won't let me format the vhosts in the described fashion

**Comment by tidusjar** [comment]
jump on Discord and someone with more skill than me might be able to help with apache

**Comment by mochflix** [comment]
I'll give that a shot tomorrow. Cheers mate
