### ISSUE TITLE
Long landing page message breaks mobile

### ISSUE THREAD

**Issue by Do-while-Bacon** [tidusjar/Ombi#1969]
#### Ombi build Version:

V 3.0.2878

#### Update Branch:

Open Beta

#### Operating System:

CentOS 7.4

#### Problem Description:

When using a notice message with the landing page feature enabled, if the message is too long (e.g. a paragraph), it will prevent mobile users from being able to press the "Continue" button. The button is pushed off the bottom of the screen and scrolling does _not_ work. The web application becomes unusable from mobile devices.

I like to use the landing page message to put a short disclaimer about what kinds of requests will be approved/rejected and why.

#### Reproduction Steps:

Enable the landing page, put in a paragraph of lorem ipsum as the notice message, and access the page from a cell phone web browser.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/issues/1599
