### ISSUE TITLE
Certain actions causing gpf in libcrypto.so.1.0.0 on debian stretch

### ISSUE THREAD

**Issue by StewGoin** [tidusjar/Ombi#1971]
#### Ombi build Version:

V 3.0.2886-DotNetCore

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux bartender 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

```
libcurl4-openssl-dev/stable,now 7.52.1-5+deb9u4 amd64 [installed]
libunwind8/stable,now 1.1-4.1 amd64 [installed]
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

relevant journalctl -f 
```
Feb 14 15:31:11 bartender kernel: traps: Ombi[19947] general protection ip:7f521c5e085d sp:7f51a0166c50 error:0
Feb 14 15:31:11 bartender kernel:  in libcrypto.so.1.0.0[7f521c46d000+233000]
Feb 14 15:31:11 bartender systemd[1]: ombi.service: Main process exited, code=killed, status=11/SEGV
Feb 14 15:31:11 bartender systemd[1]: ombi.service: Unit entered failed state.
Feb 14 15:31:11 bartender systemd[1]: ombi.service: Failed with result 'signal'.
Feb 14 15:31:16 bartender systemd[1]: ombi.service: Service hold-off time over, scheduling restart.
Feb 14 15:31:16 bartender systemd[1]: Stopped Ombi - PMS Requests System.
Feb 14 15:31:16 bartender systemd[1]: Started Ombi - PMS Requests System.
```

#### Problem Description:

Clicking certain links, opening initial login page, etc... trigger the fault and systemd then rekicks it back on -- it works "enough" to wait for the restart, then try to continue with most actions, but I can't figure out why it's faulting.

#### Reproduction Steps:
Any of the following make it happen:

- Open login page
- Click "Settings"
- Choose System->About from Settings
- Ask to "Check for Update"
- Configuration -> Customization
- Configuration -> User Importer

And some others.

**Comment by tidusjar** [comment]
Take a read of this https://github.com/dotnet/core/issues/649

**Comment by StewGoin** [comment]
That seems to have pinpointed it. I had:
```
libssl1.0.0/now 1.0.2l-1~bpo8+1 amd64 [installed,local]
```

Which was from the old backports (this server used to be Jessie before updating to Stretch) -- removed libssl1.0.0 and restarted Ombi and the error condition is no longer present.
