### ISSUE TITLE
changing ombi port number

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#1973]
#### Ombi build Version:

V 3.0.2888

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.3.4793

#### Operating System:

Windows Server 2012

#### Problem Description:

Just wondering if there's anyway to change the port on the new version. Thanks.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Startup-Parameters#--host

**Comment by chrisausbun** [comment]
Awesome, thanks. Just one question, which file in the v3 is the file I need to make this edit with?

Best Regards,

Christopher Ausbun
Chrisausbun@hotmail.com<mailto:Chrisausbun@hotmail.com>

On Feb 15, 2018, at 8:32 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1973<https://github.com/tidusjar/Ombi/issues/1973>.

**Comment by tidusjar** [comment]
You make no edits. It's a startup argument

**Comment by chrisausbun** [comment]
Ok, cool. Sorry to be a pain, but I'm using nssm for my instance so when I configure nssm, can I add that parameter when starting ombi? If so, would it be; nssm start ombi Default = "http://*:5000" ? I appreciate the assistance, I know you're probably trying to spend all your time on Ombi v3 instead of answering dumb questions all day. Which by the way, v3 looks amazing.

**Comment by tidusjar** [comment]
Not sure how nssm works but via command line you would run

`Ombi.exe --host http://*:3579`

**Comment by chrisausbun** [comment]
Awesome. That actually helps a lot. Thanks @tidusjar.

**Comment by gold007eye** [comment]
@tidusjar Not sure if this would be a related question.  I was able to get custom port working, but every time I try and use https:// it crashes the app.   It works fine if I don't use https://  any suggestions as I would prefer using SSL.
