### ISSUE TITLE
Use sub-directory in v3 package files

### ISSUE THREAD

**Issue by fryfrog** [tidusjar/Ombi#1974]
The `linux.tar.gz` file doesn't have a sub-directory inside, so when extracted the files just go where you currently are and it makes a hotness. I maintain the AUR package for ombi and it would be great if it could have an `./ombi/` directory inside it, or anything else. Looks like the previous version was `./Release/`, but I think `Ombi` or `ombi` would make more sense.

Thanks! :)

**Comment by tidusjar** [comment]
Just extract it into a ombi folder. 

I'm not going to change this since it will break the docker build, any auto updater scrips and the inbuilt auto updater for little benefit unless you can convince me otherwise! 😄

**Comment by fryfrog** [comment]
It is non-standard and will mildly frustrate anyone else making a package. Fixing it post-release will be harder than just doing the "right thing" now.

But it is easy to work around, just like the fact that your package files aren't versioned. ;)

**Comment by tidusjar** [comment]
Where are the standards for zipping up applications?

The packages are located in github, under the git release which has a git tag that defines the version.

**Comment by fryfrog** [comment]
Obviously there are no real "standards", but *most* zipped source or packages extract to a sub-directory. Surely you've noticed this in many other software.

And versioned files are only a little less common than extracting to a sub directory.

Anyway, it isn't really a big deal. If you don't want to "fix" it, working around this is easy (and already done for the AUR package) and life will go on. :)

At least we had a discussion about it. :)
