### ISSUE TITLE
Simplify reverse proxy

### ISSUE THREAD

**Issue by fryfrog** [tidusjar/Ombi#1976]
#### Ombi build Version:

V 3.0.2881

#### Media Sever:

N/A

#### Media Server Version:

N/A

#### Operating System:

Arch Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Reverse proxy is *much* more complicated than v2. Is it possible to have the ./dist/ directory obey url_base? Is there something else? In v2, my reverse proxy looked like...

```
  <Location /ombi>
    ProxyPass http://<ip here>:5000/ombi
    ProxyPassReverse http://<ip here>:5000/ombi
  </Location>
```

And worked great. As do most other apps that support a url_base.

But for v3, it looks like...

```
  <Location /ombi>
    ProxyPass http://<ip here>:5000/ombi connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse http://<ip here>:5000/ombi
  </Location>

  RewriteEngine on
  RewriteRule ^/ombi$ https://sub.domain.com/ombi/ [R=301,L]
  RewriteCond %{HTTP_REFERER} "https://sub.domain.com/ombi/"
  RewriteCond %{REQUEST_URI} !^/ombi
  RewriteRule ^(.*)$ /ombi$1 [R=301,L]
```
Which is much more complicated and honestly, I'm not good enough at reverse proxy to have figured this out on my own (thanks for [Reverse Proxy Examples](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples)) and I only *vaguely* understand what it is doing.

#### Reproduction Steps:

Try to setup an apache reverse proxy, maybe hoping to re-use your old setup.

**Comment by tidusjar** [comment]
https://github.com/angular/angular-cli/issues/4531

**Comment by fryfrog** [comment]
Glad it's on your radar. :)
