### ISSUE TITLE
Can't save at /Settings/Ombi if baseUrl is empty

### ISSUE THREAD

**Issue by erodewald** [tidusjar/Ombi#1980]
#### Ombi build Version:

V 3.0.2881

#### Update Branch:

Open Beta

#### Operating System:

```
OS Architecture | X64
OS Description | Linux 4.4.19-1-pve #1 SMP Wed Sep 14 14:33:50 CEST 2016
Process Architecture | X64
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A. There was a typescript error in the chrome console but sadly I missed it before refreshing. 

#### Problem Description:

From a fresh install, went to main settings (after the wizard) and tried to save the form after checking the box "Do not send Notifications if a User has the Auto Approve permission". The Base URL and API key fields were both empty. I noticed that submit did absolutely nothing, no network requests were made. 

I believe, from memory, there was an error in the console that would indicate that it couldn't check `baseUrl.Length`, so the validation to continue with submitting never passed. 

Oddly enough, I did not receive the message here:

```
public onSubmit(form: FormGroup) {
        if (form.invalid) {
            this.notificationService.error("Please check your entered values");
            return;
        }

     ...
```

Nor did I receive any notifications that might come from the rest of that method:
```
   const result = <IOmbiSettings>form.value;
        if(result.baseUrl.length > 0) {
            if(!result.baseUrl.startsWith("/")) {
                this.notificationService.error("Please ensure your base url starts with a '/'");
                return;
            }
        }

        this.settingsService.saveOmbi(form.value).subscribe(x => {
            if (x) {
                this.notificationService.success("Successfully saved Ombi settings");
            } else {
                this.notificationService.success("There was an error when saving the Ombi settings");
            }
        });
    }
```

#### Reproduction Steps:

Create a brand new instance, try to check a box on the Ombi settings and then hit save.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/issues/1954
