### ISSUE TITLE
Unable to update past 3.0.2564, log shows 'PlexEpisodeSync' over and over

### ISSUE THREAD

**Issue by guydavis** [tidusjar/Ombi#1981]
#### Ombi build Version:

V 3.0.2564  is shown in About | Version

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.11.3.4793

#### Operating System:

Ubuntu 16.04
[ombi.service.txt](https://github.com/tidusjar/Ombi/files/1730289/ombi.service.txt)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

[log-20180215.txt](https://github.com/tidusjar/Ombi/files/1730268/log-20180215.txt)
[ombi_systemd.log](https://github.com/tidusjar/Ombi/files/1730287/ombi_systemd.log)

#### Problem Description:

I seem unable to upgrade past this version. Watching the log, Obmi seems to be spinning in PlexEpisodeSync.  As well, the User Importer from Plex no longer seems to work as it did a month or so ago.  New invited Friends in Plex don't appear in Ombi.

I would perform clean install, however this setup of Ombi is behind a Nginx proxy with base URL (/ombi) needed which seems only configurable in the Settings area of the app first since this param doesn't seem to exist in a config file like other web apps.

#### Reproduction Steps:

 I can go to Settings | System | About and a see 'New Update Available'.    Clicking the link and then Update button says 'We've triggered the update job...' but I remain on this version.

**Comment by tidusjar** [comment]
Press the advanced button on the press settings and increase the episode batch size to 200

**Comment by guydavis** [comment]
Thanks for the quick response.  I increased the batch size to 200 as above and restarted the ombi server.   Good news is that a new Plex Friend was imported to Ombi over night so use importer is working.

Unfortunately, Ombi still seems to be unable to update to 3.0.2888, though it tries.  Log shows:

```
2018-02-16 07:36:52.888 -07:00 [Error] Failed to process the job '14400': an exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.<Update>d__18.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 220
```

ombi service runs as 'vpn' user and has full ownership of all files in /opt/ombi directory (and down recursively).  Any other tips for me to try?

[log-20180216.txt](https://github.com/tidusjar/Ombi/files/1731701/log-20180216.txt)
[ombi_systemd.log](https://github.com/tidusjar/Ombi/files/1731702/ombi_systemd.log)

**Comment by tidusjar** [comment]
Regarding the updater this is known issue. There is an open issue for this.

`ombi service runs as 'vpn' user and has full ownership of all files in /opt/ombi directory (and down recursively). Any other tips for me to try?` this is down to your setup
