### ISSUE TITLE
Use of HTTP basic auth on same domain breaks Ombi auth with Plex (OAuth)

### ISSUE THREAD

**Issue by chadmoone** [tidusjar/Ombi#1984]
#### Ombi build Version:

V 3.0.2888

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

_NA_

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

_[I can't find any `/logs/` dir in my container, and even if i set a volume there, nothing is written to it. If someone can help me locate the proper dir or fix my docker container, I will add logs here.]_

#### Problem Description:

I have set up multiple services on the same domain as Ombi, some of which use HTTP basic auth.  After setting up and authenticating to these endpoints, Ombi appears to be broken, with most requests returning `401` errors.

Upon further investigation, when I compare requests using the IP address vs the domain which has basic auth active, I notice that Ombi appears to be relying on the `Authorization` HTTP header. However, once a browser has authenticated with basic auth for the domain, that header is already populated with the basic auth info.  So what appears to happen is that the browser (at least Safari) prefers basic auth, and sends the cached basic auth token instead of the OAuth token that Ombi expects.

Is use of the `Authorization` header a requirement for Plex OAuth? Would it be possible to move this token to a cookie instead? This way it should remove the conflict.

#### Reproduction Steps:

Set up a domain with both Ombi (using Plex OAuth) and HTTP basic auth:

```nginx
server {
    listen       443;
    server_name  mydomain;

    ...

    location /other-location {
        auth_basic  "Please log in";
        auth_basic_user_file  /path-to/htpasswd;
    }

    location /ombi {
        return 301 $scheme://$host/ombi/;
    }

    location /ombi/ {
        proxy_pass 127.0.0.1:3579;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout  90;
        proxy_redirect http://127.0.0.1:3579 https://$host;
    }
    if ($http_referer ~* /ombi/) {
        rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
    }
```

Access and authenticate to `/other-location`, and then attempt to authenticate to Ombi.  It will seem to log you in to Ombi, but all API requests will fail with 401.

Restart browser (which _should_ clear basic auth cache), and authenticate to Ombi. It will work fine again until basic auth is used again.

**Comment by tidusjar** [comment]
Ombi has a requirement on the authorization header and that will not be changing.

**Comment by chadmoone** [comment]
Ok, thanks for confirming. If it's not going to be possible to change that, this issue should probably just be closed. I wasn't sure whether this was known.

It might be helpful to add some documentation somewhere about this incompatibility, as I know using a shared host with basic auth in some places is not an uncommon configuration for the type of media server setups which would be running Ombi.

**Comment by tidusjar** [comment]
No problem. I'll add it to the wiki

**Comment by palmfighter** [comment]
Hi,

not sure, but it seems to happen again. I guess due to Plex improving their login with 2FA now. I enabled 2FA and was not able to login to Ombi anymore. I disabled 2FA and now if I go through the NGINX proxy I see a lot of 401. When I go direct, no issues (url:port).

**Comment by tidusjar** [comment]
You are describing a completely different issue. 

If you have 2FA on your Plex account, you need to use the OAuth flow for Plex in ombi, or add the 2FA code at the end of your password for a manual login

**Comment by palmfighter** [comment]
Apologies, when disabling 2FA on my Plex account (as I couldn't login to Ombi (v3) anymore, I noticed that I didn't see the settings anymore and my browser showed (debug mode) a lot of 401 messages.
