### ISSUE TITLE
Does the pre release v3 support newsletter?

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#1988]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Just saw this update when I logged into my v2 admin console. Wanted to check if this version includes the newsletter as I know that was one of the limitations with v3 beta. Thanks in advance. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
It's not a limitation. It's possible but it's not there yet.

**Comment by goku-son** [comment]
@tidusjar understood. Thanks!
