### ISSUE TITLE
How to change default port?

### ISSUE THREAD

**Issue by ofurpesi** [tidusjar/Ombi#1991]
--->

#### Ombi build Version:

V 3.0.

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Server 2012 R2

```

Problem Description:

What file do i need to edit to change the default port? I know it´s startup parameter, but where do i change it?

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Startup-Parameters

It's a command line argument
