### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by luca336** [tidusjar/Ombi#1992]
#### Ombi build Version:

V 3.0.2881

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 8.1

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2881-master
Copyright (C) 2018 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.



We are running on
C:\Ombi2
info: Hangfire.SQLite.SQLiteStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.SQLite.SQLiteStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server
info: Hangfire.BackgroundJobServer[0]
      Using job storage: 'SQLite Server: Schedules.db'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer[0]
          Worker count: 1
info: Hangfire.BackgroundJobServer[0]
          Listening queues: 'default'
info: Hangfire.BackgroundJobServer[0]
          Shutdown timeout: 1.00:00:00
info: Hangfire.BackgroundJobServer[0]
          Schedule polling interval: 00:00:15
dbug: Hangfire.Server.BackgroundProcessingServer[0]
      Background process 'BackgroundProcessingServer' started.
dbug: Hangfire.Server.ServerHeartbeat[0]
      Background process 'ServerHeartbeat' started.
dbug: Hangfire.Server.ServerWatchdog[0]
      Background process 'ServerWatchdog' started.
dbug: Hangfire.SQLite.ExpirationManager[0]
      Background process 'Hangfire.SQLite.ExpirationManager' started.
dbug: Hangfire.Server.Worker[0]
      Background process 'Worker #7b9242b1' started.
dbug: Hangfire.Server.DelayedJobScheduler[0]
      Background process 'DelayedJobScheduler' started.
dbug: Hangfire.Server.RecurringJobScheduler[0]
      Background process 'RecurringJobScheduler' started.
dbug: Hangfire.SQLite.ExpirationManager[0]
      Removing outdated records from the 'AggregatedCounter' table...
dbug: Hangfire.SQLite.ExpirationManager[0]
      Removing outdated records from the 'Job' table...
dbug: Hangfire.SQLite.ExpirationManager[0]
      Removing outdated records from the 'List' table...
dbug: Hangfire.SQLite.ExpirationManager[0]
      Removing outdated records from the 'Set' table...
dbug: Hangfire.SQLite.ExpirationManager[0]
      Removing outdated records from the 'Hash' table...
Hosting environment: Production
Content root path: C:\Ombi2
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.


```

#### Problem Description:

Proxy not working correctly.

#### Reproduction Steps:

To Replicate :
Install Ombi
Change base url 
Application url
Change Preset theme to omBlur Alpha
Preset theme to add base url (<link rel="stylesheet" type="text/css" href="/baseurl/api/v1/Settings/ThemeContent?url=https://raw.githubusercontent.com/leram84/layer.Cake/master/ombi/css/omBlur.css">)
Restart Ombi
Cleaered browser cookies.

**Comment by luca336** [comment]
![proxy full](https://user-images.githubusercontent.com/24325668/36385372-b1d8fdae-1592-11e8-8d00-13e7894fa0d7.png)
![proxy](https://user-images.githubusercontent.com/24325668/36385373-b2040be8-1592-11e8-89ab-d0dc2740f35f.png)

**Comment by luca336** [comment]
For some reason they aren't showing.
![proxy full](https://user-images.githubusercontent.com/24325668/36385464-eb0b2d68-1592-11e8-82b7-23a0c4e53ed5.png)
![proxy](https://user-images.githubusercontent.com/24325668/36385465-eb29c318-1592-11e8-93c4-3256a41fcc50.png)
Using Ngnix as per the tutorial in the wiki.
Version 2 still works with the same settings.

all the items are as ombi2.

 location /ombi2 {		
     return scheme://$host/ombi2/;		
}
location /ombi2/ {
    proxy_pass http://192.168.x.x:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  90;
    proxy_redirect http://192.168.x.x:5000 https://$host;
}
if ($http_referer ~* /ombi2/) {
        rewrite ^/dist/(.*) $scheme://$host/ombi2/dist/ permanent;
}

**Comment by tidusjar** [comment]
Please in future be a bit more specific with your issue report, it doesn't actually state what is wrong.

Are you blocking `.json` files in your nginx config? Since if you Press 12 in the browser you will probably have red errors regarding the translation.json files

**Comment by tidusjar** [comment]
My question above: 

> Are you blocking .json files in your nginx config?

There is something else in your nginx config that is stopping this from working. I cannot assist with that since it's outside of my control.

**Comment by luca336** [comment]
Yes there is you can Close this issue. I overlooked it.
