### ISSUE TITLE
Can't Seem to get through the plex sign in screen

### ISSUE THREAD

**Issue by unixbird** [tidusjar/Ombi#1993]
#### Ombi build Version:

V 3.0

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.11

#### Operating System:

Debian 9

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

crit: Ombi.Controllers.External.PlexController[0]
      Error when trying to sign into Plex.tv
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Ombi.Api.OmbiHttpClient.<GetHandler>d__8.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 94
--- End of stack trace from previous location where exception was thrown ---

#### Problem Description:

Can't seem to get past the Request token page

#### Reproduction Steps:

Every single time I try and login with plex it throws these errors even after following installation steps properly

**Comment by tidusjar** [comment]
Have you done any of these: https://github.com/tidusjar/Ombi/wiki/Common-Errors

Seems to be an issue with maybe libwind8 ?

**Comment by unixbird** [comment]
Seems I had it in the system already when trying to install it to make sure

**Comment by unixbird** [comment]
Seems it works after just putting it into another VM with another build (Ubuntu 17.10 vs Debian 9).
