### ISSUE TITLE
Ombi v3.0.2881 keep config

### ISSUE THREAD

**Issue by hightechstl** [tidusjar/Ombi#1999]
#### Ombi build Version:

V 3.0.2881

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

i was prompted to update to 3.0.2881 however the old copy paste method appears to lose all of my config and makes me setup from scratch. is there any way to update to 3.0.2881 without starting over?

#### Reproduction Steps:

download windows.zip
stop ombi service
extract to ombi directory
start ombi service

**Comment by tidusjar** [comment]
That wouldn't happen unless you deleted the ombi.db file.

**Comment by jstrese** [comment]
What version are you migrating from? This might be related to issue #1589. If you're updating from V2 you won't have a V3 config file (Ombi.db). In previous versions the configuration was stored in Ombi.sqlite.

Going from V2 > V3 you will need to start from scratch according to tidusjar.
