### ISSUE TITLE
Translate request

### ISSUE THREAD

**Issue by marctrojan** [tidusjar/Ombi#2000]
Hello, I would like to know if the integration of the French translation of the applications was going to be done this year? Yes, there are problems with requests.
When I look for a movie or series in French I can not find it.
I have to write it in English to find them.

Thank you in advance,

Congratulations for everything else that is great, but makes it usable for the French.

**Comment by tidusjar** [comment]
Please follow the issue template.

But to answer your question. This can be done for movies but not yet for TV shows (TV Maze at this moment does not support other langauges).

**Comment by marctrojan** [comment]
Pour les films sa fonctionne depuis quand?
Cela fonctionne depuis une mise à jour récente de votre part?

**Comment by tidusjar** [comment]
I said it "can" be done for movies.

**Comment by marctrojan** [comment]
Sorry I do not speak very English ...
You think to do it in the year?

**Comment by tidusjar** [comment]
@marctrojan That's fine.

I do not give any time estimates since this is not my job, it's a side project. Other things in life can take priority.

**Comment by marctrojan** [comment]
Okay
Thank you :)
I will wait then
