### ISSUE TITLE
[feature request] Ability to assign plex app address

### ISSUE THREAD

**Issue by bcsteeve** [tidusjar/Ombi#2003]
Currently when the user sees their request is finished, there's a link to "View on Plex" (or something to that effect).  That link appears hardcoded to app.plex.tv.  I'm sure that's fine for most scenarios... but I'd *much* rather it point directly to myserver:32400/web/index.html

Possible?

**Comment by tidusjar** [comment]
It's possible. But please post on feathub since im not taking direct requests at the moment.

**Comment by bcsteeve** [comment]
Meanwhile... what I did was customize the email to tell the user to click the rest password link.   Not particularly elegant, but it gets the job done in the short term.
