### ISSUE TITLE
Reverse proxy not wanting to display Ombi fully

### ISSUE THREAD

**Issue by unixbird** [tidusjar/Ombi#2007]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 17.10 + Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Can't seem to get reverse proxy to fully display Ombi

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by unixbird** [comment]
Currently these are my tried options for the reverse proxy

location /ombi {
     return 301 $scheme://$host/ombi/;
}

location /ombi/ {
    proxy_pass http://192.168.1.164:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  36000s;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_redirect off;
    proxy_set_header Connection "";
    client_max_body_size 0;
  # proxy_redirect http://192.168.1.164:5000 https://$host;
}

if ($http_referer ~* /ombi/) {
        rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
}

With these nginx pushes the request but it is just stuck on "loading..." indefinitely. I have confirmed that Ombi is working through local connection in lan and i have set the base url to /ombi

**Comment by JCBird1012** [comment]
I can attest to this issue... It seems like ```2.js``` is 404'ing here, as Ombi isn't requesting it be grabbed from ```\"omni_url" + 2.js```.

**Comment by tidusjar** [comment]
Maybe post on Discord. My knowledge of reverse proxy configuration is limited.

**Comment by JCBird1012** [comment]
I'm not quite sure I follow why this issue was closed.

From my perspective, this appears to be a bug with Omni itself, not a misconfiguration of the reverse proxy. Unless you can explain to me why ```2.js``` isn't following the configured Base URL, this should continue to be treated as such. 

<img width="1679" alt="screen shot 2018-02-24 at 5 22 06 pm" src="https://user-images.githubusercontent.com/5911308/36635682-74c9ddd6-1987-11e8-9f81-d912f9271a50.png">
<img width="1271" alt="screen shot 2018-02-24 at 5 22 48 pm" src="https://user-images.githubusercontent.com/5911308/36635683-76223ab6-1987-11e8-8b62-c722b549a48d.png">

That's where the issue lies.

**Comment by tidusjar** [comment]
I am aware that `2.js` is not using the base url. I am fully aware of that. That's why there is a rewrite rule in the examples on how to deal with that. It's not a bug with Ombi.

**Comment by unixbird** [comment]
I used the rewrite however in the example configuration on the wiki and it seems to still give me the same issue where it loads and never ever displays.

**Comment by unixbird** [comment]
So i tried a couple of things and got a bit further with adding 
location ^~ /ombi/ {

        proxy_set_header Connection "upgrade";
	proxy_set_header Upgrade $http_upgrade;
with these changes i have actually gotten it to display the login page but it will not go further than that, just kinda sits there.

**Comment by unixbird** [comment]
Well after a complete reinstall (i saw some errors in terminal as i was trying this) it seems it now works, i commented out the added lines above and it seems to work anyway, here is my config as of right now


location /ombi {
     return 301 $scheme://$host/ombi/;
}

location ^~ /ombi/ {
    proxy_pass http://192.168.1.164:5000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  1d;
#   proxy_set_header Connection "upgrade";
 #  proxy_set_header Upgrade $http_upgrade;
  # proxy_buffering off;
    proxy_http_version 1.1;
    proxy_redirect http://192.168.1.164:5000 https://$host;
}

if ($http_referer ~* /ombi/) {
        rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
}


hopefully it doesnt randomly break.
