### ISSUE TITLE
ARM version - Failed to initialize CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by nephaste** [tidusjar/Ombi#2009]
#### Ombi build Version:

V 3.0.2881

#### Operating System:

Qnap ARMv7

[~/OmbiV3] # uname -a
Linux ts531P 4.2.8 #2 SMP Tue Feb 13 06:57:01 CST 2018 armv7l unknown

#### Problem Description:

Hi tidusjar

on Qnap ARm version refuse start

[~/OmbiV3] # ./Ombi --host http://*:8976
Failed to initialize CoreCLR, HRESULT: 0x80004005

no logs generated

**Comment by tidusjar** [comment]
Is this a new issue or has this never worked on v3?

**Comment by nephaste** [comment]
it never worked with v3   :(

**Comment by tidusjar** [comment]
Arm build is currently 32bit but I'm going to make it 64bit (aarch64) will that help?

**Comment by nephaste** [comment]
I actually used an Armv7l, which is 32bit... (TS-531P), and this has been done inside this NAS

 Qnap also have 64 bit aarch64... ( i am currently testing one)

Not sure what belong this Error code

**Comment by nephaste** [comment]
tried latest 3.0.3030.. same issue :(

are you sure this is running on all ARMV7 

cat /proc/cpu/cpu_info
Annapurna Labs Alpine AL314 Quad-core ARM Cortex-A15 CPU @ 1.40GHz

**Comment by nephaste** [comment]
Hi tidusjar

trying to resolve this issue by compiling source directly from source and getting an related to Cake.Core
(chrooted ARM Ubuntu 1404)
```
root@ts531P:/SRC/Ombi# ./build.sh
Downloading packages.config...
Downloading NuGet...
Feeds used:
  /root/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.27.1.
Adding package 'Cake.0.27.1' to folder '/SRC/Ombi/tools'
Added package 'Cake.0.27.1' to folder '/SRC/Ombi/tools'
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Error: The assembly 'Cake.Compression, Version=0.1.4.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

trying to pass --settings_skipverification=true

`root@ts531P:/SRC/Ombi# ./build.sh --settings_skipverification=true
Feeds used:
  /root/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /SRC/Ombi/tools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...

========================================
Clean
========================================
Executing task: Clean
Creating directory /SRC/Ombi/src/Ombi/bin/Release
Creating directory /SRC/Ombi/src/Ombi/wwwroot/dist
Finished executing task: Clean

========================================
SetVersionInfo
========================================
Executing task: SetVersionInfo

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: git2-baa87df
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () [0x00006] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
  at LibGit2Sharp.Core.NativeMethods..cctor () [0x00058] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
   --- End of inner exception stack trace ---
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject.Finalize () [0x00000] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: git2-baa87df
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () [0x00006] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
  at LibGit2Sharp.Core.NativeMethods..cctor () [0x00058] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
   --- End of inner exception stack trace ---
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject.Finalize () [0x00000] in <1a5aafd5a5444cd6a1420741ccbb6f8a>:0
An error occurred when executing task 'SetVersionInfo'.
Error: One or more errors occurred.
        GitVersion: Process returned an error (exit code 255).
`

have any clue ?
