### ISSUE TITLE
short swith not defined

### ISSUE THREAD

**Issue by dedo1911** [tidusjar/Ombi#2010]
#### Ombi build Version:
V 3.0.2881-master

#### Operating System:
Windows 10

#### Problem Description:
`System.FormatException: The short switch '-h' is not defined in the switch mappings.`

#### Reproduction Steps:
![image](https://user-images.githubusercontent.com/1364496/36642160-81816404-1a3b-11e8-927f-b10dc8366667.png)

**Comment by tidusjar** [comment]
This has been fixed in beta.
