### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by cinghialino** [tidusjar/Ombi#2011]
#### Ombi build Version:

latest docker image as today

#### Update Branch:

stable

#### Media Sever:

Plex

#### Media Server Version:

irrelevant

#### Operating System:

Synology NAS DSM 6.1

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I can't log in because every now and then any browser I try to use refuses to proceed once the submit button has been pressed.

**Comment by tidusjar** [comment]
Closing issue since there is not enough information for me to attempt to help.

Will reopen once the template has been filled out with sufficient information
