### ISSUE TITLE
htmlagilitypack.dll // flagged

### ISSUE THREAD

**Issue by thezoggy** [tidusjar/Ombi#2012]
just fyi, new install with latest symantec is showing:
![ombi](http://zoggy.net/SavUI_2018-02-26_13-22-01.png)

![ombi2](http://zoggy.net/SymCorpUI_2018-02-26_15-48-36.png)

**Comment by tidusjar** [comment]
Interesting, that's not even my library.

What version of ombi are you running?

**Comment by thezoggy** [comment]
its part of your windows download:
```D:\>unzip -l ombi-windows.zip | grep -i html
   109056  2018-02-13 13:40   HtmlAgilityPack.dll```

**Comment by thezoggy** [comment]
i think its just flagged because a lot of apps that get flagged as shady happen to have it.  anyways to note that your using v1.6.13, latest is v.1.7.0
https://www.nuget.org/packages/HtmlAgilityPack/
