### ISSUE TITLE
Custom donation link seems to cover menu

### ISSUE THREAD

**Issue by unixbird** [tidusjar/Ombi#2016]
#### Ombi build Version:

V 3.0.2881

#### Update Branch:

Stable

#### Media Sever:

N/A

#### Operating System:

Ubuntu 17.10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Seems that if you have a custom donation link that is too long then it takes up most of the menu and blocks the menu text 

https://imgur.com/4k0wgUV

**Comment by tidusjar** [comment]
There is a width limitation on the navigation bar. 

Not sure there is anything I can do about this. All I can suggest is a shorter message. Maybe use the tooltip

**Comment by unixbird** [comment]
I was hoping the custom link would be much like the current donation link that is on by default, I guess i could just swap them out
