### ISSUE TITLE
Quota no longer being recognised. All users denied requests.

### ISSUE THREAD

**Issue by DejaVu** [tidusjar/Ombi#2021]
#### Ombi build Version:

V 3.0.2935

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Docker Container

#### Operating System:

Diskstation Manager 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Not sure why to find these and there are not in 'Settings' when logged in as Admin

```

#### Problem Description:

Quota is not being honored. As Admin, I can request. All users cannot no matter what the Movie Request Limit is set to. I tried 0 (for no limit) and 10 for the limit, but users making me aware they have 'Exceeded the Maximum Quota".

#### Reproduction Steps:

Request a Movie/TV Show as a User and not an Admin.

**Comment by tidusjar** [comment]
If it's set to 0 they still cannot request?

Please upload the logs from the logs directory where ombi is installed

**Comment by DejaVu** [comment]
That is correct. Tried with 0 and still complains they are above Quota. 
I'll give it a go, but need to dig it out on Docker. :)

**Comment by DejaVu** [comment]
Whatever happened on the latest update repaired it. It's now working again. 

Case closed and thank you very much!

**Comment by tidusjar** [comment]
Didn't do anything! lol
