### ISSUE TITLE
Still not working after following reverse proxy wiki

### ISSUE THREAD

**Issue by darkstarcrash** [tidusjar/Ombi#2026]
#### Ombi build Version:

V 3.0.2947

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System: 

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I followed the reverse proxy wiki for apache but I still only see a grey screen that says loading and I can only access by going to http://IPADRESS:5000/ombi

This is my config file with subdomain and domain replaced with actual

```
<Location /ombi>
Allow from 0.0.0.0
ProxyPass "http://localhost:5000/ombi" connectiontimeout=5 timeout=30 keepalive=on 
ProxyPassReverse "http://localhost:5000/ombi"
</Location>
RewriteEngine on
RewriteEngine on
RewriteRule ^/ombi$ https://subdomain.domain.com/ombi/ [R=301,L]
RewriteCond %{HTTP_REFERER} "https://subdomain.domain.com/ombi/"
RewriteCond %{REQUEST_URI} !^/ombi
RewriteRule ^(.*)$ /ombi$1 [R=301,L]
```

#### Reproduction Steps:

I have cleared cache, restarted apache and ombi, and restarted server.

**Comment by tidusjar** [comment]
Whats the errors in your browser? can you post a screenshot?

**Comment by darkstarcrash** [comment]
![error](https://user-images.githubusercontent.com/36116801/36924379-5a48c666-1e3c-11e8-8ab7-0297f505e261.png)

This is the error I'm seeing

**Comment by tidusjar** [comment]
your rewrite rule is not working

**Comment by darkstarcrash** [comment]
I went back down to version 3.0.2328 and it worked fine. There must be something in the newer versions causing this.

**Comment by tidusjar** [comment]
Yes there is a new requirement to rewrite a URL like in the example of the proxy page.
