### ISSUE TITLE
Help with Nginx config for subdomain v3.x SSL

### ISSUE THREAD

**Issue by m1lkman** [tidusjar/Ombi#2028]
#### Ombi build Version:

V 3.0.2948

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.12.0.4829

#### Operating System:

Ubuntu 16.04.3 lts

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```



```

#### Problem Description: Just says Loading... when I attempt to access the subdomain ombi.server.com. I have no problem getting to the server.com:5000. Any help would be greatly appreciated. I have no issue with Ombi 2.x.

Here's my current proxy config

```
server {

    server_name ombi.server.com;

#        location / {
#            return 301 $scheme://$host/;
#        }

        location / {
            proxy_pass http://127.0.0.1:5000;
            proxy_max_temp_file_size 0;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout  90;
            proxy_redirect http://127.0.0.1:5000 https://$host;
        }

        if ($http_referer ~* /) {
            rewrite ^/dist/(.*) $scheme://$host/dist/$1 permanent;
        }

 # managed by Certbot

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ombi.server.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ombi.server.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}

```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Please post the errors in your browsers console?

Did you restart ombi and nginx after?

**Comment by m1lkman** [comment]
Yes, I did. Here you go.
```
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
vendor.js Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
main.js Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
```

**Comment by tidusjar** [comment]
That's your issue. There is something up with your proxy that is causing too many redirects.

I don't know much about reverse proxy so I suggest you jump on discord and ask on there.
