### ISSUE TITLE
Instant crash after landing page

### ISSUE THREAD

**Issue by yigit007** [tidusjar/Ombi#2030]
#### Ombi build Version:

3.0.2959-DotNetCore

#### Update Branch:

N/A

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Ubuntu 12.04.1 (precise)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Immediately after the landing page appears on the browser, Ombi application crashes with the following error and terminates:
`./Ombi: symbol lookup error: /opt/Ombi/System.Net.Http.Native.so: undefined symbol: curl_multi_wait
`
libcurl4-openssl-dev is installed (confirmed via apt-cache policy shown below)
`libcurl4-openssl-dev:
 Installed: 7.22.0-3ubuntu4.17`

libunwind8 is installed manually from the Trusty repository as it is not available in the Precise main or backports.
`libunwind8:
  Installed: 1.1-2.2ubuntu3`

Ombi is started on a test user and with the option --storage=/home/testuser/ombi (this folder exists and belongs to testuser). 

#### Reproduction Steps:

Problem is always happening after opening the Welcome to Ombi page.

**Comment by tidusjar** [comment]
Try this https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

Look at the bottom Q2 and A2

**Comment by yigit007** [comment]
Thanks, I think the important part here is to create a suitable environment variable that points to libcurl. Still, I followed the instructions and compiled cURL from source and it works. Closing the issue.
