### ISSUE TITLE
Radarr can't update movie info for Ombi's imports

### ISSUE THREAD

**Issue by jaydee99** [tidusjar/Ombi#2032]
#### Ombi build Version:

3.0.2959

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Debian Stretch

#### Problem Description:

When adding a movie request to Ombi, the movie is added to Radarr but poster and movie infos are not showing. When i try to click "Update movie info" button in radarr, i get this error in radarr's log

Error occurred while executing task RefreshMovie: HTTP request failed: [502:BadGateway] [GET] at [https://api.themoviedb.org/3/movie/451618?api_key=XXXXXXXXXXXXXXXXXXXXXXX&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN]

If manually searching for the movie into radarr i get 

NzbSearchService | Error while searching for [Bloody Milk]: Object reference not set to an instance of an object
-- | --

It works fine if i add the movie directly into radarr

Thanx for helping !

EDIT : This problem happens only for auto approved movies. For movies that need validation, it works perfect after clicking "approve" with default settings.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by jryantomes** [comment]
Having the same issue with Radarr only on v.2.2.1678

**Comment by tidusjar** [comment]
Please post your log files
