### ISSUE TITLE
Stuck request

### ISSUE THREAD

**Issue by Saywho527** [tidusjar/Ombi#2033]
#### Ombi build Version:

V 3.0.2849

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Qnap

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

have a TV request that has completed / but when i go to remove it there are no options to do that when I hit the +view button

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Please update
