### ISSUE TITLE
Can't login if user not created

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/Ombi#2039]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.12.0.4829

#### Operating System:

Docker 
rogueosb/docker-ombi

#### Problem Description:

Not sure if I was supposed to create this as a feature request instead, but since this worked in V2 I made it as an issue.
On V2 I could sign in to Ombi without creating a user in ombi first. So my friends just signed in as their name, instead of needing to remember their username. 

If I try to signin as a non existing user in V3, I just get asked for password, which I naturally don't have. 
I have checked the "Allow users to login without a password" box.

#### Reproduction Steps:

Try to login with an non existing user to Ombi.

**Comment by tidusjar** [comment]
There needs to be a user account created. This is not something I plan to change.
