### ISSUE TITLE
proxy using nginx page is blank

### ISSUE THREAD

**Issue by phairplay** [tidusjar/Ombi#2041]
#### Ombi build Version:

V 3.0.2970

#### Media Sever:

Plex

#### Operating System:

windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

switched to v3 updated nginx with new port yet page wont load. i see it quickly say loading in the middle of the page an orange bar go across but the page stays blank

#### Reproduction Steps:

```
					}
     location /plexrequest {
		proxy_pass http://127.0.0.1:5000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

						}
```

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by phairplay** [comment]
hi 
I loaded your example and it still doesn't work
