### ISSUE TITLE
Reverse Proxy redirection weirdness

### ISSUE THREAD

**Issue by MrBones757** [tidusjar/Ombi#2044]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.3.1.0

#### Operating System:

RancherOS (Linux)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

No logs out of the ordinary

#### Problem Description:

When using ombi behind a rancher ha-proxy, im unable to load the web interface correctly.
The first few times i tried: the redirect wouldnt work at all - rebooted a bunch of times and it began to show a plain grey ombi background and the orange loading bar at the top of the window when loading.

I changed the base url to /request from /ombi. Same symptoms persist except this time if i specify <ip/name>/request/login i can see the status screen, click continue to login. The background appears and the UI accepts my login details and prompts if incorrect. However the ui never redirects to any other Ombi page and i cant manually change to another page (using the url). All users have request permissions and the user i was trying to connect with had admin, power user.

#### Reproduction Steps:

See above - let me know if you need any more specifics.. cant think of much more to add right now

**Comment by tidusjar** [comment]
Does it work fine locally? Have you tried clearing you cache?

**Comment by MrBones757** [comment]
Hello,
Thanks for your reply!

I have done a sanity check and cleared caches on all my test devices. (chrome, edge desktop, chrome mobile). All devices gave the same results after a restart and full web cache & dns reset.
I've attached images showing what i'm observing. See the three images below:

Navigate to base url:
![image1](https://user-images.githubusercontent.com/22608473/37044745-3f33d210-219f-11e8-918b-99bcb950311e.png)

Change to /request/login
![image2](https://user-images.githubusercontent.com/22608473/37044746-3f6a37a6-219f-11e8-9bc8-55be23c28511.png)

After enter login credentials:
![image3](https://user-images.githubusercontent.com/22608473/37044747-3f9d52e4-219f-11e8-8485-6084456ca4ea.png)

Thnaks in advance for any info!

**Comment by tidusjar** [comment]
Interesting. Are there any errors in the browsers console?

**Comment by anojht** [comment]
I have the same issue as the above user and it seems like this stems from the `/dist/2.js` file not being fetched. I get a 404 error for that file. This leads me to believe the nginx rewrite rule posted in the wiki is not working correctly as the request url is still `$host/dist/2.js`

**Comment by tidusjar** [comment]
@anojht you are correct your rewrite rule is not working.

**Comment by anojht** [comment]
@tidusjar I managed to fix the rewrite rule and everything looks ok, however I cannot login to any account unless I tick the "Remember Me" box. Tested this with different accounts and different browsers. Might this be a bug? How can I help debug this?

**Comment by tidusjar** [comment]
@anojht  this current issue is not realted to that. Please raise a new issue.

**Comment by MrBones757** [comment]
Hello,

Sorry for the slow reply.
The developer console in chrome shows a 503 error. Unable to find/access dist/2.js

![image](https://user-images.githubusercontent.com/22608473/37085947-5c59cb3c-2231-11e8-97e6-b55a2c269e0b.png)

If you need anything else let me know.

**Comment by tidusjar** [comment]
This is an issue with your RP setup

**Comment by MrBones757** [comment]
I just found it weird that all my other services I've tested this proxy with worked as is.
Given the cause of this is the RP. was wondering if you had any experience with ha-proxy (used on pfsense among other things) and could check out this config. I'm not all that familiar with proxy configs - this is auto generated by the orchestrator i'm using:

backend ombi
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
    timeout check 2000
mode http
server <address> <ip> check port 3579 inter 2000 rise 2 fall 3

**Comment by tidusjar** [comment]
This means nothing to me. Maybe ask on discord?

**Comment by MrBones757** [comment]
no worries - worth a shot asking.. you never know 👍 . Will check out discord now. Will post here when i get make progress.

**Comment by anojht** [comment]
@MrBones757 Hey I use pfsense as well although I do not use HA-proxy. From your screenshot it looks like you need a rewrite rule for the file `/dist/2.js` so you would need to translate the following nginx rule for HA-proxy:

`if ($http_referer ~* /ombi/) {`
       ` rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;`
`}`

**Comment by anojht** [comment]
Try appending the following lines to the end of your proxy config for ombi, since you are using /request as base URL I have adjusted for that already:

`acl p_ext_js path_end -i .js`
`acl p_folder_dist path_beg -i /dist/`
`http-request set-path /request/dist/%[path] if !p_folder_dist p_ext_js`

**Comment by MrBones757** [comment]
Hello,
Thanks for the reply. Was just getting started figuring it out. 
So just to confirm - you're saying it should be like this:
(i have to figure out how to insert that text there as by default the controller adds it where the arrow is)

```
backend ombi
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port     <----
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
    timeout check 2000
acl p_ext_js path_end -i .js
acl p_folder_dist path_beg -i /dist/
    http-request set-path /request/dist/%[path] if !p_folder_dist p_ext_js
mode http
server <server> <ip> check port 3579 inter 2000 rise 2 fall 3
```

**Comment by anojht** [comment]
@MrBones757 Yes but see my edited comment, for the final revised version of the rule. You have it in the right place but it should look like this: 

`acl p_folder_dist path_beg -i /dist/`
`http-request set-path /request/dist/%[path] if p_folder_dist`

**Comment by MrBones757** [comment]
okay - trying to implement that now. didn't refresh the page so didn't notice you'd changed it.
