### ISSUE TITLE
Windows - Can't edit Plex Server / Load Libraries

### ISSUE THREAD

**Issue by Mattch23** [tidusjar/Ombi#2045]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.11.3.4803

#### Operating System:

Windows Server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

None :/

#### Problem Description:

Just updated via Fresh Install, completed deleted the old Ombi files, trying to add a plex server via the Config page and the following occurs:
After logging in and selecting the server (only Plex Server) clicking "Load Libraries" displays an error box top right that just says [object Object] (https://i.imgur.com/QuVkiFM.png)

Pressing Test Functionality seems to do nothing

Pressing Submit doesn't save.

This occurs regardless of if I do it via a remote connection or on the local server itself.

Tried restarting Ombi and trying again but the same issue occurs
#### Reproduction Steps:

Happens each time I try to edit the Plex Server

**Comment by tidusjar** [comment]
What's in the browsers console?

**Comment by tidusjar** [comment]
What's the host that you entered?

**Comment by campbc** [comment]
Plex and Ombi are on the same Windows host for me so I’ve tried:

localhost 
127.0.0.1
system IP

All gave the same error. When discovering the plex server it originally populated the system IP.

**Comment by Mattch23** [comment]
Hitting the Load Libraries option throws the following in console:

vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1 POST http://localhost:5000/api/v1/Plex/Libraries 500 (Internal Server Error)

Pressing the Submit button puts the following in console:

vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1 POST http://localhost:5000/api/v1/Settings/Plex/ 500 (Internal Server Error)

function.r.(anonymous function).v.(anonymous function).(anonymous function) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
y @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
onScheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.scheduleMacroTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
f @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
D.o.(anonymous function) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t._trySubscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.subscribeToResult @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._innerSub @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._tryNext @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t._trySubscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.save @ plex.component.ts:112
(anonymous) @ VM205 e.ngfactory.js:885
handleEvent @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
handleEvent @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
er @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
onInvokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.runTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
v @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
b @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1 ERROR e {headers: t, status: 500, statusText: "Internal Server Error", url: "http://localhost:5000/api/v1/Settings/Plex/", ok: false, …}
It @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.handleError @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.object.r @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.__tryOrUnsub @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.emit @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.invoke @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.run @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.runOutsideAngular @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
onHandleError @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.handleError @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.runTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
v @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
b @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
XMLHttpRequest.send (async)
function.r.(anonymous function).v.(anonymous function).(anonymous function) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
y @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
onScheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.scheduleTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.scheduleMacroTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
f @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
D.o.(anonymous function) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t._trySubscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.subscribeToResult @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._innerSub @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._tryNext @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.next @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e._subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t._trySubscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.call @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.subscribe @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.save @ plex.component.ts:112
(anonymous) @ VM205 e.ngfactory.js:885
handleEvent @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
handleEvent @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
er @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
(anonymous) @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
onInvokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
t.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.runTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
e.invokeTask @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
v @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1
b @ vendor.js?v=54gTUtIePQ8e96EQcNWY25sPLgP4PuLhFbOnjsTAG-U:1

**Comment by tidusjar** [comment]
What'sin your log file? or console output

**Comment by tidusjar** [comment]
@campbc the error you have `Invalid URI: The hostname could not be parsed.` suggests to me its your confiuration issue.

Please ensure that the hostname ONLY contains the hostname (no slashes at the end or anything), in the port is the actual port too.

**Comment by Mattch23** [comment]
@tidusjar Sorry for the delayed response, there's nothing in the log file and no errors are printed on the console

**Comment by sarvex** [comment]
I am facing the same issues....

469    at Ombi.Controllers.External.TesterController.<Plex>d__55.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 235
470 2018-03-12 19:44:28.228 +05:30 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://localhost:32400/

The Plex connection seems to completely buggy. nothing works. 

**Load Server** says one server found but the **Select Server** dropdown does not show anything. 

Why is there a "Plex Auth Token" When there is no easy way to setup this? 

Test Connectivity always failes "Failed to connected to Plex"

**Comment by devbrian** [comment]
I get the same issue.  I click test connection, it works, it shows my libraries names correctly, but when I click load libraries, I get 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1 ERROR e
It @ vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1
:5000/api/v1/Job/updateCached/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1

**Comment by devbrian** [comment]
@tidusjar any ideas?

**Comment by Mattch23** [comment]
Just confirming that the issue persists on the latest release (3.0.3020)

**Comment by devbrian** [comment]
Also, this happens on windows and Linux so it’s not OS specific.

Anyone know the latest working release?

**Comment by Mattch23** [comment]
@tidusjar Any joy with working out what this may be?  Is there anything else I could do to help you narrow down the issue?

**Comment by tidusjar** [comment]
Not yet. I've not marked this as a high priority issue since you still can fill it in manually.

**Comment by Mattch23** [comment]
With regards to manual editing, is that via editing a config file as the submit button doesn't work on the UI?

**Comment by devbrian** [comment]
@tidusjar Yeah, as @Mattch23 said, manually entering the names in the UI doesn't work either.

**Comment by tidusjar** [comment]
Manually entering in the host, port and Auth key should work fine. 

If that doesn't I suspect then there is something different with your Plex account/server that I have not seen yet. 

Whats in the console when you press submit? Since it may help with the investigation

**Comment by devbrian** [comment]
@tidusjar 



Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1 ERROR e
It @ vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1
:5000/api/v1/Job/updateCached/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1

My plex server is behind a CDN, but that shouldn't make a difference. Ombi is hosted on the same server using localhost to connect to

**Comment by Mattch23** [comment]
Looks to be the same error, happens if I click submit if I've changed anything or not

vendor.js?v=l01EXsfejme32NaKI28fdyxG1nVF73PXqEo2qEkrRGw:1 POST http://localhost:5000/requests/api/v1/Settings/Plex/ 500 (Internal Server Error)

**Comment by devbrian** [comment]
@Mattch23 any chance you are running plex behind a CDN?

**Comment by Mattch23** [comment]
@devbrian Indeed, its running behind NGINX

**Comment by devbrian** [comment]
That's probably our issue then, Ombi must not be compatible with servers running behind a CDN, which is a growing number of servers. Hopefully this is able to be solved easily.

**Comment by tidusjar** [comment]
So how are you connecting it? 

I have now setup Plex behind Nginx, are you connecting over the internete.g. DomainName.com/Plex ? or are you still using Internal IP's e.g. 192.168.1.99 ?

Can someone give me an example of what you are putting in your settings?

**Comment by livioh** [comment]
any update on this? Don't matter what i try too still can't get it to see my library

**Comment by tidusjar** [comment]
Last update as you can see above is me asking for information. 

This is not a massive problem at the moment since you still can enter the information in manually.

**Comment by sjfer** [comment]
I seem to be having similar issues setting up Ombi, whether on Debian or in a Docker container:
```
ERROR Object { headers: {…}, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown url): 0 Unknown Error", error: error } vendor.js:1:19697`
```
```
error: error { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, … }
​headers: Object { normalizedNames: Map, lazyUpdate: null, headers: Map }
​message: "Http failure response for (unknown url): 0 Unknown Error"
​name: "HttpErrorResponse"
​ok: false
​status: 0
​statusText: "Unknown Error"
​url: null
​
__proto__: Object { constructor: e() }
vendor.js:1:19697
It
http://[IP Address]:5000/dist/vendor.js:1:19697
vendor_5bb5afdc5634aebdc2f5</</kt</t.prototype.handleError
http://[IP Address]:5000/dist/vendor.js:1:19903
next
http://[IP Address]:5000/dist/vendor.js:1:43196
vendor_5bb5afdc5634aebdc2f5</</Ue</e.prototype.subscribe/r<
http://[IP Address]:5000/dist/vendor.js:1:35877
vendor_5bb5afdc5634aebdc2f5</u</e.prototype.__tryOrUnsub
http://[IP Address]:5000/dist/vendor.js:1:200596
vendor_5bb5afdc5634aebdc2f5</u</e.prototype.next
http://[IP Address]:5000/dist/vendor.js:1:199871
vendor_5bb5afdc5634aebdc2f5</l</e.prototype._next
http://[IP Address]:5000/dist/vendor.js:1:198910
vendor_5bb5afdc5634aebdc2f5</l</e.prototype.next
http://[IP Address]:5000/dist/vendor.js:1:198593
vendor_5bb5afdc5634aebdc2f5</p</e.prototype.next
http://[IP Address]:5000/dist/vendor.js:1:201762
vendor_5bb5afdc5634aebdc2f5</</Ue</e.prototype.emit
http://[IP Address]:5000/dist/vendor.js:1:35643
onHandleError/<
http://[IP Address]:5000/dist/vendor.js:1:37595
vendor_5bb5afdc5634aebdc2f5</</</</a</t.prototype.invoke
http://[IP Address]:5000/dist/vendor.js:1:2529499
vendor_5bb5afdc5634aebdc2f5</</</</r</e.prototype.run
http://[IP Address]:5000/dist/vendor.js:1:2524646
vendor_5bb5afdc5634aebdc2f5</</We</t.prototype.runOutsideAngular
http://[IP Address]:5000/dist/vendor.js:1:38304
onHandleError
http://[IP Address]:5000/dist/vendor.js:1:37557
vendor_5bb5afdc5634aebdc2f5</</</</a</t.prototype.handleError
http://[IP Address]:5000/dist/vendor.js:1:2529579
vendor_5bb5afdc5634aebdc2f5</</</</r</e.prototype.runTask
http://[IP Address]:5000/dist/vendor.js:1:2525394
vendor_5bb5afdc5634aebdc2f5</</</</l</e.invokeTask
http://[IP Address]:5000/dist/vendor.js:1:2531292
y
http://[IP Address]:5000/dist/vendor.js:1:2541988
b
http://[IP Address]:5000/dist/vendor.js:1:2542232`
```

**Comment by tidusjar** [comment]
This issue doesn't seem to be going anywhere. If anyone is having this issue please open a new issue with the appropriate information.

Thanks.
