### ISSUE TITLE
Report Issue Button Dropdown

### ISSUE THREAD

**Issue by flawlessdeadpixel** [tidusjar/Ombi#2047]
#### Ombi build Version:

V 3.0.2970-master

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.12.0.4829

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

NA

```

#### Problem Description:

Report issue button does nothing. It acts like there should be a drop down but nothing appears.

#### Reproduction Steps:

Click on report issue button from the search movie page.
![ombireportissue](https://user-images.githubusercontent.com/25791527/37063925-f9195042-214f-11e8-8b04-65ad1a73fd97.png)

**Comment by TheRealDirtyMike** [comment]
There are not pre-made/pre-defined issue categories in V3. You have to make them yourself.

![issues](https://user-images.githubusercontent.com/6248985/37074338-eece07f8-2191-11e8-8c2a-5e9b3e41144a.PNG)

**Comment by flawlessdeadpixel** [comment]
That makes sense. Sorry for the confusion!

**Comment by TheRealDirtyMike** [comment]
No worries. I actually thought the same thing when I was messing with it and almost opened an Issue myself haha. Glad I could help.
