### ISSUE TITLE
Unable to login to any account unless "Remember Me" box is checked

### ISSUE THREAD

**Issue by anojht** [tidusjar/Ombi#2048]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.3.1.0

#### Operating System:

Docker Container (Linux)
https://hub.docker.com/r/linuxserver/ombi/

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-03-06 03:10:10.029 -08:00 [Information] Created User "admin"
2018-03-06 03:10:10.336 -08:00 [Information] Created the roles
2018-03-06 03:10:10.563 -08:00 [Information] Added the Admin role
2018-03-06 16:49:52.380 -08:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://connect.emby.media/service/user/authenticate
2018-03-06 16:49:54.173 -08:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://connect.emby.media/service/user/authenticate
2018-03-06 16:50:00.919 -08:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://connect.emby.media/service/user/authenticate

```

#### Problem Description:

I cannot login to any account unless I tick the "Remember Me" box. Error pops up and says "Incorrect Username or Password", Tested this with different accounts and different browsers. Might this be a bug? How can I help debug this?

#### Reproduction Steps:

Please see the problem description above.

**Comment by tidusjar** [comment]
All the Remember Me does is set the credentails to expire in a long time rather than the usual.

It looks like from the logs that Emby is stating that your credentials are not valid

**Comment by anojht** [comment]
But if that were the case then the local admin account would work but I also experience this issue with the local admin account as well. I have no idea what is causing this. As when I click remember me box everything just works fine.

**Comment by gadgetusaf** [comment]
I experienced an issue on 2981 and rolled back to 2975. While I did not click the remember me function no user or admin could log in.

**Comment by tidusjar** [comment]
Are you saying that 2975 works fine for you?

@gadgetusaf 2981 was not a branch you should have been using, it was not the master branch or develop.

**Comment by gadgetusaf** [comment]
@tidusjar  Correct rolling back to 2975 I did not have a login issue, I can test 2970 if you would like too.

**Comment by tidusjar** [comment]
Yes please @gadgetusaf 2981 should have never been used as it was an unstable branch

**Comment by gadgetusaf** [comment]
@tidusjar in 2970 I was able to log in with no error in firefox and chrome

**Comment by tidusjar** [comment]
Ok so your issue was that you used a bad build

**Comment by anojht** [comment]
I reinstalled 2970 again from scratch. I am still getting these weird login issue. At this point idk what else to try. Is there any way of turning on debug logging? The log seems very basic.

**Comment by tidusjar** [comment]
I'm not sure what your issue is, like i said, all the remember me does is control how long the JWT token is valid for.

Have you tried a different browser?

**Comment by anojht** [comment]
Yes as stated in my original post, I tried many different browsers. What is the default JWT token valid time set for?

**Comment by anojht** [comment]
I managed to resolve this. I was being such a dumb dumb, it turns out my server time went out of sync and therefore the token valid time was off and did not allow me to login. Sorry for the troubles! Love Ombi and your work!
