### ISSUE TITLE
Mattermost Notifications "MethodNotAllowed"

### ISSUE THREAD

**Issue by PromoFaux** [tidusjar/Ombi#2055]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Debian, though running Ombi with the LinuxServer/Ombi docker container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-03-09 11:39:16.708 +00:00 [Error] StatusCode: MethodNotAllowed, Reason: Method Not Allowed, RequestUri: https://redacted/hooks/redacted/

```

#### Problem Description:

Post never actually makes it to Mattermost. Log shows `MethodNotAllowed`

#### Reproduction Steps:

Add an incoming webhook to Ombi settings.

If it helps any, I actually have an (appaulingly named) Mattermost Webhook client available to use on [Nuget](https://www.nuget.org/packages/Matterhook.NET.MatterhookClient/)

Repo here : https://github.com/promofaux/matterhook.net.matterhookclient

**Comment by seanvree** [comment]
Yeah, I'm getting this to. 

Windows 10 X64

**Comment by tidusjar** [comment]
@PromoFaux I looked at your nuget package but it's targeting .Net Framework, So I cannot use it!

**Comment by PromoFaux** [comment]
It was something I just threw together for my own use... I can take a look into `.NET Standard 2.0` if you like?

**Comment by tidusjar** [comment]
It's your choice, i've currently taken your classes (and provided the sources and credit under GPL 3.0) and tweaked them slightly for my use. If you do convert it then i'll pull down your library.

**Comment by PromoFaux** [comment]
@tidusjar - Just pushed v.1.2.4 with .NET Standard support... I think! I'm new to this multiple frameworks game :)

https://www.nuget.org/packages/Matterhook.NET.MatterhookClient/1.2.4

**Comment by tidusjar** [comment]
Can you please check the develop branch for the fix

@PromoFaux I shall update to that now.

**Comment by PromoFaux** [comment]
But either way, as long as I can get MM notifications from my Ombi install, I'm happy :D
