### ISSUE TITLE
"Caching Episodes Failed"

### ISSUE THREAD

**Issue by Pentaganos** [tidusjar/Ombi#2056]
#### Ombi build Version:

V 3.0.3004

#### Update Branch:

Develop

#### Media Sever:

Plex

#### Media Server Version:

3.39.4

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

https://pastebin.com/zXefxC32

#### Problem Description:

When trying to run a manual cache of my plex it spits out the above error.

#### Reproduction Steps:

I have about 13TB of media that Ombi is attempting to read fresh install and first cache run.

**Comment by tidusjar** [comment]
Please clear out your PlexServerContent and PlexEpisodes table using SQLite. Latest build then will work
