### ISSUE TITLE
Pending request filter does not work

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#2057]
#### Ombi build Version:

V 3.0.3004

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Centos 7

#### Problem Description:
Cannot select the pending request filer. I am using chrome. Also there is a bit of wonkyness with clearing the filters. The filters clear but do not actually get unchecked. 

![2018-03-09_12-37-48-3](https://user-images.githubusercontent.com/2241731/37222003-b8d15fba-2399-11e8-939f-f91c2c48e6f0.gif)

#### Reproduction Steps:

Go to requests. Try and select pending request filter. 

Go to requests. Select filters. Hit clear. Go back to filters. You will find they are still checked.

**Comment by tidusjar** [comment]
Fixed the Pending Approval part, technically the filter boxes are actually radio buttons and that's just how they work -.-"

**Comment by samwiseg00** [comment]
> Fixed the Pending Approval part, technically the filter boxes are actually radio buttons and that's just how they work -.-"
> --

lol ok

**Comment by tidusjar** [comment]
I'll still see if i can fix it.

**Comment by samwiseg00** [comment]
> I'll still see if i can fix it.

Ha. thanks!

**Comment by samwiseg00** [comment]
confirmed fixed! you da man!
