### ISSUE TITLE
API not honoring Apikey - Value cannot be null

### ISSUE THREAD

**Issue by iVirus** [tidusjar/Ombi#2058]
#### Ombi build Version:

V 3.0.3000

#### Update Branch:

master

#### Media Sever:

Plex and Emby

#### Media Server Version:

N/A

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
{"error":"Value cannot be null.\nParameter name: user"}
```

#### Problem Description:

The API doesn't honour Apikey after v3.0.2970. Using Authorization still works.

#### Reproduction Steps:

```
curl -H 'Apikey: <myapikey>' http://localhost:5000/api/v1/Request/movie
```

**Comment by tidusjar** [comment]
Fixed in develop
