### ISSUE TITLE
Base URL not always being used

### ISSUE THREAD

**Issue by CodaAmok** [tidusjar/Ombi#2059]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Ubuntu Server 16.04.04 LTS 4.4.0-116-generic

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
not applicable
```

#### Problem Description:

I'm using nginx reverse proxy with http basic auth. Watching the access.log I can see that GET requests are made to Ombi not honouring the configured base URL. 

Here's my nginx config relevant to Ombi:

```
        location /plexrequest {
                return 301 $scheme://$host/plexrequest/;
        }
        location /plexrequest/ {
                proxy_pass http://192.168.0.106:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout  90;
                proxy_redirect http://192.168.0.106:5000 https://$host/;
        }
        if ($http_referer ~* /plexrequest/) {
                rewrite ^/dist/(.*) $scheme://$host/plexrequest/dist/$1 permanent;
        }
```

Here's the snippet of nginx access.log:

```
192.168.0.1 - - [09/Mar/2018:19:53:18 +0000] "GET /plexrequest/search HTTP/1.1" 200 4552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
192.168.0.1 - - [09/Mar/2018:19:53:19 +0000] "GET /loading.css?v=k33zb3c0-ToEQSx13OJIBKNSzNyG6g4V29uA0YpYiV0 HTTP/1.1" 401 606 "https://domain.com/plexrequest/search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
192.168.0.1 - - [09/Mar/2018:19:53:20 +0000] "GET /plexrequest/api/v1/Settings/issuesenabled HTTP/1.1" 200 14 "https://domain.com/plexrequest/search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
192.168.0.1 - - [09/Mar/2018:19:53:20 +0000] "GET /plexrequest/api/v1/Settings/customization HTTP/1.1" 200 384 "https://domain.com/plexrequest/search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
192.168.0.1 - - [09/Mar/2018:19:53:20 +0000] "GET /plexrequest/api/v1/Settings/issues HTTP/1.1" 200 59 "https://domain.com/plexrequest/search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
192.168.0.1 - - [09/Mar/2018:19:53:20 +0000] "GET /plexrequest/api/v1/Issues/categories/ HTTP/1.1" 200 12 "https://domain.com/plexrequest/search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
```

#### Reproduction Steps:

Have an nginx web server configured as a reverse proxy, with the root location block config like below:

```
        location / {
                auth_basic "supersecret";
                auth_basic_user_file /etc/nginx/.htpasswd;
        }
```

Set location block same as I've given above.

Set base URL as **/plexrequest**

Browse to web service and observe request for basic auth. You can even escape the window and page loads OK. Not sure of the importance of the two GET requests made that don't use base url.

**Comment by tidusjar** [comment]
I can only see 1 GET request not using the base url and that's a css file?

**Comment by CodaAmok** [comment]
When you say not using a base URL, are you also using proxy_pass under location / ?

I'm interested to hear that you only see 1 GET for .css and not the other things under /api/ like I'm getting. I don't see any log files for the web server on my Ombi VM, are there any?

**Comment by tidusjar** [comment]
Looking at your access log, everything is using your base URL except a css file

**Comment by CodaAmok** [comment]
Yes...?

**Comment by tidusjar** [comment]
![image](https://user-images.githubusercontent.com/6642220/37230196-6daff10a-23de-11e8-9c28-3cbf914c602f.png)
Looks to be working for me, must be something to do with your setup.

**Comment by CodaAmok** [comment]
@tidusjar thanks for your help, I found the issue, here's my new nginx config in case any one else stumbles across it:

`
location /plexrequest {
                return 301 $scheme://$host/plexrequest/;
        }
        location /plexrequest/ {
                proxy_pass http://192.168.0.106:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout  90;
                proxy_redirect http://192.168.0.106:5000 https://$host;
        }
        if ($http_referer ~* /plexrequest/) {
                rewrite ^/dist/(.*) $scheme://$host/plexrequest/dist/$1 permanent;
        }
`

I had trailing forward slashes for the values given in proxy_pass and proxy_redirect directives.

I don't know why I didn't think to look at Ombi's headers directly before opening an issue, sorry I wasted your time.
