### ISSUE TITLE
Lidarr support?

### ISSUE THREAD

**Issue by Chadthedj** [tidusjar/Ombi#2061]
Curious if that was in the works.

**Comment by tidusjar** [comment]
It's not in the works. But I will be taking a look at it in the future

**Comment by CoderKiwi** [comment]
I assume the API would be similar to Sonarr and Radarr so adding the functionality to Ombi should be relatively straightforward.

And it's good to add a music service since Headphones was dropped (understandably).

**Comment by tidusjar** [comment]
It's not just that @CoderKiwi I also need to add a new sort of request type that supports music, need to find a music api that is suitable e.g. MusicBrainz. Need to add to the Plex/Emby scans to mark as available etc.
It's quite a lot of work.

**Comment by CoderKiwi** [comment]
Oh @tidusjar you mean that as IMDB is the metadata repository for Movies, MusicBrains would be the metadata repo for Music? Makes sense but yes would need some good vetting before implementing and depending on it...

Also would be cool to be able to request full albums or individual songs, similar to TV Shows currently with requesting Seasons or individual Episodes

**Comment by tidusjar** [comment]
Yeah, so we use TheMovieDb for movies, TvMaze for TV. 

But when we do it, it will act similar to movies I assume

**Comment by bobloadmire** [comment]
I also would like Lidarr support

**Comment by Ahsome** [comment]
Lidarr has just found its its public beta release, so that should increase the number of users!

**Comment by thewillwilson** [comment]
Lidarr seems stable enough for me, so +1 it

**Comment by HamilcarH** [comment]
Would also love lidarr support for artists.

**Comment by Pxmme** [comment]
I'd love that!

**Comment by tidusjar** [comment]
Please see #2313
