### ISSUE TITLE
Request access_token for user, without password

### ISSUE THREAD

**Issue by rourke** [tidusjar/Ombi#2062]
I'm creating a Telegram bot that uses the Ombi API in its backend. I have a few trusted users from which I know their Telegram and Ombi usernames and user_id's. When one of those users submits a request through Telegram I want to add that request to Ombi, as if submitted from that user in Ombi itself.

I can't seem to request an access_token on behalf of the user, based on a username or user_id. It requires a password. Even if I supply an `ApiKey`. I don't want to fiddle with passwords in Telegram. Is there any way I can manage this through the API?

**Comment by tidusjar** [comment]
Do you have password authentication turned off in ombi?

Otherwise you are asking to authenticate them without a password and that's a security risk.

**Comment by rourke** [comment]
I have the telegram user_id's of the trusted users, so I know which Ombi user is requesting it and I know it's legit. This makes it secure on my end. If I supply the Ombi API key it should be secure enough towards the Ombi API. So basically I just want to place a request on behalf of the other user.

**Comment by tidusjar** [comment]
Why cant you use the normal API and provide a password? 

I'm just wondering.

**Comment by rourke** [comment]
That would require my users to also enter their password through the Telegram Bot. Even though it's a private message, it's there in plaintext. After the user gives his/her full credentials I need to store it in a database - also in plaintext - so that it I can be used to communicate to the Ombi API for future requests. I don't think this method is best practice. I guess I would be okay with it if I can store the hashed passwords in my database, but the API won't accept that as far as I can see.

Instead I have a hardcoded list of my friends and their Telegram/Ombi user_id's. When they do a request through the Telegram bot I know who they are in Ombi.

Perhaps I'm looking at this all wrong. If so I'm happy to hear it.

**Comment by tidusjar** [comment]
Ok I understand. There currently is an undocumented experimental wait to access the API as a user. I also needed this functionality for the mobile apps I'm writing. It's basically an API key per user. I'll share the details when I get on the pc later.

**Comment by rourke** [comment]
That's great to hear. I'd love to experiment with that.

**Comment by tidusjar** [comment]
Ok, so you need to use a UserAccessToken header, the value is against the User record in the AspUsers table called user access token. 

So that will act similar to an API key but it will be all the permissions and username for that user. So this is a API key so do not display/expose it anywhere. 

Since this is still experimental i may change it if needed.

**Comment by rourke** [comment]
Fantastic. Thank you very much. I love Ombi :)

Just one more question. I see the UserAccessTokens are empty in my Ombi.db. Is that by default? I just want to be sure. I don't mind writing a random string to it myself.

**Comment by tidusjar** [comment]
Ah man, this is why it's experimental!

you need to be logged in as that user and go to: http://yourombi/api/v1/identity/accesstoken

It will then add it to the DB for that user.

**Comment by tidusjar** [comment]
ah wait
that wont work...

Write a random string for now

**Comment by rourke** [comment]
Alright. Thank you!
