### ISSUE TITLE
Bulk Edit Doesn't Change User's Request Limit

### ISSUE THREAD

**Issue by NaturalCarr** [tidusjar/Ombi#2063]
#### Ombi build Version:

V 3.0.2970
#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 4.14.16-unRAID
--

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When doing a bulk edit on user permissions, everything works well except their request limits, those changes don't occur.

#### Reproduction Steps:

Import a few users with a given request limit, then try to change them all using bulk edit in user management.

**Comment by tidusjar** [comment]
Cannot recreate, looks to be working for me
