### ISSUE TITLE
TV/Movie search app not being synced if down

### ISSUE THREAD

**Issue by 1activegeek** [tidusjar/Ombi#2065]
#### Ombi build Version:

V 3.0.2970

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Docker Container (ls.io)

#### Problem Description:

If the tv/movie app is down while someone makes a request, it will not end up in the queue. I recently had something happen, needed to take radarr/sonarr offline. A user came in and requested 4 movies. 1 of them happened the be requested right before I took them offline and it made it in the queue. The other 3 were not reported back to radarr. When I brought radarr back online, it was then never passed the new movie requests. The obviously showed as requested in the interface, but were not being passed along to radarr. 

#### Reproduction Steps:

1. Turn off radarr/sonarr while Ombi is running.
2. Make a request for new content in Ombi.
3. Validate request shows up in the requests section. 
4. Turn radarr/sonarr back on. 
5. Wait 15 minutes to ensure a sync has been able to run. 
6. Validate the movies have not been sent to radarr.

**Comment by tidusjar** [comment]
I am aware of this, currently Ombi will send it over as soon as it can, I plan to make this queue in the future but It currently does not work as you think

**Comment by 1activegeek** [comment]
Ahhh, ok. Got it. I'll have to make sure I take down Ombi if I take the others down then. ;) Thanks for the detail. Look forward to testing that when it comes to the app.
