### ISSUE TITLE
SSO suddenly stopped working between Organizr and Ombi

### ISSUE THREAD

**Issue by Nomelas** [tidusjar/Ombi#2075]
#### Ombi build Version:

v3.0.3030

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Latest

#### Operating System:

Windows 10 (latest)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-03-14 03:00:45.131 -03:00 [Information] 1 scheduled job(s) enqueued.
2018-03-14 09:01:10.975 -03:00 [Information] 1 scheduled job(s) enqueued.
2018-03-14 15:00:36.984 -03:00 [Information] 1 scheduled job(s) enqueued.
2018-03-14 21:01:02.850 -03:00 [Information] 1 scheduled job(s) enqueued.

```

#### Problem Description:

SSO suddenly stopped working between Organizr and Ombi.

#### Reproduction Steps:

I used to be able to log into organizr and it would also log me into ombi when I went to that tab. Since I updated to the latest few versions (I think starting with v3.0.3000 or the version before it)

**Comment by tidusjar** [comment]
Nothing should have changed regarding this. Are the any errors in your browsers console?

**Comment by Nomelas** [comment]
No errors

**Comment by tidusjar** [comment]
I've spoken to some users that use this functionality and they state that it's working fine.

I have made no changes around this area since I developed it.

**Comment by Nomelas** [comment]
It started working again. I remember removing ombi from my homepage when there was a bug with it in a certain version. seems re-adding it fixed the issue.
