### ISSUE TITLE
Tar Error in newest release

### ISSUE THREAD

**Issue by andmayfi92** [tidusjar/Ombi#2077]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

error when untarring
tar: A lone zero block at 249120

#### Reproduction Steps:

Downloaded latest linux.tar.gz and tried to tar xzf linux.tar.gz and the error

**Comment by tidusjar** [comment]
Does this happen with a previous build?

**Comment by coute** [comment]
I have the same issue : 
`tar: zero block at 249120`
After installing it, parameters menu is not available.

**Comment by coute** [comment]
I don't have the tar error message with ombi 3.0.3020

**Comment by coute** [comment]
I have the issue with parameters menu with previous builds. I will open a new issue for that.

**Comment by andmayfi92** [comment]
No I did not. I was able to go back and install the last build just fine.
