### ISSUE TITLE
Cached Items No Longer Available

### ISSUE THREAD

**Issue by carnivorouz** [tidusjar/Ombi#2080]
#### Ombi build Version:

3.0.2988 

#### Update Branch:

I grab an update when I think about it since Linux updater does not work yet.

#### Media Sever:

Plex

#### Media Server Version:

Version 1.12.1.4871

#### Operating System:

Fedora 27

#### Problem Description:

I automatically delete movies older than 6 months to save on storage.  I've had a few instances now where users say a movie is available in Ombi but is not in Plex.  For each movie I've checked and it is not in CouchPotato nor Plex.  I know there is a Cacher from the Plex configuration page but it seems like missing items are never culled out of the cache.

#### Reproduction Steps:

1. Have an item as available in Ombi
2. Delete that media
3. Manually run cacher or wait until job completes on its own
4. Media still available in Ombi?

**Comment by tidusjar** [comment]
Yes because it currently does not go through deleted things.

**Comment by estavez** [comment]
This function really needs to be added. Se my post here about it: https://github.com/tidusjar/Ombi/issues/1566#issuecomment-428004457
