### ISSUE TITLE
High virtual memory

### ISSUE THREAD

**Issue by andmayfi92** [tidusjar/Ombi#2083]
#### Ombi build Version:

V 3.0.3020

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.12.1.4885

#### Operating System:

Ubuntu16.04 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

High Virtual Memory usage (20GB+)

#### Reproduction Steps:

As soon as I start the Ombi service the virtual memory in htop is showing as 22.5G.
![image](https://user-images.githubusercontent.com/26902805/37575626-843ca95a-2afe-11e8-8bfe-655e15dcfba0.png)

**Comment by tidusjar** [comment]
https://github.com/dotnet/coreclr/issues/14738
