### ISSUE TITLE
Ombi/Nginx Reverse Proxy Image Issue

### ISSUE THREAD

**Issue by ericgcollyer** [tidusjar/Ombi#2085]
#### Ombi build Version:
V 3.0.3030
#### Update Branch:
master
#### Media Sever:
Plex
#### Media Server Version:
N/A
#### Operating System:

Ubuntu 14.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
```

Nginx reverse proxy configuration:

        location /request
        {
                return 301 $scheme://$host/request/;
        }

        location /request/
        {
                proxy_pass http://127.0.0.1:5000;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real_IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }


```

#### Problem Description:
Images not displaying correctly through nginx reverse proxy.
#### Reproduction Steps:

I currently have my server running through cloudflare (domain -> cloudflare -> nginx reverse proxy -> ombi)

When I access my Ombi installation, images are unable to load. Here's a screenshot of what I am seeing:

https://imgur.com/a/p1hZS

**Comment by tidusjar** [comment]
Tried restarting ombi and clearing your browser cache?

**Comment by ericgcollyer** [comment]
I've done both of those things (and I've also attempted to use Chrome's Incognito Mode). 

The site works if I access it directly via the IP address (E.g. 10.10.10.10:5000), but not through the reverse proxy (e.g. www.mydomain.com/request).

**Comment by tidusjar** [comment]
What's in your browsers console?

**Comment by ericgcollyer** [comment]
Looks like the relevant errors are "Refused to load the image 'https://image.tmdb.org/t/p/w300//qqO98sdPgptFgCua3Z4uZDuPcmP.jpg' because it violates the following Content Security Policy directive: "img-src 'self' https://ssl.google-analytics.com https://s-static.ak.facebook.com https://assets.zendesk.com"."

**Comment by tidusjar** [comment]
So do you have some sort of CSP rules in your proxy?

**Comment by ericgcollyer** [comment]
Derp. That was absolutely the case. I must have added it years ago and implementing Ombi made me realize it was there. I've removed it and now Ombi works flawlessly. Thanks!
