### ISSUE TITLE
Not running on macOS

### ISSUE THREAD

**Issue by jonathanlaniado** [tidusjar/Ombi#2087]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

Stable

#### Media Sever:

Plex/Emby

#### Media Server Version:

N/A

#### Operating System:

macOS 10.13.3

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I launched the Ombi executable for the first time and got this error in Terminal: `Application startup exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional.` 

#### Reproduction Steps:

Just trying to launch it for the first time.

**Comment by jonathanlaniado** [comment]
I've also tried copying the appsettings.json file to my user account directory. That stops the error from happing, but http://localhost:5000 shows this error: `"The view 'Index' was not found. The following locations were searched:\n/Views/Home/Index.cshtml\n/Views/Shared/Index.cshtml"`.

**Comment by tidusjar** [comment]
You need to make sure your working directory is where Ombi is located.
