### ISSUE TITLE
The Ombi page, cannot select Danish as language all other works?

### ISSUE THREAD

**Issue by casperse** [tidusjar/Ombi#2101]
#### Ombi build Version:

V 3.0.3020
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

N/A - Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The Ombi page, cannot select Danish as language all other works?
Is it some geo location auto language? or a bug?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by KennyVB** [comment]
yea can't use danish either.. i tried selecting english and wanted to switch back, can't
also using Docker (Rancher OS on Freenas)
