### ISSUE TITLE
movies removed from plex showing as available.

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#2102]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I deleted a movie from plex which wasn't requested (added manually). The movie is stilled marked as available on ombi even after 3 days of removal from plex.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Yes I am aware of this. We currently do not check if movies or episodes have been removed. 

I'm planning to add this functionality in the future

**Comment by estavez** [comment]
**This function really needs to be added. Se my post here about it:** https://github.com/tidusjar/Ombi/issues/1566#issuecomment-428004457
