### ISSUE TITLE
Wrong Timezone for Last Logged In for User Management

### ISSUE THREAD

**Issue by Hossy** [tidusjar/Ombi#2108]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.12.1.4885

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

The timestamp shown under the **Last Logged In** column in **User Management** is showing GMT even though the OS shows time in CST (TZ=US/Central).

#### Reproduction Steps:

http://ombiserver:3579/usermanagement

**Comment by tidusjar** [comment]
Everything is stored as UTC.

In the future I will be converting all the UI times to the users local timezone.

**Comment by vsimon** [comment]
I also ran into this issue of noticing wrong timezone for "Last Logged In". +1 for local timezones in the UI.

**Comment by JSKershaw** [comment]
Any idea on when this will be addressed?  I still notice the timezone as UTC.  I need it to show -5:00 timezone.

**Comment by tidusjar** [comment]
What version are you on

**Comment by vsimon** [comment]
3.0.3988 here

**Comment by JSKershaw** [comment]
In on 3.0.3988

**Comment by JSKershaw** [comment]
I'm now on 3.0.4119 and it's still off by 5hrs.
Running Ombi in docker and tried to use the TZ command and that didn't help either.

**Comment by cookandy** [comment]
Same here, running `3.0.4119`. Also tried using the Docker `TZ` env var but it did not work.

**Comment by gregdelima** [comment]
`Version | 3.0.4892` Also using docker with TZ=America/New_York. And getting UTC Time.

**Comment by cliny** [comment]
Version 3.0.4892, using docker with specified Australia/Melb TZ variable; still displaying UTC 'last logged in' time.

**Comment by thomasgentilhomme** [comment]
Still displaying UTC timezone, am i missing something?

**Comment by tidusjar** [comment]
This should be fixed in the dev version
