### ISSUE TITLE
(auto) Updater not working

### ISSUE THREAD

**Issue by nivong** [tidusjar/Ombi#2110]
#### Ombi build Version:

V 3.0.3030

#### Update Branch:

Master

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Not ombi logs but I saw this error in the google developer console
```
message
:
"Http failure response for http://URL:5000/api/v1/Job/updateCached/: 500 Internal Server Error"
name="HttpErrorResponse"
status=500
statusText="Internal Server Error"
url="http://URL:5000/api/v1/Job/updateCached/"
```

#### Problem Description:

Ombi v3.0.3111 is the new version and I am on 3.0.3030. When I go to:
```Settings>Update```
I click "check for update" it shows that there is no new version.
#### Related
https://github.com/tidusjar/Ombi/issues/1460

**Comment by tidusjar** [comment]
#1460
