### ISSUE TITLE
No content for movies in newsletter mail

### ISSUE THREAD

**Issue by hbooo** [tidusjar/Ombi#2111]
#### Ombi build Version:

3.0.3108

#### Update Branch:

develop

#### Media Sever:

Emby

#### Operating System:

Microsoft Windows 10.0.14393 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

This 10 times
2018-03-28 09:57:32.571 +00:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/0?api_key=removedapikey&append_to_response=videos,release_dates
```

#### Problem Description:

The mail send by the newsletter doesn't have information for new movies. There is no content or picture. Everything is fine for the new episodes part

#### Reproduction Steps:

I enabled newsletter
Changed subject and message
Update database
Launch test on my user (admin)

![image](https://user-images.githubusercontent.com/242125/38023065-8ea82d26-3281-11e8-877d-83a7b0b5f69d.png)

**Comment by tidusjar** [comment]
Fixed in develop
