### ISSUE TITLE
Feature request: Internal path to new Logo link

### ISSUE THREAD

**Issue by casperse** [tidusjar/Ombi#2113]
Feature request

#### Ombi build Version:
V 3.0.3020
#### Update Branch:
master
#### Media Sever:
Plex
#### Media Server Version:
N/A
#### Operating System:
Docker/Synology
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
N/A
(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)
#### Problem Description:
Feature request: Instead of http path for logo use internal /config/icon/logo.jpg
#### Reproduction Steps:
N/A

**Comment by tidusjar** [comment]
Please read the readme regarding feature requests
