### ISSUE TITLE
CSS fails to load with Nginx ngx_brotli

### ISSUE THREAD

**Issue by mrkno** [tidusjar/Ombi#2117]
#### Ombi build Version:

V 3.0.3115
It has been occurring for multiple builds, as well as stable. First noticed after switching to V3.

#### Update Branch:

Develop (occurs stable too)

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Ubuntu 17.10, 4.13.0-16 x86_64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
< the output in the logs is character-for-character identical with and without ngx_brotli >
```

#### Problem Description:

When [ngx_brotli](https://github.com/eustas/ngx_brotli) is enabled on an Ombi V3 reverse proxy, CSS does not fully load. Aside from CSS, everything else appears to be working as expected. ngx_brotli static files have not been enabled.

The logs show no difference which makes me suspect this problem lies in ngx_brotli - however ngx_brotli  is working with other services such as Sonarr and Radarr without problem so maybe it isn't? 

Firefox reports that `vendor.css` has about 1/3 of the number of rules when ngx_brotli is enabled vs when it is not.

With ngx_brotli enabled:  
![image](https://user-images.githubusercontent.com/6830312/38156186-aa5a7b38-34d8-11e8-9c8c-d9707549bf2a.png)

#### Reproduction Steps:

1. Setup nginx with ngx_brotli (ngx_http_brotli_filter_module) enabled. Easiest way to do this is to use the nginx-HDA bundle for Ubuntu, as it contains up to date nginx and ngx_brotli with bugfixes
2. Setup a reverse proxy for Ombi
3. Add `brotli on;` to your Ombi reverse proxy

**Comment by tidusjar** [comment]
I'm not going to fix this since it's modifying the css that I made.

I suggest you do not use that module with Ombi
