### ISSUE TITLE
Installation Wizard Failure

### ISSUE THREAD

**Issue by robflate** [tidusjar/Ombi#2119]
**Ombi build Version:**

V 3.0.3111

**Update Branch:**

Master

**Media Sever:**

Plex

**Operating System:**

I'm using MacOS 10.13.4 but Ombi is in a Docker container from [here](https://github.com/linuxserver/docker-ombi).

Ombi Applicable Logs (from /logs/ directory or the Admin page):

```
2018-04-01 08:29:57.548 +01:00 [Debug] OK, signing into Plex
2018-04-01 08:29:57.607 +01:00 [Debug] This is our first time, good to go!
2018-04-01 08:29:58.298 +01:00 [Debug] Attempting to sign in to Plex.Tv
2018-04-01 08:29:58.298 +01:00 [Debug] Sign in successful
2018-04-01 08:29:58.299 +01:00 [Debug] Getting servers
2018-04-01 08:29:58.575 +01:00 [Debug] Adding first server
2018-04-01 08:29:58.688 +01:00 [Debug] Finished
2018-04-01 08:30:01.541 +01:00 [Information] Created User "robflate"
2018-04-01 08:30:01.875 +01:00 [Information] Created the roles
2018-04-01 08:30:02.105 +01:00 [Information] Added the Admin role
```
**Problem Description:**

When I setup Ombi v3, I complete the wizard and then nothing happens. If I then remove `/Wizard/Plex` from the URL, I can see Ombi but nothing works. Search does nothing and Settings are all blank.

If I try the wizard again, I get this error message `ERROR: Could not get the Plex Admin Information`. If I try to create a new admin without Plex, I get `ERROR: There was an error... You might want to put this on Github...`

- I have tried deleting the `Ombi.db` but the problem persists.
- I have installed an older version of Ombi. [On docker hub it was 45](https://hub.docker.com/r/linuxserver/ombi/tags/). This worked and I got through the wizard. When I then installed the latest version but left the db in place, the problem returns and Ombi search and settings don't work.
- I have tried the docker container with and without traefik (reverse proxy) with the same result

**Reproduction Steps:**

Clean install of [docker-ombi:latest](https://github.com/linuxserver/docker-ombi)
Go through the wizard
The wizard fails

**Comment by benninkcorien** [comment]
Same/similar issue. New user, first time running the setup. Default settings for everything. OSX 10.12.6 with Plex running on localhost (mac mini connected to TV).

If I choose to let the Plex user be Admin for Ombi: Could not get the Plex Admin Information
If I create a new user on Ombi: There was an error... You might want to put this on Github...
If I log in on plex.tv myself server on localhost shows up fine, Ombi shows up under devices too..

If I ignore Plex and go straight to create admin account for Ombi: There was an error... You might want to put this on Github...

**Comment by robflate** [comment]
I've read through the other threads with this issue and nothing I do seems to fix it. The only way to get Ombi working is by using version 45. Any help appreciated.

**Comment by jackjohnsonuk** [comment]
again, same issue.  New user, stuck in the new Wizard trap :( running https://hub.docker.com/r/linuxserver/ombi/

**Comment by Tritiumosu** [comment]
I'm also having either an installation hang/failure or I'm just impatient. Windows 10 x64, 3.0.3239-master
I get this from the Ombi.exe window, running as Administrator:

```
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3239-master
Copyright (C) 2018 Ombi
<snip>command line flags here...</snip>
We are running on
C:\OmbiV3
Hosting environment: Production
Content root path: C:\OmbiV3
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Starting the Metadata refresh
dbug: Ombi.Controllers.PlexOAuthController[0]
      Adding first server
```

Loading http://localhost:5000/ in Chrome will start the wizard, Authenticate with my Plex OAuth, and then... it just dies. No disk/network/CPU activity that I can observe, nothing else in the Ombi.exe window after ~1hr.

**Comment by koolmon10** [comment]
Same issue here also.

Ubuntu server 16.04 LTS
Fresh install from repo

**Comment by flying-sausages** [comment]
New Ubuntu 16.04 here, installed from repositories 3.0.3239-master.
Does anyone remember when was the last version that this bug was not there?

**Comment by samip5** [comment]
@tidusjar I already have a few day old Plex account, same issue.

**Comment by MrLordy** [comment]
just a note. i tested wile talking on discord.   and i found that atleast for me on windows .  with version Ombi v3.0.3239 and the latest dev build the issue are the same.  but when i go back to Ombi v3.0.3185 . it works.  don't seem to be any issues there.

**Comment by nathforge** [comment]
Seeing the same as @MrLordy - Ombi 3.0.3239-master won't allow registrations during the initial wizard.

Tested from Ombi 3.0.3030-master up to Ombi 3.0.3239-master using the linuxserver Docker images.

I'm not using Plex or Emby.

Browser request is
```
POST /api/v1/Identity/Wizard/
{"usePlexAdminAccount": "false", "username":"user", "password": "pass"}
```

Ombi 3.0.3239-master is the only one to return `false`.

**Comment by tidusjar** [comment]
Ok thanks for the info guys. I'll take a look at this soon and see what I can do

**Comment by mindfrost82** [comment]
Having the same issue here on Windows 10 64-bit.  Going to download 3185 and see if that works like MrLordy mentioned.

**Comment by tidusjar** [comment]
can someone with this issue try build 3.0.3250 from the develop branch?

**Comment by calvinwankhede** [comment]
@tidusjar The AppVeyor build seems to have failed for 3.0.3250, can't download the release.

**Comment by tidusjar** [comment]
Yeah sorry, fixing that now

**Comment by calvinwankhede** [comment]
I just tried it out, everything is working perfectly.

**Comment by L0rdBootysniffer** [comment]
It's fixed for me, too!
