### ISSUE TITLE
Radarr Cacher - Unexpected charachter

### ISSUE THREAD

**Issue by mgladwin** [tidusjar/Ombi#2126]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.12.2.4929

#### Operating System:

unRaid

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

https://gist.github.com/mgladwin/77ad01eff2e96887154f134d91c632ae

#### Problem Description:

All movie requests (5 of them) stuck on 'Processing Request'.
Some movies are already in Radarr and some are not.

Part of log that seems to be the issue below:-

**2018/03/03 23:27:51.414 Ombi.Services.Jobs.RadarrCacher Error: Failed caching queued items from Radarr Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].alternativeTitles', line 5, position 7**.

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
Hmmmm Strange..

Can you  please post the output to:

https://RadarrURL/api/movie?apiKey=RADARRAPIKEY

If you don't want to post the output on here you can PM me on discord.

**Comment by mgladwin** [comment]
Any further on this? No rush just asking

**Comment by tidusjar** [comment]
DId you PM me on discord?

**Comment by mgladwin** [comment]
Yep

**Comment by tidusjar** [comment]
Well this is awkward... Apolgoies. Do you mind sending me the response again?

I'd clearly forgot about this.

**Comment by mgladwin** [comment]
Ok mate have done

**Comment by tidusjar** [comment]
@mgladwin There are changes in the latest release that should fix this.

Can you please confirm

**Comment by mgladwin** [comment]
Yep, seems to have fixed it. Thanks mate.
