### ISSUE TITLE
Absolute path in logo

### ISSUE THREAD

**Issue by mariusch** [tidusjar/Ombi#2128]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

In configuration -> Customisation -> Custom logo I set the logo to "images/logo.png" and it would show up fine in the preview below, but be broken on login screen and in emails. I need to use the absolute path in order for it to work. Base url is set correctly.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
This is not really a bug, What you enter into the field is what will be in the email.
