### ISSUE TITLE
Missing Extra emails from Newsletter

### ISSUE THREAD

**Issue by elit3ge** [tidusjar/Ombi#2133]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.102 x64 (Docker)

#### Problem Description:

In version 2 there was a field to add extra emails for people to receive the newsletter, however, in this version, it is missing.

**Comment by tidusjar** [comment]
Users without a account?

**Comment by tidusjar** [comment]
Added in develop

**Comment by elit3ge** [comment]
That's correct :)
