### ISSUE TITLE
Unable to find tv-show

### ISSUE THREAD

**Issue by KennyVB** [tidusjar/Ombi#2135]
#### Ombi build Version:

V 3.0.3111
 Docker

Plex

#### Media Server Version:
1.12.1.4885 
#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Can't search for a tv-show etc. named "Life of Kylie"
can find it with Sonarr, TVmaze, imdb and  tvdb so it is out there

#### Reproduction Steps:

search for Life of Kylie
comes up with nothing, try to search with fever words and still finds everything else then Kylie but finds kyle etc.

**Comment by tidusjar** [comment]
It's because that TVMaze has no tvdbid. 

http://api.tvmaze.com/search/shows?q=life%20of%20kylie

You can ask them to add it.
