### ISSUE TITLE
When trying to request movie, it already says requested. New Ombi installation.

### ISSUE THREAD

**Issue by e2zippo** [tidusjar/Ombi#2139]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

PMS 1.12.1.4885

#### Operating System:

Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
[log-20180409.txt](https://github.com/tidusjar/Ombi/files/1889065/log-20180409.txt)


```

#### Problem Description:

Just installed Ombi, and it looks awesome, I'm doing a test drive before my users are allowed to use it, to make sure it works right.

I created a test user and searched for some movies, and many of them already have the "Requested" status. But under Requests there's nothing, and I haven't requested anything. either. How can I reset this, where is it getting this information from?

#### Reproduction Steps:

Search for various movies and see that they already have the status "Requested" even though no one has requested anything since this is a new installation.

**Comment by tidusjar** [comment]
It's because it exists in Radarr/Sonarr

**Comment by e2zippo** [comment]
Thanks, that was the case! Couldn't find the information anywhere though, maybe I missed it!
