### ISSUE TITLE
Base URL Wiki section

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#214]
Can someone who understands the Base URL setting and reverse proxying in general create a bit for the Wiki on here for those (like me) who are much more novice?

Things like:
- What all pages are not valid to use?
- What is the proper formatting for the setting? "/request"
- How to use the -base switch as well?
- Would be nice for suggested settings within NGINX, Apache, etc.
- Anything else I am missing?

I think these are answered in other Issues, but it'd be nice to be well written by someone and put into the Wiki for newcomers.

**Comment by tidusjar** [comment]
Yeah that does makes sense!

I'm adding some validation to the page so it will allow "/" and it won't let you use "/requests" etc. But yes it does make sense to add it to the wiki.
