### ISSUE TITLE
Scroll up button missing in v3

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#2141]
#### Ombi build Version:

V 3 latest

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1. 12

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

V2 had a orange button with an up arrow icon that one could used to quickly get back to the top of the list. This is missing from v3. Is that intentional or is this something that was missed in v3? Thanks in advance. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
I've just not added it yet

**Comment by goku-son** [comment]
Understand, thank you for the reply.
