### ISSUE TITLE
main frame wont load after update to ombi v3 3164

### ISSUE THREAD

**Issue by dejected1** [tidusjar/Ombi#2143]
#### Ombi build Version:

v3 3164

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

windows 10 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

i cant get to the logs
```

#### Problem Description:

After updating to ombi v3 3164 from ombi v3 3111 the landing page no longer appears. If is specify /landingpage at the end of the address i get the login screen and i can login. After login thou the top bar loads but the iframe underneath is blank. It was working on 3164. I am using reverse proxy and the rewrite is in place, unless it changed from 3111 to 3164. I have restarted the services and the server several times to no avail. I have also tried several different browsers. The follow error shows up in the console when the landingpage tries to load or if i click on any of the headers on the top bar. 

vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1 ERROR Error: Uncaught (in promise): Object: {"loadChunkError":true}
    at O (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at O (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
    at t.invokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at Object.onInvokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at t.invokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at e.runTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at m (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
It @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.handleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.object.r @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.__tryOrUnsub @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e._next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.emit @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
(anonymous) @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.invoke @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.run @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.runOutsideAngular @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
onHandleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.handleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.runGuarded @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
n.microtaskDrainDone @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
m @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
Promise.then (async)
f @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
onScheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.scheduleMicroTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
k @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
O @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
(anonymous) @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
window.webpackJsonp @ bootstrap 594ddcce2b3ed1bbf879:21
(anonymous) @ 1.js:1
vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1 Uncaught (in promise) 

#### Reproduction Steps:

update to ombi v3 3164 from 3111.

**Comment by anojht** [comment]
If you are using chrome press F12 and right click on the refresh/reload button at the top and click `Empty cache and hard reload`

I just had the same issue and clearing the cache worked!

**Comment by dejected1** [comment]
Same. Console shows the following error again: 

vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1 ERROR Error: Uncaught (in promise): Object: {"loadChunkError":true}
    at O (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at O (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
    at t.invokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at Object.onInvokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at t.invokeTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at e.runTask (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
    at m (vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1)
It @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.handleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.object.r @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.__tryOrUnsub @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e._next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.next @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.emit @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
(anonymous) @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.invoke @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.run @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.runOutsideAngular @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
onHandleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.handleError @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.runGuarded @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
n.microtaskDrainDone @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
m @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
Promise.then (async)
f @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
onScheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
t.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.scheduleTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
e.scheduleMicroTask @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
k @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
O @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
(anonymous) @ vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1
window.webpackJsonp @ bootstrap 594ddcce2b3ed1bbf879:21
(anonymous) @ 2.js:1
chatjs.php:592 loading chat
vendor.js?v=R-2K3o3xrLzUpd5QNWY0nSU3HEtKmjNDlTF5moBU5cc:1 Uncaught (in promise) {loadChunkError: true}

**Comment by anojht** [comment]
Can you try incognito window?

**Comment by dejected1** [comment]
well that's interesting. I had tried incognito before posting, and it didn't work. But after i did the Empty cache and hard reload that you suggested, incognito does work. What does that mean exactly, that i have a  add-on not working or i have a rouge file it keeps loading?

**Comment by anojht** [comment]
yes this has to do with browser caching, can you completely clear all cache in your browser and try again?

**Comment by dejected1** [comment]
yeah that was the first thing i tried before posting. I also tried IE and it had the same issue. I tried browsing as a guest in chrome and that worked so i deleted my chrome profile and re-created it. Now it works. Weird man. whatever, any landing you can walk away from.
