### ISSUE TITLE
musl vs glibc? 

### ISSUE THREAD

**Issue by muhahacz** [tidusjar/Ombi#2145]
Hello,
I am trying to run latest stable version in Alpine linux in Docker.
Seems that there is a problem with musl vs glibc even if I use frolvlad/alpine-glibc as a base image.
Dependencies in Alpine: libstdc++ libuuid libunwind-dev icu-dev libcurl openssl-dev

./Ombi
./Ombi: /usr/lib/libstdc++.so.6: no version information available (required by ./Ombi)
./Ombi: /usr/lib/libstdc++.so.6: no version information available (required by ./Ombi)
./Ombi: /usr/lib/libstdc++.so.6: no version information available (required by ./Ombi)
Segmentation fault (core dumped)

dmesg:
Ombi[21269]: segfault at 0 ip 00007f3c88b8bcff sp 00007ffdb4c27ef8 error 4 in ld-musl-x86_64.so.1[7f3c88b6c000+89000]

Any suggestions?

**Comment by tidusjar** [comment]
I do not know much about docker, but I'd recommend running https://hub.docker.com/r/linuxserver/ombi/

**Comment by jalmansor** [comment]
@muhahacz, not to be facetious, but the obvious answer to me seems to be not to use Alpine. I can't see an overwhelmingly compelling reason why making it work in Alpine (aside from image size) would be better at running Ombi than using say Ubuntu (xenial being the base image of choice for the linuxserver.io Ombi image). Seems like a lot of trouble just to get it right.

**Comment by lukasmrtvy** [comment]
@tidusjar  its enough to compile it agains libc-musl for backwards compatibility. Alpine linux does not use glibc.
