### ISSUE TITLE
Caddy reverse proxy not working

### ISSUE THREAD

**Issue by tehniemer** [tidusjar/Ombi#2146]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.12.1.4885

#### Operating System:

QNAP Docker 17.07.0-ce

#### Problem Description:

I'm getting caddy setup for my plex stack and have it working for Sonarr, Radarr, ect... but I can't get it working for Ombi for some reason. I get a 502 bad gateway error every time. Here's the snippet from my Caddyfile

```
# New rewrite rule needed to load some of Ombi V3's assets
 
  rewrite {
    r ^/dist
    to /ombi/{uri}
    } 
 
  proxy /ombi 172.10.0.10:3579 {            # https://github.com/tidusjar/Ombi
    transparent								# NOT WORKING
    }
```

Not really sure where to ask, but I figured I'd start here.

**Comment by anojht** [comment]
Im not sure that for Caddy you need the rewrite rules, can you try it without them. See [Wiki:Proxy Guide](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples)

**Comment by tidusjar** [comment]
Please try example in wiki

**Comment by tehniemer** [comment]
I have tried without the rewrite, same results.

**Comment by tidusjar** [comment]
Make sure you have set your ombi base URL and then restarted ombi. 

Other than that I cannot help as I have no knowledge about caddy. Maybe jump on discord to see if anyone knows how to set it up.

**Comment by tehniemer** [comment]
Base URL is set, I have everything running in Docker, if that makes a difference. These are the errors that Caddy is throwing.

```
11/Apr/2018:02:05:19 +0000 [ERROR 502 /ombi] dial tcp 172.10.0.10:3579: connect: no route to host
11/Apr/2018:10:47:59 +0000 [ERROR 502 /ombi] dial tcp 172.10.0.10:3579: connect: no route to host
11/Apr/2018:11:03:26 +0000 [ERROR 502 /ombi] dial tcp 172.10.0.10:3579: connect: no route to host
11/Apr/2018:11:05:51 +0000 [ERROR 502 /ombi] dial tcp 172.10.0.10:3579: i/o timeout
```

I'll check with the Caddy guys as well as head to Discord, thanks for the suggestions.

**Comment by tehniemer** [comment]
I got it working by adding ```/``` after the subdirectory, so ```domain.com/ombi``` became ```doman.com/ombi/``` and it works. Nothing changed in the Caddyfile.

**Comment by anojht** [comment]
Nice! If you don't mind can you post your Caddy config please so we can possible add it to the wiki and help new users? Thanks!

**Comment by tehniemer** [comment]
That's the thing, my Caddyfile didn't' change, the extra ```/``` gets added in the browser to get it to work. I'm not familiar enough with Caddy to know exactly what it's doing in the background, but I'm going to work out what needs to happen in the Caddyfile to add the trailing ```/``` automatically. I'll submit a change request at that point.

**Comment by tehniemer** [comment]
The rewrite did the trick for me. I edited the wiki page to include it.
