### ISSUE TITLE
Imported Plex User Permission Issues

### ISSUE THREAD

**Issue by werkkrew** [tidusjar/Ombi#2150]
#### Ombi build Version:

V 3.0.XX (Not sure exactly as I cannot access the admin area - approximately 1 week old docker image)

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4947

#### Operating System:

Linux, Ombi running in Docker via LinuxServer.io

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Cannot access admin page.

```

#### Problem Description:

Fresh install after using v2 for a long time.  Imported plex users and have import plex admin set to true.  My plex admin account does not have admin access to Ombi and when querying the Ombi.db database there is no account or role which does have admin rights.  Also, no users have access to request movies even though I believe they should (cannot verify as I cannot access admin area).

The only role listed in the roles table is "RecievesNewsletter"

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by werkkrew** [comment]
Yes.  The admin area worked and I got it all set up.  A friend told me they couldn't request a movie and when I logged in to see what might be wrong I no longer have admin rights.

**Comment by tidusjar** [comment]
I'm not sure what the issue is here. Did you remove your permission? I'd just delete the ombi dB and restart ombi

**Comment by werkkrew** [comment]
The issue is Ombi has no administrator access after importing users from
Plex.

I could start from scratch but that may not fix the underlying issue.
Ideally I'd like to add the permissions back without having to reconfigure
everything again.

I didn't remove my permissions, I think there might be a bug in how Ombi
gives admin permissions to the plex admin or something.

**Comment by werkkrew** [comment]
I am closing this although I am still not sure that what I encountered was not a bug.  To resolve I started over from scratch and made sure I created a local admin account prior to importing plex users and the plex admin.

**Comment by stephenbrannen** [comment]
I'm running into the same issue. I'm migrating from running Ombi directly on my server to docker. Restoring the DB wasn't working so I started from scratch. 

version: 3.0.4256

I have both import Plex Users and import Plex Admin checked. But my plex admin account is synced as a Plex user

Luckily I created a local admin before and can still administer, but this is definitely a bug.
