### ISSUE TITLE
Update via System -> Update not working (core dump)

### ISSUE THREAD

**Issue by LandonStewart** [tidusjar/Ombi#2154]
#### Ombi build Version:

V 3.0.3173

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

[logentries.txt](https://github.com/tidusjar/Ombi/files/1908702/logentries.txt)

#### Problem Description:

The updates aren't working.

#### Reproduction Steps:

- Login as admin
- Click System dropdown
- Click Update menu item
- Click Check for Updates button
- Click Update button
- Watch logs (in my case they appear in /var/log/syslog)

**Comment by tidusjar** [comment]
Please check other issues . https://github.com/tidusjar/Ombi/issues/1460
