### ISSUE TITLE
Archive instead of Delete

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#216]
I like to have my list clean from completed requests, so currently I just delete them off. But every so often I'd like to go back and see who requested something or how many requests someone has made. But I can't do that since I delete them.

What would be nice is to Archive instead of Delete with them hidden by default but the ability to see them via a new Filter would be great!

**Comment by tidusjar** [comment]
Yeah this is a good idea. I was thinking about something like this as managing the requests is a pain.

**Comment by jrdnlc** [comment]
An option for the movie to automatically archive/delete once it's detect in Plex would be a good settings option as well.

**Comment by SuperPotatoMen** [comment]
planned for the 2.0 release
