### ISSUE TITLE
The "&" symbol is not correctly escaped for Pushover notifications

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#2164]
#### Ombi build Version:

V 3.0.3182

#### Update Branch:

develop

#### Media Sever:

Plex

#### Operating System:

Synology Linux server io Preview docker

#### Problem Description:

Titles with the & symbol in them get cut off when the notification title is sent with pushover.. The notifications are still sent but only the first part of the title appears. I have also had some notifications with no title shown which I suspect is related.

#### Reproduction Steps:

Sample title: Young & Hungry (2014)

**Comment by tidusjar** [comment]
Fixed in develop
