### ISSUE TITLE
Movies are blank in notifications emails

### ISSUE THREAD

**Issue by thehomerepot** [tidusjar/Ombi#2166]
#### Ombi build Version:

V 3.0.3185

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Ubuntu 16.04.4 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

The only thing in my logs.
```
2018-04-15 19:01:32.971 -05:00 [Information] 1 scheduled job(s) enqueued.
```

#### Problem Description:

When testing my newsletter, the Movies list is blank while the TV shows are populated. I've tried using the "update database" button and adding newer movies but it's always blank.

#### Reproduction Steps:

Click "Test" on the notifications configuration page and view the email it sends.

**Comment by tidusjar** [comment]
Make sure the metadata job has run. Wait for that to run then it should work. You can see when it runs on the jobs page.

**Comment by thehomerepot** [comment]
I updated the metadata job to run 'now' (I think, the scheduling is funny with the way it uses UTC but I enter local time? Is that by design?) but it didn't resolve anything. Should jobs be logging their status to the log files too? My logfile doesn't have anything new in it.

**Comment by thehomerepot** [comment]
I tried scheduling the metadata job with both my local time and UTC time since I can't tell what Ombi honors, and neither seemed to do anything. Nothing shows up in my logs to reflect the execution of the metadata job and the test emails still don't work.

**Comment by thehomerepot** [comment]
Ok, so I rescheduled both my newsletter and the metadata job and cycled Ombi and when it sent the movies were fixed.

Are there plans to add a button to manually fire any of the cronjobs immediately? That would help with testing/troubleshooting. Additionally, are there plans to update the cronjobs so I can enter local time instead of UTC for scheduling?

**Comment by tidusjar** [comment]
Yes the fire now is planned and also local times too. Not local times for scheduling though, since it's never really going to be changed and there are higher priority things to be done
