### ISSUE TITLE
Animated shows incorrectly categoriezed as Anime

### ISSUE THREAD

**Issue by D34DC3N73R** [tidusjar/Ombi#2167]
Shows that are not anime are labeled as anime when added to Sonarr. For instance "Final Space".  Shows incorrectly listed as anime will not download unless absolute episode number metadata has been added.

#### Ombi build Version:

V 3.0.3185

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

ubuntu 16 docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Shows incorrectly categorized as anime.

#### Reproduction Steps:

Request Final Space, F is for Family, / any animated show that is not anime.

**Comment by tidusjar** [comment]
I am not sure how to fix this one. I get back if it's an animated series from the API. If I turn this off I'll break it for sending actual anime to sonarr

**Comment by tidusjar** [comment]
Actually scrap that, just worked out how to do it. 

Note to self, look at the TVMaze genre returned.

**Comment by shaddowlink** [comment]
It would be good to have seperate (optional) anime settings for sonarr in ombi. For (quality) profile and base folder aswell

**Comment by anojht** [comment]
Thanks, this is fixed in develop. Please reopen if you find that the problem still exists.
