### ISSUE TITLE
New Plex Recently Added Sync job can't be set to a different schedule then the Plex Sync Job

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#2169]
#### Ombi build Version:

V 3.0.3185

#### Update Branch: Master

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 2012 R2

#### Problem Description:

Plex Sync and Plex Recently Added Sync jobs seem to be linked.  When I change one the other also changes.

**Comment by samwiseg00** [comment]
I can confirm this happens to me as well. :)

**Comment by tidusjar** [comment]
Fixed in develop
