### ISSUE TITLE
API and Ombi Issue

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#2176]
Another Issue, with API or searching in general....

Was playing with API again today and my GF was requesting a new show...  `Loudermilk`

So i passed the info through to the API with the tvdb  ID `328774`
https://www.thetvdb.com/?tab=series&id=328774

API returns true but no data passed...  So i look at the Ombi logs and see this...
`2018-04-19 20:03:47.187 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=328774`

Sure enough nothing comes up in that API with that ID...  so I goto tvmaze and check it out and it appears that they do have they show... but with their own API...
http://www.tvmaze.com/shows/19355/loudermilk

So i make my way over to OMBI to do a search for this show...and to my surprise... it finds nothing..
![image](https://user-images.githubusercontent.com/16184466/39028873-de0637d0-440d-11e8-9bb9-942c2c3e91ac.png)

What API are you using to search for shows?  If the API takes the argument of tvdb why not scrape tvdb for movie info?

Let me know what I can do... Thanks.

**Comment by tidusjar** [comment]
It uses TV maze but we check if the TVMaze API has TheTvDbId. Looks like they do not in this case.

**Comment by causefx** [comment]
What would be the remedy for this as there has been others that are not in tv maze with tvdb id...?

**Comment by tidusjar** [comment]
There is no remedy, Ombi requires TvDb to identify things later on down the line.

**Comment by causefx** [comment]
Correct, which i have.  The problem is you use TVmaze to scrape initially which doesnt always have or match with tvdb.

**Comment by tidusjar** [comment]
Yeah I don't plan to change this. The benefit of TVMaze in d that u don't need an API key.
