### ISSUE TITLE
Themes broke

### ISSUE THREAD

**Issue by si0972** [tidusjar/Ombi#2177]
#### Ombi build Version:

3.0.3203

#### Update Branch:

Develop

#### Operating System:

Docker

#### Problem Description:

#2148 actualy broke it. I get 500 errors in console, and a error when i browse the link manualy .

Url: `domain.com/ombi/api/v1/Settings/ThemeContent?url=https://raw.githubusercontent.com/leram84/layer.Cake/master/ombi/css/omBlur.css`
Error:`{"error":"Specified argument was out of the range of valid values.\nParameter name: startIndex"}`
Base: `/ombi`

#### Reproduction Steps:

update ombi to dev branch

**Comment by tidusjar** [comment]
This should be fixed in develop
