### ISSUE TITLE
Newsletter Update Database Not Working

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#2179]
#### Ombi build Version:

3.0.3185

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.3.1.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Log file has no updates after clicking update database for the newsletter

```

#### Problem Description:

After I imported my Emby library went to the newsletter and clicked the update database and enabled newsletters.  If I click test I successfully receive the test e-mail right away.  If I click the trigger now option I receive a newsletter about 24 hours later and it contains everything.  I triggered the newsletter a 2nd time and had the same results with a 20+ wait time and an e-mail with the entire library.  I copied the ombi.db and looked at the database and noticed the RecentlyAddedLog table has over 17,000 rows.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Fixed in develop.
