### ISSUE TITLE
Text-only option for email notification

### ISSUE THREAD

**Issue by ceptonit** [tidusjar/Ombi#2184]
It would be nice if there was an extra option for each user where we can set whether they get email notifications in HTML or Text-only format.
Not sure how to implement this GUI wise.

I'm asking this because I have some users that actually use their wireless provider's SMS gateway as their email to actually receive SMS instead of emails for Ombi notifications.
As their email, they have PhoneNumber@txt.att.net for example (AT&T being their carrier in this example).
So when an Ombi notification gets sent to them, they get a SMS with all the HTML code and 5-6 in a row because the SMS ends up being way longer than 1 can fit.

This is probably a niche case =P

**Comment by tidusjar** [comment]
Please see here for feature requests: https://feathub.com/tidusjar/Ombi
