### ISSUE TITLE
Mobile Layout - Broken on Various Android/iOS Devices

### ISSUE THREAD

**Issue by zeieri** [tidusjar/Ombi#2185]
#### Ombi build Version:

V 3.0.3058

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 (LTS)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
**Not Sure if Required**
(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When connecting to Ombi on Mobile Devices (Specifically, Samsung Galaxy S7, Google Pixel, iPhone 7, iPhone X), the view is collapsed. If we select Desktop view, it fixes it but you have to zoom in/out to make selections (as it's all really small text).

#### Reproduction Steps:

On a mobile device, open a web browser and go to the URL for Ombi. Login page is fine. Login with username/password. Once logged in, the view is messed up. See picture for view.

![phone view](https://user-images.githubusercontent.com/36149372/39091620-ad420c2a-45b4-11e8-9d75-134cc7aabd9b.png)

**Comment by anojht** [comment]
This theme file is in alpha, meaning it is not done yet. Please close this issue, thanks.
