### ISSUE TITLE
User Management Missing Users

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#2187]
#### Ombi build Version:

V 3.0.3222

#### Update Branch:

develop

#### Media Sever:

Emby

#### Media Server Version:

3.3.1.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

![screenshot](https://user-images.githubusercontent.com/38135239/39143620-09db98f8-46f4-11e8-86c2-87a8c77730d0.JPG)


```

#### Problem Description:

The user exist and are able to login, but they are not properly display in the User Management tab.  Please view screenshot

#### Reproduction Steps:

Login to Ombi and select the User Management tab.

**Comment by tidusjar** [comment]
Fixed in develop
