### ISSUE TITLE
Cannot send pushbullet notifications to a channel name

### ISSUE THREAD

**Issue by galacticat** [tidusjar/Ombi#2190]
#### Ombi build Version:

V 3.0.3229

#### Update Branch:

develop

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4947

#### Operating System:

Ubuntu 16.04 w/Docker

Showing in About: Linux 4.4.0-119-generic #143-Ubuntu  x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-04-24 12:17:31.642 -05:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/336261

```

#### Problem Description:

Can't send pushbullet notifications with Channel Name

#### Reproduction Steps:

1. Configure Pushbullet, without a channel name and send a test notification
2. Verify notification is received
3. Add your channel name, and send a test notification
4. Notification is not recieved

**Comment by tidusjar** [comment]
Is the channel name correct? What are you entering in the field?

**Comment by galacticat** [comment]
Weird, I fixed it by deleting and recreating the channel.
