### ISSUE TITLE
Some Available shows can be requested

### ISSUE THREAD

**Issue by supremacy2k** [tidusjar/Ombi#2193]
#### Ombi build Version:

V 3.0.3185

#### Update Branch:

Linuxserver.io docker image.

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Debian

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Nothing shows in logs.

```

#### Problem Description:

Some tv shows, can be requested, even though they should be listed as available.

The Flash (2014), can be requested, even though all seasons/episodes are available.
Game of Thrones (2011), is correctly listed as available.

Both series is ongoing.

Might be related to https://github.com/tidusjar/Ombi/issues/1951

**Comment by tidusjar** [comment]
Are they appearing as available in ombi?

**Comment by supremacy2k** [comment]
The Flash
https://prnt.sc/ja0orr

Game of Thrones
https://prnt.sc/ja0p3n

What puzzles me, is that GoT is available when flash is not.. and both series have all episodes/seasons

**Comment by tidusjar** [comment]
Can you press the request button, then select... It will show you what episodes are available and what is not.

**Comment by supremacy2k** [comment]
Every single episode from S01E01 to S04E19 (20-23 have not aired yet)

Under stadig, it's listed as Available, but i can click Select next to it.
https://prnt.sc/ja0zcs

Pretty odd tbh

**Comment by tidusjar** [comment]
It's not showing as available since there are episodes that have not aired. They still can be requested.
