### ISSUE TITLE
Plex OAuth redirects to local ip

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/Ombi#2199]
#### Ombi build Version:

v 3.0.3239

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Unraid Docker (lsio container)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

Plex SSO redirects to `http://192.168.8.156:3579/Login/OAuth/{token_here}`
Expected redirect to domain set under Configuration -> Customization -> Application URL

#### Reproduction Steps:

Click Plex SSO and login.

-- Sidenote - My Ombi always says I have an update available 
![image](https://user-images.githubusercontent.com/12055335/39320139-3c1edf96-4951-11e8-8f26-149091fe941a.png)

**Comment by tidusjar** [comment]
It will redirect to the current URL you are on. If you are browsing on localhost then it will redirect to that. If you are your real domain it will redirect to that.

**Comment by tidusjar** [comment]
Oh really? I just get the requested scheme, host and port.

**Comment by Codehhh** [comment]
I added the following proxy rules to my nginx config and the OAuth redirects properly now
```
proxy_pass_header Server;
proxy_redirect off;
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Scheme $scheme;
proxy_connect_timeout 10;
proxy_read_timeout 120;
```
