### ISSUE TITLE
Plex OAuth has malformed callback URL

### ISSUE THREAD

**Issue by ZephireNZ** [tidusjar/Ombi#2201]
#### Ombi build Version:

V 3.0.3239

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Docker: lsioarmhf/ombi:74
OS: archlinuxarm 
Hardware: Raspberry Pi 3 Model B

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

When Ombi redirects to the Plex OAuth page, the callback URL is incorrect for HTTPS. It uses `http://my.server.com:443/ombi/Login/OAuth/123456789` which can cause a server `400` error as this attempts HTTP on an HTTPS port.

Manually fixing the url (eg to `https://my.server.com/ombi/...` allows the login to complete as expected.

#### Reproduction Steps:

1. Enable Plex OAuth
2. Access Plex through an HTTPS URL (ie reverse proxy)
3. Login with Plex
4. Enter Credentials, and be brought to an error page

**Comment by ZephireNZ** [comment]
Example flow (including what my application URL is):

![image](https://user-images.githubusercontent.com/1644496/39351948-46f8d618-4a57-11e8-883d-9c27d6aec0d8.png)

![image](https://user-images.githubusercontent.com/1644496/39351950-4890c6ac-4a57-11e8-958d-0fd437eb66bb.png)

![image](https://user-images.githubusercontent.com/1644496/39351953-4c009006-4a57-11e8-8194-14400ff04788.png)

![image](https://user-images.githubusercontent.com/1644496/39351959-4fc3861c-4a57-11e8-9125-f78893e67e66.png)

**Comment by Codehhh** [comment]
What does your reverse proxy config look like?
My OAuth wasn't working until I added the following to my nginx config.

```
proxy_pass_header Server;
proxy_redirect off;
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Scheme $scheme;
proxy_connect_timeout 10;
proxy_read_timeout 120;
```

**Comment by tidusjar** [comment]
This is definitely due to some setting on your rp setup. All ombi does it grab the current request URL.

**Comment by supremacy2k** [comment]
I'm having trouble logging into Ombi after upgrading from 3.0.3185, haven't even touched settings let alone Plex OAuth

I'm getting a ton of:

```
[Deprecation] The deviceorientationabsolute event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Failed to load resource: the server responded with a status of 500 ()
This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Failed to load resource: the server responded with a status of 500 ()
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

After a while, i succeeded in logging in.

**Comment by carnivorouz** [comment]
I for one have not been able to use Plex Oauth since v3.0.3114 on Linux.  I've tried the stable and dev releases since then and either fails or returns me to  /landingpage upon auth.

**Comment by ZephireNZ** [comment]
```
location /ombi/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_ombi ombi;
    proxy_pass http://$upstream_ombi:3579;
}

// Where proxy.conf is:
client_max_body_size 10m;
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

# Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
```

Note that the reverse proxy is https, but the connection from the proxy to the app is http only which is where the issue is coming in.

I did some googling and added a bunch of headers that are also used for passing that SSL is on:

```
proxy_set_header X-Forwarded-Protocol https;
proxy_set_header X-Scheme https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Url-Scheme https;
proxy_set_header Front-End-Https on;
```

The URL continues to be http://<server>:443/ombi/

**Comment by ZephireNZ** [comment]
So `proxy_set_header Host $host:$server_port;` is the issue here, replacing it with `proxy_set_header Host $http_host;` as per @Codehhh works.

However the OAuth URL is still http, it's just that this time it isn't trying to push http through port 443. A minor thing, but does mean that the Plex PIN ID is being sent over plaintext so could be intercepted.

**Comment by tidusjar** [comment]
I'll change so it uses the application URL if it's set.

**Comment by carnivorouz** [comment]
Guessing it should not just be this screen indefinitely:
![](https://user-images.githubusercontent.com/12376016/39398257-dbc3646a-4ad0-11e8-8a7f-a515feb01919.png)

**Comment by tidusjar** [comment]
Usually means that the authentication didn't work correctly. Look at the browsers console
