### ISSUE TITLE
No Movies being added to Radarr

### ISSUE THREAD

**Issue by uncleiven** [tidusjar/Ombi#2204]
#### Ombi build Version:

V 3.0.3185

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

[log-20180427.txt](https://github.com/tidusjar/Ombi/files/1956396/log-20180427.txt)

[log-20180426.txt](https://github.com/tidusjar/Ombi/files/1956397/log-20180426.txt)

#### Problem Description:

When I select a movie to add to Raddar nothing gets sent to Radarr but there are no errors, it just remains saying Processing Request

#### Reproduction Steps:

I have disabled/re-enabled Radarr, changed the API. Test Connectivity is fine and it has pulled through my profiles and folder locations so it's talking to Radarr ok

**Comment by tidusjar** [comment]
Do you have a baseurl set in Radarr?

**Comment by uncleiven** [comment]
Yes, just removed it and it works fine now.

Thanks :)

**Comment by tidusjar** [comment]
If you need it, just put the baseurl in the radarr settings in ombi
