### ISSUE TITLE
Unable to progress past wizard

### ISSUE THREAD

**Issue by dwmunster** [tidusjar/Ombi#2211]
#### Ombi build Version:

V 3.0.3268

#### Media Sever:

None

#### Operating System:

Docker (both linuxserver/ombi and rogueosb/docker-ombi).

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
app_1  | We are running on http://*:3579
app_1  | /app/Ombi
app_1  | Hosting environment: Production
app_1  | Content root path: /app/Ombi
app_1  | Now listening on: http://[::]:3579
app_1  | Application started. Press Ctrl+C to shut down.
app_1  | info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
app_1  |       Starting the Metadata refresh
app_1  | info: Ombi.Controllers.IdentityController[0]
app_1  |       Created User admin
app_1  | info: Ombi.Controllers.IdentityController[0]
app_1  |       Created the roles
app_1  | info: Ombi.Controllers.IdentityController[0]
app_1  |       Added the Admin role

```

#### Problem Description:

After pulling the latest release and installing, the Wizard successfully completes, but I am unable to access any pages except the search page. The search page is functional, but I cannot access any other pages. Javascript console has the following errors
```
TypeError: _co.authenticationSettings is undefined
```

```
Error: Uncaught (in promise): Error: No NgModule metadata found for 'undefined'.
```

#### Reproduction Steps:

1) Install Ombi in docker container.
2) Select 'Skip' in Wizard.
3) Create admin account.
4) Login with admin credentials.
5) Be unable to access other pages besides Search.

**Comment by tidusjar** [comment]
Can you please try in incognito mode?

**Comment by dwmunster** [comment]
My apologies for the slow response, incognito (and subsequent clearing of the browser) did resolve the issue.
