### ISSUE TITLE
cannot add plex server,

### ISSUE THREAD

**Issue by hartyparty** [tidusjar/Ombi#2213]
[log-20180427.txt](https://github.com/tidusjar/Ombi/files/1961603/log-20180427.txt)
[log-20180429.txt](https://github.com/tidusjar/Ombi/files/1961578/log-20180429.txt)

#### Ombi build Version:

V 3.0.3239

#### Update Branch:

Master

#### Media Sever:

Plex
#### Media Server Version:
1.12.3.4973

#### Operating System:

Windows server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

i installed the v3 version of ombi, I am not very Familiar with installing something like this and i followed the steps to install it. when i go to log in via the local url site to try to set up my server with the wizard. i can log into my account and then in the command line i see a lot of errors, in the web i only see that its adding server, i let it run for over 2 hours. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
The logs only contain info about the auto updater that I suggest you turn off.

What's the actual issue where?

**Comment by hartyparty** [comment]
[log-20180427.txt](https://github.com/tidusjar/Ombi/files/1961844/log-20180427.txt)

can you point me to where the instructions to turn off the auto updater is? the problem is after i gice authentication access to my plex server after logging in, it fails to connect to my server .\

im not sure if this is the right log file or not, i only have 2 at this time.

**Comment by hartyparty** [comment]
[log-20180430.txt](https://github.com/tidusjar/Ombi/files/1962926/log-20180430.txt)

this is the most recent log. ran since the issue was submitted, currently still running

**Comment by tidusjar** [comment]
Why did you close the issue?

**Comment by tidusjar** [comment]
Why did you close the issue?
