### ISSUE TITLE
Sort function doesn't work properly

### ISSUE THREAD

**Issue by ThePierce** [tidusjar/Ombi#2219]
First of all! loving Ombi and the hard work that clearly has been put into this software!

Ombi build Version:

V 3.0.3277
-- | --
Update Branch:

Master
Media Sever:

Plex
Media Server Version:

1.3.0.5003
Operating System:

Ubuntu 16.04
Ombi Applicable Logs (from /logs/ directory or the Admin page):

Problem Description:

When you have multiple pages of requests, the sorting on theatrical date doesn't work properly. Instead of sorting on all requests, it only sorts on the requests on that page. 

Reproduction Steps:

**Comment by tidusjar** [comment]
Thanks, I'll take a look!

**Comment by kewlrobd** [comment]
I just updated to the most recent version.  Default sort is still oldest first and the sort button still only affects the current page.

**Comment by tidusjar** [comment]
I know. I fixed the filtering in the latest release. Hence why this issue is still open

**Comment by kewlrobd** [comment]
Either I am confused or I was not clear.  I updated to the latest release.  I am reporting that this issue still exists for me and that the default sort order has not changed.  Both were in the release notes for the latest version.

**Comment by tidusjar** [comment]
How is yours currently sorted?

**Comment by tidusjar** [comment]
Fixed in develop
