### ISSUE TITLE
Discord notifications

### ISSUE THREAD

**Issue by joaomconde** [tidusjar/Ombi#2222]
#### Ombi build Version:

V. 3.0.3268

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Ombi doesnt send notifications via discord when downloading movie via radarr. It does for sonarr though 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Logs?

Please follow the template

**Comment by joaomconde** [comment]
it was my bad, as i thought (and wanted) the admin to get notifications.

It felt strange because when i add a series i get a notification (although im still logged as admin) is this supposed to happen?

**Comment by joaomconde** [comment]
sorry for my english.
The issue is: When im logged as administartor i get notificartions via discord when i add a series but i dont when i add a movie (sonarr and radarr respectively). Which one is supposed to happen?

**Comment by samwiseg00** [comment]
select this option and you will not receive notifications of the items you add
![2018-06-01_20-05-49](https://user-images.githubusercontent.com/2241731/40868051-51e9d54a-65d7-11e8-9ed9-0c46ad0fbaa7.png)
.
