### ISSUE TITLE
Another case of titles not parsing in Pushover Notifications

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#2228]
#### Ombi build Version:

V 3.0.3291

#### Update Branch:

develop

#### Media Sever:

Plex

#### Operating System:

Synology Docker

#### Problem Description:

Push over notification sent "Hello! You requested R.L. Stine"

Full title:

R.L. Stine's Monsterville: The Cabinet of Souls

It looks like the single quote is not escaped.

It should have read:

Hello! You requested R.L. Stine's Monsterville: The Cabinet of Souls on MyRequests! This is now available! :)

#### Reproduction Steps:

Try addding the title:

R.L. Stine's Monsterville: The Cabinet of Souls (2015)
https://www.imdb.com/title/tt4386242/

And test notifications.

**Comment by anojht** [comment]
Fix is in develop, please reopen if you the problem exists.
