### ISSUE TITLE
User Importer does not load emby

### ISSUE THREAD

**Issue by Chris221** [tidusjar/Ombi#2231]
#### Ombi build Version:

V 3.0.3293

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

V 3.3.1.18 beta

#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

none

#### Problem Description:

User Importer does not load, it is left with a blank screen and the nav bar

there is some console error from vendor.js, there is a null value

#### Reproduction Steps:

Added it once before setting up emby, now it doesn't load the page anymore no matter how many restarts

**Comment by tidusjar** [comment]
Tried clearing the browser cache?

**Comment by Chris221** [comment]
Yes, and on multiple devices

**Comment by anojht** [comment]
Please update your emby to the latest RELEASE V3.4.1.0 and please try again

**Comment by anojht** [comment]
Closing due to lack of response.
