### ISSUE TITLE
Unable to select the Pending Approval filter

### ISSUE THREAD

**Issue by flyize** [tidusjar/Ombi#2233]
#### Ombi build Version:

V 3.0.3000

#### Update Branch:

Master
#### Media Sever:

Plex

#### Operating System:

Windows

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Unable to select the Pending Approval filter

#### Reproduction Steps:

Requests > Filter button > Under Filter Status, attempt to click Pending Approval.  

It does not work, only Approved and Processing Request work.

**Comment by anojht** [comment]
can you please update to the latest Ombi which is V3.0.3293 and try again

**Comment by flyize** [comment]
Do the automatic updates not work on the version I'm on, or are those handled differently?  I see here on GitHub, there are new releases, but mine shows no update available.
