### ISSUE TITLE
Base url not working for default movie/tv poster images

### ISSUE THREAD

**Issue by mariusch** [tidusjar/Ombi#2234]
#### Ombi build Version:

V 3.0.3291

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Image of the console:
https://imgur.com/MGdnCnI

#### Problem Description:

Base url in settings is set to "/ombi", but default poser images show 404 in console. If I inspect and manually add /ombi/ to the path they show up.

#### Reproduction Steps:

1. Set custom base url
2. Search for movie/TV show with no poster
3. Default poster will not show and a 404 is shown in the console

**Comment by tidusjar** [comment]
did you restart Ombi after setting the base url?

**Comment by mariusch** [comment]
yes

**Comment by anojht** [comment]
The default poster for tv/movie is located on disk and is an absolute file path mapping. Baseurl does not affect it. 

Can you update to the latest release and let us know if you are still facing this issue?

**Comment by mariusch** [comment]
You´re right about absolute path. Inspecting the image path shows 
src="../../../images/default_movie_poster.png" which gives me 404.
Changing it to src="../../../ombi/images/default_movie_poster.png" shows the poster.

Looking at the resources tab it is trying to hit the image from 
https://media.domain.com/images/default_movie_poster.png
and not 
https://media.domain.com/ombi/images/default_movie_poster.png

I dont know the reason behind this but hope the information helps.

Updated to 3.0.3302 and still facing this issue.

**Comment by anojht** [comment]
Sorry, you are right @mariusch looks like the images don't load if you are behind reverse proxy and have baseurl. Thanks for reporting this, I will push a fix

**Comment by anojht** [comment]
Fixed in develop
