### ISSUE TITLE
[Feature Request] More intuitive issue reporting

### ISSUE THREAD

**Issue by TheRealDirtyMike** [tidusjar/Ombi#2236]
This is more of an Enhancement -- Right now the way to report an issue is a bit obscure.. I have had to walk numerous users through the steps to report an issue with a movie or tv show. Could there be a way to search a movie or show (for issue reporting only) on the actual Issues page? Issue reporting and tracking all in one place sort of thing.

**Comment by anojht** [comment]
The landing page is a search page when user login, when they search for a particular content we display the report issue button if that content is in your library and you have enabled issue reporting. I think this is pretty intuitive, its one button, one click.

**Comment by TheRealDirtyMike** [comment]
I understand that issues are reported on the main search page when searching for something. But I have had numerous users, and I am sure other people have as well, that have gone to the "Issues" page to try and report an issue but are unable to and then don't know where to go to report one. I don't believe it is very straightforward that you would then have to go to a different page from where the issues are actually tracked to report something... But that could just be me.

**Comment by tidusjar** [comment]
I do see your point. I'll have a think

**Comment by Byakko22** [comment]
I agree with this post, some users who first logon to just submit a report. for example. They tried to go watch movie A, their first thing is to logon, go to issues and try to submit report on movie A. its natural to go to the issues tab to submit an issue. not when searching(from the user experience the movie search page job is done after request), ive gotten countless texts on how to create an issue. I ended up disabling the feature cause i just got texts on it.

**Comment by TheRealDirtyMike** [comment]
Thank you. No rush at all. Hopefully something can be done and make it a little more user friendly.

**Comment by anojht** [comment]
Merging the discussion here to a proposed implementation on #2647, thanks for your patience guys!
