### ISSUE TITLE
Movie Posters not loading

### ISSUE THREAD

**Issue by hpz937** [tidusjar/Ombi#2241]
#### Ombi build Version:

V 3.0.2328

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Movie posters are showing broken link in the ui. 
example poster for Ready Player One https://image.tmdb.org/t/p/w150//pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg
returns error "Image size not supported" however changing the size to w154 the poster will work.

#### Reproduction Steps:

Go to requests. view movie requests. Backdrops load but posters do not.

**Comment by tidusjar** [comment]
Update.
