### ISSUE TITLE
Jobs run based on GMT and not system clock

### ISSUE THREAD

**Issue by Hossy** [tidusjar/Ombi#2245]
#### Ombi build Version:

V 3.0.3304

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.12.3.4973

#### Operating System:

Linuxserver.io version:- 88 Build-date:- May-09-2018-08:33:59-UTC
https://hub.docker.com/r/linuxserver/ombi/

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Nothing in logs at the time

#### Problem Description:

The Newsletter is currently set to the default schedule of "0 12 * * 5" which means it should run Fridays at 12:00pm.  However, the job just ran at 7am which makes me believe it's working off GMT.  I checked the time on the container with `date` and it reflects the current local time and time zone.

#### Reproduction Steps:

Set a TZ other than GMT and monitor the scheduled jobs.

**Comment by tidusjar** [comment]
Nope, they are running on UTC.

I plan to make the frontend dates to local time at some point.

If you press test it should show your local time.

**Comment by Hossy** [comment]
@tidusjar It does not.  There is no date/time listed on the newsletter test email.  However, at the bottom of the mass email, it shows local time.  But the jobs are not running based on local time.

**Comment by Hossy** [comment]
Oh, lol.  I see it.  Thanks.  And the test does actually say 7am.  So, at least I can use that.
