### ISSUE TITLE
[Feature Request] Recently Added Notifications

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#2247]
#### Ombi build Version:

V 3.0.3293

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.13.0.5023

#### Operating System:

Windows 2012 R2

What I would love to see is a way for multiple users to be notified when a title becomes available.  For example if I search for Avengers Infinity War it shows up as requested because another user had already requested it.  Maybe an button at that point which allows the user to opt into the notifications when that title becomes available.  

This could also be applied to TV shows.  The user opts into notifications for a particular TV show and every time a new episode is released they receive a notification.  

I am currently sending out notifications via Tautulli but there is no way for users to opt in or out of notifications for a particular title and I set everything up manually myself.  I think this could be done far more efficiently in Ombi.

**Comment by tidusjar** [comment]
Feathub for this please. But excellent idea.
