### ISSUE TITLE
Mobile App Not Working

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#2248]
#### Ombi build Version:

V 3.0.3304

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.13.0.5023

#### Operating System:

Windows 2012 R2

#### Problem Description:

I have been trying to Enable Mobile but the setting doesn't stick.  I click the checkbox and then click submit.  When I refresh the page the box is no longer checked.  When I try to use the Mobile App I can connect but I can't search for titles.

**Comment by tidusjar** [comment]
Wrong repo, try the OmbiApp repo next time. 

What version are you on the app? 

In the website where the user drop-down is, do you see open on app option?

**Comment by kewlrobd** [comment]
I reported this here because I figured it had more to do with the Ombi settings then anything else.  

I am trying to use the Ombi Android app that you just released.  Seems to be version 1.0.  

Yes from the drop down I have the option to Open Mobile App.  When I click that on my android phone it opens the app and configures the URL.  When I try to search for something I get no results or error.  Same when I try to use the suggestions.

When I go to the Customization page in my Ombi setup There is a checkbox for "Enable Mobile".  No matter what I do I cant' get that to stay checked so I assumed my installation is not allowing mobile searches.

**Comment by tidusjar** [comment]
@kewlrobd are you using the beta or stable builds from the App Store? 

Also what phone?

**Comment by kewlrobd** [comment]
It's a Galaxy S8+.  

Stable Builds.

**Comment by tidusjar** [comment]
it's mostly likely that it's not setup correctly. Is your Application URL the externally accessible url for Ombi? Because when you press the Open On App button it uses the Application URL to connect to the Ombi API

**Comment by kewlrobd** [comment]
Hmm, it is publicly accessible but I am using some url redirection so that my users don't have to type in the port number and I guess the app couldn't follow the redirection.  I manually the URL manually with the port number and it's working now.  Thanks for pointing me in the right direction.

**Comment by nilankadesilva** [comment]
Can you help me set it up please? I'm facing a similiar problem with the settings not sticking.

**Comment by tidusjar** [comment]
Please open a new issue or jump on discord for help
