### ISSUE TITLE
Performance issues when Android App is being rendered on screen.

### ISSUE THREAD

**Issue by schmittimillian** [tidusjar/Ombi#2249]
#### Ombi build Version:

V 3.0.3304

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

not relevant

#### Operating System:

Windows 10.0.16299
Android 8.0.0

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

```

(no relevant logs)

#### Problem Description:

Severe performance impact when using app. Only happens when app is being rendered (doesn't matter if it's focused or not). See attached screengrab:
https://drive.google.com/file/d/0B8AcBmFMKWw4d2dZMElnQnFoMlVEVk14cWN0enhQTkthVkQw/view?usp=sharing

#### Reproduction Steps:

Install app, open app, see performance issues with app being rendered.

**Comment by schmittimillian** [comment]
Another note: Can't seem to get the 'Open Mobile App' link to do anything on my phone. Click the link from my phone (both firefox and chrome) and nothing happens.

Should I create a separate issue for this?

**Comment by tidusjar** [comment]
https://github.com/tidusjar/OmbiApp Please raise there
