### ISSUE TITLE
Ombi Apache conf file location

### ISSUE THREAD

**Issue by Servh37** [tidusjar/Ombi#2252]
HI All,

I'm new to Ombi, and im trying to fine the Web conf file to apply the Reverse Proxy.

But i'm not able to locate i in the Apache2 filers.

I'm hope you can help with this? or dose this get applied to the stand Apache file 000-default.conf 

Regards

**Comment by infamouswb** [comment]
I do the reverse proxy in the 000-default.conf 

[See instructions here from Wiki](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples)
