### ISSUE TITLE
Latest Ombi is not compatible with libssl1.1

### ISSUE THREAD

**Issue by muhahacz** [tidusjar/Ombi#2259]
Ombi v3.0.3330 is not compatible with libssl1.1 which is a part of openssl package in Ubuntu 18.04,  libssl1.0.0 is working.

Log:
```
We are running on http://*:5000
/opt/ombi
No usable version of the libssl was found
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3330-master
Copyright (C) 2018 Ombi
```

**Comment by tidusjar** [comment]
This is not inside my control. I suggest if you want this you raise a issue with the .net core team.
