### ISSUE TITLE
Settings button gone

### ISSUE THREAD

**Issue by jfairham1** [tidusjar/Ombi#2262]
Apologies I haven't completed the template, but I can't access settings. (this is the issue). 
Rather odd, but the settings button has disappeared. 

![image](https://user-images.githubusercontent.com/6381600/40283935-78981286-5c7e-11e8-82d0-0b0739fb8da3.png)

It is a recent commit, I've had it installed a few weeks. I re-installed latest commit and the problem is the same. 

Thanks

**Comment by tidusjar** [comment]
It's probably to do with your permissions, Only users with the "Admin" role have access to the settings.

Since you have access to the User Management that leads me to believe you have the Power User role.
