### ISSUE TITLE
Forgotten Username/Password

### ISSUE THREAD

**Issue by adriangigliotti** [tidusjar/Ombi#2264]
Hi, 

I forgot my OMBI username/password.. How do I retrieve info?

Cheers

**Comment by tidusjar** [comment]
Did you setup your email notifications? If so you can reset your password.

Otherwise you cannot. There are no 'backdoors' or anything like that.

**Comment by AlexVPerl** [comment]
I'm in the same situation, didn't setup email notifications so unable to use reset password feature. Logged out and forgot initial password.

Any advice on how I can get back in or do I now have to completely uninstall ?
