### ISSUE TITLE
Help understanding notifications

### ISSUE THREAD

**Issue by stretch886** [tidusjar/Ombi#2265]
Sorry not really an issue, more of a question that I couldn't find enough info on in the Wiki.

How are notifications supposed to function for admin and users?  Are users notified via email or any other method when their requests are approved or available?  I have Pushbullet setup as the admin for request notifications.  However when logged in as a test user, I (as the admin) still get notified when requests are approved or available.  Shouldn't that be going to the user rather than admin?

Just trying to configure things properly for myself and my users.

Thanks for any help.

Using version 3.0.3304

**Comment by tidusjar** [comment]
Hey no problem,

So currently the only information we have about users is their Email address and their mobile device (if they are using the app).

We currently do not store any other information e.g. discord username.

So the only way for users to get notifications at the moment is via email or mobile push notification.

In the future, I plan to add extra information to the user e.g. Pushbullet ID so they can receive notifications via other means.

**Comment by stretch886** [comment]
Hey sorry for the delay here, but I wanted to clarify my question.

Currently if a user makes a request, and I approve it, I end up getting the Pushbullet notification "your request has been approved".  So A) Can I turn that off, since I don't need to be notified that I approved a request? and B) can you verify what's supposed to happen for a regular user after approval and marked  available?  Do they get notifications via their Plex email that these events have occurred?

Thanks. Great program.

**Comment by tidusjar** [comment]
You can turn it off by going into the pushbullet settings and disabling the approved template on the right hand side. Yes users will be notified via their Plex email

**Comment by Kryptonit3** [comment]
I am the admin on my Ombi instance. How do I set it up to get a notification of a user request? I thought this was a default feature. I turned on Pushover and tested it to work. I logged in a day later and saw user requests but no notification on my Pushover. I approved the request and also got the "your request has been approved" notification.

**Comment by Kryptonit3** [comment]
Just realized that it sends an email... any way to send a notification with like pushover etc?

@tidusjar

**Comment by Nabukodonosor** [comment]
I have the same issue as @stretch886 had, but I'm using Pushover. How to solve it?
