### ISSUE TITLE
Error calling /api/v1/Update/develop

### ISSUE THREAD

**Issue by zybron** [tidusjar/Ombi#2268]
#### Ombi build Version:

V 3.0.3340

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I get the following error when attempting a GET request from the /api/v1/Update/develop endpoint:
```
{
  "error": "Index and length must refer to a location within the string.\nParameter name: length"
}
```

#### Reproduction Steps:

Call the endpoint specified with or without an access token and the same error is returned.

**Comment by samwiseg00** [comment]
This has already been resolved. You will need to manually update to the latest.
