### ISSUE TITLE
Updated the Theme now i cannot access Ombi to chnage it back

### ISSUE THREAD

**Issue by zionvp** [tidusjar/Ombi#2269]
#### Ombi build Version:

V 3.0.3291-develop

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Arch Linux 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Just for testing i was seeing if i could setup the broken theme and see what was broken, now i cannot login back to change it back. i get the error {"error":"Object reference not set to an instance of an object."}. Is there a config file i can edit to fix this?

#### Reproduction Steps:

Change the theme to the builtin broken theme, logout.
try accessing the url again and the error is displayed.

**Comment by tidusjar** [comment]
Update, you are on a old version
