### ISSUE TITLE
Installation question...

### ISSUE THREAD

**Issue by KipourosV** [tidusjar/Ombi#2270]
Hello, 

Finished installing inside an LXC container. My plex is also on a seprate LXC container.
So on the first time setupbthe aquire token does not work 
(probably because there is no plex running on the same machine)
But when I use plex login, I get to the screen where it says:
Plex Authentication, Please Wait
and that's it. It stays there.

Can someone enlighten me? What am I doing wrong?
Do I need to install ombi on the same machine as Plex?

Thanx!

**Comment by kewlrobd** [comment]
They don't need to be on the same machine.  In Settings > Media Server > Plex, when you put your plex credentials in and you click 'Load Servers" you don't get a new drop down menu with your list of servers?

**Comment by KipourosV** [comment]
When tried installation on seperate container, the preliminary setup never finished.

I managed to make it work on the same container as plex...

**Comment by tidusjar** [comment]
We contact Plex.tv to get information about the server, it does not need to be on the same machine.

What is the issue here?
