### ISSUE TITLE
Package source for linux - 404

### ISSUE THREAD

**Issue by Greg2dot0** [tidusjar/Ombi#2272]
#### Ombi build Version:

V 3.0.3330

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Seems that the package repository for updates is MIA.

Err:10 http://repo.ombi.turd.me/stable jessie Release
404  Not Found

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Please look at the wiki. 

This is not managed by myself.
