### ISSUE TITLE
Zombie processes spawned by auto-update process.

### ISSUE THREAD

**Issue by maran** [tidusjar/Ombi#2279]
#### Ombi build Version:

V 3.0.3185 

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04 LTS

#### Problem Description:

Ombi can't auto-update on Linux. This in itself is not much of a problem but sadly it spawns a Zombie sh session on every attempt. I already have thousand of processes running.

The error is something like this (got it from the original ticket)
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
Aborted (core dumped)
```

I understand that auto-updating on Linux is currently not very stable so it would be great if the whole option to 'check' auto-updating could be removed on linux unless there is a custom script given. Or if the zombie problem could be fixed.

#### Reproduction Steps:

Check the "Auto update" feature in settings and wait.

**Comment by tidusjar** [comment]
Know issue. Please see #1460
