### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by giacomofabbri** [tidusjar/Ombi#228]
Hi! I'm not sure whether what is, but I'd like to see the movies name and maybe also the little description under the title in Italian as its my main language, I think also the check that PlexRequest do to Plex Library is name based so every-time I add new Italian named movies it doesn't check the Available, but I'm not exactly sure how does it works, if it doesn't work this way then I think its kind of broken because of 5 movies that I added that I had requested just Kung Fu Panda was checked Available!
Thanks for all and sorry for my English!

**Comment by tidusjar** [comment]
Hello, 

I have had localisation in the back of my mind, the difficult thing about this is we get all of our Movie and TV Data from other providers that do not provide consistent language options for me to use.

The way we check Plex is something we have to put up with, Plex does not provide us with any sort of ID or unique key we can match on, so the only option we have to to make sure the Title and year are the same. So if the title is vastly different to what was requested then we will not be able to find it in Plex.

Does this answer your questions?

**Comment by giacomofabbri** [comment]
Mostly! Obviously you answered me about how PLexRequest find the match with that library and that's how I imagined, about my other question I'm not sure to understand, I mean with the Meteor version I was able to set the Italian language via the search.js file and I thought they shared almost the same code, that's why I asked, at least you should allow to "expert" user to modify some string in the js file.
I had another problem, I'm trying to execute the program even if I'm not really executing using your guide https://github.com/tidusjar/PlexRequests.Net/wiki/Installing-on-Debian-Ubuntu#create-an-upstart-script-to-auto-start-plexrequests-with-your-system-using-port-80-in-this-example
but i'm not able! I tried thousand times but overtime it fails, sorry for all the trouble and I hope to get answered, thanks for all!

**Comment by tidusjar** [comment]
Ok, 

We do not share any code actually, they are wrote completely different using different languages and ways to do it. So when you set the language, what actually is happening, the search results are coming back in a different language? 

Regrading the upstart script, I am not sure as I did not create that. @Drewster727 are you able to assist with this?

**Comment by giacomofabbri** [comment]
Every time I add a movie that it's translated differently in Italian, I'm able to find it by the Italian name for example "Il silenzio degli innocenti" but after I find it obviously it's in the English one "The silence of the lambs" so even if I'm able to add movies by the Italian name I'm not able then to see the requested one always in the Italian language! About the other matter I hope that @Drewster727 will help me, BTW I'm using Ubuntu if it might help you!! 
P.S. I hope that you will add the language personalization
Thanks as always ;)

**Comment by tidusjar** [comment]
@giacomofabbri One more question, so is the requested title in Italian?

**Comment by giacomofabbri** [comment]
Maybe I was not clear IDK, anyway when I type the Italian name of a movie, it appears but it's all in English both the title and the description and that's all, I hope that answer your question!

**Comment by tidusjar** [comment]
I get it! I will take a look!
