### ISSUE TITLE
Ombi Stable says there is a new update available on latest stable version

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#2281]
#### Ombi build Version:

V 3.0.3346

#### Update Branch:

Stable

#### Operating System:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

No applicable logs

#### Problem Description:

When I go to Settings > System > About, Ombi states that there is a new update available even though I am on the latest stable release.

#### Reproduction Steps:
Go to Settings > System > About

**Comment by McGriddle** [comment]
Can confirm. LinuxServer docker container running on ubuntu 16.04.

**Comment by EvilTactician** [comment]
Also confirming, Ubuntu 16.04 manual install.

**Comment by anojht** [comment]
Commit: f03473c47ea5eeda63494bdcc0967a31c96d7184 should fix this, thanks for reporting!
