### ISSUE TITLE
Cannot get past the installation wizard

### ISSUE THREAD

**Issue by diskmaster23** [tidusjar/Ombi#2282]
#### Ombi build Version:

V 3.0.3346-master

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

3.53.4

#### Operating System:

LXD/LXC Promox Debian GNU/Linux 9

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

root@plex:/opt/Ombi# ./Ombi
ello, welcome to Ombi
Valid options are:
Ombi 3.0.3346-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on http://*:5000
/opt/Ombi
Hosting environment: Production
Content root path: /opt/Ombi
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
dbug: Ombi.Controllers.PlexOAuthController[0]
      Adding first server



```

#### Problem Description:

Cannot get past the Wizard process. Cannot add a user. Cannot add a Plex Server. Adding a user gives me the pop-up error on the website "There was an error... You might want to put this on Github...". However, the log file, doesn't tell me anything when I try to add an user, but it tells me when I try to add the server.

I've tried previous versions, but I have not been able to get beyond this Wizard screen.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Install the latest version by extracting the gz file. Run it via ./Ombi. Try to put user admin/admin, get the "There was an error... You might want to put this on Github..."

**Comment by tidusjar** [comment]
What's in your browsers console when this happens from a fresh install?

**Comment by diskmaster23** [comment]
Not sure if this is helpful, here is some information.

`6/3/2018, 12:49:00 PM - Received message:  pb.js:39:9
Object { type: "nop" }  pb.js:39:9`

`pb.rollingLog = []
pb.log = function(message) {
    try {
        var line
        if (message instanceof Object || message instanceof Array) {
            line = message
        } else {
            line = new Date().toLocaleString() + ' - ' + message
        }

        **console.log(line)**
        pb.rollingLog.push(JSON.stringify(line))

        if (pb.rollingLog.length > 400) {
            pb.rollingLog.shift()
        }
    } catch (e) {
        console.error(e)
    }
}`

**Comment by tidusjar** [comment]
That doesn't look like it#s ombi related. Is there anything else?

**Comment by diskmaster23** [comment]
If there is, I am not experienced enough to find what you might be looking for. I've looked in syslog, nginx logs, messages, journalctl, and nothing seems to come up when the error occurs. The odd thing is, I can run Ombi on my laptop, get through the wizard, copy the contents to the machine I am erroring out on, and everything works fine. It just stops at the Wizard part. 

Is there a debug mode for the CLI?

**Comment by tidusjar** [comment]
LXC container! Interesting, can you do this: https://github.com/tidusjar/Ombi/wiki/Common-Errors#proxmox-lxc-containers

**Comment by diskmaster23** [comment]
Okay...fixed by redoing locales. 

For others, double check to see if no other locales are installed and make sure it is defaulted to en_US.UTF-8. I had en_US.UTF-8 installed, but it defaulted to something else.
