### ISSUE TITLE
Auto approve should not override the request limits

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2284]
#### Ombi build Version:

V 3.0.3330
-- | --

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I had all my users set to auto approve but I set limits of 3 movies and 3 "episodes" (I didn't know if it was actual episodes or entire shows, this should be explained BTW) and I had a user put in 63 requests and fill my hard drive (Not understanding that they take up space, lol)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I tried again to set the bulk edit again this morning and it still doesn't stick for that field. All other fields seem to work fine

**Comment by tidusjar** [comment]
AHH. Auto Approve overrides the limits... It probably shouldn't but it does currently

**Comment by WeirDave** [comment]
Well that explains how the user could make that many requests! lol Okay well that's not a very intuitive feature. Additionally, I'd like most users the ability to just make requests but I don't want them overloading my hard drive so I placed limits. I would also like to suggest to add "shows" instead of episodes or in addition to them so that I can limit the amount of shows that can be requested. Because now they can click the add all seasons and show and it could be 15 years worth of shows!

**Comment by tidusjar** [comment]
This now works as expected in the develop branch
