### ISSUE TITLE
Shows still showing as Processing once downloaded

### ISSUE THREAD

**Issue by derekoharrow** [tidusjar/Ombi#2285]
#### Ombi build Version:

V 3.0.3330
--

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Queued a series of a TV show to download. Sonarr has done a search and queued the episodes in SABnzbd. SABnzbd is downloading fine. Shows are being downloaded individually, not as one download. SABnzbd is performing post-processing ok and both Plex and Sonarr see the new episodes as they are downloaded.

In Ombi, however, all the episodes in that series are still showing as "Processing request".

#### Reproduction Steps:

As above.

**Comment by tidusjar** [comment]
Update to latest. This is fixed

**Comment by tscibilia** [comment]
im running 3.0.3383 and im still having this issue. please let me know if there's and additional info i can provide or if i should open a new issue.

**actually to be more specific:** if i search for a movie I requested that i know is available on plex it shows available however on the requests list, it never marks the movie as 'available' (it only says 'processing request')
