### ISSUE TITLE
Oculus and SteamVR load when accessing Ombi

### ISSUE THREAD

**Issue by SaskiFX** [tidusjar/Ombi#2286]
#### Ombi build Version:
3.0.3111 

#### Update Branch:
master

#### Media Sever:
Plex

#### Operating System:
FreeNAS

#### Problem Description:

This is a strange one. Anytime I open the Ombi page in my browser (Firefox) either directly, through Organizr, or Muximux: Oculus and SteamVR both launch thinking I have opened a VR related application. I'm not really even sure where to start looking to provide more information on this one. :)

#### Reproduction Steps:
Just opening Ombi. I can make a video of it happening if it helps.

**Comment by tidusjar** [comment]
wtf.

Does it only happen in firefox?

**Comment by tidusjar** [comment]
Check this out: https://support.mozilla.org/en-US/questions/1174025

**Comment by anojht** [comment]
This maybe an issue with steam VR or firefox. Closing this as Ombi has nothing to do with this.

**Comment by Kyrluckechuck** [comment]
Getting this as well, specifically when Ombi is open and *only* when Ombi is open. Closing the tab resolves it and opening it retriggers it

**Comment by SaskiFX** [comment]
The Firefox adjustment mentioned elsewhere in the thread did fix it for me.

**Comment by Kyrluckechuck** [comment]
While the above does *stop* it, it doesn't fix it as now openvr is disabled browser wide and I have to   enable and restart it again in order to use any actual openvr related webvr applications...

**Comment by TheManchineel** [comment]
Can confirm this still happens on the latest and greatest Firefox, however now it asks for permission for each VR website, so you can simply deny Ombi permission to use WebXR and it won't bother you anymore. Would be interesting to see what exactly causes Firefox to deem a webpage "VR compatible".
