### ISSUE TITLE
SMTP server not saving

### ISSUE THREAD

**Issue by brimnac** [tidusjar/Ombi#2287]
#### Ombi build Version:

3.0.3346

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

unRAID

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

System constantly says I have to fill in the SMTP settings, and I have done so and successfully received test emails. Used Gmail, set up an App Password. Using unRAID latest LSIO version, as far as I know.

#### Reproduction Steps:

Add SMTP settings for gmail account. Test and Submit. Navigate to User Management. All "Send Welcome Email" links are grayed out. When I click on Edit User and attempt to send a Password Reset Link it tells me "You need your SMTP settings setup". Not sure where else to go to place those. 

Newsletter looks like it is working.

**Comment by tidusjar** [comment]
You also need to setup your application URL in the Customization settings. That needs to be the external URL for ombi.

**Comment by brimnac1022** [comment]
Thanks - can the error be cleaned up to state that? I just found it extremely confusing that it was stating my SMTP needed the work. 

Thanks a ton, I don't know if that is a feature request or not.
