### ISSUE TITLE
Requests page does not refresh properly after a request is removed

### ISSUE THREAD

**Issue by ChrisColotti** [tidusjar/Ombi#2288]
#### Ombi build Version:

V 3.0.3346

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.0.5023

#### Operating System:

Linux/Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Not a major issue, but I have just noticed that if you "remove" a request the page does not refresh to show the remaining requests it just is blank.  If you click refresh in the browser then it seems to shwo the remaining items.  Not quite sure why that is happening.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by YodaSpow** [comment]
I discovered this to on version: 3.0.3330

**Comment by tidusjar** [comment]
Fixed in develop
