### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2290]
Add links to the users Ombi page in emails regarding requests to make it easier to "Log in and approve" the request.

**Comment by tidusjar** [comment]
you can already do this:

https://github.com/tidusjar/Ombi/wiki/Notification-Template-Variables

Use the `{ApplicationUrl}` e.g. `<a href="{ApplicationUrl}">Click here to Login</a>`

**Comment by WeirDave** [comment]
Well that soles "some" of the issue but it would be nice to have a way to click on a link in that email that takes you a list of requests that need your approval.
