### ISSUE TITLE
Android App - empty main page

### ISSUE THREAD

**Issue by SoulInfernoDE** [tidusjar/Ombi#2291]
#### Ombi build Version:

V 3.0.XX / newest docker image

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

newest plex pass version

#### Operating System:

(server: Synology Debian linux with docker ui/Android 8 with Huawei EMUI (Honor 8 Pro) )

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Install Android App
Open Android App
Go to Ombi Website with Chrome or Firefox
Log in
Press Mobile App under Admin/user
App keeps empty
Settings say connection successful)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Please open app issues here:
https://github.com/tidusjar/OmbiApp
