### ISSUE TITLE
Some checkboxes not clickable in Safari

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2298]
#### Ombi build Version:

V 3.0.3346

#### Update Branch:

stable

#### Operating System:

Server: Debian 8
Client: MacOS/Safari (latest)

#### Problem Description:

Checkboxes in the mass email settings are not clickable with Safari, only "select all" is.

#### Reproduction Steps:

Open the glorious Safari Browser, load obi website -> settings -> notifications -> mass email
Try to click the checkbox of a user.

Edit: Same issue on iOS/Safari

**Comment by tidusjar** [comment]
Can you please try this in the develop branch?

**Comment by hagabla** [comment]
Same issue.

**Comment by tidusjar** [comment]
Can you please try this in develop now?

**Comment by tidusjar** [comment]
this was fixed
