### ISSUE TITLE
Can't see anything on the Issues page

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2300]
#### Ombi build Version:

V  	3.0.3330

#### Update Branch:

 	master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.1.5063

#### Operating System:

Windows 10 V 1803

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When I click on the "issues" page only the title shows. I have created 3 categories "Movies", "TV", and "Subtitles". I am not sure if it is a bug or there is something else I need to do but I am unclear on.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by anojht** [comment]
This is how the issues page looks until you raise issues. You can raise issues by clicking the report issue button on content that you search for or have already requested. Refinement of the issues page is already suggested and will be made sometime soon.

**Comment by WeirDave** [comment]
OKay so just to make certain I understand you. Currently only searched for items can be brought up on the issues page?

**Comment by anojht** [comment]
You can report issues on content that is available in your library. Regardless of whether a request was made through Ombi.
