### ISSUE TITLE
TV Show request does not show user who requested it

### ISSUE THREAD

**Issue by Brianbrifri** [tidusjar/Ombi#2302]
#### Ombi build Version:

V 3.0.3368

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Linux 4.14.40-unRAID

#### Problem Description:

When a user requests a TV Show, the user who requested the TV Show does not show up in the information about the TV Show
#### Reproduction Steps:

1. Request a TV Show.
2. Click on Requests tab
3. Go to TV Shows tab
4. Notice that `Requested By:` is not visible in information about TV show
5. Notice also that `Request Status:` and `Request Date:` is not visible (compared to Movies)

**Comment by anojht** [comment]
Requested By: is visible when clicking the view button on a particular show. Requested Satus: is now Satus: and is visible on the TV cards. Only thing that is not visible is Request Date:
