### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2303]
#### Ombi build Version:

V 3.0.XX

  | 3.0.3330
-- | --

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Nothing in the log file to support understanding what happened and why it won't update

```

#### Problem Description:

Auto Update says it triggers a cron job but nothing has updated

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by anojht** [comment]
This is a known issues #1460 

Please read the wiki and browse the Github issues before opening issues.
