### ISSUE TITLE
Make the subscribe button more visible

### ISSUE THREAD

**Issue by chrischm** [tidusjar/Ombi#2309]
It would be nice to have this a formed button like the request and report button like I see under the Tv Collum.  Under the movie or search section I only see a tiny button that is really confusing to most of my users.  Another suggestion would be to not allow you to subscribe to your own request

**Comment by tidusjar** [comment]
You should be able to subscribe to your own request

**Comment by chrischm** [comment]
Thank you, it does look like in the newer build my issue is resolved for the subscribe button appearing on your own post. I guess the only thing I would recommend so that is user for users to see is have the subscribe button be uniform across the board to match the button in the TV section. My users have complained "they can't find this button" or "it takes me a minute or so to find it"
![subscribe](https://user-images.githubusercontent.com/40046152/41167294-1df4c016-6b08-11e8-88f5-8aacbb934620.PNG)
![subscribe2](https://user-images.githubusercontent.com/40046152/41167295-1e0fdcde-6b08-11e8-9528-81fedd2e3b42.PNG)

**Comment by tidusjar** [comment]
Done in development
