### ISSUE TITLE
Movie Requests do not show unless you type something in search bar

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2310]
#### Ombi build Version:

V 3.0.XX

Version | 3.0.3383
-- | --

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Currently when entering the page for the first time, movie requests do not show up until you type something in the search bar. As soon as you do all movies show and the filters will work accordingly

#### Reproduction Steps:

Go off the requests page to the issues page. Then back to the requests page. No movies show. Type even a single letter and hit enter. Movies now show

**Comment by tidusjar** [comment]
Have you tried clearing the cache? I cannot reproduce this.

**Comment by WeirDave** [comment]
Please explain how I am to do this and I will test immediately.

**Comment by anojht** [comment]
If you are using chrome press F12, right click the reload/refresh button choose the third option. To fully clear your cache.

**Comment by WeirDave** [comment]
Ok you meant the browser cache. Thanks I will try
