### ISSUE TITLE
Server removed

### ISSUE THREAD

**Issue by molbdron** [tidusjar/Ombi#2311]
#### Ombi build Version:

Ombi 3.0.3111-master

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.2.5142

#### Operating System:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-06-07 11:03:46.180 -04:00 [Information] 1 servers were removed due to timeout
2018-06-07 20:00:34.469 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-06-07 20:02:04.581 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-06-07 20:04:04.646 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-06-07 23:00:41.430 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-06-07 23:01:26.463 -04:00 [Information] 1 scheduled job(s) enqueued.
2018-06-07 23:02:26.537 -04:00 [Information] 1 scheduled job(s) enqueued.

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Greetz,

Thank you for the awesome project!
 It appears my Plex server is no long connected to Ombi! Plex is running and active. I have been running Ombi for a few months (Did I say nice project????). I went to log in to add more folks to the newsletter and I can no longer login! I have seen in issues, best to have non Plex user as an admin so you can get in. *SMH* I was not so enlightened when I got the build running.

I attached the output in the logs which shows a server was removed for timeout. Is that something I can add to Omni.db? I am not an SQL, sqlite3 expert by any means. Just learning some of the CLI to browse tables etc.

Would I be able to perhaps, insert the Plex server IP and token to reestablish connection or, should I consider this a valuable lesson and move/delete Ombi.db and make a better educated approach to the project?

Any consideration is greatly appreciated!

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Update to the latest version and you should be good to go!
