### ISSUE TITLE
Email notification poster url incorrect

### ISSUE THREAD

**Issue by aptalca** [tidusjar/Ombi#2312]
#### Ombi build Version:

V 3.0.3383

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

PlexPass

#### Operating System:

Linuxserver.io docker

#### Problem Description:

Email notifications are enabled. Some e-mails contain correct poster urls for items, some don't. The e-mail messages and templates are all default

#### Reproduction Steps:

New Request email: correct poster link
Request Approved e-mail: incorrect poster link
Request Available e-mail: incorrect poster link

When I compare the correct and incorrect links, I noticed that the incorrect link misses a `/` between w300 and the image id.

Here's a correct link (without the google proxy):
`https://image.tmdb.org/t/p/w300/AdQDz4LF6BzFfmyIJkMtrj707BZ.jpg`
And here's an incorrect link:
`https://image.tmdb.org/t/p/w300AdQDz4LF6BzFfmyIJkMtrj707BZ.jpg`

**Comment by tidusjar** [comment]
Fixed in develop
