### ISSUE TITLE
Add Lidarr

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#2313]
Please use the reaction buttons below this post if you want lidarr added into ombi.

**Comment by Haywood78** [comment]
HECK YA!!! You da man Tidusjar. Great software, adding Lidarr support will only make it even greater. Thank you for all the work that you do. You are truly a WIZ!

**Comment by tidusjar** [comment]
29 👍 and 9 ❤️ ... Looks like I'm doing this

**Comment by Haywood78** [comment]
You da man! OMBI ON!!!

**Comment by HamilcarH** [comment]
Awesome that you’re working on this !

I’d be happy with artist requests only !

**Comment by neuman1812** [comment]
Just installed Lidarr and Ombi this week.  Would love to see them connected

**Comment by tidusjar** [comment]
Hey man. I'm maybe half way there. You can check the project on GitHub to see the status

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/projects/4

**Comment by beloware** [comment]
:bigthumbsup: :1st_place_medal:

**Comment by tidusjar** [comment]
You guys better appreciate this, been working my ass off on this the past few days.

**Comment by cpcolella** [comment]
This is going to be good. I love ombi. I'm so excited for this new feature! You're the man.

**Comment by tidusjar** [comment]
It's already available in the development builds

**Comment by alexjustesen** [comment]
Don't worry we won't give you flacc for it taking a while 🤣😂

**Comment by ansuz07** [comment]
Love it - works great on the dev build.

One thing I noticed, though - you can only see the search tab for music on the main page if you are an admin, even if you have the request music profile enabled for the user.

**Comment by tidusjar** [comment]
That bug has been fixed in the develop build. I am now closing this Issue since it's available in develop.

Please can someone download the dev builds and mess around with it so we can iron out any bugs before I push this live?
Thanks.
