### ISSUE TITLE
Data validation to Application URL

### ISSUE THREAD

**Issue by jarkle** [tidusjar/Ombi#2315]
Data validation should be added to Application URL field when saving. 

Currently if an invalid valid is input into this field and oath is enable the oath button on the login page will not function.

**Comment by tidusjar** [comment]
Define valid?

**Comment by jarkle** [comment]
Valid: http://ciplex.tk
Invalid: 127.0.0.1

**Comment by tidusjar** [comment]
Technically they are both valid. That field is not only used for OAuth.

**Comment by jarkle** [comment]
Is it by design that if you enter an ip address that the oath stops working?

**Comment by tidusjar** [comment]
IP addresses do work with OAuth. Maybe not without the scheme though. I've not tried. Closing this for now until I think of a better way.
