### ISSUE TITLE
Bulk Edit not updating / overwriting request limits

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#2318]
#### Ombi build Version:

V 

  | 3.0.3383
-- | --

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When using bulk edit to manage users, expected behavior is to overwrite what is currently present. It does not overwrite the request limits at this time.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Cannot reproduce.

The bulk update seems to overwrite the limits. 

For example current limit is set to 10 for 3 users, bulk edit them and set the limit to 15 and press Update.

Edit the user and you will see the limit set to 15

**Comment by WeirDave** [comment]
If I set the limit to 15 then check the users they are at 15. If I go back in and set the limit to "0" (Zero they stay on 15. Actually tested with a bunch of numbers. The only number that doesn't work for me is "0". or set to no limits as I understand it.

Also as a suggestion it would be great to have a "defaults" ability
