### ISSUE TITLE
{UserName} and {Alias} notification variables do not resolve in Welcome E-mail sent to user.

### ISSUE THREAD

**Issue by flyryan** [tidusjar/Ombi#2321]
#### Ombi build Version:

V 3.0.3383

#### Update Branch:

Master

#### Operating System:

Windows 10

#### Problem Description:

The notification variables {UserName} or {Alias} when used in the Welcome E-mail notification do not resolve to the recipient's UserName/Alias. Instead, they resolve as blank. The expected behavior would be to resolve the variable to the associated UserName/Alias of the e-mail recipient (as they do for Newsletters). This would allow for personalization of the e-mail (ie: "Hello {Alias}!") and informing a new user of their username (ie: "Your login is: {UserName}").

#### Reproduction Steps:

Add {UserName} and/or {Alias} to the Welcome E-mail template and then send a welcome e-mail to a user.

**Comment by kmlucy** [comment]
I am on 3.0.3407 and am still having this issue. Specifically, those two fields are not resolving in the issue related notifications.
