### ISSUE TITLE
Searching for a show with the word "type" in it seems to not work properly.

### ISSUE THREAD

**Issue by ajhong2** [tidusjar/Ombi#2323]
#### Ombi build Version:

V 3.0.3368

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Unraid

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I found this out when one of my users tried to request a show called "The Bold Type". After some research it looks like shows with the word "type" seems to be broken. TVDB only shows 3 shows listed in that way, but this was a strange bug I noticed. It doesn't seem to be broken for movies.

https://www.thetvdb.com/search?q=type&l=en

#### Reproduction Steps:

Search for a show like "The Bold Type" or "Type 16".

**Comment by ajhong2** [comment]
When starting to type the word "type" as you get to the "p". It briefly flashes the show that should be showing up.

**Comment by tidusjar** [comment]
This is because TVMaze has no information about those shows. E.g. no tvdbid

**Comment by ajhong2** [comment]
That's odd, I thought Ombi used TVDB. Here is the link I found for tvmaze. https://www.tvmaze.com/shows/15324/the-bold-type

Like I had mentioned it does appear for a flash while typing in the word, but then vanishes with no results.

**Comment by tidusjar** [comment]
Ombi uses TVMaze   but we get the tvdbid from TVMaze. Their api doesn't contain the tvdbid for those results.
