### ISSUE TITLE
Feature Request:  View On Emby

### ISSUE THREAD

**Issue by mpearon** [tidusjar/Ombi#2328]
#### Ombi build Version: 

**3.0.2970**

#### Update Branch:

**master**

#### Media Sever:

**Plex and Emby**

#### Media Server Version:

**N/A**

#### Operating System:

**Ubuntu**

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

Would it be possible to add a "View on Emby" button like there is for Plex?

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
Update to latest, this was added but you are on a really old version

**Comment by mpearon** [comment]
Thank you, @tidusjar !  Indeed, I was running a very old version.  Thank you for your quick response!
