### ISSUE TITLE
TV shows do not mark as available once downloaded

### ISSUE THREAD

**Issue by goose-ws** [tidusjar/Ombi#2333]
#### Ombi build Version:

V 3.0.2935

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

n/a I think? 

#### Operating System:

Debian stable x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Will provide if requested/necessary

```

#### Problem Description:

When a user requests a TV show, once Sonarr grabs it, Ombi will not mark it as available. This issue does not happen for movies/Radarr. I've experienced this issue when requesting all seasons, and most recent season only.

#### Reproduction Steps:

n/a

**Comment by tidusjar** [comment]
You are on a old build. Please update.
