### ISSUE TITLE
Ombi self update falsely reports being up to date

### ISSUE THREAD

**Issue by goose-ws** [tidusjar/Ombi#2334]
#### Ombi build Version:

V 3.0.2935

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

n/a I think? 

#### Operating System:

Debian stable x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-06-18 02:00:44.426 -04:00 [Information] 1 scheduled job(s) enqueued.

```

#### Problem Description:

I opened issue #2333 and was told my Ombi is out of date. When I go to the update page, Ombi reports that it is already up to date.

#### Reproduction Steps:

Open Ombi, go to System > Update > Check for update

![screenshot_20180618-053403](https://user-images.githubusercontent.com/874014/41530705-0d369574-72bf-11e8-89f9-ee98e578b438.png)

**Comment by tidusjar** [comment]
Fixed in the later versions.
