### ISSUE TITLE
Request: Support multiple Radarr/Sonarr

### ISSUE THREAD

**Issue by mattmac24** [tidusjar/Ombi#2335]
I have one instance setup of Radarr/Sonarr for each of 4K, 1080P and 720P content.

Are there any plans to support pushing/pulling info to multiple instances of Radarr/Sonarr?

Thanks

**Comment by tidusjar** [comment]
No plans as it's never been asked

https://feathub.com/tidusjar/Ombi

**Comment by xfouloux** [comment]
I would like this feature too,

i have 2 radarr (one for movies in original version, and one for movies in french, same for radarr, one for original version, and one for multilang), I need to add manually in the other when user request something :/

**Comment by goldenpipes** [comment]
U can run a second instance of ombi just like a second radarr or sonarr

**Comment by xfouloux** [comment]
If i do that then my users have to request in both ombi. Not better :/

Le mar. 30 avr. 2019 à 17:06, goldenpipes <notifications@github.com> a
écrit :

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
