### ISSUE TITLE
TV Show Notification via discord has half empty notifications

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2338]
#### Ombi build Version:

3.0.3407

#### Update Branch:

stable

#### Operating System:

Debian 8

#### Problem Description:

discord notification on tv show request filled looks like this:
https://imgur.com/a/ZDdaUWb
Works fine with movies

**Comment by tidusjar** [comment]
Cannot reproduce, seems to be working fine for me

**Comment by hagabla** [comment]
Weird, I can reproduce it 100% of the time. On discord another guy mentioned the same yesterday.

**Comment by tidusjar** [comment]
Any specific TV shows? What's the template set as in the settings?

**Comment by hagabla** [comment]
Every TV Show

template is the default one.

Hello! You   {Title} on {ApplicationName}! This is now available! :)

**Comment by tidusjar** [comment]
Does it happen when you manually mark something as available or only when Ombi automatically marks it?

**Comment by hagabla** [comment]
automatically, never tried manually

**Comment by tidusjar** [comment]
Can you try manually for me?

**Comment by tidusjar** [comment]
Found it, Fixed in develop
