### ISSUE TITLE
Welcome emails don't get sent out when clicking the button

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2341]
#### Ombi build Version:

3.0.3407

#### Update Branch:

stable

#### Operating System:

Debian 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

nothing in logs

#### Problem Description:

Welcome emails don't get sent out when clicking the button. There is nothing in the ombi logs. smtp logs show no attempt of connecting. Email settings are fine, test email goes through.

**Comment by xXZaretXx** [comment]
Have you activate the Checkbox in notifications for email - welcome email ?

**Comment by hagabla** [comment]
I have not, works if I enable it. Thanks. Would not have thought of enabling it in email settings when I manually press the send button.
Still Ombi should not say "welcome email sent" if it does not actually send it and why have the button there if it does nothing, if not enabled in settings.

**Comment by xXZaretXx** [comment]
i had the same error last week ;) yes i agree with you that ombi shouldn't say that

**Comment by tidusjar** [comment]
Is this when the Welcome Email template is disabled in the Email settings?

**Comment by hagabla** [comment]
Yep

**Comment by tidusjar** [comment]
Fixed in develop
