### ISSUE TITLE
Ombi API breaks when ran as a service user in linux

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#2342]
#### Ombi build Version:

V 3.0.3408

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
There are no errors on the server side. 

#### Problem Description:

After version 3.0.3385 I am unable to run Ombi as a service user it must be ran as root. 

#### Reproduction Steps:
setup ombi 
run as a service user with no login
Start ombi and navigate to the webui

you can also hit the API and see the error. 
`/api/v1/Update/develop` it throws this error `{"error":"error:2006D002:BIO routines:BIO_new_file:system lib"}`

```
ombi:x:1004:1004::/home/ombi:/bin/nologin
```
The workaround right now is to run Ombi as root and then everything works correctly.

Perms on the folder/files have been verified and are set to `ombi` correctly. 

Errors on the client side. 
![unknown](https://user-images.githubusercontent.com/2241731/41624555-136fd60a-73e4-11e8-83c5-fb9ab372f935.png)

**Comment by tidusjar** [comment]
and version `3.0.3385` works fine?

**Comment by samwiseg00** [comment]
Yes. As soon as I downgrade everything returns to normal.  
 
 
>  
>    
>

**Comment by tidusjar** [comment]
Please can you check against the latest dev.

**Comment by samwiseg00** [comment]
now it wont start at all with error
```
Jun 27 08:45:21 nightwing.watch-tower.net Ombi[15661]: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyTo
Jun 27 08:45:21 nightwing.watch-tower.net Ombi[15661]: at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
Jun 27 08:45:21 nightwing.watch-tower.net Ombi[15661]: at Ombi.Store.Context.OmbiContext..ctor() in C:\projects\requestplex\src\Ombi.Store\Context\OmbiContext.cs:line 18
Jun 27 08:45:21 nightwing.watch-tower.net Ombi[15661]: at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 48
```

**Comment by camjac251** [comment]
I get the same error as @samwiseg00 on the latest develop build for linux.

**Comment by tidusjar** [comment]
Should all work now guys

**Comment by samwiseg00** [comment]
Confirmed fixed. Thanks!
