### ISSUE TITLE
Plex Authorization Bug - Can't Get Past Wizard

### ISSUE THREAD

**Issue by kev0153** [tidusjar/Ombi#2347]
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.2.5154

#### Operating System:

Linux - Ubuntu 18.04

#### Problem Description:

When trying to fetch a plex token I get an error.  Logging in thorugh plex gets stuck at Plex Authorization please wait.  Skipping this step and adding a user gives an error.

#### Reproduction Steps:

Install via apt.  Reinstalled twice with the same problem.  The weird thing is when I log in from chrome on my iphone it works.

**Comment by tidusjar** [comment]
Sounds like a potential caching issue. Try Incognito mode?

**Comment by kev0153** [comment]
I installed the development branch manually and that seemed to solve the problem
