### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by elmerfdz** [tidusjar/Ombi#2350]
#### Ombi build Version:

V 3.0.3407
--
#### Update Branch:
master
--

#### Media Sever:
Plex

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No logs on this issue

```

#### Problem Description:
There is an issue with latest update, see error below when trying to query ombi via postman, the same query returned fine after opening ombi.
```
{
    "error": "Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.\nObject name: 'OmbiContext'."
}
```

This breaks Organizr-Ombi homepage integration, it works for an hour or so and then it doesn't return any requests. It was working fine on 3.0.3284 and on 3.0.3383 (not 100% sure ). Only started noticing this since the last update.

#### Reproduction Steps:

Leave your organizr tab open with ombi requests configured on the homepage or try querying Ombi api after 2hrs or more and don't open Ombi during that period.

**Comment by Fma965** [comment]
Multiple people have reported this on the organizr discord aswell, i am also experiencing the same issue.

**Comment by tidusjar** [comment]
Can someone pastbin more of the error?

**Comment by causefx** [comment]
i Believe that is the full error...  I too just tested it.  Should also note that the HTTP status code is 500.

![image](https://user-images.githubusercontent.com/16184466/41829779-98c85df2-77f1-11e8-9dce-e278270e8ce5.png)

Once you open up the URL in browser you get the results:
![image](https://user-images.githubusercontent.com/16184466/41829798-b64b66e4-77f1-11e8-9f72-8779a7588948.png)

**Comment by causefx** [comment]
As soon as you open the main url in browser... it corrects on api instantly.

**Comment by tidusjar** [comment]
Can someone try the dev build?

I cannot reproduce this myself, but I've reimplemented the way we do this.

I suspect this is happening due to the .Net core 2.1 upgrade.

**Comment by elmerfdz** [comment]
Tried 3.0.3424, now it doesn't return API results at all even after opening the main url in browser. Could someone else confirm this please?

**Comment by causefx** [comment]
with the new update the http status code is now 401.
![image](https://user-images.githubusercontent.com/16184466/41861908-57e378ba-7857-11e8-9b71-be8ce9ec99f5.png)

I tried getting a new api key but still same error.

**Comment by tidusjar** [comment]
Is this behind Nginx or some other proxy? Can we try locally or via internal IP? 

I'm just trying to narrow down where the issue may lie. I'm pretty sure the .Net core 2.1 upgrade has broken a few things internally.

**Comment by tidusjar** [comment]
I cannot seem to reproduce on my dev environment, demo.ombi.io or my personal instance.

Can someone try both of these builds to see if it makes a difference?

This build is where the Microsoft .Net Core packages are upto date to the latest version (2.1.1)
https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.3429

This build is putting the main Microsoft package back down to what it was before the 2.1 upgrade (2.0.8)
https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.3430

**Comment by elmerfdz** [comment]
Have you left your dev environment untouched for serveral hours? It won't happen unless you do that.

This is not through nginx or proxy, can't speak for everybody but I'm using internal IP and so is @causefx.

Tried v3.0.3429, no API results returned, getting 401 status code.

Think the last working build for me is v3.0.338, I've just reinstalled it, I'll report back after a few hours.

**Comment by elmerfdz** [comment]
3 hours in, no issues on the old v3.0.338 build.

**Comment by causefx** [comment]
@elmerfdz is correct, this is all local no proxy

**Comment by tidusjar** [comment]
Please can you check against the latest dev.

**Comment by elmerfdz** [comment]
Installed the latest dev, Ombi won't start now. Tried it on my main and test vm.

![image](https://user-images.githubusercontent.com/22656503/41968307-e8f5efe0-79fb-11e8-82d6-a53061fd0b38.png)

**Comment by si0972** [comment]
Yea, its brokem, i get this with the latest dev. 
![image](https://user-images.githubusercontent.com/7110194/41971358-669597ae-7a0e-11e8-8141-7f5105766209.png)

**Comment by gilbN** [comment]
#metoo
Same error as Rox

**Comment by tidusjar** [comment]
Man sorry about that, rolling back these packages is not easy!

Latest dev build works for me.

**Comment by causefx** [comment]
let me try

**Comment by tidusjar** [comment]
:D Man you are too quick!

**Comment by causefx** [comment]
@tidusjar the API still isnt working inside PostMan.  I tried resetting the API key again and still nothing.

**Comment by tidusjar** [comment]
It's what's inside the API field in the settings 😕Your using the ApiKey header?

**Comment by tidusjar** [comment]
Oh man just realized, it's case sensitive. needs to be ApiKey. I'll fix that

**Comment by causefx** [comment]
API section works again, i will wait a few hours and test again.

**Comment by tidusjar** [comment]
Hmmmm this doesn't make sense.

Note to self, this is the PR: https://github.com/tidusjar/Ombi/pull/2336/files

Check changed package version against current develop

**Comment by tidusjar** [comment]
You still see the error about the disposed context? Is there any more of the error in the logs folder?

**Comment by causefx** [comment]
Yes same error with HTTP code 500.

```
{
    "error": "Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.\nObject name: 'OmbiContext'."
}
```

**Comment by tidusjar** [comment]
I mean when that happens. Is there any errors in the log file or stdout. Usually it will provide more information

**Comment by causefx** [comment]
nothing in logs.

**Comment by tidusjar** [comment]
What about stdout?

**Comment by causefx** [comment]
nothing pertaining to that, just regular Ombi stuff like Plex Content Cacher.

**Comment by tidusjar** [comment]
Ok, think I figured it out. Latest develop contains changes. Sorry about this hassle!

**Comment by causefx** [comment]
lemme pull and test

**Comment by tidusjar** [comment]
😢

**Comment by elmerfdz** [comment]
Looks like this has been fixed :)

**Comment by tidusjar** [comment]
Excellent.
