### ISSUE TITLE
Cannot connect to plex server

### ISSUE THREAD

**Issue by Kianytty** [tidusjar/Ombi#2353]
--->

#### Ombi build Version:

V: 3.0.3407

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.2.5154

#### Operating System:

Windows 8

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```


```

#### Problem Description:

I seem to be having an issue with connecting to my plex server. My server loads in the load server button, but when I try to test it, it says that "We could not connect to your plex server.

It seems that my server is refusing the connection even though I have the correct auth and machine number.

**Comment by tidusjar** [comment]
Logs? There's a logs folder

**Comment by Kianytty** [comment]
My alopogies

[log-20180625.txt](https://github.com/tidusjar/Ombi/files/2132093/log-20180625.txt)

**Comment by Kianytty** [comment]
Thanks. I will have a look at it now. If it persists I'll tell you
