### ISSUE TITLE
Ombi to Radarr communication

### ISSUE THREAD

**Issue by halcyonforever** [tidusjar/Ombi#2355]
#### Ombi build Version:

V 3.0.3421
--

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
2018-06-23 22:55:15.854 -07:00 [Error] Error When adding movie to Radarr, Reponse: "[
<My entire library gets dumped here.  500 entries in the following format.>
 {
    \"title\": \"<Movie Title>\",
    \"alternativeTitles\": [
      {
        \"sourceType\": \"tmdb\",
        \"movieId\": XXX,
        \"title\": \"<Movie Title>\",
        \"sourceId\": XXXXXX,
        \"votes\": 0,
        \"voteCount\": 0,
        \"language\": \"english\",
        \"id\": XXXX
      },
      {
        \"sourceType\": \"tmdb\",
        \"movieId\": XXX,
        \"title\": \"<Movie Title>\",
        \"sourceId\": XXXXX,
        \"votes\": 0,
        \"voteCount\": 0,
        \"language\": \"english\",
        \"id\": XXXX
      },
      {
        \"sourceType\": \"tmdb\",
        \"movieId\": XXX,
        \"title\": \"<Movie Title>\",
        \"sourceId\": XXXXXX,
        \"votes\": 0,
        \"voteCount\": 0,
        \"language\": \"english\",
        \"id\": XXXX
      }
    ],
    \"secondaryYearSourceId\": 0,
    \"sortTitle\": \"<Movie Title>\",
    \"sizeOnDisk\": 0,
    \"status\": \"inCinemas\",
    \"overview\": \"<overview>.\",
    \"inCinemas\": \"<date>\",
    \"images\": [
      {
        \"coverType\": \"poster\",
        \"url\": \"/radarr/MediaCover/XXX/poster.jpg\"
      },
      {
        \"coverType\": \"fanart\",
        \"url\": \"/radarr/MediaCover/XXX/fanart.jpg\"
      }
    ],
    \"website\": \"www",
    \"downloaded\": false,
    \"year\": CCCC,
    \"hasFile\": false,
    \"youTubeTrailerId\": \"XXX\",
    \"studio\": \"VVV\",
    \"path\": \"<Path>\",
    \"profileId\": 4,
    \"pathState\": \"static\",
    \"monitored\": true,
    \"minimumAvailability\": \"released\",
    \"isAvailable\": false,
    \"folderName\": \"<Path>\",
    \"runtime\": <dur>,
    \"lastInfoSync\": \"Date\",
    \"cleanTitle\": \"<Movie Title>\",
    \"imdbId\": \"<IMDB>\",
    \"tmdbId\": xxxx,
    \"titleSlug\": \"xxxxxx\",
    \"genres\": [],
    \"tags\": [],
    \"added\": \"<date>\",
    \"ratings\": {
      \"votes\": xxx,
      \"value\": X.X
    },
    \"qualityProfileId\": 4,
    \"id\": XXX
  }
]"
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111

```

#### Problem Description:

When I try to submit a request to Radarr the request fails and the log get dumped with my entire movie library from Radarr.
Ombi and Radarr each run on their own dedicated virtual server.  Adding the connection went smoothly but the requests just fail to get passed.

#### Reproduction Steps:

This happens on every request.  So it is easy to re-create.

**Comment by tidusjar** [comment]
Do you have a base URL set in radarr? If so you need to set it for ombi in the radarr settings.

**Comment by halcyonforever** [comment]
ahh that did it.  Sorry I set everything up before converting to a reverse proxy (although origionally had couchpotato before dropping it for Radarr)

Thanks!
