### ISSUE TITLE
[Feature Request] (Application) - Improved Login Flow

### ISSUE THREAD

**Issue by SippieCup** [tidusjar/Ombi#2358]
## Abstract:

An improved login flow which makes it easier for new users to attach their accounts to the Ombi server.

#### Step 1:
**Current state:** App has been initalized.
**Action:** App checks if there is a valid ombi server attached to it
- **On success:** App moves to step 4 of flow.
- **On failure:** App moves to step 2 of flow.

#### Step 2:
**Current state:** App does not have a valid Host URL
**Action:**  App checks for valid host URL

- **On failure:** App moves to step 3 of flow
- **On success:** App moves to step 4 of flow

#### Step 3:
**Current state:** App does not have a valid user token or Host URL
**Action:**  User prompted for the host URL of the Obmi server they use. 

- **On submit:** the app checks If the URL is a valid Ombi server. 
- **On submit failure:** the app rejects the user and prompts for a valid URL
- **On submit success:** the app accepts the URL and moves to step 4.

#### Step 4:

**Current state:** App has a valid URL
**Action:**  Check if user token is valid for Current Ombi server (fails if no token is found)

- **On failure:** app moves to step 5 of flow.
- **On success:** app moves to step 4A of flow.

#### Step 4A: 
**Current state:** App has valid URL, valid User Token
**Action:**  Navigate to Dashboard view

- **On success:** App moves to flow completion
- **On failure:** App reports a cataclysmic failure - this should never occur

#### Step 5:
**Current state:** App has valid URL, invalid or missing User Token
**Action:**  Open in-app Webview to a specialized app login page[1] (example URL: https://hostname/applogin)

- **On failure:** App prompts the user with a failure message "Please ensure the Ombi server supports app login"
- **On success:** App moves to step 6 of flow.

#### Step 6: 
**Current state:** App has valid URL, invalid or missing User Token, user has prompted to login within webview window
**Action:**  User logs into the Ombi server via the webview window (Similar to Facebook's React Native login flow)

On login failure: User is given an incorrect password prompt and step 6 is repeated.
On login success: App moves to step 7 of flow

#### Step 7:
**Current state:** App has valid URL, invalid or missing User Token, user has successfully logged in to server in webview
**Action:**  Server login page triggers "Open mobile app" function (instead of opening the dashboard)
- **On failure:** App reports a cataclysmic failure - this should never occur (Delete data from steps 6 through 7 and fallback to step 6?)
- **On success:** Server pushes new user token to App, App moves to step 8 of flow.

###### Notes: 

Because the webview is controlled by the app, there should not be a prompt asking to open the page in Ombi, 
This step implements the current login system

#### Step 8: 
**Current state:** App has valid URL, App has valid User Token, Webview prompt is still open.
**Action:**  Complete unknown app sync functions from current system
- **On success:** Move to Step 9
- **On failure:** App reports a cataclysmic failure - this should never occur (Delete data from steps 6 through 8 and fallback to step 6?)

#### Step 9:
**Current state:** App has valid URL, App has valid User Token, Webview prompt is still open. App is fully in sync with server.
**Action:**  App closes Webview and navigates to dashboard view.
- **On success:** Move to Flow completion.
- **On failure:** App reports a cataclysmic failure - this should never occur (Delete data from steps 6 through 8 and fallback to step 6?)

#### Flow completion:
**Current state:** App has valid URL, App has valid User Token, App is fully in sync with server.
**Action:**  No future action, Flow is completed.

### Footnotes:
[1] Specalized app login page should differ from current login page. 

It should: 
- open run open mobile app function - **On success**ful login.
- validate (via user-agent?) that it is being accessed from within a webview of the app. 
- redirect to normal login page if not in Ombi's App Webview.

**Comment by tidusjar** [comment]
WOW! This is some very detailed user stories! Nice work!

**Comment by tidusjar** [comment]
I'm just going to move it here: https://github.com/tidusjar/OmbiApp/issues/38
