### ISSUE TITLE
Sonarr V3 needs the language tag passed to add shows.

### ISSUE THREAD

**Issue by keithah** [tidusjar/Ombi#2359]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Open Beta

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2018-06-28 01:12:43.788 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/tv/api/series/
2018-06-28 01:12:44.473 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/tv/api/series/
2018-06-28 01:12:44.493 -07:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/tv/api/series/0

```

#### Problem Description:

Testing with the latest sonarr, V3, ombi can't request any tv shows. I asked Markus and he said:
<markus101> It's mostly backwards compatible, but a language profile ID needs to be included now

Here's a sonarr screenshot, of the 'events' page:
![image](https://user-images.githubusercontent.com/684920/42022025-fe10a832-7a70-11e8-9d11-4fcddbc91ead.png)

#### Reproduction Steps:
Install sonarr V3 (aka phantom branch, there's a docker package)
Setup ombi to use it
Request a show

(feel free to message me on discord, my nick is 'keith')

**Comment by tidusjar** [comment]
Do you know if there is any API documentation for V3? I've not yet looked at it?

**Comment by markus101** [comment]
No docs at the moment, it's mostly the same API under `/v3/api` instead of just `/api`. In this case the issue is a Language Profile now needs to be supplied (same as a profile currently is required). I'm going to make a change to make it backwards compatible with apps using the v2 API, which will select the first Language Profile when one isn't specified.

**Comment by tidusjar** [comment]
Thanks @markus101 

I'll provide the option for user in ombi to use V3 or V2. If it's V3 then I'll use the V3 API endpoint. 

What is the endpoint I can get the language profile?

**Comment by markus101** [comment]
Sorry, flipped the URL components around, it's `/api/v3` (not /v3/api`). Language profiles can be fetched via: `/api/v3/languageprofile`.

One change for v3 is quality profiles allow grouping of qualities, which if you're storing the quality items after fetching you'll need to change that, `id`/`name` are unchanged though.

**Comment by tidusjar** [comment]
Yeah so currently I pass the quality id when adding any series, so I need to refetch them or do something different?

**Comment by canisterhead** [comment]
Hi, is there any update on this? Support for sonarr v3 would be awesome

**Comment by tidusjar** [comment]
No update yet. I need to install v3 and start testing.

**Comment by tidusjar** [comment]
So it looks like i've done it in develop! Can someone please test this out?!

You need to go into the sonarr settings and enable the v3 flag and then add the language profiles.

**Comment by jalmansor** [comment]
> So it looks like i've done it in develop! Can someone please test this out?!
> 
> You need to go into the sonarr settings and enable the v3 flag and then add the language profiles.

@tidusjar, I can confirm this does work with v3.0.0.334! 

![screen shot 2018-12-05 at 10 49 12 am](https://user-images.githubusercontent.com/9470063/49525541-fcc16a00-f87b-11e8-9aa2-402fdadec66f.png)

**Comment by jalmansor** [comment]
@tidusjar though going back and checking the setting page again, it doesn't seem to be retaining the language selected.

**Comment by tidusjar** [comment]
No problem I'll sort that

**Comment by tidusjar** [comment]
Fixed it!

**Comment by keithah** [comment]
so I'm on 3.0.4007, which is latest develop I think, I see the V3 options, I set that and the language, yet when I request something, it still comes up in Sonarr wrong:
![image](https://user-images.githubusercontent.com/684920/49682331-978a9600-fa80-11e8-8231-d5ac76cf79b8.png)

So I don't think quite there yet..

**Comment by zappy16** [comment]
Same thing here. 
![image](https://user-images.githubusercontent.com/17417763/50607315-a268f880-0e7d-11e9-833e-d3a8db1e4c86.png)

**Comment by tidusjar** [comment]
Check latest develop

**Comment by YaibaToKen** [comment]
I'd like to point out that being able to select a specific language profile for anime would be welcome and appreciated.
