### ISSUE TITLE
Auto updater doesn't work

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#236]
See title.

**Comment by Drewster727** [comment]
Need to verify in mono as well.

**Comment by Ruvetuve** [comment]
Same here on Windows. I saw a pop-up saying "Could not access file: db.sqllite". then it crashed. Updated manually.

**Comment by tidusjar** [comment]
@Ruvetuve Sorry about that, we will fix it.

**Comment by tidusjar** [comment]
Needs testing on different systems / setups

**Comment by SuperPotatoMen** [comment]
Auto update is working on windows 10!

**Comment by SuperPotatoMen** [comment]
it is broken again

**Comment by SuperPotatoMen** [comment]
@tidusjar can we disable it again in the 2.2 version?

**Comment by nakedgoat** [comment]
Auto Updater AS well as updates in general are not working stuck at 

3.0.3945
--

**Comment by nakedgoat** [comment]
yea I did - I didn't want auto on, I clicked check update, and it went
green - then I hit update it's says  that it' submitted and I wait and
nothing happens ...
I did fix all my other issues I was having by fixing the group:owner and
permissions on /opt/Ombi



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
