### ISSUE TITLE
Mobile App Not Connecting

### ISSUE THREAD

**Issue by up735175** [tidusjar/Ombi#2360]
#### Ombi build Version:

Server build :V 3.0.3421
App version:1.2
App Build: 78

#### Update Branch:
master

#### Media Sever:

Plex

#### Operating System:

Android 8.1.0

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Mobile app does not connect to server, get error message: "StatusCode: unauthorized, Reason: unauthorized, requestUri: Http://my server ip/api/v1/search/movie/popular"

if I type this into my browser I get a HTTP 401 error
however if i use api/v2/ it loads fine? does the mobile application need updating or am i doing something wrong?

**Comment by tidusjar** [comment]
You need to log into your ombi website via your mobile browser, then press the menu bar and press Open On App

**Comment by tidusjar** [comment]
Close the app down (not running in the background) and then reopen it? Is it the same?

**Comment by up735175** [comment]
Eventually that worked, had to repeat 5 times, thank you :)

**Comment by samm91** [comment]
haing same issue but on iphone, been messing around with it for past hr.  even delted the app few times.  lunching from the menu sometime app will pull in already requested items other times simply unauthorized message
