### ISSUE TITLE
Removed Emby server, media still links to Emby

### ISSUE THREAD

**Issue by aptalca** [tidusjar/Ombi#2362]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

master

#### Media Sever:

Plex & Emby

#### Operating System:

docker/alpine

#### Problem Description:

I had set up both Plex and Emby servers. I then removed the Emby server integration. The movies and TV Shows still link to both Plex and Emby. I tried restarting, running the manual importer and waiting for several weeks.

#### Reproduction Steps:

Add an emby server, then remove. The media is still linked as "View on Emby", emby integration still exists in the database

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
