### ISSUE TITLE
Pass alias through request api call for the "requested by:" field

### ISSUE THREAD

**Issue by v0idp** [tidusjar/Ombi#2363]
As requested by TidusJar I'm posting it here.

It would be nice if it was possible to set the alias for "requested by" field for each request api call.
For example in discord I could pass the username of the user to the api call so it shows "requested by *discord username* " instead of "requested by api"

**Comment by tidusjar** [comment]
@v0idp Can you pass an additional header along with `ApiKey` e.g. `UserName` ? 

Since that would be ideal, If it's supplied then the API call runs under that user, else it runs under the API user.

**Comment by v0idp** [comment]
yes I can pass the username through the header.

**Comment by tidusjar** [comment]
Done in develop and docs updated https://github.com/tidusjar/Ombi/wiki/Api-Information

Just pass a valid username in as the "UserName" header and it will work.

**Comment by v0idp** [comment]
@tidusjar by valid username you mean a user which exists in the ombi userlist or can I just enter any string ?

**Comment by tidusjar** [comment]
It needs to be a valid ombi user (Any user in the User Management Page)

**Comment by v0idp** [comment]
The question is how to link the discord users to the ombi users ?!

**Comment by tidusjar** [comment]
There's not much I can do about that, even if I included the property in the request body it still would have needed to be a valid user.

Everything relies on being a real user (The APIKEY user is a real user, it's just hidden).

**Comment by v0idp** [comment]
so there is no way to just visually show a different name on the requests ?

**Comment by tidusjar** [comment]
I'll see what I can do.

**Comment by v0idp** [comment]
otherwise make another row where the passed username is in without using the real username so it would be something like "Requested by API" and another row with "username: xxx" and if no username was passed the row will be hidden

**Comment by goldenpipes** [comment]
could you use ombi's {UserPreference} Discord ID's?

**Comment by goldenpipes** [comment]
have mellow search the ombi user for a matching {UserPreference} (DISCORD ID) and have it get that username?

**Comment by tidusjar** [comment]
It already allows you to pass a header. But the username you pass needs to be in ombi. So yes. I need to be able to pass a nickname

**Comment by v0idp** [comment]
I dont mind doing the request with the api, but I would like to pass it a nickname so it says an additional name to the api

**Comment by tidusjar** [comment]
This has now been done.

You can pass in a `ApiAlias` header and that will now show whatever string you pass in.
