### ISSUE TITLE
Can not delete user. After mobile device has been registered.

### ISSUE THREAD

**Issue by patrick1227** [tidusjar/Ombi#2365]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.2.5154

#### Operating System:

freenas 11.1 with a ubuntu VM

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I can't delete a user once a mobile device is registered to that user.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Fixed in develop
