### ISSUE TITLE
Update view on Emby URL's

### ISSUE THREAD

**Issue by shocker2** [tidusjar/Ombi#2368]
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

Stable

#### Media Sever:

Emby

#### Operating System:

CentOS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Update view on Emby links (on search) to match the new server template.
Current link: http://app.emby.media/itemdetails.html?id=[item id]
New link: http://app.emby.media/#!/itemdetails.html?id=[item id]

#### Reproduction Steps:

Install the least Emby software and click the view on Emby URL :)

**Comment by tidusjar** [comment]
Can you please explain the issue here? The current link is incorrect? 

Did the link change, why does it require a "#!" Now?

**Comment by shocker2** [comment]
Yes, Emby changed the way links are starting with the Emby version v3.4.1.16

**Comment by Ho2x** [comment]
Hello,

in which file can I modify the link to personalize it with my server?

I do not want to go through http://app.emby.media

Thank you.

**Comment by tidusjar** [comment]
Do you have the release notes for that @shocker2 ?

**Comment by tidusjar** [comment]
Fixed in develop
