### ISSUE TITLE
Ombi doesn't find a series, alltough it have a imdb entry

### ISSUE THREAD

**Issue by xXZaretXx** [tidusjar/Ombi#2369]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Operating System:

(Place text here)

Linux 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018

#### Problem Description:

One of my friends tried to request Shaolin Wuzang but he is not able to find it there.
Shaolin Wuzang have an entry in imdb..
https://www.imdb.com/title/tt4266572/
why ombi is not able to find it ?

#### Reproduction Steps:
search -> series -> enter "shaolin wuzang"

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away
