### ISSUE TITLE
Wrong text for Request Available

### ISSUE THREAD

**Issue by JieqinT** [tidusjar/Ombi#2370]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.13.2.5154

#### Operating System:

Microsoft Windows 10.0.17134

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
Don't think logs are necessary. 
```

#### Problem Description:

Request Available's Message was -> `Hello! You   {Title} on {ApplicationName}! This is now available! :)`
It should be -> `Hello! Your request for {Title} on {ApplicationName}! This is now available! :)`

#### Reproduction Steps:

Just... there.

**Comment by tidusjar** [comment]
Thanks,

You can edit this yourself just to let you know. I'll fix the default message

**Comment by JieqinT** [comment]
Yep. Fixed this a third time now. But thought you should know.
