### ISSUE TITLE
E-mail notifications do not recognize new lines.

### ISSUE THREAD

**Issue by flyryan** [tidusjar/Ombi#2378]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

master

#### Operating System:

Windows

#### Problem Description:

In my welcome e-mail, I list out various pieces of information for the user. For example, I have:

> You have been invited to use {ApplicationName}! With {ApplicationName}, you can request Movies or TV Shows you'd like to see on {ApplicationName}.
> 
> You can login here: {ApplicationUrl}
> Your username is: {UserName} 
> 
> Just search for the Movie or TV Show you want and click the Request button on the result. Once I approve the request, it will automatically be downloaded. You will receive an e-mail whenever one of your requests become available to watch!

But it gets sent as:

> You have been invited to use {ApplicationName}! With {ApplicationName}, you can request Movies or TV Shows you'd like to see on {ApplicationName}. You can login here: {ApplicationUrl} Your username is: {UserName} Just search for the Movie or TV Show you want and click the Request button on the result. Once I approve the request, it will automatically be downloaded. You will receive an e-mail whenever one of your requests become available to watch!

#### Reproduction Steps:

Create a Welcome E-mail that contains a new line and then send that e-mail to a user. The new lines will be omitted.

**Comment by tidusjar** [comment]
It's html based
