### ISSUE TITLE
Newsletter Showing Duplicates

### ISSUE THREAD

**Issue by mpearon** [tidusjar/Ombi#2379]
#### Ombi build Version:

V 3.0.3407

#### Update Branch:

Master

#### Media Sever:

Plex & Emby

#### Media Server Version:

N/A

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Problem Description:

I have Plex and Emby running on the same box, with Ombi pointed at both instances.  They both share the exact same media - I'm just catering to two different sets of users by offering both FrontEnds.
As a side effect of the way that I use Ombi, every bit of media gets added twice.  Is there any way to have Ombi only look to one DB for new media, but still reference both for authentication?

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
Its not really designed to have both running.  Maybe I'll add an option to ignore a server from the newsletter.

**Comment by mpearon** [comment]
I was reading through some of the feature requests on FeatHub (which might be where this should have gone), and saw mention of ignoring specific libraries.  Instead of flooding the UI with options, you could include a 'Select All from _______ Server'.
Another option would be to have the script that assembles the email dedup the list before firing?  Not sure if you're using an Array or Hashtable, but that could make quick work of it.
Keep in mind - the only language I speak is PowerShell - so none of what I just said might apply. :)

**Comment by mpearon** [comment]
I want to note that I appreciate your quick responses here.

**Comment by jeffkeller87** [comment]
I am seeing duplicates for both Movies and TV shows, but unlike others, I do not have multiple media servers connected to Ombi, or even running on the machine. I use a single Emby server. I've seen as many as four duplicate newsletter entries for the same movie or TV show.

Is this a separate issue? What does Ombi actual do when it is updating its database? I have meta data files stored alongside my media (.nfo, .xml). Could Ombi be picking these files up somehow?

**Comment by mpearon** [comment]
@tidusjar - Is this still a consideration?

**Comment by tidusjar** [comment]
It's an issue for people running both media servers (plex and emby). But also in that scenario there are going to be many more issues e.g. the View on Emby/Plex buttons will be messed up. I'm going to close this since currently I don't think I am going to get around to it.

What I suggest you do is raise it on Feathub to support multiple media server types, then I can grasp the urgency/need for this requirement.
http://feathub.com/tidusjar/Ombi
