### ISSUE TITLE
Issue with "View with Emby" button

### ISSUE THREAD

**Issue by CloudyFlix** [tidusjar/Ombi#2387]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Media Sever:

Emby

#### Media Server Version:

Version 3.4.1.0

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

When I click on the button "View on EMBY" the page that opens displays nothing usable. See the screenshot here: <a href="https://www.casimages.com/i/180717114328726453.png.html">Screenshot</a>

#### Reproduction Steps:

I go to Ombi via his direct address: ipaddress: 5000/search

**Comment by tidusjar** [comment]
Fixed in the develop branch
