### ISSUE TITLE
Special episodes not available for request

### ISSUE THREAD

**Issue by j0hnzen** [tidusjar/Ombi#2390]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.13.4.5251 

#### Operating System:

Debian Jessie

#### Problem Description:

Unable to select episodes from special season as a request.
Example: Gold Rush has multiple special episodes listed in Sonarr and Plex. These episodes are located in season 0 designated as the specials season.

Is it possible to add support so users can request special episodes from season 0?

#### Reproduction Steps:

open searsch
select tv
search for gold rush
click request and chose select

No season 0 or specials is listed and user is unable to request specials

**Comment by tidusjar** [comment]
It's possible but there were reasons why we specifically exclude them. Mainly because not many people actually get the specials so it would never mark the series as "Fully Available". Please open a feathub request if you still want this.
