### ISSUE TITLE
Server busy and CPU's high consumption

### ISSUE THREAD

**Issue by Adrimau** [tidusjar/Ombi#2393]
#### Ombi build Version: 

Because my Ombi container is unavailable I can't give you the exact version but I'm sure that it's that last one.

#### Update Branch: 

Master

#### Media Sever: 

Plex

#### Media Server Version: 

1.13.3.5208

#### Problem Description:

I run Ombi in a Docker's container on my NAS Synology DS918+. Sometimes, Ombi become totally unavailable and there's this error on Safari (it's also unavailable on any device/browser) : 

> Safari can't open the page because the server unexpectedly dropped the connection. This sometimes occurs when the server is busy.

All of my others container are working great.

With this problem, my Ombi's container take abnormally a big part of my CPU (20-25%) and RAM (200-300 MB). Restart the container doesn't solve the problem.

#### Reproduction Steps: 

Don't know how to reproduce the issue, it just happen like that.

Thanks in advance!

**Comment by tidusjar** [comment]
Please provide the build version

**Comment by Adrimau** [comment]
3.0.3111

Here's an extract of the today's log file when Ombi is down :

> 2018-07-18 20:25:34.061 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:25:48.572 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:26:03.230 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:28:01.921 +00:00 [Information] 6 servers were removed due to timeout
> 2018-07-18 20:28:21.415 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:28:35.682 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:29:25.253 +00:00 [Information] 3 servers were removed due to timeout
> 2018-07-18 20:29:50.184 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:30:04.694 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:30:20.339 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:30:35.273 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:30:54.382 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:31:13.437 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:31:32.570 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:31:47.537 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:32:02.070 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:32:17.037 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:32:31.725 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:32:46.514 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:33:25.995 +00:00 [Information] 2 servers were removed due to timeout
> 2018-07-18 20:33:46.713 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:34:01.904 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:34:21.658 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:34:40.870 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:34:56.103 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:35:11.351 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:35:26.068 +00:00 [Information] 1 servers were removed due to timeout
> 2018-07-18 20:35:46.358 +00:00 [Information] 1 servers were removed due to timeout

**Comment by tidusjar** [comment]
Please update

**Comment by tidusjar** [comment]
Latest version is v3.0.3477. You can see this here: https://github.com/tidusjar/Ombi/releases

**Comment by Adrimau** [comment]
Yes I saw this yesterday but the fact are here : I'm in 3.0.31111-master and Ombi tell me that It's the latest version.
Maybe I should use another Docker source? If yes, which one?

**Comment by tidusjar** [comment]
The check for update was broken in a previous version, I am guessing that 3111 does not have that fix.

The LSIO container should update every friday by default, so check for a docker update for that container.

**Comment by tidusjar** [comment]
https://hub.docker.com/r/linuxserver/ombi/ that should contain the latest master

**Comment by Adrimau** [comment]
Yep that's the master but with the 3.0.3111 build and the broken update system. Maybe should I contact Linuxserver to update the container.
