### ISSUE TITLE
Configuration Lost After APT Repo Upgrade

### ISSUE THREAD

**Issue by m1lkman** [tidusjar/Ombi#2394]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Latest

#### Operating System:

Ubunut 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

For the third time letting APT upgrade ombi from repository my configuration is being lost or overwritten. What can I do to prevent this in the future?

#### Reproduction Steps:

Install Ombi from Apt repository, configure Ombi, complete apt-get update, bingo back to original config.

**Comment by tidusjar** [comment]
I don't manage this repository. Please check the wiki.

**Comment by louis-lau** [comment]
@m1lkman can you post the output of the following commands?

`systemctl cat ombi`
`ls -lah /opt/Ombi/Ombi.db`
`ls -lah /etc/Ombi/`

**Comment by m1lkman** [comment]
Here you go

`[Unit]
Description=Ombi - PMS Requests System
After=network-online.target plexmediaserver.service
Requires=plexmediaserver.service
PartOf=plexmediaserver.service

[Service]
Type=simple
User=ombi
Group=nogroup
WorkingDirectory=/opt/Ombi/
ExecStartPre=-/bin/chown -R ombi:ombi /opt/Ombi
ExecStart=/opt/Ombi/Ombi --host http://*:3579
TimeoutStopSec=30
Restart=on-failure
ResartSec=5

[Install]
WantedBy=multi-user.target plexmediaserver.service

[Unit]
Description=Ombi - PMS Requests System
After=network-online.target plexmediaserver.service
Requires=plexmediaserver.service
PartOf=plexmediaserver.service

[Service]
Type=simple
User=ombi
Group=nogroup
WorkingDirectory=/opt/Ombi/
ExecStartPre=-/bin/chown -R ombi:ombi /opt/Ombi
ExecStart=/opt/Ombi/Ombi --host http://*:3579
TimeoutStopSec=30
Restart=on-failure
ResartSec=5

[Install]
WantedBy=multi-user.target plexmediaserver.service

-rw-r--r-- 1 ombi nogroup 1.9M Jul 19 07:13 /opt/Ombi/Ombi.db

total 14M
drwxr-xr-x   3 ombi nogroup 4.0K Jul 18 12:04 .
drwxr-xr-x 112 root root    4.0K Jul 18 12:05 ..
drwxr-xr-x   3 ombi nogroup 4.0K Jun 25 10:06 Logs
-rw-r--r--   1 ombi nogroup 6.8M Jul 18 12:00 Ombi.db
-rw-r--r--   1 ombi nogroup 6.8M Jul 18 12:05 Ombi.db.backup
-rw-r--r--   1 ombi nogroup 456K Jul 18 12:04 Schedules.db
`

**Comment by louis-lau** [comment]
Your systemd config doesn't look right at all. What steps have you followed to edit it? (I assume you've edited it to change the default port?)

This is the service file that ships with the package:
https://github.com/louis-lau/ombi-deb-build/blob/master/master/amd64/template/debian/ombi.service

You can edit it according to this answer on askubuntu:
https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services

You'd want to change the ExecStart option to:
`ExecStart=/opt/Ombi/Ombi --storage /etc/Ombi/ --host http://*:3579`

Don't just edit it normally. Do it the way the answer on askubuntu says and you'll be fine :)

**Comment by louis-lau** [comment]
I should note though, undo you changes. so when you execute `systemctl cat ombi` your output is the same as the file I linked above. Then follow the askubuntu answer.

**Comment by m1lkman** [comment]
Thanks Louis, here's what I set in my ombi override. Let you know if I see any issues once the next Apt upgrade occurs.

```
[Service]
ExecStart=
ExecStart=-/opt/Ombi/Ombi --storage /etc/Ombi/ --host http://*:3579

[Install]
WantedBy=multi-user.target plexmediaserver.service
```

**Comment by louis-lau** [comment]
You're welcome! One other thing, remove ombi.db in /opt/Ombi.

If you don't my deb package will move it to /etc/Ombi on the next upgrade, and it will overwrite the config you have right now.

**Comment by m1lkman** [comment]
Understood. Thank you. @louis-lau

**Comment by m1lkman** [comment]
@louis-lau I can confirm after the latest update that I no longer experience this issue after making the changes you suggested. Thank you

**Comment by louis-lau** [comment]
Good to hear. You're welcome :)
