### ISSUE TITLE
Ombi Server - Currently Offline

### ISSUE THREAD

**Issue by CozyRocket** [tidusjar/Ombi#2395]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.4.5271

#### Operating System:

ClearOS (Centos)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

https://pastebin.com/VJu5mcWk
[log-20180721.txt](https://github.com/tidusjar/Ombi/files/2214759/log-20180721.txt)

#### Problem Description:

When I navigate to my Ombi site I am greeted with:

Currently Offline
The media server is currently offline.
Check this page for continuous site updates.

I, however, can't sign into Ombi using either Plex auth or local auth. The logs throw a bunch of errors out.
I created a backup of the folder, and the re-installed the latest version over the top, no success still errors out.
When I create a brand new server, it works fine as expected.

I found the Ombi.db file and cloned my backup over to my live test. Removed the Ombi.db and the service booted up fine with no issues, however, it now needs to manually be set up again which is not ideal, but if I must I can.

I'm throwing a wild guess to say that the Ombi.db file has somehow got corrupted? I can supply the db file if you would like, however, I would prefer not to put it in a public place.

Just as a side note, when I set up the brand new server, I used the same setup as I did originally, the same account and got the plex token. When I removed the new one and replaced it with the old one, it kept me signed in for some reason, its a bit weird.

Plex is also online and unaffected by this.

#### Reproduction Steps:

No idea, it just started happening.

**Comment by CozyRocket** [comment]
Would it be best that I just create a new server and set it up again? I can keep a copy of the broken one so you can possibly attempt a fix.

**Comment by tidusjar** [comment]
Please try the develop branch. It should be fixed in there
