### ISSUE TITLE
Running TV Shows never get requested filled notification

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2396]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Open stable

#### Media Sever:

Plex

#### Operating System:

Debian 9

#### Problem Description:

If someone requests a running TV show, no requested filled notification will get sent out nor will the show be marked available because it has some episodes with airdates in the future which are still marked as being processed.

(imho) ombi should send out notifications, if a user requests all season, if all episodes aired up until now are filled.

**Comment by tidusjar** [comment]
This is not how it works currently. Notifications only get sent when the whole request it fulfilled. 

I'm planning to make changes around this in the futute

**Comment by l1ge** [comment]
I'd really like this feature ! To update people about when an episode is available!
