### ISSUE TITLE
Conflicting port number

### ISSUE THREAD

**Issue by spolen88** [tidusjar/Ombi#2398]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Stable

#### Media Sever:

Emby

#### Operating System:

Ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Not Applicable

#### Problem Description:

When using the default port 5000 there's a conflict with rtorrent which also runs on port 5000

I'm not sure this will be a priority fix for the devs, but this causes a need for a more advanced setup even with the apt setup.

#### Reproduction Steps:

install using default settings while having rtorrent running

#### Current Workaround:

run with ExecStart=/opt/Ombi/Ombi --host=http://*:9090 (or whatever port you want to use) in your systemd service file

**Comment by tidusjar** [comment]
I don't understand the issue. Just use a startup argument to change the port. See the wiki
