### ISSUE TITLE
schedules.db keeps getting deleted and recreated constantly, which results in very high disk write count

### ISSUE THREAD

**Issue by strike84** [tidusjar/Ombi#2399]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.6.0.2 beta

#### Operating System:

unRAID 6.5.3 (Linux 4.14.49-unRAID)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

```
[log-20180725.txt](https://github.com/tidusjar/Ombi/files/2226006/log-20180725.txt)

#### Problem Description:

I have an issue where the schedules.db file keeps being created, deleted and created again constantly, which results in very high disk writes on my ssd cache drive. I'm afraid my disk will die one me long before it's supposed to if I keep using the container as it is now. 

I have installed an unraid plugin called file activity which logs the disk activity on my disk. I've included the output in the ombi.txt file. Keep in mind this is just 30 mins worth of log, so imagine this all day, every day, 24/7...

[ombi.txt](https://github.com/tidusjar/Ombi/files/2226004/ombi.txt)

I've tried starting with a fresh container, but the issue still persists. I've even deleted my docker image containing all my containers and recreated it.

#### Reproduction Steps:

Nothing special. Just a fresh container. If you have access to unRAID, install the file activity plugin to see the disk activity.

**Comment by tidusjar** [comment]
This is the way Sqlite works, it uses this temp file for transactions, when the transaction is complete it will then delete it.

you can prevent this by doing the following: https://stackoverflow.com/questions/633274/what-causes-a-journal-file-to-be-created-in-sqlite

But I do not know how that will affect Ombi.

**Comment by strike84** [comment]
Ok, thanks. But when I tried to issue that command on the command line I just get "PRAGMA not found".

**Comment by tidusjar** [comment]
You need to execute it within sqlite.
