### ISSUE TITLE
Report Issue dropdown not showing anything

### ISSUE THREAD

**Issue by FlyAg** [tidusjar/Ombi#2402]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.4.5251

#### Operating System:

Windows Server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

On the requests page, an item entry's "Report Issue" button should drop down with options. Instead, a black bar appears. This happens for both TV and Movies and across Chrome, Firefox, IE on multiple PCs. Logs do not show an error entry when button is clicked. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
You need to put some stuff in it...go to the settings and fill out the
categories on the issues page.

**Comment by FlyAg** [comment]
Ah I got it working now. I seem to remember that there were default options in place already in an earlier release. 
Nevertheless, thank you. I needed to add options for people to request subtitles for content. Maybe that is a feature request I can submit too.

**Comment by tidusjar** [comment]
Yeah in V2 there was prefilled options but you couldn't customize it.
