### ISSUE TITLE
No log folder

### ISSUE THREAD

**Issue by tenzone** [tidusjar/Ombi#2414]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Admin ui lists DEVELOP

#### Media Sever:

Plex

#### Operating System:

ubuntu server 17.10

Installed via instructions using debian apt repo, 
i have no logs in sight on admin page, or in the filesystem. 

Installed via instructions using debian apt repo, 
i have no logs in sight on admin page, or in the filesystem. 
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
I don't maintain this repo. So I am not sure where the logs are for this. See the wiki.

**Comment by tenzone** [comment]
i understand that the apt repo is maintained by someone else, its not install logs i dont see though, its the app logs.  e.g. there is no /opt/Ombi/log folder.

is it a different/altered package being delivered through the apt repo vs the direct release?

**Comment by grahamPegNetwork** [comment]
This is one of the first search results when running into the same issue. I followed the instructions to install from apt and end up with no logs. I understand not maintaining the repo, but is it possible to document this information somewhere?
