### ISSUE TITLE
PowerUser cant set root folder or quality profile?

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2415]
#### Ombi build Version:

V 3.0.3477

#### Update Branch: master

Open Beta

#### Media Sever:

Plex
#### Operating System:

Windows 10 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

PowerUser Role is unable to  set root folder or quality profile.  This seems incorrect behavior.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Try to change QP or RF from approval screen as power user.

YOU CANT!

**Comment by tidusjar** [comment]
Fixed in dev
