### ISSUE TITLE
App broken on iPhone X

### ISSUE THREAD

**Issue by FlyAg** [tidusjar/Ombi#2419]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

iOS 11.2.6

#### Problem Description:

On iPhone X, upon loading the app, I am unable to see or click on the field for Ombi URL since the notch covers that part of the screen. 

In addition, the fields for email and password show white/transparent text when I type so I can't see any text at all.

**Comment by tidusjar** [comment]
Thanks. This is the wrong repo but the manual login was an alternative way to logging in. 

You can use the existing login functionality by navigating to the ombi website and pressing the Open Mobile App button.

**Comment by tidusjar** [comment]
Issue raised here: https://github.com/tidusjar/OmbiApp/issues/49
