### ISSUE TITLE
Ombi frontend will not load - Ombi 3.0.3553-develop

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#2421]
#### Ombi build Version:

Ombi 3.0.3553-develop

#### Update Branch:

Open Beta

#### Operating System:

Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - Cent 7

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Browser console log. 

```
external "vendor_5bb5afdc5634aebdc2f5":1 Uncaught ReferenceError: vendor_5bb5afdc5634aebdc2f5 is not defined
    at Object.<anonymous> (external "vendor_5bb5afdc5634aebdc2f5":1)
    at r (bootstrap 6848286a01eb8a04699d:49)
    at Object.<anonymous> (pace.js from dll-reference vendor_5bb5afdc5634aebdc2f5:1)
    at r (bootstrap 6848286a01eb8a04699d:49)
    at Object.<anonymous> (main.ts:1)
    at r (bootstrap 6848286a01eb8a04699d:49)
    at bootstrap 6848286a01eb8a04699d:144
    at bootstrap 6848286a01eb8a04699d:144
(anonymous) @ external "vendor_5bb5afdc5634aebdc2f5":1
r @ bootstrap 6848286a01eb8a04699d:49
(anonymous) @ pace.js from dll-reference vendor_5bb5afdc5634aebdc2f5:1
r @ bootstrap 6848286a01eb8a04699d:49
(anonymous) @ main.ts:1
r @ bootstrap 6848286a01eb8a04699d:49
(anonymous) @ bootstrap 6848286a01eb8a04699d:144
(anonymous) @ bootstrap 6848286a01eb8a04699d:144

```

#### Problem Description:
Ombi frontend will not load. Produces browser errors. 

#### Reproduction Steps:
Run Ombi 3.0.3553-develop try and load the frontend

**Comment by tidusjar** [comment]
How did you update?

**Comment by samwiseg00** [comment]
downloading the targz file overwriting the the files in the current dir, chown to ombi and restarting

**Comment by tidusjar** [comment]
I think I need to put some documentation about this.

So in the latest dev builds we have upgraded quite a lot of the frontend to a later angular and webpack versions. In doing this we also optimized the way we bundle the app. So the actual .js file name is slightly different now and by overwriting everything will leave the existing .js file there and the angular app will attempt to load it.

What you need to do is clear out the folder (make sure you do not delete the ombi.db file) and then extract it. 

Going forward you should be fine with just overwriting things

**Comment by samwiseg00** [comment]
Ok cool. Thanks!

**Comment by samwiseg00** [comment]
I can confirm wiping all files, reinstalling, restoring the db  worked.
