### ISSUE TITLE
Ombi API breaks when ran as a service user in linux

### ISSUE THREAD

**Issue by samwiseg00** [tidusjar/Ombi#2422]
#### Ombi build Version:

V 3.0.3529

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018

#### Problem Description:

I am unable to run Ombi as a service user it must be ran as root.  This is the same problem that happened with issue https://github.com/tidusjar/Ombi/issues/2342. 

#### Reproduction Steps:
setup ombi 
run as a service user with no login
Start ombi and navigate to the webui

you can also hit the API and see the error. 
`/api/v1/Update/develop` it throws this error `{"error":"error:2006D002:BIO routines:BIO_new_file:system lib"}`

```
ombi:x:1004:1004::/home/ombi:/bin/nologin
```
The workaround right now is to run Ombi as root and then everything works correctly.

Perms on the folder/files have been verified and are set to `ombi` correctly. 

Errors on the client side. 
![unknown](https://user-images.githubusercontent.com/2241731/41624555-136fd60a-73e4-11e8-83c5-fb9ab372f935.png)

**Comment by tidusjar** [comment]
This is due to the .net core 2.1 update. I am not sure why this is causing issues, i've done a bit of investigation but no luck. Unfortunately it's not possible for me to stay on the previous version due to .net core 2.0 is not going to be supported as of October.

Can you double check the log files?

**Comment by tidusjar** [comment]
Can you also try and update OpenSSL to latest to see if it makes a difference?

**Comment by samwiseg00** [comment]
I have made sure everything is up to date. That is why I a fairly confident it has to do with something in the code. 
```
 yum install lttng-ust libcurl openssl-libs krb5-libs libicu zlib
Loaded plugins: fastestmirror, product-id, replace, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * base: mirror.wdc1.us.leaseweb.net
 * epel: mirror.us.leaseweb.net
 * extras: centosv.centos.org
 * nux-dextop: mirror.li.nux.ro
 * updates: centosv.centos.org
 * webtatic: us-east.repo.webtatic.com
Package lttng-ust-2.4.1-4.el7.x86_64 already installed and latest version
Package libcurl-7.29.0-46.el7.x86_64 already installed and latest version
Package 1:openssl-libs-1.0.2k-12.el7.x86_64 already installed and latest version
Package krb5-libs-1.15.1-19.el7.x86_64 already installed and latest version
Package libicu-50.1.2-15.el7.x86_64 already installed and latest version
Package zlib-1.2.7-17.el7.x86_64 already installed and latest version
```

Pretty sure this can be easily replicated on any centos 7 box. 

I looked again and it does seem to produce errors now. 
https://gist.github.com/samwiseg00/e23fb96a9198061111c55b515724bc31

**Comment by samwiseg00** [comment]
Leaving a comment here from the .Net core team incase someone else has this issue. 

Another workaround (other than running as root) for the moment is to set `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` in your env variable to use the older WinHttpHandler/CurlHandler HTTP stack.

```
export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
printenv DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER
0
```

**Comment by tidusjar** [comment]
Going to close this for now. Nothing i can do until .net core has fixed it.

**Comment by samwiseg00** [comment]
Sounds good! Thanks!
