### ISSUE TITLE
Icons not working via Reverse Proxy in latest update

### ISSUE THREAD

**Issue by rg9400** [tidusjar/Ombi#2424]
#### Ombi build Version:

V 3.0.3554

#### Open BetaBranch:

Develop

#### Operating System:

Windows 10

#### Problem Description:

After the update, Ombi does not show icons when accessing through a reverse proxy (specifically NGINX)

![image](https://user-images.githubusercontent.com/39887349/43620059-7acd9178-9696-11e8-9118-4b1f7330eb3c.png)

They show up when accessed locally

![image](https://user-images.githubusercontent.com/39887349/43620074-946fcd9e-9696-11e8-8f4d-242b4b9c1529.png)

#### Reproduction Steps:
Access Ombi through NGINX. Confirmed it was not due to the custom css by having other people who do not run custom CSS have same issue (no icons through reverse proxy, but show up locally)

**Comment by jeremysherriff** [comment]
More info here:
https://www.reddit.com/r/Ombi/comments/93qtgn/slight_ui_issue_might_be_reverse_proxy_related/

Issue was not present on stable release 3.0.3477.
Switched over to develop branch, issue is present in 3.0.3554

**Comment by jeremysherriff** [comment]
Actually the whole screen layout is broken for me, it seems other broken elements are css and fonts:
![image](https://user-images.githubusercontent.com/1082213/43639166-711a205e-976f-11e8-9a0a-1132e8a4355e.png)

**Comment by rg9400** [comment]
Are you using the OmBlur theme? It seems like it, and that in general is just broken. Icons are specific to this issue. 

There is a temp fix in that reddit post with an nginx rewrite

rewrite \^/dist/(.\*) $scheme://$host/request/dist/$1 permanent;

**Comment by jeremysherriff** [comment]
Indeed I did have the theme selected, and yes removing the theme sorted everything except the icons.

I haven't bothered with the rewrite, i'll wait for the icons to reappear on their own :)

**Comment by christronyxyocum** [comment]
Issue still exists on 3.0.3555.

**Comment by tidusjar** [comment]
Fixed in develop
