### ISSUE TITLE
Add option to automate newsletter

### ISSUE THREAD

**Issue by bozrdang** [tidusjar/Ombi#2425]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Any

#### Media Sever:

Plex/Emby

#### Operating System:

All

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I would love to see an option to automate the newsletter so it is automatically sent at certain intervals (say once a week) and we don't have to manually send it.

**Comment by tidusjar** [comment]
It is automated. By default it sends out every Friday 12pm local time. You can customize this from the Jobs Page in the settings

**Comment by bozrdang** [comment]
I'm sorry that I totally missed that.  Thanks!
