### ISSUE TITLE
Series are not getting marked as available full sync endless loop

### ISSUE THREAD

**Issue by hagabla** [tidusjar/Ombi#2429]
#### Ombi build Version:

V latest stable

#### Update Branch:

stable

#### Media Sever:

Plex

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

nothing in logs
```

#### Problem Description:

I changed the library layout of my plex server, then went into settings loaded the libraries again and checked the ones I wanted. Still, TV show are not getting marked available. They are available in plex.
When manually doing a full sync ombi is trapped in an endless loop constantly caching all episodes over and over again

**Comment by tidusjar** [comment]
Try Develop

**Comment by hagabla** [comment]
Same issue

**Comment by tidusjar** [comment]
Please can you provide some logs. There is the Plex cacher job. We need that to run. You can manually trigger it from the settings pages

**Comment by hagabla** [comment]
This is from syslog, since ombi.log does not show anything related
`
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server ..
 info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
	Starting EP Cacher
 info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
	 Total Epsiodes found for TV Shows = 14780
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
	 Processed 200 more episodes. Total Remaining 14580
...
...
goes on for a while till we reach 0 then
....
 info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
	       We have finished caching the episodes.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
	 Starting Plex Content Cacher
 info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
	Starting to cache the content on server ..
and we start over again, this repeats until I stop ombi
`

**Comment by tidusjar** [comment]
What happens when you run the recently added sync?

**Comment by tidusjar** [comment]
How big is your library? 

What is your current job settings (Cron expressions) for the Plex stuff?

**Comment by hagabla** [comment]
15870 items big.

plex sync: 30 5 * * *
plex recently added sync: */10 * * * *

**Comment by quincarter** [comment]
What was the resolution for this issue? I am having the same issue. Large library. About the same size. Same settings listed above

**Comment by hagabla** [comment]
There was an update that fixed the problem for me.
