### ISSUE TITLE
Newsletter formatting overlaps on mobile

### ISSUE THREAD

**Issue by bozrdang** [tidusjar/Ombi#2431]
#### Ombi build Version:

V 3.0.3555

#### Update Branch:

Dev

#### Media Sever:

Emby

#### Operating System:

Docker/Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Newsletter formatting not good for mobile (Android Gmail app).  Text overlaps if there's more than one recently added item.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

![screenshot_20180806-094921_gmail](https://user-images.githubusercontent.com/847595/43720828-2c6effaa-995f-11e8-8fdb-741e851acb7b.jpg)

**Comment by Xenocell12** [comment]
Hey Jamie,

Great app by the way. And yes, I can confirm as well it overlaps. :(

**Comment by tidusjar** [comment]
@anojht Is this something you could look at dude?

**Comment by anojht** [comment]
Sorry @tidusjar just have been busy. Yes, I will have a look at this.

**Comment by tidusjar** [comment]
Thanks man! It's cool 😄 👍

**Comment by anojht** [comment]
So just quickly did some digging, looks like gmail app will auto shrink email elements larger than device width to make it fit on the screen thus breaking all formatting. Temp fix, open the menu in the gmail app > click Settings > click General Settings > uncheck Auto Fit email option. Email will be standard size....

Some solutions suggest adding min-width CSS property to elements to prevent the resize happening...will have to test this...

**Comment by anojht** [comment]
@tidusjar I have tried many many different combinations of CSS styles, tricks and hacks to fix the layout for gmail. None of which work perfectly, most of them break compatibility for other email clients. Unless we do a complete rewrite of the newsletter HTML, or gmail improves its CSS compatibility there is no solution for this atm. 

I have already stated a temp fix in the previous comment... If someone would like to help us work on this I would be more than happy to answer any questions.

**Comment by tidusjar** [comment]
No problem @anojht 
A massive thanks for your help and assistance on this!

**Comment by d1slact0r** [comment]
Just adding myself to the list. Will have a look at it because it is unusable now on mobile phones.

**Comment by tidusjar** [comment]
It's not unusable on mobile phones. Emails are rendered differently depending on the email client.

**Comment by d1slact0r** [comment]
Even with the auto residing of it's still not readable.

Met vriendelijke groet,

Niels Voorn

**Comment by bozrdang** [comment]
Looking good now on Gmail mobile.  Thanks!
