### ISSUE TITLE
Cannot login on iphone x

### ISSUE THREAD

**Issue by matrosovas** [tidusjar/Ombi#2432]
#### Ombi build Version:

V 1.5

#### Operating System:

IOS

#### Problem Description:

on Iphone x top input field is behind the notch and cannot be accessed. This is preventing me to log in.

#### Reproduction Steps:

Open the app on ios on iphone x and try to login and change URL

**Comment by tidusjar** [comment]
Wrong repo. But I'm aware of this. 

You can use the existing way of logging in by pressing the open mobile app link in the navigation menu of ombi.
