### ISSUE TITLE
Ombi unable to connect to Plex

### ISSUE THREAD

**Issue by jasonlyle88** [tidusjar/Ombi#2433]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.13.5.5291

#### Operating System:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3477-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on
/opt/ombi3
Hosting environment: Production
Content root path: /opt/ombi3
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
fail: Ombi.Controllers.External.TesterController[1000]
      Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Server returned nothing (no headers, no data)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__61.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242


```

#### Problem Description:

I was having issues with Ombi not marking things as available, so I went into settings, plex server, and clicked test connection. It failed. After testing some, I removed the plex server shut down Ombi, and cleared the logs. I then started Ombi back up, and added my plex server (everything went fine entering my credentials, discovering my server, submitting plex settings). However, when I clicked test connection, I again got an error that it could not connect to plex (even though it just discovered the server and loaded the key and everything fine). The above log information is what came out of this process.

#### Reproduction Steps:

Read above.

**Comment by tidusjar** [comment]
Can you make sure the Host and port are correct.

**Comment by jasonlyle88** [comment]
Host and port were correct. Odd thing is, I changed the "Hostname or IP Address" field from the internal IP address (192.168.1.xxx) to "localhost" and now it is working fine...

**Comment by jasonlyle88** [comment]
@tidusjar , apparently Ombi isn't importing anything from plex now though. I see absolutely nothing in the logs when I run the plex full sync and the plex recently added sync... but when I check the Ombi.db file (plexservercontent table), the newest item is from 7/31. I've added 7 movies and 2 TV series since then (over 100 episodes) none of which are showing up.

**Comment by tidusjar** [comment]
Check stdout when running the sync

**Comment by jasonlyle88** [comment]
Ran ombi from the command line (./Ombi), went in to the app and selected full sync with plex, and got nothing from stdout other than Ombi starting.

```
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.3477-master
Copyright (C) 2018 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --help       Display this help screen.

  --version    Display version information.



We are running on
/opt/ombi3
Hosting environment: Production
Content root path: /opt/ombi3
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
```

**Comment by tidusjar** [comment]
It indicates there is something either wrong with your Plex instance or the connection to plex:  Server returned nothing (no headers, no data)

**Comment by jasonlyle88** [comment]
After much testing, messing around with a VM, and trying random things, I got everything back to working by updating the "Hostname or IP Address" field to the URL specified in the reverse proxy, specifying the port as 443, and checking the SSL box. I'm curious if this is because in plex I have everything set up to deal with HTTPS and to require secure connections.

I'm not sure if this is something that can be logged better, but if it could, that would be helpful for other users in the future. It is rather confusing getting no output when I know my plex server is up and running fine, when other programs are communicating with it fine, and when Ombi says that the "Test Connectivity" routine works fine and the "Load Libraries" button loads libraries correctly, but manually triggering the full or recently added sync does absolutely nothing.

**Comment by tidusjar** [comment]
The reason the load libraries worked is because that contacts plex.tv IIRC. Same as getting your server info. Glad you got it all working
