### ISSUE TITLE
Ombi App (android) not showing that movies are already requested

### ISSUE THREAD

**Issue by mochflix** [tidusjar/Ombi#2434]
#### Ombi build Version:

3.0.347

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.5.5291

#### Operating System:

Windows Server 2012 RII 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When Using the Android ombi app, the app doen't let users know that a movie they want to request is already available in plex. When using the regular website, Ombi shows the movie as available.

Apart from this, my sincere compliments on the app.

**Comment by mochflix** [comment]
My Bad...Sorry

**Comment by tidusjar** [comment]
No problem. Easy mistake

**Comment by mochflix** [comment]
I just updated to developer branch Version | 3.0.3555

And I am still having this problem... Could it be that the app is only caching the info from sonarr, radarr etc instead of cahcing the info from plex. The Webinterface is still giving me the correct info...

**Comment by mochflix** [comment]
or am I still being an idiot and on an older version :)

**Comment by tidusjar** [comment]
What version of the app are you using?

**Comment by mochflix** [comment]
Version 1.4 build 83 according to the app

**Comment by mochflix** [comment]
Or could it be a setting or something like that? Something in ombi.db?

**Comment by tidusjar** [comment]
Can you please post a screenshot of an available movie via the website and the same movie on the app?

**Comment by mochflix** [comment]
the Mission impossible is recognized as being requested (it's monitored by radarr, the actual request in ombi was lost due to the update), but the avengers is available in plex but not recognized as being so by the app.
I delete the movies that have downloaded from radarr so the only source of knowing is an actual plex scan result.

**Comment by tidusjar** [comment]
What does it look like in the movie details page on the app (Click on the movie)

**Comment by mochflix** [comment]
![screenshot_20180809-154109](https://user-images.githubusercontent.com/17989026/43902662-efe05d66-9bea-11e8-99e0-bce60cfc228e.jpg)

**Comment by tidusjar** [comment]
Thats strange, can you go into the settings of the app and verify that it's looking at your domain?

**Comment by mochflix** [comment]
Yes, the url is correct

**Comment by tidusjar** [comment]
Can you create me a user on your ombi instance so i can take a look myself? just email me the details @ tidusjar@gmail.com

**Comment by mochflix** [comment]
Email sent!
