### ISSUE TITLE
Bulk User Edit in Chrome

### ISSUE THREAD

**Issue by RealTacosaurus** [tidusjar/Ombi#2437]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.13.5.5291

#### Operating System:

Ubuntu Server

#### Problem Description:

Using Chrome browser in MacOS (issue not in Safari, haven't tried on another OS), on the user management page, if you select "Bulk Edit" you cannot scroll to click "update users" after selecting your desired configuration changes. A solution I found was to zoom the page out, but it would be great if the scroll worked properly or if it all fit in one page!

**Comment by tidusjar** [comment]
Can you try a different browser? Safari is not really something that I
actively try and support.

**Comment by RealTacosaurus** [comment]
Sorry my ticket wasn't clear. In Safari it _is_ working, in Chrome is where I have issues. I was able to work around, but figured it might be worth letting you know.

**Comment by tidusjar** [comment]
Please check with the latest release
