### ISSUE TITLE
Series type not correct when requesting show from sonarr

### ISSUE THREAD

**Issue by chriscpritchard** [tidusjar/Ombi#2442]
#### Ombi build Version:

V 3.0.3563

#### Update Branch:

Develop

#### Media Sever:

Plex
#### Media Server Version:
N/A

#### Operating System:

Gentoo Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Correct series type isn't set when adding a new series

#### Reproduction Steps:
Try to request an anime show, series type on sonarr set to standard.

Pull request to fix the issue submitted here: https://github.com/tidusjar/Ombi/pull/2441

**Comment by tidusjar** [comment]
Nice job. It's now in develop!
