### ISSUE TITLE
cant connect to ombi outside my network

### ISSUE THREAD

**Issue by nooblord1** [tidusjar/Ombi#2443]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.13.5.5291 

#### Operating System:

Windows10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Hello, im pretty new to ombi and plex and such. i have tried setting up ombi to work outside my network. i did port forward and made an exception to my firewall but it wont let me get into ombi anyway, hope someone can help.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by nooblord1** [comment]
okay i just checked it and it could not find service, ive tried to restart ombi but it still cant find any service :)

**Comment by tidusjar** [comment]
jump on discord. This is not an issue with Ombi
