### ISSUE TITLE
Automatic Updater does not start Ombi after completion (Windows)

### ISSUE THREAD

**Issue by rg9400** [tidusjar/Ombi#2446]
#### Ombi build Version:

V 3.0.3567

#### Update Branch:

Develop

#### Operating System:

Windows 10

#### Problem Description:

I used to have problems with auto-updating Ombi, but then I switched away from NSSM and used this guide: https://github.com/tidusjar/Ombi/wiki/Running-Ombi-as-a-Scheduled-Task-(Windows)

I can run/stop the service using Task Scheduler perfectly, and it automatically shuts down Ombi, downloads the new updated source files, and replaces my current files. So in other words, the update is successful now (which was not happening before). 

However, the very last step -- to start the Ombi service again -- does not work. After every update, Ombi is offline, so I have to start it up again. As you can see though, the version keeps updating, so the issue is fairly isolated to just starting the service back up.

**Comment by tidusjar** [comment]
There is already an open issue about this.
