### ISSUE TITLE
Unable to create filter for TV shows

### ISSUE THREAD

**Issue by safusu** [tidusjar/Ombi#2458]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu 16.04.2

#### Problem Description:

Can't create a filter for requested TV shows - it only appears for requested movies. From inspector, it looks like the code for the button is present only on the movie-requests side.

[Link to screenshots](https://imgur.com/a/cnkFPtO)

**Comment by tidusjar** [comment]
Correct. I've not done this yet

**Comment by melyux** [comment]
Could you reopen this until you add that for tracking purposes?
