### ISSUE TITLE
Ombi refuses to connect to PMS

### ISSUE THREAD

**Issue by JTT-JustTheTip** [tidusjar/Ombi#2461]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

1.12.2.4929 

#### Operating System:

Docker - Ombi run in container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
23/08/2018 16:00:28fail: Ombi.Controllers.External.TesterController[1000]
23/08/2018 16:00:28      Could not test Plex
23/08/2018 16:00:28System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
23/08/2018 16:00:28   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
23/08/2018 16:00:28   --- End of inner exception stack trace ---
23/08/2018 16:00:28   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
23/08/2018 16:00:28   at System.Threading.Tasks.ValueTask`1.get_Result()
23/08/2018 16:00:28   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
23/08/2018 16:00:28   at System.Threading.Tasks.ValueTask`1.get_Result()
23/08/2018 16:00:28   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
23/08/2018 16:00:28   at System.Threading.Tasks.ValueTask`1.get_Result()
23/08/2018 16:00:28   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
23/08/2018 16:00:28   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
23/08/2018 16:00:28   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
23/08/2018 16:00:28   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
23/08/2018 16:00:28   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
23/08/2018 16:00:28   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
23/08/2018 16:00:28   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 242
```

#### Problem Description:

When I try to connect Ombi to PMS it says "We could not connect to the Plex server AlphaServer!", this is what I get in the container logs when I try to connect to PMS. Similar to the problem found in Bug #1650 

#### Reproduction Steps:

Installed the master version of the linuxserver/ombi container and then tried to connect to Plex

**Comment by JTT-JustTheTip** [comment]
I realised just a moment ago what the issue was, the autofill feature for the details takes the servers public port which I've changed, just need to change the port field in Ombi back to 32400, silly mistake on my part. Thanks for the quick response tho, love it

Side question, is music requesting on the roadmap by chance, like Headphones and Lidarr?

Thanks again

**Comment by tidusjar** [comment]
no problem,

I'm actually working on Lidarr at the moment, it's not ready yet, but if you want to use it early, then switch to using the develop builds (I push stuff to develop once i know it works)

**Comment by JTT-JustTheTip** [comment]
whats the tag for the development build, ive tried linuxserver/ombi:dev and linuxserver/ombi:develop. I couldnt find anything in the settings on Ombi to swap either. Although I may just be being blind to be fair
