### ISSUE TITLE
Sonarr - AutoApprove fails for "New Series" only - Bad Request - 0 is not a valid ID

### ISSUE THREAD

**Issue by hummerpj** [tidusjar/Ombi#2466]
#### Ombi build Version:

v 3.0.3587

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

v 1.13.5.5291

#### Operating System:

Windows 10 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-08-26 12:38:59.293 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/sonarr/api/series/
2018-08-26 12:38:59.342 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/sonarr/api/series/
2018-08-26 12:38:59.383 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://localhost:8989/sonarr/api/series/0

```

#### Sonarr Logs:

```

18-8-26 12:38:59.0|Debug|Api|[GET] /api/Episode?seriesId=0: 200.OK (7 ms)
18-8-26 12:38:59.0|Trace|Http|Req: 57768 [GET] /api/rootfolder
18-8-26 12:38:59.0|Debug|RootFolderService|Generating list of unmapped folders
18-8-26 12:38:59.1|Debug|RootFolderService|1 unmapped folders detected.
18-8-26 12:38:59.1|Trace|Http|Res: 57768 [GET] /api/rootfolder: 200.OK (33 ms)
18-8-26 12:38:59.1|Debug|Api|[GET] /api/rootfolder: 200.OK (33 ms)
18-8-26 12:38:59.1|Trace|Http|Req: 57769 [GET] /api/series
18-8-26 12:38:59.1|Trace|Http|Req: 57770 [GET] /api/Episode?seriesId=0
18-8-26 12:38:59.1|Trace|Http|Res: 57769 [GET] /api/series: 200.OK (76 ms)
18-8-26 12:38:59.1|Trace|Http|Res: 57770 [GET] /api/Episode?seriesId=0: 200.OK (5 ms)
18-8-26 12:38:59.1|Debug|Api|[GET] /api/series: 200.OK (76 ms)
18-8-26 12:38:59.2|Debug|Api|[GET] /api/Episode?seriesId=0: 200.OK (5 ms)
18-8-26 12:38:59.2|Trace|Http|Req: 57771 [POST] /api/series/
18-8-26 12:38:59.2|Trace|NzbDroneErrorPipeline|Handling Exception
18-8-26 12:38:59.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path
18-8-26 12:38:59.2|Trace|Http|Res: 57771 [POST] /api/series/: 400.BadRequest (45 ms)
18-8-26 12:38:59.2|Debug|Api|[POST] /api/series/: 400.BadRequest (45 ms)
18-8-26 12:38:59.2|Trace|Http|Req: 57772 [POST] /api/series/
18-8-26 12:38:59.3|Trace|NzbDroneErrorPipeline|Handling Exception
18-8-26 12:38:59.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path
18-8-26 12:38:59.3|Trace|Http|Res: 57772 [POST] /api/series/: 400.BadRequest (34 ms)
18-8-26 12:38:59.3|Debug|Api|[POST] /api/series/: 400.BadRequest (34 ms)
18-8-26 12:38:59.3|Trace|Http|Req: 57773 [GET] /api/series/0
18-8-26 12:38:59.3|Trace|NzbDroneErrorPipeline|Handling Exception
18-8-26 12:38:59.3|Warn|NzbDroneErrorPipeline|API Error

[v2.0.0.5228] NzbDrone.Api.REST.BadRequestException: BadRequest :0 is not a valid ID
   at NzbDrone.Api.REST.RestModule`1.ValidateId(Int32 id) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 33
   at CallSite.Target(Closure , CallSite , RestModule`1 , Object )
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceById>b__29_0(Object options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 82
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

```

#### Problem Description:

Been trying to debug an issue I was having with a new install.  Finally was able to reproduce exact steps.  When requesting episodes for a series that has already been "added" to Sonarr there is no problem and everything seems to work as expected.  

However, if I try to request a new series that has not been previously added I get failed requests into Sonarr.

One use-case that I haven't been able to test yet is a user without "Auto Approve" role.  So I am not sure if this applies to that work flow too.  I will add to this thread if I am able to verify that.

#### Reproduction Steps:

**Working when series already "added" to Sonarr**

1. Search for show already in Sonarr but missing seasons

2. Add request for season in Ombi

3. Success in Sonarr for added season, starts downloading.

**Fails when series not "added" to Sonarr (new series)**

1. Search for show not "added" to Sonarr

2. Request any season or episode

3. Three failed requests in a row, first two "invalid path", third "0 is not a valid ID"

**Comment by hummerpj** [comment]
![image](https://user-images.githubusercontent.com/1621989/44631000-fe51cc80-a933-11e8-8e21-a8594d79abd0.png)

I tried having someone without "Auto Approve" to request some episodes but I can't seem to see where to "approve" this request in the UI.  I don't see any requests in the logs to Sonarr or in Ombi for this one so it looks like it wasn't auto approved.

**Comment by tidusjar** [comment]
Have you made your your settings are correct?

**Comment by hummerpj** [comment]
Nevermind.  Appears the user has to log-out and then log back in for permission updates to affect.  I

But I am still getting same error in the manual approval process for shows that aren't already "added" to Sonarr.

```

18-8-26 13:49:04.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path
18-8-26 13:49:04.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path
18-8-26 13:49:05.0|Warn|NzbDroneErrorPipeline|API Error

[v2.0.0.5228] NzbDrone.Api.REST.BadRequestException: BadRequest :0 is not a valid ID
   at NzbDrone.Api.REST.RestModule`1.ValidateId(Int32 id) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 33
   at CallSite.Target(Closure , CallSite , RestModule`1 , Object )
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceById>b__29_0(Object options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:line 82
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

```

**Comment by hummerpj** [comment]
Yeah settings are correct, basepath works, requests work for shows that already exist in sonarr but not for "new" ones.

I triple-checked the basepath earlier due to other threads I've read.  If I change the basepath from what I have now I get 404s so that isn't it.

The connection settings page for Sonarr is able to pull the Quality Profiles and the Root Folders just fine.

Any other settings you think I can check?  

I don't see any way to turn on debug logging or to add a proxy to Ombi so I can inspect the request/responses.  I might be able to manually feed it through a reverse proxy I have setup and capture the logs there.

**Comment by hummerpj** [comment]
Everything with Radarr and Plex integrations running smooth.

Appears I am on the latest Sonarr version.

**Comment by hummerpj** [comment]
Just checked and I am on the latest.

v 2.0.0.5228 (released June 24th)

The invalid ID only happens on the 3rd request.  I am guessing you have the internal Sonarr ID by that point since its is an URL parameter.

The first/second request is what I posted above.  Which I believe is the one to add the series to Sonarr, so makes sense there should be no ID.

Haven't looked at source but looks like Ombi retries the "add" request when the first fails.

So Sonarr doesn't like something in that JSON on the first request.  I put on "trace" logs in Sonarr but doesn't give me any more information then that.

```
18-8-26 12:38:59.2|Trace|Http|Req: 57772 [POST] /api/series/
18-8-26 12:38:59.3|Trace|NzbDroneErrorPipeline|Handling Exception
18-8-26 12:38:59.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path


18-8-26 12:38:59.3|Trace|Http|Req: 57773 [GET] /api/series/0
18-8-26 12:38:59.3|Trace|NzbDroneErrorPipeline|Handling Exception
18-8-26 12:38:59.3|Warn|NzbDroneErrorPipeline|API Error

[v2.0.0.5228] NzbDrone.Api.REST.BadRequestException: BadRequest :0 is not a valid ID
```

**Comment by tidusjar** [comment]
When you say on the 3rd request, what do you mean?

**Comment by hummerpj** [comment]
You can close this.  Appreciate the follow up and thank you for the help.

If I am able to get something accomplished I'll submit a pull request.

**Comment by SgtBatten** [comment]
@hummerpj  how did you resolve this.

All my root paths appear set. I am getting API Error: BadRequest :0 is not a valid ID when approving shows.

**Comment by mike391** [comment]
I also keep getting this error.  I restore from backup and it fixes it for about 2-3 days and then it breaks again.

**Comment by hummerpj** [comment]
@SgtBatten @mike391 

I am trying to remember any other details but its escaping me a bit.   It was mainly the rootFolderPath being messed up.  I had multiple set in Sonarr and it was set up wrong in Ombi.

There might be other things that causes this but that was my issue.  I would double and triple check your setting pages in Ombi for Radarr and/or Sonarr (depending on which you are using) to make sure everything is set correctly.  There is no validation on that page to tell you what is required and what is not (last I checked).

Lastly, you can try checking the logs in Sonarr to help you out or put a proxy between and capture requests.  Sonarr lets you change the log level to capture more data too.  

What appears to happen is that a couple different requests are fired in succession when this action takes place.  The first is to grab some show/season/episode data from Sonarr.  Even though that didn't find anything it still tries to make another request which results in passing `0` to Sonarr and showing this error.
