### ISSUE TITLE
Cannot get OMBI to work !!

### ISSUE THREAD

**Issue by markscreen** [tidusjar/Ombi#2469]
Good day all 
, I am having serious issues trying to install OMBI - I cannot launch or get it to work, I have tried install and re installing the link from Github - i have tried the windows 32 and the normal windows  v3.0.3587  and i cant get it to work - Any help will be great .. I also had a log into ombi sometime ago 6/7 months, but I have tried all the email address I have but cannt get the system to send me a new password

**Comment by tidusjar** [comment]
Need a lot more information.

Please open up a new issue and follow the issue template.
