### ISSUE TITLE
trying to request Flowers (TV Show)

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2475]
#### Ombi build Version:

V 3.0.

#### Update Branch:

Develop

#### Media Sever:

Plex

#### Operating System:

any

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

try to request the tv show 'Flowers' and nothing happens. cant even see episode list for seasons.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

1. search for tv show flowers
2. click request all
3. ?????
4. Click request seasons and nothing loads.
5. Raise github issue 🤣

**Comment by tidusjar** [comment]
Fixed in develop
