### ISSUE TITLE
PLEX Oauth Doesn't Seem To Work?

### ISSUE THREAD

**Issue by firrae** [tidusjar/Ombi#2485]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Latest

#### Operating System:

Unraid (Linux)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Nothing seems to be captured? I see no logs for anything recent, only an issue I had months ago.

```

#### Problem Description:

When I enable Plex Oauth the button appears as expected, but when it's pressed nothing happens other than a delayed notification that says "Authenticating Loading... Please Wait". Once I log in using the Imported Plex users via the normal Ombi login that notificaiton will keep appearing. If I don't try to auth with PLEX that notification never appears.

I have left the login trying to "load" for over an hour now with no obvious progress or error logged.

#### Reproduction Steps:

See above. Otherwise I just installed using the linuxserver.io Docker image.

Any help in troubleshooting is greatly appreciated.

**Comment by tidusjar** [comment]
Check if your browser blocked the popup

**Comment by dotsam** [comment]
This is an issue in both Chrome and Safari for me as both browsers’ default behaviour is to block popups that aren’t a direct result of a user action. In this case, the window.open in the login component is called in a callback nested two deep, so browsers don’t see it as being a direct result of user actions. 

The workaround is to either open the popup first and then change the location of that window after you have the Plex OAuth URL, or to open the window to an endpoint that will run the whole flow there.

**Comment by firrae** [comment]
Interesting, I will double check this out this weekend. I don't remember the pop-up block thing showing up, but I also didn't look for it specifically.

**Comment by dotsam** [comment]
Browsers may have different rules for localhost as well, which is why you may not have seen it if you’re not checking on an external instance. 

On Chrome, the location bar at least shows the “popup blocked” icon that you can click on to whitelist the site, but in Safari, the popup is silently blocked with no notification, so I was initially very confused about what was supposed to happen when first trying to use OAuth.

**Comment by tidusjar** [comment]
Fixed in develop, please can someone confirm.

Thanks for the advice @dotsam

**Comment by dotsam** [comment]
Tested and working in Chrome and Safari for me
