### ISSUE TITLE
Firefox - TV Requests info behind next request banner

### ISSUE THREAD

**Issue by christronyxyocum** [tidusjar/Ombi#2486]
#### Ombi build Version:

V 3.0.3649

#### Update Branch:

develop

#### Media Sever:

Plex

#### Operating System:

LSIO Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

In Firefox only, if you click the View button for a TV show request, the banner for the one below it gets HUGE and then you can't see the info for the request you clicked View for. Seems like it's behind the banner for the next Show below it.

https://chrisyocum.com/Images/ShareX/2018-08-30_15-15-56.gif

Issue is not present in Chrome.

#### Reproduction Steps:

In Firefox, go to TV Show requests and click the View button for a show.

**Comment by tidusjar** [comment]
@stpanzer Please feel free to submit a PR!

**Comment by tidusjar** [comment]
Fixed in develop
