### ISSUE TITLE
Get Quality Profiles spins endlessly

### ISSUE THREAD

**Issue by Outcats** [tidusjar/Ombi#2488]
#### Ombi build Version:

V 3.0.3587
--

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

core.js:1624 ERROR 
e {headers: t, status: 405, statusText: "OK", url: "https://*URL*/ombi/api/v1/Radarr/Profiles/", ok: false, …}
error
:
{message: "MethodNotAllowed"}
headers
:
t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
:
"Http failure response for https://*URL*/ombi/api/v1/Radarr/Profiles/: 405 OK"
name
:
"HttpErrorResponse"
ok
:
false
status
:
405
statusText
:
"OK"
url
:
"https://*URL*/ombi/api/v1/Radarr/Profiles/"
__proto__
:
Object

```

#### Problem Description:

I've setup and synced Plex without issue, however when trying to sync Radarr and Sonarr I've populated the fields, the test button confirms all correct but when I click to get the Quality Profiles or Root Folder I get the above error (Within Chrome) and Similar errors in Edge (My two browsers)

I've tried to access the address directly and while the interface for Radarr loads it seems to be stuck with the dots sliding back and forth endlessly.

#### Reproduction Steps:

Populate fields 
click on Get Quality Profile

**Comment by tidusjar** [comment]
Have you filled in everything? Do you have a base URL?

**Comment by Outcats** [comment]
Yeah, see below:

![image](https://user-images.githubusercontent.com/11628565/44906946-485cf880-ad0e-11e8-8f91-1b2d02b67126.png)

**Comment by Outcats** [comment]
I've grabbed an older version (Ombi v3.0.3304) and tested it and when loaded up I was able to pull those lists via the buttons, so it seems that something has changed with the functionality stopping the details from pulling. If I save the detail and copy the database file back to the latest install the drop down lists de-populate.

**Comment by tidusjar** [comment]
Base url needs to be `/radarr` make note of the `/`

**Comment by Outcats** [comment]
Hey sorry I did try with both with and without the / but made no difference, just tried again and still same error in the console with the endless spinning.

**Comment by Outcats** [comment]
Hey buddy, just saw you've closed this issue, please don't close this as this is still a problem.

**Comment by tidusjar** [comment]
So the machine that Ombi is running on, radarr can be accessed at `http://localhost:7878`?

**Comment by Outcats** [comment]
Yup, just tried it and loaded without incident straight away.

**Comment by tidusjar** [comment]
What's in your log files? it's in the logs directory

**Comment by Outcats** [comment]
The only entry in my logs file is an unrelated issue regarding Plex but I'm aware of that and there was only one instance of this error. I didn't bother attaching the logs due to this. As I said the only place I can get an error to show is via the Console on any of my Browsers.

**Comment by Haywood78** [comment]
From your screenshot it looks like your accessing Radarr via https? Do you have ssl enable in Radarr settings? If so disable it or check ssl in ombi and enter your ssl port assigned in Radarr.

**Comment by Outcats** [comment]
I do nto have SSL enabled in ether Radarr or Ombi. My IIS rules forces HTTPS but that is handled outside of the applications and since I'm working with Localhost it shouldn't matter anyway.

**Comment by Outcats** [comment]
So I was playing around some more and installed the second to latest version, I was testing and everything was looking good. Then I tried to use in my live environment and I was getting issues being unable to test Radarr and was looking into it further. It seems if I access Ombi via Localhost:5000/ombi I am able to setup Radarr and Sonarr and all tests and pulls back the correct profiles. As soon as I access it via my domain it no longer can pull back or test on this version. If I put in the address as localhost for Radarr I get the same successful test but no profiles etc, but if I put my external domain in for the address I get the following error after a few seconds of waiting:

2018-09-01 20:25:06.505 +01:00 [Error] Could not test Radarr
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.OmbiHttpClient.<SendAsync>d__5.MoveNext() in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Radarr.RadarrApi.<SystemStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Radarr>d__63.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 285

**Comment by Outcats** [comment]
There seems to be some issue with it being behind an IIS reverse proxy when it can't handle connecting, but I can't exactly release it for my Plex users to use if it is not on a forward facing domain.

**Comment by distaula** [comment]
I ran into this last week and discovered cuttoff is not an object with Id/Name, but just an int referring to the Id.  I didn't notice any place where name was used but didn't look too hard.  I got it working by changing the type of cutoff to be just an int.

I didn't check to see if there was a Sonarr API change but that'd be my guess.

**Comment by mongolianmiller** [comment]
I... feel stupid. I ended up fixing this by opening port 8989 (the default Sonarr port) on the server serving up Sonarr (separate from Ombi for me). Without the port open, it just spun and spun.

**Comment by ocxo** [comment]
Thanks @mongolianmiller, stupid here with you 😄 Firewall rule blocked me as well. Thanks for helping me fix!

**Comment by Outcats** [comment]
Not for me, I've tried opening the port but it made no difference, the sites are behind a reverse proxy so that shouldn't be needed anyway. It seems to be an issue when trying to talk to the Sonarr/Radarr API but I suspect that the IIS Reverse Proxy is what is stopping the communication rather than the issue being with Ombi directly, just unable to work it out myself!

**Comment by Outcats** [comment]
So taking this further I have found that if I access:

https://*domain*/ombi/swagger/index.html

I get the following error:


![image](https://user-images.githubusercontent.com/11628565/47797932-3d7b1000-dd1f-11e8-84d2-6974cdc7acfa.png)

Checking my debugger on my browser I see it is trying to access:

https://*Domain*/swagger/v1/swagger.json/

but if I change my URL to this it loads fine:

https://*Domain*/ombi/swagger/v1/swagger.json/

As the other issues I'm seeing is API related it all seems to fit together now. I think if I can get Swagger to honour my baseURL of /ombi/ then this should solve my issue.

Any advice?

**Comment by goldenpipes** [comment]
Is there a base url in ombi settings?
![image](https://user-images.githubusercontent.com/6140137/48639042-f8e6aa00-e997-11e8-932d-445df0f766b8.png)

**Comment by Outcats** [comment]
Yeah, got that covered. I've got an idea what is causing it and am playing around in my free time.
________________________________

**Comment by jbart12** [comment]
I fixed by allowing ports 7878 and 8989 through the firewall

**Comment by kiwijunglist** [comment]
Hi I have this issue as well.
Not using swag or reverse proxy or anything.

My radarr is http://192.168.1.173:7878/
My ombi is http://192.168.1.173:3579/

I'm accessing the settings for radar here - http://192.168.1.173:3579/Settings/Radarr

**Ombi - Radarr Settings**

Hostname/IP: 192.168.1.178
Port: 7878
SSL: No
Base url:

Test connectivity = Sucessfully connected

Load Profiles: this works and I can select all the profiles and then click Submit.

**However** - The problem is that if I go back into the radarr settings it doesn't save the profiles like it does in sonarr, all the other settings are saved, but the profile is left on spinning icon with blank profiles.

**Comment by kiwijunglist** [comment]
![001](https://github.com/Ombi-app/Ombi/assets/1858199/971838cd-a6c3-4155-95dd-3436cace4564)

![002](https://github.com/Ombi-app/Ombi/assets/1858199/e1b0e32a-e881-4180-a539-e3fa6ea6b6cf)
