### ISSUE TITLE
Get Quality Profiles spins endlessly

### ISSUE THREAD

**Issue by Outcats** [tidusjar/Ombi#2489]
(Duplicate of issue 2488 due to the fact it was closed while still an issue - I only have the url without / in the image but I used both already while testing this and nether worked.)

#### Ombi build Version:

V 3.0.3587
--

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

core.js:1624 ERROR 
e {headers: t, status: 405, statusText: "OK", url: "https://*URL*/ombi/api/v1/Radarr/Profiles/", ok: false, …}
error
:
{message: "MethodNotAllowed"}
headers
:
t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
:
"Http failure response for https://*URL*/ombi/api/v1/Radarr/Profiles/: 405 OK"
name
:
"HttpErrorResponse"
ok
:
false
status
:
405
statusText
:
"OK"
url
:
"https://*URL*/ombi/api/v1/Radarr/Profiles/"
__proto__
:
Object

```

#### Problem Description:

I've setup and synced Plex without issue, however when trying to sync Radarr and Sonarr I've populated the fields, the test button confirms all correct but when I click to get the Quality Profiles or Root Folder I get the above error (Within Chrome) and Similar errors in Edge (My two browsers)

I've tried to access the address directly and while the interface for Radarr loads it seems to be stuck with the dots sliding back and forth endlessly.

#### Reproduction Steps:

Populate fields 
click on Get Quality Profile

**Comment by tidusjar** [comment]
Duplicate #2488
