### ISSUE TITLE
Error on Pushover Notification - New Issue

### ISSUE THREAD

**Issue by zarxic** [tidusjar/Ombi#2495]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Emby

#### Media Server Version:

3.5.2.0

#### Operating System:

Win10 1803

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: https://api.pushover.net/1/messages.json?token=TOKENKEY&user=USERKEY&message=Hello! The user &amp;#39;zarxic&amp;#39; has reported a new issue for the title Deadpool 2(undefined)! &lt;/br&gt; Video/Quality - pixelated : bad quality during action sequences

```

#### Problem Description:

Pushover notifications for New Issue are not sent.  I get all other notification types from Pushover; test, Issue Comment, Issue Resolved, etc.  The above error is from the open cmd window of Ombi and happens when a new issue is created.

#### Reproduction Steps:

Each time a new issues is reported, the above error will appear in the cmd window.  Repeatable every time a new issue is created.
[log-20180902.txt](https://github.com/tidusjar/Ombi/files/2343593/log-20180902.txt)

**Comment by tidusjar** [comment]
This has been fixed in develop
