### ISSUE TITLE
Cannot configure gmail email notifications. 

### ISSUE THREAD

**Issue by Clifford10** [tidusjar/Ombi#2499]
#### Ombi build Version:

V 3.0.3682

#### Update Branch: develop

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

Not a server issue

#### Operating System:

Ombi uru

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

2018-09-07 10:40:15.176 -05:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: The SMTP server has unexpectedly disconnected.
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 94
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225

```

#### Problem Description:

Cannot get email notifications to work. 



#### Reproduction Steps:

I have tried it with SSL on and off using port 587 or 465. I created an App password on my Google account and tried that password as well. Two step verification is OFF for this google account.

![ombiemail](https://user-images.githubusercontent.com/43072052/45229562-c3cd2580-b28b-11e8-9ee8-91fe5c30a111.JPG)

**Comment by stpanzer** [comment]
Can you reach smtp.gmail.com by pinging it?

**Comment by gbdavidx** [comment]
I get while trying to use gmail There was an error when sending the Email message, please check your settings.

**Comment by thickconfusion** [comment]
I am having an issue as well with this. I am using my app password with smtp.gmail.com and I have tried both 465 and 587.

**Comment by thickconfusion** [comment]
I fixed the issue. It appears Gmail SMTP was blocking connection to the VPN server I was on.
