### ISSUE TITLE
Ombi Hangs on Loading

### ISSUE THREAD

**Issue by RikT** [tidusjar/Ombi#2506]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No info in Logs

```

#### Problem Description:

I just updated to the latest version and now ombi will not load it just hangs on Loading page and goes no further.

#### Reproduction Steps:

Upgraded and started service

**Comment by tidusjar** [comment]
Please read the release notes.
