### ISSUE TITLE
Admin cannot override path settings on my own requests.

### ISSUE THREAD

**Issue by wolffie0603** [tidusjar/Ombi#2507]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

3.69.1

#### Operating System:

Windows Server 2008 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

```

#### Problem Description:

As an admin with auto approval capabilities, I am not able to override the default path of my own requests.

#### Reproduction Steps:

I can override the paths and formats of all other requests from non admin users, while I approve their requests. When I submit a request for my own content, it skips the approval screen, and subsequently skips the override options.

**Comment by tidusjar** [comment]
Admins requests are auto approved, so it's automatically sent to sonarr/radarr.

**Comment by wolffie0603** [comment]
I'm aware of the auto approval, I even mentioned it. That's not my question. 
I'm wondering where are the options to change the "Root Folder" and the "Quality Profile" on items that I submit? There appears to be more controls for regular user requests then there is for admin requests.
