### ISSUE TITLE
Search and add doesnt work, Swagger shows Failed to load API definition.

### ISSUE THREAD

**Issue by masterxdk** [tidusjar/Ombi#2510]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Ubuntu 18.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

https://pastebin.com/sdhxdiT3

#### Problem Description:

So nothing comes up at all when searching for movies or selected one of the predefined searched (popular, upcoming etc). In tv shows it shows some shows by default, search seems to work, but cant add the show
Swagger shows: Failed to load API definition.
The integration with Organizr doesnt seem to work either

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Can you upload the logs when navigating to swagger?

**Comment by masterxdk** [comment]
> Can you upload the logs when navigating to swagger?

Sure, here you go: https://pastebin.com/xuFc4ZDV

**Comment by tidusjar** [comment]
Can you navigate to that file? example: `http://localhost:5000/swagger/v1/swagger.json`

**Comment by masterxdk** [comment]
> /swagger/v1/swagger.json

Yeah, seems like it
![ombijson](https://user-images.githubusercontent.com/1771591/45718548-bd994c00-bb9d-11e8-80ee-40b3d5a4d00c.png)

**Comment by tidusjar** [comment]
Something real strange is going on. 

Your the only person to have ever reported anything like this so I'm going to say there's an environmental issue at play. 

Is it possible you can try on another machine? Possible a VM or something?

**Comment by masterxdk** [comment]
Yeah i can try some stuff.. But it is a more or less brand new VM in Azure...

**Comment by masterxdk** [comment]
I've done multiple uninstall, remove of all files and total cleanup of files. Then reinstall and it would still fail.
But now it works after i updated the VM (dont know which updates it was, restartet, removed the db and cleared the logs). What the hell! Now its just the connection to Organizr thats not working. Will look at that and perhaps open an issue regarding that.
Thanks for the help anyway!

**Comment by justinross** [comment]
I just ran into this problem, as well. I have a base URL set on Ombi (“hostname/request”), and it looks like swagger is looking for “hostname/swagger/v1/swagger.json” (ignoring the base URL setting, pointing at the server root). 
![884b618d-6b68-4c02-b850-bce377d1b9f0](https://user-images.githubusercontent.com/1120106/48111467-6e1ee600-e206-11e8-8ccd-fc892b8cb173.jpeg)
