### ISSUE TITLE
cannot search for movies

### ISSUE THREAD

**Issue by speedracer18** [tidusjar/Ombi#2512]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Open Beta

#### Media Sever:

Emby or Plex

#### Media Server Version:

3.5.20

#### Operating System:

(windows 10)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

[log-20180916.txt](https://github.com/tidusjar/Ombi/files/2386995/log-20180916.txt)

```

#### Problem Description:
when trying to use the search suggestions features on ombi i get a bunch of err msgs

#### Reproduction Steps:
from within ombi search click on movies then click suggestion and click any of the options and thats when the errors occurs.
.

**Comment by tidusjar** [comment]
Can you log out and then back in and try again?

**Comment by speedracer18** [comment]
thanks i figured out the problem whenever i upgraded to the new version and
imported my users from emby for some reason it did not import users and
permissions.
