### ISSUE TITLE
Add "Blackberry Flat" as a theme

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#2513]
#### Ombi build Version:
V 3.0.3477+
#### Update Branch:
Open Beta
#### Media Sever:
Plex/Emby
#### Media Server Version:
Unneeeded
#### Operating System:
Unneeded
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Unneeeded
#### Problem Description:
I decided to plexify Ombi, alongside various other common home theater services. Would be great to see it as a built-in theme. The repo will be maintained moving forward, but was last tested with V3.0.3477.
https://github.com/Archmonger/Blackberry-Flat

#### Reproduction Steps:
Unneeded

**Comment by Archmonger** [comment]
Github pages has been set up for hosting BBF css.
`https://archmonger.github.io/Blackberry-Flat/bbf_ombi.css`

**Comment by Archmonger** [comment]
New theme: Blackberry Flat Ombi in Organizr. Optimizes Ombi to be viewed within Organizr+SSO alongside other Blackberry Flat themes. Would be great if two preset theme options were made available. "Blackberry Flat" and "Blackberry Flat in Organizr".
https://archmonger.github.io/Blackberry-Flat/bbf_ombi_in_organizr.css

**Comment by YodaSpow** [comment]
@Archmonger thanks for this awesome theme. I have been tweaking the CSS a bit.

Is there a way to retain the slideshow on the login page when I add the: `https://archmonger.github.io/Blackberry-Flat/bbf_ombi.css`

**Comment by tidusjar** [comment]
I'm going to close this for now, but if we need we can add it to the v4 list.
