### ISSUE TITLE
Add link on request page to media object in Sonarr/Radarr

### ISSUE THREAD

**Issue by lucienorrin** [tidusjar/Ombi#2517]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Problem Description:

Adding a link on the movie/show request banner in Ombi to the object in the download client would be awesome. I've been troubleshooting several issues with my Ombi install and have found navigating to the media object in sonarr/radarr is where most of my time is spent. 

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
Ombi has no concept of downloading. This is not really a feature I plan to add. If you still want this please raise in feathub.

**Comment by lucienorrin** [comment]
I should have been more specific, not a link to the download client but to the object in sonarr/radarr

**Comment by tidusjar** [comment]
Ombi is really intended for the users, having some sort of link seems kind of redundant since in most Ombi use cases the user will not know what is Sonarr or even Radarr.

We could do it just for the admin, please raise something on Feathub if you think it's worth adding to Ombi.
