### ISSUE TITLE
Swedish translation is missing?

### ISSUE THREAD

**Issue by Naesstrom** [tidusjar/Ombi#2518]
#### Ombi build Version:

3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Testing on OSX before launching on FreeNAS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
```

#### Problem Description:

Can't select swedish as a translated language, When looking at the english translation I can't see swedish mentioned either.
![screen shot 2018-09-19 at 13 16 25](https://user-images.githubusercontent.com/6575206/45750329-ddb52380-bc0e-11e8-892c-e1f439a4059a.png)

#### Reproduction Steps:

Try to select Swedish in the translations.

**Comment by tidusjar** [comment]
Fixed in develop
