### ISSUE TITLE
Is there a way to disable the newsletter 

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#2522]
#### Ombi build Version: 
3.0.3587
V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

(Windows 10)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

How to I disable the newsletter? I tried to go into settings and when I uncheck enable newsletter it is not saved and if I go back I can see that it is checked again. 

#### Reproduction Steps:

Attempt to disable the newsletter.

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by tidusjar** [comment]
Wrong issue, my bad

**Comment by tidusjar** [comment]
Cannot reproduce, what browser?

**Comment by goku-son** [comment]
It’s on iOS safari browser.  I will try on another browser and check back in.

**Comment by goku-son** [comment]
Working just fine. Must have been a browser issue on my side.
