### ISSUE TITLE
I do not see the requests of the users

### ISSUE THREAD

**Issue by luigi108** [tidusjar/Ombi#2524]
#### Ombi build Version:

V 3.0.3587

#### Media Sever:

Plex

#### Media Server Version:

1.13.5.5332

#### Operating System:

Linux 4.15.0-33-generic #36~16.04.1-Ubunt

#### Problem Description:

I just installed ombi for my plex, I created users and placed orders, I'm an administrator and I can not see the requests of the users.

I add a new request and users can see it, but I do not see my own requests either

**Comment by tidusjar** [comment]
Is there any errors in your browsers console?

What does it look like, can you provide a screenshot?

**Comment by thejacer87** [comment]
same things for me.

using linuxserver/docker

![image](https://user-images.githubusercontent.com/6412919/45912971-21f71e00-bddf-11e8-8532-2f2ad63a2ee2.png)
![image](https://user-images.githubusercontent.com/6412919/45913367-e0b63c80-bde5-11e8-90ec-519bb4585d0c.png)

**Comment by tidusjar** [comment]
I meant anything in the console when navigating to the requests page? 

Are you also sure there are requests from the users?

**Comment by tidusjar** [comment]
Strange, let me know if it happens again
