### ISSUE TITLE
Lost Admin access

### ISSUE THREAD

**Issue by cabagekiller** [tidusjar/Ombi#2526]
#### Ombi build Version:

V 3.0.3776

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

latest

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I lost admin access. It appears it was supposed to follow plex but it seems i lost it.

#### Reproduction Steps:

For me, I deleted everything and reinstalled. After setup I had issue so I rebooted my computer and i lost admin access

**Comment by iceman73** [comment]
I have a similar issue I can log in with local users, but cannot login with plex, as all plex users show unauthorized

**Comment by tidusjar** [comment]
This is due to the Plex API. They are authenticating with Plex. 

OP, if you deleted and reinstalled everything you would have lost everything
