### ISSUE TITLE
Music request does not trigger a search in Lidarr due to 405 response

### ISSUE THREAD

**Issue by anojht** [tidusjar/Ombi#2527]
Album search endpoint in Lidarr `/command/AlbumSearch` returns a HTTP 405 therefore we are unable to do album search when requesting for albums in Ombi. 

The request fails to do search but sets the album to monitored status and throws album is already monitored error.

Relevant logs:
```
StatusCode: MethodNotAllowed, Reason: Method Not Allowed, RequestUri: http://171.17.0.1:8686/api/v1/command/AlbumSearch
[40m[1m[33mwarn[39m[22m[49m: Ombi.Core.Engine.MusicRequestEngine[0]
Tried auto sending album but failed. Message: Album is already monitored

[40m[1m[33mwarn[39m[22m[49m: Ombi.Core.Engine.MusicRequestEngine[0]
Tried auto sending Album but failed. Message: Album is already monitored
```

Already spoke to Lidarr devs about this and this issue is for tacking purposes.

**Comment by anojht** [comment]
Note: Must pass command name as parameter like we do in radarr and sonarr according to lidarr dev.

**Comment by anojht** [comment]
fixed in develop 😄

**Comment by tjsnow** [comment]
I think this is happening again. Latest release 4.0.999.0
