### ISSUE TITLE
{Feature Request] Add Movie/TV Show Ratings to main screen and access limit

### ISSUE THREAD

**Issue by Viper911** [tidusjar/Ombi#2532]
It would be nice to know that the movie or tv show is rated when requesting.  Also, in terms of user access it would be good to only allow certain ratings to show up and be requested.

**Comment by Viper911** [comment]
For clarity I'm speaking of R, PG type rating..  not to be confused with likability rating 4.5, 3.2 rating.

**Comment by tidusjar** [comment]
Please raise this on feathub..

These BBFC ratings are also UK specific. So I'd need to add the functionality of setting a user to a country for this to work as I'd need the American rating systems etc.
