### ISSUE TITLE
Can't Select Quality and Root Profiles Settings for Individual Users

### ISSUE THREAD

**Issue by daanvb** [tidusjar/Ombi#2535]
#### Ombi build Version:

V 3.0.3793

#### Update Branch:

develop

#### Media Sever:

Plex

#### Media Server Version:

Latest Beta

#### Operating System:

Win 10

#### Problem Description:

When trying to setup Quality and Root profiles settings for individual users, nothing is displayed to enable this

![capture](https://user-images.githubusercontent.com/17300780/45973020-32a0d180-c035-11e8-9802-c9868cc87e40.JPG)

**Comment by tidusjar** [comment]
Do you have Radarr or Sonarr enabled?

**Comment by daanvb** [comment]
I have both enabled

**Comment by tidusjar** [comment]
Fixed in develop
