### ISSUE TITLE
"View On Plex" not obtaining machineid

### ISSUE THREAD

**Issue by NicJames2378** [tidusjar/Ombi#2538]
#### Ombi build Version:
V 3.0.3795

#### Update Branch:
master

#### Media Sever:
Plex

#### Media Server Version:
3.57.1

#### Operating System:
UnRaid 6.5.3

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
```

N/A

```

#### Problem Description:

I have seen where this is labeled as fixed, but it seems that the fix didn't correct all of the issue?

After setting the Plex Configuration settings correctly and verifying that everything works (i.e., movies are populating in Ombi and showing "requested", "available", etc), the "View On Plex" button is not working correctly. It is returning a malformed URL in such taht, instead of showing
* "https://app.plex.tv/web/app#!/server/TheTrove/details?key=library%2Fmetadata%2F49"
it shows 
* https://app.plex.tv/web/app#!/server//details?key=library%2Fmetadata%2F49

It seems that the machineid either is not being set when saving the settings, or it is not being properly read when loading the webpage. 

#### Reproduction Steps:

On an existing or fresh install of Ombi, navigate to "Settings>Media Server>Plex" ([http://IP:PORT/Settings/Plex]) and click "Add Server". After inputting all pertinent information, pressing "Submit", and confirming in a new tab that the Plex integration is properly working (see above), attempt to press the "View On Plex" button on [http://IP:PORT/search]. This will result in a page saying "You must be lost. This page doesn't exist" from Plex.

**Comment by NicJames2378** [comment]
Indeed. I have the Ombi "Machine Identifier" set to the same as the Plex server name.

**Comment by tidusjar** [comment]
Has that always been set? It's when we sync with Plex then we construct the URL with the Machine Identifier, so if it was not filled it at the time of the sync it will be incorrect

**Comment by NicJames2378** [comment]
That could be it. I thought it'd been set since syncing, but it is possible I missed it the first time. Most of my server maintainence happens after all day at work then school, so I'm pretty shot by then.

I will be home in about 3 hours and will test recreating and setting the I'd *before* syncing and check back with you.

**Comment by NicJames2378** [comment]
Update: I removed the server in Ombi, restarted, and readded (copy/pasted values back in from 'old' one). I clicked "submit" before "manually run full sync"; issue persists. Perhaps I need to delete the Plex cache manually to force it to try updating again? No idea. Not sure how to go about that either, but I'm open to trying anything you need.

**Comment by NicJames2378** [comment]
On further investigation, it would seem that the issue is in updating the database for cached content. Looking into the "OMBI.db" file at the "PlexServerContent" table, the URL values appear to not be updating for existing content when a manual resync is done. In good news, however: the machineidentifier does seem to be setting correctly in "GlobalSettings/PlexSettings".

I am unsure if simply deleting the PlexServerContent would work or be a good idea as it seems to be using a few relationships in the database and could possibly break things? I'll let you decide on that since you know more about your program than I do. Let me know if there's anything more I can do!

**Comment by tidusjar** [comment]
Yeah delete the records from PlexServerContent, PlexEpisodes and PlexSeasons content then just run the sync
