### ISSUE TITLE
Admin options

### ISSUE THREAD

**Issue by wolffie0603** [tidusjar/Ombi#2547]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

3.71.1

#### Operating System:

Windows Server 2008R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Where are the Admin options to override the "Root Folder" and "Quality Profile" with admin requests?

#### Reproduction Steps:

I see the options when regular user requests need to be approved, but not when admins request.

**Comment by tidusjar** [comment]
You can't with an admin request since they are approved straight away.
