### ISSUE TITLE
Lidarr search when new artist is added from Ombi Request

### ISSUE THREAD

**Issue by Haywood78** [tidusjar/Ombi#2549]
#### Ombi build Version:

V 3.0.3821

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Media Server Version:

<Lidarr 0.4.0.535 >

#### Operating System:

(Windows 10)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Just checked out the new update Tidujar. EXCELLENT WORK! Only have one issue during testing. Here's how to replicate it.

When I requested Imagine Dragons album "Evolve" this is a new artist added to the Lidarr library. Ombi sent the request, Lidarr adds the artist and all albums but instead of waiting to search till the album was added to the library Lidarr searched for Def Leppard "Adrenalize" not sure why as this album was not requested. I did the same process with another artist newly added and got the same results only a different artist and album. I also tested requesting an album that is already in the Lidarr library and it works perfectly. I guess one workaround would be to use Lidarr's import lists.

Thus far the only two issues I have found with music requesting is Lidarr random import issue (not your problem) and what I have described here with Ombi. Other than that GREAT JOB! on the new feature. Thanks for all your hard work!

**Comment by tidusjar** [comment]
Fixed in latest develop
