### ISSUE TITLE
TV Show request not Triggering Sonarr search

### ISSUE THREAD

**Issue by norrisp90** [tidusjar/Ombi#2550]
#### Ombi build Version: 
V 3.0.3795

#### Update Branch:
Master

#### Media Sever:
Plex

#### Media Server Version:
3.67.1

#### Operating System:
Ubuntu 18.04.1 LTS

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No logs available. No /Opt/Ombi/logs/ folder could be found/is missing.

```

#### Problem Description:

I have Sonarr V 2.0.0.5228 integration working, TV Show requests are added to the Sonarr Wanted queue but a search is not automatically triggered. I have checked that "Do not search" is unticked. Others are experiencing the same issue, see: https://www.reddit.com/r/Ombi/comments/9esb8n/ombi_sending_requests_to_sonarr_and_adding_the/#bottom-comments

#### Reproduction Steps:

Setup Sonarr integration,
Add TV Show request, approve it,
Check that TV shows are added to the Sonarr Wanted Queue, notice that no indexer search is triggered,
To verify it hasn't worked, manually trigger a Sonarr search and see that the indexers are searched and downloads are triggered.

**Comment by norrisp90** [comment]
Appears after some more testing that this is working as expected.

**Comment by l-t-k** [comment]
Im having the same problem. What have you done tot fixen this?
