### ISSUE TITLE
Automatically monitor TV Shows for new episodes

### ISSUE THREAD

**Issue by gelsas** [tidusjar/Ombi#2553]
just found out about this project is it possible to Automatically monitor TV Shows for new episodes ? 

And add them automatically as requested stuff ?

Also is it possible to automatically add all missing episodes from all tv shows in my library to requested ?

Does it detect the language of the shows as well ? 
Because I have 2 libaries

TV-Shows (my language)
and 
TV-Shows (English) 

When requesting stuff, is it possible that it automatically detects the language or to set the language for requests ?

(Sorry still trying to figure everything out)

**Comment by tidusjar** [comment]
Please can you raise these on feathub!

**Comment by tidusjar** [comment]
No, I'm not saying i'm going to do them. if they pick up enough traction then maybe.

Please keep in mind that I have a full time (quite demanding) job, a 2-year-old and a wife.
All my free time I try and dedicate to Ombi (I am not being paid for this).
