### ISSUE TITLE
Music in Newsletter

### ISSUE THREAD

**Issue by kewlrobd** [tidusjar/Ombi#2555]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows 2012 R2

#### Problem Description:

New albums are being listed in the newsletter and there no way to disable Music. This has caused the newsletter to become huge and be sent across multiple emails.

**Comment by tidusjar** [comment]
Fixed in develop
