### ISSUE TITLE
unable to delete users

### ISSUE THREAD

**Issue by RikT** [tidusjar/Ombi#2558]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Win10 pro build 1809

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

no logs

```

#### Problem Description:

in user management it seems that I am unable to delete users even when they are deleted from my Plex 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Logs?

**Comment by zidon** [comment]
I'm getting this too. Button is just dimmed and does nothing.

**Comment by mnoorgat** [comment]
I too am getting this.  Delete button highlights red when clicked, and then remains highlighted red even when moused away, but nothing happens.

I've even left it at the page for a considerable amount of time wondering if it was just slow, but unfortunately that was not it either.

Nothing in the browser console for me (only warnings telling me to consider using HTTPS).

**Comment by tidusjar** [comment]
Fixed in develop
