### ISSUE TITLE
synology reverse proxy configuration

### ISSUE THREAD

**Issue by gsemet** [tidusjar/Ombi#2560]
Hello

I am looking at how to configure synology to have it in front of ombi (it is in front of many of other tools, radarr, sonarr, emby, ...). But login fails and I do not see really how to adapt the [reverse proxy example page](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples).

On my setup, ombi is on a given port and on the / path, so not difficulty. I get a `400 Bad Request` error on:
```
POST https://myserver.synology.me:12345/api/v1/token/requirePassword
```

other http requests works, jpeg backgrounds work.

Locally, `GET http://192.168.x.y:21435/api/v1/token/requirePassword` works.

May it comes from https(port=12345) => http (port=21435) redirection?

**Comment by tidusjar** [comment]
My knowledge on reverse proxy setups is quite limited. I'd suggest you hop onto Discord and have a chat about it
