### ISSUE TITLE
Cannot send welcome email to new user

### ISSUE THREAD

**Issue by djzidon** [tidusjar/Ombi#2561]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Linux 4.4.0-135-generic #161-Ubuntu

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

1. Set up SMTP, Click test, successful test email received
2. Set up new user 'Add User To Ombi'
3. After filling out, click 'Create'
4. On 'User Management' screen, the 'Send Welcome Email' button is dimmed, and when hovering over it it's a circle with a line through it. It's unclickable

**Comment by tidusjar** [comment]
Because I out do not have you application URL filled in.

**Comment by djzidon** [comment]
Ok, thank you so much! I didn't know that if I don't have a purchased domain, that I can use the IP address. It works now! :)
