### ISSUE TITLE
TV Show request not Triggering Sonarr search

### ISSUE THREAD

**Issue by l-t-k** [tidusjar/Ombi#2563]
#### Ombi build Version:

3.0.3795

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Nothing logged.

#### Problem Description:

All requests send to Sonarr do not result in 'add and search' but are only added to wanted list

#### Reproduction Steps:
Doesn't matter if I use option auto approve or not.
'Do not search' is unchecked.
The episodes requested are found after a manual search trigger in sonarr.

Sonarr log:
https://pastebin.com/DUrduGa2

![1](https://user-images.githubusercontent.com/3150962/46534276-e90f7c80-c8a7-11e8-9b8a-83be471f65a5.jpg)

**Comment by rTiGd2** [comment]
Probably requires  "searchForMissingEpisodes" set to true in SonarrApi.cs AddSeries

**Comment by tidusjar** [comment]
We do a separate call to search. 

Does this happen on a new series being added to sonarr by ombi or an existing series in sonarr?
