### ISSUE TITLE
Don't show sonarr options default folder and quality profile if there is only 1

### ISSUE THREAD

**Issue by l-t-k** [tidusjar/Ombi#2564]
#### Ombi build Version:

3.0.3795

#### Update Branch:

Master

#### Media Sever:

Plex

#### Problem Description:

Ombi shouldn't provide the user the option to change default folder and quality profile if sonarr is only using one default folder and or one quality profile.

![11](https://user-images.githubusercontent.com/3150962/46534449-6affa580-c8a8-11e8-89cd-fcaa87918d4f.jpg)

![12](https://user-images.githubusercontent.com/3150962/46534513-aa2df680-c8a8-11e8-9231-99d76d0e3857.jpg)

**Comment by tidusjar** [comment]
Please raise this on feathub

**Comment by l-t-k** [comment]
Why? I do not think this is a feature. A dropdown menu with only one option isn't very useful in opinion.

**Comment by tidusjar** [comment]
Sorry I misread it.

**Comment by tidusjar** [comment]
Fixed in develop
