### ISSUE TITLE
TV Show Suggestions - Most Anticipated - disappearing

### ISSUE THREAD

**Issue by djzidon** [tidusjar/Ombi#2568]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Server: Linux 4.4.0-135-generic #161-Ubuntu
Viewing Ombi on personal laptop: MacBook Pro 2016 TouchBar.

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Results disappearing / collapsing. Many results flash, but after page fully loads all but one show disappear: Titans (2018.

#### Reproduction Steps:

1. Under Search, click TV, Most Anticipated Dropdown

**Comment by tidusjar** [comment]
Check the faq on the wiki
