### ISSUE TITLE
Ombi not sending anything to Couchpotato

### ISSUE THREAD

**Issue by screamq3** [tidusjar/Ombi#2573]
#### Ombi build Version:

V 3.0.3858

#### Update Branch:

develop

#### Media Sever:

NA

#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

follow on from api...

```

#### Problem Description:
Hi follow on from api, When i request via ombi it does not send to couchpotato. When i go to the config settings, it grabs the api and qualities, but when hitting connect (it doesnt say connected) it says Successfully saved the couchpotao settings, do you think this is why? Again sonarr works fine, all settings are correct for couch etc as i was previously using plexrequest with no issues.
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
is it enabled?

**Comment by screamq3** [comment]
This can be closed, for anyone with same issue, disable dognzb this cured it for me thanks. I have a new issue will open new ticket.
