### ISSUE TITLE
Can't remove local user - seemingly after upgrade

### ISSUE THREAD

**Issue by DatsiK96** [tidusjar/Ombi#2577]
#### Ombi build Version:
Version | 3.0.3795

#### Update Branch:

Branch | master

#### Media Sever:

Plex

#### Media Server Version:

Probably doesn't matter, Version 3.67.1 - Public Release

#### Operating System:

OS Architecture | X64
OS Description | Microsoft Windows 10.0.14393
Process Architecture | X64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Nothing in the logs reference me trying to delete the user

#### Problem Description:

I added a local user awhile back. Deleted the user. Did some testing, created him again. Updated to the latest, don't recall the previous version. I believe I tried deleting him after I updated, and nothing happened.

I then found out about the bulk import, and wanted to import him through there. Tried, everyone else got imported, but his username is the same as his Plex username, and now I can't change his username whatsoever. And the delete button doesn't work still.

#### Reproduction Steps:

If I click "delete" on the user page, nothing happens, no error reports in the logs, and nothing visually displays on screen. Changing the username fails to have any effect.

If a workaround is deleting the user manually in the DB somehow, let me know how to, and I'll do it.

**Comment by tidusjar** [comment]
Duplicate https://github.com/tidusjar/Ombi/issues/2558

A work around is you can give them the disabled permission and then they can't log in.
