### ISSUE TITLE
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0] - Movies don't detect / change to available

### ISSUE THREAD

**Issue by screamq3** [tidusjar/Ombi#2579]
#### Ombi build Version:

V 3.0.3858

#### Update Branch:

develop

#### Media Sever:

Plex

#### Media Server Version:

 1.13.8.5395

#### Operating System:

Windows Server 2012

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server 

```

#### Problem Description:

Hi, having setup plex on remote server where ombi runs, ombi does not detect what content i have, its linked to Couchpotato and linked to plex, i have run the library sync in plex and ombi. Each time a request is asked... it will grab it even though i already have it as it does not show "Available". Any suggestions will be greatly appreciated 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Are there any more logs?
