### ISSUE TITLE
Veiwing albums from Artist Search

### ISSUE THREAD

**Issue by Haywood78** [tidusjar/Ombi#2583]
#### Ombi build Version:

V 3.0.3911

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Windows 10)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Still have an issue of viewing albums from artist search. Clicking albums shows "loading" but then nothing happens. This issue occurs for several artists.)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
This is a known issue, it's trying to load a lot of albums and will take some time. I'm waiting on the Lidarr team to add a new API for me to improve this.
