### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by thedelph** [tidusjar/Ombi#2584]
I installed accidentally into a folder (on Windows) that has lots of other contents. Is there any way of uninstalling?

**Comment by tidusjar** [comment]
Delete the files?

**Comment by thedelph** [comment]
As mentioned, it was installed in a folder that has lots of other contents, other than date modified (which are all over the place) is there a script I can run that will know which files to delete?

**Comment by tidusjar** [comment]
No, you'd just have to see what files are in the zip and delete them from disk
