### ISSUE TITLE
Newsletter Video Image Links

### ISSUE THREAD

**Issue by anujpuri85** [tidusjar/Ombi#2586]
#### Ombi build Version:

V 3.0.3795

#### Update Branch:

Master

#### Media Sever:

Emby

#### Media Server Version:

3.5.3.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Don't think I need logs for this.

#### Problem Description:

In the newsletter, the movie/tv show images link to app.emby.media. Example for a movie: http://app.emby.media/#!/itemdetails.html?id=6c15fb99f2e6a9a25b4880f298f35564

Most of my users don't have an emby app account. Is there a way to change the default "app.emby.media" to my own server url?

**Comment by tidusjar** [comment]
Currently there is no way to change that. Please feel free to raise a feature request (see the readme)
