### ISSUE TITLE
Music Search

### ISSUE THREAD

**Issue by Wingjam** [tidusjar/Ombi#2592]
#### Ombi build Version:
V 3.0.3795 (latest)

#### Update Branch:
Master

#### Media Sever:
Plex

#### Operating System:
Windows 10

#### Question:
First of all, thank you for your amazing work.
Second, is there a way to let users search for music without Lidarr?

If I understood correctly, the music tab only appears if Lidarr is enabled, right?

![image](https://user-images.githubusercontent.com/7340240/46985682-9872fd00-d0b9-11e8-8139-08884e572b3d.png)

Thanks for your time.
Related issue : #2493

**Comment by tidusjar** [comment]
Correct. You need Lidarr.
