### ISSUE TITLE
Mass Email Formatting Not Supported

### ISSUE THREAD

**Issue by Wingjam** [tidusjar/Ombi#2593]
#### Ombi build Version:
V 3.0.3795 (latest)

#### Update Branch:
Master

#### Media Sever:
Plex

#### Operating System:
Windows 10

#### Problem Description:

When sending mass email, no formatting is supported. Everything is on the same line. Even if there are line breaks. The [wiki](https://github.com/tidusjar/Ombi/wiki/Mass-Email) does not provide any information about it. Would be nice to have at least line breaks.

Ombi : 
![image](https://user-images.githubusercontent.com/7340240/46987334-c9573000-d0c1-11e8-8a8b-dec87e80c42b.png)
Email : 
![image](https://user-images.githubusercontent.com/7340240/46987378-facffb80-d0c1-11e8-82b7-ff2b69687eab.png)

Thank you.

**Comment by tidusjar** [comment]
It's an email so it uses HTML.
