### ISSUE TITLE
Newsletter Test Fails

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#2600]
#### Ombi build Version:

V 3.0.3919

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.5.3.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

[log-20181019.txt](https://github.com/tidusjar/Ombi/files/2496491/log-20181019.txt)



```

#### Problem Description:

Unable to send a test newsletter.  The log file display an error and newsletter does not send.

#### Reproduction Steps:

Click the test button for newsletter

**Comment by tidusjar** [comment]
Duplicate #2601
