### ISSUE TITLE
Newsletter cannot be sent!

### ISSUE THREAD

**Issue by xunil75** [tidusjar/Ombi#2601]
Since i've installed the lastest dev Ombi version, I'm not able to send the Newsletter.

#### Ombi build Version:

V. 3.0.3917

#### Update Branch:

Dev

#### Media Sever:

Plex

#### Media Server Version:

1.13.9.5439

#### Operating System:

Ubuntu 16.4

#### Error:

``` 10663 Oct 19 17:12:56 plex Ombi
[16989]: Error when attempting to create newsletter
10664 Oct 19 17:12:56 plex Ombi[16989]: System.InvalidOperationException: Cannot use multiple DbContext instances within a single query execution. Ensure the query uses a single context instance.

**Comment by tidusjar** [comment]
Please can you confirm this has now been fixed in develop?

**Comment by NerdyRick** [comment]
I am getting the same error. New installation of Ombi. 
[log-20181019.txt](https://github.com/tidusjar/Ombi/files/2497196/log-20181019.txt)

**Comment by tidusjar** [comment]
In what version?

**Comment by NerdyRick** [comment]
The newest release for Windows.

**Comment by NerdyRick** [comment]
3.0.3919

**Comment by tidusjar** [comment]
See above, please try the dev build.

**Comment by NerdyRick** [comment]
Is there a config file I can move to get my setup back? So I don't have to spend hours redoing the setup of this app?
