### ISSUE TITLE
Can't remove Issues Category in Configuration.

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2602]
#### Ombi build Version:

V 3.0.3917
--

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

cant delete the top most Category in the issues config.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

try to delete the top most Category in the issues config.
button seems to click but nothing happens.

Cheers

![2018-10-19_14-11-21](https://user-images.githubusercontent.com/6140137/47238975-83dc8080-d3a9-11e8-9eec-f373403fd856.gif)

**Comment by tidusjar** [comment]
Are there any issues with that category applied?

**Comment by goldenpipes** [comment]
I removed all requests I as going to re do all of the request categories and found I could t delete that 1.

**Comment by goldenpipes** [comment]
strange I just checked again and there is an issue there that has been resolved but that I could not delete it. I went into the issues config and changed the "X # of days# from 5 to 1 and then it auto deleted.  Something must have been borked because the issue is gone and I was able to then remove the Category.

cheers brother!
