### ISSUE TITLE
Automatically Hide Requests->Music When Lidarr Disabled

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#2603]
#### Ombi build Version:
V 3.0.3919

#### Update Branch:
Open Beta

#### Media Sever:
Unneeded

#### Media Server Version:
Unneeded

#### Operating System:
Unneeded

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Unneeded

#### Problem Description:
You have it set for Search->Music to automatically be hidden when lidarr is disabled, but it seems like you have forgotten to also hide it under the request tab. This results in a unnecessary button for those of us that do not use lidarr.

#### Reproduction Steps:
Unneeded

**Comment by tidusjar** [comment]
Fixed in develop
