### ISSUE TITLE
Inconsistent tag naming format

### ISSUE THREAD

**Issue by frebib** [tidusjar/Ombi#2606]
Prior to 3923, the tag format was `3.0.XXXX` but you seem to have changed it to `Ombi-3.0.XXXX` this time. I can see there have been only a couple of tags in this format in the past.

It would be ideal if the format for the tags could stay the same as otherwise it requires unnecessary changes to our build system.

Would you mind re-tagging `Ombi-v3.0.3923` as `v3.0.3923` if this wasn't a deliberate change please?

**Comment by tidusjar** [comment]
Done sorry about that
