### ISSUE TITLE
[Feature] Send Telegram notifications

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/Ombi#261]
Send Telegram notifications to a Telegram chat (look at PLexPy project for examples). Useful for:
- Send message when a request is approved
- Send message when a request is available
- Send message when an issue is reported for a request
  etc.

**Comment by whitecollar17** [comment]
+1

**Comment by SuperPotatoMen** [comment]
See https://github.com/lokenx/plexrequests-meteor/issues/412 for help?

**Comment by tidusjar** [comment]
It shouldn't be too difficult, it's just another notification provider

**Comment by SuperPotatoMen** [comment]
Yeah, it was just for you. maybe its helping

**Comment by GeezusTx** [comment]
Is there any traction on adding this to v2?

**Comment by tidusjar** [comment]
Hey! So I'm not planning to add any more features to the next release, currently tidying up and bug fixing. 

But it will be coming soon!

**Comment by GeezusTx** [comment]
cool

**Comment by EYEVO** [comment]
+1   would be really nice to have !

**Comment by Ugarz** [comment]
Can't wait ! 👍

**Comment by aaomidi** [comment]
+1

**Comment by wjbeckett** [comment]
+1

**Comment by didyouexpectthat** [comment]
Is this closed as in no longer adding to ombi or closed for reopening later to implement?

**Comment by PotatoQuality** [comment]
https://github.com/tidusjar/Ombi/issues/1455

**Comment by tidusjar** [comment]
#1459
