### ISSUE TITLE
Newsletter IMDB - To many requests 

### ISSUE THREAD

**Issue by RCFilm** [tidusjar/Ombi#2611]
Having trouble with movies populating inside newsletter. This is the error code I get my log. This is weird because the web interface is able to populate new movies and I assume this is from the same database.

Is there a way to fix this

____
Hello, welcome to Ombi

Valid options are:

Ombi 3.0.3930-develop

_____
fail: Ombi.Api.Api[1000]

      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/463272?api_key=b8eabaf5608b88d0298aa189dd90bf00

fail: Ombi.Api.Api[1000]

      Retrying RequestUri: http://api.themoviedb.org/3/movie/463272?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests

info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]

      Plex Movies to send: 0

info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]

      Emby Movies to send: 0

info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]

      Albums to send: 0

info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]

      Plex Episodes to send: 39

info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]

      Emby Episodes to send: 0

#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Looks like TheMovieDb is rate limiting you. Doesn't look related to the newsletter though since you have no movies to send ?

**Comment by RCFilm** [comment]
:) seems I had 2 many movies actually 3200+. After about a 48 hour period it run successfully. I was then able to send the newsletter. I also changed to the Dev build
