### ISSUE TITLE
Provide a Setting to Disable the Loading Bar

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#2617]
#### Ombi build Version:
V 3.0.3919

#### Update Branch:
Open Beta

#### Media Sever:
Unneeded

#### Media Server Version:
Unneeded

#### Operating System:
Unneeded

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
Unneeded

#### Problem Description:
The current loading bar isn't very plex-like and looks incredibly awkward within OrganizrV2's iframe. Having a toggle option under Settings > Configuration > Customization to disable it would be greatly appreciated.

#### Reproduction Steps:
Unneeded

**Comment by Archmonger** [comment]
Toggle could simply apply the following CSS 
```.pace {
    display: none !important;
}```

**Comment by tidusjar** [comment]
This was one of the main driving forces for the custom CSS option in ombi. So people can turn or change things visually if they do not want them. 

Please feel free to raise this on feathub but I have no immediate plans to do this.
