### ISSUE TITLE
Update is disabled when new update is found

### ISSUE THREAD

**Issue by rutskiuk** [tidusjar/Ombi#2620]
Ombi build Version:

V 3.0.3594

Update Branch:

master

Operating System:
Windows 10 64bit build 1803
Problem Description:

Update option (Settings > System > Update > Check For Update > Update) is disabled. When hovering over the Update button it turns into a no entry sign

Reproduction Steps:

Go to System/Update. Click "Check for Update" and then "Update" when a new update is available.

I can see similar issues have been raised previously

**Comment by tidusjar** [comment]
You are on a very old version. I suggest you update manually and then continue from there
