### ISSUE TITLE
[ Feature Request ] Anime Search

### ISSUE THREAD

**Issue by bott0r** [tidusjar/Ombi#2625]
Well, Personally, i separate Tv Shows and Animes so i have two sonarrs runnings one for Tv and one for Anime, however an appropriate search option is missing with in Ombi. Ombi includes already all of the necessary features to accomplish this.

I propose Include Search for Anime, where one can select a second sonarr instance or so. Cheers

**Comment by tidusjar** [comment]
Please check feathub. If it's not on there then feel to raise it.
