### ISSUE TITLE
[Sonarr] Episode request result in whole season request and does not trigger search

### ISSUE THREAD

**Issue by rubenverhoef** [tidusjar/Ombi#2629]
#### Ombi build Version:

V 3.0.3945
--

#### Media Sever:

Plex

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
How can i get the logs from admin page??
```

#### Problem Description:

When requesting a single episode (or multiple but not the whole season) it will result in requesting the whole season to Sonarr. It also does not triggering a search command to Sonarr. Possible related issue: #2563 

#### Reproduction Steps:
Have Sonarr configured and just request a episode of a serie. This will result in sonarr to monitor the whole season and not search for it directly.

**Comment by goldenpipes** [comment]
are the episodes themselves monitored or just the season?

example:
![image](https://user-images.githubusercontent.com/6140137/48033059-6afcfa80-e11f-11e8-8306-756a12593586.png)

**Comment by rubenverhoef** [comment]
requesting one episode:
![request-1](https://user-images.githubusercontent.com/9071284/48053743-b9f07180-e1ab-11e8-841e-613f25c9e82c.PNG)
will result in:
![request result](https://user-images.githubusercontent.com/9071284/48053755-bfe65280-e1ab-11e8-9ba0-c32c07a8b316.PNG)
But without the spinning animation that it is searching for release, i have to do it myself but it is also requesting the whole season in stead of one episode.

**Comment by tidusjar** [comment]
Is this a request that currently does not exist on Sonarr, or a series that already exists on Sonarr?

**Comment by rubenverhoef** [comment]
This is a request that currently does not exist on sonarr.

**Comment by rubenverhoef** [comment]
If you guys need more specific information, Logs or things i have to try out. Let me know

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by chocolatethunder** [comment]
Can this fix be pushed to the master? I have Ombi installed via swizzin and it only syncs to the master branch. Thanks.
