### ISSUE TITLE
Emails not sending

### ISSUE THREAD

**Issue by damusmf** [tidusjar/Ombi#2636]
#### Ombi build Version:

V 3.0.3966

#### Update Branch:

Develop

#### Media Sever:

Plex

#### Media Server Version:

Version 1.13.5.5291 

#### Operating System:

Ubuntu 16.04 - ombi
Server 2012r2 - plex media server

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

```

#### Problem Description:

Email notifications are no longer working.  Noticed when the newsletter stopped sending and no test notifications from email config page are sent.  i don't see anything in the logs relate to it.  Cleared todays log file and restarted ombi and hit the test button on email and nothing populated.  Not sure what else to look for as other services that use my relay are still sending just fine

#### Reproduction Steps:

Attempt to send any sort of email from ombi.  Test or otherwise.

**Comment by tidusjar** [comment]
Logs?

**Comment by damusmf** [comment]
Nothing in the logs. As in to narrow down what was going on I cleared the initial log file. Restarted ombi and tried it again. The test email button doesn't write anything to the log.

**Comment by tidusjar** [comment]
Please check the stdout

**Comment by damusmf** [comment]
There is nothing.  It is like pressing the button doesn't actually do anything except say successful.  If i use the gmail smtp relay i can get it to display info, when i use my internal relay that relays through my domain i get nothing at all in logs or stdout

**Comment by damusmf** [comment]
More notes here. I have my internal smtp relay set to route mail through gsuite. As it sits this works for everything else except ombi. It used to work for ombi as well. 

Now what I'm noticing is that emails from ombi are not being sent through to other Google accounts. So any Gmail address or my gsuite address dont receive email from ombi. If I send an email from ombi to a non Google address it sends just fine. 

Again other services I have (tautulli, unifi controller) can send email using the same relay to Google email addresses just fine.

**Comment by tidusjar** [comment]
Nothing has changed in regards to the email in quite some time.

I'm using Gmail to send and receive and it's working perfectly fine....

**Comment by asc6** [comment]
Not sure how much this helps, but I have the same issue where I send my emails via GSuite and all of the sudden they are getting marked as spam by Google.  It’s been about the last month for me as well.  Same exact setup as damusmf.  Obviously if it’s a google thing, not much you can do tidusjar, but figured I’d provide more information as if there’s two of us having the exact same issue there’s bound to be more.

**Comment by Codehhh** [comment]
I just switched to GSuite and now my Ombi emails are being marked as spam. I can still receive emails from my other services just fine though.

**Comment by tidusjar** [comment]
Not sure if there is anything I can do with this, the way we send and the templates themselves have not changed in a very long time

**Comment by gdob** [comment]
I don’t know much about this and I’m using Mailgun, but the headers contain `<BG2SZ08UR6U4.GMNJKRNR2JBI2@localhost.localdomain>` so that’s probably why mails from SendGrid or Mailgun go straight to Gmail’s Spam folder. When I send email notifications from Tautulli or SSMTP it uses my hostname and I have no problems with delivery.

For instance SSMTP emails have something like this for Message ID: `<BG2SZ08UR6U4.GMNJKRNR2JBI2@example.com>`.

Maybe the email delivery system needs some tweaking on Ombi.

**Comment by tidusjar** [comment]
@gdob Good find,

I've pushed an update to develop branch, if you have the `ApplicationUrl` set in the `CustomziationSettings` then we will use that for the domain.

**Comment by gdob** [comment]
My application URL is set to `https://example.com/ombi`, so I’m guessing it will use `example.com` only, right?

**Comment by tidusjar** [comment]
Correct

**Comment by gdob** [comment]
Weird, after upgrading to v3.0.4248 the message ID header still contains localhost.localdomain.
`<MMZNV0UES6U4.3LQVJCZCGL4I@localhost.localdomain>` Maybe I have something configured incorrectly? My `ApplicationUrl` is set to ombi.example.com.

**Comment by tidusjar** [comment]
Strange. I'll reopen

**Comment by jamiew0w** [comment]
On `3.0.4256` can confirm this is still happening

```
Subject: [blah]!
Message-Id: <44MCPXW5V6U4.FMLEXO4W24O32@localhost.localdomain>
```

That's with the application path set also, is there a hotfix we can apply in the meantime?

**Comment by gdob** [comment]
I replaced the Ombi logo hosted on
Imgur and moved it on my server. It seems to have helped with inbox delivery. I’m not sure if it’s because of that or because a bunch of my friends marked the messages as not spam.

Even on Outlook the messages go to inbox.

**Comment by gdob** [comment]
I’ll just update this issue with a quote from [Mailgun’s documentation](https://documentation.mailgun.com/en/latest/faqs.html#does-the-content-of-my-email-matter-for-deliverability):

> Gmail pays particularly close attention to Message ID and Received headers. Message IDs that are formed incorrectly (without brackets <> and with wrong domain after @) can make Gmail think you are a spammer. The simplest way to create the right Message ID is to not set Message ID at all. Then Mailgun will create a perfect Message ID for you. Also, if you use the HTTP API, Mailgun will deal with all of this for you.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by starwarskidfan** [comment]
I am having the same issue with the spam, but my email is not being sent under the same domain the Ombi is on. So I can't change the ApplicationUrl.
