### ISSUE TITLE
Password Reset Link

### ISSUE THREAD

**Issue by polybius01** [tidusjar/Ombi#2638]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

Master

#### Media Sever:

Plex

#### Problem Description:

The link in the password reset email doesn't seem to take into account the url base.

mysite.com/ombi

Password link: mysite.com/token.......

Obviously it should be mysite.com/ombi/token..... (this works when manually changing the link)

**Comment by tidusjar** [comment]
What's your application URL set to?

**Comment by polybius01** [comment]
https://mysite.com...
I see why it wasn't working. It's set to **https://mysite.com/ombi** now and it works properly. Thanks!

**Comment by Bigdesertdon** [comment]
I'm having a similar issue that I can't resolve...    I have one admin account.  Of which I changed the email address.   Now I can't login with the old credentials or the new email address with the old password (I didn't change the password when I change dthe email address).    When I do a password reset, it takes me to plex to change the password there...  but my plex password is just fine... verified and logged into...  but it's out of sync ombi.
