### ISSUE TITLE
Nothing gets added in Sonarr or Radarr

### ISSUE THREAD

**Issue by zucram** [tidusjar/Ombi#2640]
#### Ombi build Version:
3.0.3966
#### Update Branch:
dev
#### Media Sever:
Plex
#### Media Server Version:
Version 1.13.9.5456
#### Operating System:
Ombi is running through docker (linux containers) on a windows machine. Sonarr and Radarr are running locally. 
#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0],
      Starting to cache the content on server "servername",
      Starting Plex Content Cacher

#### Problem Description:

Hi!
I've installed ombi and setup the connections to the plex server and both sonarr and radarr and the webgui is telling me that everything seems to work. However nothing gets added to sonarr or radarr. Ombi has been running multiple days. I've tried on both the master branch and the dev branch and no difference. Can't see anything in the logs that seem to indicate that ombi is sending info to radarr/sonarr. Just a bunch of 
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server "servername"
lines. 
Please help!
#### Reproduction Steps:
no idea

**Comment by zucram** [comment]
Hi!
Seems to be resolved now. 
Removed and readded the shows/movies and it sent them to sonarr and radarr. A question though, when adding movies that havn't been released yet are they not being added to radarr before they are actually available. Because i can't seem to find it in radarr.
Also, once the shows/movie has been downloaded they stay in the "requested" ui - can i get them to be removed automatically?

**Comment by tidusjar** [comment]
No, they will not be removed automatically
