### ISSUE TITLE
Refresh Issues

### ISSUE THREAD

**Issue by xunil75** [tidusjar/Ombi#2641]
#### Ombi build Version:

3.0.3930

#### Update Branch:

DEV

#### Media Sever:

Plex

#### Media Server Version:

1.14.0.5465

#### Operating System:

Ubuntu 16.04

#### Problem Description:

Hi guys, I have a small problem with Ombi and I don't know if it's a known issue. I was updating my Plex collection by replacing some 720p with 1080p Movies. I deleted the old 720p files from my NAS and refreshed the Plex library. I've downloaded the movies in 1080p to my second Plex Server (Ombi manages both servers) and updated the library as well. I've manually runned  a full sync on both servers via Ombi but if I search for the movies on Ombi, I still get the old results with 720p.

![ombi](https://user-images.githubusercontent.com/32961904/48407835-0ef62f80-e738-11e8-9461-f7ef64352af3.JPG)

![plex](https://user-images.githubusercontent.com/32961904/48407843-13bae380-e738-11e8-84da-14399741b8db.JPG)

clicking on "View on Plex" points me to the Plex Dashboard and not to the movie because it really doesn't exist.

**Comment by xunil75** [comment]
Meanwhile i've updated to the lastest release PR 3.0.3969 and manually runned a full sync...but nothing, still the same result.

**Comment by xunil75** [comment]
I've deleted the entry in the Database and after a new scan the movies are showing the proper resolution again.

**Comment by tidusjar** [comment]
That is the current fix/workaround until I implemented this.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by tidusjar** [comment]
Guys!?!? It's just me 🤣😂

Glad it works.
