### ISSUE TITLE
[Request] Issue resolved notificiation only for specific group

### ISSUE THREAD

**Issue by prinzpi** [tidusjar/Ombi#2649]
Hi,

would it be possible to add the feature, that the issue resolved notification only will be triggered for specific categories?

For example:
I have a category which is called "not in good quality" for tracking when the release will be.
By default also the notification will be sent if the request is available and therefore there will be sent two notification with basically the same information. (that the request is available &  the issue has been resolved).

But on the other side I would like to have the issue resolved notification for the other categories which I'm using for tracking issues.

Thanks and keep up the nice project. 👍

**Comment by tidusjar** [comment]
Hey thanks for the request, currently all feature requests are handed here: https://feathub.com/tidusjar/Ombi
