### ISSUE TITLE
Make Approval optional throughout the whole system

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/Ombi#265]
#### Plex Requests.Net Version:

1.7.4
#### Operating System:

Windows 10
#### Mono Version:

?
#### Applicable Logs (from `/logs/` directory or the Admin page):

N/A
#### Reproduction Steps:

**Page: /requests**
- When the Admin > Plex Request > "Require approval of Movie requests", "Require approval of TV show requests" and "Require approval of Music requests" checkbox is unchecked,
  the page /requests still shows the button "+Approve Movies". So even when the approval functionality is not enabled.

**Comment by Drewster727** [comment]
This is because we need to handle the cases where the approval was required and then it for turned off. There may still be pending movies/shows to approve. That make sense?

**Comment by tidusjar** [comment]
That's a good point @Drewster727

**Comment by Ruvetuve** [comment]
in that case it should be visable yes, else it doesn't right? Less clutter.
