### ISSUE TITLE
Redirect request to sickgear or sonarr depending of the user who make the request.

### ISSUE THREAD

**Issue by max01986** [tidusjar/Ombi#2652]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Synology (Linux Server)

#### Problem Description:

I have users that request tv show in english and other users who request french tv show. I enabled Sonarr for english and SickGear for french, but i can't use both. Is there something I do wrong or it's just not possible?

Configure Sonarr and enable it then configure SickGear and enable it. 
Any request will go to SickGear. (Selecting sonarr profile and root path in each users profile will not change where the request is sent.)

**Comment by tidusjar** [comment]
Please raise on feathub
