### ISSUE TITLE
Add option to change log level

### ISSUE THREAD

**Issue by rochdev** [tidusjar/Ombi#2653]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

master

#### Operating System:

macOS 10.14.1

#### Problem Description:

I am trying to lower the log level. In just a few days, I have hundreds of thousands of log entries, most of which is irrelevant information.

#### Reproduction Steps:

Use Ombi

**Comment by rochdev** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1596303/48928882-640d1080-eeb1-11e8-84d4-60bc37469b8a.png">
As you can see, "most of which" is actually an understatement

**Comment by rochdev** [comment]
Most of them are `We already have show <show name> checking for new seasons` messages. Not sure if that's normal as I was able to find a few issues related to these messages. It's possible they are not categorized properly in my log shipper.

**Comment by tidusjar** [comment]
You can currently customize the logging by editing the appsettings.json file.

**Comment by rochdev** [comment]
Totally missed that. This file doesn't seem to exist on my installation. Should I just create it? Can I include only a subset of https://github.com/tidusjar/Ombi/blob/master/src/Ombi/appsettings.json?

**Comment by tidusjar** [comment]
That file must exist or Ombi wouldn't start!

**Comment by rochdev** [comment]
Ah yes just found it but it's not in `/config`. I'm using Docker and it's the only folder mounted currently. I'll copy the file to the host and mount it as well, but I wonder if an override should be available in `/config`?

**Comment by tidusjar** [comment]
Yes maybe, but the issue would arise when I need to make changes to the file e.g. Add new sections in.

**Comment by rochdev** [comment]
Related: https://github.com/linuxserver/docker-ombi/issues/29

**Comment by rochdev** [comment]
According to 
https://github.com/linuxserver/docker-ombi/issues/29#issuecomment-392377861, it seems the code will attempt to load an additional file called `appsettings.<env>.json`.

@tidusjar Is it safe to mount a JSON file with that name with only the log level in it at that location and change the environment name accordingly?

**Comment by rochdev** [comment]
Using the aforementioned environment variables seems to work. Please feel free to close this issue if this is considered a valid way to set the log level. (although it should probably be documented somewhere)
