### ISSUE TITLE
Submenus do not get pushed down in landscape - iPad Safari

### ISSUE THREAD

**Issue by diedrichg** [tidusjar/Ombi#2656]
#### Ombi build Version:

V 3.0.3981

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Operating System:

Windows 10 x64

#### Problem Description:

iPad Air 2 Safari: submenus do not get moved down in landscape mode

**Comment by goldenpipes** [comment]
Can you test chrome on the same device please?

**Comment by goldenpipes** [comment]
Okay so this is happening on devices with a resolution width of 1024. The top NAV is doubling in size compared to if the width is a larger resolution.

@tidusjar any ideas?

**Comment by tidusjar** [comment]
No idea without looking at the CSS. Can't remember how that bit is done.

**Comment by goldenpipes** [comment]
yeah im looking at it now.

**Comment by goldenpipes** [comment]
i think this will fix it:  

`@media (min-width: 979px)
<style>…</style>
.top-spacing[_ngcontent-c0] {
    padding-top: 10%;```

**Comment by tidusjar** [comment]
Submit a PR!

**Comment by goldenpipes** [comment]
:)
