### ISSUE TITLE
Update is disabled when new update is found

### ISSUE THREAD

**Issue by rutskiuk** [tidusjar/Ombi#2657]
Ombi build Version: 3.0.3587
Update Branch: master
Operating System: Windows 10 64bit build 1803
Problem Description:

Update option (Settings > System > Update > Check For Update > Update) is disabled. When hovering over the Update button it turns into a no entry sign

Reproduction Steps:

Go to System/Update. Click "Check for Update" and then "Update" when a new update is available.

I can see similar issues have been raised previously, I myself raised this issue previously ref #2620 but that was closed being told to update manually to fix the problem, I have and it didn't.

**Comment by goldenpipes** [comment]
is the "Enable Automatic Update" check box checked?

**Comment by rutskiuk** [comment]
Good point, it was, I have unticked it, rebooted and tried again but exact same problem

**Comment by tidusjar** [comment]
Currently disabled on purpose due to the updater not working
