### ISSUE TITLE
Processing request

### ISSUE THREAD

**Issue by screwfaze** [tidusjar/Ombi#2661]
#### Ombi build Version:

V 3.0.XX

3.0.3993
--

#### Update Branch:

Dev

#### Media Sever:

Emby

#### Operating System:

(Windows 10 10.0.17134)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Music requests to Lidarr stuck in processing request even after waiting several hours. I was on Master and changed to Dev but still the same)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Is Lidarr enabled? 

Is it showing as available in Lidarr?

Any logs?

**Comment by screwfaze** [comment]
Yes Lidarr enabled and test was successful and yes I added the artist to Lidarr and son is available. I will send you the logs shortly.

Thanks

**Comment by screwfaze** [comment]
Actually I cant find the log folder can you tell me where it is in Windows? Its not in the Programdata folder where Ombi is.

**Comment by screwfaze** [comment]
@tidusjar I have just sent you my logs please have a look and tell me where I am going wrong.

Thanks

**Comment by tidusjar** [comment]
Looks like the API key is incorrect. Try re-generating an API key in Lidarr and then put the new on into Ombi.

**Comment by screwfaze** [comment]
Ok changed it will report back after some time, if the artist does not exist in Lidarr will Ombi add them and then do the search or do I have to add them manually?

**Comment by tidusjar** [comment]
For new requests yes. For existing requests no

**Comment by screwfaze** [comment]
I can confirm this is working. Thanks very much mate this is awesome keep up the good work!
