### ISSUE TITLE
Initial setup on pre-existing DB

### ISSUE THREAD

**Issue by Rsslone** [tidusjar/Ombi#2662]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Open Beta

#### Operating System:

Windows 8.1

#### Problem Description:

Ombi after upgrade and logout, now asking for initial setup but when trying to get past admin creation, it says already exists. I've tried creating a different username but same thing.

Is there any way to manually mark in the db that initial setup was completed? I already have an account

**Comment by tidusjar** [comment]
Wait, so what's happened? When you upgraded the Ombi.db would have got split out into 3 other databases, the one containing your settings is now the Settings.db

**Comment by Rsslone** [comment]
I'll redo the upgrade, I may have messed something up so let me check that now. I guess since I did not read that I needed to do a clean install this time around that it messed something up.

**Comment by Rsslone** [comment]
I redid the upgrade and its still saying "Looks like there is an existing user!"

**Comment by Rsslone** [comment]
Idk what happened, but I am just going to start from scratch.

**Comment by johnwilliams713** [comment]
I'm getting this issue as well.

**Comment by daymanbpi** [comment]
was a solution ever figured out for this issue?

**Comment by enz1ey** [comment]
I hate people who leave these threads dead without letting the entire world know the solution. Thanks, Rsslone.

**Comment by Rsslone** [comment]
I hate people who don't read the tread, @enz1ey . I clearly stated that I was starting from scratch, so no solution was searched for besides manual database repair, if you need a solution to this, make a new thread.

**Comment by SgtBatten** [comment]
I am moving to a new computer and am getting this error trying to start ombi with my old db.

**Comment by InaudibleDirge** [comment]
in case anyone is still wondering how to fix this:

- ensure you have backups of your original Ombi.db, OmbiSettings.db, and OmbiExternal.db files
- start a fresh install of Ombi and go through the whole wizard / set-up process
- once you're in the Ombi UI, open Task Manager and force quit ombi.exe
- copy your original files mentioned above to your Ombi install folder
- start it up again and you should have escaped the initial set-up / existing user loop
