### ISSUE TITLE
Ombi Sonarr settings are pulling wrong Default Root Folders

### ISSUE THREAD

**Issue by eirek1234** [tidusjar/Ombi#2664]
#### Ombi build Version:

3.0.3988
--

#### Me/Embydia Sever:

Plex

#### Media Son:

1.14.0.5470

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Under my Sonarr settings, the Default Root Folders always show the ones I use for Radarr. I have 4 Folders for Radarr and 2 for Sonarr but it shows the 4 for Radarr. I've checked my settings on Sonarr and I only have the 2 folders, and I checked my port settings and all that and they are set correctly.  I've also restarted Sonarr, Ombi and my whole server(they all run on the same server)

Radarr works perfectly but Sonarr won't receive any data presumably because of the wrong root folder settings?

#### Reproduction Steps:

Enable Sonarr, pull default root folders and they show the wrong ones.

**Comment by tidusjar** [comment]
are you sure they are looking at the correct instances? It's impossible for Radarr to know about Sonarr's root folders. So all i can suggest is to make sure they are setup correctly in ombi

**Comment by eirek1234** [comment]
Yes, I verified what folders were visible in radarr and which were
available in sonarr and no matter what I do, only the radar ones show up in
sonnar. I'll submit some screenshots

**Comment by goldenpipes** [comment]
this sounds like a browser cache thing. i get wierd stuff like this from time to time with radarr settings populating in sonarr as well. stupid autofill junk. try in a incognito browser to see if this happens.

**Comment by eirek1234** [comment]
I finally figured it out. I had to run Sonarr once as an administrator before it would show the right settings for some reason.
