### ISSUE TITLE
Feat req: change search to be agnostic, one search for both TV and movies

### ISSUE THREAD

**Issue by robertbaker** [tidusjar/Ombi#2665]
#### Ombi build Version:

V 3.0.XX - latest

#### Update Branch:

Open Beta

#### Problem Description:

When searching, you need to change tabs between tv and movies when you are searching for a title. Sometimes I forget and I start typing only to switch tabs and retype.

It would be a big usability improvement if search would be "global", as be in it would search both TV and movies and provide you grouped results. So then there's no need to change tabs between searches.

#### Reproduction Steps:

Use ombi to add about a 100 various things at a time and you encounter some UX shortcomings.

I love Ombi and I use it a lot but at the same time I feel there are valid UX improvements that can be done to make it even better!

**Comment by tidusjar** [comment]
This would be a good idea but it would slow down the searching a lot since we would need to query the movie dB and tvdbd for a single query so this is not something I'm willing to do currently. Please feel free to raise it on feathub though
