### ISSUE TITLE
[Optimization] Reduce API Calls with more client caching

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#2666]
#### Ombi build Version:

V 3.0.3993
--

#### Update Branch:

develop

#### Problem Description:

1. /api/v1/Images/tv/ calls do not really change and should be set to cache via the browser cache control header. There are also a fairly large number of these calls on both the search and requests pages. The actual images that the calls refer to, do get cached, but the calls happen regardless.

2. /api/v1/search/ , /api/v1/Request/ , /api/v1/Issues etc could likely benefit from etags . These results largely stay the same until something the user sees has been updated, added or removed. Currently there is no client side caching on these and every element gets called every time the user switches from search to request etc. It would probably have to be implemented at a user level and updated at any change. It might be worth while given the API nature of the the current design where every element seems to come back as an individual API request.

#### Reproduction Steps:

Using Chrome under the ... menu more tools --> Developer Tools. Go to Network and All. Now flip between search and requests.. You will see the client makes many of these calls over an over, however the content isn't going to change until a user adds more requests or the request is fulfilled on the server.

It wastes both the servers resources and makes the client less responsive. If a user is using a Raspberry Pi, low end NAS or a cheap tier VPS fewer calls could speed things up substantially.

**Comment by tidusjar** [comment]
Ok,

So most of this is cached on the server. So the client still does call the API, but the API code just will read it from the cache.

I don't think there is any work to do here.

**Comment by bagobones** [comment]
> So most of this is cached on the server. So the client still does call the API, but the API code just will read it from the cache.

I am referring to client side caching, IE telling the browser what it doesn't need to request again.

Client side caching is even more efficient than server side caching.. Doing both where appropriate is ideal.

Server side caching will NOT improve the experience of devices on slow mobile / wireless connections and will reduce database load but still requires the server to fulfill requests.

**Comment by tidusjar** [comment]
I get what your saying, but it's not as simple as that. The whole UI is stateless as far as the content goes, so I would need a way to manage the state of the requests in the UI, I'd need some way of telling the UI that the current state has been invalidated e.g. Request has been made available so then it can invalidate the cache.
