### ISSUE TITLE
"View on Plex" button and "Report Issue" button" missing translation

### ISSUE THREAD

**Issue by ezek1el** [tidusjar/Ombi#2669]
#### Ombi build Version:

V 3.0.3988 

#### Update Branch:

Master

#### Media Sever:

Plex

#### Problem Description:

"View on Plex" button and "Report Issue" button" are not translating properly into any language.

#### Reproduction Steps:

Switch languages while searching for Movies

![](https://cdn.discordapp.com/attachments/385544118719217674/519227010158034948/1.jpg)

![](https://cdn.discordapp.com/attachments/385544118719217674/519227027262537760/2.jpg)

**Comment by tidusjar** [comment]
Fixed in develop
