### ISSUE TITLE
Loading Ombi into an Joomla iframe wrapper

### ISSUE THREAD

**Issue by sumproguy99** [tidusjar/Ombi#2670]
Hello, 
I am hoping someone has some wisdom on this.  I am not very good at programming or webdesign.
I am using Joomla as a frontend to my website.  I am trying to pass Ombi inside joomla using an iframe wrapper.  Any help would be greatly appreciated!!! :-)

#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What errors are you getting

**Comment by goldenpipes** [comment]
never used joomla before. are you able to do this:
https://www.youtube.com/watch?v=FK26oTy6LUQ
