### ISSUE TITLE
Problem with issue tracker

### ISSUE THREAD

**Issue by masterzxz** [tidusjar/Ombi#2671]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.14.0.5470

#### Operating System:

Windows Server 2016 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Issues page stays black (except from heading which says "Issues"). Content has been cached.
Categories have been added.

#### Reproduction Steps:

Manually run full sync and recently added sync
Add categories
Enable issues
Try to load issues page

**Comment by tidusjar** [comment]
Because no one has raised an issue. 

Currently you raise issues via the search. 

I will be adding the option to raise an issue via the issues page in the future
