### ISSUE TITLE
[Enhancement] Already released can't be found denial email.

### ISSUE THREAD

**Issue by chrischm** [tidusjar/Ombi#2675]
Hello,

Thanks again for taking the time to read all these, including the dedication to correcting and developing this application further.  I have an enhancement I think would really help with communication between a lot of users. 

Idea: we should have under the request page for admin/mod only to have the ability for already approved items to be denied but when this happens it sends them a denial with maybe a reason code drop down with customization email that can be sent to the user.  '

**What I'd really like:** You could take this a step further and have an option in the settings somewhere to set a limit in days or hours using like crons or something - where if the item is not found and starting to be downloaded then an automatic email will be sent to the customer explaining item could not be found. Then this item can be deleted out of the request page to be re-requested. However this would have to be based of release date. If the content is not released yet, this would need to be excluded from this as there is more of a specific reason why a movie that is not released until 2020 would not be found vs 1995 film. Make sense? 

Thanks again 

Chris.

#### Ombi build Version:
V 3.0.4007
#### Update Branch:
Open Beta
#### Media Sever:
Plex
#### Operating System:
Windows 10

**Comment by tidusjar** [comment]
Hi regardinf the first, 

So i Invision it being similar to the issues, so you can customize the drop-down and provide an option with optional text. Good idea. 

The second part, why would it be deleted and rerequested?

**Comment by tidusjar** [comment]
I think it's a good idea, but the issue I see is that a lot of users will end up being spammed with notification and will start ignoring the notification.

The user should be expecting a Availability notification to know when it is ready to watch

**Comment by tidusjar** [comment]
There is a Deny with a reason available in Ombi now.
