### ISSUE TITLE
--baseurl is ignored for the first images

### ISSUE THREAD

**Issue by cfsmp3** [tidusjar/Ombi#2678]
#### Ombi build Version:

Ombi 3.0.3988-master

#### Update Branch:

Open Beta

#### Media Sever:

N/A

#### Media Server Version:

N/A

#### Operating System:

Ubuntu (Docker)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Empty (they don't show requests)
```

#### Problem Description:

I'm loading ombi like this:

/opt/ombi/Ombi --storage /config --host http://*:7879 --baseurl /ombi

There's a reverse proxy

However, they first images (the ombi logo in the first screen and then the plex and embi logos) don't take baseurl into account at all so they don't load.

#### Reproduction Steps:

Just start ombi without any configuration so it starts with those pages and you'll see.

**Comment by cfsmp3** [comment]
Looked a bit into this, seems like an easy fix:

<img class="landing-header" src="/images/logo.png" width="300" />

should probably be

<img class="landing-header" src="{{baseUrl}}/images/logo.png" width="300" />

Same thing in a few other places I've seen. Apologies for not sending my own pull request. I no one does it I'll give it a go even though my test environment right now is not ideal (I'm just using that Docker image from linuxserver/ombi and inspecting the source code on github)

**Comment by tidusjar** [comment]
Fixed in develop
