### ISSUE TITLE
Newsletter ignoring CRON Schedule

### ISSUE THREAD

**Issue by thekingswolf** [tidusjar/Ombi#2682]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Master

#### Media Sever:

Emby

#### Media Server Version:

3.5.3.0

#### Operating System:

Win10 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

Newsletter triggers randomly now.  I've gotten three in the past few hours, all showing newly added content since the last.  CRON schedule is still set to every Friday just like it's always been.

#### Reproduction Steps:

It's not something i'm doing, so i can't reproduce it.  It doesn't appear to be happening on any kind of schedule, just whenever something new is added.

**Comment by d1slact0r** [comment]
I have a special expression and I do not have this issue.
