### ISSUE TITLE
TV shows notifications

### ISSUE THREAD

**Issue by markpeo** [tidusjar/Ombi#2684]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Master

#### Media Sever:

Plex/Emby

#### Operating System:

unRaid Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

The value for the telegram notification preference does not get passed through to the telegram notification when sending notifications associated with TV shows. Works fine for notifications associated with Movies. Have tried with different users, same results. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
what is the template of your notification?

**Comment by markpeo** [comment]
For request approved, available & declined the template is as follows;

```
Hello {UserName},
Your request for {Title} is now available!
{UserPreference}
```

**Comment by tidusjar** [comment]
Are the TV requests fully being fulfilled? Not just 1 episode, but the whole request?

**Comment by markpeo** [comment]
Yes, the whole request is filled.
I get the notifictaion, its just that it doesnt have the {UserPreference} value at the end, but for Movies it does.

**Comment by tidusjar** [comment]
Fixed in develop
