### ISSUE TITLE
More of a simple request

### ISSUE THREAD

**Issue by nakedgoat** [tidusjar/Ombi#2687]
Custom indexer options for each section, "custom" or whatever allowing the admin to enter indexer URL and API etc. so one is not forced to use sonarr, radarr, and dog..

I would donate for sure, but really cannot use it now, as i am not paying for dog and hate the RR's :)

**Comment by tidusjar** [comment]
The reason why dognzb is there is because they provide an API to add stuff to the watchlist and that manages the downloads etc. All ombi does is add to the watchlist like ombi adds to radarr lists. 

So it actually does nothing with any Usenet providers.
