### ISSUE TITLE
[Question] Per user notification settings

### ISSUE THREAD

**Issue by BaneOfSerenity** [tidusjar/Ombi#2690]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Master

#### Media Sever:

Plex

#### Problem Description:

Under User Management when you edit a user there is a `Notification Preferences` under the `User Settings` column. I cannot seem to find any documentation for these. Specifically i would like to have pushover send receive notifications for that user when their issues/requests are completed. Do these do that? And if they do what values are supposed to go in here?

![image](https://user-images.githubusercontent.com/2280933/50047363-7843c800-0081-11e9-8ae5-ef918e2798a3.png)

**Comment by tidusjar** [comment]
Hi, apologies about the lack of documentation!

They are used as part of the notifications, for example you could put their Discord ID in and then in the template it can mention them.

You can find it here: https://github.com/tidusjar/Ombi/wiki/Notification-Template-Variables
It's the `{UserPreference}` variable
