### ISSUE TITLE
Add support for JOIN notifications

### ISSUE THREAD

**Issue by Cerothen** [tidusjar/Ombi#2693]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

Open Beta

#### Media Sever:

Emby

#### Operating System:

Debian 9

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Problem Description:

Add support for JOIN notifications, relevant code example from Sonarr is avail here:
https://github.com/Sonarr/Sonarr/tree/develop/src/NzbDrone.Core/Notifications/Join
JOIN site: https://joaoapps.com/join/

It basically replaces everything that pushbullet does in a more cost friendly (not $40/yr) package.

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
