### ISSUE TITLE
bootstrap - 3.4.0

### ISSUE THREAD

**Issue by thezoggy** [tidusjar/Ombi#2694]
I see you are using bootstrap 3.3.7 from Jul 25, 2016
There is a much newer 3.x version you can use that may solve some of the css issues i'm seeing in ombi.

https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/
- https://github.com/twbs/bootstrap/releases/tag/v3.4.0

**Comment by tidusjar** [comment]
Thanks. The problem is the CSS in ombi is terrible. 

I'd like to just start again with the UI but I'm too afraid on how much work that would be lol. 

I'll see if I can easily update
