### ISSUE TITLE
Docker Plex Ombi media library not being indexed. Test connections work but logs and ombi interface show it does not

### ISSUE THREAD

**Issue by vulcanjedi** [tidusjar/Ombi#2695]
#### Ombi build Version:

3.0.4036

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

Version 1.14.1.5488

#### Operating System:

Host Ubuntu 16.04.5 LTS
linuxserver docker container for both Plex / Ombi

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Not getting media library inventory. Some show up others (most don't)
Have tried to disable Secure Connections to Preferred instead of Required.
Test connections to the PMS are successful and SOME stuff shows up.

> 
> fail: Ombi.Api.Api[1000]
>       StatusCode: NotFound, Reason: Not Found, RequestUri: http://###-###-#-###.asdfasfasfasdfasdfasdfas.plex.direct:32400/library/metadata/365831
> warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
>       Exception thrown when attempting to cache the Plex Content in server thePlexServer
> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
>    at Newtonsoft.Json.JsonTextReader.ParseValue()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
>    at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
>    at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 390
>    at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 218
>    at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 136
> 

> fail: Ombi.ErrorHandlingMiddleware[0]
>       Something bad happened, ErrorMiddleware caught this
> System.Exception: Invalid URI: The hostname could not be parsed. ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
>    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>    at System.Uri..ctor(String uriString)
>    at System.UriBuilder.get_Uri()
>    at Ombi.Helpers.UriHelper.ReturnUri(String val, Int32 port, Boolean ssl) in C:\projects\requestplex\src\Ombi.Helpers\UriHelper.cs:line 89
>    --- End of inner exception stack trace ---
>    at Ombi.Helpers.UriHelper.ReturnUri(String val, Int32 port, Boolean ssl) in C:\projects\requestplex\src\Ombi.Helpers\UriHelper.cs:line 96
>    at Ombi.Settings.Settings.Models.External.ExternalSettings.get_FullUri() in C:\projects\requestplex\src\Ombi.Settings\Settings\Models\External\ExternalSettings.cs:line 18
>    at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
>    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
>    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
> 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Looks like it's not connected to Plex correctly, please double check your hostname, port and token

**Comment by vulcanjedi** [comment]
Thanks @tidusjar  I tried to use no SSL, switch PMS to preferred. I grabbed all the tokens and url from Tautillli instance which seems fine. I also tried the hostname/IP w/ the Docker GW address of 172.17.0.1 which also Successfully Test connects from the Ombi Admin Console. Whats odd is a handful of series and films sort of show up and I dont know why they work and the rest dont. Should be more an all/nothing thing. When I try to put the ###-###-#-###.asdfasfasfasdfasdfasdfas.plex.direct:32400/library/metadata/365831(directly) from the logs in my browser i get 401 unauthorized 'errors' but im sure I need to pass auth token in somehow. 
Pinging the ###-###-#-###.asdfasfasfasdfasdfasdfas.plex.direct does resolve the correct local IP of my host server.
From the FAQ [https://plex.tv/users/cpms ](url) does not work anymore apparently and not sure applicable as this is a self hosted PMS instance.  The only other place to get the hostname / token / machine identifier I saw was in my seemingly working Tautulli instance. (also a linuxserver docker image)

If you have any insights how to validate the hostname/port/token further Im more than willing to try. My friends Ombi instance w/ Emby seems awesome.

**Comment by tidusjar** [comment]
`Invalid URI: The hostname could not be parsed. ---> System.UriFormatException: `

What's the format of your hostname?

**Comment by vulcanjedi** [comment]
I also just reentered my creds in the Plex config page on Ombi and selected the server there.
It prepopulated with the IP of the docker host and differnent IP I put 32400 and turned off SSL and it passed test connection but the logs say this:

> fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
fail: Ombi.Api.Api[1000]
      StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/servers.xml
fail: Ombi.Controllers.External.TesterController[1000]
      Could not test Plex
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 246
fail: Ombi.Controllers.External.TesterController[1000]
      Could not test Plex
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
   at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 246
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]

**Comment by tidusjar** [comment]
Ok, so those settings seem good so far, but the fact that we are getting a 401 back from Plex means that your Auth Token is not valid.

**Comment by beyondunreal79** [comment]
I have all my plex info in ombi, it tests successfully, shows my servers and librarys. When I hit manually run full sync, the pop says triggered the plex full sync, but it never show library. Any ideas?

**Comment by tidusjar** [comment]
Need log files

**Comment by beyondunreal79** [comment]
[log-20181225.txt](https://github.com/tidusjar/Ombi/files/2708733/log-20181225.txt)

**Comment by tidusjar** [comment]
It's stating the connection was refused. So ombi cannot talk to Plex. Make sure it has access, check the hostname/ip, firewall etc

**Comment by beyondunreal79** [comment]
is there something within plex that has to be enabled? because as a test I installed ombi on my personal plex server at home and I get the same result. No firewall, on the same local network
Thanks

**Comment by vulcanjedi** [comment]
Not sure this is related or not... but before I save my PMS config I'll put user/pass, I can select server list, and libaries and test connection.
However after that, if I hit Load Servers button again i get:

> Error When Requesting Plex Servers
> Please make sure your username and password are correct

Is this expected behavior? That I'd  have to reenter user/pass again? Is this possibly related to issue why library indexing isnt working quite right in my ombi?

**Comment by beyondunreal79** [comment]
same thing for me vulcanjedi, user and pass doesn't save

**Comment by beyondunreal79** [comment]
same thing for me vulcanjedi, user and pass doesn't save

**Comment by tidusjar** [comment]
So the load servers is talking to Plex.tv when you enter in the username and password (We authenticate with Plex.Tv to load the servers).

Once you choose a server it will populate the left hand side of the screen with the media server information, this is what Ombi uses to connect to plex. Ombi does not store the username and password for your plex account at all. So the load servers functionality is more of a "helper" to fill in the plex server information for you.

**Comment by beyondunreal79** [comment]
yes, my user and pass are accepted, it shows me server list, I choose my server, ensure the ip and port are correct, click load librarys, click full sync. the pop up in the upper right says triggered full snyc, but that's as far as it goes. even when ombi is on the same lan as plex server

**Comment by tidusjar** [comment]
Then I am not sure, It seems that the Plex server is refusing the connection according to your logs. Did you double check to make sure the Auth Token is correct?

**Comment by beyondunreal79** [comment]
the machine id and auth token are populated automatically

**Comment by tidusjar** [comment]
Yes I understand that, but can you double check to make sure your auth token is correct, That token is used to authenticate the communication between ombi and plex. You can check your auth token by following this: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by beyondunreal79** [comment]
You were right, the token was wrong, what about machine id, is that the mac address of the network adapter?

**Comment by beyondunreal79** [comment]
if the info is correct, should it show me my library loading, or some kind of indication?
I still haven't gotten anywhere

**Comment by vulcanjedi** [comment]
> You were right, the token was wrong, what about machine id, is that the mac address of the network adapter?

My token was different too. My Machine ID is correct but using this method of viewing the XML my auth token isnt the same as the one the Ombi gui pulls back.
[https://support.plex.tv/articles/201638786-plex-media-server-url-commands/](url)
all that said; still dont think mine is working.

**Comment by tidusjar** [comment]
So you've updated your token and saved it. 

Why don't you think it's working? 

Open up the ombiexternal.db with SQLite and query the PlexContent table. If there are rows returned then ombi is correctly syncing with Plex.

**Comment by vulcanjedi** [comment]
I have barely any TV stuff show up on obmi but the db has a bunch of stuff for TV.
Some of the movies I've been checking show up in the db but they dont seem to have an IMDB or moviedb  ID

**Comment by beyondunreal79** [comment]
so if someone requests a movie that's in my library, does ombi show that it already exists? or show my library?

**Comment by vulcanjedi** [comment]
> so if someone requests a movie that's in my library, does ombi show that it already exists? or show my library?

It should tell you.  but yes my problem is my sonarr/radar don't have my storage linked so i dont want people pulling dupes.

**Comment by vulcanjedi** [comment]
I use application MediaCompanion to prepopulate NFOs. The NFOs have moviedb / tvdb / imdb IDs so not sure why not pulling in here.

**Comment by beyondunreal79** [comment]
Ok, finally got it working, I thought the it would say the sync was complete or something like that. Now when I search for a movie using ombi that I have, it says available

**Comment by vulcanjedi** [comment]
> Ok, finally got it working, I thought the it would say the sync was complete or something like that. Now when I search for a movie using ombi that I have, it says available
> Does it periodically update my librarys or do I have to do it manually?

Howd you get working? just updated your token?

**Comment by beyondunreal79** [comment]
Actually when I put my plex user name and pass it, it show me my servers, I choose one and it automatically populates the machine id and token, - I used those and did a manual sync and waited. After a few minutes I went to ombi search and started searching for movies I had and they showed up as available, at least most of them, some still said they weren't available. Maybe it takes time?

**Comment by tidusjar** [comment]
Yes it syncs on a schedule, you can see and edit these schedules in Settings > Jobs

**Comment by beyondunreal79** [comment]
I noticed if im logged into via web browser new added movies show right away, but not on the mobile app. Does the app take a while to sync?

**Comment by tidusjar** [comment]
They should appear the same as the web version

**Comment by beyondunreal79** [comment]
that's strange, new movies are only showing on web interface, even tried logging out of app then back in

**Comment by vulcanjedi** [comment]
I've removed my ombi mount and image and redployed the container several times. Still cant figure this out why a handful of stuff shows up but laregely most dont.  This seems amazing just wish I could iron out whats going on.

**Comment by vulcanjedi** [comment]
Would you like me to use your email in your profile or some other means?

**Comment by tidusjar** [comment]
Please email it to tidusjar@gmail.com

**Comment by vulcanjedi** [comment]
I think I may have figured it out. I have been examining the XML from the Get Info on Plex.  (Im still a loyal XBMC/KODI user and have Plex on the side....I use this old legacy plugin for NFO importing in Plex. via [GitHub - gboudreau/XBMCnfoMoviesImporter.bundle
https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle](url)
The ones that show up in Ombi were somehow scanned w/ the default Plex Agents and the ones that dont show up seem to have been scanned with the other agents
guid="com.plexapp.agents.thetvdb://####/1/1?lang=en"
guid="com.plexapp.agents.xbmcnfotv://#####/1/1?lang=xn"
guid="com.plexapp.agents.imdb://tt#####?lang=en"
guid="com.plexapp.agents.xbmcnfo://tt#####?lang=xn"
I tried to manually change one and see if it reconciles in Ombi but hasn't yet. Also not sure how to mass change / update the Plex scan w/o removing the entire library and rescanning which could take quite a while.

**Comment by vulcanjedi** [comment]
Cheers and Happy New Year Jamie. Yes it’s typically thetvdb ID however I think seldomly it may be the IMDb is for shows too.


________________________________

**Comment by tidusjar** [comment]
Ok the fix I have committed to the develop branch should fix this for you then!

Happy new year! 🎉🎊

I am going to close this issue to prevent further confusion. 

If anyone else has an issue please try develop and if that does not work then please raise an issue.
