### ISSUE TITLE
Wizard issue popping up between develop versions 4060 and 4068

### ISSUE THREAD

**Issue by aptalca** [tidusjar/Ombi#2697]
#### Ombi build Version:

V 3.0.4068

#### Update Branch:

Develop

#### Media Sever:

Plex/Emby

#### Media Server Version:

N/A

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

With version 4060, one can skip media server setup during initial wizard, but with version 4068, skip button doesn't seem to do anything.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
