### ISSUE TITLE
Show the TV show as available when we have all the episodes but future episodes have not aired (not completely fixed)

### ISSUE THREAD

**Issue by TheRealStarboy** [tidusjar/Ombi#2698]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

1.14.1.5488

#### Operating System:

Windows Server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

It looks like this issue is not completely fixed. If the next future episode is listed as next year it doesn't show as available. If the next future episode is in the current year and there are future episodes listed after that in the next year it seems to be fine.

Ok maybe that's not correct I will give an example of what I am seeing.

I have all episodes except future episodes of the following series
Arrow
The Big Bang Theory

Arrow does not show as Available
The Big Bang Theory does

The only difference I can see between them is the dates of the episodes listed to air next
Arrow is 01/21/2019
The Big Bang Theory is 01/03/2019

Ok don't know where the future episode info is coming from but I think I see what is causing the issue with Arrow.
There are 2 future episodes listed with a date of 01/01/0001.

Can someone tell me where these 2 episodes are coming from because they are not listed on the TVDB?
S07E11 	Past Sins  01/01/0001
S07E12 	Emerald Archer  01/01/0001

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
The data is coming from TV Maze, 

I'm pretty sure I have fixed this in develop.

**Comment by TheRealStarboy** [comment]
Great if it's already fixed in a future version.
I have checked many of my other series and the only series I see having this issue are ones with future episodes with the date of 01/01/0001
