### ISSUE TITLE
Seeing errors in console log - warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]       Exception thrown when attempting to cache the Plex Content in server Server 1

### ISSUE THREAD

**Issue by andyd0** [tidusjar/Ombi#2699]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

Automatic update disabled / fresh install

#### Media Sever:

Plex

#### Media Server Version:

1.14.1.5488

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server Server 1
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

#### Problem Description:

I'm seeing the above error immediately after Ombi is started

1. Plex token added
2. Plex access confirmed via Authorized Devices

#### Reproduction Steps:

I just installed the app and signed in

**Comment by tidusjar** [comment]
That means that Ombi cannot access Plex, the connection was refused. 

Double check your settings

**Comment by andyd0** [comment]
Yeah i had to change the ip to localhost. Thank you
