### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by barbidule** [tidusjar/Ombi#2701]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Master
#### Media Sever:

Plex

#### Operating System:

Windows 2016 server

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Next to the 3.0.3988 version, I see an indication that an update is available.
If I click on it, server restarts, but stays on 3.0.3988.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
There is an open issue regarding the updater.
