### ISSUE TITLE
[Enhancement] "View on Emby" button addition

### ISSUE THREAD

**Issue by Dubwize** [tidusjar/Ombi#2711]
Ombi: v3.0.4036
Branch: Master
Emby: v3.5.3.0
OS: Linux / Docker

I am looking for a small addition to the "View on Emby" feature. Is it possible to add a switch in the configs that allows for a custom IP, or FQDN to be used in place of the default ie: http://app.emby.media
?

Thanks

**Comment by tidusjar** [comment]
This is not currently possible, please raise this on Feathub
