### ISSUE TITLE
Removing request jumps back to first page

### ISSUE THREAD

**Issue by palanjam** [tidusjar/Ombi#2714]
#### Ombi build Version:

V 3.0.4007

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

CentOS (linux.tar.gz release)

#### Problem Description:

This has always been an issue with any version I've used. I will usually go through my requests page and remove requests that are now available. Whenever I'm removing a request on anything other than page 1, it will remove the request but then jump back to page 1 even though the page index at the bottom still says it's on the page I was on. It's very inconvenient to clear things on another page because I have to keep jumping back to where I was. 

#### Reproduction Steps:

Remove any request on a page other than page 1.

**Comment by tidusjar** [comment]
I am not going to fix this as it will be replaced with V4
