### ISSUE TITLE
[Enhancement] Give admins the ability to add a page for FAQ's and additional information

### ISSUE THREAD

**Issue by Oz0n3** [tidusjar/Ombi#2715]
#### Ombi build Version:

V3.0.4036

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Docker image 

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Per our discussion in Discord, This is an enhancement request to give admins the ability to add a page for FAQ's and additional information.  I would like to setup a page , in HTML or Markdown, so I can supply my users with some additional information.  For example, I would like to add a FAQ section to help users not file false issues.  I would also use this page to help the user give me all the information I need correct an issue.

Thanks for considering this request.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Note to self,

A page to Allow the user to enter whatever html they wanted. 

Enable it in the settings and an edit button on the page that brings up some sort of WYSIWYG editor.

**Comment by tidusjar** [comment]
Done
