### ISSUE TITLE
Unable to import users from plex

### ISSUE THREAD

**Issue by dbooty99** [tidusjar/Ombi#2719]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Could not create Plex user since the have no username, PlexUserId:********

```

#### Problem Description:

Can't import plex users

#### Reproduction Steps:

I hit run importer and nothing happends.

**Comment by tidusjar** [comment]
Are these home users?

**Comment by dbooty99** [comment]
Yes

**Comment by tidusjar** [comment]
Plex home users are not supported since there is no way to authenticate them with the Plex Api

**Comment by dbooty99** [comment]
Thank you for the reply.
