### ISSUE TITLE
Mentions in discord not parsing properly.

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2721]
#### Ombi build Version:

V 3.0.4105

#### Update Branch:

develop

#### Media Sever:

Plex/Emby

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

What we talked about earlier on discord.

Something is fishy 🐟 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

try to send a notification to discord with the <@{UserPreference}> and it doesnt work as expected.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
