### ISSUE TITLE
{UserPreference} variable empty for most notifications on discord

### ISSUE THREAD

**Issue by GlobalRisk** [tidusjar/Ombi#2725]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Microsoft Windows 10.0.17134 x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

no output from logs

#### Problem Description:

I'm using a discord webhook for my notifications and have set the discod ID under the notification preferences. The problem is that the {UserPreference} variable is empty when used in the notifications of issues (new issue, comment, resolved). I know it works because I use the exact same message for the available requests and there it works.

EDIT: It seems to be empty aswell when marking a tv show as available. So far I have only gotten it to work when a movie is marked available.

#### Reproduction Steps:

Send a notification about an issue to discord and use the UserPrefence variable.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by GlobalRisk** [comment]
That's great new 😄. Is there a way to switch update branches to develop and let Ombi handle it?

**Comment by tidusjar** [comment]
Just download the deveop build from appveyor and replace all the files.

This is the build: https://ci.appveyor.com/project/tidusjar/requestplex/builds/21462114

You will have to wait until it's finished
