### ISSUE TITLE
Request: Make requests from Kodi

### ISSUE THREAD

**Issue by Chris230291** [tidusjar/Ombi#2727]
Hi. I searched but I couldnt find anything on this.

I thought it would be nice if you could make requests from the Kodi EPG in a similar way to how you can record. Highlight a show/movie, bring up the contextual menu, then have a request option.

Thanks,
Chris

**Comment by tidusjar** [comment]
Hey. This is not something I want to do at the moment. Please feel free to raise it on feathub for more poeple to vote on it.

**Comment by Chris230291** [comment]
OK thanks I added it to feathub
