### ISSUE TITLE
Add support for Jellyfin

### ISSUE THREAD

**Issue by smidley** [tidusjar/Ombi#2730]
Please add support for Jellyfin servers.

https://github.com/jellyfin

**Comment by tidusjar** [comment]
Does this not work with the Emby option in Ombi?

**Comment by smidley** [comment]
It probably does, but there should be a new option for Jellyfin.

**Comment by goldenpipes** [comment]
is jellyfin a fully open source fork of emby?

**Comment by smidley** [comment]
Yes that’s correct.

**Comment by goldenpipes** [comment]
id be inteterested to see if it works just using the emby config.

**Comment by goldenpipes** [comment]
did a quick test and Ombi _does_ work with jellyfin.  You can configure the media server portion and scan the library seemingly fine. but when you try to click a "View on Emby" link from ombi it pulls up the `app.emby.media/#1/itemdetails.html?id=` which doesn't exist for jellyfin at this location.  So something will need to be added to make these links resolve to something else. 

IE: `localhost:8096/web/index.html#!/itemdetails.html?id=`

**Comment by jeffkeller87** [comment]
The ability to customize the URL has been a [feature request](https://feathub.com/tidusjar/Ombi/+292) for a while now. I would love to see Jellyfin support generally, as well.

**Comment by tidusjar** [comment]
Completed that feature request in develop.

For now I don't think we need a difference between Jellyfin vs Emby. But if any of the interfaces change then we will need to.

**Comment by jeffkeller87** [comment]
Just tried this out but couldn't get it to work... seems like there is a potential discrepancy regarding a trailing slash in the domain string [here](https://github.com/tidusjar/Ombi/commit/1f59693c7e04277dc738c1836f4ba5a67659e2ae#diff-aac0cc5cd8c90bfe7b65a8d012c9a164R74) and [here](https://github.com/tidusjar/Ombi/commit/1f59693c7e04277dc738c1836f4ba5a67659e2ae#diff-5f8d6e47bee297c198ab2fe4e9f21a1aR14)?

I tried entering my domain both ways (i.e. `https://emby.example.com` and `https://emby.example.com/`) but the "View on Emby" buttons in Ombi and the newsletter thumbnails still link to app.emby.media.

**Comment by tidusjar** [comment]
What errors are you seeing

**Comment by jeffkeller87** [comment]
Boy, this one took me a while to figure out:

No errors, but the Externally Facing Hostname value is only being applied to new content. Content that became available before I set my domain name still has the View on Emby buttons and newsletter thumbnails linking to app.emby.media, while content that became available after I set my domain name has the correct link (e.g., `https://emby.example.com/#!/itemdetails.html?id=160640`)

**Comment by joshuaboniface** [comment]
Just an FYI from the Jellyfin side.

i can definitely confirm Ombi works fine with Jellyfin when configured as Emby. It's my primary interface and so far it's worked wonderfully.

That said, this may change in the future as we do have plans to rewrite the API. I'll be sure to report on the status and perhaps try to send some resources your way when we do, just to make sure we can retain compatibility.

P.S. I love Ombi, keep up the awesome work!

**Comment by ngnglro** [comment]
doesnt work for me.
Ombi adds `/#!/itemdetails.html?id=xxxx` to the base url, but should add `#!/details?id=xxxx` instead
