### ISSUE TITLE
Custom page doesn't respect some formatting options

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2731]
#### Ombi build Version:

V 3.0.4019

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

w10x64

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Custom page doesn't respect some formatting options

#### Reproduction Steps:

Try to create a custom page with the WSYIWIG editor and center some text.  in the editor it centers like it should but when you save it there is no centered text.

**Comment by tidusjar** [comment]
I am not going to fix this as it will be replaced with V4
