### ISSUE TITLE
Better classes for TV/Movie/Music posters

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#2732]
#### Ombi build Version:

V 3.0.XX

#### Update Branch:

Open Beta

#### Media Sever:

Plex/Emby

#### Media Server Version:

ALL

#### Operating System:

ALL

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

It is currently difficult create selectors for differentiating between movie/TV/music posters.  A solution would be appending another class ID on the posters depending on what they are: `.poster-tv`, `.poster-movie`, `.album-cover`, and `.artist-cover` respectively.

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by goldenpipes** [comment]
🙌
