### ISSUE TITLE
Labels in radarr/sonarr

### ISSUE THREAD

**Issue by phildrage** [tidusjar/Ombi#2735]
#### Ombi build Version:

V 3.0.4119

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Win10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Requests are added successfully to sonarr/radarr, but the appropriate labels are not attached. This means that that the file management is not handled, and subsequently plex never sees the file. This could be an issue with the radarr/sonarr API not handling labels, or Ombi not attaching them can you advise?

Awesome software apart from that though! keep up the good work!

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Explain what you mean labels?

**Comment by phildrage** [comment]
it may be an issue with radarr and sonarr not adding the category labels, i'll ask the question. I wasn't sure if ombi needed to add the category at the point where it is pushed

**Comment by tidusjar** [comment]
I've never needed to do this before and I use these categories and seems to be working fine.

**Comment by phildrage** [comment]
how strange, I'll double check all my settings, thanks for the quick response!

**Comment by phildrage** [comment]
The problem was I was using 'LabelsPlus' in deluge instead of the default labels addon. Works perfectly, thanks for your quick response, good work! This is no longer an issue
