### ISSUE TITLE
requests tab has a client-browser javascript error: TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by saveyour** [tidusjar/Ombi#2737]
> i'm reopening this because i thought it was cloudflare related and clearing my cache fixed it temporarily but it seems the problem has kept happening. thanks!

server is running *ubuntu 16.04& (fully updated), uname -a returns: &Linux plex 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux& with plex media server (latest). as far as my ombi server, i am running:

```
 ./Ombi --version
Ombi 3.0.4036-master
```

for browsing the requests i am using google chrome on windows 10 (latest) with ublock origin disabled to help identify this error. to reproduce the error navigate to ombi home (/search) and then click on the requests tab (/requests) which manages the status of user submitted requests. it will show a blank screen. upon checking the console of chrome i found this error:

```
core.js:1624 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toUpperCase' of undefined
TypeError: Cannot read property 'toUpperCase' of undefined
    at auth.service.ts:62
    at Array.some (<anonymous>)
    at e.hasRole (auth.service.ts:62)
    at new l (tvrequests.component.ts:51)
    at Sa (core.js:9103)
    at Ea (core.js:8978)
    at os (core.js:10198)
    at fs (core.js:10514)
    at ds (core.js:10433)
    at os (core.js:10226)
    at auth.service.ts:62
    at Array.some (<anonymous>)
    at e.hasRole (auth.service.ts:62)
    at new l (tvrequests.component.ts:51)
    at Sa (core.js:9103)
    at Ea (core.js:8978)
    at os (core.js:10198)
    at fs (core.js:10514)
    at ds (core.js:10433)
    at os (core.js:10226)
    at T (zone.js:814)
    at T (zone.js:771)
    at zone.js:873
    at t.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3748)
    at t.invokeTask (zone.js:420)
    at e.runTask (zone.js:188)
    at g (zone.js:595)
$t @ core.js:1624
t.handleError @ core.js:1670
next @ core.js:4252
e.object.i @ core.js:3488
e.__tryOrUnsub @ Subscriber.js:195
e.next @ Subscriber.js:133
e._next @ Subscriber.js:77
e.next @ Subscriber.js:54
e.next @ Subject.js:47
e.emit @ core.js:3480
(anonymous) @ core.js:3779
t.invoke @ zone.js:388
e.run @ zone.js:138
t.runOutsideAngular @ core.js:3716
onHandleError @ core.js:3779
t.handleError @ zone.js:392
e.runGuarded @ zone.js:154
t @ zone.js:677
n.microtaskDrainDone @ zone.js:686
g @ zone.js:602
Promise.then (async)
f @ zone.js:578
t.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
t.scheduleTask @ zone.js:401
e.scheduleTask @ zone.js:232
e.scheduleMicroTask @ zone.js:252
R @ zone.js:862
T @ zone.js:808
(anonymous) @ zone.js:724
e @ bootstrap:25
(anonymous) @ 0.69fabea05e61b89e96a9.chunk.js:1
auth.service.ts:62 Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of undefined
    at auth.service.ts:62
    at Array.some (<anonymous>)
    at e.hasRole (auth.service.ts:62)
    at new l (tvrequests.component.ts:51)
    at Sa (core.js:9103)
    at Ea (core.js:8978)
    at os (core.js:10198)
    at fs (core.js:10514)
    at ds (core.js:10433)
    at os (core.js:10226)
```

much love to the devs. huge fan of the project. i use it every day!

**Comment by tidusjar** [comment]
Have you tried doing a hard clear of your browser cache?

**Comment by saveyour** [comment]
yes i've cleared the browser cache by pressing f12, going to application and clearing all site data. i've also cleared it by using another browser and going incognito. in addition i've cleared the caching that cloudflare was doing and it sometimes works again.. other times it does not. 

today it seems to have gotten worse and it seems on every page i encounter the error and the settings tabs do not show up to be clicked on. 

do you think this is purely a caching problem or could there be something code wise going on ?

**Comment by tidusjar** [comment]
can you try logging out and then back in?

**Comment by saveyour** [comment]
> can you try logging out and then back in?

sure. i cleared all the site data and went ahead and checked disable cache while i was in the developer tools networking tabgain so it would log me as i can't see the menu where i could log out from currently. i then logged back in but i'm still getting the error

**Comment by saveyour** [comment]
on further inspection something else i noticed is when i try to run build.sh i get
```

Unhandled Exception:
System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Could not restore NuGet packages.

```

my system shows the following are installed:

```
# dpkg -l | grep -i corlib

ii  libmono-corlib2.0-cil                                       4.2.3.4-0xamarin2                          all          Mono core library (transitional package)
ii  libmono-corlib4.0-cil                                       4.2.3.4-0xamarin2                          all          Mono core library (transitional package)
ii  libmono-corlib4.5-cil                                       4.2.3.4-0xamarin2                          all          Mono core library (for CLI 4.5)
```

would this be related at all?

**Comment by saveyour** [comment]
i did an manual reinstall from a release version. seems to be working again.. not sure what the issue was with this.. seemed to occur after i did a git pull from the development branch. i'm gonna close this as perhaps a config error or something. thanks!

**Comment by mattiaskagstrom** [comment]
I get the same issue when using the linuxserver container.

https://hub.docker.com/r/linuxserver/ombi

Ombi 3.0.4119-master

`core.js:14597 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toUpperCase' of undefined
TypeError: Cannot read property 'toUpperCase' of undefined
    at auth.service.ts:62
    at Array.some (<anonymous>)
    at e.hasRole (auth.service.ts:62)
    at new l (tvrequests.component.ts:51)
    at Km (core.js:20726)
    at Gm (core.js:20595)
    at Sv (core.js:21821)
    at Nv (core.js:22137)
    at Mv (core.js:22056)
    at Sv (core.js:21849)
    at I (zone.js:814)
    at I (zone.js:771)
    at zone.js:873
    at t.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
    at t.invokeTask (zone.js:420)
    at e.runTask (zone.js:188)
    at g (zone.js:595)
Sd @ core.js:14597
t.handleError @ core.js:14645
next @ core.js:16628
e.object.i @ core.js:12609
e.__tryOrUnsub @ Subscriber.js:196
e.next @ Subscriber.js:134
e._next @ Subscriber.js:77
e.next @ Subscriber.js:54
e.next @ Subject.js:47
e.emit @ core.js:12593
(anonymous) @ core.js:16178
t.invoke @ zone.js:388
e.run @ zone.js:138
t.runOutsideAngular @ core.js:16115
onHandleError @ core.js:16178
t.handleError @ zone.js:392
e.runGuarded @ zone.js:154
t @ zone.js:677
n.microtaskDrainDone @ zone.js:686
g @ zone.js:602
Promise.then (async)
h @ zone.js:578
t.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
t.scheduleTask @ zone.js:401
e.scheduleTask @ zone.js:232
e.scheduleMicroTask @ zone.js:252
j @ zone.js:862
I @ zone.js:808
(anonymous) @ zone.js:724
e @ bootstrap:25
(anonymous) @ 11.e971602e39a61c1d6762.chunk.js:1
auth.service.ts:62 Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of undefined
    at auth.service.ts:62
    at Array.some (<anonymous>)
    at e.hasRole (auth.service.ts:62)
    at new l (tvrequests.component.ts:51)
    at Km (core.js:20726)
    at Gm (core.js:20595)
    at Sv (core.js:21821)
    at Nv (core.js:22137)
    at Mv (core.js:22056)
    at Sv (core.js:21849)`
