### ISSUE TITLE
cant update ombi

### ISSUE THREAD

**Issue by nmbrg** [tidusjar/Ombi#2738]
#### Ombi build Version:

V 3.0.4036

#### Update Branch:
master

#### Media Sever:

Plex

#### Operating System:

Windows Server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):
dont say anything in the logs related to updating. only TooManyRequests lines regarding themoviedb requests.

```

#### Problem Description:

Ombi isnt updating.
Checking the "automatic update" box (or not checking that box) and pressing "check for update" and then pressing "update" wont do nothing other than the notification saying "we triggered the update job". But checking in the about page it says an update is available.


#### Reproduction Steps:

as above.

**Comment by tidusjar** [comment]
There is already an issue open with the updater.

**Comment by nmbrg** [comment]
Could you please link to that issue? I cant seem to find it here.
