### ISSUE TITLE
Ombi Emailing Issue

### ISSUE THREAD

**Issue by 05thomasj** [tidusjar/Ombi#2740]
#### Ombi build Version:

V 3.0.XX

Version | 3.0.4119
-- | --

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Ubuntu

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(getting email issues have cpanel hosting from buyVM but cant email out from BUYVM but it works on my WHMCS Panel any ideas? 
https://cdn.discordapp.com/attachments/535543447977852929/535545146075381772/unknown.png
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What's in the logs when you try this?
