### ISSUE TITLE
Custom page accessible when not logged in

### ISSUE THREAD

**Issue by IxFail** [tidusjar/Ombi#2743]
#### Ombi build Version:

V 3.0.4144

#### Update Branch:

develop

#### Media Sever:

Plex

#### Operating System:

Linux 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 (Ubuntu 16.04)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When using the direct url of the custom page #2715 (www.website.com/Custom) everybody can access it without logging in if the custom page option is enabled.

Or is this on purpose?

I have landing page disabled.

Other direct URL's like vote, Search, request etc. prompts a login screen.

#### Reproduction Steps:

Without being logged in, use the direct URL to the custom page (www.website.com/Custom) when the custom page option is enabled

**Comment by goldenpipes** [comment]
can you confirm this happens in an incognito session?

**Comment by tidusjar** [comment]
Yes it would. I just need to add a setting to let the user choose if they want this page to be accessed without logging in or not

**Comment by IxFail** [comment]
@goldenpipes Yes also happens in incognito and other browsers.
@tidusjar Ah okay, clear to me.
