### ISSUE TITLE
Approved requests Add whole series monitored

### ISSUE THREAD

**Issue by chadgmcd** [tidusjar/Ombi#2745]
#### Ombi build Version:

V 3.0.4119

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Linux 4.18.20-unRAID

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

[log-20190118.txt](https://github.com/tidusjar/Ombi/files/2775057/log-20190118.txt)

#### Problem Description:

Requests  work fine if an admin requests them however if a regular user requests it is set to require approval.  Once the request is approved it adds it to the series and monitors all seasons and episodes not the individual episodes requested.

#### Reproduction Steps:

Create a user make a request and approve the request.  Happens consistently.

**Comment by tidusjar** [comment]
Is this for series that already exist in Sonarr or they do not yet exist?

**Comment by chadgmcd** [comment]
This is for series that do not exist yet.
