### ISSUE TITLE
administrative messages gets broadcasted

### ISSUE THREAD

**Issue by TheUltimateC0der** [tidusjar/Ombi#2747]
When a user requests new content, and either sonarr or radarr is not available, ombi sends out a new notification that the api of sonarr/radarr was not available, but the request will be retried.

https://github.com/tidusjar/Ombi/blob/0c36462652fce369984548f33d4a54731f44a3dc/src/Ombi.Notifications/Agents/TelegramNotification.cs#L120

I can not change this to only send this via mail or something else. I want to have the ability to change where these messages will be sent and where not.

For example:

Telegram -> For notifications when requested content is available
Email -> For this kind of "administrative" information

**Comment by tidusjar** [comment]
You have the ability to Enable certain events on each notification agent.

Looks like I didn't add this to those options.

**Comment by tidusjar** [comment]
Added in develop
