### ISSUE TITLE
Mobile Notifications Not Working

### ISSUE THREAD

**Issue by angrycuban13** [tidusjar/Ombi#2753]
**Describe the bug**
When a user requests a movie, I have it set so I get alerted on the mobile app. However, this is not what is happening.

When I try to test the notification this is the error that I get:

"There was an error when sending the Mobile message. Please check your settings"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Notifications'
3. Scroll down to 'Mobile'
4. Select user from list
5. Click on "Test"
6. See error

**Expected behavior**
I expect a test notification to appear on my phone

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/39564898/51509292-2ac42480-1dbe-11e9-9f84-6de3975f5a81.jpg)

**Logs (Logs directory where Ombi is located)**

https://pastebin.com/G51qzq5P

**Desktop (please complete the following information):**
 - OS: Windows Server 2016

**Ombi Version (please complete the following information):**
 - Version 3.0.4119 
 - Media Server Plex

**Comment by tidusjar** [comment]
Can you please try again?

**Comment by tidusjar** [comment]
This seems to be a DNS issue.

Can you try and ping `https://onesignal.com/` ?

**Comment by angrycuban13** [comment]
DNS issue indeed. Looks like that site was blocked by one of my Pi-Hole lists. Whitelisting fixed it right away.

**Comment by xuset** [comment]
Just commenting the logs here for posterity and searchability sake.


I had the same issue as @angrycuban13 with pi-hole blocking the `onesignal.com` domain name. But where @angrycuban13  got these logs:
```
[Error] Could not test Mobile Notifications
System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found --->
System.Net.Sockets.SocketException: The requested name is valid, but no data of the requested type was found
```

I got this instead, but was solved the same way by white listing `onesignal.com`:
```
Could not test Mobile Notifications
System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```
