### ISSUE TITLE
[Feature] New CanEditCustomPage role

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#2756]
Create a new role that allows users to edit the custom page

**Comment by Killianbe** [comment]
Page custom don't appear
I've check for use custom page 
Thx :) 
![image](https://user-images.githubusercontent.com/16178815/51638924-f7b99680-1f5f-11e9-8d4e-0f925df669c8.png)

**Comment by tidusjar** [comment]
Refresh the page

**Comment by Killianbe** [comment]
I've refresh and restart the service ombi :)

**Comment by tidusjar** [comment]
Ok sorted, wait until the next dev build! :)
