### ISSUE TITLE
SSL 'ignore any certifcate errors' not applied until *after* restart.

### ISSUE THREAD

**Issue by r-pufky** [tidusjar/Ombi#2762]
OMBI SSL 'ignore any certificate errors' are not applied until *after* restart. The GUI reflects that this option is on and effectively a GUI state is kept, however, SSL validation continues to be enforced until the container is restarted.

The container is linuxserver/ombi:latest; I am submitting the bug here first and will move it to linuxserver if it's determined to be a container issue.

**To Reproduce**
1. Go to Settings > OMBI
2. Check 'Ignore any certificate errors`
3. Click `Submit`
4. Go to Settings > Media Server > Plex
5. Enter in server information (server name, IP, port, Check: SSL, auth token)
6. Click 'Test connectivity'
===> Plex connection failure
7. Restart container. 'docker-compose stop ombi; docker-compose start ombi'
8. Go to Settings > Media Server > Plex
9. Enter in server information (server name, IP, port, Check: SSL, auth token)
10. Click 'Test connectivity'
===> Plex connection succeeds, repeatedly

**Expected behavior**
Toggling SSL validation in the UI (and having the checkbox stick) implies that it is currently being applied. This is misleading in terms of whether SSL validation is being enforced or not.

**Screenshots**
None needed. Let me know if you need some?

**Logs (Logs directory where Ombi is located)**
None.

**Desktop (please complete the following information):**
 - Windows 10/Chrome

**Ombi Version (please complete the following information):**
- Ombi 3.0.4119
- Plex 1.14.1.5488 

**Additional context**
I think this is leading to a bunch of the "I can't connect to Plex" messages with no clear explanation on how it was fixed.

**Comment by tidusjar** [comment]
That is expected. 

I shall update the UI to make this more clear.

**Comment by MorphyDK** [comment]
Still an issue .

Made a complete new install:


Version | 3.0.4892
-- | --
Branch | masterOS Architecture | X64
OS Description | Linux 4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
Process Architecture | X64

I have been trying this over and over, but this post fixed it :) , but its still not saying it.
