### ISSUE TITLE
Never set up email notifications, latest Docker image has nuked my admin login somehow.

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [tidusjar/Ombi#2763]
What is the proper way to recover the admin password, reset it, or create a new admin account?

There's no documentation.

Can I set the password hash in the database to a hash for a known password (and then change my password once logged in)?

**Comment by tidusjar** [comment]
You cannot create a admin account if you cannot log in as a admin. 

You could rename your ombi.db and OmbiSettings.db to something else, start up ombi,.go through the wizard and create a local user, you can then go into the Ombi Db, in the AspNetUser table replace the hash with the new on (with the user you just created). Then put the old DBs back.
