### ISSUE TITLE
Movie Search - 10 Result Limit?

### ISSUE THREAD

**Issue by yetdog** [tidusjar/Ombi#2764]
I am currently running the develop branch of 3.0.4093 and am hitting a limit when searching for movies. Only 10 movie results are returned with no "next" or "more results." I've searched and can't seem to find anywhere that this is specified in the config or if this has already been named an issue. Thanks.

**Comment by tidusjar** [comment]
This functionality is not there. If you update to the latest build there are more options to refine your search.

**Comment by matthewtroup1983** [comment]
Are there plans to add this? Refining your search still does not provide solid movie ideas when you are not able to come up with ideas. There should definitely be an option in settings to give a result limit 10,20, etc etc. Not sure how complicated that would be to implement...

**Comment by tidusjar** [comment]
It's not an issue in V4

**Comment by matthewtroup1983** [comment]
Cool, when is that due out?

**Comment by iqy90** [comment]
Yes! This features should be implemented. Search actor result, only showed 10 list, no next or more.

**Comment by tidusjar** [comment]
V4 is available to use right now as an alpha

**Comment by matthewtroup1983** [comment]
Do you have to follow the v4 build wiki to run it or can you just copy it over and run it as v3?

**Comment by tidusjar** [comment]
Depends on how you run it. If via docker then use the v4 tag. If manual then go to the Ombi.releases repository and download it from the release section on GitHub

**Comment by matthewtroup1983** [comment]
Gotcha I got it figured out. However having issues getting Emby hooked in with API

Sent from my iPhone

On Feb 10, 2020, at 1:49 PM, Jamie <notifications@github.com> wrote:

﻿

Depends on how you run it. If via docker then use the v4 tag. If manual then go to the Ombi.releases repository and download it from the release section on GitHub

**Comment by iqy90** [comment]
> Depends on how you run it. If via docker then use the v4 tag. If manual then go to the Ombi.releases repository and download it from the release section on GitHub

I'm using OMBI in seedboxes, still V3.0.4892.  How to get V4?
