### ISSUE TITLE
Changed base URL from "\" to "\ombi", all language tags are broken

### ISSUE THREAD

**Issue by cjattard** [tidusjar/Ombi#2765]
**Describe the bug**
After changing the base url the representation of languages is broken. The label tag is shown and the language is unable to be changed. This only exists via proxy. Accessing locally is fine. 

Guess - Perhaps the reference to sub folders isn’t updating in the settings file?

**To Reproduce**
changed base url from \ to \ombi (as I am now running within organizr V2) it appears this has broken links to the language files. most importantly all language tags are broken and also I can no longer change language.

**Expected behavior**
all languages still correctly loading after changing base url when viewed externally; fine via 127.0.0.1:500

**Screenshots**

<img width="1384" alt="screenshot 2019-01-25 at 18 31 37" src="https://user-images.githubusercontent.com/45669214/51765582-1048be80-20d0-11e9-8ef0-e381d20e155a.png">

screenshot attached; photo has Nginx reverse proxy on the left (broken) and local on the right (which still works)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - all

**Ombi Version (please complete the following information):**
 - not linked to media server but running on plex.

**Additional context**
perhaps a database entry is not correctly updated?

**Comment by tidusjar** [comment]
Clear cache, also please fill in the version.

**Comment by goldenpipes** [comment]
`\` ? should it not be `/`

**Comment by cjattard** [comment]
i tried clearing browser cache, also using a new device; same behaviour on desktop shown on and IOS and desktop devices.

Version is 3.0.4119

and finally updated my typo! \ = /

**Comment by goldenpipes** [comment]
So to be clear you changed your base url from blank to /ombi?

**Comment by cjattard** [comment]
Thats correct, from blank to /ombi. i tried a couple of things including spinning up a fresh Ombi v3 instance - same behaviour. so i can't rule out an issue on my side.

my server block looks like `  location /ombi/ {
    auth_request off;
    proxy_intercept_errors off;
    proxy_pass http://127.0.0.1:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  90;
    proxy_redirect http://127.0.0.1:5000 https://$host;
}`

and console output:
<img width="1270" alt="screenshot 2019-01-26 at 23 33 19" src="https://user-images.githubusercontent.com/45669214/51803512-d271a480-224d-11e9-94db-f6ab954afb82.png">

**Comment by cjattard** [comment]
a more useful console shot: <img width="1174" alt="screenshot 2019-01-28 at 17 32 53" src="https://user-images.githubusercontent.com/45669214/51854592-08348d00-2323-11e9-9344-ee9e86b2bb59.png">

**Comment by tidusjar** [comment]
It's saying that your browser is unauthorized to load JSON files.

**Comment by cjattard** [comment]
yep - my bad! I had a line of code to block unauthorised JSON in my nginx setup - it was fine when Ombi was / but triggered when changed to /ombi.

Error on setup no fault within Ombi. keep up the great work and thanks for the nudge in the right direction.
