### ISSUE TITLE
Is it possible to disable Ombi login and solely use Plex OAuth?

### ISSUE THREAD

**Issue by raman325** [tidusjar/Ombi#2766]
In my use case, only users with Plex accounts can login to my Ombi instance. Is it possible to force them to use Plex OAuth? I suppose I could randomize their Ombi passwords to make that path untenable, but the preferred solution would be to force them to use their Plex accounts to login.

Thanks for your help!

**Comment by tidusjar** [comment]
Use the custom CSS to hide the button

**Comment by DeathByDentures** [comment]
@raman325 Thank you! This worked fantastically for me!

**Comment by abpostelnicu** [comment]
> Use the custom CSS to hide the button

This is not by far a solution since the login mechanism still is present in the front end and also is accepted by the backend, so from a security stand-point this is useless.

**Comment by epheterson** [comment]
Thanks this worked great! To address @abpostelnicu 's concern, for me this isn't about security but instead guiding users down the right path.

**Comment by raman325** [comment]
It would still be better if this path was treated as a first class citizen from a security standpoint but as long as you use good passwords for admin accounts, the damage a hacker could inflict is relatively low

**Comment by ECKoBASE** [comment]
When will this feature spill into V4?

**Comment by tidusjar** [comment]
It's already in the latest version of V4.

Regarding the security comments, please can someone explain how having a local login is a security risk? I'll happily go into detail of what security measures are used and provide articles explaining the algorithms that are used (Microsoft Identity Server framework)

**Comment by abpostelnicu** [comment]
For example a weak password or something generic, I know this can be put on the user but having this disabled is something nice to have. As long as you have more entry points the number of potential breaches increases.

**Comment by ECKoBASE** [comment]
> It's already in the latest version of V4.
> 
> Regarding the security comments, please can someone explain how having a local login is a security risk? I'll happily go into detail of what security measures are used and provide articles explaining the algorithms that are used (Microsoft Identity framework)

Where do I disable local login and just have Plex Auth only on the login screen?

**Comment by abpostelnicu** [comment]
I think you can use a css for this.

**Comment by ECKoBASE** [comment]
> I think you can use a css for this.
> […](#)
> On 19 Aug 2020, at 12:52, ECKoBASE ***@***.***> wrote: ﻿ It's already in the latest version of V4. Regarding the security comments, please can someone explain how having a local login is a security risk? I'll happily go into detail of what security measures are used and provide articles explaining the algorithms that are used (Microsoft Identity framework) Where do I disable local login and just have Plex Auth only on the login screen? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I tired using the same custom CSS from V3 but it doesn't seem to work with V4 atm

**Comment by ECKoBASE** [comment]
> ```css
> .login-buttons button:first-of-type { display: none; }
> ```
> 
> Above works for me on v4

Yes this version of the code actually works on V4!
