### ISSUE TITLE
[FR] Delete issues

### ISSUE THREAD

**Issue by csy7550** [tidusjar/Ombi#2768]
Feature request:

Add option to delete issues regardless of state.

I've got like 30-40 unsolvable issues that I would like to delete without marking them as solved and enabling the "delete resolved issues" option as I'm pushing issue states to Telegram and don't want to cause any confusion for the users.

Regards,
Csy7550.

**Comment by goldenpipes** [comment]
+8999

**Comment by tidusjar** [comment]
Not stale
