### ISSUE TITLE
Unable to modify Users

### ISSUE THREAD

**Issue by Artiume** [tidusjar/Ombi#2769]
**Describe the bug**
I am able to update user alias's, however upon attempting to update user's username, it will acknowledge the change in the user's name (upon exiting from 

**To Reproduce**
1. Go to 'User Management'
2. Click on 'Details/Edit' of any user
3. Modify 'Username' from XXX to YYY
4. Click Update
5. The notification will appear saying The User YYY has been changed. However, if you go back into the User's settings, it will show XXX again.

**Expected behavior**
Username should be changed to YYY.

**Screenshots**
Not really necessary to describe the issue.

**Logs (Logs directory where Ombi is located)**
Could not find any relevant entries in the logs (however, I was using the docker log feed) 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, running in Docker 18.06.0-ce

**Ombi Version (please complete the following information):**
 - Version, 3.0.4119
- Media Server, Plex

**Additional context**
This came about as an attempt to remove potentially personal information (username and email matching exactly) so that people would not worry about PII concerns when performing movie requests (TV shows dont show the requester). 

Username is unable to be changed. However, Alias and Email Address can both be modified.

**Comment by tidusjar** [comment]
The alias is not the same as the username. 

The username cannot be changed.

**Comment by Artiume** [comment]
Can we make a change where alias overrides username for all users (not only Admin) or have the option of removing who request movies?
