### ISSUE TITLE
Why no bitcoin or crypto-currencies in donation?

### ISSUE THREAD

**Issue by Mercurial** [tidusjar/Ombi#2772]
Why don't you put bitcoin address or crypto-currency in your donation page?

**Comment by tidusjar** [comment]
Hello,

I don't have any crypto-currency accounts and no one has ever asked me about this!

**Comment by tidusjar** [comment]
If you want to donate via a crypto-currency contact me on discord or just email me tidusjar@gmail.com

Thanks!
