### ISSUE TITLE
can't login/access via NGINX

### ISSUE THREAD

**Issue by feerlessleadr** [tidusjar/Ombi#2773]
**Describe the bug**
I installed the stable version of Ombi on a Windows 10 Pro machine, and am able to access the web interface locally (http://192.168.1.16:5000), where I'm able to follow the setup wizard, add my services etc.). 

I am also able to add my Ombi install to my current NGINX conf (also running on the same Windows 10 box, which hosts my emby, sonarr, radarr, and many other services via my domain) and access the login screen successfully. However, after I input my username & password, and click to sign-in, nothing happens. The screen doesn't show that it is loading, or anything like that. I have the cmd window open, and nothing is reported in the window when I attempt to login. I know that the proxy is set up correctly, as I am able to access the login screen (and my other services work using the same settings), so I'm  not sure where I'm going wrong.

I have also tried installing the latest Dev branch (3.0.4182), which gives the same results. I have also tried setting up a 100% fresh install while connected through the proxy (not ideal, I know), and while in the wizard, I am able to get to the screen where I am asked to enter in my Emby connection details, however once I click on the button to add the emby server, nothing happens (same situation as when I tried to log into an already set up server). 

I have also tried this on multiple browsers on 2 Windows 10 machines (firefox, chrome, IE), as well as on firefox & chrome on my Note 8), both on the same network and on different networks.

**To Reproduce**
1. Set up Ombi locally w/ username password & confirm local access works as intended
2. Add Ombi install to my existing nginx conf
3. Navigate to sub.mydomain.com, and enter username/password (using
4. Click sign-in and nothing happens

**Expected behavior**
Click sign-in should take me to the Ombi home screen

**Screenshots**
N/A - no screenshot of logs

**Logs (Logs directory where Ombi is located)**
N/A -no logs are produced on the cmd window

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Ombi Version (please complete the following information):**
 - Version Ombi v3.0.4119
- Media Server [e.g. Plex] Emby 4.0.1

**Additional context**

EDIT:: I can't figure out how to format this to look pretty, but hopefully you get the idea.

Here is my Nginx Conf:

# user  nobody;
# multiple workers works !
worker_processes  2;

events {
    worker_connections  8192;
}

http {
    #include      /nginx/conf/naxsi_core.rules;
    include       mime.types;
    default_type  application/octet-stream;
	server_tokens off;

    sendfile        off;
	
	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	gzip_min_length 1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	gzip_types
	text/plain
	text/css
	text/js
	text/xml
	text/javascript
	application/javascript
	application/x-javascript
	application/json
	application/xml
	application/rss+xml
	image/svg+xml;

	tcp_nodelay on;
    
	server_names_hash_bucket_size 128;
    map_hash_bucket_size 64;

## Start: Timeouts ##
    client_body_timeout   10;
    client_header_timeout 10;
    keepalive_timeout     30;
    send_timeout          10;
    keepalive_requests    10;
## End: Timeouts ##

    #gzip  on;

	

##Ombi Server##
	
	server {
    listen [::]:80;
    listen 80;
    listen [::]:4433 ssl;
    listen 4433 ssl;
    server_name ombi.mydomain.com; 
	
        ssl_session_timeout 30m;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
		ssl_certificate      SSL/cert.pem;
		ssl_certificate_key  SSL/private.key;
        ssl_session_cache shared:SSL:10m;
		if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }

		add_header X-Xss-Protection "1; mode=block" always;
		add_header X-Content-Type-Options "nosniff" always;
		add_header Strict-Transport-Security "max-age=2592000; includeSubdomains" always;
		add_header X-Frame-Options "SAMEORIGIN" always;
		proxy_hide_header X-Powered-By;
		add_header 'Referrer-Policy' 'no-referrer';
		add_header Content-Security-Policy "frame-ancestors mydomain.com emby.mydomain.com;radarr.mydomain.com;sonarr.mydomain.com;get.mydomain.com;books.mydomain.com;hydra.mydomain.com;tiny.mydomain.com;vault.mydomain.com;ombi.mydomain.com;";

     location / {
        proxy_pass http://192.168.1.16:5000;  # Local emby ip and non SSL port

		proxy_hide_header X-Powered-By;
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #Next three lines allow websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
		location ^~ /.well-known/acme-challenge/ {
}

}
}

**Comment by tidusjar** [comment]
I'd recommend using the example config in the wiki. But my knowledge outside that is very limited in regards to nginx. So not sure what you want me to do with this?

**Comment by feerlessleadr** [comment]
Well I was hoping that this was something that someone might have seen before (although a search of the issues didn't turn up anything). 

It turns out that the following portion of my conf was causing the issue (although on idea how/why. Removing it solved the issue:

> #Next three lines allow websockets
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
