### ISSUE TITLE
Ombi doesn't show TV episode as available

### ISSUE THREAD

**Issue by pete-oconnell** [tidusjar/Ombi#2778]
I may be wrong in the understanding of this but I've got Sonarr and Radarr set up and they're happy processing the requests for downloads however once the download is complete Ombi is not showing it as available.

Should it show it as available or only once the tv ep/film is in the media server such as plex?

**Comment by tidusjar** [comment]
It only shows as available once it's in Plex. 

Please in future can you fill out the template.
