### ISSUE TITLE
How to remove registered mobile app/device

### ISSUE THREAD

**Issue by glassbase** [tidusjar/Ombi#2780]
**Describe the bug**
Reference [issue 64](https://github.com/tidusjar/OmbiApp/issues/64) from OmbiApp 

I show a registered mobile device under my username. Cannot remove in web interface and no longer have the phone (wouldn't power on and sent for warranty replacement).

**To Reproduce**
1. Register mobile device
2. Shows in Ombi as a registered device
3. Lose or smash phone to pieces
4. How do you remove the registered device?

**Expected behavior**
A way to remove the registered device in Ombi or in some config file.

**Desktop (please complete the following information):**
 - OS: iOS

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server = Plex

**Comment by tidusjar** [comment]
Not possible from the UI currently. 

You can remove it from the dB if you wish. It's the notification user id table.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
