### ISSUE TITLE
Unable to add movies to Radarr from Ombi

### ISSUE THREAD

**Issue by sean1604** [tidusjar/Ombi#2781]
**Describe the bug**
Unable to add movies to radarr

**To Reproduce**
adding a movie from ombi to hit radarr

**Expected behavior**
movie to be sent to radarr and then to qbit

**Screenshots**

**Logs (Logs directory where Ombi is located)**
selected parts of log;
https://pastebin.com/1yu5keUK

full log; 
https://drive.google.com/open?id=1LJ8ULLpap6-TVXGOtH4z38vqcvKPlBQs

**Desktop (please complete the following information):**
 - OS: Windows 7

**Ombi Version (please complete the following information):**
 - Version 3.0.4119 
- Media Server plex

**Additional context**
Ombi did initially work when I tested it with the admin account. However since then I set up a test user and now neither the admin or user works. When I add stuff with the user it goes in to failed request and when I add with the admin it doesn't go anywhere.

**Comment by tidusjar** [comment]
It seems that radarr is not setup correctly according to your log file. 

Can you please double check your radarr settings inside Plex

**Comment by tidusjar** [comment]
Have you filled in a radarr base URL if you have one? 

Are the quality profiles and paths correctly filled in?

**Comment by sean1604** [comment]
so i've not long set up reverse proxy although it was working at that time. I set up HTTPS last night though. 

I'm not sure what to put in these fields now;
Hostname or IP ; should this be my DDNS domain?
port; should this be null due to the reverse proxy?
ssl; ticked i assume
base url; I've changed it to /radarr which is what it is set as.

**Comment by sean1604** [comment]
adding the base URL (which I thought I had done) seems to have fixed the issues. thanks.
