### ISSUE TITLE
ApiAlias appears to be ignored

### ISSUE THREAD

**Issue by switchlove** [tidusjar/Ombi#2782]
At this time I am using the Request module for Node.JS to pass the post request to Ombi to add movies via the API. I have it set up authorizing with my API key and I am passing an ApiAlias header as well. I'm not sure if I'm just passing it wrong or if it is being ignored. However even with the ApiAlias set the Requested By: is showing as API still.

```javascript
var options = {
	method: 'post',
	body: {
	  'theMovieDbId': 7326,
	  'languageCode': "en"
	},
	json: true, 
	timeout: 20000, 
	url: 'http://my.media.server/api/v1/Request/movie',
	headers: {
		'ApiKey': 'API_KEY_HERE',
		'ApiAlias': 'SwitchLove'
	}
}

request(options, function (err, res, body) {
	if (err) {
		console.log('Error :', err)
		return
	}
	console.log(' Body :', body)
});
```
Which returns the following output:
```javascript
Body : { result: true,
  message: 'Juno (2007) has been successfully added!',
  isError: false,
  errorMessage: null,
  requestId: 22 }
```

**Expected behavior**
Requested by info for movie should show the ApiAlias passed.

**Screenshots**
[https://i.imgur.com/Uj8QGYJ.png](https://i.imgur.com/Uj8QGYJ.png)

**Logs (Logs directory where Ombi is located)**
Logs show no errors or anything else regarding the API request. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS

**Ombi Version (please complete the following information):**
 - Version: 3.0.4119
- Media Server: Plex

**Additional context**
As far as I can tell, the headers are being passed correctly and I can see them in the res of the request function.

**Comment by tidusjar** [comment]
This is not available in master yet.

https://github.com/tidusjar/Ombi/commit/3b913923233ec65976b8a33ede0104860f757e93
