### ISSUE TITLE
Issues button is very big with Spanish language.

### ISSUE THREAD

**Issue by vsc55** [tidusjar/Ombi#2784]
**Describe the bug**
In section search "Issues" button movies and TV it is very large and exceeds the edge of the box.

**To Reproduce**
1. Select translation to Spanish.
2. go to the search section
3. search any movie.

**Screenshots**
![image](https://user-images.githubusercontent.com/13438676/52175046-f5e0a600-279d-11e9-8925-9a4c20c9ba57.png)

**Logs (Logs directory where Ombi is located)**
`NA`

**Desktop (please complete the following information):**
- OS: Windows 10

**Ombi Version:**
- Version: 3.0.4183
- Branch: develop

**Additional context**
Tested with the following browsers:
- Firefox 65
- Chrome 71.0.3578.98
- Microsoft Edge

**Comment by tidusjar** [comment]
Thanks for the report.

I am not sure what I can do about this. Is it possible to have a smaller translation but keep the correct context?

**Comment by vsc55** [comment]
you could change the text to the next one that takes up less space:
> Avisar de problema/error

**Comment by tidusjar** [comment]
Can you please make the change on CrowdIn. It's on the wiki page. All translations are community source. 

Thanks!
