### ISSUE TITLE
Series still listed as not available when they have episodes with dates of 01/01/0001

### ISSUE THREAD

**Issue by TheRealStarboy** [tidusjar/Ombi#2786]
**Describe the bug**
Episodes with the date of 01/01/0001 cause the Series to show the request button instead of the Available button. I have posted this issue before and was told it was already fixed in the next version but it still doesn't seem to be fixed. This seems to happen a lot with future episodes to be aired they get assigned a date of 01/01/0001.

**To Reproduce**
1. This happens with any series that has episodes with this date structure. A current example would be Lucifer.

**Expected behavior**
I would expect that ombi would ignore this date just like it ignores all future dates even though this is not a future date it is always the same and could easily be filtered just like future dates.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Server: Windows Server 2012 R2
 - Client: Windows 10 Enterprise 1803

**Ombi Version (please complete the following information):**
 - Ombi Version 3.0.4119]
- Media Server Plex 1.14.1.5488

**Additional context**

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
