### ISSUE TITLE
Set Discord user ID via the API

### ISSUE THREAD

**Issue by Puyodead1** [tidusjar/Ombi#2789]
I am using the API to create users but cannot see how to add notification preferences with it. i need to set the discord id if its possible.

**Comment by tidusjar** [comment]
Take a look at swagger at these endpoints

![image](https://user-images.githubusercontent.com/6642220/52238787-cb3d3d00-28c4-11e9-92f0-d1b307ed8616.png)

**Comment by Puyodead1** [comment]
Thanks
