### ISSUE TITLE
Unable to manage users on Chrome

### ISSUE THREAD

**Issue by DeathByDentures** [tidusjar/Ombi#2792]
**Describe the bug**
When I click on details/edit next to a user it loads their profile, then immediately reverts to my profile.

**To Reproduce**
1. Go to 'User Management'
2. Click on 'Details/Edit'

**Expected behavior**
Previously it would stay on their user information so I could edit roles, aliases, etc.

**Screenshots**
https://imgur.com/a/QRLfMuM

**Logs (Logs directory where Ombi is located)**
If applicable, I happy to provide.

**Desktop (please complete the following information):**
 - OS: Debian 9

**Ombi Version (please complete the following information):**
 - Version: 3.0.4119
- Media Server: Plex

**Additional context**
I restarted the service and the machine - no effect.

**Comment by tidusjar** [comment]
Try clearing cache?

**Comment by DeathByDentures** [comment]
This issue continues, just FYI. Chrome keeps doing the same thing. I can only get it to work if I clear the cache then immediately log in and edit users - or use a different browser. 

After a few minutes, it starts repeating the error first reported.

**Comment by infamouswb** [comment]
I am not sure whats happening, but I cant manage users or login....no ones password is working....

**Comment by goldenpipes** [comment]
@DeathByDentures do you have any chrome addons messing with things?  I have been unable to re-produce this.  Could you try it with addons disabled?

**Comment by DillonsFlix** [comment]
For a few months now I have been having issues with Chrome's cache across Ombi, radarr, and sonarr.  I either have to clear my cache or open the site in incognito mode.  I have not had time to figure it out so I have learned to just live with it.

**Comment by DeathByDentures** [comment]
> @DeathByDentures do you have any chrome addons messing with things? I have been unable to re-produce this. Could you try it with addons disabled?

Hit the nail on the head. It's lastpass. So apparently when you enter a new username it changes it at the top. So it's not really changing the user, it's only auto-filling the details with my login. 

Any way I can change this report from a bug report to an incompatibility?

**Comment by tidusjar** [comment]
That's interesting. Well I'm redoing the whole UI with v4 so this will be fixed in that.
