### ISSUE TITLE
Swagger index doesn't prepend configured baseurl

### ISSUE THREAD

**Issue by au5ton** [tidusjar/Ombi#2793]
**Describe the bug**

The Swagger HTML landing page does not prepend the configured baseurl when trying to reach the Swagger endpoint. For instance, I am configured for a reverse proxy through nginx such that: `https://hostname/ombi/search` is the Ombi homepage when logged in. The Ombi homepage and other functionality functions normally and has expected behavior. However, when visiting `https://hostname/ombi/swagger/index.html` the webpage presented loads and the XMLHTTPRequest sent via JavaScript fails because it is trying to reach the endpoint: `https://hostname/swagger/v1/swagger.json` instead of `https://hostname/ombi/swagger/v1/swagger.json`

**To Reproduce**
- Configure Ombi to use a baseurl (/Settings/Ombi)
- Access Swagger under the baseurl (/baseurl/Swagger/index.html)
- Swagger fails to display properly

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/4109551/52320423-e11a3300-2994-11e9-86ac-aa6708b68680.png)

![image](https://user-images.githubusercontent.com/4109551/52320507-4706ba80-2995-11e9-8f4a-4accc5c43fc1.png)

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server Plex

**Additional context**

https://github.com/tidusjar/Ombi/blob/5ee25be669e0ae7f3b9754656530197e0237731b/src/Ombi/Startup.cs#L244

**Comment by tidusjar** [comment]
Not stale

**Comment by au5ton** [comment]
I'll look into this

**Comment by au5ton** [comment]
PR submitted. 👍
