### ISSUE TITLE
Shows just disappear when searching

### ISSUE THREAD

**Issue by nmbrg** [tidusjar/Ombi#2794]
**Describe the bug**
When searching for (and trying to add/request) the shows "good omens" and "the boys" they just breifly show up, and then disappears. Both shows have tvdbID (checked and confirmed with tvmaze)

**To Reproduce**
1. Go to Search
2. Click on TV
3. Write either "good omens" or "the boys"
4. Watch how they breifly show up (a split second) and then just disappears.

**Expected behavior**
Expected it to show the tv-shows so i could add/request them.

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2

**Ombi Version (please complete the following information):**
 - Version 3.0.4119

**Comment by nmbrg** [comment]
for some reason thetvdb removed "good omens" now, and tvmaze then decided to remove tvdbID for that show. But that still leaves "the boys" not working as it should.

**Comment by nmbrg** [comment]
The boys show up when searching in the iOS app.
But not when searching in a browser on a PC. 
tried firefox, Edge and IE (with and without private mode)
no plugins installed on Edge and IE.

**Comment by goldenpipes** [comment]
https://github.com/tidusjar/Ombi/wiki/FAQ

Once the data is available on tvmaze it should show in ombi.

**Comment by nmbrg** [comment]
Haha, your kidding right?
I literary just told you that it shows up in the ios app. And I also said that the data was available on tvmaze. (Except the removal of tvdbid of good omens). So no, this isn't a "external problem"

**Comment by tidusjar** [comment]
Please keep it friendly. Goldenpipes was only trying to help.

It's because TV Maze doesn't hold any episode information for that show. The reason it's working on the App is due to a bug that I have tried fixing but Apple is denying me to publish any updates at the moment due to "Copyright infringement"

**Comment by nmbrg** [comment]
So when its working, it's a bug? And when its not working its someone else's fault?

**Comment by tidusjar** [comment]
It should not be showing.

TVMaze has no episode information so there would be no way to request anything.

I'm not sure what your issue is, but remember that this is free software that i develop for you in my **free** time.

**Comment by nmbrg** [comment]
my issue is what i was describing in my original post (and then added more information about in the second, and third, post).

**Comment by tidusjar** [comment]
And i've stated what needs to be done and what is wrong.

When I said "I'm not sure on what your issue is", I was referring to the hostilely and negativity you are bringing.

**Comment by nmbrg** [comment]
no shit sherlock. :)
and ""I'm not sure on what your issue is" isnt hostile?
live as you learn mr. 

have a nice day.
