### ISSUE TITLE
Ombi Scan before Emby picked up metadata

### ISSUE THREAD

**Issue by quorn23** [tidusjar/Ombi#2797]
**Describe the bug**
Ombi keeps being "stuck" in a request processing state, if the Ombi Scan of Emby runs before Emby picked up the meta data.

The Title in the "EmbyContent" Table in OmbiExternal.db has the release name and not the movie title
"ImdbID" and "TheMovieDbId" tables are empty.

Edit: https://ibb.co/p4HbBYs Screenshot for reference

**To Reproduce**
1. Shedule Library scan task in emby for every 12 hour
2. Request a movie in Ombi
3. Let Radarr fulfill the request
4. Wait for Notification Movieblabla has been added to Emby Server
5. Ombi Scan runs
6. Ombi DB keeps the release name which are without any imdb/moviedb ids yet

**Expected behavior**
Ombi Scan of Emby should happen after the metadata has been populated by Emby, or update the db with it.

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]

3.0.4119
--

- Media Server [e.g. Plex]

Emby 4.0.1.0

**Additional context**
Talked with Tidusjar on Discord helping me to these findings.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
