### ISSUE TITLE
Separate custom logo for emails

### ISSUE THREAD

**Issue by Malcolmest** [tidusjar/Ombi#2798]
I have setup a nice logo for my services with white text on a clear background. It looks wonderful for the login and landing pages but when that same image is used in a newsletter, welcome, or password reset email it shows as a large white space above the text of the email. I would love an option to use a second image so that I can use my logo with a black background on my emails. Thanks for all the hard work on this project!

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
