### ISSUE TITLE
Ombi Allows Album Requests that Lidarr Doesn't Recognize

### ISSUE THREAD

**Issue by millertime0503** [tidusjar/Ombi#2805]
**Describe the bug**
Ombi shows albums and allows you to "successfully" request them, but they go to a blackhole if Lidarr doesn't have the listed with that artist.

**To Reproduce**
1. View Albums for "Dr. Dre"
2. Request Detoxification
3. Note that this album does not exist as part of Dr. Dre's catalogue in Lidarr (I did turn on all Metadata Profiles)

**Expected behavior**
If Lidarr does not have the ability to add the album that Ombi found, it should at least fail the request. Ideally, it would not show albums that Lidarr will not be able to add.

**Screenshots**
![dre-lidarr](https://user-images.githubusercontent.com/47581506/52750523-58595380-2fa1-11e9-8a33-38430d41928c.PNG)
![dre-ombi](https://user-images.githubusercontent.com/47581506/52750526-5b544400-2fa1-11e9-863b-918525fc38fe.PNG)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Standard

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Plex

**Additional context**
Please just let me know if you need any more information. This happens with most artists for me, not just Dr. Dre. Thank you!

**Comment by tidusjar** [comment]
That's strange since we are using the Lidarr api

**Comment by millertime0503** [comment]
Thanks Jamie -- I needed to rescan the artist in Lidarr to get it to add the missing tracks (and/or "Allow Metadata file creation").
