### ISSUE TITLE
Unable to remove failed requests

### ISSUE THREAD

**Issue by dualznz** [tidusjar/Ombi#2806]
**Describe the bug**
When trying to remove failed requests nothing happens and it throws an error in chrome console.
Also why are there failed requests in the first place as the files are on my server....

**To Reproduce**
1. Go to Settings
2. Click on System
3. Scroll down to Failed Requests
4. See error when trying to remove items in chrome console

**Expected behavior**
When clicking on "Remove" the item should be removed from Failed Requests

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/f733a0781fcd562fd4c2f538caa51172/raw)](https://gyazo.com/f733a0781fcd562fd4c2f538caa51172)

Please note i have hidden the direct url of the site as it is on production and not local, but as you will see in the provided screenshot the full url has two // so maybe missing route.

**Desktop (please complete the following information):**
Server = Ubuntu 16.04.5 LTS Server Environment
Desktop = Windows 10 Pro
Browser = Chrome (latest)

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server = Plex

**Comment by tidusjar** [comment]
I am unable to recreate this.

Are you able to email me your Ombi.db so I can try and reproduce it with your data?

tidusjar@gmail.com

**Comment by tidusjar** [comment]
As discussed on Discord, I was still unable to reproduce this even with your database. I was able to remove the failed requests without an issue

**Comment by lcasale** [comment]
@dualznz were you by chance using a subdomain as a reverse proxy? I was experiencing the same issue because I missed the trailing "/" in the proxy_pass directive until I took a closer look at https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#nginx

**Comment by Undeadllama** [comment]
(Sorry for the thread necro... let me know if I should open a new issue instead)

I'm also seeing this problem when attempting to remove failed requests... even when accessing the Ombi interface directly (not via reverse proxy).

![image](https://user-images.githubusercontent.com/3908975/74934783-da633000-53de-11ea-94b1-63f2cf782c03.png)

Environment:
Desktop = Tested on both Windows 10 Pro and Windows Server 2012 R2
Browser = Chrome (80.0.3987.106 and latest)

Server = Windows Server 2012 R2
Ombi version = 3.0.4892
Media Server = Plex

**Comment by Keelan** [comment]
Similar issue i believe
![image](https://user-images.githubusercontent.com/1158997/81488069-182f6200-9232-11ea-95a7-9f55ba42a704.png)

**Comment by scottdfedorov** [comment]
Also having the issue. A demo user with the manage requests role was unable to remove an item, but my admin user was able to.
