### ISSUE TITLE
Ombi not recognizing TV shows as available but saying "We already have episodes requested from series ...."

### ISSUE THREAD

**Issue by beanieman77** [tidusjar/Ombi#2808]
So basically True Detective is a good example of this. 

Even though I have the series, it has the request button next to it

But if i go to add it, it says this:

Request added
We already have episodes requested from series True Detective. But it is not in the requests tab.

**Comment by roborobp** [comment]
I also see this issue.

**Comment by tidusjar** [comment]
Please in future use the issue template. It's there for a reason.

This would be due to you having some episodes/seasons monitored in Sonarr. This is expected.

**Comment by timartinelli** [comment]
I have this same problem and I don't have the series on the sonnar.

**Comment by SlovakianCanon** [comment]
Same here, and I don't have Sonarr enabled, I only linked Ombi to Plex. Most shows are appearing correctly but Friends and Sherlock don't, to name these two
