### ISSUE TITLE
Issue with TV shows not showing as available even though the library already has 

### ISSUE THREAD

**Issue by beanieman77** [tidusjar/Ombi#2809]
**Describe the bug**
All of the movies that are in the library are correctly displayed as "Available" in Ombi. However, all of the TV shows that are in the library have the +Request button next to them as if they are not already in the library. If I click the +Request button next to that show, I get a message stating "Request Added: We already have episodes requested from series "" "" ""

**To Reproduce**
Search for True Detective. 
Next to True Detective, see +Request button (True Detective is already in library)
Pushing +Request button returns message, "Request Added: We already have episodes requested from series "" "" "" When looking at requests tab under TV Shows, True Detective does not appear.

**Expected behavior**
True Detective should show up as "Available" when searching because its already in the Plex Library

[
[OmbiExternal.zip](https://github.com/tidusjar/Ombi/files/2867157/OmbiExternal.zip)

](url)
**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
Windows 10 x64

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
This has been fixed by user.
