### ISSUE TITLE
Link to plex media in newsletter with Emby configured

### ISSUE THREAD

**Issue by hbooo** [tidusjar/Ombi#2810]
**Describe the bug**
 First I had Plex configured and running but decided to switch to emby. I disabled plex server in Ombi and add Emby server, but newsleeter 

**To Reproduce**
1. Add Plex Server
2. Configure newsletter, newsletter is sent with plex links
3. Remove Plex Server
4. Add Emby Server
5. Newsletter is sent with plex links

**Expected behavior**
Newsletter should use active server

**Desktop:**
 - OS: unRaid

**Ombi Version:**
 - Version 3.0.4222
- Media Server : Plex disabled, Emby enable

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
