### ISSUE TITLE
Discord notification being sent even though user is not setup to receive them.

### ISSUE THREAD

**Issue by alexandzors** [tidusjar/Ombi#2815]
Not sure if this is a bug or if I missed a config setting somewhere.

**Describe the bug**
User is added to Ombi as local user with no notifications setup. User requests media and Ombi fires a discord notification like so:

`<@!Tori> - The First has been approved! It will be available shortly!`

User's Discord settings in Ombi:
![image](https://user-images.githubusercontent.com/25626115/52922868-6a652a00-32f2-11e9-9092-b6039efc6d1a.png)

**To Reproduce**
1. Create local Ombi user.
2. Setup discord notifications so that a user is @ when notification is fired. `<@!{UserPreference}> - {Title} has been approved! It will be available shortly!`
3. Setup new local user to not use discord notifications.
4. Have new local user request media.

**Expected behavior**
Ombi should not send a discord notification if the user is not setup to use it as a means of being notified.

**Screenshots**
![image](https://user-images.githubusercontent.com/25626115/52922951-dcd60a00-32f2-11e9-9c49-f48ea3b31ff5.png)

**Logs (Logs directory where Ombi is located)**
I did not see anything in the current log file about notifications. Just media image grabbing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.10

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]: 3.0.4119
- Media See.g. Plex]: Plex

**Additional context**
Ombi is running via the linuxserver.io/ombi:latest docker container.
Docker engine vr: 
![image](https://user-images.githubusercontent.com/25626115/52923085-cbd9c880-32f3-11e9-8c44-3fc5e83103d3.png)

**Comment by tidusjar** [comment]
what you  are seeing is the correct behaviour. 

The `UserPreference` is empty in your screenshot.

Since it is empty it will fallback to the Alias then Username.

Please see here for the variables https://github.com/tidusjar/Ombi/wiki/Notification-Template-Variables.
