### ISSUE TITLE
Error when trying to trigger a newsletter

### ISSUE THREAD

**Issue by hbooo** [tidusjar/Ombi#2818]
**Describe the bug**
If I test a newsletter, it is correctly generated and sent but if I try to trigger one, I have an error in the logs

**To Reproduce**
1. Go to newlsetter
2. Test a newsletter
3. Mail is sent
4. Trigger a newsletter
5. Nothing happens

**Expected behavior**
Newsletter should be generated and sent

**Logs (Logs directory where Ombi is located)**
[49m: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0]
Error when attempting to create newsletter

MimeKit.ParseException: Unexpected token at offset 26
at MimeKit.MailboxAddress.set_Address(String value)
at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 198

**Desktop (please complete the following information):**
 - OS: unRAID

**Ombi Version (please complete the following information):**
 - Version 3.0.4244
- Media Server : Emby

**Comment by tidusjar** [comment]
Looks like one of your users email that we are attempting to send a newsletter to is invalid.

**Comment by hbooo** [comment]
That's it, one of my users was registered with a space at the end of the mail. Thanks for the help
