### ISSUE TITLE
Status set as Available even after movie has been deleted from Radarr and/or Plex

### ISSUE THREAD

**Issue by rudyolph** [tidusjar/Ombi#2824]
**Describe the bug**
After a movie is deleted from the plex server either by radarr or plex directly the movie still shows as available in Ombi.  

**To Reproduce**
Request a movie.
Wait until movie is downloaded and added to plex and ombi reports it as available.
delete movie either in plex directly or via radarr.

**Expected behavior**
The expected behavior would be that ombi would recognize the movie was deleted or no longer available on plex and report it unavailable.

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - OS: Windows 110

**Ombi Version (please complete the following information):**
 - Version 3.4222
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
Ombi does do this, it's on a job that runs every 5 days by default.

**Comment by rudyolph** [comment]
Yes but I'm saying it doesn't appear to be working or at least i have yet to see it work.   It is a very intensive job?  Why run only 5 days as opposed to every day?

**Comment by tidusjar** [comment]
It's very intensive, I wouldn't recommend running it frequently.

**Comment by rudyolph** [comment]
Just an FYI...its been 11 days and movies that were deleted from both radarr and plex are still showing as available in Ombi.  I know you want to keep this closed but it is still a viable bug.

**Comment by tidusjar** [comment]
Can you query the PlexContent table for the media item in question?

It's in the OmbiExternal.db

**Comment by rudyolph** [comment]
It is not in the table but the request is still flagged available.
![request](https://user-images.githubusercontent.com/28231598/53755621-f3e53200-3e84-11e9-8f68-de2025b1e55f.PNG)
![db](https://user-images.githubusercontent.com/28231598/53755628-fa73a980-3e84-11e9-8921-ba00431ea27c.PNG)

**Comment by tidusjar** [comment]
Sorry my misunderstanding of your issue. 

Once a request has been made available, ombi will not keep looking at the media server to update that request. This is expected.

Requests are not meant to be for keeping the state, as there would be no notification saying that request X is not unavailable. 

Once a request has been fulfilled, it's pretty pointless keeping it around.

**Comment by jaretclifton** [comment]
This is still an issue. I'm running into the same thing -- delete media on Plex/Radarr/Sonarr but Ombi continues to show the file as "Available". This prevents users from re-requesting it in the future... I tend to go in and purge old/unwatched shows/movies at random intervals... inevitably one of my users will want to go watch one of these deleted items and not find it in Plex. They head to Ombi to request it, only to find Ombi says the title is available. The mouse icon becomes a circle with a slash through it and they cannot request the item again.

As an admin, I can't even set the item to unavailable in Ombi. I too receive the circle with a slash mouse pointer.

**Comment by rudyolph** [comment]
I believe Tid's view on this is that you should just manually delete the
old request in Ombi after you delete the show/movie which should then allow
it to be re-requested.  However I question the usability and flow of that
process. It doesn't seem intuitive to me and is rather clunky. Ombi should
be able to determine the movie was deleted and just automatically dele the
old request or flag it's status as unavailable.

**Comment by nebb00** [comment]
> This is still an issue. I'm running into the same thing -- delete media on Plex/Radarr/Sonarr but Ombi continues to show the file as "Available". This prevents users from re-requesting it in the future... I tend to go in and purge old/unwatched shows/movies at random intervals... inevitably one of my users will want to go watch one of these deleted items and not find it in Plex. They head to Ombi to request it, only to find Ombi says the title is available. The mouse icon becomes a circle with a slash through it and they cannot request the item again.
> 
> As an admin, I can't even set the item to unavailable in Ombi. I too receive the circle with a slash mouse pointer.

I would love the same feature. Could it not be a manually run command to check the status of previously available requests. If its no longer exists. Ombi deletes the request?

**Comment by danktankk** [comment]
This is STILL an issue.  You cant delete the request that I can tell either.

**Comment by itchykill** [comment]
It does seem strange, that you have to manually remove the requests.

**Comment by TobiasKneidl** [comment]
@tidusjar any update on this? This is still an issue!

If I deleted something my users can't re-request it becauso ombi says its still available.

**Comment by Zachar2** [comment]
Same problem here. Can't re-request after deletion as it shows as still available :(.

**Comment by nebb00** [comment]
A workaround is to turn off ombi and delete one of the databases. External something? I don't remember. Starting ombi recreates it and forces a fresh plex scan.

Someone else might remember the name

**Comment by Zachar2** [comment]
Thanks. Manually deleting OmbiExternal.db and restarting Ombi container solved the issue.

**Comment by nebb00** [comment]
To save on the manually steps. It would be nice for a button to recreate this db. But least the workaround isn't too painful

**Comment by johnudberg** [comment]
Has something changed that means deleting OmbiExternal.db and restarting Ombi won't now fix this issue?  I have done those steps and Movies that have been deleted in Plex are still showing as available in Ombi.

**Comment by tidusjar** [comment]
It could be the case that’s it’s available in radarr and you have the radarr availability setting enabled

**Comment by johnudberg** [comment]
> It could be the case that’s it’s available in radarr and you have the radarr availability setting enabled

No, that didn’t seem to be the case. I’ve since realised Ombi has a setting to do this now and you can schedule a job to run to delete requests x days after they are fulfilled. Problem sorted without the workaround!

**Comment by omg-wtf-bbq-lol** [comment]
I too am running in to the same issue.  Is there a way to manually purge the "availability" from the DB or something?  I changed the cron job time for the plex sync and media refresh jobs, in hopes that might make a difference, but it did not.
