### ISSUE TITLE
LidarrAlbumCache table is empty even after Lidarr Sync is run.

### ISSUE THREAD

**Issue by rudyolph** [tidusjar/Ombi#2825]
**Describe the bug**
After connecting Lidarr to ombi and the sync has run the LidarrAlbumCache table remains empty.
The LidarrArtistCache table is populated fine but nothing appears in the AlbumCache table.  I've noticed that Ombi also doesn't seem to report that album are availalbe correctly even after they are fully downloaded and showing as available in Lidarr and plex.  I'm wondering if the empty table and the issue with status reporting is related?

**To Reproduce**
Wait for lidarr sync to run and view the table using a SQLite DB viewer.

**Expected behavior**
The table would be populated with album information

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.4222
- Media Server Plex
-Lidarr Version: 0.5.0.633

**Additional context**

**Comment by tidusjar** [comment]
Which database are you looking in?

**Comment by rudyolph** [comment]
ombiexternal.db

**Comment by Qstick** [comment]
@tidusjar this should be fixed from our side, looks like OP on nightly, so likely same as other issue
