### ISSUE TITLE
Only TV is marked available and viewable in ombi

### ISSUE THREAD

**Issue by Ing-Med** [tidusjar/Ombi#2828]
**Describe the bug**
There are only but a few movies in my requests which show the green available and plex button. I recently added movies, but even after manual sync (full or recent), they would not show up correctly in ombi. 
TV on the other hand works without problems. 

Plex integration and radarr integration per se work as intended. Testbuttons work. Plex librarys are all selected for sync. 

**To Reproduce**
Problem persists with new movie requests - new TV requests get handled properly.

**Expected behavior**
Downloaded movies should show up in ombi, marked as avialable and viewable (link) with plex

**Logs (Logs directory where Ombi is located)**
`      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV-gdrive = 2676
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2526
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2376
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2226
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2076
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1926
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1776
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1626
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1476
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1326
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1176
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1026
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 876
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 726
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 576
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 426
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 276
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 126
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      We have finished caching the episodes.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server`

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Plex 1.14.1.5488

PS: Please add timestamps to the logs :) 

Thanks in advance!

**Comment by tidusjar** [comment]
Run the Manual Full Sync wait for it to finish by monitoring the logs (It's finished when it starts doing episodes), then please upload the log file.

**Comment by Ing-Med** [comment]
here is the full log since yesterdays search.

`info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV-gdrive = 2676
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2526
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2376
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2226
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2076
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1926
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1776
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1626
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1476
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1326
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1176
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1026
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 876
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 726
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 576
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 426
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 276
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 126
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      We have finished caching the episodes.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV-gdrive = 2676
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2526
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2376
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2226
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2076
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1926
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1776
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1626
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1476
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1326
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1176
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1026
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 876
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 726
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 576
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 426
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 276
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 126
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      We have finished caching the episodes.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Starting the Metadata refresh from RecentlyAddedSync
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Starting the Metadata refresh from RecentlyAddedSync
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Total Epsiodes found for TV-gdrive = 2676
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2526
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2376
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2226
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 2076
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1926
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1776
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1626
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1476
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1326
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1176
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 1026
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 876
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 726
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 576
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 426
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 276
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      Processed 150 more episodes. Total Remaining 126
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
      We have finished caching the episodes.
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server localhost
`

**Comment by tidusjar** [comment]
Where did you get the logs from?

**Comment by Ing-Med** [comment]
My ombi is preinstalled on a server. The log file resides in the a directory where the config is stored, not the app. A separate /Logs folder is, i think, only used for error logs.

![image](https://user-images.githubusercontent.com/45925210/53205210-f4343080-362d-11e9-9676-7a9eb71ffc9c.png)

**Comment by goldenpipes** [comment]
When you search for a movie that **you know is available** on your Plex Server, does it show as, 'Available on Plex' in the search results?

**Comment by Ing-Med** [comment]
Yes, each move is marked available after i some time (i think this is due to the sync intervals which are rather high, daily or half daily if i remember correctly).
It says literally: "Request status: Available"

**Comment by tidusjar** [comment]
So what's the issue?

**Comment by Ing-Med** [comment]
I will try to show you in pictures.

In the request window, there are no buttons for plex. 
![image](https://user-images.githubusercontent.com/45925210/53303570-2c28b700-386c-11e9-96ee-951d70339a80.png)

In the search window, there is (?!) Everything seems normal there. But i don't even know why the movie shows up in the search window.
![image](https://user-images.githubusercontent.com/45925210/53303578-5c705580-386c-11e9-907b-997b87dc29a3.png)

Hope this makes it more clear.

**Comment by tidusjar** [comment]
The view on Plex only appears on the search. That is expected. 

The movie still did appear in the search. All this is expected. 

The UI will be more clear in v4

**Comment by Ing-Med** [comment]
Ah, interesting. 
Looking forward to v4 then :) 

Thanks, sorry for the inconvenience

**Comment by tidusjar** [comment]
Don't be sorry!

Thanks for taking an interest
