### ISSUE TITLE
Unable to use Discord to Send Welcome Email

### ISSUE THREAD

**Issue by DoomGekicher** [tidusjar/Ombi#2831]
Under Notifcations->Discord I can see "Welcome Email" as one of the options but It seems that even though the option is there you can't actually use Discord to send them. Not sure if this is an Issue or intended but currently I don't want to setup an email server or whatever I have to do and would rather keep all notifs to discord.

**To Reproduce**
Irrelevant

**Expected behavior**
Should be able to select which notif service you want to use to send out welcome emails, or just default to whatever you have selected maybe?

**Screenshots**
Irrelevant 

**Logs (Logs directory where Ombi is located)**
Irrelevant

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**
Also would be cool if you added the ability to send Newsletter to Discord.

**Comment by tidusjar** [comment]
You cannot send a welcome email to Discord. That shouldn't be there.
