### ISSUE TITLE
Ombi letsencrypt linux

### ISSUE THREAD

**Issue by MarvinMedia** [tidusjar/Ombi#2836]
Hey man sorry but I can't use letsencrypt with Ombi, how I do that?

I have Ombi installed with Emby on linux (Debian 9)

Thank you.

**Comment by tidusjar** [comment]
You need a reverse proxy in place or a webserver in front of Ombi, usual is Nginx

**Comment by MarvinMedia** [comment]
Okay thank you I check this later thank you for your answer.
OMBI is so nice to use thank you for that.
