### ISSUE TITLE
Rotating/Random selection for suggested shows/movies

### ISSUE THREAD

**Issue by lenaxia** [tidusjar/Ombi#2837]
Currently suggested Movies and TV shows only show the top an, at best, slowly rotating list of suggestions.

To improve discovery, instead, grab a random selection of the top movies and display those so every time the page is refreshed, different movies show up.

e.g. in /src/Ombi.Core/Engine/MovieSearchEngine.cs

127 return await TransformMovieResultsToResponse(result.Take(MovieLimit)); // Take x to stop us overloading the API

Might look like 

127 return await TransformMovieResultsToResponse(result.TakeRandom(MovieLimit)); // Take x to stop us overloading the API

Where result.TakeRandom() returns a random set of the top most popular movies.

Or potentially in /src/Ombi.Core/Engine/Interfaces/IMovieEngine.cs add an:

Task<IEnumerable<SearchMovieViewModel>> RandomPopularMovies();

**Comment by tidusjar** [comment]
This is a good suggestion for the V4 interface.

See the below for the V4 interface:

![image](https://user-images.githubusercontent.com/6642220/53204811-7881b600-3624-11e9-89ad-06ebad5cfd42.png)

**Comment by lenaxia** [comment]
Nice! 

Point of feedback, as I didn't see a specific tag for V4 (I can create a new issue if that works better).

* Having [+Request] and [Similar] immediately accessible is very convenient as it minimizes the number of clicks a user needs to perform an "Add", same goes with Similar.
* Since it seems like tags and buttons will be hidden, will they be visible in the "v" menu? On touch devices, like iOS, or Windows 10, hover over elements don't work well.

For what it's worth, on desktop websites, I really like the current UI. Having the summary displayed next to the cover photo and most important UI elements (Request and similar) available without extra clicks is a very good user experience. 

For mobile, I agree the current UI doesn't perform as well (since it can't render so much text and buttons). And can see how the "v" feature will be a big improvement. 

-Mike

**Comment by tidusjar** [comment]
The V menu is a click and opens this:
![image](https://user-images.githubusercontent.com/6642220/53205950-9f8db700-3627-11e9-864b-53aa6d7125ee.png)

**Comment by tidusjar** [comment]
When clicking on the poster you get this:
![image](https://user-images.githubusercontent.com/6642220/53205982-b46a4a80-3627-11e9-8b29-ec2a0f20d2b1.png)

**Comment by tidusjar** [comment]
Done this in v4
