### ISSUE TITLE
Paragraphs at top of Requests and Search tabs not always accurate--could benefit from being editable

### ISSUE THREAD

**Issue by harrv** [tidusjar/Ombi#2838]
Hi. I love Ombi. Thanks for all of the hard work on it!

I'm opening this issue to report a bug, and to ask for a related feature.

**Bug Report**

In wwwroot/translations/en.json in Requests.Paragraph the string is, "Below you can see yours and all other requests, as well as their download and approval status." That string is shown at the top of the Requests page, but isn't accurate for my Ombi setup, because I have selected "Hide requests from other users" in the Ombi configuration. So a user will only see his or her own requests on the Requests page, not "and all other requests".

**Related Feature Request**

For a while now, I've been editing wwwroot/translations/en.json on my local installation, both to fix the issue above and because I want to customize the message further. The two strings that I customize are Requests.Paragraph and Search.Paragraph. If you're interested, my custom strings look like this...

On the requests tab:
_Below you can see the status of your requests. If the request status says "Processing Request" for more than a few hours, it probably couldn't be found but the system will keep looking. New requests can be made from the Search tab._

On the search tab:
_Check Netflix before making a request. Requested movies are automatically added to the server but are deleted after four weeks to make room for more requests, so if you make a request plan to watch it soon. You may request a movie that isn't out on Blu-ray/DVD yet, but fulfillment will be postponed until it is._

Some of the information I want to convey on those pages is somewhat unique to my particular server, but I think it would be common for Ombi administrators to want to be able to edit at least those two strings.

Editing wwwroot/translations/en.json works fine temporarily, but an update clobbers it, so it would be great to be able to save those customizations in the Ombi config so it persists (I presume, in a database) through the update process.

I only have a handful of users and they're all English speakers, but I recognize that because the two strings I'm talking about are currently part of the Ombi translation files, that could present a challenge if you allow customization. However, it's really not a lot different than other things you currently allow to be customized--email notifications templates, for example. I haven't noticed a way to provide multiple versions of the email templates for different languages, so perhaps the admins who want to customize the paragraph strings on the Requests and Search pages won't mind if you limit the customization to a single language as well. Or, for maximum flexibility, you could come up with a way to customize _any_ string in _any_ of the translation JSON files.

Thanks for your time, and for considering my request! Keep up the good work!

**Comment by goldenpipes** [comment]
BRILLIANT.

**Comment by goldenpipes** [comment]
This is brilliant!  Even if its just a textbox in the Customization Settings in ombi settings.

**Comment by goldenpipes** [comment]
This is brilliant!  Even if its just a textbox in the Customization Settings in ombi settings.

**Comment by tidusjar** [comment]
Hey sorry I must have not seen this.

Yeah it's a good idea, but the thing is with the new V4 UI, none of that text is going to exist.

So what I would recommend you doing is use the Custom Page and put the information on there? Or even the Landing Page?

Thanks
