### ISSUE TITLE
not able to login to Ombi via NGINX ombi version 3.0.4256

### ISSUE THREAD

**Issue by irabeamte2** [tidusjar/Ombi#2839]
**Describe the bug**
i can't login to ombi via ombi.myadress.com. works perfect if i acces it local. 
- if i press the 'Login with plex' button i get a popup with the same question again (sign in with ombi, sign in with plex). if i press the sign in with ombi button i can put in anything. but no response. 
**To Reproduce**
1. Go to 'ombi.mydomain.com'
2. Click on 'login plex, popup with same question' & 'login ombi, no response with correct or wrong username'

**Expected behavior**
I should be able to login 

Log:
https://codeshare.io/G6oLlo
****

**Ombi Version (please complete the following information):**
Version | 3.0.4256
Branch | master
 - Ubuntu 18.04, Ombi running in Docker

**Comment by tidusjar** [comment]
What's in the browsers console?

**Comment by tidusjar** [comment]
Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by xlordnashx** [comment]
Same Problem here / started after the last time I updated the app. 


[192.168.1.150-1550853747006.log](https://github.com/tidusjar/Ombi/files/2894891/192.168.1.150-1550853747006.log)


[log-20190222.txt](https://github.com/tidusjar/Ombi/files/2894901/log-20190222.txt)

**Comment by goldenpipes** [comment]
how are you serving ombi to your domain? 
A Record pointing to the IP to ombi.domain.tld ?

**Comment by Iguana9999phil** [comment]
Same here, suddenly no one can log in. If I’m logged in I can refresh and use ombi normal. Logging out and back in again gives me the same errors. Ombi docker (also does this without docker) nginx reverse proxy with ssl cert.

**Comment by irabeamte2** [comment]
@goldenpipes i use ssl. my domain is on google domains. dns via cloudflaire. so I have certificates from letsencrypt for all subdomains. everetyng is behind NGINX. so https://ombi.mydomain.com points to ombi port. all other services work fine (organizr, sonarr, radarr, sabnzbd, plex, homeassistant, nodered). 
@tidusjar  there is nothing in the preview sceen.
![image](https://user-images.githubusercontent.com/45318057/53280956-1e1a4f80-3721-11e9-91e3-183d4ed47030.png)
