### ISSUE TITLE
User Management not Working Properly

### ISSUE THREAD

**Issue by mouzzampk2014** [tidusjar/Ombi#2841]
**Describe the bug**
I have three users including Plex Admin and two Plex Users. Ombi successfully imported the users into the User Management but when I Plex Users exclude from Import and add "**user b**" in the exclude I can still the "**user b**" in User Management.

**Expected behavior**
I thought once I add the user in exclude list then I won't see in the User Management list.

**Screenshots**
I attached the screenshots.

![1](https://user-images.githubusercontent.com/44548525/53228627-b0671880-3679-11e9-996b-5212855bdca5.JPG)
![2](https://user-images.githubusercontent.com/44548525/53228628-b0ffaf00-3679-11e9-8825-7f0f2ce26a8d.JPG)

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server [Plex]

**Comment by tidusjar** [comment]
Did the importer already add `userb` before you excluded it?

**Comment by mouzzampk2014** [comment]
Morning Jamie,

Yes Ombi already imported the user.

Thank you

**Comment by tidusjar** [comment]
This is expected. If Ombi has already imported the user then it will not delete it automatically.

**Comment by mouzzampk2014** [comment]
Hi Jamie, can we add this feature if it's possible :)

Thank you

Hassan Arshad
