### ISSUE TITLE
TV shows showing up as "resuest" when they are already in Sonarr

### ISSUE THREAD

**Issue by mstrdraco** [tidusjar/Ombi#2844]
**Describe the bug**
When I look in OMBI and goto TVShows it does not appear to be pulling "current" tv shows in from my Sonarr.. IE The Big Bang Theory ( I have the past 3 seasons) and The Walking Dead (past 3 seasons) both show as +request when they are already in my Sonarr with Several seasons downloaded already. 

**To Reproduce**
Link your Sonarr to OMBI and I've tested connection to verify it's working.  It does show other series however like Game of Thrones- As it shows available. 

**Expected behavior**
It should be pulling in the fact that I have the last 3 seasons on my server and show as "Available" not "+request"

**Desktop (please complete the following information):**
 - OS: Windows Server 2016

**Ombi Version (please complete the following information):**
 Version | 3.0.4256

- Media Server - Plex Media Server, Sonarr for TV and Radarr for Movies

**Comment by mstrdraco** [comment]
It appears to me that if I don't have "ALL" Seasons of a series it's showing that the series in "+request" state, but if I have all seasons IE as I do Game of Thrones then it's showing that it's available.  So I'm guessing it's looking for that first "Season" and Episode to say that it's available?  I would think it should see the Folder in existence and see that there are available seasons and set it as available.

**Comment by tidusjar** [comment]
No, the reason why it's showing as request is that the user still has the ability to request episodes.
