### ISSUE TITLE
Missing essential database management options

### ISSUE THREAD

**Issue by Iguana9999phil** [tidusjar/Ombi#2846]
I’m missing some essential database management options like removing / archiving all available movies / series and mass deletion of all requests. I’ve googled and seen some other users who requested this a couple of years ago, it also WAS available in v2. Removing one by one is a choir as Ombi needs to write it to the database and it takes a couple of seconds. With hundreds of available movies its no fun. If I can do it with sqlite3 directly in the database its also ok (for mass deletion) but a “remove / archive all available” would be essential.

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
