### ISSUE TITLE
Post Request Plex Sharing

### ISSUE THREAD

**Issue by Puyodead1** [tidusjar/Ombi#2849]
I couldn't find a request for sharing the plex library with post or get. is this possible?

**Comment by tidusjar** [comment]
What? Can you please expand

**Comment by Puyodead1** [comment]
You can add Ombi users with a post request, can you share the plex library as well? 
![image](https://user-images.githubusercontent.com/14828766/53352596-14474680-38f1-11e9-9bed-6db8caca7c10.png)
i need to share the library with javascript

**Comment by tidusjar** [comment]
All the code to do that is in this repository.

**Comment by Puyodead1** [comment]
A. i don't know C# so i can't do anything myself with that
B. What i want is a website with a form where people can register, it will create an ombi account and share the plex library to the email they give.

**Comment by tidusjar** [comment]
When you run Ombi, if you go to http://yourombiurl/swagger you will get the ombi API documentation.

Example: https://demo.ombi.io/swagger
