### ISSUE TITLE
Ombi not opening my Emby's server Externally Facing Hostname

### ISSUE THREAD

**Issue by ezanchi** [tidusjar/Ombi#2850]
**Describe the bug**
View On Emby is not poiting to my server eventhough I pasted it in the "Externally Facing Hostname"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Media Server' and the 'Emby'
3. Scroll down to 'Externally Facing Hostname'
4. Pasted there my server's IP
5. Go to Home and search for any already in the library movie.
6. Click on View on Emby, and it wont use my Externally Facing Hostname.

**Expected behavior**
It should redirect users to my Emby's server.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Emby

**Comment by tidusjar** [comment]
It only applies that when the content is cached. So you will delete to delete your OmbiExternal.db and restart ombi (ombi will then re-cache the data)
