### ISSUE TITLE
Feature Request: New status "Partial Available" for Series

### ISSUE THREAD

**Issue by 5ll** [tidusjar/Ombi#2854]
It would be nice if ombi would differentiate between the following states regarding series:

Not Available: no episodes are available in plex
Available: All episodes in all seasons are available in plex
Partial Available: everything in between the above. E. g. some episodes in one or more seasons are available

Right now if just one episode in a 9 season series is missing, "requests" suggests that the series is not available.

**Comment by tidusjar** [comment]
This is also already present in the V4 ui
