### ISSUE TITLE
[Feature Request] Requester has Played the Request

### ISSUE THREAD

**Issue by imerkle** [tidusjar/Ombi#2857]
A Feature that shows Requester that requested the movie has finished playing it.
This would be helpful to purge whatever requester has requested but nobody else wants to watch.

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
