### ISSUE TITLE
Series listed as not available when you have all episodes except ones with dates listed as unknown

### ISSUE THREAD

**Issue by TheRealStarboy** [tidusjar/Ombi#2860]
**Describe the bug**
This is a continuation of the #2786 bug that was closed and listed in the release notes as fixed for version 3.0.4256. What it looks like is that all the dates that would previously be displayed as 01/01/0001 are now displayed as unknown. That's great and all but the logic that marks the series as Available doesn't seem to know that you shouldn't have the episode(s) if it doesn't have an air date that is in the past.

**To Reproduce**
1. This happens with any series that has episodes with dates that are displayed as unknown (previously displayed as 01/01/0001). A current example would be Lucifer.
2. To test use a series that you have and have all the episodes that have air dates in the past but has some future episodes with dates displayed as unknown.
3. That series will not be displayed as Available and will allow you to request episodes that are displayed as unknown.

**Expected behavior**
As I posted in the previous report I would expect any series that has all episodes that have air dates in the past to be counted as Available. If I am wrong about how I perceive this should work then fine but this still seems like a bug to me.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
    Server: Windows Server 2012 R2
    Client: Windows 10 Enterprise 1803

**Ombi Version (please complete the following information):**
 - Version Ombi Version 3.0.4256
- Media Server Plex 1.14.1.5488

**Additional context**

**Comment by tidusjar** [comment]
Can you please send me your OmbiExternal.db to tidusjar@gmail.com so I can reproduce this

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
