### ISSUE TITLE
E-Mail Formatting To Add A Clickable Link

### ISSUE THREAD

**Issue by relctisgerg** [tidusjar/Ombi#2863]
**Describe the bug**
I am trying to add a clickable link in my email. The link shows up in the preview but Ombi formats the link in plain text every time.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Notifications'
3. Select 'Mass Email'
4. Enter 'Link Test' in the 'Subject' line
5. In the 'Body' Enter:
Hello!
&lt;br&gt;
&lt;br&gt;
You have been invited to use {ApplicationName} where you can request conted to be added to Your friendly neighborhood Plex server! 
&lt;br&gt;
&lt;br&gt;
You can login here:  &lt;b&gt;&lt;a href="{ApplicationUrl}"&gt;{ApplicationUrl}&lt;/b&gt;&lt;/a&gt;
&lt;/td&gt;
&lt;br&gt;
&lt;br&gt;
Greg Sitcler
6. Message preview shows a clickable link that works
7. Check the box by your user name in the 'Recipients' column

**Expected behavior**
I expected the email to come out with a clickable link to my Ombi site

**Screenshots**
![ombi email](https://user-images.githubusercontent.com/48181819/53697549-47318480-3da0-11e9-92f5-c6b0a7df68ff.png)

**Logs (Logs directory where Ombi is located)**
None pertaining to this

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 	3.0.4256
- Media Server Plex

**Additional context**
Ass you can see the 'Ombi' and 'www.avast.com' are links but the ombimyplex.hopto.org:5000 is plain text.  I tried to format it like the avast was, but I got the same results

**Comment by relctisgerg** [comment]
`Hello!
<br>
<br>
You have been invited to use {ApplicationName} where you can request conted to be added to Your friendly neighborhood Plex server! 
<br>
<br>
You can login here:  <b><a href="{ApplicationUrl}">{ApplicationUrl}</b></a>
</td>
<br>
<br>
Greg Sitcler`

**Comment by relctisgerg** [comment]
<!-- 
Hello!
<br>
<br>
You have been invited to use {ApplicationName} where you can request conted to be added to Your friendly neighborhood Plex server! 
<br>
<br>
You can login here:  <b><a href="{ApplicationUrl}">{ApplicationUrl}</b></a>
</td>
<br>
<br>
Greg Sitcler
 -- >

**Comment by tidusjar** [comment]
How do you know ombi is removing the link?

In future please follow the issue template or the issue will be closed.

**Comment by relctisgerg** [comment]
Because the test email came out like this
![ombi email](https://user-images.githubusercontent.com/48181819/53697549-47318480-3da0-11e9-92f5-c6b0a7df68ff.png)

**Comment by relctisgerg** [comment]
Code from test email:

Link Test
Greg Sitcler &lt;relctisgerg@gmail.com&gt;
Sun 3/3/2019 9:53 AM
 
Ombi logo
Hello! 

You have been invited to use Ombi where you can request conted to be added to Your friendly neighborhood Plex server! 

You can login here: ombimyplex.hopto.org:5000 

Greg Sitcler


	Virus-free. www.avast.com
Powered by Ombi Sunday, March 3, 2019 9:53 AM	 

Received: from HE1EUR01HT066.eop-EUR01.prod.protection.outlook.com
(2603:10b6:5:94::49) by DM6PR16MB2809.namprd16.prod.outlook.com with HTTPS
via DM6PR07CA0036.NAMPRD07.PROD.OUTLOOK.COM; Sun, 3 Mar 2019 14:53:17 +0000
Received: from HE1EUR01FT029.eop-EUR01.prod.protection.outlook.com
(10.152.0.60) by HE1EUR01HT066.eop-EUR01.prod.protection.outlook.com
(10.152.0.254) with Microsoft SMTP Server (version=TLS1_2,
cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.1643.21; Sun, 3 Mar
2019 14:53:16 +0000
Authentication-Results: spf=pass (sender IP is 209.85.166.194)
smtp.mailfrom=gmail.com; hotmail.com; dkim=pass (signature was verified)
header.d=gmail.com;hotmail.com; dmarc=pass action=none header.from=gmail.com;
Received-SPF: Pass (protection.outlook.com: domain of gmail.com designates
209.85.166.194 as permitted sender) receiver=protection.outlook.com;
client-ip=209.85.166.194; helo=mail-it1-f194.google.com;
Received: from mail-it1-f194.google.com (209.85.166.194) by
HE1EUR01FT029.mail.protection.outlook.com (10.152.0.155) with Microsoft SMTP
Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
15.20.1643.21 via Frontend Transport; Sun, 3 Mar 2019 14:53:16 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:D2C723EE65DBA00A230E5EE7406841A64621358DE394EDAF194C39B703A493E2;UpperCasedChecksum:132FB687C31D090B0BFDFCF6AF7F1141486D6DAACF335C27469DE84F34D1FFB1;SizeAsReceived:2550;Count:18
Received: by mail-it1-f194.google.com with SMTP id v83so3903584itf.1
for &lt;relctisgerg@hotmail.com&gt;; Sun, 03 Mar 2019 06:53:16 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20161025;
h=from:date:subject:message-id:to:mime-version:content-id;
bh=B75ydhKnqy2peDN4+51CCFIdCiGWc8343EzLfz2yD+0=;
b=f21vbZlAc9jGbtcjD7XbiDG7IkOFrOWSxLWkzyISbMuGCsuVbnVLq5x9vfa7idtL3r
phqVHCW1ZbHo8cnQP/gKUWXsD6eMkMwXzK2QiBQasDh1lXSBCxnamMtogUF6phP2C7po
6MLaV3KKglUjw8vyeuN2k6PoWLgoqbVPg+mo3VRz8wGiwmv7o504s0Vl5Ey8Ymc7ejk0
thhNwQ344F1jwT5FEwrLfQWRol4kAON01b661cYpOOqFOGOcXOs0EyzmC6Ss0oOt6N9z
EF6Io39kNR/YiGrNYjTsbPneu/AcjN5f8wKBnJe0zIMZD3p0RmLt3C22zK+g5yiKKiOu
XsJQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20161025;
h=x-gm-message-state:from:date:subject:message-id:to:mime-version
:content-id;
bh=B75ydhKnqy2peDN4+51CCFIdCiGWc8343EzLfz2yD+0=;
b=pYRlu9OwuFRAhij+WtKtyKNzIhhKZhBaEuPjHdOVoaNoX1HjzmnLstTTm+LgS6ugEu
c/LtyElrbzeu0YYtuRIJT4vl5OiAcBJmVkEMHBnVZYwE7Nxv6wV56k81eS5npBthfVT/
GyUbkSwr2TkBwVvddWVXKPjZpzQYv2sl9dXrwKR6zQetF1VkNLV0tcjBqyp9PCm6YOwN
DtzD4x6J6UBysXHSBI66Dhhk+u8CqNDpnwWgKbtGNj8QJb0wTZ379JjrQIKlKDk9WyDU
ppYtiH0zF+wD3Gu5doaaFnEaqGUy4xm+RuWTst4xRptMADtEfjlGDYmaWqTsQ0XlrjI2
xYsw==
X-Gm-Message-State: AHQUAuaNveztmUZ0asILBnB8a9A+f13D3qVb9norFJR45Y3Iw7ybLEiE
ynYTNyvcI5Y157hjA9iTOWXiRIjcLoo=
X-Google-Smtp-Source: AHgI3IaTYWFLT3LLTBv0gr35GOQMr/6SrDAvIjOmLPk33htq33EcH5gKtlu7bEZfRDhAUxYrBXxNrg==
X-Received: by 2002:a24:43d1:: with SMTP id s200mr8267021itb.118.1551624795173;
Sun, 03 Mar 2019 06:53:15 -0800 (PST)
Return-Path: relctisgerg@gmail.com
Received: from [192.168.1.4] ([184.17.202.177])
by smtp.gmail.com with ESMTPSA id u197sm1878165itb.9.2019.03.03.06.53.14
for &lt;relctisgerg@hotmail.com&gt;
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Sun, 03 Mar 2019 06:53:14 -0800 (PST)
From: Greg Sitcler &lt;relctisgerg@gmail.com&gt;
Date: Sun, 03 Mar 2019 09:53:14 -0500
Subject: Link Test
Message-Id: &lt;JR2UN9MAW6U4.JUF7IBVK1CJY2@localhost.localdomain&gt;
To: "relctisgerg@hotmail.com" &lt;relctisgerg@hotmail.com&gt;
Content-Type: text/html; charset="utf-8"
Content-Id: &lt;303UN9MAW6U4.2M032ASKI18S2@localhost.localdomain&gt;
X-Antivirus: Avast (VPS 190303-0, 03/03/2019), Outbound message
X-Antivirus-Status: Clean
X-IncomingHeaderCount: 18
X-MS-Exchange-Organization-ExpirationStartTime: 03 Mar 2019 14:53:16.1381
(UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id: 336c66fd-465d-4c2d-a90b-08d69fe7f7b1
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-Forefront-Antispam-Report: EFV:NLI;
X-MS-Exchange-Organization-AuthSource:
HE1EUR01FT029.eop-EUR01.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-UserLastLogonTime: 3/3/2019 2:49:05 PM
X-MS-Office365-Filtering-Correlation-Id: 336c66fd-465d-4c2d-a90b-08d69fe7f7b1
X-Microsoft-Antispam:
BCL:0;PCL:0;RULEID:(2390118)(5000111)(711020)(4605104)(610169)(650170)(651021)(8291501072);SRVR:HE1EUR01HT066;
X-MS-TrafficTypeDiagnostic: HE1EUR01HT066:
X-MS-Exchange-PUrlCount: 3
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 209.85.166.194
X-SID-PRA: RELCTISGERG@GMAIL.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 03 Mar 2019 14:53:16.1000
(UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 336c66fd-465d-4c2d-a90b-08d69fe7f7b1
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: HE1EUR01HT066
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.0414736
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1665.000
X-Microsoft-Antispam-Mailbox-Delivery:
abwl:1;rwl:0;ucf:0;jmr:0;ex:1;auth:1;dest:I;OFR:SenderInAddressBook;ENG:(5062000261)(5061607266)(5061608174)(4900095)(4920090)(6515079)(4950130)(560107);
X-Message-Info:
5vMbyqxGkdftSQwYatzi8jnM2+k4X/U62xTQ7SR9aZDKvo2c4lf9n7R2iJrOpu0xCB/acqpl3dV31Yts7SKfcdxVh9ExAeC/RvsqdcPc5qy/eyW9qPZkxjseVTwLy8B7ffFdlDB2g5U5zGUegvj12NrO6/L7ypT58UhGIsj+Mk3G47IDRP7EnOnogmQsam2PI9Qc9xtIf4S4bdA21Vb7+Q==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
kanTOwwClrh6E9IKjbZV+qAbvAhUk9t5pm/TXG/1YkwpoEvTpQ1S5VReim7BqwFA14b0oXCLY+nGcHLLSZELnuiMntDjgjCghElfhEiYlzQOn/eldIRyBUndZjielAI0QMtO5v/7gfxW/6dJFnsVy1n87DDArX3KRoec4sJgqZAI89nkI1Q+G006S1VKZPPQg5PpWNv8K6NhDDn0b7eeX+e++Qvf/5iUm+Dq1dLNTKAyQn/xZEQ8z1IaBKEk2ziP6LvB9avsu/SFqXjPQlkBm+Yk4kwItQyPA7yMvk4BbUO4Ub5zxiffLrinb4yVP/yF/eBwWcGY24+qoyYKa2L/WQrIbOsuhVaPm5qNcqbQ3bTfD7YgSMgc4x5XOSdxhvVcGMzQBy4zSuS8Z5CMQIWxAHLMpS3zk8k97LaFThoGEedgYIsInkCqYo8wl4kdsZYJBTXdUtea00fU1y4fGtEiIF24a39dfpGNsYAIEq6Med+ksS757qn5/cwTz5CWj3wnpikngoIyFlC5ZFaf+Se6SQnuGsSbfaX9h//Pe17VA4tnR62HpU+Ikr8VzNYt/Y+i6kMeNGCbyoOofC6CWeGvxJ2o84Jwrg4qQTTq+58hqUsVpi4PBXWjj2VtyGCcyR1FgHbq567Uc17DVONibjUiwb8+tdiqpGPe3ortueNdoBrxiCiKv/daoQzVpur4R9DMleWG/oHJxXGlJU8HuhYsxbiPLpa9EtY82/jqchz0dxl7lQLNlJd5fIvWubOGVTi0DD7XOWnbMQgiJHaRjBPQnjOlDRXwkBdCfHWYQ3LBBkAPKU2xEXDyMtC9dq6bkjWg
MIME-Version: 1.0

&lt;!doctype html&gt;&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;&lt;meta name="viewport" content="width=device-width"&gt;

&lt;title&gt;Ombi&lt;/title&gt;
&lt;style media="all" type="text/css"&gt;
@media all {
.btn-primary table td:hover {
background-color: #34495e !important;
}

.btn-primary a:hover {
background-color: #34495e !important;
border-color: #34495e !important;
}
}

@media all {
.btn-secondary a:hover {
border-color: #34495e !important;
color: #34495e !important;
}
}

@media only screen and (max-width: 620px) {
table[class=body] h1 {
font-size: 28px !important;
margin-bottom: 10px !important;
}

table[class=body] h2 {
font-size: 22px !important;
margin-bottom: 10px !important;
}

table[class=body] h3 {
font-size: 16px !important;
margin-bottom: 10px !important;
}

table[class=body] p,
table[class=body] ul,
table[class=body] ol,
table[class=body] td,
table[class=body] span,
table[class=body] a {
font-size: 16px !important;
}

table[class=body] .wrapper,
table[class=body] .article {
padding: 10px !important;
}

table[class=body] .content {
padding: 0 !important;
}

table[class=body] .container {
padding: 0 !important;
width: 100% !important;
}

table[class=body] .header {
margin-bottom: 10px !important;
}

table[class=body] .main {
border-left-width: 0 !important;
border-radius: 0 !important;
border-right-width: 0 !important;
}

table[class=body] .btn table {
width: 100% !important;
}

table[class=body] .btn a {
width: 100% !important;
}

table[class=body] .img-responsive {
height: auto !important;
max-width: 100% !important;
width: auto !important;
}

table[class=body] .alert td {
border-radius: 0 !important;
padding: 10px !important;
}

table[class=body] .span-2,
table[class=body] .span-3 {
max-width: none !important;
width: 100% !important;
}

table[class=body] .receipt {
width: 100% !important;
}
}

@media all {
.ExternalClass {
width: 100%;
}

.ExternalClass,
.ExternalClass p,
.ExternalClass span,
.ExternalClass font,
.ExternalClass td,
.ExternalClass div {
line-height: 100%;
}

.apple-link a {
color: inherit !important;
font-family: inherit !important;
font-size: inherit !important;
font-weight: inherit !important;
line-height: inherit !important;
text-decoration: none !important;
}
}
&lt;/style&gt;
&lt;/head&gt;
&lt;body class="" style="font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #f6f6f6; margin: 0; padding: 0;"&gt;
&lt;table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;" width="100%" bgcolor="#f6f6f6"&gt;
&lt;tr&gt;
&lt;td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top"&gt;&nbsp;&lt;/td&gt;
&lt;td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto !important; max-width: 580px; padding: 10px; width: 580px;" width="580" valign="top"&gt;
&lt;div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;"&gt;

&lt;!-- START CENTERED WHITE CONTAINER --&gt;
&lt;span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;"&gt;Ombi&lt;/span&gt;
&lt;table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #fff; border-radius: 3px;" width="100%"&gt;

&lt;!-- START MAIN CONTENT AREA --&gt;
&lt;tr&gt;
&lt;td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;" valign="top"&gt;
&lt;table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%"&gt;
&lt;tr&gt;
&lt;td align="center"&gt;
&lt;img src="http://i.imgur.com/7pqVq7W.png" alt="Ombi logo" width="400px" text-align="center"&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top"&gt;
&lt;p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"&gt;&lt;html&gt;
&lt;body&gt;Hello!
&lt;br&gt;
&lt;br&gt;
You have been invited to use Ombi where you can request conted to be added to Your friendly neighborhood Plex server! 
&lt;br&gt;
&lt;br&gt;
You can login here: &lt;a href="ombimyplex.hopto.org:5000"&gt;ombimyplex.hopto.org:5000&lt;/a&gt;
&lt;br&gt;
&lt;br&gt;
Greg Sitcler
&lt;div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"&gt;&lt;br&gt;
&lt;table style="border-top: 1px solid #D3D4DE;"&gt;
&lt;tr&gt;
&lt;td style="width: 55px; padding-top: 13px;"&gt;&lt;a href="https://www.avast.com/sig-email?utm_medium=email&amp;utm_source=link&amp;utm_campaign=sig-email&amp;utm_content=emailclient&amp;utm_term=icon" target="_blank"&gt;&lt;img src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif" alt="" width="46" height="29" style="width: 46px; height: 29px;"&gt;&lt;/a&gt;&lt;/td&gt;
&lt;td style="width: 470px; padding-top: 12px; color: #41424e; font-size: 13px; font-family: Arial, Helvetica, sans-serif; line-height: 18px;"&gt;Virus-free. &lt;a href="https://www.avast.com/sig-email?utm_medium=email&amp;utm_source=link&amp;utm_campaign=sig-email&amp;utm_content=emailclient&amp;utm_term=link" target="_blank" style="color: #4453ea;"&gt;www.avast.com&lt;/a&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;&lt;a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"&gt; &lt;/a&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;&lt;/p&gt;

&lt;/td&gt;
&lt;/tr&gt;

&lt;/table&gt;
&lt;/td&gt;
&lt;/tr&gt;

&lt;!-- END MAIN CONTENT AREA --&gt;
&lt;/table&gt;

&lt;!-- START FOOTER --&gt;
&lt;div class="footer" style="clear: both; padding-top: 10px; text-align: center; width: 100%;"&gt;
&lt;table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%"&gt;
&lt;tr&gt;
&lt;td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-top: 10px; padding-bottom: 10px; font-size: 12px; color: #999999; text-align: center;" valign="top" align="center"&gt;
Powered by &lt;a href="https://github.com/tidusjar/Ombi" style="color: #999999; font-size: 12px; text-align: center; text-decoration: underline;"&gt;Ombi&lt;/a&gt; Sunday, March 3, 2019 9:53 AM
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;
&lt;/div&gt;

&lt;!-- END FOOTER --&gt;
&lt;!-- END CENTERED WHITE CONTAINER --&gt;
&lt;/div&gt;
&lt;/td&gt;
&lt;td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top"&gt;&nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by relctisgerg** [comment]
I figured it out
