### ISSUE TITLE
Application URL is adding token info

### ISSUE THREAD

**Issue by sodajim** [tidusjar/Ombi#2865]
**Describe the bug**
Whenever a user tries to use the reset their password link the Application URL adds the following "/token?token=" and keeps adding this every time someone clicks on the reset password link.

**To Reproduce**
1.User visits application URL
2. User clicks on reset password link
3. User enters their email address and hits reset password
4. password reset fails because URL is not correct and it displays "Invalid Token"

**Screenshots**
![image](https://user-images.githubusercontent.com/48231895/53778698-45141680-3ec3-11e9-81cf-e1caf53ee1b8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2

**Ombi Version (please complete the following information):**
 - Version 3.0.4256

- Media Server Plex

**Additional context**
Thanks for your work!

**Comment by tidusjar** [comment]
Please provide the application URL you have entered? Just the format will
be fine

**Comment by sodajim** [comment]
I have tried a few.
http://media.myserver.xyz
http://media.myserver.xyz/
http://media.myserver.xyz/ombi
http://media.myserver.xyz/ombi/

**Comment by tidusjar** [comment]
I cannot seem to reproduce it. Is this for a ombi user?

**Comment by sodajim** [comment]
I was able to reproduce it with a local user and a plex imported user.

**Comment by Generalnoob** [comment]
For me it happens everytime I try to send a password reset link, hope this helps

**Comment by Generalnoob** [comment]
will this be addressed soon please

**Comment by tidusjar** [comment]
Please keep in mind that Ombi is not my primary job, I do not get paid to support and maintain Ombi. I currently have a full time job, 2 year old child, wife and puppy at home so my life is pretty busy without Ombi.

Any free time that I have is dedicated to Ombi and there are many many things to do on this project. So if I have not yet got around to fixing this then apologies, but I'm the only dev and I'm only human :smile:

**Comment by Generalnoob** [comment]
ok bud just checking :)

**Comment by byusinger84** [comment]
This is also happening to me on Windows. Only seems to happen with Plex users.

**Comment by SiGmAX666** [comment]
I don't know how to debug C# webapps and I've never coded in C#, but I suspect the issue relates to how [IdentityController.cs](https://github.com/tidusjar/Ombi/blob/9940156fea2e4220681df126f3272ed069b86940/src/Ombi/Controllers/IdentityController.cs#L778) calls `AddToUrl` at line 778, and then what `AddToUrl` does. It appears that `AddToUrl` within [CustomizationSettings.cs](https://github.com/tidusjar/Ombi/blob/9940156fea2e4220681df126f3272ed069b86940/src/Ombi.Settings/Settings/Models/CustomizationSettings.cs#L15) is actually modifying `customizationSettings.ApplicationUrl` vs returning the `ApplicationUrl` plus the string passed to it (`part`). 

[IdentityController.cs](https://github.com/tidusjar/Ombi/blob/9940156fea2e4220681df126f3272ed069b86940/src/Ombi/Controllers/IdentityController.cs#L778) Lines 778-779:

```
customizationSettings.AddToUrl("/token?token=");
var url = customizationSettings.ApplicationUrl;
```

[CustomizationSettings.cs](https://github.com/tidusjar/Ombi/blob/9940156fea2e4220681df126f3272ed069b86940/src/Ombi.Settings/Settings/Models/CustomizationSettings.cs#L15)
```
public void AddToUrl(string part)
{
    if (string.IsNullOrEmpty(ApplicationUrl))
    {
        ApplicationUrl = part;
    }

    if (ApplicationUrl.EndsWith("/"))
    {
        ApplicationUrl.Remove(ApplicationUrl.Length - 1);
    }
    if (!part.StartsWith("/"))
    {
        part = "/" + part;
    }
    ApplicationUrl = ApplicationUrl + part;
}
```
I think `AddToUrl` should be returning a concatenated string, not updating the `ApplicationUrl` object. But I could be misunderstanding what is happening somewhere else in the code!

**Comment by tidusjar** [comment]
Thanks for the investigation, you are probably correct, at some point it seems that it must be persisted back to the database.

**Comment by vsc55** [comment]
Hi,
I wanted to add a note.
It seems some Frontend failure, since "/ token? Token =" is only added in the UI.
If you look for the ApplicationUrl option in the database, it appears correctly.
