### ISSUE TITLE
Add option to change root folder upon request

### ISSUE THREAD

**Issue by b-rockx** [tidusjar/Ombi#287]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.7.4
#### Operating System:

N/A
#### Mono Version:

N/A
#### Applicable Logs (from `/logs/` directory or the Admin page):

N/A

```
Logs go here (Please make sure you remove any personal information from the logs)
```

N/A
#### Reproduction Steps:

When requesting a show, give the option to change the root directory (drop down, based on pre-set folders under admin). 

Such as 
Cartoons
Anime
Series

This will help with sorting various shows.  

--EDIT:
Also add ability to include tags when requesting. (The tags that are used by sonarr, under settings, indexers, restrictions in the advanced area)

**Comment by tidusjar** [comment]
See this: https://www.reddit.com/r/PleX/comments/4kvkjc/plex_requests_net_update_17_user_notifications/d3ojsx4

and this: https://www.reddit.com/r/PleX/comments/4kvkjc/plex_requests_net_update_17_user_notifications/d3pmilo

**Comment by tidusjar** [comment]
When approval is not enabled. Allow the user to specify a 'category'

**Comment by b-rockx** [comment]
Thanks for working on this. Tags in Sonarr allow you to set specific criteria for shows, such as a release group or setting it to english only subs. I use this specifically for anime. From what I have experienced, you add the tag after you add the series (when doing so in sonarr).

**Comment by gold007eye** [comment]
I agree in your statement on #289 about Admin should decide this vs the User.  Most of my users wouldn't necessarily know what should go where (especially when it comes to "Classics"). lol

**Comment by tidusjar** [comment]
@gold007eye I'll add it as an optional feature. Since I know not everyone will use it

**Comment by gold007eye** [comment]
@tidusjar thanks :+1:

**Comment by b-rockx** [comment]
Has this been added? If so where is it?

Thanks!

**Comment by tidusjar** [comment]
This has not been added yet unfortunately. There are some higher priority items being worked on e.g. Requesting individual TV Episodes. 

If you take a look at the github labels you can see it's in a planned state. 
You can see everything that is being worked on here: https://waffle.io/tidusjar/PlexRequests.Net

**Comment by Rsslone** [comment]
+1
This actually will be really useful. Anime watchers as myself and a couple of my clients need special care to request a item. Since generally anime is a separate library I need to either delete the request and manually set it in sonnar or approve the request then change the directory, tag, and type of show in sonnar.

**Comment by b-rockx** [comment]
Awesome looks like a variation of this was added!! Is there any way we can get this setup so we don't have to approve it? I'd like the ability to just have tabs next to TV or have a drop down when requesting.
