### ISSUE TITLE
Custom Logo sizing issue on Landing Page with ultrawide monitors

### ISSUE THREAD

**Issue by Berserkir-Wolf** [tidusjar/Ombi#2870]
**Describe the bug**
Custom icon on landing page fills the screen and pushes content out-of-bounds on ultrawide displays.
Changing to a lower-resolution file just causes the logo to pixelate while maintaining the same size on screen.
Resizing the window to not take advantage of the full monitor makes all content appear as expected.

**To Reproduce**
1. Enable landing page
2. Add a Custom Logo
3. Logout and view landing page on ultrawide display

**Expected behavior**
The custom logo and landing page should either scale to fit page height or cause the creation of a scroll-bar.

**Screenshots**
[Fullscreen on monitor](https://i.imgur.com/G5GtMnk.png)
[Half-sized window](https://i.imgur.com/v7AmeoP.png)

**Logs (Logs directory where Ombi is located)**
Not applicable

**Desktop (please complete the following information):**
 - OS (host): [Windows Server 2012 R2 Essentials]
 - Access type:  [IIS reverse proxy]

**Ombi Version (please complete the following information):**
 - Version [3.0.4256]
 - Branch: [master]
 - Media Server [Plex]

**Additional context**
 - Monitor resolution: [2560*1080]
 - Logo resolution: [800*800]
 - [Landing page](https://media.berserkir.net/ombi/landingpage)

**Comment by tidusjar** [comment]
Thanks for the report. I am currently not going to fix this issue as the page is due to be reworked.


Currently you can use the Custom CSS option in Ombi to apply a custom height yourself
