### ISSUE TITLE
Trying to request "After Life" tv show

### ISSUE THREAD

**Issue by goldenpipes** [tidusjar/Ombi#2871]
**Describe the bug**
when trying to request that specific show we get this error:

![image](https://user-images.githubusercontent.com/6140137/53932857-6f9bd600-4061-11e9-9ba8-2ccebacdf67a.png)

**To Reproduce**

**Expected behavior**
the show to request and add the series to sonarr.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
nothing sticks out in the log

**Desktop (please complete the following information):**
unraid docker
**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]
Ombi v3.0.4256

**Additional context**

**Comment by tidusjar** [comment]
This seems to be an issue with TheTvDb.

It seems that TVMaze is reporting the TVDbId to be 351064 but infact it looks like the show doesn't exist https://www.thetvdb.com/series/afterlifenetflix/seasons/all

Not much I can do about this currently
