### ISSUE TITLE
token?token=/token?token= when setting url?

### ISSUE THREAD

**Issue by Generalnoob** [tidusjar/Ombi#2873]
**Describe the bug**
Hi there,
When i set up the customization url it adds this token?token=/token?token= everything i send a password reset so far its like this

http://urlinuse:portal/token?token=/token?token=token?token=/token?token=token?token=/token?token=token?token=/token?token=token?token=/token?token=token?token=/token?token=token?token=/token?token=token?token=/token?token=

**Comment by tidusjar** [comment]
Duplicate of #2865

**Comment by tidusjar** [comment]
Please fill in the template when raising an issue in the future
