### ISSUE TITLE
Include request id as notification variable

### ISSUE THREAD

**Issue by Autotonic** [tidusjar/Ombi#2874]
Mainly for Discord webhook usage.
This would simply using a bot in Discord to approve a request.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

Please see this page for the new variable https://github.com/tidusjar/Ombi/wiki/Notification-Template-Variables

**Comment by wymangr** [comment]
@tidusjar Stupid question here, but has this been added to any builds yet? I'm on the latest build (version: 3.0.4892) and when I use the variable {RequestId} in my "New Request" message, it doesn't work. Am I missing something?

**Comment by tidusjar** [comment]
It should work. If it doesn't please raise a issue
