### ISSUE TITLE
Request: Add Artist support for Lidarr

### ISSUE THREAD

**Issue by bobloadmire** [tidusjar/Ombi#2875]
Currently, there is no option to add artist, and therefore add all associated albums.

**Comment by tidusjar** [comment]
Correct. I am waiting for the Lidarr team to add an additional API so this can be done

**Comment by RandomNinjaAtk** [comment]
So after chatting with the lidarr devs this is possible via api currently.

Basically I was told the front end (web interface) currently adds artists via api call. So this is just a lack of documentation.

Here is the specific file that adds the artist to lidarr:
https://github.com/lidarr/Lidarr/blob/8b860bcb8284dad1da004a46ec77f6442bf35f2b/frontend/src/Store/Actions/addArtistActions.js

Looks like its performing a "POST" command with some additional data.

**Comment by tidusjar** [comment]
This is a perfect feature for v4

**Comment by ta264** [comment]
Happy to assist with any API questions on the lidarr discord

**Comment by tidusjar** [comment]
The API part is the simple bit

I just need to work out how I'm going to do it in ombi from a request point of view. Everything currently is based off albums, so you approve album requests and not artists.
