### ISSUE TITLE
[Feature] Add Series Without Searching

### ISSUE THREAD

**Issue by halorrr** [tidusjar/Ombi#2879]
Sometimes a user requests an older show that I would rather manually handle the torrent searching (usually to search a private tracker for a freeleech collection of what is out so far). Currently if I approve a request it gets added to Sonarr and Sonarr immediately starts searching for the show, sonarr then starts to queue up a ton of torrents on its' own. 

I'd like an option to approve a show so it is monitored, but not instigate a search immediately (the same way it works if I add a new show directly in Sonarr). Maybe have a dropdown from the Approve button to "Approve Without Search"?

**Comment by tidusjar** [comment]
Press the advanced button in the sonarr settings. It's already there

**Comment by halorrr** [comment]
Admittedly I missed that setting, but my request was looking to be able to have this option on a per request basis. Some requests I'm happy to let Sonarr do its' thing, some I'd rather manually deal with.

**Comment by tidusjar** [comment]
Unfortunately there is currently not an option per request.

Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
