### ISSUE TITLE
Lots of 400 Bad Request on almost all Ombi pages

### ISSUE THREAD

**Issue by rcdailey** [tidusjar/Ombi#2881]
**Describe the bug**

When I go to the main page of Ombi (defaults to the Search tab), I get several of these errors in the Firefox console:

```
ERROR 
Object { headers: {…}, status: 400, statusText: "Bad Request", url: "https://domain.com/ombi/api/v1/search/Movie/info", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://domain.com/ombi/api/v1/search/Movie/info: 400 Bad Request", error: null }
core.js:14597
```

Using Firefox 66.0b14 (64-bit)

**To Reproduce**

1. Load up the main page, defaults to search, open Firefox console (F12) to view the errors

**Expected behavior**

I expect no errors in console. These errors explain why many functions in Ombi are not working for me, such as the inability to save general ombi settings in the administrative control panel.

**Screenshots**

![image](https://user-images.githubusercontent.com/1768054/54096878-b64c4180-437b-11e9-9009-82fe8dcee76c.png)

**Logs (Logs directory where Ombi is located)**

* No server side logs (Logs directory is empty)
* No NGINX logs indicating failures (reverse proxy)

**Desktop (please complete the following information):**
 - OS: Ubuntu using Docker image: `linuxserver/ombi`

**Ombi Version (please complete the following information):**
- Media Server: Plex

| | |
-- | --
Version | 3.0.4256
Branch | master
Github | https://github.com/tidusjar/Ombi
Discord | https://discord.gg/Sa7wNWb
Reddit | https://www.reddit.com/r/Ombi/
Issues | https://github.com/tidusjar/Ombi/issues
Wiki | https://github.com/tidusjar/Ombi/wiki
OS Architecture | X64
OS Description | Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
Process Architecture | X64
Application Base Path | /opt/ombi

**Comment by tidusjar** [comment]
That's unusual, does it happen every time?

**Comment by xunil75** [comment]
I don't seem to see on which Ombi Version you are! I made a check on my Ombi and could not reproduce your error, in fact there's not a single error on the Search page. Could be a Reverse Proxy issue on your side? Can you post your Nginx config please?

**Comment by rcdailey** [comment]
I've included my NGINX proxy config below. I boiled it down a bit. I have other subfolders mapping to other services (such as `/nzbget` mapping to NZBget). This is just the configuration relevant to Ombi itself.

```
server {
    listen 443 ssl http2;
    server_name domain.com;
    client_max_body_size 0;
    resolver 127.0.0.11 valid=30s;

    # Security headers
    add_header Content-Security-Policy "upgrade-insecure-requests";
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-UA-Compatible "IE=Edge" always;
    add_header Cache-Control "no-transform" always;
    add_header Referrer-Policy "same-origin" always;

    # session settings
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # Diffie-Hellman parameter for DHE cipher suites
    ssl_dhparam /config/nginx/dhparams.pem;

    # ssl certs
    ssl_certificate /config/keys/letsencrypt/fullchain.pem;
    ssl_certificate_key /config/keys/letsencrypt/privkey.pem;

    # protocols
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # Allow websockets on all servers
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Basic Proxy Config
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Ssl on;

    location = / {
        return 418;
    }

    set $upstream_ombi http://ombi:3579;

    location /ombi {
        #auth_request /organizr/auth-998;
        proxy_pass $upstream_ombi;
    }
}
```

**Comment by xunil75** [comment]
Please replace this code with your **location /ombi {** and try again. Make sure you restart Nginx!

```
location /ombi/ {
    proxy_pass http://127.0.0.1:3579;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout  90;
    proxy_redirect http://127.0.0.1:3579 https://$host;
}
```

**Comment by rcdailey** [comment]
Thanks to your sample, I was able to determine the cause of the errors. It's because of this NGINX config:

```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

This enables websockets, but my understanding is that if a web application does not use them, then these headers are harmless. Is that not the case? Why do these cause problems with Ombi?

**Comment by rcdailey** [comment]
Another update. Apparently the connection shouldn't be upgraded by the reverse proxy if the client never requested it. The NGINX documentation explains how to set this up here: http://nginx.org/en/docs/http/websocket.html

Example they provide:

```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        ...

        location /chat/ {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
```

After changing the `Connection` header to use this map, everything is working fine and the errors are no longer seen. Before I close this issue, @tidusjar do you feel that this is 100% a reverse proxy configuration issue? Or do you see anything about the HTTP 400 involving Websockets that you'd like to make some code changes for? If the former, please feel free to close.

Thanks again to you both for your time.

**Comment by tidusjar** [comment]
Yeah I was not expecting this to be a code issue otherwise it would be a lot more widespread. 

So it being an proxy issue makes sense. 

Nice investigation guys.
