### ISSUE TITLE
Mixed Content HTTPS/HTTP for Lidarr album art.

### ISSUE THREAD

**Issue by escservices** [tidusjar/Ombi#2884]
OS: Windows Server 2016
Version: 3.0.4256
Branch: Master

When searching for or reviewing lidarr music requests it's pulling down non https fanart.tv images.  Movies and TV shows appear to be unaffected just music.  
![image](https://user-images.githubusercontent.com/1287511/54159535-92443b00-4423-11e9-9739-aa0ccd6214fc.png)

Also when trying to remove a music request it throws this red "Cannot read property 'subscribe' error and nothing happens on the web ui.  But once the page is refreshed the item is removed. Only happens to music as well. 

![image](https://user-images.githubusercontent.com/1287511/54159547-9b350c80-4423-11e9-98d9-abfd932fde06.png)

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
