### ISSUE TITLE
Feature Emby select which library to monitor

### ISSUE THREAD

**Issue by JosefineJensen** [tidusjar/Ombi#2885]
It would be nice if it was possible to select which library to monitor for emby, like the feature that exist for plex servers

**Comment by xunil75** [comment]
Please post it under [Feathub](http://feathub.com/tidusjar/Ombi) if doesn’t exist yet.

Thanks!

**Comment by tidusjar** [comment]
@xunil75 Thanks but I asked him to post it here :)

**Comment by tidusjar** [comment]
Duplicate of https://github.com/tidusjar/Ombi/issues/2389
