### ISSUE TITLE
Unable to remove PushBullet access token

### ISSUE THREAD

**Issue by Technifocal** [tidusjar/Ombi#2890]
**Describe the bug**
The administrator is unable to remove the access token for PushBullet under `/Settings/Pushbullet`

**To Reproduce**
1. Visit `/Settings/Pushbullet`
2. If an access token exists, skip to step \#5
3. Add an access token
4. Click "Submit"
5. Remove the access token
6. The "Submit" button disables itself and the form states "The Access Token is required".

**Expected behavior**
  - Be able to delete the access token if `enable` isn't checked.

**Screenshots**
  - ![Image](https://user-images.githubusercontent.com/20205745/54394185-1278d380-46a4-11e9-9e28-264957592093.png)

**Logs (Logs directory where Ombi is located)**
  - N/A

**Desktop (please complete the following information):**
  - Chromium 73.0.3683.75

**Ombi Version (please complete the following information):**
  - Ombi 3.0.4256

**Additional context**
N/A

**Comment by tidusjar** [comment]
Thanks for the bug.

In the meantime if you want to remove it you can enter anything in the field.

I'm not going to fix this as the whole settings area is being redesigned right now for V4.
