### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by McGriddle** [tidusjar/Ombi#2893]
Loving Ombi. Its great for non-technical people as a nice frontend to all the various backend-frontends(?). Would Ombi be a good place to display a calendar? Like the radarr and sonarr calendars. I know you can export ical links with those services, but IMHO those are technical details. Thanks for the consideration.

Dev Comment:
Calendar view,
Show Movies, Episodes and Album release dates for Requests? Or only subscribed? Need to think

**Comment by tidusjar** [comment]
I agree, this would fit perfectly into V4.

Now the only thing I need to think about is what to show on there.

I think that we should have the following options:
Show All requests
Show My Requests

Once one of those filters is selected, the calendar will always default to that preference.

There will also be options to Show Episodes, Movies and Albums that you could toggle on and off.

Each calendar entry will be color coded to match it's request status e.g. Processing, Not approved, available.

Opinions?

**Comment by clambert11** [comment]
I'm all for this.  It would be a great tool for the users.  I'm not sure how much you can borrow from Organizr but what they have done is pretty damn perfect. Descriptions with ratings and artwork, color coding, filtering, and date ranges.  

Is the calendar just going to interface with Ombi requests?  Or is it going to use the Sonarr / Radarr calendar too?  The majority of my catalog was setup before I started using Ombi.  It would be nice if those showed in the calendar as well.

There should also be an option to disable the calendar for those who truly don't want it.

**Comment by tidusjar** [comment]
So I was actually implementing and discussing this on the stream last night.

I've not seen Org's calendar but i will check it out. The responses were mixed, and that was between people that use Org and people that don't.
So the plan is to display requests release dates on the calendar, with color coding according to it's status.

And there will be an option to disable.

**Comment by McGriddle** [comment]
That makes sense for movies. For shows it seems more complicated (at least to me). If I have a show that is 100% available for 2 seasons, then the show would be marked as available. Next year when season 3 is announced and starts airing would a new request have to be made?

**Comment by tidusjar** [comment]
Shows are not going to appear on the Calendar, Episodes will appear!

**Comment by lixenstrand** [comment]
With this, could you also manage to put the date for blueray realise next to the movie, so you don't have to go in to the calender to see approx. When a movie will become available. I've mentioned it before but just wanted to put it forward again 😊
