### ISSUE TITLE
Question: How does Plex OAuth work?

### ISSUE THREAD

**Issue by AngellusMortis** [tidusjar/Ombi#2894]
So it seems like you have cracked how to do Plex OAuth and not need to collect the user's username/email and password. How does it work?

I tried following the code, but unfortunately I am not very versed in C#. I am pretty fimilar with OAuth concepts, mostly need to know:

1. How do I get a client ID/client secret? Do I need both of them?
2. What are the parameters for the authorization URL? I see `code`, `context`, `clientID`, but what does `code` and `context` do and what do they need to be?
3. After authenticating, how are you getting the user details back from Plex? Is it some type of authorization code you pass back to Plex?

**Comment by Jbond312** [comment]
I've been playing around with this myself recently. I might not have everything covered but my main understanding is this:

1. You generate your own ClientId. This is to identify yourself as a client for current and future requests to ensure the correct client is requesting the information.
2. The remaining `X-Plex-` headers appear to be additional metadata about the client making the request. You can usually see this when you log into Plex and look at your 'Authorised Devices', you'll see the same metadata showing to identify a specific device that has authenticated with a Plex account.
3. You start by creating a 'Pin' (e.g. [POST-CreatePin](https://plex.tv/api/v2/pins?strong=true)) This grants you a temporary (30 min) token and you'll need the `code` and `id` from its response and also take note that the `authToken` is null.
4. Navigate to the Plex auth login page using your code, clientid and remaining headers and optional forwardUrl. For example:
https://app.plex.tv/auth#?forwardUrl=http://google.com&clientID=123456789&code=abcdef123456
5. When navigated to that URL the user is prompted for their credentials.
6. Once valid credentials have been entered, a PUT request is made to the `Pins` resource to update it with an access token.
7. If you now make a `GET` request to the `Pins` resource with your `PinId` you received when creating the pin (e.g. [GET-GetPin](https://plex.tv/api/v2/pins/12345)) along with your `X-Plex-Client-Identifier`. You should get back a response that now has the `authToken` populated.
8. Use the `authToken` you receive as the `X-Plex-Token` header in requests to access account information for that user. e.g. https://plex.tv/users/account.json

Others might have a bit more information about it but it should get you started.

**Comment by AngellusMortis** [comment]
Sweet. Thanks @Jbond312. I got it working. Here is the full flow to summarize for anyone else.

### Step 1

Make a `POST` to https://plex.tv/api/v2/pins.json?strong=true to get an authentication code
```
X-Plex-Product: Name
X-Plex-Platform: Web
X-Plex-Device: Name (Web)
X-Plex-Client-Identifier: client-id
```
* `Name` - will be the value displayed to the end user when they are asked to log in for Plex.
* `client-id` - can be anything. This should be considered a secret value.

You will get back a response like the following:
```
{
    "id": #########,
    "code": "authentication-code",
    "trusted": false,
    "clientIdentifier": "client-id",
    "location": {
        "code": "US",
        "country": "United States",
        "city": "City",
        "time_zone": "America/New_York",
        "postal_code": "zip_code",
        "subdivisions": "state",
        "coordinates": "lat, long"
    },
    "expiresIn": 1799,
    "createdAt": "2019-03-28T00:56:17.247Z",
    "expiresAt": "2019-03-28T01:26:17.245Z",
    "authToken": null
}
```

* `client-id` - will be the value you passed in. `code` is your authentication code you need for the next step. 
* `id` - will be a value you need for step 3.

### Step 2

Redirect the URL to the following URL:
https://app.plex.tv/auth#?context[device][product]=Name&context[device][environment]=bundled&context[device][layout]=desktop&context[device][platform]=Web&context[device][device]=Name%20(Web)&clientID=client-id&forwardUrl=https://callback.domain&code=authentication-code

* `context[device][product]`, `context[device][platform]`, and `context[device][device]` - should match the plaform/product/device headers from above.
* `clientID` - your client ID secret you choose. 
* `forwardURL` - location for Plex to redirect the user's browser to. Optional, but super useful to make a call back to your back end to know when to do step 3.
* `code` - your authentication code from Step 1

### Step 3

AFTER the user has authenticated, you need to make a `GET` to https://plex.tv/api/v2/pins/<id>.json where `id` is the `id` value from Step 1. You will also need to pass your `client-id` again as a header.

```
X-Plex-Client-Identifier: client-id
```

You should get a response similar to the following:

```
{
    "id": #########,
    "code": "authentication-code",
    "trusted": false,
    "clientIdentifier": "client-id",
    "location": {
        "code": "US",
        "country": "United States",
        "city": "City",
        "time_zone": "America/New_York",
        "postal_code": "zip_code",
        "subdivisions": "state",
        "coordinates": "lat, long"
    },
    "expiresIn": 1799,
    "createdAt": "2019-03-28T00:56:17.247Z",
    "expiresAt": "2019-03-28T01:26:17.245Z",
    "authToken": "authentication-token"
}
```

This the same response from Step 1, **except** `authToken` is not empty now. This is the value you need.

### Step 4

Last step. Call back to Plex and get data about the user. You need to make a `GET` to https://plex.tv/users/account.json with `authentication-token` in the header.

```
X-Plex-Token: authentication-token
```

You should get a response like the following:

```
{
    "user": {
        "id": ######,
        "uuid": "uuid",
        "email": "user@example.com",
        "joined_at": "2014-01-22T21:48:35.000Z",
        "username": "username",
        "title": "username",
        "thumb": "https://plex.tv/users/uuid/avatar",
        "hasPassword": true,
        "authToken": "authentication-token",
        "authentication_token": "authentication-token",
        "subscription": {
            "active": true,
            "status": "Active",
            "plan": "lifetime",
            "features": [ ... ]
        },
        "roles": {
            "roles": [
                "plexpass"
            ]
        },
        "entitlements": [ ... ],
        "confirmedAt": "2014-01-22T23:08:20.000Z",
        "forumId": null
    }
}
```

**Comment by cbackas** [comment]
@AngellusMortis step #3 you might want to edit it to make the GET url more clear. The 'id' is left out before the .json and added a bit of confusion

**Comment by yonderbread** [comment]
Thank you so much for this, it's really difficult to find resources online that document the Plex API and this was extremely helpful
