### ISSUE TITLE
Posters not displaying in results

### ISSUE THREAD

**Issue by silkyclouds** [tidusjar/Ombi#2895]
**Describe the bug**
When searching for movies in ombi, absolutely no picture / poster is displayed. 
Tried this from several devices, and user accounts, same issue happens. 

**To Reproduce**
Open ombi
Search for a movie

**Expected behavior**
See the posters

**Screenshots**
https://www.screencast.com/t/uYJacOEHC

**Logs (Logs directory where Ombi is located)**
I'm getting a lot of these errors but I'm usure if they are linked to the issue : 

https://pastebin.com/ACrRMRFs

**Desktop (please complete the following information):**
Ubuntu server 18.04 headless

**Ombi Version (please complete the following information):**

Application Version: | 2.2.1678
-- | --
OS: | Mono
System Version: | 5.8.0.127 (tarball Wed Feb 21 16:44:45 UTC 2018)
Branch: | Stable
Media player : plex

**Additional context**
FYI, requesting movies works and does show up in radarr. There's really only the covers not displaying. 

THANKS !!! :)

**Comment by tidusjar** [comment]
V2 is no longer supported. Please upgrade to V3.
