### ISSUE TITLE
install ombi without sudo ? 

### ISSUE THREAD

**Issue by silkyclouds** [tidusjar/Ombi#2896]
hey there,

I've just created a ticket but was replied that I was using V2 which is not supported anymore. 

Problem is that I'm using a seedhost box on which I don't have root access. And they are not willing to upgrade ombi to V3... :( 

Is there any way to install ombi on my box without having root access? Any tutorial would be highly appreciated. 

thanks a lot !!!!

**Comment by tidusjar** [comment]
Hello,

The main question would be, why are they not willing to update their Ombi version, since V2 has not been supported since 4th March 2018 (over a year ago).

There are many tutorials on the Wiki on how to install, but I am unsure what type of access you would require.

**Comment by silkyclouds** [comment]
yeah...well... this is their answer :  

"Dear customer,
Unfortunately at this moment we don't offer latest ombi version. We need to update whole installation script for do it.
At this moment you can try to install it yourself via SSH by user."

**Comment by tidusjar** [comment]
I don't know who your provider are, but that doesn't seem great. I guess they must only be a small team without much capacity. 

Anyway, so you have SSH access, to I guess follow a guide in the wiki. If you run into issues jump on discord, i'm pretty sure some of the guys on there would have done something similar. I'm a linux noob so I wouldn't be able to help much with the installation.
