### ISSUE TITLE
Option to disable translation

### ISSUE THREAD

**Issue by Derkades** [tidusjar/Ombi#2902]
I'd like an option to globally disable translations. Translated text is often longer than the English text, which causes UI issues.

**Comment by tidusjar** [comment]
Use the custom CSS to hide the option to change language. 

But language is also inferred from browser settings. 

I'm not planning to add an option to disable this.

**Comment by Derkades** [comment]
Hiding the language change option will do the opposite of what I want, it will keep me from changing my language back to English and won't affect the default language.
