### ISSUE TITLE
Searching TV Shows is Broken in the API

### ISSUE THREAD

**Issue by AlphaHMD** [tidusjar/Ombi#2904]
**Describe the bug**
When you search for a TV show in the API, the keys "approved", "requested", and "available" all come back as false regardless of whether the show is in your library or not. Shows that show as available in the Ombi dashboard come back as unavailable when called from the API. This also affects the keys "fullyAvailable" and "partlyAvailable", which also return as false.

This only affects TV Shows, as movies work just fine. It also doesn't show any season requests for the show either.

**To Reproduce**
Call the API from /api/v1/Search/tv/TvShowName using an API Key or JWT Bearer

**Expected behavior**
The API should return the current status of the show as well as the requests that have been made for it.

**Screenshots**
![Postman_3rA338SXPX](https://user-images.githubusercontent.com/22331737/55051857-4a313500-502d-11e9-8ba3-636630d87cf1.png)
![mstsc_ljeIURq3mS](https://user-images.githubusercontent.com/22331737/55051894-71880200-502d-11e9-8834-f29aac05c5dd.png)

**Logs (Logs directory where Ombi is located)**
I've looked through the logs but nothing stands out.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256
- Media Server: Plex

**Additional context**
This IS fixed in the v4 branch. It's still broken in the v1 API, but the V2 API does not have these issues. I don't know what change was made that fixed it there.

**Comment by tidusjar** [comment]
Your UI is showing available?

**Comment by AlphaHMD** [comment]
> 
> 
> Your UI is showing available?

Right but if you take a look at the first screenshot, the API is showing it as unavailable. That's a response from the API when using the /api/v1/Search/tv endpoint. It should be showing available:true, fullyAvailable:true, and partlyAvailable:true. Instead the data is all false.

**Comment by tidusjar** [comment]
Ok, if you take a look at the network tab in the browsers console you can see that we will do a second call to the API. Sometimes we need to do this to get extra information e.g. ImdbId. It's in a separate call since I didn't want to hang the UI.
