### ISSUE TITLE
[Feature Request] Improving Issues usability

### ISSUE THREAD

**Issue by enchained** [tidusjar/Ombi#2905]
First of all, thank you for this feature, I used to forget when my friends reported to me everything in chats, and it was frustrating to keep track without the proper system, but now we use Ombi Issues quite a lot.
- Mark in Progress and Mark Resolved probably should be separate buttons, right now you always have to go through the in-progress state, while the issues that require "in progress" are not that often in my case.
- Some users don't know/notice there's "In Progress" and are creating duplicate issues. It would be nice to warn the user on submitting if any user already reported same issue for same title when it's not resolved yet. Something like red message saying that (and the existing issue description) and the Submit button changes to "Submit anyway".
- I'd like to keep Issues history, but also want an option to manually remove some issues - like test issues or duplicates. 
- It would be really cool if I could remove, resolve, or in-progress issues right from the Issues list (maybe by using icons at the end of the row?) without having to go to the details. Also an indicator of whether there's a description (icon with description text tooltip on hover) or any comments (comment icon with comment count) would really help speeding things up - most of my issues are really specific, so there's rarely any comments or even descriptions, so it would be possible to speed up through a lot of issues in no time with those quick actions. 
- And even without quick actions, it would be quite useful to have "Next unresolved issue" button in the details, and maybe move the action buttons in details from the bottom to the top? It often jumps from top to bottom when poster is loading, and I usually go to details after the issue is resolved, and every time I mis-click it or have to wait, so I feel like there's some potential to making it more streamlined for those who have a lot of reports from users.

**Comment by tidusjar** [comment]
Thanks for the feedback. I'm actually rewriting the whole issues area with the V4 update.

Please subscribe to #2647
