### ISSUE TITLE
Select the profile to use when clicking Request button

### ISSUE THREAD

**Issue by GeoCookie** [tidusjar/Ombi#2912]
Hello,

First, thank you for your work! Ombi have an important place in my setup. Everything work great but…(there is always a but :) ) i’m missing something that can make the difference for me.
I have many profiles in Radarr and Sonarr with differents languages cause i like to watch movies in their original language.
When using Ombi, i am forced to use the profile define in the options. So for english movies or tv shows, it’s ok but for a french movie for exemple, Ombi can’t b use (or i have to change the default profile). I would like to be able to choose which profile to use when clicking on Request button for a tv show or a movie.
Do you think if its a good idea and if it’s possible ?

Once again, thank you for you work !

**Comment by tidusjar** [comment]
This is already in the system. 

If a request is not Auto Approved then on the requests page you can change the root folder and quality profile before approving.

**Comment by GeoCookie** [comment]
Indeed, I did not see this possibility because I activated the self approval. I will try like that, even if I am a little disappointed to disable this option.

Thank you

**Comment by tidusjar** [comment]
There would be no way of identifying where it should go otherwise, or i'd have to setup some complicated mapping between genres and root folders, but then people might want to do it via release date to root folders. It would be endless.

**Comment by GeoCookie** [comment]
My idea was to choose the profile when clicking on request button. Maybe with a scrolling list which list all the profiles.
But disabling auto approve and choosing the profile in the requests menu is ok for my case. But I can choose the profile for movies but not for tv shows. I am missing something?

Movies OK
<img width="768" alt="movies ok" src="https://user-images.githubusercontent.com/43962716/55669699-c96b0800-587a-11e9-9820-b7a156dd5c07.png">

TV Shows NOK
<img width="771" alt="th shows nok" src="https://user-images.githubusercontent.com/43962716/55669704-d556ca00-587a-11e9-9624-239a0c54c6e4.png">

**Comment by hadim** [comment]
I agree with @GeoCookie . That would be nice to be able to choose a profile when requesting a movie and/or tv show.

**Comment by arnishow** [comment]
+1

**Comment by pannal** [comment]
+1

**Comment by Chiron1991** [comment]
+1
