### ISSUE TITLE
Re-sync to couchpotato after DB crash

### ISSUE THREAD

**Issue by Symbiot78** [tidusjar/Ombi#2913]
Hi

After a crash of my CP database I now have a list of wanted movies in Ombi but it's not reflected in CP.
How can I re-sync the wanted list from ombi back over to CP?

If I remove a movie from the request list in Ombi I cannot re-add it. It keeps registering as "Requested".

**Comment by tidusjar** [comment]
You need to delete the requests, then delete the Ombiexternal db and
restart ombi.

**Comment by Symbiot78** [comment]
hm.. 
removed all requests from "requests"
Stopped ombi
deleted ombi_external.db
started ombi
searched for one of the movies I had in my request list
it was still marked as "requested"

**Comment by Symbiot78** [comment]
tried also deleting Ombi.db
that helped..
will update back if I succeed to readd the movies.

**Comment by Symbiot78** [comment]
ok. Managed to get everything up again. it took a few tries deleting the db files and readding everything.
