### ISSUE TITLE
Offline Notification

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#2919]
Is there any way to set up an email notification whenever Ombi is unable to reach my Server? I'm currently using PlexPy/Tautulli and since Plex.exe is still running on my Plex Server, PlexPy doesn't notify me when my server is down even though it's in a crashed state. But usually when that happens, the Ombi landing page will say that my server is offline and when it detects that, it would be super helpful to get notified when that happens.

Thanks.

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
