### ISSUE TITLE
Combine Admin/User Login

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/Ombi#292]
I think a nice improvement would be to have just 1 login page and then from drop down or tabbed option select user or admin login.  To improve this even more is maybe have an option to select a plex user to have admin rights and then you could administrate, and add requests if wanted from the same login instead of currently needing to log in both.

**Comment by tidusjar** [comment]
I am looking at improving the whole user/admin stuff in the near future, including creating your own "local" users. This is a good idea.

**Comment by SuperPotatoMen** [comment]
Can be a part of https://github.com/tidusjar/PlexRequests.Net/issues/218

**Comment by SuperPotatoMen** [comment]
@tidusjar this is already live in the dev branch?

**Comment by tidusjar** [comment]
No it's not, I'm pushing this back slightly as it needs some considerations.

If we are combining them, we need to have a think about the following:

1. Authentication not enabled, but the user wants to log into their local account (In this case there is not password presented on screen).
2. Plex Authentication enabled with no password (Same as the above)

**Comment by tidusjar** [comment]
This is live in the Early Access Preview Branch
