### ISSUE TITLE
Ombi web ui and ombi app not showing the same info for movies

### ISSUE THREAD

**Issue by blassley** [tidusjar/Ombi#2920]
**Describe the bug**
I have setup ombi and within the web ui everything is showing correctly, I go to say rush hour 3 under movies and it shows as an available movie and does not allow it to be requested “this is good” but when logging into the ombi app on iOS only a select few movies show the correct information I can go to the same rush hour movie within the app and it wants me to request it any help would be awesome! 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Wrong repository, this is the Ombi repo where you need the Ombi app repo :) 

Anyway there is already a bug raised for this in the Ombi app repo so I suggest you subscribe to that issue.
