### ISSUE TITLE
Ombi reports title is available, clicking view brings to unrelated show.

### ISSUE THREAD

**Issue by lordkitsuna** [tidusjar/Ombi#2921]
**Describe the bug**
Ombi says that Captain marvel is available on my plex, its not. when i say view on plex it brings me to "Komori-san Can't Decline" an anime from 2015

**To Reproduce**
1. Go to 'search and look for captain marvel'
2. Click on 'view on plex'

**Expected behavior**
The movie shows up as not available as its not

**Screenshots**
https://i.imgur.com/hBcbiPA.png
https://i.imgur.com/r2GJfMM.jpg

**Logs (Logs directory where Ombi is located)**
I do not see anything in the logs related to this

**Desktop (please complete the following information):**
 - https://i.imgur.com/tumlSut.png

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Plex

**Comment by tidusjar** [comment]
Ok, Stop Ombi, Delete your OmbiExternal.db, Start up Ombi then run the Plex Sync manually.

Does that fix it?

**Comment by lordkitsuna** [comment]
Sadly no, the db delete did make it request-able but once i did the sync it showed as available again. Links with the same show as well.

**Comment by tidusjar** [comment]
What does the metadata look like in Plex for the movie?

**Comment by lordkitsuna** [comment]
thats whats weird its not even a movie its linking up with its an anime series. The metadata in plex is all correct for the show so i am not sure why ombi thinks its captain marvel 
<img width="1677" alt="Screenshot_20190411_002053" src="https://user-images.githubusercontent.com/3444267/55938257-d9267b80-5bef-11e9-84ec-0c0ff7f2b6c3.png">

**Comment by tidusjar** [comment]
Can you please provide the XML for that?

You can do this by pressing the "..." -> Get Info -> View XML

**Comment by lordkitsuna** [comment]
sorry for the delay, i do not see a get info option under the ... 
<img width="582" alt="plex" src="https://user-images.githubusercontent.com/3444267/56014632-efddd880-5caa-11e9-8847-83e40d1b3deb.png">

**Comment by tidusjar** [comment]
Can you  try and unmatch and then rematch?
Then refresh the metadata?

**Comment by lordkitsuna** [comment]
Sorry for the long delay life takes over sometimes. I went ahead and did as you suggested but it does not appear to have fixed the issue ombi still sees it as captain marvel for some reason
