### ISSUE TITLE
Issue with shows not appearing after searching

### ISSUE THREAD

**Issue by abarber229** [tidusjar/Ombi#2923]
Version -- 3.0.4256
Windows 10

I seem to have some issues when searching for a show. For example, when I search for Chambers, there are shows with the word chambers that do populate. However, there is no next page like on TVMaze. Also Ombi doesn't seem to be returning all of the results like TVMaze. I did search in TVMaze's API and found the show "http://www.tvmaze.com/shows/34346/chambers" which is what I was trying to find. I also found the show when searching in Sonarr. I did manually at the show in Sonarr since I couldn't get Ombi to find it. I'm not sure if I am missing something in my configuration or not. This has happened with a couple other shows but I do not recall, since I added them manually in Sonarr. If I find/remember the others I will update the post.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all

**Comment by abarber229** [comment]
Yes, I saw the wiki for that, but I don't understand on what is the next step I need to take. Is it something I need to be doing on my end or is it something that I need to edit on TV Maze. Sorry for my confusion!

**Comment by tidusjar** [comment]
Its something that needs to be done on TV Maze, it needs the external ids
