### ISSUE TITLE
Ombi APP can't login

### ISSUE THREAD

**Issue by casperse** [tidusjar/Ombi#2926]
**Describe the bug**

First logging into Ombi using the webpage on the phone works!

**To Reproduce**
1. Go to '...' Install latest Ombi app on android try to login
(Have deleted and re-installed it many times no change)

the path and password is correct (same logged in by web) get the following error message:

**Screenshots**
![Ombi](https://user-images.githubusercontent.com/2026859/56077721-c4103f00-5ddf-11e9-9321-76b990f63864.jpg)

**Comment by tidusjar** [comment]
Have you tried logging out, force close the app and then manual login?

**Comment by casperse** [comment]
I did a reboot of the server and log-out login and now it works (I did this yesterday also?)
One thing I still have problems logging ind and need to restore the settings.db and then things work again?
I found that this is mostly after adding API keys to sonarr or Radarr is this a coincident?

**Comment by tidusjar** [comment]
What do you mean?
