### ISSUE TITLE
Installed Ombi using apt and there's no Log folder

### ISSUE THREAD

**Issue by jaredneedell** [tidusjar/Ombi#2929]
Just installed Ombi using the provided Apt instructions here and there is no log folder to be found. I'm trying to investigate why I am not seeing Ombi showing movies/tv shows as marked available

**Comment by tidusjar** [comment]
There will always be a logs folder, I'm not the maintainer of that apt repo. check /etc/ombi/logs or /opt/ombi/logs

**Comment by jaredneedell** [comment]
There is nothing there when I search, it's stored under /opt/Ombi, i even manually created the folder and it's not populating any log files.

**Comment by tidusjar** [comment]
It's where ever you specified the --storage argument
