### ISSUE TITLE
Ombi not showing all episodes in series.

### ISSUE THREAD

**Issue by mkono87** [tidusjar/Ombi#2931]
**Describe the bug**
When accepting a a series request not all episodes are being monitored. For example, if a season has 12 episodes, ombi would only show it having 5 episodes. Sonarr would show all episodes, but only monitor the 5 that ombi shows. I would have to manually select the eps and search again on sonarr.

**Desktop (please complete the following information):**
search and requests made on Windows 10 systems using Chrome.

**Ombi Version (please complete the following information):**
 - Version 3.0.4256-master   linuxserver docker (unraid)
]

**Comment by tidusjar** [comment]
Can you please explain further, I don't fully understand your issue.

**Comment by mkono87** [comment]
Il try but I thought I was clear enough.

Picture this someone requests season 1 of a series. In this case (proven innocent 2019) its an ongoing season with a total of 13 episodes. For some reason ombi only shows it as 5... So as a result sonarr shows all 13 but only monitors 5 so far 3 episodes did not get downloaded. Just noticed a few series like this just this month. Does that explain it better?

**Comment by tidusjar** [comment]
Ombi is showing 13 episodes for me:
![image](https://user-images.githubusercontent.com/6642220/56097832-505e5700-5ef1-11e9-8eda-08d5f7a983ae.png)

**Comment by mkono87** [comment]
Okay if we can keep this issue open for a bit and next time il post pics. Its happened to 3 series just this week.

**Comment by mkono87** [comment]
Here we go, perfect example.
![Capture1](https://user-images.githubusercontent.com/35116314/56097922-6dcafb00-5ec8-11e9-9335-e2754e24c8de.PNG)
![Capture2](https://user-images.githubusercontent.com/35116314/56097923-6dcafb00-5ec8-11e9-9101-ca820a010593.PNG)

**Comment by tidusjar** [comment]
That's because you have requested the first 5 episodes.

You are looking at the request

**Comment by mkono87** [comment]
I just specifically chose first season and hit select all episodes. Still only shows 5 ep. This issue is NOT closed.
![Capture](https://user-images.githubusercontent.com/35116314/56098083-9f44c600-5eca-11e9-91b9-243adea76f92.PNG)

**Comment by tidusjar** [comment]
That is correct, "The Code" only has 5 episodes.

It has been closed since there is no issue here yet. 

If there is a valid issue please let me know.

**Comment by mkono87** [comment]
So would it be sonarr showing the wrong info? Not sure why its Sonarr is showing 12 episodes.

**Comment by tidusjar** [comment]
According to Wiki it's only 5 https://en.wikipedia.org/wiki/The_Code_(2019_TV_series)

**Comment by mkono87** [comment]
Thats so odd with sonarr then. Thanks for the help :)

**Comment by blassley** [comment]
This is because sonarr also is showing shows that have not aired yet, there are only 5 episodes available as of now, so that is what ombi is showing you

**Comment by mkono87** [comment]
> This is because sonarr also is showing shows that have not aired yet, there are only 5 episodes available as of now, so that is what ombi is showing you

But iv been using ombi for about a year and people can request the eps even if they havent aired yet.

**Comment by shorty88** [comment]
> According to Wiki it's only 5 https://en.wikipedia.org/wiki/The_Code_(2019_TV_series)

I am have the exact same issue with a different tv show which I know to have more episodes and seasons that what shows on Ombi. For example house hunters has new episodes for 2019 coming up and way more than 34 episodes in 2018 neither of which are showing up on ombi 
![image](https://user-images.githubusercontent.com/8666888/56260099-c6a2bb00-60a3-11e9-9835-51f7cd32beb3.png)

I am using ombi 

3.0.4256 master

**Comment by tidusjar** [comment]
All the data comes from TV maze.
