### ISSUE TITLE
[v4 - Feature request] Grab only unavailable requests from API

### ISSUE THREAD

**Issue by nameproof** [tidusjar/Ombi#2932]
On the homepage in Organizr you can have requests (from Ombi) shown. Currently you can only grab all the requests in Ombi clogging up the home screen with ALOT of available content. 

Make it possible to query the Ombi v4 API for only unavailable requests. This way you can easily see what is already requested. 

Thanks

**Comment by tidusjar** [comment]
Note to self API's per request status

**Comment by nameproof** [comment]
Thought you should know; organizr dev found a way to do this without this feature request. At least for my use case, this isn't needed anymore. Proceed as you wish, thanks!

**Comment by nwithan8** [comment]
They probably just use the old Request/tv and then iterate over the returned JSON and tracked which had "available: true"

**Comment by tidusjar** [comment]
Done in V4
