### ISSUE TITLE
Update to 3.0.4434 lost requests

### ISSUE THREAD

**Issue by jpdribbler** [tidusjar/Ombi#2935]
Hi,

first of all thanks a lot for developing OMBI, i love it!

Unforuntately i have issues after updating OMBI. In the last versions i lost all settings. This time i just lost all saved requests but the other settings are fine. 

I have updated ombi in Ubuntu 16 via sudo apt-get upgrade and updated to version 3.0.4434 but now the requested movie/TV page is completely empty!

Any idea what i could have done wrong or what should i do before upgrading to prevent loosing my requested movies/tv's?

Thank you.

Best Regards

**Comment by tidusjar** [comment]
Please fill in the bug template. There is information in the bug template I need.

Please reply once you have done this and then I will reopen.
