### ISSUE TITLE
Unable to authenticate with Office365 mail

### ISSUE THREAD

**Issue by lrdv8r** [tidusjar/Ombi#2936]
**Describe the bug**
Unable to authenticate to Office365 set up through a GoDaddy hosted account. Credentials work fine to log in directly to web O365.

**To Reproduce**
1. Create GoDaddy domain and add "Email Essentials" 
2. Go to Ombi and set up Email Notifications using the following settings:

- Enabled: Checked
- SMTP Authentication: Checked
- SMTP Host: smtp.office365.com
- SMTP Port: 587
- Email sender: user-a@domain-a.com
- Admin email: user-b@domain-b.com
- Username: user-a@domain-a.com
- Password: password for username (confirmed working through O365 web interface)

3. Click the "Test" button
4. Message displays "Successfully Saved Email Settings"
5. Message displays "There was an error when sending the message. Please check your email settings"

**Expected behavior**
Ombi test message to arrive in user-b@domain-b.com email inbox.

**Logs (Logs directory where Ombi is located)**
`2019-04-16 13:52:45.164 -07:00 [Warning] Exception when testing Email Notifications
MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [BYAPR11CA0051.namprd11.prod.outlook.com] ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.3 Authentication unsuccessful [BYAPR11CA0051.namprd11.prod.outlook.com]
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 225`

**Desktop (please complete the following information):**
 - Host OS: Centos 7.4
- Kernel version: Linux docker 4.19.10-1.el7.elrepo.x86_64 #1 SMP Mon Dec 17 08:44:04 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Docker version: Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Ombi Version (please complete the following information):**
 - Ombi Version 3.0.4256 
- Plex Media Server version: 1.15.4.919

**Additional context**
Attempted multiple iterations of user/pass, varying checkboxes and SMTP server settings. Nothing works for Office365. I did manage to get it working using Gmail SMTP settings and my gmail account, however. Worked as expected but switching back to O365 SMTP and user/pass results in authentication error.

**Comment by tidusjar** [comment]
See here: https://github.community/t5/Project-Development-Help-and/Office365-SMTP-not-working/m-p/8786#M1757
