### ISSUE TITLE
Search text box not obvious

### ISSUE THREAD

**Issue by 2fst4u** [tidusjar/Ombi#2940]
Hi, love the work and the app.

**Describe the bug**
The search box on desktop, and to a lesser extent on mobile, isn't obvious enough for users. I've introduced two new users to the web app, both very techno-literate people, and both of them have been confused about where exactly to start typing their search term in. Once you know that it's the grey box it's fine, but for a new user it isn't obvious enough.

**To Reproduce**
Introduce new user to the app and ask them to search 😝

**Expected behavior**
It would be preferable if the search box was bordered, with the buttons labelled "search" and "filter" spaced a bit further away. Currently it just looks a bit like a label saying "search", but it isn't clear that the word "search" is where you type.

**Screenshots**
Unable to get a screenshot, sorry.

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - all

**Ombi Version (please complete the following information):**
 - Version 3.0.4256

**Additional context**
None

**Comment by krisklosterman** [comment]
Speak of the devil lol I just submitted this pull request yesterday as I have the same issue.

https://github.com/tidusjar/Ombi/pull/2939

**Comment by tidusjar** [comment]
@krisklosterman has fixed this. His changes are now in develop
