### ISSUE TITLE
Menu drop-down doesn't disappear after click

### ISSUE THREAD

**Issue by 2fst4u** [tidusjar/Ombi#2941]
**Describe the bug**
The menu button stays open after clicking and going to a new page.

**To Reproduce**
1. Tap or click on the menu. 
2. Select a menu item
3. The page will change but the menu stays open, overlaying the new page.

**Expected behavior**
After tapping on or clicking on a menu item, the menu should disappear.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: all

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
 

**Additional context**
N/A

**Comment by tidusjar** [comment]
Thanks for the bug report. 

Currently I'm not making any further changes to the v3 UI. This will be superseded soon by the v4 UI. Thanks

**Comment by 2fst4u** [comment]
Ah I didn't even realise there was going to be a V4. Thanks. Sorry about
the spam then.
