### ISSUE TITLE
feature request: disable search suggestions on main search page

### ISSUE THREAD

**Issue by godofjesters** [tidusjar/Ombi#2942]
when you first log in, the search screen has suggestions that come up, but no instructions on how to either make it suggest other movies/shows, or how to turn them off completely. the suggestions when you're typing is helpful because that helps you find other movies or shows immediately but the ones that come up by default are unnecessary. most of them i have already so there's no way to not display them.

**Comment by tidusjar** [comment]
I'm not going to change this since v4 replaces the UI and everything is different.

**Comment by godofjesters** [comment]
sounds good! can't wait to see
