### ISSUE TITLE
{Feature Request} Ability to remove single items from request

### ISSUE THREAD

**Issue by uglytruckling** [tidusjar/Ombi#2943]
After a tv series has been requested and as the episodes become available on PLEX, could the available episodes remove themselves from the requested list, or allow the option of removing individual episodes from the list?

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
