### ISSUE TITLE
Search Text Overflow issue

### ISSUE THREAD

**Issue by chrischm** [tidusjar/Ombi#2946]
It seems in version 3.0.4455 there seems to be a formatting issue for the search bar and the side elements see below.  I tried on the Iphone 8  it seems okay. However on the Iphone X the mobile response I am getting is this. 

![57540223_767637296963738_8177505809031233536_n](https://user-images.githubusercontent.com/40046152/56620933-78c80e80-65df-11e9-94be-67811bd6b31d.jpg)

**Comment by tidusjar** [comment]
It's difficult due to the search bar and the extra options inside there. This will not be an issue on V4 which will be the next major release.
