### ISSUE TITLE
Newsletter uses wrong Link if Emby is used

### ISSUE THREAD

**Issue by Brudertac** [tidusjar/Ombi#2950]
If you use Emby and Setup an Externally Facing Hostname (URL) then the TV Shows Section in the Newsletter uses the wrong Link. It uses "app.emby.media..." instead of your own URL.

**To Reproduce**
1. Setup Externally Facing Hostname in Ombi for your Emby Server
2. Try send a Newsletter with TV Show Content
3. Test the Link on a TV Show

**Desktop (please complete the following information):**
- Ombi / Linuxserver Docker on Synology

- Ombi Developer [3.0.4489]
- Emby (4.1.0.26)

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
