### ISSUE TITLE
Users with permissions, are told they do not have permissions when requesting.

### ISSUE THREAD

**Issue by rylandthomas** [tidusjar/Ombi#2954]
**Describe the bug**
2 Users 1 on android 1 on ios are told they do not have the correct permissions when requesting films or series.

**Expected behavior**
for them to request films/series as i am with my admin rights.

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Comment by tidusjar** [comment]
Please expand, I don't understand. 

Do they have the Request Movie and Request TV permission?

**Comment by rylandthomas** [comment]
Sorry, yes they have request movies and request series on their accounts. I am able to request external with my admin rights no issues.

**Comment by tidusjar** [comment]
Can they request via the website?

**Comment by rylandthomas** [comment]
they are using the website as the external ombi url isnt working on the log in screen via app. it initially for a couple seconds says its requested then pops up saying they do not have permissions.

**Comment by rylandthomas** [comment]
just to clarify the external url works when using the website.

**Comment by tidusjar** [comment]
tell them to log out and then log in

**Comment by rylandthomas** [comment]
fixed. Was it an issue my end as i tried this in multiple devices and was getting the same error. Thank you.
