### ISSUE TITLE
V4  buttons broke 4.0.4519

### ISSUE THREAD

**Issue by chrischm** [tidusjar/Ombi#2957]
![background](https://user-images.githubusercontent.com/40046152/56857656-fb313500-6935-11e9-8a1b-6669dd4990bc.PNG)
For this one I was curious when the background logo we put in will be allowed again?

![not good](https://user-images.githubusercontent.com/40046152/56857712-a17d3a80-6936-11e9-8e89-64b1d8609d0c.PNG)
Then this one gives and example of the buttons not working with white theme.  ( I should correct this. when I say not working I just mean the correct color is not visible).

![Good](https://user-images.githubusercontent.com/40046152/56857721-aa6e0c00-6936-11e9-8cec-e3c868a54ad8.PNG)

**Comment by tidusjar** [comment]
You know v4 is no where near ready yet right?  

It's still a work in progress
