### ISSUE TITLE
Preferred language not working in Safari on macOS or iOS / Norwegian

### ISSUE THREAD

**Issue by InternationalAdvice0** [tidusjar/Ombi#2958]
**Describe the bug**
When I visit my Ombi on Safari either on iOS or macOS the default language is set to English and not changing to Norwegian even tho my browser is set to Norwegian. When I manually set the language to Norwegian in the navigator it changes to Norwegian but when I refresh the website it goes back to fallback language English. It works fine in Chrome.

**To Reproduce**
1. Go to 'my website'
2. Seeing English language being loaded. 
3. Change to "Norsk".
4. Refresh, goes back to English.

**Expected behavior**
I expected to get Norwegian language just like in Chrome, and when I choose the language I want from the drop down meny it remembers the choice when I refresh the website. (cookie)

**Screenshots**
https://res.cloudinary.com/danieldjupvik/image/upload/v1556459635/Skjermbilde_2019-04-28_kl._15.53.06.jpg

**Desktop (please complete the following information):**
 - OS: iOS 12.1.1 and macOS 10.14.4
 - OS: Ombi running on Windows 10 64-bit 

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256 Master
- Media Server: Plex

**Additional context**
I've tried the command "navigator.languages" and it says "nb-NO" meaning "Norsk Bokmål - Norsk". I use Apache webserver with Reverse Proxy to access Ombi with SSL.

Is there any way to choose a default language on Ombi? That way I know my users get the right language. Many of my users use iOS to access my website and there's no way of changing the language on Safari, cause it uses the system language of the iOS...

**Comment by tidusjar** [comment]
This has been resolved in v4
