### ISSUE TITLE
Discord notifications (webhook) are completely broken.

### ISSUE THREAD

**Issue by 437studios** [tidusjar/Ombi#2959]
**Describe the bug**
Discord notifications are completely broken, with and without /slack at the end of the webhook URL. "Test" work by clicking the test button.

However, as seen here, I created a simple test message for "Create Issue" notifications
They don't ever fire.
Not for PLEX (imported, auto) users, not for Local (manual created) users.
Not even for admins.

**Expected behavior**
Discord should receive a webhook notification.

**Screenshots**
Image: https://i.imgur.com/u1VHsmG.png
https://i.imgur.com/rqacH97.png

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - OS: Windows 10, 1903, x64

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server: Plex

What the heck am I doing wrong? I have been trying all combinations of settings for the last 12 hours and no notification ever fires.

**Comment by 437studios** [comment]
Working on `3.0.4248`

Proof: https://i.imgur.com/Tg1TGrE.png

**Comment by goldenpipes** [comment]
This has been fixed in develop.

The next release should include the fix as well.
