### ISSUE TITLE
[Feature Request] Split Issue & Request notifications

### ISSUE THREAD

**Issue by 437studios** [tidusjar/Ombi#2960]
Currently, a single webhook is used to notify agents of both issues (creation, resolution, etc) and requests (creation, approval, declination, fulfillment)

I think it would be pertinent and quite robust to split these into separate notifications settings, so that they can be tracked separately, e.g. two separate discord channels, one for issues, one for requests.

Thank you!

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
