### ISSUE TITLE
Organizr SSO auth token for Ombi expires too early

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#2963]
**Describe the bug**
Recently (Past 1-2 months?) I've been having issues where my Organizr users and myself frequently get logged out of Ombi.

**To Reproduce**
1) Log in via Organizr SSO
2) Continue using Organizr
3) You will eventually be logged out of Ombi but still remain logged in to Organizr

**Expected behavior**
User should not be frequently logged out when using Organizr SSO.

**Screenshots**
![image](https://user-images.githubusercontent.com/16909269/57038939-117a1200-6c10-11e9-9c29-f3fd844ed03a.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Unraid Docker

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]: 3.0.4256
- Media Server [e.g. Plex]: Plex

**Additional context**
Currently unsure if the bug is caused by Organizr or Ombi. Seeing how it's only happened recently and a new Ombi release with auth related features hasn't occurred for a while, I would likely assume it to be related to Organizr's code. I haven't changed anything on my webserver config (besides updating dockers) in >8 months.

**Comment by tidusjar** [comment]
I spoke to Cause regarding this a week or so back.

I double checked the code and explained to him what happens. There has been no change to the way org uses Ombi SSO for over 2 years now.

Basically if you have a correct JWT token in local storage then you will be logged in.

**Comment by goldenpipes** [comment]
I've had this happen sometimes too but usually if I log out of org and in again it's fine

**Comment by Archmonger** [comment]
Relogging does temporarily fix the issue, as it refreshes the token. For additional information, I have never had this issue occur with Plex or Tautulli when using Org SSO. If I discover any concrete reason as to why this occurs I will post back here.

**Comment by ericfledderman** [comment]
> Relogging does temporarily fix the issue, as it refreshes the token. For additional information, I have never had this issue occur with Plex or Tautulli when using Org SSO. If I discover any concrete reason as to why this occurs I will post back here.

+1
Saaaaame

**Comment by Archmonger** [comment]
Yeah can confirm this still occurs. Attempted a completely clean configuration of Organizr, nginx, and Ombi (through Unraid Docker) and the issue persists on Chromium browsers (Opera, Google Chrome). Have not tested on other browsers. Issue does not occur with any other Organizr SSO service.

**Comment by zjpleau** [comment]
I am having this issue too. Was anyone ever able to solve it? Also using Google Chrome
