### ISSUE TITLE
Unable to configure Gmail notifications

### ISSUE THREAD

**Issue by lithium1978** [tidusjar/Ombi#2965]
Attempting to use Gmail for email notifications.   Confirmed 2 Factor Auth is turned off and less secure apps access is on.   using smtp.gmail.com and port 465, settings save without issue but when I test I get the error below.

- OS: Window 10
- Ombi Version 3.0.4256
- Media Server Emby

Log snippet:

2019-05-02 18:23:21.766 -04:00 [Warning] Exception when testing Email Notifications
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---

**Comment by tidusjar** [comment]
Use port 587

**Comment by lithium1978** [comment]
I have port 587 set and smtp.gmail.com  using my gmail address and password.   I have it enabled and enabled authentication = true, disable TLS/SSL = true, Disable Cert checking = true.

When I test I get this response in the logs:

2019-05-05 19:31:52.763 -04:00 [Warning] Exception when testing Email Notifications
System.NotSupportedException: The SMTP server does not support authentication.


If I uncheck enable authentication I get this:

2019-05-05 19:34:19.591 -04:00 [Warning] Exception when testing Email Notifications
MailKit.ServiceNotAuthenticatedException: 5.7.0 Must issue a STARTTLS command first. z140sm17365400wmc.27 - gsmtp

**Comment by tidusjar** [comment]
It's working perfectly fine for me using my Gmail.

Please read this: https://github.com/tidusjar/Ombi/wiki/Email-Notification-Settings#setting-up-email-notifications
