### ISSUE TITLE
Donate to Library Maintainer Button in app?

### ISSUE THREAD

**Issue by Yapsonark** [tidusjar/Ombi#2966]
I’m sorry if this is in the wrong place to post this. 

I’ve been searching everywhere to see if someone discussed this in the past but no luck.

My issue is 95% of my viewers don’t own or ever use computers just mobile. I realize they can log into the site on their browser and I’ll tell them about it but with the app I doubt they would. 

Is it possible to add the library maintainer donate button in the app itself? Is there a way to enable this? Or maybe not allowed by google store /apple. A link to PayPal.me from in the app would make things a lot easier and if there is a place to request this feature I’d love to know where.

Thanks for your time and I am loving Ombi. We will all be buying it I can promise that XD

**Comment by tidusjar** [comment]
Thanks, this is something I'm not planning to add, plus I'm not sure how the app stores would like this, since I'm not sure if it counts as advertising within the app
