### ISSUE TITLE
Pushover notification truncated at apostrophe

### ISSUE THREAD

**Issue by a-jackson** [tidusjar/Ombi#2967]
Where a movie title includes an apostrophe the entire notification text ends at that. I only use Pushover and email and the email is fine.

E.g. I received
"Hello! Your request for The Gruffalo"
Rather than
"Hello! Your request for The Gruffalo's Child has been approved"

**Comment by a-jackson** [comment]
I have just found #2228 which seems to be the same thing. I am running 3.0.4256 which appears to be the latest version?

**Comment by tidusjar** [comment]
Now fixed in develop
