### ISSUE TITLE
Movies showing requested with no interaction

### ISSUE THREAD

**Issue by evlsmurf** [tidusjar/Ombi#2971]
Running Ombi, Plex, Radarr/Sonarr and Jackett. With no user interaction if i search a movie that radarr has from my rss feed ombi shows it as requested. Is there a setting I need to fix to prevent ombi from showing items as requested when no one is requesting them. If I request something that's hasn't been in my rss feed im fine its works as should.

**Comment by tidusjar** [comment]
Please follow the issue template
