### ISSUE TITLE
Custom logo broken in all browsers except firefox

### ISSUE THREAD

**Issue by b000p** [tidusjar/Ombi#2972]
**Describe the bug**
In windows 10, the custom logo image works on landing page & login with firefox but displays a broke image icon in chrome. 
In iOS, firefox and safari it renders a white square shape where the image is but does not load it. The preview displays logo and the image is directly accessible from the web.

**Expected behavior**
Load the image across all browsers.

**Desktop (please complete the following information):**
 - OS: Windows 10, iOS 12

**Ombi Version (please complete the following information):**
- Version- v3.0.4256
- Container- linuxserver/ombi 
- Linuxserver.io version:- v3.0.4256-ls17
- Media Server- Plex

**Additional context**
The ombi logo renders fine across all browsers/devices.

**Comment by tidusjar** [comment]
It's probably due to your custom logo. Can you try an image from Google or something else?

**Comment by b000p** [comment]
I feel silly now.. Yes its working thank you. 
Any ideas as to the cause of this or can you recommend file specs and image hosting that's compatible as i tested several clean images and a couple different hosts.

**Comment by tidusjar** [comment]
Imgur always worked fine for me!

**Comment by b000p** [comment]
Ok. Love your work. V4 looks sexy! Donation coming your way.

**Comment by tidusjar** [comment]
Haha thanks! Glad you like it!
