### ISSUE TITLE
[GUI Request] Placeholder in search box

### ISSUE THREAD

**Issue by KrunchMuffin** [tidusjar/Ombi#2974]
I have users that are not so tech savvy. They find the interface confusing. They don't know what to do. Would be nice to add a placeholder on the search box something like "Enter Your Search Here". Just from looking at it, you would never know it was an input box.

**Comment by Yapsonark** [comment]
The new UI is gonna be awesome when it releases, should fix that problem.

https://github.com/tidusjar/Ombi/projects

**Comment by KrunchMuffin** [comment]
Oh nice! Didn't know. Thanks!
