### ISSUE TITLE
Movies added by Ombi to Radarr is unmonitored

### ISSUE THREAD

**Issue by CyberMew** [tidusjar/Ombi#2977]
**Describe the bug**
Movies added by `Ombi` to `Radarr` is unmonitored. This causes a problem because even though the movie has been out for 1 year and is indeed available, `Radarr` doesn't search it periodically since it is `Unmonitored`.

**To Reproduce**
1. Go to Ombi
2. Add a movie
3. Go to movie in Radarr
4. See Unmonitored tag

**Expected behavior**
Step 4 should be seeing a Monitored tag.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Unraid 6.6.7

**Ombi Version (please complete the following information):**
- 3.0.4538 develop

OS Architecture | X64
-- | --
OS Description | Linux 4.18.20-unRAID #1 SMP Fri Nov 23 11:38:16 PST 2018
Process Architecture | X64
Application Base Path | /app/ombi

**Additional context**

**Comment by tidusjar** [comment]
Radarr version? I can't seem to reproduce

**Comment by CyberMew** [comment]
0.2.1293 for radarr. 

But weird, it seems to be working again. Must be some remnants from the past versions. Will close for now and reopen if I encounter it again. Thanks!
