### ISSUE TITLE
Requests won't connect to Radarr

### ISSUE THREAD

**Issue by cdrracing** [tidusjar/Ombi#2978]
Ombi is failing to send approved requests to Radarr.  Everything was working properly, then suddenly between 4/29 & 5/02 it stopped working.
It's still working well with Sonarr, and Radarr succesfully passes the test in settings but when a request is filed it throws up the error "it could not be added.  It will be added to the request queue"
[log-20190509.txt](https://github.com/tidusjar/Ombi/files/3168660/log-20190509.txt)

**Comment by tidusjar** [comment]
Please use the bug template.
