### ISSUE TITLE
Radarr not sending requests to Radarr

### ISSUE THREAD

**Issue by cdrracing** [tidusjar/Ombi#2979]
**Describe the bug**
Ombi is not sending requests to Radarr

**To Reproduce**
Submit request to Ombi

**Expected behavior**
Movie gets added to the "grab" list in Radarr

**Logs (Logs directory where Ombi is located)**
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
2019-05-09 22:14:49.559 -05:00 [Error] Error when sending movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57

**Desktop**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server 1.15.5.994

**Additional context**
[log-20190509.txt](https://github.com/tidusjar/Ombi/files/3169312/log-20190509.txt)

**Comment by tidusjar** [comment]
Radarr version? 

Ombi is not sending to Radarr but it's being added to the grab list? Can you please explain further?

**Comment by cdrracing** [comment]
Radarr version: 0.2.0.1344

That's exactly right.  When a movie is approved I get the "Item added to fault queue" 
notification and it never makes it to Radarr.
Ombi and Radarr were working perfectly together for over a year so I know they're connected properly, however I have tried changing the API Key in both programs to be safe.

![Ombi - Radarr](https://user-images.githubusercontent.com/16027087/57573817-f075a600-73f3-11e9-9a2b-4e0b52acc14b.png)

**Comment by tidusjar** [comment]
What is a grab list?

**Comment by cdrracing** [comment]
Lol, That was the best terminology I could come up with to explain what I thought it was doing.  I assumed that once a movie is approved it gets added to some sort of grab list, which is then sent to Radarr.

**Comment by tidusjar** [comment]
So what should happen is as soon as it's approved. It will be sent to Radarr and marked as monitored. 

Have you added a base URL to Radarr? You sure your settings are correct?

**Comment by cdrracing** [comment]
I haven't, and honestly I'm not sure what that does.  It was working before without a Base URL and Sonarr is currently working without it.

I'm absolutely positive that all my settings are correct and Ombi agrees since it passes the connectivity test.

![Ombi 2](https://user-images.githubusercontent.com/16027087/57576736-e58b3780-742c-11e9-83db-9e847abbbcd9.png)
![Ombi 3](https://user-images.githubusercontent.com/16027087/57576737-e8862800-742c-11e9-8ba9-bdf8c46a78dc.png)

**Comment by cdrracing** [comment]
After reading what I wrote I realize that it probably came across as douchy.  I can't be absolutely positive that ALL my settings are correct but I can say that the port matches on both ends, the API matches on both ends and I've tried both my internal ip and external ip and neither are having any effect on Radarr receiving requests.

I guess the strangest part is that it is passing the connectivity test.

**Comment by tidusjar** [comment]
Can you try and send a movie to Radarr using Ombi again but this time post the relevant Radarr logs?

**Comment by cdrracing** [comment]
I wasn't able to find any relevant content in the Radarr logs so I decided to remove all the files and start new.  Once I did that I connected both programs and submitted a request and it successfully sent to Radarr.  So I decided to (just to make sure) remove the config files from Radarr and put the old one back and the same thing happened as before (requests not showing up in Radarr).

So it looks like somehow Radarr got botched.  Looking back I feel dumb that I didn't think that Radarr could be the problem.

Thanks for your help Jamie
And thanks for creating Ombi!

**Comment by tidusjar** [comment]
No problem. Glad you sorted out the issue

**Comment by goldenpipes** [comment]
The radarr config.xml can get corrupted on windows. I've had it happen before. Deleteing it will generate a new Api Key for radarr. You can restore a work backup of the config without touching the radarr db.

**Comment by thejamescarter** [comment]
I am getting the exact same error. I request a movie it sends me this notification error: "Hello! The user @ has requested XXX but it could not be added. This has been added into the requests queue and will keep retrying. Even though the command goes through to radarr and the movie is added. When configuring radarr in Ombi connection is perfect. When adding a movie i also get this error in the logs: "Error when sending movie to DVR app, added to the request queue" I'm not exactly willing to delete all files and start from scratch with radarr as OP did. Any help would be great.
