### ISSUE TITLE
Not pulling new TV titles

### ISSUE THREAD

**Issue by leftovernick** [tidusjar/Ombi#2982]
**Describe the bug**
Ombi doesn’t populate some new titles. I’ve noticed this a few times with Netflix series. The shows show up when doing a search on TVmaze 
Example: Dead to Me
https://www.tvmaze.com/shows/35846/dead-to-me

**To Reproduce**
1. Go to Search
2. Click on TV
3. Search “Dead To Me”

**Expected behavior**
No results show

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256
- Media Server: Plex

**Additional context**

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all
