### ISSUE TITLE
Missing Left Nav Bar - V4

### ISSUE THREAD

**Issue by jaretclifton** [tidusjar/Ombi#2984]
**Describe the bug**
Upon a clean installation (or upgrade -- have tried both) running most of the recent versions (currently on 4.0.4574) the entire left navigation pane is missing. It appears the default redirect is to /discover which fills the entire page thus preventing the search nav or admin panels on the left to display.

**To Reproduce**
1. Install new 4.0.4574 instance
2. Load the base URL
3. Presented with /discover and nothing else

**Expected behavior**
Nav bar to display on the far left.

**Screenshots**
![image](https://user-images.githubusercontent.com/20193366/57916837-95c4ca00-788b-11e9-92e7-7d3445030b21.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LXC container on Proxmox

**Ombi Version (please complete the following information):**
 - Version 4.0.4574
- Media Server: Plex

**Comment by tidusjar** [comment]
What's your screen resolution?

You do know that V4 is not ready to be used yet right?

**Comment by jaretclifton** [comment]
Oh absolutely I understand it's not ready yet. I have a dev instance container that I keep updating V4 on just to check the progress and see all the new fun things you're adding! :) By no means is this my "production" instance -- that's running 3.0.4572.

As for the resolution... this happens on 2560x1440, 1920x1080, 1920x1200 as well as mobile displays.

**Comment by tidusjar** [comment]
Oh that's strange. Have you tried clearing your browser's cache?

**Comment by jaretclifton** [comment]
Apologies, was out of the country and didn't get a chance to update this. Yes I've cleared cache, tried it on multiple devices, purged cache in Cloudflare, bypassed Cloudflare, typed manual URLs etc. Nothing seems to make the left nav bar display. The URL that keeps being displayed is [root domain]/discover
