### ISSUE TITLE
plexUrl is null and available is false when searching movie through api call

### ISSUE THREAD

**Issue by mariotacke** [tidusjar/Ombi#2985]
**Describe the bug**
When I query the API via `/api/v1/search/movie/:movie-name` it properly returns the movie I was searching but does **not** correctly indicate if it is available in Plex. A subsequent call to `/api/v1/search/movie/info/:the-movie-db-id` however does properly indicate it.

**To Reproduce**
1. Use Postman with `ApiKey` authentication
2. Run `GET /api/v1/search/movie/:movie-name` (a movie in your Plex library by name)
3. Check fields `plexUrl` being `null` and `available` being `false`.
4. This should be the URL to Plex and available should be `true` instead.
5. Run `GET /api/v1/search/Movie/info/:the-movie-db-id` (`theMovieDbId` from the payload above)
6. Notice `plexUrl` and `available` being properly populated.

**Expected behavior**
I expect the search to return a populated `plexUrl` and `available` field if it is available in my Plex library.

**Desktop (please complete the following information):**
 - OS: Ubuntu, Docker

**Ombi Version (please complete the following information):**
- Version: `3.0.4256`, `Linuxserver.io version:- v3.0.4256-ls17 Build-date:- 2019-05-07T07:23:55+01:00`
- Media Server Plex
- Docker image: `linuxserver/ombi:latest`, `1c991bd8b10c`

**Additional context**
I have a feeling this has worked in the past but stopped working at some unknown point. The API/JSON body defines the field, so I assume it should be populated.

**Comment by tidusjar** [comment]
So, this is slightly complicated. 

Basically the short version is, it all depends on what metadata ombi holds for the movie and also it depends on what movie agents you have setup in Plex. 

Basically we need certain information e.g. imdbid to match up if it's available on Plex. 

So we do an extra call after to get this information. We do not do it as part of the initial call as we want to be able to show the results straight away.

**Comment by mariotacke** [comment]
@tidusjar, I see. I had a hunch this was performance related. Since the result set could be very large, making these look-ups might take a long time, I suppose. It was confusing because it has the fields as part of the search result payload. Perhaps we can just document this behavior **or** remove the specific keys?

**Comment by tidusjar** [comment]
Yeah it has the fields because we potentially have the correct metadata for it. But we also might not. 

What do you mean remove the specific keys?

**Comment by mariotacke** [comment]
I was referring to the specific fields / keys (`plexUrl`, `available`, etc.) in the object that comes back from the search request. I assume it is using the same DTO from the info response and thus shares the layout. For the mobile app, are you planning to make additional requests to get the missing information (from #2861) like the web client? If so, we can probably close this issue and perhaps just add this behavior to the documentation?

**Comment by tidusjar** [comment]
Yes I am planning to mimic the same functionality in the mobile app. 
I'm not going to remove the keys since I mentioned, depending on the metadata, they could be populated.
