### ISSUE TITLE
Cannot connect to Plex if it is set to required SSL

### ISSUE THREAD

**Issue by hstorey219** [tidusjar/Ombi#2986]
I did some testing and found out why I can not connect to the Plex server. If you have on the Plex server under Network settings , Secure Connections set to "Required". Obmi will not connect, but if you change it to Preferred, then Obmi will connect to the Plex Server.

**Comment by tidusjar** [comment]
Please follow the bug template. 

Also please search before opening a issue. https://github.com/tidusjar/Ombi/issues/2909
