### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by trackermb** [tidusjar/Ombi#2987]
Hi there I'm doing a clear out and need to remove a number of users.  Some seem to delete fine but others dont seem to be able to be removed.

**To Reproduce**
1. Go to usermanagement
2. Click on details/edit
3. Click delete 
4. Click yes 
Nothing happens

**Expected behavior**
user to be remove

**Desktop (please complete the following information):**
 - OS: Linux

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Additional context**
I have also tried doing this with the API and got the following error

{
  "error": "SQLite Error 19: 'FOREIGN KEY constraint failed'."
}
There is not unusual characters in the username.  From what I have test it seems to be if user has requested content they are unable to be removed for user list.

**Comment by goldenpipes** [comment]
manually cleared out foreign key out of db's fixed it
