### ISSUE TITLE
[V4 Feedback] Radarr/Sonarr Order

### ISSUE THREAD

**Issue by angrycuban13** [tidusjar/Ombi#2989]
Just started using V4 and one of the things that I would recommend is to put Sonarr/Radarr on the same order, either at the beginning or at the end. 

![Ombi-V4](https://user-images.githubusercontent.com/39564898/58361959-d0b09a00-7e57-11e9-9644-21886d885edb.png)

**Comment by tidusjar** [comment]
I've not tackled the settings yet, but thanks for the pointers :)
