### ISSUE TITLE
Pushbullet channel notification

### ISSUE THREAD

**Issue by damiantje99** [tidusjar/Ombi#299]
First of all, you did a great job! Second, is it possible to add a channel in the Pushbullet notification?

This way, my other administrator can also receive requests from users.

**Comment by tidusjar** [comment]
Thanks, yes it's possible as far as I am aware! It shall be done!

**Comment by damiantje99** [comment]
Jeez, you fast. Thanks!

**Comment by badincite** [comment]
Will this be added back for ombi?

**Comment by tidusjar** [comment]
It was never removed so I am not sure what you mean by added back...

**Comment by badincite** [comment]
I don't see any area to put in the channel if I put it in the device identifier I don't get any notifications
![image](https://cloud.githubusercontent.com/assets/7386290/23306079/acf66a5e-fa6f-11e6-93a1-a4b8d24f3798.png)

**Comment by tidusjar** [comment]
It's because i've not developed that functionality yet :)

**Comment by badincite** [comment]
Gotcha no problem I'm patient, I was using it in plexrequest and had a channel setup I just noticed it wasn't working.
