### ISSUE TITLE
Automated email sends twice

### ISSUE THREAD

**Issue by dejected1** [tidusjar/Ombi#2990]
Version 3.0.4256
windows 10 x64
nginx

version 4256 but its been occurring across versions for a while. Basically any of the auto generated emails from ombi are sent twice. Like the email that states requested content is now available. The user will get that email twice. 

I've tried three different email forwarders. Gmail, zoho and elasticmail. 

If I subscribe to a pending request from a different user, when the auto generated email is sent, the user will get two, but the administrator will only get one. However if the admin does the request, that email will still be sent twice. 

I don't see any errors in the log because both emails are being sent successfully. The problem is that I keeps sending two.

**Comment by tidusjar** [comment]
Please follow the issue template.
