### ISSUE TITLE
Able to update user settings through API

### ISSUE THREAD

**Issue by PoGo606** [tidusjar/Ombi#2991]
Hello, 

I'm working on a script to populate my user's email address.
They are sync through a local Emby server that authenticate them with LDAP.

`LDAP <==[auth]==> Emby <==[auth]==> Ombi`

Import works well but no email is populated (which is normal, Emby user's settings does not come with an email).
As email notification is quite fancy, I'm trying to populate my Ombi users with their mail.
I made up a little perl script that will perform these actions:
- Get all Ombi's users (API) => OK
- Get a missing user's email address with LDAP => OK
- Set it's email in the Ombi database

After looking at the API swagger, it appears that it's missing a :
`PUT /api/v1/Identity/User/{userId}`
In order to update a specific user.

Am I missing something ? Or is it a feature that is not available yet ?

Thanks in advance.

**Comment by PoGo606** [comment]
Nevermind, found my way with a GET on /api/v1/Identity and getting + "userName" header
And pushing it back with PUT after modifying it.

**Comment by gyates100895** [comment]
As someone wishing to do the same thing, could you provide this script? I have the exact same setup regarding ldap->emby->ombi. Also use nginx with the nginx-auth-ldap module to secure all sub sites if your interested.

**Comment by PoGo606** [comment]
Hi @gyates100895, you can find it here : https://wtf.roflcopter.fr/paste/?8b0ef109df4651d8#HreskqQr9DLQ19aKMXH31znuys6eWb8k7R5VXrwZZnFT

It's written in Perl and not really thought to be exported publicly. So please forgive the lack of comments ;)

**Comment by gyates100895** [comment]
@PoGo606 Much appreciated :) I'll figure it out. If I get to adding comments, which I will have to make along the way as I am not familiar with Perl, would you like an appended copy when I get it up and running?

**Comment by PoGo606** [comment]
@gyates100895 Well, that would be much appreciated ! Meanwhile, don't hesitate to reach me out if you need help !
