### ISSUE TITLE
Notify user via Telegram

### ISSUE THREAD

**Issue by jakob42** [tidusjar/Ombi#2993]
Hi,

I've setup a Telegram bot, put in the API key and my chat ID in the global settings. When a user requests a movie I'm getting notified. So far so good. Now I edit that user and put his telegram chat id (also tried his telegram username) into his settings. But when I approve the request, it just sends **me** the message instead of him. He added the bot and put "/start" in, so the bot should be able to contact him.

I might be stupid, but isn't the feature so the users get notified if a request has been approved/added? Please let me know if this isn't intended like that.

Thanks for the great app!

**Comment by tidusjar** [comment]
So it's pretty generic, personally I don't use telegram so I don't know how it works. 

But basically if that setting is filled in for that user you can use it in the template. Please refer to the notification variables in the wiki. See the UserPreference variable.

**Comment by mueslo** [comment]
It would be a lot more useful if you could enter the chat id of that user so he can get a direct message.

**Comment by lightmaster** [comment]
Just to confirm, no way to send a user a private message via Telegram instead of using email? All messages have to go to the group that's added to the telegram configuration?

**Comment by melyux** [comment]
Please allow us to use a specific Chat ID for each notification type, and use the {UserPreference} variable to be used for this Chat ID.
