### ISSUE TITLE
Deleted Movie Available

### ISSUE THREAD

**Issue by silveringking** [tidusjar/Ombi#2996]
So I've already referred to this thread https://github.com/tidusjar/Ombi/issues/1866

However I'm still having an issue with this. I have a docker image with ombi however.

The system is completely free of software besides git and docker/dockerstarter

sudo apt-get install -f sqlite3

I've edited my script to fit my needs:

`#!/bin/bash
sudo sqlite3 /home/silveringking/.config/appdata/ombi/Ombi.db "select * from PlexServerContent where Title like '%$1%'"
read -p " Delete really?! Going on with pressing Enter!"
sudo sqlite3 /home/silveringking/.config/appdata/ombi/Ombi.db "delete from PlexServerContent where Title like '%$1%'"
sudo sqlite3 /home/silveringking/.config/appdata/ombi/Ombi.db "select * from PlexServerContent where Title like '%$1%'"`

after that chmod +x nameofthescript.sh

enter root

./nameofthescript.sh "Catch\ Me\ If\ You\ Can"

sudo reboot

cleaning browser in windows with ccleaner

And it is still stuck.

I'm sending the contents of Ombi.db

I can't paste it here so I'm pastebin'g it

https://pastebin.com/fRJrPwz0

Kind regards

**Comment by tidusjar** [comment]
Do it in the OmbiExternal.Db.
