### ISSUE TITLE
User without "Manage Own Requests" role can see a "Remove" button

### ISSUE THREAD

**Issue by telecomguyML** [tidusjar/Ombi#2997]
**Describe the bug**
If you are a user that has the roles "Request Movie" and "Request TV", you can submit requests without issues, and you can view your requests.  However, the requests have a "Remove" button that when you click on it, it just refreshes the page but the request remains.  

**To Reproduce**
See description of the bug

**Expected behavior**
You would see the request, but there would be no "Remove" button on the request

**Screenshots**
Should be self explanatory, but can provide screenshots if necessary

**Logs (Logs directory where Ombi is located)**
Not sure if logs are required, but I can provide if necessary

**Desktop (please complete the following information):**
 - OS: Docker container

**Ombi Version (please complete the following information):**
 - Version - 3.0.4613
 - Media Server - Plex

**Comment by tidusjar** [comment]
This has been fixed in v4
