### ISSUE TITLE
[Feature Request] Additional Custom Text in Newsletter

### ISSUE THREAD

**Issue by Cessquill** [tidusjar/Ombi#2999]
Ability to enter text into textarea that's automatically amended to the next newsletter and then cleared.

Often have things to tell people that don't warrant a mass email, but they could still do with knowing (eg, upload speed has increased - improve your streams, offline sync now enabled, series x has been upgraded/fixed, recommend you watch x, Merry Christmas, scheduled maintenance next Thursday morning, etc.).

Raised it a while ago on the Unraid forums, but forgot to replicate here.  Obviously not a big deal, but I'd find it very useful.

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
