### ISSUE TITLE
[Feature Request] Validate Request Queue

### ISSUE THREAD

**Issue by EricHupp** [tidusjar/Ombi#3000]
Would it be possible to add the ability to validate the request queue?  Maybe a button on the settings page same as the 2 sync buttons?   It would allow people that were having problems with requests not being forwarded to say Sonarr or Radarr the ability to check their requests after fixing the problem.  Eliminating the need to manually add any missed requests to the respective utilities.

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
