### ISSUE TITLE
Wiki page for roles not complete.

### ISSUE THREAD

**Issue by Dipskcit** [tidusjar/Ombi#3004]
As the title says, on the wiki page explaining what each role does, not every role is explained.

**Comment by tidusjar** [comment]
Which page and what roles are missing?

**Comment by Dipskcit** [comment]
https://github.com/tidusjar/Ombi/wiki/User-Roles-Explained

Edit Custom Page is missing and Manage Own Requests has no description

**Comment by tidusjar** [comment]
Updated.
