### ISSUE TITLE
New users unable to search due to UX

### ISSUE THREAD

**Issue by ptr727** [tidusjar/Ombi#3005]
**Describe the bug**
New users do not how how to search.
The search box does not look like a search box.
Users think they have to click the search button to get to the search option.
There is no visual indication to make it obvious to a user that they are supposed to click and type in the search area.

**To Reproduce**
I cut cable, and I introduced Ombi to my family (I do not want them to use Sonarr and Radarr directly).
I sent them invitation emails (and the email did not include the server URI, I manually sent them the correct URL, the URL is set in configuration, but that is not the issue I want to report).
I watch them open Ombi on their phones, I ask them to search for something, they keep clicking the search icon, and nothing happens.
They are mad at me because Ombi does not work.
In watching them, the UX gives no indication of where the search terms should be entered.
The search box looks like a visual element, there is no border, there is no text inside it, it does not look like an edit box.

**Expected behavior**
Search capability is the most important thing for users in Ombi.
Search should be super obvious, and super simple.
The default layout that shows movies and shows that were not searched for is confusing and makes the UI busy.
Make the search box more visible, make it look like an edit box, not a graphic element.
E.g. put it in the middle of a clutter free page, give it a border, put the pre selection filters outside away from the search edit box, put the search icon right next to the search box, do not default to show content from the pre-selection options.
E.g. Look at how google does it, search box center, with search instructions written in search box, very obvious how to use.

**Screenshots**
Compare the Ombi search page with Google, there is no visual hint helping a user know where to enter search text.

**Logs (Logs directory where Ombi is located)**
NA

**Desktop (please complete the following information):**
 - OS: iOS Chrome, Win10 Chrome

**Ombi Version (please complete the following information):**
- Version 3.0.4256, Unraid, LSIO Docker
- Media Server: Plex

**Additional context**
NA
![20190608_142845000_iOS](https://user-images.githubusercontent.com/2061579/59148731-8257db00-89c1-11e9-8856-fe12bfede1bb.png)
![2019-06-08 (2)](https://user-images.githubusercontent.com/2061579/59148732-8e439d00-89c1-11e9-8d59-93f336ed79e5.png)
![2019-06-08 (3)](https://user-images.githubusercontent.com/2061579/59148733-8e439d00-89c1-11e9-9712-b04ebdd71539.png)

**Comment by tidusjar** [comment]
This has been resolved in v4. You can verify here

Https://app.ombi.io with the username and password as beta

**Comment by ptr727** [comment]
Wow, that UX is so much better, great job :)
Let me figure out how to get a LSIO docker running version 4.

**Comment by tidusjar** [comment]
Lsio does have a tag for it. But it's still in development and is not really ready yet.

**Comment by ptr727** [comment]
Ok, I'll wait.
