### ISSUE TITLE
External Plex Auth window does not close

### ISSUE THREAD

**Issue by danner26** [tidusjar/Ombi#3006]
**Describe the bug**
When logging into Ombi using a Plex login, it spawns the login window, then you proceed to login, and you end up authorized after a successful login attempt.

I have noticed that this login window telling you that it was successful does not close automatically. Is there no time out? or is this an external issue (aka its a plex issue) rather than an Ombi one?

**To Reproduce**
1. Navigate to Ombi
2. Login which should spawn a https://auth.plex.tv page
3. Wait, it never closes

**Expected behavior**
It should automatically close that page after x amount of time, or have a hypertext link to click rather than having to close the tab manually.

**Desktop (please complete the following information):**
 - OS: Windows
Occurs on android as well

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Comment by tidusjar** [comment]
It doesn't close because I have no control over the window once it has gone to plex.tv. I think Plex do say you can close this window now.
