### ISSUE TITLE
Deny button sends an approved notification

### ISSUE THREAD

**Issue by dparrish** [tidusjar/Ombi#3009]
I have notifications enabled on Slack.

When a user adds a request and I click the "Deny" button, I get a notification on Slack like:

"Hello! Your request for Superman/Shazam!: The Return of Black Adam on Ombi! This is now available! :)"

The request stays on the ombi interface, still unapproved.

I expect to see a message that the request has been denied and I expect to see the request removed from the list of requests.

**Comment by yoriiis** [comment]
Hello @dparrish, I've also reproduced the bug and I've created the issue with the good template. You can follow the issue here https://github.com/tidusjar/Ombi/issues/3153
Thanks
