### ISSUE TITLE
Ombi not checking Monitored flag in Radarr

### ISSUE THREAD

**Issue by Craig-H** [tidusjar/Ombi#3010]
**Issue**

Ombi not distinguishing Radarr movies that are monitored from those that just exist in the Radarr db.

**To reproduce**

Set-up a list in Radarr with **Enable Automatic Sync = true** and **Add Movies Monitored = false**. Run the **Net import sync** and wait to complete. This allows you to see new movies in the Radarr calendar without automatically monitoring/downloading them.

In Ombi, all Radarr un-monitored movies cannot be Requested as the Ombi UI shows the movie as **Requested** 

**Expected behavior**

In Ombi, it should be possible to request a movie that exists in Radarr but is unmonitored. 

**Ombi Version**
- Version 3.0.4256
- Plex Media Server 1.15.8.1198 
- Radarr 0.2.0.1344

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by Craig-H** [comment]
The fix has not worked. In fact, _some_ items that are monitored are now allowing "Request" and others that are not monitored are showing as "Requested". I deleted all three db's and re-setup on dev branch.

**Comment by tidusjar** [comment]
Got my condition the wrong way around... Rookie mistake.

**Comment by Craig-H** [comment]
Fixed now.
Thanks
