### ISSUE TITLE
Scheduled recently added scan does not detect new media

### ISSUE THREAD

**Issue by Do-while-Bacon** [tidusjar/Ombi#3023]
**Describe the bug**

The job that runs every 30 minutes to discover recently added media in Plex appears to kick off successfully and **does** see the new media, however, the status in Ombi never gets updated to "Available" until one of two things happens:

1. A daily full sync runs at 2:00 AM
2. Recently added (or full) sync is executed manually in the settings menu

**To Reproduce**
1. A request is approved and sent to Radarr
2. Request is fulfilled
3. Plex syncs the new media and it appears on the dashboard as recently added.
4. Ombi runs the next 30 minute scheduled job to sync recently added media
5. Media is not marked available. Requesting user is not notified.

**Expected behavior**

Media should be marked available when the next scheduled sync completes.

**Screenshots**

![unavailable](https://user-images.githubusercontent.com/9923207/59569821-f8f97600-905c-11e9-8459-2c7f13f515b5.jpg)
![sync](https://user-images.githubusercontent.com/9923207/59569822-fc8cfd00-905c-11e9-929f-9211a2162541.jpg)
![available](https://user-images.githubusercontent.com/9923207/59569823-0151b100-905d-11e9-8502-01350060826e.jpg)

**Logs**

Latest linuxserver.io docker container appears to have enabled debug logging, so my log files are huge (500+ MB). I can communicate with you on Discord to send all desired logging information.

**Ombi Version:**

- Version 3.0.4629 (linuxserver.io docker -- development tag)
- Plex 1.16.0.1226

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
