### ISSUE TITLE
new qpkg for qnap

### ISSUE THREAD

**Issue by tvann2182** [tidusjar/Ombi#3029]
**Describe the bug**
This is not a bug, i am asking when a new qpkg will be released on the qnapclub.eu store, it has been 3 months since the last release and i know that there have been revisions since then. Just looking for an update.

**To Reproduce**
1. Go to 'System'
2. Click on 'update'
3. Click on check for update
4. no updates available

**Expected behavior**
state new update available, then update the program

**Screenshots**

![ombi](https://user-images.githubusercontent.com/13427261/59794195-6cda8f00-92a6-11e9-8821-cee617b547f4.PNG)

**Desktop (please complete the following information):**
 - OS: Qnap Firmware: 4.3.6.0923

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex Version 1.16.0.1220

**Comment by tvann2182** [comment]
Qnap Firmware: 4.3.6.0923

**Comment by tidusjar** [comment]
Please post a screenshot of your about settings

**Comment by tvann2182** [comment]
current version of ombi
![ombi2](https://user-images.githubusercontent.com/13427261/59799688-deb8d580-92b2-11e9-8883-45ead8d4eb37.PNG)

**Comment by tidusjar** [comment]
Sorry but that version of Ombi is not supported by myself.

I do not own or have any involvement with that package, sorry you had to waste your money, I suggest you use the docker version.

**Comment by tvann2182** [comment]
I do not know how to do that, is there a guide that you know of that i can
follow, i thought this was your build as it points to you...

**Comment by tidusjar** [comment]
I write Ombi, But the qnap package is not supported by myself. Your server needs to support docker, then you can install the LinuxServer.io docker container

**Comment by tvann2182** [comment]
thank you for the information. I am looking into qnap containers and docker
images now. Looks like i installed everything native and now I am going to
have to make a switch to containers.
