### ISSUE TITLE
Can't send welcome email

### ISSUE THREAD

**Issue by WhiskyRiver101** [tidusjar/Ombi#3036]
**Describe the bug**
Welcome email not sending (test emails are fine).

**To Reproduce**
Confirm email working via Test. Add a user, and click send Welcome Email.

**Expected behavior**
Welcome email should be sent.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
MailKit.ServiceNotAuthenticatedException: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM5PR0201CA0019.eurprd02.prod.outlook.com]

**Desktop (please complete the following information):**
 - OS: Running inside docker. 

**Ombi Version (please complete the following information):**
 - Version 3.0.4256 
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
It states your error from your SMTP provider here: Client was not authenticated to send anonymous mail

**Comment by WhiskyRiver101** [comment]
So that means my smtp server is wrong? i use hotmail (now live) to send and i can't find the right smtp

**Comment by tidusjar** [comment]
Really? Restart ombi and try?

**Comment by WhiskyRiver101** [comment]
thanks, it is working nice and smooth.
