### ISSUE TITLE
Loading Ombi on iphone/ipad not working. (loading...)

### ISSUE THREAD

**Issue by WhiskyRiver101** [tidusjar/Ombi#3037]
**Describe the bug**
When i try to load Ombi with my iPhone or iPad it keeps saying Loading...

**To Reproduce**
Open the website or welcome invite with my iPhone or iPad. (the website is a reverse proxy with my own domain).

**Expected behavior**
The site should be loading and showing the interface.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Running on Docker, opening website on Firefox/Chrome/Safari on Windows/iPhone/iPad

**Ombi Version (please complete the following information):**
 - Version 3.0.4256 
- Media Server Plex

**Comment by tidusjar** [comment]
Does it load fine on other devices?

Does demo.ombi.io load on your iPad?

**Comment by WhiskyRiver101** [comment]
On other devices, like my friends pc using chrome or explorer, it gives the same loading...
Yes, the demo works fine.

**Comment by kyle0440** [comment]
My Ombi behind an Apache reverse proxy has been having the same issue for all devices that use the proxy since I updated Ombi to the latest version. If you access it directly, it works fine.

**Comment by tidusjar** [comment]
So the demo site is using NGINX with the proxy config located in the wiki and that seems to work fine.

**Comment by kyle0440** [comment]
For me, after digging through logs, it seems to be a manifestation of #2750 actually causing the login issues - which delivers the proper 500 error when accessing directly but for some reason delivers a 404 error instead when going through the reverse proxy.
