### ISSUE TITLE
Users are not logged out when deleted

### ISSUE THREAD

**Issue by Fronix** [tidusjar/Ombi#3042]
**Describe the bug**
If a user is logged in and I delete the user, they are not logged out properly. They can't request, see issues or edit usersettings but it be a security issue, so they should be properly logged out.

**To Reproduce**
1. Go to user settings
2. Delete a user while they are logged in

**Expected behavior**
They should be sent to the landing page 

**Desktop (please complete the following information):**
 - OS: Linux (Debian)

**Ombi Version (please complete the following information):**
 - Version: 3.0.4639

**Comment by tidusjar** [comment]
What's the security issue here?

**Comment by Fronix** [comment]
I would think logging a deleted user out is best practice no?

**Comment by tidusjar** [comment]
I understand the problem but you stated:

> but it be a security issue

What is the security issue?

**Comment by Fronix** [comment]
I meant to say it could be a potential security issue. The security issue would be if some  code isnt using the user id and the deleted user can still use that function, even though it shouldn't be possible. It's more of a "bad shit can happen" problem.

**Comment by goldenpipes** [comment]
could a cookie check be implemented or something @tidusjar ?
