### ISSUE TITLE
Ombi does not sync with couchpotato/sickrage

### ISSUE THREAD

**Issue by Merrick28** [tidusjar/Ombi#3046]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
If you can't put the effort of filling in the template then I cannot help.

**Comment by Merrick28** [comment]
Sorry, I don't undersatnd what happened, I sepnd some time filling the template... and all vanished. Anyways, I will open a new one :-/
