### ISSUE TITLE
"View On Plex" uses wrong server ID

### ISSUE THREAD

**Issue by Inrego** [tidusjar/Ombi#3053]
**Describe the bug**
A wrong server ID was grabbed for my Plex Server. I went to the Plex config and changed the Machine Identifier, but the generated Plex links didn't change. By default, the Machine Identifier was set to `cee7fbd8562c0e93c729ca6f59cc98332c23b9d4`, and example of link from "View On Plex" is: https://app.plex.tv/desktop#!/server/cee7fbd8562c0e93c729ca6f59cc98332c23b9d4/details?key=library%2Fmetadata%2F30363

I went to plex config and changed Machine Identifier to db5687dd4913b37c86118834a774ef2aa7f7a27b, but alas - the link on "View On Plex" remains to be https://app.plex.tv/desktop#!/server/cee7fbd8562c0e93c729ca6f59cc98332c23b9d4/details?key=library%2Fmetadata%2F30363

**To Reproduce**
1. Go to Settings
2. Choose Media Server -> Plex
3. Change value of Machine Identifier
4. View On Plex link doesn't change, and keeps linking to old server id.

**Expected behavior**
I expected the link to update after I updated the Machine Identifier.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4659
- Plex Version 3.104.1

**Comment by tidusjar** [comment]
This is more of an limitation rather than bug, so we store the machine ID against the media item once we cache it, because you can have multiple servers we need to know which server it came from.

So when the Media Refresh job runs (every 5 days by default) it will clear it out and pickup the new token.

**Comment by chrisdelrey** [comment]
Can you force the sync? I'm running into a very similar issue. I have two Plex Server running on Ubuntu. I had availability issues with one, it was offline for a couple of days. now when I log in via the IP:32400 it will show the other server? Same behavior via the portal access. I confirmed the ProcessMachineIdentifier is unique on both servers. Is there anyway I can force the sync?
