### ISSUE TITLE
Newsletter: Recent TV Shows and Movies not added due to TMDB API URL error

### ISSUE THREAD

**Issue by jennec** [tidusjar/Ombi#3055]
**Describe the bug**
Recently added TV Shows and Movies not showing Newsletter. When viewing the consoel output the following line is observed and the job never finishes:

info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 4506,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 4356,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 4206,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 4056,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3906,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3756,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3606,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3456,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3306,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3156,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 3006,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2856,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2706,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2556,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2406,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2256,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 2106,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1956,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1806,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1656,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1506,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1356,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1206,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1056,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 906,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 756,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 606,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 456,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 306,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 156,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 6,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      We have finished caching the episodes.,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Total Epsiodes found for TV  - Anime = 1584,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1434,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1284,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 1134,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 984,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 834,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 684,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 534,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 384,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 234,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      Processed 150 more episodes. Total Remaining 84,
info: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002],
      We have finished caching the episodes.,
info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0],
      Plex Movies to send: 0,
info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0],
      Emby Movies to send: 0,
info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0],
      Albums to send: 0,
info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0],
      Plex Episodes to send: 20914,
info: Ombi.Schedule.Jobs.Ombi.NewsletterJob[0],
      Emby Episodes to send: 0,
**fail: Ombi.Api.Api[1000],
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00,**

**To Reproduce**
Sync Plex Content, either by schedule or manuall
View Log output
See fail message.
Send Test Newsletter
Observe no content in newsletter.

**Expected behavior**
Recent TV and Movies to show on newsletter

**Screenshots**

**Logs
[Logs.zip](https://github.com/tidusjar/Ombi/files/3358873/Logs.zip)

**Desktop (please complete the following information):**
 - OS: Linuxserver/ombi docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4659
- Media Server Plex

**Additional context**
I only installed this two days, but since then I have tested with requests being completed via Ombi and also with media that added via Sonarr or Radarr.   In this time several movies and TV Show Episodes have been added.  But do not show in the newsletter.  Ombi can see that they are available though.  

This was reported on #2927 back in Paril it seems with no resolution.  From what I can tell Ombi is able to scan plex but is not neceaarily able to get info from TMDB using that particular API URL.  Perhaps this is a limit imposed by TMDB in some way or the URL or API key has changed?

**Comment by tidusjar** [comment]
Update the database (Button in the newsletter settings), it's trying to send out too much

**Comment by jennec** [comment]
I had done that previously, before logging this ticket.  But I did this again just now for you, still no TV Shows or Movies in the newsletter (3 more episodes have been added since the ticket was logged).  The out put I got were was the same as before, but it also started to do a metadat refresh and the following lines appear for every single movie:


info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      The Media item Captive State does not have a TheMovieDbId, searching for TheMovieDbId
fail: Ombi.Api.Api[1000]
      StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/find/tt5968394?api_key=b8eabaf5608b88d0298aa189dd90bf00&external_source=imdb_id
fail: Ombi.Api.Api[1000]
      Retrying RequestUri: http://api.themoviedb.org/3/find/tt5968394?api_key=b8eabaf5608b88d0298aa189dd90bf00&external_source=imdb_id Because we got Status Code: TooManyRequests
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Setting Show Captive State because we have ImdbId, result: True

Additionally after the movies each TV show gets the following output as well:
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      Setting Show How I Met Your Mother because we have TvDbId, result: True
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      The media item How I Met Your Mother does not have a ImdbId, searching for ImdbId
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
      The show How I Met Your Mother has tvdbid but not ImdbId, searching for ImdbId

So it would seem that there is a limit to the number of requests the TMDB, TVDB and IMDB will process from an single IP address within a certain time period.  I imagine that this might contribute to the situation I find myself in.  

Reading your response, i can imagein two scenarios then where the newletter will always fail to send out recently added items:
1: If too many requests have been made to the TMDB or other metadata resources because this is a new install where a lot of content is already present in Plex or Emby.
2: If there is too many entries to send in a newletter (from what I cleam from your response)

Would it be possible to add some event handling in these situtaions:
1. Adding a notification that newsletters will not functions on a new install of obmi because the media server has too much content to include in one newsletter.  Perhaps the newsletter could be split intomultiple edditions when x number of recently added media is detected.
2. An alert to the admin that the newsletter will not contain any content this week because the API for accessing metadata is not work or is over used and cananot obtain this content.  

Without those it would seem to those looking to use Ombi that is cannot do what it says it can do, leading to people loosing faith in its abilities and not using it.

Additionally, I can unsertand the tempation to quickly close tickets with a suggested solution where you beleive the issue is a duplicate.  But in this instance it gives the impression you have not looked into my issues very closely and have made an assumption of the root cause.  Granted we cannot always reply or look into things because other commitments are taking precidence, but to close a ticket without first confirming a solutuion is not a confidence builder to the end user.

**Comment by tidusjar** [comment]
Apologies for prematurely closing the issue.

So hopefully this will clarify the way the newsletter works.

When it is triggered it will look in the Ombi database to see what Plex/Emby content Ombi has synced (From the Plex/Emby Sync Jobs). It then compares to what items it has previously sent out in the newsletter (So in a fresh install, It is always recommended to click the update database button to tell ombi that all of the current content has been sent via the newsletter).

So there is the dependency that the Ombi Plex/Emby job has picked up the new content from the media server, Once that has happened then the newsletter will recognize that there is a new item to send. If there is nothing new then nothing will be sent out even know it was scheduled (So we don't send duplicate/empty emails).

Does that clear things up for you?

If you are still having issues then it might be worth seeing if Ombi has picked up the new content from Plex/Emby (For movies just search for them and see if the View on Plex/Emby button appears, or if it is a request, the request should automatically be marked as available).

Regarding the IP request limit, this is something I am aware of and I've already made vast improvements in the V4 version of Ombi (not yet ready) so please be patient with me regarding this.

**Comment by pressRtowin** [comment]
My newsletter has been broken for months. I'm getting this similar error every time I try to send a test:

```
Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/find/?api_key=b8eabaf5608b88d0298aa189dd90bf00&external_source=imdb_id
```

No amount of updating the database, manually rescanning, clearing data and resyncing, etc. has resolved this.

**Comment by tidusjar** [comment]
Please can you raise a new issue, as everything has moves on since this original issue.
