### ISSUE TITLE
Issues using updater inside Ombi

### ISSUE THREAD

**Issue by jonnwhite1** [tidusjar/Ombi#3057]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Closing because if you can't be bothered to fill in the template, then I'm not bothering to help.

**Comment by jonnwhite1** [comment]
Sorry! I did fill it in but I don’t know what happened there as I even copied code! I’ll repost tomorrow. Sorry again!!

**Comment by tidusjar** [comment]
Ah ok no problem, some people don't even bother filling it in, that was the reason for my response! 

If it's regarding the autoupdater there is already an open issue about it
