### ISSUE TITLE
Newsletter emails going to back to users spam folders

### ISSUE THREAD

**Issue by cjattard** [tidusjar/Ombi#3062]
**Describe the bug**
following update 3.0.4659 emails to users are now going into spam - this is likely because the "to" recipient field is now blank and users are BCC'd.

I seem to recall this problem was fixed in a previous release - and has since resurfaced. 

**To Reproduce**
1. Go to 'emails to users are going into spam folder by default setup on gmail'
2. Click on 'email'
3. Scroll down to 'to field'
4. See error - no recipient address most likely breaching spam condition

**Expected behavior**
email received into main email box with recipient email address
**Screenshots**
not applicable
**Logs (Logs directory where Ombi is located)**
not applicable
**Desktop (please complete the following information):**
 - OS: OSX Mojave

**Ombi Version (please complete the following information):**
 - Version 3.0.4659
- Media Server - not applicable

**Additional context**
I think this was previously fixed and looks like a new fault with the latest release

**Comment by nwithan8** [comment]
Did you fill out the Email Sender section? I know email clients like Gmail will kick something if there isn't a "friendly name" (i.e. from line reads: My Name <myemail@gmail.com>)
