### ISSUE TITLE
Case sensitive plex username causing SSO from orgranizr to fail

### ISSUE THREAD

**Issue by riemers** [tidusjar/Ombi#3064]
**Describe the bug**
If the Organizr user logs in as "username" and it tries to go to Ombi by means of SSO it will fail if the user in the Plex import user list of Ombi is called "Username" the list is case sensitive.

Most of the users don't even know it has a uppercase first letter since lowercase works too on plex logins.

**Expected behavior**
To be able to login with lowercase username too. (should not be case sensitive)

**Ombi Version (please complete the following information):**
 - Version 3.0.4659 (master)

**Additional context**
Something similar in the past https://github.com/tidusjar/Ombi/issues/882 (might not be the right context, but looks same back then) could not find anything else matching that. Did search for it in the code, but lot has changed since then :)

**Comment by tidusjar** [comment]
Any idea what API Org is using to login?

**Comment by riemers** [comment]
I don't really, but the settings i have placed in it are just the "http://ombi:3579" and then the token.

As described here https://docs.organizr.app/books/setup-features/page/sso#bkmrk-ombi. It uses an auth token too from what i can tell. If that fails to map it won't continue. (assuming this is part of the info your looking for) otherwise point me where to look and i will see if i can find the information.

**Comment by tidusjar** [comment]
Are you sure this is the behaviour you are seeing? Since I don't understand how casing matters. 

Can you login directly on Ombi with a different case username?

**Comment by riemers** [comment]
I think i narrowed it down a bit. The first account i create on Organizr was with different usercase then the one that got imported on Ombi. Since i imported all my users in Organizr it skipped my account because it was already there not fixing the one letter with different casing. I fixed it manually for my user and that seems to be ok now. Checked all other users and they have the same case as the ones in Organizer now.

But i would presume casing should not matter when it comes to usernames. So if i now change my username in Ombi to "riemers" instead of "Riemers" as example it would fail to log me in automaticly. (since the cookie auth as described in the url above will have the "Riemers" with uppercase in it) and that is what most likely made it fail.

**Comment by tidusjar** [comment]
So what seems to happen is that Org calls out to the Ombi API with the username and password and Ombi returns a JWT Token. Org then pushes that into a cookie. 
When org goes to the ombi cookie page we read out the JWT token from the cookie and then you are authenticated.

I am struggling to see how casing on usernames matter here. 😢

**Comment by riemers** [comment]
I am no expert, i only know that when i changed my username to match the one i have in organizr it worked fine. We could also just say, it is a one off 'issue' and by changing the name it is fine now and be done with it. I just thought it is good to report these kinds of things :)

**Comment by riemers** [comment]
I think we can call this as , it is solved. A weird one and lets move on..
