### ISSUE TITLE
Telegram Notification not sending to user

### ISSUE THREAD

**Issue by Marct27** [tidusjar/Ombi#3070]
**Describe the bug**
When telegram notifications are configured via a bot, the notifications only go to the user configured on the notifications configuration, including the request accepted / denied and no notification are sent to the requesting user.

**To Reproduce**
Configure bot api
Configure admin / chat group ID
Configure user id in user management
have user request a movie / show
Admin accept or deny request
*user has also initiated a chat with the bot*

**Expected behavior**
Notification come to admin, aproval / deny request be only sent to user and not admin.

**Desktop (please complete the following information):**
 - OS: linuxserver/ombi

**Ombi Version (please complete the following information):**
 - Version 3.0.4659
- Media Server Plex

**Comment by tidusjar** [comment]
This is a current limitation to the way notifications currently work in the system

**Comment by Marct27** [comment]
Many Thanks
