### ISSUE TITLE
Plex oAuth Authentication Broken

### ISSUE THREAD

**Issue by jeffe** [tidusjar/Ombi#3073]
**Describe the bug**
Plex appears to have updated their API to enforce the requirement of a new header variable (X-Plex-Product:)
It appears Ombi doesn't currently include this parameter, as a result auth attempts via plex oAuth are failing.

**To Reproduce**
Attempt to login via Plex oAuth

**Expected behavior**
You should login.

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
Log Output is:
fail: Ombi.Api.Api[1000]

StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/XXXXXXXXX

**Desktop (please complete the following information):**
 All Browsers, All Platforms

**Ombi Version (please complete the following information):**
Version: Current
Plex Version: Plex Pass Current

**Additional context**
Discussion on Plex Forum:
https://forums.plex.tv/t/plex-oauth-not-working-with-tautulli-ombi-etc/433945

**Comment by tidusjar** [comment]
This is incorrect, Ombi does provide the X-Plex-Product parameter, and it sets it to `Ombi`. 

Plex have recently changed how this works with their OAuth that is currently only allowing requests that Identify themself as `Plex Web` to authenticate.

**Comment by jeffe** [comment]
Ah, apologies, my mistake.

Is there any known information on if Plex will open the scope of allowed application identifiers again? Or is there an alternative solution (short of modifying the local instance to send a different client identifier)

**Comment by tidusjar** [comment]
People hope this is just a mistake on Plex's end and that it will be reverted. I'm not 100% sure if this wasn't their initial intention.

For now I'll make a change to let Ombi identify itself as the Plex Web Client to let us through. I'll push out a stable release in the next few hours.

**Comment by jeffe** [comment]
Thank you!
