### ISSUE TITLE
Landing Page states server is offline when it is not.

### ISSUE THREAD

**Issue by gbdavidx** [tidusjar/Ombi#3075]
**Describe the bug**

**To Reproduce**
1. Enable ombi and type in a status message

**Expected behavior**
1.  Display message created by me without server is offline message

Landing page shows server is offline when it is not

**Screenshots**
https://imgur.com/a/d9IHwW2

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by bmn001** [comment]
I just ran into this as well.

Not sure what the solution is other than to nuke the entire installation and start over :(

**Comment by tidusjar** [comment]
Please can you raise a new issue
