### ISSUE TITLE
Emby Server - Item Details

### ISSUE THREAD

**Issue by zippy-man** [tidusjar/Ombi#3078]
**Describe the bug**
Emby links (on search) are broken due to url change

**To Reproduce**
1. Open Ombi
2. Find a title tha is in Emby
3. Click on View on Emby
4. Page does not load

**Expected behavior**
Item is shown in Emby

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Emby

**Additional context**
Current link: http://app.emby.media/#!/itemdetails.html?id=[item id]
New link: http://app.emby.media/#!/item/item.html?id=[item id]

**Comment by tidusjar** [comment]
Is this a URL change in Emby?

When did this happen?

**Comment by zippy-man** [comment]
Yes this was a change with Emby server. I am not exactly sure when the change happened but very recently. 

Emby server is version 4.2.0.32

**Comment by NiklasOlofsson** [comment]
Same here. Running the Emby beta 4.2.033 so it could be only in beta for now..

**Comment by crxo1** [comment]
The URL is also changed in the 4.2.0.40 final release, which was released 7 days ago.

**Comment by NiklasOlofsson** [comment]
Yep. I'm on latest stable now. The url has definitively changed. :)

**Comment by Aerion** [comment]
_Just a note about Jellyfin, the open-source fork of Emby, if this were to be fixed._

Jellyfin didn't change still uses [itemdetails.html](https://github.com/jellyfin/jellyfin-web/blob/4a3bf18d73eb2071b6cd69ae94bd27d734b19170/src/scripts/routes.js#L139), so if the url were to change in Ombi, could it be configurable?

Currently, in the Emby configuration page, the parameter [_Externally Facing Hostname_](https://github.com/tidusjar/Ombi/blob/3b46f14c08b575c6bf90dbf06357ddd7914123ca/src/Ombi.Core/Rule/Rules/Search/EmbyAvailabilityRule.cs#L71) is used to specify the hostname used for configuring View on Emby hostname url. I suppose it could be also be used to specify if the user is using Emby (itemdetails.html) or an older version of Emby/Jellyfin (item/item.html).

**Comment by gcorgnet** [comment]
This says "merged" but it seems to still be broken in my current version (3.0.4740 - develop)
Do I need to wait for this to be included in a release?
Thanks

**Comment by yoriiis** [comment]
Hello, is there any news about this issue ? It is broken on the last release (3.0.4680).
Thanks

**Comment by amadeusrotundo** [comment]
still broken.  Version 3.0.4680

**Comment by n1lsfps** [comment]
still broken

**Comment by aksiksi** [comment]
Can we get a minor release with this merged?

**Comment by tidusjar** [comment]
See above comments

**Comment by yoriiis** [comment]
I found the PR with the fix, it was merged into `develop` branch on 15 august 2019.
The detail is available here: https://github.com/tidusjar/Ombi/commit/e019402a039b3853b7b91b7aa5cf89fb1d2a16d7

Is it also possible to merged into `master` branch @tidusjar ?

**Comment by tidusjar** [comment]
The PR didn't seem to fully fix the issue. So if I merge it, it will still be broken

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
