### ISSUE TITLE
Sonarr shows episode available but Ombi does not

### ISSUE THREAD

**Issue by arjohnson15** [tidusjar/Ombi#3081]
**Describe the bug**
Sonarr shows all episodes for a tv show as downloaded but muli episode files that are labeled "tvshow.S01E01-02 are only showing episode 1 as available in Ombi. I label them this way so plex doesnt play the same episode twice but Sonarr will show the episode as downloaded.
So the episode is actually missing in Plex but not in sonar because of the labeling.
If Ombi is pulling its available content from Plex and not sonarr at all could there be a way to mark an episode as available manually in Ombi?

**To Reproduce**
1. label and episode s01e01-02 instead of what plex wants which would be s01e01e02.
2. sonarr should show both episodes as available but plex will only show the first episode (I then relabel it manually).
3. Ombi will then show the second episode as not available also.

**Expected behavior**
**Screenshots**
**Logs (Logs directory where Ombi is located)**
**Desktop (please complete the following information):**
**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
Can you post some screenshots of the file name, what it looks like in sonarr and Plex ?

**Comment by arjohnson15** [comment]
![file name](https://user-images.githubusercontent.com/49290460/61553803-e342ec00-aa20-11e9-960e-d7878837effb.PNG)

In Ombi it shows "processing request"
![ombi image](https://user-images.githubusercontent.com/49290460/61553801-e342ec00-aa20-11e9-8aa4-4f8bcc6ae78d.PNG)
In Plex with the way I label it Plex wont make an episode 18
![plex image](https://user-images.githubusercontent.com/49290460/61553802-e342ec00-aa20-11e9-859f-66f1d7dae3dc.PNG)
With this label structure sonarr will see it as available tho and stop looking for it. 
![sonarr image](https://user-images.githubusercontent.com/49290460/61553958-6106f780-aa21-11e9-8bcf-b8230bc7f547.PNG)

**Comment by arjohnson15** [comment]
I manually relabel the episode in plex to make it say "part 1 & 2"... If I label the file as "The Challenge - S33E17E18" instead of S33E17-18 sonarr will still see both episodes but plex will make an episode 17 and 18 and they will play the same file.

**Comment by arjohnson15** [comment]
as a test I removed an episode from my file structure. Plex and sonarr both show it missing after a scan but ombi has the show marked as available still after running a full sync. 
not exactly related just something else I found.

**Comment by goldenpipes** [comment]
I have never had this problem using the conventional plex naming scheme for multi part episodes. Plex always finds them as well.
![image](https://user-images.githubusercontent.com/6140137/61568737-19489600-aa4a-11e9-9aad-8b5ca7acfaea.png)
![image](https://user-images.githubusercontent.com/6140137/61568756-25ccee80-aa4a-11e9-9e8d-542370ce344e.png)
![image](https://user-images.githubusercontent.com/6140137/61568782-39785500-aa4a-11e9-9571-2a0a42b66fe3.png)

**Comment by goldenpipes** [comment]
I'm closing this issue since there is nothing that can be done on Ombi's side. Unless we don't rely on Plex for Item availability.
