### ISSUE TITLE
User management doesnt show "RequestMovie" or "RequestSeries" roles

### ISSUE THREAD

**Issue by Stormyy** [tidusjar/Ombi#3085]
**Describe the bug**
Since updating to version 3.0.4680 the roles "Request movies"and "Request series" are not shown anymore. Sonarr and radarr are both enabled with a valid connection

**To Reproduce**
Go to User importer or add/edit user screen

**Expected behavior**
Roles "Request movies"and "Request series" should show

**Screenshots**
![](https://snag.gy/b34Lfc.jpg)

**Desktop (please complete the following information):**
 - OS: Linux, Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
 - Media Server Plex

**Comment by tidusjar** [comment]
Looks like something has gone wrong with the database. You sure this happened after updating?

**Comment by maxtrax04** [comment]
I can confirm that I also have this issue on a fresh install with the current version. If there is something I can try/submit, please advise

OS: Microsoft Windows 10.0.18362
Ombi Version: 3.0.4680 
Media Server: Plex
