### ISSUE TITLE
Lidar integration fails to add album

### ISSUE THREAD

**Issue by zombiehoffa** [tidusjar/Ombi#3087]
**Describe the bug**
I connected my lidarr instance to ombi which passed connectivity test, then I went to search, music, artist, searched for an artist  (there's no way to request the artist, which is weird for lidar because it basically works on the artist being requested and usually tries to get all past and future albums)  Then I clicked "view albums" and requested an album and it failed with the following log output (I did this a couple times, I tried to choose a whole instance of ding it once, I apologize if I ended up snipping half way between to attempts):

  Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 120
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 43
[40m[1m[33mwarn[39m[22m[49m: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending album but failed. Message: Something went wrong!
[40m[1m[33mwarn[39m[22m[49m: Ombi.Core.Engine.MusicRequestEngine[0]
      Tried auto sending Album but failed. Message: Something went wrong!
[40m[32minfo[39m[22m[49m: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for Test, for agent Mobile
[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.3.106:8686/api/v1/artist
[41m[30mfail[39m[22m[49m: Ombi.Core.Senders.MusicSender[0]

**To Reproduce**
Do what I did in the description, try to request an album
**Expected behavior**
I would expect the artist to be added to lidar  with that album marked to be searched for at a bare minimum (after approval if that user requires approval). What I would really like this to do would be to also have a request artist button on the artist to just add the artist and add all albums to search, a way for me as the admin to set default behaviour when an albuum is requested and approved (i.e. let me choose to just add all albums to search when one from a new artist is requested or let it only select the one album to be added to search)

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
windows, accessing ombi latest via brave browser.
**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]
4.0.4680 running in docker off linuxserver image.
**Additional context**

**Comment by tidusjar** [comment]
Please post an image of your settings?

**Comment by zombiehoffa** [comment]
![image](https://user-images.githubusercontent.com/627402/61715059-847bbc00-ad19-11e9-98dd-2b37e82ccc5b.png)

**Comment by zombiehoffa** [comment]
so "get metadata" worked instead of apparently timing out the first time I set this up and the artist did end up being added to lidarr once I selected something for metadata profile, but with no albums set to monitored, I suspect because musicbrainz doesn't have the album I requested associated with the artist.  Sorry for wasting time here (It would still be awesome if you added a "request artist" button  to add the artist with all albums monitored.)

**Comment by tidusjar** [comment]
That's coming in V4
