### ISSUE TITLE
0 Episodes in a series marks request as available

### ISSUE THREAD

**Issue by Inrego** [tidusjar/Ombi#3090]
**Describe the bug**
When adding a newly announced TV show, which doesn't yet have any episodes, then the request gets marked as available, and notification sent to requester. I'd expect a workaround would be to check that there are more than 0 episodes, before checking if all episodes are available.

**To Reproduce**
1. Add newly announced show (right now, I've experienced it with "His Dark Materials").
2. Wait
3. You will get notified that the request is available.

**Expected behavior**
I should get the available notification, only when it's actually available.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 3.0.4659

**Comment by tidusjar** [comment]
Problem with this is that it will never become available because you have requested no episodes... I think we should block you from requesting this yet,

**Comment by Inrego** [comment]
I think there's a valid use case in requesting future shows. Maybe another workaround like creating a phantom episode, or being able to request a show (regardless of episodes)?

**Comment by Inrego** [comment]
I know blocking the request is the easy workaround, but not really logical for the end user

**Comment by tidusjar** [comment]
The issue would be that I'd need to create some sort of background worker to constantly poll to see if we have any new episodes. That would be quite a large piece of work, that's my only issue with it. But yes you are right

**Comment by tidusjar** [comment]
I can't even search for "His Dark Materials". It doesn't appear. Do you have another example?

**Comment by Inrego** [comment]
I used to. But that one too disappeared from search. It's hard times living on the edge 😅
