### ISSUE TITLE
Welcome Email Does Not Contain URL

### ISSUE THREAD

**Issue by alex12342** [tidusjar/Ombi#3098]
**Describe the bug**
The welcome email contains no URL for users to follow

**To Reproduce**
1. Go to user management
2. Click on send welcome email (sent to test account)
3. check email on a test account
4. welcome email arrives without URL

**Expected behavior**

the welcome email should contain a URL

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Additional context**
welcome email is structured as follows:

Hello! You have been invited to use {ApplicationName}! You can login here: {ApplicationUrl}

the url does not get sent in the email

**Comment by tidusjar** [comment]
Have you added your application URL in the settings?
![image](https://user-images.githubusercontent.com/6642220/62279378-dcb16d00-b441-11e9-9509-4dd370e71c82.png)
