### ISSUE TITLE
Ombi creates dead links to Plex movie

### ISSUE THREAD

**Issue by callahan22** [tidusjar/Ombi#3100]
**Describe the bug**
Ombi generates dead Plex links for movies

**To Reproduce**
1. Click the Search link
2. Search for a movie you already have and thus it's highlighted in green
3. Click the link "View on Plex"
4. You're taken to a dead link.

**Expected behavior**
Expected it to take you to the Plex movie page so you can play the movie in the web browser. The link itself is missing a string. Take "The Matrix" for the sake of an example. The link generated in Ombi is: https://app.plex.tv/desktop#!/server//details?key=library%2Fmetadata%2F8073
The real link should read: https://app.plex.tv/desktop#!/server/ab32e8ad179c5b52a0710fa231c54f4d2d6a2c39/details?key=%2Flibrary%2Fmetadata%2F8073
It's missing the "ab32e8ad179c5b52a0710fa231c54f4d2d6a2c39" string. You can see where is should go in the Ombi URL section: "//" I'm not sure what this string represents, the movie ID in Plex's DB perhaps but either way, it might be something you may want to look into.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - 3.0.4680 (Docker)
- Plex
- Connected Services: Plex, Radarr, Sonarr
- Webserver info: ombi's internal webserver + reverse proxy via nginx

**Comment by tidusjar** [comment]
You need to fill in your machine key in the Plex Settings page.

**Comment by callahan22** [comment]
From what I've read, the machine ID is filled out when I do my initial sync
of my Plex server. I've removed and added it back in a good few times but
the machine ID field is never populated. Is this something I can find
myself? Is it just asking for the hostname of my Plex server? If not, where
do I pull this info from on my Plex box?

Thanks again for your help.

**Comment by callahan22** [comment]
So it appears my ID is: ab32e8ad179c5b52a0710fa231c54f4d2d6a2c39 - I've
pulled that from the Plex URLs. Have entered it into the Machine ID field
in Ombi but the links are still dead.

**Comment by tidusjar** [comment]
Yes because we need to support multiple Plex servers, we save the machine id against the media item when we scan it. So if you delete your Ombiexternal database and then restart ombi and run your sync it will sort it all out.

**Comment by callahan22** [comment]
Perfect. This has fixed the issue.

Thanks.
