### ISSUE TITLE
Change to newer and better themoviedb API endpoint for similar media

### ISSUE THREAD

**Issue by Phault** [tidusjar/Ombi#3106]
**Describe the bug**
Ombi is currently using the old /movie/{movie_id}/similar endpoint, instead of the newer /movie/{movie_id}/recommendations endpoint. The old endpoint uses a different and in some cases horrible method for finding similar media.

[The themoviedb founder recommends using the newer API and themoviedb site itself uses it.](https://www.themoviedb.org/talk/59efc7fcc3a3680682004dba?language=en-US)

**To Reproduce**
1. Search movies for 'Furious 7'
2. Click on 'Similar.'
4. Notice none of the listed movies are relevant to the movie.
5. Go to themoviedb.org
6. Search for Furious 7
7. Scroll down to Recommendations
8. Notice all the listed movies are relevant

**Expected behavior**
All or most movies should be relevant.

**Screenshots**
[Ombi's similar movies](https://imgur.com/td8pwf6)
[Themoviedb's recommended movies](https://imgur.com/0MQ7K2s)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
N/A

**Ombi Version (please complete the following information):**
 - Version 3.0.4689

**Additional context**

**Comment by tidusjar** [comment]
This has actually been resolved in V4 already!
