### ISSUE TITLE
Mobile app - Red warning with positive message.

### ISSUE THREAD

**Issue by callahan22** [tidusjar/Ombi#3109]
**Describe the bug**
More a feature request. On the mobile app, when you request a movie and that request is accepted, you get a red bar notification pop up at the bottom of the screen. I, (and I appreciate this might well be a personal preference), always think that the request has failed. Might I suggest that as it's a positive message, that the banner is in green and save the red for any failures (as you do with any failures to log into the app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a movie you want in the Request section of the app.
2. Tap the Request button.
3. Red <warning> :-) popup shows to say request has been accepted.

**Expected behaviour**
A green positive pop up instead of a red warning pop up.

**Ombi Version:**
 - Version: Latest mobile app.
- Media Server: Plex

**Comment by tidusjar** [comment]
Makes sense, I'll make the change in the app
