### ISSUE TITLE
Another welcome email won't send issue

### ISSUE THREAD

**Issue by jorjenava** [tidusjar/Ombi#3111]
**Describe the bug**
When I click on the button to send the welcome email next to a user no email is sent and nothing is logged.

**To Reproduce**
1. Go to user management
2. Click "Send Welcome Email" next to a user

**Expected behavior**
Welcome email to be sent to user.

**Screenshots**
![email_settings](https://user-images.githubusercontent.com/2952710/62498603-c727a480-b7ad-11e9-8f0a-69c9bec613a4.png)

![customization_settings](https://user-images.githubusercontent.com/2952710/62498594-c3941d80-b7ad-11e9-9438-f54f1166f9c6.png)

**Logs (Logs directory where Ombi is located)**
Nothing in the log is applicable. I can see test emails and mass emails in the log. Whenever I try to send a welcome email nothing happens in the log.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux bullseye/sid

**Ombi Version (please complete the following information):**
 - Version 3.0.4680 (from apt)
- Media Server Plex

**Additional context**
Test emails work fine. Mass emails work fine. I have set an application url under customization and I have made sure that the welcome email is enabled under the email settings. I have tried sending the email to user's imported from plex as well as user's created manually using ombi. I've also ensured the email addresses I'm trying to send the welcome email to are valid. I have tried disabling and reenabling the welcome emails. I have tried restarting the ombi service.

**Comment by tidusjar** [comment]
Does the user you are attempting to send it to actually have an email address? you sure there is nothing in the logs?

**Comment by jorjenava** [comment]
Yes and yes. I've tried sending it to multiple users. They all have email addresses correctly configured and none of them get the email. I am certain nothing is being logged when I click the button. I have a tail running on the log file when I click the button and nothing happens.

**Comment by tidusjar** [comment]
Nothing in the users spam/junk folders?

**Comment by jorjenava** [comment]
Correct. The emails are not going into spam or junk folders. It seems they are getting the "Recently Added Content" emails though. I'm also getting issue and request emails so it's odd that that is literally the only thing that's not working.
