### ISSUE TITLE
"New Request" email notification not working/test notification works

### ISSUE THREAD

**Issue by Ir0nhide27** [tidusjar/Ombi#3112]
**Describe the bug**
When I have a user submit a request, no notification is sent to the admin (me). The test email notification works fine and when I submit a request I can receive the "your request was approved/denied" email notification.

**To Reproduce**

User submits the request for a new TV show (only TV approvals enabled)

**Expected behavior**
Admin should receive email notification of new request. No email is sent.

**Logs** (Logs directory where Ombi is located)
https://drive.google.com/file/d/1Z1dbnZv79QRxWM3HQwRP1Ty_K4boEHOg/view?usp=sharing

**Desktop:**

OS: Windows Server 2016 Datacenter

**Ombi Version:**

Version 3.0.4256
Media Server: Plex

**Additional context:**
Test emails work fine. I have tried restarting the ombi service. I assume SMTP settings are configured correctly since I can receive the test email and other user notifications. I am using office 365 SMTP servers. Users have the Request Movie, Auto Approve Movie & Request TV Roles. I have the Admin role.

EDIT: More context, I can see the requests from the users waiting for approval in Ombi when I login.

**Comment by tidusjar** [comment]
What permissions do the user have?

**Comment by Ir0nhide27** [comment]
All users have the Request Movie, Auto Approve Movie & Request TV Roles. I have the Admin role.

**Comment by tidusjar** [comment]
Check your settings under Ombi. 

There is an option to disable notifications if they have auto approve permissions.

**Comment by Ir0nhide27** [comment]
I saw that setting and have it enabled. Correct me if I'm wrong but in my case they only have the auto approve role for movies so shouldn't it still notify me for tv show requests? Or does it disable all notifications if any auto approve role is assigned?

**Comment by tidusjar** [comment]
I cannot explain why the test emails work, but you defiantly have issues with your SMTP setup:

The below is from your log file  
```
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

**Comment by Ir0nhide27** [comment]
I saw that when I was trying to investigate the issue but I don't know if it's talking about Microsoft's certificate or mine (using office365 SMTP servers) I don't have an SSL certificate so do I need one?

**Comment by tidusjar** [comment]
https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate

There's not much I can suggest here, it's outside of my control

**Comment by Ir0nhide27** [comment]
The issue appears to have been related to some DNS misconfiguration on my network that happened at the same time I was testing notification emails which caused the SMTP certificate error in the logs. I just had a user submit 2 requests for TV shows and I got notified via email. I'll close the issue.
