### ISSUE TITLE
Login loop with a reverse proxy and custom domain

### ISSUE THREAD

**Issue by goodpunk6** [tidusjar/Ombi#3113]
**Describe the bug**
when I use the ip and port to access ombi via a web browser it works fine. I can login no problem. When I try to use the custom domain, I am unable to login. I am prompted but either nothing happens after I enter my password and hit enter, or what should be the plex login popup just reopens the same login page ombi has.
**To Reproduce**
put ombi behind a nginx reverse proxy, apply a custom domain, and then use that domain to try and login

**Expected behavior**
I am expecting to login
**Screenshots**

**Logs (Logs directory where Ombi is located)**
I don't know where this is
**Desktop (please complete the following information):**
 Ombi is running on a cloud VM
**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Additional context**
works fine when using the IP address in any browser

**Comment by tidusjar** [comment]
Sounds like your issue is with your reverse proxy setup. I am running ombi behind nginx with a custom domain, and so are many others. I suggest you take a look at the wiki for proxy examples and If that doesn't work then jump on discord and someone should be able to assist you.
