### ISSUE TITLE
Landing/Login Page Backgrounds not showing.

### ISSUE THREAD

**Issue by almulder** [tidusjar/Ombi#3114]
Updated to the latest build and now the backgrounds are not showing. I have even edited the 'appsettings.json' file and removed all the TV and all the Movies, and added in 2 movies for testing, and nothing ever shows up.

Here is what I have:
`  "LandingPageBackground": {
    "Movies": [
      384018,
      420818
    ],
    "TvShows": [
]
  },
`

**Comment by loheiman** [comment]
I figured out why this is. It's because TV shows require the TDVB ID, not the MovieDB ID.
