### ISSUE TITLE
resolved issues never get deleted despite auto deletion is configured

### ISSUE THREAD

**Issue by dearekaelle** [tidusjar/Ombi#3125]
**Describe the bug**
same symptoms as #2802
Although configured the resolved issues never get deleted.

**To Reproduce**
1. Go to 'Configuration->Issues'
2. Set 'Leave the resolved issue for X amount of days before deletion' to 1
3. Wait 1 (or more) days
4. Resolved issues remain in place

**Expected behavior**
Resolved issues should be deleted.

**Logs (Logs directory where Ombi is located)**
System.IIssuesPurge task is being launched as per cron definition

2019-08-17 11:19:00.001 +02:00 [Debug] Calling Execute on job System.IIssuesPurge
2019-08-17 11:19:00.003 +02:00 [Debug] Trigger instruction : NoInstruction
2019-08-17 11:19:29.553 +02:00 [Debug] Batch acquisition of 0 triggers
2019-08-17 11:19:52.986 +02:00 [Debug] Batch acquisition of 1 triggers
2019-08-17 11:20:00.000 +02:00 [Debug] Batch acquisition of 0 triggers

**Ombi Version (please complete the following information):**
 - Version 3.0.4727; running from docker linuxserver/ombi:development
- Media Server Plex

**Comment by tidusjar** [comment]
It's a duplicate. Please follow the issue you mentioned.

**Comment by dearekaelle** [comment]
I would but it is closed.

**Comment by tidusjar** [comment]
Sorry! Didn't notice that

**Comment by dearekaelle** [comment]
this issue remains in the latest version 3.0.4822.

**Comment by macstainless** [comment]
Having this problem too. I have no way to delete a resolved issue even when auto-delete is on.
