### ISSUE TITLE
Ombi mobile app missing the Approved/Available bar & info in requests TV section

### ISSUE THREAD

**Issue by callahan22** [tidusjar/Ombi#3129]
**Describe the bug**
Using the Ombi mobile app on Android, the TV sections are missing all the info about the shows.

**To Reproduce**
1. Using the Ombi mobile app on Android. Tap the hamburger, select Requests.
2. You will see a list of your Movie requests with small banners beneath them stating if the movie has been approved or is available.
3. Tap the TV tab to the right and you will see your TV show requests. However, the status banners are missing for the TV shows. Tapping the TV Shows themselves will take you to a page with the "Approved" or "Available" banner box shown but it's missing all the detail about the TV show that you get when doing the same to a Movie.

**Expected behavior**
When tapping the TV show, I expect an identical response / info as I get when tapping a movie in the requests section.

**Desktop (please complete the following information):**
 - OS: Android

**Ombi Version (please complete the following information):**
 - Version: Latest mobile version.
- Media Server: Plex

**Comment by tidusjar** [comment]
This is the expected behaviour. It's pretty much how the website works too. You need to drill into the TV show to see the status of the request

**Comment by callahan22** [comment]
Fair enough! Closing ticket! Thanks for your reply :-)
