### ISSUE TITLE
newsletter not being sent

### ISSUE THREAD

**Issue by phildrage** [tidusjar/Ombi#3138]
**Describe the bug**
Newsletter not being sent. Newsletter test works fine, but triggering does nothing. I'm using a mailjet server and ionos 1&1 email. On newsletter test, i get logs (below) and the correct email recieved.

2019-08-29 12:19:05.724 +01:00 [Information] Plex Movies to send: 
101 2019-08-29 12:19:05.725 +01:00 [Information] Emby Movies to send: 0 
2019-08-29 12:19:05.725 +01:00 [Information] Albums to send: 0 
2019-08-29 12:19:06.383 +01:00 [Information] Plex Episodes to send: 51 
2019-08-29 12:19:06.383 +01:00 [Information] Emby Episodes to send: 0

But when pressing 'trigger now' nothing in the logs at all, and the message 'triggered newsletter job'

**To Reproduce**
click on 'test' on newsletter page, works correctly, click on 'trigger now', nothing happens

**Expected behavior**
newsletter to be sent!

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
windows 10, mailjet email server, ionos 1&1 email address

**Ombi Version (please complete the following information):**
 - Version 3.0.4119
- Media Server -Plex

**Additional context**

**Comment by tidusjar** [comment]
Have you read through this? https://github.com/tidusjar/Ombi/wiki/Newsletter-Settings

**Comment by phildrage** [comment]
Yes, all users have 'recieves newsletter'  enabled, and the newsletter is enabled itself.

**Comment by tidusjar** [comment]
Do you have your SMTP settings enabled? and also does the SMTP settings work?

**Comment by phildrage** [comment]
SMTP works, (ie the test function sends an email from the email notification setup page)

**Comment by phildrage** [comment]
Is there a way of enabling more detailed logs to get some more information?

**Comment by phildrage** [comment]
as above, how would i find out what point the newsletter is failing? Mailjet isn't seeing anything come through at all, nothing in the logs

**Comment by DillonsFlix** [comment]
I had the same issue which never got resolved.  I disabled the newsletter and started using NowShowing as my newsletter.

**Comment by phildrage** [comment]
Interesting, I'll take a look. Do you have a link for that?

**Comment by DillonsFlix** [comment]
Check this out.  [https://github.com/ninthwalker/NowShowing](url)
