### ISSUE TITLE
Ombi v4 sample not working

### ISSUE THREAD

**Issue by vinaykapadia** [tidusjar/Ombi#3139]
**Describe the bug**
Not sure if this is the right place for this, but the v4 sample page is not loading.

**To Reproduce**
1. Go to https://app.ombi.io

**Expected behavior**
Page opens without error.

**Screenshots**
Shows this:
{"error":"The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.\nYour application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.\n"}

**Desktop (please complete the following information):**
 - OS: Android

**Ombi Version (please complete the following information):**
 - Version 4

**Comment by tidusjar** [comment]
Thanks for raising this. I'll get it fixed!

**Comment by evanrich** [comment]
Closed, but it still does it? also my home instance shows same thing.

**Comment by thomasvt1** [comment]
+1 also have this issue at home @tidusjar

**Comment by Reconos87** [comment]
+1 on this at home aswell :(

**Comment by tidusjar** [comment]
Yeah guys I'm currently on vacation and I'll take a look once I'm back

**Comment by gstacks13** [comment]
I've still got this issue happening on my setup as well.  Running the latest docker on v4-preview as of this comment. Cleared cache and cookies after the upgrade to no avail.

**Comment by edrock200** [comment]
happening here too

**Comment by radusuciu** [comment]
Also happening with v4-preview docker image
