### ISSUE TITLE
Login page does not close after using Sign In With Plex

### ISSUE THREAD

**Issue by Rogue136198** [tidusjar/Ombi#3143]
**Describe the bug**
When logging into Ombi with Plex SSO "Sign In With Plex" it fails to close the popup/new tab that is opened for plex sign in.

**To Reproduce**
1. Load Ombi login page
2. Click Sign In With Plex
3. Complete Plex Sign In
4. You are left at the screen "Thanks! You have successfully signed in. You may now close this window."

**Expected behavior**
This window should be able to close automatically once Plex login is complete. Not having the window close automatically is a poor experience to end users

**Screenshots**
![image](https://user-images.githubusercontent.com/14829730/64168072-c28bf580-ce18-11e9-8d0c-2ee411327a61.png)

**Logs (Logs directory where Ombi is located)**
Nothing appears in the log related to this

**Desktop (please complete the following information):**
 - Windows 10, Android (both chrome)

**Ombi Version (please complete the following information):**
 - 3.0.4680

**Additional context**
I know Tautulli completes the workflow as I would expect. Their popup window closes after the plex login is complete. It makes it all feel more seamless.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

Please give it a go and let me know how it works!
