### ISSUE TITLE
[Feature Request] Shutdown/Restart Options

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/Ombi#315]
I think this would be nice option.  Would definitely be nice if I needed to restart server for something away from home where I could get to PlexRequests but not necessarily my pc.

**Comment by tidusjar** [comment]
Shutdown/Restart Plex Requests or the server?

**Comment by MiuiSwitzerland** [comment]
Maybe something similar to PlexPy?

![shutdown](https://cloud.githubusercontent.com/assets/1059104/15960497/642ad106-2f00-11e6-874b-8e6bbd8ef34a.jpg)

**Comment by tidusjar** [comment]
This restarts/shutdown the application?

The problem I am facing with this is that It's difficult to restart a .Net application in all the different environments. I can give it a go, but I'd need someone to help test Linux

**Comment by MiuiSwitzerland** [comment]
@tidusjar yes, this restarts/shutdown the application. I'm at your service if you want me to test it.

**Comment by gold007eye** [comment]
@tidusjar exactly what @MiuiSwitzerland said is what I was thinking of.

**Comment by SuperPotatoMen** [comment]
@tidusjar Can you this one a little more higher priority? 
A lot of requests are of this one (emby forum, feathub and reddit)

**Comment by stephen304** [comment]
I think this is kinda important when the how to guides don't have instructions on restarting. I changed ports and I'm just gonna resort to restarting my jail because it's started in a screen session from a crontab (per the guide here https://github.com/tidusjar/Ombi/wiki/FAQ)

**Comment by flvinny521** [comment]
I have Ombi v 2.2.1591 running on Windows 2012 server and the service is completely unresponsive; it can't even be killed in Task Manager. Something is causing my entire server to lag, and this is the only service I can't manually kill, but with no way to shut it down from the interface (which does work, albeit slowly), I have no choice but to reboot my server.

**Comment by SuperPotatoMen** [comment]
Well that Isn't a problem of ombi. If you use the nssm service you need to run the correct commando..

**Comment by flvinny521** [comment]
I didn't mean to insinuate it was a problem, just a situation that could be easier to remedy if there was a shutdown/reboot button directly in the interface.

**Comment by SuperPotatoMen** [comment]
Well Ombi can't restart If you run Ombi understand nssm..

**Comment by flvinny521** [comment]
> Well Ombi can't restart If you run Ombi understand nssm..

You're right, I had a bit of a brain fart forgetting that I had used NSSM for Ombi. Obviously NSSM was not allowing that to happen. Back to your regularly scheduled programming.
