### ISSUE TITLE
Ombi lets me request stuff already in Plex DB

### ISSUE THREAD

**Issue by qazero** [tidusjar/Ombi#3155]
**Describe the bug**
I have tried to do a manual sync on multiple occasions but the issue still persists. I am able to request stuff already in the Plex database. Issue seems to be mainly with my entire TV library.

**Logs (Logs directory where Ombi is located)**

> 2019-09-14 23:52:04.943 -05:00 [Warning] The episode title "Terror Tales of the Park VI" we cannot find the parent series. The episode grandparentKey = 37254, grandparentTitle = "Regular Show"
> 2019-09-14 23:52:07.464 -05:00 [Warning] The episode title "Trial & Error" we cannot find the parent series. The episode grandparentKey = 154454, grandparentTitle = "The Resident"
> 2019-09-14 23:52:07.562 -05:00 [Warning] The episode title "Operator Error" we cannot find the parent series. The episode grandparentKey = 154454, grandparentTitle = "The Resident"
> 2019-09-14 23:53:04.501 -05:00 [Warning] The episode title "Is the Genius Girl a Monster? Brainwashing School of Terror" we cannot find the parent series. The episode grandparentKey = 38546, grandparentTitle = "Sailor Moon"
> 2019-09-14 23:54:19.523 -05:00 [Warning] The episode title "The Count's Counting Error" we cannot find the parent series. The episode grandparentKey = 139471, grandparentTitle = "Sesame Street"
> 2019-09-14 23:54:40.209 -05:00 [Warning] The episode title "Server Error" we cannot find the parent series. The episode grandparentKey = 132859, grandparentTitle = "Silicon Valley"
> 2019-09-14 23:54:47.852 -05:00 [Warning] The episode title "Trilogy of Error" we cannot find the parent series. The episode grandparentKey = 46017, grandparentTitle = "The Simpsons"
> 2019-09-14 23:55:02.214 -05:00 [Warning] The episode title "Terror Starts at Home" we cannot find the parent series. The episode grandparentKey = 71763, grandparentTitle = "Six Feet Under"
> 2019-09-14 23:55:11.988 -05:00 [Warning] The episode title "Trial and Error" we cannot find the parent series. The episode grandparentKey = 39866, grandparentTitle = "Smart Guy"
> 2019-09-14 23:56:04.060 -05:00 [Warning] The episode title "Campaign of Terror" we cannot find the parent series. The episode grandparentKey = 115356, grandparentTitle = "Stalked: Someone's Watching"
> 2019-09-14 23:56:06.555 -05:00 [Warning] The episode title "Balance of Terror" we cannot find the parent series. The episode grandparentKey = 113458, grandparentTitle = "Star Trek"
> 2019-09-14 23:56:11.656 -05:00 [Warning] The episode title "Night Terrors" we cannot find the parent series. The episode grandparentKey = 121039, grandparentTitle = "Star Trek: The Next Generation"
> 2019-09-14 23:56:18.848 -05:00 [Warning] The episode title "Human Error" we cannot find the parent series. The episode grandparentKey = 121151, grandparentTitle = "Star Trek: Voyager"
> 2019-09-14 23:56:25.192 -05:00 [Warning] The episode title "Legacy of Terror" we cannot find the parent series. The episode grandparentKey = 166737, grandparentTitle = "Star Wars: The Clone Wars"
> 2019-09-14 23:56:36.806 -05:00 [Warning] The episode title "Trial and Error" we cannot find the parent series. The episode grandparentKey = 159680, grandparentTitle = "Stargate Universe"
> 2019-09-14 23:56:43.493 -05:00 [Warning] The episode title "Trailer Park Terror" we cannot find the parent series. The episode grandparentKey = 115710, grandparentTitle = "A Stranger in My Home"
> 2019-09-14 23:56:53.142 -05:00 [Warning] The episode title "Errors and Omissions" we cannot find the parent series. The episode grandparentKey = 40708, grandparentTitle = "Suits"
> 2019-09-14 23:57:07.018 -05:00 [Warning] The episode title "Trial and Error" we cannot find the parent series. The episode grandparentKey = 40832, grandparentTitle = "Supernatural"
> 2019-09-14 23:57:07.494 -05:00 [Warning] The episode title "Holy Terror" we cannot find the parent series. The episode grandparentKey = 40832, grandparentTitle = "Supernatural"
> 2019-09-14 23:57:12.881 -05:00 [Warning] The episode title "Terror Beach" we cannot find the parent series. The episode grandparentKey = 121719, grandparentTitle = "Surviving Evil"
> 2019-09-14 23:57:12.933 -05:00 [Warning] The episode title "Underground Terror" we cannot find the parent series. The episode grandparentKey = 121719, grandparentTitle = "Surviving Evil"
> 2019-09-14 23:57:32.836 -05:00 [Warning] The episode title "Night Terrors" we cannot find the parent series. The episode grandparentKey = 41464, grandparentTitle = "Swamp People"
> 2019-09-14 23:57:39.729 -05:00 [Warning] The episode title "Television Terror" we cannot find the parent series. The episode grandparentKey = 41688, grandparentTitle = "Tales from the Crypt"
> 2019-09-14 23:57:47.282 -05:00 [Warning] The episode title "Clerical Error" we cannot find the parent series. The episode grandparentKey = 134350, grandparentTitle = "Tales of the Unexpected"
> 2019-09-14 23:58:25.824 -05:00 [Warning] The episode title "The Terror" we cannot find the parent series. The episode grandparentKey = 199218, grandparentTitle = "The Tick (2001)"
> 2019-09-14 23:58:56.138 -05:00 [Warning] The episode title "Acts of Terror" we cannot find the parent series. The episode grandparentKey = 122194, grandparentTitle = "The Twilight Zone (1985)"
> 2019-09-14 23:59:47.356 -05:00 [Warning] The episode title "Terror on Cupcake Street" we cannot find the parent series. The episode grandparentKey = 106664, grandparentTitle = "Victorious"
> 

**Desktop (please complete the following information):**
 - Ubuntu Server 18.04.3 64bit LTS

**Ombi Version (please complete the following information):**
- Ombi 3.0.4680 (running in Docker)
- Plex Media Server 1.16.6.1592 Web Client 3.108.2

**Comment by tidusjar** [comment]
Strange, can you delete the `OmbiExternal.db` and then restart Ombi and then run a manual full sync?

**Comment by Iguana9999phil** [comment]
I'm having the same issue, users keep on requesting TVShows that are in my libraries for ages. Checked it myself and on the request page, searched for "Breaking bad" while the orange bar loads the button "Request" is already available and working, this means a user (who doesn't care about the orange loading bar) will request it. It takes a couple of seconds to load and show it is available, by that time the users is already doing another search. 
This is with a freshly synced OmbiExternal.db on a VPS dedicated to Ombi (as Ombi is already slow) 
What is the use of the database if Ombi still needs to query Plex / Sonarr for availability?
Possible solutions: don't show the request button before Ombi has queried Plex / Sonarr.

**Comment by tidusjar** [comment]
Ombi doesn't query Plex. This only happens when we need to do another query to get the relevant IDs e.g. IMDb to then check if it matches what we already have. 

This has been resolved in v4 so I will not fix this in V3 for now.
