### ISSUE TITLE
Shrek 2

### ISSUE THREAD

**Issue by mwdancin1** [tidusjar/Ombi#3165]
**Describe the bug**
3d version is playing through plex

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Closing due to lack of information. Please fill in the template correctly.
