### ISSUE TITLE
problems with sonarr and lidarr integration

### ISSUE THREAD

**Issue by killmark-prog** [tidusjar/Ombi#3166]
**Describe the bug**
I'm having a couple of issues that I am finding difficult to resolve. I use ombi with plex, sonarr, radarr and lidarr and followed all the instructions I could find in the wiki pages but have the following problems.

Radarr works as intended and I've been able to set the default root folder but can not with sonarr. When I press the option to get sonarrs default root nothing happens (test connection works and I can can set the quality profile).

I have a similar issue with lidarr and cant get the default root, or set the language, although I note that its been highlighted that the languages have been removed from the latest version of lidarr (which I am using) however I would have still expected it to find the default root folder?.

I have also found that some content isnt showing as available on the plex server when you look at ombi, although that seems to be the exception rather than the rule.

**To Reproduce**
1. download latest versions of plex, ombi, sonarr, radarr, lidarr
2. install plex & setup libraries, then sonarr, radarr, lidarr and add content.
3. test that sonarr, radarr, lidarr are able to retrieve files etc by torrents
4. setup ombi, link to plex, radarr, sonarr, lidarr

**Expected behavior**
After testing connection All drop downs options be retrieved after connecting to services. 

**Desktop (please complete the following information):**
 Windows

**Ombi Version (please complete the following information):**
Ombi v3.0.4680
Plex v1.16.6.1592
Radarr v0.2.0.1358
Sonarr v2.0.0.5338
Lidarr v0.7.1.1381

**Comment by tidusjar** [comment]
The sonarr/radarr and lidarr integration is working fine for me, in the latest develop branch for ombi, we have removed the language profile for lidarr.

The integrations are very similar, so without any logs which you didn't include, I cannot help much.
