### ISSUE TITLE
Ombi not triggering plex scan automatically

### ISSUE THREAD

**Issue by tctfox** [tidusjar/Ombi#3170]
**Describe the bug**
Hello there

In the jobs settings I put in a cronjob wich should trigger a manual sync (recently added) every 5 minutes. But this doesnt seem to happen. My requests dont get marked "aviable" even if the things are on the plex server. I also made sure to restart ombi after the changes and ombi says the cronjobs are valid.

Edit: manually triggering does work, but thats not a good workaround

**To Reproduce**
Described above

**Expected behavior**
That it does the sync every 5 minutes

**Logs (Logs directory where Ombi is located)**
Didnt find anything in the logs related to this

**Desktop (please complete the following information):**
 - OS: debian

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Comment by tctfox** [comment]
Here a screenshot of the "jobs" settings
http://cubeupload.com/im/tctfox/Screenshot2019092315.jpg

**Comment by tidusjar** [comment]
I can't seem to reproduce this, but others have reported it too.

I have the same cron, running every 5 minutes and it seems to be working as expected.

Is it only after a certain amount of time? Is there any more information you can share with this?

**Comment by tidusjar** [comment]
Is it just Movies or Just tv episodes etc?

**Comment by tctfox** [comment]
Hei there. I reinstalled completely and set everything up the same way and now it works. I am happy about it, but cant say you why it works now. I use the same crontabs as before
