### ISSUE TITLE
Newsletter not looking good in lower resolutions

### ISSUE THREAD

**Issue by GnaXi** [tidusjar/Ombi#3173]
**Describe the bug**
Easier to just show it:
![image](https://user-images.githubusercontent.com/1616448/65795230-149b0f00-e16a-11e9-983d-10f408ebf095.png)

**To Reproduce**
1. Open the newsletter on a phone

**Desktop (please complete the following information):**
Android

**Ombi Version (please complete the following information):**
 - 3.0.4680

**Comment by tidusjar** [comment]
Mail client?

**Comment by GnaXi** [comment]
Gmail

**Comment by tidusjar** [comment]
Closing as this is due to be reworked as part of v4
