### ISSUE TITLE
mobile notification sends only to admin and not user

### ISSUE THREAD

**Issue by Leemillard** [tidusjar/Ombi#3183]
**Describe the bug**
I have multiple users that can leave issues without any problems.

However when i reply to the issue its the admin that replies that gets the mobile notification, if that admin has no mobile linked you get the error below.

the user that reported it gets nothing even if mobile is linked

Thanks

Lee

**To Reproduce**
1. Go to 'issues'
2. Click on 'details'
3. submit message

**Expected behavior**
Should send notification to the user not admin

**Screenshots**
not applicable

**Logs (Logs directory where Ombi is located)**
if no mobile is linked to user
info: Ombi.Notifications.Agents.MobileNotification[0]
there are no admins to send a notification for IssueComment, for agent Mobile

**Desktop (please complete the following information):**
 - OS: iOS

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex

**Additional context**
Not Applicable

**Comment by Leemillard** [comment]
sends me the notification as the admin saying hello there is a comment on the issue you submitted... also the user gets test notifications fine

**Comment by tidusjar** [comment]
So the way this should be working is like the following

1. User raises an issue -> Admin gets notification
1. Admin comments on issue -> User gets notification
1. User comments on issue -> Admin gets notification

Does that clear things up?

**Comment by Leemillard** [comment]
Ok thank you for clarifying..

But here is how it’s currently working

1. User raises an issue > admin gets notification
2. Admin comments on issue > admin gets the notification as if admin raised it
3. Notification test to user > user gets notification

Thanks

Lee

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
