### ISSUE TITLE
Search not finding some shows

### ISSUE THREAD

**Issue by christoefar** [tidusjar/Ombi#3184]
**Describe the bug**
When search for a particular TV show, no results are found. This happens on the demo application running at https://demo.ombi.io as well, so I think this is a code issue rather than an environment problem.

Doing a direct call to TV Maze does return the data required (http://api.tvmaze.com/search/shows?q=living%20with%20yourself)

**To Reproduce**
1. Enter "living with yourself" in the search box.

**Expected behavior**
Living with Yourself is returned by the API call to TV Maze

**Logs (Logs directory where Ombi is located)**
No logs provided.

**Desktop (please complete the following information):**
 - OS: unRAID 6.7.0 / Docker

**Ombi Version (please complete the following information):**
 - Version: 3.0.4803
- Media Server: Plex

**Comment by tidusjar** [comment]
Did you read this? https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all

**Comment by christoefar** [comment]
I have now, sorry about that.

I see from this issue #408 that you found a few reasons to use TVMaze. Speed, API Key, Fuzzy Search.

Would you be open to a PR to allow users to switch between TVMaze and the TVDB? For me, since we _require_ the tvdbid it makes more sense to use that API directly.

I haven't looked into this at all, so maybe this is unfeasible! :)

**Comment by tidusjar** [comment]
No problem. It would be possible but would require a bit of rework since I never had this in mind. Would require writing a new layer between the Ombi engines and the API's and then new mappings between the TV provider and ombis models. It's not a small task
