### ISSUE TITLE
Requests not marking as avaliable on Windows

### ISSUE THREAD

**Issue by goldhousefire** [tidusjar/Ombi#3190]
**Describe the bug**
I am running Ombi: 3.0.4680 on Windows Server Core 2019. 
When a movie has completed downloading it shows under search as AVALIABLE but the request is never marked AVALIABLE and therefore no Push notification is sent to the Ombi app.
My _users_ dont know when thier requests are completed so instead have to search every time.

Its the exact issue pointed out in [2626](https://github.com/tidusjar/Ombi/issues/2626) but I am on Windows. I tried setting my locale to en-US and rebooted the server,

I have NO PLEX or other Media Server. Is a media server required for this feature to work? 
It makes little sense for SEARCH to show a movie as avaliable but not the REQUEST.

**To Reproduce**
1. Make a request for a movie
2. Wait for it to download
3. Manually check its downloaded in your DownloadClient
4. Check the Ombi SEARCH to see if the movie has been marked AVALIABLE
5. Check the request, it is NOT marked as avaliable

**Expected behavior**
Once a request is detected on disk by Radarr or Sonarr Ombi should mark the request as AVALIABLE.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 2019 Server Core. (Microsoft Windows 10.0.17763)

**Ombi Version (please complete the following information):**
I am running Ombi: 3.0.4680 on Windows Server Core 2019. 
I have NO PLEX.

**Comment by tidusjar** [comment]
You need a media server for this to work. If you do not have a media server then you will need to mark as available manually.

**Comment by goldhousefire** [comment]
Thanks for the quick response. Could it be made possible to have a switch in Ombi which uses Sonarr and Radarr to check if a request should be made available? Or a switch that marks a request as available if it’s available in search 

I have no need for Emby or Plex because I use a plain old SMB share with Kodi. I guess others are not in the same boat!

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
