### ISSUE TITLE
TV show's not showing "Requested By"

### ISSUE THREAD

**Issue by CrashyBang** [tidusjar/Ombi#3191]
**Describe the bug**
TV show's are not showing the "requested by" line with the user name.

Movies are showing this.

**To Reproduce**
1. Navigate to the TV requests section.

**Expected behavior**
For the "Requested by" line to show.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/2978850/66286640-d1d9f380-e92e-11e9-8195-01a519a8b3e8.PNG)

**Logs (Logs directory where Ombi is located)**
Running in the `linuxserver` docker container, I can try and extract these if needed.

**Desktop (please complete the following information):**
 - OS: Docker (on UNRAID)

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256 
- Media Server: Plex

**Additional context**
It just stopped working all of a sudden, I am not sure.

**Comment by tidusjar** [comment]
Please press the view button. It's because TV requests as based off
episodes. So what you are seeing is all requested for that show grouped.

**Comment by CrashyBang** [comment]
@tidusjar,

I am so sorry I should have figured that one out!

Cheers.
