### ISSUE TITLE
Album Search Grid misaligned

### ISSUE THREAD

**Issue by kionay** [tidusjar/Ombi#3205]
**Describe the bug**
When searching for music albums, the three-wide grid organization can sometimes look wrong.

**To Reproduce**
1. Go to Music
2. Ensure Album search checkbox is checked.
3. Search for "Sound"
4. See that the 3rd row at most resolutions has a gap that appears to be a missing album.

**Expected behavior**
An "even" 3-wide grid of albums.

**Screenshots**
![Screenshot attached](https://user-images.githubusercontent.com/8558954/66719697-3975c000-edc1-11e9-8ec1-79f32b8bbb5e.jpg)
(zoomed out to get the entire effect in one shot)

**Desktop (please complete the following information):**
 - OS: Windows, using chrome browser to view the Ombi web application

**Ombi Version (please complete the following information):**
 - Version 3.0.4817

**Additional context**
The `<div>` tags with `col-md-4` and `ng-star-inserted` classes are of subtly different heights.
The height differences are due to posters having various sizes, which works well for very long posters (for example "Sound on Sound" by the band André de Saint-Obin has [this](https://coverartarchive.org/release/2a59a130-3ac4-4f03-9e17-2a9a7d3acf20/24299931025.jpg) very long album image.

If the long album image occurred near the gaps it would be obvious that the gaps exist so that the long poster could spill over into the next row. However, with poster images that are just a few pixels off of the 300x300 standard the gap is still made, and to the naked eye it looks like a mistake. In the example of searching for "Sound" the "Sound on Sound" album cover is 
300.**5**px and the Sound Shattering Sound album cover is **297.98**px. 

This picture is probably a better illustration of the problem with height and padding, with padding highlighted.
![Ombi2](https://user-images.githubusercontent.com/8558954/66719806-6d9db080-edc2-11e9-8948-a254aff3b9d4.png)

[Best of luck fixing this <3](https://i.imgur.com/Q3cUg29.gif)

**Comment by tidusjar** [comment]
Haha thanks for the report. I am not going to even attempt to fix this.

V4 has improved that and hopefully you will be able to use V4 soon.
