### ISSUE TITLE
Ombi Does Not Run under macOS Catalina Due to Unidentified Developer

### ISSUE THREAD

**Issue by macstainless** [tidusjar/Ombi#3206]
**Describe the bug**
When launching Ombi via ./Ombi or a LaunchAgent, Catalina's new security never allows Ombi to fully launch. Each DLL is triggering the following security prompt: "macOS cannot verify the developer of "X.dll". Allowing them individually dismisses the prompt, but Ombi uses so many DLL files, that it is an endless cycle of approving the DLLs, which then repeat security approval multiple times.

**To Reproduce**
1. Launch Ombi via Terminal.
2. Security prompts will appear repeatedly.

**Expected behavior**
Ombi should launch without prompt or a single security prompt should be shown.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
New Install (latest version) so no logs are found in the Ombi directory.
**Desktop (please complete the following information):**
 - OS: macOS 10.15 Catalina

**Ombi Version (please complete the following information):**
 - Version 3.0.4817 (happened on prior version too)
- Media Server Plex.

**Additional context**
This is specific to macOS Catalina and updated security restrictions. This did not happen on any prior releases of macOS.

**Comment by tidusjar** [comment]
From my understanding, for me to fix this Ombi would need to be part of the App Store for Mac. That is not going to happen... So unsure what to do.

**Comment by macstainless** [comment]
I'm not sure that is entirely true because Sonarr, Radarr, and Tautulli all function without this issue. However, Sonarr and Radarr are packaged as Mac apps (neither are on the App Store), while Tautulli runs as a python script. I'm not technical enough about macOS to know the solution, but I do know that Ombi is the only Plex-related app I'm using who's directory structure is significantly different. Maybe that helps? Not sure.

Alternatively, having the app trigger a single warning that would require overriding would work too. The current setup though causes an endless cascade of approval messages that never stops.

**Comment by tidusjar** [comment]
Please read this: https://github.com/tidusjar/Ombi/wiki/Installation#macos
