### ISSUE TITLE
Ombi not automatically syncing movies

### ISSUE THREAD

**Issue by Tragyn** [tidusjar/Ombi#3208]
**Describe the bug**
Requests are being added properly, found by radarr, downloaded, and added to Plex.  Ombi still says "processing request" and running full sync/manual sync doesn't change that.  I have the cron jobs set to run every 5 minutes just for testing, and it is syncing TV shows in the log:

> Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
>Processed 150 more episodes. Total Remaining 2451
>Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2002]
>We have finished caching the episodes.

But nothing about movies.  

**To Reproduce**

1. Request movie
2. Check status

**Expected behavior**
Expect movie to be marked as available and trigger notifications.

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/LRZVyF27

**Desktop (please complete the following information):**
 - OS: unRaid

**Ombi Version (please complete the following information):**
 - Version 3.0.4822 (also on master, etc)
Plex

**Comment by Ezzahhh** [comment]
For me running full manual sync will work, but running manual recently added does not update.

**Comment by Heppie** [comment]
I can confirm that the version mentioned no longer syncs Plex movies even running a manual full sync. Recently added sync does not work with movies either, but it did not in the previous version anyway.

Running the linuxserver docker on unRAID.

**Comment by mhbates** [comment]
Full sync is working for me, but not recently added sync. 3.0.4817.

**Comment by tidusjar** [comment]
This should be fixed in develop
