### ISSUE TITLE
False possible on there is a update available

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#3210]
**Describe the bug**
Just a minor bug:
After updating to the last version (3.0.4817), ombi still says there is a new version.

**To Reproduce**
1. Go to Settings
2. Click on About
3. See error: "Version | 3.0.4817 (New Update Available)"

**Expected behavior**
Saying that ombi is up to date instead of saying there is a new update.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version:3.0.4817 

**Additional context**

**Comment by tidusjar** [comment]
My bad! forgot to update the changelog!
