### ISSUE TITLE
tv show requests should show # of episodes available out of # episodes in series

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/Ombi#322]
On the requests page, we show a checkmark icon when a movie or show is available. What we don't indicate is the number of episodes that are available for the show. I'm proposing we show something like "50/60" or something to that effect to indicate that it's missing items. 

The natural next step would be to indicate which items are missing (but that probably isn't very important).

**Comment by gold007eye** [comment]
I love this idea.  I was just thinking about that last week when someone requested a TV Show.. check mark was saying it was available but after checking Sonarr 12 episodes were still missing.
