### ISSUE TITLE
Notifications on mobile device not alerting when download is finished or its 6 hours late.

### ISSUE THREAD

**Issue by stevefo813** [tidusjar/Ombi#3220]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Closing due to lack of information in the template.
