### ISSUE TITLE
Unable to re-import Plex Users

### ISSUE THREAD

**Issue by motodrew** [tidusjar/Ombi#3224]
**Describe the bug**
After deleting a user from User Management the Import Job will not re-add the missing User.

**To Reproduce**
1. Go to 'User Management'
2. Delete a user (making sure they are a Plex User)
3. Go to 'Settings' -> 'User Importer'
4. Click 'Run Importer'
5. After waiting some time check 'User Management' again
6. The deleted user is not re-added

**Expected behavior**
I would expect the user to be re-added as they are not a part of the created users.

**Desktop (please complete the following information):**
 - OS: Running on docker in Unraid

**Ombi Version (please complete the following information):**
 - Version 3.0.4817
- Media Server Plex

**Additional context**
My assumption is that a record or something needs to be marked that the user can be re-added again just not sure where that exists.

**Comment by tidusjar** [comment]
Any logs when the user importer runs?

**Comment by motodrew** [comment]
Sadly am not by my server at the moment but will post them in hopefully an hour or so. Wanted to pop it in just in case it was more of a known issue or a pebkac

**Comment by motodrew** [comment]
Just looked at the logs and realized it was an authentication issue :(. Sorry for being dumb! But thanks for making an amazing application!!!
