### ISSUE TITLE
Ombi delayed mobile notifications

### ISSUE THREAD

**Issue by stevefo813** [tidusjar/Ombi#3227]
**Describe the bug**
When I download a movie at any time using Ombi, I don't get a mobile notification that it successfully downloaded until exactly 2am every night.

**To Reproduce**
1. Go to 'request movie in Ombi'
2. Wait for it to tranfer into Plex
3. Wait for Ombi mobile notification that it successfully downloaded
4. Mobile notification shows up at exactly 2am that movie successfully downloaded

**Expected behavior**
Soon after requesting a movie and being transferred to Plex, I should receive a mobile notification that it successfully downloaded.

**Screenshots**
none

**Logs (Logs directory where Ombi is located)**
I didn't supply them

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04LTS  and I'm using ios Ombi app 1.7

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.4847]
- Media Server [Plex]

**Additional context**
Sending mobile test notification works instantly.

**Comment by zellenberg** [comment]
I am experiencing this as well

**Comment by tidusjar** [comment]
This should be fixed in develop now.

**Comment by stevefo813** [comment]
> This should be fixed in develop now.

I'm currently on 3.0.4850. Will it be fixed in the next release? Thanks!

**Comment by stevefo813** [comment]
Spoke too soon. It's working good now on 3.0.4850. Thank you tidusjar! Awesome app and program!
