### ISSUE TITLE
Reverse Proxy Not working

### ISSUE THREAD

**Issue by DatsiK96** [tidusjar/Ombi#3229]
**Describe the bug**
Per the instructions at here: https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples
I set up reverse proxy on an NGINX web server.

I have no auth setup from NGINX side. So it should go straight to Ombi where Ombi will authenticate users.

Organizr was setup with NGINX and is working as expected there. Adding the location /ombi section to the NGINX config is where behavior starts getting weird.

Visiting https://my.domain/ombi shows only a "Loading . . ." and nothing ever happens after that. The tab on the browser will change to "Ombi" so it appears as if NGINX is redirecting it as expected, but Ombi doesn't load properly when it's done with this method.

**Expected behavior**
I'm trying to get Ombi on a reverse proxy to deliver the unsecured site as a secure site.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ombi and NGINX are both on the same Win 2019 server.

**Ombi Version (please complete the following information):**
 - Whatever the latest stable release is of Ombi.

**Additional context**
Any information or tips would be greatly appreciated. Thank you.

**Comment by agneevX** [comment]
Not the dev, but did you add the Base Url under Settings -> Ombi to `/ombi`?

**Comment by stephanrenggli** [comment]
I have the same Issue, however I am using Traefik as reverse proxy.

Ombi works fine if I access it directly without reverse proxy.
When looking at the chrome console, a lot of 401 errors appear.

```
request:69 GET https://plex.example.com/request/dist/vendor.css?v=A5VSEkY8uq7pAj1OkaY6vaxKY0-yZsGZSG_UJMjE8Vg net::ERR_ABORTED 401
request:71 GET https://plex.example.com/request/dist/app.js?v=XawlTL8OELEQyUgS30UXVes4gso6WOav44mIWK9v0EA net::ERR_ABORTED 401
favicon.ico:1 GET https://plex.example.com/request/images/favicon/favicon.ico 401
favicon-32x32.png:1 GET https://plex.example.com/request/images/favicon/favicon-32x32.png 401
favicon-16x16.png:1 GET https://plex.example.com/request/images/favicon/favicon-16x16.png 401

```

Traefik config:
```
    labels:
      - traefik.enable=true
      - traefik.http.services.ombi.loadbalancer.server.port=3579
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.ombi.rule=Host(`plex.example.com`) && Path(`/request`)
      - traefik.http.routers.ombi.entrypoints=https
      - traefik.http.routers.ombi.tls.certresolver=letsencrypt
      - traefik.http.routers.ombi.tls.domains[0].main=*.example.com
      - traefik.http.routers.ombi.tls.domains[0].sans=example.com
      - traefik.http.middlewares.ombi.headers.SSLRedirect=true
      - traefik.http.middlewares.ombi.headers.STSSeconds=315360000
      - traefik.http.middlewares.ombi.headers.browserXSSFilter=true
      - traefik.http.middlewares.ombi.headers.contentTypeNosniff=true
      - traefik.http.middlewares.ombi.headers.forceSTSHeader=true
      - traefik.http.middlewares.ombi.headers.SSLHost=
      - traefik.http.middlewares.ombi.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.ombi.headers.STSPreload=true
      - traefik.http.middlewares.ombi.headers.frameDeny=true
```

**Comment by DatsiK96** [comment]
> Not the dev, but did you add the Base Url under Settings -> Ombi to `/ombi`?

I'm not sure I follow you, I followed the instructions on the guide.

If you're talking about inside ombi -> Settings -> Configuration -> Application URL;

I did not change that from the my.domain:5000 to my.domain:5000/ombi/

Is that what you're telling me to do? It sounds like it would kill my access to the app...

**Comment by ignatiusmb** [comment]
> I have the same Issue, however I am using Traefik as reverse proxy.

I got the same issue using Caddy as reverse proxy. It just shows a static HTML with the word `loading` and three dots.

> Not the dev, but did you add the Base Url under Settings -> Ombi to `/ombi`?

Caddy has a built-in URL trimmer so the `/ombi` path passed through the reverse proxy is removed.

Ombi works fine from `localhost` and through a subdomain, but not with a path.

**Comment by ignatiusmb** [comment]
Can't really help with NGINX, but I finally got mine working with Caddy. It's really simple, [check this example](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#caddy)

**Comment by stephanrenggli** [comment]
I found out what the issue was with my traefik configuration, maybe this applies to other reverse proxies as well. The labels below work for traefik v2. The important change I made was switching from 'Path' to 'PathPrefix', the official documentation explains why this is necessary.

From https://docs.traefik.io/routing/routers/:
> Use Path if your service listens on the exact path only. For instance, Path: /products would match /products but not /products/shoes.
> 
> Use a *Prefix* matcher if your service listens on a particular base path but also serves requests on sub-paths. For instance, PathPrefix: /products would match /products but also /products/shoes and /products/shirts. Since the path is forwarded as-is, your service is expected to listen on /products.

Obviously the use of sub-paths is required for ombi.

```yaml
    labels:
      - traefik.enable=true
      - traefik.http.services.ombi.loadbalancer.server.port=3579
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.ombi.rule=Host(`plex.example.com`) && PathPrefix(`/request`)
      - traefik.http.routers.ombi.entrypoints=https
      - traefik.http.routers.ombi.tls.certresolver=letsencrypt
      - traefik.http.routers.ombi.tls.domains[0].main=*.example.com
      - traefik.http.routers.ombi.tls.domains[0].sans=example.com
      - traefik.http.middlewares.ombi.headers.SSLRedirect=true
      - traefik.http.middlewares.ombi.headers.STSSeconds=315360000
      - traefik.http.middlewares.ombi.headers.browserXSSFilter=true
      - traefik.http.middlewares.ombi.headers.contentTypeNosniff=true
      - traefik.http.middlewares.ombi.headers.forceSTSHeader=true
      - traefik.http.middlewares.ombi.headers.SSLHost=
      - traefik.http.middlewares.ombi.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.ombi.headers.STSPreload=true
      - traefik.http.middlewares.ombi.headers.frameDeny=true
```

**Comment by DatsiK96** [comment]
My issue with the reverse proxy has been resolved, I ended up rebuilding Ombi from scratch, and utilizing IIS with URL Rewrite with CertifyTheWeb/LetsEncrypt to generate certs for it.

**Comment by coronel08** [comment]
> I found out what the issue was with my traefik configuration, maybe this applies to other reverse proxies as well. The labels below work for traefik v2. The important change I made was switching from 'Path' to 'PathPrefix', the official documentation explains why this is necessary.
> 
> From https://docs.traefik.io/routing/routers/:
> 
> > Use Path if your service listens on the exact path only. For instance, Path: /products would match /products but not /products/shoes.
> > Use a _Prefix_ matcher if your service listens on a particular base path but also serves requests on sub-paths. For instance, PathPrefix: /products would match /products but also /products/shoes and /products/shirts. Since the path is forwarded as-is, your service is expected to listen on /products.
> 
> Obviously the use of sub-paths is required for ombi.
> 
> ```yaml
>     labels:
>       - traefik.enable=true
>       - traefik.http.services.ombi.loadbalancer.server.port=3579
>       - traefik.docker.network=traefik_proxy
>       - traefik.http.routers.ombi.rule=Host(`plex.example.com`) && PathPrefix(`/request`)
>       - traefik.http.routers.ombi.entrypoints=https
>       - traefik.http.routers.ombi.tls.certresolver=letsencrypt
>       - traefik.http.routers.ombi.tls.domains[0].main=*.example.com
>       - traefik.http.routers.ombi.tls.domains[0].sans=example.com
>       - traefik.http.middlewares.ombi.headers.SSLRedirect=true
>       - traefik.http.middlewares.ombi.headers.STSSeconds=315360000
>       - traefik.http.middlewares.ombi.headers.browserXSSFilter=true
>       - traefik.http.middlewares.ombi.headers.contentTypeNosniff=true
>       - traefik.http.middlewares.ombi.headers.forceSTSHeader=true
>       - traefik.http.middlewares.ombi.headers.SSLHost=
>       - traefik.http.middlewares.ombi.headers.STSIncludeSubdomains=true
>       - traefik.http.middlewares.ombi.headers.STSPreload=true
>       - traefik.http.middlewares.ombi.headers.frameDeny=true
> ```
> 
> **Edit**: I added fairly detailed configuration examples to the [wiki](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#traefik) if you want to check it out.

Thank you so much I ended up using the configuration wiki you linked on ombi and got it working as a subdomain. I built my Traefik Reverse Docker stack by following https://www.smarthomebeginner.com/traefik-2-docker-tutorial/ and their docker-compose-t2.yml file. 

So far this works for me and has solved the problem. Thanks!!!! here's my code. Be sure to set the variables for USERDIR and DOMAINNAME 

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${USERDIR}/docker/ombi:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "3579:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
#      - BASE_URL=${BASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      ## HTTP Routers
      - "traefik.http.routers.ombi-rtr.entrypoints=https"
      - "traefik.http.routers.ombi-rtr.rule=Host(`ombi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.ombi-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.ombi-rtr.service=ombi-svc"
      - "traefik.http.services.ombi-svc.loadbalancer.server.port=3579"
      ## https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#traefik
      ## Extra stuff from https://github.com/tidusjar/Ombi/issues/3229
      - "traefik.http.routers.ombi-rtr.tls.domains[0].main=(`*.$DOMAINNAME`)"
      - "traefik.http.routers.ombi-rtr.tls.domains[0].sans=($DOMAINNAME)"
      - "traefik.http.middlewares.ombi-rtr.headers.SSLRedirect=true"
      - "traefik.http.middlewares.ombi-rtr.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.ombi-rtr.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.ombi-rtr.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.ombi-rtr.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.ombi-rtr.headers.SSLHost="
      - "traefik.http.middlewares.ombi-rtr.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.ombi-rtr.headers.STSPreload=true"
      - "traefik.http.middlewares.ombi-rtr.headers.frameDeny=true"
#      - "traefik.http.routers.ombi-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs

**Comment by coronel08** [comment]
Thank you so much I ended up using the configuration user stephanrenggli [linked ](https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#traefik)on ombi and got it working as a subdomain. I built my Traefik Reverse Docker stack by following https://www.smarthomebeginner.com/traefik-2-docker-tutorial/ and their docker-compose-t2.yml file.

So far this works for me and has solved the problem. Thanks!!!! here's my code. Be sure to set the variables for userdir and domainname

ombi:
image: linuxserver/ombi
container_name: ombi
restart: always
networks:
- t2_proxy
security_opt:
- no-new-privileges:true
volumes:
- ${USERDIR}/docker/ombi:/config
- ${USERDIR}/docker/shared:/shared
ports:
- "3579:3579"
environment:
- PUID=${PUID}
- PGID=${PGID}
- TZ=${TZ}

- BASE_URL=${BASE_URL}
labels:
  - "traefik.enable=true"
  - "traefik.docker.network=t2_proxy"
  ## HTTP Routers
  - "traefik.http.routers.ombi-rtr.entrypoints=https"
  - "traefik.http.routers.ombi-rtr.rule=Host(`ombi.$DOMAINNAME`)"
  ## Middlewares
  - "traefik.http.routers.ombi-rtr.middlewares=chain-no-auth@file"
  ## HTTP Services
  - "traefik.http.routers.ombi-rtr.service=ombi-svc"
  - "traefik.http.services.ombi-svc.loadbalancer.server.port=3579"
  ## https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#traefik
  ## Extra stuff from https://github.com/tidusjar/Ombi/issues/3229
  - "traefik.http.routers.ombi-rtr.tls.domains[0].main=(`*.$DOMAINNAME`)"
  - "traefik.http.routers.ombi-rtr.tls.domains[0].sans=($DOMAINNAME)"
  - "traefik.http.middlewares.ombi-rtr.headers.SSLRedirect=true"
  - "traefik.http.middlewares.ombi-rtr.headers.STSSeconds=315360000"
  - "traefik.http.middlewares.ombi-rtr.headers.browserXSSFilter=true"
  - "traefik.http.middlewares.ombi-rtr.headers.contentTypeNosniff=true"
  - "traefik.http.middlewares.ombi-rtr.headers.forceSTSHeader=true"
  - "traefik.http.middlewares.ombi-rtr.headers.SSLHost="
  - "traefik.http.middlewares.ombi-rtr.headers.STSIncludeSubdomains=true"
  - "traefik.http.middlewares.ombi-rtr.headers.STSPreload=true"
  - "traefik.http.middlewares.ombi-rtr.headers.frameDeny=true"
  - "traefik.http.routers.ombi-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
