### ISSUE TITLE
JSON deserialization error when attempting to add movie to Radarr

### ISSUE THREAD

**Issue by doweaver** [tidusjar/Ombi#3233]
**Describe the bug**
Ombi fails to add a movie to Radarr

**To Reproduce**
1. Add a movie through the normal path

**Expected behavior**
Movie shows up in Radarr list

**Logs (Logs directory where Ombi is located)**
[log-20191029.txt](https://github.com/tidusjar/Ombi/files/3786621/log-20191029.txt)

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

**Desktop (please complete the following information):**
Linux 4.19.56-Unraid #1 SMP Tue Jun 25 10:19:34 PDT 2019

**Ombi Version (please complete the following information):**
Ombi - 3.0.4817

- Media Server [e.g. Plex]
Plex - Version 1.18.1.1973

**Additional context**
Radarrr - 0.2.0.1358

**Comment by joshuaboniface** [comment]
Getting the same error with Music requests.

**Comment by tidusjar** [comment]
This is usually due to the settings not being correct, if you are using a URL base with Radarr ensure that is set in the Ombi settings too.

e.g. `/Radarr`

**Comment by Wizofgoz** [comment]
I'm seeing this for music as well. Settings for Lidar seem correct to my eye and testing of the connection succeeds.
