### ISSUE TITLE
Reverse Proxy Not Working

### ISSUE THREAD

**Issue by montgomery102** [tidusjar/Ombi#3238]
**Describe the bug**
Reverse proxy using NGINX not working. Have followed all direction at https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 

**Ombi Version (please complete the following information):**
 - Version 3.0.4850
- Media Server Plex

**Additional context**
NGINX Config file 
server {
  listen 8080;
  listen [::]:8080;

  server_name ombi.ryelgrnat.com;

  location / {
        proxy_pass http://192.168.100.100:5000;
  }
}

At the moment the UFW firewall is turn off on the NGINX server and the Ombi server. NGINX server is 192.168.200.100. The only thing that i have modified is that the NGINX serve is listening on prot 8080 instead of 80 as in the examples on the page noted above. Also the NGINX server has a word press site that runs on 443. Hoeing you can help. I have been trying everything I can for the last 3 weeks with not luck.

**Comment by tidusjar** [comment]
Have you take a look at the examples in the wiki?

**Comment by montgomery102** [comment]
I have looked at the examples on the wiki.

**Comment by tidusjar** [comment]
I admit that my knowledge on reverse proxies is not very good. If you google on Ombi Reverse Proxy there should be some guides.

Otherwise I cannot help with this

**Comment by Berserkir-Wolf** [comment]
@montgomery102  - hop on over to discord if you have no further luck there. I would suggest you look into defining 'virtualhosts' for the proxy setup - that way your wordpress site and ombi proxy can coexist on the same ports without conflict.
