### ISSUE TITLE
Show admin auto-approve roles in User Settings/Roles

### ISSUE THREAD

**Issue by dovry** [tidusjar/Ombi#3239]
**Describe the bug**
By default, admins have auto-approve since #132, but the settings don't show that anywhere. I had to google my way to #132

**To Reproduce**
1. Give user admin rights
1. User requests media
1. Wonder why you don't get notified and why Toy Story appeared in 'Films' instead of 'Kids'

**Expected behavior**
The settings should show that admins have auto-approve by filling in the  auto-approve fields when Admin is ticked.
Possibly greying out the fields if Admins should have the roles by default, or giving the option to tick them off to disable that specific admins' rights to have requests auto-approved.

Related to #1628, but this is more of a UI fix to show that Admin has auto-approve, however I still agree with #1628.

**Screenshots**

![image](https://user-images.githubusercontent.com/15201298/68084525-11650400-fe37-11e9-9252-ad8f27cb4a65.png)

**Ombi Version (please complete the following information):**
 - 3.0.4817 (latest LinuxServer container)

**Comment by tidusjar** [comment]
Going forward in V4 I am making the Roles and Permissions system a LOT more granular. So you will be able to add your own Roles and then assign permissions to that role. E.g. Permission AutoApproveMovie can be assigned to the Admin role, or it can be taken out.
