### ISSUE TITLE
Add Movies based on Actor

### ISSUE THREAD

**Issue by zenjabba** [tidusjar/Ombi#324]
Would it be at all possible to type in an actor's name and have the movies appear that way, so we can have a "collection of xyz" movies brought in.

**Comment by jrdnlc** [comment]
+1 - Love this idea.

**Comment by tidusjar** [comment]
Need to see if the API supports this

**Comment by SuperPotatoMen** [comment]
Other Feature request is "I'm looking for the ability to search by actor, director, etc. This is primarily for movies/tv shows."

**Comment by smcpeck** [comment]
I have a PR in the dev branch for this.  #1178

**Comment by zenjabba** [comment]
This looks fantastic!

**Comment by smcpeck** [comment]
This is in EAP now. Can probably be closed.

**Comment by SuperPotatoMen** [comment]
Big Thanks to @smcpeck! It is now live in dev branch.
