### ISSUE TITLE
TV Show Requests not being listed

### ISSUE THREAD

**Issue by jaketowt** [tidusjar/Ombi#3242]
**Describe the bug**
When I as an admin attempt to see what TV shows have been requested, it is blank. I know people have been requesting, but it seems to not load them. Movies work just fine

**To Reproduce**
1. Go to requests
2. Click on tv
3. See error

**Expected behavior**
It should be showing the current TV requests

**Screenshots**
[http://www.jacobanderson.me/PlexIssue.png](http://www.jacobanderson.me/PlexIssue.png)

**Logs (Logs directory where Ombi is located)**
Not sure

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional

**Ombi Version (please complete the following information):**
 - Version [3.0.4817]
- Media Server [Plex]

**Additional context**
n/a

**Comment by tidusjar** [comment]
Need some server logs here.

also are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by jaketowt** [comment]
Screenshot
![PlexIssue2](https://user-images.githubusercontent.com/54048083/68244229-97b54d80-ffd1-11e9-9432-67ce605e1e6b.png)
HAR File
[ombi.jacobanderson.me.har.zip](https://github.com/tidusjar/Ombi/files/3811106/ombi.jacobanderson.me.har.zip)

**Comment by jaketowt** [comment]
Log files
[log-20191105.txt](https://github.com/tidusjar/Ombi/files/3811110/log-20191105.txt)

**Comment by tidusjar** [comment]
According to the API result, you have no tv requests?

**Comment by jaketowt** [comment]
They are blank. Movies are showing fine.

**Comment by tidusjar** [comment]
What I am saying is Ombi doesn't have any tv requests, that's why they are not showing

**Comment by jaketowt** [comment]
I just put a TV Show in there myself. Nothing listed.

**Comment by jaketowt** [comment]
Wait.. nevermind. I feel stupid. You are correct.

**Comment by jaketowt** [comment]
Thank you for supporting this fool :)
