### ISSUE TITLE
`Loading…` screen requires multiple refreshes to get login page

### ISSUE THREAD

**Issue by SturmB** [tidusjar/Ombi#3243]
**Describe the bug**
The app rarely loads on the first attempt to navigate to it. Instead, the app shows `Loading…` in a serif font on a black background. Refreshing the page causes the word `Loading…` to be in a sans-serif font. One more refresh will (usually) allow the app to finally load the login page.

Sometimes it only takes one refresh, sometimes several. Regardless, the app **never** loads the first time it is navigated to.

**To Reproduce**
1. Go to 'https://ombi.solamnia.xyz'
2. Witness a `Loading…` screen that never changes to a login page.
3. Refresh the page. (Repeat as necessary until the login screen appears.)

**Expected behavior**
I expect the login to appear almost immediately after navigating to the above site. Or, at the very least, I expect the `Loading…` screen to only last a few seconds before the login page appears.

**Screenshots**
No need. Visiting the URL above shows the issue quite well.

**Logs (Logs directory where Ombi is located)**
I am unfamiliar with where the logs are located. If they would help to diagnose this issue, please inform me of their location and I'll gladly post them here.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903 and Chrome (latest version)

**Ombi Version (please complete the following information):**
 - Version: 3.0.4817
- Media Server: Plex

**Additional context**
The only other information that _might_ be relevant to this is the fact that all of my apps (Radarr, Sonarr, Plex, Ombi, Let's Encrypt, etc.) are running as Docker containers on a Synology DS918+. I am also only an amateur with Docker, so I don't know how to diagnose these things myself.

Thank you.

**Comment by tidusjar** [comment]
Does this happen in your local network when navigating to it internally? (Not using your FQDN)

**Comment by SturmB** [comment]
Hey, thanks for the response, @tidusjar. You're onto something.

Using a separate browser with a clean cache, it seems that navigating to `192.168.###.###:3579` brings up the login page almost immediately while using the FQDN (both attempts from inside the network) results in that aforementioned perpetual `Loading…` screen.

**Comment by tidusjar** [comment]
Yeah it's going to be something with your own reverse proxy setup. I'm not sure how I can help with this. Have you take a look at the reverse proxy examples on the wiki?

**Comment by SturmB** [comment]
Yes, I had a look at those examples, but I didn't see anything there that would help. Possibly the disabling of Websockets, but I'm not sure how to do that with my current setup, which is a Let's Encrypt Docker container.

So, yeah, I'm using the [Let's Encrypt Docker image](https://hub.docker.com/r/linuxserver/letsencrypt/) to do all of my reverse-proxying. It has been doing quite well for many months now. The only hiccup is this hanging at `Loading…`, which eventually goes away after a few browser refreshes. Here's the current nginx config for ombi:

```
# make sure that your dns has a cname set for ombi and that your ombi container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ombi.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi ombi;
        proxy_pass http://$upstream_ombi:3579;
    }

    # This allows access to the actual api
    location ~ (/ombi)?/api {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi ombi;
        proxy_pass http://$upstream_ombi:3579;
   }

    # This allows access to the documentation for the api
    location ~ (/ombi)?/swagger {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi ombi;
        proxy_pass http://$upstream_ombi:3579;
   }
   if ($http_referer ~* /ombi) {
       rewrite ^/swagger/(.*) /ombi/swagger/$1? redirect;
   }
}

# HTTP redirect
server {
    listen 80;
    listen [::]:80;

    server_name ombi.*;

    return 301 https://$host$request_uri;
}
```

I realize this may be out of the scope of this issue, so if you are unable to help me figure out what needs to be done, just please let me know and I'll see if I can get some help from the Linuxserver.io devs.

**Comment by tidusjar** [comment]
It might be worth going on the Ombi Discord and asking for some assistance. Sorry I cannot help any further
