### ISSUE TITLE
Submit disabled after upgrade for Emby/Jellyfin Configuration

### ISSUE THREAD

**Issue by bugsyb** [tidusjar/Ombi#3246]
**Describe the bug**
Submit button is disabled after upgrade for Emby/Jellyfin Configuration.
Previous Ombi version was: 3.0.4680, upgraded to: 3.0.4817.
Settings are correct, but can't Submit changes, disabling/enabling server doesn't help.

**Expected behavior**
Should be able to modify settings and submit changes (current settings are correct).

** OS:**
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

** Ombi Version: **
    Ombi Version 3.0.4817, upgraded from 3.0.4680 on which it was working fine.
    Jellyfin: 10.4.1 (but this doesn't play a role)

**Comment by tidusjar** [comment]
Press the new discover button and then it will be fine

**Comment by bugsyb** [comment]
The discovery/test button results in same issue as https://github.com/tidusjar/Ombi/issues/3245
Let's try first to fix the other one.
