### ISSUE TITLE
Plex "Recently Added" sync not working/notifying of new content

### ISSUE THREAD

**Issue by CorneliousJD** [tidusjar/Ombi#3249]
**Describe the bug**
Plex FULL sync is set to run at 2AM daily, which works fine and then issues e-mail notifications that new movies/shows are available for users, however the interval scan of recently added no longer works, as movies and shows that are downloaded do not notify users until 2AM daily.
This issue started on about October 15th, 2019 for me. I'm using the LinuxServer.io docker container..

**To Reproduce**
1. Setup Plex sync and add a request, and let the recently added sync run, you will not be notified of new content being available until the FULL syn runs.

**Expected behavior**
Expected behavior would be that the recently added sync would realize the new content is there and send the notification to the user that their content is available. 

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
The logs themselves show the IPlexContentSyncRecentlyAdded is running, but it doesn't seem to trigger any notifications ever, or may just not be ever finding anay content or episodes at all any longer?

019-10-29 20:00:00.002 -04:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2019-10-29 20:00:00.005 -04:00 [Information] Starting Plex Content Cacher Recently Added Scan
2019-10-29 20:00:00.005 -04:00 [Information] Starting to cache the content on server "XXXXXXXXXX"
2019-10-29 20:00:02.337 -04:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: True
2019-10-29 20:00:02.337 -04:00 [Debug] Trigger instruction : NoInstruction

**Desktop (please complete the following information):**
 - OS: Unraid Docker Container (LinuxServer.io)

**Ombi Version (please complete the following information):**
 - Version 3.0.4817
- Media Server Plex 1.18.2.2015

**Additional context**
Can provide other details if needed, just let me know.

**Comment by tidusjar** [comment]
This should be fixed in develop. I am about to publish a new release

**Comment by zellenberg** [comment]
If I am running the linuxserver docker image on Unraid, is there a way for me to use te develop branch?

**Comment by loheiman** [comment]
I'm having the same issue albeit intermittently. What steps can I take to troubleshoot this?
