### ISSUE TITLE
Ombi 100% CPU spikes

### ISSUE THREAD

**Issue by jLemmings** [tidusjar/Ombi#3252]
**Describe the bug**
Ombi process spikes CPU to 100%

**Expected behavior**
Should not happen

**Screenshots**
https://imgur.com/a/SPEq2My

**Logs (Logs directory where Ombi is located)**
Can I enable verbose logging somewhere? The only thing in the logs is this:
```
2019-11-12 07:26:13.387 +01:00 [Information] 1 scheduled job(s) enqueued.
2019-11-12 13:00:38.816 +01:00 [Information] 1 scheduled job(s) enqueued.
2019-11-12 19:00:51.320 +01:00 [Information] 1 scheduled job(s) enqueued.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3

**Ombi Version (please complete the following information):**
 - Version: 3.0.2935 
- Media Server: Plex
- Mono: 5.10.1.20

Please tell me if you need further information

**Comment by tidusjar** [comment]
Need some more information here.... What is Utility? 

At what time does it happen? Is there a specific background job that starts it. 

Also, what is your system specs....

**Comment by jLemmings** [comment]
Sorry should have specified that "Utility" is the VM running Ombi. The VM only has a single core and 2GB of RAM.

It seems to be a timely triggered spike as it always starts at ~XX:20 and ends at ~XX:55. During these spikes there is no one using Ombi.

**Comment by tidusjar** [comment]
And what is in your log file during this time period?

**Comment by jLemmings** [comment]
Mostly nothing funny enough, the only thing I find in my logs is this message at various times: `1 scheduled job(s) enqueued.`

**Comment by tidusjar** [comment]
In the `appsettings.json` (you can find this file where ombi is installed) can you change the log levels to debug and then restart ombi. You should have a lot more logging then

**Comment by jLemmings** [comment]
Hmm it seems like its already set to debug right?

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "None",
      "Hangfire": "None"
    }
  },
  "ApplicationSettings": {
    "Verison": "{{VERSIONNUMBER}}",
    "OmbiService": "https://ombiservice.azurewebsites.net/",
    "Branch": "{{BRANCH}}",
    "FriendlyVersion": "v3.0.0"
  },
  "UserSettings": {
    "WebsiteUrl": "http://localhost:52038",
    "UseHttps": false
  },
  "TokenAuthentication": {
    "SecretKey": "XXX"
  },
  "LandingPageBackground": {
    "Movies": [
      278,
      244786,
      680,
      155,
      13,
      1891,
      399106
    ],
    "TvShows": [
      121361,
      74205,
      81189,
      79126,
      79349,
      275274
    ]
  }
}
```

By checking the status of the ombi service I've found a probable source of the issue:
```
Nov 13 10:13:05 utility Ombi[24995]: warn: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[0]
Nov 13 10:13:05 utility Ombi[24995]:       The episode title XXXX we cannot find the parent series. The episode grandparentKey = XXX, grandparentTitle = 

```

Is this a known issue?

**Comment by jLemmings** [comment]
I just realized that I've been using an old version of Ombi. I have since upgraded and there haven't been any spikes the past hour.

I will keep this open until tomorrow and if everything seems fine will close the issue.

**Comment by tidusjar** [comment]
Yeah your right. I didn't notice it either! Very old version!

**Comment by jLemmings** [comment]
Issue is resolved, guess its easy to tell at what time I've updated Ombi.
https://imgur.com/a/S0K5Tsn
