### ISSUE TITLE
Unable to login to new v3.0.4880

### ISSUE THREAD

**Issue by fishtek** [tidusjar/Ombi#3256]
**Describe the bug**
When I attempt to login after upgrading to v3.0.4880, I click "Sign in with PLEX", and a new pops up like normal, however this window also has the same two login choice buttons. Click "Sign in with PLEX" again just causes another pop up over this one, I'm never redirected to the actual PLEX login page where I can actually authenticate like I had been doing in previous versions.

**To Reproduce**
1. The initial Ombi sign in page
2. Click on 'Continue' to get to the page that gives you the choice of signing in w/ Plex or with Ombi
3. Click on 'Sign in with Plex'
4. See that a pop up comes up but instead of the Plex login page I'm presented w/ the previous choices of Signing in with Plex or Signing in with Ombi again, and this will repeat forever with additional popups each time 'Sign in with Plex' is chosen.

**Expected behavior**
In previous versions after clicking 'Sign in with Plex' from the main page, the pop up redirects me to the actual Plex login page for authentication.

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - Browser is google chrome on linux

**Ombi Version (please complete the following information):**
- Ombi v3.0.4880
  - I'm using the LinuxServer.io version of ombi: https://hub.docker.com/r/linuxserver/ombi/
- Plex is v1.18.2.2015

**Additional context**
n/a

**Comment by paulfantom** [comment]
Same here. I can login with a browser that has cookies saved from previous ombi server version, but it failed when I tried to do that from a mobile phone (or from a browser with cleared cookies).

**Comment by tidusjar** [comment]
I cannot reproduce this, can you try clearing your browsers cache?

**Comment by bojia-chen** [comment]
Plex Authentication Server experienced an outage at around that time. I don't think this was an Ombi issue.

https://status.plex.tv/

**Comment by fishtek** [comment]
Tried clearing cache and hard reload, also cleared local cookies and assets in local and session storage. I don't think it is a temporary issue as the popup window simply displays the same as the original page https://ombi.mydomain.org/login/true. If I wait then both the pop up and the initial page will cycle the pretty backgrounds but that is it. Clickin on the "Sign in with Plex" simply opens another pop up window, but ultimately none of the popups are redirected to plex's sign in page like they used to be.

**Comment by GnaXi** [comment]
I'm having issues with my Emby imported users as well, after the latest update.
Local users work fine, but all Emby imported users are told that their password is incorrect. Not sure if it is related, but it seems like it.

**Comment by tidusjar** [comment]
@GnaXi  That would be a completely different problem. If it's still an issue for you can you please raise a separate issue.

@fishtek Is this still an issue for you as @bojia-chen mentioned that Plex Auth did have an outage

**Comment by paulfantom** [comment]
I can confirm login is working with latest ombi version.

**Comment by fishtek** [comment]
Yup things look good again, must have been the authentication or something w/ PLEX itself, thanks guys!
