### ISSUE TITLE
Accessing Request Owner via API or other source

### ISSUE THREAD

**Issue by ReichJordan** [tidusjar/Ombi#3258]
**Describe the bug**
Is it possible to identify through an API, text-file, etc. who requested what content from the system? API would be the best option but not sure this is a thing? If so, do you have documentation you could reference? And/or what other options could be possible.

We are attempting to identify who created the request programatically so the owner of the content file can be changed on the physical file. Allowing windows to track quota for individuals and use the system much like a DVR system by allocating space.

But we cannot do this if we cannot identify who made the request.

Thanks!

**To Reproduce**
Not Relevant

**Expected behavior**
Not Relevant

**Screenshots**
Not Relevant

**Logs (Logs directory where Ombi is located)**
Not Relevant

**Desktop (please complete the following information):**
 Windows Server 2016

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- PLEX Server 1.16.5.1554

**Additional context**
Not Relevant

**Comment by ReichJordan** [comment]
The best option I can find right now would be to utilize PoSH with the PSSQLite module.

Access the Ombi.db and leverage the AspNetUsers, MovieRequests, TVRequests, and RequestLog to pull a database view that contains the information needed above. But this is a rather involved process.

Hoping there is an easier solution available before I go down that route.

Thanks!

**Comment by tidusjar** [comment]
So you want to see all requests and who requested them? You can use the API for that. If you go to your ombi instance and then /swagger you will get the API documentation
