### ISSUE TITLE
Admin login not possible after Plex account delete

### ISSUE THREAD

**Issue by dinner95** [tidusjar/Ombi#3260]
**Describe the bug**
Admin login not possible after Plex account delete

**To Reproduce**
Go to login page
Try to Login with my admin credentials (Linked to Plex Account)
Login is not possible

**Expected behavior**
It would be great to get admin access to the server via shell commands if possible.

**Screenshots**
there re no screens

**Logs (Logs directory where Ombi is located)**
there re no logs yet

**Desktop (please complete the following information):**
 - OS: Docker Container (Linux) running on DSM

**Ombi Version (please complete the following information):**
 - Version 3.0.4875-develop

**Additional context**
After I deleted my Plex Account linked to my OMBI Admin, it is not possible to login with my admin user now. It is related to Plex login and OMBI Login.
After a look into the console of my Docker container, I can see, that Ombi is also not able to Logon at the Server anymore. So it will be not possible to sync any users from Plex.
Is there any chance to get back into Ombi via shell to create a new admin account?

Thanks a lot for your help in advance.

**Comment by dinner95** [comment]
Hi, i read the FAQ and the wiki and found nothing related to the topic.

**Comment by dinner95** [comment]
![image](https://user-images.githubusercontent.com/26787776/68792674-19e5e780-064c-11ea-97d5-1f9cedf9fadd.png)

**Comment by tidusjar** [comment]
If you deleted your Plex account that is the only admin account. There is nothing that can be done. I always recommend creating a local account

**Comment by dinner95** [comment]
Hi Jamie,

thank you for your fast reply.
I will reset my container.
