### ISSUE TITLE
XBMCnfoTV matching

### ISSUE THREAD

**Issue by kimpenhaus** [tidusjar/Ombi#3277]
**Describe the bug**
Please see text below, in short: TV shows are not mapped properly with XBMCnfoTV bundle.

**To Reproduce**
See text and screenshots

**Expected behavior**
Would be great to have TV-shows mapped properly.

**Screenshots**
in the text below

**Logs (Logs directory where Ombi is located)**
Can' t find relating entries in the logs but will provide with little help

**Desktop (please complete the following information):**
 - OS: [Docker - x64 - Linux 3.10.105 #24922]

**Ombi Version (please complete the following information):**
 - Version [3.0.4892]
- Media Server [Plex]

**Additional context**

----

Hi Jamie,

based on issue #2695 I assume that I am one of the very minority using the old `XBMCnfo` bundles with Plex - having nfo files with meta data. I saw in the other issue and its commits that you've added support for that - movies is very fine but with tv shows I have some problems.

I am using the `XBMCnfoTv`bundle together with provider `tvdb`. From commit cb7c799 I saw the regex you are using to determine wether the provider is imdb or tvdb is:

`"//[0-9]+/([0-9]{1,3})/([0-9]{1,3})"` 

I must confess I haven't debugged yet (cause I am mainly running on osx) but I think there is an issue with that. From what I can see Plex uses different styles wether it is the tv-show itself or just an episode of a season.

* TV-show guids look like: `com.plexapp.agents.xbmcnfotv://153021?lang=xn`
* Episode guids look like: `com.plexapp.agents.xbmcnfotv://153021/2/1?lang=xn`

I think it's plain simple to see that the regex is just matching those season/episode guids - not those of the show. And I think metadata is collected on top level?

At least that's what I think and that's why I think it leads to not matching shows - which is expressed by NULL values inside the db `OmbiExternal.db`:

<img width="1247" alt="grafik" src="https://user-images.githubusercontent.com/575109/69273603-ef120b00-0bd8-11ea-95c1-b25f60e471ba.png">

And of course no matching on the search view:

<img width="1243" alt="grafik" src="https://user-images.githubusercontent.com/575109/69273508-c7bb3e00-0bd8-11ea-8a04-df560a443208.png">

I am not pretty sure if you will do something about that - as it is not mainstream - but I will try to support you with as much information needed to get it working, if you want to 😁 

Thanks for your time,
cheers
m.

PS: Sorry for double posting - got some problems with the bot - hopefully he will let me pass this time 😉

**Comment by tidusjar** [comment]
Hey man!

Thanks for the detailed bug report and investigation! You have saved me a tonne of time! 

I'll add some more unit tests to cover this scenario to see if I can reproduce it and then fix it. 

Thanks.

**Comment by tidusjar** [comment]
Question, do you know what the value is for the IDs? Is it TvDb for tv and themoviedb for movies?

**Comment by tidusjar** [comment]
I've pushed some changes to develop, but I'm making the assumption that movies will not be in that format: `//153021?lang=xn`

If this is not the case can you please let me know and I can see what I can do for the movies.

**Comment by kimpenhaus** [comment]
Hey Jamie,

wow that was quick - thanks a thousand times.

Regarding your questions:

* on my site movie GUIDs look like `com.plexapp.agents.xbmcnfo://tt0120586?lang=xn`

But in general you have the ability to set the provider - in my case its imdb - thats why movie id's look like this and works out of the box). [Kodi movies nfo](https://kodi.wiki/view/NFO_files/Movies#nfo_Tags)

Same is for the TV shows ([Kodi tv-shows nfo](https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags_2) - I am fine with the assumptions you did. (as I use the provider tvdb with shows)

As soon as my docker gets updated I will let you know if it works - thanks again!

**Comment by tidusjar** [comment]
Excellent, let me know how it goes, this will only be available in the develop version of the docker container as this has not been pushed to master yet

**Comment by kimpenhaus** [comment]
<img width="1304" alt="grafik" src="https://user-images.githubusercontent.com/575109/69374477-69f52780-0ca6-11ea-964a-c742efa00eaf.png">

That's great mate! Works :+1:

Thanks a lot!

**Comment by tidusjar** [comment]
Excellent!
