### ISSUE TITLE
Tv Shows not showing in search even though they're in imdb

### ISSUE THREAD

**Issue by AllTheThangz** [tidusjar/Ombi#3284]
**Describe the bug**
When searching for the shows or movies, a lot of actual titles are missing from results.

**To Reproduce**
1. Login to ombi
2. Click tv show search
3. Search for "Daybreak" (IMDb tt8755226)
4. See results missing actual show

**Expected behavior**
Expected result to include known title tt8755226 

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: docker

**Ombi Version (please complete the following information):

Version | 3.0.4892
Branch | master
Linux 5.3.12-Unraid #1 SMP Wed Nov 20 10:57:39 PST 2019
Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
Have you read this: https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all ?

**Comment by AllTheThangz** [comment]
Yes,

The tvdb Id is there.

**Comment by tidusjar** [comment]
http://api.tvmaze.com/search/shows?q=Daybreak

Nope, there is no tvdbid.
