### ISSUE TITLE
2 features not working - details in report

### ISSUE THREAD

**Issue by soulvoid86** [tidusjar/Ombi#3286]
**Describe the bug**
Ombi is no longer detecting when items are successfully added to Plex. This was working initially, but stopped working at a random point, not sure when. I noticed that my email notifications had slowed down from Ombi. There are a ton of errors in the log about this regarding SQL when I tried to run a full scan, but I have no idea what is happening. You can see this in the first few lines. Partial scans don't work either.

I did migrate this DB from a Windows installation, but everything was working fine for weeks.

My suggestions for Movies is not working either. The page just shows the search bar, and nothing shows up until you actually search for a Movie. TV Shows works just fine, and every other feature works fine, except the other listed above of course.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
[log-20191126.txt](https://github.com/tidusjar/Ombi/files/3893936/log-20191126.txt)

**Desktop (please complete the following information):**
 - OS: Windows? I'm not sure what you're asking here. But the server is running Linux.

**Ombi Version (please complete the following information):**
 - Version - v3.0.4892
 - Media Server - Plex

**Additional context**

**Comment by tidusjar** [comment]
Both issues relate to #3253
