### ISSUE TITLE
[Feature Request]  Subscribe to existing requests

### ISSUE THREAD

**Issue by Cessquill** [tidusjar/Ombi#3288]
Hi - would be a nice-to-have if...

- User1 requests a title
- User2 tries to request same title, sees it has been requested
- User2 has the ability to subscribe to notifications for that title
- Both User1 and User2 receive notifications when title is available

**Comment by tidusjar** [comment]
This is current functionality

**Comment by Cessquill** [comment]
D'OH!  Many apologies - it was a shower thought this morning.
