### ISSUE TITLE
Ombi Posts 500 for all Movie API requests.

### ISSUE THREAD

**Issue by Archmonger** [tidusjar/Ombi#3289]
**Describe the bug**
HTTP 500 error is received on api/movies requests. Everything movie API related is broken (movie related search/home discovery/mobile app). Does not occur on TV searches.

**To Reproduce**
Version 3.0.4822 is functions properly, 3.0.4825 does not. Linuxserver docker image.

**Expected behavior**
Movie searches should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/16909269/69795803-af6f9400-1181-11ea-91ce-3d7e820b928c.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version: 3.0.4817-ls37
- Media Server: Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
#3253
