### ISSUE TITLE
Changing main folder for specific requested movies

### ISSUE THREAD

**Issue by miniliQuid** [tidusjar/Ombi#3300]
**Describe the bug**
Not sure if this is correct, but for TV shows I can change the main directory manually before accepting requests (even after they are accepting but still being searched for).

However when looking at movies I have no such option which is causing some issues. Is this just missing for movies, or have I done something wrong?

Ombi is linked to Sonarr & Radarr.

**To Reproduce**
Simply go to movie requests and compare it to series requests. Series have the option to edit main folder, movies do not for some reason.

**Expected behavior**
I expect it to show the line "main folder" or "root folder" or whatever it says at series where you can switch the folder for your different series submaps (documentaries, anime, daily shows, normal shows). For my movies I have two folders (movies & new movies) which I would like to be able to pick from in which directory the requested movie ends up.

**Screenshots**
N/A for now

**Logs (Logs directory where Ombi is located)**
Not really a bug I think so no log available

**Desktop (please complete the following information):**
Windows 10 running as a service in NSSM

**Ombi Version (please complete the following information):**
3.0.4887

**Additional context**
Hope this already suffices.

**Comment by miniliQuid** [comment]
Anyone able to give me some insight on this?

**Comment by miniliQuid** [comment]
bump

**Comment by tidusjar** [comment]
Please do not "bump" issues.

I have a full time demanding job, a wife, a 3 year old at home. I cannot spend my whole time replying to you. If I have not yet replied it is because I've not had a chance.

This is what is appearing for me with it hooked up to Radarr
![Screenshot 2019-12-11 at 8 24 58 pm](https://user-images.githubusercontent.com/6642220/70657832-8b698380-1c54-11ea-8833-e87c74c6458b.png)

**Comment by goldenpipes** [comment]
I think your user permissions are set incorrectly. IIRC there is a permission to be able to change root folders/quality profiles.

**Comment by miniliQuid** [comment]
> 
> 
> Please do not "bump" issues.
> 
> I have a full time demanding job, a wife, a 3 year old at home. I cannot spend my whole time replying to you. If I have not yet replied it is because I've not had a chance.
> 
> This is what is appearing for me with it hooked up to Radarr
> ![Screenshot 2019-12-11 at 8 24 58 pm](https://user-images.githubusercontent.com/6642220/70657832-8b698380-1c54-11ea-8833-e87c74c6458b.png)

Sorry, new to ombi and also pretty new to github (don't tend to use it much, if at all). Noticed this was one of the few ways to get issues solved but it seemed abandoned. May just be that it works somewhat different than other forums. Also tried to get it solved before having to go away for a bit but I understand it's annoying.

Anyway thanks for your reply. As to your picture, that is what my TV section looks like. However when going to Movie section the root folder and quality drop away for some reason:

![ombi](https://user-images.githubusercontent.com/46374109/71190813-8a080e80-2285-11ea-8da8-08eac2306be0.jpg)



> 
> 
> I think your user permissions are set incorrectly. IIRC there is a permission to be able to change root folders/quality profiles.

Thanks for your reply as well. Can you point me to the specific permissions? Is this seperate from tv permission? Currently TV section works as expected, just movies don't. Also, I am using the admin account and given myself power user to be sure. But perhaps it gets messed up instead that way?
