### ISSUE TITLE
Various Error's in Console

### ISSUE THREAD

**Issue by jonnwhite1** [tidusjar/Ombi#3302]
**Describe the bug**
Various errors (Attached) When searching for something it's taking a long time to load. The orange bar at the top is staying right at the end for around 4 minutes. 

**To Reproduce**
Launch webpage without even searching

**Expected behavior**
Results to be returned quickly. 

**Screenshots**
Please see attachments 

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex
![omb2](https://user-images.githubusercontent.com/51175698/70381401-8a2d1380-1941-11ea-9289-361626385f1d.PNG)
![Ombi1](https://user-images.githubusercontent.com/51175698/70381402-8a2d1380-1941-11ea-9142-1912436cee53.PNG)

**Additional context**
Have tried downgrading, rebooting and reinstalling. Orange Bar shown in image below.
Unsure what it's failing to connect to via HTTP, have reconnected, Plex, Sonarr, Radarr and Lidarr. Deleted OmbiExternal.db etc. 

![Orange bar](https://user-images.githubusercontent.com/51175698/70381418-b3e63a80-1941-11ea-8d3b-8cd036495533.PNG)

**Comment by jonnwhite1** [comment]
Now also getting the attached


![new](https://user-images.githubusercontent.com/51175698/70381454-6918f280-1942-11ea-93ff-27d73d7cfc9c.PNG)

**Comment by tidusjar** [comment]
Most of those errors are your server failing to communicate with FanArt.tv. That's why it still "appears" as loading. Just trying to load additional images.

**Comment by jonnwhite1** [comment]
Hmmm okay, anything i can do? it's making Ombi pretty much unusable :(

**Comment by MrBrax** [comment]
Happening to me too with the FanArt.tv requests

**Comment by lord-carlos** [comment]
> Various errors (Attached) When searching for something it's taking a long time to load. The orange bar at the top is staying right at the end for around 4 minutes.

I have similar problems. Sadly I don't see any related errors either browser terminal or docker.
Sometimes the sites just does not really response. 
Not sure how I can debug this.

**Comment by tidusjar** [comment]
Is this still happening? As this is outside of my control, it's either 
1. FanArt's servers are having an issue
1. Your network is not allowing FanArt requests

**Comment by MrBrax** [comment]
Yes, it's fixed now. You should probably add a try-catch/error handler to the request so it doesn't stall the whole interface

**Comment by tidusjar** [comment]
It shouldn't stall the whole interface as mentioned above. But I am always welcoming PRs.

**Comment by MrBrax** [comment]
It made the javascript ajax portion stop working. You couldn't click on the tabs for searching different kinds of media for example.

**Comment by MrBrax** [comment]
So what's happening is not fanart.tv being down, it's them displaying something else than JSON. There's no check when you're trying to parse the response from the server.

**Comment by tidusjar** [comment]
How do you know this?

**Comment by MrBrax** [comment]
Because it's trying to deserialize a '<', very common in the start of HTML documents. FanArts' site probably errored out without caring about making a JSON response, and Ombi chugged on it.

**Comment by tidusjar** [comment]
In that case an exception will be thrown and the request aborted. It would do hold up the UI. again I'm open for PRs

**Comment by MrBrax** [comment]
I mean it's obviously not catching something.
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.FanartTv.FanartTvApi.GetTvImages(Int32 tvdbId, String token) in C:\projects\requestplex\src\Ombi.Api.FanartTv\FanartTvApi.cs:line 27
```

I can't test/pr it since they don't have an issue anymore, but there's something to it.

**Comment by tidusjar** [comment]
Correct, we are not catching that, because we cannot parse that document, it's not what we expect. The correct thing to do is for the exception to bubble up to the surface and not swallow it... I'm not sure what you are getting at here.
