### ISSUE TITLE
Ombi db to MySQL documentation 

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#3305]
**Describe the bug**
Documentation on db migration. 

**To Reproduce**
Try and migrate to Mysql. 

**Expected behavior**
 Documentation on migrating Ombi Db to MySQL. 

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version [latest]
- Media Server [plex latest]

**Additional context**
Is there any documentation on how to migrate the Ombi db to MySQL? I saw this, but no info on how to implement:

https://github.com/tidusjar/Ombi/pull/3241

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database

**Comment by vctls** [comment]
Current link:
https://docs.ombi.app/guides/migrating-databases/
