### ISSUE TITLE
After migration to MySQL Ombi will not start

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#3306]
**Describe the bug**
I followed the steps outlined here with not problems:

https://github.com/tidusjar/Ombi/wiki/Using-a-different-database

**To Reproduce**
Followed these steps with no errors:
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database

**Expected behavior**
That Ombi be able to start.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Executed the migration and here is the output:

c:\ombi_sqlite_mysql>python ombi_sqlite2mysql.py -c C:\OmbiV3 --host localhost --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.2) By VSC55

Generate file "database.json":
- Saving in (C:\OmbiV3\database.json)... [Γ£ô]

MySQL > Connecting... [Γ£ô]
- Reading   [############################################################] 1/1
Read tables [Γ£ô]

Check migration.json:
- SettingsDatabase [SQLite >> Migrate]
- OmbiDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- SettingsDatabase  [############################################################] 26/26
- OmbiDatabase      [############################################################] 15735/15735
- ExternalDatabase  [############################################################] 14150/14150

Start clean tables:
- [CLEAN ] -> applicationconfiguration -> rows: 3
- [CLEAN ] -> aspnetusers -> rows: 1
- [CLEAN ] -> globalsettings -> rows: 2
- [CLEAN ] -> notificationtemplates -> rows: 90
- [CLEAN ] -> __efmigrationshistory -> rows: 3

- Running   [############################################################] 5/5
Clean tables [Γ£ô]

Start Migration:
- Preparing [############################################################] 29923/29923
- Running   [############################################################] 29836/29836
- [!!] -> __efmigrationshistory -> [SQLite (0) / MySQL (40)] = -40
- [!!] -> applicationconfiguration -> [SQLite (0) / MySQL (3)] = -3
- [!!] -> aspnetroles -> [SQLite (0) / MySQL (12)] = -12
- [!!] -> aspnetuserroles -> [SQLite (0) / MySQL (33)] = -33
- [!!] -> aspnetusers -> [SQLite (0) / MySQL (11)] = -11
- [!!] -> audit -> [SQLite (0) / MySQL (703)] = -703
- [!!] -> childrequests -> [SQLite (0) / MySQL (102)] = -102
- [!!] -> episoderequests -> [SQLite (0) / MySQL (1832)] = -1832
- [!!] -> globalsettings -> [SQLite (0) / MySQL (11)] = -11
- [!!] -> movierequests -> [SQLite (0) / MySQL (453)] = -453
- [!!] -> notificationtemplates -> [SQLite (0) / MySQL (90)] = -90
- [!!] -> plexepisode -> [SQLite (0) / MySQL (3325)] = -3325
- [!!] -> plexseasonscontent -> [SQLite (0) / MySQL (39)] = -39
- [!!] -> plexservercontent -> [SQLite (0) / MySQL (1450)] = -1450
- [!!] -> radarrcache -> [SQLite (0) / MySQL (1381)] = -1381
- [!!] -> recentlyaddedlog -> [SQLite (0) / MySQL (4196)] = -4196
- [!!] -> requestlog -> [SQLite (0) / MySQL (479)] = -479
- [!!] -> requestqueue -> [SQLite (0) / MySQL (3)] = -3
- [!!] -> seasonrequests -> [SQLite (0) / MySQL (163)] = -163
- [!!] -> sonarrcache -> [SQLite (0) / MySQL (149)] = -149
- [!!] -> sonarrepisodecache -> [SQLite (0) / MySQL (15264)] = -15264
- [!!] -> tvrequests -> [SQLite (0) / MySQL (97)] = -97
- Checking  [############################################################] 43/43

MySQL > Disconnecting... [Γ£ô]

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Ombi Version (please complete the following information):**
 - Version [e.g. v3.0.4892]
- Media Server [e.g. Plex 1.18.2.2058-e67a4e892]

**Additional context**
I typlically start ombi as a service and after noticing that I could not log in in to the GUI, I went back and noticed that the services kept toggling from Running to Starting in a loop. 

I then started Ombi in the foreground and saw the following: 

C:\OmbiV3>Ombi.exe
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.4892-master
Copyright (C) 2019 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
               of URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "*" to indicate that the server should
               listen for requests on any IP address or hostname using the
               specified port and protocol (for example, http://*:5000). The
               protocol (http:// or https://) must be included with each URL.
               Supported formats vary between servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --help       Display this help screen.

  --version    Display version information.

Unhandled Exception: MySql.Data.MySqlClient.MySqlException: Table 'applicationconfiguration' already exists ---> MySql.Data.MySqlClient.MySqlException: Table 'applicationconfiguration' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 111
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlConverterCommandBuilderFactory.MySqlConverterRelationalCommandBuilder.MySqlConverterRelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 61

C:\OmbiV3>

It appears to be complaining about  table 'applicationconfiguration' already existing which I would expect give that the migration output I show above, shows that this table was migrated. If I go into MySQL, I can see that table along with the others that were migrated:

+-----------------------------+
| Tables_in_ombi              |
+-----------------------------+
| __efmigrationshistory       |
| albumrequests               |
| applicationconfiguration    |
| aspnetroleclaims            |
| aspnetroles                 |
| aspnetuserclaims            |
| aspnetuserlogins            |
| aspnetuserroles             |
| aspnetusers                 |
| aspnetusertokens            |
| audit                       |
| childrequests               |
| couchpotatocache            |
| embycontent                 |
| embyepisode                 |
| episoderequests             |
| globalsettings              |
| issuecategory               |
| issuecomments               |
| issues                      |
| lidarralbumcache            |
| lidarrartistcache           |
| movierequests               |
| notificationtemplates       |
| notificationuserid          |
| plexepisode                 |
| plexseasonscontent          |
| plexservercontent           |
| radarrcache                 |
| recentlyaddedlog            |
| requestlog                  |
| requestqueue                |
| requestsubscription         |
| seasonrequests              |
| sickragecache               |
| sickrageepisodecache        |
| sonarrcache                 |
| sonarrepisodecache          |
| tokens                      |
| tvrequests                  |
| usernotificationpreferences |
| userqualityprofiles         |
| votes                       |
+-----------------------------+
43 rows in set (0.01 sec)

Even running Ombi.exe --version produces the above errors and this pop-up:
![image](https://user-images.githubusercontent.com/20881936/70776415-9e5a8180-1d42-11ea-9c44-e6246c012498.png)

MySQL is running 8.0.18.0. The Ombi logs do not show anything current, so that's why I started in the foreground to see what the issue was.

Also checked the tables that were migrated over to make sure they are not corrupted:
c:\Program Files\MySQL\MySQL Server 8.0\bin>mysqlcheck.exe -c Ombi -u root -p
Enter password: ********
ombi.__efmigrationshistory                         OK
ombi.albumrequests                                 OK
ombi.applicationconfiguration                      OK
ombi.aspnetroleclaims                              OK
ombi.aspnetroles                                   OK
ombi.aspnetuserclaims                              OK
ombi.aspnetuserlogins                              OK
ombi.aspnetuserroles                               OK
ombi.aspnetusers                                   OK
ombi.aspnetusertokens                              OK
ombi.audit                                         OK
ombi.childrequests                                 OK
ombi.couchpotatocache                              OK
ombi.embycontent                                   OK
ombi.embyepisode                                   OK
ombi.episoderequests                               OK
ombi.globalsettings                                OK
ombi.issuecategory                                 OK
ombi.issuecomments                                 OK
ombi.issues                                        OK
ombi.lidarralbumcache                              OK
ombi.lidarrartistcache                             OK
ombi.movierequests                                 OK
ombi.notificationtemplates                         OK
ombi.notificationuserid                            OK
ombi.plexepisode                                   OK
ombi.plexseasonscontent                            OK
ombi.plexservercontent                             OK
ombi.radarrcache                                   OK
ombi.recentlyaddedlog                              OK
ombi.requestlog                                    OK
ombi.requestqueue                                  OK
ombi.requestsubscription                           OK
ombi.seasonrequests                                OK
ombi.sickragecache                                 OK
ombi.sickrageepisodecache                          OK
ombi.sonarrcache                                   OK
ombi.sonarrepisodecache                            OK
ombi.tokens                                        OK
ombi.tvrequests                                    OK
ombi.usernotificationpreferences                   OK
ombi.userqualityprofiles                           OK
ombi.votes                                         OK

c:\Program Files\MySQL\MySQL Server 8.0\bin>

Any ideas or suggestions on the best way to move forward? For now, removing database.json and migration.json out of the Ombi directory allows me to start it up .

**Comment by tidusjar** [comment]
Looks like the migration didn't happen correctly in your MySQL database,
can you post the contents of the __efmigrationshistory table?
