### ISSUE TITLE
[wish] better user isolation

### ISSUE THREAD

**Issue by aka-charos** [tidusjar/Ombi#3307]
Firstly let me thank you for all your efforts in Ombi.

If I could add this wish/request: Provide an option for isolating users by setting up an option to hide usernames on "Issues > Reported by" username and also on the user who requested a movie/tv show.
This information (to me at least) seems relevant only to admins -not on regular user accounts.
That way users can do requests and report issues , while keeping their privacy to other end users.

Just planting seeds :)

**Comment by CaptAintHere** [comment]
+1 it could be great to have a user isolation similar to Tautulli : users can see all requests/issues but the author is anonymized.
