### ISSUE TITLE
Mobile version - menu isn’t going away

### ISSUE THREAD

**Issue by fillilutten** [tidusjar/Ombi#3316]
**Describe the bug**
When using the site on a phone the menu isn’t hiding after you click an menu option. The menu option is loaded behind and then you have to push the burger icon to make the menu go away. 

**To Reproduce**
1. Click on ' burger menu on an phone'
2. Click on '' A menu option “

**Expected behavior**
Menu should go away after menu option is done

**Ombi Version (please complete the following information):**
 - Version 3.0.4892

**Comment by tidusjar** [comment]
This will be resolved in V4.
