### ISSUE TITLE
[Feature Request] Allow subscribing to existing requests (automatic requests, not user requests)

### ISSUE THREAD

**Issue by 0aeonnoea0** [tidusjar/Ombi#3322]
**Describe the bug**
Currently when searching, if the desired media item is "requested" by virtue of it already being in Sonarr / Radarr / etc., the subscribe button is hidden. It would be great if users could subscribe so they can be notified when new movies / TV shows come out etc.

**To Reproduce**
1. Add a movie in Radarr (or TV show in Sonarr...)
2. Search for that movie in Ombi
3. Subscribe button isn't visible

**Expected behavior**
Would like the subscribe button to be available in this case.

**Screenshots**
Missing subscribe button:
![image](https://user-images.githubusercontent.com/46950349/71563295-f4d6f800-2a84-11ea-9480-8b526ca04724.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: All

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]: 3.0.4892
- Media Server [e.g. Plex] Plex

**Additional context**

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks
