### ISSUE TITLE
Movie permission issue?

### ISSUE THREAD

**Issue by miniliQuid** [tidusjar/Ombi#3323]
**Describe the bug**
Sorry in advance for starting this one again, but since I haven't been able to resolve the problem and the previous topic is closed I feel the need to create this issue once more.Not sure if this is correct, but for TV shows I can change the main directory manually before accepting requests (even after they are accepting but still being searched for).

However when looking at movies I have no such option which is causing some issues. Is this just missing for movies, or have I done something wrong?

Ombi is linked to Sonarr & Radarr.

**To Reproduce**
Simply go to movie requests and compare it to series requests. Series have the option to edit main folder, movies do not for some reason.

**Expected behavior**
I expect it to show the line "main folder" or "root folder" or whatever it says at series where you can switch the folder for your different series submaps (documentaries, anime, daily shows, normal shows). For my movies I have two folders (movies & new movies) which I would like to be able to pick from in which directory the requested movie ends up.

**Screenshots**
![ombi](https://user-images.githubusercontent.com/46374109/71547172-d4337300-299c-11ea-89bc-af44083350be.jpg)

**Logs (Logs directory where Ombi is located)**
Not really a bug I think so no log available

**Desktop (please complete the following information):**
Windows 10 running as a service in NSSM

**Ombi Version (please complete the following information):**
3.0.4887

**Additional context**
Above is the picture of how movies and series show up for me after request. In previous topic (https://github.com/tidusjar/Ombi/issues/3300) goldenpipes already mentioned it might be a user permission issue. I am however the admin account (also have power user on), so I am unsure which specific permission would allow me to change folder/quality for movies specifically (since I can already do so for TV shows it seems).

Hope someone can help me out, any replies are appreciated.

**Comment by tidusjar** [comment]
I cannot seem to reproduce this. Can you try setting up a fresh separate install and see if it still happens for you?

**Comment by miniliQuid** [comment]
Thanks for the reply, will try and do this today and see if that solves it.

**Comment by miniliQuid** [comment]
Nice, that worked like a charm, thanks for helping.
2 questsions:

1. After chosing root folder with movies, the choice option is gone (so picking wrong folder by accident when changing, means you have to remove and request), while with shows, the option to pick is still there. Is this working as intended or is there still something wrong with my installation.

It's no big problem since I can work with it just fine this way, just wondering if I have something tangled again in case I get more bug like things, then I'll just reinstall before asking for help.

2. Think this is more like a request, but when setting up sonarr in ombi there is the choice to fill in show information and seperate anime information. However when selecting season folders there is one single option that goes for both, either create season folders or not. In sonarr this is decided on a show by show basis. Can this be implemented to Ombi somehow (or at least a seperate box for the anime)? I use season folders for my shows and documentaries, but my anime goes by absolute order so no season folders.

Thanks in advance for your reply!

**Comment by tidusjar** [comment]
1. Is resolved in v4
2. I can add to v4!
