### ISSUE TITLE
plex film status not updated on ombi

### ISSUE THREAD

**Issue by gandalf764** [tidusjar/Ombi#3326]
**Describe the bug**
I have a problem, if a film already requested is deleted from the plex library, OMBI does not update the status of the request and is always available even if in reality it is no longer on plex.
can it be solved? thank you.

**To Reproduce**
1. make a movie request
2. wait for the request to be completed and OMBI to mark it as AVAILABLE
3. Delete the film from plex
4. su ombi will always be marked as AVAILABLE while the reality of the film is gone

**Expected behavior**
after a synchronization with plex (also manual) ombi must point out that the film is no longer available

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server PLEX: 1.18.3.2156

**Additional context**

**Comment by tidusjar** [comment]
There is a job that runs every 5 days by default that will fix this.

If you want it to run sooner (I suggest it's not that often, you can change it in the jobs settings page)
