### ISSUE TITLE
Return a request to a user

### ISSUE THREAD

**Issue by gandalf764** [tidusjar/Ombi#3332]
**Describe the bug**
If a user makes a request which is then not available, it would be necessary to be able to return the request to his account but it does not seem possible to do so except increase the maximum number of requests available for that user.

**To Reproduce**

**Expected behavior**
Is it possible to increase only 1 request with a dedicated key?
thank you

**Screenshots**
![screenshot_261](https://user-images.githubusercontent.com/41706025/71746399-14976300-2e6d-11ea-8f4c-166e8b854a4d.png)

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex 1.18.3.2156

**Additional context**
thanx

**Comment by tidusjar** [comment]
This doesn't make sense. Ombi has no idea if you have the ability to fulfill that request before actually requesting.

The whole point is a request is made and the user has the ability to request X number of items. If you cannot fulfill that request, that's not down to Ombi.

**Comment by gandalf764** [comment]
I don't mean that, maybe I explained myself wrong.
I would like the possibility to manually add 1 request to the user. maybe
through a +1 key or by going to manually edit some files.
thank you

Il lun 6 gen 2020, 09:24 Jamie <notifications@github.com> ha scritto:
