### ISSUE TITLE
Fresh Database: SQLite Error 5: 'database is locked'

### ISSUE THREAD

**Issue by 5drH64gDnDJb** [tidusjar/Ombi#3340]
**Describe the bug**
I started a fresh install/database thinking that would resolve the issue a couple months ago, but I continue to get "Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'." I even have it reboot nightly to clean up the error, but still happens every day.

If I reboot I am able to log into the plex request site, but at some point during the day, if you try to login again, I am not able to get in, after 30 seconds or so you will see the database is locked error and will have to reboot the server.

**Logs**
[log-20200115.txt](https://github.com/tidusjar/Ombi/files/4066188/log-20200115.txt)
[log-20200114.txt](https://github.com/tidusjar/Ombi/files/4066191/log-20200114.txt)
[log-20200113.txt](https://github.com/tidusjar/Ombi/files/4066192/log-20200113.txt)
[log-20200112.txt](https://github.com/tidusjar/Ombi/files/4066194/log-20200112.txt)
[log-20200111.txt](https://github.com/tidusjar/Ombi/files/4066196/log-20200111.txt)
[log-20200110.txt](https://github.com/tidusjar/Ombi/files/4066197/log-20200110.txt)
[log-20200109.txt](https://github.com/tidusjar/Ombi/files/4066198/log-20200109.txt)
[log-20200108.txt](https://github.com/tidusjar/Ombi/files/4066200/log-20200108.txt)
[log-20200107.txt](https://github.com/tidusjar/Ombi/files/4033297/log-20200107.txt)
[log-20200106.txt](https://github.com/tidusjar/Ombi/files/4033298/log-20200106.txt)
[log-20200105.txt](https://github.com/tidusjar/Ombi/files/4033300/log-20200105.txt)
[log-20200104.txt](https://github.com/tidusjar/Ombi/files/4033301/log-20200104.txt)
[log-20200103.txt](https://github.com/tidusjar/Ombi/files/4033302/log-20200103.txt)

**Desktop:**
 - OS: Server 2019

**Ombi Version:**
 - Version: 3.0.4958
- Media Server: Plex

**Comment by tidusjar** [comment]
Please use MySql, it seems that we have outgrown sqlite
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database

**Comment by 5drH64gDnDJb** [comment]
Thanks, I had no idea, I'll do that today!
