### ISSUE TITLE
Movies not included in Newsletter

### ISSUE THREAD

**Issue by Cessquill** [tidusjar/Ombi#3342]
When weekly emails go out, it is just TV shows.  Ombi is aware of the movies and they can be successfully requested and show up as available.  Movies are not disabled in the Newsletter Settings.  Thinking about it, Music is not included either.

Weekly email set to go out every Friday.

Movies (and Music) expected to be included in Newsletter email.

**Screenshots**
Can provide screenshots if required, but not sure what of.

**Logs (Logs directory where Ombi is located)**
Have attached today's log - not sure what I'm looking for
[log-20200110.zip](https://github.com/tidusjar/Ombi/files/4045524/log-20200110.zip)

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
- Version: 3.0.4892
- Media Server: Plex

**Additional context**
No extra content at the moment.  Hopefully it's just me being stupid!

**Comment by the-llama** [comment]
Also having this same issue; I see multiple instances of this error are the time of the newsletter being creating/sent:
2020-01-11 09:04:29.630 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00

[log-20200111.txt](https://github.com/tidusjar/Ombi/files/4049514/log-20200111.txt)

**Comment by Cessquill** [comment]
Yes, I see the same in my log now I look back.  Interesting.

**Comment by the-llama** [comment]
I should also add, I've had a normally working newsletter going for over a year, it was working as expected up until early December I believe. I think I deleted those emails so I'm not completely sure but it's been at least a few weeks.

**Comment by Cessquill** [comment]
I thought I had adhered to the template.  I'll try again shortly.
