### ISSUE TITLE
V4: Testing, Unable to delete requests

### ISSUE THREAD

**Issue by stevezau** [tidusjar/Ombi#3345]
Hi,

I wasn't sure where to post this. I am testing v4 and noticed there is no ability to delete requests once they are made available.

Is this simply because it has not been impl yet or a bug?

Thanks

**Comment by tidusjar** [comment]
It's in the latest version. Just need to fix the build

**Comment by stevezau** [comment]
Thanks! i'll wait for the docker img to be pushed then will test linuxserver/ombi:v4-preview
