### ISSUE TITLE
Movies not included in weekly newsletter

### ISSUE THREAD

**Issue by the-llama** [tidusjar/Ombi#3348]
**Describe the bug**
I have a weekly newsletter that recently (last month or so) stopped including any movies. The 'Movies' section is not present. New TV shows are still being shown. 
I have added new movies and Ombi is able to see those movies as present in Plex.

**To Reproduce**
1. Add new movies to Plex
2. Run newsletter cron job (Sending a test newsletter does show a sampling of already existing movies)
3. Movies are not displayed

**Expected behavior**
Movies should be displayed when enabled in the newsletter configuration

**Screenshots**
Recent email:
[Ombi on NEON_ Recently Added Content!.zip](https://github.com/tidusjar/Ombi/files/4056730/Ombi.on.NEON_.Recently.Added.Content.zip)
Newsletter config:
![Ombi1](https://user-images.githubusercontent.com/30959012/72304123-d1877d80-362c-11ea-9ac3-0e511fea8507.png)

**Logs (Logs directory where Ombi is located)**
[log-20200111.txt](https://github.com/tidusjar/Ombi/files/4056732/log-20200111.txt)
I noticed an interesting log message around the time the newsletter is being generated:
`2020-01-11 09:04:19.180 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/?api_key=b8eabaf5608b88d0298aa189dd90bf00`
repeated a dozen or so times.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plex is on Server 2012 R2 if that matters.
**Ombi Version (please complete the following information):**
 - Version [3.0.4892]
- Media Server [Plex 1.18.4.2171]

**Comment by Cessquill** [comment]
Thanks for opening this - I'm no good on here and my report got auto-closed (https://github.com/tidusjar/Ombi/issues/3342).

Same issue here with same repeated lines in log, but running in docker on Unraid.

**Comment by tidusjar** [comment]
Hey guys.

Just to make you aware, I am aware of this issue. Just not had much time
recently to fix it.

**Comment by the-llama** [comment]
@tidusjar Thanks much for the note, appreciate it!

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by Cessquill** [comment]
Should this have filtered down to the Unraid build yet?  Not sure whether I need to do anything (or wait).
