### ISSUE TITLE
TVDBID

### ISSUE THREAD

**Issue by bbakermmc** [tidusjar/Ombi#3353]
**Describe the bug**
Use TVDBID in search.

Can you point me to where I could make a PR that would take a token like "tvdbid=1232" as a search criteria and then it goes out to the tvdb api and pulls the name, passes that to tvmaze, if tvmaze doesnt have the tvdbdid external it uses the one from the tvdb api?  Its kinda hacky but figured it would be a quicker pr then to do a whole tvmaze replace.

**To Reproduce**
None - Help request

**Expected behavior**
Search for shows via tvdbid/api instead of tvmaze

**Screenshots**
NA

**Logs (Logs directory where Ombi is located)**
NA

**Desktop (please complete the following information):**
NA

**Ombi Version (please complete the following information):**
NA

**Additional context**
NA

**Comment by tidusjar** [comment]
I'd welcome this PR, you need to change the frontend angular code and also the backend.

**Comment by bbakermmc** [comment]
Yeah I was expecting a little more direction then update the front end and back end.  But its okay.  I just wont contribute lol, can just manually find in Sonarr/Radarr w/out Ombi, seems to be they adding features to make Ombi obsolete anyways.
