### ISSUE TITLE
Update to v3.0.4892 is failing 

### ISSUE THREAD

**Issue by fitzy2211** [tidusjar/Ombi#3354]
**Describe the bug**
I am trying to follow the process outlined in https://github.com/tidusjar/Ombi/wiki/Update-Settings.
I am currently on v3.0.3988
When following the guide, it mentions database.json which I cannot locate.
Once I follow the guide and start up ombi again, I keep getting an error message and none of my requests/search is shown. 

**To Reproduce**
1. stopped process running in windows
2. deleted contents of Ombi directory except for Ombi.db & OmbiExternal.db & OmbiSettings.db
3. extracted and copied contents of 3.0.4892 zip into Ombi directory 
4. copied Ombi.db & OmbiExternal.db & OmbiSettings.db into folder
5. ran ombi.exe

**Expected behavior**
For the update to be successful and for me to be on the latest version 

**Logs (Logs directory where Ombi is located)**
[log-20200118.txt](https://github.com/tidusjar/Ombi/files/4080046/log-20200118.txt)

**Desktop (please complete the following information):**
Windows 10

**Ombi Version (please complete the following information):**
 - Version: 3.0.3988
 - Server: Plex

**Comment by tidusjar** [comment]
You are almost a thousand versions behind :cry:

I'd update every few version until you get to the latest.
