### ISSUE TITLE
Sign in getting very slow

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#3356]
**Describe the bug**
Within the last few builds / updates sign in is taking a very very long time.

**To Reproduce**
Sign in or return to ombi after being somewhere else.

**Expected behavior**
Sign in has never been very fast but one of my scripts that signs in with username and password stopped working once it started taking longer than 30 seconds.

**Screenshots**
Nothing to show

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [docker]

**Ombi Version (please complete the following information):**
- Version [3.0.4892]
- Media Server [e.g. Plex]

**Comment by tidusjar** [comment]
https://github.com/tidusjar/Ombi/wiki/Using-a-different-database
