### ISSUE TITLE
Custom Page is giving no options to edit

### ISSUE THREAD

**Issue by Jakimbo** [tidusjar/Ombi#3364]
**Describe the bug**

After enabling the custom page in the menu, the option appears, but the actual page is completely blank besides the menu. 

**Expected behavior**

Option somewhere to open the WISYWIG HTML editor

**Desktop (please complete the following information):**
-Ubuntu

**Ombi Version (please complete the following information):**
 - Version 3.0.4892 
- Media Server Plex

**Comment by Jakimbo** [comment]
Looks like this is an issue with chrome and firefox, I get the edit button when using edge

**Comment by tidusjar** [comment]
This is being reworked with V4 that is the next major release.
