### ISSUE TITLE
BUG:  Not staying set --> Allow us to collect anonymous analytical data e.g. browser used

### ISSUE THREAD

**Issue by fireheadman** [tidusjar/Ombi#3366]
**Describe the bug**
BUG:  Not staying set --> Allow us to collect anonymous analytical data e.g. browser used

**To Reproduce**
1. GOTO ombi settings, uncheck the Allow us to collect anonymous analytical data....etc
2. stop service
3. start service
4. check ombi settings again and it is Checked again

**Expected behavior**
Expecting it to stay unchecked

**Screenshots**
![image](https://user-images.githubusercontent.com/19847195/73117260-e652f380-3eff-11ea-9f85-ee59bcc3ad83.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
Ubuntu 18.0.x

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by fireheadman** [comment]
Believe all the info you need is present
I have read the wiki.  nothing there that helps

**Comment by fireheadman** [comment]
Have also powered off the VM and tried rebooting.
Also cleared browser cache  (Using firefox)

**Comment by tidusjar** [comment]
Update ombi to the latest develop version, This is not an issue there, you seem to be on quite a old version

**Comment by TheCatLady** [comment]
I'm on v4.0.956.0 and still seeing this issue.

I've verified that the setting is successfully written to the `OmbiSettings.db` upon submission of the form (`"CollectAnalyticData":false`).  However, when the Docker container is restarted or recreated, the setting is reset/overwritten (`"CollectAnalyticData":true`).
