### ISSUE TITLE
Plex User import dosent work

### ISSUE THREAD

**Issue by fastsui** [tidusjar/Ombi#3368]
**Describe the bug**
When i Import from Plex User manuel or the cron Job - Both why dosent work

**To Reproduce**
1. Go to User Importer
2. Run Importer

**Expected behavior**

**Screenshots**
User Importer: https://i.imgur.com/p5bjpEr.png
Error Screen on Console: https://i.imgur.com/U4zLpef.png

**Logs (Logs directory where Ombi is located)**
Error Console: https://i.imgur.com/U4zLpef.png
On Website i see non error

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version Newest
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
If you are getting unauthorized, then your Plex settings muct be incorrect

**Comment by fastsui** [comment]
Maybe - but how i can fix this ?


The movies are correct import from plex.. The newest movie are correct in ombi imported... Thats work..

**Comment by fastsui** [comment]
i have found the error - The Problem was that i have  relogin on the plex site in OMBI agaian and now its work.
