### ISSUE TITLE
Ombi V4 Custom CSS doesn't work

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tidusjar/Ombi#3372]
**Describe the bug**
Ombi V4 Custom CSS doesn't work. Nothing happens.

**To Reproduce**
1. Change Custom CSS to 
`.mat-drawer-inner-container {
    background-color: #B22222
}` Just a test color
2. Submit, refresh page and nothing changes.

**Expected behavior**
Change colors to custom css

**Desktop (please complete the following information):**
 Both Firefox and Chrome

**Ombi Version (please complete the following information):**
 - Version 4 latest pull. Ombi setting page shows 4.0.0.

**Additional context**
It's also very hard finding the right element to edit to change colors and text, since they all have the same name in inspect element.

**Comment by captains1stm8** [comment]
I know this has been marked closed, but it still appears to be an issue and is not listed in the bugs/todo section of the project

Is there a current workaround?

Thanks!

**Comment by Cookie-Monster-Coder** [comment]
> Is there a current workaround?

Edit _index.html_ in _/OmbiV4/ClientApp/dist/_ to include 
```<link rel="stylesheet" href="CustomCSS.css">```
right under 
```<link rel="stylesheet" href="styles.4d16b0dc8c12c7d965e8.css"><link rel="stylesheet" href="main.8ae492ffa0cbafb195ba.css">``` and before ```</head>```

then create another file called _CustomCSS.css_ in _/OmbiV4/ClientApp/dist/_

then add your css in there in the following format:

>  .mat-drawer-inner-container {
    background-color: #121212
}

**Comment by Cookie-Monster-Coder** [comment]
I guess I marked it as closed since I found a solution, but it really sound be closed

**Comment by captains1stm8** [comment]
Awesome!  I’ll give this a shot later tonight/tomorrow.

Thanks for the reply on this

**Comment by Floflobel** [comment]
Hello, it still doesn't work with the V4 is it possible to fix this issue?

**Comment by Cookie-Monster-Coder** [comment]
> Hello, it still doesn't work with the V4 is it possible to fix this issue?

Read the thread... 
https://github.com/tidusjar/Ombi/issues/3372#issuecomment-617329953

**Comment by DevilsDesigns** [comment]
> 
> 
> > Is there a current workaround?
> 
> Edit _index.html_ in _/OmbiV4/ClientApp/dist/_ to include
> `<link rel="stylesheet" href="CustomCSS.css">`
> right under
> `<link rel="stylesheet" href="styles.4d16b0dc8c12c7d965e8.css"><link rel="stylesheet" href="main.8ae492ffa0cbafb195ba.css">` and before `</head>`
> 
> then create another file called _CustomCSS.css_ in _/OmbiV4/ClientApp/dist/_
> 
> then add your css in there in the following format:
> 
> > .mat-drawer-inner-container {
> > background-color: #000000
> > }

is there a tutorial on where this hotifx would be in docker as i tried to acces the container in shell and i couldnt find the direcotry listed.

**Comment by DevilsDesigns** [comment]
nevermind figured it out
1. docker ps
2. run the commands below to ssh into your docker container (I used for ease of acccess you can also use bin/bash if you prefer)
```
docker run -d -p 2222:22 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e CONTAINER=ombi -e AUTH_MECHANISM=noAuth \
  jeroenpeeters/docker-ssh
```
3. install nano in container
`apt install nano`
4. Run the command below to run the ssh in container 
`ssh localhost -p 2222`
5. once ssh into container run this to get to the directory
`nano /opt/ombi/ClientApp/dist/index.html`
6. Edit , Save and follow the rest of the steps in the tutorial.

**Comment by hirenshah** [comment]
> > Hello, it still doesn't work with the V4 is it possible to fix this issue?
> 
> Read the thread...
> [#3372 (comment)](https://github.com/tidusjar/Ombi/issues/3372#issuecomment-617329953)

Is the Custom CSS option redundant then?

@DevilsDesigns suggestion for Docker installations doesn't persist when the image is updated right?

**Comment by tidusjar** [comment]
Custom CSS still works.

Check https://app.ombi.io/ you can see that I've used the Custom CSS option to change the Sign In button.
![image](https://user-images.githubusercontent.com/6642220/103635583-a7675380-4f40-11eb-9ec8-c4ff73d99121.png)

**Comment by hirenshah** [comment]
Sorry, just saw this reply.  I have no idea what was wrong initially but my Custom CSS works now.  Having the original within Docker is quite annoying though because the CSS overrides are proving to be quite messy.  I may run this separately instead so I can easily modify the core files.

**Comment by tidusjar** [comment]
> I may run this separately instead so I can easily modify the core files.

This will be overwrote after each update and not something I would recommend due to there are going to be some big page restructures coming up in the future.

**Comment by rheniumtorn** [comment]
I'm still having this issue running version 4.0.1340 from linuxserver/ombi:development on docker. I've tried these instructions as well but no luck. The "Custom Page" feature also doesn't seem to work at all. 

> nevermind figured it out
> How to Make A Custom CSS in Docker for Ombi
> 
> 1. run the commands below to ssh into your docker container (I used for ease of acccess you can also use bin/bash if you prefer)
> 
> ```
> docker run -d -p 2222:22 \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -e CONTAINER=ombi -e AUTH_MECHANISM=noAuth \
>   jeroenpeeters/docker-ssh
> ```
> 
> 1. Run the command below to run the ssh in container
>    `ssh localhost -p 2222`
> 2. install nano in container
>    `apt install nano`
> 3. once ssh into container run this to get to the directory
>    `nano /opt/ombi/ClientApp/dist/index.html`
> 4. Make the below edits to the file.
>    `<link rel="stylesheet" href="CustomCSS.css">`
> 
> right under
> 
> `<link rel="stylesheet" href="styles.4d16b0dc8c12c7d965e8.css"><link rel="stylesheet" href="main.8ae492ffa0cbafb195ba.css">`
> 
> and before
> 6. CTRL+ O and then CTRL+X
> 7. Now run this command
> `touch CustomCSS.css`
> 8. Now edit your new CSS
> `nano /opt/ombi/ClientApp/dist/CustomCSS.css`
> 9. Edit Your CSS to your liking
> 10. Success and Rejoice

**Comment by xxxtrashcion** [comment]
It kills me how this straight up just doesn't work and keeps getting marked as closed. Like what is the point on having the option in the customization section if you have to use a workaround for the feature?
