### ISSUE TITLE
User can't request all seasons after requesting first season

### ISSUE THREAD

**Issue by nelsonblaha** [tidusjar/Ombi#3375]
**Describe the bug**
User can't request all seasons of a show after requesting the first season

**To Reproduce**
1. Request the first season of a show
2. First season is gotten
3. Enjoy the show enough to request all seasons
4. No response

**Expected behavior**
Request is re-created as all-seasons or changed to all-seasons and sonarr looks for them

**Desktop (please complete the following information):**
 - OS: Ubuntu docker (linuxserver/ombi:latest)

**Ombi Version (please complete the following information):**
 - Version 3.0.4892

**Comment by tidusjar** [comment]
you shouldn't be able to request all seasons, as the first season will already be "requested" currently.

**Comment by nelsonblaha** [comment]
For some reason that wasn't the case, and anyway shouldn't a user be able to request the first season and then all seasons later?

**Comment by tidusjar** [comment]
Yeah I'm planning to make that change, but currently if you request ALL it will error stating that you have already requested the first season
