### ISSUE TITLE
TV Show description in another language than english?

### ISSUE THREAD

**Issue by thenamelessthing** [tidusjar/Ombi#3377]
**Describe the bug**
Hi, is there a way to change the language of the description for the suggestion? I set the ombi interface in french but the tv show description is still in english.

I have read all the wiki without find the solution..

Thanks you for your help.

**To Reproduce**
Set interface in french
look for the language description of the tv show suggestion 

**Expected behavior**
The tv show description must be in french

**Screenshots**
![image](https://user-images.githubusercontent.com/10235448/73771253-05e1eb80-474c-11ea-9954-fcb85525121a.png)

**Logs (Logs directory where Ombi is located)**
Where is located the log? I run under linux

**Desktop (please complete the following information):**
 - OS:  ubuntu 16.04.3

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex, radarr & sickrage

**Additional context**

**Comment by tidusjar** [comment]
Unfortunately not due to TV Maze not supporting other languages currently. If they add support for other languages then I will revisit this.
