### ISSUE TITLE
Multiple pages available for regular users

### ISSUE THREAD

**Issue by PoTskiii** [tidusjar/Ombi#3378]
**Describe the bug**
There are multiple pages available from a regular user that should not be available. Like issues is available for users and being able to add comments on issues for other users. Thats when the issues page is disabled as well.

**To Reproduce**
1. Disable issues
2. append /issues in the url when logged in as a regular user without any special rights

**Expected behavior**
There should be a user role to limit access to the issues page and other pages and maybe also hide created issues from other users so users cant see other peoples email address. A User should not be able to see the issues created from another users and they should defiantly not be able to post comments in other users issues.

**Desktop (please complete the following information):**
 - OS: Server 2019 Datacenter

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server 1.18.5.2309

**Comment by tidusjar** [comment]
This is more a feature request. 

Regarding appending the URL, if issues are disabled then it doesn't matter as there should be no issues. 

Please see the readme regarding feature requests
