### ISSUE TITLE
Movie search doesn't work (after fresh install)

### ISSUE THREAD

**Issue by thenamelessthing** [tidusjar/Ombi#3380]
**Describe the bug**
Section Movies in Search tab doesn't show any movies and don't return any results after trying to search. There is no such problem in TV Shows tab.

**To Reproduce**
Go to 'Search'
Click on 'Movies' (already at this point there is no proposed movies)
Enter any movie title and press Enter or click on looking glass icon
Nothing happens

**Expected behavior**
Movie propositions are displayed and search works.

**Screenshots**
Look the gif I recorded on this link to understand what happen:
https://nxworld.club/index.php/s/4DPSNZ5WNBscpDA/download

**Logs (Logs directory where Ombi is located)**
Which log do you need?

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.3

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**
-Fresh install

**Comment by tidusjar** [comment]
The magnifying glass is not actually a button, it should execute the search a few seconds after typing.
It should also load a load of suggestions when the page loads.

Please navigate to the search page and then provide the logs for the past minute.

**Comment by thenamelessthing** [comment]
Hi, I have found the solution by myself!

After I look the ombi logs I have see this error:

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.

As mentionned in this post:
https://github.com/tidusjar/Ombi/issues/3214

The solution is:

Navigate to the ombi directory (you should be able to see the file OmbiExternal.db)

Run: sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
