### ISSUE TITLE
Ombi V4 Apllication Name and Logo wouldn't change 

### ISSUE THREAD

**Issue by eltonzz** [tidusjar/Ombi#3383]
**Describe the bug**
Changing the Application name and logo doesn't reflect on any browser
![bug](https://user-images.githubusercontent.com/60944667/74278904-ef0d3d00-4ce7-11ea-9a41-2a98cded737e.JPG)

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Customization'
3. Scroll down to 'Application Name'

**Expected behavior**
Tried changing the name and logo, restarting the container and opening the page from a fresh/never used browser and computer and it still shows "Ombi" in address bar with the generic logo

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Linux Docker container

**Ombi Version (please complete the following information):**
 - Version 4.0.186.0
- Media Server Plex

**Comment by Ho2x** [comment]
Same problem as well as the custom page which is wrong.  I would like to use version 4 for testing and feedback but this bug prevents me from being able to install it over the long term.

 Thank you.

**Comment by tidusjar** [comment]
Custom page has not even been started yet. Yeah I'm aware this is an issue, but it's lower priority compared to some of the other things

**Comment by eltonzz** [comment]
I'm not looking to create a custom landing page I just need to change the logo and application name that's all.

**Comment by eltonzz** [comment]
> Custom page has not even been started yet. Yeah I'm aware this is an issue, but it's lower priority compared to some of the other things

Hi, are there any updates on this bug?
All what I'm looking for is the logo and application name; I'm not looking to create any custom page

**Comment by BodingClockchian** [comment]
Im having the same issue

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

Please keep in mind that V4 is still a work in progress.

**Comment by tidusjar** [comment]
This works fine now
