### ISSUE TITLE
Auth loop on Ombi v3.0.4892

### ISSUE THREAD

**Issue by TGM** [tidusjar/Ombi#3387]
**Describe the bug**
The GUI gets stuck on login with the message.

`Authenticating
Loading... Please Wait`

**To Reproduce**
Try to login on Ombi v3.0.4892

**Expected behavior**
Should be able to login.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
https://hastebin.com/xaqesupike.rb

**Desktop (please complete the following information):**
Firefox 72.0.2 (64-bit)

**Ombi Version (please complete the following information):**
- Ombi v3.0.4892
- OS Docker 19.03

**Additional context**
Let me know if you need anything else.

**Comment by tidusjar** [comment]
`Resource temporarily unavailable` looks like Plex.tv authentication API is having issues

**Comment by Aireezz** [comment]
I'm having this same issue, across multiple days

**Comment by mishac** [comment]
I'm having the same issue on 4.x

And the logs show:
`      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1002161870`

and so on...

**Comment by cyberden** [comment]
It's definitely not working for me. Is it just me or has plex changed something that broke Ombi for good?

**Comment by tidusjar** [comment]
Upgrade to v4
