### ISSUE TITLE
Ombi Behind Proxy

### ISSUE THREAD

**Issue by falahati** [tidusjar/Ombi#3389]
**Describe the bug**
Well, it is not actually a bug, but rather a feature request. Unfortunately as of now, Ombi does not work behind a proxy. This shows itself as part of the initial setup wizard with Plex and later on with any other outbound request.
This is the case even if `HTTP_PROXY` and/or `HTTPS_PROXY`  environment variables are present.
Considering the fact that OMBI is the only software that does not support proxies one way or another in the stack (Plex, Ombi, Radarr, Sonarr, Jackett, etc), and since adding it should be trivial, I believe it will be amazing to have this feature.

**To Reproduce**
1. Install behind a proxy
2. Select Plex as a media server and try to log in
3. See error 500 in console regarding a bad response or timeout of underlying requests

**Expected behavior**
Have proxy settings or at least respect the environment variables

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
 - Media Server Plex

Unfortunately, NetCore2.0 does not automatically respect environment variables I think. Therefore the fastest way to implement it is to read the environment variables and create an `IWebProxy` instance globally to be used with all outgoing requests. Or just move to NetCore 3. Otherwise, a page for network settings like in Sonarr and Radarr is sufficient. I think the only place responsible for all outgoing requests is the `Ombi.App.Request<T>()` method. Not sure it is also used for getting box arts and other images.

NetCore 3 API proposal:
https://github.com/dotnet/runtime/issues/29147

And the two PRs in response that can be used to implement the feature without moving to NetCore3:
https://github.com/dotnet/corefx/pull/37333
https://github.com/dotnet/corefx/pull/37200

**Comment by tidusjar** [comment]
Ombi does support being behind a proxy? 

See the wiki here: https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by falahati** [comment]
Hey @tidusjar,
No, I mean a being behind a forward proxy for access to the internet. Reverse proxies are in fact the exact opposite and used to forward traffic to the application. It is usually used in the corporate environment these days but sometimes used in other setups to control internet access or to increase security (as a firewall). Another good example of its usage is with TOR since it does in fact expose a SOCKS proxy to other programs and applications when TOR service is running.

But in my special case, it is due to the fact that all torrent websites and even Plex are blocked in my country so I have a VM with an always-on VPN connection and a proxy server to go around the national firewall.

The protocols are already included and implemented in NetCore and NetFramework (since NF1.1 I believe) but the auto-detect option is recently added to NetCore and since this project is still on NetCore2 we should explicitly provide proxy settings to be used for outgoing traffic.

**Comment by tidusjar** [comment]
Sorry for the misunderstanding!

So as part of V4, I've already got a branch with .net core 3.1 (feature/netcore3.1`), just finalizing some parts of that now, so rather than me setting something up, let's just use the `HTTP_PROXY` env var when you upgrade to V4

**Comment by falahati** [comment]
Good to know. thanks

**Comment by tidusjar** [comment]
v4 is now running .net core 3.1
