### ISSUE TITLE
RocketChat notifications

### ISSUE THREAD

**Issue by Floflobel** [tidusjar/Ombi#3396]
**Describe the bug**
I'd like to remove my Slack notifications to migrate to RocketChat. The problem is that the Slack notification doesn't allow me to put the URL of my webhook it always replaces it by adding the slack url first:
https://hooks.slack.com/https://rocketchat.domain/hooks/Z5uHaYusu6HkFebg6/XXXXXXXXXXXX/XXXXXXXXXXXXX

Is it possible to change this so that Ombi can support RocketChat? 
I don't know if I should send my request in the feature request or leave it in bug? 

**To Reproduce**
1. Go to 'notification' > Slack
2. Set-up the URL webhook of RocketChat server
4. See that the URL has been replaced

**Expected behavior**
Not replace the webhook URL by Slack

**Ombi Version (please complete the following information):**
 - Version 3.0.4680

**Additional context**
I understand that Slack's Webhook works exactly the same as RocketChat, so there shouldn't be any code changes to make. But I can't verify that.

**Comment by tidusjar** [comment]
This is more of a feature request! Checkout feathub (link on the readme). Thanks
