### ISSUE TITLE
v4 - Sending Multiple Available Notifications

### ISSUE THREAD

**Issue by johntrask** [tidusjar/Ombi#3398]
**Describe the bug**
Ombi is sending 2 emails once a show has been added to Plex and Ombi confirm it is there. 

**To Reproduce**
1. Have a user request a movie
2. Approve It
3. Wait for it to download and be scanned by Ombi
4. When the email is sent to the user that it is available, there will be 2 sent to the user.

**Expected behavior**
Ombi should only send 1 email.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Not seeing anything in the log in reference to emails. Either way, logs added.

**Desktop (please complete the following information):**
 - OS: Ombi is running on Server 2016

**Ombi Version (please complete the following information):**
 - Version: 4.0.191.0
- Media Server Plex - 1.18.6.2368 
[log-20200217.txt](https://github.com/tidusjar/Ombi/files/4214350/log-20200217.txt)
![2020-02-17 10_48_15-Sent Mail - johntrask@gmail com - Gmail](https://user-images.githubusercontent.com/31781818/74664148-8ef91980-5173-11ea-8cc6-03bef546fa85.png)

**Additional context**

**Comment by johntrask** [comment]
Edit, it is also happening for Pushover as well. Seems to be doing it for all notification types, or at least the 2 I use.

**Comment by tidusjar** [comment]
Thanks I can see the issue, it's the regular plex sync and the recently added sync happen to run at the same time on your system, then they both pick up that there is a new item and both jobs send out the notificaiton.

**Comment by tidusjar** [comment]
This has been fixed in the v4 branch! 🎉 🎈

**Comment by johntrask** [comment]
Nice, thanks man.
