### ISSUE TITLE
Cannot send Welcome or Password reset emails.

### ISSUE THREAD

**Issue by JimboJamez** [tidusjar/Ombi#3401]
**Describe the bug**
Trying to set up email notifications in OMBI. Test emails are being sent and received but when I click on 'Send Reset Password Link' or 'Send Welcome Email' the error below is returned.

I have checked the spam folder and nothing is in there either...

**To Reproduce**
1. Go to 'User Management'
2. Click on 'Send Welcome Email'
3. An email should be sent and received
4. Check email inbox and nothing is there
5. See error

**Expected behavior**
Welcome or password reset email should be sent.

**Logs (Logs directory where Ombi is located)**

> 2020-02-20 20:34:53.840 +11:00 [Error] Exception when attempting to send an email
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_DnsSafeHost()
>    at System.Uri.get_IdnHost()
>    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
> 2020-02-20 20:34:53.848 +11:00 [Error] Something bad happened, ErrorMiddleware caught this
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_DnsSafeHost()
>    at System.Uri.get_IdnHost()
>    at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
>    at Ombi.Controllers.IdentityController.SubmitResetPassword(SubmitPasswordReset email) in C:\projects\requestplex\src\Ombi\Controllers\IdentityController.cs:line 784
>    at lambda_method(Closure , Object )
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
>    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
>    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version: 3.0.4892
- Media Server: Plex

**Comment by tidusjar** [comment]
Whats your Application URL in your Customisation Settings?

**Comment by JimboJamez** [comment]
Hi @tidusjar 

Sorry about the late reply, a lot is going on at the moment!

I don't currently have an Application URL set, is this something that I need to do? If so, what information should I enter here?

![image](https://user-images.githubusercontent.com/25968238/76915203-a4976580-6910-11ea-96a1-b1bb80aa0efc.png)

**Comment by tidusjar** [comment]
The application url needs to be the externally accessible url for your ombi.
