### ISSUE TITLE
Unable to request episodes from incomplete first tv season through browser

### ISSUE THREAD

**Issue by barfnuts** [tidusjar/Ombi#3403]
**Describe the bug**
I'm experiencing a weird issue with a TV show that is halfway through its first season. 5/10 episodes have been broadcast so far, and I currently have the first 4 in Plex. 

If i use a browser interface (mobile or desktop), after I search for the show, there is no option to request the missing shows. All it shows is that it is "Available". 

However, if I use the iOS app interface, I can browse to the show, view the episode list, and request the missing shows like normal. 

So, if a user isn't using the Ombi app, they're currently unable to request that particular show. 

**To Reproduce**
1. Go to any web browser
2. Log into Ombi 
3. Search for a show in its first season, which is incomplete in Plex (only a few episodes downloaded)
4. Request button not visible, shows only that it is "available"

**Expected behavior**
I would expect that the browser interface should have the same functionality as the iOS app in terms of requesting missing episodes

**Screenshots**
Browser screenshot:
![748431A7-DA0D-41D2-85DB-A22DCE50E914](https://user-images.githubusercontent.com/40758359/75006637-449fc300-5427-11ea-9845-2c842eed1fea.png)

iOS app screenshot:
![AB1B3C27-7982-4E2B-8287-9BE848A061F7](https://user-images.githubusercontent.com/40758359/75006657-55e8cf80-5427-11ea-9d5d-36c5cb2d9f16.png)

**Logs (Logs directory where Ombi is located)**
Nothing out of place in the log files. 

**Desktop (please complete the following information):**
 - OS: windows 10 64-bit, google chrome 

**Ombi Version (please complete the following information):**
 - Version - 3.0.4892
- Media Server - Plex

**Additional context**
None, everything else works like it should. Great program!

**Comment by tidusjar** [comment]
The browser is the expected behaviour, your show is available since there are no unaired episodes, this shows better on the v4 interface and still allows you to request.
