### ISSUE TITLE
Stuck in the wizard after a successful install

### ISSUE THREAD

**Issue by duindain** [tidusjar/Ombi#3412]
**Describe the bug**
I've installed this 3 days ago with no issues on linux mint 19.3 not using docker 
Today I've f5 refreshed as it was showing a episode that i already have as request option and it triggered the wizard
It now prompts me for a fresh install every time i hit the site, restarting the service did not help
I've tried going through the wizard by skipping plex or attempting to sign in with it
The signing in works then nothing happens after closing the extra window
If i skip and try registering it says there is already an admin account existing with the same details and it stays on the same screen in the wizard

**To Reproduce**
1. Install
2. Run through wizard, configure everything
3. ...
4. Refresh and stuck in wizard hell

**Expected behavior**
I should be able to cancel the wizard or login, it shouldn't trigger the wizard when there is an issue,
Instructions on clearing the install and starting again if needed?

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
I've checked the logs in /opt/ombi and there is no details about starting the wizard there is an error with Plex but it isnt during the login process

**Desktop (please complete the following information):**
Linux mint 19.3

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex
Radarr
Sonarr
Lidarr

**Additional context**

**Comment by tidusjar** [comment]
Very strange, I'd suggest deleting the Ombi.db and OmbiSettings.db, restarting ombi and then again?

**Comment by duindain** [comment]
Thanks I've deleted, restarted the service and run through the wizard again and got it running, fingers crossed it keeps working :)

Thanks for the help :+1:
