### ISSUE TITLE
Can't choose profile with Radarr

### ISSUE THREAD

**Issue by almottier** [tidusjar/Ombi#3415]
**Describe the bug**
I can't choose a profile with Radarr when I add a new request

**To Reproduce**
1. Select a movie
2. Profiles are not displayed

**Expected behavior**
Show different Radarr profiles as working with Sonarr

**Screenshots**
...

**Logs (Logs directory where Ombi is located)**
No error logs

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
This is included in v4
