### ISSUE TITLE
"Looks like there's an existing user!" cannot get passed Ombi setup

### ISSUE THREAD

**Issue by amatrosovasGM** [tidusjar/Ombi#3416]
**Describe the bug**
After ubutu update I can no longer link ombi to plex nor just skip that step and create a user. in both cases I keep getting "Looks like there's an existing user!"

**To Reproduce**
1. try to link plex to Ombi
2. see an error popping up saying "Looks like there's an existing user!"

**Expected behavior**
Ombi should link to plex/login with plex or in another case create an ombi user

**Screenshots**
![CleanShot 2020-03-06 at 00 17 46@2x](https://user-images.githubusercontent.com/54270554/76031218-f539b680-5f3f-11ea-873c-a1d3dd3be0bb.jpg)

**Logs (Logs directory where Ombi is located)**
Not sure where to find them as I don't see anything relevant in /opt/Ombi

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Ombi Version (please complete the following information):**
 - Version 3.0.5020
- Media Server Plex

**Additional context**
I have tried running sudo apt remove ombi and then install it again but the issue persists

**Comment by amatrosovasGM** [comment]
just deleted the database at /etc/Ombi and started from scratch

**Comment by tidusjar** [comment]
Delete the .db files and restart ombi
