### ISSUE TITLE
OmbiV4 doesn't display properly with Organizr SSO subdomain becasue of /discover in the URL

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tidusjar/Ombi#3417]
**Describe the bug**
Since OmbiV4 now uses /discover at the end of the url and Organizr SSO subdomain requires /auth/cookie/ in the tab URL, it signs in perfectly but the display is all messed up.

**To Reproduce**
1. Set up SSO in Organizr with Ombi4
2. Login and go to Ombi tab

**Expected behavior**
Sign in and display properly

**Screenshots**
[Screenshot](https://i.imgur.com/405dFSr.png)

**Desktop (please complete the following information):**
 - OS: Firefox/Chrome

**Ombi Version (please complete the following information):**
 - Version 4.0.234.0

**Comment by tidusjar** [comment]
Assuming it all works fine on a refresh then?

**Comment by Cookie-Monster-Coder** [comment]
> Assuming it all works fine on a refresh then?

No, it still has the same issue.
[According to this doc](https://docs.organizr.app/books/setup-features/page/sso) the URL you would put in the Organizr tab would be https://ombi.domain.com/auth/cookie but Ombi 4 wants https://ombi.domain.com/discover for it to display right. I tried using a redirect like https://ombi.domain.com/auth/cookie/?redirect_uri=/discover/ it logins in successfully but still displays weirdly.

I was testing something totally different and decided to use a subdomain and found this issue. I normally use a reverse proxy and use https://domain.com/ombi. I just thought I'll post it here increase someone is using a subdomain in their setup.

**Comment by tidusjar** [comment]
This is fixed now
