### ISSUE TITLE
Ombi not notifying when item available if requested via API

### ISSUE THREAD

**Issue by Anon0ne** [tidusjar/Ombi#3422]
**Describe the bug**
Using a Discord based chat not which requests movies and TV via ombi API key. Works fine, but when the file is done downloading Ombi doesn't notify the chat like it would normally.

**To Reproduce**
Request a movie or show via API, and notifications don't work.

**Expected behavior**
A notification should be sent regardless of how the item is requested

**Comment by tidusjar** [comment]
Ombi doesn't have a concept of downloading or knowing the progress of the download

**Comment by tidusjar** [comment]
Also the API account is currently like an admin account, so notifications do not work for admins. This will be changing in the future with a more granular permissions system
