### ISSUE TITLE
New Requests fail

### ISSUE THREAD

**Issue by LiQiuDGG** [tidusjar/Ombi#3430]
**Describe the bug**
Hello, in the last day or so, any new Ombi requests fail, and the pasted information below is in the log. It looks like it's failing on the API call to themoviedb, however when trying that call manually it works, so I'm not sure what the issue is to be honest. I get the same behavior whether it is TV or a movie.

**To Reproduce**
    Go to TV Shows
    Click request on any show
    nothing happens

    Go to Movies
    Click request on any movie
    nothing happens

**Expected behavior**
Movie or TV Show should be requested.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
[log_snippet.txt](https://github.com/tidusjar/Ombi/files/4340598/log_snippet.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10, Mac, Android
 - Browser: Firefox, Chrome, IE, Edge, Safari

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
Hi. 

Your logs show me you are getting a Forbidden response back from the movie dB API. 

What happens when you navigate to the following?
http://api.themoviedb.org/3/discover/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en&sort_by=popularity.desc&include_adult=false

**Comment by LiQiuDGG** [comment]
I agree, but when i try the api.themoviedb.org link myself it works fine and gives me the json data.  I get the same when trying the api link you have there.  

However that lead me down a path to check out the API call using curl from the machine itself.  I can see that it's opendns blocking it, so I just told it to never block that domain, and everything looks fine.  

Sorry for the issue, but thank you for putting me on the right path.
