### ISSUE TITLE
API Search shows a movie as not being available, in GUI search shows it as available

### ISSUE THREAD

**Issue by MarcusSattler** [tidusjar/Ombi#3433]
**Describe the bug**
Using the API call http://ombi:3579/api/v1/Search/movie/ to search for a movie shows it is not available:

"id": 330457,
    "approved": false,
    "requested": false,
    "requestId": 0,
    "available": false,

When i search for the same movie within the GUI, it shows as being available, with a link to Plex.

**Expected behavior**
The API should show the movie as available, if it's found in the GUI

**Desktop:**
 - OS: Linux Docker

**Ombi Version:**
 - Version 3.0.4892
- Media Server Plex

**Comment by tidusjar** [comment]
Check the network tab when browsing via the website. It will show you what's going on, we do an extra call to get additional information. This way we can keep the search fast.

**Comment by MarcusSattler** [comment]
That's the thing, I can see the API results in swagger:

Swagger Results:

{
    "adult": false,
    "backdropPath": "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
    "genreIds": [],
    "originalLanguage": "en",
    "originalTitle": "Frozen II",
    "overview": "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
    "popularity": 163.38099670410156,
    "posterPath": "/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
    "releaseDate": "2019-11-20T00:00:00",
    "title": "Frozen II",
    "video": false,
    "voteAverage": 7.099999904632568,
    "voteCount": 2940,
    "alreadyInCp": false,
    "trailer": null,
    "homepage": null,
    "rootPathOverride": 0,
    "qualityOverride": 0,
    "type": 1,
    "releaseDates": null,
    "digitalReleaseDate": null,
    "id": 330457,
    "approved": false,
    "requested": false,
    "requestId": 0,
    "available": false,
    "plexUrl": null,
    "embyUrl": null,
    "quality": null,
    "imdbId": null,
    "theTvDbId": null,
    "theMovieDbId": "330457",
    "subscribed": false,
    "showSubscribe": true
  },



Now the same movie pulled out of the Ombi db:

923	Frozen II	2019	tt4520988			0	https://app.plex.tv/web/app#!/server/************/details?key=library%2Fmetadata%2F342901	342901	2020-03-18 13:36:29.9634723	sd

So why would the API show it as being unavailable when the record is in the Ombi db?

**Comment by MarcusSattler** [comment]
I noticed that some of the movies giving me issue are utilizing the Plex Movie Agent, not themoviedb agent.  Going to fix that and see if that fixes the issue.   

If the PlexMovieAgent doesn't fill in the moviedb id number, then it wouldn't match. But I'm not sure why in the GUI it would still see it?  A different query?

**Comment by tidusjar** [comment]
Look at the network tab in the development tools when you search for a movie via the UI. That will tell you what requests are happening and what is going on.
