### ISSUE TITLE
Ombi failing to request certian shows through sonarr

### ISSUE THREAD

**Issue by Mavranel** [tidusjar/Ombi#3438]
**Describe the bug**
Ombi is failing to request TV Shows. Specificially anime. I have no problem with american television shows. I have attempted requesting multiple Television shows and the problem seems to be consistent. It does not appear to matter whether the show is airing or not it's only occuring with anime.

**To Reproduce**
Request TV Show Darwin's Game is one such suffering from this issue.
Wait
See something wrong has happened
Check failed request
See Darwin's Game

**Expected behavior**
Expected to not get a failed request

**Screenshots**
https://i.imgur.com/H7hxzBj.png

**Logs (Logs directory where Ombi is located)**
I was unable to find the logs directory or any file named logs in my Ombi Directory

**Desktop (please complete the following information):**
Ubuntu 18.0.4 headless

**Ombi Version (please complete the following information):**

    Version 3.0.4892
    Media Server Plex

**Additional context**
Remove and request series again
Restart
Reinstall
Java Update (noticed when hovering over the error it was about a JSON file. Figured it wouldn't hurt)

Please let me know if you need any more information to help fix this issue. I will happily provide it if I am able.

**Comment by Mavranel** [comment]
Well I set a cron job to retry them once every hour before I went to bed and now two of them managed to get the request through. I still have four series in the failed request list however.

**Comment by smailpouri** [comment]
I had an issue request being stuck in "Processing request" after trying everything (upgraded from v3 to v4 too) I could think off, I realize one setting I changed in Radarr and Sonarr.
"URL Base" was set to /Radarr and /Sonarr because I was trying to set a reverse proxy and never finished setting it up. After deleting the "URL Base" and restarting both Radarr and Sonarr all is back to normal.

**Comment by Mavranel** [comment]
I never entered a URL Base for either Sonarr or Radarr. I just checked to make sure both fields are empty in case I forgot about something and they are. So that is not the issue at present.

**Comment by Mavranel** [comment]
I would also like to reiterate that this problem is not universal. The sonarr connection does work and most TV shows I attempt to request are in fact processed. It is just certain shows that happen to all be anime that are not processed. Some anime shows are processed however the majority seem to be failing to process.

**Comment by ErroneousBosch** [comment]
I have also seen this, especially on some Anime. In my case it is a series that SOnarr itself cannot find with "Add Series" so I wonder if it is related?

**Comment by Mavranel** [comment]
Unrelated as I eventually gave up and just added the affected series directly via Sonarr and had no problems doing so. The issue in my case is with Ombi.
