### ISSUE TITLE
Newsletter Only Listing Latest TV Shows, Not Movies

### ISSUE THREAD

**Issue by fernandoaleman** [tidusjar/Ombi#3446]
**Describe the bug**
When a test newsletter, "trigger now" newsletter or cron newsletter is sent, no "New Movies" content is sent, only "New TV".

**To Reproduce**
1. Go to Settings and Notifications
2. Click on Newsletter
3. Scroll down to either "Test" or "Trigger Now" button and click.
4. Review newsletter that is email to you.

**Expected behavior**
Expect to see both "New Movies" content and "New TV" content in the newsletter.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Running on Unraid via linux docker container

**Ombi Version (please complete the following information):**
 - Version: 4.0.2
- Media Server: Plex

**Additional context**
I am testing this with new content added to Plex in both Movies and TV Shows, but only TV Show content is sent in the newsletter.

**Comment by jgruber96** [comment]
I also have the same issue.  Newsletter trigger, either by testing or the daily email, only includes new TV.

**Comment by Mark7even** [comment]
Same issue here. I am running the Linux Server version of the unRAID docker.

**Comment by tidusjar** [comment]
use the development tag docker, this has been fixed in develop

**Comment by Mark7even** [comment]
@tidusjar can you explain how to use the development tag docker for unRAID?

**Comment by jgruber96** [comment]
> @tidusjar can you explain how to use the development tag docker for unRAID?

Should be able to do something like tidusjar/ombi:develop

**Comment by Mark7even** [comment]
@jgruber96 where do you put that though?

**Comment by tidusjar** [comment]
It's the development tag for the Linux server container

**Comment by Mark7even** [comment]
@tidusjar I don't really understand what that means? I understand I am on the stable version, but unsure where to change that or enter a different tag.

**Comment by tidusjar** [comment]
https://hub.docker.com/layers/linuxserver/ombi/development/images/sha256-86fe0c1767738208f862c8ab5e12625d046ad59076e322e1cead5ccfe483ea14?context=explore

**Comment by Mark7even** [comment]
Got it,

Just needed to put "linuxserver/ombi:development" in the repository section of unRAID.

**Comment by Mark7even** [comment]
@tidusjar same issue at least with "Test" newsletter on the development branch. No movies showing.

**Comment by tidusjar** [comment]
The test is not a good example to use, since the test just grabs the first 10 items that Ombi found every time, which could happen to be TV Shows.

**Comment by Mark7even** [comment]
@tidusjar okay did a trigger now. Same issue, only TV showing, no movies. I added new movies today and yesterday.

**Comment by tidusjar** [comment]
Are they appearing as available inside ombi?

**Comment by Mark7even** [comment]
Yes they are.

**Comment by tidusjar** [comment]
Can you please check the PlexServerContent table in the OmbiExternal.db to see if the movie in question is there?

**Comment by Mark7even** [comment]
The Movies in question are in the DB

[](https://imgur.com/a/IFkmxwF)

**Comment by tidusjar** [comment]
Ok cool, can you now query the RecentlyAddedLog table where the `ContentId` = the value for the `TheMovieDbid` column for the movie?

**Comment by Mark7even** [comment]
@tidusjar I am not entirely sure what you mean. I do not see a RecentlyAddedLog table, and almost all of my movies are populated by ImdbID and NOT TheMovieDBId.

**Comment by tidusjar** [comment]
Ok, then search on the ImdbId in the ContentId field

**Comment by Mark7even** [comment]
I am sorry, I don't understand what you mean by search in the ContentId
field.

Best,
Jon

**Comment by tidusjar** [comment]
Query the RecentlyAddedLog table where the contentid = ImdbId of the movie in question

**Comment by Mark7even** [comment]
I am very new to any sort of database navigation or querying, but I do not see the RecentlyAddedLog table. Maybe thats my issue?

https://imgur.com/Ad9BEZ0

**Comment by andcbii** [comment]
I'm having an issue were movies aren't added to the newsletter. It doesn't even list the movie header. I've only had this issue since i upgraded to the newest version. When I test the news letter, the header and 1 movie does show.

**Comment by andcbii** [comment]
FYI when i look at the RecentlyAddedLog, I don't see IMDB IDs, they are themoviedb.org IDs and nothing has been added with a contentType of 0 since i upgraded to the last version on 4/17. It looks like movies aren't being added to the log. They are showing up on Ombi as in my library.

**Comment by roylee77** [comment]
As per above. I have the same problem on v3.0.4892 running on Windows 10 with Plex. 

Recently added TV Shows appear on the newsletter, however nothing for movies, even those that were added within the last few hours / 1 day etc. 

The log shows:
2020-05-11 10:24:37.927 +01:00 [Information] Plex Movies to send: 0
2020-05-11 10:24:37.929 +01:00 [Information] Emby Movies to send: 0
2020-05-11 10:24:37.929 +01:00 [Information] Albums to send: 0
2020-05-11 10:24:40.942 +01:00 [Information] Plex Episodes to send: 2003

**Comment by dawidajm** [comment]
I added movies and TV shows today. They show as available in OMBI but does not look like they are in the RecentlyAddedLog. The TV show did show up in my newsletter when manually running "Trigger Now" but the movies did not. I am running v3.0.4892.

https://i.imgur.com/fai5C2q.png - RecentlyAddedLog Table
https://i.imgur.com/kCSsHd3.png - Request Page TV Show
https://i.imgur.com/lKCNx8h.jpg - Request Page Movie
https://i.imgur.com/QWihrUL.png - Newsletter

**Comment by andcbii** [comment]
@tidusjar any help with this? I hope you don't mind me "at"ing you.

**Comment by andcbii** [comment]
bump?

**Comment by tidusjar** [comment]
Sorry guys, please follow #3421
