### ISSUE TITLE
Auto Updater for 4.0 Not working..

### ISSUE THREAD

**Issue by ne0ark** [tidusjar/Ombi#3450]
**Describe the bug**
Version 4.0 is not able to auto update.

**To Reproduce**
1. Go to 'Settings -> System
2. Click on 'Check for Update'

**Expected behavior**
Update to current 4.0 branch release.

**Ombi Version (please complete the following information):**
 - Version 4.0.280.0

**Comment by tidusjar** [comment]
v3 also didn't auto update. It needs to be reworked.
