### ISSUE TITLE
User Roles Missing

### ISSUE THREAD

**Issue by ronso21** [tidusjar/Ombi#3454]
**Describe the bug**
Cannot assign roles under users. Either new users or imported Plex users.
Roles section is blank with no roles available to select.

**To Reproduce**
1. Go to 'User Management'
2. Click on 'Details/Edit'
3. Click on 'Roles'
4. No roles are listed

**Expected behavior**
A table of available roles for users

**Screenshots**
![image](https://user-images.githubusercontent.com/48181235/77852737-ded0f480-71a5-11ea-8ee3-281dd311d7ca.png)
![image](https://user-images.githubusercontent.com/48181235/77852741-e55f6c00-71a5-11ea-962a-f528342512e2.png)

**Logs (Logs directory where Ombi is located)**
C:\Ombi\Logs
[log-20200329.txt](https://github.com/tidusjar/Ombi/files/4399128/log-20200329.txt)

**Desktop (please complete the following information):**
 - Win10 Pro v 1909

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
![image](https://user-images.githubusercontent.com/48181235/77852877-8fd78f00-71a6-11ea-833e-f1ffe4ca5053.png)

- Media Server
Plex v1.18.9.2571

**Additional context**
Users cannot request movies or TV shows as they do not have permissions to request.

Happened after upgrade then also after fresh install.

**Comment by tidusjar** [comment]
Update your ombi version, you are really behind.

**Comment by ronso21** [comment]
The app says it is up to date and it is the latest available version in the
develop tree.

**Comment by tidusjar** [comment]
Do not use the inbuilt updater.

**Comment by ronso21** [comment]
So what is the latest version I should be using?

**Comment by tidusjar** [comment]
It's mentioned in the comment above

**Comment by ronso21** [comment]
I am running version 3.0.5105
