### ISSUE TITLE
Cant not remove Emby server?

### ISSUE THREAD

**Issue by casperse** [tidusjar/Ombi#3458]
I want to remove the Emby server but no matter what I do it keeps the connection?

Expected behavior
Emby server reference and cash data would be removed
Only Plex left....

Screenshots
Its just not able to remove it "missing a "Done" or Submit button?

Ombi Version (please complete the following information):
Docker Linuxserver
Version | 3.0.4892
Branch | master

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by goldenpipes** [comment]
Sounds like a corrupt database, you can edit the ombi.db with sqlitebrowser (make a backup first) and remove the tables that correspond with Emby server.  OmbiExternal.db can be deleted and will remove the Emby Library cache from ombi.
