### ISSUE TITLE
User role missing from user Management

### ISSUE THREAD

**Issue by ronso21** [tidusjar/Ombi#3461]
**Describe the bug**
User roles missing from User Management screen

**To Reproduce**
When adding or editing users on User Management screen the role step is blank.

**Expected behavior**
A list of roles available

**Screenshots**
![image](https://user-images.githubusercontent.com/48181235/78154029-5f3f6180-7401-11ea-9cce-98832843d41c.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

[log-20200401.txt](https://github.com/tidusjar/Ombi/files/4416097/log-20200401.txt)

**Desktop (please complete the following information):**
 - OS: Win 10

**Ombi Version (please complete the following information):**
 - Version 4.0.2850
- Media Server Plex

**Additional context**
Fresh install of Ombi to new location on server.

**Comment by tidusjar** [comment]
This is still WIP and not really finished yet
