### ISSUE TITLE
Unable to search or request TV shows with invalid air dates or years

### ISSUE THREAD

**Issue by bagobones** [tidusjar/Ombi#3462]
**Describe the bug**

TV shows that do not have a valid year / release date can't be requested / do not display in search. It makes it impossible to request some future releases.

**To Reproduce**
Search for "lower decks" under TV it will show a single result for a second and then show no results.

**Expected behavior**
Release date / year should not be important for making a request.

**Desktop (please complete the following information):**
 - OS: docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
It's going to be related to this: https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all

**Comment by bagobones** [comment]
http://api.tvmaze.com/search/shows?q=lower%20decks

"externals":{"tvrage":null,"thetvdb":367138,"imdb":"tt9184820"}"

It has a thetvdb and imdb does it require All three? Other specifics needed to not fail?
