### ISSUE TITLE
Email notification no longer working ?

### ISSUE THREAD

**Issue by ochbob** [tidusjar/Ombi#3465]
**Describe the bug**

Email notification no longer working

**To Reproduce**
1. Go to 'Email Notifications'
2. Click on 'Test'
3. Ombi says, "successfully sent email", but nothing in my inbox / spambox
I don't have change my settings, working great before (last stable), so I update to the last develop to see if it happen again, but no chance.
All my other stuff working great with my smtp settings / credentials.
I use my ISP's SMTP (Orange) / 465 / SMTP auth

**Ombi Version (please complete the following information):**
 - Version: develop 3.0.5105  (Debian 10)
- Media Server: Plex

Any idea ? Did I miss something ?

**Comment by tidusjar** [comment]
check your logs.

**Comment by ochbob** [comment]
Already did:

https://pastebin.com/vgVuDWS6
(sorry, debug mode, lot of logs)

But seems OK, at least no error message (like GUI from Ombi said "successfully sent email")

**Comment by tidusjar** [comment]
No issues being reported, so the emails are leaving Ombi. Check the junk/spam folder of the recipient. Also check the sent folder of the email address you are sending the emails from

**Comment by ochbob** [comment]
No chance :(

**Comment by mhbates** [comment]
Same issue here. Looks like it has to do with either MailKit (what Ombi uses for notifications) or our email providers. Ombi is throwing the following error for me:

`2020-04-02 06:33:25.680 -07:00 [Warning] Exception when testing Email Notifications
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.
`

Once I check the "Disable Certificate Checking" option in Ombi, emails start to work again.

**Comment by hergonoway** [comment]
Just got this issue today also, thanks for the tip

**Comment by ochbob** [comment]
It's not Ombi, it works great with another smtp, but I can't figure out why Tautulli, for example, works great with my SMTP settings...
And why it was working great 2 weeks ago...
