### ISSUE TITLE
OMBI V4 Newsletter has each movie twice

### ISSUE THREAD

**Issue by rmeaux** [tidusjar/Ombi#3467]
**Describe the bug**
Stayed on V3:latest and not :development so my Movies haven't been on my newsletter for a few months. My newsletter went out this morning via V4 and now includes New Movie and New TV. Great, thanks!

The newsletter included every movie that I had not sent out yet with each one doubled. Including all the movies never sent out under the V3 newsletter. There were two Titles and posters for each Movie entry.

TV Shows were normal. One Title and Poster and episodes that were added.
Only running one media server.
When running the "Test" it sends 10 single entries of each movies and TV shows as normal.

**To Reproduce**
Auto-Newsletter sent on Fridays

**Expected behavior**
One Title and Poster for each Movie. 

**Screenshots**
https://imgur.com/a/xufhcZf

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - OS: unRaid 6.8.3

**Ombi Version (please complete the following information):**
 - Version 4.0.287.0
 - Media Server Plex
 - All Dockers are LSIO (radarr, sonarr, lidarr, ombi, plex)

**Additional context**
Loving V4 by the way.
Thanks

**Comment by rmeaux** [comment]
I performed an "Update Database" I can report back next Friday what happens.

**Comment by jwor80** [comment]
FYI, I'm seeing the same issue.

**Comment by tidusjar** [comment]
I would be interested in seeing what happens on the 2nd run

**Comment by jwor80** [comment]
My issue is occurring with every daily scheduled newsletter.  Every movie has been duplicated all week long.

**Comment by rmeaux** [comment]
Friday auto newsletter went out and movies were still duplicated. Tv shows went out as normal. 

Also Radarr downloaded a movie at 720 and then replaced it with a 1080 a little later. That movie showed up 4 times. 

Let me know if you need anymore info.

**Comment by iammortimer** [comment]
Same issue for me.

**Comment by vw-kombi** [comment]
Me too.  Plus same issue as V3 that TV shows are read from any library in Emby - need library control for the emby server - I dont want all libraries being included in the newsletter updates.

**Comment by DillonsFlix** [comment]
I have been having the same issue for a while now.

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

**Comment by rmeaux** [comment]
OP for this big report. No rush. Keep up the great work. Family comes first. Love OMBI even though.

**Comment by DillonsFlix** [comment]
> Hi sorry but there has been no further progress on this yet.
> 
> Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy.
> All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.
> 
> Ombi is currently a 1 person development team.
> 
> So if I have not yet got around to this you now know why 😄

Your hard work is much appreciated.  Certainly not trying to rush you.  

If it helps I have noticed that when I have both Moves and TV Shows enabled on the newsletter only the TV Shows are included.  If I only have Movies enabled I get the duplicate issue.

**Comment by douglasparker** [comment]
This is still an issue.

**Comment by rmeaux** [comment]
Yes it is. I meant to come on here and revive it when I got the email stating it was stale and to be closed.￼ But I forgot to.￼

**Comment by rmeaux** [comment]
Just and update. I got single movies today for the first time. But no new TV Shows were included.

**Comment by jiznon** [comment]
Also experiencing this issue. v4.0.483.0

**Comment by Rickth64** [comment]
Can’t we reopen? I have this issue on 4.0.550.0

**Comment by rmeaux** [comment]
I'm not that much of a GitHub guru but I don't see any options for me as issue OP to revive/open it other than to comment.

**Comment by rmeaux** [comment]
Someone made a new ticket. #3785
