### ISSUE TITLE
Ombi to slow to notice requested content

### ISSUE THREAD

**Issue by evlo** [tidusjar/Ombi#3468]
Hi,

how can I make Ombi to notice content is available? I can see the movie in plex, but ombie takes hours to notice it.

**Comment by goldenpipes** [comment]
Chances are your Ombi -> PLEX connection has failed.

1. Create a local ombi admin user if you do not have one already.
2. Sign out and in again with the new admin user. (skip if already signed in with local admin)
3. Remove Plex Media Server from ombi.
4. In your Plex Settings go to Authorized Devices, and remove all entries related to Ombi.
5. Stop Ombi, delete OmbiExternal.db
6. Start Ombi, Add Plex and run a Full Sync.
7. Profit.

**Comment by goldenpipes** [comment]
You can also tell Ombi [how frequently to scan for recently added media](https://github.com/tidusjar/Ombi/wiki/Jobs-Tasks-Schedules).

The default is every 30 minutes. you can change the cron expression to whatever you want. I have mine set to 5 minutes.
