### ISSUE TITLE
Feature Request: "Claimed" or "In-Progress" for requests

### ISSUE THREAD

**Issue by RedTedRedemption** [tidusjar/Ombi#3471]
**Describe the bug**
When there are multiple fulfillers, it's possible for multiple people to start fulfilling a request at the same time, resulting in duplicate files.

**To Reproduce**
1. Multiple Users see request
2. Multiple users upload files
3. DUPLICATE FILESSSS!!!

**Expected behavior**
-User A looks at the open requests list and sees something they can fulfill.
-They "claim" or mark the request as "in progress"

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Multiple users uploading files? Ombi has nothing to do with files etc.

I do not understand this scenario

**Comment by RedTedRedemption** [comment]
I have multiple users that are responsible for fulfilling requests posted to ombi. We don't do uploading via ombi (usually sftp or similar), but I've had cases where multiple users upload files to fulfill a request simultaneously and we end up with duplicate files.

**Comment by tidusjar** [comment]
This is a very unusual use case for Ombi. I suggest you post the request in feathub, but currently unless there is more interest, this is not something I'm planning on adding.
