### ISSUE TITLE
Redirect view on Plex sometimes does not work

### ISSUE THREAD

**Issue by evlo** [tidusjar/Ombi#3472]
**Describe the bug**
Sometimes redirect to plex does not work.

**To Reproduce**
https://www.youtube.com/watch?v=xFk0bGLEW2w

**Expected behavior**
Redirect works always :)

**Screenshots**
See video

**Logs (Logs directory where Ombi is located)**
Nothing relevant found in time on click

**Desktop (please complete the following information):**
 - OS: Debian9

**Ombi Version (please complete the following information):**
 - Version [3.0.4892]
- Media Server [Plex]

**Additional context**
Not super important issue

**Comment by Miloune** [comment]
I have the same problem, but for me it's occurs every time. Even in the newsletter the problem occur.

This issue should be ReOpen.
