### ISSUE TITLE
View on Emby needs &serverId (Seriously)

### ISSUE THREAD

**Issue by Rojikku** [tidusjar/Ombi#3476]
**Describe the bug**
Not trying to upset anyone by reviving #3337 #3444 , but they never got real replies.
#3455 might be related but they described the issue differently and the solution arrived at seems to be different.

Emby 4.4.1.0 is literally refusing to accept the link from Ombi, and just gives me a black screen.

**To Reproduce**
1. Setup Emby correctly
2. Click View on Emby in Ombi
3. Get black screen

**Expected behavior**
Emby shows the show I clicked the link for.

**Screenshots**
![Ombi_Issue2](https://user-images.githubusercontent.com/1676068/78578250-3e11b300-77fd-11ea-9fa8-32d4ceb4285b.png)

**Logs (Logs directory where Ombi is located)**
(Probably not applicable)

**Desktop (please complete the following information):**
 linuxserver/ombi:latest

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Emby

**Additional context**
If I hit view on emby, I get pictures screen. No matter how many times I hit ctrl + r, it stays that way.
If I paste &serverId=(ServerIDHere) after it, hit ctrl + r once, it loads right up.

Yes, web/index.html#!/item/item.html?id=64849&serverId=8a3bc30000c6429daa23f57ff17c50f7 works, and
web/index.html#!/item/item.html?id=64849 doesn't.

If I delete &serverId, hit refresh, and the page is black again.

**Comment by Pyro2677** [comment]
I think it has something to do with Emby and Jellyfin accepting different addresses. He combined them and it looks like it only works for Jellyfin. Maybe he is too busy to seperate them.

**Comment by Rojikku** [comment]
> I think it has something to do with Emby and Jellyfin accepting different addresses. He combined them and it looks like it only works for Jellyfin. Maybe he is too busy to seperate them.

It's probable the issue originates from there, and a recent change in Emby has caused this. It's just a simple "if" statement and a radio button, honestly. I believe the developer has just been busy, and therefore hasn't gotten to the issue.
It's admittedly low priority.

The fact I can't filter TV shows, and thus keep deleting them from Ombi so the list is actually manageable, means the "View on emby" button isn't particularly useful compared to just using emby.

**Comment by tidusjar** [comment]
Yeah, I've been extremely busy with real life work. Regarding sorting and filtering TV shows, that's part of v4 already. So I won't be back porting it to V3. 

I will get around to this at some point soon

**Comment by tidusjar** [comment]
Not stale

**Comment by harrv** [comment]
Yes, I was just going to report this but I searched and found this open issue. The View on Emby button in Ombi on items that are available does produce a mostly correct URL, but Emby requires "serverId" as a query param and when missing just shows a blank page. It won't be very hard to fix because on the Emby settings page you have a button that loads server info from their API. One of the things returned from that API call is "serverId". So, you could add a field for it on the same page, automatically populate it, and then use it as a variable in Emby item URLs. Thanks!

**Comment by Ho2x** [comment]
Same bug V4 ...

Thank's ;)
