### ISSUE TITLE
cant press submit button on Emby server edit page

### ISSUE THREAD

**Issue by RobinMM** [tidusjar/Ombi#3480]
**Describe the bug**
cant press submit button on Emby server edit page when making a change. For example add external facing URL.

**To Reproduce**
1. go to Mediaserver > Emby/jellyfin
2. Add a external facing URL

**Expected behavior**
When updating or adding value to fields expect the SUBMIT button to become clickable

**Screenshots**
![submit-not-clickable](https://user-images.githubusercontent.com/1236301/78888444-ea53d380-7a61-11ea-9200-7d66b3ba4815.JPG)

**Desktop (please complete the following information):**
 - OS: Docker linuxserver v4 preview

**Ombi Version (please complete the following information):**
 - Version 4.0.287.0

**Comment by c0ffein** [comment]
Hi,

try to hit "Discover Server Information" after you've made your changes, then the submit button will be clickable. That's what worked for me so far.

**Comment by RobinMM** [comment]
you saved my day! Thanks @c0ffein
