### ISSUE TITLE
ApiKey Unauthorized to Update Notification Preferences

### ISSUE THREAD

**Issue by mmedic** [tidusjar/Ombi#3484]
**Describe the bug**
When attempting to update user notification preferences using a master API Key, 401 is returned.

**To Reproduce**
```
curl --request POST \
  --url https://ombi.com/api/v1/Identity/NotificationPreferences/ \
  --header 'apikey: xxxxxxxxxxxxxxxxxxxxxxxxx' \
  --header 'content-type: application/json' \
  --data '[
	{
    "userId": "0480cfd0-29ee-434d-b155-e7dbe5283ec1",
    "agent": 2,
    "enabled": true,
    "value": "123456789"
  }
]'
```

**Expected behavior**
Operation should succeed. Same ApiKey can be used to retrieve preferences.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
There is nothing in the logs.

**Desktop (please complete the following information):**
 - OS: macOS

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**
None

**Comment by mmedic** [comment]
This is still an issue

**Comment by hrfee** [comment]
Just ran into this issue on the latest version as well.

**Comment by mmedic** [comment]
Through trial and error I figured out that the request needed a `UserName` header in addition to the API key. hat worked for me.

**Comment by hrfee** [comment]
that fixed it, thanks so much!
