### ISSUE TITLE
TV Show vanishes after search - valid IMDB and TVDB ID in TV Maze (Missing TV Rage)

### ISSUE THREAD

**Issue by jakevis** [tidusjar/Ombi#3489]
**Describe the bug**
A user searches for a show - in this case "wandavision", it appears for a split second and disapears

**To Reproduce**
1. Go to TV Shows, search for "wandavision"
2. Click on search
3. Show is there.. then its not

**Expected behavior**
wandavision stays there and a user can select it

**Logs (Logs directory where Ombi is located)**
Attaching.. but I couldnt see anything useful
[log-20200413.txt](https://github.com/tidusjar/Ombi/files/4473172/log-20200413.txt)

**Desktop (please complete the following information):**
 - OS: Windows Server 

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
 - Media Server Plex

**Additional context**
This is similar to: https://github.com/tidusjar/Ombi/issues/3462
And after reading: https://github.com/tidusjar/Ombi/wiki/FAQ#when-searching-for-a-tv-show-it-appears-and-then-disappears-straight-away-or-doesnt-appear-at-all I did some digging... 
TV Maze has both IMDB and TVDB entries, but is missing TV Rage: http://api.tvmaze.com/search/shows?q=wandavision 
"externals":{"tvrage":null,"thetvdb":362392,"imdb":"tt9140560"}

I would expect shows with a missing TV rage entry to still load and function... Sonarr shows this fine and I can select it directly within that.

If there is anything else you need for debugging please let me know

**Comment by nexurus** [comment]
I am having the same issue. I'm not sure where the logs are located, but I can provide these once I find them if needed.

**Comment by eoltean** [comment]
Also having the same problem.

**Comment by PaxxiFixxi** [comment]
Same here. When i click on show name for example Breaking bad the link is broken: https://www.imdb.com/title/http://www.imdb.com/title/tt0903747//

**Comment by christianfds** [comment]
The same thing happens to the series "Resident alien"

**Comment by zachbunyard** [comment]
I'm experiencing the same issue.  I did notice that for the brief moment that the show did appear in Ombi, the title appeared as 'WandaVision (Invalid Date)'.  Is this issue instead because of a missing start date?

Another thing I notice is that WandaVision has no episodes listed on TVDB.  Nor does Resident Alien.  Could this be the issue?

I can confirm that this isn't an issue of a TheTvDb ID being present.  It's present for both WandaVision and Resident Alien:

http://api.tvmaze.com/search/shows?q=wandavision
```
[{"score":32.338104,"show":{"id":41748,"url":"http://www.tvmaze.com/shows/41748/wandavision","name":"WandaVision","type":"Scripted","language":"English","genres":["Drama","Action","Science-Fiction"],"status":"In Development","runtime":60,"premiered":null,"officialSite":"https://disneyplusoriginals.disney.com/show/wandavision","schedule":{"time":"","days":[]},"rating":{"average":6.3},"weight":99,"network":null,"webChannel":{"id":287,"name":"Disney+","country":null},"externals":{"tvrage":null,"thetvdb":362392,"imdb":"tt9140560"},"image":{"medium":"http://static.tvmaze.com/uploads/images/medium_portrait/274/686032.jpg","original":"http://static.tvmaze.com/uploads/images/original_untouched/274/686032.jpg"},"summary":"<p><b>WandaVision</b> blends the style of classic sitcoms with the Marvel Cinematic Universe in which Wanda Maximoff and Vision—two super-powered beings living their ideal suburban lives—begin to suspect that everything is not as it seems.</p>","updated":1600722290,"_links":{"self":{"href":"http://api.tvmaze.com/shows/41748"}}}}]
```

http://api.tvmaze.com/search/shows?q=resident-alien
```
[{"score":37.56215,"show":{"id":36947,"url":"http://www.tvmaze.com/shows/36947/resident-alien","name":"Resident Alien","type":"Scripted","language":"English","genres":["Drama","Comedy","Science-Fiction"],"status":"In Development","runtime":60,"premiered":null,"officialSite":"https://www.syfy.com/resident-alien","schedule":{"time":"","days":[]},"rating":{"average":null},"weight":98,"network":{"id":16,"name":"Syfy","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":null,"thetvdb":368166,"imdb":"tt8690918"},"image":{"medium":"http://static.tvmaze.com/uploads/images/medium_portrait/232/580162.jpg","original":"http://static.tvmaze.com/uploads/images/original_untouched/232/580162.jpg"},"summary":"<p><b>Resident Alien</b> is a dark, twisted and comedic fish-out-of-water story that follows a crash-landed alien named Harry who, after taking on the identity of a small-town Colorado doctor, slowly begins to wrestle with the moral dilemma of his secret mission on Earth — ultimately asking the question, \"Are human beings worth saving?\"</p>","updated":1603359655,"_links":{"self":{"href":"http://api.tvmaze.com/shows/36947"}}}}]
```
