### ISSUE TITLE
OMBI Mobile App not Connecting

### ISSUE THREAD

**Issue by jchakkalakal** [tidusjar/Ombi#3496]
**Describe the bug**
Is there a simple step by step to connect the OMBI mobile app to my OMBI server?
Here is what i have done

- Ombi installed on my server- Working
- Sonarr and Radarr intergrated- Working
- Port Forwarding on my router: port 5000 setup and working
- DuckDNS- setup dynamic dns- Working, let call it jmedia.duckdns.org that points to my server
- Setup User in OMBI user management- Working
- When use my laptop/mobiel browser and type in http://jmedia.duckdns.org:5000 it accesses OMBI on the server
- On the Ombi "Configuration" page url is http://jmedia.duckdns.org , application name is "Ombi" (default)

here is my issue:
On the mobile app (disconnected from my wifi) here are my settings

- url: http://jmedia.duckdns.org
- username: jmedia
- password: XXXX

error: "Somethings not right, check you details"

What am i missing? Thank you in advance to anyone that will prevent me from pulling out more hairs from my head :(

**Logs (Logs directory where Ombi is located)**
No Logs

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Comment by tidusjar** [comment]
PM me on Discord and i'll assist, it's going to do with how you are entering the URL

**Comment by ballersoc44** [comment]
I am having the same issue. What do I need to correct in the URL for this to work?

**Comment by jchakkalakal** [comment]
Figured it out, need to make sure the :5000 (or whatever your port is) is included in the url

Cheers,
Joel

Joel Franco Chakkalakal
c: +1.281.606.JOEL (5635)
joel@chakkalakal.com<mailto:joel@chakkalakal.com>

Book time directly on my calendar.<Calendar.Chakkalakal.com>

**Comment by jchakkalakal** [comment]
Issue is resolved
