### ISSUE TITLE
Request: Clickable "Votes Needed" page

### ISSUE THREAD

**Issue by douginoz** [tidusjar/Ombi#3498]
I'm trying to get my users to start using the voting system so that I know that it's worthwhile to honour requests.  If I direct them to the voting page (http:<blah>:5000/vote), they can see a thumbnail and title of the shows that are waiting for votes, but they can't find out anything about them.  Nothing is clickable.  So it's going to be very unlikely that users will bother voting on them if they can't easily find out what the show is about.
Of course they could find out through a more circuitous route of leaving that page and going elsewhere, but I need to encourage users to vote, not discourage them.
This request is simply to put some sort of clickable image or text in each entry to let users obtain more information needed to vote on it.

**Comment by tidusjar** [comment]
As part of v4 ill be moving the voting to the details pages
