### ISSUE TITLE
Feathub is dead - can't log feature requests

### ISSUE THREAD

**Issue by douginoz** [tidusjar/Ombi#3500]
**Describe the bug**
My 2 requests in here were auto closed with a directive to read a Readme, which tells me to use "Feathub" and a link.  Feathub appears to be dead.   The last update they made on their twitter feed was 2 years ago.

How do I make feature requests?

**To Reproduce**
Click on the link in the readme at https://github.com/tidusjar/Ombi or simply try to go to www.feathub.com
**Expected behavior**
A way to log feature requests for Ombi

**Desktop (please complete the following information):**
 - OS: Tried on iphone, Firefox, and Chrome, from inside my house out away

**Ombi Version (please complete the following information):**
 - Version all versions
- Media Server Plex

**Comment by tidusjar** [comment]
Well that sucks... If feathub is really dead and not just down then i've lost a lot of information about feature requests...

**Comment by ionred** [comment]
Their DNS is just messy. www.feathub.com doesn't work, has to be just feathub.com
