### ISSUE TITLE
Unable to select server

### ISSUE THREAD

**Issue by BodingClockchian** [tidusjar/Ombi#3502]
**Describe the bug**
Hi, im having trouble selecting a Plex server when entered my login details.

I know its there but im unable to click on it. Its actually shows the notification in the top screen that a server has been found.
Tried using multiple browsers with/without adblockers cookies etc.

**To Reproduce**
Add new Plex server, fill username password and click on Load Servers

**Expected behavior**
A clickable button for me to add the Plex server

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28387829/79690224-a464ef80-8259-11ea-9917-13c4f0e7cb8d.png)

**Logs**
No log

**Desktop**
Windows 10 
Latest firefox
Latest edge
Latest Chrome
Firefox on Android

**Ombi Version**
LinuxServer stable container
Ombi version: 3.0.4892
Plex 4.22.3 
Docker 19.03.8
Ubuntu 18

Tried to use v4, same issue for me..

**Comment by tidusjar** [comment]
This is just calling the Plex API, it seems that the API is not returning any servers for the user you have used. You can still manually enter in your Plex Details into the settings.
