### ISSUE TITLE
sqlite errors after updating to latest container

### ISSUE THREAD

**Issue by Xarin** [tidusjar/Ombi#3506]
**Describe the bug**
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.TotalSeasons'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestedByAlias'.

**To Reproduce**
It was an update from an old container to the latest (apologies I did not check the old version.)

**Expected behavior**
container starts, and web page functions as normal with no db errors

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
Ubuntu 18.04 running docker 19.03.8 with the linuxserver/ombi container

**Ombi Version (please complete the following information):**
 - latest: Linuxserver.io version:- v3.0.4892-ls53
- linuxserver/plex

**Additional context**
I have tried deleting OmbiExternal.db since that was mentioned in a previous thread but not luck.
I was able to run 
"sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'"
So if there are similar commands for RequestedByAlias and TotalSeasons that would be great!
Thanks

**Comment by tidusjar** [comment]
Wow, you must have been on a very old version. 

Any chance you have a backup of the databases before updating to the latest?

**Comment by Xarin** [comment]
Yeah doing some maintenance on my docker setup, and figured I'd get all my containers up to date while I was at it. I do have a full backup of the old database, can config files.
Thanks

**Comment by tidusjar** [comment]
OK! In that case upgrade to v3.0.4817 and start up ombi and navigate to the site (do a search or something) and then upgrade to v3.0.4892. Hopefully that will solve your issue

**Comment by Xarin** [comment]
We back up and running! Thanks for your help.

For anyone else having this issue -
1. Remove running docker container
2. Restore old ombi config
3. Create/start container using linuxserver/ombi:v3.0.4817-ls38 or equivalent official ombi docker.
4. Search for a movie and/or tv show via web browser
5. Remove container and recreate using linuxserver/ombi:v3.0.4892-ls53 or equivalent official ombi docker.
6. Run sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL' in the folder with the OmbiExternal.db (if you get the x.requestid errors in the logs)
7. If everything is working as it should upgrade to the latest ombi version.

Thanks again!

**Comment by masterwaffle** [comment]
Thanks!
