### ISSUE TITLE
Deletion of requested items still show the movie(s) as requested (Ombi v4)

### ISSUE THREAD

**Issue by dmike3** [tidusjar/Ombi#3508]
**Describe the bug**
Removal of requests still show "Requested" when looking at the movie from search

**To Reproduce**
1. Add a movie
2. Delete the request
3. Go back to movie and it still shows "Requested"

**Expected behavior**
I suspect it should remove the "Requested" action. In case somebody wants to re-request.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Ubuntu

**Ombi Version (please complete the following information):**
 - 4.0.291.0
- Plex

**Additional context**

**Comment by tidusjar** [comment]
Are they present in Radarr as Monitored?
