### ISSUE TITLE
Caddy Documentation Question

### ISSUE THREAD

**Issue by Artiume** [tidusjar/Ombi#3510]
**Describe the bug**

On https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#caddy it shows port 5000, I'm confused as to what that port is supposed to do?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]

**Additional context**

**Comment by tidusjar** [comment]
Probably better to ask on Discord. The wiki is community driven.

**Comment by Artiume** [comment]
I don't use discord. You can't answer if port 5000 is used? Thanks for your time

**Comment by tidusjar** [comment]
By default we  use port 5000, but you can change that. Check the wiki for the startup parameters
