### ISSUE TITLE
V4 - deleting user does not work

### ISSUE THREAD

**Issue by RobinMM** [tidusjar/Ombi#3517]
**Describe the bug**
deleting user does not work

**To Reproduce**
Edit a user, go to Actions tab, click delete button. Nothing happens

**Expected behavior**
User getting deleted and once returning to users overview page, the user wont be there

**Desktop (please complete the following information):**
Docker

**Ombi Version (please complete the following information):**
4.0.291.0

**Additional context**
Updating works, its a manually added user

**Comment by ionred** [comment]
Also seeing this issue on V4

**Comment by tidusjar** [comment]
This area still needs to be finished in v4
