### ISSUE TITLE
v4 - MySQL errors when attempting to use

### ISSUE THREAD

**Issue by HNGamingUK** [tidusjar/Ombi#3519]
**Describe the bug**
When attempting to startup Ombi v4 using MySQL it does not work. 

**To Reproduce**
Download Ombi v4 docker
Create databases
Create database.json file
Start Ombi v4 docker

**Expected behavior**
When starting the docker it should create the tables within the databases without issue and then display that it is open on port 3579 in the docker logs. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5269015/80563089-e4f30480-89e1-11ea-9162-f2e6628838ce.png)

**Use**
WebUI

**Ombi Version**
Using the latest version of v4 tag avalible from Linuxserver.io

**Comment by dearekaelle** [comment]
Hi Conmyster, 

I am also using Ombi in a docker (linuxserver/ombi:v4-preview) and followed the migrations steps in the wiki (very well documented and with appropriate tools btw! good job on that!) and I had no issue whatsoever. 

my ombi is running fine, no errors.

**Comment by tidusjar** [comment]
This is going to be something with the MySQL db collation you are using

**Comment by nonissue** [comment]
@dearekaelle Are the v4 specific Mysql instructions? I had v3 running perfectly with Mysql for 8 months, and then docker container updated with watchtower without me realizing. Ombi v4 wouldn't start unless i removed the database.json fail, and that reverted my data to December (to my sqlite config). I then rolled back the docker container to v3, and it still won't connect to my mysql server, it will only boot with the v3 sqlite files. I'm worried the mysql db has been modified by v4 and I'm hooped. @tidusjar

**Comment by nonissue** [comment]
Update: I'm an idiot, I restarted the mysql docker container i was using, and it's IP changed, so that's why it wasn't connecting. Haven't retried the v4 update, but wanted to acknowledge my mistake!
