### ISSUE TITLE
User's notification dont work - only to admin

### ISSUE THREAD

**Issue by MacGyver27** [tidusjar/Ombi#3521]
**Describe the bug**
I want my users to be notified when they request and when it becomes available/grabbed/ready.. I followed this https://github.com/tidusjar/Ombi/wiki/Telegram-Notifications but it does not work. Please either improve the instructions or fix the problem.

**To Reproduce**
Follow https://github.com/tidusjar/Ombi/wiki/Telegram-Notifications and then request something. Nothing arrives on Telegram..

Telegram bot is configured properly since admin receives notifications.

**Expected behavior**
User to receive notification on his telegram account.

**Desktop (please complete the following information):**
 - OS: Debian 10

**Ombi Version (please complete the following information):**
 - Version 3.0.5120 
- Media Server Plex

**Comment by tidusjar** [comment]
Can you show me what actually happens? Got some screenshots or something?

**Comment by MacGyver27** [comment]
What happens is that only admin in the specific chat (via chat id) is ever receiving the notifications..

I believe privately notifying users isn't the option - since Telegram needs chat id. So either stick with emails or make that chat room a group chat - but that would be used for all push notifications including admin's as well - which is not ideal.. correct me if I am wrong.

**Comment by tidusjar** [comment]
Currently we only support a group chat, more work needs to be done to support private chats.

**Comment by MacGyver27** [comment]
Thanks for the info. Will be looking forward to it. Michal
