### ISSUE TITLE
[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: ...

### ISSUE THREAD

**Issue by tordenflesk** [tidusjar/Ombi#3522]
**Describe the bug**
Requests are stuck on "Processing Request"

**To Reproduce**
1. Setup Linuxserver/Ombi Docker with Plex, Sonarr & Radarr
2. Request Show
3. Request gets stuck as "Processing Request"
4. [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/668203?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates&language=en
[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00

**Expected behavior**
Request to work properly...

**Screenshots**
https://i.imgur.com/5dnDc5u.png

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/raw/aCC9UpC8

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - 3.0.4892
- Plex

**Additional context**
This is on a fresh re-install of the docker, didn't work before either.

**Comment by tunes0710** [comment]
This also happens on mine.
It is when you go to the search screen and it brings up suggested movies

2020-05-04 12:58:52.153 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/668203?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates&language=en
2020-05-04 12:58:52.160 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/0?api_key=b8eabaf5608b88d0298aa189dd90bf00
2


They are both relating to scary movie 6
https://www.themoviedb.org/movie/668203 will redirect to https://www.themoviedb.org/movie/668203-scary-movie-6 which is no longer in the DB
And in Ombi... if you hover over the bit that says (Invalid Date) on SM6 - you'll see it points to https://www.themoviedb.org/movie/0/
