### ISSUE TITLE
IMBD link for shows is duplicated causing an error.

### ISSUE THREAD

**Issue by kruug** [tidusjar/Ombi#3523]
**Describe the bug**
When clicking on a TV series title in the Search, it should take you to the IMDB page but the URL is duplicated.

**To Reproduce**
1. Go to http://url.com/ombi/search
2. Click on 'TV Shows'
3. Click on show title.

**Expected behavior**
Should show IMDB page for show.

**Ombi Version (please complete the following information):**
 - Version 3.0.5127 
- Plex

**Additional context**
As an example, this is the result for Game of Thrones.
URL should be: http://www.imdb.com/title/tt0944947//
URL is: https://www.imdb.com/title/http://www.imdb.com/title/tt0944947//

**Comment by mouseware** [comment]
Same issue. Movies are OK, but the links for TV are exactly as indicated by @krugg.

Version	3.0.5127
Branch	develop
OS Architecture	X64
OS Description	Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
Process Architecture	X64

**Comment by gitty85** [comment]
Same issue

Version 3.0.5140
Branch develop
OS Architecture X64
OS Description Ubuntu 19.04 LTS
Process Architecture X64

**Comment by ThaMunsta** [comment]
Still in v3.0.5202

**Comment by tazire** [comment]
Same issue as this. I have re installed docker having deleted all appdata and issue persists. I get the following log error as a result

[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://xxx.xxx.x.xxx:8989/api/series/0

I wonder if the other posts in relation to this error have the same issue??

**Comment by Roxedus** [comment]
This is resolved in V4.
