### ISSUE TITLE
oAuth failing with reverse proxy

### ISSUE THREAD

**Issue by KJThaDon** [tidusjar/Ombi#3531]
**Describe the bug**
i've now uninstalled this twice and clean installed. Somehow admin accounts no longer work (with the correct passwords) even with Plex login..Here's the chrome console for server login and plex login.

**To Reproduce**
Setup subdomain as sub.example.com with https and plex oauth.

**Expected behavior**
Login with plex or admin

**Screenshots**
https://i.ibb.co/nmLTvj3/console.jpg
https://i.ibb.co/hCnTD3n/2.jpg

**Config file for Reverse proxy
https://paste.ofcode.org/NbFpE8M3v7f4PvtiSB2Pc8

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
Latest ombi and plex docker

**Additional context**

**Comment by PotatoQuality** [comment]
Please enter you're reverse proxy code here in code tags.

The linked page isn't working

404 Not Found
The resource could not be found.

/NbFpE8M3v7f4PvtiSB2Pc8
