### ISSUE TITLE
Unable to delete items in failed requests queue

### ISSUE THREAD

**Issue by LordJosh03** [tidusjar/Ombi#3536]
**Describe the bug**
Items in the Failed Requests queue are not being re-attempted.  Additionally I am unable to delete them.  When i inspect in Chrome, when clicking "Delete" it produces an error: "Http failure during parsing for http://192.168.1.19:3579/api/v1/requestretry//1".  Same problem occurs when using reverse DNS URL.  https://ombi.something.com (as example)

**To Reproduce**
1. Open Ombi, add something that fails to add to Sonarr or Radarr.  
2. Go to Failure Request queue.  
3. Attempt to delete item. Nothing happens. 
4. Look at Chrome and Inspect item and see error produced.

**Expected behavior**
When I click the Delete button, it deletes the item from the queue.

**Screenshots:**
Failed Requests queue Page - https://i.imgur.com/yqDnvv2.png
Chrome Error - https://i.imgur.com/r7ZdAkU.png

**Logs (Logs directory where Ombi is located)**
Will provide if needed, but nothing of note showing.

**Desktop (please complete the following information):**
OS: Ubuntu 19.01 - Docker
Ombi Version (please complete the following information): 3.0.4892
Media Server: Plex

**Additional context**
This is on a fresh re-install of the docker, didn't work before either.

**Comment by Keelan** [comment]
I assume its related to https://github.com/tidusjar/Ombi/issues/2806
Definitely an issue. Ive tried with/without reverse proxy

**Comment by haxx0r07** [comment]
I'm still experiencing this issue, has anyone found a resolution?
