### ISSUE TITLE
"View on emby" link

### ISSUE THREAD

**Issue by Thunderstormy** [tidusjar/Ombi#3537]
**Describe the bug**
_View on emby button has the wrong link format_

**To Reproduce**
_Clickon the link and you get a blank emby page_

**Expected behavior**
_To see the move listed_

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 _- OS: windows_

**Ombi Version (please complete the following information):**
 _- Version - 3.0.4892
- Media Server - Emby_

**Additional context**

_This is the link on ombi
http://mediaserver:8096/#!/item/item.html?id=551437

Emby link copied form address bar
http://mediaserver:8096/web/index.html#!/item?id=551437&serverId=a8f45644e5a34e6e8bead05482709dbb_

**Comment by atg22896** [comment]
I am noticing this same issue - The link Ombi uses does not work becuase it does not have the serverId part in it.

**Comment by PoseidonFR** [comment]
Hello,
I have exactly the same concerns.

The link is not good in Ombi.

**Comment by tidusjar** [comment]
Duplicate #3476
