### ISSUE TITLE
Can't Connect to Jellyfin

### ISSUE THREAD

**Issue by dylanevs** [tidusjar/Ombi#3540]
**Describe the bug**
I have configured ombi to connect to jellyfin but ombi gives the error:
Cannot connect to the server jellyfin

**To Reproduce**
Steps to reproduce the behaviour:
1. go to media centre - emby/jellyfin
2. enter Name for server.
3. Input IP address.
4. Input port of docker container (21352)
5. Input API Key.
6. Input url /jellyfin

**Expected behaviour**
Ombi connects to server.

**Actual Behaviour** 
Error:
Cannot connect to the server jellyfin
**Screenshots**
![Inkedmsedge_i27wGsvWBm_LI](https://user-images.githubusercontent.com/19555971/81488753-eb487280-9264-11ea-9c31-e4f3d45cf663.jpg)

**Desktop (please complete the following information):**
 - OS: Linux

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Jellyfin: 10.5.5

**Comment by Thunderstormy** [comment]
HI
I think your issue is with the item 4 "Input port of docker container (21352)"
Jellyfin is the same as emby i think, put 8096 in there and see what happens :)

**Comment by dylanevs** [comment]
Tried 8096 receiving the same error

**Comment by tidusjar** [comment]
Try and use develop

**Comment by MrChip53** [comment]
If you are still experiencing this issue I believe it is because Ombi v3 does not support Jellyfin with a base URL. Remove the /jellyfin base url and try again. If you are using a reverse proxy you can setup your jellyfin server on a subdomain with no base url ex. jellyfin.myweb.com instead of the main domain with base url.

**Comment by tidusjar** [comment]
@MrChip53 Use develop branch for v3, I have added the option to provide a base url for jellyfin/emby there....
