### ISSUE TITLE
TV shows reported as not available even though they are

### ISSUE THREAD

**Issue by gitty85** [tidusjar/Ombi#3546]
**Describe the bug**
If I run a manual full sync against my server (Plex) everything that I have correctly shows as available when searching. However after some time (not sure how long) things then revert to being not available and can be requested. This only happens for TV shows. If I run another full sync then everything goes back to available then again after some time back to unavailable and so on. 

**To Reproduce**
1. Check TV search and see if a show you have is unavailable
2. Do a manual full sync
3. Check same TV show and see if now available
4. Wait an amount of time (maybe overnight?) and check the same show to see if it is now unavailable again.
5. go back to 1 and repeat

**Expected behavior**
Once a show is available is should always be available unless it was actually removed

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
Nothing unusual in the logs, full sync works correctly and lists what it is doing. New sync does the same and does not mark as unavailable. Can attach a previous days log if required but would have a lot of info to remove, happy to send privately though?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS - Server

**Ombi Version (please complete the following information):**
 - Version 3.0.5140 - develop branch
- Media Server Plex

**Additional context**
This looks like it could be a job that only runs once a day that is reverting the status' I have tried to delete the External DB to see if that helped but unfortunately it did not.

**Comment by tidusjar** [comment]
Have you changed any of the jobs CRONs?

**Comment by gitty85** [comment]
Yes I have, I changed the Plex Recently Added Sync to 10 minutes, not sure I changed anything else though.

`Job Settings
Changes to any of the below requires you to restart Ombi. You can generate valid CRON Expressions here: http://www.cronmaker.com/
Sonarr Sync
0 10 0/1 1/1 * ? *
SickRage Sync
0 35 0/1 1/1 * ? *
Radarr Sync
0 15 0/1 1/1 * ? *
Lidarr Sync
0 40 0/1 1/1 * ? *
CouchPotato Sync
0 30 0/1 1/1 * ? *
Automatic Update
0 0 0/6 1/1 * ? *
Retry Failed Requests
0 0 6 1/1 * ? *
Plex Sync
0 0 2 1/1 * ? *
Plex Recently Added Sync
0 0/10 * 1/1 * ? *
Emby Sync
0 5 0/1 1/1 * ? *
User Importer
0 0 0 1/1 * ? *
Refresh Metadata
0 0 0/6 1/1 * ? *
Newsletter
0 0 12 ? * 6 *
Issue Purge/Delete
0 0 0 1/1 * ? *
Media Data Refresh
0 0 0/6 1/1 * ? *
`

**Comment by mikejaques** [comment]
I'm using main branch, 3.0.4892 and I can confirm problems with Television searching as well.

I'm running dockerized versions of plex (official), sonarr, radarr, ombi (all containerized by linuxserver).

I've gone as far as opening permissions on my media directory wide (it wasn't initially) and a umask in my yaml file as well ...   ombi sees my movies fine, but first run it picked up some of my TV shows, like GoT (available button and play in plex buttons), but not others, like Sherlock which just showed a +Requests button.  

If I went to add Sherlock via "+Request"  it gave me the message:
"Request Added We already have episodes requested from series Sherlock" ....  but nothing showed up in the requests.

I thought that strange, so I went to the extreme, of removing my TV shows library in plex, removing the OmbiExternal.db in my ombi config folder and regenerating both, and now, it still sees my movies, but it won't pick up ANY of my TV shows, not even GoT which previously detected.  Strange.

Nothing in the long file is overly interesting, when I click "Manually run a full sync" I get the following output:

2020-05-12 19:59:43.206 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:43.207 -06:00 [Debug] Calling Execute on job Plex.IPlexContentSync
2020-05-12 19:59:43.207 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:43.209 -06:00 [Information] Starting Plex Content Cacher
2020-05-12 19:59:43.209 -06:00 [Information] Starting to cache the content on server "proto"
2020-05-12 19:59:44.761 -06:00 [Information] Starting EP Cacher
2020-05-12 19:59:44.761 -06:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: False
2020-05-12 19:59:44.761 -06:00 [Debug] Trigger instruction : DeleteTrigger
2020-05-12 19:59:44.761 -06:00 [Debug] Deleting trigger
2020-05-12 19:59:44.767 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:44.767 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:44.767 -06:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2020-05-12 19:59:44.770 -06:00 [Debug] Trigger instruction : DeleteTrigger
2020-05-12 19:59:44.770 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:44.770 -06:00 [Debug] Deleting trigger
2020-05-12 19:59:44.771 -06:00 [Debug] Batch acquisition of 1 triggers
2020-05-12 19:59:44.771 -06:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2020-05-12 19:59:44.779 -06:00 [Debug] Trigger instruction : DeleteTrigger
2020-05-12 19:59:44.779 -06:00 [Debug] Deleting trigger
2020-05-12 20:00:00.000 -06:00 [Debug] Batch acquisition of 0 triggers
2020-05-12 20:00:00.000 -06:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2020-05-12 20:00:00.002 -06:00 [Information] Starting Plex Content Cacher Recently Added Scan
2020-05-12 20:00:00.002 -06:00 [Information] Starting to cache the content on server "proto"
2020-05-12 20:00:00.147 -06:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: True
2020-05-12 20:00:00.147 -06:00 [Debug] Trigger instruction : NoInstruction

**Comment by gitty85** [comment]
Hi,
Attached is a log from yesterday for the entire day. I have (I think) removed all lines that reference my media by name but have left lines in that relate to number of shows etc. Line 6067 says something about a database being locked? There also seems to be some other errors which I have not noticed before. 

If you need anything else please let me know.

[ombi_log.txt](https://github.com/tidusjar/Ombi/files/4620310/ombi_log.txt)

**Comment by gitty85** [comment]
Also, log from today so far, TV shows are not showing as available again.

[ombi_log1.txt](https://github.com/tidusjar/Ombi/files/4620335/ombi_log1.txt)

**Comment by gitty85** [comment]
That looks remarkably similar :)

**Comment by gitty85** [comment]
Duplicate of #3549

**Comment by mikejaques** [comment]
I fixed my issues by changing around PUID/PGID in my docker-compose and resetting file permissions on all my /config directories 

Now it all seems to work as expected, for the moment :)

**Comment by gitty85** [comment]
> 
> 
> I fixed my issues by changing around PUID/PGID in my docker-compose and resetting file permissions on all my /config directories
> 
> Now it all seems to work as expected, for the moment :)

I am not using docker so presume this does not apply?

**Comment by mikejaques** [comment]
Probably not Gitty.

I would still check permissions, I created a full new profile via Docker
where all my Docker instances live. I had previously used another general
profile. All my problems went away.

**Comment by Wytoo** [comment]
Hi there

I've got the same problem. But my log just says

     ` We have finished caching the episodes.`

**Comment by tidusjar** [comment]
A partially available status is coming in v4

**Comment by gitty85** [comment]
But all the show episodes are available? This is not a partially available issue.

**Comment by gitty85** [comment]
> Hi there
> 
> I've got the same problem. But my log just says
> 
> ```
> 2020-05-27 15:27:30.557 +01:00 [Information] We have finished caching the episodes.
> 2020-05-27 15:27:30.561 +01:00 [Debug] Batch acquisition of 1 triggers
> 2020-05-27 15:27:30.561 +01:00 [Debug] Trigger instruction : DeleteTrigger
> 2020-05-27 15:27:30.561 +01:00 [Debug] Deleting trigger
> ```
> 
> UPDATE: Figured it out. It was this https://www.reddit.com/r/Ombi/comments/cp2w12/tv_shows_downloaded_prior_to_installing_ombi/ewney89/?utm_source=share&utm_medium=web2x
> 
> It's not showing available, cause 1 or 2 episodes are missing.
> 
> A not completely available would be nice

This is seperate to my issue where I have all episodes
