### ISSUE TITLE
Enabling Android Notifications on Ombi 4 does not work

### ISSUE THREAD

**Issue by cdemi** [tidusjar/Ombi#3550]
**Describe the bug**
When using Ombi 4.0.315.0 in combination with the Android mobile app and I try to enable notifications, I get no error but notifications are still turned off. There are no errors in the logs server side and the mobile application doesn't throw an error.

**To Reproduce**
1. Open Mobile App
2. Go to Settings
3. Click Enable Notifications

**Expected behavior**
I expect to see a notification device registered in the Ombi Mobile Notification section and the mobile app to show "Notifications Enabled: True"

**Desktop (please complete the following information):**
 - OS: Android + 4.0.315.0  in docker

**Ombi Version (please complete the following information):**
 - Version 4.0.315.0 
- Media Server Plex

**Comment by tidusjar** [comment]
Check your logs at the time a notification is being sent

**Comment by cdemi** [comment]
![Screenshot_20200513-194448](https://user-images.githubusercontent.com/8025435/81846395-4ecaec80-9552-11ea-9bb7-8679e37ee291.jpg)
I see no logs while notification is being sent. I suspect it's because the app isn't registering as a mobile device for notifications

**Comment by tidusjar** [comment]
You sure it's connected to your ombi instance? Doesn't look like. 

Can you logout, force close and then relogin to your ombi.

**Comment by cdemi** [comment]
It is connected because I can browse and request content. Also if I press test connection I get a success message. It's just when I press "Enable Notifications" nothing happens. I get a loading screen and then nothing

![Screenshot_20200513-210555__01](https://user-images.githubusercontent.com/8025435/81854077-acb10180-955d-11ea-8917-984bc7a02d1d.jpg)

**Comment by cdemi** [comment]
FYI this works now with version 4.0.319.0 

Thanks a lot!
