### ISSUE TITLE
Ombi error while requesting.

### ISSUE THREAD

**Issue by stevefo813** [tidusjar/Ombi#3555]
**Describe the bug**
When I request a Movie, I get an error "Unexpected character encountered while parsing value: {. Path 'images' , line 12, position 5"    The movie still downloads anyway. This seems to have happened as soon as I started using Radarr Version 3

**To Reproduce**
1. Go to 'Ombi' While using the latest Radarr Version 3.0.0.2973. Click on 'Request a movie'
3. This error shows up in failed requests 'Unexpected character encountered while parsing value: {. Path 'images' , line 12, position 5' 
4.  The movie still downloads anyway
5. This seems to have started when i updated Radarr to Version 3

**Expected behavior**
A request should happen without error

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Unraid, Ubuntu

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.4892]
- Media Server [Plex]

**Additional context**
I noticed that Ombi does not have a V3 checkbox in Radarr settings. Sonarr does have a V3 checkbox.
<img width="883" alt="Screen Shot 2020-05-21 at 7 00 34 AM" src="https://user-images.githubusercontent.com/52574971/82552864-f0dd6c80-9b30-11ea-9c7e-dc3bbb4f3abb.png">

**Comment by tidusjar** [comment]
Radarr V3 is not yet supported by Ombi
