### ISSUE TITLE
Ombi4 - Landpage text is black, can't see it very good

### ISSUE THREAD

**Issue by dmike3** [tidusjar/Ombi#3561]
**Describe the bug**
 Landpage text is black, can't see it very good

**To Reproduce**
1. Go to landing page. 

**Expected behavior**
The text color should be white so people can see it.

**Screenshots**
None needed

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
Ubuntu

**Ombi Version (please complete the following information):**
- v4.0.339

**Additional context**
N/A

**Comment by tidusjar** [comment]
Please share a screenshot?

**Comment by mike3y** [comment]
> Please share a screenshot?

![Capture](https://user-images.githubusercontent.com/2846831/82692183-3f703100-9c2d-11ea-87b8-1a4f851fcb3d.PNG)

**Comment by alexandzors** [comment]
I just deployed v4 and am also experiencing this. Makes it really hard to read the landing page text. I tried inserting color tags into the html but that doesn't seem to fix it.
![image](https://user-images.githubusercontent.com/25626115/88195552-2c1e1980-cc0e-11ea-8043-542aa88adace.png)
![image](https://user-images.githubusercontent.com/25626115/88195593-350eeb00-cc0e-11ea-941d-b5577eeed158.png)

**Comment by douginoz** [comment]
Same problem.  html 5 tags are stripped out and the old <font> tag doesn't work either.  There's no way for users to see the landing page.

**Comment by tidusjar** [comment]
Landing page has not yet been re-worked as part of V4.

You can now use the custom css feature though until I fix it.

**Comment by Majibear** [comment]
I'm experiencing this also. Does anyone have a Custom CSS example for changing the landing page text color?

**Comment by Kazz3r24** [comment]
Works perfectly as of 4.0.500.0

**Comment by tidusjar** [comment]
Yep! Landing page has been sorted
