### ISSUE TITLE
OMBI 4 - Can access ombi only from localhost or 127.0.0.1

### ISSUE THREAD

**Issue by max01986** [tidusjar/Ombi#3564]
**Describe the bug**
-From the computer where ombi4 is installed, i can reach ombi using the address localhost:5000 or 127.0.0.1:5000 but does not work using the ip address
-Cannot reach ombi from any other computer (LAN or WAN)
-If I replace ombiv4 files with ombiv3 files, it's working perfectly.
-I tryed with multiple versions before opening the issue.

**To Reproduce**
1. Unzip folder and copy files to c:\ombi on a windows 10 PC
2. Open port 5000 firewall or disable firewall
2. Start ombi service
3. From OMBI "Server" browse to ServerIP:5000

**Expected behavior**
This site can't be reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/38813688/82706679-39d41480-9c48-11ea-8ec6-108096e9f9b5.png)

**Logs (Logs directory where Ombi is located)**
[log-20200522.txt](https://github.com/tidusjar/Ombi/files/4670205/log-20200522.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 
![image](https://user-images.githubusercontent.com/38813688/82706954-080f7d80-9c49-11ea-9f3c-054a3a7dc1cc.png)

**Ombi Version (please complete the following information):**
 - Version [4.0.339.0]
- Media Server [Plex]

**Comment by tidusjar** [comment]
Run with --host http:*:5000

**Comment by max01986** [comment]
Thank you,

and sorry... missed that of the guide...
