### ISSUE TITLE
Can't set quality and root path for requests on v4

### ISSUE THREAD

**Issue by jimski427** [tidusjar/Ombi#3565]
**Describe the bug**
No advanced options like movies where you can change the root folder and quality for requests.

**To Reproduce**
1. Go to tv requests
2. Click on options

**Expected behavior**
Have the option to dictate quality and root path for the shows like you can movies. 

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: windows 10/server 2019 

**Ombi Version (please complete the following information):**
 - Omvi Version 4.0.339.0
- Media Server version plex 1.19.3.2843

**Additional context**

**Comment by tidusjar** [comment]
It's the advanced button in the details page: 
![image](https://user-images.githubusercontent.com/6642220/82739803-b6dfb680-9d3a-11ea-8c03-ecb374c00c0c.png)

**Comment by jimski427** [comment]
> It's the advanced button in the details page:
> ![image](https://user-images.githubusercontent.com/6642220/82739803-b6dfb680-9d3a-11ea-8c03-ecb374c00c0c.png)

It is on movies but not on TV shows.
