### ISSUE TITLE
Feature Request: Change DB backup location or allowed amount of backups.

### ISSUE THREAD

**Issue by theg1nger** [tidusjar/Ombi#357]
While I love that the DB gets backed up, multiple backups take up a large amount of space (I found 11 backups totaling 8.8GB) It would be great if I could chose where these get backed up to or even the ability to chose how many backups are keep. That way the backup folder doesn't keep growing and growing. Just an idea.

Thanks,
-W

**Comment by tidusjar** [comment]
We should be deleting backups older than 7 days.

**Comment by theg1nger** [comment]
Was that changed in a release newer than 1.7.5? I just updated to 1.8.1 from 1.7.5 (Lazy me ;-) ) and noticed that I had a bunch of backups. 

![image](https://cloud.githubusercontent.com/assets/12101893/16268512/5e67c258-3854-11e6-9549-43cc04f8d3cc.png)

**Comment by tidusjar** [comment]
What you are seeing looks correct, there are no older backups than 7 days ago. I can make it configurable, so you can specify the amount of days?

**Comment by theg1nger** [comment]
That would be great or even how many backups to keep. So like 7 days or 7 backups whichever is hit first. I noticed that there are 3 6/20 backups. Does it run a backup every time its shutdown/started?

**Comment by tidusjar** [comment]
Ok!

So the rules are, if you shutdown and reopen, it checks if there has been a backup in the last hour, if not then it will backup. 

So if you start and shutdown multiple times within an hour we should only take 1 backup.

**Comment by theg1nger** [comment]
Understood. Thanks for the info. I'll keep an eye on the backups folder for the time being.

**Comment by tidusjar** [comment]
If you want for now, I can modify the relevant `.dll` to say only keep it for 2 days and send it over to you? It's a copy and replace then? Until we do it properly?

Date: Wed, 22 Jun 2016 06:48:15 -0700

**Comment by theg1nger** [comment]
Nah. I appreciate it but I can just make a symlink to a folder on a drive with more space. Really, thanks though. I love the "issues" section. Such a great feature. I don't really monitor what is actually requested so sometimes movies and such have bad audio or need subs. A+ man.
