### ISSUE TITLE
Requests to Radarr Aphrodite marked as failed

### ISSUE THREAD

**Issue by rg9400** [tidusjar/Ombi#3570]
**Describe the bug**
When adding a movie to Radarr Aphrodite branch, the movie is added fine (with no errors on Radarr's end), but it is marked as failed in Ombi. Once the movie is downloaded and added to Plex, it does get marked Available in Ombi, so it works in a practical sense though.

**To Reproduce**
1. Using an Aphrodite build for Radarr, request a movie

**Expected behavior**
Everything should work as is, but Ombi should recognize that the request went through successfully. 

**Logs (Logs directory where Ombi is located)**
```
2020-05-22 14:49:00.025 -05:00 [Warning] Tried auto sending movie but failed. Message: "constraint failed
UNIQUE constraint failed: Movies.TitleSlug"
```
```
2020-05-22 14:48:59.961 -05:00 [Error] Error when sending movie to DVR app, added to the request queue
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 12, position 5.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Ombi Version (please complete the following information):**
Ombi version: 4.0.337.0
Radarr version: 3.0.0.2977
- Media Server: Plex

**Additional context**
Talked to the Radarr devs about the issue. Per them, the issue is at Ombi's end since everything works correctly within Radarr.

**Comment by CanonCan** [comment]
I have this issue too since updating to the Radarr v3 preview aka Aphrodite

Ombi tells me about the request, then a second notification comes in immedaitely saying its sending to the retry queue and if i check sabnzbd the file is already downloading...after a few minutes Ombi reflects its available

I think what ever magic you have for the sonarr v3 fix needs to be added to the radarr set up in Ombi as well

**Comment by Cruv** [comment]
I'm getting the same behavior as well on Radarr V3 while using the develop branch of Ombi.

**Comment by tidusjar** [comment]
Yeah. In v3 they have changed the API response. I need to fix it but it's not really high priority to me at the moment as this is still in alpha.

**Comment by CanonCan** [comment]
That is unfortunate I really enjoy radar V3, isn’t the API change similar to sonarr, shouldn’t it be a fairly simple change

**Comment by tidusjar** [comment]
No idea. Not yet looked into it

**Comment by CanonCan** [comment]
Jaime any chance you could look into two user account bugs

One is local accounts cannot be deleted and there is nothing in logs or error in the web GUI (using docker for Unraid 

Other is setting user permissions under bulk edit on large shared user list (over 50) messes up all permissions in what seems randomly assigned permissions to each plex account and local account

**Comment by Do-while-Bacon** [comment]
Any chance we could get this revisited? Aphrodite feels pretty stable to me. Would be really nice not to have the "added to retry queue" spam.

**Comment by tidusjar** [comment]
Already fixed in v4

**Comment by CorneliousJD** [comment]
Since Ombi v4 is still beta, is there any plans to implement this fix int Ombi v3? 
Radarr v3 is now out of beta it seems and it's mucking up the works or more people I would imagine.

Thanks in advance.

**Comment by tidusjar** [comment]
It's been fixed in V3 develop
