### ISSUE TITLE
Ombi v4 - Settings tab clickable area too small

### ISSUE THREAD

**Issue by rg9400** [tidusjar/Ombi#3571]
**Describe the bug**
On the settings page, to click on the tabs, you have to slightly below the text. Hovering/clicking on the text itself does nothing because it is not "clickable"

**To Reproduce**
1. Go to settings page
2. Try hovering over the notification tab text vs right below the text

**Expected behavior**
The entire tab (the text, below the text, above the text) should be clickable

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]: 4.0.337.0

**Comment by tidusjar** [comment]
Browser?

**Comment by rg9400** [comment]
Microsoft Edge Version 83.0.478.37 (Official build) beta (64-bit)

**Comment by jaycedk** [comment]
Seeing the same in Firefox 76.0.1 (64-bit)
in Chrome 83.0.4103.61 its fine.

**Comment by tidusjar** [comment]
One for you @twanariens ?

**Comment by twanariens** [comment]
Have been looking at this one already. Ill see what I can do to fix it.
