### ISSUE TITLE
Sonarr - Please Check Your Entered Values

### ISSUE THREAD

**Issue by taalexander0614** [tidusjar/Ombi#3573]
Not really a bug I guess. I am trying to connect Sonarr to Ombi, I did it the same way I did with Radarr which was successful. However, when doing Sonarr when I click test connectivity it says please check your entered values. When I click load folders/quality it just spins indefinitely.

I checked the API Key using http://192.168.1.19:8989/api/system/status?apikey=[My API Key was here]

![API Verification](https://user-images.githubusercontent.com/65827376/82737872-db6b6c80-9d01-11ea-8917-9ef77bdd22e2.PNG)

**Screenshots**
![Ombi Screenshot](https://user-images.githubusercontent.com/65827376/82737959-677d9400-9d02-11ea-879d-21d395633b04.PNG)
![Sonarr Screenshot](https://user-images.githubusercontent.com/65827376/82737962-6a788480-9d02-11ea-8eb0-d2e9bb244c82.PNG)

**Logs (Logs directory where Ombi is located)**
Not sure what to look for...I didn't see anything that seemed relevant though

[log-20200523.txt](https://github.com/tidusjar/Ombi/files/4672340/log-20200523.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**
I have tried refreshing the api key, restarting the Sonarr service, using localhost/sonarr/IP address, I tried to connect both on the server and on the windows PC I access it with, I opened up the port in windows firewall, I tried with/without SSL, I tried with V3 selected

**Comment by tidusjar** [comment]
Are the any server errors or errors in the browser when you click load folders? Check the errors after a minute or so

**Comment by PotatoQuality** [comment]
Can you change the server host to localhost or on the local machine ip address?

**Comment by tidusjar** [comment]
Closing as there has been no response.
