### ISSUE TITLE
Ombi v4 - Increase the Auto Logout from 7 days to Admin Set Setting

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tidusjar/Ombi#3574]
**Describe the bug**
Ombi v4 auto logs out after 7 days, when using the Organizr SSO. Which leads to a user being loged in Organizr, but not Ombi after the 7 days are up. If the admin can set a custom amount of days in the settings before Ombi logs the user out.

**To Reproduce**
1. Signin
2. Wait 7 days
3. See that user is logout

**Expected behavior**
Users are still logged in after 7 days.

**Desktop (please complete the following information):**
 - OS: Linux

**Ombi Version (please complete the following information):**
 - Version: 4.0.339
- Media Server: Plex

**Comment by tidusjar** [comment]
This behaviour has not changed in v4

**Comment by Cookie-Monster-Coder** [comment]
> This behaviour has not changed in v4

So, it's not supposed to auto log out after 7 days? Why would this be happening then? I've tested it multiple times, and in exactly 7 days it shows me the login page.

**Comment by tidusjar** [comment]
Correct, In V3 and V4 this was the behaviour

**Comment by Cookie-Monster-Coder** [comment]
> Correct, In V3 and V4 this was the behaviour

Thank you for confirming.
Any idea on could be causing the logout?

**Comment by tidusjar** [comment]
Sorry, maybe I misunderstood.

It is expected that you are logged out after 7 days, this has always been the behaviour

**Comment by Cookie-Monster-Coder** [comment]
> Sorry, maybe I misunderstood.
> 
> It is expected that you are logged out after 7 days, this has always been the behaviour

No, worries I did word it weirdly.

Anyway to increase the amount of days? Like to 30 days. Maybe have an option in settings to customize the amount of days.

**Comment by tidusjar** [comment]
Yeah that's a possibility
