### ISSUE TITLE
HTML file seems to be interpreted as a JS file

### ISSUE THREAD

**Issue by ZackaryH8** [tidusjar/Ombi#3576]
**Describe the bug**
One of the HTML files seems to have the prefix .js and therefore believes that < is an invalid token

**To Reproduce**
1. Load any page locally
2. Press F12

**Expected behavior**
To load the page and display properly

**Screenshots**
![image](https://user-images.githubusercontent.com/40175773/82763677-4e0f4180-9e01-11ea-8b87-7d72f1a13d91.png)
![image](https://user-images.githubusercontent.com/40175773/82763691-62ebd500-9e01-11ea-8c37-b74a210cac3f.png)

**Logs (Logs directory where Ombi is located)**
No relevant logs

**Desktop (please complete the following information):**
 - OS: Windows 10 (Chrome)

**Ombi Version (please complete the following information):**
 - Version 4.0.339.0
- Media Server Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
This is not an issue, if you take a look at the code we are attempting to find the base URL dynamically.
