### ISSUE TITLE
Ombi v4 Unable to select root path and quality for tv shows. 

### ISSUE THREAD

**Issue by jimski427** [tidusjar/Ombi#3578]
> It's the advanced button in the details page:
> ![image](https://user-images.githubusercontent.com/6642220/82739803-b6dfb680-9d3a-11ea-8c03-ecb374c00c0c.png)

It is on movies but not on TV shows.  i have attached a screen shot of what i see on the tv section. 

![ombi](https://user-images.githubusercontent.com/51083907/82740033-f1cdf400-9d12-11ea-88eb-f2c7b801191e.png)

![ombi1](https://user-images.githubusercontent.com/51083907/82740044-11fdb300-9d13-11ea-8ced-e59167a7f965.png)

_Originally posted by @jimski427 in https://github.com/tidusjar/Ombi/issues/3565#issuecomment-633133637_

**Comment by tidusjar** [comment]
https://dev.azure.com/tidusjar/Ombi/_workitems/edit/21
