### ISSUE TITLE
Add the ability to mass email all Plex Users

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#358]
It would be useful to have the ability to send out an email to all of the Plex Users.
- Checkboxes against the users to deselect or select certain users
- Default to all users selected

**Comment by zenjabba** [comment]
Was looking for exactly this!

**Comment by SuperPotatoMen** [comment]
Planned in the notification update

**Comment by dhruvb14** [comment]
Working on implementing this into existing system under the Newsletter tab.

**Comment by SuperPotatoMen** [comment]
@dhruvb14 , maybe also supporting emby for this one?

**Comment by dhruvb14** [comment]
I can attempt to but not familiar with Emby API if I need to grab users since they are not already in DB till emby support is added. I haven't used Emby since it was XBMC on an original Xbox 😜

**Comment by SuperPotatoMen** [comment]
@dhruvb14 true, cool that you working on this. A lot of plex admins love this one :dancer:

**Comment by tidusjar** [comment]
It's cool if emby support isn't added in, I can add that in later on :)

**Comment by SuperPotatoMen** [comment]
In the dev branch!

**Comment by ChrisColotti** [comment]
Has it been suggested or in the works to have the mass E-Mail automatically BCC the selected users?

**Comment by tidusjar** [comment]
Mass email does BCC.
