### ISSUE TITLE
TV shows matched on Plex with TMDB instead of TVDB do not show as available

### ISSUE THREAD

**Issue by mcxr** [tidusjar/Ombi#3584]
**Describe the bug**
Shows with all episodes available on Plex but only have TheMovieDbId under PlexServerContent table in OmbiExternal.db set will not show up as available and can be requested. When requesting, the message is: Request Added - We already have episodes requested from series *SeriesName*. Manually adding the TvDbId for that show in the db will then mark that show as available on Ombi.

**Ombi Version (please complete the following information):**
- Version 3.0.4892
- Plex

**Additional context**
Some shows have better metadata on TMDB than TVDB so I'm using TMDB as the Plex agent for TV show libraries.

**Comment by tidusjar** [comment]
Please has latest develop

**Comment by mcxr** [comment]
> Please has latest develop

Nice, that works great! Thanks for your work on Ombi  :)
