### ISSUE TITLE
Synching TV shows from Plex causes errors

### ISSUE THREAD

**Issue by MorningSleeper** [tidusjar/Ombi#3585]
**Describe the bug**

I noticed some TV Shows I have in Plex library do not show up as Available in Ombi. I went to Ombi > Settings > Media Server > Plex and clicked the "Manually Run Full Sync" button then checked the Ombi log and there are some errors about too many requests to tvmaze.com as well as some errors that follow which I do not understand which also appear in log after Ombi does a scan for recently added files on Plex. Please see attached Ombi log file containing relevant lines.

Is the reason some tv shows don't show up as Available due to the tvmaze errors or the subsequent errors or something else?

**To Reproduce**

1. Use a Plex server with at least 5975 TV episodes.
2. Go to  Ombi > Settings > Media Server > Plex
3. Click the "Manually Run Full Sync" button
4. Check the Ombi log for errors

**Expected behavior**

I expect Ombi log to not have errors when it tries to synch with Plex for TV shows.

**Screenshots**

No screen shots available, please see attached log.

**Logs (Logs directory where Ombi is located)**

Please see attached log.

**Desktop (please complete the following information):**

- Hardware: QNAP TS-451+
- OS: 4.4.2.1310
- Docker: Latest image from https://hub.docker.com/r/linuxserver/ombi/

**Ombi Version (please complete the following information):**

- Ombi Version 3.0.4892
- Plex Version 1.19.3.2852

**Additional context**

None

[ombiLog.txt](https://github.com/tidusjar/Ombi/files/4692615/ombiLog.txt)

**Comment by tidusjar** [comment]
Your logs look fine. Mainly complaint about it can't get a background image. 

Please use the develop image and everything should work fine.

**Comment by MorningSleeper** [comment]
Hi, thanks for reopening and suggestion. I noticed since posting some of the ones that were not marked as Available had since been but not all. I installed the development image as suggested. Did a full refresh as described before and don't see the errors about tvmaze or the other previously reported ones so that is good. After waiting for the Meta Refresh to apparently complete, there are still some TV Shows that have a Request button even though they are available in Plex. For example ...

![image](https://user-images.githubusercontent.com/8920632/83191269-96bc4880-a0e8-11ea-9cde-3e354b0bb324.png)

As you can see, both have the green Available icon under their titles yet there is still the larger Request button. I checked the logs and the lines related to both shows don't look any different from the lines for any other TV Show that show up correctly in Ombi. Any other ideas on how I can get the Requset button to not show on TV Shows that are in Plex?

```2020-05-28 13:00:10.770 -07:00 [Information] The Media item "Fear the Walking Dead" does not have a TheMovieDbId, searching for TheMovieDbId
2020-05-28 13:00:10.785 -07:00 [Information] Setting Show "Fear the Walking Dead" because we have TvDbId, result: True
2020-05-28 13:00:10.786 -07:00 [Information] The media item "Fear the Walking Dead" does not have a ImdbId, searching for ImdbId
2020-05-28 13:00:10.786 -07:00 [Information] The show "Fear the Walking Dead" has tvdbid but not ImdbId, searching for ImdbId
...
2020-05-28 13:01:18.483 -07:00 [Information] The Media item "The Walking Dead" does not have a TheMovieDbId, searching for TheMovieDbId
2020-05-28 13:01:18.499 -07:00 [Information] Setting Show "The Walking Dead" because we have TvDbId, result: True
2020-05-28 13:01:18.499 -07:00 [Information] The media item "The Walking Dead" does not have a ImdbId, searching for ImdbId
2020-05-28 13:01:18.499 -07:00 [Information] The show "The Walking Dead" has tvdbid but not ImdbId, searching for ImdbId
```

**Comment by MorningSleeper** [comment]
Oh wait, will it still show a request button if the most recent episode is missing?
