### ISSUE TITLE
Consider moving release tags to the same repo as the code

### ISSUE THREAD

**Issue by frebib** [tidusjar/Ombi#3587]
**Describe the bug**
Today I came to build Ombi for our Docker image to find that the beta v4 "release" tags are in a separate repo (I can't work out why) and unhelpfully the git tags are on a bogus commit. The whole point of generating releases alongside the code is so there is a relationship between source and binary. There is no way of programatically mapping the tree from which the release was generated, and the tag attached to the release. I can't even use the github source tar because it is for the other repo.

Please consider putting the source and the release tags in the same repo; either reinstating the tags in this repo, or duplicating the source tree into the release repo and retaining the tags there. As it currently stands, I have no choice but to either build HEAD (probably fine, but there is little point of reference for breakages, and no version numbers) or use your precompiled source (which I'd rather not do, I want it to work on Alpine)

**To Reproduce**
1. Nope
2. Not relevant
3. Why do you enforce this stupid template?

**Expected behavior**
To not have my valid issues closed by a fucking bot

**Screenshots**
No

**Logs (Logs directory where Ombi is located)**
...

**Desktop (please complete the following information):**
Not every bug report is user error

**Ombi Version (please complete the following information):**
 - If there were tags I would know

**Additional context**
Your bot is pointless

**Comment by tidusjar** [comment]
Wow, what's with all the attitude in this issue.

Regards to the separate repo, this is not a new concept I have just "made" up. For example, the Emby Team do a similar thing: https://github.com/MediaBrowser/Emby.Releases/releases

If you are that desperate to link up the commits with the build, you can just check the build pipelines. https://dev.azure.com/tidusjar/Ombi/_build?definitionId=18&_a=summary

So thanks for you input, but I'm not going to change this just because you don't like it.

Also next time, please try and ask questions a bit nicer, this is an open source project, not a paid for service. Keep that in mind.

**Comment by frebib** [comment]
Sorry about the frustration coming out, I was pretty pissed when I wrote this- not exactly good form. By apologies. I do appreciate your work on this, it's very useful

Emby isn't exactly a good model to live by given their more recent history, IMO.

Perhaps if you don't want to change the releases repo, could you instead put the release tags on this repo too aswell?
Looking at the CI, I can't see where the release tags come from? Are they automatically generated?

**Comment by frebib** [comment]
An even easier method would be to upload a source tarball in the releases repo alongside the built binaries. Github provides source tarballs, but they are for the local repo, so in this case would contain the README file for the releases repo.

**Comment by tidusjar** [comment]
Hi, 

Ombi will remain open source and I have no plans to change that. 

Sure, that's a good idea, I'll look into adding git tags so you can match them up.

**Comment by frebib** [comment]
Thank you very much!

**Comment by frebib** [comment]
Hi, this doesn't appear to be working properly. I don't see any release tags being created, and the CI job implies that the tag is not being created? I'm not familiar with Azure CI
https://dev.azure.com/tidusjar/Ombi/_build/results?buildId=381&view=logs&jobId=2f689f16-4ad0-5dfb-f7b0-9208c60e4ced&j=2f689f16-4ad0-5dfb-f7b0-9208c60e4ced&t=5204e978-511e-5f95-656e-eddb53d8c3e0
https://github.com/tidusjar/Ombi/releases/tag/v4.0.381

**Comment by frebib** [comment]
As per the docs, I think you need `pre-release` not `draft`

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops#arguments

| Option | Description |
| --- | --- |
| Draft release | (Optional) Indicate whether the release should be saved as a draft (unpublished). If false, the release will be published. |
| Pre-release | (Optional) Indicate whether the release should be marked as a pre-release. |
