### ISSUE TITLE
Ombi v3 - some movies stuck on processing request

### ISSUE THREAD

**Issue by almulder** [tidusjar/Ombi#3589]
**Describe the bug**
I have been using ombi now for over a year and I am now noticing that there are movies that are stuck on "processing request" I can add several movies and no issues and they out of nowhere the next movie will be stuck, but the one right after that goes with no issue.

**To Reproduce**
Cant reproduce on the fly as I can add several movies in a row and one right in the middle will get stuck.

**Expected behavior**
there should be an auto retry for processing requests that are stuck for more than a day

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 -UNRAID

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server: Plex

**Additional context**
Wife added 15+ movies last night and only a few are stuck all the others went through to radarr

**Comment by tidusjar** [comment]
What do you mean get stuck?

Is there anything in the failed request queue? (Settings page for it)

**Comment by almulder** [comment]
No noting in the failed.  And by struck I mean they don't get pushed to radarr. I can add 10 movies and one might not get pushed for an unknown reason. I looked at the logs but seen nothing that would have stopped it.

**Comment by camjac251** [comment]
I am seeing this as well. Tried to view the logs under system > logs but that page doesn't show anything

**Comment by tidusjar** [comment]
You sure the request was actually made?

**Comment by almulder** [comment]
Ok i can reproduce this in both v3 and v4.

I notice this happens sometimes when my internet drops or Sonarr/Radarer is unreachable

Should it not auto retry, I can add new items and they pass through, but the ones stuck never seem to retry.

Is there a way to force return the processing requests., Looks like one day my wife went nuts adding when it could not connect to radarr and I have over 1000 now in the list not going through.

To Reproduce
Steps to reproduce the behavior:
disable Radarr
add a movie
re-enable radarr
move is now stuck on processing request
restarting ombi does not help
same issue in v3 and v4

**Comment by tidusjar** [comment]
If the connection drops then the request will go into a auto retry queue. 

If you turn off radarr/sonarr and request and then turn it back on, nothing will happen and you need to manually manage the request.

**Comment by almulder** [comment]
Well there are plenty that were requested while it could connect to radarr, yet they still sit as processing request. Is there anyway to force re request all items in processing request section? if not could you add a feature to do so, seems like this is an ongoing issue with people and a button to re process all would be awesome. (Also really loving v4)

**Comment by tidusjar** [comment]
A re-send feature is planned for future development!

feel free to add it here:

https://features.ombi.io/
