### ISSUE TITLE
V4 - New setup - unable to re login with plex credentials / and more issues, requests

### ISSUE THREAD

**Issue by almulder** [tidusjar/Ombi#3591]
**Describe the bug**
1) I setup v4 to test out and used my plex login to link it, upon using my plex login suring the initial setup it bypasses the admin login creation, however once I log out and try to log back in, it stays at the login screen (and no errors) if I change the name or password then I get the errors. So i could not log back in, so I nuked the settings and started fresh, this time before I logged out I created another admin user manually just incase and I am glad I did as I again could not log in with my plex stuff.

2) When setting up the plex media server during setup, it pulled the wrong ip and port. Had to manually change them.

3) Dark Mode - have chrome using dark mode and when viewing the text in v4 its dark gray text and a slightly lighter gray background due to dark mode, so it make it hard to read text and buttons.

4) Custom Logo does not appear on login page.

5) Landing page is not centered on screen like before (v3) (and would like to have a smaller custom logo show here. Its a bit in the face)

6) donation links are not shown.

7) When viewing movie list, non english movies are appearing. (should have an option to hide non english stuff)

8) When viewing the requested list, only a list is shown, would expect a poster view option as well, along with each section having a running total. All requests, Pending, Available, denied (show how many)

9) When pulling items from plex it should also pull from radarr and such.

10) Need a way to verify if the requests were sent and received my sonarr, radarr and such. and if they were not received by them, then at x time daily, weekly, resend the request to sonarr, radarr, after 5 failed attempts add to failed list with a short reason as to why.

11) Calendar view, when clicking on a date with releases, I would expect it to show them for that day in a poster list. and if in calendar view and we click on just the title of one it would open that request.

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version 4.0.340.0
- Media Server: Plex

Overall I am super excited to use v4 as my new replacement once the buys get worked out. Also plan  on sending another donation once my wife approves me to do so. :)

**Comment by tidusjar** [comment]
Thanks, please keep in mind v4 is still in an alpha state as not all the functionality is complete.

1. This is an existing problem in v3, i'm going to resolve it by always forcing the user to create an admin user

2. Same as v3, those details come from the Plex API

3. Please provide a screenshot to explain

4. Known issue

5. Landing page has not yet been redesigned to fit in with v4

6. Not added yet

7. Same as v3, no difference

8. Not planning to add posters, not in the inital v4 release, the requests page is mainly for the admin anyway, users never look at it.

9. Same as v3

10. This already happens and the admin recieves a notification

11. Calendar view has not been finished

**Comment by almulder** [comment]
Wow that was a quick response. :) I know its alpha and you have alot on your plate to take care of, more an FYI. Wife tried it out and she is in love with the new version even the current way she love it so much better. 
3) Once it happens again I will get a screen shot as it done not always use dark mode, not sure if it a me issue or not. 

Your doing awesome work and cant wait to see what else you do to the app. :) Thanks so much for continuing to update the app. 

As promised just sent ya $25, wish I could send more, but at least its something. :) Thanks again for all that you do.

**Comment by tidusjar** [comment]
Thanks, Appreciate it!
