### ISSUE TITLE
v4 UI broken and buttons not working

### ISSUE THREAD

**Issue by 19wolf** [tidusjar/Ombi#3600]
**Describe the bug**
The UI is broken, and only two of the buttons seem to do anything.

**To Reproduce**
1. Go to ip:3579
2. Click on 'settings'
3. Nothing happens

**Expected behavior**
Settings should open

**Screenshots**
https://imgur.com/W9viS0X

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/raw/gUKLJsYc <-- Google Chrome console log after clicking on settings

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version no idea, but it comes from linuxserver/ombi:v4.0.349-ls2
- Media Server Plex

**Comment by tidusjar** [comment]
Working fine for me, ensure you clear your browsers cache, and do not install over V3, requires a clean install

**Comment by juliemars** [comment]
Same issue spent the past hour trying to work it out and finally got it. 

2 issues 1 is it was pulling the fonts via cross site which is disabled on modern browsers turning this off stopped it and then I found that default pi-hole blocks the domain fonts.gstatic.com disabling pihole for 10 seconds and refreshing the page and leaving Cross site disabled allowed it to load the font and icons.
