### ISSUE TITLE
V4 - Legacy Mobile Notifications - unable to remove user

### ISSUE THREAD

**Issue by esticle** [tidusjar/Ombi#3605]
**Describe the bug**
I seem to be unable to remove a legacy mobile notification user.

**To Reproduce**
1. Go to Settings -> Notifications -> Legacy Mobile 
2. Click on the user dropdown and select user
3. Click on 'Remove User'
4. Nothing occurs

**Expected behavior**
I expect the notification method to get deleted

**Logs (Logs directory where Ombi is located)**

Probably unrelated but my logs also show:

```
info: Ombi.Notifications.Agents.LegacyMobileNotification[0]
      there are no users to send a notification for RequestAvailable, for agent Mobile
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no users to send a notification for RequestAvailable, for agent Mobile
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
fail: Ombi.Api.CloudService.CloudMobileNotification[0]
      Error when sending mobile notification message, status code: InternalServerError. Please raise an issue on Github, might be a problem with the notification service!
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
fail: Ombi.Api.CloudService.CloudMobileNotification[0]
      Error when sending mobile notification message, status code: InternalServerError. Please raise an issue on Github, might be a problem with the notification service!

```

**Desktop (please complete the following information):**
 - Linux x64

**Ombi Version (please complete the following information):**
 - linuxserver.io Docker container of Ombi  v4.0.358.0

Thanks!

**Comment by tidusjar** [comment]
Trending is a combination of Most Watched (movies) and Trending (Tv Shows), so it's pretty difficult to rank them in order, but the first page is pretty much always the top "trending"

**Comment by esticle** [comment]
I suspect this comment relates to #3606 and not this bug report?

**Comment by tidusjar** [comment]
haha damn!
