### ISSUE TITLE
v4 - Trending titles in random order

### ISSUE THREAD

**Issue by esticle** [tidusjar/Ombi#3606]
**Describe the bug**

I understand why we might want to randomise the content display order under 'Popular' however why is content randomised when clicking 'Trending'? 

Trending (to me at least) would mean a list in order of trend position rather than a randomised list of trending items.

Thoughts?

**To Reproduce**
1. Go to 'Discover'
2. Click on 'Trending', observe order of content
3. Click on 'Popular'
4. Click on 'Trending', observe order of content

**Expected behavior**
I expect trending items to be listed in order of their trend position.

**Desktop (please complete the following information):**
 - Linux x64

**Ombi Version (please complete the following information):**
 - linuxserver.io v4.0.358.0

**Comment by tidusjar** [comment]
Trending is a combination of Most Watched (movies) and Trending (Tv Shows), so it's pretty difficult to rank them in order, but the first page is pretty much always the top "trending"
