### ISSUE TITLE
v4 - 'Object' appears in search box

### ISSUE THREAD

**Issue by esticle** [tidusjar/Ombi#3608]
**Describe the bug**

At times, the word 'Object' is repeatedly shown in the search field.

**To Reproduce**
1. In the search bar type 'test search'
2. Click on the first result
3. Click on the search bar and press the backspace once
4. Notice the word 'Object' appear and then go away

**Expected behavior**

Should not seen 'Object' listed when it was not searched for.

**Desktop (please complete the following information):**
 - OS: Linux_x64

**Ombi Version (please complete the following information):**
 - Dockered v4.0.362.0 
 - Plex

**Additional context**

I seem to now-and-then get 'Object' in the search box if I click there even if I am not searching anything, however cannot find a way to repeatedly replicate that behaviour.

**Comment by PotatoQuality** [comment]
Can't reproduce the problem locally. Can you pull the last updates and try again?

**Comment by esticle** [comment]
Agree, this does not appear in v4.0.371.0 anymore. Thanks!
