### ISSUE TITLE
V4 unable to fetch movies through radarr

### ISSUE THREAD

**Issue by tommy-b-10** [tidusjar/Ombi#3609]
**Describe the bug**
I have setup Radarr with both v3 & v4 identically. When attempting to request and fetch movies on v4, the following message appears at the bottom of the screen:
`constraint failed NOT NULL constraint failed: Movies.Images`

**To Reproduce**
1. Search or find a movie via Discover
2. Open the movie and click 'Request'
3. Following appears in banner at the bottom of the screen
`constraint failed NOT NULL constraint failed: Movies.Images`
4. Radarr logs show 'Adding Movie [_Movie Title (Year)_][, 503919] Path: [_/movies/Movie Title (Year)_]
4. No movie is actually added or searched for in Radarr
5. Ombi does not show it as a failed request, and shows as 'Processing Request'

**Expected behavior**
The movie be added to Radarr to be searched.

**Logs (Logs directory where Ombi is located)**
```
2020-06-11 22:38:41.352 +09:30 [Error] constraint failed
NOT NULL constraint failed: Movies.Images
2020-06-11 22:38:41.354 +09:30 [Warning] Tried auto sending movie but failed. Message: "constraint failed
NOT NULL constraint failed: Movies.Images"
2020-06-11 22:38:41.354 +09:30 [Warning] Tried auto sending movie but failed. Message: "constraint failed
NOT NULL constraint failed: Movies.Images"
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.359.0
- Media Server Plex

**Comment by soccerdmon11** [comment]
Hi,
Also adding to this. After updating to v4.0.362 I also am getting this error (removed my IP:Port):

2020-06-11 10:06:10.480 -07:00 [Error] StatusCode: Conflict, Reason: Conflict, RequestUri: http://IP:PORT/api/movie
2020-06-11 10:06:10.482 -07:00 [Error] constraint failed
NOT NULL constraint failed: Movies.Images
2020-06-11 10:06:10.485 -07:00 [Warning] Tried auto sending movie but failed. Message: "constraint failed
NOT NULL constraint failed: Movies.Images"

**Comment by tidusjar** [comment]
Use the latest version now. I've fixed this

**Comment by soccerdmon11** [comment]
Just tested this with the updated v4.0.365 and it is now sending to Radarr properly. Thanks!

**Comment by tommy-b-10** [comment]
Tested with v4.0.365 and is working as expected. Thanks @tidusjar!
