### ISSUE TITLE
[Enhancement] Discord Notifications

### ISSUE THREAD

**Issue by ducky** [tidusjar/Ombi#3611]
**Describe the Enhancement**
The notifications in Discord were doing the job, but I couldn't find a way to remove images and saw that there was an old issue mentioning that it wasn't a high priority to add a toggle, which I totally understand.

**My Workaround**
I ended up using a Mattermost webhook to hit my own custom url with the payload and then I parsed it and hit Discord using my own webhook.

**Notes**
I'm not super fluent in .NET and didn't want to go through pulling the repo down just to update the notification template, so instead I've included my sample JSON payload that I'm hitting Discord with to achieve what feels like a nicer notification format that I feel like could be picked apart relatively easily.

I didn't add Issues on my end but they could be added similar to rejection I'd assume. This also kind of removes the need for custom user crafted messages in the Ombi UI?

**Screenshots**
![image](https://user-images.githubusercontent.com/1869084/84433622-92218500-abfc-11ea-97e9-584e188a1103.png)
![image](https://user-images.githubusercontent.com/1869084/84433665-a6fe1880-abfc-11ea-9366-f357f39f2ed2.png)
![image](https://user-images.githubusercontent.com/1869084/84434025-48856a00-abfd-11ea-9c72-3c5ec67dd439.png)

**Discord Webhook Code (JavaScript just to show my optional fields)**
```js
const message = {
  title: '{Title} ({Year})',
  description: '{Overview}',
  color: 2206669, // I used different colors for the action (Green - Approved/Available, Blue - Requested, Red - Rejected), but a neutral color works too
  timestamp: new Date(), // or {RequestedDate}
  fields: [
    { name: 'Requested By', value: '<@{UserPreference}> or {Alias}', inline: true },
    { name: 'Status', value: `\`APPROVED\``, inline: true }, // Requested, Approved, Rejected, Available
    isTvShow && { name: '# Seasons', value: 'Length of {SeasonsList}', inline: true },
    isTvShow && { name: '# Episodes', value: 'Length of {EpisodesList}', inline: true },
    isRejected && { name: 'Rejection Reason', value: '{ReasonDeny}' },
  ],
  author: {
    name: '{ApplicationName}',
    url: '{ApplicationUrl}',
    icon_url: 'https://path.to.ombi.or/favicon.png',
  },
  footer: {
    text: reason, // Marked as Rejected, etc
  },
};

if (details.requestArt) {
  message.thumbnail = { url: '{PosterImage}' };
}

const httpBody = {
  embeds: [message],
};
```

**Ombi Version (please complete the following information):**
- Version: 3.0.4892
- Media Server: Plex

**Final Thoughts**
Feel free to close this if it's not relevant. I've already got it working well on my end but figured I'd pass it on!

**Comment by tidusjar** [comment]
Nice!! I'll add it in!

**Comment by ducky** [comment]
Awesome! Glad you like it!

Also if you wanted to tweak/test, this site was super helpful for previewing it: https://leovoel.github.io/embed-visualizer/

Something that'd be a lot more work, but really cool at some point could be adding a way to approve/deny a request via a reaction (up/down arrows) directly from Discord. I'm not sure if that's supported via webhooks and would probably have to be a bot, but figured I'd just throw it out there.

**Comment by tidusjar** [comment]
Discord has been enhanced, thanks for the tops!

**Comment by ducky** [comment]
Awesome, excited to try it out, and hope others like it too!
