### ISSUE TITLE
Ombi v4 - Lidarr switches aligned right

### ISSUE THREAD

**Issue by dualznz** [tidusjar/Ombi#3612]
**Describe the bug**
Lidarr administration switches are aligned right which are horrible for widescreens

**To Reproduce**
1. Go to **Settings**
2. Click on **Music**
3. Scroll down to **Lidarr**

**Expected behavior**
Align switches to the right for cleaner layout

**Screenshots**
![https://i.gyazo.com/2facf6a042d387d52fb86c81bea6b0e1.png](https://i.gyazo.com/2facf6a042d387d52fb86c81bea6b0e1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS Server

**Ombi Version (please complete the following information):**
 - Version **4.0.365.0**
- Media Server **Plex**

**Comment by tidusjar** [comment]
This should now be fixed in the latest version
