### ISSUE TITLE
Ombi v4 - User bulk edit model broken

### ISSUE THREAD

**Issue by dualznz** [tidusjar/Ombi#3613]
**Describe the bug**
When trying to bulk edit users the model comes up transparent and cannot be accessed when clicking on anything within the model it closes. 

**To Reproduce**
1. Go to **User Management**
2. Click on **User Tick Boxes**
3. Then click on **Bulk Edit**
3. See error

**Expected behavior**
The model should not be transparent and should be accessible without the model closing on-click

**Screenshots**
![https://i.gyazo.com/141ebdddf788a85ee941b6837126bbdb.png](https://i.gyazo.com/141ebdddf788a85ee941b6837126bbdb.png)

**Desktop (please complete the following information):**
 - OS: **Ubuntu 18.04.4 LTS Server**

**Ombi Version (please complete the following information):**
 - Version **4.0.365.0**
- Media Server **Plex**

**Comment by PotatoQuality** [comment]
bug confirmed

**Comment by abendel** [comment]
Bug confirmed.
You can edit individually

**Comment by PotatoQuality** [comment]
(small bump)

**Comment by bruvv** [comment]
Why does this has the label `wontfix`?

**Comment by PotatoQuality** [comment]
@bruvv where did you found that there is a label assing wontfix?

**Comment by dualznz** [comment]
the `wontfix` label has been removed it was the bot doing it due to stale movement

**Comment by tidusjar** [comment]
fixed
