### ISSUE TITLE
Ombi does not send notification to a Telegram Group

### ISSUE THREAD

**Issue by rshamsz** [tidusjar/Ombi#3616]
**Describe the bug**
Ombi does not send notification to a Telegram Group
**To Reproduce**
On setting > Notification > Telegram >   Chat ID , use a Group ChatID like "-4495226**".
Click Test nothing is received on the Telegram Group,

**Expected behavior**
A message should be sent to the Telegram Group as it is sent to a Telegram UserID.
-I assume that when a user requests something, a message like this:

Hello! The user @{UserPreference} has requested the {Type} '{Title}'! Please log in to approve this request. Request Date: {RequestedDate}

will be sent to the Telegram Group configured in the setting > notification > Telegram > Chat Id, and that user will be tagged in the message using the "User Preference" which is set for that user in the "User Management"> <User> details > Notification Preferences > Telegram section

**Screenshots**
![image](https://user-images.githubusercontent.com/44298524/84578938-abab0400-ad97-11ea-865a-0e40fd504266.png)

**Desktop (please complete the following information):**
 - OS:Windows 10, FireFox

**Ombi Version (please complete the following information):**
Docker on CentOS7 host
Version | 3.0.4892
-- | --
Branch | master

- Media Server : Plex

**Additional context**
-If I use a Telegram UserID, that user will receive the messages.

**Comment by PotatoQuality** [comment]
Please post the logs files from Ombi so we can investigate what is going on.

**Comment by paradoxni** [comment]
@rshamsz I have the same version as you and Telegram notifications to groups are working fine. I did get the same issue when I used the incorrect chat_ID for the group. I had followed a guide that suggested adding @get_id_bot to the group, which gave me a chat_ID, but this failed to notify from Ombi. I then tested outside of Ombi using curl and got an error about the chat_ID. I found the correct chat_ID via this method:

- Add your bot to your group
- Browse to https://api.telegram.org/bot<YOUR BOT API KEY>/getUpdates
- Look for your group name in the response and note the chat_ID has a negative number
- Use this negative value chat_ID in Ombi

You should now fine Ombi notifies the group as expected.
