### ISSUE TITLE
Requests from Organizr homepage not working

### ISSUE THREAD

**Issue by ajhong2** [tidusjar/Ombi#3618]
**Describe the bug**
Cannot make request from Organizr homepage. Tested connection and all seems well.

**To Reproduce**
1. Install Organizr
2. Add Ombi to homepage
3. Try making a request
4. Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31233783/84582037-a64fb880-ad9b-11ea-8864-47371c5c28c0.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Unraid Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4892

- Media Server
Plex

**Additional context**

**Comment by PotatoQuality** [comment]
Please post the logs files from Ombi so we can investigate what is going on.

**Comment by ajhong2** [comment]
Seems that restarting the Ombi docker has resolved the issue.
