### ISSUE TITLE
Ombi v4 - Rocketchat - The webhook doesn't send the text 

### ISSUE THREAD

**Issue by Floflobel** [tidusjar/Ombi#3621]
**Describe the bug**
I set up a RocketChat server to allow me to receive my notifications. I'm using webhook to get notifications of requests but it seems that it doesn't work well. I only receive the username but not the text.

**To Reproduce**
1. Setting up a webhook "URL base".
2. Test the sending of a message or wait for a notification to arrive

**Expected behavior**
A message should be sent below the username (look at the screenshot). I think we should add a configuration on Ombi to let the user choose which JSON to send to the destination URL. 

**Screenshots**
Example on Slack (works)
![Screenshot from 2020-06-16 17-22-27](https://user-images.githubusercontent.com/13889750/84794069-1b1e2f00-aff6-11ea-9fbc-bb84fb26aece.png)

Example on Rocketchat (doesn't works)
![Screenshot from 2020-06-16 17-22-47](https://user-images.githubusercontent.com/13889750/84794057-18bbd500-aff6-11ea-9c12-1ac94397dbc4.png)

**Logs (Logs directory where Ombi is located)**
No logs

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Ombi Version (please complete the following information):**
 - Version: v4.0.372

**Additional context**
JSON send example
```
{
  "text": "Example message",
  "attachments": [
    {
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat",
      "image_url": "/images/integration-attachment-example.png",
      "color": "#764FA5"
    }
  ]
}
```

or with a curl:
```
curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' https://mydomain/hooks/Zfdgdfgdfgdfgdfgdfgdebg6/7Wdfgfgdfgdfgdfgdfgdfgus8RRxsPiev4P7yQmBK8Cg
```

**Comment by tidusjar** [comment]
We do not have a rocketchat integration, if you are using webhooks, it's most likely that the webhook format Ombi uses is not compatible with RocketChat.

**Comment by Floflobel** [comment]
Isn't it possible to add a field to customize the JSON sent with the web-hooks ?
