### ISSUE TITLE
[V4] Search no longer works when using Firefox

### ISSUE THREAD

**Issue by PrincessLuna2253** [tidusjar/Ombi#3622]
**Describe the bug**
After the latest update, I can no longer use the search bar with Firefox. Worked fine last update, and it still works fine in MS Edge, the only other browser I have installed. I can type in the name of a movie or show and it gives me suggestions, but when I click one instead of being taken to the page for that movie or show nothing happens.

**To Reproduce**
1. Go to home page of Ombi
2. Type movie or show name into the search bar at the top of the screen
3. Click on a search result

**Expected behavior**
Being taken to the page for the selected piece of media, where it can be requested

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
Wouldn't expect to see anything in the logs for this issue, would be happy to provide them if they'll help though

**Desktop (please complete the following information):**
 - OS: Windows 10 update 2004, Firefox 77.0.1

**Ombi Version (please complete the following information):**
 - Version 4.0.375.0

**Comment by tidusjar** [comment]
Please provide the errors from the browsers console.

**Comment by PrincessLuna2253** [comment]
Well, I'm embarrassed. Despite only being an issue on Firefox, the issue ended up being my reverse proxy configuration. Didn't think to check that since Edge and later Chrome worked fine.
