### ISSUE TITLE
Recommendations for improved search screen

### ISSUE THREAD

**Issue by cwilcoxc** [tidusjar/Ombi#3626]
On the 'Search' screen there are separate orange tabs to search within: one for Movies, one for TV, one for Music. 
I don't know about anyone else, but in my opinion, these tabs and styling below really let the interface down as it is are not obvious enough for users to quickly work out what is going on:

1. the tab font is too small
2. there is no 'inactive' colour for the tabs
3. the 'active' orange tab colour does not align with the grey background containing the search results below

A bit of CSS to rectify these points would, in my opinion, make would make this page so much easier to navigate. Just a thought, and I'm sure there are many more pressing issues!

Cheers!

**Comment by tidusjar** [comment]
V4 resolves this
