### ISSUE TITLE
Ombi v4 - Are there suppose to be different types of check boxes?

### ISSUE THREAD

**Issue by ziggie216** [tidusjar/Ombi#3629]
**Describe the bug**
Just a visual thing, but was wondering about the consistency of the selection / check boxes. WAs this intended to be like this? Some looks normal (black background with proper spacing between box and text) and other looks smaller (white background box with text stuck next to box).

**To Reproduce**
Proper looking check box Settings > Ombi | Settings > Configuration > Customization, Landing Page, 
Not proper looking boxes Settings > Configuration > Issues and all others

I tried Chrome and Safari, both browser looks the same.

**Screenshots**
https://imgur.com/MkYX6JK
https://imgur.com/Jojahz8
**Desktop (please complete the following information):**
 - OS: unRAID

**Ombi Version (please complete the following information):**
 - Version 4.0.381.0
- Media Server Plex

**Comment by tidusjar** [comment]
Not all the settings pages have yet been restyled to the new version
