### ISSUE TITLE
Ombi shows items as requested, but they are not

### ISSUE THREAD

**Issue by ReenigneArcher** [tidusjar/Ombi#3649]
**Describe the bug**
In Lidarr I added an artist. I then removed the artist from Lidarr, and was going to add the albums in Ombi; however several of the albums are showing as requested when searching. No music is shown in the requests section of Ombi. I restarted Lidarr, Ombi, and the entire server.

**To Reproduce**
1. Go to Lidarr
2. Add an artist
3. Remove the artist
4. Search for the artist and albums in Ombi
5. Some (maybe all) of the albums will be marked as requested in Ombi

**Expected behavior**
After items are removed from Lidarr, they shouldn't be marked as requested in Ombi.

**Screenshots**
![image](https://user-images.githubusercontent.com/42013603/86401450-3f297380-bc78-11ea-9658-b4a30fa9c56e.png)
![image](https://user-images.githubusercontent.com/42013603/86401484-4c466280-bc78-11ea-973a-4a1d0dfff4ee.png)
![image](https://user-images.githubusercontent.com/42013603/86401522-5bc5ab80-bc78-11ea-9611-c4a674cee75e.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
Win 10 Pro 64bit

**Ombi Version (please complete the following information):**
V 3.0.4892 - master
Plex

**Additional context**

**Comment by tidusjar** [comment]
Ombi has cached the monitored artists and albums, next time the job runs it will sort itself out
