### ISSUE TITLE
Loading wheel keeps spinning when trying to open an "Issue"

### ISSUE THREAD

**Issue by Jakesparrow** [tidusjar/Ombi#3650]
**Describe the bug**
A user reported an issue with a movie. I click on "Issues", and I see the movie title and the description of the issue. I click on "Details" so I can mark it as resolved etc. but itjust spins and spins and never loads. 

**To Reproduce**
Have user report issue. 
Go to issues in Ombi.
Click on "Details" on the right.

**Expected behavior**
Load additional options to mark issue as resolved.

**Logs (Logs directory where Ombi is located)**

[log-20200703.txt](https://github.com/tidusjar/Ombi/files/4869705/log-20200703.txt)

**Desktop (please complete the following information):**
Windows 10 64 Version 10.0.18362 Build 18362

**Ombi Version (please complete the following information):**
 v4.0.392

Plex

**Comment by PotatoQuality** [comment]
Please post your console logs from your browser when the problem occurs so we can troubleshoot the problem.

**Comment by Jakesparrow** [comment]
> Please post your console logs from your browser when the problem occurs so we can troubleshoot the problem.

Here you go!
[browserlogs.txt](https://github.com/tidusjar/Ombi/files/4872996/browserlogs.txt)

Thanks for the reply!

**Comment by PotatoQuality** [comment]
You still posting the Ombi logs instead of the console logs of the browser.

Its look like this:
![image](https://user-images.githubusercontent.com/2944704/86540267-21703e80-bf04-11ea-9429-851e5163d151.png)
