### ISSUE TITLE
Ombi v4 nav and search bar not always showing

### ISSUE THREAD

**Issue by markschrik** [tidusjar/Ombi#3654]
**Describe the bug**

**To Reproduce**
Log into Ombi v4 with a chrome mobile or samsung mobile browser. Beware, the problem does not always occur.
**Expected behavior**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/56775030/86533121-1c44cc80-becf-11ea-87ba-8c2380836730.png)
![unknown2](https://user-images.githubusercontent.com/56775030/86533122-1d75f980-becf-11ea-81fd-8bf081c8782f.png)

**Logs (Logs directory where Ombi is located)**
Can not find any http issues in the log. 

**Desktop (please complete the following information):**
 - OS: Android 9

**Ombi Version (please complete the following information):**
 - Version 4.0.392.0
- Media Server Plex

**Additional context**
Sometimes whenever someone logs in with Plex oAuth, the top bar is just gone. Not able to search.

**Comment by tidusjar** [comment]
What mobile is that on? Looks like it's to do with the resolution
breakpoints

**Comment by markschrik** [comment]
Galaxy S7 as far as I know

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dragon4nogard** [comment]
I'm having the same issue on a Pixel Slate running Version 83.0.4103.119 (Official Build) (64-bit). I did not have this issue on a Windows 10 desktop running Chrome (likely version 83 but I can confirm if that will help). Whenever I search for content I just get the loading arrows in the drop down but nothing loads.
