### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by springjools** [tidusjar/Ombi#3657]
**Describe the bug**
Unexpected character encountered while parsing value: {. Path 'images', line 11, position 5.

**To Reproduce**
Request a movie

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
#033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Core.Senders.MovieSender[0]
Jul  6 11:50:21 jovian Ombi[31536]:       Error when sending movie to DVR app, added to the request queue
Jul  6 11:50:21 jovian Ombi[31536]: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 11, position 5.
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonTextReader.ReadAsString()
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
Jul  6 11:50:21 jovian Ombi[31536]:    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
Jul  6 11:50:21 jovian Ombi[31536]:    at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
Jul  6 11:50:21 jovian Ombi[31536]:    at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
Jul  6 11:50:21 jovian Ombi[31536]:    at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
Jul  6 11:50:22 jovian Ombi[31536]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.MobileNotification[0]
Jul  6 11:50:22 jovian Ombi[31536]:       there are no admins to send a notification for Test, for agent Mobile
Jul  6 11:50:56 jovian Ombi[31536]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Core.Senders.MovieSender[0]
Jul  6 11:50:56 jovian Ombi[31536]:       Error when sending movie to DVR app, added to the request queue
Jul  6 11:50:56 jovian Ombi[31536]: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 11, position 5.
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonTextReader.ReadAsString()
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
Jul  6 11:50:56 jovian Ombi[31536]:    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
Jul  6 11:50:56 jovian Ombi[31536]:    at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
Jul  6 11:50:56 jovian Ombi[31536]:    at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
Jul  6 11:50:56 jovian Ombi[31536]:    at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
Jul  6 11:50:56 jovian Ombi[31536]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.MobileNotification[0]
Jul  6 11:50:56 jovian Ombi[31536]:       there are no admins to send a notification for Test, for agent Mobile

**Desktop (please complete the following information):**
 - OS: Debian 10,4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

**Ombi Version (please complete the following information):**
 - Version 3.0.5164
- Media Server: Plex and Kodi

**Additional context**

**Comment by tidusjar** [comment]
This is due to radarr V3, this has been fixed in v4 of ombi
