### ISSUE TITLE
Plex Authentication Loop when attempting to login with no associated ombi user

### ISSUE THREAD

**Issue by vtyr** [tidusjar/Ombi#3658]
**Describe the bug**
Ombi sits in an 'Authenticating' state when a Plex auth attempts to login that isn't the account which didn't originally set Ombi up.

**To Reproduce**
1. Go to Ombi login
2. Click on 'Login with Plex'
3. Login, close Plex auth window

**Expected behavior**
User should login

**Screenshots**
![image](https://user-images.githubusercontent.com/32479561/86896053-4c71b280-c0fd-11ea-9078-76a4ffbdddf8.png)

**Logs (Logs directory where Ombi is located)**
There are no errors relating to this in the Ombi logs, only this:
2020-07-08 09:27:41.647 +01:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
 - OS: Windows 10/Server 2019

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
 - Media Server: Plex

**Additional context**
Server is running on Server 2019 as a service. I've changed from SQLite to MySQL but the issue persists.

**Comment by bakerboy448** [comment]
I'm having the same issue with the plex user ORIGINALLY used for Ombi setup.

Possible API issue?
2020-07-15 00:11:47.491 +00:00 [Error] StatusCode: TooManyRequests, Reason: Too Many Requests, RequestUri: https://plex.tv/api/v2/pins/355142134
2020-07-15 00:11:47.493 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()

[log-20200715.txt](https://github.com/tidusjar/Ombi/files/4922166/log-20200715.txt)

**Comment by scottdfedorov** [comment]
+1 this is happening for me as well.

**Comment by itzyoungen** [comment]
happening to me now..

**Comment by reyreaud-l** [comment]
Happening right now to my install. First login with plex admin works, then after logout plex authentication is not working for any user.
I figured the issue is because I rename the ombi with a custom name. That causes to change the Header X-Plex-Product to change when doing the Plex authentication, and results in a 403 forbiden on the plex pin endpoint.
Removing my custom name fixes the issue as the value of X-Plex-Product is set back to "Ombi" that is accepted by the Plex endpoint.

**Comment by Raketemensch** [comment]
This has been an ongoing issue for ages now. Logging in via Plex just results in an infinite loop of login -> ok -> login -> ok -> login -> ok.

This happens in both Safari and Firefox on MacOS 10.14.6. 

I have not been able to find a workaround for ~1 year now. Deleting cookies has no effect.

**Comment by Thunder-Chief** [comment]
Any progression here?

**Comment by kkelly87** [comment]
Any idea whats going on here? I'm seeing same issue using latest ombi docker image on my synology. This -was- working about a month ago. Suddenly just stopped. I even rebuilt the entire container and started fresh but hit it again today.

**Comment by tidusjar** [comment]
Please can you raise a new issue and fill out the GitHub bug template

**Comment by IMMILDEW** [comment]
Still an issue to this day.
