### ISSUE TITLE
V4 - Scrolling broken on Mobile

### ISSUE THREAD

**Issue by Xiot** [tidusjar/Ombi#3660]
**Describe the bug**
The elements are too big, which is causeing them to extend past their parents which causes more scrollbars

**To Reproduce**
1. Go to app.ombi.io on a mobile sized screen
2. scroll right

**Expected behavior**
No horizontal scrolling

**Screenshots**
![image](https://user-images.githubusercontent.com/1887318/86956133-9fac2b00-c126-11ea-97eb-350ef6afb538.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - Pixel 3

**Ombi Version (please complete the following information):**
 - Version 4

**Additional context**

**Comment by bagobones** [comment]
First thing I also noticed going to v4 on mobile. iOS 13.6, iPhone 7 Safari

**Comment by MokiTa** [comment]
The problem still exists on Ombi v4.0.451.
iOS 13.6. iPhone X
Safari
Ubuntu 16.04.6 LTS x64
Mono 5.8.0.127

**Comment by tidusjar** [comment]
Thanks for the update @MokiTa 
It's difficult to debug mobile safari issues locally! 

I think it's the grow animation that is causing it, I'll see about disabling it on mobile devices

**Comment by tidusjar** [comment]
Just pushed another update, can you please try v4.0.453!

**Comment by damusmf** [comment]
the scrolling catches on the artwork on non iOS devices as well.  Pixel 3 in my case.

**Comment by bagobones** [comment]
4.0.477.0 Even worse on iOS safari? Trying to scroll causes initial rendered content to just scroll up and off the screen and blank screen.

**Comment by HedgeCr33p** [comment]
Mobile browsing is completely broken for me too on V4. shows the discover screen for a split second then goes completely blank.

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, baby, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

**Comment by bagobones** [comment]
That is fair, only ask that when you have time you take a look, most of my users use a smart phone for requests so it is a significant issue.

I might try rolling back to previous docker images to see if I can find a more functional one.. If anyone has suggestions let me know. .Tried to jump back to v3 but it seems like something are a mess, didn't have time to troubleshoot.

**Comment by tidusjar** [comment]
Just pushed a small update that might help

**Comment by HedgeCr33p** [comment]
You're a wizard! That worked for me. Thank you

**Comment by bagobones** [comment]
Seems to have improved things..

**Comment by tidusjar** [comment]
Improved but not fixed?

**Comment by bagobones** [comment]
I haven't had time to test in any detail but testing several screens they are functional now. Alignment and other issues are covered in other tickets... I guess this one can be closed unless others are still seeing issues.
