### ISSUE TITLE
Adding a Movie Error

### ISSUE THREAD

**Issue by kingmartell72** [tidusjar/Ombi#3663]
**Describe the bug**
Ombi sends me a pushbullet notification everytime I add a movie saying an issue has occured. Radarr still gets the request and fufills it. Upon completion, Ombi fails to notify me that the movie is available.

**To Reproduce**
1. Add a movie to the queue

**Expected behavior**
I expect Ombi to push me the request is approved and request is available notifications.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
today at 9:05 PM fail: Ombi.Core.Senders.MovieSender[0]
today at 9:05 PM Error when sending movie to DVR app, added to the request queue
today at 9:05 PM Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'images', line 12, position 5.
today at 9:05 PM at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
today at 9:05 PM at Newtonsoft.Json.JsonTextReader.ReadAsString()
today at 9:05 PM at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
today at 9:05 PM at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
today at 9:05 PM at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
today at 9:05 PM at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
today at 9:05 PM at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
today at 9:05 PM at Ombi.Api.Radarr.RadarrApi.AddMovie(Int32 tmdbId, String title, Int32 year, Int32 qualityId, String rootPath, String apiKey, String baseUrl, Boolean searchNow, String minimumAvailability) in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
today at 9:05 PM at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 160
today at 9:05 PM at Ombi.Core.Senders.MovieSender.Send(MovieRequests model) in C:\projects\requestplex\src\Ombi.Core\Senders\MovieSender.cs:line 57
today at 9:05 PM info: Ombi.Notifications.Agents.MobileNotification[0]
today at 9:05 PM there are no admins to send a notification for Test, for agent Mobile

**Desktop (please complete the following information):**
 - OS: Docker Container

**Ombi Version (please complete the following information):**
 - Version 3.0.4892 
- Media Server Jellyfin

**Additional context**
Everything else works appropriately, I use Sonarr with no issues and the same kind of configuration.

**Comment by tidusjar** [comment]
Radarr V3 is currently not supported in V3. 

I assume that is what you are using?

**Comment by kingmartell72** [comment]
Ah, that would be the issue then. I didn't see anywhere that V3 isn't supported. I already have everything configured so I guess I'll just roll with the issue push for now. On the other hand, for anyone else, V3 Radarr still will receive the request it just throws and issue but it will complete it. Thanks guys.
