### ISSUE TITLE
Slow Ombi

### ISSUE THREAD

**Issue by djbears32** [tidusjar/Ombi#3666]
**Describe the bug**
90% of the time logging into ombi takes my users and myself longer than it should, most of the time it errors out and doesnt work.

**To Reproduce**
Log in as any user anywhere and the issue can be replicated

**Expected behavior**
Ombi will either spin and say authenticating or it will let you in an be slow to load databases

**Screenshots**

**Logs (Logs directory where Ombi is located)**
C:\Ombi

**Desktop (please complete the following information):**
 - OS: Windows Server 2016

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Plex

**Additional context**
I have had a slow Ombi for awhile and its to the point i dont even use it now. That being said i try ever once and awhile to restart the service and overall fix the issue but nothing i have done seems to fix it. I have been researching this issue and see most of the fixes include updating to the lastest version which i am on. Any help would be greatly appreciated, if you need anything else besides the attached log files let me know.

[log-20200713.txt](https://github.com/tidusjar/Ombi/files/4913969/log-20200713.txt)

Also i did see issue https://github.com/tidusjar/Ombi/issues/3356 but was unclear what the intention of that is?

**Comment by tidusjar** [comment]
Looking at your logs it's the issue where the sqlite db is just not made for the amount of use that you currently have. 

The way to resolve this would be to run ombis database on a mysql instance. There's a guide on the wiki for this

**Comment by djbears32** [comment]
@tidusjar That fixed my issue thank you so much!
