### ISSUE TITLE
Unable to send email via smtp

### ISSUE THREAD

**Issue by abendel** [tidusjar/Ombi#3677]
**Describe the bug**
I am unable to send a email. When configuring the email notification settings the test email doesn't send and I did not change any settings from when I had v3. 

**To Reproduce**
1. Go to settings
2. Click on "notifications", "email".

**Expected behavior**
Test/ real email is sent

**Screenshots**
https://imgur.com/a/WyOTK8c
https://imgur.com/a/UYVK57O

**Logs (Logs directory where Ombi is located)**
fail: Ombi.Notifications.GenericEmailProvider[0]                                                                                            
      Exception when attempting to send an email                                                                                            
System.ArgumentException: The domain is invalid. (Parameter 'domain')                                                                       
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)                                                                              
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/vsts/work/1/
s/src/Ombi.Notifications/GenericEmailProvider.cs:line 47                                                                                    
warn: Ombi.Controllers.V1.External.TesterController[0]                                                                                      
      Exception when testing Email Notifications                                                                                            
System.ArgumentException: The domain is invalid. (Parameter 'domain')                                                                       
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)                                                                              
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/vsts/work/1/
s/src/Ombi.Notifications/GenericEmailProvider.cs:line 47                                                                                    
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1
/External/TesterController.cs:line 284  

**Desktop (please complete the following information):**
 - Linux - Docker
**Ombi Version (please complete the following information):**
 - Version -4.0.407.0
-  Plex

**Comment by tidusjar** [comment]
What's your application URL set to? In the customisation settings?

**Comment by abendel** [comment]
It’s a custom url.
Xxx.myqnapcloud:port

**Comment by abendel** [comment]
Its a custom Url....
XXX.XXXXX:3579

It didnt have this issue v3..

**Comment by abendel** [comment]
@tidusjar i deleted the custom application url and it works now...
Anyway to have a custom url and have smtp working?

**Comment by tidusjar** [comment]
Don't use a port and make sure your application URL is a valid domain
