### ISSUE TITLE
GET /api/v1/Search/music/album/info/{foreignAlbumId} doesn't work

### ISSUE THREAD

**Issue by springjools** [tidusjar/Ombi#3680]
**Describe the bug**
GET
/api/v1/Search/music/album/info/{foreignAlbumId}
Returns the album information specified by the foreignAlbumId passed in

**To Reproduce**
curl -X GET "https://server/api/v1/Search/music/album/info/%225af2629b-36de-486c-ad50-a89a28ff050f%22" -H  "accept: application/json" -H  "ApiKey: 

**Expected behavior**
HTTP 200

**Ombi Version (please complete the following information):**
 - Version Ombi 3.0.5164-develop

**Additional context**
Returns http 500: internal server error: "error": "Object reference not set to an instance of an object."

**Comment by tidusjar** [comment]
Need some server logs

**Comment by springjools** [comment]
![image](https://user-images.githubusercontent.com/5911982/88438990-9e5f4b80-ce12-11ea-935f-bb18596fc828.png)
I just tested it with swagger, the method doesn't exist as it is documented. Swagger doesn't produce any logs AFAIK.

**Comment by springjools** [comment]
What exactly do you need the logs from? Have you tested the method yourself and have it working?

⁣Get BlueMail for Android ​

**Comment by tidusjar** [comment]
I am asking for the logs as it's part of the GitHub issue template that you deleted.  There's a reason why the issue template exists and contains this sort of information as it's supposed to speed up my investigation. 

The UI uses this method.

**Comment by springjools** [comment]
https://pastebin.com/gYWzQBQE

**Comment by springjools** [comment]
You are probably aware of the fact that (String foreignAlbumId) is at some point misspelled as "forignAlbumId". It could just be this.
