### ISSUE TITLE
Ombi Causing Emby GUI To Drastically Slow Down 

### ISSUE THREAD

**Issue by mbc0** [tidusjar/Ombi#3687]
**Describe the bug**
Hi,

No actual error but V3 & V4 both cause Emby GUI to slow down to a painful crawl after 12+ hours

If I stop the Ombi Docker then Emby immediately restores its speed.

I suspect this is due to large libraries, possibly mainly due to my Music Library and/or the fact that I have a lot of Motorsport on my Emby Server which Ombi would never be able to recognize.

Is it possible to have selective libraries? it would be a great way to test where the issue is.

Many Thanks!

**To Reproduce**
1. Start Ombi Docker
2. Nothing
3. Nothing
4. There Is No Error Code

**Expected behavior**
Not To Slow Down Emby

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: unRAID

**Ombi Version (please complete the following information):**
 - Version 3 or 4 
- Media Server Emby

**Additional context**

**Comment by plsharevme** [comment]
i also face same problem, if config ombi connect with emby , i emby become very lags , and the cpu usage is 100%,
