### ISSUE TITLE
v4 - Mobile view search too narrow

### ISSUE THREAD

**Issue by Reddax** [tidusjar/Ombi#3690]
**Describe the bug**
The search bar is too slim on the mobile view. When searching and the results pop up, it can only show the image and a few letters of the movie/tv show. I think the search bar needs to be widened for the mobile view.

**To Reproduce**
1. On your phone, use the search bar.

**Expected behavior**
The search bar should show results in full, but only shows the image and first few letters of the movie title

**Screenshots**
![image](https://user-images.githubusercontent.com/1349626/88574103-b238c680-d039-11ea-997e-3341890ca783.png)

**Desktop (please complete the following information):**
Android 10. Samsung S20 ultra & Samsung S10 Chrome & Edge mobile browsers
**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
4.0.414.0
- Media Server [e.g. Plex]
Plex

**Comment by bagobones** [comment]
Same here iOS 13.6 on iPhone 7 Safari

**Comment by damusmf** [comment]
on a Pixel 3, android 10.

Mobile compatibility is the only thing keeping me from v4 full time use.  Most, if not all, of the users i have will be using mobile devices to request things.  The search bar being extremely narrow as well as posters not scaling properly are the biggest things.  Then there is the weird scrolling as stated in https://github.com/tidusjar/Ombi/issues/3660

**Comment by tidusjar** [comment]
Yeah I'm aware there are still mobile issues, I'm slowly working through them

**Comment by bdschuster** [comment]
Not sure if anyone else is seeing this, but on some phones, the search bar isn't even there, in portrait or landscape in Chrome.
![118600311_10158646778761163_5781817935081700972_o](https://user-images.githubusercontent.com/38221778/91781738-adc77680-ebc0-11ea-97c3-38d0a00ee691.jpg)
![118598004_10158646788956163_5929894865828372012_o](https://user-images.githubusercontent.com/38221778/91781739-ae600d00-ebc0-11ea-853e-4504b89bc21d.jpg)

**Comment by bdschuster** [comment]
Not sure if anyone else is seeing this, but on some phones, the search bar isn't even there, in portrait or landscape in Chrome.
![118600311_10158646778761163_5781817935081700972_o](https://user-images.githubusercontent.com/38221778/91781819-e9624080-ebc0-11ea-9e0d-007d2e958182.jpg)
![118598004_10158646788956163_5929894865828372012_o](https://user-images.githubusercontent.com/38221778/91781820-e9624080-ebc0-11ea-812f-f3360709da08.jpg)

**Comment by kkatayama** [comment]
I adding my 2 css customizations here.
**These css customizations work for my use cases but should not be viewed as correct implementations.** 

## Customization 1 - Remove "Sign in with Ombi" (Only "Sign in with Plex")
> I only wanted users to see "Sign in with Plex" option.  This css mod attempts to hide the "Sign in with Ombi" option but does not disable it.  A user could inspect the HTML element and "unhide" the ombi login option, but my hope is "out of sight == out of mind".

Original login: 
![](https://raw.githubusercontent.com/kkatayama/test_project/master/ombi_login_orig.png)

#### css mod
```
button.mat-focus-indicator.ng-tns-c126-0.mat-raised-button.mat-button-base.mat-primary {
    display: none;
}
```

Login now: 
![](https://raw.githubusercontent.com/kkatayama/test_project/master/ombi_login_now.png)


## Customization 2 - Increase "Search Bar" for better mobile viewing
> The current search bar is hard coded to "width: 50%".  This solution is not perfect nor elegant, but it works for now. 

Original mobile search:
 ![](https://raw.githubusercontent.com/kkatayama/test_project/master/ombi_search_orig.png)

#### css mod
```
app-nav-search mat-form-field{
    margin-left: -50%;
    min-width: 200%;
}
```

Mobile search now: 
![](https://raw.githubusercontent.com/kkatayama/test_project/master/ombi_search_now.png)

---

I hope this is useful.  If anyone has a better way, please share :)

**Comment by MrDynamo** [comment]
Any fix for the top nav bar being all messed up?

I'm not very good with css or I would attempt a basic fix

![image](https://user-images.githubusercontent.com/675855/101585666-d91ee600-39a5-11eb-89ae-19532182a0c0.png)
