### ISSUE TITLE
Sync with Plex Server not working after changing to new metadata scanner

### ISSUE THREAD

**Issue by adamskoog** [tidusjar/Ombi#3692]
**Describe the bug**
A few days ago I changed to using Plex's new Metadata Scanner. Since then I'd been noticing that requests in Ombi were not being marked as completed. As an attempt to troubleshoot I spun up a fresh container with no configuration and connected to PMS. I get these 2 lines for every movie in the library:

`2020-07-27 13:47:57.152 -05:00 [Information] The media item "<name>" does not have a ImdbId, searching for ImdbId
2020-07-27 13:47:57.153 -05:00 [Information] The Media item "<name>" does not have a TheMovieDbId, searching for TheMovieDbId`

This could definitely be coincidence and I just noticed it now as I see in this fresh container that I also get the same series of logs from TV Shows as well:
`2020-07-27 13:49:28.465 -05:00 [Information] The Media item "<name>" does not have a TheMovieDbId, searching for TheMovieDbId
2020-07-27 13:49:28.518 -05:00 [Information] Setting Show "<name>" because we have TvDbId, result: True
2020-07-27 13:49:28.519 -05:00 [Information] The media item "<name>" does not have a ImdbId, searching for ImdbId
2020-07-27 13:49:28.519 -05:00 [Information] The show "<name>" has tvdbid but not ImdbId, searching for ImdbId`

**To Reproduce**
1. Create new container - `docker run -d --name=Ombi -e TZ=America/Chicago -p 5000:3579 -v C:\Docker\Ombi\config:/config --restart unless-stopped linuxserver/ombi`
2. Setup connection to PMS
3. Run Full Sync
4. Note logs

**Expected behavior**
Expect sync to run successfully so notifications that requests are fulfilled are sent to users.

**Desktop (please complete the following information):**
 - OS: Windows 10 Update 2004
   - Docker Desktop w/Hyper-V backed, Linux containers

**Ombi Version (please complete the following information):**
 - Version: 3.0.5202
 - Media Server: Plex

**Comment by tidusjar** [comment]
Nope it's 100% that issue since Plex metadata now does not provide me any external information on what the media actually is. 

I am not sure how to go forward with this since Plex keeps all of their information hidden and undocumented, I can only assume the new id for their metadata is for their metadata server which again, I do not have visibility of...

**Comment by tidusjar** [comment]
Just to inform you: https://forums.plex.tv/t/allow-access-to-external-provider-ids-for-media/619090

Also, if you are running radarr and sonarr, in v4 we will now check radarr and sonarr for availability

**Comment by adamskoog** [comment]
I have gave v4 a try and it really seems like there are a few to many things that don't work quite right for the end user experience. It picks up things great from Radarr so that they are shown as available, but my users are having trouble making requests due to issues (scrolling seems really off on mobile, iOS sometimes won't even let you scroll when there are results when looking at the desktop browser). Here's hoping that Plex will make an endpoint to get the matching information from the new Provider.

**Comment by adamskoog** [comment]
Looks like they released the update to beta to support getting this information: https://forums.plex.tv/t/plex-media-server/30447/360
I have it installed and running a metadata refresh if you need someone to test.

**Comment by wptex** [comment]
It doesn't seem to work in Ombi v3.0.5202 still. IMDB & TMDB ID's are there in PMS 1.20.1.3213 now after refreshing all metadata in movies library. Ran recently added and full scan on several occasions in Ombi and it is not marking content Available. I also have Radarr connected and all the movies imported there, and Ombi doesn't mark them Available from that either.

For now, I've removed Auto Approve permissions in Ombi so I don't get requests for existing content automatically sent to Radarr. I have to manually check if it's available first.

**Comment by adamskoog** [comment]
Being this issue is still open, I'm guessing he hasn't implemented an update for this issue yet. Plex has changed where you get the info from, so it's not going to just start working again.
I'm curious if it's planned to be fixed in v4 or if v4 is going to be just the way to go from now on.

**Comment by tidusjar** [comment]
Correct, I have not yet fixed this. I've not had time with my newborn at home.

I'm planning to fix this in V4 only at the

**Comment by sienar1** [comment]
Also having this issue with Ombi. The new plex movie agent solved a lot of metadata issues for me, so I don't plan to go back. The old agent is being moved to legacy and will be deprecated eventually. Glad you're aware and planning to fix. Thanks @tidusjar!

**Comment by ne0ark** [comment]
Yeh I hope this gets resolved soon. I can’t revert back.

**Comment by dotsam** [comment]
@tidusjar Any thoughts on back porting this to v3? The commit that fixes this appears to apply cleanly to the v3.0.5202 tag.

**Comment by wptex** [comment]
@tidusjar +1 for implementing the fixes for IDs/scan in v3 if it's not too much trouble as @dotsam suggests. Sent a little your way in case that helps to motivate.
