### ISSUE TITLE
Movies are not marked available with new plex agent

### ISSUE THREAD

**Issue by Egleu** [tidusjar/Ombi#3699]
**Describe the bug**
After upgrading libraries to the new plex agent Ombi will not mark them as available, even after full sync.

**To Reproduce**
1. Request movie in Ombi
2. Movie appears in Plex movie library
3. Ombi still lists movie as processing

**Expected behavior**
Ombi lists movie as available.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version: 4.0.418.0
- Media Server: Plex

**Comment by tidusjar** [comment]
Delicate #3692
