### ISSUE TITLE
Unable to sort columns on User Management page

### ISSUE THREAD

**Issue by macstainless** [tidusjar/Ombi#3702]
**Describe the bug**
When viewing the User Management page on V4, none of the sort arrows are functional. This applies to all columns, clicking the arrows at the top of the table does nothing.

**To Reproduce**
1. Log in as admin.
2. Navigate to User Management page
3. Click any sort arrow at the top of the table.

**Expected behavior**
Table should sort based on sorting arrow at the top.

**Screenshots**
Not needed.

**Logs (Logs directory where Ombi is located)**
Not needed.

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Ombi Version (please complete the following information):**
 - Version 4.0.424.0
- Media Server Plex

**Additional context**
This DID work on V3 so there looks to be regression on this.

**Comment by vinaykapadia** [comment]
I'm experiencing this too.
