### ISSUE TITLE
Omvi v3+4: "Could not create Plex user since the have no username" for 2-character Plex username

### ISSUE THREAD

**Issue by douginoz** [tidusjar/Ombi#3706]
**Describe the bug**
This happens on Ombi v3 and v4.0.433 and has for a while.  All my Plex users import into Ombi fine except one, "Bu".  
I have 4 "home users" configured in Plex.   Myself (admin), Guest, blah@gmail.com, and "Bu".  

Bu was set up a long time ago.
Viewing Bu's profile in Plex shows 4 "tabs" to view - Shared Libraries, Shared Media, Profile, and Restrictions.  
What's interesting is that neither the Guest user or the blah@gmail.com user has the "Profile" tab in Plex's Users & Sharing view.
His Plex user has a 4-digit pin on it.  Nobody else's has.
Apart from that, and his username being 2 characters, his profile is the same as other home users and the libraries he has access to is the same for all home users and friends.

**To Reproduce**
1. Go to http://192.168.1.xxx:5000/Settings/UserManagement
2. Click on 'Run Importer'
3. Check Ombi log/console
4. See error: 
"info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
 Could not create Plex user since the have no username, PlexUserId: 12656155"
(UserId 12656155 is 'Bu' in plex).

**Expected behavior**
User should get imported into Ombi.

**Logs (Logs directory where Ombi is located)**
info: Ombi.Schedule.Jobs.Plex.PlexUserImporter[0]
      Could not create Plex user since the have no username, PlexUserId: 12656155

**Desktop (please complete the following information):**
 - OS: Linux 20.04 on desktop
Linux 20.04 on Ombi server
Ombi is running in a kvm VM
Plex Web 4.39.1

**Ombi Version (please complete the following information):**
 - Version 4.0.433
- Media Server: Plex Server 1.20.0.3133-fede5bdc7

**Additional context**
This was a problem in Ombi v3 (recent versions at least) and has been around for me for "yonks". I only updated to v4 today (4.0.433).  The startup/migration went flawlessly and everything seems to be working apart from this.  I'm running Ombi from the command line so it's the first time I've noticed the console message appear.

Both "Allow users to login without a password" and "Enable Plex OAuth" are ticked.

**Comment by didyouexpectthat** [comment]
I found on my Ombi v3 that the user who couldn't be added was a Managed User via Plex Home (the acct I use for my living room specifically).

**Comment by tidusjar** [comment]
Ombi cannot import home users as there is no way to login via Plex.tv. 

So it just logs a warning, this is expected
