### ISSUE TITLE
Move notification icon to more intuitive position?

### ISSUE THREAD

**Issue by naq90** [tidusjar/Ombi#371]
Hi there I'm running an into an issue with a lot of my users not immediately finding the bell icon to turn on notifications. Could it be possible to move it to a spot that is more intuitive and also have notifications or something written next to it? I think it would be used more if it was easier for them to spot it right off the bat.

**Comment by csy7550** [comment]
I agree. I'm used to the bell from plexpy etc, but none of my users has found the setting yet..

**Comment by tidusjar** [comment]
Hmmmm... I'm not sure where we can move it to without breaking the flow... Any suggestions?

**Comment by naq90** [comment]
Could it be a drop down option once you click request? Like you click it and then below have something say, "Be notified when the movie is added?"

**Comment by tidusjar** [comment]
@naq90 But that implies that you can enable it for certain requests. What we have in place currently is more of a 'global' flag stating that you will get notified for ALL of your requests

**Comment by naq90** [comment]
Alternatively, could we as administrators decide who gets requests and who doesn't?

**Comment by naq90** [comment]
Another suggestion: What about another creating tab right next to "Movies" and "TV Shows" titled Notifications with a little bell icon? It will be where most users are looking instead of all the way to the right. And users would be able to tell what it is right away instead of having to intuitively know what the bell stands for.

**Comment by SuperPotatoMen** [comment]
@tidusjar we can force from the admin panel everyone get a notification if the end user don't like it he can turn it of in his own setting panel?

**Comment by tidusjar** [comment]
Yeah maybe, after the user management the individual users should have their own settings page
