### ISSUE TITLE
System.InvalidOperationException: No service for type 'Ombi.Store.Context.SettingsContext' has been registered.

### ISSUE THREAD

**Issue by navels** [tidusjar/Ombi#3715]
**Describe the bug**
I've been getting this error trying to start up Ombi used MariaDB instead of SQlite (trying to get past the constant locking errors):

```
Unhandled exception. System.InvalidOperationException: No service for type 'Ombi.Store.Context.SettingsContext' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/vsts/work/1/s/src/Ombi/Program.cs:line 65
```

This is with V3 and the latest V4. Here is my database.json:

```
{
  "OmbiDatabase": {
    "Type": "MariaDB",
    "ConnectionString": "Server=127.0.0.1;Database=Ombi;User=ombi"
  },
  "SettingsDatabase": {
    "Type": "MariaDB",
    "ConnectionString": "Server=127.0.0.1;Database=Ombi;User=ombi"
  },
  "ExternalDatabase": {
    "Type": "MariaDB",
    "ConnectionString": "Server=127.0.0.1;Database=Ombi;User=ombi"
  }
}
```

also tried with the multi-database configuration.

**To Reproduce**
Start Ombi:

```
./Ombi --host http://*.40333 --storage ~/.ombi/
```

**Expected behavior**
Server starts normally.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
See above

**Desktop (please complete the following information):**
 - OS: Linux Gentoo 2.6

**Ombi Version (please complete the following information):**
 - Version 4.0.443

**Additional context**
N/A

**Comment by tidusjar** [comment]
The Type should be `MySql` even if you are using `MariaDB`

**Comment by navels** [comment]
Thanks.  I'd suggest making that more clear on the wiki.
