### ISSUE TITLE
New Landing Page is great!

### ISSUE THREAD

**Issue by DejaVu** [tidusjar/Ombi#372]
Loving this feature!

I would like to keep the landing page after logging in if possible and the ability to add further services into the mix via a URL (also ping it to check its up) and maybe grab the fav.ico (or add a custom image) to say that other services running on the server are available... like Plex.py, uTorrent, CP, Sonarr etc.

Can a custom image be added instead of Plex Requests logo too to customise to the server? Perhaps insert a footer as 'part of Plex Requests'.

This program is going from strength to strength and paired with Plex.Py, I barely need anything else. 
I was hoping also for Server Stats to be added like HTPC Manager has with Disk Space/Load/Transcode Sessions etc. 

All the programs melded together would make an awesome addiction to the Plex experience!

**Comment by tidusjar** [comment]
I'm glad you like it!

>I would like to keep the landing page after logging in if possible

What do you mean by this? So hit landing page after you login? You can do that in the settings

> ability to add further services into the mix via a URL (also ping it to check its up)

What services to add? We do "ping" Plex to see if it's up.

> maybe grab the fav.ico (or add a custom image) to say that other services running on the server are available... like Plex.py, uTorrent, CP, Sonarr etc.

The landing page was more of a user friendly page and not an "admin" dashboard

> Can a custom image be added instead of Plex Requests logo too to customise to the server? 

Yes it can, you just need to replace the image file (Located  [here](https://github.com/tidusjar/PlexRequests.Net/tree/master/PlexRequests.UI/Content/images))

> I was hoping also for Server Stats to be added 

This does deviate away from the original goal of Plex Requests, i'm not saying it will never be done, but something like this currently doesn't fit into the Plex Requests ecosystem.

Thanks for the feedback :)

**Comment by DejaVu** [comment]
What I mean by server stats, not really admin, but something better than this - 
http://itsmyplex.co.uk (this mine) using an outdated 3rd party app made ages ago I had to tweak to get to work.

What I wanted was for this page to be accessible AFTER the user logs in. 

When you land on Plex Requests, only the login page is present. Then once logged in, presented by the landing page. Reason for this, is to allow only those permitted to see the status of the server.

**Comment by tidusjar** [comment]
> When you land on Plex Requests, only the login page is present. Then once logged in, presented by the landing page. Reason for this, is to allow only those permitted to see the status of the server.

You can do that, there is a checkbox in the settings.

Regarding the stats and stuff, I'm still not sure if it fits in with the product. Plus we need to support multiple platforms. Maybe in the future, but not any time soon.

**Comment by whitecollar17** [comment]
@DejaVu Pleas be alert! you're sonarr configuration has no Authentication enabled.

**Comment by LindsayCole** [comment]
@tidusjar Any chance of getting the ability to monitor multiple servers? I have multiple Plex servers (in the same location) and would like the ability for PR to show the status of all of them.

Thanks,

**Comment by tidusjar** [comment]
Not yet,
there is an issue somewhere to add support for this as some people (Including yourself) want to also have Plex Requests search on multiple servers.
It's in the pipleline, but no ETA on when i'll be starting it.


Date: Thu, 7 Jul 2016 08:22:06 -0700

**Comment by LindsayCole** [comment]
@tidusjar Gotcha. Yeah, I don't need it to search multiple servers, as they all have the same shared storage. But good to know it is in the pipeline!

**Comment by LindsayCole** [comment]
Was there an update on this with the closure? :)

**Comment by tidusjar** [comment]
Sorry, accidental close! I was cleaning up! :)

**Comment by SuperPotatoMen** [comment]
planned in the landing page update

**Comment by SuperPotatoMen** [comment]
Guys, we have new idea's for a new landing page. Can you look at this new idea and give some feedback on it? https://github.com/tidusjar/Ombi/issues/1106
