### ISSUE TITLE
iOS app is missing the button for Issue reporting

### ISSUE THREAD

**Issue by silverhack77** [tidusjar/Ombi#3725]
**Describe the bug**
The Ombi mobile app does not have any buttons to report an issue.   The buttons are present and working correctly in the website, but not on the iOS app.

**To Reproduce**
1. Select any title in the request list
2. See that there is no option to report an issue

**Expected behavior**
A button should be present to report an issue, similar to what is show on the website for each title in a the Requests list

**Screenshots**
Mobile app:
![IMG_4947](https://user-images.githubusercontent.com/19563901/90575971-97a5c900-e171-11ea-8d28-6a8c9546b8b2.png)

Web interface:
![IMG_4948](https://user-images.githubusercontent.com/19563901/90575973-9aa0b980-e171-11ea-8725-02fffab98a55.jpeg)

**Logs (Logs directory where Ombi is located)**
(none)

**Desktop (please complete the following information):**
 - OS: iOS / Safari for using the web interface

**Mobile app**
 - OS: iOS 13
 - Ombi mobile app version: 1.7, build 50

**Ombi Version (please complete the following information):**
 - Version: 3.0.5202
- Media Server: Plex

**Additional context**
(none)

**Comment by tidusjar** [comment]
Mobile app is currently being rewrote and will have this feature
