### ISSUE TITLE
4.0.454.0 - The Movie Database Filter not saving and/or working

### ISSUE THREAD

**Issue by shortywz** [tidusjar/Ombi#3727]
**Describe the bug**
Attempting to add 'erotic movie' to the filter, either via text or via the ID (190370) reports success, but there is no visual indicator that it saves, and movies continue to populate in discover with that tag.

On that note, I have show adult content unchecked, and movies tagged with this continue to populate (example: https://www.themoviedb.org/movie/569715-delicious-sisters).

**To Reproduce**
See above

**Expected behavior**
Should give some visual indication of what is currently filtered.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 - Version: 4.0.454.0
- Media Server: Plex

**Comment by tidusjar** [comment]
I've not finished this page in v4 yet
