### ISSUE TITLE
Cannot add plex to media servers

### ISSUE THREAD

**Issue by jordyarm** [tidusjar/Ombi#3729]
Just created installed Ombi following your installation guide. I am struggling to get it to talk with Plex when i test the connection. I have managed to import users, and even when I fill out the user/pass on the add server page, it picks up plex and puts in the correct information, but it fails when I test and thus am not able to import my libraries.

I notice when reading the logs below that it is trying to access files located in "C:\projects" which does not exist. Should these files be within Ombi's install folder?

Your help is most appreciated.

Thanks

**To Reproduce**
```
<blockquote class="imgur-embed-pub" lang="en" data-id="a/J0EDN5d" data-context="false" ><a href="//imgur.com/a/J0EDN5d"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
```
Added server from either initial wizard, or using the user/pass fields.
**Expected behavior**
I would expect the test to pass.

**Logs (Logs directory where Ombi is located)**

> 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) at System.Net.Http.HttpConnection.FillAsync() at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 61
at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 38
at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 97
at Ombi.Controllers.External.TesterController.Plex(PlexServers settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 298
`

**Desktop (please complete the following information):**
 - OS: [Win 10

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server: Plex

**Comment by jordyarm** [comment]
I am using the template. please help

**Comment by PotatoQuality** [comment]
Hi @jordyarm,

Please open a new issue without deleting stuff from the github template.
