### ISSUE TITLE
Search Pane is missing (and left pane as well)

### ISSUE THREAD

**Issue by nogardvfx** [tidusjar/Ombi#3730]
**Describe the bug**
Users cannot see the search pane at the top and the left pane.  Works fine for me, but I am the admin.  Created a temp account as a normal user on Plex and then logged in.  Had to same results as my users.

**To Reproduce**
1. User logs in using Plex credentials.
2. User gets to upcoming movies/tv page
3. Thats it.

**Expected behavior**
Would expect to see Search pane at the top.  Not 100% sure about left pane.  I assume something it supposed to be there.

**Screenshots**
Adding two screenshots.  One as a generic base user, the other as me (admin).
![ombi1](https://user-images.githubusercontent.com/8843229/90989641-39e9f600-e550-11ea-911c-51d552c42493.jpg)
![ombi2](https://user-images.githubusercontent.com/8843229/90989644-3ce4e680-e550-11ea-9c78-d9596de856e4.jpg)

**Logs (Logs directory where Ombi is located)**
[log-20200823.txt](https://github.com/tidusjar/Ombi/files/5115095/log-20200823.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu, IOS, Windows 10

**Ombi Version (please complete the following information):**
 - Version: 4.0.454.0 
- Media Server: Plex

.

**Comment by PotatoQuality** [comment]
Can you add a screenshot of your user management overview?

**Comment by nogardvfx** [comment]
Thanks for getting back to me.  Here is the screenshot.
![ombi3](https://user-images.githubusercontent.com/8843229/91074576-9fda8a00-e5f1-11ea-97a1-1315874eab3b.jpg)

FYI: I have tried combinations of these settings.  Auto approves on.  Super user and Admin user setting.  Movie and Episode limit at 0 and 9999.

Willing to try anything.  Cheers.

**Comment by tidusjar** [comment]
Think this has been fixed with the latest build

**Comment by nogardvfx** [comment]
Awesome!  Will give ti a try.  Thank you very much!

**Comment by nogardvfx** [comment]
Looks good!  Thank you again.
