### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by Novalak** [tidusjar/Ombi#3731]
**Describe the bug**
Multiple users unable to request. Appears to be working in mobile app (Says approved), however, the request is not successful.
Restarting windows service allows the user to request again and be successful
Upon further investigation, "Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'." is the error message in logs. This has happened a number of times

**To Reproduce**
Unknown

**Expected behavior**
Request should be successful

Desktop (please complete the following information):

OS: Windows Server 2016
Mobile OS: Android (Unknown version)
Ombi Version (please complete the following information):

Version: v4.0.449
Media Server: Plex

[log-20200823.txt](https://github.com/tidusjar/Ombi/files/5117331/log-20200823.txt)

**Comment by tidusjar** [comment]
I'd suggest switching to MySQL

Please see the guide and migration in the wiki
