### ISSUE TITLE
Feature suggestion can be seen by all users

### ISSUE THREAD

**Issue by arjohnson15** [tidusjar/Ombi#3734]
**Describe the bug**
I have about 200 users with access to my Ombi page and they will all be able to see and use the "Feature Suggestion" link. They will think it comes to me and you will get flooded with posts I am sure if i move to V4. 

**To Reproduce**
1. Go to 'ombi web interface as general non admin user'
2. Click on 'feature suggestion'
3. takes you to the feature suggestion site

**Expected behavior**
login as a general non admin user and can still see and select the "feature suggestion" link 

**Screenshots**
NA

**Logs (Logs directory where Ombi is located)**
NA

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.454.0
- Media Server Plex

**Comment by tidusjar** [comment]
Solution is to only show this menu option if the logged in user has the Admin role

**Comment by TRaSH-** [comment]
And how would i disable this ?
i can't find it in the settings or it's hidden somewhere
