### ISSUE TITLE
Lidarr does not retain Qualities Profile setting

### ISSUE THREAD

**Issue by Greg2dot0** [tidusjar/Ombi#3735]
**Describe the bug**
When setting up Lidarr, I noticed that the Qualities profile always reverts back to not selected when leaving and coming back into the configuration

**To Reproduce**
1. Go to Settings/Lidarr
2. submit your server info
3. Click Load Profiles
4. Select profile e.g. "Standard"
5. Finish lidarr config
6. Click out to a new page
7. Come back to lidarr config

**Expected behavior**
Setting retains it's selection.

**Screenshots**
[
![Lidarr - Quality Profiles](https://user-images.githubusercontent.com/18699503/91325769-96882380-e791-11ea-965a-1eef52450120.png)
](url)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.454.0
- Media Server - Plex

**Additional context**

**Comment by NightShaman** [comment]
I have the same issue.
