### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Weggy** [tidusjar/Ombi#3737]
**Describe the bug**
My VM ran out of space due to being overloaded by Ombi request. Since this occured (and freeing space) I've been unable to sign in (as have all other users) with the expected usernames and password. We all now receive "Incorrect username or password".

**To Reproduce**
1. Run out of disk space
2. Obersve unable to login to Ombi

**Expected behavior**
Always able to login to Ombi when passing the correct credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/7091582/91485656-1225c580-e8a3-11ea-8122-0c22a68bd70d.png)

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/77YvtpUZ

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server: Plex

**Additional context**
None

**Comment by PotatoQuality** [comment]
Please full-in the full issue template. you deleted multiple things out of it.

**Comment by Weggy** [comment]
> Please full-in the full issue template. you deleted multiple things out of it.

Done

**Comment by tidusjar** [comment]
There are no errors in the logs,  are there any errors in the browser console?

**Comment by Weggy** [comment]
Browser Chrome.

Console...
`lpfulllib.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
include_language @ VM113 lpfulllib.js:1
(anonymous) @ VM113 lpfulllib.js:1
VM51:1 POST http://149.202.17.192:5001/api/v1/token/ 401 (Unauthorized)
(anonymous) @ VM51:1
o.<computed>.y.<computed>.<computed> @ zone.js:1345
m @ zone.js:2969
t.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
t.scheduleTask @ zone.js:401
e.scheduleTask @ zone.js:232
e.scheduleMacroTask @ zone.js:255
h @ zone.js:1114
(anonymous) @ zone.js:3001
P.i.<computed> @ zone.js:1394
(anonymous) @ http.js:1630
t._trySubscribe @ Observable.js:43
t.subscribe @ Observable.js:29
(anonymous) @ subscribeTo.js:21
i @ subscribeToResult.js:11
e._innerSub @ mergeMap.js:74
e._tryNext @ mergeMap.js:68
e._next @ mergeMap.js:51
e.next @ Subscriber.js:54
(anonymous) @ scalar.js:5
t._trySubscribe @ Observable.js:43
t.subscribe @ Observable.js:29
t.call @ mergeMap.js:29
t.subscribe @ Observable.js:24
t.call @ filter.js:15
t.subscribe @ Observable.js:24
t.call @ map.js:18
t.subscribe @ Observable.js:24
(anonymous) @ login.component.ts:117
e.__tryOrUnsub @ Subscriber.js:196
e.next @ Subscriber.js:134
e._next @ Subscriber.js:77
e.next @ Subscriber.js:54
e._next @ map.js:41
e.next @ Subscriber.js:54
e._next @ filter.js:38
e.next @ Subscriber.js:54
e.notifyNext @ mergeMap.js:84
e._next @ InnerSubscriber.js:15
e.next @ Subscriber.js:54
u @ http.js:1534
t.invokeTask @ zone.js:421
onInvokeTask @ core.js:16147
t.invokeTask @ zone.js:420
e.runTask @ zone.js:188
e.invokeTask @ zone.js:496
y @ zone.js:1540
b @ zone.js:1566
load (async)
I @ zone.js:1666
t.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
t.scheduleTask @ zone.js:401
e.scheduleTask @ zone.js:232
e.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
o.<computed>.y.<computed>.<computed> @ zone.js:1345
(anonymous) @ http.js:1618
t._trySubscribe @ Observable.js:43
t.subscribe @ Observable.js:29
(anonymous) @ subscribeTo.js:21
i @ subscribeToResult.js:11
e._innerSub @ mergeMap.js:74
e._tryNext @ mergeMap.js:68
e._next @ mergeMap.js:51
e.next @ Subscriber.js:54
(anonymous) @ scalar.js:5
t._trySubscribe @ Observable.js:43
t.subscribe @ Observable.js:29
t.call @ mergeMap.js:29
t.subscribe @ Observable.js:24
t.call @ filter.js:15
t.subscribe @ Observable.js:24
t.call @ map.js:18
t.subscribe @ Observable.js:24
t.onSubmit @ login.component.ts:110
(anonymous) @ login.component.ngfactory.js:49
handleEvent @ core.js:21673
handleEvent @ core.js:22218
Cg @ core.js:19122
(anonymous) @ core.js:20612
i @ core.js:12621
e.__tryOrUnsub @ Subscriber.js:196
e.next @ Subscriber.js:134
e._next @ Subscriber.js:77
e.next @ Subscriber.js:54
e.next @ Subject.js:47
e.emit @ core.js:12593
e.onSubmit @ forms.js:5253
(anonymous) @ login.component.ngfactory.js:43
handleEvent @ core.js:21673
handleEvent @ core.js:22218
Cg @ core.js:19122
(anonymous) @ core.js:19569
(anonymous) @ platform-browser.js:993
t.invokeTask @ zone.js:421
onInvokeTask @ core.js:16147
t.invokeTask @ zone.js:420
e.runTask @ zone.js:188
e.invokeTask @ zone.js:496
y @ zone.js:1540
b @ zone.js:1566
Show 72 more frames`

**Comment by Weggy** [comment]
If there is no way to recover, is there an easy way to reset?

**Comment by tidusjar** [comment]
There doesn't seem to be much in the way of errors. So are you sure your credentials are correct?

To reset delete the .db files and restart ombi
