### ISSUE TITLE
Only old/unused Plex server is returned from "Load Servers"

### ISSUE THREAD

**Issue by PaarthShah** [tidusjar/Ombi#3739]
**Describe the bug**
New Ombi install. When clicking "Load Servers" for Plex using my Plex login, only an old, unused server is returned, and not the one I actually currently have active.

**To Reproduce**
1. Go to Settings -> Media Server -> Plex
2. Fill in my username/password, click submit then load servers.
3. See old server, but no new server in list. Checking the network tab also confirms that only that one server was returned.

**Expected behavior**
See new server, or both old server and new server.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Firefox on Windows 10.

**Ombi Version (please complete the following information):**
 - Version: ~~3.0.5202~~ 4.0.456.0 (via docker)
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Ombi hosted on this machine worked before, in non-docker. Host network on or off makes no difference.

**Comment by PotatoQuality** [comment]
version 3.0 is not supported anymore.

**Comment by PaarthShah** [comment]
> 
> 
> version 3.0 is not supported anymore.

Ahh. Since it was the "stable" version I assumed it was.

**Comment by PaarthShah** [comment]
Having just updated to 4.0.456.0 (again, via docker) the issue persists.

**Comment by tidusjar** [comment]
The load servers is just returned from the Plex.tv API. I'm not in control of the data
