### ISSUE TITLE
Ombi Molie App

### ISSUE THREAD

**Issue by Weggy** [tidusjar/Ombi#3743]
**Describe the bug**
within the mobile app I'm unable to select filter "Suggestions" and change it to another filter.

**To Reproduce**
1. Go to Andriod mobile Ombi application
2. Click on Suggestions
3. See no menu to change the filter is displayed (as it is in the PC web version)

**Expected behavior**
You should be able to select you filters within the mobile app

**Screenshots**
![image](https://user-images.githubusercontent.com/7091582/91760376-2fbc9d00-ebcb-11ea-8998-16aba05728b0.png)

**Logs (Logs directory where Ombi is located)**
Not applicable

**Desktop (please complete the following information):**
 - OS: Android version 10

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server Plex
- Database Type: Sqlite - Data Source=Ombi.db

**Additional context**
Occurs on the paid for andriod application

**Comment by tidusjar** [comment]
Thanks for the report.

Currently I am rewriting the app and I've already got feature parity and
vast visual improvements.

If you want to join just pm me your email address tidusjar@gmail.com
