### ISSUE TITLE
V4 Custom Donation Link Not Showing

### ISSUE THREAD

**Issue by mmaghometech** [tidusjar/Ombi#3760]
In v3 I used the custom donation successfully to point to self hosted tautulli newsletter.  Feature is no longer working in v4

**Describe the bug**
Custom donation is not showing navigation bar

**To Reproduce**
1. Enable custom page for admin user
2. Go to settings and then custom donation link
3. Input link and description 
4. Submit changes 

**Expected behavior**
Link not showing in navigation bar despite admin role having edit custom page enabled

**Screenshots**

**Logs (Logs directory where Ombi is located)**
No applicable logs for issue

**Desktop (please complete the following information):**
RunningOmbi in docker.  Issue persist viewing on all browsers

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by NightShaman** [comment]
Same here.

**Comment by bdschuster** [comment]
Same

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, baby, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

**Comment by mmaghometech** [comment]
> Hi sorry but there has been no further progress on this yet.
> 
> Please remember that I have a full time (quite demanding) job, a toddler, baby, a wife and a puppy.
> All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.
> 
> Ombi is currently a 1 person development team.
> 
> So if I have not yet got around to this you now know why 😄

No worries! I get it. Just submitted so if you weren’t aware of it. At least the core functionality of the app is working and users can still make requests. And in all honesty I don’t think any of my users really ever look at the letter.
