### ISSUE TITLE
Advanced Options on TV requests missing - V4

### ISSUE THREAD

**Issue by g4m3r7ag** [tidusjar/Ombi#3778]
**Describe the bug**
When logged in as an admin/power user, and viewing a TV Show request, there is no advanced options button to change the root folder, series type etc... like there is for movies. 
**To Reproduce**
1. Login as an admin/power user and navigate to a pending show request
2. Click on details
3. There is no advanced options button or any other way to change the root folder path/series type etc... 

**Expected behavior**
Ability to modify root folder/series type for a pending request before approving the request

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10/Ubuntu 20.04 - Chrome browser latest 
edit: Ombi is running in Docker on an Ubuntu 18.04 host. Access is being done by the above. 

**Ombi Version (please complete the following information):**
 - Version 4.0.489.0
- Media Server Plex
- Database Type: MySQL

**Additional context**
I have asked on the Ombi Discord and got no answer about this. I also posted on Reddit and someone also noted they were seeing the same thing when logging in as admin

https://www.reddit.com/r/Ombi/comments/j2fk4m/root_folder_override_in_v4/

Sonarr Verison: 3.0.3.937
Checkbox for V3 is checked in Ombi settings for Sonarr. 

edit: I do have the advanced options button on Movies requests when logging in as admin.

**Comment by g4m3r7ag** [comment]
@tidusjar Sorry to ping you on this, just wondering if you can replicate this or if I have an edge case that might be resolved by deleting my databases and starting over? Ombi build is up to 4.0.529.0 and it is still present.

**Comment by tidusjar** [comment]
It's on my next list of things to add to the new interface

**Comment by g4m3r7ag** [comment]
Ah my bad then, guess it's an enhancement and not a bug request then lol. Since it was on the movies I assumed it was a bug. Thank you. 

For now, anyone else coming across, I'll toggle the Do Not Search option on Sonarr settings, approve the anime requests, go change the settings in Sonarr and start the search there, then disable the do not search option in Ombi for normal requests since those are more frequent then requests that need modified.

**Comment by g4m3r7ag** [comment]
This was added with the most recent commit.
