### ISSUE TITLE
Ombi Logged Out after like a week

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tidusjar/Ombi#3784]
**Describe the bug**
Sign in to Ombi and after about a week it loges out even if the Remember me option is checked.

**To Reproduce**
1. Sign in to Ombi
2. Wait about a week
3. See that you are logged out

**Expected behavior**
Keep Ombi signed in.

**Comment by tidusjar** [comment]
This is expected behaviour, the remember me will keep your local token valid for 7 days

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> This is expected behaviour, the remember me will keep your local token valid for 7 days

Any way to increase the amount of days? A setting in the admin page perhaps?

**Comment by tidusjar** [comment]
Yeah, can you please raise a feature request for that? https://features.ombi.io/

Thank you
