### ISSUE TITLE
Newsletter listing each movie twice - V4

### ISSUE THREAD

**Issue by g4m3r7ag** [tidusjar/Ombi#3785]
**Describe the bug**
The weekly newsletter is showing each recently added movie twice. 

**To Reproduce**
1. Send newsletter

**Expected behavior**
Only list recently added movies once

**Screenshots**
![Screenshot from 2020-10-03 15-45-51](https://user-images.githubusercontent.com/46694420/95000531-9c8ed280-058f-11eb-8695-3fae135a5237.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ombi is running in docker on Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version 4.0.500.0
- Media Server Plex
- Database Type: MySQL

**Additional context**

**Comment by tctx79** [comment]
Same issue

**Comment by jiznon** [comment]
Also experiencing this issue. v4.0.483.0.

**Comment by rmeaux** [comment]
Awesome. I was coming here to say I also started this issue a while back #3467 and it was closed. I did not know it linked topics like that.

**Comment by douglasparker** [comment]
I also still have this issue.

**Comment by Rickth64** [comment]
Also on v4.0.551.0. I only have Plex connected.

At first I thought it was fixed after upgrading v4.0.550.0 to v4.0.551.0, but only when I use 'Test' it is OK. When using the actual 'Trigger now' (or wait for the cron) all movies are in there twice.

**Comment by d-d** [comment]
Still see this behaviour on  4.0.681.0

**Comment by thickconfusion** [comment]
Experiencing this on 4.0.489.0. FYI, TV is NOT duplicated (not series nor episodes).

**Comment by scottcase** [comment]
Still an issue with version 4.0.728.0

**Comment by tidusjar** [comment]
Pushed an update that should fix this, let me know how you get on (V4)

**Comment by rmeaux** [comment]
Just received my newsletter. I only added one movie this week but it was it duplicated on the email. Waiting for a friends newsletter to come through. Will post results.

**Comment by thickconfusion** [comment]
Based on timing of install I had to manually cue the library scan task and
newsletter task. No duplicates. I'll continue to watch for it. Thanks!

**Comment by thickconfusion** [comment]
Newsletter went out this week on time and did not have duplicates (4.0.731.0). Thanks!

**Comment by g4m3r7ag** [comment]
I got no newsletter this week. It seems to get skipped every couple of
weeks for some reason.

**Comment by bruvv** [comment]
4.0.731.0 fixed it for me too, thanks

**Comment by d-d** [comment]
Fixed. 4.0.739.0 and the newsletter is fine without duplicates

**Comment by bruvv** [comment]
@tidusjar or @g4m3r7ag please close this.
