### ISSUE TITLE
Movies not showing as available

### ISSUE THREAD

**Issue by Shadow229** [tidusjar/Ombi#3790]
**Describe the bug**
Movies are showing as available on the 'Discover' screen, but not when clicked into or searched for. (see images)

**To Reproduce**
1.  Updated Ombi to v4.0.505-ls14 (I was getting no movies showing as available before this)
2.  Manually Run Full Sync
3. To go Discover (here you can see the green bars of available movies)
4. Click onto any available and see 'not available' in the info.

**Expected behavior**
All available movies to show as available and not have the option to re-request available titles

**Screenshots**
![image](https://user-images.githubusercontent.com/55843220/95055576-65cdcf00-06eb-11eb-895e-9f2839331de0.png)

![image](https://user-images.githubusercontent.com/55843220/95055599-70886400-06eb-11eb-88d6-856c194657ef.png)

**Logs (Logs directory where Ombi is located)**
```
info: Ombi.Schedule.Jobs.Ombi.RefreshMetadata[0]
The show Wreck-It Ralph has TheMovieDbId but not ImdbId, searching for ImdbId
fail: Ombi.Api.Api[1000]
StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/82690/external_ids?api_key=00000000000000000000000
```

**Desktop (please complete the following information):**
 - OS: Windows 10 - using Linux Docker

**Ombi Version (please complete the following information):**
 - Version - v4.0.505-ls14
- Media Server - Plex

**Additional context**
Log shows API calls failing as its querying the 'tv' path instead of 'movie' - confirmed API works if I manually check with 'movie' in browser.

**Comment by Shadow229** [comment]
Adding to this, a request goes through find and pushes out to Radarr. When it completed and hits Plex, the request on Ombi never updates either.

**Comment by tidusjar** [comment]
Ok, my main question is, should this movie be available or not for you?

**Comment by Shadow229** [comment]
Hi @tidusjar, I made some progress on this by loading the movies folder independently and that seemed to let it pick them all up. So my solution was: Fresh install, then when connecting the server, load each folder one by one - movies first!

That's stopped the errors in the log querying the 'tv' path on movies and its now showing my available movies. (This movie should show as available yes)

![image](https://user-images.githubusercontent.com/55843220/95191114-32ad3d80-07c8-11eb-8b37-53e79c6e9e6b.png)


For some reason however, its now showing every other movie as 'Pending Approval' - but only in the long view (pics below)

![image](https://user-images.githubusercontent.com/55843220/95190990-042f6280-07c8-11eb-91b9-5e8d1367b4f9.png)

The other view seems to work fine (this detail just doesn't exist on the boxed view) - and once you click into the detail it shows correctly both ways.

not available - not requested
![image](https://user-images.githubusercontent.com/55843220/95191357-90418a00-07c8-11eb-9c7a-11b8711476ce.png)

detail windows shows as expected
![image](https://user-images.githubusercontent.com/55843220/95191395-9f283c80-07c8-11eb-9849-ddd9c6b9957b.png)


Also - when clicking into a movie that's been requested and fulfilled, the option to deny remains persistent even when its picked it back up and is showing as available? Not sure if that's expected behaviour as denying as this point I'm guessing wouldn't do anything?
![image](https://user-images.githubusercontent.com/55843220/95191982-705e9600-07c9-11eb-8eb8-b1fed5c7824c.png)


I understand v4 is under heavy development at the moment - Its looking amazing and these additional points certainly aren't app breaking for a pre-release - but hopefully they are helpful for the dev work going into it.

Thanks!

**Comment by tidusjar** [comment]
Thanks, The new grid view has already been fixed, I only added that yesterday :D Glad people are using the latest features!

Regarding the Deny button, what was the request status for Project Power?

**Comment by Shadow229** [comment]
Nice man - I've pulled the latest and the grids looking awesome! To anyone who finds this isn't fixed - be sure to clear your browser cache to pull the changes through.

Current request status for project power is below:
![image](https://user-images.githubusercontent.com/55843220/95322018-c566de80-0893-11eb-9f6d-6491f869a35a.png)

Under the options here I can delete the request. Going into the details takes me to the screen shot in my last post allowing me to deny it.

**Comment by tidusjar** [comment]
Fixed!

**Comment by newmailaa** [comment]
FG

<a href="https://www.watch4khd.com"><img src="https://github.com/user-attachments/assets/fdad9678-1cc7-4359-b32c-3ba786c61aa5" alt="" /></a>


FG



<a href="https://www.watch4khd.com"><img src="https://github.com/user-attachments/assets/39945430-6900-4d33-9fc8-0281f83d2a2d" alt="" /></a>



cxdsfsdf
