### ISSUE TITLE
Users cannot place requests after running Ombi (Synology docker) for a couple of hours.  Ombi V3 and V4!

### ISSUE THREAD

**Issue by Moerderbeer** [tidusjar/Ombi#3791]
**Describe the bug**
Users cannot place a request after the server runs for +/- 48 hours. They do not get feedback the request is placed. Admin sees no request pending or coming in.

**To Reproduce**
Log in via PlexAuth
1. Select a Movie or Serie
2. Click on + Request
3. No feedback 

**Expected behavior**
User should see a confirmation the request has been placed.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
[log-20201005__.txt](https://github.com/tidusjar/Ombi/files/5326368/log-20201005__.txt)

**Desktop (please complete the following information):**
 - OS: Synology DSM 6.2.3-25426 Update 2
- Docker

**Ombi Version (please complete the following information):**
 - Version 4.0.489.0
- Media Server Plex 4.0.489.0
- Database Type: SQLite

**Additional context**
Turning off the docker, deleting OmbiExternal.db file and starting the docker solves this problem for a couple of hours.

**Comment by tidusjar** [comment]
You are facing the database locking issue, this is an issue when the SQLite DB's get big enough and there is more load on the system. I'd recommend you swapping to using MySQL for a DB provider in ombi
See here:


https://github.com/tidusjar/Ombi/wiki/Migration-procedure-from-SQLite-to-MySQL-or-MariaDB
