### ISSUE TITLE
Movies and TV shows blank - searches do nothing

### ISSUE THREAD

**Issue by Ubergeeksov** [tidusjar/Ombi#3792]
**Describe the bug**
Sometimes Ombi works fine. Sometimes the problem arises. Either situation can last for weeks or months. Problem: when I log on and go to the search page the list of movie suggestions is blank. Likewise, if I click on the TV tab, the suggestions are also blank. If I attempt a search it is as if nothing happens - no results appear. There is no error message. I have read somewhere that deleting the OmbiExternal.db file can resolve this problem. Sometimes it has done, but not always.

**To Reproduce**
See above.

**Expected behavior**
A list of recommended movies or TV shows to appear. Search to display a list of movie or tv shows matching search parameter.

**Screenshots**
<img width="2560" alt="Screenshot 2020-10-05 at 14 09 27" src="https://user-images.githubusercontent.com/14360478/95083899-0be1ff00-0715-11eb-83d7-8476a43f114d.png">

**Logs (Logs directory where Ombi is located)**
[log-20201005.txt](https://github.com/tidusjar/Ombi/files/5327575/log-20201005.txt)

**Desktop (please complete the following information):**
 - OS: OMV 5.5.1.12-1 (Usul) (Linux 4.14.198-odroidxu4)

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server [e.g. Plex]
- Database Type: SQLite

**Additional context**
Although I am now having the problem using OMV5, I also had the problem using OMV5. This makes me think that it is something to do with my set up, but I cannot understand why it then has worked on occasions.

**Comment by PotatoQuality** [comment]
this version isnt supported anymore.

**Comment by Ubergeeksov** [comment]
Thanks.

Sorry to be a pest, and I appreciate that Docker is not supported, but I'm struggling to work out how I can obtain v4 (using Portainer).

Thanks again,

Richard

**Comment by tidusjar** [comment]
Hi @Ubergeeksov v3 is still supported for critical fixes and security updates, but further development is happening in V4, I cannot afford to keep adding features to both versions.

You can use the LSIO container with the `v4-preview` tag
