### ISSUE TITLE
Feature: slack notifications

### ISSUE THREAD

**Issue by DereckR** [tidusjar/Ombi#380]
Hello,

Would like to have an option under slack option that I can choose to include username with request or not. Some user may not want that included in the notification. Also where is the layout or code located so formatting can be changed if I would like?

Thanks,
Dereck

**Comment by tidusjar** [comment]
You want to have the ability to edit the message? Currently this is a string in the source and is compiled into a .dll so that is not possible. But I can add a setting to allow you to use your own message?

**Comment by DereckR** [comment]
That would be great to be able to send your own message as well. Kinda like PlexPy allows. And the ability to like include users name that requested it or just leave it out.

**Comment by SuperPotatoMen** [comment]
planned in the notification update

**Comment by TheDogg** [comment]
Can we also have the option to specify the icon for the slack notification?
