### ISSUE TITLE
V4 Wizard Rework

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#3803]
We need to rework the initial setup wizard to fit more in with the V4 style

### Requirements
Configuring the media server's should be optional, we should be able to skip the Plex and Emby setup.
Creating a local admin should be mandatory (if you can not setup the Plex server)

#### Plex Configuration
We should be able to provide the username and password for the Plex account and then login with that information.
We should also provide the ability to login with Plex's OAuth.
If the user chooses to login with either option, then if we get a successful response we can navigate them to the default page (/discover) as they will now have the auth token

#### Emby Configuration
Note: This is not as advanced as the Plex configuration
We should be able to provide the Emby Hostname, IP Address, API Key and the option to use SSL for connections, all fields are required if the user chooses to configure this.
There should be the option to test the connection before attempting to save it
(tester.service.ts :: embyTest)

#### Local admin
User should provide a username and password (probably a confirm password too). Currently do not worry about password complexity.
This step in the wizard is mandatory if they did not follow the Plex Configuration

Note, all API's are available and the current wizard does work, so everything from a backend perspective should be there, but if backend work is required it would be very quick and easy to add that in

### How to get to this initial state
To get into this state, just ensure you delete the `Ombi.db` , `OmbiExternal.db` and the `OmbiSettings.db` file located in your Ombi folder (where the wwwroot folder is) and then restart the backend. You can then logout of the Web App and should end up back at the initial wizard

**Comment by tidusjar** [comment]
@ben348

**Comment by delbonis** [comment]
> We should also provide the ability to login with Plex's OAuth.

Or more generally, it would be nice to support OAuth2 logins from anywhere for people that use things like Keycloak or Mastodon.

**Comment by tidusjar** [comment]
Currently this is just to rework the frontend to get it feature parity with v3
