### ISSUE TITLE
No movie sinc plex/ombi

### ISSUE THREAD

**Issue by gandalf764** [tidusjar/Ombi#3804]
**Describe the bug**
lately many movies that I have in my plex server are not available on ombi.
therefore the user is able to apply even if the film is already present.
I did manual sync from the settings by selecting the libraries concerned but nothing changes.
thank you

**Screenshots**
<a href="https://postimages.org/" target="_blank"><img src="https://i.postimg.cc/fbNKqdD6/1.png" alt="1"/></a><br/><br/>
<a href="https://postimages.org/" target="_blank"><img src="https://i.postimg.cc/cLYhchyR/3.png" alt="3"/></a><br/><br/>
<a href="https://postimages.org/" target="_blank"><img src="https://i.postimg.cc/KYD56YY4/Schermata-del-2020-10-10-16-56-27.png" alt="Schermata-del-2020-10-10-16-56-27"/></a><br/><br/>

**Comment by tidusjar** [comment]
This is due to Plex recent metadata agent changes. This has been resolved in v4 of ombi, I'd recommend switching as we will be merging to develop soon

**Comment by gandalf764** [comment]
will it be an update like everyone else or will I have to put another copy
of ombi?

Il giorno sab 10 ott 2020 alle ore 17:04 Jamie <notifications@github.com>
ha scritto:

**Comment by tidusjar** [comment]
Completely depends on your setup, if you are using an lsio docker container for example, it will auto update
