### ISSUE TITLE
V4 - All shows in discover have a status of pending approval

### ISSUE THREAD

**Issue by ddevenport** [tidusjar/Ombi#3808]
**Describe the bug**
When in grid view for TV shows under Discover, the status of every show is pending approval. None of these shows have been requested. If you navigate to the TV show's page, or the poster view, they don't show this way.

Note that every show appears this way because the option to hide available content is on. If I turn that off, available shows appear correctly.

**To Reproduce**
1. Go to Discover
2. Click on TV
3. Click on Grid View
4. See issue

**Expected behavior**
Don't show pending approval until it has been requested, and is awaiting to be approved. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22359002/95705518-81683680-0c11-11eb-9ce1-ac7fc1485b7c.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 v2004

**Ombi Version (please complete the following information):**
- Version: Ombi 4.0.530.0
- Media Server: PMS 1.20.2.3402
- Database Type: SQLite

**Additional context**
N/A

**Comment by tidusjar** [comment]
This was a bug in an older version of V4. It states your version is 4.0.530 but your screenshot it's not even loading a backdrop in so I believe it's probably around version 4.0.506

**Comment by tidusjar** [comment]
As you can see this was fixed previously
![image](https://user-images.githubusercontent.com/6642220/95716389-4d1d6600-0c63-11eb-891f-75b2c1d62576.png)

**Comment by ddevenport** [comment]
@tidusjar I downloaded 4.0.530 earlier today, I'm for sure on that version.
![image](https://user-images.githubusercontent.com/22359002/95716670-090d6f80-0c29-11eb-9ffa-6449f724609b.png)

**Comment by tidusjar** [comment]
Can you  clear your browser cache and try again?

**Comment by ddevenport** [comment]
Normally when updating I stop the Ombi service and copy the files from the zip into the folder, overwriting the existing files. For good measure I deleted everything except the .db files and copied everything brand new from the same update file from earlier today. After refreshing it worked. Not sure why overwrite vs deleting and copying would change anything.

**Comment by tidusjar** [comment]
OK cool, glad it's now resolved!
