### ISSUE TITLE
Update v3 to v4

### ISSUE THREAD

**Issue by gandalf764** [tidusjar/Ombi#3812]
I apologize if I write here but I don't know where else to do it.
I would like to upgrade to version 4 of ombi. Is there a way to do this without losing all configuration?
Is there an automatic update script?
I would like detailed instructions to upgrade. thanks a lot

**Comment by rubernck21** [comment]
there are 2 files that you need to keep  Ombi.db and OmbiSettings.db.  all the others you can delete/replace with the new files.  there is 1 other file  mentioned to keep, but the last 2 times i kept that file, I had issues.
