### ISSUE TITLE
Not all files honour base url

### ISSUE THREAD

**Issue by Craig-H** [tidusjar/Ombi#3815]
**Describe the bug**

If you run a reverse proxy that enforces http authentication for all locations except (for example) /ombi, a file tries to load from the root of the domain e.g. https://domainname.com/styles/please-wait.js even though Ombi is configured to use the base URL /ombi. This causes users to be presented with the browsers default http authentication pop-up.

**To Reproduce**

1.Set-up nginx reverse proxy as per Ombi documentaion
2.Amend to set auth_basic "Restricted"; at server level
3.Amend to set auth_basic "off"; at location /ombi
4.Ensure base url set to /ombi in Ombi settings
5.Load ombi homepage
6.http authentication will pop-up

Alternative reproduction:

1.Using Telerik Fiddler, switch on capture
2.Go to Ombi homepage
3.You will see a request to /styles/please-wait.js rather than /ombi/styles/please-wait.js
4.If basic authentication is switched on at server level but switched off at location /ombi level, you will see a http 401 error

**Expected behavior**
Should work as V3, i.e. all URL's are rooted from base url, e.g. /ombi

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Client is Windows 10

**Ombi Version (please complete the following information):**
- Version v4.0.530
- Media Server Plex 1.20.3.3430
- Database Type: SQLite
- Server OS: Ubuntu 20.04
- nginx 1.18.0

**Additional context**

**Comment by Driekes** [comment]
I have the same issue!
