### ISSUE TITLE
Link on https://ombi.io/ points to wrong new issue link

### ISSUE THREAD

**Issue by glensc** [tidusjar/Ombi#3823]
**Describe the bug**

On https://ombi.io/ page, there's block that says

> HAAAALP! I'm stuck!

And that points to:
- https://github.com/tidusjar/Ombi/issues/new

So, I created an issue, and then a mean bot came and closed it:
- https://github.com/tidusjar/Ombi/issues/3821

The link needs to be changed to:
- https://github.com/tidusjar/Ombi/issues/new/choose

**Comment by tidusjar** [comment]
fixed!

**Comment by glensc** [comment]
@tidusjar can you open the previously wrongly closed issue noted in issue body?

**Comment by tidusjar** [comment]
Apologies I misread this issue. The bot closed it because you deleted the bug report template.

**Comment by glensc** [comment]
@tidusjar I did not delete the bug report template. there was no template , to begin with because the bug report link was without a template. 

you can click the links in https://github.com/tidusjar/Ombi/issues/3823 yourself to validate.

yet my bug report https://github.com/tidusjar/Ombi/issues/3821 is valid, but I can not re-open it.
