### ISSUE TITLE
DirectoryNotFoundException when trying to view logs in Ombi v4

### ISSUE THREAD

**Issue by douglasparker** [tidusjar/Ombi#3827]
**Describe the bug**
A DirectoryNotFoundException is thrown when trying to view the logs in Ombi v4. I imagine this is the result of using a different storage path.

In my case:
`--storage=/opt/ombi/config`

**To Reproduce**
1. Set a custom storage path for Ombi.
2. Navigate to Settings -> System -> Logs
3. At this point you will see a blank page. View the error in the logs.

**Expected behavior**
Ombi v4 should attempt to open the logs using the defined storage path.

**Screenshots**
![HCLpVDEAdT](https://user-images.githubusercontent.com/18235822/96916295-3691be80-145c-11eb-9ca2-1f275071927c.png)

**Logs (Logs directory where Ombi is located)**
[log-20201022.txt](https://github.com/tidusjar/Ombi/files/5425057/log-20201022.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version 4.0.530.0
- Media Server: Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
n/a

**Comment by douglasparker** [comment]
This seems to be a duplicate of issue #3733; although I am not using docker.

**Comment by tidusjar** [comment]
Fixed!
