### ISSUE TITLE
OMBI V4 no notification!

### ISSUE THREAD

**Issue by gandalf764** [tidusjar/Ombi#3828]
**Describe the bug**
I am not receiving any notification for any event.
I set mail setting correctly (the test works)
I have set a telegram channel (the test works)
when a user adds a new request, I do not receive any notification either on the email or on the telegram.
In the V3 I had no problems

**To Reproduce**
1. setup mail notification
2. on new request no notification arrive!

**Expected behavior**
when a user makes a new request I would like to receive a message either on telegram or in the email

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Ombi Version 4.0.533.0
- Media Server: plex (lastest version)
![Schermata del 2020-10-23 23-45-59](https://user-images.githubusercontent.com/41706025/97056739-fa5c7c00-1589-11eb-8450-b61275386b52.png)

**Additional context**

**Comment by tidusjar** [comment]
Need some logs when someone requests a movie, also, do they have the auto approve role?

**Comment by gandalf764** [comment]
yes the auto-approve movie rule is active. I noticed that if I disable it,
notifications arrive regularly. in version v3 the notifications arrived
even with this rule applied. thank you


Il sab 24 ott 2020, 09:23 Jamie <notifications@github.com> ha scritto:

**Comment by tidusjar** [comment]
Nope this behaviour has not changed
