### ISSUE TITLE
Unable to set Movie DB keywords 4.0

### ISSUE THREAD

**Issue by pvtcblount** [tidusjar/Ombi#3831]
**Describe the bug**
unable to set keywords under movie database settings, you can type but it doesn't save.

**To Reproduce**
1. Go to settings page for movie database
2. attempt to save anything

**Expected behavior**
keywords can be set so we can hide things

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10 & Windows Server 2019 Google Chrome and internet Explorer

**Ombi Version (please complete the following information):**
 - Version 4.0
- Media Server Plex
- Database Type: MySQL

**Additional context**

**Comment by tidusjar** [comment]
This page has yet to be reworked
