### ISSUE TITLE
After upgrading to latest v3, Ombi is unusable

### ISSUE THREAD

**Issue by BRTPOB** [tidusjar/Ombi#3835]
**Describe the bug**
I was previously on build/version 5202 and just upgraded to the latest v3 version. After doing so, Search, Requests, Settings, and everything outside of the main headers does not display any longer.

**To Reproduce**
1. Start Ombi
2. Login
3. Observe
4. Click on Settings
5. Observe

**Expected behavior**
Expected information regarding suggested movies/TV shows or any other actual information to display.

**Screenshots**
![image](https://user-images.githubusercontent.com/7201028/97311099-e8b1f780-185b-11eb-804c-7a50e0fa9177.png)
This is what Settings looks like.

**Logs (Logs directory where Ombi is located)**
[log-20201027.txt](https://github.com/tidusjar/Ombi/files/5445756/log-20201027.txt)
Attached log

**Desktop (please complete the following information):**
 - OS: Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.5218
- Media Server Plex
- Database Type: SQLite

**Comment by jorgentol** [comment]
Just want to say I too am experiencing this issue. Running the docker image linuxserver/ombi.

**Comment by BRTPOB** [comment]
Adding an addendum: using the latest Development build shows the exact same behaviour, so it's not just 3.0 not working.

**Comment by mhbates** [comment]
Same issue here.

**Comment by mhbates** [comment]
Rolling back to 3.0.5164 fixes it.

**Comment by w1kk1** [comment]
same issue for me

**Comment by tidusjar** [comment]
Log out and then log back in.

**Comment by tidusjar** [comment]
Fixed in the latest version
