### ISSUE TITLE
QNAP NAS and Apache for install

### ISSUE THREAD

**Issue by WeirDave** [tidusjar/Ombi#3838]
**Describe the bug**
Don't know which Apache to get for my installation on a QNAP NAS.

**To Reproduce**
N/A

**Expected behavior**
Link to correct Apache version on https://www.qnapclub.eu/en/qpkg/1002#

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158] Ombi4_4.0.533_x86_64
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Do not use the qpkg from that "maintainer". Use the docket container

**Comment by WeirDave** [comment]
Thank you for responding! I'm sorry forgive me, but might you further explain what the "docket container" is?

**Comment by tidusjar** [comment]
Phone autocomplete doesn't help. Apologies, I meant to say docker container.

**Comment by WeirDave** [comment]
Ok no problem. I have not been running Docker container on my NAS. Will I need it going forward with your program? Also if I install it to use your program will it talk okay to my Plex "not" in a container?

**Comment by tidusjar** [comment]
That's what I would recommend, you can use that qnap package, but the maintainer is very shady and I do not endorse you using it.

Ombi does not care about how things are running so it will talk to Plex with no issues

**Comment by WeirDave** [comment]
Thanks! I will investigate how to set that up. Hoping it's not complicated...
