### ISSUE TITLE
Invite email sent without subdomain configured

### ISSUE THREAD

**Issue by mapleleafs89** [tidusjar/Ombi#3839]
**Describe the bug**
Invite link is send with incorrect link.

**To Reproduce**
1. Setup nginx reverse proxy with subdomain https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples#nginx-with-subdomain
2. Send a user an invite to ombi
3. The invite uses the main domain, but subdomain is left out. 
4. Link in email looks like https://domain.com/token?token=

**Expected behavior**
Expected link in email to be https://subdomain.domain.com

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: docker on centos

**Ombi Version (please complete the following information):**
- Version 3.0.5202
- Media Server Plex
- Database Type: whatever the docker image ships with :)

**Comment by tidusjar** [comment]
Set your Application Url in the settings and it will use that.

Configuration > Customization
