### ISSUE TITLE
Request: Ask if users want to add a note before submitting the issue

### ISSUE THREAD

**Issue by RacerBas** [tidusjar/Ombi#384]
So I had some of my family members test this out and so far they only had one issue.

With TV shows the subtitles are incorrect quite often, when they report this they find themselves unable to specify which episode is the one with the issue. Now I do know you have the option to add notes to your issue but that's too many clicks away for them. They have to create the issue, then go to the issue itself, then click details and only then can they add a note saying which episode has the issue.

What I would like to see is the ability to either add the note immediately when submitting the issue, or having the option to select which episode from which season has the issue they specified.

Thanks in advance!

**Comment by tidusjar** [comment]
Why can't they just Report Issues > Other and then put it in there?

**Comment by RacerBas** [comment]
Well let's say for instance Episode 4 of season 7 has no subtitles. The user looks for the show, clicks no subtitles and they submit it. This creates an issue that says that show X has no subtitle, however I have no clue wether this is in S01E01 or S07E04.

**Comment by tidusjar** [comment]
Yeah I agree, we do have some limitations around TV Shows currently. I plan to hopefully remove these limitations.

But for now as a workaround, can't they select Issue> Other and put in the season and episode?

**Comment by RacerBas** [comment]
That's fine for now yes.

It's not really an urgent matter but more something that improves the experience and usability for the user.

Off-topic:
They had no issues at all with the movies section :+1:

**Comment by Collisionc** [comment]
IMO, it would be significantly more useful to me if "Other" were the default behavior, especially with tv shows where it's generally one or two episodes that are screwed up and telling me that a show with 10 seasons has wrong audio is completely useless.

**Comment by RacerBas** [comment]
IMO it would be better to just show up a menu in which you can select the episodes that have the specific issue rather than showing a text box.
