### ISSUE TITLE
Tags for the "latest" release on Ombi V4

### ISSUE THREAD

**Issue by Kakogod** [tidusjar/Ombi#3841]
**Describe the bug**
First time raising an issue so I might make mistakes on how to create one.

I created a small script for updater that worked well for OmbiV3 which automatically backups the original files, download the latest release specific for Linux OS using the API link/page. However switching to V4 that makes it not possible as the latest releases are not tagged as `latest` .

**To Reproduce**
The API link i use for V3 "https://api.github.com/repos/tidusjar/Ombi/releases/latest" shows the latest release for different assets. 

However accessing the same link for V4 "https://api.github.com/repos/tidusjar/Ombi.Releases/releases/latest" results in a empty page.

**Expected behavior**
I would expect it to have similar content (tag latest) for the V4 link that i provided so that script can continue working and downloading the release using the latest tag.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version Related to any V4 version

- Database Type: SQLite

**Comment by tidusjar** [comment]
https://api.github.com/repos/tidusjar/Ombi.Releases/releases is the correct endpoint

If you look at the docs the `/latest` endpoint will not return pre-releases
https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-latest-release
