### ISSUE TITLE
V4 - Albums option missing from Discover tab

### ISSUE THREAD

**Issue by jnines** [tidusjar/Ombi#3842]
**Describe the bug**
Even when properly connected to Lidarr, there is no Albums section on the Discover tab, despite it existing in the Requests tab.  I originally though it might be an issue with the docker image (linuxserver.io), but a standard install on an Ubuntu VM shows the same issue.

**To Reproduce**
1. Connect to and enable Lidarr
2. Click on Discover tab

**Expected behavior**
Have the ability for users to discover/request music.

**Screenshots**
![Discover](https://i.imgur.com/vJ9TUcJ.jpg)
![Requests](https://i.imgur.com/CfJJeXc.jpg)
![Settings](https://i.imgur.com/J9wStcs.jpg)

**Desktop (please complete the following information):**
 - OS: Arch/Firefox, but also tried on Win10VM with Chrome

**Ombi Version (please complete the following information):**
 - Version: 4.0.551.0 (linuxserver/ombi)
- Media Server: Plex
- Database Type: SQLite

**Comment by Strychnide4602** [comment]
Same issue here running on non-VM Windows 10. Users are unable to search for music.

**Comment by electronicbard** [comment]
Same issue running in docker on UNRAID

**Comment by tidusjar** [comment]
This is not actually an issue. 

The reason it doesn't appear is I cannot find any APIs that fit into the same categories e.g. popular

**Comment by hirenshah** [comment]
I'm running v4 on Docker and see Albums under Requests but nowhere else.  I have Lidarr disabled so surely it shouldn't be visible under the Requests section?
