### ISSUE TITLE
Item title hidden behind poster

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [tidusjar/Ombi#3843]
**Describe the bug**
Item title hidden behind poster.

**To Reproduce**
1. Click on an item

**Expected behavior**
For the item title to be fully visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/15848969/97791615-b5989c80-1baa-11eb-90b1-b489c203fce7.png)

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - OS: Windows for client

**Ombi Version (please complete the following information):**
 - Version: 4.0.551.0
- Media Server: n/a
- Database Type: sqlite

**Comment by thorrrr** [comment]
Same issue

**Comment by tidusjar** [comment]
should be resolved in the latest version

**Comment by thorrrr** [comment]
Still got the same issue on version 4.0.975.0
