### ISSUE TITLE
400 thrown on login

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [tidusjar/Ombi#3845]
**Describe the bug**
400 is thrown when login page is requesting requirePassword and a base url is used.

**To Reproduce**
1. Use a base URL and nginx
2. Try to login

**Expected behavior**
To login successfully

**Desktop (please complete the following information):**
 - OS: Linux

**Ombi Version (please complete the following information):**
 - Version 4.0.551.0

**Additional context**
Nginx config:
```
location /ombi {
proxy_pass http://127.0.0.1:5000;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_redirect http://127.0.0.1:5000 https://$host;
}
```

Request sent to endpoint `/ombi/api/v1/token/requirePassword` as expected.

**Comment by tidusjar** [comment]
Did you restart ombi after setting the base URL?

**Comment by ThatNerdyPikachu** [comment]
Yes.

I believe this may have something to do with this part:
```
proxy_http_version 1.1; 
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection "upgrade";
```

as removing them from a simpler config with a subdomain work fine with the API endpoints, but not when they are added.
