### ISSUE TITLE
Version 4.0.546.0 clears all menu items

### ISSUE THREAD

**Issue by PearsonFlyer** [tidusjar/Ombi#3846]
**Describe the bug**
Upgrading from .545 to .546 or any version higher than .545 makes every menu item (requests, settings, users, issues) empty. Rolling back to 545 brings all those menu items back again.

**To Reproduce**
1. Stop Ombi service
2. Update to .546 or higher
3. Restart Ombi service
4. Navigate to any menu and see it blank

**Expected behavior**
I expect the same requests, users, etc. that existed previously to appear.

**Screenshots**
Requests, version .545: https://imgur.com/Eq10ljs
Requests, version .546: https://imgur.com/EcDzBwO
Settings, version .545: https://imgur.com/STPZhMS
Settings, version .546: https://imgur.com/BNq4seZ

**Logs (Logs directory where Ombi is located)**
The data seems to still be there, so logs would not be helpful in this situation.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.546+
- Media Server Plex
- Database Type: SQLite

**Additional context**
I have tried all versions between .546 and .551 and all have the same issue.

**Comment by ne0ark** [comment]
I can't even reinstall version 4 it brings me to the username and password page. But there is none set on a new installation.

**Comment by tidusjar** [comment]
Logout and back in to fix the issue

**Comment by evanrich** [comment]
@tidusjar  Sorry but this still isn't fixed

![image](https://user-images.githubusercontent.com/518320/98053236-f3850300-1dec-11eb-8072-72f1ffc3a7ce.png)


4.0.596, no menu options exist besides logout.  Tried logging out and back in with the same admin account that always worked.

**Comment by GhostPyxel** [comment]
Clearing cache doesn't work aswell, I got the same behavior here with guests and admin accounts.
(Love the idea of a profile picture btw)

**Comment by evanrich** [comment]
@GhostPyxel  thats why i tried incognito...no cache ;)

**Comment by evanrich** [comment]
Strange, without touching it now it works again, same incognito browser

**Comment by GhostPyxel** [comment]
Oh right, it passed over me sorry lmao
Still not working on my side though, not sure how you unlocked the situation

**Comment by tidusjar** [comment]
update to latest version
