### ISSUE TITLE
Windows V4 MySql update issue

### ISSUE THREAD

**Issue by jendru214** [tidusjar/Ombi#3852]
**Describe the bug**
I have always updated ombi on windows by copy paste and replace the files in ombi catalog and run it again. Recently I have switched to mysql for better performance and less issues on version 4.0.529.0 and now when trying to update with replacing the files to the newest one I get empty ombi. It will start from a backup/copy again but not the new version. I have checked the database.json file is there and is configured correctly.

**To Reproduce**
I guess install 4.0.529.0 with MariaDB (even give the user full database privileges) and try to update with replacing the files.

**Expected behavior**
I expected Ombi to run like it previously did on sqlite

**Screenshots**
Settings page on the old version:
![image](https://user-images.githubusercontent.com/67014283/98130321-69a36b80-1eba-11eb-9877-9e4c396d60e6.png)
Settings on the new updated version:
![image](https://user-images.githubusercontent.com/67014283/98130449-8e97de80-1eba-11eb-9b60-ab0af98e4ceb.png)
Also other pages look like this too
![image](https://user-images.githubusercontent.com/67014283/98130544-a7a08f80-1eba-11eb-87f8-2f108f05fef0.png)
Also the console window keeps spitting those
![image](https://user-images.githubusercontent.com/67014283/98130735-ddde0f00-1eba-11eb-937a-8036e7d4535a.png)

**Logs (Logs directory where Ombi is located)**
[console log.txt](https://github.com/tidusjar/Ombi/files/5488761/console.log.txt)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019

**Ombi Version (please complete the following information):**
 - Version above in description
- Media Server Plex with Plex auth turned on
- Database Type: mysql

**Additional context**

**Comment by jendru214** [comment]
And for some reason it seems to work after I left it running for some time in edge. I guess its a cookies issue. Can we have something that after update Ombi would purge all remembered browser stuff?

**Comment by vsc55** [comment]
Hi @jendru214,
If it is a matter of cookies and cache, something similar happened to me.
One solution is to log out and log back in. with this the problem of cookies can be corrected.
