### ISSUE TITLE
Broken Dropdown: Report Issue Category

### ISSUE THREAD

**Issue by gorgarp** [tidusjar/Ombi#3854]
**Describe the bug**
Report issue on movie > select category. Unresponsive and unable to select any categories.

**To Reproduce**
See above

**Expected behavior**
The dropdown for category show categories.

**Desktop (please complete the following information):**
 - OS: Windows 10, Edge

**Ombi Version (please complete the following information):**
 - Version 4.0.632
- Media Server Plex
- Database Type: MySQL

Open to discuss as needed but should be pretty straight forward.

**Comment by tidusjar** [comment]
You need to add some categories in the settings.
