### ISSUE TITLE
v4 - unable to bulk edit users

### ISSUE THREAD

**Issue by CanonCan** [tidusjar/Ombi#3857]
**Describe the bug**
a definite coding issue found when trying to bulk edit users: a transparent bulk edit window slides in place overlapping user information and is hard to read. clicking just hides the window see attached screenshot

**To Reproduce**
1. Go to User Management
2. Click on two or more users and click bulk edit

**Expected behavior**
A clear and concise description of what you expected to happen. expect a proper bulk edit screen to pop up

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

Firefox, Chrome and Safari, iOS (chrome) doesnt render user management screen properly

**Ombi Version (please complete the following information):**
 - Version all versions of 4 upto and including 
4.0.643.0
running the linuxserver/ombi:preview in a docker on unraid
![v4 bulk edit](https://user-images.githubusercontent.com/31594024/98334986-57602500-1fc1-11eb-97b7-eb090276fde5.png)

**Additional context**

**Comment by tidusjar** [comment]
Fixed
