### ISSUE TITLE
Feature Request: Logo for home page icon in iOS/Android

### ISSUE THREAD

**Issue by theg1nger** [tidusjar/Ombi#386]
Landing page is awesome! I saw that you can change the logo in this ticket. 

https://github.com/tidusjar/PlexRequests.Net/issues/372

What I would love is having the plexrequest logo as an icon for saved app icons like in these instructions:
http://www.kylejlarson.com/blog/adding-an-icon-for-iphone-ipad-android-to-your-website/

Also, it would be great if we could upload our own if we didn't want to use the default logo. Right now when saving the page to the home screen its just a screenshot of the page.

Thanks,
-W

**Comment by tidusjar** [comment]
Thanks,

I'll add them to the list :)
