### ISSUE TITLE
IMDB Links are broken

### ISSUE THREAD

**Issue by grdnkln** [tidusjar/Ombi#3863]
**Describe the bug**

When I click on movie titles in the "TV Shows" section, it links to a broken IMDB page.
The link is e.g. https://www.imdb.com/title/http://www.imdb.com/title/tt8111088//    when the correct link would be http://www.imdb.com/title/tt8111088/

This doesn't happen for the "Movies" section because that section is using TheMovieDatabase instead of IMDB.

**To Reproduce**
Open Ombi. Go to the "TV Shows" tab, click on the title of any movie

**Expected behavior**
Navigate to the IMDB TV show webpage

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
Windows 10 2004

**Ombi Version (please complete the following information):**
 - Version 3.0.5223

**Comment by natephysics** [comment]
I have the same issue.

**Comment by uberguy16** [comment]
Same for me as well.

**Comment by tidusjar** [comment]
Please use v4

**Comment by uberguy16** [comment]
Much better. Thank you!
