### ISSUE TITLE
Gravatar not being displayed

### ISSUE THREAD

**Issue by adamskoog** [tidusjar/Ombi#3864]
**Describe the bug**
The gravatar that is linked to my email address is not displayed in the new profile area on the side bar. Just shows a default Ombi logo.

**Expected behavior**
The image displayed should show my gravatar linked to my email address as mentioned in the New section. Link to gravatar pic: http://www.gravatar.com/avatar/92cb57f453f1b5e60f4620b841428f02

**Screenshots**
![image](https://user-images.githubusercontent.com/1199962/98851851-74ab4e00-241c-11eb-8426-6017907cdfba.png)

**Desktop:**
 - OS: Docker, hotio/ombi:testing
 - Running Nginx in a reverse proxy as well, Ombi is at the root of my domain.

**Ombi Version:**
 - Version 4.0.681.0
- Media Server [e.g. Plex]
- Database Type: SQLite

**Comment by tidusjar** [comment]
Is your email address correct against your user in ombi?

**Comment by adamskoog** [comment]
Yes, it is the email I used to generate the hash above for the gravatar link:
![image](https://user-images.githubusercontent.com/1199962/98855268-585de000-2421-11eb-9d10-f3c5bb3b3a7b.png)

**Comment by mrjohnpoz** [comment]
yeah just updated to latest 4.0.698 and it was working..  Now doesn't seem to be..

**Comment by CanonCan** [comment]
I am having same issue I thought it was becasue i enabled Plex OAuth but disabled that and still not working it was for a while and prior to latest update 4.0.698.0 and no longer working

Gravatar and Ombi using same email address

**Comment by mrjohnpoz** [comment]
Yup that fixed it..

**Comment by adamskoog** [comment]
Indeed, mine is working now as well.

**Comment by CanonCan** [comment]
Thanks working now once again! Thanks for all your hard work
