### ISSUE TITLE
Browser Console gives web socket errors accessing hubs/notification

### ISSUE THREAD

**Issue by adamskoog** [tidusjar/Ombi#3865]
**Describe the bug**
Seeing these errors in the logs of the web console (Edge Chromium and Chrome give the below) when accessing the application:
![image](https://user-images.githubusercontent.com/1199962/98852783-cdc7b180-241d-11eb-9037-1f2f20668171.png)
Firefox gives the following:
![image](https://user-images.githubusercontent.com/1199962/98854860-bdfd9c80-2420-11eb-8298-941f6768ec5f.png)

**Expected behavior**
I assume this is somehow related to UI updates. I'm not seeing any issues with the application visibly (found this trying to troubleshoot something else), but seemed like something worth pointing out in case it indicates some issue. I'm guessing server logs won't be terribly helpful, since it appears to never get that far, but would happy to provide if they would help.

**Screenshots**
Screen shot of nginx proxy config for Ombi:
![image](https://user-images.githubusercontent.com/1199962/98852985-1aab8800-241e-11eb-9f90-1113c47737b3.png)

**Desktop:**
 - OS: Docker Desktop, Windows
 - Ombi Container: hotio/ombi:testing
 - Nginx Container: linuxserver/letsencrypt

**Ombi Version:**
 - Version 4.0.681.0
- Database Type: SQLite

**Comment by tidusjar** [comment]
Yes those are to do with updates for the UI coming from the backend over a websocket. You need to allow websocket connections through your proxy.

**Comment by adamskoog** [comment]
Ahh, good to know, it was an easy fix. I'll post the updated nginx config that I have in case others have the same.

```
location / {
	proxy_pass http://192.168.1.111:5000;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Host $server_name;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_read_timeout 90;
	
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
}
```

**Comment by adamskoog** [comment]
I added the above, and the application was working fine. Now this morning I am unable to log in to the application without removing lines added to the proxy. This is using the ombi login, if I use the plex login, it opens a new window and simply reloads asking if I want to use the Ombi or Plex sign in.
![image](https://user-images.githubusercontent.com/1199962/98938801-1464ec80-24ae-11eb-9dfc-d111a8dbdeaa.png)

**Comment by adamskoog** [comment]
Well, apparently some of the config was still wrong (even getting the info from nginx's site). The correct config is below (grabbed from the Radarr wiki):
```
location / {
	proxy_pass http://<applicationhost>:5000;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Host $server_name;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_read_timeout 90;
	
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection $http_connection;
}
```
