### ISSUE TITLE
Ombi won't start after version v4.0.681

### ISSUE THREAD

**Issue by douglasparker** [tidusjar/Ombi#3887]
**Describe the bug**
The last working version of Ombi is v4.0.681. Ombi v4.0.698 and later results in Ombi not being able to start.

**Logs (Logs directory where Ombi is located)**
[log-20201124.txt](https://github.com/tidusjar/Ombi/files/5592558/log-20201124.txt)

**Comment by NSempsrott** [comment]
This might be a useless comment of something you've already tried, but I had the same issue. I ended up having to totally wipe my Ombi directory, put the newest release in the folder, then copy Ombi.db OmbiExternal.db and OmbiSettings.db back in. Obviously backup the whole folder before trying that so you don't lose anything. Might be a stupid suggestion you've already tried, but figured I'd say it anyways just in case.

**Comment by douglasparker** [comment]
> This might be a useless comment of something you've already tried, but I had the same issue. I ended up having to totally wipe my Ombi directory, put the newest release in the folder, then copy Ombi.db OmbiExternal.db and OmbiSettings.db back in. Obviously backup the whole folder before trying that so you don't lose anything. Might be a stupid suggestion you've already tried, but figured I'd say it anyways just in case.

I will give this a try and then report back.

Thank you for the suggestion. 😁

**Comment by tidusjar** [comment]
Yes, you cannot use the usual overwrite everything in the folder method.
I've changed the way ombi is packed.

**Comment by douglasparker** [comment]
> > This might be a useless comment of something you've already tried, but I had the same issue. I ended up having to totally wipe my Ombi directory, put the newest release in the folder, then copy Ombi.db OmbiExternal.db and OmbiSettings.db back in. Obviously backup the whole folder before trying that so you don't lose anything. Might be a stupid suggestion you've already tried, but figured I'd say it anyways just in case.
> 
> I will give this a try and then report back.
> 
> Thank you for the suggestion. 😁

This ended up being the solution! Thanks for pointing this out to me.

It's actually [mentioned](https://github.com/tidusjar/Ombi/wiki/Update-Settings#manual-updates) in the Wiki.
