### ISSUE TITLE
Newly implemented 2FA makes login fails on V3

### ISSUE THREAD

**Issue by alfablac** [tidusjar/Ombi#3894]
**Describe the bug**
Newly Plex implementation of 2FA makes login fails on V3

**To Reproduce**
1. Go to login page
2. Put the valid credentials
3. Click Login
4. Popups appear "Incorrect username and login"

**Expected behavior**
Should login

**Logs (Logs directory where Ombi is located)**
The request on the logs fail. I'm inclined to believe the 2FA would work differently than normal login
[Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json

**Ombi Version (please complete the following information):**
 - 3.0.4892-master
- Plex

**Comment by palmfighter** [comment]
Hi,

can you try by adding the 2FA code behind your password, I heard from the developer this should allow you to login.

**Comment by alfablac** [comment]
@palmfighter pass2FAcode is what worked for me. Thanks!

**Comment by Fireant456** [comment]
Not sure if this works in the Media Server config menu. Can anyone confirm? @palmfighter

**Comment by palmfighter** [comment]
Sorry I am no longer on v3.

**Comment by sifotes** [comment]
@Fireant456 Yes, works fine. 
@tidusjar Might be worth adding this to GUI and to the docs (if it's not already there).
