### ISSUE TITLE
Plex 2FA support prevents login to Ombi Website

### ISSUE THREAD

**Issue by Fribb** [tidusjar/Ombi#3908]
**Describe the bug**
After Plex has added [2FA to its login authentication](https://support.plex.tv/articles/two-factor-authentication/) Ombi is incapable to login the user on the website. Error Message is "Wrong username or Password"

**To Reproduce**
1. Login to Ombi without 2FA activated -> Works
2. Activate 2FA in your Plex Server
3. Login to Ombi with 2FA activate -> Wrong Username or Password"

**Expected behavior**
The Expected behaviour would be to let the user enter the 2FA code for authentication and after verification login the user.

**Screenshots**
- No screenshot

**Logs (Logs directory where Ombi is located)**
`[41m[30mfail[39m[22m[49m: Ombi.Api.Api[1000]
StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
[40m[1m[33mwarn[39m[22m[49m: Ombi.Controllers.V1.TokenController[0]
Failed login attempt by IP: ::ffff:192.168.178.13`

**Desktop (please complete the following information):**
 - OS: Linuxserver Docker version-v4.0.533 running on Unraid 6.8.3

**Ombi Version (please complete the following information):**
- Version Ombi: 4.0.533
- Media Server: Plex
- Database Type: I think it is MySQL but I'm not sure.

**Additional context**
- no additional context

**Comment by JDIacobbo** [comment]
I can confirm this issue. Disabling 2FA allows me to auth in. Same line in logs.

2020-12-05 20:48:44.281 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json

**Comment by tidusjar** [comment]
Use the OAuth flow in Ombi (Under authorization), or if you do not want to use this, add your 2FA code at the end of your password.

My recommendation would be to enable the Plex OAuth login.
