### ISSUE TITLE
"Root Folder" and "Quality" Override values inverted

### ISSUE THREAD

**Issue by bxlouis** [tidusjar/Ombi#3911]
**Describe the bug**
I noticed that when manually specifying a Quality profile and Root Folder from the "Advanced Options" menu, the values displayed in the summary are inverted.

In the screenshot below, one can observe that "FR - Ultra HD" is indicated instead of "/movies" and vice-versa.

**To Reproduce**
1. Click the "Advanced Options" from a request details page
2. Specify values for "Quality Profile" and "Root Folder"

**Expected behavior**
Values are not inverted.

**Screenshots**
<img width="351" alt="Screenshot 2020-12-05 at 10 58 37" src="https://user-images.githubusercontent.com/4128333/101239586-e0659b80-36e8-11eb-8811-cad9f6f1bee5.png">

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
- OS: Docker running on Synology DS918+

**Ombi Version (please complete the following information):**
Version Ombi: 4.0.739.0
Media Server: Plex
Database Type: No Idea

**Additional context**
N/A

**Comment by tidusjar** [comment]
This should be fixed in the latest version

**Comment by bxlouis** [comment]
@tidusjar unfortunately, I still notice the issue in the v4.0.1037.0 (development tag in docker).
Furthermore, after using this feature and reloading the page, the settings are not displayed. Not sure if this feature works then.
