### ISSUE TITLE
TVShows details are hardcoded into English.

### ISSUE THREAD

**Issue by cleme29** [tidusjar/Ombi#3912]
**Describe the bug**
The TVShows details are hardcoded into English.

**To Reproduce**
1. Have Ombi in an another language.
2. Look at the TV Shows tab on the search page.
3. Details are in English.

**Expected behavior**
Have the details of the TV Show in the correct language set in the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/8092733/101258903-dc0ba380-3725-11eb-964e-3057523cfab0.png)

**Step to resolve ?**
You did well with the movies but you forgot to add this line :
```request.AddQueryString("language", langCode);```
on line 275 of here :
https://github.com/tidusjar/Ombi/blob/ce39f205f3add989e77176ebd22e799a6a5aabe8/src/Ombi.TheMovieDbApi/TheMovieDbApi.cs#L271-L279

Is there any reason ? Because according to [the wiki of TMD](https://developers.themoviedb.org/3/tv/get-tv-details) the "language" parameter seems to exist like it exists on the movie side.

Anyway, thanks in advance and keep up the excellent work !

**Comment by tidusjar** [comment]
TV shows come from TvMaze and not the movie dB. Currently TvMaze does not support any other languages
