### ISSUE TITLE
Failed Dylib on M1 Mac

### ISSUE THREAD

**Issue by mushbuddygoose** [tidusjar/Ombi#3913]
**Describe the bug**
I am trying to launch Ombi v4 on a M1 Mac mini but am receiving an error loading the libcoreclr.dylib

**To Reproduce**
1. Tried to launch fresh install of Ombi on new M1 Mac and first received a Library Validation error related to the libcoreclr.dylib
2. Launched the libcoreclr.dylib in terminal to get rid of that error
3. Subsequently tried to launch Ombi (both under a native terminal and one emulating under Rosetta2
4. Receiving a fatal error "Failed to load JIT compiler

**Expected behavior**
Ombi launching without error (however I am unsure if Ombi and dependancies are supported on new M1 w/ Big Sur)

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
Log file attached

**Desktop (please complete the following information):**
Big Sur 11.0.1

**Ombi Version (please complete the following information):**
 - Version [4.0.739]
- Media Server [Plex]
- Database Type: MariaDB (mysql) installed via Homebrew

[Ombi_2020-12-05-130500_Mac-Daddy-M1.txt](https://github.com/tidusjar/Ombi/files/5647665/Ombi_2020-12-05-130500_Mac-Daddy-M1.txt)

**Comment by mushbuddygoose** [comment]
Following up on my own issue, appears this issue may be because .NET isn't running not he new M1s, even in Rosetta2? Assume there is no way around this?

**Comment by tidusjar** [comment]
If net core 5 doesn't support it then there's not much I can do

**Comment by tidusjar** [comment]
Here's the supported OS
https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md
