### ISSUE TITLE
Pasting to search area does not trigger find

### ISSUE THREAD

**Issue by glensc** [tidusjar/Ombi#3914]
**Describe the bug**

Pasting text on Android Chrome browser to search area does not trigger find. 

**To Reproduce**
1. Go to search page
2. Pin on search input, choose paste from the popup

**Expected behavior**

The ui should refresh and show results of the search, but it does nothing. 

As a workaround you can delete last character of the search and re-insert to trigger searching. 

**Screenshots**

![Screenshot_20201206-151720](https://user-images.githubusercontent.com/199095/101281360-28fb8280-37d7-11eb-8211-147bbeda545d.jpg)

**Comment by tidusjar** [comment]
Not going to fix this as V4 works very differently.

**Comment by glensc** [comment]
@tidusjar shouldn't your response then be please use v4? or v4 is not ready for use?

**Comment by tidusjar** [comment]
Ok sorry, please upgrade to v4
