### ISSUE TITLE
Fails to start citing arithmetic overflow and possible file corruption on Arch Linux

### ISSUE THREAD

**Issue by gwstorm** [tidusjar/Ombi#3916]
**Describe the bug**
Clean/fresh install of Ombi on Arch Linux results in a failure to start the service. 

**To Reproduce**
1. Have Arch Linux
2. Install from AUR. There are a couple versions of AUR packages for ombi, including [ombi-v4](https://aur.archlinux.org/packages/ombi-v4) and [ombi-develop](https://aur.archlinux.org/packages/ombi-preview). Both result in the exact same error listed below.

**Expected behavior**
Expectation is the service to start.

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
Ombi doesn't generate logs itself, but the journal output produces only this.

```
Dec 06 13:06:47 server audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ombi comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 06 13:06:47 server Ombi[54673]: Failure processing application bundle; possible file corruption.
Dec 06 13:06:47 server Ombi[54673]: Arithmetic overflow while reading bundle.
Dec 06 13:06:47 server Ombi[54673]: A fatal error occured while processing application bundle
Dec 06 13:06:47 server systemd[1]: ombi.service: Main process exited, code=exited, status=159/n/a
```

**Desktop (please complete the following information):**
 - OS: Arch Linux with kernel 5.9.11

**Ombi Version (please complete the following information):**
 - Version: I have tried the latest few versions as well as a range of versions from October 2020 to present
- Media Server: Emby
- Database Type: I have mariadb as well as sqlite installed. Not sure if there's a conflict there.

**Additional context**
At least two cases of this from package ombi-develop and users seem to be holding back their updates from the ombi-v4 package, but still seems to be functional for them. I tried the specific versions they mentioned and still received the same error. So an existing install seems to be able to downgrade, but no matter what, a fresh install results in the error.

**Comment by fryfrog** [comment]
I'll give this a look on my test system this evening too. Probably just something changed between original creation of the package and now, I don't use it and haven't kept up besides occasionally bumping the version.

**Comment by nicolahinssen** [comment]
Thank you for posting this issue.

I am the maintainer of the [ombi-v4](https://aur.archlinux.org/packages/ombi-v4/) package, and indeed, it's not functional at the moment. The past weeks have been quite busy for me, so I haven't had time to really dig into the problem. However, I've tried a few modifications (unsuccessfully) and I'm keeping an eye on the Ombi GitHub.

Probably the issue is related to the many updating issues I have read over here. The resolution almost every time was to perform a "clean" update, so by removing the old files an then placing the new. Unfortunately this also didn't work.

Hope to hear from the developer soon!

**Comment by tidusjar** [comment]
@nicolahinssen I don't know much about how it's packed, but I did come across this:
https://bbs.archlinux.org/viewtopic.php?id=257600

**Comment by gwstorm** [comment]
@fryfrog and @nicolahinssen 

I have tested this on both of your PKGBUILD files and it works. Simple adding `'!strip'` to the options line, making the complete line `options=('!strip' 'staticlibs')` builds the package successfully and starts.

Thanks for finding that, @tidusjar

**Comment by fryfrog** [comment]
I updated `ombi-preview` like you tried, will give it a try later.

**Comment by nicolahinssen** [comment]
Thank you @tidusjar and @gwstorm, worked like a charm!
