### ISSUE TITLE
V4 - Menu not showing correctly

### ISSUE THREAD

**Issue by Drewskieza** [tidusjar/Ombi#3920]
**Describe the bug**
The menus on the left hand side are not displaying correctly, I have tried Chrome, Firefox and Edge and they all look the same

**To Reproduce**
1. Clean installation of version 4.0.739.0 on windows
2. Log in

**Expected behavior**
Clear words of each selection

**Screenshots**
![image](https://user-images.githubusercontent.com/34630805/101389016-70623b80-38c9-11eb-9e4b-33b184ef45a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.739.0
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
That can't be a clean install, that is not the default colors to start?

**Comment by Drewskieza** [comment]
Correct, I did apply the Netflix CSS customization.  Here it is with the customization removed.
![image](https://user-images.githubusercontent.com/34630805/101721045-bbd63e80-3aaf-11eb-9764-3999bceb56f6.png)

**Comment by JaxonWright** [comment]
Are you blocking fonts? It appears that the Material Icons font required to show icons in the menu is not loading properly

**Comment by Drewskieza** [comment]
Bingo, PI-Hole was blocking the traffic.
Thank you.

**Comment by ashleyrfound12** [comment]
I have just installed this and I am getting the same problem. Any advice would be great.
