### ISSUE TITLE
 Background fanart not showing up [Router may be blocking a required country]

### ISSUE THREAD

**Issue by fireheadman** [tidusjar/Ombi#3937]
**Describe the bug**
Would like to know the countries used to provide content for Ombi.
Reason for asking is... I suspect my router (Unifi UDM Pro) is blocking a specific country.

**To Reproduce**
1. Go to 'main login page...'
2. Click on 'no need to click....'
3. Scroll down to 'no need to scroll....'

**Expected behavior**
When I attempted to update it this evening I had 2 failures for:

Could not connect to repo.ombi.turd.me:80 (176.9.117.41), connection timed out (Germany)
Could not connect to ppa.launchpad.net:80 (91.189.95.85), connection timed out (United Kingdom)

After unblocking these 2 countries I was able to update my Ombi server.
I'm back online, but not seeing any background fanart, which used to be there.

I have parsed through the logs and not seeing any errors that would hint at an IP or domain name being blocked to be able to look up anything... Would you know which countries the fanart is served from for Ombi?
Thanks in advance.

**Screenshots**
![image](https://user-images.githubusercontent.com/19847195/102452031-e3b92b00-3ff6-11eb-9428-0fe47ad549d3.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158] 3.0.5223
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Is this regarding updating?

Since I do not own or control those e.g. repo.ombi.turd.me

**Comment by fireheadman** [comment]
If you do not own or control one, please refrain from commenting on an
issue.   This will cause confusion
