### ISSUE TITLE
V4 - Unable to login via iOS App

### ISSUE THREAD

**Issue by stevezau** [tidusjar/Ombi#3942]
**Describe the bug**

Hi, i'm using v4 but i'm unable to login to the iOS app. In v3 i could log into the website using my plex credentials then hit the "open in mobile app link". However, this link does not exist on v4. The iOS app only allows for user/pass auth not plex creds.

**Ombi Version (please complete the following information):**
 - Version 4.0.779.0
- Media Server Plex

**Additional context**
I believe this is likely as it is not supported yet, but figured i'd create an issue anyway in case it is meant to work.

**Comment by gandalf764** [comment]
You can insert your plex data login.
I wait for qr code... I cant generate

**Comment by stevezau** [comment]
Hi @gandalf764, what did you mean by "You can insert your plex data login."?

Based on your comments I'm assuming that the mobile app is just  not supported in v4?

**Comment by gandalf764** [comment]
If you use google for login to your plex server, you can insert your google
data for login to ombi.

Il dom 27 dic 2020, 22:51 Steve Adams <notifications@github.com> ha scritto:

**Comment by modem7** [comment]
QR code is definitely broken in this case since the new v4 ombi app was released

**Comment by ethayer** [comment]
Could be related, I also have trouble logging into Ombi via mobile.  I think it may be a problem with form validation on mobile, as I used a password manager to paste into those fields, I have to enter an extra char after pasting in from the password manager, and then delete the extra char, and it works!

**Comment by tidusjar** [comment]
There's a button in the preferences section that works the same as the "Open in mobile" link in V3
