### ISSUE TITLE
v.4 Movie poster shows up twice

### ISSUE THREAD

**Issue by thu3n** [tidusjar/Ombi#3963]
**Describe the bug**
When you discover movies it can display same movie posters twice. See picture

**To Reproduce**
1. Go to 'Discover, press Movies then in my case "Trending" then scroll.' i am not a developer but i think if it happens in movie section it also happens in tv?

**Expected behavior**
Just one movie poster should appear 

**Screenshots**
 https://imgur.com/a/oM05gub

**Logs (Logs directory where Ombi is located)**
don't think this one needs a log?

**Desktop (please complete the following information):**
 - Windows, and using webb browser chrome

**Ombi Version (please complete the following information):**
 - Version 4.0.890.0
- Media Server Plex
- Database Type: SQLite

**Comment by Magikarplvl4** [comment]
https://github.com/tidusjar/Ombi/issues/3959

**Comment by thu3n** [comment]
Nice, i looked for similar. But didn’t find this ticket. I’m closing mine.
