### ISSUE TITLE
[V4] Movie showing available but it has been removed / deleted

### ISSUE THREAD

**Issue by lebowski9000** [tidusjar/Ombi#3965]
**Describe the bug**
When looking at the discover page, I can see movies as "Available" but I have removed them from Emby / Radarr. 

**To Reproduce**
1. Go to 'Delete a movie from Emby and Radarr'
2. Click on 'Discover'
3. Scroll down to 'Movie is possibly found in Discover as Available, even if it's removed. (Still showing after Cron jobs have sync)'

**Expected behavior**
The movie should not show as Available

**Screenshots**
I deleted this terrible movie, nothing in Emby, Radarr or Folders on the server
![image](https://user-images.githubusercontent.com/61567198/103858066-68cdc680-5103-11eb-9a9d-a28236853b37.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10 Client (Chrome) UnRAID Server Docker.

**Ombi Version (please complete the following information):**
 - Version 4.0.891.0
- Media Server Emby
- Database Type: MySQL

**Additional context**
Here is my Radarr settings:

![image](https://user-images.githubusercontent.com/61567198/103858326-d843b600-5103-11eb-85db-15c23c6bbd5d.png)

**Comment by Magikarplvl4** [comment]
Did you searched in the open issues? This issue is allready reported multiple times

**Comment by lebowski9000** [comment]
My bad, I'll close this
