### ISSUE TITLE
V4 - User import not working

### ISSUE THREAD

**Issue by Vinnpinn** [tidusjar/Ombi#3966]
**Describe the bug**
I can't import my Plex Users to Ombi. After clicking on "Import Users" it tells me that it started the import but nothing happens. I've attached the error logs.
My Plex Server is the one and only media server that is enabled. Everthing else seems to sync without any problems. Shows that are available on my Plex are marked as available in ombi.

**To Reproduce**
Issue occurs when going into the Settings, then Configuration and then User Management.
I've selected Import Plex Users and Import Plex Admin and set the default roles to Request Music, Movie and Tv.

**Expected behavior**
It should import the Users from Plex

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

[ombi logs.txt](https://github.com/tidusjar/Ombi/files/5785194/ombi.logs.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium

**Server (please complete the following information):**
 - OS: Linux 4.14.24-qnap #1 SMP Mon Nov 23 10:17:09 CST 2020
 - Running Ombi inside a Docker Container

**Ombi Version (please complete the following information):**
 - Version 4.0.891.0
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Been fixed in latest version
