### ISSUE TITLE
Blank Requests page

### ISSUE THREAD

**Issue by Fireant456** [tidusjar/Ombi#3971]
**Describe the bug**
System working normally but Requests page is now blank, only navigation UI shows.

**To Reproduce**
1. Go to Requests page

**Expected behavior**
Couple years of requests should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/1479965/104153156-380dbb80-53a7-11eb-8a7c-df9c3f9500da.png)

**Logs (Logs directory where Ombi is located)**
![image](https://user-images.githubusercontent.com/1479965/104153455-01847080-53a8-11eb-9573-dec9ab758efe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Chrome

**Ombi Version (please complete the following information):**
 - Version 3.0.5223 (Docker on UnRaid)
- Media Server: Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
Log out and back in
