### ISSUE TITLE
An information page

### ISSUE THREAD

**Issue by tedrock** [tidusjar/Ombi#398]
Just an enhancement suggestion. At some point it would be a great idea to make up a page that shows; Version, OS, mono version, relevant sites like the github and gitter, report a bug (see #399 for a suggestion to make that easier), etc.

You could do this like SABnzbd and make it the landing page for settings, do an About page like CouchPotato, or a System section like Sonarr.

For one thing this would make it much easier for users to submit bug reports.

**Comment by SuperPotatoMen** [comment]
planned for the 1.10.1 release
