### ISSUE TITLE
OMBI Linux help with db

### ISSUE THREAD

**Issue by chrischm** [tidusjar/Ombi#3981]
**Describe the bug**
After version 
4.0.681.0 I have not been able to start OMBI? there is no executable in the linux version. I am not very good with linux so I have no idea how this works now. How do you start OMBI? 

**Ombi Version (please complete the following information):**
 - Version 
4.0.975.0
- Media Server  Plex]
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Please see the wiki https://github.com/tidusjar/Ombi/wiki/Installation#linux-systems
