### ISSUE TITLE
Report a bug button

### ISSUE THREAD

**Issue by tedrock** [tidusjar/Ombi#399]
Another enhancement request to go along with #398 

In the menu bar beside donate I'd recommend putting a little bug icon and "Report Bugs" this could encourage even users to report bugs.

You could take advantage of the information gathered in #398 and pass that on to the New Issue form along with browser and OS.

Example: https://github.com/tidusjar/PlexRequests.Net/issues/new?title=&body=OS:Windows%207%0D%0ABrowser:Chrome%0D%0AETC

**Comment by tidusjar** [comment]
Nice!

**Comment by tedrock** [comment]
I did notice you have a limit to how much information you can pass in the URL and it also wipes out your current template.

**Comment by SuperPotatoMen** [comment]
planned for the 1.10.1 release

**Comment by nbyloff** [comment]
I might suggest this is a bad idea. Couch Potato had this for a while, and disabled the feature because of the sheer amount of bugs that were submitted. Unless you have a system to weed out duplicates, you might quickly hit hundreds if not thousands of bugs, some of which aren't actual bugs.
