### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#402]
Hi All,

Please post here regarding any translations.

You can view the current set of translations here: https://1drv.ms/x/s!Ar0TPpCxBSHZrQANUxCNnwl-5A8E

If you have any suggestions for changes either:
1. Post the suggestion on this issue
2. Request access to edit the above spreadsheet (Post your email address)

**Comment by Ruvetuve** [comment]
Please explain how do you want us to upload changes or new languages.

**Comment by tidusjar** [comment]
Good point. Updated the post.

**Comment by ElYoM** [comment]
Sorry to insist but the statement "Série tv should be Série télé because tv is not a actual french word" is wrong. TV is actually the french initialism of the word Télévision.

**Comment by chris1neji** [comment]
I have a few suggestions for spanish version 
email  christian.1992.14@hotmail.com

**Comment by tidusjar** [comment]
Updated the translations with all of the current changes (in dev build currently), @chris1neji you should have an email in your inbox with a link to edit them.

**Comment by RacerBas** [comment]
The Dutch translation Should now be correct for the biggest part.

**Comment by tidusjar** [comment]
Excellent, I'll import it into the application.

**Comment by Jonn3y** [comment]
Hey, i updated the german suff a little bit. 
[Excel-Link(DropBox)](https://www.dropbox.com/s/qpies6z4boy3c8o/Resources%2029.06.2016%20-%20DE%20updatet%2008.08.2016.xlsx?dl=1)

But you have to add all the new stuff from the admin-menu like:
```
You will have to restart after changing the url base.
...
Search for Movies
Search for TV Shows
```

=)

**Comment by tidusjar** [comment]
Thanks. I'll add it in. Yeah localising the website is boring and takes a while :D I was doing the main user areas first and the admin after.

**Comment by tidusjar** [comment]
Updated the translations and re-uploaded them for you guys to see:

https://1drv.ms/x/s!Ar0TPpCxBSHZrQANUxCNnwl-5A8E

**Comment by RacerBas** [comment]
Can you send me a link to edit it? I spotted some mistakes in the Dutch translation

**Comment by tidusjar** [comment]
@RacerBas Sent you an email that should have the editable link

**Comment by RacerBas** [comment]
Unless I missed something it should be correct now :)

**Comment by tidusjar** [comment]
Awesome, I'll import it soon

**Comment by thecorax** [comment]
Hi, I would like to improve the german translation.

thesquall@gmx.net

**Comment by tidusjar** [comment]
@thecorax Invited
