### ISSUE TITLE
Feature Request: Request show without adding season.

### ISSUE THREAD

**Issue by theg1nger** [tidusjar/Ombi#404]
Right now when requesting a tv show you can only request:
All Season
First Season
Last Season
Select... (Which lets you choose what season)

The problem I have is that when the show is requested, sonarr automatically starts searching for the show (depending on the season(s) requested). If i just want to add it to sonarr without having it go look for anything I can't do that right now. There is no "No seasons" type of request which will just add the show to sonarr as "don't monitor". 

Make sense?

Thanks,
-W

**Comment by tidusjar** [comment]
Yeah that makes sense, but why would you request it if you don't want to download it?

**Comment by theg1nger** [comment]
If there is a show I just want to try out. I don't necessarily want to download all the episodes of the first season. Maybe just 1-3 of 24 episodes. 

Sonarr automatically just starts grabbing from whatever source you make available to it. There could be a 200mb SD version of the episode or a 600mb SD version of the episode. I like the choice of picking which one downloads. Or sometimes i don't care what it is and i just want to grab. 

I realize that this could be setup in sonarr but I'd still like the ability to add stuff through plexrequest without it grabbing 24 episodes as soon as its added. I guess its just a control issue thing :-)

**Comment by anonaut** [comment]
I would like to additionally request the "Future" option. It's already in sonarr and basically the same as "None" except it watches future episodes. Background to this is as theg1nger says limited configurable control in sonarr in regards to prefered groups/releases.

**Comment by tidusjar** [comment]
@anonaut can you raise a separate issue please?

**Comment by SuperPotatoMen** [comment]
@theg1nger it is possible to request 1 or 2 episodes :)
I will close this one for now.

**Comment by theg1nger** [comment]
@SuperPotatoMen Yup! Thats what I've been doing. Thanks!
