### ISSUE TITLE
Request: Turn off Reports/Issues

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#421]
**Request**
I have my own landning page with built in Issue reporting would be nice to turn PlexRequests issue reporting off for all users.

Also option for automatic removing of requests that's now available.

**Comment by ElYoM** [comment]
@Garderoben Do you use a pre-made solution for reporting issues ? If yes, what is it ? I'm interested to include a system like this into my own landing page. Thanks.

**Comment by Garderoben** [comment]
@ElYoM its just simple PHP/Javascript and a MySQL database.
