### ISSUE TITLE
Request: show a message with estimated time on plex after a request

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#427]
A little Request:
Show a little text block after hitting the request button with a text how mutch time it will take to handle you're request.
The system can look at the release date of a movie or tv show. If it After that, you can show the requested a custom message with a estimated time that the request take to process the request and when it can watch on plex.
A admin can set the custom message after the request in the admin panel.
For example: I know that it takes me about 3 minutes to a series is actually visible on plex.

**Comment by tidusjar** [comment]
That's a pretty good idea. I guess we could put it in the green notification on the top right? Rather than a separate modal.

What you think?

**Comment by whitecollar17** [comment]
I like message's in the middle of the sceen +1

**Comment by tidusjar** [comment]
Seems quite intrusive though.

**Comment by whitecollar17** [comment]
Top right is okay :+1:

**Comment by whitecollar17** [comment]
@tidusjar maybe this one for acktoberfest ?

**Comment by tidusjar** [comment]
Note: Add something in the settings where the user can specify a custom message after a request.
When requesting something, if the custom message is enabled, then show a toast notification after requesting something

**Comment by SuperPotatoMen** [comment]
@tidusjar Maybe we can make a different screen? After the requesting it you have a button: Follow your request. If you can click on it, you have a track and trace page of your request
Something like this:
![image](https://cloud.githubusercontent.com/assets/2944704/21358379/d31568f4-c6d8-11e6-80ef-d797938b36b2.png)

**Comment by tidusjar** [comment]
Like a parcel tracker? 😆

**Comment by SuperPotatoMen** [comment]
Yeah, see my message on gitter :D
