### ISSUE TITLE
[FR] Sonarr - Multiple Root save directories for TV shows

### ISSUE THREAD

**Issue by anonaut** [tidusjar/Ombi#445]
At the moment its only possible to have one root save directory for sonarr configured in plexrequests. 

In sonarr i have multiple directories configured, Anime and TV Shows, for better view in plex.

Would it be possible to add more then one save directory in the settings, and let users choose where they want to save it when they request a show?

maybe even adding genres to those directory entries in the config and let plexrequests decide (should be easy to get the genres from tvdb)?

for example: 2 directories, TV Shows with genre "All", Anime with genre "Anime"
when a user adds breaking bad plexrequests checks tvdb for the genres, if anime is included we use configured path for TV Shows. same if a user adds kill la kill, plexrequests checks genres, anime is included -> use anime path.

**Comment by tidusjar** [comment]
This is being done in #535

**Comment by RacerBas** [comment]
Nice work!
