### ISSUE TITLE
[Feature] Support for sharing labels

### ISSUE THREAD

**Issue by some-guy-23** [tidusjar/Ombi#453]
With a Plex Pass, instead of sharing an entire library with every user, you are able to restrict based on "sharing labels". This is useful if you are setup on a server with limited bandwidth, and don't want to share every TV Show and Movie with every user. With this feature you can whitelist specific TV Shows or Movies, to make them accessible to a given user.

The first step is setting up "sharing labels" is under Users -> Friends -> {Username} -> Restrictions. For an example, you can allow "User1" to only access media that is has a sharing label of "Friend1" in your TV Show and Movie libraries.

The second step would be adding this sharing label to a piece of media. This can be done by going to any TV Show or Movie, then hitting Edit->Sharing. Here you can add the users' label that you'd like to have access e.g. "Friend1". You can add as many sharing labels as you want to one piece of media.

My proposal for a PlexRequests.Net feature would be an automatic way to handle this sharing label process. Here are some thoughts I had on it ->

1) First step would be to have an option for "restricted (label based) sharing". If this is enabled, it will present a mapping of "username" to "share label" that you can setup. Or maybe this info can even be retrieved automatically from Plex?

2) Now when a user requests a TV Show or Movie, the normal flow of events occurs. However, after the media is confirmed to have been added to Plex, it would also write the "share label" to it, to allow access. Will have to see if this is something that can be easily done w/ the Plex API?

3) One consideration would be, what happens if the media is already present on the Plex Server, but the user requesting it does not yet have access to it? I would think that in this case, it would wait for approval of the admin, then go ahead and add the "share label", to allow access to said media.

**Comment by Rsslone** [comment]
I'm just speaking out of my ass here but wouldn't this be easier if Sonarr and CP supported this first? The only thing Plex API is being used for is authentication and checking if you already have a title on the server.

**Comment by some-guy-23** [comment]
@Rsslone - my thoughts on it are, right now Sonarr and CP don't have any kind of awareness of sharing or users on your server. They also don't write anything via the Plex API (that I can think of).

So, while this would definitely be a big step for PlexRequests to take, I think it at least has a foot in the door, compared with Sonarr/CP. I also think it just makes more sense in general here, since the goal is to automatically provide new-content to users on demand. So, I think this is still in line with that goal, just more complicated.

**Comment by Rsslone** [comment]
@tidusjar will have to comment on how feasible it is but I agree it could be a useful feature.

**Comment by tidusjar** [comment]
I think it's a feature that could be implemented, I can see it's use.

It shall be done, but when I have no idea, got a lot of things to do before this!

**Comment by tidusjar** [comment]
Thanks for taking a look. 

It sounds like it's getting more complex!

**Comment by some-guy-23** [comment]
Yes, it does seem like a solution will be fairly complex!

The good news is that the required Plex API calls at least are fairly straightforward. I have been able to add/remove a label to a given Show/Movie. Also, retrieving whether or not a Show/Movie already has a share label only requires a slight modification to the metadata API call that was already being made (for advanced searching option).

**Comment by tidusjar** [comment]
If you could put the API Call information into this issue that would be a big help

**Comment by some-guy-23** [comment]
Just wanted to post an update on this after poking around in the TV search/request code today -

Possible Scenarios (TV Shows)

1) Someone requests a full show, it already exists on Plex but is not shared

Request is flagged to just required approval (will not send to Sonarr). Can use the type field in DB for this, once approved sharing label will be added to the show

2) Someone requests a full show, it does not yet exist on Plex

Request is submitted as normal, however once request is fufilled, any users on that request will also get their sharing labels assigned

3) Someone requests specific episodes on Plex, some episodes exist, some do not, show is not shared yet

Essentially same as #2, but the request will be for episodes, no need to check for sharing label, can just assign it twice without issues

4) Someone requests specific episodes on Plex, and all of them exist, but show is not shared yet

Similiar to #1, a request is created still, but once approved it simply sets the needed share label


Extra notes -

1) Admins should never get a request option for shows that exist on Plex, should just show as avaliable

2) If auto approval is turned on, logic should be the same (with when share labels are applied), just without a wait for approval

Complications -

1) Right now, any kind of label checking would require the "advanced search" feature be turned on. This is because the share labels are only on individual show/movie metadata (as opposed to library directory info)
