### ISSUE TITLE
How to disable Authentication for requests

### ISSUE THREAD

**Issue by iNilo** [tidusjar/Ombi#454]
I unticked the 

Authentication Settings
`Enable User Authentication [  ]`

And it still requires/shows to login before I can request something.

How do I turn off authentication fully (not even a username field) ? (Home network,want to allow anyone to request)

Thanks

**Comment by tidusjar** [comment]
That is currently not supported. When you disable authentication they just need to enter a username so we know who they are.

**Comment by iNilo** [comment]
if(ip == localnetwork) -> set username ("family") ?

**Comment by tidusjar** [comment]
"Anonymous" ?

**Comment by iNilo** [comment]
Custom userfield to be overridden otherwise fall back on Anonymous ?

**Comment by tidusjar** [comment]
No, I cannot detect where the user has come from.

I was thinking about just add an option to remove the login page and default their usernames to anonymous.

**Comment by iNilo** [comment]
Oh very good idea nevertheless

**Comment by Burry** [comment]
It would be great to be able to disable the Ombi login. Some of us use custom authentication like [PlexAuth](https://github.com/hjone72/PlexAuth) or other SSO implementations, and having the ability to bypass Ombi's login would make it much more flexible for custom set-ups.

**Comment by AngryNoodlez** [comment]
+1 to Burry's idea. I also use PlexAuth for a custom SSO Setup with the meteor version of PlexRequests currently which was easy to implement SSO for given its "_authenitcation_" method. (Username written to key/pair value in local storage)

Would love to be able to test out Ombi with SSO support and see how my users like the new feature set it offers.

**Comment by pkoenig10** [comment]
+1 to this. It is really cumbersome to have a second "login" page when using Ombi with a separate SSO solution.

**Comment by clifford786** [comment]
+1 to Burry's idea.
Using Caddy to reverse proxy a few services, and have a separate service for authentication, the Ombi login page is redundant and confuses some of my users. I already limit who has access to what, allowing all user's to use an 'Anonymous' account on Ombi would be move convenient.

**Comment by ned-kelly** [comment]
> Using Caddy to reverse proxy a few services, and have a separate service for authentication, the Ombi login page is redundant and confuses some of my users. I already limit who has access to what, allowing all user's to use an 'Anonymous' account on Ombi would be move convenient.

Exact same setup here!

**Comment by kirsch33** [comment]
has there been any update to this discussion? would love to have SSO between my own portal, Ombi, Radarr, etc.

**Comment by jferris-** [comment]
Agreed. Please make this a thing!

**Comment by kirsch33** [comment]
The use case is very specific but hopefully someone can make use of it in anyways... I have developed a plugin for Caddy v2 that bypasses the Ombi login by cookie authentication. Documentation is poor as I just finished it up last night but open to suggestions or improvements.

https://github.com/kirsch33/plexsso

**Comment by Theweasels** [comment]
Sorry for adding a comment 5 years later but this is the first google result for "ombi remove authentication". I was able to do this fairly easily with Caddy acting as my reverse proxy. Other proxies can probably do it to if you can adjust the headers.

In Ombi:
1. Create a user. I used "guest".
2. Under Settings > Configuration > Authentication, Enable Authentication with Header Variable.
3. Enter a header variable in the textbox. I used "ombi-user" since I wanted to make sure it's not a real http header.

In the Caddyfile add the "header_up" directive under the reverse proxy like so: 
```
ombi.example.com {
    reverse_proxy http://docker.internal.example.com:3579 {
        header_up ombi-user "guest"
    }
}
```

That's it. All requests going through the reverse proxy get automatically signed in as "guest".
