### ISSUE TITLE
Request: NZBGet integration

### ISSUE THREAD

**Issue by iNilo** [tidusjar/Ombi#455]
It would be very nice that in the "requested" section I would show the current download progress.

**Comment by tidusjar** [comment]
Hmmm... I'm not to sure about this.

First, there is no way to link up a request by the actual download, so we could show the progress of an actual request.

Secondly, I don't think this is the right type of feature for plex requests.

Anyone, please feel free to disagree.

**Comment by iNilo** [comment]
There is "no exact way" to link it, however regex/etc... matching can be done?
Or generally on requests it could show the NZBGet movies/series section of currently downloading

**Comment by tidusjar** [comment]
We could guess by the title yes, but that could lead to inaccurate results, and I can see issues being raised about that.

It is 100% possible to get the list of NZBGet downloads, but why would the users doing the requesting want to see that?

**Comment by iNilo** [comment]
When someone requests a movie to see in 2 hours, it might be nice to show something is actually happening, this way the requester knows he/she will be able to see that movie tonight.

**Comment by tidusjar** [comment]
If we add support for NZBGet we will also have to add support for SabNzbbd. I'll have a think about it.

**Comment by iNilo** [comment]
You don't "have" to, but support for both would be very nice. 

I'll look into this a bit more.

**Comment by tidusjar** [comment]
Yeah of course! Maybe if we do decide to do this, we will add NZBGet first and then see if anyone request sab.

**Comment by whitecollar17** [comment]
Is it possible to show the download status from Sonarr by a tv show?

In Sonaar, you can see a progress bar, maybe you can get the infomation from te sonarr api?

**Comment by tidusjar** [comment]
@whitecollar17 that's actually a very good point. I'll check

**Comment by iNilo** [comment]
https://github.com/Sonarr/Sonarr/wiki/Queue has

`    "sizeleft": 0,
    "timeleft": "00:00:00",
    "estimatedCompletionTime": "2016-02-05T22:46:52.440104Z",
    "status": "Downloading",
    "trackedDownloadStatus": "Ok",`

**Comment by iNilo** [comment]
Using Sonarr API removes the need to support every download client, since it provides it to

**Comment by causefx** [comment]
@iNilo @tidusjar That API will only work for TV Shows.  What if a user wants to know about his movies?  What you could do....which would suck as it requires a bit of coding is...  parse the download queue from NZBGet is SAB, and query the results as the following:

TV Shows:
Name and S00E00

Movies:
Use IMDB# as CouchPotato adds the download with cp(tt00000000)

**Comment by tidusjar** [comment]
Good point.

**Comment by tidusjar** [comment]
I've decided not to do this.
