### ISSUE TITLE
[Feature] Clear all available requests

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#468]
I would love a button where i can clear all requests that's available or has been available for x time.
If i'm not wrong the "Delete Movies" button deletes every thing even if i am using a Filter.

**Comment by tidusjar** [comment]
What about a clear all approved requests, Doing a time thing will be difficult (not from a code point of view, but from a user) as some people will want it after X days and others after N Days etc.

**Comment by Garderoben** [comment]
Thing is, i don't want to clear the once that are approved and not available.
I have auto approval on, but not all the time Couch Potato finds them in my qualitys or they are not released yet.

F**k the time thing hehe was just an idea to automatically clear X old items. But i would love a way to clear all the movies that Approved and Available on Plex. But leave the once that's missing.

**Comment by tidusjar** [comment]
Ok. Yeah that sounds good. Clear all the are available

**Comment by Garderoben** [comment]
Just wanted to add to this as of this date my request panel is broken.

Since i have so many request it takes enormous time for Ombi to load them all that it some times crashes and when its loaded it lags as hell.

Would be awesome if the "Delete Movies" button only deleted the movies that are shown, aka if i filter some out don't remove the ounces filtered out.

**Comment by tidusjar** [comment]
Hi, I am aware that the requests page is not very useful for large libraries.

It's just having the time to rewrite that page...
