### ISSUE TITLE
Add the ability to view the Plex Library

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#47]
A new page that shows all current Plex content with their quality.

Add the ability to request the same version but different quality

**Comment by curlz620** [comment]
Just a thought, if this feature is added it would be really nice to be able to disable the multiple quality request. I generally keep my requests at a lower quality and I feel many of my users would request high quality even though they stream at lower qualities.

**Comment by tidusjar** [comment]
That's not a bad idea. can just add a new setting to enable requesting of higher quality.

**Comment by Snipees** [comment]
And what about, in this Plex library, to add the ability to download the matching file locally ? (some users occasionally wants to keep some movies)

**Comment by leram84** [comment]
there seem to be a few different requests that have to do with quality. Would it be possible to keep ALL quality settings completely hidden as an option? I make all quality decisions myself, and I don't want my users to even know there is such a thing as different qualities lol.

**Comment by tidusjar** [comment]
Yeah, I personally don't like the idea of allowing users to request different quality, it makes the experience more complex.
