### ISSUE TITLE
Rework the requests page, needs to support 700+ requests

### ISSUE THREAD

**Issue by jimphreak** [tidusjar/Ombi#481]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9
#### Operating System:

Docker on Ubuntu 16.04
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```
#### Reproduction Steps:

When I search for and request a movie I see the movie show up in CouchPotato.  Howerver when I click on the Requests page it's blank.  It's reading something because as you can see the "Sorry, we didn't find any results" message is gone.  Then, if I click "Delete Movies" and try to search for the same movie again it shows it's been requested and I can't add it.   Logs are empty even with log level set to Trace.

**Comment by tidusjar** [comment]
Anything in the browsers console? F12? There should be an error in red, if you click on it and post the response?

**Comment by jimphreak** [comment]
I see no errors when I hit F12.  I've tried in both Chrome and IE11.

**Comment by tidusjar** [comment]
Strange, I cannot reproduce this. Are we able to do some sort of remote desktop session so you can show me via teamviewer or something?

**Comment by zenjabba** [comment]
I'm also having the same problem, but it simply seems it taking so long to load the list.

Happy to share my database so you can look at it.

**Comment by tidusjar** [comment]
@zenjabba If you could that would be great, can you just change the admin password.

jamierees@outlook.com

**Comment by zenjabba** [comment]
https://smoke-mirrors.box.com/s/mswmiyeph291m9idhnj82vkk9ga2lfmh

password: password

**Comment by tidusjar** [comment]
Thanks, I removed the link just incase you may have any personal info in your logs

**Comment by zenjabba** [comment]
Understood.

**Comment by tidusjar** [comment]
Wow, I know your problem @zenjabba there are too many movies to load at one time and the UI can't cope.

@jimphreak Is your couchpotato set up correctly?

**Comment by zenjabba** [comment]
@tidusjar I'm a good test site for large data testing. Let me know when you're needing a beta tester

**Comment by tidusjar** [comment]
Thanks @zenjabba 

Yeah you have over 700 movie requests, the UI was never meant to hold that much data!

I'm going to have to redesign the requests UI. 

Server > Client = milliseconds.

Client rendering is where the time is being spend, I am using the template framework handlebars to render each movie request and it's not optimal for 700! 

I'm thinking about moving the ordering/filtering to the server and introducing something like paging or page virtualization. 

It's no easy task though...

For now @zenjabba I can delete all your approved and available requests so you can see the page?

**Comment by zenjabba** [comment]
If I leave it long enough, it comes good. I'll wait till you update the code.

**Comment by tidusjar** [comment]
OK
