### ISSUE TITLE
Request a specific couchpotato category

### ISSUE THREAD

**Issue by jdelvecchio** [tidusjar/Ombi#490]
Actually, users can only request a movie and it gets downloaded using the default couchpotato profile.
What if they want the movie in a different language ? 
I set up multiple couchpotato categories, but users cannot requests for a movie with a specific category (french, english, multi...).

Is this possible ?

**Comment by tidusjar** [comment]
It is possible!

I'll add this onto the backlog.

Just a FYI, the default category is set in the couchpotato settings (It's the profile).

**Comment by jdelvecchio** [comment]
That'd be great, thanks !

**Comment by armandkd** [comment]
Hi,
Was this ever released? This functionality would be really great!
Thanks.

**Comment by tidusjar** [comment]
No, I suggest you switch to Radarr

**Comment by armandkd** [comment]
Ok, I switched to Radarr and disabled Couchpotato. Still no way of selecting a profile when requesting a movie as an admin...
