### ISSUE TITLE
Request: PLEX Channel for PlexRequests.net

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#497]
Is it possible to connect the plexRequests.net to a plex request channel like this one:

https://github.com/ngovil21/PlexRequestChannel.bundle

would be very useful!

**Comment by tidusjar** [comment]
I don't think I want to also create and maintain a channel, what's wrong with that one?

**Comment by seanvree** [comment]
@tidusjar , just so you don't have to launch the website, you could do it directly from PLEX. I wouldn't want to use that one because it doesn't talk to your app.

**Comment by tidusjar** [comment]
@seanvree True, maybe i'll talk to the original owner to see if he wants to integrate

**Comment by seanvree** [comment]
Thanks, I really do think MOST of your plex "friends" would use this rather than going to the webUI.

**Comment by seanvree** [comment]
Any movement on this?

**Comment by StevenChorkley** [comment]
I too would like to know if there's been any development. 

Thank you for your awesome tool!

**Comment by SuperPotatoMen** [comment]
This feature request is not in the scope at the moment.
We have now other priorities at the moment.

**Comment by cwallace** [comment]
I would really love if Ombi had a plex channel. Not all of my family is savvy enough to open a separate URL to a domain they've never heard of. Being inside Plex would be amazing.

**Comment by richardpoyner** [comment]
I would really appreciate this too :)

**Comment by lpreams** [comment]
I don't even want Ombi to be available in a plex channel, I would just like a channel that my friends can click that will redirect or provide a link to my Ombi install. That way they don't need a separate URL. 

I'm just speculating, but maybe that could also have the user be logged in to Ombi somehow? I have no idea how that might work, just an idea.
