### ISSUE TITLE
Auto-queue coming soon movies

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/Ombi#503]
For some of us that want to always have the latest movies on our plex server, it would be great if we could enable a feature to queue up movies in the "coming soon" category automatically, on a schedule.

It could probably check hourly, or even just once a day.

**Comment by tidusjar** [comment]
Yeah that's good idea. 

Who would be the 'requestor' though? The system? Would be it added as a request?

**Comment by Drewster727** [comment]
Probably just the system. I don't think the end-users would ever need to see/adjust this feature. I was going to write a little task to do this, but I think it would be better served as a feature of PR :)

**Comment by tidusjar** [comment]
Yeah it's a good idea. So you think it should be added as a request?

**Comment by Drewster727** [comment]
Yep, I think it should just go through the normal pipeline. That way if people search for one of these auto-queued items, it'll show "Requested" already.

**Comment by Foebik** [comment]
Keep in mind Couchpotato can do some of this out the box.
Popular Movies - Imports the top titles of movies that have been in theaters. Script provided by Steven Lu
Here is a link to the page showing it the data/script it will use to get movies.
http://movies.stevenlu.com/

**Comment by Drewster727** [comment]
wow good call @Foebik - I've never used that feature. Much appreciated. We might consider axing this one @tidusjar

**Comment by tidusjar** [comment]
That's a good point. I use that in couchpotato

**Comment by SuperPotatoMen** [comment]
@tidusjar now we support more systems (Radarr and Watcher) maybe we can give this idea a little higher prioritiy. The feature is now only available in CP, but more and more people are going to watcher or radarr that doesn't have the option.

**Comment by SuperPotatoMen** [comment]
It will be nice if we sync with the api of trakt.tv Its a nice system and stable platform :)

**Comment by thatoneguy99** [comment]
Going back to the thought of Radarr and Watcher not having that ability. Radarr has the ability to add from IMBD lists. There are many lists available through IMDB for new releases, top box office, etc. This could easily be handled by Radarr. Not too sure about Watcher.

**Comment by pmow** [comment]
Although CP can do this (as @Foebik mentioned) these movies still wouldn't show up in Ombi.
Instead of duplicating the functionality already implemented in Radarr/CP, maybe the movies can be imported into Ombi as an admin request.  That way, users wouldn't try and request them, and could actually report issues on them even if no human had requested.  One place to submit issues with videos in Plex.

**Comment by thatoneguy99** [comment]
I am sure your setup is different than mine but I don't understand why you would want a user to report an issue with a movie that is "Requested". Once Radarr (whatever service) downloads it, it will become "available" in Ombi, and they can report an issue. Reporting an issue on a video you don't have? I can't wrap my head around that.  
 It would be nice for CP/Radarr/Watcher "Wanted" list to show up as "Requested" in Ombi. That would solve all of this right?

**Comment by pmow** [comment]
I wasn't suggesting a change in what a user can file an issue on. But there are legit reasons to do so. It's a report to the admin that a request should be out already and downloaded, for example.

I was suggesting that populating Ombi with movies wanted in CP and movies on PMS would result in more effective reporting of issues

**Comment by thatoneguy99** [comment]
Just curious. Thanks for the explanation.
