### ISSUE TITLE
[Feature] Give the option of change the sender name in the From field

### ISSUE THREAD

**Issue by nickiman** [tidusjar/Ombi#509]
Hi,

As this [page ](https://www.bettercloud.com/monitor/the-academy/how-to-change-your-sender-name-in-gmail/)indicates I think that could be a good idea implement the option of change the sender name as other gmail users can do. 

Maybe this code can be useful for you...

> message = MIMEText(message, 'plain', "utf-8")
>         message['Subject'] = subject
>         message['From'] = email.utils.formataddr(('PlexRequests', Request.CONFIG.EMAIL_FROM))
>         message['To'] = plexpy.CONFIG.EMAIL_TO
>         message['CC'] = plexpy.CONFIG.EMAIL_CC

This will create an e-mail notification more clear in order to identify it.

Best regards.

**Comment by tidusjar** [comment]
I am planning to completly rework the way we have notifications. I plan to make everything editable including the messages etc. So this will happen :)
