### ISSUE TITLE
[Request] Add the ability to specify series type upon requesting series

### ISSUE THREAD

**Issue by DRankex** [tidusjar/Ombi#522]
Would it be possible to add the option to define the series type when requesting a series and a custom directory depending on the series type that was defined.
Doing this would be nice for sonarr users with both TV and Anime as myself.

If this isn't possible I would like to be able toggle monitoring before accepting a series so that I have time to go to sonarr and manually change series type and save directory before it starts searching the indexers.

**Comment by AloiSama** [comment]
I would appreciate this feature as well. That way the proper indexers are used for each type.

Thank you for a great app!

**Comment by tidusjar** [comment]
Hey!

What do you mean by 'type'?

**Comment by AloiSama** [comment]
Hello =D

I'm referring to this option: http://i.imgur.com/QWlI5VZ.png

Currently, Ombi defaults to Standard, which causes Sonarr to look for anime in the wrong place and not find the series properly.

What do you guys think?

**Comment by tidusjar** [comment]
Hey that makes sense!

**Comment by AloiSama** [comment]
How would one go about this? Is there a way to add such feature and contribute to this repository?

**Comment by tidusjar** [comment]
The code is open source, so if you know .Net and C# you can contribute yourself and submit a Pull Request.

But this version of the code (v2) will become obsolete soon as the rewrite will take over.
