### ISSUE TITLE
DVR support

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#523]
i will be nice if users can request a recording for de new DVR support on plex :)

**Comment by tidusjar** [comment]
That would be good!
Not sure what we need to do for that yet! Any information you have please post here

**Comment by whitecollar17** [comment]
Well, i'm still waiting for a replay if there is any api for it.
We can work with a workaround. Place a second button with calls: "Request manual recording"
After you request it,, it the requested tv show or movie has the tag, waiting for processing. The admin can give the status: "manual recording set".

in the admin panel you can turn off and on the button.

**Comment by tidusjar** [comment]
Yeah that's a good idea for now

**Comment by CarterBrehm** [comment]
Was this ever implemented? The concept of a simple requests system is great, although I'd rather get TV from the air, legally.

**Comment by tidusjar** [comment]
This was never done @CarterBrehm
