### ISSUE TITLE
already exists tv shows can be re-requested

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#528]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.1
#### Operating System:

windows 10 pro
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```
#### Reproduction Steps:

Use Advanced Search on
Enable Episode Searching on

You can re-requests already exists tv shows in plex.

I have White collar on plex but i can re-request it for all seasons. it's not showing up like "allready on plex"

https://files.gitter.im/tidusjar/PlexRequests.Net/MPJL/blob

https://files.gitter.im/tidusjar/PlexRequests.Net/ju4S/blob

**Comment by tidusjar** [comment]
Are you missing any episodes?

**Comment by tidusjar** [comment]
I see the problem, is this an urgent bug? Because it doesn't really effect the system or Sonarr/Sickrage. It's difficult because of the "First/Latest/All" buttons

**Comment by whitecollar17** [comment]
I have it also with movies.

**Comment by tidusjar** [comment]
@whitecollar17 what movies is this happening with? I cannot get it to reproduce with movies as it's showing as available for me

**Comment by whitecollar17** [comment]
With the movies  don't have the problem anymore. Can't reproduce here also :/ magic!

**Comment by tidusjar** [comment]
It's possible that this happened straight after the upgrade and the app didn't get to crawl through plex completely?

**Comment by tidusjar** [comment]
Any update @whitecollar17

**Comment by whitecollar17** [comment]
Well, i have still the problem. I update now to the new version to check if that make a difference

**Comment by whitecollar17** [comment]
You can see here the problem. Marked like "available" but still possible to request the show.

![image](https://cloud.githubusercontent.com/assets/2944704/18811408/bc0c7af8-82ae-11e6-8e09-51afdb2cf106.png)

**Comment by tidusjar** [comment]
That's because you do not have all of the episodes?

**Comment by whitecollar17** [comment]
If i look at Sonarr, i have them all

![image](https://cloud.githubusercontent.com/assets/2944704/18811629/cb9ef68c-82b6-11e6-9140-bb1af27aac42.png)

**Comment by tidusjar** [comment]
Except specials... I'll make the change to exclude specials

**Comment by whitecollar17** [comment]
But its not monitored?

**Comment by SuperPotatoMen** [comment]
Note for @tidusjar  don't look if the specials also available beceause sonarr don't support it very good.

**Comment by SuperPotatoMen** [comment]
Fixed in last EAP version
