### ISSUE TITLE
Requested TV shows being marked available before show is added

### ISSUE THREAD

**Issue by gadgetusaf** [tidusjar/Ombi#549]
Any show that is requested is being marked as available. Prior to updating to latest it would also be marked as approved whiteout out my approval (require approval is check)

**Comment by gadgetusaf** [comment]
This is before the show is added to plex

**Comment by tidusjar** [comment]
You do not have the show in Plex at all?
Is advanced episode search and advanced plex search turned on?

**Comment by gadgetusaf** [comment]
Plex Config
SSL: Active
Use Advanced Search: Active
Enable Episode Searching: Active 
Request 
Search for Movies: Active
Search for TV Shows: Active
Require approval of Movie requests: Active 
Require approval of TV show requests: Active
Approval White listed Users: Empty

The requested shows were not in my library at all (0 episodes) they also were also not approved by the admin nor added SR. they would go approved and available. I have not had any request since upgrading yesterday. I will see if it continues.

**Comment by tidusjar** [comment]
Requests are auto marked as approved if it can find it in your Plex library. 

What was the TV show? 
Do you have any TV shows with similar name (Shouldn't matter if you have advanced search)

**Comment by gadgetusaf** [comment]
Shows that I have not fixed by munal add are listed below
Murder in the First (2014) - No show in plex with similar name
Warehouse 13 (2009) -  No show in plex with similar name
Fringe (2008) -   No show in plex with similar name
The Closer (2005) - No show in plex with similar name
A.P.B.  - No show in plex with similar name
The Blacklist: Redemption 
The Catch (2016)  - No show in plex with similar name
Chicago Justice (2017)  - No show in plex with similar name
Dr. Ken (2015)  - No show in plex with similar name

**Comment by porksandwich** [comment]
This is happening to me as well.

A user requests 4 shows, they were auto-marked as approved and available, despite not being in my Plex library.  Furthermore, none of them were in Sonarr.

My install requires approval for all Shows.

I marked them as unavailable, and they went back be waiting for approval status.

I do have advanced search and episode searching enabled as well.  I can make additional requests to try to help troubleshoot if that helps?

**Comment by HamilcarH** [comment]
Awesome, thanks !

**Comment by tidusjar** [comment]
@HamilcarH @porksandwich @gadgetusaf Is this still happening with the latest release?

**Comment by gadgetusaf** [comment]
I have not seen this with new request in the latest release although I haven't had to many request come in. It appears to be working much better thanks.

**Comment by HamilcarH** [comment]
Seems to be fixed for me, however is it normal that a show still has the "processing request" status even though the whole season / show is available ?

**Comment by tidusjar** [comment]
When it says processing, it means approved but Sonarr/CP is processing it and it is not yet available

**Comment by HamilcarH** [comment]
ok so it's another issue I have because the shows are available on plex, and show as downloaded in sonarr

**Comment by tidusjar** [comment]
Yeah, that means we are not picking up the fact that you have that series, is this for everything?

**Comment by HamilcarH** [comment]
actually, no it seems to happen on the more "recent" requests.

**Comment by SuperPotatoMen** [comment]
yeah, i saw this too, if you don't download the special episode it will be processing forever.

For the most people, we don't download the special episode because sonarr don't support that to mutch.
@tidusjar can we make a change that PR don't look at the special episodes and give the request "available" mark when all of the episodes are on plex but not the special ones?

**Comment by HamilcarH** [comment]
Yeah that would be great or maybe something for later: show the episode / season already downloaded, and what's not.

**Comment by tidusjar** [comment]
I've not had time to look into this, but I don't think that I know which seasons are 'special ones'. But i've not had time to look properly.

**Comment by SuperPotatoMen** [comment]
Maybe you can check in sonarr if the episode not monitored skip that episode?

**Comment by SuperPotatoMen** [comment]
moved up the time line to the 1.10.1 release

**Comment by SuperPotatoMen** [comment]
Guys can you upgrade to the last EAP version and check if the problem still exist?
