### ISSUE TITLE
[Feature Request] Allow user to tag media as 'bad'

### ISSUE THREAD

**Issue by ira787** [tidusjar/Ombi#566]
Sometimes my users run across content on my plex server that is corrupt and text me about it.

I think the issue tracking system could be enhanced to allow users to mark individual items as 'non-playable' and maybe have an admin button next to the issue to delete the bad content and kick off a Sonarr/Couchpotato scan so the library is updated.

**Comment by tidusjar** [comment]
That's a good idea, a sort of 'resend' button.
I don't think the deletion from Plex Requests is a good idea though, I'd
rather not be responsible for managing that actual physical files.

**Comment by ira787** [comment]
I can see why managing content can get....hairy. 

I was hoping to resolve the bad content issue in one action rather than having to remote into my server and delete the content manually, then kicking off a Plex and Sonarr re-scan.

Also, PlexRequests rocks!

**Comment by pichardoSoftware** [comment]
@tidusjar Is there any way I can help you? Any ideas on how to solve it yet?

**Comment by tidusjar** [comment]
Haven't yet thought about it. Haven't had time sorry!

**Comment by pichardoSoftware** [comment]
@tidusjar That's fine, would you mind if I analyze it and tell you what I thought?

**Comment by tidusjar** [comment]
Go for it! :)
