### ISSUE TITLE
[enhancement] Some overal improvement

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#582]
I was looking at plex request, and i have some suggestions to improve the overal look and feeling
1. 1.  If season and episode is disabled in the settings panel, don't show the dropdown menu at all. You need only to hit the request button.
   ![image](https://cloud.githubusercontent.com/assets/2944704/19252411/029ef6ec-8f45-11e6-8564-244af55bcfdc.png)
2.  New admin categorys: Newletter, (move newsletter settings)  Remove Status page and move version and version check  to Plex Request page, Request settings (move all of the options to it:
   Search for Movies
   Search for TV Shows
   Search for Music
   Require approval of Movie requests
   Require approval of TV show requests
   Require approval of Music requests
   Users can view their own requests only
   Users can view their own issues only
   Disable TV requests by episode
   Disable TV requests by season
   Do not send notifications for requests that don't require approval
   Allow us to collect anonymous analytical data e.g. browser used
   ![image](https://cloud.githubusercontent.com/assets/2944704/19254105/9ce72390-8f50-11e6-93fb-689d410e780f.png)
   )
3. ability to customize some things: you can show you own logo on the top of the left.
4. Ability to customize the text "Plex Requests" on the left corner.
5.  On the requests page, use the same tags that we use by the request page and remove some text status like "Approved" , "Available" and "Issue:". You can better show that on one status instead of different statussen. Its a kind busy over there ;) If there is issue, show by tv show status "problem reported".
   ![image](https://cloud.githubusercontent.com/assets/2944704/19254309/82ce5bfc-8f52-11e6-86b6-3187ffe75f47.png)
6. Use the same tags that we have by the tv show request pages by requesting a movie.
7. give the buttons on the issue page a little more space 
   ![image](https://cloud.githubusercontent.com/assets/2944704/19254387/55045bf8-8f53-11e6-960c-55a47d9d23c9.png)
8.  If season and episode is Disable. Don't show  after a request the ability to request the same tv show again. You have allready request the whole tv show ;)

**Comment by tidusjar** [comment]
Wow thanks! They are some good suggestions 👍

**Comment by ProtoJazz** [comment]
I was actually looking at doing some grouping for UI elements in the admin menu but decided it should be a separate PR. Ill look at getting started on this tonight

**Comment by Flippage** [comment]
These are all great! If I can suggest something myself as well:
How about on the landing page, where it shows that Plex is "Online" or "Offline" - Can you show the status of the apps that are linked in to PlexRequests as well, like Sonarr and CouchPotato?

Just something I would find useful :+1:
