### ISSUE TITLE
recapture addition

### ISSUE THREAD

**Issue by DereckR** [tidusjar/Ombi#584]
Feature Request

Can you add the ability to add recapture option? Whether it being accessing the page or when user logs in. Had some recent mass amounts of spam hit my page. Think this would just add a little more security.

Thanks,
Dereck

**Comment by tidusjar** [comment]
Good idea!

**Comment by whitecollar17** [comment]
Maybe, we can make sone security options in the admin panel? 
Like :  Max Login Attempt in 5 minuts. 
Max at tv shows and tv movies  every 2 minuts.
