### ISSUE TITLE
Cannot Connect to Headphones: Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by adelatour11** [tidusjar/Ombi#596]
Plex Requests.Net Version: Version:  1.9.4
Operating System: debian wheezy
Mono Version: Mono JIT compiler version 4.6.1
Applicable Logs (from `/logs/` directory or the Admin page):

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: A. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x00029] in <607e95f78559498690f968784b884761>:0   PlexRequests.UI.Modules.ApplicationTesterModule Warn    10/15/2016 2:56:05 PM
Exception thrown when attempting to get Headphones's status:    PlexRequests.UI.Modules.ApplicationTesterModule Warn    10/15/2016 2:56:04 PM
Deserialzing Object PlexRequests.Api.ApiRequest Trace   10/15/2016 2:56:03 PM
API not enabled PlexRequests.Api.ApiRequest Trace   10/15/2016 2:56:03 PM

Reproduction Steps:
Tryning to test connection with Headphones

**Comment by tidusjar** [comment]
Any logs in headphones?

The issue with headphones is that it's very unreliable from a API point of view.
