### ISSUE TITLE
[FEATURE] Subscription system and calender.

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#599]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net

1.9.4

I have a google calendar linked up to sonarr on my landing page to show users upcoming episodes. Would be nice to see a fully integrated calender showing upcoming episodes. Also a subscription button next to TV shows to get email notifications on upcoming episodes.

**Comment by SuperPotatoMen** [comment]
Can you open a feathub item for this one?
I'm not sure if we make it, but it is a very nice idea!
