### ISSUE TITLE
Feature Request: Pushbullet/Email Notification when new release is pushed

### ISSUE THREAD

**Issue by theg1nger** [tidusjar/Ombi#60]
Title says it all.

**Comment by tidusjar** [comment]
That's not a bad idea. Should be quite easy :)

**Comment by tidusjar** [comment]
@WinstonP Who would the notification go to? The admin, so push a new notification if we find that we now have a new movie/tv show in Plex?

**Comment by OoGuru** [comment]
How about enabling the option to push to a PushBullet channel - I currently use this from PlexPy which enables me to share the channel with other users, effectively informing them about new additions automatically.

**Comment by csy7550** [comment]
How about giving each user the option to add his/her own individual pushbullet/pushover setting? So if user X requests something, user X gets a notification of his/her choice.

**Comment by theg1nger** [comment]
I like where @csy7550 is going with this. Would be great for my users if they knew when new stuff was downloaded. 

A pushbullet update to the admin would be great.

**Comment by tidusjar** [comment]
We have enabled user notifications in the form of email. This will be worked on after 1.7

**Comment by jrdnlc** [comment]
I get notified when new movies/tv shows are downloaded. Sonarr and Couchpotato have this feature
