### ISSUE TITLE
Automatically pull all "Wanted" titles from Couchpotato into PR

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#603]
Would be great for PR to automatically add everything in the couchpotato wanted list into pr (maybe as an admin request, or a dummy account, don't really have a preference on this), so that users could see that the title is already "requested" even if it was added directly to cp, or via any of cp's hooks (imdb, trakt, popular lists, etc).

**Comment by leram84** [comment]
Can i amend this request? I made this request when i was assuming the views for the request page would change. Since that likely won't be the case (which is totally understandable), this feature request would actually cripple plexrequests for me. The current view is just too large to handle everything in my couchpotato wanted list. If you do go forward with importing the cp wanted list, I would request that you pull the information, so when you search for a movie you can see it is already pending, BUT don't add it to "requests" page. This way i can still do the bulk of my adding in trakt/other couchpotato sources, and prnet just becomes a place for USER requests

**Comment by tidusjar** [comment]
So we already are doing what you are asking. When searching for a movie we already have a lot of things that are wanted in CP, I think we show 'requested' for that movie

**Comment by SuperPotatoMen** [comment]
This is a little out of the scope for know. I will close this one.
