### ISSUE TITLE
FEATURE REQUEST: Movies to auto remove from request list

### ISSUE THREAD

**Issue by armss001** [tidusjar/Ombi#606]
Once a movie becomes available on PLEX, could it remove itself from the requested list? It is not needed here as users can search for the movie again to report a problem. Would like to keep the request list as tidy as possible. 

Also could this list store the sorting option, I would like it to sort by release date automatically (closest dates at the top).

**Comment by SuperPotatoMen** [comment]
Duplicate request: https://github.com/tidusjar/PlexRequests.Net/issues/338

**Comment by SuperPotatoMen** [comment]
Well i make a mistake, i'm sorry @armss001. planned for 2.0
