### ISSUE TITLE
[Feature Request] Support Mattermost notifications

### ISSUE THREAD

**Issue by gravufo** [tidusjar/Ombi#611]
It would be really nice to have Mattermost integration, just like the Slack integration that's already present.

Technically, Mattermost is compatible with Slack-like API, so the integration _theoretically_ shouldn't be too difficult (that obviously always depends hehe).
Here is some doc if you need: [Slack Compatible Webhooks](https://docs.mattermost.com/developer/api.html#slack-compatible-webhooks)

Let me know what you think!
Thanks

**Comment by justinbaciao** [comment]
Mattermost is great. Would love to see support for it added to Ombi.

**Comment by anonaut** [comment]
Hey guys, i implemented a working version for mattermost based on the slack class. I'll try to get a pull request working.

**Comment by PotatoQuality** [comment]
Live in Def branch
