### ISSUE TITLE
[Feature Request] Import Plexrequests-Meteor Database

### ISSUE THREAD

**Issue by AngryNoodlez** [tidusjar/Ombi#613]
Hi,

I've been using the PlexRequests.Net for a short while and feel the only thing stopping me switching over from Plexrequests-meteor is that I can't find a way to import the database for my request history.

Is this something that is currently possible? Or something you would look to add in a future release?

Cheers!
~Mat

Ps. Love your work with the .NET version of PlexRequests! Some incredibly new features and my users have thoroughly enjoyed using this version I have running in Dev.

**Comment by tidusjar** [comment]
I can look into it, but we require a lot of information for a single request so I doubt we can do it. But i shall look into it!

**Comment by SuperPotatoMen** [comment]
@AngryNoodlez 
Can you open a feathub item for us on this one?
If it more then 1 request we can make it :)
