### ISSUE TITLE
Ability to force Plex Availablity Checker

### ISSUE THREAD

**Issue by Auwen** [tidusjar/Ombi#627]
The default setting for the Plex Availability Checker is 60 minutes and is fine for that. But _every so often_ I'd like to force that check so that my friends get notified sooner that some media is available.

**Comment by SuperPotatoMen** [comment]
Do you like to have a button to force it in the admin panel?

**Comment by Auwen** [comment]
Yup, that'd be a good place for it. I really like how Sonarr handles the scheduled tasks:

![image](https://cloud.githubusercontent.com/assets/12058855/19819145/e790155c-9d18-11e6-9468-d2b8eddc55f0.png)

Not sure if you could follow that exactly, as the Task intervals within PR are customization, but it may be a good starting point.

**Comment by SuperPotatoMen** [comment]
Well i think that is a great idea.  If we can force every task in the admin panel.
