### ISSUE TITLE
TV show request is returning extra seasons

### ISSUE THREAD

**Issue by mimminito** [tidusjar/Ombi#628]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.6
#### Operating System:

Ubuntu
#### Mono Version:

4.2.3
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

http://pastebin.com/ak32z63X
#### Reproduction Steps:

Request Once Upon a Time. If you select a specific season it will monitor them correctly in Sonarr. If you select to monitor the latest then it tries to monitor the "latest" season in the list. For the provided example it lists 123 seasons and tries to monitor the 123rd.

**Comment by SuperPotatoMen** [comment]
So, If I understand correct,  If you Request the last Episode PlexRequests.Net set a monitoring for the whole season om sonarr?

**Comment by SuperPotatoMen** [comment]
@mimminito So, If I understand correct, If you Request the last Episode PlexRequests.Net set a monitoring for the whole season on sonarr instead of a single episode?

**Comment by mimminito** [comment]
Sorry took so long to reply.

No, what happens is when I request "latest" season, the data that is returned is not correct. If you check the pastebin link I added, the actual latest season is 6, but its returning 123 seasons for some reason. This means its tried to monitor season 123 instead of season 6, but season 123 does not exist.

**Comment by SuperPotatoMen** [comment]
@tidusjar little mistake with the rollback?

**Comment by tidusjar** [comment]
I took a quick look, I cannot see how this is happening, maybe something wrong with the data on TVMaze
