### ISSUE TITLE
Possibly Intergration with Trakt.Tv for FlexGet

### ISSUE THREAD

**Issue by Aireezz** [tidusjar/Ombi#636]
So I know absolutely 0 about whether this would or wouldn't work, but I have found myself and many others on the interwebs disliking couchpotato. I've swapped to FlexGet, and while it's not as user friendly it does a better job (at least IMO) than couchpotato. I don't know if you could intergrate a way to add the request to either a trakt.tv wishlist or a FlexGet list so people who use that (for both tv and/or movies) can more easily use it alongside PlexRequests.Net

**Comment by tidusjar** [comment]
This is a good idea, add everything from the wishlist into Plex Requests?
Sounds good

**Comment by Aireezz** [comment]
Well, you could do that. (I wasn't thinking of it like that, but I'm sure many people use trakt.tv to keep track of things, and it would be nice to have it in one place.) I mean't send the PlexRequest request to the trakt.tv or FlexGet list so FlexGet can download it as Sonarr or Couchpotato would.

**Comment by tidusjar** [comment]
Ah, so the opposite, send requests to trakt. I'll take a look at their API
and see what can be done.

**Comment by leram84** [comment]
wait... does "planned" mean that you checked the trakt api, and this is possible?? I would be VERY excited for this feature as well. its the one missing link that would let me run PR and trakt side by side with couch, and get the benefits of both!

(and yeah, the direct trakt to PR sync isn't really necessary cause its already handled by the Trakt to couch to PR sync... but pr to trakt!! that would be excellent)

**Comment by tidusjar** [comment]
Sorry, I've not yet looked.

The plan is to send the requests to CP and Trakt, but as I mentioned, not looked yet :)

I would only send the items requested inside Plex Requests too.

**Comment by SuperPotatoMen** [comment]
@leram84 No i'm sorry for miss understanding, i set a label planned beceause we look at this by the the release of v2.1
I help @tidusjar  a little with doing the release and  resources planning beceause he has limited time for coding.

**Comment by leram84** [comment]
no worries, i just got excited :))

and @tidusjar you're right, adding everything from cp to trakt doesn't really make sense for PR (and its not really that important either... the pr stuff is what really matters). When you do get the time for this, you might want to check out the [plex trakt scrobbler](https://github.com/trakt/Plex-Trakt-Scrobbler) since that has a (beta) feature to keep playlists (plex) and watchlists (trakt) in sync... might be give you what you need from trakt's api.

**Comment by tidusjar** [comment]
Thanks!!

**Comment by PhyberApex** [comment]
Maybe I'll try to bring myself into this as I plan to contribute to a open source project for a long time. Maybe this will be my first PR :)

**Comment by SuperPotatoMen** [comment]
@PhyberApex that will be fantastic! If you need anyhelp, ask @tidusjar for support :)

**Comment by tidusjar** [comment]
@PhyberApex Yeah if you need any help just let me know.

I think the requirements of this has changed slightly now there are more than 1 CP alternative (Radarr, Watcher).

So I guess maybe expand this to a two way sync... Let's start with send requests to Trackt then i'll raise another feature later to sync Trackt to Ombi.

**Comment by Glynnryan** [comment]
@tidusjar have you found a way to get the requests between Trakt and Ombi working by any chance or custom script to test?

**Comment by tidusjar** [comment]
No I've not had a chance yet. Priority is currently the rewrite. Plus this : https://github.com/tidusjar/Ombi/issues/1405

**Comment by gled-rs** [comment]
To get flexget working, a simple export of the list in csv or rss would be enough, as Flexget allows parsing such sources as an input plugin.

**Comment by snickers2k** [comment]
maybe someone here to finish this up? https://github.com/Flexget/Flexget/pull/2109/files
altough ombi should import trakt_watchlist on it's own, the workaround with flexget could work aswell.

**Comment by Aireezz** [comment]
Are you talking about using trakt.tv lists to import movies like sonarr and radarr already support, but having ombi flag that title as requested? Why not just import the list to sonarr/radarr and ombi would see it as requested from there? Seems like an extra step unless I'm misunderstanding

**Comment by snickers2k** [comment]
@Aireezz because i don't have radarr/sonarr. Working with Flexget and JDownloader.
So for me radarr/sonarr would be an extra step ;)

**Comment by Aireezz** [comment]
So you want the list from trakt.tv to go to ombi, to then import into flexget?

**Comment by snickers2k** [comment]
aren't you using flexget too? seems you are missing the whole combination with trakt, my friend ;)

okay, lets go from zero.
https://flexget.com/Plugins/List/trakt_list 

this allows for things like adding trakt most "popular" or "trending" automatically to flexget for example. amount can be edited.

plus trakt being my Database for everything. i sync plex, emby, flexget, trakt-android-app "cinetrak" and some more, with all it's "collected", "watchlisted" and "watched" status - with trakt being the main point.

there is no way i would use ombi or radarr/sonarr as an alternative for that.

so the only problem is requests from my shared-users... where ombi comes in place.

So having most of the movies already in my trakt-watchlist, 99% of requested movies by shared-users with Ombi would just make no sense.

... makes sense? :)

**Comment by Aireezz** [comment]
I used flexget for a short while, but once radarr came out I stopped. I do understand what you're saying now.
