### ISSUE TITLE
Users unable to log in with Plex email address. Must use actual username.

### ISSUE THREAD

**Issue by iamthemachine** [tidusjar/Ombi#640]
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Username "myplexuser@gmail.com" attempting to login
Using password
Need to auth and also provide pass
Correct credentials, checking if the user is account owner or in the friends list
Friends list result = False
Username "myplexuser" attempting to login
Using password
Need to auth and also provide pass
Correct credentials, checking if the user is account owner or in the friends list
Friends list result = True
We are authenticated! Setting session.
```

#### Reproduction Steps:

Any user attempting to log in with their email address associated with their Plex account are unable to as the PlexRequests.UI.Modules.UserLoginModule does not consider them on my friends list. Using their actual Plex username works fine.

**Comment by tidusjar** [comment]
Yeah, this is intended behaviour. I'll add in the option to support the email address
