### ISSUE TITLE
[Feature Request] Sending Custom Alerts to all Friends/Custom Alert Types

### ISSUE THREAD

**Issue by jpartain89** [tidusjar/Ombi#653]
Would it be possible at all if we would be able to have a "I just added Plex Requests and you should check out the link here!" kind of email? Would really make the addition a ton easier, plus if we were to want an "onboarding" routine for new friends added to Plex, this would honestly be the best way I could think of handling it.

And, other than adding our friends to our slack channels, why not allow them to add their own slacks/custom emails/pushbullets/etc to their profiles? This way the info to them is as ubiquitous as is to us admins.

**Comment by SuperPotatoMen** [comment]
Nice idea,  I'm not sure if we can at this one in 2.1 but maybe it is something for 2.2 :)

**Comment by SuperPotatoMen** [comment]
@jpartain89 1 question, do you mean a custom bulk message to all of you plex request users?

**Comment by SuperPotatoMen** [comment]
See pull request: https://github.com/tidusjar/Ombi/pull/1047
