### ISSUE TITLE
Run PlexRequests over SSL/HTTPS

### ISSUE THREAD

**Issue by heartisall** [tidusjar/Ombi#66]
Since I have Plex requests out on the web and users are logging in with their passwords it would be nice to send this over https so PWs aren't being sent in plain text.

**Comment by tidusjar** [comment]
Yes, Will look into it. I don't think it will be in the next release as I already have a list of things planned for it. https://github.com/tidusjar/PlexRequests.Net/milestones/Release%20v1.5.0

**Comment by heartisall** [comment]
No worries, 1.5 looks good. Pretty excited with how quickly this is being improved on. Great work

**Comment by tidusjar** [comment]
Well I get excited about things like this and end up spending a lot of time on them, plus when people are interested it makes me want to do it more!

**Comment by heartisall** [comment]
Yea I hear that, well it's much appreciated. My family/friends have been pretty blown away with being able to request things and have it show up so quickly.

**Comment by tidusjar** [comment]
Well that's what I want to hear! If you/they have any suggestions as you know, feel free to suggest them :+1:

**Comment by noahruss** [comment]
In the mean time I've been using stunnel and it works wonderfully

**Comment by heartisall** [comment]
@tidusjar Was this added to the new release? If so how do I enable it? Thanks for all the hard work

**Comment by tidusjar** [comment]
Sorry I wasn't suppose to close this issue! I've currently only turned the external links to HTTPS. This will be next!

Apologies.

**Comment by heartisall** [comment]
Awesome, You're the man!

**Comment by taytortots** [comment]
Just curious if there was any update on this.

**Comment by tidusjar** [comment]
Sorry, I've not had time to look Into this yet. It will get done. I was thinking about adding it into the next release but I'm adding tv episode requests.

**Comment by taytortots** [comment]
Sweet, I'm just glad to know it's coming. :)

TV Episode requests sounds great, too.

**Comment by Electronickss** [comment]
Update on this?

**Comment by tidusjar** [comment]
Not yet, been quite busy recently. This is not as important as some of the other issues as I know people are using NGINX and setting it as HTTPS from there (I don't know how that is done)

**Comment by taytortots** [comment]
@Electronickss I've got HTTPS working by hiding it behind Apache. I know people have gotten it to work with NGINX, too, like mentioned above.

**Comment by Electronickss** [comment]
Yup just going to use nginx. I was just going to forward a port to it so it was up while I worked to get nginx production but it looks like getting it out to the Internet will just have to wait

**Comment by StrayanDropbear** [comment]
Would be nice if HTTPS could be apart of PlexRequests though

**Comment by tidusjar** [comment]
@StrayanDropbear I agree! It will be part of PlexRequests... At some point 😄

**Comment by StrayanDropbear** [comment]
Haha that's fine, take your time.

**Comment by ericgcollyer** [comment]
Just putting in my two cents. I'd love to see this feature implemented.

**Comment by SuperPotatoMen** [comment]
planned for the 2.0 version.

**Comment by seanvree** [comment]
Hey guys! Great job on this! Just wondering if you guys were still planning on putting this out on 2.0? Any time frame for 2.0?  Weeks? Months?  No rush! First world problems!

Cheers gents.

**Comment by tidusjar** [comment]
I need to release 2.0 soon, but it won't contain everything in the 2.0 list

**Comment by cvockrodt** [comment]
I'd love to see https implemented

**Comment by kingsleyadam** [comment]
+1 for this requests. @tidusjar, great work man. This is an amazing application.

**Comment by joscross49** [comment]
Definitely would love to see this get implemented! Keep up the good work!

**Comment by jdenson** [comment]
Looking forward to this. Thanks for all the hard work @tidusjar

**Comment by CyberMew** [comment]
What is the update on this?

**Comment by tidusjar** [comment]
There is no update. I've not started it yet, no plan to start it within the
next few weeks. I'll be working on an auto updater and reworking the sonarr
integration next.

**Comment by StrayanDropbear** [comment]
Honestly this isn't a huge issue, currently using nginx for reverse proxy with ssl and it works fine. Take your time on this one.

**Comment by CyberMew** [comment]
For the less technical ones like me is there any tutorial on how to enable "ngix for reverse proxy with ssl" for my users?

**Comment by StrayanDropbear** [comment]
Are you running ombi on windows or linux? this tutorial will work for ombi https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

**Comment by chrisausbun** [comment]
@tidusjar, I'm running windows 10 and would greatly appreciate an easy how to for setting up nginx or something else that will ensure all the Ombi traffic is forced to go through https.



On Mar 11, 2017, at 3:47 AM, Michael <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you running ombi on windows or linux? this tutorial will work for ombi https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

**Comment by cvockrodt** [comment]
https://developers.coveo.com/display/public/SearchREST/Configuring+HTTPS+Reverse+Proxy+in+IIS

**Comment by seanvree** [comment]
I've got this working fine on IIS with reverse proxy and SSL. 

You have to make sure in IIS that you create a virtual directory. DO NOT CREATE an application for it, then you create you rewrite rule for that virtual directory only.  Make sure you disable all the other inherited rules. 

So, would look something like this:
WWWRoot\
\Plexreqeust (Virtual Dir)
\web.config:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <defaultDocument>
            <files>
                <remove value="index.html" />
            </files>
        </defaultDocument>
        <rewrite>
            <rules>
                <clear />
                <rule name="ReverseProxyInboundPlexRequest" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://localhost:3579/plexrequest/{R:1}" />
                </rule>
            </rules>
            <outboundRules>
                <clear />
                <rule name="ReverseProxyOutboundPlexRequest" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Form, Img" pattern="^http(s)?://localhost:3579/plexrequest/(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="true" />
                    <action type="Rewrite" value="http{R:1}://yourdomainname.com/{R:2}" />
                </rule>
            </outboundRules>
        </rewrite>
        <security>
            <authentication>
                <anonymousAuthentication enabled="true" />
            </authentication>
        </security>
    </system.webServer>
</configuration>

**Comment by chrisausbun** [comment]
Thanks for the recommendations.



On Mar 11, 2017, at 8:17 PM, seanvree <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got this working fine on IIS with reverse proxy and SSL.

You have to make sure in IIS that you create a virtual directory. DO NOT CREATE an application for it, then you create you rewrite rule for that virtual directory only. Make sure you disable all the other inherited rules.

So, would look something like this:
WWWRoot
\Plexreqeust (Virtual Dir)
\web.config:

**Comment by seanvree** [comment]
Also, make sure you enable anon auth in the vir dir so you can simply rely on PLEX auth.  Otherwize, if a user hit YOURDOMAIN.com/plexrequest/ then they would have to auth with IIS, and then again with PLEX.

Just some tips.

**Comment by carnivorouz** [comment]
+1 for this.  Thanks for the great work.

**Comment by SuperPotatoMen** [comment]
Workaround is setup a reverse proxy server

**Comment by SuperPotatoMen** [comment]
You need a domein anyway If you use the ssl option..

**Comment by ukdeveloper** [comment]
Hi, I'm pretty new to this. Could someone explain exactly what this is? Is it purely a "request service" where users can ask you to add something to your plex, or is it fully automated where users can request something and its automatically added... somehow.

**Comment by PotatoQuality** [comment]
@ukdeveloper this is not the right place to ask something like that. See our forums for more support.

**Comment by ukdeveloper** [comment]
oh sorry. like I say I'm very new to this but eager to learn. Could you paste me the forum address?

**Comment by tidusjar** [comment]
@ukdeveloper https://forums.ombi.io/

**Comment by mmedic** [comment]
@seanvree Could you please re-publish your web.config? Seems like your patebin post is expired. I am trying to do the same - reverse proxy to PlexPy and PlexRequests through IIS. Thanks!

**Comment by seanvree** [comment]
@mmedic  Sorry, just saw your comment.  I assume you've figured it out, if not:

https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples

**Comment by tidusjar** [comment]
@goku-son there are currently no plans for native SSL

**Comment by Froodle** [comment]
Any updates to this? is it still not planned/implemented? seems like many people want this feature

**Comment by ericgcollyer** [comment]
> Any updates to this? is it still not planned/implemented? seems like many people want this feature

I think most people who want to run Ombi with SSL implement reverse proxies. Especially since Ombi runs in combination with other services, this makes much more sense.
