### ISSUE TITLE
Constant crashes on CentOS 7 when logged in as admin

### ISSUE THREAD

**Issue by Do-while-Bacon** [tidusjar/Ombi#660]
#### Plex Requests.Net Version:
1.9.6

#### Operating System: 
Centos 7.2.1511

#### Mono Version:
4.2.4

#### Applicable Logs (from `/logs/` directory or the Admin page):
Nov  4 22:35:54 www mono: Unhandled Exception:
Nov  4 22:35:54 www mono: System.ObjectDisposedException: Cannot access a disposed object.
Nov  4 22:35:54 www mono: Object name: 'System.Threading.ManualResetEvent'.
Nov  4 22:35:54 www mono: at System.Threading.WaitHandle.CheckDisposed () <0x7f727a89c250 + 0x00050> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.EventWaitHandle.Reset () <0x7f727a895c50 + 0x0003a> in <filename unknown>:0
Nov  4 22:35:54 www mono: at (wrapper remoting-invoke-with-check) System.Threading.EventWaitHandle:Reset ()
Nov  4 22:35:54 www mono: at System.Runtime.Caching.MemoryCacheStore.BlockInsert () <0x4163d840 + 0x00021> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Runtime.Caching.CacheEntryCollection.FlushItems (DateTime limit, CacheEntryRemovedReason reason, Boolean blockInsert, Int32 count) <0x4163d5c0 + 0x00083> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Runtime.Caching.CacheExpires.FlushExpiredItems (Boolean blockInsert) <0x4163d4c0 + 0x0003f> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Runtime.Caching.CacheExpires.<EnableExpirationTimer>m__0 (System.Object o) <0x4163d320 + 0x00013> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.Timer+Scheduler.TimerCB (System.Object o) <0x7f727a89a960 + 0x00147> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7f727a6fb520 + 0x0002f> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x7f727a6f9b20 + 0x001d6> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7f727a6fb3a0 + 0x00008> in <filename unknown>:0
Nov  4 22:35:54 www mono: [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List`1' threw an exception. ---> System.Threading.ThreadAbortException:
Nov  4 22:35:54 www mono: --- End of inner exception stack trace ---
Nov  4 22:35:54 www mono: at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x41333480 + 0x00083> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x41333010 + 0x0021a> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x41332fd0 + 0x00028> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x41332f10 + 0x00061> in <filename unknown>:0
Nov  4 22:35:54 www mono: at System.Threading.ThreadHelper.ThreadStart () <0x41332e80 + 0x00039> in <filename unknown>:0
Nov  4 22:35:54 www systemd: requests.service: main process exited, code=exited, status=1/FAILURE
Nov  4 22:35:54 www systemd: Unit requests.service entered failed state.
Nov  4 22:35:54 www systemd: requests.service failed.

#### Reproduction Steps:
Start plexrequests, navigate to the search page, log in as admin, click around a few different menus and pages. It will crash on me after about 3-5 menu clicks.

#### My setup specifics:
Using baseurl with nginx reverse proxy.
SELinux is disabled
Landing page is not enabled

Edit: I have updated to mono 4.6.1 and the problem persists. I have also tried running the application as root instead of a regular users to see if there is a permissions problem -- no luck.

**Comment by SuperPotatoMen** [comment]
I'm not a linux guy, i can't help you with this one :(

**Comment by tidusjar** [comment]
This is defiantly a mono issue, since in that whole stacktrace there is none of my code...
I'm not sure what to suggest here...

**Comment by Do-while-Bacon** [comment]
Updated to mono 4.6.2 but it did not help. I also tried installing a number of supporting packages: mono-addins, mono-complete, monodevelop, xsp, referenceassemblies-pcl which was suggested in this issue 521 for the same error: https://github.com/tidusjar/PlexRequests.Net/issues/521

I haven't had any crashes of Sonarr, which is using mono on the same system. I don't know what else to try on my end..

**Comment by SuperPotatoMen** [comment]
Can you use the last version. Maybe it help. We can't support you on this one. Sorry :(
