### ISSUE TITLE
[Feature] Forgot Password Link

### ISSUE THREAD

**Issue by bromanguydude** [tidusjar/Ombi#673]
I have some forgetful, not so computer savy people using my server like the rest of us. A {Forgot Password} link on the authentication page would probably helpful to some just so they dont have to link back out to Plex.tv and find where the reset page is.

Happy streaming.

-BMGD

**Comment by SuperPotatoMen** [comment]
Planned in the 1.10.1 release

**Comment by SuperPotatoMen** [comment]
@bromanguydude  1 question, do you mean a custom bulk message to all of you plex request users?

**Comment by bromanguydude** [comment]
@SuperPotatoMen Nah, just a link to (https://www.plex.tv/sign-in/password-reset/) that is displayed on the Plex Requests Login page as "Forgot Password?".

**Comment by SuperPotatoMen** [comment]
@bromanguydude lol i posted a replay on the wrong issue. i understand. planned for releasing it on version 1.10.1

**Comment by th0mk** [comment]
I like how this went from version to version, and then eventually you just closed it lol
