### ISSUE TITLE
Logging into PlexRequests logs me out of Sonarr (vice versa)

### ISSUE THREAD

**Issue by BuggeringHell** [tidusjar/Ombi#697]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Debian 8.6

#### Mono Version:
Stable 4.6.1.3

Using Sonarr and Plexrequests under the same installation of Mono creates an annoyance where I have to log back in to either service if using forms to authenticate.

**Comment by tidusjar** [comment]
Hmmm, Plex Requests and Sonarr use the same backend technology, and we were using the same authentication provider (provided by the NancyFx framework), but in the next release I have implemented my own authentication provider (for the user management), so this may possibly fix it. Not sure though.

**Comment by SuperPotatoMen** [comment]
@BuggeringHell does you have still this problem?
