### ISSUE TITLE
Document root location

### ISSUE THREAD

**Issue by CodaAmok** [tidusjar/Ombi#712]
Hello

Congrats on new born

Quick question, trying to set up letsencrypt with nginx for reverse proxy and for the challenging to work I need to store a file in the document root. Where is it?

Cheers, coda

**Comment by CodaAmok** [comment]
Not sure what more info you need... 

certbox (LetsEncrypt) writes to the document root of a webserver (url.com/.well-known/....) and reads what it wrote as a method to ensure the user generating the cert actually owns or has necessary access to the web server. 

Another way to ensure the users owns the webserver is for letsencrypt to output a string, instruct user to save it in a file accessible by url.com/.well-known/..../file.txt then read its contents and spit out cert. I want to use this option because my nginx reverse proxy isn't on the same host so I can't tell certbot to go to /var/www/website as it's not local.

I've spent some time looking through the folder structure of this but I can't figure out where the root of the webserver is. It's apparent that it is all modular.

**Comment by carnivorouz** [comment]
+1 this.  I have nginx working now to redirect to https but can't for the life of me figure out how to get certbot (letsencrypt) to work.  As CodaAmok mentioned, the webroot path is needed for the process.
