### ISSUE TITLE
Priority/Notes When Requesting

### ISSUE THREAD

**Issue by Aireezz** [tidusjar/Ombi#713]
I think it would be cool to allow the user requesting something to give it a 'priority' if you would. For ex. if they would like to see it on Plex but have already watched it it, or think others would enjoy it because of other shows on Plex the user could set the priority to a 1 of 3, or something along those lines. If they haven't seen it, and would like to they could set it to a priority 3 of 3 or something, and/or could add notes to the request, for example 

Shameless (2011)
TV show status: Running
Request status: Pending approval
Priority: 3

Release Date: 6 years ago

Seasons Requested: All
Requested By: Aireezz
Requested Date: a month ago

-----------------------------

Dragon Ball GT (2005)
TV show status: Ended
Request status: Pending approval
Priority:1
Note: I have watched this, and think it would be a good show to add  to your collection when the space is available.

Release Date: 12 years ago

Seasons Requested: All
Requested By: Aireezz
Requested Date: a month ago

**Comment by SuperPotatoMen** [comment]
For Ombi it is nice to be easy to use. In my opion that doesn't fit right now to make systems with priority. 
This is something for on feathub to look if this is populair for making it.

I close this one for now.
Can you open a item on feathub if you like it if we make it in ombi?
