### ISSUE TITLE
[feature request] notifications for resolved issues

### ISSUE THREAD

**Issue by kamilkrzeminski** [tidusjar/Ombi#714]
Hi, could you include a functionality to notify the person that filed an issue once it is resolved?

**Comment by tidusjar** [comment]
We can!

**Comment by kamilkrzeminski** [comment]
:+1:

**Comment by SuperPotatoMen** [comment]
Planned in the notification update (2.1)

**Comment by SuperPotatoMen** [comment]
See: https://github.com/tidusjar/Ombi/issues/554
