### ISSUE TITLE
[REQ] Discord Webhook Support

### ISSUE THREAD

**Issue by karbowiak** [tidusjar/Ombi#739]
Hi there!

Discord has a Webhook just like Slack does now, and it's even Slack compatible if you add /slack to the end of the webhook url.

Sadly tho, PlexRequests.Net doesn't obey the url, and tries to use it for Slack.
Any chance of a catch to fix so that if the url contains Discord in it, it'll prod Discord instead of Slack? :)

**Comment by tidusjar** [comment]
Interesting, 

Personally, i'd rather add a new section rather than hacking the Slack notification to do this.

But Discord support shall be done!

**Comment by karbowiak** [comment]
Woohoo \o/

Either way would work really :)

More info available here: https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
and https://discordapp.com/developers/docs/resources/webhook (Probably most interesting)

**Comment by tidusjar** [comment]
Thanks!

**Comment by SuperPotatoMen** [comment]
Planned  in the big notification update

**Comment by Merckle** [comment]
Id love to see this working as well. I was playing around with it but couldnt seem to ever get it working with out getting errors

**Comment by SuperPotatoMen** [comment]
It is now live in the 2.1 version!
