### ISSUE TITLE
[UI] If you only give the option to add entire tv series, there's no need for a drop down

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#742]
Since i only allow the addition of entire shows, there is no point to having the drop down and then clicking "all seasons". Just clicking "add show" (like it is for movies) should be sufficient no?

**Comment by tidusjar** [comment]
You mean when you configure the settings to only allow it? Then yeah good point

**Comment by leram84** [comment]
yup

**Comment by SuperPotatoMen** [comment]
Fixed in the 2.0 release. Thanks to @mhann for the fix 👍
