### ISSUE TITLE
Beta feature "Update Automatically" hasn't worked ever since first introduced

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#747]
#### Plex Requests.Net Version:
Dev 1.10.1041

#### Operating System:
Windows 10 Home

Whenever I attempt to use the Beta feature "Update Automatically", it never works. I've tried using this feature with no luck ever since it was first introduced. I even though it might be related to having to unblock the .zip folder before extracting, so I changed it to automatically unblock once it's been downloaded and still no luck.

If you need any logs, please let me know and I'll send them over. Thanks.

**Comment by SuperPotatoMen** [comment]
intresting, i'm using it too and it work fine on my windows 10 setup. Can you send some logs when you using it?

**Comment by chrisausbun** [comment]
So, I didn't really notice anything in the error logs referring to the setup but here's what I had for my error logs:

Begin executing GetProfiles call to Sonarr for quality profiles	PlexRequests.Core.Setup	Info	12/8/2016 12:55:19 PM
Begin executing GetProfiles call to CouchPotato for quality profiles	PlexRequests.Core.Setup	Info	12/8/2016 12:55:19 PM
Begin executing GetProfiles call to Sonarr for quality profiles	PlexRequests.Core.Setup	Info	12/8/2016 12:46:40 PM

Please let me know if there are any other logs you needed and how to get them just to be on the safe side. Thanks.

**Comment by chrisjace** [comment]
Not working either for me on 1.10.1041 (Mac OS X). I get the following error: The file /Users/jmassot/mono PlexRequests.Updater.exe does not exist. Issue with the paths to both mono and PlexRequests.Update.exe files. Anyway to get this fixed? Thanks!

**Comment by SuperPotatoMen** [comment]
moved up the time line to the 1.10.1 release

**Comment by Foebik** [comment]
On 1.10.1 and this also happened to me on 1.10. But I am unable to even get to the status screen. This is what I get as an error.

```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'PlexRequests.Core.SettingModels.SystemSettings' **does not contain a definition for 'UpdateAvailable'**
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

Nothing shows in the error logs...

**Comment by tidusjar** [comment]
Chris, for the update from 1.9.x to 1.10.0. It required a clean install (no
overwriting)

**Comment by SuperPotatoMen** [comment]
@Foebik you need to do a clean install  (no overwriting), see the patch notes

**Comment by Foebik** [comment]
Understood, where is the database file located again so I can at least have the old info repopulated? Or is that something that needs to be build new too?

**Comment by SuperPotatoMen** [comment]
@Foebik you can find it in the root directory of plexrequest.net 
Search for the file called: "PlexRequests.sqlite"

**Comment by Foebik** [comment]
Yeah, SuperPotatoMen, you were too quick for me. I had just updated my comment above. :)

**Comment by SuperPotatoMen** [comment]
Master issue is now: https://github.com/tidusjar/Ombi/issues/236
