### ISSUE TITLE
[Feature Request] Report issue with specific episode or season instead of entire show

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#762]
My apologies if this is a duplicate request, but I've had users that have had issues with either a specific episode or season of a TV show and they can't report it without reporting an issue with the entire show. So, whenever I've had a user do that, I've had to tell them when reporting issues with TV shows, please report issue as other and specify which episode or season has an issue. 

I think it'd be super awesome if when reporting issues with TV shows there was something that popped up and asked the user to specify whether or not the issue is with the series itself, a season, or a specific episode. I understand that this can be very intensive and so if it'd be easier, I'd even be happy with something where they type in the season and episode so it doesn't have to query the Plex database. I was thinking something like when you click report an issue, instead of the choices popping up there could be a window that pops up with the information below:

Entire Series: Yes or No

Entire Season: Yes or No

Season: 

Episode:

Issue (Please check your issue below or click other and specify your issue if it's not listed):

You could also just make the maximum values 99 for the season and 9999 for the episode. And, if they were to click yes for entire series, it would blank out the season and episode fields and if they select entire season, it would blank out the episodes field.

**Comment by tidusjar** [comment]
Yeah i'm aware of this, not sure if there is an issue open but I will be looking to improve the issues area in the next few releases.
