### ISSUE TITLE
[Feature Request] Multi language movie database search

### ISSUE THREAD

**Issue by chrisjace** [tidusjar/Ombi#765]
It would be nice to get a search feature allowing to search movie database to pick up original movie titles in other languages than just English, to address the following context: several movie libraries in Plex, including a library with English movies, and a library with French movies, for instance. I'd like to be able to also identify the French movies when doing a search, and not only the English movies. I guess this may mean pointing to movie database with language set to English and French, in this case? Or perhaps it is more a matter of being able to add another movie database search source for the French movies? Not sure if I am clear enough of what I am after?

**Comment by SuperPotatoMen** [comment]
@chrisjace 
Hi, can you make for this one a feathub item?
If we have more request we can more time on makeing it!
