### ISSUE TITLE
Newsletter showing more than recently added items

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#767]
#### Plex Requests.Net Version:
1.10.1067

#### Update Branch:
Development

#### Operating System:
Windows 10 Home

Whenever the newsletter is sent, it's not just the recently added items on it. It's showing me items that have been added more than a week or two ago, it's showing everything for a couple different libraries that I created probably more than a month ago, and some of the items aren't correctly displayed. I'm not too sure if this has already been planned, but I think it'd be super helpful in this situation if I could specify which Plex libraries it pulled from. For example, these are all my categories below but all I ever get new movies for is mainly kids movies, movies, and tv shows. Everything else is few and far between. I also attached a zip file with the newsletter that was sent to admin so you could see.

![plex libraries](https://cloud.githubusercontent.com/assets/22944072/21080997/d66c987e-bf71-11e6-99d3-3594fef88a16.png)

[New Content on Plex!.zip](https://github.com/tidusjar/PlexRequests.Net/files/644517/New.Content.on.Plex.zip)

**Comment by tidusjar** [comment]
So with the recently added, the way I get the content is just by calling the Plex Api (recently added is in the api) and then just format the results from the api.

There is defiantly some improvements that could be done, since I am caching the flex content in the database I could now use that, also allowing you to select the libraries to include is an excellent idea.

**Comment by rudyvarner** [comment]
I am getting things that are not even in my library along with my own items when I send a test newsletter. Is this by design?

**Comment by tidusjar** [comment]
All I do is call the Plex API and just format the results. 

I'll be looking to improve this soon. Since we store the content. I can make the newsletter more customisable.

**Comment by rguyor2** [comment]
I'm seeing the same thing. I checked my plex library for them and they're definitely  not there. Here are a some examples that appear in mine (so we can see if they're the same):
The Man Who Knew Too Much 1956
Life in Loops (A Megacities RMX) 2006
The Endless Summer 1966
Sunday in August 2004
9 Songs 2004
The Hustler 1961

It appears to be only Movies that are listing these strange extras.

**Comment by rudyvarner** [comment]
Still getting items not in my library and also a ton of broken links.  Are these movies in your library and somehow have gotten added to the Ombi db?  Or maybe it calling them from someone else's library?

![ombi_newsletter](https://cloud.githubusercontent.com/assets/5005529/21850461/ae808332-d7d8-11e6-9b51-508910f5b9e8.png)

**Comment by tidusjar** [comment]
So what happens is we grab the IMDB id out of the Plex metadata and then look that up on either TheMovieDB or TVMaze and display the output. So it could either be we are not parsing it correctly, or the mapping is incorrect on TheMovieDB/TVMaze.

I am not going to spend much time looking into this as I plan to redesign it to use our database instead of Plex (since we cache all of the Plex DB content anyway).

**Comment by jneljeff** [comment]
So I just want to make some clarification here.  As it is now, the newsletter is not reporting only things that were added in the last 7 days, but the last X number recent items provided by the API?

**Comment by tidusjar** [comment]
Basically everything provided by the API. I'll be changing it to look at
the data we have cached in Ombi so we will never show the same thing twice

**Comment by tb2007** [comment]
This would be a good re-design.

My movie section doesn't change much, so I'm getting the same 10+ movies that the API returns cluttering the newsletter,

My TV section changes a lot, so the API data is good.  The only bad part is its at the bottom of the newsletter.
