### ISSUE TITLE
Re brand Plex Requests :(

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#775]
Plex has asked me to remove the association with Plex.

We need a new name 😢

**Comment by chrisausbun** [comment]
That's terrible news :(. Well, you could always try to rename it so it sounds the same but it's not spelled the same. Like, Plecks or something else. Or, you could replace Plex Requests with My Requests or just Requests. Yeah, looking over PlexRequests I'm thinking that renaming it to My Requests would probably be the least confusing to the users who all of us have that use Plex Requests.

On Dec 14, 2016, at 12:39 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Plex has asked me to remove the association with Plex.

We need a new name ?

-

**Comment by chrisausbun** [comment]
Just out of curiosity, the next update that you release, would it be possible to overwrite everything else but say a plex ui theme file you have that way you can say that you've updated your requests to not have the Plex name in it anymore and some of us who think this is kinda bs could keep it?

On Dec 14, 2016, at 12:39 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Plex has asked me to remove the association with Plex.

We need a new name ?

-

**Comment by tidusjar** [comment]
@chrisausbun When I finally choose a new name, I'm going to rebrand everything so, once I've moved away from `Plex Requests` that's it.

Plus I have been thinking to extend Plex Requests outside of the Plex ecosystem anyway (Support for Emby)

**Comment by SuperPotatoMen** [comment]
I guess My Requests will be the best name.

**Comment by hoopty** [comment]
Media Requests?

**Comment by tidusjar** [comment]
https://www.reddit.com/r/PleX/comments/5i995g/plexrequests_needs_you_help/db7zafu/

**Comment by WindfallProphet** [comment]
Seems like you went with Ombi. How about a new theme to commemorate the new name? What sort of colors go with a name like Ombi?

**Comment by tidusjar** [comment]
Excellent idea, and I don't know! What do you have in mind?

**Comment by SuperPotatoMen** [comment]
What about you can do it on your self?

**Comment by Ruvetuve** [comment]
White + Purple, as in the logo of @WindfallProphet first thing that came up my mind.

**Comment by SuperPotatoMen** [comment]
Is this one done @tidusjar ?

**Comment by tidusjar** [comment]
Yes!
