### ISSUE TITLE
Newsletter Customization

### ISSUE THREAD

**Issue by jpenberthy** [tidusjar/Ombi#790]
Newsletter needs customization in options (How often it goes out, Content to Show, etc.)?

Also the posters are all different sizes, especially the TV shows. Which makes the email scroll forever, even more so when a lot of content was added recently.

The Newsletter should also remember what it sent out prior as newly added content to not show it again. This will help it not scroll forever as well.

Need to have 2 formats for email. Poster View and Summary View. This way we can just send out a summary of listings without them having to scroll through the list.

Great work though, keep it up.

**Comment by SuperPotatoMen** [comment]
Planned feature for the notification update

**Comment by Ahsome** [comment]
Is this idea no longer planned?

**Comment by tidusjar** [comment]
It is, but not in V2 of Ombi. I'm currently in the middle of writing V3 so we can support Linux platforms better. It will be included in that.

**Comment by SmolSoftBoi** [comment]
> It is, but not in V2 of Ombi. I'm currently in the middle of writing V3 so we can support Linux platforms better. It will be included in that.

We're now on version 4, was this included as I can't find it.
