### ISSUE TITLE
Add version to compiled and name to souce download

### ISSUE THREAD

**Issue by fryfrog** [tidusjar/Ombi#793]
Currently, the source files for a release are named 'v1.10.0.zip' for example, but the compiled version is just 'PlexRequests.zip'. It'd be great if both could be improved, for example I'd name the compiled download 'PlexRequests-v1.10.0.zip' adding the version. For the source, maybe 'PlexRequests-v1.10.0.src.(zip|tar.gz)'.

The benefit to *me* is that packages can use a versioned file that doesn't get cached. It also makes it a little more clear what you've downloaded, in the case of the source... a few days from download, who knows what "v1.10.0.zip" is and for the compiled version... who knows what version "PlexRequests.zip" is. :)

**Comment by tidusjar** [comment]
When you say src, you mean the branch? Like Dev, Early Access and master?

**Comment by SuperPotatoMen** [comment]
HI @fryfrog ,

pleas provide us more information of your request.
