### ISSUE TITLE
Specify Note when Reporting Issues with Media

### ISSUE THREAD

**Issue by jpenberthy** [tidusjar/Ombi#798]
I have some people reporting issues now they have seen that option. Though, stating playback issues is very generic and maybe just an issue on their side (i.e. media not compatible with client device). Otherwise, I have no idea what I may be looking for when trying to play it myself.

Having a descriptor option when reporting issues would be nice. This could also go for subtitles or audio tracks in certain languages.

**Comment by SuperPotatoMen** [comment]
It is already possible to put a note in the report for a user. I'm not sure what you are request over here right now. Can you explain it a little bit more?

**Comment by jpenberthy** [comment]
If a user goes to report an issue for a movie or tv show and select playback, it just reports it and doesn't ask the user for more details, just reports it. They can after the fact, go into issues and add a note. This is to complicated for most of my users.  Needs to ask them for more details after reporting an issue, though details can still be optional.

**Comment by SuperPotatoMen** [comment]
I agree on that, I will planning this one on a new release
