### ISSUE TITLE
Allow add email addresses in User Management for Managed Users plex accounts

### ISSUE THREAD

**Issue by kangfat** [tidusjar/Ombi#811]
#### Reproduction Steps:

Open User Management->Click Details/Edit on any existing user->Attempt to type in an email address in the Email Address field.

**Comment by SuperPotatoMen** [comment]
@tidusjar  I'm not sure this one is a bug or by design? (Management plex users don't have email address by default)

**Comment by tidusjar** [comment]
It's an oversight, I think we should be able to modify the email address for Managed users, there is nothing stopping us.

**Comment by SuperPotatoMen** [comment]
see: https://github.com/tidusjar/Ombi/issues/824

**Comment by ninthwalker** [comment]
I would like this as well. Specifying the email would be great. Thanks.
