### ISSUE TITLE
Settingfile for baseurl?

### ISSUE THREAD

**Issue by damiantje99** [tidusjar/Ombi#812]
If this is a bug report or support request please make sure you have filled the following in:
(If this is afeature request pleas submit your feature request over here: http://feathub.com/tidusjar/PlexRequests.Net)

#### Plex Requests.Net Version:
10.1

#### update Branch:

development

#### Operating System:
Openflixr (Linux) Baremetal

Hi,

I've just updated PlexRequest to the 10.1 dev. Now, when i'm accessing the page, i'm getting a 404 error. 
I use reverse proxy with Nginx and when i'm going back to my old 9.7 version (with the old files), i get it to work.

As far as I know I need to enter the baseurl in the application self. Because i'm running bare metal, I can't access localhost on the server and I can't access it from another internal computer. 

So my question, is there a settings file (if so, which one) where I can manually enter the baseurl?

**Comment by SuperPotatoMen** [comment]
Best way you can to this to open the PlexRequests.sqlite file with a sql reader.

**Comment by damiantje99** [comment]
Thanks, going to try that. I'll let you know if that worked.

**Comment by SuperPotatoMen** [comment]
Cool, If you need help let me know.

**Comment by tidusjar** [comment]
Hello,

Sorry that won't work. All of the settings are encrypted. 

What you would need to do is start with a fresh database (delete the sqlite file) and run the application with the '-b' argument and your base URL. 
E.g.

PlexRequests.exe -b request

Where 'request' is the base URL

**Comment by damiantje99** [comment]
Still getting the same error:

404 - NotFound
The resource you have requested cannot be found.

We're sorry :-(

I've just copied back the files from the 1.9.7 version and started the daemon and its running without any problem. Any ideas?

**Comment by tidusjar** [comment]
So what is your base url and the url you are accessing?

**Comment by damiantje99** [comment]
What do you mean with the base url? The base url in PlexRequest? Because that one is empty in the dev version. In the 1.9.7 version it is "Request" (without the quotes obviously). This is also the url that i'm accessing.

So, the base url is request and i'm accessing the page through https://website.nl/request

**Comment by damiantje99** [comment]
Hi,

I fixed the problem by copying the old .sqlite file to the new version. Just saw that you mentioned that in the 10.1 update.

Anyways, thanks for the help!

**Comment by SuperPotatoMen** [comment]
nice, good to know! 👍
