### ISSUE TITLE
Global setting to control email notifications for user's requests?

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#813]
I think it would be really useful for the admin to be able to set the default setting to enable/disable email notifications that are only sent to the requestor when a request is filled.

The current notification setting is a bit confusing.  Is this the setting under "modify Features" - Request added notification? If so, if that's checked, that means that user and only that user will get a notification when their request is filled? Also, that's a "per user" setting, right? Is there a way to enable this feature "globally"?

Ref:  http://feathub.com/tidusjar/Ombi/+3

**Comment by SuperPotatoMen** [comment]
Best way you can do that is to go to:  Admin panel > User Management Settings  and enable the "Recently Added Notifications".

**Comment by seanvree** [comment]
@SuperPotatoMen  - Okay, but this is still a bit confusing.   

If I enable recently added notifications - this will notify EVERY user when ANYTHING is added...correct?

**Comment by SuperPotatoMen** [comment]
@seanvree 
Yeah maybe i agree on that that is a bit confusing. Let me explain:

When you enable for a user: Recently added notification, the user will get only a notification for his **own** request. Other request from different users doesn't trigger a notification.

**Comment by seanvree** [comment]
@SuperPotatoMen  Right, I understand when you enable it per user that's how it supposed to work.  

My original suggestion was that was a way to enable that feature for ALL users...meaning all users get notifications when only HIS/HER request is filled. 

So again, if  i enable Admin panel > User Management Settings and enable the "Recently Added Notifications", does that notify all users when ANY request is filled?

**Comment by SuperPotatoMen** [comment]
For now that isn't possible you can use the newsletter for that.
I will make this issue a feature request.

**Comment by seanvree** [comment]
okay, got it.

Thanks for your patience!

Keep up the good work!!!

**Comment by seanvree** [comment]
This is implemented in the latest OBMI version!

THANKS!
