### ISSUE TITLE
Auto Updater not working.

### ISSUE THREAD

**Issue by mrangryoven** [tidusjar/Ombi#814]
!! Pleas use the template, otherway we will close the github issue !!

If this is a bug report or support request please make sure you have filled the following in:
(If this is afeature request pleas submit your feature request over here: http://feathub.com/tidusjar/PlexRequests.Net)

#### Plex Requests.Net Version:
Version 1.10

#### update Branch:

**Stable**/Early Access Preview/development

#### Operating System:
Windows Server 2012 R2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Nothing in the logs for the issue im facing, only connection errors to my VM running CouchPotato and Sonarr which isnt running so is fine.

```

#### Problem Description:

After pressing button to use auto updater, button changes to "Updating" and then restarts the service and doesnt update PlexRequests.

#### Reproduction Steps:
Login to PlexRequests 1.10 using admin account, click "Here" on the orange banner, Click "Automatic Updater (Beta)"

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I am unsure of how to properly manually update PlexRequests, if I could have some help that would be great :)

**Comment by bromanguydude** [comment]
This is also happening to me. I was wondering is the Zip needed to be downloaded first in order to update.

**Comment by SuperPotatoMen** [comment]
Yeah, it look like its still broken.

**Comment by SuperPotatoMen** [comment]
Master ticket: https://github.com/tidusjar/Ombi/issues/236
