### ISSUE TITLE
Let admin choose what type of request are possible

### ISSUE THREAD

**Issue by Ublala** [tidusjar/Ombi#815]
#### Plex Requests.Net Version:
1.10.1

#### update Branch:

Stable

#### Operating System:

Windows 10

#### Problem Description:

I have disabled the TV requests by season, but when I or one of my users searches for a TV Show there are two options: select episode or all seasons.

Obviously I do not want my users to request all seasons, is there a way to remove this option when the 'Disable TV requests by season' option is checked?

**Comment by SuperPotatoMen** [comment]
At the moment that isn't possible, i will make a feature request of it.

**Comment by SuperPotatoMen** [comment]
Maybe a dropdown menu and you can choose what kind of request are possible.

**Comment by Ublala** [comment]
A dropdown menu would be great!

**Comment by SuperPotatoMen** [comment]
Planned in version 2.0
