### ISSUE TITLE
[Support] Slack Notifications 

### ISSUE THREAD

**Issue by FunkMast3rFlex** [tidusjar/Ombi#819]
I really appreciate all the work and i will admit that some of this is ahead of me and some of this I know, but I am learning.

I'm currently using Slack to notify a private group of just myself of contents that have been requested. I have a public group that I plan to add my users in and I want to use that to notify them of movies that have been added to the server. Is this feature currently active? If their is already a tread on this please link and Ill look over it

Also is it possible to push and notice messages to slack instead of using the landing page? Ive noticed that using the landing page before login can sometimes for a loop of having to keep signing in.

Thanks.

**Comment by SuperPotatoMen** [comment]
See: https://github.com/tidusjar/Ombi/issues/380

**Comment by FunkMast3rFlex** [comment]
Thanks
