### ISSUE TITLE
Request: Custom Themes

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#820]
Would be nice to be able to load custom themes.

I tried copying one of the themes and renamed the files but the system does not recognize the theme.
I did some googling and cant find any thing about it.

**Comment by tidusjar** [comment]
The only way to customise the theme currently is to modify the existing .css files. But I can add an option where you can just drop in your own .css file and we can pick it up?

**Comment by tidusjar** [comment]
You would need to edit either

original.css OR plex.css
https://github.com/tidusjar/Ombi/tree/master/PlexRequests.UI/Content/Themes

**Comment by Garderoben** [comment]
Yes that sounds good, for now i will edit the existing one.
