### ISSUE TITLE
Ombi hangs when plex is timing out on our  GetEpisodeMetaData api request (big libraries)

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#823]
In some situations Ombi hangs and doesn't respond anymore when plex is timing out to our GetEpisodeMetaData api requests .
Maybe we can set a higher timeout time and prevent that Ombi keeps trying every time. (just skip it)

**Comment by mushbuddygoose** [comment]
Happening to me as well. Mine is freezing once a day and I need to reboot to fix it.

**Comment by tidusjar** [comment]
Can you disable episode searching. Should solve the issue

**Comment by lastb0isct** [comment]
after re-authenticating plex it went away for me.
