### ISSUE TITLE
Updater not working.

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#826]
#### Ombi Version:

V 1.10.0

#### Update Branch:

Stable

#### Operating System:

windows server 2012

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)

```

#### Reproduction Steps:

Click update and it looks like its working then when finished, it stays on the same version.

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/236
