### ISSUE TITLE
Version 2.X Release

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#828]
**Version 2.X will be include:**

**New pages**
- An information page #398
- Report a bug button #399

**Security:**
- SSL/https support #66
- recapture addition #584

**Login page**
-  Combine Admin/User Login  #292
-  Forgot Password Link #673
- Support Plex email address to log in #640

**System Support:**
- Don't let be plex server a requirement #136

**New features on seach page:**
- New admin settings
         -  Restrict requests based on time since release #463
         - Choose what type of request are possible #815 #582 
- New features on main request page
      - Show dvd release date on main page #373 
      - Show more information button with  Cast/Crew/Genre Info #115 
      - User can follow the process of his own request #427
- Request user can specify the Quality 
      - Set a default setting of quality profile (and don't show the option)  
      - User mangement option to turn on/off  the default settings and let the end use choose #605  #175
      - Sonarr support  #170
      - Couchpotato support #490 
- Request tv shows/movies based on:
                  - Actor #324
                  - director #637 
- Add an option for "more" from "Coming Soon" or "In theaters" suggestions #471            
- Don't show dropdown menu if you only give 1 option to request (all season) #742 
- exclude specials #528

**New advanced settings features on search page:**
- make your own categories and connect it to a path (instead you can only click on movie or tv show) #289
                - Sonarr Support #445 
                - Sonarr tag support part of: #287
                - Couchpotato support
                - Set on every Categories if users can see it and have AutoApprove permissions (if you like to handle some request manually)

**Request page:**
- New admin settings
             - Delete or move to archive when requests is available #216 #606 #468
- Admin can specify the Quality and the path by aprovel
        - Sonarr Support #445  #287  #535
        - Couchpotato Support #176 
- tv show requests should show # of episodes available out of # episodes in series #322
- Rework the requests page, needs to support 700+ requests  #481
- Default filter option is set to not approved instead of all on requests page #719
- Exclude specials #528
- Undo button for Removes

**Report System:**
- New admin settings:
            - Turn off Reports/Issues #421
- Report Issues directly to episode #443
- Force Note bij initial Reporting Issues with Media #798

**Comment by leram84** [comment]
jesus

**Comment by SuperPotatoMen** [comment]
@tidusjar and i'm not sure yet for the 2.0 release.

We need to split it out in 3 versions.

I think we need to drop the ability to view the Plex Library #47, Web newsletter #64 , Support for multiple plex servers #196 ,  Emby support #435

**Comment by tidusjar** [comment]
Makes sense! It's still a lot of things but it should be doable!

**Comment by delrio1110** [comment]
is there early access to this build ?

**Comment by tidusjar** [comment]
Not yet! You can switch to the early access preview branch and you will be
notified

**Comment by Aireezz** [comment]
I don't think you should drop

the ability to view the Plex Library #47
Support for multiple plex servers #196

but maybe just postpone? I would really like to see those features come to Ombi, especially #47

**Comment by SuperPotatoMen** [comment]
That two is already dropped  :)

**Comment by tidusjar** [comment]
When we say "dropped" we mean dropped out of this release and postponed

**Comment by Aireezz** [comment]
Ah okay! I thought you mean't dropped as in forever. Good to know! Thanks.

**Comment by valantislevas** [comment]
Request page:

New admin settings
- Delete or move to archive when requests is available #216 #606 #468 

is that possible on ombi v3?

**Comment by PotatoQuality** [comment]
Pleas do a feature request on the feature request page
