### ISSUE TITLE
Cant modify permissions of admin plex account 

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#829]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
No logs (even with trace on)

```

F12 gives me:

```
angular.min.js:118 Error: [orderBy:notarray] http://errors.angularjs.org/1.5.8/orderBy/notarray?p0=%7B%22%24%24state%22%3A%7B%22status%22%3A0%7D%7D
    at angular.min.js:6
    at angular.min.js:172
    at fn (eval at compile (angular.min.js:233), <anonymous>:4:429)
    at angular.min.js:128
    at m.$digest (angular.min.js:143)
    at m.$apply (angular.min.js:146)
    at l (angular.min.js:97)
    at J (angular.min.js:102)
    at XMLHttpRequest.t.onload (angular.min.js:103)
```

#### Problem Description:

If i try to give permissions to my own  admin account (plex.tv account) nothing happend if i hit the save button.
Other accounts are fine. (also the default permissions not set on the admin plex.tv account)

#### Reproduction Steps:

Try to give permissions to the plex.tv account, nothing happend.

**Comment by Elrique64** [comment]
I have the same problem.  Can't update the main Plex.tv admin account's permissions.  Can't make requests when logged in as the admin Plex.TV account.

**Comment by tidusjar** [comment]
This has been fixed in the early access preview branch
