### ISSUE TITLE
Request: New User Registration Page

### ISSUE THREAD

**Issue by Peanutman85** [tidusjar/Ombi#833]
It would be nice to allow new users without a Plex account a way to create an account, which an admin could then approve and assign permissions. 

Currently it seems the admin has to create the account, including the username and password.

**Comment by FunkMast3rFlex** [comment]
I thought the same but isn't the software primarily for those who are user on your server? Why would those outside of that need access?

**Comment by SuperPotatoMen** [comment]
See the issue format where you can post a feature request
