### ISSUE TITLE
Local users unable to login from main landing page

### ISSUE THREAD

**Issue by rjsears** [tidusjar/Ombi#837]
#### Ombi Version:

1.10.1

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04 LTS

#### Mono Version (only if your not on windows)

Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Need to auth and also provide pass	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:47:47 PM
Using password	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:47:47 PM
Username "mary" attempting to login	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:47:47 PM
Need to auth and also provide pass	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:11 PM
Using password	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:11 PM
Username "mary" attempting to login	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:11 PM
Need to auth and also provide pass	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:03 PM
Using password	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:03 PM
Username "mary" attempting to login	PlexRequests.UI.Modules.UserLoginModule	Debug	12/23/2016 7:39:03 PM

```

#### Problem Description:

Most of my users are managed users so I added several local users in PR. When I go to the default landing page for PR (http://myserver:3579) it gives me a login prompt for a username and password. It says plex.tv uusername but when I try to enter a local username and password it fails.

The only way I can log in as a local user is to click on the Admin button on the upper right of the screen and enter my local username and password there.

#### Reproduction Steps:

This URL does not work (default landing page):
http://myserver:3579/userlogin?landing

This URL does work (arrived at by clicking on Admin button in the upper right corner of the above page):
http://myserver:3579/login?redirect=/userlogin

**Comment by SuperPotatoMen** [comment]
Hi, this is nog a bug but by design. 

We already planned to combinate the to login pages. 

See https://github.com/tidusjar/Ombi/issues/292
