### ISSUE TITLE
Request Rejection

### ISSUE THREAD

**Issue by jpenberthy** [tidusjar/Ombi#840]
I approve all requests, because I don't mind making it available. Though I would like someway to reject it, weather it is just for space or maybe I cannot get it. So you should be able to mark the item rejected for cause and list a reason, then it sends an email to them (and even a slack message, etc).

**Comment by SuperPotatoMen** [comment]
Did you read the automatically  issue format?

**Comment by jpenberthy** [comment]
my bad, didn't read the new issue text

**Comment by SuperPotatoMen** [comment]
No problem :)
