### ISSUE TITLE
[Request] Integrate Watcher (CouchPotato Replacement)

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#844]
https://github.com/nosmokingbandit/watcher

This is a couchpotato replacement.  They too have an api.  Might be something to look into in the future.

**Comment by tidusjar** [comment]
I did see the reddit thread about this. I think it's a good option.

**Comment by flixajki** [comment]
Great was just about to post this.

**Comment by TheRealShiz** [comment]
This makes me happy to see

**Comment by tidusjar** [comment]
Mostly finished, need to do some testing to make sure we can add, and also check if it's already in the Watcher 'wanted' list

**Comment by tidusjar** [comment]
This is in the Early Access Preview branch 🎉

**Comment by tidusjar** [comment]
Oops, not fully finished, missed an area

**Comment by tidusjar** [comment]
Nope ignore me, it's finished

**Comment by causefx** [comment]
wow you're fast!

**Comment by tidusjar** [comment]
@causefx Just efficient ;)

**Comment by rjsears** [comment]
@tidusjar Hey I think I am missing something...I installed the latest version of Ombi and I could not find where to add Watcher under movies. It shows CP, Dog and Radarr but no Watcher.

Thanks

**Comment by tidusjar** [comment]
It's not been added to v3 yet

**Comment by rjsears** [comment]
Well then it makes perfect sense that I cannot find it :-)

**Comment by lucacri** [comment]
Any idea when this will be added?

**Comment by tidusjar** [comment]
No plans. People stopped asking for this.
