### ISSUE TITLE
Default User Management Settings don't change the settings of any user

### ISSUE THREAD

**Issue by tijmenvn** [tidusjar/Ombi#861]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

Stable 4.6.2.7/08fd525

#### Problem Description:

Changing the settings in the default user management settings doesnt change any setting in my individual users setting. changing setting on individual users does still work

**Comment by tidusjar** [comment]
I've already fixed this in the early access preview branch. You cannot modify your Plex admin account right? 

If you don't want to use the early access preview branch then you could just create a local admin user with all the permissions as a work around for now.

**Comment by tijmenvn** [comment]
True, my own local account has no permissions and I cannot give him any, my main problem lies that all requests from all my users are now auto accepted, but I'll wait for the stable release

**Comment by tidusjar** [comment]
Oh wait, you are referring to the settings page? That's the default
settings that any new Plex users get. If you change it,  it won't update
all your users.

**Comment by tijmenvn** [comment]
Aah okay, since I know manually have to set the permissions for like 70 users. Maybe a feature for next release to change multiple users (or all) at a time

**Comment by chrisausbun** [comment]
Yes, I second that. As a Plex Admin with 50 or more users, that was not fun. Thanks for suggesting that.

On Dec 29, 2016, at 2:42 PM, Tijmen van Nisselrooij <notifications@github.com<mailto:notifications@github.com>> wrote:


Aah okay, since I know manually have to set the permissions for like 70 users. Maybe a feature for next release to change multiple users (or all) at a time

-

**Comment by tidusjar** [comment]
Yeah that makes sense. I can add a button on the settings page saying
"apply to all" which will then apply the settings to all users that are not
the admins
