### ISSUE TITLE
Port to .Net core

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#865]
Let's all face it, anyone running on anything but windows usually runs into issues at some point.

Let's port this over to .Net core and remove the dependency from Mono.

**Comment by vertigo235** [comment]
So is it not planned yet or in progress?  I'm confused

**Comment by tidusjar** [comment]
It's in progress but a backburner, only working on it when I have time.

This will take a while to port everything over, since the frameworks are different, Core API is different from the Full Framework too and there are many dependencies that we use are not supported on .Net Core yet.

**Comment by yeyeoke** [comment]
Wow, truly great news, I'm running Ombi on Ubuntu Server 16.10 and I've been experiencing that Ombi becomes unresponsive and only comes online again after I restart it, I figured it was due to mono.

**Comment by tidusjar** [comment]
Yeah, we have few issues from the limitations of mono. It's an excellent framework but it does have its caviats! 

This has been put on hold for the time being as I am waiting for .Net core to mature a bit as there are still problems with the tooling and it's still very much influx.

**Comment by RyanAStrouse** [comment]
Excellent news! Thanks!

**Comment by SuperPotatoMen** [comment]
@tidusjar just started with tis. it will take a while but i think the linux users will be happy :+1:

**Comment by tidusjar** [comment]
Sonarr Integration is taking a while

Few reasons:

- There are many different scenarios to test e.g. Single Episode request, Multiple episode requests in different seasons, Full season request, whole series request etc.

- To cater for the above scenarios I need to code this right 😄 

- I want to get it right the first time around!

**Comment by roly445** [comment]
Do you need any help with this?

**Comment by tidusjar** [comment]
I could always use help!

**Comment by roly445** [comment]
Do you have a task list.  Should I email you?

**Comment by bulbajackel** [comment]
+1 I would like to help with some of the angular 4 work that you have.

**Comment by tidusjar** [comment]
@roly445 I'll create a task list, it's all in my head currently!

@bulbajackel  yeah man that's cool!

**Comment by tidusjar** [comment]
I've created a bunch of high level tasks that is required! If you have any questions post on them :)

**Comment by RaymondSchnyder** [comment]
How far is this progressed? I ask because ombi crashes every 2 minutes on mono 5 xD

**Comment by nemchik** [comment]
There were 9 commits in the past 10 days. Not sure if they were game changers, but there is some kind of progress.

I do not have issues with mono 5 other than Ombi being slow as hell. You might have some other issue.

**Comment by mrkno** [comment]
Mono's GC is terrible so hopefully a .net core port fixes some of the issues. A picture of Ombi memory utilisation over a few days (you can clearly see the point where I killed it; note that Transmission, Plex and lighttpd are all running and being actively used in the remaining memory):
![image](https://user-images.githubusercontent.com/6830312/28244163-c0b8c168-6a36-11e7-9d88-0811ab1c2019.png)

**Comment by tidusjar** [comment]
Hey guys. I'm working on this as my priority. All of my changes are pretty big ones. Literally in my spare time this is all I am doing !

**Comment by zin105** [comment]
Will we see any alpha/beta build we can test and help you iron out issues? :)

**Comment by PotatoQuality** [comment]
If there is a alpha beta build ready, we will notice it in this issue.

**Comment by PotatoQuality** [comment]
Every 4 days asking if there is a beta or alpha build will not fast forward the process.
I suggest to stop asking it and wait for a sign from @tidusjar

**Comment by zin105** [comment]
This is the first time I'm asking. I don't see any questions about it. If you guys are removing the comments then obviously it's very difficult for us to know if it's already been asked.

**Comment by PotatoQuality** [comment]
Well i do:

![image](https://user-images.githubusercontent.com/2944704/28380078-4040f456-6cb6-11e7-99ab-3262f12988f0.png)

**Comment by zin105** [comment]
He's not asking if there will be an alpha/beta build, he's just asking for the progress of the project.

**Comment by PotatoQuality** [comment]
Well, as fair i know, its means the same. Its done when its done.

**Comment by zin105** [comment]
I'm not asking for when it's done. I'm asking if there's anything we non developers can do to help, which is usually  to test and find bugs. Anyways just delete this whole conversation it's pointless clutter.

**Comment by PotatoQuality** [comment]
@zin105  i already told you that: If there is a alpha or beta build ready, we will notice it in this issue.

**Comment by tidusjar** [comment]
@zin105 I'll let you know! There are a few things I need to iron out first :) it shouldn't be too long.

**Comment by jdenson** [comment]
Excited to see so much work on this. Thanks for the hard work @tidusjar !

**Comment by horstepipe** [comment]
Yeah I can hardly wait for a test build.
I just discovered Ombi for Emby and love it. Unfortunately it crashes very often on my Ubuntu 16.04 vps.

So thank you very much for the hard work

**Comment by tidusjar** [comment]
Thanks guys! 

I'm trying to work on this as much as my free time let's me. It might be a bit slow over the next 2 weeks as i'm getting married! 💒

**Comment by jdenson** [comment]
Congratulations Jamie!

Jason

⁣Sent from BlueMail

**Comment by xnaas** [comment]
Yeah, wow, seriously, grats @tidusjar!

**Comment by smasher816** [comment]
I'm not sure if this is an issue with Ombi, or my dotnet install. I'm using Arch Linux with the `dotnet-runtime-2.0 package` (https://aur.archlinux.org/packages/dotnet-runtime-2.0/).

`$ chmod +x Ombi; ./Ombi`
```
Error:
  An assembly specified in the application dependencies manifest (Ombi.deps.json) was not found:
    package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.0.0'
    path: 'runtimes/linux-x64/native/System.Native.a'
```

I have also tried running `/usr/bin/dotnet /opt/ombi/Ombi.dll` which gives the same error.

**Comment by tidusjar** [comment]
Are you trying to run from source?

**Comment by smasher816** [comment]
This was from the linux.tar.gz appveyor build artifact this morning (https://ci.appveyor.com/api/buildjobs/43vlt3g81ahfc684/artifacts/linux.tar.gz I believe)

**Comment by tidusjar** [comment]
You do not need to install the .net runtime. It's a self contained application meaning it should have all the dependencies inside the .gz.

Make sure your working directory is where you extracted Ombi and then run `.\Ombi`

**Comment by smasher816** [comment]
Thank you for the info. I've narrowed down my issue to when using a PKGBUILD in arch. If I simply download and extract the tar.gz then it does in fact run correctly.

Edit: After a little more poking it is because makepkg strips static libs (.a) files by default. Disabling that option fixes everything.

**Comment by horstepipe** [comment]
is there a guide on how to install the .net version on Ubuntu?

**Comment by PotatoQuality** [comment]
@horstepipe see the main page of this github
