### ISSUE TITLE
Cannot create local user

### ISSUE THREAD

**Issue by xp-1000** [tidusjar/Ombi#881]
#### Ombi Version:

V 2.0.1175

#### Update Branch:

Early Access Preview

#### Operating System:

Archlinux

#### Mono Version (only if your not on windows)

4.6.1.3

#### Applicable Logs (from `/logs/` directory or the Admin page): 
The only log I have is from the web browser dev console :

```

Error: $scope.users.some is not a function
controller/$scope.addUser@http://requests.example.com/Content/app/userManagement/userManagementController.js?v=2.0.0:77:36
anonymous/fn@http://requests.example.com/Content/angular.min.js line 233 > Function:2:209
b@http://requests.example.com/Content/angular.min.js:126:128
Lc[b]</<.compile/</</e@http://requests.example.com/Content/angular.min.js:276:195
vf/this.$get</m.prototype.$eval@http://requests.example.com/Content/angular.min.js:145:343
vf/this.$get</m.prototype.$apply@http://requests.example.com/Content/angular.min.js:146:47
Lc[b]</<.compile/</<@http://requests.example.com/Content/angular.min.js:276:245
n.event.dispatch@http://requests.example.com/Content/jquery-2.2.1.min.js:3:7464
n.event.add/r.handle@http://requests.example.com/Content/jquery-2.2.1.min.js:3:5580
  angular.min.js:118:8
	e/< http://requests.example.com/Content/angular.min.js:118:8
	hf/this.$get</< http://requests.example.com/Content/angular.min.js:90:220
	vf/this.$get</m.prototype.$apply http://requests.example.com/Content/angular.min.js:146:94
	Lc[b]</<.compile/</< http://requests.example.com/Content/angular.min.js:276:245
	n.event.dispatch http://requests.example.com/Content/jquery-2.2.1.min.js:3:7464
	n.event.add/r.handle http://requests.example.com/Content/jquery-2.2.1.min.js:3:5580

```

#### Problem Description:

When I try to create a user, there is no reaction (no webui message, no log on system side). When I try to create withtout permission selected, there is a warning message but when I fill all necessary fields (email, login, password and permissions), just no consequence, nothing.

#### Reproduction Steps:

Just try to create a user. I am not on fresh install, I upgraded and imported sqlite database from older version (1.9 / 1.10). Thanks

**Comment by tidusjar** [comment]
Note: angular error:

Error: $scope.users.some is not a function controller/$scope.addUser@http://requests.manfroi.fr/Content/app/userManagement/userManagementController.js?v=2.0.0:77:36 anonymous/fn@http://requests.manfroi.fr/Content/angular.min.js line 233 > Function:2:209 b@http://requests.manfroi.fr/Content/angular.min.js:126:128 Lc[b]</<.compile/</</e@http://requests.manfroi.fr/Content/angular.min.js:276:195 vf/this.$get</m.prototype.$eval@http://requests.manfroi.fr/Content/angular.min.js:145:343 vf/this.$get</m.prototype.$apply@http://requests.manfroi.fr/Content/angular.min.js:146:47 Lc[b]</<.compile/</<@http://requests.manfroi.fr/Content/angular.min.js:276:245 n.event.dispatch@http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:7464 n.event.add/r.handle@http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:5580 angular.min.js:118:8 e/< http://requests.manfroi.fr/Content/angular.min.js:118:8 hf/this.$get</< http://requests.manfroi.fr/Content/angular.min.js:90:220 vf/this.$get</m.prototype.$apply http://requests.manfroi.fr/Content/angular.min.js:146:94 Lc[b]</<.compile/</< http://requests.manfroi.fr/Content/angular.min.js:276:245 n.event.dispatch http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:7464 n.event.add/r.handle

**Comment by tidusjar** [comment]
How many users do you currently have in your user management screen?

**Comment by tidusjar** [comment]
I'll push to the Early Access Build later

**Comment by xp-1000** [comment]
I have 0 user currently on my screen.
Thanks I will wait for a new build to test the fix.
