### ISSUE TITLE
User Management settings not functional. ("Override Limit, "AutoApprove")

### ISSUE THREAD

**Issue by Rsslone** [tidusjar/Ombi#882]
#### Ombi Version:

V 2.0.1175

#### Update Branch:

Stable and Early Access Preview (Saw problem on both)

#### Operating System:

Win 8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):
```
http://puu.sh/t8TRb/307c30f013.png
Not exactly sure if related but it had "PlexUserChecker"```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Confirmed "Override Limit" and "Auto Approve" options do not work with plex users without a local ombi account. If a local account is created the "Override Limit" option seems to work.

#### Reproduction Steps:

Related settings: Enable User Authentication ; Disable Require users to login with their passwords

Log into Plex user account with override limit enabled and with no local account created
Request more shows than global limit
Observe

**Comment by tidusjar** [comment]
Thanks, i'll take a look, the error with the PlexUserChecker is different, i'll fix that too!

**Comment by Rsslone** [comment]
You sir, are a saint and a scholar.
*tips hat*

**Comment by tidusjar** [comment]
Can you post a screenshot of a user in question (showing their permissions) feel free to blank out any personal info?

**Comment by Rsslone** [comment]
http://puu.sh/t8XmZ/1c735c9d51.png
http://puu.sh/t8XoO/3cb9283013.jpg

This is a example of the auto approve not working. I can private message you on gitter if you want to mess around with my server.

**Comment by tidusjar** [comment]
@Rsslone I'm not doubting you here, but I cannot seem to reproduce this, it always get's approved and then sent to CP in my case... Looking at the code I also cannot see any way it could happen.

Are you 100% sure it was that user that requested that when they had the permissions above?

**Comment by Rsslone** [comment]
Let me just recheck it again but just today I had to manually approve movies to CP from a user who has auto approve enabled. Either that or the button shows up even if it was approved automatically, I'm going to hop on over to gitter if you want to IM me.

**Comment by Rsslone** [comment]
Check your DMs for the uncensored screens

**Comment by thegame3202** [comment]
I may have figured this one out.  Username is case sensitive for auto-approve.  All lowercase works for a user on mine, but not if they capitalize the first letter.

**Comment by Rsslone** [comment]
I spoke to them privately about this. We've figured out that it approved but the button didn't reflect that so it was misleading people to believe the request was not approved. If there is a bug beyond that I don't know.

**Comment by thegame3202** [comment]
Ah, not the same with me.  It auto-approves as expected with lowercase username, but I have to approve before it downloads with mixed case.  Thanks for the reply :-)

**Comment by Rsslone** [comment]
Interesting. This isn't expected with the bug I am having. I fixed it by making local profiles for my users using capital letters when their username was in lowercase. *shrug* @tidusjar Not sure what you can obtain from this.

**Comment by tidusjar** [comment]
So the rules on auto approval are:

User has the Administrator permission = Auto Approve

```
if request = movie
    if user has permission AutoApproveMovie
       then auto approve

if request = tv show/episode
    if user has permission AutoApproveTv
       then auto approve

if request = album
    if user has permission AutoApproveAlbum
       then auto approve
```

**Comment by tidusjar** [comment]
But... After looking at the sql queries, the actual queries themselves to find the users are case sensitive... damn!

**Comment by tidusjar** [comment]
Fixed it, included `COLLATE NOCASE` into the queries.

**Comment by thegame3202** [comment]
Awesome!  Thank you sir!!

**Comment by Rsslone** [comment]
Way to go! @thegame3202  Thanks for the fix! @tidusjar

**Comment by thegame3202** [comment]
Hmm, running dev branch and still seems to be case sensitive.  After seeing what you did, I applied the same fix needed to PlexUserRepository.cs

I don't know how to apply fixes in Github... I'm a noob.  But adding COLLATE NOCASE into that file, fixed my issue!  Thanks @tidusjar !

**Comment by tidusjar** [comment]
@thegame3202 I guess you compiled it yourself after?

**Comment by thegame3202** [comment]
Yup, compiled and tested on my end!  Figured out how to post pull requests too haha :-) https://github.com/tidusjar/Ombi/pull/910
