### ISSUE TITLE
[Feature Request] Use Netflix API to check if already on Netflix?

### ISSUE THREAD

**Issue by Xenocell12** [tidusjar/Ombi#884]
Hello Gang,

Great software by the way?

I have a proposed feature request.

I'm not sure if this guy has a license to his code but this was sort of a personal attempt to help Plex admins see what they have in their Plex Library already vs Netflix.

https://github.com/SpaceK33z/plex2netflix

So picture this...

While users search for items to request for Plex- on TOP of the method of matching of what admins already have in their Plex Library, maybe also have it match to see if it's on Netflix?

I can see concerns with this. Would this stir a problem with Netflix servers? Does a database need to be made? Proxy? (Netflix has gigantic server farms so I don't think its a issue afterall???)

Much like having a label stating it is available on the admins plex server, have a label that mentions it is on Netflix.

**Comment by chrisausbun** [comment]
It looks like Netflix's 4k content do not show up when you search for it. Marvel's Daredevil for an example does not show up but Orange is the New Black does. Same for movies, Top Gun does not show up as available on Netflix but The Rock does.

**Comment by tidusjar** [comment]
There is currently not much I can do about this. It seems that the API is providing me results from the American version of Netflix. I can't find any other APIs that allow me to select a language.

**Comment by cbgj** [comment]
It would be awesome if you could restrict requests to not be made when they already exists on Netflix.

**Comment by bnevets27** [comment]
Would be nice to be able to disable this. Thanks

**Comment by tidusjar** [comment]
@bnevets27 I think I added a setting to disable this, if not please raise a feature request.

@cbgj Can you raise a feature request for that?

**Comment by bobbintb** [comment]
Is it 4k that's the problem? I too have shows available on Netflix not showing as such.
