### ISSUE TITLE
First Launch Crash

### ISSUE THREAD

**Issue by kfulgham** [tidusjar/Ombi#885]
New Install throws error. Followed install guide. Unblocked but still kicks this out:

> Starting Up! Please wait, this can usually take a few seconds.
> Version: 1.10.1106
> Location of the database: C:\PlexRequests.net\PlexRequests.sqlite
> no configuration section <common/logging> found - suppressing logging output
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
>    at System.Net.HttpListener.AddAllPrefixes()
>    at System.Net.HttpListener.Start()
>    at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
>    at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
>    at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 93
> 
> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
>    at System.Net.HttpListener.AddAllPrefixes()
>    at System.Net.HttpListener.Start()
>    at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
>    at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
>    at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
>    at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125
>

**Comment by tidusjar** [comment]
Run as admin
