### ISSUE TITLE
The Installation Guide in the Wiki was Updated FAR too soon

### ISSUE THREAD

**Issue by jpartain89** [tidusjar/Ombi#886]
#### Ombi Version:

V PlexRequests/Ombi N/A

#### Update Branch:

Stable

#### Operating System:

Ubuntu/Debian Instruction Page

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Problem Description:

Since, like, literally none of the files that are in your compiled .zip downloads are yet renamed to Ombi, if you were to get any new users RIGHT NOW, they'd have major issues trying to figure out what on earth was going on, and why nothing would work per your directions. 

How-to updates should be committed together with whole-program updates, especially with something as important as naming conventions.

**Comment by kfulgham** [comment]
I'm definitely lost on a fresh install. Unfortunately I'm just pointed back to outdated how tos.

**Comment by ryanjoachim** [comment]
Too true. If I hadn't been using PlexRequests on Ubuntu for a few months already (so I remembered a lot of steps/naming), I would be lost as well.

The Gitter channel (on the main page of the Wiki) is a great place for questions though, if you run into issues.

**Comment by tidusjar** [comment]
Rolledback

**Comment by jojogrosso** [comment]
Is there a link to the new Ombi install guide? I can only seem to find the PlexRequests.Net install guide.
