### ISSUE TITLE
Email customisation

### ISSUE THREAD

**Issue by mochflix** [tidusjar/Ombi#888]
Is it possible to customise the email the user who has made a request receives when the item is available?

I searched the issues but couldn't find it.

TIA!

And thanks very much for all the great work!

**Comment by tidusjar** [comment]
Hello, there is an item to complete this. We will allow customisation of notifications. Not sure when this will get done yet though!

**Comment by mochflix** [comment]
Cheers mate! I'll keep an eye on the changelog!!


Op 3 jan. 2017 19:42 schreef "Jamie" <notifications@github.com>:

Hello, there is an item to complete this. We will allow customisation of
notifications. Not sure when this will get done yet though!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/Ombi/issues/888#issuecomment-270189391>, or mute
the thread

**Comment by francesco2013** [comment]
I see this has been closed but customization of the emails it is still not available. Am I wrong ?

**Comment by mochflix** [comment]
Hi,

No, afaik still no customisation possible

Cheers,

Michiel

Op 4 aug. 2017 22:13 schreef "francesco2013" <notifications@github.com>:

**Comment by tidusjar** [comment]
This feature is available in v3, all notifications are now allow customisation.

**Comment by mochflix** [comment]
I thought the latest version was 2.2.1... Or did I.miss something?

Regards,

Michiel

**Comment by francesco2013** [comment]
Yeah exactly same here. Where do I get the V3 @tidusjar ?

**Comment by francesco2013** [comment]
Never mind I have found it out :) 

@mochflix on the DEV branch  https://ci.appveyor.com/api/buildjobs/0s9th9l5c0you5c1/artifacts/Ombi.zip

**Comment by mochflix** [comment]
I'll give it a go :)

**Comment by francesco2013** [comment]
Nope it is 2.2.1853 the dev

**Comment by tidusjar** [comment]
It's the rewrite, it's still in development. I'll be releasing a beta in a few weeks.

**Comment by francesco2013** [comment]
Cool one. Thanks man.
