### ISSUE TITLE
Collapsible top navbar on landing page not working.

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#890]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

windows server 2012 r2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm trying to add a navbar which is collapsible and stays on top of the page, to my landing page, but the problem is it doesn't collapse on mobile devices after un-collapsing.
When I test the HTML code separately it works, but doesn't work in Ombi.

Please help me solve this,
thanks.

#### Reproduction Steps:

I took code from here: http://www.w3schools.com/bootstrap/bootstrap_navbar.asp

I removed this line from the head
`  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">`

I also combined "Collapsing The Navigation Bar" and "Fixed Navigation Bar" from the link above.

**Comment by tidusjar** [comment]
Sorry @ksbansal I can't help with this currently, I'm hard up for time as it is.
