### ISSUE TITLE
No username for managed users

### ISSUE THREAD

**Issue by escservices** [tidusjar/Ombi#895]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Windows 10 version 1607 build 14393.576

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When visiting user management the top 3 users are all bank (I have 3 managed users in plex), no username, no email (expected), and permissions set to none.  I also found that the user could still login but experiences different results based on if they capitalized the first letter.  For instance "dad" couldn't request anything but "Dad" had default permissions and could request things but if I go in and give that blank user more permissions they didn't take.  The only way I knew who was who was by the Plex user pic.  I tried restarting and I also tried requesting another token from plex.  I just switched yesterday from the meteor version so I'm not sure if this was a new issue but it's been this way since I finished the setup. I added the alias.
![capture1](https://cloud.githubusercontent.com/assets/1287511/21707607/a37f7e04-d39e-11e6-9f44-e406b81c7742.JPG)
![capture2](https://cloud.githubusercontent.com/assets/1287511/21707606/a37d9ddc-d39e-11e6-8e79-b589102802bf.JPG)

#### Reproduction Steps:

Setup plexrequests.net, visit user management page and you'll find them. (Nothing showed in the logs)

**Comment by SuperPotatoMen** [comment]
Look like the usermanagement doesn't support plex managed users.
@tidusjar can we make support for that?

**Comment by escservices** [comment]
Also I just noticed (maybe this is because of the managed users?) if you go to user management and click on the the orange settings button it goes to the page that says "Here you can manage the default permissions and features that your users get" whether I take away permissions or add them they don't effect the user unless I manually add them to each user individually. Not sure if that's intentional or related to managed users issues.  I can ope a new issue if unrelated.

**Comment by SuperPotatoMen** [comment]
@escservices that isn't a problem. You need to wait until the job has run the task to change all of the settings. (it isn't live setting)

**Comment by escservices** [comment]
That makes sense now, thanks for the info. @SuperPotatoMen

**Comment by tidusjar** [comment]
Support for managed users will be in the next release
