### ISSUE TITLE
Plexrequests crashes after roughly 10minutes

### ISSUE THREAD

**Issue by In0cenT** [tidusjar/Ombi#897]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04.1

#### Mono Version (only if your not on windows)

Mono 4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

Logs were to longs: http://www.file-upload.net/download-12223179/2017-01-06.log.html

#### Problem Description:

Plexrequests just crashes after roughly 10minutes, if I restart the service its back to normal for 10minutes.

**Comment by SuperPotatoMen** [comment]
Pleas open a new issue and  copy past your logs in the issue instead of uploading on a strange website.
