### ISSUE TITLE
Plexrequests crashes after roughly 10minutes

### ISSUE THREAD

**Issue by In0cenT** [tidusjar/Ombi#900]
Ombi Version:

V 1.10.1

Update Branch:

Stable

Operating System:

Ubuntu 16.04.1

Mono Version (only if your not on windows)

Mono 4.6.2

Applicable Logs (from /logs/ directory or the Admin page):

Logs were to long:
[2017-01-06.txt](https://github.com/tidusjar/Ombi/files/690728/2017-01-06.txt)

Problem Description:

Plexrequests just crashes after roughly 10minutes, if I restart the service its back to normal for 10minutes.

**Comment by moonjazzz** [comment]
I have had the same exact issue. So far no luck, but try out the EPA update stream.

**Comment by SuperPotatoMen** [comment]
Pleas update to the eap branch
 We make changes to resolve the Slowakije responses from plex.tv api

**Comment by In0cenT** [comment]
Just done that got this error:

`Error Details

Error compiling template: Views/Shared/_Layout.cshtml

Errors:
[CS0234] Line: 2 Column: 16 - The type or namespace name `UI' does not exist in the namespace `Ombi'. Are you missing an assembly reference? (show)

Details:
@*@using StackExchange.Profiling*@
@using Ombi.UI.Helpers
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase
<html id="htmlId">
@Html.Partial("Shared/Partial/_Head")

<body>

    @Html.Partial("Shared/Partial/_Navbar")

    <div class="container" style="padding-top: 5%">
        @RenderBody()
    </div>
<div class="scroll-top-wrapper ">
    <span class="scroll-top-inner">
            <i class="fa fa-2x fa-arrow-circle-up"></i>
        </span>
</div>
</body>

@Html.GetInformationalVersion()

</html>
@Html.Partial("Shared/Partial/_LayoutScripts")

Compilation Source:
// ------------------------------------------------------------------------------
Line 1:	//  <autogenerated>
Line 2:	//      This code was generated by a tool.
Line 3:	//      Mono Runtime Version: 4.0.30319.42000
Line 4:	// 
Line 5:	//      Changes to this file may cause incorrect behavior and will be lost if 
Line 6:	//      the code is regenerated.
Line 7:	//  </autogenerated>
Line 8:	// ------------------------------------------------------------------------------
Line 9:	
Line 10:	namespace RazorOutput {
Line 11:	    using Microsoft.CSharp.RuntimeBinder;
Line 12:	    using System;
Line 13:	    using System.IO;
Line 14:	    
Line 15:	    #line 2 "roo"
Line 16:	    using Ombi.UI.Helpers;
Line 17:	    
Line 18:	    #line default
Line 19:	    #line hidden
Line 20:	    using System.Dynamic;
Line 21:	    
Line 22:	    
Line 23:	    public class RazorView : Nancy.ViewEngines.Razor.NancyRazorViewBase {
Line 24:	        
Line 25:	#line hidden
Line 26:	        
Line 27:	        public RazorView() {
Line 28:	        }
Line 29:	        
Line 30:	        public override void Execute() {
Line 31:	WriteLiteral("\n");
Line 32:	
Line 33:	WriteLiteral("<html");
Line 34:	
Line 35:	WriteLiteral(" id=\"htmlId\"");
Line 36:	
Line 37:	WriteLiteral(">\n");
Line 38:	
Line 39:	            
Line 40:	            #line 5 "roo"
Line 41:	Write(Html.Partial("Shared/Partial/_Head"));
Line 42:	
Line 43:	            
Line 44:	            #line default
Line 45:	            #line hidden
Line 46:	WriteLiteral("\n\n<body>\n\n");
Line 47:	
Line 48:	WriteLiteral("    ");
Line 49:	
Line 50:	            
Line 51:	            #line 9 "roo"
Line 52:	Write(Html.Partial("Shared/Partial/_Navbar"));
Line 53:	
Line 54:	            
Line 55:	            #line default
Line 56:	            #line hidden
Line 57:	WriteLiteral("\n\n    <div");
Line 58:	
Line 59:	WriteLiteral(" class=\"container\"");
Line 60:	
Line 61:	WriteLiteral(" style=\"padding-top: 5%\"");
Line 62:	
Line 63:	WriteLiteral(">\n");
Line 64:	
Line 65:	WriteLiteral("        ");
Line 66:	
Line 67:	            
Line 68:	            #line 12 "roo"
Line 69:	   Write(RenderBody());
Line 70:	
Line 71:	            
Line 72:	            #line default
Line 73:	            #line hidden
Line 74:	WriteLiteral("\n    </div>\n<div");
Line 75:	
Line 76:	WriteLiteral(" class=\"scroll-top-wrapper \"");
Line 77:	
Line 78:	WriteLiteral(">\n    <span");
Line 79:	
Line 80:	WriteLiteral(" class=\"scroll-top-inner\"");
Line 81:	
Line 82:	WriteLiteral(">\n            <i");
Line 83:	
Line 84:	WriteLiteral(" class=\"fa fa-2x fa-arrow-circle-up\"");
Line 85:	
Line 86:	WriteLiteral("></i>\n        </span>\n</div>\n</body>\n\n");
Line 87:	
Line 88:	            
Line 89:	            #line 21 "roo"
Line 90:	Write(Html.GetInformationalVersion());
Line 91:	
Line 92:	            
Line 93:	            #line default
Line 94:	            #line hidden
Line 95:	WriteLiteral("\n\n</html>\n");
Line 96:	
Line 97:	            
Line 98:	            #line 24 "roo"
Line 99:	Write(Html.Partial("Shared/Partial/_LayoutScripts"));
Line 100:	
Line 101:	            
Line 102:	            #line default
Line 103:	            #line hidden
Line 104:	WriteLiteral("\n");
Line 105:	
Line 106:	        }
Line 107:	    }
Line 108:	}
Line 109:	`

**Comment by SuperPotatoMen** [comment]
You need to do a clean install not to override the files

**Comment by moonjazzz** [comment]
@SuperPotatoMen whats the link for the lastest EAP?

**Comment by didyouexpectthat** [comment]
I received the same error following the FAQ questions: https://github.com/tidusjar/Ombi/wiki/FAQ#how-can-i-upgrade-to-the-newest-version-of-plex-requestsnet

I went ahead and overwrite and go the same error. 

When I tried to fresh install and copy over my database, it failed to start.

**Comment by tidusjar** [comment]
@didyouexpectthat That is the perferred upgrade path, but not for the next major release (2.0.0) as there are major changes and renames. I'm documenting the release notes now ready for the next release.
