### ISSUE TITLE
Can't disable "Use Advanced Search"

### ISSUE THREAD

**Issue by heartisall** [tidusjar/Ombi#904]
I don't use the advanced search feature because I have over 2,000 movies and because of this it takes forever. Somehow it got enabled and I get the notice "Currently we are indexing all of the available tv shows and movies on the Plex server, so there might be some unexpected behavior. This shouldn't take too long." when I got to Ombi. I have tried turning the feature off but it just re-enables it.

#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable/Early Access Preview/development

#### Operating System:

Server 2012 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
The advanced search is not really advanced anymore and it's key that it is enabled as we rely on it.

So I should really remove the option from the UI....

What would take a very long time is the episode search, make sure that is disabled, but regarding 2000 movies, it shouldn't take too long for that. 

Also when that message appears, it's not just doing Plex things, it's also talking to Cp/Sonarr/Headphones etc.

So if you take a look here: https://github.com/tidusjar/Ombi/blob/EAP/Ombi.UI/Jobs/Scheduler.cs#L176

You can see all of the background jobs, there are some that start straight away (`StartNow()`) and some that start in a few minutes time (`StartAt(DateBuilder.FutureDate(2, IntervalUnit.Minute))`).

All of the ones that relate to movies/tv shows will display that message.

**Comment by heartisall** [comment]
OK, It does take quite some time to process them though as I can see it touching every single movie on my plex interface. I am only using ombi with Plex and Sonarr so none of the others apply. Would this job be the Plex availability cacher?

**Comment by tidusjar** [comment]
It's the `PlexContentCacher`. So what happens is that we cache the content in a local DB, then the Availability Checker comes along later to see if any requests are available.

It doesn't really touch every single movie, Plex provides an API that passes me all of the movies in one hit (After navigating through the libraries) .

**Comment by heartisall** [comment]
Hmm Ok, I say it seems to touch each movie because when I have plex open in my browser I can see each processed movie at the bottom. It's about 50 minutes in so far and it's only at the letter K. Is that normal?

**Comment by tidusjar** [comment]
Never really looked at Plex, didn't know it displayed anything. I'll take a look at somepoint tonight if I can

**Comment by heartisall** [comment]
Yea it took between 2-3 hrs to finish the scan, right when it finished it just started over again and is pretty much endlessly querying my plex server.

**Comment by tidusjar** [comment]
The schedule is configurable for this reason?

**Comment by heartisall** [comment]
Ok, let me mess with the Plex availablity checker scheduler and see if It helps. Is there a max value to the minutes variable that I can put in?

**Comment by tidusjar** [comment]
Not really, it does require a restart for the settings to work though.

**Comment by heartisall** [comment]
I changed the availablility checker to only check once a week, but it's still running through my library constantly. I did reset OMBI after I changed the value.

**Comment by tidusjar** [comment]
Sorry, you want to change the Plex Cacher to once a week, not the
availability checker!
