### ISSUE TITLE
Admin account login only works once

### ISSUE THREAD

**Issue by nbyloff** [tidusjar/Ombi#911]
#### Ombi Version:

V 1.10.1

#### Operating System:

Synology NAS

#### Mono Version (only if your not on windows)

Mono JIT compiler version 4.2.1 (Stable 4.2.1.124/39edf24 Tue Dec 27 19:20:37 CST 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

Nothing is being written. Changed permissions to 777 just in case.

```
2017/01/10 10:47:08.546 PlexRequests.UI.Program Trace: Getting startup Port
2017/01/10 10:47:09.754 PlexRequests.UI.Program Trace: Port: 0
```

#### Problem Description:

Admin login does not work after initial wizard setup. I cannot change permissions on other user accounts to make them an admin, and I also cannot login with the newly created admin account.

#### Reproduction Steps:

When I go through the wizard and setup Ombi, it all works fine and logs me into with the newly created admin account. However, even though I have saved the user name and password in the browser, cleared cookies, etc. I cannot login anymore with that admin account. When I try and make my main Plex.tv user an admin, nothing happens. but I see JavaScript/angular errors in the console.

```
Error: [orderBy:notarray] http://errors.angularjs.org/1.5.8/orderBy/notarray?p0=%7B%22%24%24state%22%3A%7B%22status%22%3A0%7D%7D
```

I even tried making a new user that's an admin. But logging in with that new account fails as well. After trying all these attempts, I checked the log folder, and it only shows the two lines above.

**Comment by tidusjar** [comment]
Did the admin account have the same username as the Plex Account?

**Comment by nbyloff** [comment]
No, I specifically made a different name to avoid this conflict. Rebooted couple times and can only login with my actual plex account, not the local admin account created during wizard setup.

**Comment by SuperPotatoMen** [comment]
@nbyloff did you use the /userlogin page to login with your local admin account or did you use the admin login page (that is a different one, click on the admin right corner)

**Comment by tidusjar** [comment]
I think the latest Early Access Preview branch will help you with the possible confusion:
https://ci.appveyor.com/project/tidusjar/requestplex/build/2.0.1212/artifacts

This will be released very soon.

**Comment by SuperPotatoMen** [comment]
Hi @nbyloff Can you give us some feedback on the build that Tidusjar just post?

**Comment by nbyloff** [comment]
Absolutely. I probably won't be able to get to it until tomorrow night or this weekend, but I will.  Does the EAP branch have the exe pre-built? I'm not really setup here to compile executables.

**Comment by SuperPotatoMen** [comment]
No problem, we will wait for that 👍  The EAP branch does have the exe files.
Pleas be aware: you need to delete all of the files except the "PlexRequests.sqlite" files.
If you unzip and unblock the files place your PlexRequests.sqlite file back and you are ready to go :)

**Comment by nbyloff** [comment]
I was about to install it. Checked out the EAP branch but don't see any exe?

**Comment by SuperPotatoMen** [comment]
Hi,  im not following.  You need to run the eap build that tidusjar  post 2 days ago in this post. 

The file called Ombi.exe

**Comment by nbyloff** [comment]
Yeah, I'm not either. I am not sure what I am supposed to be seeing on that link. There's no files to download at all. We must see different things in that link...

I even created an account on appveyor

**Comment by SuperPotatoMen** [comment]
The new version is live. Can you use that one? :)

**Comment by nbyloff** [comment]
Yes this release seems a lot more stable.
