### ISSUE TITLE
UI Bug - Admin view Requests defaults to "All" but says "Not Approved"

### ISSUE THREAD

**Issue by DblTapZ** [tidusjar/Ombi#915]
#### Ombi Version:

V 2.0.1207

#### Update Branch:

EAP

#### Operating System:

OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview
Log Level:	Info
Database Location:	C:\Ombi\Ombi.sqlite
Running Directory:	C:\Ombi

#### Applicable Logs (from `/logs/` directory or the Admin page):

Nothing in logs, just a UI bug

#### Problem Description:

When navigating to the Requests page, it shows All movies, but the filter at the top says Not Approved. Example in the gfycat link below

https://gfycat.com/OfficialJampackedDinosaur

#### Reproduction Steps:

Have an already approved movie, and then as an admin look at the requests page, and all movies show up instead of only Not Approved. Has also occurred on previous EAP 2.0 builds and PR 1.10.1

**Comment by SuperPotatoMen** [comment]
Assigned to @tidusjar for investigation & fix
