### ISSUE TITLE
Request: Scan for deleted requests

### ISSUE THREAD

**Issue by topper59** [tidusjar/Ombi#918]
I have a separate folder and Plex library for requests, and it's been working great. But, I have a script that runs daily at 4:30am that deletes any requested movie older than 30 days to save space. The script also refreshes the Requests library in Plex to reflect the change via the URL command. Couchpotato scans the folder daily for changes as well. The only thing left is PR/Ombi because the requests still show up in the Requests section, and as a result they show up as "Available" when searching. This prevents someone from requesting a previously deleted request again, in case they didn't watch it within the 30 days or someone else wants to watch it. 

I realize this is probably a really niche use, but it would be nice to be able to either scan the folder daily for missing/deleted requested movies or somehow allow requests to be deleted via a script. 

Great work by the way, even without this functionality it's been working perfectly!

**Comment by SuperPotatoMen** [comment]
@topper59  Maybe you can use the Ombi api to delete the record from the database?
