### ISSUE TITLE
Add support for Radarr (Sonarr for movies)

### ISSUE THREAD

**Issue by TheDogg** [tidusjar/Ombi#920]
#### Ombi Version:

V 1

#### Update Branch:

Stable/Early Access Preview/development

#### Operating System:

Windows 10

#### Problem Description:

Add support for Radarr (https://github.com/Radarr/Radarr) for movies (alternative to couchPotato)

**Comment by tidusjar** [comment]
Please see: http://feathub.com/tidusjar/Ombi/+33
