### ISSUE TITLE
Support for Radarr Integration

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/Ombi#923]
Feathub request: http://feathub.com/tidusjar/Ombi/+33
Needs api Integration

See : https://github.com/Radarr/Radarr/issues/194

**Comment by SuperPotatoMen** [comment]
On hold be because radarr don't have a working api yey

**Comment by Keelan** [comment]
@SuperPotatoMen 

Realistically its a fork of sonarr should the existing code work (essentially)?

**Comment by galli-leo** [comment]
@SuperPotatoMen To add to what Keelan said, the API is working. It's just not documented. However, if you hop on our discord (https://discord.gg/AD3UP37) we are more than willing to help you understand the most important endpoints :)

**Comment by SuperPotatoMen** [comment]
@tidusjar do you have time to do a implementation in the 2.1 release?

**Comment by tidusjar** [comment]
Possibly, just need to chat to the guys really at some point.

**Comment by SuperPotatoMen** [comment]
@galli-leo Thanks for you input! @tidusjar  will go back you to guys soon.

For now i planned this one for the V2.2 release.

**Comment by tidusjar** [comment]
I've started working on it. Should be in the next release :)

**Comment by SuperPotatoMen** [comment]
Repland to 2.1 :)

**Comment by SuperPotatoMen** [comment]
Status is in progress

**Comment by tidusjar** [comment]
This is now in the Early Access Preview Branch!
