### ISSUE TITLE
Missing Requests on EAP Branch after upgrade.

### ISSUE THREAD

**Issue by Rsslone** [tidusjar/Ombi#925]
#### Ombi Version:

V 2.0.1213

#### Update Branch:

Early Access Preview

#### Operating System:

Win8.1

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
```

#### Problem Description:

Requests are missing from the EAP branch after upgrade to 2.0.1213. I sat to see if they would load for a bit but nothing came of it.

#### Reproduction Steps:

-Upgrade from 2.0.1198 to 2.0.1213
-Log into Admin account
-Go to "Requests" page
-Observe the screen.

![blob](https://cloud.githubusercontent.com/assets/2944704/21913262/9907e528-d92b-11e6-8c50-3e4a5a1e10c0.png)

**Comment by porksandwich** [comment]
Also experiencing this on upgrade from 2.0.1198 to 2.0.1213.

**Comment by nightwing12** [comment]
changing the filter from 'not approved' to 'approved' or 'all' will show you the requests. looks like maybe the default option got changed to 'not approved'

**Comment by Rsslone** [comment]
@nightwing12 MInd... Blown. Okay if we can confirm that this can be close. Obviously that should be stated so the issues page doesn't get flooded.

**Comment by nightwing12** [comment]
@Rsslone i think its still a legit issue, i cant find a setting to not have it default to that view. it should probably default to All.

**Comment by Rsslone** [comment]
Maybe add a setting for this? I'd love to have default view options and maybe a filter to view requests of each user. I'm sure Jamie will figure it out but seems as intended if that's the case. Just threw me off a bit.

**Comment by tidusjar** [comment]
Finished, the admin can set a default filter and sort for the admin users. Regular users will always just have the default.

**Comment by tidusjar** [comment]
This is now in EAP, please let me know what you think so we can get EAP released 😄
