### ISSUE TITLE
Logged on idle refreshes to inbetween login state

### ISSUE THREAD

**Issue by DblTapZ** [tidusjar/Ombi#926]
#### Ombi Version:

V 2.0.1213

#### Update Branch:

EAP

#### Operating System:

OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview
Log Level:	Info
Database Location:	C:\Ombi\Ombi.sqlite
Running Directory:	C:\Ombi

#### Applicable Logs (from `/logs/` directory or the Admin page):

No visible logs, UI issue

#### Problem Description:

After being logged in a while and letting the page idle, when refreshing/navigating elsewhere you lose access to User Management and the Settings (at least when I'm logged in as admin), and are on the Log In page, but still have access to other pages. And then have to log out and back in to get the admin options back. This started to occur for me on V 2.0.1207

#### Reproduction Steps:

Log in as local admin user, leave the page in the background and come back after a bit (not sure on exact time, maybe 10-15min) and refresh page. User Management and Settings are gone, but can still access Search, Requests, and Issues but can't approve/deny etc. See linked video for an example

https://youtu.be/cmc5Guqn7gM

**Comment by tidusjar** [comment]
Are you running Sonarr with Forms Authentication?

**Comment by DblTapZ** [comment]
I do have the Forms authentication enabled yes, and also had it enabled while I was on PR V1.10.1, didn't experience this event prior

**Comment by SuperPotatoMen** [comment]
see: https://github.com/tidusjar/Ombi/issues/697

**Comment by DblTapZ** [comment]
As a note, I have Ombi and Sonarr running on 2 different systems
