### ISSUE TITLE
Unable to log in without password

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#928]
Ombi Version:
V 2.0.1224

Update Branch:
Development

Operating System:
Windows 10 Home x64

Problem Description:
Even though "Require users to login with their passwords" is unchecked under authentication, Ombi is still forcing users to sign in with their Plex.tv password.

**Comment by tidusjar** [comment]
The admin will always have to login. Is the user a Plex user or local user
with the admin permission?

**Comment by mrangryoven** [comment]
Can confirm the same issue, all users are being asked for passwords when logging in. "Require users to login with their passwords" is also unticked for me.

**Comment by tidusjar** [comment]
Does this user have admin permissions
See the above post.

**Comment by mrangryoven** [comment]
@tidusjar Its an odd situation, a few users have admin permissions, however, the plex media server account does not have admin permissions and still asks for a password. My personal account which is an admin asks for a password and so do all the other admin accounts. Other accounts that are not admins are not asked for passwords, just the account that runs the Plex Media Server, which it has never done before.

**Comment by chrisausbun** [comment]
@tidusjar sorry for the delay, I can confirm it's only requiring password for Admin users. No the users are not local users. But as @mrangryoven stated, it has never asked for password before.

On Jan 15, 2017, at 9:45 AM, mrangryoven <notifications@github.com<mailto:notifications@github.com>> wrote:


@tidusjar<https://github.com/tidusjar> Its an odd situation, a few users have admin permissions, however, the plex media server account does not have admin permissions and still asks for a password. My personal account which is an admin asks for a password and so do all the other admin accounts. Other accounts that are not admins are not asked for passwords, just the account that runs the Plex Media Server, which it has never done before.

-

**Comment by tidusjar** [comment]
This behaviour is expected. Because of the new permissions I decided to not allow users with admin permissions to login without a password, as admin permissions means they have access to EVERYTHING on Ombi.

Also the Plex Server admin is also treated as an administrator.

**Comment by chrisausbun** [comment]
Ok that makes sense. I assumed this behavior was for all users so I'm happy that's not the case. Thanks.

On Jan 15, 2017, at 11:28 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #928<https://github.com/tidusjar/Ombi/issues/928>.

-

**Comment by schott1984** [comment]
> This behaviour is expected. Because of the new permissions I decided to not allow users with admin permissions to login without a password, as admin permissions means they have access to EVERYTHING on Ombi.
Also the Plex Server admin is also treated as an administrator.

PERFECT. I am glad my PMS owner login has password required, but I was PUZZLED as to if there was a setting or how it ended up being this way. Now I understand it's designed to be that way!
