### ISSUE TITLE
No option to log in as Admin

### ISSUE THREAD

**Issue by jrdnlc** [tidusjar/Ombi#929]
hey guys just installed the latest Ombi version 2.0.1223. After creating an account and changing base url to "request" I no longer get an option to log in as admin.

**Comment by dunecokc** [comment]
@jrdnlc  When I switched to the EAP I noticed that too, but if you type in admin as the plex username, and the password you set, should let you in.

**Comment by jrdnlc** [comment]
Ah! Looks like the admin/user logins have been merged. Thays why the option is no longer there. Thanks!

**Comment by Keelan** [comment]
I dont require a password just plex user login. Both my plex and admin account wont login (admin because no password field.)
