### ISSUE TITLE
Always shows new update available

### ISSUE THREAD

**Issue by escservices** [tidusjar/Ombi#930]
#### Ombi Version:

V 2.0.1223

#### Update Branch:

Stable

#### Operating System:

Windows 10 Pro 64Bit

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Nothing, just getting Sonarr and couchpotato profiles.

```

#### Problem Description:

It always says there is a new update available.  
![problem](https://cloud.githubusercontent.com/assets/1287511/21960252/1075bf4a-dab2-11e6-9b09-81f1b4f8a203.JPG)

#### Reproduction Steps:

It's always there, tried reinstalling manually and tried auto update after manually updating.

**Comment by jrdnlc** [comment]
I'm having the same issue. I'm sure there is a fix on the way

**Comment by lattedesu** [comment]
Same issue here. I deleted the plexrequests.net folder and made a clean install from scratch.

**Comment by tidusjar** [comment]
This is fixed now right?

**Comment by lattedesu** [comment]
Can confirm after (auto)updating I don't see the issue.

**Comment by jrdnlc** [comment]
Can confirm is fixed @tidusjar

**Comment by escservices** [comment]
@tidusjar still happing for me, it went away for awhile then there was an update for 2.0.1 and after updating same thing notification is still there.

**Comment by tidusjar** [comment]
It's there currently? What is your branch set in the settings?

**Comment by escservices** [comment]
Stable, but I figured out the problem I tried to update using the automatic update option and it never went to 2.0.1 so I just manually copied the files over and now I'm on 2.0.1 and the notification is gone. Thanks
