### ISSUE TITLE
Can't request series

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#934]
#### Ombi Version:

V 2.0.1223

#### Update Branch:

Stable

#### Operating System:

Windows 2012R2

#### Applicable Logs (from `/logs/` directory or the Admin page):

No logg info see bellow.

#### Problem Description:

I simply cant request series any more, and here comes the tricky part.

Nothing happens when i click the request button, no request is made, no error in chrome console and network log is empty, its like the button is not even used.

Movies works fine as showed bellow, and Sonarr connection is OK.

Nothing in logs, Error,Trace,Debug since button click is not even registered?

http://prntscr.com/dw05xr
http://prntscr.com/dw094s
http://prntscr.com/dw09iq

Before i updated to Ombi we got an Error saying "Something went wrong"

#### Reproduction Steps:

Request any series.

**Comment by SuperPotatoMen** [comment]
Did you do a fresh installation?

**Comment by ElYoM** [comment]
Same bug for me, except that when I try the request again, it appears this time in "pending approval" status. In the end, I can not approve it anywhere.

**Comment by SuperPotatoMen** [comment]
Same question for you :-)  Did you do a fresh installation?

**Comment by ElYoM** [comment]
Sorry you answered me while I was editing my previous post. ;)

**Comment by SuperPotatoMen** [comment]
@tidusjar can you look at this one?

**Comment by SuperPotatoMen** [comment]
@tidusjar can you look at this one?  Core function is maybe broken with the last update?

**Comment by dbershev** [comment]
I have the same issue. Running it on Ubuntu 16.04, fresh install using old sqlite db.

**Comment by chrisausbun** [comment]
I too am having the same issue running on Windows Home x64, using old sqlite db that I renamed from PlexRequests.sqlite to Ombi.sqlite after doing a fresh install.

**Comment by SuperPotatoMen** [comment]
I canceld the rolling out of The v2.0 release for making a hotfix.

**Comment by tidusjar** [comment]
This was a bug from a PR... I should have checked it a bit more thoroughly.

**Comment by SuperPotatoMen** [comment]
@Garderoben @ElYoM @dbershev @chrisausbun thanks for reporting this issue.
@tidusjar just release a hotfix release. Pleas upgrade to version:  V2.0.1

**Comment by chrisausbun** [comment]
The issue is still occurring with V2.0.1 for me. My OS is Windows 10 Home x64.

**Comment by Garderoben** [comment]
@SuperPotatoMen Fresh install with old database.

After updating to 2.0.1 i can now press the button but now we get errors.
http://prntscr.com/dw8a5w
http://prntscr.com/dw8b10
Nothing in Error log

Trace logs:
http://prntscr.com/dw8bel

**Comment by SuperPotatoMen** [comment]
something triggert a 404 not found error :/

**Comment by Garderoben** [comment]
@SuperPotatoMen i think i know why, when looking for the same show in Sonarr i cant find it.
I tried requesting another show and it worked :)

**Comment by SuperPotatoMen** [comment]
@Garderoben can you open a new issue for that one? .  We have a failed queue handle system that should pick up kinds of this errors. But i looks like hé doesn't do his job.

**Comment by ElYoM** [comment]
Thanks for the hotfix ! ;-)
