### ISSUE TITLE
Content requested no longer list who requested it

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#936]
#### Ombi Version:

V 2.0.1224

#### Update Branch:

Development

#### Operating System:

Windows 10 Home x64

#### Problem Description:

Movies requested no longer list "Requested By".

#### Reproduction Steps:

Request any movie.

**Comment by SuperPotatoMen** [comment]
Do have a printscreen?

**Comment by chrisausbun** [comment]
So, this is kind of strange. I went ahead and tested a request with another user and it looks like it's showing requested by with that user but then the two prior requests does not show requested by.

![requested](https://cloud.githubusercontent.com/assets/22944072/21973317/a5ecfd32-db74-11e6-8d29-5d089d21a6a3.png)

**Comment by SuperPotatoMen** [comment]
Is old Request makes before you upgraded to Ombi?

**Comment by SuperPotatoMen** [comment]
Maybe a migration database issue from the old version to the new one.

**Comment by chrisausbun** [comment]
I've actually been upgrading my development versions of Ombi daily, so this has been working but for some odd reason it just stopped for two movies. For the most recent movie (Volcano) made 5 hours ago, it worked but then for the two movies requested 9 hours ago it didn't. However, for a movie that was requested a day ago it worked. I'm not too sure what's going on if it's some weird bug that just happened once for the two movies requested 9 hours ago but now that it seems to be fine so, I'm ok with you closing out the issue. Thank you for taking some time to look into this.

**Comment by dbershev** [comment]
I have also encountered this glitch on Ubuntu 16.04.
http://imgur.com/a/4bRbu

**Comment by tidusjar** [comment]
Hmmm, Yeah it must have been a bug from version 1.10 when I introduced the user management. I can no longer reproduce this issue though. This should only happen for requests that was made in 1.10

**Comment by dbershev** [comment]
These requests were made with the latest 2.0.X version...

**Comment by tidusjar** [comment]
I have made lots of changes around this in the new EAP branch that should stop this from happening in the future. I think it was to do with the introduction of using an Alias and I must have missed a bit.
