### ISSUE TITLE
Requested shows added to Sonarr but aren't monitored/downloading

### ISSUE THREAD

**Issue by a2theziz** [tidusjar/Ombi#939]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/01/16 14:32:20.314 Ombi.Api.SonarrApi Debug: Adding series This Is Us 
2017/01/16 14:32:20.337 Ombi.Api.SonarrApi Debug: Seasons = [], out of 0 seasons 
2017/01/16 14:32:20.348 Ombi.Api.SonarrApi Debug: Sonarr API Options: 
2017/01/16 14:32:20.361 Ombi.Api.SonarrApi Debug: {
  "addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": true,
    "searchForMissingEpisodes": false
  },
  "title": "This Is Us",
  "seasons": [],
  "rootFolderPath": "E:\\Plex\\TV Shows",
  "qualityProfileId": 7,
  "seasonFolder": true,
  "monitored": false,
  "tvdbId": 311714,
  "tvRageId": 0,
  "cleanTitle": null,
  "imdbId": null,
  "titleSlug": "This Is Us",
  "id": 0,
  "images": []
} 

2017/01/16 14:35:51.068 Ombi.Api.SonarrApi Debug: Adding series The Big Bang Theory 
2017/01/16 14:35:51.080 Ombi.Api.SonarrApi Debug: Seasons = [], out of 0 seasons 
2017/01/16 14:35:51.095 Ombi.Api.SonarrApi Debug: Sonarr API Options: 
2017/01/16 14:35:51.108 Ombi.Api.SonarrApi Debug: {
  "addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": true,
    "searchForMissingEpisodes": false
  },
  "title": "The Big Bang Theory",
  "seasons": [],
  "rootFolderPath": "E:\\Plex\\TV Shows",
  "qualityProfileId": 7,
  "seasonFolder": true,
  "monitored": false,
  "tvdbId": 80379,
  "tvRageId": 0,
  "cleanTitle": null,
  "imdbId": null,
  "titleSlug": "The Big Bang Theory",
  "id": 0,
  "images": []
} 


```

#### Problem Description:

When requesting shows by "Select Episode" option, the show gets added to Sonarr but it isn't monitored and therefore not downloading automatically. In both cases I selected the first 2 episodes of each show.

**Comment by tidusjar** [comment]
Did this happen for you in version 10.X?

**Comment by tidusjar** [comment]
Just looked at my commit history, none of the sonarr stuff has changed, what version of Sonarr are you running?

**Comment by a2theziz** [comment]
Yeah, had the same issue with v1.10.1.

I'm currently on Sonarr v2.0.0.4472

Looking at the logs:

```
 
2017/01/16 14:32:20.314 Ombi.Api.SonarrApi Debug: Adding series This Is Us 
2017/01/16 14:32:20.337 Ombi.Api.SonarrApi Debug: Seasons = [], out of 0 seasons 
2017/01/16 14:32:20.348 Ombi.Api.SonarrApi Debug: Sonarr API Options: 
2017/01/16 14:32:20.361 Ombi.Api.SonarrApi Debug: {
  "addOptions": {
    "ignoreEpisodesWithFiles": true,
    "ignoreEpisodesWithoutFiles": true,
    "searchForMissingEpisodes": false
  },
  "title": "This Is Us",
  "seasons": [],
  "rootFolderPath": "E:\\Plex\\TV Shows",
  "qualityProfileId": 7,
  "seasonFolder": true,
  "monitored": false,
  "tvdbId": 311714,
  "tvRageId": 0,
  "cleanTitle": null,
  "imdbId": null,
  "titleSlug": "This Is Us",
  "id": 0,
  "images": []
} 


```

This was a request for episodes 1 and 2 for This is Us and from what I can tell, there is nothing in the API requesting those episodes. Also shouldn't the "monitored" be set to true?

Thanks

**Comment by Ublala** [comment]
I've had this issue as well. Also with other request options (can't remember which ones, but not all). Also when selecting a single episode it seems to work. If it happens again I'll make a note of it.

**Comment by tidusjar** [comment]
Hmmm, This is working fine for me with single episodes...

Was the TV Show already requested before?

**Comment by a2theziz** [comment]
Steps
1. I request a new show ABC by selecting episodes EP 1,2 . Show gets added to Sonarr and nothing downloads.
2. I submit a new request for show ABC and this time I request EP 1,2,3 (EP 1,2 already checked)
3. Nothing downloads but when I check the requests page, it is asking to approve the request even though I am admin and have Auto-Approve enabled for all users.
4. I approve the request and EP 1,2,3 start downloading.

So now I have an issue of requests not getting auto-approved.

**Comment by tidusjar** [comment]
Can you post a image of the users permissions that this is not working for?

**Comment by a2theziz** [comment]
Sure!

![untitled](https://cloud.githubusercontent.com/assets/25150295/21993409/be22c6b8-dc2b-11e6-982b-979ed7fe57e6.png)

**Comment by seanvree** [comment]
Hey, I'm not sure if this applies to this issue, but I'm not seeing the requests on the request status page?  I can make a request as the local admin user and it adds the requests to sonarr, but I don't see the status of the request?


Application Version:	2.0.1312
OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview
Log Level:	Info
Database Location:	C:\Ombi\PlexRequests.sqlite
Running Directory:	C:\Ombi

**Comment by tidusjar** [comment]
@seanvree check your filters

**Comment by seanvree** [comment]
@tidusjar  - No filters applied.

**Comment by tidusjar** [comment]
@seanvree can you raise a new issue for this please?

**Comment by ceptonit** [comment]
I'm having the same issue as the OP but here are more details.

Requesting "All Seasons", "First Season", "Latest Season", "Select Season..." all work no problem.

The "Select Episode..." only seems to work if the TV show is already present in Sonarr.

So for example, my Sonarr doesn't have Breaking Bad. If I request any episode of any season, let's use S01E01, Sonarr will get the request, create the Breaking Bad show but same as OP, all episodes/seasons will have their monitored icon turned off and S01E01 doesn't get downloaded.
Now go back to Ombi, and request another episode of Breaking Bad, S02E03, and Sonarr starts the download of S02E03 no problem and switches its monitor on.
S01E01 on the other hand still gets forgotten.

I 've added a show in Sonarr with only its 4th season downloaded.
Made a request in Ombi for S02E03, and Sonarr processed it no problem.

So it just seems that the "Select Episode..." option, right now, only works as long as the show in question is already in Sonarr.
