### ISSUE TITLE
Error when requesting shows that Sonarr cant find

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#940]
**Ombi Version:** V 2.0.1234

**Update Branch:** Stable

**Operating System:** Windows 2012R2

**Applicable Logs (from /logs/ directory or the Admin page):**
Trace logs: http://prntscr.com/dw8bel

**Problem Description:**
When requesting a show that's not on Sonarr yet you get error "Some thing went wrong"
http://prnt.sc/dw8a5w
http://prnt.sc/dw8b10

**Reproduction Steps:**
Request any show that Sonarr cannot find.

**Comment by tidusjar** [comment]
Did you unblock the .zip file before you extracted?

**Comment by SuperPotatoMen** [comment]
@tidusjar this issue look like the failed queue handler doesn't add it to his queue. 
Can we make some changes about that?
