### ISSUE TITLE
Ombi -- Razor Compilation Error -- Ubuntu 

### ISSUE THREAD

**Issue by llamadog123** [tidusjar/Ombi#941]
#### Ombi Version:

V 2.XX

#### Update Branch:

Stable

#### Operating System:

Ubuntu

#### Mono Version (only if your not on windows)

 4.2.3 

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

2017/01/16 08:56:27.918 PlexRequests.UI.Program Trace: Getting startup Port
2017/01/16 08:56:28.079 PlexRequests.UI.Program Trace: Port: 0


```

#### Problem Description:

Razor Compilation Error. Error below:

Error compiling template: Views/Shared/_Layout.cshtml

Errors:
[CS0234] Line: 2 Column: 16 - The type or namespace name `UI' does not exist in the namespace `Ombi'. Are you missing an assembly reference? (show)

Details:
@*@using StackExchange.Profiling*@
@using Ombi.UI.Helpers
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase
<html id="htmlId">
@Html.Partial("Shared/Partial/_Head")

<body>

    @Html.Partial("Shared/Partial/_Navbar")

    <div class="container" style="padding-top: 5%">
        @RenderBody()
    </div>
<div class="scroll-top-wrapper ">
    <span class="scroll-top-inner">
            <i class="fa fa-2x fa-arrow-circle-up"></i>
        </span>
</div>
</body>

@Html.GetInformationalVersion()

</html>
@Html.Partial("Shared/Partial/_LayoutScripts")

Compilation Source:

//` ------------------------------------------------------------------------------
Line 1:	//  <autogenerated>
Line 2:	//      This code was generated by a tool.
Line 3:	//      Mono Runtime Version: 4.0.30319.17020
Line 4:	// 
Line 5:	//      Changes to this file may cause incorrect behavior and will be lost if 
Line 6:	//      the code is regenerated.
Line 7:	//  </autogenerated>
Line 8:	// ------------------------------------------------------------------------------
Line 9:	
Line 10:	namespace RazorOutput {
Line 11:	    using Microsoft.CSharp.RuntimeBinder;
Line 12:	    using System;
Line 13:	    using System.IO;
Line 14:	    
Line 15:	    #line 2 "roo"
Line 16:	    using Ombi.UI.Helpers;
Line 17:	    
Line 18:	    #line default
Line 19:	    #line hidden
Line 20:	    
Line 21:	    
Line 22:	    public class RazorView : Nancy.ViewEngines.Razor.NancyRazorViewBase {
Line 23:	        
Line 24:	#line hidden
Line 25:	        
Line 26:	        public RazorView() {
Line 27:	        }
Line 28:	        
Line 29:	        public override void Execute() {
Line 30:	WriteLiteral("\n");
Line 31:	
Line 32:	WriteLiteral("<html");
Line 33:	
Line 34:	WriteLiteral(" id=\"htmlId\"");
Line 35:	
Line 36:	WriteLiteral(">\n");
Line 37:	
Line 38:	            
Line 39:	            #line 5 "roo"
Line 40:	Write(Html.Partial("Shared/Partial/_Head"));
Line 41:	
Line 42:	            
Line 43:	            #line default
Line 44:	            #line hidden
Line 45:	WriteLiteral("\n\n<body>\n\n");
Line 46:	
Line 47:	WriteLiteral("    ");
Line 48:	
Line 49:	            
Line 50:	            #line 9 "roo"
Line 51:	Write(Html.Partial("Shared/Partial/_Navbar"));
Line 52:	
Line 53:	            
Line 54:	            #line default
Line 55:	            #line hidden
Line 56:	WriteLiteral("\n\n    <div");
Line 57:	
Line 58:	WriteLiteral(" class=\"container\"");
Line 59:	
Line 60:	WriteLiteral(" style=\"padding-top: 5%\"");
Line 61:	
Line 62:	WriteLiteral(">\n");
Line 63:	
Line 64:	WriteLiteral("        ");
Line 65:	
Line 66:	            
Line 67:	            #line 12 "roo"
Line 68:	   Write(RenderBody());
Line 69:	
Line 70:	            
Line 71:	            #line default
Line 72:	            #line hidden
Line 73:	WriteLiteral("\n    </div>\n<div");
Line 74:	
Line 75:	WriteLiteral(" class=\"scroll-top-wrapper \"");
Line 76:	
Line 77:	WriteLiteral(">\n    <span");
Line 78:	
Line 79:	WriteLiteral(" class=\"scroll-top-inner\"");
Line 80:	
Line 81:	WriteLiteral(">\n            <i");
Line 82:	
Line 83:	WriteLiteral(" class=\"fa fa-2x fa-arrow-circle-up\"");
Line 84:	
Line 85:	WriteLiteral("></i>\n        </span>\n</div>\n</body>\n\n");
Line 86:	
Line 87:	            
Line 88:	            #line 21 "roo"
Line 89:	Write(Html.GetInformationalVersion());
Line 90:	
Line 91:	            
Line 92:	            #line default
Line 93:	            #line hidden
Line 94:	WriteLiteral("\n\n</html>\n");
Line 95:	
Line 96:	            
Line 97:	            #line 24 "roo"
Line 98:	Write(Html.Partial("Shared/Partial/_LayoutScripts"));
Line 99:	
Line 100:	            
Line 101:	            #line default
Line 102:	            #line hidden
Line 103:	WriteLiteral("\n");
Line 104:	
Line 105:	        }
Line 106:	    }
Line 107:	}
Line 108:	

#### Reproduction Steps:

First I tried updating automatically, then manually, then I tried a fresh install. All the same error.

**Comment by tidusjar** [comment]
This is a fresh installation? Not overwriting files right?

**Comment by llamadog123** [comment]
The current one is a fresh installation but with overwriting files. When I do a git clone I get everything but the executable. Unless I am missing something. Possible noob alert :)

**Comment by tidusjar** [comment]
Do not overwrite the files, I did mention it in the release note. this is because not much will get overridden because of the name change :smile:

**Comment by llamadog123** [comment]
Then how am I supposed to run it? If cloning the git doesn't give me something to run that is.

**Comment by llamadog123** [comment]
Nevermind. I figured it out. Cloning gets me the SLN. Finding your release in the release notes gave me the executable.

**Comment by tidusjar** [comment]
;)
