### ISSUE TITLE
Question/Support - Plex Channel redirect

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#943]
#### Ombi Version:

V 2.0.1236

#### Update Branch:

Development

#### Operating System:

Windows 10 Home x64

#### Problem Description:

Is there any way to add a custom channel or something in Plex that will redirect them to the Ombi site for any requests they'd like to make? Some of my users don't have a computer or are a little older so it'd be nice if they could just click something in Channels or somewhere in Plex that will take them to the request page. The only thing at the moment I can think of doing is creating a library called "Making Requests and/or Reporting Issues" and have an image with a link and a how to guide Ombi but it'd be much easier and more efficient if they could click somewhere and it'd take them straight there instead, especially if they're trying to do it on a device that isn't a computer.

**Comment by tidusjar** [comment]
Hmmmm... I'd have to make a Plex Channel that will redirect them to your Ombi website... Currently that is a bit out of scope. But please raise it on Feathub to see if others are interested in this.

http://feathub.com/tidusjar/Ombi/
