### ISSUE TITLE
Notification issue question

### ISSUE THREAD

**Issue by ahiguero** [tidusjar/Ombi#944]
#### Ombi Version:

Application Version:	2.0.1234
OS:	Mono
System Version:	4.4.2 (Stable 4.4.2.11/f72fe45 Tue Aug 2 16:34:53 EDT 2016)
Branch:	Stable
Log Level:	Error
Database Location:	/share/CACHEDEV2_DATA/.qpkg/Ombi/Release/Ombi.sqlite
Running Directory:	/share/CACHEDEV2_DATA/.qpkg/Ombi/Release

#### Problem Description:

i would like to understand the newsletter settings. i want to send the "recently added content" to certain plex users (not all of them) so in the newsletter settings i checked the newsletter for recently added content checkbox and disabled (not checked) the send newsletter to all plex users. in the user management i when and selected the newsletter option for the plex users that i want to send the news letter. is this the correct way of doing this?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
I'm not sure i'm following. 

So the 'newsletter' is an email that will go out and inform them what has been recently added to the Plex server.

The other notification is when that user requests something, when it becomes available we will send them an email saying that, that request is now on Plex basically.

Does that answer your question?

**Comment by ahiguero** [comment]
Thank you Jaime for your email

yes i am referring to the newsletter that goes out to the users indicating
what has been added to the server. i would like to send it on a weekly
basis, but only to certain plex friends, not all of them.

if i click on the "send newsletter to all my plex friends, will it send it
to all of them regardless if i select the newsletter option in the user
management screen for that user or not?

**Comment by tidusjar** [comment]
Forgot about that option. Just had a quick look at the code. That send to Plex friends does not do anything anymore. I'll remove it. 

They require the newsletter permission and also a valid email address against their user :D

**Comment by ahiguero** [comment]
ok so if i understood correctly...

the plex user needs to have a valid ip address (checked)
the newsletter permission needs to be enabled (checked)
the newsletter for added content needs to be enabled (checked)
proper configuration of the cron job (check).

i will let you know if it works tomorrow as i have configured the job to
send the newsletter out at 2:00am tomorrow

**Comment by ahiguero** [comment]
It did not work, also i do no see the int he scheduled jobs a job that will trigger the newsletter to be sent

**Comment by ahiguero** [comment]
The newsletter was sent today at 6:00am in the morning but only to the admin account, not to the users that i had selected the newsletter to be sent to.

**Comment by tidusjar** [comment]
Can you post a screenshot of a users permissions that you expected them to get a notification?

**Comment by ahiguero** [comment]
Here are the screenshots
![user setting](https://cloud.githubusercontent.com/assets/9029745/22025841/9b4767ca-dc94-11e6-8443-c0c3b4c5e71b.jpg)

![user setting](https://cloud.githubusercontent.com/assets/9029745/22025995/0e4dcfde-dc95-11e6-9df1-c0f006a420a2.jpg)

let me know if you need the log it is set to debug

**Comment by tidusjar** [comment]
Hmmm... It's enabled in the settings right?

![image](https://cloud.githubusercontent.com/assets/6642220/22026112/c2b9f0ba-dcc7-11e6-965b-79a4a2748ad2.png)

**Comment by ahiguero** [comment]
yes it is enabled Jaime. thats the thing... question could it be that the
email notification setting the recipient field needs to be blank?

**Comment by tidusjar** [comment]
Hi @ahiguero can you please try the latest EAP branch?

**Comment by ahiguero** [comment]
swtiching from the stable branch to the EAP branch... i will trigger the newsletter today and see what happens

**Comment by ahiguero** [comment]
same issue... only the administrators are the only ones getting the newsletter notification. non of hte other users that have the newsletter option selected get it.
