### ISSUE TITLE
Landing page not working on last stable release

### ISSUE THREAD

**Issue by igowas** [tidusjar/Ombi#945]
#### Ombi Version:

V 2.0.1223

#### Update Branch:

Stable

#### Operating System:

windows 7

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Landing page not showing up even if enable box is checked. 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Hello,

Please provide a screenshot of your Landing Page settings?

**Comment by igowas** [comment]
![landingpagesetup](https://cloud.githubusercontent.com/assets/14265154/22012671/4bb469e6-dc63-11e6-817d-9f3063cda043.jpg)

I also try to do a fresh install without using my old database file but same result both way.

**Comment by tidusjar** [comment]
So the expected behavior is once the user logs in, they should be redirected to the landing page. Is that not working?

**Comment by igowas** [comment]
Exactly, it was working fine on version 1.0.

**Comment by geekcroft** [comment]
I had this too - funny though it works if you set the Landing page to show before login.

What is even more bizarre is that the last version I had of Plexrequests.Net had the opposite issue - it would only show after login not before.

**Comment by igowas** [comment]
Btw IT works if I manualy type the URL http://ip/landing so I think its only a redirection bug

**Comment by tidusjar** [comment]
That's right, 

The redirection part is quite complicated unfortunately. Just took a quick look to see if I could easily fix it but it's going to take a bit longer.

It's difficult to explain but it is being redirected but then something is triggering in that HTTP pipeline (maybe because the system has realised that you are authenticated) and taking you to the search page!

**Comment by uberswimmer** [comment]
Thanks for looking in to this. I am experiencing the same issue on EAP 2.1.1496 and appreciate the insight.

**Comment by MarcusSattler** [comment]
Same here,

Thanks!
