### ISSUE TITLE
Can't save email address for Plex Home users

### ISSUE THREAD

**Issue by RXWatcher1** [tidusjar/Ombi#947]
Application Version:	2.0.1234
OS:	Ubuntu 16.04 using Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
Branch:	Stable

#### Problem Description:

I would like to add email addresses to my Plex Home users so they can get email notifications for the newsletter.

#### Reproduction Steps:
Go into User Management
Scroll Down to a Plex Home user and edit it.
Add Email Address and select Update.
Email address will be populated in the list of users correctly immediately after the update.
Leave User Management and go back in
Email address will be missing.

**Comment by SuperPotatoMen** [comment]
If you f5 on the user management page, is the problem fixed or still there?

**Comment by RXWatcher1** [comment]
The issue is still there. I also tried in incognito mode of chrome.

I can create a new user and it saves the information. It seems specific to the Plex Home users.

**Comment by SuperPotatoMen** [comment]
Thanks for you information, @tidusjar will take it from here.

**Comment by ninthwalker** [comment]
Not to hijack this thread, I can make another one if needed.
But could it be possible to edit/save the email of a plex user to override the email that is pulled down from plex.tv? Thanks.

**Comment by SuperPotatoMen** [comment]
@ninthwalker pleas make a new issue for that question.  Thanks :)

**Comment by tidusjar** [comment]
It's being saved into the database, I'm just not returning it to the UI. Fixed that now.

**Comment by RXWatcher1** [comment]
I will test this a bit later but I don't think it's sending the newsletter to these people even if it's being stored and not displayed. I have to test because I'm not sure I tested this after I figured out the newsletter button wasn't correct.

**Comment by SuperPotatoMen** [comment]
And why do you think that? :)

**Comment by tidusjar** [comment]
I'm pretty confident it will work, it's goes through the `NotificationEngine`, and the users are pretty generic, it just lookups up the users from the database, we don't use any Plex information at that point (as managed users do not have email addresses in Plex)
