### ISSUE TITLE
User Management "Modify Features" check boxes are not correct. 

### ISSUE THREAD

**Issue by RXWatcher1** [tidusjar/Ombi#951]
#### Ombi Version:

Application Version:	2.0.1234
OS:	Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
Branch:	Stable
Log Level:	Trace

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:
Users are not getting the newsletter
Users not getting Request Added Notifications

#### Reproduction Steps:
User Management->Details/Edit User->Check Newsletter checkbox under Modify Features.

Modify Features:
Newsletter
Request Added Notification

What I have uncovered by debugging and tracing this:

* The newsletter gets sent to the user when "Request Added Notification" is checked.

* No Request Added Notifications are sent no matter what checkbox is checked.

**Comment by tidusjar** [comment]
I've fixed the newsletter issue... My bad!

But I cannot find the issue with "Request Added Notification".

You need to make sure your email settings are filled in correctly.

**Comment by RXWatcher1** [comment]
The settings are correct for the email sending client. Once I swapped the checkbox, people started seeing the newsletters. I actually had the newsletter cronjob running every 5 minutes and I was tailing the log to watch it happen which I worked through the issue and I checked the sent mail on my gmail account used to send these.

I did get one of these today:
**Hi there!

My_Movie is now available!

Hello! You requested My_Movie on PlexRequests! This is now available on Plex!** 

I am not seeing it even try to send Request Added Notifications.

Should this trigger when a Request is added to the Ombi system OR when the media was actually added to Plex?

If its the former then I should be getting notifications on any requests that are added to the system and I'm not getting those and if it's the latter then I should be seeing it send the above message to everyone on my system as both checkboxes are checked at the moment. I wonder if the Newsletter being the wrong checkbox issue was interfering with this Request Added Notification?

**Comment by tidusjar** [comment]
So yeah, I was using the Request Added Notification for the newsletter, I've fixed that now (My bad).

The real request added notification works like the following:
User A Requests Movie B
Ombi detects that Movie B is now in Plex
Ombi will get all users with the request added notification
Find which user requested Movie B (could be multiple)
Check that user has a valid email address
Send "You requested Movie B, this is now available!" email to that user.


Does that help?

**Comment by RXWatcher1** [comment]
Yes, that helps a lot. I didn't think about a use case where multiple people would request the same movie.

May I ask what the purpose of the slack notification is?
I can get the initial test message to appear but nothing after that. I was thinking it might be to send all notices that a movie was requested and it is now in plex..Ala a team notification.

**Comment by tidusjar** [comment]
The slack notification does the following:

Notifies for Issues, New Requests, Test messages and if some request was added to the fault queue.
