### ISSUE TITLE
Users Required to Enter Password even when Option is turned off

### ISSUE THREAD

**Issue by lastb0isct** [tidusjar/Ombi#953]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Notifying Users Count 1	Ombi.Services.Notification.NotificationEngine	Debug	1/18/2017 9:51:47 PM
Requests that will be updated count 1	Ombi.Services.Jobs.PlexAvailabilityChecker	Debug	1/18/2017 9:51:46 PM


```

#### Problem Description:

Users are still being asked to enter in their password even with the authentication option unchecked.  Also, when "Enable User Authentication" option is completely turned off the users are still asked for both user/pass to enter in.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Does the user have the administrator permission? Administrators need to use
a password since they have control over the whole system.

**Comment by lastb0isct** [comment]
You're correct!  Looks like previously I was able to get by the password prompt somehow.  Just had a friend try and it went straight through for them.  Thank you!!
