### ISSUE TITLE
[Request] TVMaze API Images

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#955]
API - http://api.tvmaze.com

can we change the image url when parsing info from this api to HTTPS?  currently it parses the images as HTTP which will break pages served through HTTPS.  

P.S.

I'm digging the new update!  Thank you for everything you are doing.

**Comment by tidusjar** [comment]
Oh really? I thought I did this previously! I'll get to it!

**Comment by tidusjar** [comment]
Where in the UI are we loading them over HTTP? @causefx 


![image](https://cloud.githubusercontent.com/assets/6642220/22098817/49bf20ae-de20-11e6-8be9-c94dc90fb8ea.png)

**Comment by causefx** [comment]
hi @tidusjar,

I'm seeing this in the request screen:

![image](https://cloud.githubusercontent.com/assets/16184466/22114649/789a16a2-de27-11e6-874d-714b37f0db6f.png)
![image](https://cloud.githubusercontent.com/assets/16184466/22114697/a32b6b8c-de27-11e6-84cb-ab345391af8b.png)

that's odd that yours shows correctly.

**Comment by causefx** [comment]
another image:
![image](https://cloud.githubusercontent.com/assets/16184466/22114907/43d1eb92-de28-11e6-841e-7f4ba489d4c4.png)
