### ISSUE TITLE
Bulk option for change the permissions in user management 

### ISSUE THREAD

**Issue by PotatoQuality** [tidusjar/Ombi#957]

**Comment by lpreams** [comment]
This would be an excellent addition, especially for new setups. Ombi automatically adds my shared users as Ombi users before I get a chance to set default permissions. It would be nice if either there was a button to apply the global default to current users, or, alternatively, if the default permissions were added to the setup wizard so permissions could be selected before Ombi imports users from Plex.

**Comment by basmith7** [comment]
did this get implemented?

**Comment by lpreams** [comment]
No, hence this issue still being Open

**Comment by crotinger** [comment]
As a workaround, you can modify the permissions in the DB directly. Use at your own risk.

**Comment by MagicMicky** [comment]
Why was this issue closed ?
I still don't see any bulk editing options, and editing in the database, even if it can be a workaround, is too much hacky to close the issue imho

**Comment by PotatoQuality** [comment]
pleas read first the issue i opened where im explaining why all the issues are closed

**Comment by MagicMicky** [comment]
Oops thx. For other users: https://github.com/tidusjar/Ombi/issues/1455
