### ISSUE TITLE
Omni is not refreshing plex friend email addresses

### ISSUE THREAD

**Issue by RXWatcher1** [tidusjar/Ombi#958]
#### Ombi Version:

Application Version:	2.0.1234
OS:	Ubuntu 16.04 using Mono
System Version:	4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
Branch:	Stable

#### Update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I'm sorry to keep hammering at these User Management issues..I love Ombi! Thats why I keep working on it and finding issues.

I have a Plex Friend who's email address was incorrect. gmaill.com instead of gmail.com. I had her correct it in Plex however Ombi isnt pulling in the updated email address. I obviously can't edit the email address in Ombi as it has to come from Plex.

Plex User Checker has been running on a regular basis,  I have restarted the application.

#### Reproduction Steps:

Have a plex friend alter their email address via plex and see if Ombi gets updated.

**Comment by tidusjar** [comment]
So the Plex User checker should pick up that it's changed and update it!

Code is here: https://github.com/tidusjar/Ombi/blob/a1cc3b6690a79403389c3e07be722907f597d1bb/Ombi.Services/Jobs/PlexUserChecker.cs#L103

We are checking if the user returned from the Plex Api email address is the same as what we have stored locally, if it's not then update our database with the new email address.

Unless the API is not returning the new email address :/ 

Can you check what is returned from the API?

https://plex.tv/pms/friends/all?X-Plex-Token=**PLEXTOKEN**&X-Plex-Client-Identifier=1&X-Plex-Product=Ombi&X-Plex-Version=2

**Comment by RXWatcher1** [comment]
You are spot on. It's not updated on the Plex side. I will close this.

Thank you for all of your efforts.

**Comment by tidusjar** [comment]
No problem!

Make sure they did actually change it! :)
