### ISSUE TITLE
Newsletter feature issue

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#959]
Application Version:	2.0.1223
OS:	Mono
System Version:	4.2.2 (Stable 4.2.2.30/996df3c Fri Jan 29 21:11:18 CET 2016)
Branch:	Stable
Log Level:	Error
Database Location:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release/Ombi.sqlite
Running Directory:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release

#### Problem Description:

I added few users yesterday and at user level I didn't check the "Newsletter" feature. I do have the global setting: "Enable the newsletter of recently added content" enabled. Today all these new users were copied in the e-mail with the last movies added to Plex.
If I understood correctly the settings it shouldn't have happened unless I'm missing something.

Also a question related: What is the period of time Ombi is taking into account for new content added to Plex?

#### Reproduction Steps:

1. Create new Ombi user without the "Newsletter" privilege
2. Wait until Newsletter is generated.

**Comment by tidusjar** [comment]
There is a bug that I have fixed where I was using the wrong feature. The newsletter was getting sent for the "Added Notification". 

Regarding the newsletter, I just call the Recently Added API that Plex returns, I will be looking to improve this in the future.

You can run the Early Access Build for the fix.
