### ISSUE TITLE
Availability status not updating after adding requested tv show to Plex

### ISSUE THREAD

**Issue by rock7632** [tidusjar/Ombi#960]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable
#### Operating System:

Ubuntu 16.04

#### Mono Version (only if your not on windows)

4.21

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Availability does not update to "available" on requests page after a tv show has been added to Plex. Under scheduled jobs it shows that Plex availability cacher and all other jobs were run after the show was added. Logs don't show any errors.

#### Reproduction Steps:

Request a show, add show to Plex, let scheduled jobs run and it does not show as available in the requests page.

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/Ombi/issues/817
