### ISSUE TITLE
Plex Server Status and Notice Message on main page instead of needing Landing Page

### ISSUE THREAD

**Issue by wibuf** [tidusjar/Ombi#961]
#### Ombi Version:

V2.0.1234

#### Update Branch:

Stable

#### Operating System:

Mono

#### Mono Version (only if your not on windows)

4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

No problem, just a feature request. I think the status of the server and notice message would be good to have on the main request page. Even if it just in the status bar so user's can see it without needing to click through an extra landing page.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Feature request goes over here: Pleas submit a feature request over here: http://feathub.com/tidusjar/Ombi

(it is in the issue format post)
