### ISSUE TITLE
Newsletter sending out regardless of User setup

### ISSUE THREAD

**Issue by DblTapZ** [tidusjar/Ombi#965]
#### Ombi Version:

V 2.0.1252 I believe when I was notified of the issue about 30min ago. Had updated to newest EAP immediately after
V 2.0.1260 Currently, but has been happening since at least a week ago

#### Update Branch:

EAP

#### Operating System:

OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview
Log Level:	Info
Database Location:	C:\Ombi\Ombi.sqlite
Running Directory:	C:\Ombi

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

```
Except from 1-13-17 of time when newsletter went out (7am EST)
http://pastebin.com/6FkAXPmK

1-20-17
http://pastebin.com/wA3UpNf0
#### Problem Description:

Newsletter is sending out to users even if "Send to all of your Plex 'Friends'" is unchecked, as well as not having their email in the manual list. Users received Newsletter even with Newsletter Feature unchecked in User Management as well. And on the topic of newsletters, the Movie section is right aligned when viewing the email on a computer, but the TV section is left aligned 

http://imgur.com/cXYuIbt.png
http://i.imgur.com/ay7cOVt.png
http://i.imgur.com/f4WcQE2.png

#### Reproduction Steps:

Check the box to "Enable the newsletter of recently added content" and make sure Email Notifications are set up. I had a couple emails in the manual text box, but others that weren't set were still sent

**Comment by tidusjar** [comment]
This is unusual! 

I'll take a look into this, can you please upload screenshots of your newsletter settings and also a users permissions that is receiving the newsletter when thry shouldn't be?

**Comment by DblTapZ** [comment]
Sure. Here's 3 screenshots from it

1. http://i.imgur.com/wOjdJeq.png Newsletter Settings Page. It's enabled, but only the 2 email addresses listed should be getting the email.

2. http://i.imgur.com/TJmpqo3.png User Management for 1 of my users, who touched base with me about the email being formatted weirdly, and then me noticing that they should never have gotten that email to begin with.

3. http://i.imgur.com/mXNO3zz.png User Management for another user I contacted right afterwards and had them check their email, and they had also received the newsletter

**Comment by tidusjar** [comment]
Ah yes, there was a bug that I have fixed where users with the Request Added notification feature was getting the newsletter. If you upgrade to the latest EAP build it will be fixed.
