### ISSUE TITLE
Unable To Disable Watcher

### ISSUE THREAD

**Issue by vertigo235** [tidusjar/Ombi#970]
I am unable to disable watcher (so that I can enable radarr).  When I try to uncheck the enable box for watcher it says "Cannot have Watcher and CouchPotato both enabled.", which is fine because I don't have couchpotato enabled and never have.  That's beside the fact that I'm trying to disable watcher.

#### Ombi Version:

V 2.0.1260

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 10 64bit

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by vertigo235** [comment]
Thank you sir

**Comment by tidusjar** [comment]
Thank you for reporting it!
