### ISSUE TITLE
Custom Donation URL

### ISSUE THREAD

**Issue by gilbN** [tidusjar/Ombi#972]
#### Ombi Version:

V 2.0.1234

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When I add a custom donation URL it adds the base url before the custom URL. 
So when a user clicks the custom donation button it redirects to: http://192.168.1.177:3579/www.paypal.me/xxxxxxx
I guess this is useful if you have a reverse proxy setup that can redirect the /Custom Donation URL

Is there any way to not have it do this?

#### Reproduction Steps:

Add custom donation URL-
Click on custom donation button-

**Comment by porksandwich** [comment]
Try using the full url.

https://www.paypal.me/xxxxxx

**Comment by gilbN** [comment]
Thanks! That worked great!
