### ISSUE TITLE
Movie in Plex is not show as available and user can put it in the request list

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#973]
Application Version:	2.0.1223
OS:	Mono
System Version:	4.2.2 (Stable 4.2.2.30/996df3c Fri Jan 29 21:11:18 CET 2016)
Branch:	Stable
Log Level:	Error
Database Location:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release/Ombi.sqlite
Running Directory:	/share/CACHEDEV1_DATA/.qpkg/Ombi/Release

#### Problem Description:

I have 1 movie that for some reason is not mark as available in Ombi. One user searched it put the request for it but is already available. I marked it as available but if another user search it .. again .. is put in the request list. The name of the movie in Plex match what Ombi shows so not sure what could be wrong.

Other movies added after this one are showed correctly in Ombi.

Not sure how to troubleshoot this.

#### Reproduction Steps:

User search movie in question. Ombi doesn't show it as available.

**Comment by tidusjar** [comment]
Is it just that one movie that is causing the issue?

**Comment by cesalo** [comment]
Yes, so far. I've been trying to find another case but no luck. I've tried movies recently added or even old ones and couldn't replicate the issue.

**Comment by cesalo** [comment]
Spoke too soon. I just found another one and I think I found the issue. It seems the year in the metadata of Plex is different from the one Ombii is using in themoviedb. For example: https://www.themoviedb.org/movie/375366-the-girl-with-all-the-gifts. In Plex this movie is listed with 2017 but in ombi is 2016.

**Comment by tidusjar** [comment]
That would be a issue, the data we get from TheMovieDB we have to assume it's accurate.

There is not much I can do from an Ombi side of things here...

**Comment by cesalo** [comment]
How about have some flexibility? .. it seems generally is 1 year or so. Also there should be some sort of manual setting. If I mark it as available ombi should recognize it next time somebody ask the same movie.

**Comment by tidusjar** [comment]
The flexibility is difficult as it can introduce false positive matches which I try and avoid.
If there is a request for a movie already, the user should not be able to re-request it unless they cannot see other users requests. If they can see other requests then it should show as 'Requested'.

If you have marked the request as available, it should then show available.

**Comment by cesalo** [comment]
If I use admin to search the movie it lists the movie as if it wasn't in plex. If I use any other user (non admin) it will show it as available in Plex. That's why before, since I was using admin, thought it wasn't working.
Thanks for the assistance. This is a great app and it does a lot, thanks for your effort.

**Comment by tidusjar** [comment]
No problem!

**Comment by cesalo** [comment]
Going back to this issue .. Now I have a similar problem with the movie Split .. according with Plex is from 2017 .. IMDB is also listing the year as 2017 and even CouchPotato which uses IMDB i think (?). In TheMovieDB is listing this movie as a 2016 movie. The issue is that there is another movie Split from 2016 so is using the wrong movie. Due to this they can report issues for this movie as is listed as "Requested" but not available.
What about having the option to choose from different sources and choose the movie that is the match? Like the option "Fix incorrect Match" in Plex. In this case I could choose the correct movie "Split".
