### ISSUE TITLE
Prowl Notifications

### ISSUE THREAD

**Issue by hossame** [tidusjar/Ombi#975]
Please consider implementing Prowl notifications for Ombi.

Sonarr, Couchpotato, et al support this feature already.

https://www.prowlapp.com/api.php

At the most basic, request notifications for the administrator would be good.

More advanced options could be Prowl notifications for users when their request is approved / denied.

Users would need to provide their API keys in that case.

Thanks for your consideration!

**Comment by hossame** [comment]
Should I put this on feathub instead?

**Comment by SuperPotatoMen** [comment]
Yep

**Comment by hossame** [comment]
Done. Feel free to delete this issue.
