### ISSUE TITLE
Movies added through Radarr are moved and renamed twice

### ISSUE THREAD

**Issue by VanCityGuy** [tidusjar/Ombi#979]
#### Ombi Version:

V 2.0.1260

#### Update Branch:

Early Access Preview

#### Operating System:

Mac OSX 10.11.4

#### Mono Version (only if your not on windows)

4.6.2 

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

No Applicable Logs

```

#### Problem Description:

After using an old plex request channel and couchpotato for movies, today I updated to Radarr and Ombi. I tested Radarr first, downloaded a few movies, and it moved it from my completed folder out of Sabnzbd to my media drive, and renamed it as I specified in the settings. Then I added the latest version of Ombi to equation, and I am able to add request, have it add it to Radarr, download and complete. The issue now is that when the movie goes through Ombi, it seems to duplicate the move and rename process. It now comes with two copies of the movie, and the directory containing the file has (0) at the end. eg: Moonrise Kingdom (0), as opposed to the Radarr only version: Moonrise Kingdom (2012)

#### Reproduction Steps:
 Add a movie from Ombi with only Radarr configured in the settings

Ombi sends the request to Radarr

Radarr snags the request, downloads it, sends it to Sabnzbd, and moves the completed files to my media drive.

Ombi also seems to be doing the move and rename step.

I tried leaving the media directory in the Radarr settings with Ombi blank, but then it will not allow me to add a request.

**Comment by tidusjar** [comment]
Ombi will never move or rename your content.

**Comment by VanCityGuy** [comment]
Oh odd, it must me something in the way Radarr is interacting with Ombi, I will close this an open an issue with Radarr.

Thanks for the quick reply!
