### ISSUE TITLE
no PlexRequests.exe anymore?

### ISSUE THREAD

**Issue by mow4cash** [tidusjar/Ombi#981]
#### Ombi Version:

On 1.10.0 upgrading to
Ombi v2.0.1

#### Update Branch:

Stable

#### Operating System:
FreeBSD/FreeNas

#### Mono Version (only if your not on windows)

(1.9.4)

#### Problem Description:

The Wiki FAQ says to `screen mono /var/db/plex_requests/PlexRequests.exe` How do I run the new Ombi version if there is no PlexRequests.exe anymore? I am currently running version 1.10.0 and trying to upgrade.

**Comment by tidusjar** [comment]
Ombi.exe :)

**Comment by mow4cash** [comment]
I don't see Ombi.exe in root folder of the download zip? Where is the location of it? I'm probably missing something stupid.

**Comment by tidusjar** [comment]
Did you check the latest github release?

**Comment by mow4cash** [comment]
Haha. I knew I was doing something stupid. I was downloading the source code. I didn't know there was a difference. Thanks
