### ISSUE TITLE
Issue when trying to log in

### ISSUE THREAD

**Issue by ofurpesi** [tidusjar/Ombi#986]
#### Ombi Version:

V 2.0.1234

#### Update Branch:

Early Access Preview

#### Operating System:

Server 2012 R2

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

When I try to log in and press Sign in, it goes back to Username window. Password window never comes up.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
That was my fault sorry, JS functions got messed up. Try and get the latest EAP now!
