### ISSUE TITLE
Ombi Installation/documentation needs updating

### ISSUE THREAD

**Issue by ninja-squirrel** [tidusjar/Ombi#989]
#### Ombi Version:

V 2.0.1

#### Update Branch:

Stable

#### Operating System:

(Windows 7)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```



```

#### Problem Description:

Ombi Installation/documentation needs updating. Windows Installation instructions still refer to Plex Requests.net. Installation instructions given with the new version are not detailed. How is the application started? There is no .exe file. Please elaborate on instructions. Thanks in advance!

**Comment by FVGAZI** [comment]
Yeah, I was feeling like a dummy looking for the .exe file.
Can we get an update on this ASAP please?

**Comment by SuperPotatoMen** [comment]
I'm not sure what the problem is, the installation instruction are already up to date with the new situation?

**Comment by SuperPotatoMen** [comment]
the guide over here is up to date: http://www.htpcguides.com/install-plex-requests-net-windows-system-service/

**Comment by tidusjar** [comment]
I think he's referring to our docs on the wiki: https://github.com/tidusjar/Ombi/wiki/Installing-on-Mac-OS-X

**Comment by RXWatcher1** [comment]
It would be nice if there was some place with the info on how to download the Early Access Previews. For the life of me I can't find them anywhere. The Auto Update isnt working on my linux box so I can't use that.

**Comment by tidusjar** [comment]
@RXWatcher1 look at the readme and click the AppVeyor EAP Build icon :) 

Good idea though

**Comment by RXWatcher1** [comment]
Got it...thank you! I really was looking everywhere and almost opened a ticket but didnt want to bother people.

**Comment by ninja-squirrel** [comment]
I'm not sure how this is "up to date"? (Screenshot attached)

![plexrequests](https://cloud.githubusercontent.com/assets/25334047/22350400/a25cbe58-e3e1-11e6-9865-21267a66b513.PNG)


Also, the other link from the wiki that was provided was for Mac OS X installation, but the link for the Windows installation goes to this same page in my screenshot.

**Comment by SuperPotatoMen** [comment]
First of all, we are not htpc guides. Second.
It is up to date...
![image](https://cloud.githubusercontent.com/assets/2944704/22350470/2dbbc1ec-e414-11e6-8cf5-f0a6492d8dc6.png)

**Comment by ninja-squirrel** [comment]
Not sure how you are seeing that. http://www.htpcguides.com/install-plex-requests-net-windows-system-service/

![plexrequests](https://cloud.githubusercontent.com/assets/25334047/22353056/b10be158-e3ec-11e6-91b6-0f5671f36449.PNG)

**Comment by ninja-squirrel** [comment]
The zip file has obviously been updated since I posted this, but nonetheless I installed it successfully substituting Ombi for Plexrequests.net in the installation instructions.
