### ISSUE TITLE
[Question/Bug] Information being sent to the Radarr API from Ombi

### ISSUE THREAD

**Issue by fedoranimus** [tidusjar/Ombi#990]
#### Ombi Version:

V 2.0.1275

#### Update Branch:

development

#### Operating System:

Windows 10

#### Problem Description:

What information is Ombi sending to Radarr to request a movie? It appears that it's only sending the tmbdId & the title. Could it also send the year?

#### Reproduction Steps:

Request a movie for Radarr.

**Comment by TheDogg** [comment]
I noticed that the folders create for the movie is: Movie Name (0)

usually the year should be in the parenthesis

**Comment by fedoranimus** [comment]
Yes, that's why I'm asking. We're not getting year information from Ombi that we expect.

**Comment by SuperPotatoMen** [comment]
Question redirected to @tidusjar

**Comment by tidusjar** [comment]
@fedoranimus That's fine!

I'll send that across too, I was expecting Radarr to lookup that sort of information from the IMDB id.

But I can easily send it across.

**Comment by fedoranimus** [comment]
Thanks, I'll test it out once available.

**Comment by SuperPotatoMen** [comment]
issue linked to external problem by radarr: https://github.com/Radarr/Radarr/issues/402

**Comment by tidusjar** [comment]
In EAP now.
