### ISSUE TITLE
Cant get Quality Profiles on Sonarr

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#991]
#### Ombi Version:

V 2.0.1277

#### Update Branch:

Early Access Preview

#### Operating System:

Windows 8/Windows Server 2012

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
{"result":false,"message":"You must specify a Quality Profile."}
```

#### Problem Description:

After updating to EAP, Sonarr "lost" the Quality Profile and when clicking the button "Get Quality Profiles" the error comes.

#### Reproduction Steps:

Click Get Quality Profiles under Sonarr

**Comment by tidusjar** [comment]
Thanks,
It must have been from where I added the new Root path stuff.

I'll get this fixed.

**Comment by sluquet** [comment]
I am still getting this error. Tried all three release branches without any luck. Win 10.

**Comment by Extcee** [comment]
I am getting this also. I've tried every branch and I'm using the Sonarr master branch.

**Comment by tidusjar** [comment]
Can you please raise a new issue
