### ISSUE TITLE
TV shows requested are not showing up

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/Ombi#995]
#### Ombi Version:

V 2.0.1282/2.0.1284

#### Update Branch:

Development

#### Operating System:

Windows 10 Home x64

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Previously requested TV shows are not showing up under requests. I've also tried requesting a series on v2.0.1282 and there's still nothing showing up. I've listed both 1282 and 1284 versions because I've tried with both but currently I'm on 1282. Th movie requests are working normally. 

#### Reproduction Steps:

Navigate to TV show requests are requesting a series.

**Comment by tidusjar** [comment]
So you are requesting something and it's not appearing? Have you checked
your filters?

**Comment by chrisausbun** [comment]
Shows that have already been requested and shows that I'm trying to request now are not showing up. The requests for TV shows is blank. All filters are set to show all and have not been changed. The only thing that has changed is the Dev version I upgraded to. Here's a screenshot:

![blank requests](https://cloud.githubusercontent.com/assets/22944072/22305168/5c89ee98-e2ef-11e6-816f-f848f994ace3.png)

**Comment by chrisausbun** [comment]
If any logs would help, please let me know what log level I should change it to and what I need to send you. I've never really know what I'm doing when I'm sending logs so any help would be greatly appreciated. Thanks for looking into this.

**Comment by tidusjar** [comment]
Can you open up the browser developer tool and refresh the page and see if
there are any errors in the console?

**Comment by chrisausbun** [comment]
Thanks @tidusjar, it looks to be resolved with the latest Dev build.

**Comment by epitsi** [comment]
FWIW: I ran into this issue with stable version 2.1.1336. I created a new docker container using the dev build, and the issue is gone on 2.1.1565. Unfortunately I didn't try creating the container first on the stable version, so I don't know if simply that would have helped.
