### ISSUE TITLE
Can I install this on a Mac?

### ISSUE THREAD

**Issue by jpborjas** [tidusjar/Ombi#999]
#### Ombi Version:

V 1.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Operating System:

OS X Sierra

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I run a Mac shot, all Macs in my house. Can I install this on a Mac?

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by VanCityGuy** [comment]
[Yes you can](https://github.com/tidusjar/Ombi/wiki/Installing-on-Mac-OS-X)

**Comment by jpborjas** [comment]
Thanks for your reply. I Cloned and Downloaded the latest release, install mono on my Mac, and it mentions PlexRequest and a .exe file. Is this for a legacy name or product? I don't see any .exe files anywhere. Please advise.

**Comment by tidusjar** [comment]
You need to download a release and not clone the repo. Take a look at the
github releases for this project. It was called PlexRequests before but
Plex made me change the name so it's Ombi now. I need to update the
documentation
